### ISSUE TITLE
DeDRM couldn't remove DRM

### ISSUE THREAD

**Issue by gregorymilani** [apprenticeharper/DeDRM_tools#1001]
Hello, attached below is the log. I tried two books, one attained through Libby, and one obtained through Kindle Unlimited. Neither worked. Any help would be great, thanks!

**Comment by gregorymilani** [comment]
calibre Debug log
calibre 4.9.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 29, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 29, 0) && KFX metadata reader (from KFX Input) (1, 29, 0) && KFX Input (1, 29, 0)
calibre 4.9.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 29, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 29, 0) && KFX metadata reader (from KFX Input) (1, 29, 0) && KFX Input (1, 29, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[1.45] main UI initialized...
[1.45] Hiding splash screen
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G0016T0294520AU5&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=5)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g0016t0294520au5&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (1L, 1L)}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 14, count of files in metadata: 14, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 14
DeviceJob: set_books_in_library finished: time= 0.00300002098083
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[14.08] splash screen hidden
[14.08] Started up in 14.08 seconds with 8 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [')\xd1\x7f\x02\xc5\x1a$\x88b\xb6\xfe\x19\xbam\xa7\xd0,\x85\xe7\xed\x84\x95\xde\xad\xa7\xd8\xb3Wz\xdb\xff\x9e', 'E:\\documents\\Downloads\\Items01\\Harry Potter and the Deathly Hallows_B0192CTMWS.kfx']
Gather KFX-ZIP (from KFX Input) 1.29.0: Importing E:\documents\Downloads\Items01\Harry Potter and the Deathly Hallows_B0192CTMWS.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\grego\AppData\Local\Temp\calibre_6btgma\_v4xqn.kfx-zip
DeDRM v6.6.3: Trying to decrypt _v4xqn.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: _v4xqn
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\grego\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.29.0: Packaging C:\Users\grego\AppData\Local\Temp\calibre_6btgma\_v4xqn.kfx-zip
Processing container: CR!424KF4XTGX3C37KDED49Z5TYQA5P.kfx
Processing container: Harry Potter and the Deathly Hallows_B0192CTMWS.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container Harry Potter and the Deathly Hallows_B0192CTMWS.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\grego\AppData\Local\Temp\calibre_6btgma\7agllp_add_books\0\Harry Potter and the Deathly Hallows_B0192CTMWS.kfx-zip
Added Harry Potter and the Deathly Hallows to db in: 0.2
Added 1 books in 1.1 seconds
calibre 4.9.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 29, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 29, 0) && KFX metadata reader (from KFX Input) (1, 29, 0) && KFX Input (1, 29, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\view.py", line 246, in view_triggered
  File "site-packages\calibre\gui2\actions\view.py", line 329, in _view_books
  File "site-packages\calibre\gui2\actions\view.py", line 281, in _view_calibre_books
  File "site-packages\calibre\gui2\actions\view.py", line 108, in view_format_by_id
  File "site-packages\calibre\gui2\actions\view.py", line 157, in _view_file
  File "site-packages\calibre\gui2\actions\view.py", line 147, in _launch_viewer
  File "site-packages\calibre\gui2\__init__.py", line 1275, in open_local_file
WindowsError: [Error 1155] No application is associated with the specified file for this operation: u'C:\\Users\\grego\\Calibre Library\\J.K. Rowling\\Harry Potter and the Deathly Hallows (32)\\Harry Potter and the Deathly Ha - J.K. Rowling.kfx-zip'

Worker Launch took: 0.121999979019
Job: 3 Convert book 1 of 1 (Harry Potter and the Deathly Hallows) finished
Convert book 1 of 1 (Harry Potter and the Deathly Hallows)
	Conversion options changed from defaults:
	  output_profile: u'kindle_pw3'
	  read_metadata_from_opf: u'C:\\Users\\grego\\AppData\\Local\\Temp\\calibre_6btgma\\3rxpvb.opf'
	  cover: u'C:\\Users\\grego\\AppData\\Local\\Temp\\calibre_6btgma\\t0vjte.jpeg'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.9.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\grego\\AppData\\Local\\Temp\\calibre_6btgma\\t0vjte.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001D3CE588B88>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000001D3CE6B2408>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\grego\\AppData\\Local\\Temp\\calibre_6btgma\\3rxpvb.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\grego\AppData\Local\Temp\calibre_6btgma\ng7l7v.kfx-zip
	Software versions: KFX Input 1.29.0, calibre 4.9.1 [64bit], Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\grego\AppData\Local\Temp\calibre_6btgma\ng7l7v.kfx-zip
	Processing container: CR!424KF4XTGX3C37KDED49Z5TYQA5P.kfx
	Processing container: Harry Potter and the Deathly Hallows_B0192CTMWS.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container Harry Potter and the Deathly Hallows_B0192CTMWS.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
These tools are intended for books you own.
