### ISSUE TITLE
DeDRM 6.6.3. failed to decrypt AdobeDigital Editions 4.5 epub

### ISSUE THREAD

**Issue by mannix34** [apprenticeharper/DeDRM_tools#1003]
calibre Debug log
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.48] splash screen shown
[0.48] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[2.66] main UI initialized...
[2.66] Hiding splash screen
[22.34] splash screen hidden
[22.34] Started up in 22.34 seconds with 61 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x1aa>n\xbb\x0evDX\x17\xea\x81l!\xb7\xd2\xa6\xd0i\x0eJ\xcc\xd8\x88`G\xd6\xd3)\xaayn', 'C:\\Users\\manni\\Ultimate\\Die Angst des Tormanns beim Elfmeter - Erz\xc3\xa4hlung.pdf']
DeDRM v6.6.3: Trying to decrypt Die Angst des Tormanns beim Elfmeter - ErzÃ¤hlung.pdf
DeDRM v6.6.3: Die Angst des Tormanns beim Elfmeter - ErzÃ¤hlung.pdf is a PDF ebook
DeDRM v6.6.3: Trying Encryption key default_key
DeDRM v6.6.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 427, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1475, in initialize
PDFEncryptionError: Document is not encrypted.
DeDRM v6.6.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 506, in PDFDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Die Angst des Tormanns beim Elfmeter - Erzählung_nodrm to db in: 1.3
Added 1 books in 2.5 seconds
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\delete.py", line 404, in delete_books
  File "site-packages\calibre\gui2\actions\delete.py", line 378, in do_library_delete
  File "site-packages\calibre\gui2\library\models.py", line 416, in delete_books_by_id
  File "site-packages\calibre\db\cache.py", line 62, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1654, in remove_books
  File "site-packages\calibre\db\tables.py", line 559, in remove_books
  File "site-packages\calibre\db\tables.py", line 415, in remove_books
  File "site-packages\calibre\db\backend.py", line 886, in executemany
  File "c:\t\t\apsw-r08j4l0g\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

Traceback (most recent call last):
Traceback (most recent call last):
  File "site-packages\calibre\utils\recycle_bin.py", line 45, in recycler_main
  File "site-packages\calibre\utils\recycle_bin.py", line 144, in delete_tree
  File "site-packages\calibre\utils\recycle_bin.py", line 31, in recycle_path
  File "site-packages\calibre\utils\recycle_bin.py", line 85, in recycle
  File "site-packages\calibre\utils\recycle_bin.py", line 70, in delegate_recycle
RuntimeError: recycler failed to recycle: u'Y:\\ deleted vcvfe8\\Die Angst des Tormanns beim Elfmete (141)'
OSError: Failed to perform delete operation
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd1\x1eI3\x03\xfb\xeb\xc2Fs4!\x9bqYD|R\x1dx]\x91\xa3@7 \xfe\xadl\xd5\x82\x1c', 'C:\\Users\\manni\\Ultimate\\Die Angst des Tormanns beim Elfmeter - Erz\xc3\xa4hlung_nodrm.txt']
Added 0 books in 1.1 seconds
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "site-packages\calibre\db\backup.py", line 53, in run
  File "site-packages\calibre\db\backup.py", line 115, in do_one
  File "site-packages\calibre\db\cache.py", line 62, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1177, in clear_dirtied
  File "site-packages\calibre\db\backend.py", line 874, in execute
  File "c:\t\t\apsw-r08j4l0g\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1\x8c;rw\xbd\x11\xc0\x8a(\xcf\xd64\xec\xa1\xda~\xb4\xf3Z8V\xc8b\x8c\x92\x86\x0f\x0f%-\xb7', 'C:\\Users\\manni\\Downloads\\DeDRM_tools_6.6.3\\DeDRM_calibre_plugin\\DeDRM_plugin.zip']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xbf`<v%\xed\xdc(\x9e\xcc\xaf\x1f\x90\xd6E\x1e\x15mc\x11a \x1biX\xeaI\x1a1\x8a\x08\xdb', 'C:\\Users\\manni\\Documents\\My Digital Editions\\MARCO POLO Reisef\xc3\xbchrer Griechische Inseln, \xc3\x84gais.epub']
DeDRM v6.6.3: Trying to decrypt MARCO POLO ReisefÃ¼hrer Griechische Inseln, Ã„gais.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: MARCO POLO ReisefÃ¼hrer Griechische Inseln, Ã„gais.epub is a secure Adobe Adept ePub
DeDRM v6.6.3: Trying Encryption key default_key
DeDRM v6.6.3: Decrypted with key default_key after 2.1 seconds
DeDRM v6.6.3: Finished after 2.1 seconds
Added 0 books in 5.5 seconds
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 1064, in closeEvent
  File "site-packages\calibre\gui2\ui.py", line 921, in write_settings
  File "site-packages\calibre\gui2\init.py", line 781, in save_layout_state
  File "site-packages\calibre\gui2\library\views.py", line 636, in save_state
  File "site-packages\calibre\gui2\library\views.py", line 630, in write_state
  File "site-packages\calibre\db\cache.py", line 62, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 616, in set_pref
  File "site-packages\calibre\db\backend.py", line 134, in set
  File "site-packages\calibre\db\backend.py", line 121, in __setitem__
  File "site-packages\calibre\db\backend.py", line 865, in conn
  File "site-packages\calibre\db\backend.py", line 291, in __init__
CantOpenError: CantOpenError: unable to open database file

**Comment by ElleKayEm** [comment]
Not sure what is going on here.  I see a PDF which the log says is not encrypted.  Then an EPUB which is successfully decrypted, but it looks like calibre is unable to save it to the calibre library.

**Comment by mannix34** [comment]
Thanks, the calibre library is my server, no problem to save or read files.

ElleKayEm <notifications@github.com> schrieb am Sa., 15. Feb. 2020, 21:14:

**Comment by ElleKayEm** [comment]
If you disable the DeDRM plugin, are you able to add books to calibre?

**Comment by mannix34** [comment]
Yes, with no decryption

ElleKayEm <notifications@github.com> schrieb am Sa., 15. Feb. 2020, 21:46:

**Comment by ElleKayEm** [comment]
I don't know why the book is successfully decrypted, but then not added to calibre.  Usually a book will still be added even when DRM removal doesn't work.

Have you tried a fresh install of calibre?

I am not having trouble myself with Adobe DRM books with Windows 10, Adobe 2.0.1, and calibre 4.10.

**Comment by mannix34** [comment]
Yes, same problem with calibre 4.1., did not try with
Adobe digital 2.0.1 for windows 10, where can I download this ver in
Europe?

ElleKayEm <notifications@github.com> schrieb am Sa., 15. Feb. 2020, 22:43:

**Comment by ElleKayEm** [comment]
Adobe 2.0.1 is available here:

www.adobe.com/support/digitaleditions/downloads.html

Although decryption doesn't seem to be the problem.  The issue seems to be between DeDRM passing the book to calibre after decryption.

Is it just Adobe DRM books that are the problem?  Just this particular book?

**Comment by mannix34** [comment]
Thanks for your support.

Am Sa., 15. Feb. 2020 um 23:23 Uhr schrieb ElleKayEm <
notifications@github.com>:

> Adobe 2.0.1 is available here:
>
I tried this version and get error message "check activation", unless ADE
confirms, that my PC is licensed

> www.adobe.com/support/digitaleditions/downloads.html
>
> Although decryption doesn't seem to be the problem. The issue seems to be
> between DeDRM passing the book to calibre after decryption.
>
> Is it just Adobe DRM books that are the problem? Just this particular book?
>
Every book von onleihe.de

**Comment by ElleKayEm** [comment]
You could try to de-authorize and then re-authorize ADE with your Adobe ID following the instructions here (scroll down for Windows):

https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

I would wonder if they were using the hardened Adobe DRM that can't be decrypted, but the log says it is decrypted.  But I don't know what happens to that file if it doesn't get saved to calibre.

**Comment by mannix34** [comment]
I de-autorized and tried another e-book of onleihe.com, onleihe is in the
process of changing DRM, it's called "CARE", a european readium LCP
solution, partner is a french company, "TEA - The Ebook Alternative" see
log:


calibre, version 4.10.0
ERROR: Errors while adding: Failed to add any books, click "Show details"
for more information


----------------------------------------------------------------------
Failed to add the book: Helmut Schmidt
C:\Users\manni\Documents\My Digital Editions\Helmut Schmidt.epub
With error:
Traceback (most recent call last):
  File "site-packages\calibre\gui2\add.py", line 414, in add_book
  File "site-packages\calibre\db\legacy.py", line 225, in create_book_entry
  File "site-packages\calibre\db\cache.py", line 62, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1590, in create_book_entry
  File "site-packages\calibre\db\cache.py", line 1310, in set_metadata
  File "site-packages\calibre\db\cache.py", line 1136, in update_path
  File "site-packages\calibre\db\backend.py", line 1606, in update_path
  File "site-packages\calibre\db\tables.py", line 137, in set_path
  File "site-packages\calibre\db\backend.py", line 874, in execute
  File "c:\t\t\apsw-k8s6ukkv\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

Am So., 16. Feb. 2020 um 12:49 Uhr schrieb ElleKayEm <
notifications@github.com>:

**Comment by ElleKayEm** [comment]
Ok, I see these are library loans.  The tools here are intended for purchased books.

**Comment by mannix34** [comment]
Anyway, thanks for your support.

ElleKayEm <notifications@github.com> schrieb am So., 16. Feb. 2020, 13:49:
