### ISSUE TITLE
Missing a module and can't get DRM removal tools to work

### ISSUE THREAD

**Issue by kelseyhusky** [apprenticeharper/DeDRM_tools#1005]
There is 1 ebook to be decrypted.
Processing file: B07R69PSND_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -s 'B0540907450503H9' '/Users/kelsey/Desktop/B07R69PSND_EBOK.azw' '/Users/kelsey/Desktop/' > '/Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.6
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/kelsey/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'cdfe90683c62' and UserName 'kelsey'
Saved a key to /Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/KindleKey 4.der' '/Users/kelsey/Desktop/B07R69PSND_EBOK.azw' '/Users/kelsey/Desktop/' > '/Users/kelsey/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/dv/kzs65vdd79j2g2tw5kqt9f9r0000gn/T/AppTranslocation/D0FFEF9B-B5D2-476D-8FE2-E7DD6E456217/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
B07R69PSND_EBOK.azw couldn't be decrypted.

I am using Kindle for mac 1.17.0 on MacOS 10.12.6

**Comment by ElleKayEm** [comment]
See the FAQs here:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-application-opens-but-always-gives-an-error-in-the-log-importerror-no-module-named-cryptocipher

**Comment by apprenticeharper** [comment]
Now fixed in 6.7.0. Please report back if it isn't.
