### ISSUE TITLE
DeDRM not working for Kindle Book 

### ISSUE THREAD

**Issue by Jonesmitty** [apprenticeharper/DeDRM_tools#1012]
calibre Debug log
calibre 4.10.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.10.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[3.19] main UI initialized...
[3.19] Hiding splash screen
[5.84] splash screen hidden
[5.84] Started up in 5.84 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa6(\x97\xb4WhL0y\xe0\xe3\x0e=\xbe\x04_\xb4\xd5\x03H\x16\xc3\xf8z={\xb9\xe7{\xa1y\x11', "C:\\Users\\lehre\\OneDrive\\SCHOOL\\NATIONAL UNIVERSITY\\LAW240\\Anderson's Business Law and the Legal Environment, Comprehensive Volume.azw4"]
DeDRM v6.7.0: Trying to decrypt Anderson's Business Law and the Legal Environment, Comprehensive Volume.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Anderson's Business Law and the Legal Environment, Comprehensive Volume
Found 2 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\lehre\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\lehre\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2665407038' and UserName '6c65687265'
DeDRM v6.7.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Anderson's Business Law and the Legal Environment, Comprehensive Volume
Got DSN key from database default_key_1
Found 3 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Anderson's Business Law and the Legal Environment, Comprehensive Volume to db in: 0.5
Added 1 books in 9.6 seconds

**Comment by ElleKayEm** [comment]
If this is from the website for "download & transfer via USB", then you need to choose an E-ink Kindle (not a Fire) for the device and enter its serial number into the DeDRM plugin customization.
