### ISSUE TITLE
DeDRM not working for Kindle Book

### ISSUE THREAD

**Issue by rspadinger** [apprenticeharper/DeDRM_tools#1015]
This item is NOT from the website for "download & transfer via USB"

calibre Debug log :+1: 
calibre 4.11.1 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.11.1 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[1.69] main UI initialized...
[1.69] Hiding splash screen
[286.12] splash screen hidden
[286.12] Started up in 286.12 seconds with 52 books
DeDRM v6.7.0: Trying to decrypt B07R6W4L7Y_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mastering Ethereum: Implement advanced blockchain applications using Ethereum-supported tools, services, and protocols
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Robert\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Robert\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4037482704' and UserName '526f62657274'
DeDRM v6.7.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mastering Ethereum: Implement advanced blockchain applications using Ethereum-supported tools, services, and protocols
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Mastering Ethereum: Implement advanced blockchain applications using Ethereum-supported tools, services, and protocols to db in: 0.1
Added 1 books in 0.6 seconds

[B07R6W4L7Y_EBOK.zip](https://github.com/apprenticeharper/DeDRM_tools/files/4238974/B07R6W4L7Y_EBOK.zip)

**Comment by ElleKayEm** [comment]
Was this book downloaded with the current installation of Kindle for PC on the same machine and user as calibre with DeDRM?
