### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by gemstern** [apprenticeharper/DeDRM_tools#1017]
I'm on Mac OS Catalina 10.15.3. Calibre 4.11.1, Kindle paperwhite 5.8.11. 

Tried to understand the FAQ, but couldn't follow. Book from Amazon downloaded to Mac, then imported into Calibre. Also downloaded newest version for DeDRM plugin.

Book was downloaded to Kindle directly before, also did not work.

calibre Fehlerdiagnoseprotokoll
calibre 4.11.1  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: de
Initialized urlfixer
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Wikidata (1, 3, 0) && Obok DeDRM (6, 5, 4)
calibre 4.11.1  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Wikidata (1, 3, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 108.50000163
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.04] main UI initialized...
[1.04] Hiding splash screen
Initialized urlfixer
DeDRM v6.7.0: Trying to decrypt Knife Children (The Sharing Knife series) - Lois McMaster Bujold.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Knife Children (The Sharing Knife series)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[7.51] splash screen hidden
[7.52] Started up in 7.52 seconds with 662 books
Added Knife Children (The Sharing Knife series) to db in: 0.0
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
Choose your Paperwhite with the "download & transfer via USB" option on the website.  Enter the Paperwhite's serial number into the DeDRM plugin customization.
