### ISSUE TITLE
DeDRM not working with Kindle for Mac

### ISSUE THREAD

**Issue by MiMoHo** [apprenticeharper/DeDRM_tools#1021]
Cannot convert rental ebook with Kindle for Mac 1.23.1, Calibre 4.11.0, DeDRM 6.7.0 on OS X 10.14.6 due to DRM restrictions.
[Debug log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4271720/Debug.log.txt)

Error:

```
Buch 1 von 1 (_name of book_) konvertieren
Conversion options changed from defaults:
  read_metadata_from_opf: u'/var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/8coPfX.opf'
  verbose: 2
  output_profile: u'kindle'
  cover: u'/var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/66kByC.jpeg'
Resolved conversion options
calibre version: 4.11.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/66kByC.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x113d5ecd0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x113d6b3d0>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/8coPfX.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on /var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/chMgJp.kfx-zip
Software versions: KFX Input 1.30.0, calibre 4.11, Darwin-18.7.0-x86_64-i386-64bit
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting /var/folders/x1/wk7dpyhn6pb59kfpx6q5m89h0000gn/C/calibre_4.11.0_tmp_wdS8ic/chMgJp.kfx-zip
Processing container: B0849LZ2JH_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B0849LZ2JH_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly: This book has DRM!
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!
```

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.
