### ISSUE TITLE
Plug in seens not working

### ISSUE THREAD

**Issue by anderpioner** [apprenticeharper/DeDRM_tools#1024]
Here is the log file:

calibre Log de Debug
calibre 4.12  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.12  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[2.27] main UI initialized...
[2.27] Hiding splash screen
[6.77] splash screen hidden
[6.77] Started up in 6.77 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfa_\xec\x1d\xe8k\x06\n\xa6\x18-\x8e\xf7\x84\xbbm\x80\n\x94\x8c\xfe\x0bi\x03\xd2~\xc2\xc6H\x1f\x12H', 'C:\\Users\\Anderson\\Documents\\My Kindle Content\\B07Z81R6WL_EBOK\\B07Z81R6WL_EBOK.azw', 'C:\\Users\\Anderson\\Documents\\My Kindle Content\\B07Z81R6WL_EBOK\\CR!3ZW59VMC0S2J30451MYC5ZGFSY4C.azw.md']
DeDRM v6.7.0: Trying to decrypt B07Z81R6WL_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.7.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Anderson\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Anderson\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2294122702' and UserName '416e646572736f6e'
DeDRM v6.7.0: Found 1 new key
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 321, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B07Z81R6WL EBOK to db in: 0.1
Added CR!3ZW59VMC0S2J30451MYC5ZGFSY4C.azw to db in: 0.1
Added 2 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.24 or earlier.  Also add the KFX Input plugin or turn off KFX format downloads from K4PC.  See this post at MobileRead:

https://www.mobileread.com/forums/showthread.php?t=283371
