### ISSUE TITLE
TOPAZ - Calibre version 4.12.0 - DeDRM_tools_6.7.0.zip > DeDRM_Plugin.zip

### ISSUE THREAD

**Issue by wilnav** [apprenticeharper/DeDRM_tools#1028]
Good day,

My guess is that TOPAZ or TPZ no longer uses HTMLZ. 
The system setup and simple error log follows. 
_________
Calibre version 4.12.0

DeDRM_tools_6.7.0.zip > DeDRM_Plugin.zip

 GNOME Ver. 3.30.2 
					7.7 GiB
					Intel Core i5-6200U CPU @ 2.40 GHz x 4
					PURE OS: 64 bit
					Disk  241.0 GB
					Amazon Kindle 
					
	Installation
------------
Open calibre's Preferences dialog.  Click on the "Plugins" button.  Next, click on the button, "Load plugin from file".  Navigate to the unzipped DeDRM_tools folder, find the file "DeDRM_plugin.zip".  Click to select the file and select "Open".  Click "Yes" in the "Are you sure?" dialog box. Click the "OK" button in the "Success" dialog box.

					
					
	calibre, version 4.12.0
ERROR: Loading book failed: Failed to open the book at /media/genie/030DFDB400289EF8/Calibre Library/Geshe Jampa Tegchok/Transforming Adversity Into Joy And Courage_ An Explanation Of The Thirty-Seven Practices Of Bo (775)/Transforming Adversity Into Joy And Courag - Geshe Jampa Tegchok.tpz. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 426, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: /media/genie/030DFDB400289EF8/Calibre Library/Geshe Jampa Tegchok/Transforming Adversity Into Joy And Courage_ An Explanation Of The Thirty-Seven Practices Of Bo (775)/Transforming Adversity Into Joy And Courag - Geshe Jampa Tegchok.tpz with error:
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 851, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 844, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 819, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 54, in extract_book
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 755, in __init__
ValueError: No plugin to handle input format: tpz

[tmpQHvXXf.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4357097/tmpQHvXXf.txt)

**Comment by wilnav** [comment]
Sorry forgot amazon file. Put into .zip file so Github would take it.
[amazon tpz.zip](https://github.com/apprenticeharper/DeDRM_tools/files/4357134/amazon.tpz.zip)

**Comment by ElleKayEm** [comment]
Is the book directly from an E-ink Kindle device?  And do you have the Kindle's serial number entered into the DeDRM plugin customization?

**Comment by wilnav** [comment]
It is a paperwhite, Kindle voyage. The SN = BO1309075203003W

Thank you for looking into this.

william

**Comment by ElleKayEm** [comment]
Try changing that 2nd character from an O to a zero.

**Comment by wilnav** [comment]
Works. Thank you for the solution. I will keep in mind in the future. My face is red. 
Again Thank you
