### ISSUE TITLE
unable to DeDRM ADE2.0

### ISSUE THREAD

**Issue by Karen-cat** [apprenticeharper/DeDRM_tools#1030]
Windows 10, Calibre 4.12, DeDRM tools 6.7.0
book purchased from Google books, downloaded into ADE 2.0 and can open it there but when I attempt to import into Calibre it won't remove the DRM. Have tried several different books multiple times to make sure it's reproducible.   Thank you.

calibre Debug log
calibre 4.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Goodreads (1, 4, 0) && KoboTouchExtended (3, 1, 5) && Count Pages (1, 9, 0) && Find Duplicates (1, 6, 3) && KePub Output (3, 1, 3) && EpubCheck (0, 2, 2) && Diaps Editing Toolbag (0, 3, 6) && Obok DeDRM (6, 7, 0) && Kobo Utilities (2, 11, 0)
calibre 4.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Goodreads (1, 4, 0) && KoboTouchExtended (3, 1, 5) && Count Pages (1, 9, 0) && Find Duplicates (1, 6, 3) && KePub Output (3, 1, 3) && EpubCheck (0, 2, 2) && Diaps Editing Toolbag (0, 3, 6) && Obok DeDRM (6, 7, 0) && Kobo Utilities (2, 11, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 79.2832369942
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.55] db initialized
[0.55] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    1.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[2.38] main UI initialized...
[2.38] Hiding splash screen
[13.97] splash screen hidden
[13.97] Started up in 13.97 seconds with 1156 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['-v\xf4\x96\xce/1\x0f\xe5~\x1eq?\xea\xde\x05\x8d\xf2\x8c\xd8G\xd1\xe4\xe7\x8aCu\x10\xce>p\xdc', 'C:\\Users\\catsk\\Documents\\My Digital Editions\\Catholicism And American Freedom.epub']
DeDRM v6.7.0: Trying to decrypt Catholicism And American Freedom.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Catholicism And American Freedom.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Catholicism And American Freedom to db in: 0.2
Added 1 books in 0.8 seconds
Worker Launch took: 0.105999946594
Job: 0 Convert book 1 of 1 (Catholicism And American Freedom) finished
Convert book 1 of 1 (Catholicism And American Freedom)
	Conversion options changed from defaults:
	  output_profile: u'tablet'
	  read_metadata_from_opf: u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_xmnkzt\\3k0q80.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.12.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000021A35053948>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'kepub_clean_markup': True,
	 'kepub_disable_hyphenation': False,
	 'kepub_hyphenate': True,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x0000021A35038DC8>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_xmnkzt\\3k0q80.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\catsk\AppData\Local\Temp\calibre_xmnkzt\o_r57h.epub
	Python function terminated unexpectedly
	  o_r57h.epub (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: o_r57h.epub

**Comment by ElleKayEm** [comment]
Try de-authorizing and re-authorizing ADE with you Adobe ID.  Then add your book to calibre again.  Scroll down for Windows instructions here:

https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

**Comment by Karen-cat** [comment]
Thank you for the quick response.  I just tried it and it's still doing the same thing.  New log:
calibre Debug log
calibre 4.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && KePub Output (3, 1, 3) && Kobo Utilities (2, 11, 0) && Count Pages (1, 9, 0) && KoboTouchExtended (3, 1, 5) && Find Duplicates (1, 6, 3) && Diaps Editing Toolbag (0, 3, 6) && EpubCheck (0, 2, 2) && Obok DeDRM (6, 7, 0) && Goodreads (1, 4, 0)
calibre 4.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && KePub Output (3, 1, 3) && Kobo Utilities (2, 11, 0) && Count Pages (1, 9, 0) && KoboTouchExtended (3, 1, 5) && Find Duplicates (1, 6, 3) && Diaps Editing Toolbag (0, 3, 6) && EpubCheck (0, 2, 2) && Obok DeDRM (6, 7, 0) && Goodreads (1, 4, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 79.2832369942
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    1.5 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.5 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[2.12] main UI initialized...
[2.12] Hiding splash screen
[5.09] splash screen hidden
[5.09] Started up in 5.09 seconds with 1157 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xde\x14\x93\x82_\xf5\x9f\xd6\x8ak7\xea,\\{&\x1f\xe5\xcb\xb43\x0f\xaa\xca\x18\xb1\xef\x8b\x1c\x1eIQ', 'C:\\Users\\catsk\\Documents\\My Digital Editions\\Catholicism And American Freedom.epub']
DeDRM v6.7.0: Trying to decrypt Catholicism And American Freedom.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Catholicism And American Freedom.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 0 books in 0.6 seconds
Worker Launch took: 0.101999998093
Job: 0 Convert book 1 of 1 (Catholicism And American Freedom) finished
Convert book 1 of 1 (Catholicism And American Freedom)
	Conversion options changed from defaults:
	  output_profile: u'tablet'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_pphvct\\axcggk.opf'
	Resolved conversion options
	calibre version: 4.12.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002F18A1EFF88>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'kepub_clean_markup': True,
	 'kepub_disable_hyphenation': False,
	 'kepub_hyphenate': True,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x000002F18A1D7408>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_pphvct\\axcggk.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\catsk\AppData\Local\Temp\calibre_pphvct\mtj75o.epub
	Python function terminated unexpectedly
	  mtj75o.epub (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: mtj75o.epub

Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000001D31B6DC048>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000001D31B245C48>> ignored
Completed duplicate analysis in: 0.0880000591278
Found 0 duplicate groups covering 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x91\x07\x0f\xa90\xa0\xb0U\xaf\xbc\xc7\x02\xa8\xf1 $\xcf\x91\xd6R\x17\x1daQ\xbe\xa6\xd6\x91gz\xfe\xc9', 'C:\\Users\\catsk\\Documents\\My Digital Editions\\Catholicism And American Freedom.epub']
DeDRM v6.7.0: Trying to decrypt Catholicism And American Freedom.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Catholicism And American Freedom.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Catholicism And American Freedom to db in: 0.2
Added 1 books in 0.7 seconds
Worker Launch took: 0.102999925613
Job: 1 Convert book 1 of 1 (Catholicism And American Freedom) finished
Convert book 1 of 1 (Catholicism And American Freedom)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_pphvct\\f141y3.opf'
	  verbose: 2
	  output_profile: u'tablet'
	Resolved conversion options
	calibre version: 4.12.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000277540D2A88>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'kepub_clean_markup': True,
	 'kepub_disable_hyphenation': False,
	 'kepub_hyphenate': True,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x00000277540D6F08>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\catsk\\AppData\\Local\\Temp\\calibre_pphvct\\f141y3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\catsk\AppData\Local\Temp\calibre_pphvct\veetx5.epub
	Python function terminated unexpectedly
	  veetx5.epub (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: veetx5.epub

**Comment by ElleKayEm** [comment]
ADE was authorized with your Adobe ID when you opened the .acsm file and downloaded the epub?  And ADE is installed on the same machine and user as calibre with DeDRM?

**Comment by Karen-cat** [comment]
Yes to both questions. Thanks

**Comment by ElleKayEm** [comment]
Not sure what else to suggest.  Usually deleting that Adept key from the Windows registry and then re-authorizing ADE straightens out problems with Adobe DRM removal.
