### ISSUE TITLE
Unable to DeDRM azw3 file

### ISSUE THREAD

**Issue by eugenetan** [apprenticeharper/DeDRM_tools#1031]
This a AZW3 ebook purchased from Amazon. eInk Kindle Voyager serial number has been add.

Installed DeDRM v6.7.0. Same issue with a AZW ebook as well.

Both ebooks downloaded from Amazon with the manual download and usb copy method.

calibre Debug log
calibre 4.12  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.12  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 108.735785953 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
[3.34] splash screen hidden
[3.34] Started up in 3.34 seconds with 697 books
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(2L, 'C')], (7L, 2L): [(1L, 'H')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90130907632300E1&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=14)
{u'drive_letters': ['H'],
 u'pnp_id_map': {'H': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90130907632300e1&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'H': (2L, 1L)}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: H:\ documents
DEBUG:    0.1 USBMS: scan from root False H:\documents
DEBUG:    0.2 USBMS: count found in cache: 204, count of files in metadata: 204, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 204
DeviceJob: set_books_in_library finished: time= 0.00999999046326
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
DeDRM v6.7.0: Trying to decrypt Norse Mythology.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Norse Mythology
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\####\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\####\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '##########' and UserName '##########'
DeDRM v6.7.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Norse Mythology
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Norse Mythology to db in: 2.3
Added 1 books in 3.3 seconds

**Comment by ElleKayEm** [comment]
Make sure you have the serial number entered correctly -- try copy and paste from the website.  If you got the book from the website for "download & transfer via USB", make sure that you chose the correct E-ink Kindle.

**Comment by eugenetan** [comment]
Thank you that was it!.

I was using the wrong darn e-ink kindle.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
