### ISSUE TITLE
Unable to remove DRM from AZW file (Legimi)

### ISSUE THREAD

**Issue by tomekrupik** [apprenticeharper/DeDRM_tools#1036]
I am using Calibre 4.13 on MacOS 10.15.3 and have installed plugin DeDRM 6.7.0. 
I tried to import an AZW file that I have bought from Legimi (legimi.pl) - I synchronised the book with Kindle though their app first https://www.legimi.pl/pobierz-legimi/ and moved it to Calibre.

I am attaching the debug file contents:

calibre Debug log
calibre 3.31  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
calibre 3.31  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.61] splash screen shown
[0.61] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Google Books at version: 6
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Virtualo at version: 10
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: LitRes at version: 2
Loaded cached store plugin for: Woblink at version: 15
Loaded cached store plugin for: Project Gutenberg at version: 6
Loaded cached store plugin for: Mills and Boon UK at version: 4
Loaded cached store plugin for: Legimi at version: 10
Loaded cached store plugin for: Empik at version: 9
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Świat Ebooków at version: 2
[2.01] main UI initialized...
[2.01] Hiding splash screen
[2.06] splash screen hidden
[2.06] Started up in 2.06 seconds with 78 books
DeDRM v6.7.0: Trying to decrypt Rozmyślania - Marek Aureliusz.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Rozmyślania
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Debugging DND event
text/uri-list 167 'file:///Users/Dropbox/Rozmy%C5%9Blania%20-%20Marek%20Aureliusz.azw\r\n' 

Firefox rurl: None None
URLS: ['file:///Users/Dropbox/Rozmy%C5%9Blania%20-%20Marek%20Aureliusz.azw']
Paths: [u'/Users/Dropbox/Rozmy\u015blania - Marek Aureliusz.azw']
Extensions: frozenset([u'azw'])
Added Rozmyślania to db in: 0.0
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
The book is tag as borrowed or rented.  Legimi looks like a ebook subscription service.  These tools are intended for purchased books.

**Comment by ickam** [comment]
I'd like to make a case for allowing DRM removal from legimi books. Under their subscription you are allowed to sync 7 or 10 books a month with your kindle (7 if you subscribe to an "unlimited ebooks" plan, 10 if you get "unlimited ebooks and audiobooks" plan). This in itself is somewhat unfair because if you were to use their Windows or Android apps you actually get unlimited books, but with Kindle it is only 7 or 10.
As far as I can tell the books that you sync to kindle do not have expiry dates on them, and once you synced them they stay available to you even after you cancelled the subscription.
Syncing with the wire is also somewhat problematic for people with disabilities like myself. Being able to email it to my kindle would be much more accessible.
Last, but not least, allowing to remove DRM on these books would allow people with visual impairments to listen to the books that don't have the audiobook counterparts, with apps like @voice app for android.
Thanks in advance for considering these arguments.

**Comment by j-howell** [comment]
As ElleKayEm  wrote, these tools are meant to be used for purchased books. They are specifically not meant for use with books that are rented, on loan, or provided as part of a time-limited subscription service such as Legimi.

With Legimi are you saving money as compared to the cost of purchasing books outright in exchange for some restrictions, such as the availability of those books only while the subscription is in effect.

**Comment by ickam** [comment]
With all due respect to the developers and other contributors to these tools, does it seem fair to you that it is only the Kindle owners that have to suffer from the main restriction, i.e. only being able to read a limited number of books on a plan that, in any other circumstances, does not exist?
Let me reiterate that if I owned another brand of reader, that allows for installing third-party apps, I would've been able to take out as many books as I please. I thought removing such undue restrictions is precisely why these tools exist.

**Comment by ElleKayEm** [comment]
We obviously have different ideas about undue restrictions.  If you want less restrictions, you can buy the book.

**Comment by Eiluviann** [comment]
There's another reason why someone would like to dedrm ebook rented from Legimi.
**I simply want to enrich the metadata.** Unfortunately ebooks from Legimi do not have a lot of metadata, series name does not populate and book covers tend to be low quality. Covers I can override by modifying cache on my Pocketbook but there is no way to override the series.

**Comment by ElleKayEm** [comment]
Don't see why it matters much on a book you're only borrowing.

**Comment by Eiluviann** [comment]
@ElleKayEm Well you might not but I do as I'm autistic and highly prefer my ebook collection to be well organised and metadata-rich. These ebooks have a watermark embedded anyway and the only thing I want to do is edit the metadata, that's it. Additionally ebooks you get from Legimi stay on your device until you stop paying for the subscription.

Also, a lot of the books I read are part of a series and not being able to use the series functionality on my e-reader is suboptimal to say the least.

**Comment by ElleKayEm** [comment]
That's why I remove DRM from purchased books.  But not for books that are just borrowed.
