### ISSUE TITLE
Epub failed

### ISSUE THREAD

**Issue by asphoa** [apprenticeharper/DeDRM_tools#1039]
It's a Epub in Chinese language that I downloaed online. Could someone help me?

The log reads:
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 4.13  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Chinese Text Conversion (2, 3, 4) && Hyphenate This! (0, 0, 9) && Job Spy (1, 0, 176) && Overdrive Link (2, 38, 0)
calibre 4.13  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Chinese Text Conversion (2, 3, 4) && Hyphenate This! (0, 0, 9) && Job Spy (1, 0, 176) && Overdrive Link (2, 38, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
Job Spy has finished initialization...
[1.85] main UI initialized...
[1.85] Hiding splash screen
DeDRM v6.7.0: Trying to decrypt H035-日本唐代文学研究十家v1_0.epub
DeDRM v6.7.0: Verifying zip archive integrity
[81.85] splash screen hidden
[81.85] Started up in 81.85 seconds with 577 books
DeDRM v6.7.0: “H035-日本唐代文学研究十家v1_0.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Couldn't decrypt after 2.9 seconds. DRM free perhaps?

**Comment by ElleKayEm** [comment]
It doesn't appear to have either Adobe or B&N DRM which are the types of epub DRM that these tools can handle.
