### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by Bones8264** [apprenticeharper/DeDRM_tools#1041]
Hi,

Sorry to be a pest.

I have downloaded a free book from Amazon.  When i try to DeDRM it using 64bit Calibre v4.13 i get the following log:

calibre Debug log
calibre 4.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Goodreads Sync (1, 14, 2) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Goodreads Sync (1, 14, 2) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[2.53] splash screen shown
[2.53] Initializing db...
[7.05] db initialized
[7.05] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    6.6 HttpHelper::__init__: proxy=None
[14.20] main UI initialized...
[14.20] Hiding splash screen
[65.89] splash screen hidden
[65.89] Started up in 65.89 seconds with 23360 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xaa\x0b\xbb\x01\xd6\x90\xe7\x84\x11G\xe7\x9c\x12\x8cS\x90\xaa\xb2\x9f\xcfM\xad\xac.\x02-\xc5\xd8i\x02\xed(', "C:\\Users\\markj\\Downloads\\Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge)_B00L2I3CEU.kfx"]
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\markj\Downloads\Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge)_B00L2I3CEU.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\markj\AppData\Local\Temp\calibre_llu2uq\ro3bgr.kfx-zip
DeDRM v6.7.0: Trying to decrypt ro3bgr.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: ro3bgr
Found 2 keys to try after 0.2 seconds
DeDRM v6.7.0: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.7.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\markj\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\markj\AppData\Local\Temp\calibre_llu2uq\ro3bgr.kfx-zip
Processing container: Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge)_B00L2I3CEU.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge)_B00L2I3CEU.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\markj\AppData\Local\Temp\calibre_llu2uq\jvm5t8_add_books\0\Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge)_B00L2I3CEU.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 132, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Solstice Day Gifts (an Emperor's Edge short story) (The Emperor's Edge) B00L2I3CEU to db in: 0.2
Added 1 books in 3.6 seconds"

Have i missed a process out?

**Comment by ElleKayEm** [comment]
Here's a post detailing the ways to retrieve Kindle books which can be DeDRMed:

https://www.mobileread.com/forums/showthread.php?t=283371
