### ISSUE TITLE
can't remove DRM (Kindle) on a Mac

### ISSUE THREAD

**Issue by Charel-Ferdi** [apprenticeharper/DeDRM_tools#1047]
Hi tried to remove DRM from a german book purchased on my Amazon account. The book title "Due Bagage" downloaded on an old Kindle 4th generation (4.1.4) to get an AZW3 -file.
I'm using a MAC-OS 10.15.4 and Calibre 4.10.1
calibre Debug log
calibre 4.10.1  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.10.1  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.24] main UI initialized...
[1.24] Hiding splash screen
DeDRM v6.7.0: Trying to decrypt Die Bagage-asin_B081HZK83V-type_EBOK-v_0.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Die Bagage (German Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[4.16] splash screen hidden
[4.16] Started up in 4.16 seconds with 378 books
Added Die Bagage (German Edition) to db in: 0.0
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
You need to enter your E-ink Kindle's serial number into the DeDRM plugin customization.

**Comment by Charel-Ferdi** [comment]
WOW, works perfectly!
THANKS

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
