### ISSUE TITLE
can't remove DRM (Kobo) 

### ISSUE THREAD

**Issue by gigixshiori** [apprenticeharper/DeDRM_tools#1050]
I tried to remove DRM from four Chinese book purchased on my kobo account.
I'm using Windows10(64 bits) , Calibre 4.13.0 and Obok DeDrm 6.5.4
Thank you.
calibre Debug log
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 78.8275862069
Using calibre Qt style: True

**Comment by ElleKayEm** [comment]
That's the whole log?  Are the books from Kobo Desktop or from a Kobo ereader?  Can you import other Kobo books with Obok or is it just these that aren't working?

(You could also try the Adobe DRM versions with DeDRM.)

**Comment by gigixshiori** [comment]
The books are from Kobo Desktop. 
The whole log in calibre is
calibre, version 4.13.0
錯誤： 未處理的例外: <b>OperationalError</b>:unable to open database file

calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 96, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 385, in __init__
OperationalError: unable to open database file


I tried the Adobe DRM versions with DeDRM, it was working successfully.

**Comment by ElleKayEm** [comment]
Something is blocking calibre/Obok from opening the Kobo database.  An antivirus program?

**Comment by gigixshiori** [comment]
No, I turned off the antivirus program.

**Comment by ElleKayEm** [comment]
Is everything on the same local drive?  Not sure what could be blocking access.

I don't know if there are any changes besides an update to the version number to match DeDRM, but you could try the current 6.7 version of the Obok plugin.

**Comment by gigixshiori** [comment]
Yes, everything is on the same local drive.I tried the current 6.7 version of the Obok plugin, while the result is the same as using the old version.

calibre Debug log
calibre, version 4.13.0
錯誤： 未處理的例外: <b>OperationalError</b>:unable to open database file

calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 96, in launchObok
  File "calibre_plugins.obok_dedrm.obok.obok", line 389, in __init__
OperationalError: unable to open database file

**Comment by ElleKayEm** [comment]
I just tested it myself with Kobo Desktop 4.20.12714, calibre 4.13 (64-bit), and Obok 6.7 on Windows 10  and was able to remove DRM from one of my books.

I don't know what's causing the problem in your setup or how to fix it.
