### ISSUE TITLE
Books still have DRM, actual text is gibberish when it is removed.

### ISSUE THREAD

**Issue by FrustratedDeDRM** [apprenticeharper/DeDRM_tools#1052]
Trying to import books, have DeDRM and the KFX input plugins. At first I was able to remove the DRM to open the ebooks, however once they were opened, the actual text inside was a bunch of characters that were meaningless to me. Then I downloaded the KFX input plugin, thinking it would decode and convert the text, but now the DRM is not being removed. The metadata imported and converted fine. These are Kindle Ebooks, downloaded and imported from the Kindle for PC app. I have copied and pasted the calibre debug log for a book that did not open due to DRM. If you want me to post one that is able to be opened but is gibberish, let me know! I import the books using the subdirectories option in calibre, tried the entire "my kindle content" folder and individual book folders.

calibre Debug log
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.52] splash screen shown
[0.52] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
[2.25] main UI initialized...
[2.25] Hiding splash screen
[6.95] splash screen hidden
[6.95] Started up in 6.95 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0f\xaf\xb0\xb7\xc9\x01\x95&\xbdQ\x0e\xf8\xbe\x9a\x12\xfc\xa4?GQ\x9f\xa2~\xe9Wf\x99\xc9(-y\xfb', 'C:\\Users\\adria\\OneDrive\\Documents\\My Kindle Content\\B000FBJCK8_EBOK']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\adria\OneDrive\Documents\My Kindle Content\B000FBJCK8_EBOK\B000FBJCK8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\adria\AppData\Local\Temp\calibre_nigd3u\u7h0w7.kfx-zip
DeDRM v6.7.0: Trying to decrypt u7h0w7.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: u7h0w7
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cd8b2622-8188-4952-8553-a5a2ddeb97a3.voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\adria\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\adria\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '772465219' and UserName '6164726961'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: u7h0w7
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cd8b2622-8188-4952-8553-a5a2ddeb97a3.voucher
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\adria\AppData\Local\Temp\calibre_nigd3u\u7h0w7.kfx-zip
Processing container: B000FBJCK8_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B000FBJCK8_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\adria\AppData\Local\Temp\calibre_nigd3u\qudjad_add_books\0\B000FBJCK8_EBOK.kfx-zip
Added CR!1TNAKHRRR90EH5108NJCX9SH6ED1.azw to db in: 0.2
Added 1 books in 8.4 seconds
Worker Launch took: 0.139999866486
Job: 0 Convert book 1 of 1 (CR!1TNAKHRRR90EH5108NJCX9SH6ED1.azw) finished
Convert book 1 of 1 (CR!1TNAKHRRR90EH5108NJCX9SH6ED1.azw)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\adria\\AppData\\Local\\Temp\\calibre_nigd3u\\yydchl.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\adria\\AppData\\Local\\Temp\\calibre_nigd3u\\k9wkcs.opf'
	  output_profile: u'generic_eink'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.13.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\adria\\AppData\\Local\\Temp\\calibre_nigd3u\\yydchl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05D6DAF0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x05D6DCF0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\adria\\AppData\\Local\\Temp\\calibre_nigd3u\\k9wkcs.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\adria\AppData\Local\Temp\calibre_nigd3u\8etibh.kfx-zip
	Software versions: KFX Input 1.31.0, calibre 4.13, Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\adria\AppData\Local\Temp\calibre_nigd3u\8etibh.kfx-zip
	Processing container: B000FBJCK8_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container B000FBJCK8_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by FrustratedDeDRM** [comment]
I'm using kindle 1.28, will download an earlier version  and see if that fixes it.

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.24 or earlier.
