### ISSUE TITLE
Kobo book not decrypted

### ISSUE THREAD

**Issue by faelys** [apprenticeharper/DeDRM_tools#1057]
I hope I'm not reporting a duplicate here, but I have just bought 7 Kobo e-books, and the plugin works perfectly for 6 of them (as it did for all my previous purchases, thanks a lot for that).

The book opens fine the Kobo desktop application v4.20.12714 on windows 10, and its DRM parameters do not seem different from the others (though admittedly I don't think I have found the exact Adobe DRM version).

When importing using Obok DeDRM v6.7.0 in Calibre 4.13.0, the first suspicious thing is that the book is marked as "DRM free", while it is supposed to be DRMed according to the Kobo page. Trying to import it in Calibre does so without reporting any error, but opening the import book shows only scrambled signs instead of text.

Here is the output of the operation performed under `calibre-debug -g`:
```
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164557 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[2.20] main UI initialized...
[2.22] Hiding splash screen
[2.48] splash screen hidden
[2.48] Started up in 2.48 seconds with 28 books
Running Obok DeDRM v6.7.0
DEBUG:   12.3 didn't find device
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\faelys\appdata\local\temp\tmplqoqrv
DEBUG:   12.3 got kobodir C:\Users\Faelys\AppData\Local\Kobo\Kobo Desktop Edition
Found 12 possible keys to try.
DEBUG:   45.7 BookListTableWidget:get_books - book_num: 18
DEBUG:   45.7 BookListTableWidget:get_books - book: Smoke Bitten
DEBUG:   45.7 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.7.0 - Decrypting Smoke Bitten
Trying key:  d2b8b3505d56708c9e14f6a727853865
Success!
DEBUG:   45.8 DecryptAddProgressDialog::do_book_action - decrypted book: 'Smoke Bitten'
Traceback (most recent call last):
  File "site-packages\calibre\db\cache.py", line 1330, in set_metadata
  File "site-packages\calibre\db\cache.py", line 1253, in set_cover
  File "site-packages\calibre\db\backend.py", line 1456, in set_cover
  File "site-packages\calibre\utils\img.py", line 287, in save_cover_data_to
  File "site-packages\calibre\utils\img.py", line 199, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Obok DeDRM v6.7.0 - Added Smoke Bitten
Obok DeDRM v6.7.0 - wrapping up results.
```

Is there anything I'm doing wrong? Can I do anything to further diagnose the issue?

Thanks in advance for your help.

**Comment by faelys** [comment]
Also I forgot to mention, the book which does work is `Smoke Bitten`, and I do not have ADE installed on my computer, and I do not own any Kobo device (I buy on Kobo website, then download on the Desktop App on another computer, then read the DRM free files on a PocketBook device).

**Comment by faelys** [comment]
While I did uninstall and reinstall the plug-in before reporting the issue, I did not try going all the way to unstalling and reinstalling Calibre, which apparently solved the issue (the book is correctly detected as locked in the selection list, and correctly decrypted afterwards).

Sorry for the noise and thank you for providing the plug-in!
