### ISSUE TITLE
Can't remove DRM in Windows PC

### ISSUE THREAD

**Issue by majc18** [apprenticeharper/DeDRM_tools#1059]
calibre Debug log
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Obok DeDRM (6, 7, 0)
calibre 4.13  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.89] main UI initialized...
[1.89] Hiding splash screen
[15.34] splash screen hidden
[15.36] Started up in 15.36 seconds with 4 books
Worker Launch took: 0.210000038147
Job: 0 Convert book 1 of 1 (Aquele Homem) finished
Convert book 1 of 1 (Aquele Homem)
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\majc1\\AppData\\Local\\Temp\\calibre_gm4hmp\\robo3q.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\majc1\\AppData\\Local\\Temp\\calibre_gm4hmp\\akvhtw.opf'
	  output_profile: u'tablet'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.13.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\majc1\\AppData\\Local\\Temp\\calibre_gm4hmp\\robo3q.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05000CB0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x0500D2D0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\majc1\\AppData\\Local\\Temp\\calibre_gm4hmp\\akvhtw.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\majc1\AppData\Local\Temp\calibre_gm4hmp\swfr09.azw
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Aquele Homem (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Aquele Homem

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre, not during conversion.  So we'll need a log of the book getting added to see what went wrong.  See the FAQs here:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by jomarkGit** [comment]
calibre Debug log
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 0) && KFX Output (1, 41, 0)
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 0) && KFX Output (1, 41, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.017029703 x 95.9198312236
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
[4.38] splash screen hidden
[4.38] Started up in 4.38 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf0GpA\xea\xc8\xf7\xa9\x0e\xf2\xa2\xd4%\xdaX\x1c\xaa\xa9\xa0\xc4\xf7\x8f\x93\xc3I\x1d\xd4\xae\x83\x91Y%', 'C:\\Users\\Base\\Documents\\My Kindle Content\\B06WRP1GR3_EBOK\\B06WRP1GR3_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\Base\Documents\My Kindle Content\B06WRP1GR3_EBOK\B06WRP1GR3_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\Base\AppData\Local\Temp\calibre_ppjylm\hvyt8b.kfx-zip
DeDRM v6.6.3: Trying to decrypt hvyt8b.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: hvyt8b
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a6212537-356e-48fd-8e53-261d1c27622a.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.3: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Base\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Base\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3871176200' and UserName '42617365'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: hvyt8b
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a6212537-356e-48fd-8e53-261d1c27622a.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\Base\AppData\Local\Temp\calibre_ppjylm\hvyt8b.kfx-zip
Processing container: B06WRP1GR3_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B06WRP1GR3_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Base\AppData\Local\Temp\calibre_ppjylm\i75gqd_add_books\0\B06WRP1GR3_EBOK.kfx-zip
Added Master PowerShell Tricks (Volume Book 2) to db in: 0.1
Added 1 books in 1.1 seconds

**Comment by ElleKayEm** [comment]
From the log:

> This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by jomarkGit** [comment]
> From the log:
> 
> > This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

 It was worked !!! .
Thank you  ElleKayEm
