### ISSUE TITLE
Can't acces to plugin preferences

### ISSUE THREAD

**Issue by julienboulay** [apprenticeharper/DeDRM_tools#107]
I've installed Calibre v2.57.1 with the latest DeDRM version 6.4.3, on windows 7, but I can not make it work properly.

When I want to open the preferences window, I get the following error:

calibre, version 2.57.1
ERREUR : Exception non gérée: <b>AttributeError</b>:'module' object has no attribute 'ConfigWidget'

calibre 2.57.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 628, in config_widget
AttributeError: 'module' object has no attribute 'ConfigWidget'

**Comment by julienboulay** [comment]
Ok, I just uninstalled the plugin and reinstalled it and it works now.
I downloaded the package from https://github.com/apprenticeharper/DeDRM_tools/releases
