### ISSUE TITLE
DRM Removal Didn't Work on Win7 PC

### ISSUE THREAD

**Issue by Mysteryoustraveler** [apprenticeharper/DeDRM_tools#1072]
Purchased book on Amazon.
*****************************************************************************************************

calibre Debug log
calibre 4.14  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.16+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0) && Set KFX metadata (from KFX Output) (1, 15, 0) && KFX Output (1, 15, 0)
calibre 4.14  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.16+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0) && Set KFX metadata (from KFX Output) (1, 15, 0) && KFX Output (1, 15, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[2.00] main UI initialized...
[2.00] Hiding splash screen
[28.67] splash screen hidden
[28.67] Started up in 28.67 seconds with 86 books
Gather KFX-ZIP (from KFX Input) 1.18.0: Importing C:/Users/User/Documents/My Kindle Content/B002BDUBXU_EBOK/B002BDUBXU_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\User\AppData\Local\Temp\calibre_nmeijf\nfcgiv.kfx-zip
DeDRM v6.7.0: Trying to decrypt nfcgiv.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: nfcgiv
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.83a6137c-1af5-41d0-8a2c-d148089ac0c7.voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\User\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '613936582' and UserName '55736572'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: nfcgiv
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.83a6137c-1af5-41d0-8a2c-d148089ac0c7.voucher
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.18.0: Packaging C:\Users\User\AppData\Local\Temp\calibre_nmeijf\nfcgiv.kfx-zip
Processing container: B002BDUBXU_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B002BDUBXU_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\User\AppData\Local\Temp\calibre_nmeijf\cjzkqb_add_books\0\B002BDUBXU_EBOK.kfx-zip
Added Tarot Reader's Workbook - A Comprehensive Guide from Beginner to Master to db in: 0.2
Added 1 books in 1.4 seconds

**Comment by ElleKayEm** [comment]
You'll need to use Kindle for PC 1.24 or earlier.

**Comment by Mysteryoustraveler** [comment]
Thank you for your reply.  I discovered this after I posted.  No worries, I found another workaround.  Thanks again!
