### ISSUE TITLE
DRM removal failed

### ISSUE THREAD

**Issue by bobapop** [apprenticeharper/DeDRM_tools#1073]
Log:

```
calibre,` version 4.14.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Freemasonry: Spiritual Alchemy (The Spiritual Freemasonry series Book 2))

Convert book 1 of 1 (Freemasonry: Spiritual Alchemy (The Spiritual Freemasonry series Book 2))
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  pdf_sans_family: u'MS Shell Dlg 2'
  verbose: 2
  cover: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_p0jlgd\\kauqch.jpeg'
  read_metadata_from_opf: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_p0jlgd\\exrdwb.opf'
  pdf_serif_family: u'MS Shell Dlg 2'
Resolved conversion options
calibre version: 4.14.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_p0jlgd\\kauqch.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000004131E08>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000000004134A48>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\calibre_p0jlgd\\exrdwb.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\ADMINI~1\AppData\Local\Temp\calibre_p0jlgd\cx6maq.kfx-zip
Software versions: KFX Input 1.31.0, calibre 4.14 [64bit], Windows-7-6.1.7601-SP1
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\ADMINI~1\AppData\Local\Temp\calibre_p0jlgd\cx6maq.kfx-zip
Processing container: B07YRMS9K6_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07YRMS9K6_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!
```

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
