### ISSUE TITLE
Cannot decrypt AZW3 under Wine

### ISSUE THREAD

**Issue by vace117** [apprenticeharper/DeDRM_tools#1074]
Greetings. Having lots of trouble after following all instructions. Here's what I have setup:

- Ubuntu Eoan
- Calibre 3.46
- DeDRM 6.7.0
- wine-4.0.2 (32-bit)
** python27
** pycrypto-2.6.win32-py2.7.exe
** KindleForPC-installer-1.17.44170.exe

I can run Kindle for PC under Wine, I can log in to my Amazon account, and I can read the book from the application.

Furthermore, I can run `kindlekey.py` manually and obtain the `k4i` file:
```text
calibre@52aa3a56a0a2:~$ wine python.exe "/home/calibre/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/calibre/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"
kindlekey.py v2.6
Copyright ? 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
searching for kinfoFiles in C:\users\calibre\Local Settings\Application Data
Found K4PC 1.9+ kinf2011 file: C:\users\calibre\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '0' and UserName '63616c69627265'
Saved a key to Z:\home\calibre\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey2.k4i
```
The `k4i` file looks good to me.

But then, here's what happens when I try add a `AZW3` file that I downloaded from Amazon using `Download & transfer via USB` function:
```text
DeDRM v6.7.0: Trying to decrypt Birth Partner 5th Edition_A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright ? 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Birth Partner 5th Edition:A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions
Got DSN key from database kindlekey1
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.7.0: Running kindlekey.py under Wine
DeDRM v6.7.0: Command line: 'wine python.exe "/home/calibre/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/calibre/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
kindlekey.py v2.6
Copyright ? 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
searching for kinfoFiles in C:\users\calibre\Local Settings\Application Data
Found K4PC 1.9+ kinf2011 file: C:\users\calibre\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '0' and UserName '63616c69627265'
Saved a key to Z:\home\calibre\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey3.k4i
DeDRM v6.7.0: Found and decrypted 3 key files
DeDRM v6.7.0: Found 3 new keys
MobiDeDrm v0.42.
Copyright ? 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Birth Partner 5th Edition:A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions
Got DSN key from database default_key_3
Got DSN key from database default_key_2
Got DSN key from database default_key_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

Don't know what to try next, so any advice would be greatly appreciated!

**Comment by vace117** [comment]
I have tried the same book, but now on Windows 10. The results seems to be about the same...

```text
λ tail -f tmpabhomt.txt
physicalDpi: 96.0 x 95.8401486989
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.11] main UI initialized...
[1.11] Hiding splash screen
[74.80] splash screen hidden
[74.80] Started up in 74.80 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x96=\xfc\xfbw\x9b\x83\xcdI9K\xc9o\x14-s\x1cK\xac\xa6\xbdQU\xba|I\x83\xb7\xdb%\xcd<', 'D:\\books\\DRM\\Birth Partner 5th Edition_A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions.azw3']
DeDRM v6.7.0: Trying to decrypt Birth Partner 5th Edition_A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Birth Partner 5th Edition:A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\val\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\val\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3971830177' and UserName '76616c'
DeDRM v6.7.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Birth Partner 5th Edition:A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Birth Partner 5th Edition:A Complete Guide to Childbirth for Dads, Partners, Doulas, and All Other Labor Companions to db in: 0.2
Added 1 books in 1.3 seconds
```

**Comment by ElleKayEm** [comment]
For a book downloaded from the website, you need to choose an E-ink Kindle (not a Fire) for the device and enter the Kindle's serial number into the DeDRM plugin customization.  The key that the plug retrieved (and that you got from running kindlekey.py) would work on a book downloaded with Kindle for PC that you have installed under Wine.  Each device and app installation has a different key -- even for the same Amazon account.

**Comment by vace117** [comment]
@ElleKayEm Thank you for clearing that up! I can now DeDRM books by downloading them in the Kindle app first (on Windows - I'll try my Linux setup a bit later).
However, DeDRMing that `AZW3` file that I downloaded from the Amazon website still fails, even if I enter my Kindle's serial number in the DeDRM plugin customization. It now says:

```text
DeDRM v6.7.0: Failed to decrypt with error: No key found in 6 keys tried.
```
It used to say `0 keys tried`, so I am assuming it is trying the serial based key, but it doesn't match for some reason?

**Comment by ElleKayEm** [comment]
Make sure you have the serial number entered correctly - try copy & paste from the website.  Make sure the file is for that Kindle if you have more than one on your account.  And again it needs to be E-ink.  It won't work for Fire tablets.

**Comment by vace117** [comment]
@ElleKayEm That was it! The serial number I was trying to use came from my Kindle itself. I went to `Settings -> Device Options -> Device Info -> Serial Number`. For some reason that is not the correct number to use...

I checked the Serial Number on the Amazon website, and it was different! It also worked to decrypt the book. Thank you so much!

Any idea how my Kindle is able to decrypt the books considering that its serial number clearly does not match the encryption?

**Comment by ElleKayEm** [comment]
Are you sure the physical Kindle is the same as the one on the website that you chose when downloading the file?  Or did you misread the serial number on the device?  Easy to mistake B for 8, G for 6 etc.

**Comment by vace117** [comment]
@ElleKayEm Yep - you are correct. There were 2 devices registered on the Amazon website, and I downloaded the file for the wrong one. Mystery solved :)

I still haven't had a chance to try the Linux setup with Wine again. My eventual goal is to make a Docker container with ADE + Kindle for PC + Calibre + DeDRM, in order to finally have a user-friendly and version-controlled way of running all of that software correctly.

**Comment by vace117** [comment]
Everything works under Wine too now. 

I have documented and automated the entire setup here: 
       https://github.com/vace117/calibre-dedrm-docker-image
