### ISSUE TITLE
Unable to remove DRM from Amazon

### ISSUE THREAD

**Issue by MakelKoszmar** [apprenticeharper/DeDRM_tools#1075]
Using a Windows 10 PC, trying to convert to PDF on 3 books but it isn't working.
____________________________
calibre Debug log
calibre 4.14  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.14  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
[3.97] splash screen hidden
[3.97] Started up in 3.97 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['q\xcd\nN"\x1d\xaek\x9d\x1b\xf4%\xb1\xd20R\xb9\x01\xecA\xe8-\xe8\x1eU-\x16n\xe7\x12\x98H', 'H:\\Doc_2020_march\\Calibre Library\\BookOfTongues.azw', 'H:\\Doc_2020_march\\Calibre Library\\RopeOfThorns.azw', 'H:\\Doc_2020_march\\Calibre Library\\Spect2.azw', 'H:\\Doc_2020_march\\Calibre Library\\Spectr1.azw', 'H:\\Doc_2020_march\\Calibre Library\\TreeOfBones.azw']
DeDRM v6.7.0: Trying to decrypt BookOfTongues.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Book of Tongues: Volume One of the Hexslinger Series: 1
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Tom_s\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v6.7.0: Trying to decrypt TreeOfBones.azw
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
DeDRM v6.7.0: Trying to decrypt RopeOfThorns.azw
Decrypting Kindle Format 8 ebook: A Tree of Bones: Volume Three of the Hexslinger Series
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Tom_s\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Rope of Thorns: Volume Two of the Hexslinger Series
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Tom_s\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v6.7.0: Trying to decrypt Spectr1.azw
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: SPECTR: Volume 1
Found 0 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v6.7.0: Finished after 0.0 seconds
DeDRM v6.7.0: Trying to decrypt Spect2.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: SPECTR: Volume 2
Found 0 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v6.7.0: Finished after 0.0 seconds
Added A Book of Tongues: Volume One of the Hexslinger Series: 1 to db in: 0.3
Added A Tree of Bones: Volume Three of the Hexslinger Series to db in: 0.3
Added SPECTR: Volume 1 to db in: 0.3
Added A Rope of Thorns: Volume Two of the Hexslinger Series to db in: 0.3
Added SPECTR: Volume 2 to db in: 0.5
Added 5 books in 2.2 seconds

**Comment by alokc83** [comment]
`Found 0 keys to try after 0.0 seconds` 

It doesn't seem like you have added kindle serial number to the plugin. 

Go to plug-ins under preference then if you double click on DeDRM plug-in it would open the configuration. You need to give a valid kindle serial number.

**Comment by ElleKayEm** [comment]
And it needs to be an E-ink Kindle, not a Fire.
