### ISSUE TITLE
Unable to remove DRM on Windows 10 PC

### ISSUE THREAD

**Issue by kachow99** [apprenticeharper/DeDRM_tools#1077]
calibre Fehlerdiagnoseprotokoll
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0)
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[1.70] main UI initialized...
[1.70] Hiding splash screen
[4.92] splash screen hidden
[4.92] Started up in 4.92 seconds with 1 books
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0310\6&128165BA&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x310 devid=usb\vid_1949&pid_0004&rev_0310 devinst=11)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0310#6&128165ba&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.0 USBMS: scan from root False D:\documents
DEBUG:    0.0 USBMS: count found in cache: 22, count of files in metadata: 22, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 22
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0310\6&128165BA&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x310 devid=usb\vid_1949&pid_0004&rev_0310 devinst=11)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0310#6&128165ba&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 3 Geräteinformationen abrufen started
DeviceJob: 3 Geräteinformationen abrufen done, calling callback
DeviceJob: 3 Geräteinformationen abrufen callback returned
Job: 4 Bibliotheksinformationen festlegen started
DeviceJob: 4 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 4 Bibliotheksinformationen festlegen callback returned
Job: 5 Gerätebücherliste abrufen started
DEBUG:  105.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:  105.3 USBMS: dirs are: D:\ documents
DEBUG:  105.3 USBMS: scan from root False D:\documents
DEBUG:  105.3 USBMS: count found in cache: 22, count of files in metadata: 22, need_sync: False
DEBUG:  105.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:  105.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:  105.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 5 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 22
DeviceJob: set_books_in_library finished: time= 0.00500011444092
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 5 Gerätebücherliste abrufen callback returned
Job: 5 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 3 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 4 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['f\xfcmkL3\x1c\x1fxA\xa9\xea\x9e\xef\xe4\x88\x11\xe6\xd8\xf1k\xbe\xa1i\x0f\xe8\xad\xfb-\xc6\xf7E', "D:\\documents\\Die 13 1_2 Leben des K\xc3\xa4pt'n Blaub\xc3\xa4r_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx"]
Gather KFX-ZIP (from KFX Input) 1.20.0: Importing D:\documents\Die 13 1_2 Leben des KÃ¤pt'n BlaubÃ¤r_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx
Gather KFX-ZIP (from KFX Input): Gathered 14 file(s) as C:\Users\georg\AppData\Local\Temp\calibre_raayi5\81oz30.kfx-zip
DeDRM v6.7.0: Trying to decrypt 81oz30.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 81oz30
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\georg\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\georg\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1212373353' and UserName '67656f7267'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: 81oz30
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.20.0: Packaging C:\Users\georg\AppData\Local\Temp\calibre_raayi5\81oz30.kfx-zip
Processing container: CR!0ACEE7YMT16GZC4P9CX4MEX1B3PQ.kfx
Processing container: CR!782DNEKZR152Z8NT9D0DJ8NG056P.kfx
Processing container: CR!9ZE8YWSNFX5G5D12VBJ6M0X3Q5H8.kfx
Processing container: CR!BBA21MVWN57E18X9NY3T3FC02P36.kfx
Processing container: CR!FBKEM4H8C9789B3MSQR1V39Y24FA.kfx
Processing container: CR!NDE98RT57X5GS4EB8NY2NKFRD163.kfx
Processing container: CR!NSKZWY6GBD5B7FTXPJPXSASR5GZ2.kfx
Processing container: CR!TD7ZVR59YH6XS68NT26C5XY1BA3E.kfx
Processing container: CR!XK4EKQN95X15Q4T23N2BM7Y8B9YT.kfx
Processing container: CR!YDB7B45P750KH9QXQ5W698GEGAKJ.kfx
Processing container: CR!YKGX3VK3457ZVFJERRKXJXJKFND1.kfx
Processing container: Die 13 1_2 Leben des KÃ¤pt'n BlaubÃ¤r_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container Die 13 1_2 Leben des KÃ¤pt'n BlaubÃ¤r_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\georg\AppData\Local\Temp\calibre_raayi5\ykfwhp_add_books\0\Die 13 1_2 Leben des KÃ¤pt'n BlaubÃ¤r_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx-zip
Added Die 13 1/2 Leben des Käpt'n Blaubär: Roman, erstmals in Farbe (German Edition) to db in: 0.2
Added 1 books in 2.8 seconds
Worker Launch took: 0.174000024796
Job: 6 Buch 1 von 1 (Die 13 1/2 Leben des Käpt'n Blaubär: Roman, erstmals in Farbe (German Edition)) konvertieren finished
Buch 1 von 1 (Die 13 1/2 Leben des Käpt'n Blaubär: Roman, erstmals in Farbe (German Edition)) konvertieren
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\georg\\AppData\\Local\\Temp\\calibre_raayi5\\dk1wto.opf'
	  cover: u'C:\\Users\\georg\\AppData\\Local\\Temp\\calibre_raayi5\\mh8ogy.jpeg'
	  output_profile: u'kindle'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.14.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\georg\\AppData\\Local\\Temp\\calibre_raayi5\\mh8ogy.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000021EABAF9AC8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x0000021EABB01F48>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\georg\\AppData\\Local\\Temp\\calibre_raayi5\\dk1wto.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\georg\AppData\Local\Temp\calibre_raayi5\3tn1qe.kfx-zip
	Software versions: KFX Input 1.20.0, calibre 4.14 [64bit], Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\georg\AppData\Local\Temp\calibre_raayi5\3tn1qe.kfx-zip
	Processing container: CR!0ACEE7YMT16GZC4P9CX4MEX1B3PQ.kfx
	Processing container: CR!782DNEKZR152Z8NT9D0DJ8NG056P.kfx
	Processing container: CR!9ZE8YWSNFX5G5D12VBJ6M0X3Q5H8.kfx
	Processing container: CR!BBA21MVWN57E18X9NY3T3FC02P36.kfx
	Processing container: CR!FBKEM4H8C9789B3MSQR1V39Y24FA.kfx
	Processing container: CR!NDE98RT57X5GS4EB8NY2NKFRD163.kfx
	Processing container: CR!NSKZWY6GBD5B7FTXPJPXSASR5GZ2.kfx
	Processing container: CR!TD7ZVR59YH6XS68NT26C5XY1BA3E.kfx
	Processing container: CR!XK4EKQN95X15Q4T23N2BM7Y8B9YT.kfx
	Processing container: CR!YDB7B45P750KH9QXQ5W698GEGAKJ.kfx
	Processing container: CR!YKGX3VK3457ZVFJERRKXJXJKFND1.kfx
	Processing container: Die 13 1_2 Leben des Käpt'n Blaubär_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	  File "calibre_plugins.kfx_input.__init__", line 195, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container Die 13 1_2 Leben des Käpt'n Blaubär_ Roman, erstmals in Farbe (German Edition)_B00GGHUYDO.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 103, in convert
	calibre.ebooks.DRMError: This book has DRM!

I did type in my Serial Number and I'm 99% certain it was correct.

**Comment by ElleKayEm** [comment]
You'll either need to get the file from the website for "download & transfer via USB" or use Kindle for PC 1.24 or earlier.

**Comment by boubilanijay** [comment]
Hey, my name is caio, I'm not a programmer or anything..
I'm trying to de DRM my e-book but, when I open the EPUB converted file in the Calibre app the e-book appears unreadable, like a "soup of symbols". I have read the Readme and I'm pasting the log of the import process next: 

calibre Debug log
calibre 4.10.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.10.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.048235294 x 102.669473684
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.81] splash screen shown
[0.81] Initializing db...
[0.81] db initialized
[0.81] Constructing main UI...
[2.81] main UI initialized...
[2.81] Hiding splash screen
[90.14] splash screen hidden
[90.14] Started up in 90.14 seconds with 30 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['b\x88+M\xc7\xde3\x14\x96D\x1fY\xae\xbe\x7f%\xdf\xf4\xa9\xbax\x0e\\\x9fI\xb5\xc7\x06V\xde\xd4T', 'C:\\Users\\Caio Bibiani\\Documents\\My Kindle Content\\B01MS90BQ8_EBOK\\CR!VFFT34R8V9059677YW6A4G8DFFSW.azw.md']
Added CR!VFFT34R8V9059677YW6A4G8DFFSW.azw to db in: 1.5
Added 1 books in 2.3 seconds


Can somebody tell me what I am missing?
Many thanks in advance

OBS: I have a 1.17 Kindle version for PC, my Calibre version is updated and I am using the DeDRM 6.6.3 (but I had the same result with the DeDRM 6.7.0)

**Comment by ElleKayEm** [comment]
Looks like Kindle for PC updated or you didn't redownload your books after downgrading.  Take a look at the first post here, particularly the part at the bottom about preventing unwanted updates:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by boubilanijay** [comment]
Thank you very much for your help! I checked the post and it works now. You saved my studies, thanks!
