### ISSUE TITLE
Removing DRM from KFX-Files from a Kindle doesn't work

### ISSUE THREAD

**Issue by mushrooms4free** [apprenticeharper/DeDRM_tools#1079]
I have installed DeDRM using DeDRM_Plugin.zip file, added the correct serial number (I checked it multiple time) and installed KFX input. After that I connected my Kindle (standard, 8. generation I think) via USB cable and added an ebook with the KFX extension from G:\documents\Downloads\Items01 with G: being the Kindle but DeDRM doesn't seem to have worked since I can't convert or read in Calibre. The ebook was purchased through the store on Kindle. I don't use Kindle for PC. DeDRM is on the latest release (just downloaded it) and Calibre is on 4.14.0. My OS is Windows 10 if that's relevant. According to the log it seems like no key could successfully decrypt KFX DRM voucher (whatever that means). Here is the log:

calibre Fehlerdiagnoseprotokoll
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.58] splash screen shown
[0.58] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[1.86] main UI initialized...
[1.86] Hiding splash screen
Storage number map:
{(7L, 0L): [(4L, 'C'), (6L, 'D')], (7L, 1L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G090WH0591020151&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=3)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g090wh0591020151&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'G': (1L, 1L)}}
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.0 USBMS: scan from root False G:\documents
DEBUG:    0.1 USBMS: count found in cache: 10, count of files in metadata: 10, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 10
DeviceJob: set_books_in_library finished: time= 0.00200009346008
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
[15.38] splash screen hidden
[15.38] Started up in 15.38 seconds with 22 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc5!X\xa1gfx\xbd7\x9b\xbbG_U{z\xc9-\xa4<\xea,c\xc4\xf4[\x17{\x14m\xcd\xef', 'G:\\documents\\Downloads\\Items01\\All You Need Is Kill Novel_B076PJ967N.kfx']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing G:\documents\Downloads\Items01\All You Need Is Kill Novel_B076PJ967N.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\PC\AppData\Local\Temp\calibre_e6ywdd\dli80y.kfx-zip
DeDRM v6.7.0: Trying to decrypt dli80y.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: dli80y
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\PC\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\PC\AppData\Local\Temp\calibre_e6ywdd\dli80y.kfx-zip
Processing container: All You Need Is Kill Novel_B076PJ967N.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container All You Need Is Kill Novel_B076PJ967N.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\PC\AppData\Local\Temp\calibre_e6ywdd\pjhfau_add_books\0\All You Need Is Kill Novel_B076PJ967N.kfx-zip
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added All You Need Is Kill Novel (German Edition) to db in: 1.4
Added 1 books in 2.2 seconds
Worker Launch took: 0.230999946594
Job: 3 Buch 1 von 1 (All You Need Is Kill Novel (German Edition)) konvertieren finished
Buch 1 von 1 (All You Need Is Kill Novel (German Edition)) konvertieren
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'kindle'
	  read_metadata_from_opf: u'C:\\Users\\PC\\AppData\\Local\\Temp\\calibre_e6ywdd\\4i5zi_.opf'
	  verbose: 2
	  cover: u'C:\\Users\\PC\\AppData\\Local\\Temp\\calibre_e6ywdd\\tgoarp.jpeg'
	Resolved conversion options
	calibre version: 4.14.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\PC\\AppData\\Local\\Temp\\calibre_e6ywdd\\tgoarp.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000138C99D0FC8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x00000138C99E3508>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\PC\\AppData\\Local\\Temp\\calibre_e6ywdd\\4i5zi_.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\PC\AppData\Local\Temp\calibre_e6ywdd\yc8pnm.kfx-zip
	Software versions: KFX Input 1.31.0, calibre 4.14 [64bit], Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\PC\AppData\Local\Temp\calibre_e6ywdd\yc8pnm.kfx-zip
	Processing container: All You Need Is Kill Novel_B076PJ967N.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container All You Need Is Kill Novel_B076PJ967N.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by mushrooms4free** [comment]
> 
> 
> As long as it's an E-ink Kindle and not a Fire, get the book from the website for "download & transfer via USB."

It worked, thanks :)
