### ISSUE TITLE
Can not import Kindle book / remove DRM

### ISSUE THREAD

**Issue by Barstuck** [apprenticeharper/DeDRM_tools#1080]
Windows 10
Kindle for PC version 1.24.3

calibre Debug log
calibre 4.14 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
calibre 4.14 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.0 x 108.213017751
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.45] main UI initialized...
[2.45] Hiding splash screen
[7.75] splash screen hidden
[7.75] Started up in 7.75 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa7\xdf\x1c\x1csD\xd8,\xeb5L\x8b\xce\xdeH\x95#\x02\xa8|/^\xb3v\xb4\x8b\xe0\xc5g\xc5\xd1P', 'C:\\Users\\daryl\\Documents\\My Kindle Content\\B07Y8HKVGJ_EBOK\\B07Y8HKVGJ_EBOK.azw']
DeDRM v6.7.0: Trying to decrypt B07Y8HKVGJ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.7.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\daryl\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\daryl\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '907912871' and UserName '646172796c'
DeDRM v6.7.0: Found 1 new key
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 321, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B07Y8HKVGJ EBOK to db in: 4.7
Added 1 books in 6.2 seconds
Worker Launch took: 0.190999984741
Traceback (most recent call last):
Traceback (most recent call last):
  File "site-packages\calibre\utils\recycle_bin.py", line 144, in delete_tree
  File "site-packages\calibre\utils\recycle_bin.py", line 45, in recycler_main
  File "site-packages\calibre\utils\recycle_bin.py", line 85, in recycle
  File "site-packages\calibre\utils\recycle_bin.py", line 31, in recycle_path
  File "site-packages\calibre\utils\recycle_bin.py", line 70, in delegate_recycle
OSError: Failed to perform delete operation
RuntimeError: recycler failed to recycle: u'E:\\Calibre Portable\\Calibre Library deleted facmjz\\B07Y8HKVGJ EBOK (7)'
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xde,SK\xc8\xe3\tt\x93\xc2\xba\xb7\xba\xde\xfb\x1e\xbd\xff\xb0\xb8@W\x10\x19\x1c\x85aA\x1eAj\xd1', 'C:\\Users\\daryl\\Documents\\My Kindle Content\\B073XVHCCT_EBOK\\B073XVHCCT_EBOK.azw']
DeDRM v6.7.0: Trying to decrypt B073XVHCCT_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.7.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\daryl\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\daryl\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '907912871' and UserName '646172796c'
DeDRM v6.7.0: Found 1 new key
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 321, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B073XVHCCT EBOK to db in: 1.1
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
Add the KFX Input plugin.

**Comment by Barstuck** [comment]
Ah, that step wasn't in the readme. 

Thanks... works now.
