### ISSUE TITLE
DeDRM 6.7.0 plugin not working in Caliber 4.14.0 in Win10

### ISSUE THREAD

**Issue by ouver12** [apprenticeharper/DeDRM_tools#1081]
calibre Debug log
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.45] splash screen shown
[0.45] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
[2.00] main UI initialized...
[2.00] Hiding splash screen
[80.11] splash screen hidden
[80.11] Started up in 80.11 seconds with 1199 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x85$\r\xce\xae\xbff\x0b\x16u\x13$\xd6\xdf\xed\x88\xa7"\x15[\xd1\xa0\xb2\x9c\x90\x8d\x82=M}\xeaF', 'S:\\Downloads\\The Anarchy.epub']
DeDRM v6.7.0: Trying to decrypt The Anarchy.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: The Anarchy.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Trying Encryption key default_key
Could not decrypt tmzqf2.epub. Wrong key
DeDRM v6.7.0: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Anarchy to db in: 1.2
Added 1 books in 2.0 seconds
Worker Launch took: 0.125

**Comment by ElleKayEm** [comment]
Is ADE 2.0.1 authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by ouver12** [comment]
Hi,

 

I don’t know what an Adobe ID is but to work around another issue, I’ve had to install ADE on a laptop and bring the .epub over to my main machine that has Caliber. The version of ADE installed on my laptop is 4.5.

 

Cheers

 

/eric

**Comment by ElleKayEm** [comment]
When you first installed ADE, it should have asked you to authorize the computer by creating or signing in with an Adobe ID.  If you don't do that, books get locked to that installation of ADE.  Check under the Help menu in ADE for Authorization Information.  If it isn't authorized, I don't know if you'll be able to remove the DRM.

In order for DeDRM to retrieve the key needed to unlock your book for the first time, ADE and calibre need to be on the same machine and user.  If you install calibre and DeDRM on your laptop and successfully remove DRM from a book, you can export the saved key from that installation of calibre/DeDRM and import it into calibre/DeDRM on your main machine.

ADE 2.0.1 only uses the type of Adobe DRM that these tools can remove.  Later versions of ADE can handle both the older DRM and a newer hardened DRM which these tools can't remove.  If a book can be opened with ADE 2.0.1 authorized with your Adobe ID, then the DRM can be removed.

**Comment by ouver12** [comment]
OK great, many thanks for clarifying this.

 

Cheers

 

/eric
