### ISSUE TITLE
DeDRM not working 

### ISSUE THREAD

**Issue by moaholiveira** [apprenticeharper/DeDRM_tools#1082]
calibre Log de Debug
calibre 4.14  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Barnes & Noble (1, 2, 15) && Generate Cover (1, 5, 22) && Kindle hi-res covers (0, 4, 0) && APNX Generator (1, 1, 0) && Obok DeDRM (6, 7, 0) && Skoob Books (1, 4, 0) && Prettify Cover (1, 0, 6) && Skoob Sync (0, 3, 4) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.14  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && Barnes & Noble (1, 2, 15) && Generate Cover (1, 5, 22) && Kindle hi-res covers (0, 4, 0) && APNX Generator (1, 1, 0) && Obok DeDRM (6, 7, 0) && Skoob Books (1, 4, 0) && Prettify Cover (1, 0, 6) && Skoob Sync (0, 3, 4) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 102.453781513 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.47] splash screen shown
[1.47] Initializing db...
[1.50] db initialized
[1.50] Constructing main UI...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 157, in __init__
  File "site-packages\calibre\gui2\ui.py", line 171, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 613, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.apnx_generator.apnxaction", line 14, in <module>
ImportError: No module named PyQt4.Qt
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[5.05] main UI initialized...
[5.05] Hiding splash screen
[11.97] splash screen hidden
[11.97] Started up in 11.97 seconds with 6 books
Worker Launch took: 0.324000120163
Job: 0 Converter livro 1 de 1 (Um estudo em Charlotte: Você nunca viu Watson e Holmes desse jeito antes (Charlotte Holmes Livro 1)) finished
Converter livro 1 de 1 (Um estudo em Charlotte: Você nunca viu Watson e Holmes desse jeito antes (Charlotte Holmes Livro 1))
	D:\Arquivos de programas\Calibre\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\MOAH~1.DES\\AppData\\Local\\Temp\\calibre_bqytg7\\u5e_mg.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\MOAH~1.DES\\AppData\\Local\\Temp\\calibre_bqytg7\\aaz1g9.opf'
	  verbose: 2
	  output_profile: u'kindle_pw3'
	Resolved conversion options
	calibre version: 4.14.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\MOAH~1.DES\\AppData\\Local\\Temp\\calibre_bqytg7\\u5e_mg.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x052742F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x052746F0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\MOAH~1.DES\\AppData\\Local\\Temp\\calibre_bqytg7\\aaz1g9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\MOAH~1.DES\AppData\Local\Temp\calibre_bqytg7\a6e_vi.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Um estudo em Charlotte: Você nunca viu Watson e Holmes desse jeito antes (Charlotte Holmes Livro 1) (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Um estudo em Charlotte: Você nunca viu Watson e Holmes desse jeito antes (Charlotte Holmes Livro 1)

Ebook from the website for "download & transfer via USB".

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre, not during conversion.  Do you have the serial number entered for your E-ink Kindle?

**Comment by moaholiveira** [comment]
Yep, i put serial number. But I solved the problem using an old version of DeDRM.

**Comment by ElleKayEm** [comment]
Current version 6.7 of DeDRM works.  Or did you mean an older version of Kindle for PC?

**Comment by moaholiveira** [comment]
Version 6.7 of DeDRM does not work, I tested it here.

**Comment by ElleKayEm** [comment]
Working fine for me and many others.  Post an import log if you us to look at it.
