### ISSUE TITLE
Obok no longer available under Fedora 32

### ISSUE THREAD

**Issue by madhatter0** [apprenticeharper/DeDRM_tools#1084]
Obok no longer launching since upgrade from Fedora 30 to Fedora 32.

```
[madhatta@risby kobo]$ calibre 
Failed to initialize plugin: '/home/madhatta/.config/calibre/plugins/KoboTouchExtended.zip'
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/ui.py", line 156, in __init__
    ac = self.init_iaction(action)
  File "/usr/lib64/calibre/calibre/gui2/ui.py", line 170, in init_iaction
    ac = action.load_actual_plugin(self)
  File "/usr/lib64/calibre/calibre/customize/__init__.py", line 613, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
ModuleNotFoundError: No module named 'StringIO'
```

**Comment by ElleKayEm** [comment]
I'm guessing it's because Obok probably needs to updated to work with Python 3.

**Comment by ElleKayEm** [comment]
No idea myself.  Hopefully someone else will chime in.

**Comment by madhatter0** [comment]
This seems to be covered already, by https://github.com/apprenticeharper/DeDRM_tools/issues/979 .

**Comment by madhatter0** [comment]
Thanks to norbusan and lalmeras _inter alia_ there is now a working python3-friendly Obok over in https://github.com/apprenticeharper/DeDRM_tools/issues/979 , so I'm closing this ticket.
