### ISSUE TITLE
Calibre Error: InvalidPlugin

### ISSUE THREAD

**Issue by erithacus2020** [apprenticeharper/DeDRM_tools#1086]
calibre, version 4.14.0
FEHLER: Unbehandelter Ausnahmefehler: <b>InvalidPlugin</b>:The plugin in u'D:\\Programme\\Calibre Portable\\DeDRM_tools_6.7.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.14 Portable embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.16+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: de
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'D:\\Programme\\Calibre Portable\\DeDRM_tools_6.7.0.zip' is invalid. It does not contain a top-level __init__.py file

What can I Do?

**Comment by ElleKayEm** [comment]
Did you mean to close this?  If not, unzip DeDRM_tools_6.7.0.zip and load DeDRM_Plugin.zip into calibre.
