### ISSUE TITLE
Unable to remove DRM from kindle paperwhite .kfx file

### ISSUE THREAD

**Issue by vinicius-affonso** [apprenticeharper/DeDRM_tools#1087]
calibre Debug log
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
calibre 4.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 1) && KFX Output (1, 41, 1) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[2.06] main UI initialized...
[2.06] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'D')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090G105817600RM&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=12)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090g105817600rm&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.1 USBMS: scan from root False F:\documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    0.4 USBMS: count found in cache: 171, count of files in metadata: 171, need_sync: False
DEBUG:    0.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 171
DeviceJob: set_books_in_library finished: time= 0.0120000839233
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
[38.64] splash screen hidden
[38.64] Started up in 38.64 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing D:/Documentos/e-books/GestÃ£o da mudanÃ§a e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\Vinicius\AppData\Local\Temp\calibre_ywkj9w\kprez5.kfx-zip
DeDRM v6.6.2: Trying to decrypt kprez5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: kprez5
Found 1 keys to try after 0.1 seconds
DeDRM v6.6.2: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Vinicius\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\Vinicius\AppData\Local\Temp\calibre_ywkj9w\kprez5.kfx-zip
Processing container: GestÃ£o da mudanÃ§a e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container GestÃ£o da mudanÃ§a e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Vinicius\AppData\Local\Temp\calibre_ywkj9w\uutjvk_add_books\0\GestÃ£o da mudanÃ§a e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 132, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Gestão da mudança e cultura organizacional (FGV Management) (Portuguese Edition) B01DWE9EMK to db in: 2.1
Added 1 books in 2.9 seconds
Worker Launch took: 0.273000001907
Job: 3 Convert book 1 of 1 (Gestão da mudança e cultura organizacional (FGV Management) (Portuguese Edition) B01DWE9EMK) finished
Convert book 1 of 1 (Gestão da mudança e cultura organizacional (FGV Management) (Portuguese Edition) B01DWE9EMK)
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\Vinicius\\AppData\\Local\\Temp\\calibre_ywkj9w\\rpzqzk.opf'
	  verbose: 2
	  output_profile: u'kindle_pw3'
	Resolved conversion options
	calibre version: 4.14.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000015EC379D6C8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000015EC3790F08>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Vinicius\\AppData\\Local\\Temp\\calibre_ywkj9w\\rpzqzk.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Vinicius\AppData\Local\Temp\calibre_ywkj9w\zxfiye.kfx-zip
	Software versions: KFX Input 1.31.0, calibre 4.14 [64bit], Windows-10-10.0.18362-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Vinicius\AppData\Local\Temp\calibre_ywkj9w\zxfiye.kfx-zip
	Processing container: Gestão da mudança e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container Gestão da mudança e cultura organizacional (FGV Management) (Portuguese Edition)_B01DWE9EMK.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
You will need to get the book from the website for "download & transfer via USB."  Or install Kindle for PC version 1.24 or earlier on this machine and download a copy of the book that way.

**Comment by armaan115** [comment]
I mean this workaround does work but should we be expecting a fix for this?

**Comment by armaan115** [comment]
Also, it took me some time to find out where the "download and transfer via USB feature" was so if **you* are looking for it, I'm leaving the instructions below

1. Go to www.amazon.com, click on your account, go to "Manage content and devices", 
2. Then find the book you want 
3 .Click on the the three dots next to it and hit "download and transfer via USB feature."

**Comment by ElleKayEm** [comment]
Eventually someone will probably figure it out, share a solution, and then these tools will get updated.  Especially if workarounds get more difficult.

**Comment by Losses** [comment]
@armaan115 
![image](https://user-images.githubusercontent.com/1384036/81881173-08ad7180-95c2-11ea-92e3-aa70cfdcae94.png)
Errrrr.... it's not there...

**Comment by j-howell** [comment]
> Errrrr.... it's not there...

Books in the more recently supported languages of Traditional Chinese and Arabic are only available in KFX format and cannot be sideloaded via USB.

**Comment by Losses** [comment]
> > Errrrr.... it's not there...
> 
> Books in the more recently supported languages of Traditional Chinese and Arabic are only available in KFX format and cannot be sideloaded via USB.

Oops....
