### ISSUE TITLE
It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by ajfra** [apprenticeharper/DeDRM_tools#109]
calibre, version 2.57.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Angelo\\Documents\\My Software\\Calibre\\DeDRM_tools_6.4.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.57.1 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: K4PC, K4Mac, Kindle Mobi and Topaz DeDRM && KindleUnpack - The Plugin
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 415, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 55, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 188, in load
  File "site-packages\calibre\customize\zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Angelo\\Documents\\My Software\\Calibre\\DeDRM_tools_6.4.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You were trying to load the whole archive.  Unzip it and look inside the DRM calibre plugin folder.

**Comment by ajfra** [comment]
Silly me!
Thank you very much: it is now working like a charm.
