### ISSUE TITLE
DeDRM not working on AZW files downloaded for transfer via USB

### ISSUE THREAD

**Issue by cgstadler** [apprenticeharper/DeDRM_tools#1092]
Mac OSX
Paperwhite Kindle

**Observed behavior:**
1. download AZW3 file from Amazon via "transfer via USB"
2. add to Calibre w latest DeDRM plugin installed
3. attempt to open view in Calibre, or convert file: DRM in place
4. file opens fine in Kindle for Mac

**Debug log:** 

```
calibre 4.15  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.79] main UI initialized...
[0.79] Hiding splash screen
[0.95] splash screen hidden
[0.95] Started up in 0.95 seconds with 5 books
DeDRM v6.7.0: Trying to decrypt The Body in Question.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Body in Question
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Body in Question to db in: 0.0
Added 1 books in 0.5 seconds
```

**Comment by ElleKayEm** [comment]
Make sure you have your Paperwhite Kindle's serial number entered into the DeDRM plugin's customization.

**Comment by cgstadler** [comment]
Thank you for tthe quick reply. 

1. I went to Amazon and copied my PW's serial from the list of my Amazon devices
2. I confirmed it is already listed ([screenshot](https://www.dropbox.com/s/6p7tdm8sihi8v9k/Screenshot%202020-05-13%2008.50.32.jpg?dl=0))

**Comment by ElleKayEm** [comment]
Then make sure that's the device you chose when downloading from the website.

**Comment by cgstadler** [comment]
That fixed it! When I was downloading from Amazon, I was choosing the incorrect device. 

Thanks again for your help.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
