### ISSUE TITLE
DeDRM 6.7.0 Not Working for Deseret Bookshelf e-books

### ISSUE THREAD

**Issue by TDC2** [apprenticeharper/DeDRM_tools#1100]
Hi, 

I'm trying to add a book to my Calibre library but after it is added the book is unreadable.  I have added other volumes of this series in the past with no issues.  By the way, I purchased this ebook (EPUB) from Deseret Book.  Below is the Calibre debug log.

calibre Debug log
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && EpubMerge (2, 9, 0) && KePub Metadata Reader (3, 2, 7) && KePub Metadata Writer (3, 2, 7) && KePub Input (3, 2, 7) && KindleUnpack - The Plugin (0, 82, 1)
calibre 4.16 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0) && EpubMerge (2, 9, 0) && KePub Metadata Reader (3, 2, 7) && KePub Metadata Writer (3, 2, 7) && KePub Input (3, 2, 7) && KindleUnpack - The Plugin (0, 82, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164557 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
EpubMerge: DEBUG: 2020-05-18 14:21:02,578: calibre_plugins.epubmerge.epubmerge_plugin(157): macmenuhack file_path:C:\Users\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.28] main UI initialized...
[2.28] Hiding splash screen
[35.97] splash screen hidden
[35.97] Started up in 35.97 seconds with 89 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['%\x88\x03\x89\x1f \xac\x94\x18\xc1*$!\xf7*_\xe5|O\xe8\x0ea\xf8\xe99\xda\x8b_\xb8\xbf\xcfk', 'E:\\eBook Testing\\Deseret Book\\The Joseph Smith Papers - Documents Vol 9\\Joseph Smith Papers - Documents Volume 9.epub']
DeDRM v6.7.0: Trying to decrypt Joseph Smith Papers - Documents Volume 9.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: â€œJoseph Smith Papers - Documents Volume 9.epubâ€ is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Couldn't decrypt after 1.0 seconds. DRM free perhaps?
Added The Joseph Smith Papers: Documents, Volume 9: December 1841–April 1842 to db in: 0.2
Added 1 books in 2.8 seconds

My computer:
HP Pavillion dv7
Intel Core I7 processor
Radeon discrete graphics card

Any help would be appreciated.

Thanks!!

**Comment by ElleKayEm** [comment]
These tools handle Adobe DRM and Barnes & Nobles DRM.

**Comment by TDC2** [comment]
Are there any other DRM tools I could try?

**Comment by ElleKayEm** [comment]
Not that I'm aware of.

**Comment by TDC2** [comment]
Thanks for replying ElleKayEm!!

**Comment by DB99** [comment]
I am a fellow user, not a member of this project, but would like to add that Deseret Books is yet another of those vendors who wish to confine readers to either an IOS or Android application, or a web based viewer.  Their site specifically indicates this.  Many of these sites produce books in epub format but use either their own proprietary DRM or licence a more obscure DRM system from other companies.  There is little chance that these tools or any other dedrm programs will be able to remove this type of DRM, simply because it is not widely enough used.  I strongly suggest avoiding the use of these types of bookshops.

**Comment by TDC2** [comment]
Thanks for the reply DB99!  I agree with your conclusion.  Unfortunately, the prices for the particular ebooks sold by Deseret Book are usually much higher with Amazon Kindle, Kobo and other ebook retailers.
