### ISSUE TITLE
Error importing Adobe Editions to Calibre 4.17

### ISSUE THREAD

**Issue by RocDoc1** [apprenticeharper/DeDRM_tools#1104]
This book was bought from a digital libraary company. It has worked in Adobe Digital app on my phone, but I want to import to Calibre for more flexibility. 
Error on import. Book is in DRM format....
Debug log follows.
And help would be much appreciated.

calibre Debug log
calibre 4.17  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.17  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
[2.06] main UI initialized...
[2.06] Hiding splash screen
[11.83] splash screen hidden
[11.83] Started up in 11.83 seconds with 2965 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['%\xcc\xe1\xb1\x13\xa0\xb8i\x1b\x0f\xe4\xf8\xb0f\xaf\xc0\xcc\xa3\x02\xc7+\x17\\,1X&\xba\x01\xb60I', 'C:\\Users\\RocDoc\\Downloads\\Emulation Ritual.epub']
DeDRM v6.7.0: Trying to decrypt Emulation Ritual.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Emulation Ritual.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
ADEPTError: Adobe Digital Editions not activated
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Emulation Ritual to db in: 0.5
Added 1 books in 1.1 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x06055D90>> ignored
Worker Launch took: 0.12099981308

**Comment by ElleKayEm** [comment]
You need Adobe Digital Editions 2.0.1 authorized with your Adobe ID on the same machine and user as calibre with DeDRM.  At least until DeDRM has been able to retrieve the key.  Then as long as the app on your phone is authorized with the same Adobe ID (and the ebookstore isn't using the newer hardened Adobe DRM), its books should unlock with that key too.
