### ISSUE TITLE
Caliber is not Converting my File

### ISSUE THREAD

**Issue by Edwanlima** [apprenticeharper/DeDRM_tools#1107]
Here is the message:
calibre, version 4.13.0 (win32, embedded-python: True)
Erro ao converter: Falha: Converter livro 1 de 1 (Scrum - Um Guia de Bolso: Um companheiro de viagem inteligente)

Converter livro 1 de 1 (Scrum - Um Guia de Bolso: Um companheiro de viagem inteligente)
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  pdf_serif_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_nd1zbf\\8p0b87.jpeg'
  read_metadata_from_opf: u'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_nd1zbf\\biau3w.opf'
  verbose: 2
  output_profile: u'generic_eink'
  pdf_sans_family: u'MS Shell Dlg 2'
Resolved conversion options
calibre version: 4.13.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_nd1zbf\\8p0b87.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000203E8DB9908>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000203E8DC7548>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_nd1zbf\\biau3w.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\edwan\AppData\Local\Temp\calibre_nd1zbf\3k5fgn.kfx-zip
Software versions: KFX Input 1.31.0, calibre 4.13 [64bit], Windows-10-10.0.18362-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\edwan\AppData\Local\Temp\calibre_nd1zbf\3k5fgn.kfx-zip
Processing container: B07TDN99LX_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07TDN99LX_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book, not during conversion.  Here's how to get a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Edwanlima** [comment]
Tks, Now here´s the correct log:
calibre Log de Debug
calibre 4.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 0) && KFX Output (1, 41, 0)
calibre 4.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 31, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 31, 0) && KFX metadata reader (from KFX Input) (1, 31, 0) && KFX Input (1, 31, 0) && Set KFX metadata (from KFX Output) (1, 41, 0) && KFX Output (1, 41, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.50] main UI initialized...
[1.50] Hiding splash screen
[17.11] splash screen hidden
[17.11] Started up in 17.11 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x02\x02\x85\xa6\xcftQ\xc3\x8f5\x12\x82a\x93\x16\x16\xed\xdf\nB\xb1\rh_\xfc\xf3\x86q\x90^\xa3\xe9', 'C:\\Users\\edwan\\OneDrive\\Documents\\My Kindle Content\\B07TDN99LX_EBOK\\B07TDN99LX_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.31.0: Importing C:\Users\edwan\OneDrive\Documents\My Kindle Content\B07TDN99LX_EBOK\B07TDN99LX_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as C:\Users\edwan\AppData\Local\Temp\calibre_3fxzvc\8ko_cd.kfx-zip
DeDRM v6.7.0: Trying to decrypt 8ko_cd.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 8ko_cd
Got DSN key from database default_key
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.13598446-5227-4ad4-9dfe-0589f4f52271.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.7.0: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\edwan\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\edwan\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1250582550' and UserName '656477616e'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: 8ko_cd
Got DSN key from database default_key_1
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.13598446-5227-4ad4-9dfe-0589f4f52271.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.7.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.31.0: Packaging C:\Users\edwan\AppData\Local\Temp\calibre_3fxzvc\8ko_cd.kfx-zip
Processing container: B07TDN99LX_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07TDN99LX_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\edwan\AppData\Local\Temp\calibre_3fxzvc\t_ccdn_add_books\0\B07TDN99LX_EBOK.kfx-zip
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Scrum - Um Guia de Bolso: Um companheiro de viagem inteligente to db in: 2.3
Added 1 books in 4.8 seconds

**Comment by ElleKayEm** [comment]
From the log:

>DeDRM v6.7.0: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by Edwanlima** [comment]
Ok, tks. And are you thinking about a DeDRM versoin for Kindle Unlimited?

**Comment by ElleKayEm** [comment]
No.  As it says, these tools are for purchased books.
