### ISSUE TITLE
Zip Import Error

### ISSUE THREAD

**Issue by ZipperDipper** [apprenticeharper/DeDRM_tools#1112]
I was unable to install the De-DRM package using latest package and latest version of Calibre. I got the following error message:
calibre, version 4.15.0
ERROR: Unhandled exception: <b>ZipImportError</b>:bad local file header: C:\Program Files (x86)\Calibre2\\app\pylib.zip

Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 418, in check_for_add_to_toolbars
ZipImportError: bad local file header: C:\Program Files (x86)\Calibre2\\app\pylib.zip

**Comment by ElleKayEm** [comment]
Should work if you unzip DeDRM_tools_6.7.0.zip, and load DeDRM_plugin.zip.

**Comment by ZipperDipper** [comment]
I did that earlier, and it did not work - However, now it did work when I repeated this procedure. However, the process by which one could de-DRM KFX files appears to no longer work. I downloaded and installed Kindle-for-PC 1.17 which does not use KFX files (or so the instructions state)  https://www.mobileread.com/forums/showthread.php?t=283371  But when it downloaded the book, it downloaded several types of files none of which were of familiar form - Calibre tries to import an MD file from the My Kindle Content directory and could not convert it to any recognizable format.

**Comment by ElleKayEm** [comment]
If you're seeing an MD file, then Kindle for PC has auto-updated.  See the info in the post you linked to about preventing unwanted updates.
