### ISSUE TITLE
Unable to remove DRM from Adobe Digital Editions

### ISSUE THREAD

**Issue by Retr0-Bit** [apprenticeharper/DeDRM_tools#1115]
Mac OS: 10.15.5 
Caliber: Calibre 4.17
eBook from: Adobe Digital Editions 4.5.11 Windows

calibre Debug log
calibre 4.17  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.17  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.82] main UI initialized...
[0.82] Hiding splash screen
DeDRM v6.7.0: Trying to decrypt Space Invaders.epub
DeDRM v6.7.0: Verifying zip archive integrity
DeDRM v6.7.0: Space Invaders.epub is a secure Adobe Adept ePub
DeDRM v6.7.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.7.0: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 447, in adeptkeys
ADEPTError: Could not find ADE activation.dat file.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[20.81] splash screen hidden
[20.81] Started up in 20.81 seconds with 4 books
Added Space Invaders to db in: 0.0
Added 1 books in 0.5 seconds
Worker Launch took: 0.0741889476776

**Comment by ElleKayEm** [comment]
Is Adobe Digital Editions on the same machine and user as calibre with DeDRM? Is it authorized with your Adobe ID?
