### ISSUE TITLE
ZIP Import Error

### ISSUE THREAD

**Issue by osm-frasch** [apprenticeharper/DeDRM_tools#1116]
Hello, i get this error installing DeDRM Tools Version _6.7.0
later  i tried to install Version v6.6.3...i got a install error as well. 

I using:
openSUSE Tumbleweed 20200602
KDE-Plasma-Version: 5.18.5
KDE-Frameworks-Version: 5.70.0
Qt-Version: 5.15.0
Kernel-Version: 5.6.14-1-default
Art des Betriebssystems: 64-bit

Here is calibres output:

calibre, version 4.18.0
FEHLER: Unbehandelter Ausnahmefehler: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.18  embedded-python: False is64bit: True
Linux-5.6.14-1-default-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.6.14-1-default', '#1 SMP Wed May 20 08:32:48 UTC 2020 (b0ab48a)')
Python 3.8.3
Interface language: de
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib64/calibre/polyglot/builtins.py", line 113, in reload
    return importlib.reload(module)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Not compatible with Python 3 yet.

**Comment by osm-frasch** [comment]
whoops, sorry... I hadn't thought of that. Is there any vague idea when python 3 compatibility will be achieved?

Thanks & Cheers
Frank

**Comment by ElleKayEm** [comment]
It's being worked on.  There's another thread here somewhere.

**Comment by marook** [comment]
See #928 for more details.
