### ISSUE TITLE
I can't convert to pdf my ebook

### ISSUE THREAD

**Issue by Maver12** [apprenticeharper/DeDRM_tools#1117]
calibre Καταγραφή προβλημάτων
calibre 4.18 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: el
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 4.18 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: el
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 119.529411765 x 119.269565217
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[2.06] main UI initialized...
[2.06] Hiding splash screen
[10.77] splash screen hidden
[10.77] Started up in 10.77 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe1eT\xd2\xe2$\x8aMt\x86\x89l\xd1\x0b\xe28\x1b\xf9Zh\xd4\xf9\xf16\xce\xaf\xe3\x90\x95\xfc\xd0\x96', 'C:\\Users\\Asus - PC\\Documents\\My Kindle Content\\B083PN9XWJ_EBOK\\B083PN9XWJ_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing C:\Users\Asus - PC\Documents\My Kindle Content\B083PN9XWJ_EBOK\B083PN9XWJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ASUS-P~1\AppData\Local\Temp\calibre_mhwbhp\5pkwgq.kfx-zip
DeDRM v6.7.0: Trying to decrypt 5pkwgq.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 5pkwgq
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.37e9339f-3197-4f75-ac3f-7ede331376e4.voucher
DeDRM v6.7.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Asus - PC\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Asus - PC\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1163409392' and UserName '41737573202d205043'
DeDRM v6.7.0: Found 1 new key
Decrypting KFX-ZIP ebook: 5pkwgq
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.37e9339f-3197-4f75-ac3f-7ede331376e4.voucher
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.13.0: Packaging C:\Users\ASUS-P~1\AppData\Local\Temp\calibre_mhwbhp\5pkwgq.kfx-zip
Processing container: B083PN9XWJ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B083PN9XWJ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ASUS-P~1\AppData\Local\Temp\calibre_mhwbhp\qliahl_add_books\0\B083PN9XWJ_EBOK.kfx-zip
Import symbol table YJ_symbols version 10 max_id 777 exceeds known table size 770
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Applied Concepts in Vision Therapy (Ridgevue) to db in: 0.2
Added 1 books in 2.6 seconds

**Comment by ElleKayEm** [comment]
You'll need to use Kindle for PC 1.24 or earlier.  You might want to update the KFX Input plugin.
