### ISSUE TITLE
Error with DeDRM 6.7

### ISSUE THREAD

**Issue by ColinofRame** [apprenticeharper/DeDRM_tools#1123]
Previous versions of DeDRM have worked flawlessly. This gives error "This book has DRM. Cannot convert" when adding books to library.
Book was downloaded directly from my Amazon Kindle account. 'Black Summer (Washington Poe).azw3'
OS is Linux Mint 19.3 Tricia 64bit .
Debug shows out of space error.
/dev/sda1           203G  178G   15G  93% /
/dev/sdb2           220G  145G   63G  70% /usr
/dev/sdb1           220G   37G  172G  18% /home
tmpfs               786M   24K  786M   1% /run/user/1000

Books selected containing 10 items Free space 67.6GB

qt5ct: using qt5ct plugin
inotify_add_watch("/home/sue/.config/qt5ct") failed: "No space left on device"
qt5ct: D-Bus global menu: no
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
qt5ct: D-Bus system tray: no
calibre Debug log
calibre 3.21  embedded-python: False is64bit: True
Linux-5.0.0-32-generic-x86_64-with-LinuxMint-19.3-tricia Linux ('64bit', '')
('Linux', '5.0.0-32-generic', '#34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019')
Python 2.7.17
Linux: ('LinuxMint', '19.3', 'tricia')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
calibre 3.21  embedded-python: False is64bit: True
Linux-5.0.0-32-generic-x86_64-with-LinuxMint-19.3-tricia Linux ('64bit', '')
('Linux', '5.0.0-32-generic', '#34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019')
Python 2.7.17
Linux: ('LinuxMint', '19.3', 'tricia')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Google Books at version: 6
Loaded cached store plugin for: Project Gutenberg at version: 6
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.58] main UI initialized...
[0.58] Hiding splash screen
inotify_add_watch("/home/sue/Downloads/books") failed: "No space left on device"
DeDRM v6.7.0: Trying to decrypt Black Summer (Washington Poe).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Black Summer (Washington Poe)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.7.0: Running kindlekey.py under Wine
DeDRM v6.7.0: Command line: 'wine python.exe "/home/sue/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/sue/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.7.0: Found and decrypted 0 key files
DeDRM v6.7.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Found device nodes: /dev/sdc None None
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= TOLINO oncard= None
DEBUG:    0.0 USBMS: dirs are: /media/sue/tolino/ 
DEBUG:    0.0 USBMS: scan from root False /media/sue/tolino/
DEBUG:    0.1 USBMS: count found in cache: 127, count of files in metadata: 127, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= TOLINO oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= TOLINO oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 127
DeviceJob: set_books_in_library finished: time= 0.00646305084229
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
[7.84] splash screen hidden
[7.85] Started up in 7.85 seconds with 268 books
Added Black Summer (Washington Poe) to db in: 0.1
Added 1 books in 0.8 seconds
Worker Launch took: 0.118854045868
Job: 4 Convert book 1 of 1 (Black Summer (Washington Poe)) finished
Convert book 1 of 1 (Black Summer (Washington Poe))
	Conversion options changed from defaults:
	  cover: u'/tmp/calibre_3.21.0_tmp_OikVGD/WmjCWv.jpeg'
	  output_profile: 'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'/tmp/calibre_3.21.0_tmp_OikVGD/_KvLmm.opf'
	Resolved conversion options
	calibre version: 3.21.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/tmp/calibre_3.21.0_tmp_OikVGD/WmjCWv.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7fa1331c5910>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7fa133062150>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/tmp/calibre_3.21.0_tmp_OikVGD/_KvLmm.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_3.21.0_tmp_OikVGD/hkagd5.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 20, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 195, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	    override_input_metadata=True)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1088, in run
	    accelerators, tdir)
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
	    log, accelerators)
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	    opf = os.path.abspath(mr())
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	    self.mobi6_reader.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: Black Summer (Washington Poe)

**Comment by ElleKayEm** [comment]
Doesn't look like you have entered your E-ink Kindle serial number into the DeDRM plugin customization.

**Comment by cpiber** [comment]
> DeDRM v6.7.0: Command line: 'wine python.exe "/home/sue/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/sue/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
> wine: cannot find L"C:\windows\system32\python.exe"
You don't have python in your wine install, to it can't extract the keys. https://github.com/apprenticeharper/DeDRM_tools/issues/1222#issuecomment-686660410

**Comment by ElleKayEm** [comment]
The book isn't from Kindle for PC.  So in this case, a serial number is needed (provided that's an E-ink Kindle and not a Fire.)

**Comment by cpiber** [comment]
It's trying to run `kindlekey.py` under wine and complaining that there is no python. Though setting the key properly should also work, as you say

**Comment by ElleKayEm** [comment]
It still tries to find a Kindle for PC key since it's an Amazon book and there wasn't any key already entered.  But that wouldn't work for this book anyway.
