### ISSUE TITLE
DeDRM is failing

### ISSUE THREAD

**Issue by Snrico** [apprenticeharper/DeDRM_tools#1128]
calibre Debug log
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0)
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 81.0000012165 x 81.0000012165
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.37] splash screen shown
[0.37] Initializing db...
[0.37] db initialized
[0.37] Constructing main UI...
[1.13] main UI initialized...
[1.13] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.32.0: Importing /Users/stephenrico/Library/Application Support/Kindle/My Kindle Content/B07R7F1MKP_EBOK/B07R7F1MKP_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 30 file(s) as /var/folders/6y/rdkrt58s3qs9t8wbqbnyn9zr0000gn/C/calibre_4.19.0_tmp_D14M2y/jcgRMN.kfx-zip
DeDRM v6.8.0: Trying to decrypt jcgRMN.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: jcgRMN
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7b0f927c-ec40-4e79-9395-a52a39efac57.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/stephenrico/Library/Application Support/Kindle/storage/.kinf2018
[4.01] splash screen hidden
[4.01] Started up in 4.01 seconds with 0 books
Decrypted key file using IDString '01fbc5fe6e7a' and UserName 'stephenrico'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: jcgRMN
Got DSN key from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7b0f927c-ec40-4e79-9395-a52a39efac57.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.32.0: Packaging /var/folders/6y/rdkrt58s3qs9t8wbqbnyn9zr0000gn/C/calibre_4.19.0_tmp_D14M2y/jcgRMN.kfx-zip
Processing container: B07R7F1MKP_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 182, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 289, in get_container
KFXDRMError: Book container B07R7F1MKP_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/6y/rdkrt58s3qs9t8wbqbnyn9zr0000gn/C/calibre_4.19.0_tmp_D14M2y/iMC28G_add_books/0/B07R7F1MKP_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
The book was downloaded with the current installation of Kindle for Mac on the same machine and user as calibre with DeDRM?

**Comment by Snrico** [comment]
Yes the book was downloaded with Kindle for mac version 1.28 on the same user profile that calibre with DeDRM is installed. 
Any attempt to use an older version of Kindle or shutting of the KFX function with the command line results in the app not allowing me to download the book.

**Comment by ElleKayEm** [comment]
Is this a purchased book?  It won't work with rented  books.

**Comment by Snrico** [comment]
See above comment. It is purchased.

**Comment by ElleKayEm** [comment]
Hmm, this looks like it may be a book that the tools still can't decrypt.  Are you able to DeDRM other Kindle books?

**Comment by Snrico** [comment]
Yes other purchased books that were downloaded before today have been able to decrypt and convert perfectly. Refer to this link: [Mobileread](https://www.mobileread.com/forums/showthread.php?t=283371&page=56) 
I believe it answers to why this is occurring. Amazon seems to have found a way to stop the latest release from working already.

**Comment by ElleKayEm** [comment]
Ugh.  Were any others that worked before today also only available in KFX format?

**Comment by Snrico** [comment]
Yes, most of my library is the same way. They seem to have all updated to KFX-ZIP :(

**Comment by Snrico** [comment]
Correction for anyone else reading, sorry I am learning as I go. 
A quote from mobilereads by jhowell:
![Screen Shot 2020-06-19 at 4 41 00 PM](https://user-images.githubusercontent.com/67172608/85186058-59ca1880-b286-11ea-9d89-5df6a7255f2c.png)
[post number 831](url)

**Comment by ElleKayEm** [comment]
Sounds like certain publishers are really pushing Amazon to keep their books secure.  You can check a product page to see what apps and devices a book is available for.  If it says that it requires the latest version of Kindle for PC, then you'll know you won't be able to access it in the older formats.

**Comment by DB99** [comment]
Whatever Amazon has done it is very interesting.  It appears that with K4PC 1.28 (latest) the tools no longer work.  I tested yesterday using 1.28.0.  So far as I can see there was no update.  I downgraded to Kindle for PC 1.24.3 (51068) and the tools now work as intended and convert downloaded books to kfx.  So it seems all versions of K4PC that support kfx up to and including 1.24.3 (51068) support kfx drm decryption with Apprentice Sakura's change.  Assuming no sneaky pushed update somewhere after this time Amazon has updated both K4PC and e-ink Kindle firmware to include use of an alternate drm scheme.  It seems they were all prepared and all they had to do when the latest tools were released was make an adjustment on their servers.

**Comment by ElleKayEm** [comment]
KFX decryption was already possible on Kindle for PC/Mac 1.19 through 1.24 before Apprentice Sakuya's update.  DeDRM 6.8 should still help Mac users since they can shut off KFX downloads on later versions Kindle for Mac.  It should make new installations on Catalina possible.  Of course, everyone's still out-of-luck with books which are only available in KFX and require the latest versions of Kindle for PC/Mac to download.

**Comment by DB99** [comment]
Thanks for correcting me on this.  It will be interesting to test with 1.25.  I wonder if Amazon was implementing alternative DRM from the implementation of the new key and format.

**Comment by ElleKayEm** [comment]
It seems like there was both a new key (.kinf2018) and specifically for KFX format a different encryption  starting with 1.25.  And whatever change Amazon made in the past day or so broke the KFX decryption that DeDRM 6.8 allowed on 1.25 plus.  But I'm guessing it didn't break the ability to get the new key.  So I'm eager to hear if someone with a completely new installation of Kindle for Mac on Catalina (which requires K4Mac 1.25 or later) can still download and decrypt the older formats.  Before you needed to have updated over an existing working setup of Mojave, K4Mac, and calibre with DeDRM.

**Comment by apprenticesakuya** [comment]
If you haven't already, please try using [version 1.26 ](https://s3.amazonaws.com/kindleformac/55093/KindleForMac-55093.dmg) to download the book.

**Comment by not-here373** [comment]
On a new Catalina install, new user account, wiping files with AppCleaner between Kindle versions:

New Calibre install, DeDRM 6.8.0, KFX plugin installed

1.26.1  KindleForMac-55093.dmg
With KFX plugin can read into calibre, but viewer goes to import->already in library dialogue.  Can convert to epub and read.
On disabling KFX downloads and not opening in Kindle, can read into calibre as mobi or azw3.  Kindle reliably crashes on close with KFX file set -x.


1.28  KindleForMac-57029.dmg
Download and open in kindle (KFX) - get metadata but text still drm: viewer does nothing, convert says ‘drm’.
Same for download without open
Disable KFX download, download but do not open in kindle, now **can** read into calibre as azw3 and read.  Kindle reliably crashes on close with KFX file set -x.

On both versions frequently find preferences re-set, probably due to crashes.  (So automatic updates re-enabled)

**Comment by ElleKayEm** [comment]
Due a change Amazon did just after the 6.8 release, KFX format can only be DeDRMed on Kindle for PC/Mac 1.26 and earlier.  If you disable KFX downloads, then the older formats can be decrypted from the later versions of Kindle for Mac.  See this post:

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

As for the calibre ebook viewer, do you have it set to open KFX format?  Look under Preferences > Behavior.

**Comment by not-here373** [comment]
Thanks, was not aware of the preferences option for viewing KFX format or the post you linked to, I'm sure that would fix the issue with the reader.

This was just to report behaviour "with a completely new installation of Kindle for Mac on Catalina."  

So yes, as noted above I was able to download and decrypt the older formats without updating over any previous installation, on Catalina with a clean install of 1.28 (KindleForMac-57029.dmg).

**Comment by ElleKayEm** [comment]
Thanks for reporting on that...very good news!  No need to worry about not being able to use the 32-bit Kindle for Mac.

**Comment by Snrico** [comment]
@ElleKayEm Hi there, sorry for dropping off the face of the planet. So the book I tried downloading is in fact Pearson and is in fact requiring me to download the latest K4Mac in order to download the book. Ive been keeping up with everything going on at mobile reads but am wondering if I need to try again with this book and which option will work...(I believe its method 4 we are looking at here) 
thanks so much

**Comment by ElleKayEm** [comment]
@Snrico 
Have you tried downloading it with Kindle for Mac 1.26?  Link in apprenticesakuya's comment above.

**Comment by Snrico** [comment]
Yep, didnt work. 
![Screen Shot 2020-06-22 at 5 18 54 PM](https://user-images.githubusercontent.com/67172608/85347124-2fc36100-b4e7-11ea-9c27-9742b1050e2e.png)
I followed the steps for Mac 1.26 using [https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508](this post)

**Comment by ElleKayEm** [comment]
Please try it without disabling KFX downloads.

**Comment by Snrico** [comment]
@ElleKayEm That also did not work :)
![Screen Shot 2020-06-22 at 5 31 16 PM](https://user-images.githubusercontent.com/67172608/85347708-ea079800-b4e8-11ea-82be-19b4f68d092b.png)

**Comment by ElleKayEm** [comment]
Oh, well. Thanks for trying.
