### ISSUE TITLE
can't Dedrm book in calibre, error message

### ISSUE THREAD

**Issue by alias123banana** [apprenticeharper/DeDRM_tools#1132]
hello
no matter what I do, I cannot load a kindle (kindle for PC) book into caliber and the De DRM plug ins dont seem to work. no matter what I do I get an error message.
What am I doing wrong. I have a windows 10, brand new calibre and kindle downloads.

I have also tried everystep on my old windows computer and doesn't work.
here is the error message I am getting
![image](https://user-images.githubusercontent.com/67406492/85660656-e0fefe00-b683-11ea-88d3-f75e8e5321de.png)

**Comment by alias123banana** [comment]
![image](https://user-images.githubusercontent.com/67406492/85660798-0be95200-b684-11ea-9eed-820b99c70da9.png)

**Comment by alias123banana** [comment]
I have run calibre on debug mode to show the results:

calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.76] main UI initialized...
[1.76] Hiding splash screen
[7.72] splash screen hidden
[7.72] Started up in 7.72 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['%~@\xf3e\xf7\x14\xa8\xefP\xde\xad\x175\x9f5keU\x8c\x83h\x96\x11 \xbe\xc7\n\xc1\xa7UF', 'C:\\Users\\swell\\Documents\\My Kindle Content\\B01DK93WKW_EBOK\\B01DK93WKW_EBOK.azw']
DeDRM v6.8.0: Trying to decrypt B01DK93WKW_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\swell\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\swell\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2559598512' and UserName '7377656c6c696e65'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 7.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 7.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
Added B01DK93WKW EBOK to db in: 0.0
Added 1 books in 8.3 seconds
stdout+stderr from file dialog helper: ['', '']
Worker Launch took: 0.095999956131

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.24 or earlier.  Then either disable KFX format downloads or install the KFX Input plugin.  See this post:

https://www.mobileread.com/forums/showthread.php?t=283371
