### ISSUE TITLE
deDRM installs into 4.19.0 but book not deDRM'd

### ISSUE THREAD

**Issue by livtin** [apprenticeharper/DeDRM_tools#1136]
calibre Debug log
calibre 4.19  embedded-python: True is64bit: True
Linux-5.4.0-39-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-39-generic', '#43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && all recipes Recipe Reader (1, 0, 2) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Obok DeDRM (6, 7, 0)
calibre 4.19  embedded-python: True is64bit: True
Linux-5.4.0-39-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-39-generic', '#43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 32, 0) && all recipes Recipe Reader (1, 0, 2) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.13] splash screen shown
[0.13] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[2.06] main UI initialized...
[2.06] Hiding splash screen
[6.09] splash screen hidden
[6.09] Started up in 6.09 seconds with 134 books

Ignoring the node: sdc as could not read size from: /sys/devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host7/target7:0:0/7:0:0:0/block/sdc/size

Ignoring the node: sdc as could not read size from: /sys/devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host7/target7:0:0/7:0:0:0/block/sdc/size
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f955a069e10>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 812, in open
  File "site-packages/calibre/devices/usbms/device.py", line 565, in open_linux
DeviceError: Unable to detect the KINDLE2 disk drive. Either the device has already been ejected, or your kernel is exporting a deprecated version of SYSFS.

Connect to device failed, retrying in 5 seconds...

Ignoring the node: sdc as could not read size from: /sys/devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host7/target7:0:0/7:0:0:0/block/sdc/size

Ignoring the node: sdc as could not read size from: /sys/devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host7/target7:0:0/7:0:0:0/block/sdc/size
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f955a069e10>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 812, in open
  File "site-packages/calibre/devices/usbms/device.py", line 565, in open_linux
DeviceError: Unable to detect the KINDLE2 disk drive. Either the device has already been ejected, or your kernel is exporting a deprecated version of SYSFS.

Device connect failed again, giving up

Ignoring the node: sdc as could not read size from: /sys/devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1:1.0/host7/target7:0:0/7:0:0:0/block/sdc/size
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x7f955a069e10>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 812, in open
  File "site-packages/calibre/devices/usbms/device.py", line 560, in open_linux
  File "site-packages/calibre/devices/usbms/device.py", line 481, in find_device_nodes
DeviceError: Unable to detect the KINDLE2 disk drive.

Connect to device failed, retrying in 5 seconds...

Found device nodes: /dev/sdc1 None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /media/tina/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /media/tina/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 99, count of files in metadata: 99, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 99
DeviceJob: set_books_in_library finished: time= 0.0174829959869
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.

Found device nodes: /dev/sdc1 None None
Udisks mount call failed:
Traceback (most recent call last):
  File "site-packages/calibre/devices/usbms/device.py", line 547, in do_mount
  File "site-packages/calibre/devices/udisks.py", line 194, in mount
  File "site-packages/calibre/devices/udisks.py", line 135, in mount
  File "site-packages/calibre/devices/udisks.py", line 132, in device
ValueError: u'/dev/sdc1' not known to UDisks2

Found device nodes: /dev/sdc1 None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 3 Get device information started
DeviceJob: 3 Get device information done, calling callback
DeviceJob: 3 Get device information callback returned
Job: 4 Set library information started
DeviceJob: 4 Set library information done, calling callback
DeviceJob: 4 Set library information callback returned
Job: 5 Get list of books on device started
DEBUG:  327.6 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:  327.6 USBMS: dirs are: /media/tina/Kindle/ documents
DEBUG:  328.1 USBMS: scan from root False /media/tina/Kindle/documents
DEBUG:  328.1 USBMS: count found in cache: 99, count of files in metadata: 99, need_sync: False
DEBUG:  328.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:  328.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:  328.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 5 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 99
DeviceJob: set_books_in_library finished: time= 0.00931310653687
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 5 Get list of books on device callback returned
Job: 3 Get device information finished
No details available.
Job: 4 Set library information finished
No details available.
Job: 5 Get list of books on device finished
No details available.
Job: 6 View book on device started
DeviceJob: 6 View book on device done, calling callback
DeviceJob: 6 View book on device callback returned
Worker Launch took: 0.0912439823151
Job: 6 View book on device finished
No details available.

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book to calibre.  No book is imported in this log.
