### ISSUE TITLE
DRM 6.8 not working with Calibre 4.19?

### ISSUE THREAD

**Issue by Gourbs** [apprenticeharper/DeDRM_tools#1138]
calibre, version 4.19.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Stephen.Gourley\\Desktop\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.19 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Stephen.Gourley\\Desktop\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive.  Unzip DeDRM_tools_6.8.0.zip and just load DeDRM_Plugin.zip.

**Comment by sgweinst** [comment]
I am having a problem with it also. Any help would be appreciated.

Here's the debug log:
calibre Debug log
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.19  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.42] main UI initialized...
[1.42] Hiding splash screen
[5.64] splash screen hidden
[5.64] Started up in 5.64 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['b-k{I\xdeS\xf57\xc5"\xfd\x1c\x1b\x8f\x17O=\xe8\xb2\x1b\xbbE\x1f\x86N\x82\xf0\xc2\xf1rO', 'D:\\Books\\My Kindle Content\\B086Q6S1H4_EBOK\\B086Q6S1H4_EBOK.azw']
DeDRM v6.8.0: Trying to decrypt B086Q6S1H4_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\sgwei\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\sgwei\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '920172241' and UserName '7367776569'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 7.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 7.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B086Q6S1H4 EBOK to db in: 0.9
Added 1 books in 8.5 seconds

**Comment by ElleKayEm** [comment]
@sgweinst 

This book is KFX format.  See this post for ways to avoid or deal with it:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Gourbs** [comment]
That did it, thank you!

**Comment by ElleKayEm** [comment]
@Gourbs 
If you're all set, you can close the issue.

**Comment by sgweinst** [comment]
I tried a number of times. I finally just downloaded the older Kindle for PC and was able to do it.
Thank you

**Comment by ElleKayEm** [comment]
@sgweinst 
That's one of the suggested methods.

**Comment by Murari1008** [comment]
How to remove DRM from ADE 4.5 PDF?
Getting EBX_Handler error with DeDRM Plugins.

**Comment by ElleKayEm** [comment]
@Murari1008 
If it can't be opened with ADE 2.0.1 with the same Adobe ID, then DeDRM can't remove the DRM yet.  No idea if anyone is working on this.  Not many vendors have switched to exclusively use the hardened DRM.  Until it becomes more common, there's not a lot of motivation or even opportunity to look at it.
