### ISSUE TITLE
6.8.0 doesn't want to install in Calibre 4.19 on *ubuntu 20.04.  

### ISSUE THREAD

**Issue by mjtalarczyk** [apprenticeharper/DeDRM_tools#1139]
Calibre 4.19
Kubuntu 20.04
Python 3.8.2

Is this by design, or have I misconfigured?

Install log:

"calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-39-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-39-generic', '#43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020')
Python 3.8.2
Interface language: None
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax"

**Comment by ElleKayEm** [comment]
DeDRM isn't compatible with Python 3 yet.  For now, use the non-beta release of calibre which still has Python 2.

**Comment by mjtalarczyk** [comment]
Thanks for the quick response. I apologize for missing that point.
