### ISSUE TITLE
Failure to remove DRM

### ISSUE THREAD

**Issue by neuwirthe** [apprenticeharper/DeDRM_tools#1143]
iMac
Mojave 10.14.6
Calibre 4.19
Kindle 1.23.1

DeDRM plugin failed

```
calibre Debug log
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.40] db initialized
[0.40] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.13] main UI initialized...
[1.13] Hiding splash screen
objc[76623]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9cced3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11a2dcf50). One of the two will be used. Which one is undefined.
DeDRM v6.8.0: Trying to decrypt B088TTFTDR_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/neuwirth/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '0922063ab1e9' and UserName 'neuwirth'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
[10.26] splash screen hidden
[10.26] Started up in 10.26 seconds with 15 books
Added B088TTFTDR EBOK to db in: 0.0
Added 1 books in 0.7 seconds
```

With Kindle 1.28.0 the following happens:

```
calibre Debug log
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.19  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.03] main UI initialized...
[1.03] Hiding splash screen
objc[76894]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9cced3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x116d11f50). One of the two will be used. Which one is undefined.
DeDRM v6.8.0: Trying to decrypt B088TTFTDR_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/neuwirth/Library/Application Support/Kindle/storage/.kinf2018
Decrypted key file using IDString '0922063ab1e9' and UserName 'neuwirth'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
[3.06] splash screen hidden
[3.06] Started up in 3.06 seconds with 15 books
Added B088TTFTDR EBOK to db in: 0.0
Added 1 books in 1.1 seconds

```

**Comment by ElleKayEm** [comment]
Either disable KFX downloads or install the KFX Input plugin.  Method 2 or 4 here:

https://www.mobileread.com/forums/showthread.php?t=283371
