### ISSUE TITLE
Getting Syntax error while install the plugin in calibre

### ISSUE THREAD

**Issue by mujeebcpy** [apprenticeharper/DeDRM_tools#1145]
im using ubuntu 20.04 and calibre version 4.99.4
while i trying to install this plugin it gives an error
```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 167)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-39-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-39-generic', '#43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020')
Python 3.8.2
Interface language: None
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 167
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by ElleKayEm** [comment]
DeDRM is not compatible with Python 3 yet.  For now, use the non-beta release of calibre which still has Python 2.

**Comment by mujeebcpy** [comment]
okey, thanks for the quick reply
