### ISSUE TITLE
Issue in conversion kindle purchased book to pdf

### ISSUE THREAD

**Issue by davaguilar** [apprenticeharper/DeDRM_tools#1147]
Hey! I Tried to convert this book and it was not possible:

MacOS Catalina 10.15.15
calibre Registro de depuración
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.10] main UI initialized...
[1.10] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt Everything You Always Wanted to Know about - Eric Metaxas.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Everything You Always Wanted to Know about God (But Were Afraid to Ask)
Found 2 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.4 seconds
Found k4Mac kinf2018 file: /Users/davidaguilar/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
[7.71] splash screen hidden
[7.72] Started up in 7.72 seconds with 7 books
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 9.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire)?  Do you have its serial number entered correctly in the DeDRM plugin customization?

**Comment by davaguilar** [comment]
Hi! Yes too all; I double checked the serial number of my eInk Kindle; tried to convert again and failed. This is the log:

calibre, version 4.20.0 (darwin, embedded-python: True)
Error de conversión: Fallo: Convertido el libro 1 de 1 (Everything You Always Wanted to Know about God (But Were Afraid to Ask))

Convertido el libro 1 de 1 (Everything You Always Wanted to Know about God (But Were Afraid to Ask))
Conversion options changed from defaults:
  verbose: 2
  output_profile: u'tablet'
  cover: u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/f9Xh3H.jpeg'
  read_metadata_from_opf: u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/g3sNBa.opf'
Resolved conversion options
calibre version: 4.20.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/f9Xh3H.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x112227310>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x112227e50>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/g3sNBa.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/UMal5_.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly: Everything You Always Wanted to Know about God (But Were Afraid to Ask)
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Everything You Always Wanted to Know about God (But Were Afraid to Ask)

**Comment by ElleKayEm** [comment]
Try shortening that file name before adding it to calbre.

**Comment by davaguilar** [comment]
Tried shorter name but same results :(

Convertido el libro 1 de 1 (Everything You Always Wanted to Know)
Conversion options changed from defaults:
  verbose: 2
  output_profile: u'tablet'
  cover: u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/vZxslO.jpeg'
  read_metadata_from_opf: u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/K_3oQ7.opf'
Resolved conversion options
calibre version: 4.20.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/vZxslO.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11546e350>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x11546ee90>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/K_3oQ7.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/jg/mhqk1qhd6530m2kmx9g6q_bm0000gn/C/calibre_4.20.0_tmp_rsQmby/KbUoIn.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly: Everything You Always Wanted to Know about God (But Were Afraid to Ask)
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Everything You Always Wanted to Know about God (But Were Afraid to Ask)

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book, not during conversion.
