### ISSUE TITLE
Didn't remove DRM

### ISSUE THREAD

**Issue by xelas84** [apprenticeharper/DeDRM_tools#1148]
DeDRM 6.8.0
Wind 10
Application Kindle
WindowsError [Error 1155]

calibre Log di debug
calibre 4.20  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.20  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.12] main UI initialized...
[1.12] Hiding splash screen
[40.01] splash screen hidden
[40.01] Started up in 40.01 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['M\xb2\xd2\x83:\xd7W\xb6G\x08\x19\xdd\x8d\xb4k7\xc3\x92\x93r\x0c\xfe\r\x1a\x8f\x85*>$\x10\xb1y', 'C:\\Users\\Xelas\\Documents\\My Kindle Content\\B07P2GQX56_EBOK\\B07P2GQX56_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\Xelas\Documents\My Kindle Content\B07P2GQX56_EBOK\B07P2GQX56_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Xelas\AppData\Local\Temp\calibre_orojhs\w8pn4i.kfx-zip
DeDRM v6.8.0: Trying to decrypt w8pn4i.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: w8pn4i
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.2f1ccd22-b854-4f91-a9b2-46f155d05d34.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Xelas\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Xelas\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3023744148' and UserName '58656c6173'
DeDRM v6.8.0: Ultimately failed to decrypt after 6.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\Xelas\AppData\Local\Temp\calibre_orojhs\w8pn4i.kfx-zip
Processing container: B07P2GQX56_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B07P2GQX56_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Xelas\AppData\Local\Temp\calibre_orojhs\in5fdg_add_books\0\B07P2GQX56_EBOK.kfx-zip
Added L'indice di equilibrio: Come, cosa e quando mangi è più importante di quanto mangi (Italian Edition) to db in: 0.1
Added 1 books in 6.7 seconds
calibre 4.20  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\view.py", line 246, in view_triggered
  File "site-packages\calibre\gui2\actions\view.py", line 329, in _view_books
  File "site-packages\calibre\gui2\actions\view.py", line 281, in _view_calibre_books
  File "site-packages\calibre\gui2\actions\view.py", line 108, in view_format_by_id
  File "site-packages\calibre\gui2\actions\view.py", line 157, in _view_file
  File "site-packages\calibre\gui2\actions\view.py", line 147, in _launch_viewer
  File "site-packages\calibre\gui2\__init__.py", line 1286, in open_local_file
WindowsError: [Error 1155] Nessuna applicazione associata al file specificato per questa operazione: u"C:\\Users\\Xelas\\Biblioteca di calibre\\Iader Fabbri\\L'indice di equilibrio_ Come, cosa e (12)\\L'indice di equilibrio_ Come, c - Iader Fabbri.kfx-zip"

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.26 or earlier.

**Comment by xelas84** [comment]
I did it (Run Kindle 1.26) but it doesn't work


calibre Log di debug
calibre 4.20  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Obok DeDRM (6, 7, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.20  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Obok DeDRM (6, 7, 0) && Set KFX metadata (from KFX Output) (1, 40, 0) && KFX Output (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.20] main UI initialized...
[1.22] Hiding splash screen
[15.00] splash screen hidden
[15.00] Started up in 15.00 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["_\x8a]I\xc9'\x8eP8\x81\x04/\x14\xd1\xa0;\x9a\xd90\xba\x01\x9dj!\xe2\xbe\xeb\x91,\xa4U ", 'C:\\Users\\Xelas\\Documents\\My Kindle Content\\B07P2GQX56_EBOK\\B07P2GQX56_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\Xelas\Documents\My Kindle Content\B07P2GQX56_EBOK\B07P2GQX56_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Xelas\AppData\Local\Temp\calibre_hf2bya\ubjfvo.kfx-zip
DeDRM v6.8.0: Trying to decrypt ubjfvo.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: ubjfvo
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.2f1ccd22-b854-4f91-a9b2-46f155d05d34.voucher
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B07P2GQX56_EBOK.azw
Decryption succeeded after 0.1 seconds
DeDRM v6.8.0: Finished after 0.1 seconds
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\Xelas\AppData\Local\Temp\calibre_hf2bya\rfzzv8.kfx-zip
Processing container: B07P2GQX56_EBOK.azw
Processing container: CR!27BKT2XREH1Y18G9XEP6G1FZS256.azw.md
Processing container: CR!48FNJSN9V55A71Q35PND8GR7X6PR.azw.res
kfxgen version: 7.236.1.0
Features: CanonicalFormat-2, kfxgen.pidMapWithOffset-1, kfxgen.textBlock-1, max_id-786, reflow-style-2, yj_table-6, yj_table_viewer-1
Metadata: ASIN=B07P2GQX56, asset_id=CR!X5QSSSFB3N1Z78K5Y4W75F6GDM15, author="Fabbri, Iader", book_id=-2-OuPtPTdaeVeEhwr42bw0, cde_content_type=EBOK, content_id=B07P2GQX56, cover_image=800x976, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2019-02-26, language=it, override_kindle_font=False, publisher="MONDADORI LIBRI TRADE ELECTA", reading_orders=1, selection=enabled, title="L'indice di equilibrio: Come, cosa e quando mangi Ã¨ piÃ¹ importante di quanto mangi (Italian Edition)"
Package KFX (from KFX Input): Imported as C:\Users\Xelas\AppData\Local\Temp\calibre_hf2bya\zisihw.kfx
KFX metadata reader (from KFX Input) activated for C:\Users\Xelas\AppData\Local\Temp\calibre_hf2bya\qr8zbg_add_books\0\B07P2GQX56_EBOK.kfx
Added L'indice di equilibrio: Come, cosa e quando mangi è più importante di quanto mangi (Italian Edition) to db in: 0.1
Added 1 books in 2.0 seconds
