### ISSUE TITLE
Didn't remove DRM

### ISSUE THREAD

**Issue by sidneydemoraes** [apprenticeharper/DeDRM_tools#1149]
DeDRM 6.8.0
Ubuntu 20.04
Kindle for PC 1.16.0.44025
Calibre 4.20

```
calibre, version 4.20.0
ERROR: Loading book failed: Failed to open the book at .../Hipnose - Pyong Lee.azw. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 468, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: .../Hipnose - Pyong Lee.azw with error:
InputFormatPlugin: MOBI Input running
on /home/sid/Biblioteca do calibre/Pyong Lee/Hipnose (57)/Hipnose - Pyong Lee.azw
Found KF8 MOBI of type u'standalone'
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 862, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 855, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 830, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Hipnose
```

**Comment by ElleKayEm** [comment]
DRM removal happens when you first load the book into calibre, not during conversion.  Here's how to get the log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by sidneydemoraes** [comment]
Sorry about that. I'll post the full log here.

**Comment by sidneydemoraes** [comment]
```
calibre Debug log
calibre 4.20  embedded-python: True is64bit: True
Linux-5.4.0-40-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-40-generic', '#44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.20  embedded-python: True is64bit: True
Linux-5.4.0-40-generic-x86_64-with-debian-bullseye-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-40-generic', '#44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020')
Python 2.7.16
Linux: ('debian', 'bullseye/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.76] main UI initialized...
[0.76] Hiding splash screen
[34.33] splash screen hidden
[34.33] Started up in 34.33 seconds with 40 books
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing .../B07DHT865G_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B07DHT865G_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Hipnose
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe ".../.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/sid/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
000b:fixme:winediag:__wine_start_process Wine Staging 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
001c:fixme:ver:GetCurrentPackageId (0xc9eb90 (nil)): stub
0029:err:setupapi:SetupDiSelectBestCompatDrv No compatible drivers were enumerated for device L"USB\\VID_1C7A&PID_0603\\0".
0029:err:plugplay:install_device_driver Install function 0x17 failed, error 0xe0000228.
0009:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Hipnose to db in: 0.2
Added 1 books in 2.1 seconds
Worker Launch took: 0.0800879001617
```

**Comment by ElleKayEm** [comment]
I think the problem is here:

> err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found

Do you have Python and PyCrypto installed under wine?

**Comment by tartley** [comment]
@ElleKayEm  Hi. As you've seen, I'm trying to close resolved issues and merge dupes, so that it's easier to see what still actually needs to be fixed.

In a case like this, where you provided a plausible cause for the user's problem, and they didn't get back to you, then after an amount of time, I'd like to close the issue as resolved. How about if we give users 3 months to respond, and then close the issue?  (only in the cases where a plausible cause and fix or workaround was provided)

**Comment by ElleKayEm** [comment]
@tartley Hi!  Thank you for your efforts here!  I'm just now catching up on these.  That's fine by me.  Apprentice Harper would sometimes close things like this with a comment along the lines of "Assumed resolved.  Open a new issue if you still need help."
