### ISSUE TITLE
Again: androidkeys error

### ISSUE THREAD

**Issue by Norghul** [apprenticeharper/DeDRM_tools#115]
Hi,

i've seen this error has already been there and classified as "too old calibre version". I've got the same issue with the most recent version of Calibre and DeDRM, when trying to open the plugin configuration...
An ideas?

>calibre, version 2.62.0
>FEHLER: Nicht abgefangener Fehler: <b>KeyError</b>:'androidkeys'
>
>calibre 2.62 Portable embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 4, 3)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 628, in config_widget
  File "calibre_plugins.dedrm.config", line 57, in __init__
  File "calibre_plugins.dedrm.prefs", line 50, in __getitem__
  File "site-packages\calibre\utils\config.py", line 398, in __getitem__
KeyError: 'androidkeys'

**Comment by apprenticeharper** [comment]
I'm mystified. In DeDRM 6.4.3, line 50 of pref.py is the blank line *before* getitem. My best guess is that somehow there's an older version partially installed in some way. Uninstall the DeDRM plugin and then check the calibre preferences folders for any trace of DeDRM and get rid of any left-over files. The try re-installing.

**Comment by Norghul** [comment]
omg... could have thought of it myself ;-) 
Ok, I removed the dedrm.json from settings folder and everything was working again. Maybe some incompatibility with the old settings (from before the update - 6.1.x) version.
Thanks.
