### ISSUE TITLE
DRM not removing - followed instructions as listed in READ ME

### ISSUE THREAD

**Issue by shizunaluver** [apprenticeharper/DeDRM_tools#1150]
calibre Debug log
calibre 4.18 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Hello World Plugin (1, 0, 0)
calibre 4.18 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Hello World Plugin (1, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.69] db initialized
[0.69] Constructing main UI...
[3.09] main UI initialized...
[3.09] Hiding splash screen
[9.45] splash screen hidden
[9.47] Started up in 9.47 seconds with 124 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xa9\xf4u7\xa3@/U\xb1U\xceV\x06\xc5\xf0\x1dtY2\xb3k+>\x0fd\xd7\xe3._&\xc5;', 'C:\\Users\\luver\\Downloads\\Weird & Wonderful Holiday Romance Anthology 18 Holiday-themed Romances with a Twist!.azw3']
DeDRM v6.8.0: Trying to decrypt Weird & Wonderful Holiday Romance Anthology 18 Holiday-themed Romances with a Twist!.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Weird & Wonderful Holiday Romance Anthology: 18 Holiday-themed Romances with a Twist!
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\luver\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\luver\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2449984119' and UserName '6c75766572'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Weird & Wonderful Holiday Romance Anthology: 18 Holiday-themed Romances with a Twist!
Got DSN key from database default_key_1
Found 4 keys to try after 23.4 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 23.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 23.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Weird & Wonderful Holiday Romance Anthology: 18 Holiday-themed Romances with a Twist! to db in: 3.6
Added 1 books in 28.9 seconds
Worker Launch took: 0.216000080109

**Comment by ElleKayEm** [comment]
Is this from the website for "download & transfer via USB"?  Needs to be an E-ink Kindle (not a Fire) and you need to enter its serial number into the DeDRM plugin customization.

**Comment by shizunaluver** [comment]
I only own a kindle fire. I followed the directions for "download & transfer via USB" as the instructions made it sound like there were extra steps needed if an e-ink was in use. How am I to get the book's files otherwise?

**Comment by ElleKayEm** [comment]
Then you will need to use Kindle for PC.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371
