### ISSUE TITLE
Failed to decrypt KFX voucher with any key

### ISSUE THREAD

**Issue by adumbgreen** [apprenticeharper/DeDRM_tools#1156]
Hello,

I'm trying to decrypt a KFX-ZIP eBook using 6.8.0 and KFX-Input using Calibre. I'm having some trouble getting it to decrypt. I'm using Kindle for Mac 1.2.8.

I ended up diving in a little myself and made the log output more explicit since I couldn't identify where the hold up is. I've found that it's failing to decrypt my in `kfxdedrm.py`'s `decrypt_voucher`; it's not able to create a `DrmIonVoucher` and decrypt without an exception. Log output below, emphasis added for my added verbosity:

```
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing /Users/adam.green/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B083JSGMLK_EBOK/B083JSGMLK_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 19 file(s) as /var/folders/gc/673s5r6d2v552cxggt4y5yrm0000gn/C/calibre_4.20.0_tmp_9p4ccz/6HvosY.kfx-zip
DeDRM v6.8.0: Trying to decrypt 6HvosY.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 6HvosY
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.83d20c3b-aa6c-4521-9038-4e26ad4a8277.voucher
Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/adam.green/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
[3.59] splash screen hidden
[3.59] Started up in 3.59 seconds with 1 books
Decrypted key file using IDString '55bd3d6c8321' and UserName 'adam.green'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: 6HvosY
Got DSN key from database default_key_1
Found 1 keys to try after 0.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.83d20c3b-aa6c-4521-9038-4e26ad4a8277.voucher
>>>>>>>>>>> Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging /var/folders/gc/673s5r6d2v552cxggt4y5yrm0000gn/C/calibre_4.20.0_tmp_9p4ccz/6HvosY.kfx-zip
Processing container: B083JSGMLK_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B083JSGMLK_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/gc/673s5r6d2v552cxggt4y5yrm0000gn/C/calibre_4.20.0_tmp_9p4ccz/57nw7c_add_books/0/B083JSGMLK_EBOK.kfx-zip
```

**Comment by ElleKayEm** [comment]
Use Kindle for Mac 1.26 or earlier.  Alternatively, shut off KFX downloads.  See method 2 or 4 here:  https://www.mobileread.com/forums/showthread.php?t=283371
