### ISSUE TITLE
Kindle for PC 1.17 and DeDRM 6.8.0 Didn't remove DRM

### ISSUE THREAD

**Issue by freewellas** [apprenticeharper/DeDRM_tools#1157]
![image](https://user-images.githubusercontent.com/68121031/87177330-6107a380-c2d3-11ea-9ad5-c6bc0487ce1b.png)
I am trying to remove the DRM and I am having some difficulties. Can someone help me?

**Comment by ElleKayEm** [comment]
Post a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by freewellas** [comment]
calibre Registo de depuração
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 6, 3) && Kindle and Mobipocket DeDRM (0, 4, 18) && Package KFX (from KFX Input) (1, 33, 0) && Ignoble Epub DeDRM (0, 2, 6) && eReader PDB 2 PML (0, 0, 8) && Inept PDF DeDRM (0, 1, 9) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && KePub Output (3, 2, 13)
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: pt
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 6, 3) && Kindle and Mobipocket DeDRM (0, 4, 18) && Package KFX (from KFX Input) (1, 33, 0) && Ignoble Epub DeDRM (0, 2, 6) && eReader PDB 2 PML (0, 0, 8) && Inept PDF DeDRM (0, 1, 9) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && KePub Output (3, 2, 13)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.52] splash screen shown
[1.52] Initializing db...
[1.58] db initialized
[1.58] Constructing main UI...
[5.39] main UI initialized...
[5.39] Hiding splash screen
[45.41] splash screen hidden
[45.41] Started up in 45.41 seconds with 147 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xbac\xba3\xd7[4K\xfb\x1f\xf6{dp\xae|U\x84\xf9K\xb7\xe6\xe6\x8eJ\xe5~\xa4\xa4\x1d\xacv', 'D:\\Documentos\\My Kindle Content\\B07GRCCLXC_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing D:\Documentos\My Kindle Content\B07GRCCLXC_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B07GRCCLXC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Development of the Youth Athlete
Got DSN key from database default_key
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\xxxx\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\xxxx\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4162674459' and UserName '46696c697065204d61746f73'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Development of the Youth Athlete
Got DSN key from database default_key_1
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Kindle and Mobipocket DeDRM v0.4.18: Trying to decrypt B07GRCCLXC_EBOK.azw.
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 121, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 254, in config
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
D:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Development of the Youth Athlete to db in: 2.1
Added 1 books in 4.8 seconds
Worker Launch took: 0.460000038147
Worker Launch took: 0.522000074387
Job: 1 Converter livros 1 de 1 (Development of the Youth Athlete) finished
Converter livros 1 de 1 (Development of the Youth Athlete)
	D:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  read_metadata_from_opf: u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\xluu1b.opf'
	  verbose: 2
	  pdf_serif_family: u'MS Shell Dlg 2'
	  cover: u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\m1nnzb.jpeg'
	Resolved conversion options
	calibre version: 4.20.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\m1nnzb.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B6971183C8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001B697118FC8>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Helvetica',
	 'pdf_serif_family': u'MS Shell Dlg 2',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\xluu1b.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\xxxx~1\AppData\Local\Temp\calibre_4yaywp\3wl7fo.azw
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Development of the Youth Athlete (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	DRMError: Development of the Youth Athlete

Converter livros 1 de 1 (name of book)
D:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  read_metadata_from_opf: u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\xluu1b.opf'
  verbose: 2
  pdf_serif_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\m1nnzb.jpeg'
Resolved conversion options
calibre version: 4.20.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\m1nnzb.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B6971183C8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001B697118FC8>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\xxxx~1\\AppData\\Local\\Temp\\calibre_4yaywp\\xluu1b.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\xxxx~1\AppData\Local\Temp\calibre_4yaywp\3wl7fo.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  Development of the Youth Athlete (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: name of book

**Comment by ElleKayEm** [comment]
From the log:

> Failed to decrypt with error: Cannot decode library or rented ebooks.

DeDRM is intended for purchased books.

**Comment by freewellas** [comment]
> From the log:
> 
> > Failed to decrypt with error: Cannot decode library or rented ebooks.
> 
> DeDRM is intended for purchased books.

Thank you so much!
