### ISSUE TITLE
DRM not removed from Amazon AZW3 file...

### ISSUE THREAD

**Issue by andrew-strong** [apprenticeharper/DeDRM_tools#1159]
I am using Calibre 4.2.0 and DeDRM 6.8.0 and I am having trouble removing the DRM in an Amazon purchased AZW3 file. The error message is as follows:

`calibre, version 4.20.0
ERROR: Loading book failed: Failed to open the book at /mnt/ssd2/Calibre Library/John Bingham/No Need for Speed (190)/No Need for Speed - John Bingham.azw3. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 468, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: /mnt/ssd2/Calibre Library/John Bingham/No Need for Speed (190)/No Need for Speed - John Bingham.azw3 with error:
InputFormatPlugin: MOBI Input running
on /mnt/ssd2/Calibre Library/John Bingham/No Need for Speed (190)/No Need for Speed - John Bingham.azw3
Found KF8 MOBI of type u'standalone'
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 862, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 855, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 830, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: No Need for Speed`

Please let me know if I can provide more information...

**Comment by andrew-strong** [comment]
Full Calibre debug log as follows, after attempting to 'View' the AZW3 file from within Calibre:

`calibre Debug log

calibre 4.20 embedded-python: True is64bit: True Linux-5.4.50-ads-x86_64-AMD_Ryzen_Threadripper_2950X_16-Core_Processor-with-slackware-14.2 Linux (‘64bit’, ‘ELF’) (‘Linux’, ‘5.4.50-ads’, ‘#1 SMP Sat Jul 11 12:19:58 AEST 2020’) Python 2.7.16

Linux: (‘Slackware ‘, ‘14.2’, ”)

Interface language: None

Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) calibre 4.20 embedded-python: True is64bit: True Linux-5.4.50-ads-x86_64-AMD_Ryzen_Threadripper_2950X_16-Core_Processor-with-slackware-14.2 Linux (‘64bit’, ‘ELF’) (‘Linux’, ‘5.4.50-ads’, ‘#1 SMP Sat Jul 11 12:19:58 AEST 2020’) Python 2.7.16

Linux: (‘Slackware ‘, ‘14.2’, ”)

Interface language: None

Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) Turning off automatic hidpi scaling

devicePixelRatio: 1.0

logicalDpi: 162.154613466 x 161.127753304

physicalDpi: 108.373333333 x 107.576470588

Using calibre Qt style: True

[0.00] Starting up…

[0.00] Showing splash screen…

[0.04] splash screen shown

[0.04] Initializing db…

[0.05] db initialized

[0.05] Constructing main UI…

[0.69] main UI initialized…

[0.69] Hiding splash screen

[3.99] splash screen hidden

[3.99] Started up in 3.99 seconds with 64 books Found device nodes: devsdc None None

Syncing cover thumbnails to workaround amazon cover bug Restored 0 cover thumbnails that were destroyed by Amazon Job: 0 Get device information started

DeviceJob: 0 Get device information done, calling callback DeviceJob: 0 Get device information callback returned Job: 1 Set library information started

DeviceJob: 1 Set library information done, calling callback DeviceJob: 1 Set library information callback returned Job: 2 Get list of books on device started

DEBUG: 0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None DEBUG: 0.0 USBMS: dirs are: mediaKindle/ documents DEBUG: 0.0 USBMS: scan from root False mediaKindle/documents DEBUG: 0.0 USBMS: count found in cache: 66, count of files in metadata: 66, need_sync: False DEBUG: 0.0 USBMS: Finished fetching list of books from device. oncard= None DEBUG: 0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda DEBUG: 0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb DeviceJob: 2 Get list of books on device done, calling callback DeviceJob: metadata_downloaded: Starting set_books_in_library DeviceJob: set_books_in_library: books to process= 66

DeviceJob: set_books_in_library finished: time= 0.00299715995789

DeviceJob: metadata_downloaded: updating views DeviceJob: metadata_downloaded: syncing

DeviceJob: metadata_downloaded: refreshing ondevice DeviceJob: metadata_downloaded: sending metadata_available signal DeviceJob: 2 Get list of books on device callback returned Job: 0 Get device information finished

No details available.

Job: 1 Set library information finished

No details available.

Job: 2 Get list of books on device finished

No details available.

Worker Launch took: 0.0353579521179`

**Comment by andrew-strong** [comment]
User error: my apologies for the noise :)
