### ISSUE TITLE
Download and Transfer via USB not converting

### ISSUE THREAD

**Issue by Fenway68** [apprenticeharper/DeDRM_tools#1160]
Device: MacBookPro 13" 2012
iOs Catalina 10.15.5
Calibre 4.20

On Amazon selected "Download and Transfer via USB" as usual, then added book from my directory to Calibre, DRM remains.

calibre Debug log
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.23] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
[4.49] main UI initialized...
[4.49] Hiding splash screen
[17.57] splash screen hidden
[17.58] Started up in 17.57 seconds with 367 books

{u'bsd_drives': {u'main': u'/dev/disk4s1'},
 u'drives': {u'main': '/Volumes/Kindle'},
 u'mount_map': {'/Users/Brown/Downloads/DeDRM_tools_6.6.2/DeDRM_Macintosh_Application/DeDRM.app': '/private/var/folders/7j/wy_tr72s255gbh6stzcvw6500000gp/T/AppTranslocation/9BCE090F-303C-4240-839C-4F013E6F7F4C',
                '/dev/disk1s1': '/System/Volumes/Data',
                '/dev/disk1s3': '/Volumes/Recovery',
                '/dev/disk1s4': '/private/var/vm',
                '/dev/disk1s5': '/',
                '/dev/disk3s1': '/Volumes/calibre-4.20.0',
                '/dev/disk4s1': '/Volumes/Kindle',
                'devfs': '/dev',
                'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.3 USBMS: scan from root False /Volumes/Kindle/documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    0.9 USBMS: count found in cache: 221, count of files in metadata: 221, need_sync: False
DEBUG:    0.9 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.9 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 221
DeviceJob: set_books_in_library finished: time= 0.0190780162811
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
DeDRM v6.8.0: Trying to decrypt Again, but Better.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Again, but Better
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kindle-info file: /Users/Brown/Library/Application Support/Amazon/Kindle for Mac/storage/.kindle-info
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Looks like you need to enter the E-ink Kindle serial number to the DeDRM plugin customization.

**Comment by Fenway68** [comment]
Yes, realized right after I sent the message. I was using the standalone app prior but took me a bit to figure out where the configuration window was in the integrated product. All set now. Thanks. I like that I now can save a step in the process.
