### ISSUE TITLE
Topaz book not able to be converted

### ISSUE THREAD

**Issue by david-mears** [apprenticeharper/DeDRM_tools#1161]
I purchased 'Magic, Power, Language, Symbol: A Magician's Exploration of Linguistics'. DeDRM seems not to convert it.

I **am** able to convert other of my Kindle books, which happen to be in the azw3 format. This one's file name ends in azw.

I would highlight this line from the logs. `No k4Mac kindle-info/rainier/kinf2011 files have been found.`

Log:

```
calibre Debug log
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.20  embedded-python: True is64bit: True
Darwin-19.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.4.0', 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.4', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.06] Showing splash screen...
[0.55] splash screen shown
[0.55] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[2.60] main UI initialized...
[2.60] Hiding splash screen
[6.52] splash screen hidden
[6.52] Started up in 6.52 seconds with 3 books

{u'bsd_drives': {u'main': u'/dev/disk9'},
 u'drives': {u'main': '/Volumes/KOBOeReader'},
 u'mount_map': {'/Users/daivdmears/Downloads/Spectacle.app': '/private/var/folders/1l/j398jrrs42x53z_chgql4bn40000gp/T/AppTranslocation/5F24CB6D-3CD9-4453-81C6-6297626C4238',
                '/dev/disk1s1': '/',
                '/dev/disk1s4': '/private/var/vm',
                '/dev/disk1s5': '/System/Volumes/Data',
                '/dev/disk2s1': '/Volumes/Kobo',
                '/dev/disk4s1': '/Volumes/calibre-4.18.0',
                '/dev/disk6s1': '/Volumes/calibre-4.20.0',
                '/dev/disk7s1': '/Volumes/Kindle',
                '/dev/disk8s1': '/Volumes/Inform',
                '/dev/disk9': '/Volumes/KOBOeReader',
                'devfs': '/dev',
                'kbfs@kbfuse1': '/Volumes/Keybase (daivdmears)',
                'keybase-redirector': '/Volumes/Keybase',
                'map auto_home': '/System/Volumes/Data/home'}}
DEBUG:    0.0 KoboTouch::open_osx - mount_map= {'/Users/daivdmears/Downloads/Spectacle.app': '/private/var/folders/1l/j398jrrs42x53z_chgql4bn40000gp/T/AppTranslocation/5F24CB6D-3CD9-4453-81C6-6297626C4238', '/dev/disk1s1': '/', '/dev/disk1s4': '/private/var/vm', '/dev/disk1s5': '/System/Volumes/Data', '/dev/disk8s1': '/Volumes/Inform', 'devfs': '/dev', 'map auto_home': '/System/Volumes/Data/home', '/dev/disk4s1': '/Volumes/calibre-4.18.0', '/dev/disk6s1': '/Volumes/calibre-4.20.0', '/dev/disk9': '/Volumes/KOBOeReader', '/dev/disk2s1': '/Volumes/Kobo', 'kbfs@kbfuse1': '/Volumes/Keybase (daivdmears)', '/dev/disk7s1': '/Volumes/Kindle', 'keybase-redirector': '/Volumes/Keybase'}
DEBUG:    0.0 KoboTouch::open_osx - self._main_prefix= /Volumes/KOBOeReader/
DEBUG:    0.0 KoboTouch::open_osx - self._card_a_prefix= None
DEBUG:    0.0 KoboTouch::open_osx - self._card_b_prefix= None
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.1 KoboTouch:books - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='None', prefix='/Volumes/KOBOeReader/'
DEBUG:    0.1 Kobo device: Kobo Clara HD
DEBUG:    0.1 Version of driver: (2, 5, 1) Has kepubs: True
DEBUG:    0.1 Version of firmware: (4, 22, 15190) Has kepubs: True
DEBUG:    0.1 Firmware supports cover image tree: True
DEBUG:    0.1 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.1 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: [u'kepub', u'epub', u'pdf', u'txt', u'cbz', u'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: None, modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 
DEBUG:    0.1 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.1 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:books - length bl=0
DEBUG:    0.1 KoboTouch:books - length bl after sync=5
DEBUG:    0.1 KoboTouch:books - reading device database
DEBUG:    0.2 Database Version:  160
DEBUG:    0.2 KoboTouch:books - shelf list: [u'ReadingList']
DEBUG:    0.2 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId,DeDRM v6.7.0: Trying to decrypt B0030T1EO4_EBOK.azw
Using Library AlfCrypto Python
Decrypting Topaz ebook: Magic, Power, Language, Symbol: A Magician's Exploration of Linguistics
Found 2 keys to try after 0.1 seconds
Trying: 7Nt0f6dX
Trying: 1T5T67Q*
DeDRM v6.7.0: Failed to decrypt with error: No key found in 2 keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v6.7.0: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
 ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.4 KoboTouch:books - self.kobo_series_dict= {u'ORTHOGONAL': u'b6b3b727-7c32-5961-bdbb-d897f0a63779', u'Pelican Books': u'fbfa7d19-1747-5d40-aff9-6669db8bc21b', u'Orthogonal': u'b6b3b727-7c32-5961-bdbb-d897f0a63779'}
DEBUG:    0.4 KoboTouch:books - about to sync_booklists
DEBUG:    0.4 USBMS: starting sync_booklists
DEBUG:    0.4 USBMS: finished sync_booklists
DEBUG:    0.4 KoboTouch:books - have done sync_booklists
DEBUG:    0.4 KoboTouch:books - end - oncard='None'
DEBUG:    0.4 KoboTouch:books - oncard='carda'
DEBUG:    0.4 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.4 KoboTouch:books - oncard='cardb'
DEBUG:    0.4 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 5
DeviceJob: set_books_in_library finished: time= 0.00198602676392
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added Magic, Power, Language, Symbol: A Magician's Exploration of Linguistics to db in: 0.0
Added 1 books in 1.8 seconds
```

**Comment by david-mears** [comment]
I called the issue 'Topaz book not able to be converted' because Calibre claims this book is a Topaz book when I try to open and read it.

**Comment by ElleKayEm** [comment]
Update to DeDRM 6.8.0.
