### ISSUE TITLE
Cannot Install DeDRM Tools Plugin into Calibre 4.99.4 on Linux

### ISSUE THREAD

**Issue by ncweber00** [apprenticeharper/DeDRM_tools#1162]
I am using Calibre 4.99.4 on Ubuntu 20.04.  When I attempt to install DeDRM Tools 6.8.0 plugin into Calibre, I get a syntax error on line 168, and the plugin fails to install.  Below is the response I receive.

```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-40-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-40-generic', '#44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020')
Python 3.8.2
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by ElleKayEm** [comment]
DeDRM is not compatible with Python 3 yet.  Use the official non-beta release of calibre which still has Python 2.

**Comment by squarooticus** [comment]
If you're familiar with Docker, I put together a straightforward Docker build producing a container image you can use to run an older stable version of Calibre: https://github.com/squarooticus/caliboat

**Comment by ncweber00** [comment]
Thanks for the responses.  I managed to perform a work around with a copy of calibrePortable from PortableApps.com and Codeweavers' CrossOver for Linux. It worked perfectly.
