### ISSUE TITLE
FAIL

### ISSUE THREAD

**Issue by Solenya85** [apprenticeharper/DeDRM_tools#1164]
calibre Debug log
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 2.7.16+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.569275362 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[2.14] main UI initialized...
[2.14] Hiding splash screen
[14.16] splash screen hidden
[14.16] Started up in 14.16 seconds with 99 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x95\x8cy\x94\xb5\xf4\x84\x9d\xf4\x16?&\xb1\xdb\x8c\xbc\xf8(?\xccRS\xcbM\xab\x81\xa4\xce:\xd3\xd0i', 'C:\\Users\\user\\Downloads\\Brimstone Kiss_ Phantom Queen Book 10 - A Temple Verse Series (The Phantom Queen Diaries).azw3']
DeDRM v6.8.0: Trying to decrypt Brimstone Kiss_ Phantom Queen Book 10 - A Temple Verse Series (The Phantom Queen Diaries).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Brimstone Kiss: Phantom Queen Book 10 - A Temple Verse Series (The Phantom Queen Diaries)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1485034261' and UserName '75736572'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Brimstone Kiss: Phantom Queen Book 10 - A Temple Verse Series (The Phantom Queen Diaries)
Got DSN key from database default_key_1
Found 4 keys to try after 9.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 9.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 9.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Brimstone Kiss: Phantom Queen Book 10 - A Temple Verse Series (The Phantom Queen Diaries) to db in: 1.2
Added 1 books in 10.8 seconds

**Comment by ElleKayEm** [comment]
If that book is for an E-ink Kindle (not a Fire), then you need to put its serial number into DeDRM's customization.

**Comment by Solenya85** [comment]
it was downloaded to comp for kindle tab..... i put fire serial in the e-ink section after it didnt work the first time...

**Comment by ElleKayEm** [comment]
Books for a Fire can't be decrypted.  If you don't have an E-ink Kindle, then you'll need to use Kindle for PC, see method 1, 2, or 4 here:

https://www.mobileread.com/forums/showthread.php?t=283371
