### ISSUE TITLE
Failed to Decrypt

### ISSUE THREAD

**Issue by kayovoldk** [apprenticeharper/DeDRM_tools#1167]
calibre Debug log
calibre 4.21  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Hymn Reader (1, 0, 1) && Embed Comic Metadata (1, 4, 0) && Comicvine (0, 12, 1) && X-Ray Creator (3, 2, 1) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.21  embedded-python: True is64bit: True
Darwin-19.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.5.0', 'Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Hymn Reader (1, 0, 1) && Embed Comic Metadata (1, 4, 0) && Comicvine (0, 12, 1) && X-Ray Creator (3, 2, 1) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[1.41] main UI initialized...
[1.41] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing /Users/kayovoldk/Library/Application Support/Kindle/My Kindle Content/B082H2YHTJ_EBOK/B082H2YHTJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/03/zcclxj8d3p5073fnybr394fm0000gr/C/calibre_4.21.0_tmp_vUPo8i/F404TJ.kfx-zip
DeDRM v6.8.0: Trying to decrypt F404TJ.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: F404TJ
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bb23a33d-e0ed-4d6d-8513-f60918dc99ba.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/kayovoldk/Library/Application Support/Kindle/storage/.kinf2018
[3.03] splash screen hidden
[3.03] Started up in 3.03 seconds with 195 books
Decrypted key file using IDString '2d4c5b8bdb77' and UserName 'blanc'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: F404TJ
Got DSN key from database default_key_1
Found 1 keys to try after 0.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bb23a33d-e0ed-4d6d-8513-f60918dc99ba.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging /var/folders/03/zcclxj8d3p5073fnybr394fm0000gr/C/calibre_4.21.0_tmp_vUPo8i/F404TJ.kfx-zip
Processing container: B082H2YHTJ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B082H2YHTJ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/03/zcclxj8d3p5073fnybr394fm0000gr/C/calibre_4.21.0_tmp_vUPo8i/u0CweW_add_books/0/B082H2YHTJ_EBOK.kfx-zip
Added Shadows Rising (World of Warcraft: Shadowlands) to db in: 0.1
Added 1 books in 11.9 seconds

**Comment by ElleKayEm** [comment]
Either use Kindle for Mac 1.26 or earlier.  Or disable KFX downloads.  See Method 2 or 4 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by kayovoldk** [comment]
Honest question why does the latest release say that the latest version of the Kindle Mac app is supported when it's not?

**Comment by ElleKayEm** [comment]
It worked for the first day after release.  Then Amazon made a change.  You can still use the current version if you turn off KFX downloads.
