### ISSUE TITLE
DeDRM 6.8.0 fails to convert book on "add book"

### ISSUE THREAD

**Issue by rogard** [apprenticeharper/DeDRM_tools#1172]
I have a DRM protected epub on an old Mac, that I'm trying to transfer to my Linux machine. 

As I understand it, first you install the plugin, then add the book, and conversion should be automatic. Q1: is this correct in principle?

That's what I did on Linux, from the GUI, and I cannot view the book: I get the message "locked by DRM". I made sure the plugin was enabled. Q2: any troubleshooting steps I could take?

Mac:
ADE: 4.5

Linux:
Calibre: 3.1
OS: LM 19 (Tara)
DeDRM: 6.8.0

PS: The first problem was 'wine' was not working. Here's the updated log after fixing that:

Log:

```
$ calibre-debug -g
calibre 3.21  embedded-python: False is64bit: True
Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19-tara Linux ('64bit', '')
('Linux', '4.15.0-20-generic', '#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018')
Python 2.7.15+
Linux: ('LinuxMint', '19', 'tara')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.11] splash screen shown
[0.12] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
Loaded cached store plugin for: Beam EBooks DE at version: 4
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: Legimi at version: 10
Loaded cached store plugin for: Google Books at version: 6
Loaded cached store plugin for: Woblink at version: 15
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Empik at version: 9
Loaded cached store plugin for: Świat Ebooków at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 6
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Mills and Boon UK at version: 4
Loaded cached store plugin for: LitRes at version: 2
Loaded cached store plugin for: Virtualo at version: 10
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.83] main UI initialized...
[0.83] Hiding splash screen
[0.96] splash screen hidden
[0.96] Started up in 0.96 seconds with 1 books
DeDRM v6.8.0: Trying to decrypt book xyz.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: book xyz.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.8.0: Running adobekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/er/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/er/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
**wine: cannot find L"C:\\windows\\system32\\python.exe**"
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Exception when getting default Adobe Key after 1.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 357, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.8.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added book xyz to db in: 1.4
Added 1 books in 2.8 seconds
```

**Comment by ElleKayEm** [comment]
A1:  The key can automatically be retrieved if Adobe Digital Editions authorized with your Adobe ID is on the same machine and user as calibre with DeDRM.

A2:  I think the easiest way would be to (at least temporarily) install calibre and DeDRM on the Mac.  Then you can save your key from that setup and import it into the Linux setup.

**Comment by rogard** [comment]
@ElleKayEm yeah, it worked. Thanks.
