### ISSUE TITLE
Invalid META-INF/container.xml can crash DeDRM

### ISSUE THREAD

**Issue by pmdevita** [apprenticeharper/DeDRM_tools#1181]
Long story short, I ended up with [this ebook](https://www.kobo.com/jp/ja/ebook/RR0v_gJb2TyYvTGgCVt2Ow) from Japanese Kobo which had the following META-INF/container.xml file

```
<?xml version="1.0" encoding="UTF-8"?><container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0">
	<rootfiles>
		<rootfile full-path="OPS/standard.opf" media-type="application/oebps-package+xml"/>
		<rootfile full-path="OPS/advanced.opf" media-type="application/oebps-package+xml"/>
	</rootfiles>
</container>
```

However, the file did not actually contain the "OPS/advanced.opf" file, and when decrypted, the following error was produced.

```
DeDRM v6.8.0: Trying to decrypt 大正処女御伽話 2.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: 大正処女御伽話 2.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Trying Encryption key default_key
DeDRM v6.8.0: Decrypted with key default_key after 2.2 seconds
DeDRM v6.8.0: Finished after 2.2 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 195, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 255, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 160, in read_bytes
  File "site-packages\calibre\utils\zipfile.py", line 995, in read
  File "site-packages\calibre\utils\zipfile.py", line 1023, in open
  File "site-packages\calibre\utils\zipfile.py", line 985, in getinfo
KeyError: u"There is no item named 'OPS/advanced.opf' in the archive"
Added 大正処女御伽話 2 to db in: 0.4
Added 1 books in 3.2 seconds
```

Removing the entry for advanced.opf in the container.xml file bypasses this and decrypts the book normally. However, DeDRM should be more cautious about trusting a book's metadata as it may not always be correct. Doubling checking files exist before accessing them would be a good idea.

~~Additionally (although I'm not sure this is DeDRM's fault), the resulting book is decrypted but broken and unusable without additional fixes to the HTML. But I have a feeling something not standard is going on there so I suppose it is to be expected.~~ Pretty sure it's not DeDRM's fault, book is just broken in many ways

Thanks for the tools by the way, it's really let me start investing in ebooks without fear of DRM locking me in.

**Comment by ElleKayEm** [comment]
Out of curiosity, have you tried the KEPUB version (from the Kobo Desktop app or a Kobo ereader) with the Obok plugin?

**Comment by pmdevita** [comment]
Same thing actually

```
DEBUG:    6.8 got kobodir C:\Users\pmdevita\AppData\Local\Kobo\Kobo Desktop Edition
Found 20 possible keys to try.
DEBUG:   13.3 BookListTableWidget:get_books - book_num: 0
DEBUG:   13.3 BookListTableWidget:get_books - book: 大正処女御伽話 2
DEBUG:   13.3 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.7.0 - Decrypting 大正処女御伽話 2
Trying key:  b798e54f8c10aa5723a26f10493c4dae
Success!
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 195, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 255, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 160, in read_bytes
  File "site-packages\calibre\utils\zipfile.py", line 995, in read
  File "site-packages\calibre\utils\zipfile.py", line 1023, in open
  File "site-packages\calibre\utils\zipfile.py", line 985, in getinfo
KeyError: u"There is no item named 'OPS/advanced.opf' in the archive"
DEBUG:   15.2 DecryptAddProgressDialog::do_book_action - decrypted book: '大正処女御伽話 2'
Obok DeDRM v6.7.0 - Added ncsd9l
Obok DeDRM v6.7.0 - wrapping up results.
```

But when I did this, I realized it had actually decrypted the book properly, I just didn't realize it before because I didn't know how broken the book was.

So I went back and it turns out that the Adobe version was also decrypting properly, everything actually works fine. I confused this book's issues for a problem with DeDRM and didn't investigate enough, sorry about that.

**Comment by ElleKayEm** [comment]
Thanks for checking and reporting back.
