### ISSUE TITLE
failed to remove DRM

### ISSUE THREAD

**Issue by zacwfallows** [apprenticeharper/DeDRM_tools#1182]
Convert book 1 of 1 (Runes for Beginners: A Guide to Reading Runes in Divination, Rune Magic, and the Meaning of the Elder Futhark Runes)
Conversion options changed from defaults:
  pdf_serif_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\zacwf\\AppData\\Local\\Temp\\calibre_xxyuop\\bzx2yx.jpeg'
  read_metadata_from_opf: u'C:\\Users\\zacwf\\AppData\\Local\\Temp\\calibre_xxyuop\\87fsxo.opf'
  pdf_sans_family: u'MS Shell Dlg 2'
  verbose: 2
  output_profile: u'generic_eink'
Resolved conversion options
calibre version: 4.0.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\zacwf\\AppData\\Local\\Temp\\calibre_xxyuop\\bzx2yx.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000025FFEA86488>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000025FFEA950C8>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\zacwf\\AppData\\Local\\Temp\\calibre_xxyuop\\87fsxo.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\zacwf\AppData\Local\Temp\calibre_xxyuop\zyekcm.kfx-zip
Software versions: KFX Input 1.33.0, calibre 4.0 [64bit], Windows-10-10.0.19041-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\zacwf\AppData\Local\Temp\calibre_xxyuop\zyekcm.kfx-zip
Processing container: B07D81S366_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B07D81S366_EBOK.azw has DRM and cannot be converted
P

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre so we can't determine the problem from a conversion log.  See if this post helps:  

https://www.mobileread.com/forums/showthread.php?t=283371

If that doesn't do it, post an import log:  

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
