### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by oghp1234** [apprenticeharper/DeDRM_tools#1188]
calibre Debug log
calibre 4.22  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.22  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.387434555 x 106.822429907
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.92] splash screen shown
[1.92] Initializing db...
[1.92] db initialized
[1.92] Constructing main UI...
[3.61] main UI initialized...
[3.61] Hiding splash screen
[7.77] splash screen hidden
[7.77] Started up in 7.77 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0flPA@\x01{\xb0\xa3\x1e\x16\x88<\xc6\xc4eA?\xfc\xe6Z\x7f\x0c$8\xa9{X\xd85NL', 'C:\\Users\\Heather\\Downloads\\Harbor Me.azw3']
DeDRM v6.8.0: Trying to decrypt Harbor Me.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Harbor Me
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Heather\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Heather\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2388838765' and UserName '48656174686572'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Harbor Me
Got DSN key from database default_key_1
Found 4 keys to try after 16.3 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 16.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 16.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Harbor Me to db in: 1.6
Added 1 books in 19.1 seconds

**Comment by ElleKayEm** [comment]
Looks like you haven't put the serial number for your E-ink Kindle into the DeDRM plugin customization.  If you don't have an E-ink Kindle, you'll need to use Kindle for PC.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
