### ISSUE TITLE
DeDRM v6.8.0: Ultimately failed to decrypt after 9.0 seconds.

### ISSUE THREAD

**Issue by dewi-ny-je** [apprenticeharper/DeDRM_tools#1189]
Hi, 
I'm on Windows 10 latest update, Calibre latest version, DeDRM 6.8.0, KFX Input 1.33.0 directly from Calibre repository.

I removed every device from Amazon Kindle website, I uninstalled Kindle for PC, deleted the folders as written.
Then I installed Kindle for PC, I entered my credentials, downloaded a book I bought, and I tried to add a Kindle book for conversion to EPUB (for Kobo). The eBook was regularly bought, no renting or free ebook.

This is the log:

```
calibre Debug log
calibre 4.22  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.22  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.0150943396 x 91.44
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[1.78] main UI initialized...
[1.78] Hiding splash screen
[3.58] splash screen hidden
[3.58] Started up in 3.58 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['$\x98\xbd\x9eF+\x0f\xee\xb0\xc5\xcd\x99\x17P\x80\xd4\xbf\xc6\xfe^\xc3\xa5\x80g\x84\xe2k\x05G]\x91\xe3', 'C:\\Users\\olaf\\Documents\\My Kindle Content\\B00E4Y75YC_EBOK\\B00E4Y75YC_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\olaf\Documents\My Kindle Content\B00E4Y75YC_EBOK\B00E4Y75YC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\olaf\AppData\Local\Temp\calibre_ddwev8\3qpxmk.kfx-zip
DeDRM v6.8.0: Trying to decrypt 3qpxmk.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 3qpxmk
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ca3e55d9-f2e6-4368-a9ce-89df8098f7bb.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\olaf\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\olaf\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2758805902' and UserName '6f6c6166'
DeDRM v6.8.0: Ultimately failed to decrypt after 9.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 9.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\olaf\AppData\Local\Temp\calibre_ddwev8\3qpxmk.kfx-zip
Processing container: B00E4Y75YC_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B00E4Y75YC_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\olaf\AppData\Local\Temp\calibre_ddwev8\ufgmoi_add_books\0\B00E4Y75YC_EBOK.kfx-zip
Added Tutte le opere (eNewton Classici) (Italian Edition) to db in: 1.5
Added 1 books in 11.7 seconds
```

I tried twice: the first time with the Calibre library in a network share (E:), the second time I redid the Calibre welcome wizard and set it for a folder under My Documents.
I didn't grab the log again but it didn't work on local storage as well.
What I get is a KFX-ZIP file which is still DRM'd.

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.26 or earlier or disable KFX downloads.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by dewi-ny-je** [comment]
Maybe it should be put in the FAQ.
I'll check those solutions.

**Comment by ElleKayEm** [comment]
There is a link to that post in the FAQs.

**Comment by dewi-ny-je** [comment]
The method with the .cmd file worked!
Thanks
