### ISSUE TITLE
Cannot remove DRM with Kindle 1.29.0 (58033) on Mac OS Catalina

### ISSUE THREAD

**Issue by clevec** [apprenticeharper/DeDRM_tools#1200]
Hi I am unable to remove the DRM for Kindle books. Using Kindle 1.29.0 (58033) on Mac OS Catalina with Calibre 4.22.

Please help.

The Calibre Log as follows:

----
calibre Debug log
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Kindle Collections (1, 7, 26) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.22  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Kindle Collections (1, 7, 26) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.000001637 x 109.000001637
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.89] main UI initialized...
[0.89] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing /Users/clevechia/Documents/My Kindle Content/B015P643WO_EBOK/B015P643WO_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/19/gkyp6j8106bbtwdddkm8c_yh0000gn/C/calibre_4.22.0_tmp_MQNkIw/eMwMZK.kfx-zip
DeDRM v6.8.0: Trying to decrypt eMwMZK.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: eMwMZK
Got DSN key from database default_key
Got DSN key from database default_key_2
Got DSN key from database default_key_3
Found 3 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.eb2bec0f-890d-49e7-bcfd-9a82779f7894.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/clevechia/Library/Application Support/Kindle/storage/.kinf2018
[2.83] splash screen hidden
[2.83] Started up in 2.83 seconds with 241 books
Decrypted key file using IDString '99875e8ff69b' and UserName 'clevechia'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: eMwMZK
Got DSN key from database default_key_1
Found 1 keys to try after 0.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.eb2bec0f-890d-49e7-bcfd-9a82779f7894.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging /var/folders/19/gkyp6j8106bbtwdddkm8c_yh0000gn/C/calibre_4.22.0_tmp_MQNkIw/eMwMZK.kfx-zip
Processing container: B015P643WO_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B015P643WO_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/19/gkyp6j8106bbtwdddkm8c_yh0000gn/C/calibre_4.22.0_tmp_MQNkIw/EbvNCp_add_books/0/B015P643WO_EBOK.kfx-zip
--------------

**Comment by ElleKayEm** [comment]
You'll need to disable KFX downloads or go back to Kindle for Mac version 1.26.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
