### ISSUE TITLE
DRM Removal Failure

### ISSUE THREAD

**Issue by NinjaMittens** [apprenticeharper/DeDRM_tools#1201]
calibre Debug log
calibre 4.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.66] main UI initialized...
[1.66] Hiding splash screen
[5.20] splash screen hidden
[5.20] Started up in 5.20 seconds with 777 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["y\xb42\x93\x80\xd48\xaf\xc3,\xd3y\xf7'B\xc7i\xb8\x810 ^z\xe9\\0\xba0\xf3\xa9\xc6\xaa", 'C:\\Users\\Johns\\Downloads\\The Ballad of Songbirds and Snakes (A Hunger Games Novel).azw3']
DeDRM v6.8.0: Trying to decrypt The Ballad of Songbirds and Snakes (A Hunger Games Novel).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Ballad of Songbirds and Snakes (A Hunger Games Novel)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Johns\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Johns\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2862054650' and UserName '4a6f686e73'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Ballad of Songbirds and Snakes (A Hunger Games Novel)
Got DSN key from database default_key_1
Found 4 keys to try after 4.9 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 4.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 4.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Ballad of Songbirds and Snakes (A Hunger Games Novel) to db in: 1.5
Added 1 books in 6.7 seconds
Worker Launch took: 0.0759999752045

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle, you need to enter its serial number into the DeDRM plugin customization.

**Comment by NinjaMittens** [comment]
Serial number was entered correctly into the customization, i checked that

**Comment by NinjaMittens** [comment]
![registered](https://user-images.githubusercontent.com/69727655/90318724-4387b400-dee7-11ea-9ed7-d71a89856d4f.PNG)

**Comment by ElleKayEm** [comment]
Then make sure that you chose that Kindle when you downloaded the file from the website.  Double-check the serial number is correct (copy and paste from the website).  Last thing to try is restarting calibre before re-adding the book.
