### ISSUE TITLE
Cannot open ebook in epub format 

### ISSUE THREAD

**Issue by BeFreeNowHere** [apprenticeharper/DeDRM_tools#1204]
I get the following error opening  an epub:

calibre, version 4.22.0
FEHLER: Buch konnte nicht geladen werden: Buch konnte nicht geöffnet werden: Corona Fehlalarm Zahlen Daten und Hintergr - Sucharit Bhakdi Karina Reiss.epub
Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 468, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 234, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: ebook.epub with error:
InputFormatPlugin: EPUB Input running
on Corona Fehlalarm Zahlen Daten und Hintergr - Sucharit Bhakdi Karina Reiss.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 862, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 855, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 830, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
DRMError: Corona Fehlalarm Zahlen Daten und Hintergr - Sucharit Bhakdi Karina Reiss.epub

Can you fix it with a version update?
Thank you

Best regards

**Comment by ElleKayEm** [comment]
DRM not removed.  Post a log of adding the book so we can figure out why:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
