### ISSUE TITLE
Cannot install plugin in Calibre (using Fedora)

### ISSUE THREAD

**Issue by gbonnema** [apprenticeharper/DeDRM_tools#1205]
Hi, I was installing the plugin as instructed, but got an error message for which I included the log. It is looks like a syntax error, but tbh as you guys have had many people install it, it may be a distribution specific thing. I copy the log below.

calibre, version 4.17.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.17  embedded-python: False is64bit: True
Linux-5.7.14-200.fc32.x86_64-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.7.14-200.fc32.x86_64', '#1 SMP Fri Aug 7 23:16:37 UTC 2020')
Python 3.8.5
Interface language: None
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Yes, that version of calibre has Python 3 and DeDRM isn't compatible yet.  If you install the regular release of calibre with Python 2, you'll be fine.

**Comment by gbonnema** [comment]
Yeah, I was afraid it was something like that. Unfortunately Fedora more or less abandoned Py2. I might be able to use some compatibility library for py2 and some older version of calibre.

Are you guys planning the py2->py3 transition? Any target period or date?

**Comment by ElleKayEm** [comment]
The regular release of calibre has an embedded Python 2 interpreter.  DeDRM is a community project so no timeline on Python 3.  Anyone is welcome to help.  See the pull request.

**Comment by gbonnema** [comment]
That's my bad. *Now* I get what you mean by regular release, you mean the release apart from the Fedora repository. Probably Fedora forces the python3 version. I will have a look at it.

Unfortunately my knowledge of python (2 or 3) is insufficient to help you, so I will have to look into getting a hold of the regular release of Calibra. Thank you for the advice and quick answers. I will close the query now.
