### ISSUE TITLE
DRM not removed using new tools 6.8 help please

### ISSUE THREAD

**Issue by PatriciaZu** [apprenticeharper/DeDRM_tools#1206]
calibre Registro de depuración
calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.22 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.67] splash screen shown
[0.67] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
[2.80] main UI initialized...
[2.80] Hiding splash screen
[6.47] splash screen hidden
[6.47] Started up in 6.47 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0e-\xd6\xb1\x05z%\x1fw^\x9c5\x07\x8fvS^u\x91+\xb2\xb0\xae\xeb\xfb\xea%\x9e\xae\x9c[\xdb', 'C:\\Users\\Dex631\\Documents\\My Kindle Content\\B075HT6Q1Z_EBOK\\B075HT6Q1Z_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing C:\Users\Dex631\Documents\My Kindle Content\B075HT6Q1Z_EBOK\B075HT6Q1Z_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 28 file(s) as C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cqxdef.kfx-zip
DeDRM v6.8.0: Trying to decrypt cqxdef.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: cqxdef
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 2 keys to try after 2.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9a251740-d4c2-4442-9909-2f36db8d9665.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 2.7 seconds
searching for kinfoFiles in C:\Users\Dex631\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Dex631\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2563315327' and UserName '446578363331'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: cqxdef
Got DSN key from database default_key_1
Found 1 keys to try after 15.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9a251740-d4c2-4442-9909-2f36db8d9665.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 15.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 15.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cqxdef.kfx-zip
Processing container: B075HT6Q1Z_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B075HT6Q1Z_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\gdz3ll_add_books\0\B075HT6Q1Z_EBOK.kfx-zip
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Recetas El Poder del Metabolismo: ¡Coma sabroso mientras mejora su metabolismo y adelgaza! (Spanish Edition) to db in: 2.6
Added 1 books in 24.4 seconds
Worker Launch took: 0.302000045776
Job: 0 Convertido el libro 1 de 1 (Recetas El Poder del Metabolismo: ¡Coma sabroso mientras mejora su metabolismo y adelgaza! (Spanish Edition)) finished
Convertido el libro 1 de 1 (Recetas El Poder del Metabolismo: ¡Coma sabroso mientras mejora su metabolismo y adelgaza! (Spanish Edition))
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  pdf_sans_family: u'MS Shell Dlg 2'
	  cover: u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\eiadv0.jpeg'
	  verbose: 2
	  pdf_serif_family: u'MS Shell Dlg 2'
	  read_metadata_from_opf: u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\ktukzp.opf'
	Resolved conversion options
	calibre version: 4.22.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\eiadv0.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000018C865F7A08>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000018C86754D08>,
	 'page_breaks_before': u'/',
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'MS Shell Dlg 2',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\ktukzp.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cwlfgl.kfx-zip
	Software versions: KFX Input 1.33.0, calibre 4.22 [64bit], Windows-10-10.0.17763-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cwlfgl.kfx-zip
	Processing container: B075HT6Q1Z_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 99, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
	KFXDRMError: Book container B075HT6Q1Z_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 104, in convert
	DRMError: This book has DRM!

Convertido el libro 1 de 1 (Recetas El Poder del Metabolismo: ¡Coma sabroso mientras mejora su metabolismo y adelgaza! (Spanish Edition))
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  output_profile: u'generic_eink'
  pdf_sans_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\eiadv0.jpeg'
  verbose: 2
  pdf_serif_family: u'MS Shell Dlg 2'
  read_metadata_from_opf: u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\ktukzp.opf'
Resolved conversion options
calibre version: 4.22.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\eiadv0.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000018C865F7A08>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000018C86754D08>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Dex631\\AppData\\Local\\Temp\\calibre_tmbxgf\\ktukzp.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cwlfgl.kfx-zip
Software versions: KFX Input 1.33.0, calibre 4.22 [64bit], Windows-10-10.0.17763-SP0
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\Dex631\AppData\Local\Temp\calibre_tmbxgf\cwlfgl.kfx-zip
Processing container: B075HT6Q1Z_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 99, in convert
  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
KFXDRMError: Book container B075HT6Q1Z_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
For KFX format books, you'll need to use Kindle for PC 1.26 or earlier.  Or you can disable KFX format downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
