### ISSUE TITLE
calibre won't add books (so I can't remove drm)

### ISSUE THREAD

**Issue by crisco111** [apprenticeharper/DeDRM_tools#1208]
I have been using the de-DRM tools from Apprentice Alf for about six or seven years and all has worked fine.  I'm using Windows 10.  And the DRM removes smoothly when I add books to Calibre.  Suddenly when I try to add books, the program stops responding -- hence I can't remove any DRMs!  I got a reply from Calibre that my anti-virus must be conflicting -- the only anti-virus I have is Windows Defender that came free.  Calibre also suggested making changes to environmental variables -- which I tried, but not sure what I'm doing.  I've tried reverting to Calibre 3.48 from version 4.? but no difference.  The only thing I've done recently with Calibre, other than a book or two onto my reader, was to delete about 200 books from my library.  Please give me some suggestions.  I'm baffled -- and with Covid, I'm doing a lot of reading!!  

Here's the message from Calibre --
calibre, version 3.48.0
ERROR: Unhandled exception: <b>Exception</b>:File dialog failed (return code -805306369):  

calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 4, 3)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\add.py", line 474, in add_books
  File "site-packages\calibre\gui2\win_file_dialogs.py", line 254, in choose_files
  File "site-packages\calibre\gui2\win_file_dialogs.py", line 208, in run_file_dialog
Exception: File dialog failed (return code -805306369):

**Comment by ElleKayEm** [comment]
Is your calibre library location been moved somewhere full or where you don't have write access?  Run the welcome wizard (under preferences menu) to see and/or change.  I would update to the latest calibre and DeDRM.

**Comment by crisco111** [comment]
I haven't done anything with the library, other than remove a few books.
It's been untouched (location wise) forever.  I am concerned that the issue
is only on adding books -- everything else still works fine.  I don't even
get to select something to add -- as soon as I go to Add Books, it stops
responding.  I just ran the welcome wizard -- no difference.   I will
update Calibre (again) -- but this happened before I updated and was the
reason I updated (thinking it would help).  I hesitate to go through all
the deDRM stuff again since it doesn't seem like the program even gets to
that point -- it just stops before I can even select a book to add.

**Comment by ElleKayEm** [comment]
I don't know.  Did you ask over in the calibre forum over at MobileRead?  I assume this isn't a DeDRM issue, is it?  Or can you add books with DeDRM disabled?

**Comment by crisco111** [comment]
I don't think it's a deDRM issue really, since I don't even get to select a
book before it comes to a grinding halt.  I don't know how to disable the
deDRM -- as I said, I'm not too computer literate, and I just followed the
instructions several years ago and all has been great.  I'll try the
MobileRead forum.  Thanks.

**Comment by ElleKayEm** [comment]
I don't have calibre available right now.  But I think you can disable the plugins from the plugins window somewhere.  But I think it is some issue with calibre itself.
