### ISSUE TITLE
The plugin is invalid for Calibre

### ISSUE THREAD

**Issue by zxdawn** [apprenticeharper/DeDRM_tools#1218]
Here's the error when I tried to install the plugin to Calibre V4.23.0:

```
calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'E:\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'E:\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by ElleKayEm** [comment]
You're not loading the plugin.  Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

**Comment by zxdawn** [comment]
Sorry for the stupid question ... Close now.
