### ISSUE TITLE
I can't Convert awz4 book suing calibre, it says ValueError: No embedded PDF found in AZW4 file

### ISSUE THREAD

**Issue by Ravikshukla** [apprenticeharper/DeDRM_tools#1225]
calibre, version 4.23.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (25 Years UPSC IAS/ IPS Prelims Topic-wise Solved Papers 1 & 2 (1995-2019) 10th Edition)

Convert book 1 of 1 (25 Years UPSC IAS/ IPS Prelims Topic-wise Solved Papers 1 & 2 (1995-2019) 10th Edition)
Conversion options changed from defaults:
  pdf_serif_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\rvish\\AppData\\Local\\Temp\\calibre_vnq9kb\\8aimig.jpeg'
  read_metadata_from_opf: u'C:\\Users\\rvish\\AppData\\Local\\Temp\\calibre_vnq9kb\\4aliil.opf'
  output_profile: u'generic_eink'
  pdf_sans_family: u'MS Shell Dlg 2'
  verbose: 2
Resolved conversion options
calibre version: 4.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\rvish\\AppData\\Local\\Temp\\calibre_vnq9kb\\8aimig.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04EDF390>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x04EDF590>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\rvish\\AppData\\Local\\Temp\\calibre_vnq9kb\\4aliil.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Python function terminated unexpectedly
  No embedded PDF found in AZW4 file (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1095, in run
  File "site-packages\calibre\ebooks\azw4\reader.py", line 26, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre.  We'll need to see an import log to figure out if that's the issue.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Ravikshukla** [comment]
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 101.07357513
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
[1.91] main UI initialized...
[1.91] Hiding splash screen
[16.34] splash screen hidden
[16.34] Started up in 16.34 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x87yv\x99\xfe\x92W\xa9\x8f\xb3\x99\x13m\xe6f\xad\xc4F\x95\x02e<|nO\xec\xad\xa1\xf8\xcdf\xff', 'C:\\Users\\rvish\\Documents\\My Kindle Content\\B07T7H66XD_EBOK.azw4']
DeDRM v6.8.0: Trying to decrypt B07T7H66XD_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: 25 Years UPSC IAS/ IPS Prelims Topic-wise Solved Papers 1 & 2 (1995-2019) 10th Edition
Got DSN key from database default_key
Found 4 keys to try after 6.9 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 6.9 seconds
searching for kinfoFiles in C:\Users\rvish\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\rvish\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1454966506' and UserName '7276697368'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
DeDRM v6.8.0: Ultimately failed to decrypt after 7.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 7.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 25 Years UPSC IAS/ IPS Prelims Topic-wise Solved Papers 1 & 2 (1995-2019) 10th Edition to db in: 7.9
Added 1 books in 16.2 seconds

**Comment by ElleKayEm** [comment]
The key that DeDRM is finding isn't the right one for this book.  Was it downloaded with the current installation of Kindle for PC on the same machine and user as calibre with DeDRM?

**Comment by Ravikshukla** [comment]
yes it was downloaded with the same installation, but I had also downloaded the sample book previously, is that what is causing the problem? How do I solve the issue?

**Comment by ElleKayEm** [comment]
No, downloading a sample shouldn't be a problem.  You should be able to decrypt the sample or the full book.  Maybe the key DeDRM is finding is from a previous installation?  Is this a purchased book or a rental?

**Comment by Ravikshukla** [comment]
I have purchased this book.
I had downloaded the sample book before purchasing the book though.

**Comment by ElleKayEm** [comment]
I'd try removing the book from Kindle for PC and redownloading.  Remove previous copy and add this new copy to calibre.

If that doesn't do it, the next step is to do a complete uninstall and reinstall of Kindle for PC.  See these instructions:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

Looks like you have Kindle for PC version 1.17 installed now.  If you don't still have the setup file for that, scroll down on the first post here for info on "Obtaining and verifying Kindle for PC/Mac software":

https://www.mobileread.com/forums/showthread.php?t=283371
