### ISSUE TITLE
Failure to convert one particular AZW3 book

### ISSUE THREAD

**Issue by chrisisbd** [apprenticeharper/DeDRM_tools#1226]
I am running Calibre 4.23 with dedrm 6.8.0, this is a recent update to my installation because I had to back out from the latest (beta) version of Calibre that my distribution had installed as it tries to use Python 3 and that doesn't work with dederm.

So I installed 4.23 from the Calibre site and installed the latest dedrm.  It successfully removed DRM from one AZW3 file but not from a second one.  I've no more to try at the moment.

The log of the conversion with the error at the end is:-
```
Convert book 1 of 1 (Hitler)
Conversion options changed from defaults:
  output_profile: u'kindle'
  verbose: 2
  read_metadata_from_opf: u'/tmp/calibre_4.23.0_tmp_akUrCE/3J95_d.opf'
  cover: u'/tmp/calibre_4.23.0_tmp_akUrCE/RFCvYY.jpeg'
Resolved conversion options
calibre version: 4.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/tmp/calibre_4.23.0_tmp_akUrCE/RFCvYY.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7faf34485c90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7faf3448f390>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/tmp/calibre_4.23.0_tmp_akUrCE/3J95_d.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /tmp/calibre_4.23.0_tmp_akUrCE/BIQLm4.azw3
Found KF8 MOBI of type u'standalone'
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Hitler
```

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre.  Here's how to get the log we need to figure out what's going on:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by chrisisbd** [comment]
Oops, a complete retry of the whole process fixed the problem.  I.e. I deleted the book from Calibre and re-downloaded it and requested the conversion and it worked.  I don't understand where it was finding that MOBI input from.

Anyway it was basically finger trouble of some sort, probably due to my uninstall/reinstall of Calibre.

Sorry for the noise.

**Comment by ElleKayEm** [comment]
Sometimes that's all it takes.  If you're all set, you can close the issue.
