### ISSUE TITLE
DRM Removal stopped working

### ISSUE THREAD

**Issue by jwynia** [apprenticeharper/DeDRM_tools#1227]
Plugin used to work on the computer in question. I recently tried to update my library with books I'd bought in the last few months. DRM removal failed. I re-installed the latest Calibre, uninstalled and reinstalled the plugins and double-checked the serial number setup. I have serial numbers for both an Oasis and a Paperwhite entered in. The books were downloaded from Amazon for USB transfer with the Paperwhite selected as the destination device.

Debug log below:

calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.18] main UI initialized...
[1.18] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt Evocative Objects.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Evocative Objects
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[6.49] splash screen hidden
[6.49] Started up in 6.49 seconds with 866 books
Added Evocative Objects to db in: 0.0
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
Only two possibilities: either the serial number is not entered correctly or a different device was chosen when downloading from the website.

**Comment by jwynia** [comment]
I don't disagree, but that's why I'm puzzled. I literally copied and pasted the serial number from Calibre into my script for running https://github.com/ch33s3w0rm/kindle_dedrm and it worked on the same downloaded books. For now, I can just run that script. I'm just trying to figure out how to fix it in Calibre as well as it's easier to not have to do the scripting step when grabbing my books.

**Comment by ElleKayEm** [comment]
I don't know of anything else it could be.

**Comment by edent** [comment]
I've had the same issue. The old version works well. It generates 2 PIDs. The 2nd PID is the same as the one generated by the DeDRM code - and doesn't work.

The 1st PID works if I use it with the DeDRM script.
