### ISSUE TITLE
Can't remove DRM of KFX file downloaded from Kindle PW3

### ISSUE THREAD

**Issue by duckdodger** [apprenticeharper/DeDRM_tools#1235]
Hello, I just purchased a book and wanted to modify the alignment of the ebook (since it seems to be hardcoded). Found this tool, I entered the serial number correctly in the customization options and tried everything I could, but I'm not able to open the ebook in Calibre. I have pasted the log below:

```calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 78.9126213592 x 77.9318181818
Using calibre Qt style: False
[0.00] Starting up...
[0.00] Showing splash screen...
[0.80] splash screen shown
[0.80] Initializing db...
[0.81] db initialized
[0.81] Constructing main UI...
[2.69] main UI initialized...
[2.69] Hiding splash screen
Storage number map:
{(7L, 0L): [(3L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\G090KB0383120FB8&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=3)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#g090kb0383120fb8&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.0 USBMS: scan from root False D:\documents
DEBUG:    0.0 USBMS: count found in cache: 12, count of files in metadata: 12, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 12
DeviceJob: set_books_in_library finished: time= 0.00399994850159
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[14.95] splash screen hidden
[14.95] Started up in 14.95 seconds with 10 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x9e\x9fq9\xa5^?[:\xf2\xa4\x83V\xc3\xaav\x9a*\x1d6\xb3[\xeb\xc5m\x1a\xefW\xfdtH\xa7', 'C:\\Users\\harik\\OneDrive\\Documents\\Fooled by Randomness_ The Hidden Role of Chance in Life and in the Markets_B002RI9BH6.kfx']
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\harik\OneDrive\Documents\Fooled by Randomness_ The Hidden Role of Chance in Life and in the Markets_B002RI9BH6.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\harik\AppData\Local\Temp\calibre_khsptq\6a0nfs.kfx-zip
DeDRM v6.8.0: Trying to decrypt 6a0nfs.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 6a0nfs
Found 1 keys to try after 0.1 seconds
DeDRM v6.8.0: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\harik\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\harik\AppData\Local\Temp\calibre_khsptq\6a0nfs.kfx-zip
Processing container: Fooled by Randomness_ The Hidden Role of Chance in Life and in the Markets_B002RI9BH6.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container Fooled by Randomness_ The Hidden Role of Chance in Life and in the Markets_B002RI9BH6.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\harik\AppData\Local\Temp\calibre_khsptq\zg6v1e_add_books\0\Fooled by Randomness_ The Hidden Role of Chance in Life and in the Markets_B002RI9BH6.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Fooled by Randomness The Hidden Role of Chance in Life and in the Markets B002RI9BH6 to db in: 0.1
Added 1 books in 1.8 seconds
Worker Launch took: 0.150000095367
```

**Comment by ElleKayEm** [comment]
You won't be able to decrypt a KFX format book which was downloaded to a Kindle.  If it is an E-ink Kindle, you can download a copy from the website in the older format and decrypt that.  Details and other options here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by duckdodger** [comment]
> You won't be able to decrypt a KFX format book which was downloaded to a Kindle. If it is an E-ink Kindle, you can download a copy from the website in the older format and decrypt that. Details and other options here:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371

Ah I see, thanks! I'll see if I can find the older format and decrypt it.
