### ISSUE TITLE
Unable to convert AZW file

### ISSUE THREAD

**Issue by luminiera** [apprenticeharper/DeDRM_tools#1237]
Using Kindle 1.17 for PC, downloaded an AZW file and imported it into Calibre 4.23 with DeDrm 6.8.0 straight from the library it was downloaded in (C:\Users\Ryan\Documents\My Kindle Content). Attempting to convert it to any file format results in a DRM error. I'm guessing my keys aren't being imported or something on import? Import log below. 

Thank you for the help.

> calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.11] main UI initialized...
[1.11] Hiding splash screen
[38.12] splash screen hidden
[38.12] Started up in 38.12 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:/Users/Ryan/Documents/My Kindle Content/B06WVLVWT2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B06WVLVWT2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cancer Immunotherapy Principles and Practice
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Ryan\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Ryan\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3260756204' and UserName '5279616e'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cancer Immunotherapy Principles and Practice
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Cancer Immunotherapy Principles and Practice to db in: 0.2
Added 1 books in 1.3 seconds

**Comment by luminiera** [comment]
It was a rented book. Oops.
