### ISSUE TITLE
Amazon Ebook does not convert in Calibre

### ISSUE THREAD

**Issue by joejohn1492** [apprenticeharper/DeDRM_tools#1242]
Samsung	LAPTOP-NPQX411 Windows 10
OS Name	Microsoft Windows 10 Home
Version	10.0.19041 Build 19041
Purchased ebook from Amazon

This is the log file:
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 105.558441558 x 105.103448276
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
Ignoring blacklisted device: The \\?\usb#vid_04e8&pid_6860&ms_comp_mtp&samsung_android#8&39572c2f&1&0000#{6ac27878-a6fa-4155-ba85-f98f491d4f33} device has been blacklisted by the user
[2.66] main UI initialized...
[2.66] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
[56.03] splash screen hidden
[56.05] Started up in 56.05 seconds with 395 books
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
DeDRM v6.7.0: Trying to decrypt B01AI5I8Y6_EBOK.prc
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Catholic Study Bible
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Joseph Alvarez\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v6.7.0: Trying to decrypt B003ODIZL6_EBOK.prc
DeDRM v6.7.0: Trying to decrypt B01069X4H0_EBOK.prc
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: The 7 Habits of Highly Effective People
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Joseph Alvarez\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Decrypting Mobipocket 7 ebook: The New Oxford American Dictionary
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.7.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.7.0: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Joseph Alvarez\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Catholic Study Bible to db in: 0.9
Added The 7 Habits of Highly Effective People to db in: 0.6
Added The New Oxford American Dictionary to db in: 0.6
Added 3 books in 4.2 seconds
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Worker Launch took: 0.171000003815
Job: 0 Convert book 1 of 1 (The Catholic Study Bible) finished
Convert book 1 of 1 (The Catholic Study Bible)
	Conversion options changed from defaults:
	  output_profile: u'nook_hd_plus'
	  verbose: 2
	  cover: u'C:\\Users\\JOSEPH~1\\AppData\\Local\\Temp\\calibre_umnpez\\nxl2rk.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\JOSEPH~1\\AppData\\Local\\Temp\\calibre_umnpez\\prtx_d.opf'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\JOSEPH~1\\AppData\\Local\\Temp\\calibre_umnpez\\nxl2rk.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x053273B0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.NookHD object at 0x05327890>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\JOSEPH~1\\AppData\\Local\\Temp\\calibre_umnpez\\prtx_d.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\JOSEPH~1\AppData\Local\Temp\calibre_umnpez\mvb3vb.prc
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  The Catholic Study Bible (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: The Catholic Study Bible

Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'E')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400&ms_comp_mtp&samsung_android devinst=1)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x05131850>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 201, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...

**Comment by ElleKayEm** [comment]
First, update to DeDRM 6.8.0.  If you have an E-ink Kindle (not a Fire), you can download your book from the website choosing that for the device.  Enter the Kindle's serial number into the DeDRM customization.  If not, you'll need to install Kindle for PC on the same machine and user as calibre with DeDRM.  With this method, you'll either need to disable downloads of KFX format or you'll need Kindle for PC version 1.26 or earlier and to install the KFX Input plugin.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
