### ISSUE TITLE
I get a problem with 32 and 64 bits in every version I use what to do

### ISSUE THREAD

**Issue by apeas1** [apprenticeharper/DeDRM_tools#1246]
> calibre 5.0.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: es
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 202, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 167
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Use calibre 4.23.  DeDRM is not compatible with calibre 5 yet.

**Comment by apeas1** [comment]
> Use calibre 4.23. DeDRM is not compatible with calibre 5 yet.

nowhere I look lets me download 4.23 , only 5.0.1 even if it says 4.23

**Comment by ElleKayEm** [comment]
https://download.calibre-ebook.com/4.23.0/

**Comment by apeas1** [comment]
> https://download.calibre-ebook.com/4.23.0/
It worked, thanks a lot
