### ISSUE TITLE
DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by stanhirose** [apprenticeharper/DeDRM_tools#1250]
I tried loading version 6.8  of DeDRM_tools_6.8.0.zip and got the error below. I am using version 5.0 of Calibre on Windows 10 home ver. 2004. 

Is there an update for version 6.8?

Stan
----------------------
calibre, version 5.0.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\stanh\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.0  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 193, in load
  File "site-packages\calibre\customize\zipplugin.py", line 289, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\stanh\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
First, DeDRM is not compatible with calibre 5 yet.  So you will need the previous version 4.23 of calibre.  Second, you're trying to load the whole archive.  Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.
