### ISSUE TITLE
6.8.0 install in Calibre 5.0.1

### ISSUE THREAD

**Issue by aquastor** [apprenticeharper/DeDRM_tools#1252]
When attempting to install DeDRM_Plugin.zip using "Load plugin from file", I get a syntax error on line 180:

calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by aquastor** [comment]
It looks like my copy/paste wasn't correct. Here's the corrected version. Thanks!

calibre, version 5.0.1
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
DeDRM is not compatible with calibre 5 yet.  Use calibre 4.23 for now.

**Comment by aquastor** [comment]
Thanks!
