### ISSUE TITLE
DeDRM_Plugin.zip doesn't work with Calibre 5.01

### ISSUE THREAD

**Issue by noversioncontrol** [apprenticeharper/DeDRM_tools#1253]
DeDRM_Plugin.zip doesn't load/work with Calibre 5.01.  Calibre Library 5.x swiched to python 3.x and the plugin no longer shows up.  If I roll back to Calibre 4.23 then the plugin shows up and loads fine.

**Comment by ElleKayEm** [comment]
Yes, that's correct.  Python 3 compatibility is being worked on.

**Comment by Geremia** [comment]
@ElleKayEm How much code has to be ported?

**Comment by ElleKayEm** [comment]
Not sure how much work is left.  People have been working on it for some time since beta versions of calibre with Python 3 have been available (and often included with Linux distros) for a while now.  Now that calibre 5 has been released and Apprentice Harper is active here again progress should be relatively steady.

**Comment by PiperKev** [comment]
I downloaded and used the latest "master" branch version of the tool this morning, and it appears to work with calibre 5.0.1 now, at least on my Linux Mint 20 OS.  The plugin shows up as DeDRM 7.0.0 in my list of plugins.  I tested it on a book that I knew was DRMed, and it failed to convert when I disabled the plugin but converted fine after re-enabling it.  Well done!!

**Comment by sehlat** [comment]
I just downloaded and used the current "master" branch version.  I checked it using a book known to me to have DRM (the earlier version could not deal with it) and it worked with Calibre 5.0.1.  My system runs Windows 7. and I'm seeing DeDRM 7.0.0 in the "File Type" list on my copy. Many thanks to all who are working to keep this irreplaceable add-on working.

**Comment by hub2git** [comment]
> I downloaded and used the latest "master" branch version of the tool this morning, and it appears to work with calibre 5.0.1 now, at least on my Linux Mint 20 OS. The plugin shows up as DeDRM 7.0.0 in my list of plugins. I tested it on a book that I knew was DRMed, and it failed to convert when I disabled the plugin but converted fine after re-enabling it. Well done!!

@PiperKev I'm on Cinnamon Linux Mint 20. Could you share the URL to the "master" branch dedrm.zip file that works with Calibre 5? Thanks.

**Comment by PiperKev** [comment]
> > I downloaded and used the latest "master" branch version of the tool this morning, and it appears to work with calibre 5.0.1 now, at least on my Linux Mint 20 OS. The plugin shows up as DeDRM 7.0.0 in my list of plugins. I tested it on a book that I knew was DRMed, and it failed to convert when I disabled the plugin but converted fine after re-enabling it. Well done!!
> 
> @PiperKev I'm on Cinnamon Linux Mint 20. Could you share the URL to the "master" branch dedrm.zip file that works with Calibre 5? Thanks.


https://github.com/apprenticeharper/DeDRM_tools/tree/master/DeDRM_plugin

**Comment by hub2git** [comment]
@PiperKev I'm downloaded that master.zip. It appears as "DeDRM_tools-master.zip". I extract that zip file and then when I enter the folder, I see a DeDRM_tools-master/DeDRM_plugin subfolder. Calibre doesn't seem to load plugins when they're in "folder form". Calibre needs a zip file. 

I don't see a DeDRM_plugin.zip file within. :(

**Comment by PiperKev** [comment]
> @PiperKev I'm downloaded that master.zip. It appears as "DeDRM_tools-master.zip". I extract that zip file and then when I enter the folder, I see a DeDRM_tools-master/DeDRM_plugin subfolder. Calibre doesn't seem to load plugins when they're in "folder form". Calibre needs a zip file.
> 
> I don't see a DeDRM_plugin.zip file within. :(

Ah, sorry!  You'll have to zip the contents of the "DeDRM_plugin" folder, and then you can install the plugin using the normal "Preferences - plugins" window.

**Comment by junefish** [comment]
The "master" link above doesn't work for me with Calibre 5.0.1 on Windows 10-64.

**Comment by PiperKev** [comment]
> The "master" link above doesn't work for me with Calibre 5.0.1 on Windows 10-64.

Did you zip the contents of the "DeDRM_plugin" folder and try adding it that way?

**Comment by hub2git** [comment]
> > @PiperKev I'm downloaded that master.zip. It appears as "DeDRM_tools-master.zip". I extract that zip file and then when I enter the folder, I see a DeDRM_tools-master/DeDRM_plugin subfolder. Calibre doesn't seem to load plugins when they're in "folder form". Calibre needs a zip file.
> > I don't see a DeDRM_plugin.zip file within. :(
> 
> Ah, sorry! You'll have to zip the contents of the "DeDRM_plugin" folder, and then you can install the plugin using the normal "Preferences - plugins" window.
I tried doing that and here's the error message:

calibre, version 5.0.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/Downloads/DeDRM_tools-master/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.0.1  embedded-python: True is64bit: True
Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-48-generic', '#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && Package KFX (from KFX Input) (1, 34, 0) && Annotations (1, 12, 0) && EpubCheck (0, 2, 3) && Extract ISBN (1, 5, 0) && Find Duplicates (1, 7, 2) && Goodreads (1, 5, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 2, 15) && Kobo Books (1, 8, 0) && Kobo Utilities (2, 11, 5) && KoboTouchExtended (3, 2, 15) && Modify ePub (1, 4, 1) && Obok DeDRM (6, 7, 0) && Quality Check (1, 10, 1) && Recoll Full Text Search (1, 0, 1)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 193, in load
  File "site-packages/calibre/customize/zipplugin.py", line 289, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/Downloads/DeDRM_tools-master/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by PiperKev** [comment]
> > > @PiperKev I'm downloaded that master.zip. It appears as "DeDRM_tools-master.zip". I extract that zip file and then when I enter the folder, I see a DeDRM_tools-master/DeDRM_plugin subfolder. Calibre doesn't seem to load plugins when they're in "folder form". Calibre needs a zip file.
> > > I don't see a DeDRM_plugin.zip file within. :(
> > 
> > 
> > Ah, sorry! You'll have to zip the contents of the "DeDRM_plugin" folder, and then you can install the plugin using the normal "Preferences - plugins" window.
> 
> I tried doing that and here's the error message:
 
Well, crap!  Do you have an email address where I can send you the .zip file that worked for me?

**Comment by hub2git** [comment]
@PiperKev Could you upload it on your github and share the link here? :)

**Comment by PiperKev** [comment]
> @PiperKev Could you upload it onto your github and share the link here? :)

Ah, I didn't realize I could do that!  I'm not that experienced with github!  ;-)  Hope this works!

[DeDRM_plugin.zip](https://github.com/apprenticeharper/DeDRM_tools/files/5295617/DeDRM_plugin.zip)

**Comment by ElleKayEm** [comment]
@hub2git 
Not that it matters now that PiperKev has shared this...but did your DeDRM_plugin.zip contain a DeDRM_plugin folder inside it, instead of just that folder's contents?

**Comment by hub2git** [comment]
> 
> 
> @hub2git
> Not that it matters now that PiperKev has shared this...but did your DeDRM_plugin.zip contain a DeDRM_plugin folder inside it, instead of just that folder's contents?

@ElleKayEm  I'm not on my Linux Mint computer right now. I'm on a Windows 10 computer. I zipped the DeDRM_plugin folder inside the zip and it's still producing an error.

@PiperKev Your attached zip file works! Thanks. :)

**Comment by PiperKev** [comment]
> > 
> @PiperKev Your attached zip file works! Thanks. :)
> 
> UPDATE: Hi @ElleKayEm, PiperKiev's zip file, as you'll see, does not have a folder that holds all the files.

That's awesome!  Glad I could help!

**Comment by ElleKayEm** [comment]
Yes, PiperKev's file is a zip of the contents only of the DeDRM_Plugin folder, no folder inside the zip.

**Comment by hub2git** [comment]
I can check tomorrow whether my Linux computer created a folder within the zip file.

**Comment by PiperKev** [comment]
A HUGE "Thank you" to everyone who made this plugin work with calibre 5!!  Your hard work is VERY much appreciated!!

**Comment by noversioncontrol** [comment]
the 7.0 Plugin works with Calibre 5.01 on Windows 10.  Great work, was not expecting such a fast turn around.  Really apricate you all.

**Comment by JSWolf** [comment]
The 7.0 Plugin does not work with Calibre 5.0.1 under Windows 10. Trying to add a key to the ADE section errors and the DRM is not removed from ePub.

**Comment by hub2git** [comment]
For the exercise, I downloaded the master zip file @PiperKev linked to in [his comment](https://github.com/apprenticeharper/DeDRM_tools/issues/1253#issuecomment-700344733). I then zipped the contents of the DeDRM_plugin folder. I successfully loaded/installed that plugin in Calibre.

Happy to say that it remembered all my Kindle for Mac and PC keys and Adobe Digital Edition keys.

**Comment by ableeker** [comment]
Worked for my too with some Kindle azw(3) books.

**Comment by noversioncontrol** [comment]
Are you using a clean install of Calibre library 5.01 or an upgrade from. 4.x?  If you had 4.x version of  Calibre with a 6.x plugin before you installed 5.01 you need to downgrade to Calibre 4.x, then uninstall the de drm plugin from Calibre.  Then you can upgrade to Calibre 5.01 and  you should then be able to load 7.0 plugin and it should work.

On September 29, 2020 10:43:45 AM EDT, JSWolf <notifications@github.com> wrote:
>The 7.0 Plugin does not work with Calibre 5.0.1 under Windows 10.
>Trying to add a key to the ADE section errors and the DRM is not
>removed from ePub.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/apprenticeharper/DeDRM_tools/issues/1253#issuecomment-700753982

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by caelestiie** [comment]
Hello all, just putting in my recent experience of the 7.0 DeDRM not working. I have Calibre 5.01 and Windows 10 and I was trying to strip a B&N epub

> calibre Debug log
calibre 5.0.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\gcalv\\AppData\\Roaming\\calibre\\plugins\\Read MP3 AudioBook metadata.zip'
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Goodreads (1, 5, 1) && Obok DeDRM (6, 5, 4) && Resize Cover (1, 1, 0)
calibre 5.0.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Goodreads (1, 5, 1) && Obok DeDRM (6, 5, 4) && Resize Cover (1, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
{'default': True, 'height': 680, 'width': 450}
Resize Covers::rebuild_menus - size_data={'default': True, 'height': 680, 'width': 450}
[1.26] main UI initialized...
[1.26] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.28:  0.814) _startup_on_demand listening on port 9090
SMART_DEV (   1.32:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.34:  0.000) _startup_on_demand broadcast socket listening on port 54982
[2.83] splash screen hidden
[2.83] Started up in 2.83 seconds with 321 books
DeDRM v7.0.0: Trying to decrypt 9780062931788.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Error 'a bytes-like object is required, not 'str'' when checking zip archive
SMART_DEV (   2.37:  1.007) run All IP addresses {'{A71C8BCB-29F1-4108-A246-1FAC206347F4}': [{'addr': '192.168.1.185', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{8A05ED06-ECF3-11E7-9A7A-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'i!\xdcG\x82\xd5\xa6(\x14\xd1s\xd5\xa2AYGA\x18@\x9e%*\x81\xdcB\xf71`\xa3\xff\x80\xf6', b'C:\\Users\\gcalv\\AppData\\Local\\Packages\\BarnesNoble.Nook_ahnzqzva31enc\\LocalState\\9780062931788.epub']
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 203, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 50, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 683, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 709, in _GetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 752, in _RealGetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 289, in __init__
TypeError: a bytes-like object is required, not 'str'

**Comment by Zigrang** [comment]
Still doesn't work for me for Adobe .epub books. Removed v.6.8.0 plugin, uninstalled Calibre v.4.2.3, upgraded to Calibre v. 5.0.1, installed plugin v.7.0.0, but still DRM persists, as unable to edit cover of books. Also note that Calibre v.5.0.1 doesn't show the correct cover of an added book initially.

**Comment by ElleKayEm** [comment]
Anyone having problems with DeDRM 6.8.0 in calibre 4.23, start your own issue and I'll take a look.

**Comment by JSWolf** [comment]
> 
> Are you using a clean install of Calibre library 5.01 or an upgrade from. 4.x? If you had 4.x version of Calibre with a 6.x plugin before you installed 5.01 you need to downgrade to Calibre 4.x, then uninstall the de drm plugin from Calibre. Then you can upgrade to Calibre 5.01 and you should then be able to load 7.0 plugin and it should work.
> […](#)
> On September 29, 2020 10:43:45 AM EDT, JSWolf ***@***.***> wrote: The 7.0 Plugin does not work with Calibre 5.0.1 under Windows 10. Trying to add a key to the ADE section errors and the DRM is not removed from ePub. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#1253 (comment)](https://github.com/apprenticeharper/DeDRM_tools/issues/1253#issuecomment-700753982)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

I renamed my settings directory so I would be starting with a clean Calibre 5.0.1 and DeDRM 7.0 does not work. There is no way to save the ADE key. It's buggered and still needs fixing.

**Comment by Transformatiecoach** [comment]
The 7.0 DeDRM_plugin.zip from PiperKev got installed within Calibre 5.01 on Windows 10

However, it didn't removed DRM from an e-book that I've got from the library as an .acsm
It opens fine as an epub with adobe digital editions 4.5
But I can't open it with Calibre

I have done all these steps:
 - Remove the DRMed book from calibre.
 - Click the Preferences drop-down menu and choose 'Restart in debug mode'.
 - Once calibre has re-started, import the problem ebook.
 - Now close calibre

Here is the log, hope someone can help me out:

calibre Foutopsporingslog
calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: DeDRM (7, 0, 0)
calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: DeDRM (7, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.78] splash screen shown
[0.78] Initializing db...
[0.80] db initialized
[0.80] Constructing main UI...
Key 'B' for shortcut Browse annotations is already used by Boeken bijschaven, ignoring
[1.69] main UI initialized...
[1.69] Hiding splash screen
Starting QuickView
[2.98] splash screen hidden
[2.98] Started up in 2.98 seconds with 308 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'V\xa6\xe4:olY\xb7wA\xed\xf9)|\xc7\xb1\x0c+\xc5\x1b\xc6\xe8\x8e\xec\xe2\x99\xf5\xb6\xf6\x94\xfd\x9e', b'C:\\Users\\Transformatiecoach\\Documents\\My Digital Editions\\Doordenken over dooddoeners.epub']
DeDRM v7.0.0: Trying to decrypt Doordenken over dooddoeners.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Error 'a bytes-like object is required, not 'str'' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 203, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 50, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 683, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 709, in _GetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 752, in _RealGetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 289, in __init__
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 207, in ePubDecrypt
Exception: a bytes-like object is required, not 'strAdded Doordenken over dooddoeners to db in: 1.2
Added 1 books in 3.0 seconds

**Comment by ElleKayEm** [comment]
@Transformatiecoach 
Not working yet with pre-release DeDRM 7, and these tools are intended for purchased books.

**Comment by Transformatiecoach** [comment]
> @Transformatiecoach
> Not working yet with pre-release DeDRM 7, and these tools are intended for purchased books.

Understandable.

**Comment by JSWolf** [comment]
> 
> 
> @Transformatiecoach
> Not working yet with pre-release DeDRM 7, and these tools are intended for purchased books.

But it's not working on Purchased ePub. In fact, if you install 7.0 from a fresh Calibre 5.0.1, you cannot even get the key as it crashes when you try to save the key. 7.0 should never have been released even for testing because it's not even alpha level.

**Comment by ElleKayEm** [comment]
@JSWolf 
There's been no release for testing.  It's a complete work-in-progress that's been going on for a while.  People are just jumping on it now because of the release of calibre 5.

**Comment by Transformatiecoach** [comment]
> @JSWolf
> There's been no release for testing. It's a complete work-in-progress that's been going on for a while. People are just jumping on it now because of the release of calibre 5.

Thank you, that made it clear for me. I can read the book now in calibre reader without any problem.
This is what I did:
- uninstalled Calibre 5.01
- reinstalled  Calibre 4.23
- Installed the 6.8.0 DeDRM_Plugin from here (https://github.com/apprenticeharper/DeDRM_tools/releases/)
- imported the book again
et voilla I can read it now with calibre :-)

So I will wait to use calibre 5 until the new DeDRM_Plugin release.
Thanks for all this great work.

**Comment by xythrez** [comment]
> Trying to add a key to the ADE section errors and the DRM is not removed from ePub.

I'm not sure if this is the same issue but adding a kindle serial key in the new version adds a newline character to the end of the serial number stored. This was causing issues with decrypting until it was manually removed from dedrm.json.

**Comment by manam4chine** [comment]
> manually removed from dedrm.json

I don't see any json files in the package?

**Comment by xythrez** [comment]
I should probably clarify that this was in the config file `$CALIBRE_CONFIG_DIRECTORY/plugins/dedrm.json`

**Comment by CiccioIV** [comment]
To give my feedback, since DRM removal just worked for me.
Running Calibre 5.3.0 on Windows 10.
I have downloaded the latest master branch on my computer, and unzipped the whole file on my pc.
I've zipped all files within "DeDRM_plugin" folder in a single .zip file (zip root must contain all files, no root folder).
Then, I've installed the plugin in Calibre 5 by selecting the newly created .zip.
I confirm it works, the plugin has succesfully removed the DRM from an .azw file.

**Comment by JSWolf** [comment]
> 
> 
> To give my feedback, since DRM removal just worked for me.
> Running Calibre 5.3.0 on Windows 10.
> I have downloaded the latest master branch on my computer, and unzipped the whole file on my pc.
> I've zipped all files within "DeDRM_plugin" folder in a single .zip file (zip root must contain all files, no root folder).
> Then, I've installed the plugin in Calibre 5 by selecting the newly created .zip.
> I confirm it works, the plugin has succesfully removed the DRM from an .azw file.

But it will not do something even more important. It will not yet remove the DRM from ePub.

**Comment by joaolucasreis** [comment]
Where can I find my Kindle keys for PC? The number I have to put in the plugin.

**Comment by ElleKayEm** [comment]
@joaolucasreis 
If importing books from Kindle for PC, the keys are retrieved automatically as long as K4PC is installed on the same machine and user as calibre with DeDRM.

**Comment by joaolucasreis** [comment]
> @joaolucasreis
> If importing books from Kindle for PC, the keys are retrieved automatically as long as K4PC is installed on the same machine and user as calibre with DeDRM.

But Caliber is not removing DRM. Would K4PC be another plugin?

**Comment by ElleKayEm** [comment]
K4PC is short for Kindle for PC.  See if the info in this post helps:

https://www.mobileread.com/forums/showthread.php?t=283371

If not, start your own issue and post a log of importing a book:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by JSWolf** [comment]
> 
> 
> > @joaolucasreis
> > If importing books from Kindle for PC, the keys are retrieved automatically as long as K4PC is installed on the same machine and user as calibre with DeDRM.
> 
> But Caliber is not removing DRM. Would K4PC be another plugin?

It's not working because the code is broken.

**Comment by JSWolf** [comment]
> 
> 
> Where can I find my Kindle keys for PC? The number I have to put in the plugin.

The plugin gets it. But the plugin doesn't work with KindleforPC5 yet.

**Comment by brashley468** [comment]
Thank you thank you thank you! Just got the .zip installed in Calibre 5 .. and tested it ... it works great! It will NOT install in previous versions of calibre.

**Comment by ElleKayEm** [comment]
Yes, DeDRM 7 will only work in calibre 5 and later, but is still very much a work in progress.  In many cases, it's best to stick with the current DeDRM 6.8 with calibre 4.23.

**Comment by fubar66** [comment]
> Thank you thank you thank you! Just got the .zip installed in Calibre 5 .. and tested it ... it works great! It will NOT install in previous versions of calibre.

How can i download DeDRM 7 ? I am a newbie on this site.

**Comment by ElleKayEm** [comment]
@fubar66 Go to the [main page](https://github.com/apprenticeharper/DeDRM_tools) of this repo.  Click the green Code button.  Choose download zip.   Unzip that and either run make_release.py or zip up the contents of the DeDRM_Plugin folder.  But I strongly suggest just using DeDRM 6.8 (with calibre 4.23) until 7 is officially released.

**Comment by ableeker** [comment]
If somebody would like to try to decrypt ePubs, you can get the current master. However, before you create the plugin, you'll have to change 1 line in file ineptepub.py to make it work with Calibre 5, and Python 3.

Open file ineptepub.py in folder DeDRM_plugin in a text editor and find line 314.
Change it from:
`return long(total)`
To:
`return total`
Zip the files in the folder DeDRM_plugin, making sure all files are in the root of the zip, NOT in a sub folder.
Load the zip in Calibre.

**Comment by SkyyKorat** [comment]
I apologize in advance, ‘cause I have absolutely NO idea what I'm doing at this point...

I’m using Calibre 5.6 on Windows 10 Pro.  I WAS (I think) using DeDRM 6.6.1 or 6.7.
It has ALWAYS WORKED PERFECTLY.  I’m pretty sure I’ve added at LEAST one book I bought to Calibre since September, and had no problem removing the DRM so I could put it on the tablet and read it.

Today I bought a book, put it in Calibre and Got an error.  Went out and downloaded 6.8.1 and tried to install it exactly the way I always have and got:
calibre, version 5.6.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.6  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

I found this discussion and looked through the whole thing, but it may as well be hieroglyphics.  I found a bunch of “it works this way”, “no it doesn’t” and “now it works this way”…

I ran Calibre in debug mode and got a whole FILE of gibberish that didn’t tell me anything.

I’m not sure at this point how badly I’ve got everything screwed up.  Whatever is in Calibre at the moment doesn’t work.  All I want to do is get whatever I need in Calibre so I can get the DRM off the book and read it.  Can someone provide simple, idiot-proof instructions?

**Comment by ElleKayEm** [comment]
@SkyyKorat 
Use calibre 4.23 and DeDRM 6.8.1.

**Comment by SkyyKorat** [comment]
Thanks...  I'm still confused...  I've been using 5.6 since it came out.  And whatever version of the plugin - 6.6.1 maybe?  And it worked FINE...  What changed that it STOPPED working?

I can certainly go back to 4.23 as long as it doesn't do anything bad to the database, but why did the whole Calibre/plug-in I had quit?

**Comment by ElleKayEm** [comment]
DeDRM is still in the process of being re-written to Python 3 which is required for calibre 5.x.  DeDRM 6.8.1 is in Python 2 and calibre 4.23 is the last version it works on.  For calibre 5.x, you can try the beta DeDRM 7.0.0b4.  But it is still a work in progress.

**Comment by SkyyKorat** [comment]
OK.  I didn't have a copy of 4.23 handy but I had 4.3 so I put that on.  It worked, and the book I added is now readable...  
Thanks a lot...

But, I already had the new book in Calibre and when I tried to remove it, I got this:
calibre, version 4.3.0
ERROR: Unhandled exception: <b>SQLError</b>:SQLError: no such module: fts5

calibre 4.3  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\delete.py", line 404, in delete_books
  File "site-packages\calibre\gui2\actions\delete.py", line 378, in do_library_delete
  File "site-packages\calibre\gui2\library\models.py", line 416, in delete_books_by_id
  File "site-packages\calibre\db\cache.py", line 62, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1647, in remove_books
  File "site-packages\calibre\db\backend.py", line 1676, in remove_books
  File "site-packages\calibre\db\backend.py", line 886, in executemany
  File "c:\t\t\apsw-nhrdandw\src\cursor.c", line 1136, in APSWCursor_executemany.sqlite3_prepare
  File "c:\t\t\apsw-nhrdandw\src\statementcache.c", line 386, in sqlite3_prepare
SQLError: SQLError: no such module: fts5

I renamed the old book, created an empty book and put the book back in so that part is working.  But how do I get rid of the earlier copy?  fts5?

**Comment by ElleKayEm** [comment]
Your database from calibre 5 is probably not compatible with that much older of a version of calibre.  Here is [calibre 4.23](https://download.calibre-ebook.com/4.23.0/).

**Comment by JSWolf** [comment]
You can stick with Calibre 5.x as DeDRM 7.0.0b4 is working with Mobi, KF8, and ePub. It does not work with PDF and I do not know what else doesn't work. But given that I only remove the DRM from ePub, KF8, and Mobi, I'm OK. If you are on Windows, you can install the Calibre 4.23 portable version and run that when you need to use DeDRM 6.8.1.

**Comment by lnxme** [comment]
> OK. I didn't have a copy of 4.23 handy but I had 4.3 so I put that on. It worked, and the book I added is now readable...
> Thanks a lot...

You can find al the variants of Calibre 4.23 at [https://download.calibre-ebook.com/4.23.0/](url)

**Comment by SkyyKorat** [comment]
I know y'all are helping and I appreciate it, but I'm getting whiplash.........
I put 4.3 on, 'cause I didn't have a handy 4.23 (I know where they are, I was just too lazy to go get 4.23 since I had 4.3 sitting here)...  If the error is due to the V5 database and 4.3 gets the error, isn't 4.23 ALSO going to get it?
And as far as "sticking with 5.X, I STARTED with 5.X - I was running 5.6 and using plugin 6.6.1 or 6.7 and it WORKED PERFECTLY as recently as 11/29/2020.  Nothing on the box related to Calibre changed between then and 12/20 when it DIDN'T work.
I tried to SWITCH to 6.8.1 at that point and things continued NOT to work...
So I went BACK to 4.3.  
If I go out and get 4.23.0 is THAT version going to work with the database I have and the plugin - which though it came from a zip file that says 6.8.1 insists that it's 6.8.0 when I look at it.  Which version of which thing do I need so everything works normally if that's possible at this point?  If not, I can live without being able to remove books for a while I think.  I'll just rename them to something that I'll know should be removed when I CAN remove them, whenever that is.

**Comment by ElleKayEm** [comment]
Calibre 4.23 is the last version before 5.  Its database is reportedly compatible with calibre 5.  Calibre 5 does not work with any version of DeDRM except the beta DeDRM 7 pre-releases (latest version is 7.0.0b4).  If you had updated calibre past 4.23 and still had DeDRM 6.x, the only way it could have "worked" was if the book was already DRM-free.

Either use calibre 5.x and DeDRM 7.0.0b4.  Or calibre 4.23 and DeDRM 6.8.1.  Just be aware that not everything is working properly yet with DeDRM 7.  I don't know if both or neither will resolve the problem of being unable to delete books after using calibre 4.3.  If not, ask over at the calibre forum at MobileRead.  That is not a DeDRM issue.

**Comment by SkyyKorat** [comment]
That was MY mistake...  I got so fixated on the Calibre/DRM version weirdness that I completely lost sight of the fact that the error I got when deleting had NOTHING to do with DRM...  I presume it's a Calibre version vs database version thing...  I'll have to try again to find the DRM topic over there.  When I looked before coming here I couldn't find it in the Calibre section.

So if I'm understanding you, I can put 5.X on.  In my case it'll be 5.6 since that's what I had working previously.  And I'll put DeDRM 7.0.0b4 on and see...

**Comment by SkyyKorat** [comment]
OK!  Everybody has been happily working for the last week...  Calibre 5.6, the version of DRM stuff that works with it.  Books go in, books are readable, DRM sits there quietly and doesn't annoy the horses, all is normal, quiet, and BORING...  I LIKE boring.
I'm planning on never doing another update!

Thanks for the help.
