### ISSUE TITLE
Failed to deDRM Kindle ebooks

### ISSUE THREAD

**Issue by yohanjo** [apprenticeharper/DeDRM_tools#1256]
Hello. I cannot open Kindle ebooks on Calibre due to the DRM issue.
I made a log of the import process as suggested in DeDRM_plugin_ReadMe.txt:

```
calibre Debug log
calibre 5.0.1  embedded-python: True is64bit: True
macOS-10.15.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
AlfCrypto not found. Using python PC1 implementation.
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
calibre 5.0.1  embedded-python: True is64bit: True
macOS-10.15.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 7, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
[0.83] main UI initialized...
[0.83] Hiding splash screen
Starting QuickView
AlfCrypto not found. Using python PC1 implementation.
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing /Users/yohanjo/Dropbox/Documents/My Kindle Content/B00GHJKAMQ_EBOK/B00GHJKAMQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/tj/srlzxdvd1cl68cbl5__0p97c0000gn/C/calibre_5.0.1_tmp_nyq49efk/trg2m436.kfx-zip
DeDRM v6.7.0: Trying to decrypt trg2m436.kfx-zip
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Using Library AlfCrypto Python
DeDRM v6.7.0: Failed to decrypt with error: Invalid file format
DeDRM v6.7.0: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging /var/folders/tj/srlzxdvd1cl68cbl5__0p97c0000gn/C/calibre_5.0.1_tmp_nyq49efk/trg2m436.kfx-zip
Processing container: B00GHJKAMQ_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/tj/srlzxdvd1cl68cbl5__0p97c0000gn/C/calibre_5.0.1_tmp_nyq49efk/k2ygx48f_add_books/0/B00GHJKAMQ_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 218, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 260, in __init__
calibre_plugins.dedrm.mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v6.7.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00GHJKAMQ_EBOK.azw has DRM and cannot be converted
[14.50] splash screen hidden
[14.51] Started up in 14.51 seconds with 0 books
Added CR!797JVQ6CA12T5E95876ACX13X63P.azw to db in: 0.0
Added 1 books in 0.8 seconds
```

Here's the system info:
 * OS: macOS Catalina 10.15.6 (19G2021)
 * Calibre: 5.0.1
 * Ebook: from Amazon Kindle for Mac 1.29.0
 * Installed plugins:
    * DeDRM from `https://github.com/lalmeras/DeDRM_tools/tree/Python3` on Sep 27
    * Obok v6.8.0 from `https://github.com/apprenticeharper/DeDRM_tools/releases` on Sep 27
    * KFX Input (1.34.0) plugins from within Calibre

**Comment by ElleKayEm** [comment]
For now I would recommend sticking with calibre 4.23 and DeDRM 6.8.0.  You will also need to use Kindle for Mac 1.26 or disable KFX downloads in K4Mac 1.29.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by PiperKev** [comment]
I tried the latest version ("master" branch) of DeDRM Tools, and it seems to work with my installation of calibre 5.0.1 on Linux Mint 20.  I can convert my DRMed azw3 books with no problem.  I made sure the book I tested it with did indeed have DRM, because it wouldn't convert when I disabled the plugin.

**Comment by yohanjo** [comment]
Thank you, @ElleKayEm.
Do you have any plans to support Kindle 1.28?
I can't downgrade my Kindle, because I lost my Amazon account. I'm afraid I may not be able to open my Kindle books at all after reinstalling Kindle.

**Comment by ElleKayEm** [comment]
It is possible to DeDRM the older formats from later versions of the Kindle app.  But if you cannot download new copies after disabling KFX downloads, then that won't work.  Eventually the changes to the KFX format's DRM may be figured out, but without access to the Amazon account your books were purchased with you are probably out of luck.

**Comment by yohanjo** [comment]
I see. Thank you!

**Comment by ElleKayEm** [comment]
If there's nothing else, you can close the issue.
