### ISSUE TITLE
comics

### ISSUE THREAD

**Issue by KOH111** [apprenticeharper/DeDRM_tools#1258]
Is it possible to convert the Nook epubs to no DRM?  The normal epubs convert fine, it's only the graphic novels.

**Comment by ElleKayEm** [comment]
Downloaded with the Windows store app?  Maybe, with some fiddling.  If you can access your books another way (rooted Nook, rooted Android, Android emulator), you might be able to DeDRM those copies just like other epubs.  

Otherwise, here's a comment I wrote at Alf's blog about how I was able to DeDRM some Nook comics:

https://apprenticealf.wordpress.com/2012/09/10/drm-removal-tools-for-ebooks/comment-page-38/#comment-62274

Additional note:  If your rights.xml file has a "permissions" section, just delete everything from the opening to the closing permission tags.

This has worked for me and others in the past (that comment is from a couple years ago), but who knows what may have changed in the meantime.

**Comment by KOH111** [comment]
Thanks, I'll try it

**Comment by KOH111** [comment]
Oh well, it didn't work.  I just got a couple of pages of nonsense characters

**Comment by ElleKayEm** [comment]
I'll take a look at the import log if you like:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by KOH111** [comment]
Thanks.  Do you want the actual books?

Keith


On Wed, 30 Sep 2020 00:34:46 -1000, ElleKayEm <notifications@github.com>  
wrote:

>
> I'll take a look at the import log if you like:  
> https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a->log-how-do-i-do-that
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Using Opera's mail client: http://www.opera.com/mail/
calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 33, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 88.6690909091 x 88.4903225806
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.55] splash screen shown
[0.55] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.64] main UI initialized...
[1.64] Hiding splash screen
[27.88] splash screen hidden
[27.88] Started up in 27.88 seconds with 561 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xeaK~\xa2\xe8\xb1\xdb\x01}\xf8\xf9\xdf/\xb0n\xd5\xb17\xfb\x15{\x8d\x01f\xf3\xd3\xe2\xf7z\xcfK"', 'D:\\temp\\New Compression.epub']
DeDRM v6.8.0: Trying to decrypt New Compression.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “New Compression.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 1.1 seconds. DRM free perhaps?
WARNING: Epub doesn't contain a valid mimetype declaration
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 195, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "site-packages\calibre\ebooks\metadata\epub.py", line 165, in get_zip_reader
  File "site-packages\calibre\ebooks\metadata\epub.py", line 148, in __init__
  File "site-packages\calibre\ebooks\metadata\epub.py", line 102, in __init__
EPubException: missing OCF container.xml file
Added New Compression to db in: 1.2
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
No.

**Comment by ElleKayEm** [comment]
Looks like the book is still missing its rights.xml.

**Comment by KOH111** [comment]
This is what I have:


[New Compression.zip](https://github.com/apprenticeharper/DeDRM_tools/files/5331302/New.Compression.zip)

**Comment by ElleKayEm** [comment]
Somehow things are still not configured in the way they should be, but I don't know what is wrong.  I see the following problems in the log:

> DeDRM v6.8.0: “New Compression.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

> WARNING: Epub doesn't contain a valid mimetype declaration

> EPubException: missing OCF container.xml file

If you have a B&N regular epub that you can DeDRM, maybe you can unzip and take a look at a copy before DRM removal to compare.  It's been quite a while since I successfully removed DRM from one of these comics so things may have changed.

**Comment by KOH111** [comment]
META-INF looks similar, OPS is quite different.  The book includes package.opf, toc.ncx, and a lot of .xhtml's.  The comic includes pub.ncx, pub.opf, replicaMap.xml, and section.xml, and has no .xhtml's. Mimetype is the same.  Maybe the problem is in the zipping?

**Comment by ElleKayEm** [comment]
Possibly.  You don't have any zip folders inside the epub itself?

**Comment by KOH111** [comment]
I thought I responded but it doesn't seem to be here.  

I'm not sure what you mean, I don't see any .zip files

**Comment by KOH111** [comment]
Thanks for trying to help

**Comment by DARK-MASKS** [comment]
DeDRM isn't "seeing" the rights.xml file on mine either when I add my epub to calibre. please help.

**Comment by ElleKayEm** [comment]
Is the rights.xml file in the epub itself?  Did you have to add it like I explained above?

**Comment by DARK-MASKS** [comment]
I put the rights.xml file in the META-INF folder and changed it back to epub and when I added it to Calibre, it gave me a blank cover page and the DRM wasn't removed.

**Comment by ElleKayEm** [comment]
You have your BN key in DeDRM?

**Comment by DARK-MASKS** [comment]
Yeah I got it

**Comment by ElleKayEm** [comment]
Have you tried noDRM's DeDRM? https://github.com/noDRM/DeDRM_tools

**Comment by KOH111** [comment]
Thanks I'll try it

On Wed, 30 Mar 2022 05:11:23 -1000, ElleKayEm ***@***.***>  
wrote:

>
> Have you tried noDRM's DeDRM? https://github.com/noDRM/DeDRM_tools
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.



-- 
Using Opera's mail client: http://www.opera.com/mail/
