### ISSUE TITLE
Failed to deDMR Adobe Digitals

### ISSUE THREAD

**Issue by marcomg** [apprenticeharper/DeDRM_tools#1259]
Calibre 5.0.1 and DeDRM_tools master

calibre Log di debug
calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 0, 0)
calibre 5.0.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 130.03412969283275 x 129.59183673469386
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.69] splash screen shown
[0.69] Initializing db...
[0.69] db initialized
[0.69] Constructing main UI...
Key 'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.42] main UI initialized...
[1.42] Hiding splash screen
Starting QuickView
[11.12] splash screen hidden
[11.12] Started up in 11.12 seconds with 20 books
DeDRM v7.0.0: Trying to decrypt Istruzioni per diventare fascisti.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Error 'a bytes-like object is required, not 'str'' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 203, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 50, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 683, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 709, in _GetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 752, in _RealGetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 289, in __init__
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 207, in ePubDecrypt
Exception: a bytes-like object is required, not 'strAdded Istruzioni per diventare fascisti to db in: 0.3
Added 1 books in 1.8 seconds
Worker Launch took: 0.2813568115234375

**Comment by ElleKayEm** [comment]
If you're not just putting this here as info for the people working on the next release, then use DeDRM 6.8 and calibre 4.23.

**Comment by marcomg** [comment]
Thanks for answering, I did it before reporting the issue (seeing your comment in #1256). But the error was different so I thought may be helpful.

**Comment by ElleKayEm** [comment]
I'm assuming the error above is due to the pre-release state of DeDRM 7.  I'll take a look at problems with DeDRM 6.8 on calibre 4.23 though.

**Comment by hamkg** [comment]
See https://github.com/apprenticeharper/DeDRM_tools/issues/979#issuecomment-700960177
This solution seems to work at least for kindle and epub, windows and linux.
