### ISSUE TITLE
using "masterbranch" dedrm zip in Calibre 5.0.1 successfully decrypts all except one

### ISSUE THREAD

**Issue by hub2git** [apprenticeharper/DeDRM_tools#1260]
I'm on Calibre 5.0.1 on Linux. I'm using the "master" version of dedrm_plugin.zip (as linked to by @piperkev at https://github.com/apprenticeharper/DeDRM_tools/issues/1253#issuecomment-700336041, who shares the zip file directly on a later comment https://github.com/apprenticeharper/DeDRM_tools/files/5295617/DeDRM_plugin.zip)

With this master version of the plugin, Calibre 5.0.1 susccessffully decrypts most of the epubs from Adobe Digital Editions. All except for one. Here is the error message for the problem ebook:

> calibre, version 5.0.1
> ERROR: Loading book failed: Failed to open the book at /home/me/text/calibrelibrary/Unknown/somebook.epub. Click "Show details" for more info.
> 
> Failed to convert book: /home/me/text/calibrelibrary/Unknown/somebook.epub with error:
> DeDRM v7.0.0: Trying to decrypt somebook.epub
> DeDRM v7.0.0: Verifying zip archive integrity
> DeDRM v7.0.0: Error 'can only concatenate str (not "bytes") to str' when checking zip archive
> Failed to initialize plugin: '/home/me/.config/calibre/plugins/Goodreads More Tags.zip'
> InputFormatPlugin: EPUB Input running
> on /home/me/text/calibrelibrary/Unknown/somebook.epub
> WARNING: Header ('OEBPS/images/Reyn_9780307761927_epub_039_r1.jpg') and directory ('OEBPS/images/Reyn_9780307761927_epub\x0bi╟mh╛2\x00√\x7f\r') filenames do not match inside ZipFile
> Using directory filename 'OEBPS/images/Reyn_9780307761927_epub\x0bi╟mh╛2\x00√\x7f\r'
> WARNING: Header ('Reyn_9780307761927_epub_opf_r1.opf') and directory ('Reyn_9780307761927_epub_opwZ╟mî¡2\x00') filenames do not match inside ZipFile
> Using directory filename 'Reyn_9780307761927_epub_opwZ╟mî¡2\x00'
> Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
> Traceback (most recent call last):
> File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
> File "site-packages/calibre/customize/builtins.py", line 194, in get_metadata
> File "site-packages/calibre/ebooks/metadata/epub.py", line 238, in get_quick_metadata
> File "site-packages/calibre/ebooks/metadata/epub.py", line 218, in get_metadata
> File "site-packages/calibre/ebooks/metadata/epub.py", line 156, in read_bytes
> File "site-packages/calibre/utils/zipfile.py", line 1007, in read
> File "site-packages/calibre/utils/zipfile.py", line 1035, in open
> File "site-packages/calibre/utils/zipfile.py", line 996, in getinfo
> KeyError: "There is no item named 'Reyn_9780307761927_epub_opf_r1.opf' in the archive"
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
> File "calibre_plugins.dedrm.zipfix", line 140, in fix
> File "calibre_plugins.dedrm.zipfilerugged", line 826, in read
> File "calibre_plugins.dedrm.zipfilerugged", line 864, in open
> calibre_plugins.dedrm.zipfilerugged.BadZipfile: File name in directory "b'Reyn_9780307761927_epub_opwZ\xc7m\x8c\xad2\x00' " and header "b'Reyn_9780307761927_epub_opf_r1.opf'" differ.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "calibre_plugins.dedrm.__init__", line 204, in ePubDecrypt
> File "calibre_plugins.dedrm.zipfix", line 143, in fix
> File "calibre_plugins.dedrm.zipfix", line 105, in getfiledata
> File "calibre_plugins.dedrm.zipfix", line 78, in uncompress
> TypeError: can only concatenate str (not "bytes") to str
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
> File "calibre_plugins.dedrm.__init__", line 637, in run
> File "calibre_plugins.dedrm.__init__", line 207, in ePubDecrypt
> Exception: can only concatenate str (not "bytes") to str
> Traceback (most recent call last):
> File "runpy.py", line 194, in _run_module_as_main
> File "runpy.py", line 87, in _run_code
> File "site.py", line 48, in <module>
> File "site.py", line 44, in main
> File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
> File "<string>", line 1, in <module>
> File "site-packages/calibre/srv/render_book.py", line 871, in viewer_main
> File "site-packages/calibre/srv/render_book.py", line 862, in render_for_viewer
> File "site-packages/calibre/srv/render_book.py", line 839, in render
> File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 63, in extract_book
> File "site-packages/calibre/customize/conversion.py", line 245, in __call__
> File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 281, in convert
> ValueError: /home/me/text/calibrelibrary/Unknown/somebook.epub is not a valid EPUB file (could not find opf)

**Comment by ElleKayEm** [comment]
Not sure if this is a pre-release DeDRM 7 problem or something wonky with that particular book.  The log says it "is not a valid EPUB file (could not find opf)."  Is it tied to the same Adobe ID as the ones that were successfully decrypted?  From the same source?  Can you read it in ADE authorized with your Adobe ID?

**Comment by hub2git** [comment]
yes, it's the tied to same adobe ID of other books I've successfully decrypted in the same time.
Yes, I can read it in ADE with the Adobe ID.

**Comment by ElleKayEm** [comment]
ADE 2.0.1?

**Comment by ableeker** [comment]
Kindle books decrypt successfully as well.

**Comment by hub2git** [comment]
Yes, @ElleKayEm, ADE 2.0.1.78765.

**Comment by zioalex** [comment]
It works for me on Linux with protect epub files. Thanks for sharing @hub2git

**Comment by yurepluu** [comment]
What is linx? what is masterbranch. please provide instructions.

> Kindle books decrypt successfully as well. The 2 books I've tried anyway. YMMV.

**Comment by yurepluu** [comment]
> It works for me on Linux with protect epub files. Thanks for sharing @hub2git

Explain with instructions

**Comment by yurepluu** [comment]
> It works for me on Linux with protect epub files. Thanks for sharing @hub2git

Please provide instructions to all of this

**Comment by ElleKayEm** [comment]
@hub2git 
Have you tried with DeDRM 6.8 and calibre 4.23?
