### ISSUE TITLE
dedrm master fails to decrypt KFX file

### ISSUE THREAD

**Issue by evildarkarchon** [apprenticeharper/DeDRM_tools#1262]
I was experimenting with dedrm 7.0 in its current state and tryed a kindle ebook downloaded using Kindle for PC v1.26. When I run calibre in debug mode, it gives me the following output.

`Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:\My Kindle Content\B071Z8XRFP_EBOK\B071Z8XRFP_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\evild\AppData\Local\Temp\calibre_eyg1804i\4t3gbc1d.kfx-zip
DeDRM v7.0.0: Trying to decrypt 4t3gbc1d.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.00.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.0.0: Failed to decrypt with error: Invalid file format
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.0.0: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 218, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 261, in __init__
calibre_plugins.dedrm.mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 543, in KindleMobiDecrypt
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dedrm.kindlekey", line 189, in <module>
ModuleNotFoundError: No module named '_winreg'
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\evild\AppData\Local\Temp\calibre_eyg1804i\4t3gbc1d.kfx-zip
Processing container: B071Z8XRFP_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\evild\AppData\Local\Temp\calibre_eyg1804i\6a__m_ui_add_books\0\B071Z8XRFP_EBOK.kfx-zip
Added <ebook title> to db in: 0.1
Added 1 books in 1.0 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 218, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 261, in __init__
calibre_plugins.dedrm.mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B071Z8XRFP_EBOK.azw has DRM and cannot be converted`

**Comment by evildarkarchon** [comment]
Tried again with the latest commits and kfx files still fail to decrypt. I tried 2 strategies, one was to let the plugin try to find the key itself and I got this message:

```
PS C:\Users\evild\source\repos\DeDRM_tools> calibre-debug --gui
calibre 5.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\evild\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 285, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre_plugins.barnes_noble.__init__", line 11, in <module>
ImportError: cannot import name 'quote' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 34, 0) && Consolidate All Library Metadata (2, 0, 37) && EpubCheck (0, 2, 3) && Fantastic Fiction (1, 4, 0) && Fantastic Fiction Adults (1, 2, 0) && Favourites Menu (1, 0, 5) && Find Duplicates (1, 8, 3) && Generate Cover (1, 5, 25) && Goodreads (1, 5, 1) && Goodreads Sync (1, 14, 5) && Hyphenate This! (0, 1, 3) && Job Spy (1, 0, 187) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && KePub Input (3, 2, 10) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 4, 1) && Kindle hi-res covers (0, 5, 0) && Kobo Books (1, 8, 0) && KoboTouchExtended (3, 4, 1) && Manage Series (1, 2, 11) && Modify ePub (1, 6, 1) && MultiColumnSearch (1, 0, 85) && Smashwords Metadata (1, 0, 2) && View Manager (1, 5, 7)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.56] splash screen shown
[1.56] Initializing db...
[1.56] db initialized
[1.56] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
CALM: initialization_complete............
DEBUG:    0.7 HttpHelper::__init__: proxy=None
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
libpng warning: iCCP: known incorrect sRGB profile
Job Spy has finished initialization...
[0] un-optimized number of undesirable characters accumulated:  756
[1] optimized number of undesirable characters accumulated:  596
MCS has finished initialization...
[2.78] main UI initialized...
[2.78] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.19:  0.835) _startup_on_demand listening on port 9090
SMART_DEV (   1.20:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.23:  0.000) _startup_on_demand broadcast socket listening on port 54982
[4.16] splash screen hidden
[4.16] Started up in 4.16 seconds with 0 books
SMART_DEV (   2.25:  1.011) run All IP addresses {'{D65DDC1C-CE84-476B-9F55-EE9C7099B72A}': [{'addr': '192.168.0.114', 'netmask': '255.255.255.0', 'broadcast': '192.168.0.255'}], '{64C58EEF-CA50-11E7-B828-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}], '{FA78B01D-5A83-408E-BDAC-B38CEB7C8551}': [{'addr': '172.23.176.1', 'netmask': '255.255.240.0', 'broadcast': '172.23.191.255'}], '{8FA18ADB-01CB-42A2-834C-21E1F10FAD8A}': [{'addr': '172.22.128.1', 'netmask': '255.255.240.0', 'broadcast': '172.22.143.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe9\xbb`_6\x1fOd"\xd2\x9d/E\xf1\xebW\xafa\xa6L\x1bu\xccq\xb4\xc2El\xc4\x83j1', b'E:\\My Kindle Content\\B07QC4LLRH_EBOK\\B07QC4LLRH_EBOK.azw']
Failed to initialize plugin: 'C:\\Users\\evild\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:\My Kindle Content\B07QC4LLRH_EBOK\B07QC4LLRH_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\evild\AppData\Local\Temp\calibre_8i842yo3\b979qyq7.kfx-zip
DeDRM v7.0.0: Trying to decrypt b979qyq7.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: b979qyq7
Found 0 keys to try after 0.0 seconds
The .kfx-zip archive does not contain an encrypted DRMION file
Decryption succeeded after 0.0 seconds
DeDRM v7.0.0: Finished after 0.1 seconds
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\evild\AppData\Local\Temp\calibre_8i842yo3\qy0881sz.kfx-zip
Processing container: B07QC4LLRH_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\evild\AppData\Local\Temp\calibre_8i842yo3\534rqk_o_add_books\0\B07QC4LLRH_EBOK.kfx-zip
Added Convincing Michael to db in: 0.1
Added 1 books in 0.9 seconds
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07QC4LLRH_EBOK.azw has DRM and cannot be converted
```
and the other was to use the default_key that I exported to a k4i file from calibre 4 portable with version 6.8.0 and I get this error:
```
calibre 5.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\evild\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 285, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre_plugins.barnes_noble.__init__", line 11, in <module>
ImportError: cannot import name 'quote' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 34, 0) && Consolidate All Library Metadata (2, 0, 37) && EpubCheck (0, 2, 3) && Fantastic Fiction (1, 4, 0) && Fantastic Fiction Adults (1, 2, 0) && Favourites Menu (1, 0, 5) && Find Duplicates (1, 8, 3) && Generate Cover (1, 5, 25) && Goodreads (1, 5, 1) && Goodreads Sync (1, 14, 5) && Hyphenate This! (0, 1, 3) && Job Spy (1, 0, 187) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && KePub Input (3, 2, 10) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 4, 1) && Kindle hi-res covers (0, 5, 0) && Kobo Books (1, 8, 0) && KoboTouchExtended (3, 4, 1) && Manage Series (1, 2, 11) && Modify ePub (1, 6, 1) && MultiColumnSearch (1, 0, 85) && Smashwords Metadata (1, 0, 2) && View Manager (1, 5, 7)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[1.55] splash screen shown
[1.55] Initializing db...
[1.55] db initialized
[1.55] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
CALM: initialization_complete............
DEBUG:    0.7 HttpHelper::__init__: proxy=None
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
libpng warning: iCCP: known incorrect sRGB profile
Job Spy has finished initialization...
[0] un-optimized number of undesirable characters accumulated:  756
[1] optimized number of undesirable characters accumulated:  596
MCS has finished initialization...
[2.69] main UI initialized...
[2.69] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.17:  0.838) _startup_on_demand listening on port 9090
SMART_DEV (   1.19:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.21:  0.000) _startup_on_demand broadcast socket listening on port 54982
[4.05] splash screen hidden
[4.05] Started up in 4.05 seconds with 0 books
SMART_DEV (   2.24:  1.010) run All IP addresses {'{D65DDC1C-CE84-476B-9F55-EE9C7099B72A}': [{'addr': '192.168.0.114', 'netmask': '255.255.255.0', 'broadcast': '192.168.0.255'}], '{64C58EEF-CA50-11E7-B828-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}], '{FA78B01D-5A83-408E-BDAC-B38CEB7C8551}': [{'addr': '172.23.176.1', 'netmask': '255.255.240.0', 'broadcast': '172.23.191.255'}], '{8FA18ADB-01CB-42A2-834C-21E1F10FAD8A}': [{'addr': '172.22.128.1', 'netmask': '255.255.240.0', 'broadcast': '172.22.143.255'}]}
searching for kinfoFiles in C:\Users\evild\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\evild\AppData\Local\Amazon\Kindle\storage\.kinf2018
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 780, in __init__
  File "calibre_plugins.dedrm.kindlekey", line 1699, in kindlekeys
  File "calibre_plugins.dedrm.kindlekey", line 1087, in getDBfromFile
TypeError: can't concat str to bytes
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xd1\xf2\xe91uPR\xef\xa5,\x87G\xef\xc1\xc7\x04\x1b \xb8'\x01{\x0co1\x99\x99\x1a\x1d\xa1)\xdc", b'C:\\Users\\evild\\default_key.k4i']
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc1\xbe\xf9A\xc3\x1d\x18\xa7\x1a5\xa0\xd9e`\x91\x10\xe1\xc1\xbf}\xe2\xb5\x05\xe8\x15\xcdg\x1fe\xf1\x95\x88', b'E:\\My Kindle Content\\B07QC4LLRH_EBOK\\B07QC4LLRH_EBOK.azw']
Failed to initialize plugin: 'C:\\Users\\evild\\AppData\\Roaming\\calibre\\plugins\\Barnes & Noble.zip'
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing E:\My Kindle Content\B07QC4LLRH_EBOK\B07QC4LLRH_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\jjaxk6l2.kfx-zip
DeDRM v7.0.0: Trying to decrypt jjaxk6l2.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: jjaxk6l2
Got DSN key from database default_key
DeDRM v7.0.0: Failed to decrypt with error: unhashable type: 'bytearray'
DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\evild\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\evild\AppData\Local\Amazon\Kindle\storage\.kinf2018
DeDRM v7.0.0: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 233, in GetDecryptedBook
TypeError: unhashable type: 'bytearray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 545, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.kindlekey", line 1699, in kindlekeys
  File "calibre_plugins.dedrm.kindlekey", line 1074, in getDBfromFile
  File "calibre_plugins.dedrm.kindlekey", line 835, in UnprotectHeaderData
  File "C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\kvzr9j7yplugin_unzip\alfcrypto.py", line 298, in pbkdf2
  File "C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\kvzr9j7yplugin_unzip\alfcrypto.py", line 286, in pbkdf2_F
  File "C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\kvzr9j7yplugin_unzip\alfcrypto.py", line 274, in xorstr
  File "C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\kvzr9j7yplugin_unzip\alfcrypto.py", line 274, in <genexpr>
TypeError: ord() expected string of length 1, but int found
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\jjaxk6l2.kfx-zip
Processing container: B07QC4LLRH_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\evild\AppData\Local\Temp\calibre_q5m8x7wq\ysastyhz_add_books\0\B07QC4LLRH_EBOK.kfx-zip
Added Convincing Michael to db in: 0.1
Added 1 books in 0.9 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 533, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 233, in GetDecryptedBook
TypeError: unhashable type: 'bytearray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07QC4LLRH_EBOK.azw has DRM and cannot be converted
```

**Comment by ElleKayEm** [comment]
FYI, each Kindle app installation has its own unique key, even if they are logged into the same account.  So the key that works in your calibre 4.23/DeDRM 6.8 setup is specifically for books downloaded with Kindle for PC currently installed on the same machine and user.  So if you're testing an imported key, use books from there too.

**Comment by evildarkarchon** [comment]
I used the same computer and K4PC version (1.26.0) both times and it worked in 6.8.0/calibre 4.23 but didn't work in master (as of the time of the test)/calibre 5.1. I only used the "default_key" shuffle as a diagnostic step. 

I see that some fixes for kindle books have been put into the plugin since my last test but I, unfortunately, won't be able to test them for this issue since I'm no longer using K4PC to download books.
