### ISSUE TITLE
Missing urllib2

### ISSUE THREAD

**Issue by tomdean1939** [apprenticeharper/DeDRM_tools#1273]
calibre 5.0.1  embedded-python: True is64bit: True
Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-48-generic', '#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 598, in retrieve_key
  File "calibre_plugins.dedrm.ignoblekeyfetch", line 112, in fetch_key
ModuleNotFoundError: No module named 'urllib2'

**Comment by ElleKayEm** [comment]
Python 3 compatibility is still a work-in-progress.  And the method for B&N key retrieval in ignoblekeyfetch stopped working a while ago when B&N cut off its old Nook for PC app.

**Comment by tartley** [comment]
Does that mean this issue is a 'wontfix', because we can't fix, without B&N co-operation? Or am I misunderstanding?

**Comment by ElleKayEm** [comment]
Yes, the methods for B&N key retrieval included in DeDRM depended on the old desktop Nook apps which completely stopped working quite a while ago.
