### ISSUE TITLE
[master][Calibre 5.1] Kindle AWZ works, EPUBs do not.

### ISSUE THREAD

**Issue by jasonjunk** [apprenticeharper/DeDRM_tools#1281]
calibre Debug log
calibre 5.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 5.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.99999999999999 x 128.18691588785046
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
Starting QuickView
DeDRM v7.0.0: Trying to decrypt Skyhunter.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Error 'a bytes-like object is required, not 'str'' when checking zip archive
[9.45] splash screen hidden
[9.45] Started up in 9.45 seconds with 1893 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xcf\x16'wVLY\xda\x85\xbc\xffp\xc4 \xafP\xcc\xc6\xe7qf2\x1d\x1fT\x11\xb0\x0e\xa0\xa5I\xd9", b'C:\\Users\\Jason\\Documents\\My Digital Editions\\Skyhunter.epub']
Added Skyhunter to db in: 1.4
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 203, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 50, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 683, in __init__
  File "calibre_plugins.dedrm.zipfilerugged", line 709, in _GetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 752, in _RealGetContents
  File "calibre_plugins.dedrm.zipfilerugged", line 289, in __init__
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 207, in ePubDecrypt
Exception: a bytes-like object is required, not 'strAdded 1 books in 2.1 seconds

**Comment by ElleKayEm** [comment]
It's seems like the script for Adobe key retrieval is not working yet in pre-release DeDRM 7.  It should work on DeDRM 6.8 and calibre 4.23.

**Comment by pengtsin** [comment]
I filed a bug with Calibre and got this response ... (Calibre 4.23 is the last version that supports DeDRM v6.8.0.)

As of calibre 5, calibre has moved from Python 2 to Python 3, because Python 2 has been end-of-lifed.
This means that some third party calibre plugins that have not yet been ported to Python 3 will not work
with calibre 5. If you depend on such a plugin, you will have to either:

1) Wait for the plugin to be ported to Python 3
2) If you are on windows, you can install the last calibre 4.x release using calibre portable and
run the plugin there
3) Downgrade to calibre 4.x until the plugin is ported. You can simply uninstall calibre 5 and install calibre 4.23, doing so
will not affect your books or settings.

**Comment by ElleKayEm** [comment]
@pengtsin 
This issue is in regard to unreleased DeDRM 7 which can be installed on calibre 5.  But only some of the code has been updated to Python 3 compatibility so far.
