### ISSUE TITLE
DRM not removed on some Epub books

### ISSUE THREAD

**Issue by Ludi3** [apprenticeharper/DeDRM_tools#1282]
I have been using the plugin for a while and it generally removes all DRM from epub books.
It does not work in this case:

calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.52] splash screen shown
[0.52] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[2.19] main UI initialized...
[2.19] Hiding splash screen
[145.41] splash screen hidden
[145.41] Started up in 145.41 seconds with 126 books
DeDRM v6.8.0: Trying to decrypt Harry Potter and the Cursed Child.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Harry Potter and the Cursed Child.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Trying Encryption key default_key
Could not decrypt io6g8s.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 465, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 379, in decrypt
  File "calibre_plugins.dedrm.ineptepub", line 365, in decompress
error: Error -3 while decompressing: invalid stored block lengths

DeDRM v6.8.0: Failed to decrypt with key default_key after 0.6 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.6 seconds
Found 1 keys
DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Harry Potter and the Cursed Child to db in: 1.6
Added 1 books in 3.4 seconds

**Comment by ElleKayEm** [comment]
Try 64-bit calibre.  But make sure to stick with calibre version 4.23.

**Comment by Ludi3** [comment]
Hi there,

still the same:

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
[1.98] main UI initialized...
[2.00] Hiding splash screen
[5.19] splash screen hidden
[5.20] Started up in 5.20 seconds with 126 books
DeDRM v6.8.0: Trying to decrypt Harry Potter and the Cursed Child.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: Harry Potter and the Cursed Child.epub is a secure Adobe Adept ePub
DeDRM v6.8.0: Trying Encryption key default_key
Could not decrypt mrsezo.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 465, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 379, in decrypt
  File "calibre_plugins.dedrm.ineptepub", line 365, in decompress
error: Error -3 while decompressing: invalid stored block lengths

DeDRM v6.8.0: Failed to decrypt with key default_key after 0.7 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.7 seconds
Found 1 keys
DeDRM v6.8.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 407, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Harry Potter and the Cursed Child to db in: 1.6
Added 1 books in 4.7 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000026A80042588>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000026A80042908>> ignored

**Comment by ElleKayEm** [comment]
The problem seems to be here:

> Error -3 while decompressing: invalid stored block lengths

But I don't know how to resolve it.  Is the book tied to the same Adobe ID and from a source you've had success decrypting before?  Can the book be read in Adobe Digital Editions 2.0.1?

**Comment by pengtsin** [comment]
FYI ... I filed a bug with Calibre and got this response ... (Calibre 4.23 is the last version that supports DeDRM v6.8.0.)

As of calibre 5, calibre has moved from Python 2 to Python 3, because Python 2 has been end-of-lifed.
This means that some third party calibre plugins that have not yet been ported to Python 3 will not work
with calibre 5. If you depend on such a plugin, you will have to either:

Wait for the plugin to be ported to Python 3
If you are on windows, you can install the last calibre 4.x release using calibre portable and
run the plugin there
Downgrade to calibre 4.x until the plugin is ported. You can simply uninstall calibre 5 and install calibre 4.23, doing so
will not affect your books or settings.

**Comment by ElleKayEm** [comment]
@pengtsin 
That's not the problem here.

**Comment by ElleKayEm** [comment]
Have you tried downloading a fresh copy of the book?

**Comment by Ludi3** [comment]
Yes, a couple of times. It looks like it was just this one book. the rest still decrypt fine.

**Comment by ElleKayEm** [comment]
Seems like @apprenticeharper or someone will need to take a look at this.

**Comment by ElleKayEm** [comment]
Looks like this might be an enhanced copy of the book.  If you unzip the epub, remove audio files, then zip it back up, you may at least be able to decrypt the text.

**Comment by ElleKayEm** [comment]
Possible solution in issue #1444 .
