### ISSUE TITLE
book can be opened but empty

### ISSUE THREAD

**Issue by nbctcp** [apprenticeharper/DeDRM_tools#1283]
SW INFO:
WIN10
Kindle PC 1.24.3
Calibre 4.23

PROBLEMS:
1. book can be imported but empty.
book file size shown 100kb in Calibre

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[2.11] splash screen shown
[2.11] Initializing db...
[2.12] db initialized
[2.12] Constructing main UI...
[4.39] main UI initialized...
[4.39] Hiding splash screen
[266.86] splash screen hidden
[266.88] Started up in 266.88 seconds with 11 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfc\x1d\xda|\xfe\xeb\x05\xd2M>ju.\x80F\x88\xf6\xb4\x17\xda\xb9\x03\xd9.\xf7\xe3\xed>xe\x88\x9d', 'C:\\Users\\\\Documents\\My Kindle Content\\B01IC5TT6K_EBOK\\B01IC5TT6K_EBOK.azw']
DeDRM v6.8.0: Trying to decrypt B01IC5TT6K_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\nbctcp\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\nbctcp\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\nbctcp\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4008901122' and UserName '6e6263746370'
Decrypted key file using IDString '4008901122' and UserName '6e6263746370'
DeDRM v6.8.0: Found 2 new keys
DeDRM v6.8.0: Ultimately failed to decrypt after 17.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 17.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
Added B01IC5TT6K EBOK to db in: 2.3
Added 1 books in 22.2 seconds

**Comment by nbctcp** [comment]
SOLVED
Need to use Kindle 1.17

**Comment by ElleKayEm** [comment]
Other options would be to disable KFX format downloads in later versions of Kindle for PC.  Or install the KFX Input plugin.  But I'm sticking with K4PC 1.17 for as long as it continues to work myself.
