### ISSUE TITLE
Unable to decrypt KFX from Kindle for Windows

### ISSUE THREAD

**Issue by HerbCaudill** [apprenticeharper/DeDRM_tools#1290]
I'm using: 
- Kindle for Windows 1.29
- KFX Input 1.34
- DeDRM 6.8
- Calibre 4.23
- Windows 10.0.19041

Here's the log output: 

```
calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.245901639 x 133.100436681
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.49] splash screen shown
[0.49] Initializing db...
[0.49] db initialized
[0.49] Constructing main UI...
[1.74] main UI initialized...
[1.74] Hiding splash screen
[11.22] splash screen hidden
[11.22] Started up in 11.22 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8e\x87\xf4\xf4\xc2\x98=3W\xa3(\xeeL\xdcN(\x0e\xa2\xac\x9e\xe5Y[+\xcc\xffp5\xfa\xf6\x98\xef', 'C:\\Users\\herb\\Documents\\My Kindle Content\\B08BDGXVK9_EBOK\\B08BDGXVK9_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing C:\Users\herb\Documents\My Kindle Content\B08BDGXVK9_EBOK\B08BDGXVK9_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\herb\AppData\Local\Temp\calibre_q_ovlr\za_ihu.kfx-zip
DeDRM v6.8.0: Trying to decrypt za_ihu.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: za_ihu
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.87365a2d-49dc-49f6-8005-af2e8bb92ce0.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\herb\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\herb\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2886455439' and UserName '68657262'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: za_ihu
Got DSN key from database default_key_1
Found 1 keys to try after 6.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.87365a2d-49dc-49f6-8005-af2e8bb92ce0.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 6.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 6.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging C:\Users\herb\AppData\Local\Temp\calibre_q_ovlr\za_ihu.kfx-zip
Processing container: B08BDGXVK9_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B08BDGXVK9_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\herb\AppData\Local\Temp\calibre_q_ovlr\uj6n6i_add_books\0\B08BDGXVK9_EBOK.kfx-zip
Added xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx to db in: 0.2
Added 1 books in 7.8 seconds
```

**Comment by evildarkarchon** [comment]
This is a limitation of DeDRM at this time, what you can do is:
1. Delete book from both calibre and kindle for pc
2. Download kindle for pc <=1.26
3. Redownload book and reimport into calibre

**Comment by tartley** [comment]
This requirement for older versions of Kindle for PC is documented in a proposed README update giving precise instructions for using DeDRM https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM

Closing this issue for now. Shout if that's not OK.

**Comment by ElleKayEm** [comment]
Or disable KFX downloads and decrypt the older formats.  See method 2 here:  https://www.mobileread.com/forums/showthread.php?t=283371
