### ISSUE TITLE
Calibre error when installing DeDRM_plugin.zip

### ISSUE THREAD

**Issue by chyron8472** [apprenticeharper/DeDRM_tools#13]
calibre, version 2.28.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Initialization of plugin Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.dedrm.__init__", line 145, in initialize
AttributeError: 'DeDRM' object has no attribute 'starttime'
 failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.dedrm.__init__", line 145, in initialize
AttributeError: 'DeDRM' object has no attribute 'starttime'

calibre 2.28  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 392, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 559, in initialize_plugin
InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.dedrm.__init__", line 145, in initialize
AttributeError: 'DeDRM' object has no attribute 'starttime'
 failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 553, in initialize_plugin
  File "calibre_plugins.dedrm.__init__", line 145, in initialize
AttributeError: 'DeDRM' object has no attribute 'starttime'

**Comment by chyron8472** [comment]
Issue resolved. I needed to first uninstall all other DRM removal plugins. I was only ever paying attention to the "DeDRM" one.
