### ISSUE TITLE
PyCrypto has been dead since 2014

### ISSUE THREAD

**Issue by tartley** [apprenticeharper/DeDRM_tools#1306]
We use pycrypto in quite a few places, but it is long dead: See https://github.com/pycrypto/pycrypto/issues/173 (and hasn't had a commit since 2014)

We should start migrating to something maintained, such as possibly
https://cryptography.io/en/latest/

One immediate advantage this brings is being able to install wheels directly from PyPI with 'pip install'.

**Comment by clach04** [comment]
I agree a dependency on PyCrypto is not a good idea in 2020, I recommend PyCryptodome as the alternative. It works in my installations, out of the box. Only change needed is the dependency.

I recommend against switching/porting to a new API like pyca/cryptography.

**Comment by tartley** [comment]
Thanks for the advice, what you say makes sense. I didn't know which were drop-in compatible.

**Comment by apprenticeharper** [comment]
I agree that we should move to pycrptodome. Which makes no difference to the scripts, as it's a drop-in replacement. The instructions and readme need updating, but since we only really support the plugin now, I suspect it's a non-issue. We'll be using whatever calibre is using.

**Comment by tartley** [comment]
Thanks for the info. I'll create a branch with documentation changes, see what you think...

**Comment by ivan-m** [comment]
I don't think it's a drop-in replacement (at least when used with Python 2.7):

```
DeDRM v6.7.0: Trying Encryption key adobekey
Could not decrypt MozHX6.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 420, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 329, in decrypt
  File "/nix/store/39fqf4pa2bqlcs4zf9dw0galrr3h9k37-python2.7-pycryptodome-3.9.4/lib/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 375, in decrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
```

(KFX decryption succeeds, ADE fails; if I actually force installation and usage of pycrypto then it succeeds.)

**Comment by ametzler** [comment]
> I agree that we should move to pycrptodome. Which makes no difference to the scripts, as it's a drop-in replacement. The instructions and readme need updating, but since we only really support the plugin now, I suspect it's a non-issue. We'll be using whatever calibre is using.

Does not work for me on Debian, with python3-pycryptodome installed (but without python3-crypto) I get

~~~
DeDRM v7.0.3: Trying to decrypt encrypted-from_kpw.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 15, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/dev/shm/calibre_5.10.1_tmp_y89ct300/iv1ehdglplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
~~~

s/Crypto\./Cryptodome/ in the sourcefiles seems to have done the trick.
