### ISSUE TITLE
DRMError: <Book Title>

### ISSUE THREAD

**Issue by Jsanches8448** [apprenticeharper/DeDRM_tools#1307]
Thank you for all that you guys do!
***System Information***
OS: Windows 10 1903
Calibre: 4.4
DeDRM tools: Tried 6.6.3 and 6.8

Convert book 1 of 1 (Europe's Barbarians AD 200-600 (The Medieval World))
Conversion options changed from defaults:
  cover: u'C:\\Users\\<MyUsernameHere>\\AppData\\Local\\Temp\\calibre_gy9udx\\uksrkh.jpeg'
  pdf_sans_family: u'Calibri'
  margin_left: 75.0
  margin_right: 75.0
  paper_size: u'a4'
  pdf_serif_family: u'Calibri'
  read_metadata_from_opf: u'C:\\Users\\<MyUsernameHere>\\AppData\\Local\\Temp\\calibre_gy9udx\\xoo7ym.opf'
  output_profile: u'generic_eink'
  pdf_default_font_size: 18
  verbose: 2
  margin_top: 75.0
Resolved conversion options
calibre version: 4.4.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\<MyUsernameHere>\\AppData\\Local\\Temp\\calibre_gy9udx\\uksrkh.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x054BEAB0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 75.0,
 'margin_right': 75.0,
 'margin_top': 75.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x054BECB0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'a4',
 'pdf_add_toc': False,
 'pdf_default_font_size': 18,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Calibri',
 'pdf_serif_family': u'Calibri',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\<MyUsernameHere>\\AppData\\Local\\Temp\\calibre_gy9udx\\xoo7ym.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\<MyUsernameHere>\AppData\Local\Temp\calibre_gy9udx\nrg5cn.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  Europe's Barbarians AD 200-600 (The Medieval World) (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: Europe's Barbarians AD 200-600 (The Medieval World)

**Comment by Sanchito-exe** [comment]
Received the ebook from kindle

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre.  So we'll need an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
