### ISSUE TITLE
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds.

### ISSUE THREAD

**Issue by dgauche** [apprenticeharper/DeDRM_tools#1311]
MacOS 10.15.7
DeDRM v6.8.0
Kindle for Mac v1.26.1 (55093)
Calibre 4.23.0
KFX Input v1.34.0

I want to "write" (not just highlight, but draw and make handwritten notes) on my ebook using my Apple Pencil on my iPad... the stupid Kindle App does not cater for this, but iBooks does and so does Notability and Goodnotes. So I need to access my ebooks in one of those 3 apps.

**DeDRM seems to be unable to remove the DRM, but I cannot see why.** I have searched, but have not found a similar issue...

Can anyone point me in the right direction please?

Debug output:
-----------------------------------------------------------
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0) && Set KFX metadata (from KFX Output) (1, 44, 0) && KFX Output (1, 44, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.23] main UI initialized...
[1.24] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing /Users/bob1/Library/Application Support/Kindle/My Kindle Content/B07Z3ZSZPZ_EBOK/B07Z3ZSZPZ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/0w/b3n4b0v53j5br2sm4c2792880000gn/C/calibre_4.23.0_tmp_IwQaJY/1uOUcB.kfx-zip
DeDRM v6.8.0: Trying to decrypt 1uOUcB.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: 1uOUcB
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6e541da5-8a3d-40f2-b034-9f67d15e9443.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/bob1/Library/Application Support/Kindle/storage/.kinf2018
[3.71] splash screen hidden
[3.71] Started up in 3.71 seconds with 0 books
Decrypted key file using IDString 'ddeae630cfac' and UserName 'bob1'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: 1uOUcB
Got DSN key from database default_key_1
Found 1 keys to try after 0.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6e541da5-8a3d-40f2-b034-9f67d15e9443.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.34.0: Packaging /var/folders/0w/b3n4b0v53j5br2sm4c2792880000gn/C/calibre_4.23.0_tmp_IwQaJY/1uOUcB.kfx-zip
Processing container: B07Z3ZSZPZ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 202, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 309, in get_container
KFXDRMError: Book container B07Z3ZSZPZ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/0w/b3n4b0v53j5br2sm4c2792880000gn/C/calibre_4.23.0_tmp_IwQaJY/ZoZVbg_add_books/0/B07Z3ZSZPZ_EBOK.kfx-zip
Added //Book name removed// to db in: 0.0
Added 1 books in 1.3 seconds

**Comment by dgauche** [comment]
After days of trying to fix the issue, I ended up finding the solutions shortly after logging it... Murphey
