### ISSUE TITLE
how to unlock DRM from encrypted pdf  

### ISSUE THREAD

**Issue by uzairuzi78** [apprenticeharper/DeDRM_tools#1315]
i have digital edition and adobe id signed in account in digital edition. and also downloaded some encrypted eBooks 
I want to share these book with other's in PDF how to unlock these books 

**all DRM removal software failed to remove drm from pdf**

error code from epub DRM removal 

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\Program Files (x86)\eBook Converter\ePub DRM Removal\lib\pdfdrm.py", line 2213, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "C:\Program Files (x86)\eBook Converter\ePub DRM Removal\lib\pdfdrm.py", line 2188, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "C:\Program Files (x86)\eBook Converter\ePub DRM Removal\lib\pdfdrm.py", line 1998, in __init__
    doc.initialize(userkey)
  File "C:\Program Files (x86)\eBook Converter\ePub DRM Removal\lib\pdfdrm.py", line 1483, in initialize
    return self.initialize_ebx(password, docid, param)
  File "C:\Program Files (x86)\eBook Converter\ePub DRM Removal\lib\pdfdrm.py", line 1615, in initialize_ebx
    raise ADEPTError('error decrypting book session key')
pdfdrm.ADEPTError: error decrypting book session key

**Comment by ElleKayEm** [comment]
Have calibre 4.23 with DeDRM 6.8 on the same machine and user as Adobe 2.0.1 authorized with your Adobe ID.
