### ISSUE TITLE
Kindle KF8 Mobi. DeDRM failing to remove drm on book 

### ISSUE THREAD

**Issue by Kilarin** [apprenticeharper/DeDRM_tools#1316]
I'm running Ubuntu 18.04, running Kindle 1.16.0 under wine.  (I can't get 1.17 to install under wine)
I purchased a book on 2020/01/19, downloaded it to my pc, and it IS readable in Kindle there.
I try importing it into calibre though, and I can't seem to DeDRM it and convert it into an epub.
I tried uninstalling Kindle, re-installing Kindle, and downloading the book fresh, that did not make a difference.
I still get the "No key found" errors listed below.
DeDRM is an AWESOME product.  Thank you for any help in getting it to work on this particular book.

-------------------------------

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.21  embedded-python: False is64bit: True
Linux-4.15.0-121-generic-x86_64-with-Ubuntu-18.04-bionic Linux ('64bit', '')
('Linux', '4.15.0-121-generic', '#123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020')
Python 2.7.17
Linux: ('Ubuntu', '18.04', 'bionic')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 3.21  embedded-python: False is64bit: True
Linux-4.15.0-121-generic-x86_64-with-Ubuntu-18.04-bionic Linux ('64bit', '')
('Linux', '4.15.0-121-generic', '#123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020')
Python 2.7.17
Linux: ('Ubuntu', '18.04', 'bionic')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 88.1880650995 x 88.7766990291
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.43] main UI initialized...
[1.43] Hiding splash screen
Gtk-Message: 09:43:06.506: GtkDialog mapped without a transient parent. This is discouraged.
Gather KFX-ZIP (from KFX Input) 1.34.0: Importing /media/expdrv/DCH/Alexander Key/B00LLSF5NC_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B00LLSF5NC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Incredible Tide
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/donald/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/donald/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.8.0: Found and decrypted 0 key files
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[8.31] splash screen hidden
[8.31] Started up in 8.31 seconds with 20 books
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Added The Incredible Tide to db in: 2.3
Added 1 books in 3.7 seconds
Worker Launch took: 0.127640962601
Worker Launch took: 0.319119930267
Job: 2 Convert book 1 of 1 (The Incredible Tide) finished
Convert book 1 of 1 (The Incredible Tide)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/tmp/calibre_3.21.0_tmp_2idEFL/A20hCx.opf'
	  verbose: 2
	  output_profile: 'generic_eink'
	  cover: u'/tmp/calibre_3.21.0_tmp_2idEFL/w93Tre.jpeg'
	Resolved conversion options
	calibre version: 3.21.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/tmp/calibre_3.21.0_tmp_2idEFL/w93Tre.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f912ad99c90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x7f912ac380d0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/tmp/calibre_3.21.0_tmp_2idEFL/A20hCx.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_3.21.0_tmp_2idEFL/FLtt9o.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 20, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 195, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	    override_input_metadata=True)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1088, in run
	    accelerators, tdir)
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 245, in __call__
	    log, accelerators)
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	    opf = os.path.abspath(mr())
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	    self.mobi6_reader.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 157, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: The Incredible Tide

**Comment by ElleKayEm** [comment]
Here's the issue:

> DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v6.8.0: Running kindlekey.py under Wine
DeDRM v6.8.0: Command line: 'wine python.exe "/home/donald/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/donald/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\windows\system32\python.exe"

Do you have Python and PyCrypto installed under Wine?

**Comment by DavidVentura** [comment]
i'm having the same problem running on linux, without wine, using a static build of calibre

**Comment by Kilarin** [comment]
Sorry for the long delay in responding, it's been a hectic month. :)   I've just got to figure out how to install python under wine, and then I'll try again.  Thank you!
