### ISSUE TITLE
DRM removal not working

### ISSUE THREAD

**Issue by jjran** [apprenticeharper/DeDRM_tools#1334]
I have the same problem with several books, this is just one of them.

calibre Vianmääritysloki
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fi
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fi
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.58] splash screen shown
[0.58] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[2.61] main UI initialized...
[2.61] Hiding splash screen
[5.88] splash screen hidden
[5.88] Started up in 5.88 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['-\\\xf3L\xdfn\xbc\xaf\xea\x1d\x9f\x93\xe6\xf3\x9cM\x1b\xaa\xa8!$\x96\xc6\xc3\xe3xF\xf6D\x1f|6', 'C:\\Users\\janju\\Documents\\My Digital Editions\\Julkinen johtaminen-2.epub']
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Julkinen johtaminen to db in: 0.3
Added 1 books in 1.4 seconds

**Comment by jjran** [comment]
Here's another one (or should I post this as a new issue?):

calibre Vianmääritysloki
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fi
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: fi
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.758381503
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
[2.69] main UI initialized...
[2.69] Hiding splash screen
[4.83] splash screen hidden
[4.83] Started up in 4.83 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe3;U*55\xb2|\xf6\xf28$\xedd\x81\xf3\x1a\x99\x9b.\xea\xee\xf4>\x83\xdd\xaeF\xa6/\xc1D', 'C:\\Users\\janju\\Documents\\My Digital Editions\\Elinik\xc3\xa4inen oppiminen ihmist\xc3\xa4 m\xc3\xa4\xc3\xa4ritt\xc3\xa4m\xc3\xa4ss\xc3\xa4 Genealoginen analyys-1.pdf']
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added Elinikäinen oppiminen ihmistä määrittämässä Genealoginen analyys-1 to db in: 0.2
Added 1 books in 1.7 seconds

**Comment by ElleKayEm** [comment]
This is odd.  I see the book added, but DeDRM never even tries to remove the DRM.  You have DeDRM enabled?  These are the actual epub and pdf files and not the acsm file, right?

**Comment by henderjon** [comment]
I noticed that G()()GLE has *recently* updated their play books interface and now I'm not able to use this plugin either. It's possible they changed something?

**Comment by ElleKayEm** [comment]
Still working for me.
