### ISSUE TITLE
DeDRM_Plugin.zip doesn't work with Calibre 5.03 (Syntax Error: "calibre_plugins.dedrm.__init__", line 168 )

### ISSUE THREAD

**Issue by Nivek-** [apprenticeharper/DeDRM_tools#1342]
## DeDRM_Plugin.zip doesn't work with Calibre 5.03
I am getting an error adding the last version of DeDRM_Plugin.zip (v6.8.0) to my Calibre

## It seems to be a Syntax error (By the way... I have the spanish version of Calibre )
calibre, version 5.3.0
ERROR: Excepción no considerada: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 285, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 177, in exec_module
  File "calibre\customize\zipplugin.py", line 173, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

</details>

**Comment by extesy** [comment]
@Nivek- Did you read the readme on the main page? https://github.com/apprenticeharper/DeDRM_tools#calibre-50

**Comment by Nivek-** [comment]
Sorry... I'am going to install the last 4.x.x version instead. Thanks for the help :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by wallner** [comment]
I'm seeing the same error, although with calibre 4.23.0:
```
calibre, version 4.23.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.23  embedded-python: False is64bit: True
Linux-5.8.18-300.fc33.x86_64-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.8.18-300.fc33.x86_64', '#1 SMP Mon Nov 2 19:09:05 UTC 2020')
Python 3.9.0
Interface language: None
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 316, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib64/calibre/polyglot/builtins.py", line 112, in reload
    return importlib.reload(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 611, in _exec
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
````
Is my python too recent?

**Comment by ElleKayEm** [comment]
You need the [regular release of calibre 4.23](https://download.calibre-ebook.com/4.23.0/).  That version has Python 3.
