### ISSUE TITLE
Amazon to Kindle for PC to Calibre DeDRM Fails

### ISSUE THREAD

**Issue by Explorer942** [apprenticeharper/DeDRM_tools#1346]
<Hello,

I have been using Calibre with Apprentice Alf’s DeDRM plugin successfully for a number of years.  I used Kindle for PC version 1.17 to import and open my ebooks from Amazon then import them into Calibre using the “Add Books” feature.  From Calibre, I could side-load my books into my Kindle Papwewhite or email them to the Kindle app on my iPhone.  I disabled the Kindle automatic updates in order to preserve the old DRM encoding.  Amazon finally forced a Kindle automatic update on me and now I can’t de-DRM my books.

Here is my current setup:
Kindle for PC version 1.30.0
Calibre 64-bit version 4.23.0
deDRM plug-in version 6.6.3
Windows 10
Kindle Paperwhite Serial Number:  G000 PP10 8454 00WL.  Note: I have checked very carefully and every character that looks like a zero is a zero.

I have added the Paperwhite serial number to the initialization of the plugin.  I do not understand how the Paperwhite S/N applies to an ebook downloaded into the Kindle for PC app.

I tried downloading from Amazon directly into the Paperwhite and then checking for the title via a USB connection to my PC, but could not see the book either with the PC’s directory structure or with “Add Books” in Calibre.

Any advice you can give me about how to continue to deDRM my books is greatly appreciated.  Per your instructions, here is the debug log from Calibre:

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.7381489842 x 91.8072289157
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.52] splash screen shown
[0.52] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[2.30] main UI initialized...
[2.30] Hiding splash screen
[5.72] splash screen hidden
[5.72] Started up in 5.72 seconds with 578 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x87$\xe9\x0f\xdf\xd6\xd5a\xb0v\x99\xb1\xbe$;\x8cP\x8f\x9bP\xe8\xa8\xea\x911\xb4|\x08v\xa5\x8c\xd3', 'C:\\Users\\Tom\\Documents\\My Kindle Content\\B07B7K973K_EBOK\\B07B7K973K_EBOK.azw']
DeDRM v6.6.3: Trying to decrypt B07B7K973K_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.3: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Tom\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Tom\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '213417602' and UserName '546f6d'
DeDRM v6.6.3: Found 1 new key
DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
Added B07B7K973K EBOK to db in: 1.2
Added 1 books in 3.0 seconds

>

**Comment by ElleKayEm** [comment]
For Kindle for PC books, you will need to go back to Kindle for PC 1.26 or earlier.  OR disable KFX format downloads if using a version later than 1.17.

Since you have a Paperwhite, you can decrypt books downloaded from the website.  Select "download & transfer via USB" and choose the Paperwhite.  Its serial number acts as the key to unlock those books.

**Comment by user897943** [comment]
I am having the same issue. When I choose "download and transfer via usb" it asks me to select a device, I only have the paperwhite so I select that, I then click on the single button to confirm and nothing happens.

**Comment by ElleKayEm** [comment]
Are you using Chrome?  A recent change causes it to think that type of download is insecure.  Click the lock to the left of the url.  Then site settings.  Scroll down to insecure content and switch it from block to allow.  You should then be able to download the book.
