### ISSUE TITLE
[Invalid Plugin] ERROR

### ISSUE THREAD

**Issue by OmAn94** [apprenticeharper/DeDRM_tools#1352]
**LOG**: 
```
calibre, version 4.23.0
ERROR: Excepción no considerada: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Jared\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Jared\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by OmAn94** [comment]
Already works, just search on the issues pages, sorry!!!

**Comment by ElleKayEm** [comment]
Just in case someone else needs the answer:  unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.
