### ISSUE TITLE
DeDRM tool won't work with Calibre

### ISSUE THREAD

**Issue by JustP00Pit** [apprenticeharper/DeDRM_tools#1366]
I am using Windows 10 64 bit. I installed an earlier version of Calibre and I'm using the latest DeDRM tool. I keep getting an error message saying something about missing an important file.

calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Ratze\\Downloads\\DeDRM_tools-6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Ratze\\Downloads\\DeDRM_tools-6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

Please help.

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools-6.8.0.zip.  Load DeDRM_Plugin.zip.

**Comment by JustP00Pit** [comment]
I'm trying to convert to pdf from amazon kindle and now I get this:


Convert book 1 of 1 (B004GXAZX4 EBOK)
Conversion options changed from defaults:
  pdf_sans_family: u'MS Shell Dlg 2'
  pdf_serif_family: u'MS Shell Dlg 2'
  read_metadata_from_opf: u'C:\\Users\\Ratze\\AppData\\Local\\Temp\\calibre_uybknv\\vogq9k.opf'
  verbose: 2
  output_profile: u'generic_eink'
Resolved conversion options
calibre version: 4.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001BAE612E888>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001BAE61344C8>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Ratze\\AppData\\Local\\Temp\\calibre_uybknv\\vogq9k.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Ratze\AppData\Local\Temp\calibre_uybknv\yrca4i.azw
Python function terminated unexpectedly
  This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books. (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 37, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book to calibre, not during conversion.  Take a look at the link in the log.  If you're still having issues after that, then post an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by RDCarr** [comment]
> Unzip DeDRM_tools-6.8.0.zip. Load DeDRM_Plugin.zip.

I must be doing something wrong... I have unzipped the master file.  I proceeded to zip the DeDRM_plugin file but that gave me the same init.py error.  I noticed the init.py was one layer down within a second DeDRM_plugin folder so I tried zipping just the contents of the folder and ran into the same issue... what am I missing?  Thanks

**Comment by ElleKayEm** [comment]
Oh, sorry... just released that's the wrong file.  You want to download DeDRM_tools_6.8.0.zip (with underscore before the version number, not a hyphen).  First link under assets on [the release page](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.0).  Not the source code link.  Unzip that and you will find DeDRM_Plugin.zip.

**Comment by wishwise** [comment]
it works well for  calibre, version 4.23.0  with DeDRM_tools-6.8.0.zip. This error is most likely because the book to be converted was imported before you installed the plugin, which is wrong. You should import the book after installing the plugin

**Comment by ElleKayEm** [comment]
DeDRM does work on conversion now too.  Not sure what version added that.
