### ISSUE TITLE
Oops - Just discovered that DeDRM_Tools_6.8.0.zip doesn't work with Calibre 5.5

### ISSUE THREAD

**Issue by JBlyth** [apprenticeharper/DeDRM_tools#1367]
Oops - Sorry, I didn't realise that DeDRM doesn't work with Calibre 5+ yet.... Sorry.

I am getting this error message when I try and install DeDRM_Tools_6.8.0.zip in the usual way.

Any suggestions to fix this?

Many thanks.....

calibre, version 5.5.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Stick with calibre 4.23.  Unzip DeDRM_Tools_6.8.0.zip and load DeDRM_Plugin.zip.
