### ISSUE TITLE
[QUESTION] Upload failed - Syntax Error

### ISSUE THREAD

**Issue by case1106** [apprenticeharper/DeDRM_tools#1374]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>invalid syntax (calibre_plugins.dedrm.__init__,line 168)</summary>

```log
calibre, version 5.5.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

```
</details>

**Comment by case1106** [comment]
Hi this is my first time uploading plugin to Callibre and encountered this issue. Please let me know if there's any setup not done. Thanks.

Obok_plugin is successfully installed but DeDRM_Plugin is failed.

**Comment by ElleKayEm** [comment]
Use calibre 4.23 for the current DeDRM 6.8 release.  Updates are underway to make DeDRM compatible with calibre 5.x.
