### ISSUE TITLE
DeDRM is not working with azw3 files on Calibre 4.23 installed on mac OS 11.0.1

### ISSUE THREAD

**Issue by tos070** [apprenticeharper/DeDRM_tools#1376]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Log
<details><summary>Removing DRM from A Promised Land</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.500001885 x 125.500001885
Using calibre Qt style: True
[0.00] Starting up...
[0.08] Showing splash screen...
[0.65] splash screen shown
[0.65] Initializing db...
[0.70] db initialized
[0.70] Constructing main UI...
[16.82] main UI initialized...
[16.82] Hiding splash screen
[21.57] splash screen hidden
[21.57] Started up in 21.57 seconds with 151 books
DeDRM v6.8.0: Trying to decrypt A Promised Land-2.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Promised Land
Found 2 keys to try after 1.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 1.1 seconds
Found k4Mac kinf2018 file: /Users/sotiris/Library/Application Support/Kindle/storage/.kinf2018
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added A Promised Land to db in: 0.4
Added 1 books in 19.1 seconds
```
</details>

**Comment by tos070** [comment]
I bought the ebook from Amazon. I downloaded the azw3 file from the "Manage Devices and Content" page of my Amazon account. I can read the book on my kindle and on the Kindle for Mac app. But I cannot remove the DMR and cannot read it in the Calibre Viewer.

**Comment by ElleKayEm** [comment]
If you have an E-ink Kindle (not a Fire) on your account, then that's the device you should choose when downloading "for transfer via USB".  Enter the Kindle's serial number into DeDRM's customization.  Remove and re-add the book.

**Comment by tos070** [comment]
Thanks, it worked. Can I add more than one serial numbers when customising the DeDRM?

**Comment by ElleKayEm** [comment]
Yes.
