### ISSUE TITLE
Unable to convert .azw

### ISSUE THREAD

**Issue by LSStream** [apprenticeharper/DeDRM_tools#1390]
Hello.

This applies to using my MacbookPro on 10.14.6 (Mojave).

I have successfully done this several times before over the past few years, but today I am unable to import/convert a new AMZN book that I just purchased as a Kindle book. I just happen to prefer to keep my books as PDF, my preferred format. After updating the DeDRM plug-in to 6.8.0 (then 6.8.1 and 7.0.0b3 and the KFX Input plugin to 7.0.0, I tried using Calibre (both 4.2.2 and 5.6) to add my .azw book (I downloaded two copies, one with Kindle 1.12 and one with 1.23). No matter what, the process is stuck at 0%, even after several minutes. The laptop fan is very audible, though, so something is happening. But, Calibre is certainly not importing the content.

I ran Calibre 5.6 with debugging on to see if it would offer clues to those who are smarter about this stuff than I am. Here's the content. If anyone can offer any suggestions, I would be most appreciative.

Thank you. And happy holiday season to everyone!

-----------
calibre Debug log
calibre 5.6  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Fri Oct 30 12:37:06 PDT 2020; root:xnu-4903.278.44.0.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.6  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Fri Oct 30 12:37:06 PDT 2020; root:xnu-4903.278.44.0.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000165954353 x 110.50000165954353
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.32] splash screen shown
[0.32] Initializing db...
[0.32] db initialized
[0.33] Constructing main UI...
[1.06] main UI initialized...
[1.06] Hiding splash screen
Starting QuickView
objc[13643]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9942f3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x116a00f50). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/snp/Library/Application Support/Kindle/My Kindle Content/B01F31LR3E_EBOK/B01F31LR3E_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.0.0: Trying to decrypt B01F31LR3E_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Diagnostic Imaging: Musculoskeletal Non-Traumatic Disease E-Book
Error getting PIDs from database default_key: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Got DSN key from database default_key_3
Error getting PIDs from database default_key_4: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Found 8 keys to try after 0.3 seconds
Crypto Type is: 2
File is encoded with PID b'pJWoQC5fS2'.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [15.88] splash screen hidden
[15.88] Started up in 15.88 seconds with 35 books
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/snp/Library/Application Support/Kindle/My Kindle Content/B01F31LR3E_EBOK/B01F31LR3E_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.0.0: Trying to decrypt B01F31LR3E_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Diagnostic Imaging: Musculoskeletal Non-Traumatic Disease E-Book
Error getting PIDs from database default_key: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Got DSN key from database default_key_3
Error getting PIDs from database default_key_4: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Found 8 keys to try after 0.4 seconds
Crypto Type is: 2
File is encoded with PID b'pJWoQC5fS2'.
Decrypting. Please wait . . . . DeDRM v7.0.0: Trying to decrypt B01F31LR3E_EBOK.azw4
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Diagnostic Imaging: Musculoskeletal Non-Traumatic Disease E-Book
Error getting PIDs from database default_key: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Got DSN key from database default_key_3
Error getting PIDs from database default_key_4: can't concat str to bytes
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(getK4Pids(md1, md2, kDatabase))
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
    pidHash = SHA1(DSN+kindleAccountToken+rec209+token)
TypeError: can't concat str to bytes
Found 8 keys to try after 0.3 seconds
Crypto Type is: 2
File is encoded with PID b'08+TtF1yMF'.
Decrypting. Please wait . . . . . . 
---------

**Comment by ElleKayEm** [comment]
Stick with calibre 4.23 and DeDRM 6.8.0 (or 6.8.1, either is fine for Mojave).  Don't mess with calibre 5 and beta DeDRM 7 -- that still needs work.  Don't worry about KFX Input.  It's better to avoid KFX format if you want to convert to PDF.  It doesn't matter what version of Kindle for Mac you use as long as it is on the same machine and user as calibre with DeDRM.  But if you use version 1.19 or later, disable KFX downloads.  See Method 2 at [this MobileRead post](https://www.mobileread.com/forums/showthread.php?t=283371).  Read [this post](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508) if you use Kindle for Mac 1.25 or later.  Download a fresh copy of the book with the currently installed Kindle for Mac.  Remove any unsuccessfully DeDRMed copy from calibre, and add the new copy.  That should work.  If not, post another log.  If the decrypted book has the AZW4 extension once it is added to calibre, then try using the KindleUnpack plugin to extract the PDF.

**Comment by LSStream** [comment]
Thank you very much for your reply.

I downloaded and installed a copy of cailbre 4.23 and installed the DeDRM 6.8.0 plugin. I deleted the prior book download(s) from my My Kindle Content folder. I redownloaded the book using Kindle 1.12, and ended up with B01F31LR3E_EBOK.azw4 (109 MB), as well as  B01F31LR3E_EBOK.mbpV2 and B0813RRGT7_EBOK.apnx. I restarted calibre and tried to add the .azw4 file, but again, things never move beyond 0% for some reason. BTW, everything is being done under one user on my MBP (Mojave). This is stumping me - am I doing something wrong here? Anyhow, I created another debug log. Again, thanks so much for the feedback and guidance.

----------------
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Fri Oct 30 12:37:06 PDT 2020; root:xnu-4903.278.44.0.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Fri Oct 30 12:37:06 PDT 2020; root:xnu-4903.278.44.0.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
objc[15138]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9942f3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x113d93f50). One of the two will be used. Which one is undefined.
DeDRM v6.8.0: Trying to decrypt B01F31LR3E_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Diagnostic Imaging: Musculoskeletal Non-Traumatic Disease E-Book
Got DSN key from database default_key_3
Found 11 keys to try after 0.3 seconds
Crypto Type is: 2
File is encoded with PID 8JWVxk17JZ.
Decrypting. Please wait . . . [4.00] splash screen hidden
[4.00] Started up in 4.00 seconds with 35 books
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 

-------------------

**Comment by ElleKayEm** [comment]
Looks like it was working.  If it's a really large file, it could take a while.

**Comment by pdurrant** [comment]
.azw4 is a PDF file in a PDB format wrapper. It certainly looks like decryption is happening, you just need to let it run longer.

**Comment by LSStream** [comment]
Thank you for the guidance. I did try it again and let it run for a while, and it did finally work after several minutes. I think what threw me was that there was never any progress bar advancement, so I mistook this for being hung (I recall seeing some progress bar activity in the past, IIRC). The other thing that was a bit odd was that once decrypted and imported into the calibre library, I was unable to view the file. Anytime I tried to do so within calibre, it would merely try to re-add it to the library (and begin the decryption process again) - I'm not sure why this is different behavior from what I used to experience. Anyway, I checked in the Calibre Library folder and found the .azw4 file. I then selected it within calibre for conversion to PDF and it worked, so mission accomplished. I'm grateful for the assistance! Have a great week.

**Comment by pdurrant** [comment]
I don't know if calibre has special case code for azw4 or not. You might get a better 'conversion' result by using the KindleUnpack plugin, as an AZW4 file is already really a PDF file, it just needs extracting from the wrapper.

**Comment by ElleKayEm** [comment]
You need to turn on the option to view AZW4 in calibre's built-in viewer.  But I think it converts it to display it which may not work well. I also recommend using the KindleUnpack plugin and using some actual PDF reader.

**Comment by LSStream** [comment]
Thanks, again. I installed and tried the KindleUnpack plug-in, and that works well. I also checked the box under Preferences > Behavior to use calibre's internal viewer for AZW4 files, and that now works fine. I left PDF unchecked, so on the Mac, it opens it Preview, which is fine for me. Thanks so much, once again! The only other thing that would be useful is if the progress bar could give at least some indication that it was successfully processing the conversion (at least for AZW4), which I didn't witness for the e-book in question (about 110 MB or so). Cheers!

**Comment by ElleKayEm** [comment]
You mean processing the DRM removal, right?  That 0% progress might be calibre just waiting for DeDRM to finish before it adds the book.  But that is confusing.

**Comment by LSStream** [comment]
It's certainly possible. In that case, the DeDRM is taking a while, and then the book is added to calibre almost instantly, so the progress bar finishes in a flash. It might be nice if calibre was able to give a status about other processes as they occur, such as plugins like DeDRM, if that's even possible. Thanks!

**Comment by ElleKayEm** [comment]
Yeah, I don't know if that's something that would be on the plugins' side or if it would need to be from calibre's side.
