### ISSUE TITLE
[QUESTION] calibre, version 5.6.0 错误： 未处理的异常: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

### ISSUE THREAD

**Issue by SunSquirrel** [apprenticeharper/DeDRM_tools#1394]
calibre, version 5.6.0
错误： 未处理的异常: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.6  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: zh_CN
Successfully initialized third party plugins: Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
The Obok plugin is not ready for calibre 5 yet.  You will need calibre 4.23 for now.

**Comment by ks202005** [comment]
I'm having this issue with DeDRM_Plugin.zip, not just Obok_plugin.zip. Downgrading to calibre 4.23 fixed it for me.

**Comment by ElleKayEm** [comment]
That's correct.  Pre-release DeDRM 7 is for calibre 5.  DeDRM 6.8 is for calibre 4.23.
