### ISSUE TITLE
[Calibre 5/DeDRM git] Cannot open KFX-ZIP format

### ISSUE THREAD

**Issue by raffaem** [apprenticeharper/DeDRM_tools#1397]
## My Problem

Books in the format of AZW3 are converted seamlessly.

When I import a book in the format KFX-ZIP, the books appear in the list with its metadata and its cover.

But when I double click on it, at first an error popped up that no software was established to open this file format.

Then I went to calibre settings and requested this file format to be opened with the internal viewer.

Now when I open the book it just says it is protected by DRM.

I have the KFX input plugin.

## Log
<details><summary>Log</summary>

```log
calibre Debug log
calibre 5.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing [USER_FOLDER]\Documents\My Kindle Content\B07JZH997Q_EBOK\B07JZH997Q_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as [USER_FOLDER]\AppData\Local\Temp\calibre__en99czk\zpl1cz1v.kfx-zip
DeDRM v7.0.0: Trying to decrypt zpl1cz1v.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: zpl1cz1v
Got DSN key from database default_key
DeDRM v7.0.0: Failed to decrypt with error: unhashable type: 'bytearray'
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in [USER_FOLDER]\AppData\Local
Found K4PC 1.25+ kinf2018 file: [USER_FOLDER]\AppData\Local\Amazon\Kindle\storage\.kinf2018
[11.56] splash screen hidden
[11.56] Started up in 11.56 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe5qk\x14d\xa4\x93.\xa0\xcd\x83\xae4\x16\xec\xd4\xb7\xb4\xa5\xdf\xb8\x08QM_\x9d;%\xc4\x11\xfb\x9a', b'[USER_FOLDER]\\Documents\\My Kindle Content\\B07JZH997Q_EBOK\\B07JZH997Q_EBOK.azw']
Decrypted key file using IDString '3525902189' and UserName 'Raffaele'
DeDRM v7.0.0: Found 1 new key
Decrypting KFX-ZIP ebook: zpl1cz1v
Got DSN key from database default_key_1
DeDRM v7.0.0: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging [USER_FOLDER]\AppData\Local\Temp\calibre__en99czk\zpl1cz1v.kfx-zip
Processing container: B07JZH997Q_EBOK.azw
KFX metadata reader (from KFX Input) activated for [USER_FOLDER]\AppData\Local\Temp\calibre__en99czk\xdl2bwt5_add_books\0\B07JZH997Q_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 233, in GetDecryptedBook
TypeError: unhashable type: 'bytearray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07JZH997Q_EBOK.azw has DRM and cannot Added Where the Crawdads Sing to db in: 0.0
Added 1 books in 3.1 seconds
Worker Launch took: 0.10917973518371582
```
</details>

**Comment by ElleKayEm** [comment]
It looks like DeDRM 7 stills needs some work for KFX format.  I suggest disabling KFX format downloads in Kindle for PC or downloading from the website if you have an E-ink Kindle.

**Comment by raffaem** [comment]
Hello,

I was able to use it with Kindle 1.30 by disabling the KFX download.

I have updated the [wiki](https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM) explaining how to disable KFX downloads for Kindle for PC v1.30 using this [post](https://www.mobileread.com/forums/showthread.php?p=4021279#post4021279)

Let me know if I can help with the KFX format and how

**Comment by ElleKayEm** [comment]
@raffaem You have to run that script each time you want to open Kindle for PC 1.30, right?  And the script edits the Windows registry.  Personally, I'm sticking with 1.17 which doesn't use KFX at all.  When it stops working, I'll use 1.24 which has a simpler way of disabling KFX as long as I can.

If you're all set, you can close the issue.

**Comment by raffaem** [comment]
@ElleKayEm Yes, every time you start Kindle for PC, it must be started by the script and not directly.
If you start it directly, the book will be downloaded in KFX-ZIP format.
If you start it from the script in the link, the book will be downloaded in the AZW3 format.
Yes the script adds a key to the Windows registry, it seems pretty harmless and pretty straightforward.
Can I do something to help support the KFX-ZIP format?
