### ISSUE TITLE
Hopefully this is a user error? What is going on?

### ISSUE THREAD

**Issue by OdeToViceroy** [apprenticeharper/DeDRM_tools#1400]
Convert book 1 of 1 (Local Government in Canada)
DeDRM v7.0.0: Trying to decrypt u4eprxmf.pdf
DeDRM v7.0.0: u4eprxmf.pdf is a PDF ebook
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'generic_eink'
  prefer_metadata_cover: True
  read_metadata_from_opf: '/var/folders/76/8f3qhz257b1fk7x1p9gtkh4m0000gn/C/calibre_5.6.0_tmp_x9_g0g71/x03d5vs_.opf'
Resolved conversion options
calibre version: 5.6.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x119fd99a0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_images': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x119fd9ca0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': True,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/76/8f3qhz257b1fk7x1p9gtkh4m0000gn/C/calibre_5.6.0_tmp_x9_g0g71/x03d5vs_.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 470, in PDFDecrypt
    if keyvalue.encode('hex') not in dedrmprefs['adeptkeys'].values():
AttributeError: 'bytes' object has no attribute 'encode'
DeDRM v7.0.0: Trying to decrypt u4eprxmf.pdf
DeDRM v7.0.0: u4eprxmf.pdf is a PDF ebook
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 470, in PDFDecrypt
    if keyvalue.encode('hex') not in dedrmprefs['adeptkeys'].values():
AttributeError: 'bytes' object has no attribute 'encode'
InputFormatPlugin: PDF Input running
on /var/folders/76/8f3qhz257b1fk7x1p9gtkh4m0000gn/C/calibre_5.6.0_tmp_x9_g0g71/u4eprxmf.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

My OS: Catalina 10.15.7
Computer: MBP 2016

**Comment by ElleKayEm** [comment]
Probably a case of DeDRM 7 not working for Adobe DRM PDFs yet.  If you're using 7.0.0b3, then give the latest 7.0.0b4 a try.  If that still doesn't work, you can go back to calibre 4.23 and DeDRM 6.8.1 or wait for the next release.
