### ISSUE TITLE
[7.0] undeclared Python dependency: PyCryptodome

### ISSUE THREAD

**Issue by salfter** [apprenticeharper/DeDRM_tools#1402]
I checked back to see if some progress had been made at making the DeDRM plugin compatible with Python 3, as Python 2 is pretty aggressively being deprecated...got excited to see that the 7.0 betas address this concern.  I updated Calibre on one of my Gentoo desktops to 5.4.2 and added the plugin.  Configuration still had the serial number of my Kindle Touch in it, so I tried importing a known-DRM'd book.  It was still DRM'd.  Following the instructions to try running Calibre in debug mode, I tried importing it again...got this message:

```
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 521, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 17, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 184, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Added 0 books in 12.2 seconds
```

I tried emerging dev-python/cryptography...no joy.  Next, I tried dev-python/pycryptodome...success!  Since this Python module isn't brought in by a normal Calibre build, it might not be a bad idea to mention in the installation instructions for the plugin that you might need to add PyCryptodome by whatever means your distro provides.

**Comment by ableeker** [comment]
It depends on PyCrypto.  When running Windows it seems to be included with Calibre/DeDRM, but this package isn't available anymore in the standard repositories. However, when you need it, and can't install it, PyCryptodome is available, and is supposed to be a drop-in replacement.

**Comment by xxyzz** [comment]
PyCryptodome was broken untill calibre 5.6. DeDrm plugin should set the minimum calibre to 5.6.0.

**Comment by laxdog** [comment]
Thanks, this saved me a lot of investigation.
