### ISSUE TITLE
Fail to decrypt Kindle for Mac with v7.0.0b4

### ISSUE THREAD

**Issue by ernestyao** [apprenticeharper/DeDRM_tools#1403]
### DeDRM: `7.0.0b4`

I've tried as [this post](https://bestapps.medium.com/tallcalibre-dedrm-plugin-on-mac-catalina-8acf394c9b58) said. So I suppose it's not .KFX concerned. And I just create the default-key.

## Log
<details><summary>Log Title</summary>

```log
转换书籍 第 1 本，共 1 本 (Wagner's Ring of the Nibelung: A Companion)
DeDRM v7.0.0: Trying to decrypt in_ty975.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Wagner's Ring of the Nibelung: A Companion
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/ern/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'ern'  on file  /Users/ern/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c1ee5536b7ec'
trying IDString: b'292035dca6e8'
Decrypted key file using IDString '292035dca6e8' and UserName 'ern'
DeDRM v7.0.0: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  cover: '/var/folders/tv/8456g_ks4wgb37_yyjpj0kk00000gp/C/calibre_5.6.0_tmp_jkyiqyvy/6agewywp.jpeg'
  output_profile: 'kindle_voyage'
  read_metadata_from_opf: '/var/folders/tv/8456g_ks4wgb37_yyjpj0kk00000gp/C/calibre_5.6.0_tmp_jkyiqyvy/uekb6goh.opf'
  preserve_cover_aspect_ratio: True
  insert_blank_line_size: 1.5
  max_toc_links: 500
  verbose: 2
  chapter: "//*[((name()='h1' or name()='h2') and re:test(., 'chapter|book|section|part|prologue|epilogue\\s+', 'i')) or @class = 'chapter']"
  pdf_serif_family: 'FZYaSongS-L-GB'
  pdf_mono_family: 'Courier New'
  minimum_line_height: 180.0
  pdf_mono_font_size: 20
  embed_all_fonts: True
  paper_size: 'a4'
  pdf_sans_family: 'PingFang SC'
Resolved conversion options
calibre version: 5.6.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'chapter|book|section|part|prologue|epilogue\\s+', 'i')) or "
            "@class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/tv/8456g_ks4wgb37_yyjpj0kk00000gp/C/calibre_5.6.0_tmp_jkyiqyvy/6agewywp.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': True,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10e067df0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 1.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 500,
 'minimum_line_height': 180.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x10e06d400>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'a4',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier New',
 'pdf_mono_font_size': 20,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'PingFang SC',
 'pdf_serif_family': 'FZYaSongS-L-GB',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': True,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/tv/8456g_ks4wgb37_yyjpj0kk00000gp/C/calibre_5.6.0_tmp_jkyiqyvy/uekb6goh.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
    raise DrmException("No key found in {0:d} keys tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 6 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.0.0: Trying to decrypt in_ty975.azw
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Wagner's Ring of the Nibelung: A Companion
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 6 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/ern/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'ern'  on file  /Users/ern/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c1ee5536b7ec'
trying IDString: b'292035dca6e8'
Decrypted key file using IDString '292035dca6e8' and UserName 'ern'
DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
    raise DrmException("No key found in {0:d} keys tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 6 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on /var/folders/tv/8456g_ks4wgb37_yyjpj0kk00000gp/C/calibre_5.6.0_tmp_jkyiqyvy/in_ty975.azw
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
calibre.ebooks.DRMError: Wagner's Ring of the Nibelung: A Companion
```
</details>

**Comment by ElleKayEm** [comment]
Was the book downloaded with the installation of Kindle for Mac currently on the same machine and user as calibre with DeDRM?

**Comment by ernestyao** [comment]
> Was the book downloaded with the installation of Kindle for Mac currently on the same machine and user as calibre with DeDRM?

Yes. Same machine & same user.

**Comment by ElleKayEm** [comment]
Then it should work with DeDRM 6.8.1 and calibre 4.23.

**Comment by ernestyao** [comment]
> Then it should work with DeDRM 6.8.1 and calibre 4.23.

The v7.0.0b4 works fine with downloaded .azw3 (with a Kindle serial and account of course). So I suppose it'll work with Kindle for Mac too.
