### ISSUE TITLE
Can't DeDrm eInk Kindle KFX book

### ISSUE THREAD

**Issue by Day1721** [apprenticeharper/DeDRM_tools#1408]
## Can't DeDrm file from my kindle paperwhite

As far as I know (and FAQ tells) DeDRM of books from eInk Kindle devices is supported.
So I installed required plugins for KFX input and added serial number of my kindle paperwhite.
But when I tried to add it to library, it showed up there, with correct metadata, but attempt to convert it to other format failed on error "Book is DRM protected". After some google'ing about it I haven't found solution for it so decided to ask about it here.

And it only happens with KFX books, I can DeDRM AZW3 file from eInk Kindle, it's just doesn't work when used with KFX format.

## Log
<details><summary>Log file of failed DeDRM attempt</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Quality Check (1, 10, 1) && Set KFX metadata (from KFX Output) (1, 45, 0) && KFX Output (1, 45, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Quality Check (1, 10, 1) && Set KFX metadata (from KFX Output) (1, 45, 0) && KFX Output (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: False
[0.00] Starting up...
[0.00] Showing splash screen...
[0.73] splash screen shown
[0.73] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[2.84] main UI initialized...
[2.84] Hiding splash screen
Storage number map:
{(7L, 0L): [(5L, 'C')],
 (7L, 1L): [(2L, 'E'), (5L, 'D')],
 (7L, 2L): [(1L, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G000PP1303950BT0&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=6)
{u'drive_letters': ['G'],
 u'pnp_id_map': {'G': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g000pp1303950bt0&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'G': (2L, 1L)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.0 USBMS: scan from root False G:\documents
DEBUG:    0.1 USBMS: count found in cache: 47, count of files in metadata: 47, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 47
DeviceJob: set_books_in_library finished: time= 0.00799989700317
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[16.64] splash screen hidden
[16.64] Started up in 16.64 seconds with 46 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xeb\x95=\xb3^\x92w\xd2\x19\xcd\xf2\x14n\xbds\xc2\x9a\x82\x0b\x1f\xca\xb5m\xf4'[\x9e\x0f\xd1\xf9 A", 'G:\\documents\\Downloads\\Items01\\\xe3\x83\x9e\xe3\x82\xa4\xe3\x83\x9b\xe3\x83\xbc\xe3\x83\xa0\xe3\x83\x92\xe3\x83\xbc\xe3\x83\xad\xe3\x83\xbc\xef\xbc\x88\xef\xbc\x91\xef\xbc\x89 (\xe3\x83\xa4\xe3\x83\xb3\xe3\x82\xb0\xe3\x83\x9e\xe3\x82\xac\xe3\x82\xb8\xe3\x83\xb3\xe3\x82\xb3\xe3\x83\x9f\xe3\x83\x83\xe3\x82\xaf\xe3\x82\xb9)_B075651TX5.kfx']
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing G:\documents\Downloads\Items01\マイホームヒーロー（１） (ヤングマガジンコミックス)_B075651TX5.kfx
Gather KFX-ZIP (from KFX Input): Gathered 20 file(s) as C:\Users\xxxxx\AppData\Local\Temp\calibrePortableTemp\calibre_cerkjh\h6plfy.kfx-zip
DeDRM v6.8.0: Trying to decrypt h6plfy.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: h6plfy
Got DSN key from database default_key
Found 2 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\xxxxx\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\xxxxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3936556118' and UserName '4d6172656b'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: h6plfy
Got DSN key from database default_key_1
Found 1 keys to try after 11.7 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 11.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 11.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\xxxxx\AppData\Local\Temp\calibrePortableTemp\calibre_cerkjh\h6plfy.kfx-zip
Processing container: CR!0XZ3A6Z7396V50794P0E5H2N4DMT.kfx
Processing container: CR!4T4GB3MD6X1WK2X84C9GMP556A65.kfx
Processing container: CR!5B06WNM1411HZDAYZC6A9A56VQXV.kfx
Processing container: CR!5F3A0772CH1S5CZZY8QTNJ55H65R.kfx
Processing container: CR!6T0JZSTR9D0BSE98HEVN3SSY5VX8.kfx
Processing container: CR!74YZAX0CR115Z79SFCTS3EPRMRF5.kfx
Processing container: CR!7885KQ1ACH6QKFYES4CY991EQ09T.kfx
Processing container: CR!7KVH1W7NG974F8HG326H7KBKRMG4.kfx
Processing container: CR!96S2ZN544X4Q3C6EFVWJ3Z99QH6C.kfx
Processing container: CR!AN20KYG9PX42B7VYTGZ2NJ30NXC4.kfx
Processing container: CR!G40BQ310BD7AH84ZXKWMARJGE97Z.kfx
Processing container: CR!GVE3A963JD07F1JY7TGTH3H8X708.kfx
Processing container: CR!H100J91RT51S9CQS9R1SGE7RV6W5.kfx
Processing container: CR!J14VM5GKT906D1RRDNQBN9JKCY35.kfx
Processing container: CR!MVH8KARVT55PX2NNFQGH89J6YNYM.kfx
Processing container: CR!V1S5WZS7YD0XNDRFXZYVNGJJ8S9A.kfx
Processing container: CR!ZRDSG4V0FN6J7A5JZ6W4RVCC9GRE.kfx
Processing container: metadata.kfx
Processing container: マイホームヒーロー（１） (ヤングマガジンコミックス)_B075651TX5.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
KFXDRMError: Book container マイホームヒーロー（１） (ヤングマガジンコミックス)_B075651TX5.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\xxxxx\AppData\Local\Temp\calibrePortableTemp\calibre_cerkjh\jjm6ad_add_books\0\マイホームヒーロー（１） (ヤングマガジンコミックス)_B075651TX5.kfx-zip
Added マイホームヒーロー（１） (ヤングマガジンコミックス) to db in: 3.0
Added 1 books in 19.9 seconds
Worker Launch took: 0.393000125885
Job: 3 Convert book 1 of 1 (マイホームヒーロー（１） (ヤングマガジンコミックス)) finished

```
</details>

**Comment by ElleKayEm** [comment]
It is not possible to DeDRM KFX format from E-ink Kindle devices at this time.  You can get the book from the website for "download & transfer via usb" for that Kindle in the older formats if available.  Or you can download the book via Kindle for PC/Mac.  If you would like the KFX format, you will need 1.26 or earlier of the Kindle app.  Or you can disable KFX downloads and receive the older formats.

**Comment by Day1721** [comment]
Thanks for fast reply.
Good to know. IMHO it would be great to have in Readme info that "eInk Kindle dedrm is supported, but not in all formats (like KFX)" so people like me could just read it and know that it's dead end (by now at least). Current Readme kind of suggests that all KFX are supported, which isn't true.

**Comment by ElleKayEm** [comment]
There is a [wiki here](https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM).  Also pull requests are welcome to modify the Readme or other help files.
