### ISSUE TITLE
Can't customize 6.5.1 under Windows 7

### ISSUE THREAD

**Issue by JPUnix** [apprenticeharper/DeDRM_tools#141]
I just upgraded DeDRM from 6.0.9 to 6.5.1 for Calibre. When I try to "customize" I get the following error:

calibre, version 2.69.0
ERROR: Unhandled exception: <b>KeyError</b>:'androidkeys'

calibre 2.69 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 291, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 369, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 632, in config_widget
  File "calibre_plugins.dedrm.config", line 57, in __init__
  File "calibre_plugins.dedrm.prefs", line 50, in __getitem__
  File "site-packages\calibre\utils\config.py", line 398, in __getitem__
KeyError: 'androidkeys'

**Comment by ElleKayEm** [comment]
Try removing the plugin, restarting calibre, reloading the plugin, then restarting calibre again before trying to customize.

**Comment by JPUnix** [comment]
Yes! That fixed it! Thank you!

**Comment by JPUnix** [comment]
Closed per recommended fix.
