### ISSUE TITLE
WindowsError:1155

### ISSUE THREAD

**Issue by Tomolin** [apprenticeharper/DeDRM_tools#1414]
# WindowsError: [Error 1155]
Error 1155 occurs, even I followed the instruction in mobileread and FAQs

## Log
<details><summary>Log Title</summary>

```log
calibre, version 4.23.0
ERROR: Unhandled exception: <b>WindowsError</b>:[Error 1155] : u'C:\\Users\\tomo1\\Calibre \u4e66\u5e93\\Frederik Obermaier\\The Panama Papers_ Breaking the Stor (37)\\The Panama Papers_ Breaking the - Frederik Obermaier.kfx'

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && Obok DeDRM (6, 7, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\view.py", line 246, in view_triggered
  File "site-packages\calibre\gui2\actions\view.py", line 329, in _view_books
  File "site-packages\calibre\gui2\actions\view.py", line 281, in _view_calibre_books
  File "site-packages\calibre\gui2\actions\view.py", line 108, in view_format_by_id
  File "site-packages\calibre\gui2\actions\view.py", line 157, in _view_file
  File "site-packages\calibre\gui2\actions\view.py", line 147, in _launch_viewer
  File "site-packages\calibre\gui2\__init__.py", line 1286, in open_local_file
WindowsError: [Error 1155] : u'C:\\Users\\tomo1\\Calibre \u4e66\u5e93\\Frederik Obermaier\\The Panama Papers_ Breaking the Stor (37)\\The Panama Papers_ Breaking the - Frederik Obermaier.kfx'
```
</details>

**Comment by ElleKayEm** [comment]
This error is because calibre doesn't know what program to open this with.  Can't tell if it still has DRM or not from this log.  Post a log of adding the book to calibre:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Tomolin** [comment]
## calibre Debug log
```
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 185.429657795 x 185.853658537
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[1.03] splash screen shown
[1.03] Initializing db...
[1.03] db initialized
[1.03] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[2.39] main UI initialized...
[2.39] Hiding splash screen
[36.34] splash screen hidden
[36.34] Started up in 36.34 seconds with 8 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['GR\x8bL\x01=O\xa8\xc1zMp\xbf\x1a\xa0\x9a\xd3<\xb0\xff\xd2\xa7\x88\x18gF\x87\xd1\xee8gE', 'C:\\Users\\tomo1\\Documents\\My Kindle Content\\B06X9QPDN2_EBOK\\B06X9QPDN2_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\tomo1\Documents\My Kindle Content\B06X9QPDN2_EBOK\B06X9QPDN2_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\tomo1\AppData\Local\Temp\calibre_y3xueg\jotmhi.kfx-zip
DeDRM v6.8.0: Trying to decrypt jotmhi.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: jotmhi
Got DSN key from database default_key_2
Got DSN key from database default_key
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5c04ac2b-a70b-4499-9f5d-2121c12202bf.voucher
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B06X9QPDN2_EBOK.azw
Decryption succeeded after 0.2 seconds
DeDRM v6.8.0: Finished after 0.2 seconds
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\tomo1\AppData\Local\Temp\calibre_y3xueg\pp3dxq.kfx-zip
Processing container: B06X9QPDN2_EBOK.azw
Processing container: CR!DDPPEZXT4D17X6S3JD2ATCSN9SKD.azw.res
Processing container: CR!DJHGEQ8P7X373161B5SB5EAZSDGT.azw.md
kfxgen version: 20.12.238.0, 7.228.1.0
Features: CanonicalFormat-2, kfxgen.textBlock-1, max_id-785, reflow-style-2, yj_table-1
Metadata: ASIN=B06X9QPDN2, asset_id=CR!GEFQVFR2JX78Q3WHMB7BH58GSTG5, author="Obermaier, Frederik", author="Obermayer, Bastian", book_id=FF5xaVP3TCCN2ar1YbvxCg0, cde_content_type=EBOK, content_id=B06X9QPDN2, cover_image=1251x1920, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2017-03-30, language=en, override_kindle_font=False, pages=471, publisher="Oneworld Publications", reading_orders=1, selection=enabled, title="The Panama Papers: Breaking the Story of How the Rich and Powerful Hide Their Money"
Package KFX (from KFX Input): Imported as C:\Users\tomo1\AppData\Local\Temp\calibre_y3xueg\623cvu.kfx
KFX metadata reader (from KFX Input) activated for C:\Users\tomo1\AppData\Local\Temp\calibre_y3xueg\s_uwmv_add_books\0\B06X9QPDN2_EBOK.kfx
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Panama Papers: Breaking the Story of How the Rich and Powerful Hide Their Money to db in: 0.1
Added 1 books in 4.8 seconds
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\actions\view.py", line 246, in view_triggered
  File "site-packages\calibre\gui2\actions\view.py", line 329, in _view_books
  File "site-packages\calibre\gui2\actions\view.py", line 281, in _view_calibre_books
  File "site-packages\calibre\gui2\actions\view.py", line 108, in view_format_by_id
  File "site-packages\calibre\gui2\actions\view.py", line 157, in _view_file
  File "site-packages\calibre\gui2\actions\view.py", line 147, in _launch_viewer
  File "site-packages\calibre\gui2\__init__.py", line 1286, in open_local_file
WindowsError: [Error 1155] : u'C:\\Users\\tomo1\\Calibre \u4e66\u5e93\\Frederik Obermaier\\The Panama Papers_ Breaking the Stor (38)\\The Panama Papers_ Breaking the - Frederik Obermaier.kfx'
```

**Comment by ElleKayEm** [comment]
DRM is successfully removed.  Looks like you just need to set what calibre should open kfx files with.

**Comment by Tomolin** [comment]
I don't know how to fix this so far, but I work out another way without KFX files from this post
[https://www.mobileread.com/forums/showthread.php?p=4012925#post4012925](url)

**Comment by ElleKayEm** [comment]
This is not a DeDRM issue.  As I said, the DRM is removed.  You just don't have calibre's viewer set to open KFX files and there isn't an external program associated with that file type.  But you are probably better off avoiding KFX format anyway.  If you're all set, you can close the issue.
