### ISSUE TITLE
Can not decrypt book pdf with Adobe DRM (epub works)

### ISSUE THREAD

**Issue by dny238** [apprenticeharper/DeDRM_tools#1415]
I tried to follow the directions in 
https://github.com/apprenticeharper/DeDRM_tools/issues/348
but it didn't help. I tried another computer as well to test and that doesn't work either. 

Epubs work well. Just not PDF's. 

I tried ADE 2.0.1 and the newer 4.5.1. 
Thoughts? 
Rob

## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
Convert book 1 of 1 (For a future to be possible commentaries on the five wonderful)
DeDRM v7.0.0: Trying to decrypt s2dvc3c7.pdf
DeDRM v7.0.0: s2dvc3c7.pdf is a PDF ebook
DeDRM v7.0.0: Trying Encryption key default_key
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  verbose: 2
  read_metadata_from_opf: 'C:\\Users\\<user>\\AppData\\Local\\Temp\\calibre_zns2owv0\\w1tp0f34.opf'
  output_profile: 'kindle'
Resolved conversion options
calibre version: 5.7.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000019819F469D0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x0000019819F46EE0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\<user>\\AppData\\Local\\Temp\\calibre_zns2owv0\\w1tp0f34.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.0.0: Trying to decrypt s2dvc3c7.pdf
DeDRM v7.0.0: s2dvc3c7.pdf is a PDF ebook
DeDRM v7.0.0: Trying Encryption key default_key
DeDRM v7.0.0: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with key default_key after 0.0 seconds
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Found 1 keys
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.0 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on C:\Users\<user>\AppData\Local\Temp\calibre_zns2owv0\s2dvc3c7.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
Exception ignored in: <function NativeFunction.__del__ at 0x000001981AB1D160>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001981AB1D160>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
```
</details>

**Comment by ElleKayEm** [comment]
DeDRM 7 needs more work.  Either use DeDRM 6.8 with calibre 4.23 or wait to try the next release.

**Comment by dueringa** [comment]
I can confirm that using a old version of calibre + DeDRM works for me in the same scenario (encrypted PDF, doesn't work with most recent calibre + DeDRM beta)
