### ISSUE TITLE
[QUESTION] Couldn't decrypt purchased ".azw" file with Mac (11.0.1)

### ISSUE THREAD

**Issue by ajboxjr** [apprenticeharper/DeDRM_tools#1417]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Couldn't decrypt purchased ".azw" file with Mac (11.0.1)
I have successfully been able to prevent kfx files from downloading, but it seems as if I can't get .azw3 which I believe is the issue. Same results occur on upgraded 1.30.0

## Log
<details><summary>7.0.0b4 could not decrypt ".azw"</summary>

```log
calibre Debug log
calibre 5.7  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
calibre 5.7  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
[1.94] main UI initialized...
[1.94] Hiding splash screen
Starting QuickView
[16.30] splash screen hidden
[16.30] Started up in 16.30 seconds with 2 books

Debugging DND event
text/uri-list 121 b'file:///Users/ajboxjr/Library/Application%20Support/Kindle/My%20Kindle%20Content/B07DCF4K49_EBOK/B07DCF4K49_EBOK.azw\r\n' 


Firefox rurl: None None
URLS: ['file:///Users/ajboxjr/Library/Application%20Support/Kindle/My%20Kindle%20Content/B07DCF4K49_EBOK/B07DCF4K49_EBOK.azw']
Paths: ['/Users/ajboxjr/Library/Application Support/Kindle/My Kindle Content/B07DCF4K49_EBOK/B07DCF4K49_EBOK.azw']
Extensions: frozenset({'azw'})
DeDRM v7.0.0: Trying to decrypt B07DCF4K49_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Surviving Schizophrenia, 7th Edition
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.4 seconds
Found k4Mac kinf2018 file: /Users/ajboxjr/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'ajboxjr'  on file  /Users/ajboxjr/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'6116a4631b32'
Decrypted key file using IDString '6116a4631b32' and UserName 'ajboxjr'
DeDRM v7.0.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Surviving Schizophrenia, 7th Edition
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
    raise DrmException("No key found in {0:d} keys tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```
</details>

**Comment by ElleKayEm** [comment]
With Kindle for Mac, any main book file will have the AZW extension regardless of the underlying format.  You won't see the AZW3 (or other specific format) extension until you remove the DRM.  If the .azw file also has .res and .md files in its folder, then that's KFX.    Take a look at this post that gives the details for dealing with the later versions of Kindle for Mac:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

If you don't have KFX format, then it's probably just DeDRM 7 not handling everything yet.  Try DeDRM 6.8.1 with calibre 4.23 or wait for the next DeDRM release.

**Comment by ajboxjr** [comment]
Got it to work! Thanks for the suggestion
