### ISSUE TITLE
Error when trying to install DeDRM tools in Calibre

### ISSUE THREAD

**Issue by BriMan83** [apprenticeharper/DeDRM_tools#1421]
Calibre Version: 4.23 (tried on both 32 and 64 bit versions)
DeDRM Version: 6.8.0
ADE 2.0.1.78765

ADE installed fine and can open the protected book with no problem.  Calibre installs and opens fine.  When I go to the advanced options in calibre and try to add the DeDRM_tools_6.8.0 file, it pops about the zip file not having a top level init.py file.  Here are the contents of the details window.

```
4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Brian\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive instead of the plugin itself.  Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

**Comment by bouzas** [comment]
When trying to load DeDRM_plugin.zip:

calibre, version 5.7.2
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.7.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by BriMan83** [comment]
I don't know how I missed that in the FAQ.  Thank you Elle.  It's throwing me another error while trying to remove the DRM, but I'll open a new ticket for that.  Unzipping the archive fixed this one.

**Comment by ElleKayEm** [comment]
@bouzas 
Either install pre-release DeDRM 7.0.0b4 or go back to calibre 4.23 for DeDRM 6.8.
