### ISSUE TITLE
Generating errors when trying to remove DRM from Adobe

### ISSUE THREAD

**Issue by BriMan83** [apprenticeharper/DeDRM_tools#1425]
Calibre Version: 4.23 [64 bit]
DeDRM Version: 6.8.1
Adobe DE: 2.0.1.78765

I have a PDF file encrypted with the Adept DRM.  It opens fine when I open it in ADE, but when I try to open it in Calibre it throws errors.  This is the error that is in the pop-up when I try to open it in the built in reader.

```
calibre, version 4.23.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Brian\Calibre Library\Unknown\The Party Hop (2)\The Party Hop - Unknown.pdf. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\viewer\ui.py", line 468, in _load_ebook_worker
  File "site-packages\calibre\gui2\viewer\convert_book.py", line 234, in prepare_book
  File "site-packages\calibre\gui2\viewer\convert_book.py", line 191, in do_convert
ConversionFailure: Failed to convert book: C:\Users\Brian\Calibre Library\Unknown\The Party Hop (2)\The Party Hop - Unknown.pdf with error:
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
InputFormatPlugin: PDF Input running
on C:\Users\Brian\Calibre Library\Unknown\The Party Hop (2)\The Party Hop - Unknown.pdf
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Python function terminated unexpectedly
  pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages\calibre\srv\render_book.py", line 862, in viewer_main
  File "site-packages\calibre\srv\render_book.py", line 855, in render_for_viewer
  File "site-packages\calibre\srv\render_book.py", line 830, in render
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 90, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
```

**Comment by ElleKayEm** [comment]
The internal viewer does not do well with PDFs.  Let's see an import log to figure out what's going on with the DRM removal:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by BriMan83** [comment]
Apparently my system knows when you get involved and decides to just start doing it's job.  I tried removing it and reimporting it twice before I opened a ticket, and it worked flawlessly now.
