### ISSUE TITLE
Syntax error installing plugin

### ISSUE THREAD

**Issue by maurerc** [apprenticeharper/DeDRM_tools#1427]
Tried to install 7.0.0b4 on an M1 Mac. Calibre reported this error. Repeated after restarting.

calibre, version 5.7.2
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && Package KFX (from KFX Input) (1, 36, 0) && Find Duplicates (1, 8, 3) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 46, 0) && KFX Output (1, 46, 0) && Quality Check (1, 11, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
You did NOT unzip it and are loading the entire DeDRM_plugin_7.0.0b4.zip file?

**Comment by akh8zm** [comment]
Rando dropping in 🙌 Just ran into this issue myself trying to install the plugin. After snooping around it looks like if you have Calibre5 it won't work since DeDRM isn't in Python3 yet (still written in Python2). Other issues suggest downgrading to Calibre4 and retrying. See #1245 and the more recent #1324

**Comment by ElleKayEm** [comment]
@akh8zm The pre-release DeDRM 7.0.0.b4 which the OP says they are trying to load is in Python 3 and requires calibre 5.  But it does look like they may actually be trying to load the Python 2 version which only works with calibre 4 (or 3).

**Comment by innovationdriver** [comment]
Thank you for all of your hard work on the very useful software.
Tried to install 6.8.1 into Calibre 5.7.2 on Mac running Mojave 10.14.6. Calibre returned a syntax Error as follows. Tried twice, including re-starting Calibre.

calibre, version 5.7.2
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && Package KFX (from KFX Input) (1, 36, 0) && Find Duplicates (1, 8, 3) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
DeDRM 6.8.1 needs no later then calibre 4.23.  If you want to stick with calibre 5, you can try pre-release DeDRM 7.0.0b4.  Be aware that that version still needs work in some areas.

**Comment by innovationdriver** [comment]
Super helpful; thanks!

**Comment by awilkins** [comment]
Getting this in Calbre 4.99.4 ; probably because it's Ubuntu 20.04 and the default Python install is 3.8.5

```
calibre, version 4.99.4
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/awilkins/Downloads/DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.8.0-41-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.8.0-41-generic', '#46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021')
Python 3.8.5
Interface language: en_GB
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 193, in load
    plugin_name = self._locate_code(zf, path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 289, in _locate_code
    raise InvalidPlugin(('The plugin in %r is invalid. It does not '
calibre.customize.InvalidPlugin: The plugin in '/home/awilkins/Downloads/DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by ElleKayEm** [comment]
@awilkins That's the beta version of calibre with Python 3.  You'll need DeDRM 7.0.3.  I'd recommend updating calibre too.

**Comment by awilkins** [comment]
Yeah, I just twigged that because the top-level binary has the Python 3 shebang at the top. I tried the 7.0.3 release but it's metadata markers say "5 and above" so it refused to install. Will have a look at getting Calibre 5 (PPA time, probably).
