### ISSUE TITLE
[QUESTION] DeDRM Kindle no longer working after upgrading & downgrading Calibre

### ISSUE THREAD

**Issue by ThomasDaheim** [apprenticeharper/DeDRM_tools#1429]
### DeDRM: `6.8.0`

I managed to accidentally upgrade Calibre to 5.27. After I noticed that DeDRM 6.8.0 isn't working with it I downgraded to Calibre 4.23. And now my DeDRM plugin (after new install) isn't working anymore. Below a log from one of the failed attempts. Error in "check_for_drm". Any ideas what I could do to get it running again?

Thanks,
Thomas

## Log
```
C:\Program Files\Calibre2>calibre-debug -g
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.1467181467 x 94.0740740741
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.51] db initialized
[0.51] Constructing main UI...
[2.16] main UI initialized...
[2.16] Hiding splash screen
[2.44] splash screen hidden
[2.44] Started up in 2.44 seconds with 158 books
Worker Launch took: 0.121999979019
Job: 0 Convert book 1 of 1 (******) finished
Convert book 1 of 1 (******)
        Conversion options changed from defaults:
          prefer_metadata_cover: True
          read_metadata_from_opf: u'******'
          cover: u'******'
          verbose: 2
        Resolved conversion options
        calibre version: 4.23.0
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': u'******',
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'epub_version': u'2',
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002DA54E11C08>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000002DA54E19788>,
         'page_breaks_before': u"//*[name()='h1' or name()='h2']",
         'prefer_metadata_cover': True,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'******',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: MOBI Input running
        on ******
        Python function terminated unexpectedly
          ****** (Error Code: 1)
         Traceback (most recent call last):
          File "site.py", line 114, in main
          File "site.py", line 88, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
          File "site-packages\calibre\customize\conversion.py", line 246, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 39, in convert
          File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 162, in extract_content
          File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
        calibre.ebooks.DRMError: ******
```

**Comment by ElleKayEm** [comment]
Did you remove and re-add the book to calibre?

**Comment by ThomasDaheim** [comment]
That did the trick! Thanks a lot for the fast response.
