### ISSUE TITLE
[QUESTION] v7.0.0b4 doesn't work with .azw from Kindle for PC 1.30

### ISSUE THREAD

**Issue by ZYinMD** [apprenticeharper/DeDRM_tools#1430]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

v7.0.0b4 doesn't work with .azw from Kindle for PC 1.30
### Note:
I got a 9-digit key from the "Decrypted key file using id string" part in the log, and put that key into an [online converter](http://onlineconverter.epubor.com/kindle-drm-removal.htm), and successfully decrypted my book. So I assume it's a bug of the plugin?

## Log
<details><summary>calibre Debug log</summary>

```log
calibre Debug log
calibre 5.6 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0)
calibre 5.6 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.81139489194499 x 95.9160839160839
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
Starting QuickView
[4.33] splash screen hidden
[4.34] Started up in 4.34 seconds with 65 books
Worker Launch took: 0.20499706268310547
Job: 0 Convert book 1 of 1 (Harry Potter: The Complete Collection (1-7)) finished
Convert book 1 of 1 (Harry Potter: The Complete Collection (1-7))

	DeDRM v7.0.0: Trying to decrypt t7672552.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Harry Potter: The Complete Collection (1-7)
	Got DSN key from database D13 Kindle App
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.0.0: Failed to decrypt with error: No key found in 4 keys tried.
	DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Zhi\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Zhi\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2819223229' and UserName 'Su'
	DeDRM v7.0.0: Ultimately failed to decrypt after 4.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  no_default_epub_cover: True

	  verbose: 2

	  margin_left: 2.0

	  minimum_line_height: 150.0

	  search_replace: '[["<p>(\\\\s*\\uff08.{1,3}\\uff09.+)</p>", "<p class=\\"chapter\\">\\\\1</p>"]]'

	  insert_blank_line: True

	  margin_right: 2.0

	  read_metadata_from_opf: 'C:\\Users\\Zhi\\AppData\\Local\\Temp\\calibre_8vfuyhcd\\bsc0h00l.opf'

	  insert_blank_line_size: 0.8

	  output_profile: 'sony'

	  change_justification: 'left'

	  cover: 'C:\\Users\\Zhi\\AppData\\Local\\Temp\\calibre_8vfuyhcd\\fktg4ekq.jpeg'

	  margin_top: 2.0

	  margin_bottom: 2.0

	Resolved conversion options

	calibre version: 5.6.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'left',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Zhi\\AppData\\Local\\Temp\\calibre_8vfuyhcd\\fktg4ekq.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x08EB84A8>,

	 'insert_blank_line': True,

	 'insert_blank_line_size': 0.8,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 2.0,

	 'margin_left': 2.0,

	 'margin_right': 2.0,

	 'margin_top': 2.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 150.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': True,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.SonyReaderOutput object at 0x08EB88B0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Zhi\\AppData\\Local\\Temp\\calibre_8vfuyhcd\\bsc0h00l.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[["<p>(\\\\s*\\uff08.{1,3}\\uff09.+)</p>", "<p '

	                   'class=\\"chapter\\">\\\\1</p>"]]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 keys tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 627, in run

	  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 4.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.0.0: Trying to decrypt t7672552.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Harry Potter: The Complete Collection (1-7)
	Got DSN key from database D13 Kindle App
	Found 4 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.0.0: Failed to decrypt with error: No key found in 4 keys tried.
	DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Zhi\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Zhi\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2819223229' and UserName 'Su'
	DeDRM v7.0.0: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 keys tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 627, in run

	  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\Zhi\AppData\Local\Temp\calibre_8vfuyhcd\t7672552.azw

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: Harry Potter: The Complete Collection (1-7)



```
</details>

**Comment by ElleKayEm** [comment]
Do you have KFX downloads disabled on Kindle for PC 1.30?

Definitely more work to be done on DeDRM 7.  You can always use DeDRM 6.8 with calibre 4.23 or wait to try the next DeDRM release.

**Comment by ZYinMD** [comment]
I don't see a setting to "disable KFX downloads" on my Kindle for PC 1.30, where is it? But anyway, I didn't modify the default settings after installing Kindle for PC 1.30.

I believe my book isn't in KFX format? In `My Kindle Content`, I find these files:
```
B01B3DIPMW_EBOK.apnx
B01B3DIPMW_EBOK.azw
B01B3DIPMW_EBOK.lpr
B01B3DIPMW_EBOK.mbpV2
B01B3DIPMW_EBOK.phl
```
Does it mean the book isn't in KFX format?

**Comment by ElleKayEm** [comment]
No, that doesn't seem to be kfx or you'd see .voucher, .res, and .md files.  Try 64-bit calibre.  The problem might just be the file size.

**Comment by ZYinMD** [comment]
Yeah I was using the portable version of calibre. The [official download](https://calibre-ebook.com/download_portable) doesn't seem to provide a portable 64-bit version? Anyway my problem is solved for now. Thanks for your help.

If you need my large .azw file to test I can send it to you.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
