### ISSUE TITLE
Fails to decrypt using BigSur and DeDRM 7.0

### ISSUE THREAD

**Issue by Lxstr** [apprenticeharper/DeDRM_tools#1435]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title

Fails to decrypt using BigSur and DeDRM 7.0
Thanks for the great work. Will try calibre 4 in the meantime.

## Log
<details><summary>Does not decrypt</summary>

```log

calibre Debug log
calibre 5.6  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Kindle hi-res covers (0, 5, 0)
calibre 5.6  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Kindle hi-res covers (0, 5, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Initializing db...
[0.04] db initialized
[0.04] Constructing main UI...
[0.76] main UI initialized...
[0.76] Started up in 0.76 seconds with 397 books
Starting QuickView
DeDRM v7.0.0: Trying to decrypt B002RI90M2_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Certain Je Ne Sais Quoi
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/lex/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'lex'  on file  /Users/lex/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'bba50777bfcd'
trying IDString: b'bba50777bfcc'
trying IDString: b'bd9b4a887112'
Decrypted key file using IDString 'bd9b4a887112' and UserName 'lex'
DeDRM v7.0.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
    raise DrmException("No key found in {0:d} keys tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added A Certain Je Ne Sais Quoi to db in: 0.0
Added 1 books in 1.6 seconds
```
</details>

**Comment by Lxstr** [comment]
Calibre 4 and DeDRM 6 work fine with the same file and same kindle install.

**Comment by ElleKayEm** [comment]
What extension does the file have in calibre 4 when successfully decrypted?  With calibre 5.6, do you have the latest beta 7.0.0b4?

**Comment by ElleKayEm** [comment]
Was calibre 5 with DeDRM 7 on the same machine and user as the Kindle for Mac installation where the book was downloaded?

**Comment by Lxstr** [comment]
@ElleKayEm For some reason the extension disappeared but I'm confident it was the latest b4. I reinstalled the b4 and same issue occurs with other books. They are all azw and I have run sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test. 

Also yes the same machine and user. It is a M1 chip Mac, but I'm not sure what that would effect.

**Comment by ElleKayEm** [comment]
All the beta versions just show 7 in the logs - and 4b does address a Big Sur specific issue so that's why I asked.  What extension did the successfully decrypted books show inside calibre 4?  If they were successfully decrypted, it won't be the generic azw of all formats that you see in the Kindle content folder.

**Comment by Lxstr** [comment]
Went to mobi format. I can't be sure which beta so happy to close for now and I'll reattempt with next release.

**Comment by ElleKayEm** [comment]
It definitely seems like there's something about Big Sur that's still not working with DeDRM 7.  Others are also reporting that they need to stick with DeDRM 6.8.1 and calibre 4.23.

**Comment by apprenticeharper** [comment]
I note that the report is of a machine with the new ARM-based M1 chip. This might also be relevant. It will be some time before I have an M1-based machine to play with.

**Comment by adamwinn** [comment]
I have an m1 mac too and couldn't get DeDRM 7.0.3 and calibre 5 to work either.  I got the same `No key found in 4 keys tried.` message.  Reverting to DeDRM 6.8 + calibre 4 worked tho

**Comment by shatteringlass** [comment]
I have this same error on Big Sur but Intel Mac, with DeDRM 7.0.3. and calibre 5.

**Comment by ElleKayEm** [comment]
@shatteringlass 
Have you tried calibre 4.23 and DeDRM 6.8.1?

**Comment by shatteringlass** [comment]
@ElleKayEm sure, it does work for some reason.

**Comment by robingirard** [comment]
I have a similar problem here with Big Sur, an intel processor (not M1 !), calibre 5.19, DeDRM 7.2.1 , sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test successful, azw file transfered from folder My kindle content to calibre. But when I try to open it or convert it in calibre I have this error : 
<img width="377" alt="Capture d’écran 2021-05-30 à 16 49 04" src="https://user-images.githubusercontent.com/4168448/120108776-f4a1c700-c166-11eb-9969-7a33adfc98c9.png">

**Comment by ElleKayEm** [comment]
Try using calibre 4.23 and DeDRM 6.8.1.  If that works, then you should be able to update back to your current versions.

**Comment by robingirard** [comment]
I've tried calibre 4.23 and DeDRM 6.8.1. Same error, in addition in this case, I have noticed that the encryption key cannot be found (I don't have this error with C5.x DeDRM7) 
<img width="440" alt="Capture d’écran 2021-05-30 à 17 37 11" src="https://user-images.githubusercontent.com/4168448/120110422-aba14100-c16d-11eb-9212-24c31acc8a68.png">

**Comment by ElleKayEm** [comment]
Let's see a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by robingirard** [comment]
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.40] db initialized
[0.40] Constructing main UI...
[1.52] main UI initialized...
[1.52] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /Users/robin.girard/Documents/Perso/Livres/Kindle/My Kindle Content/B009H4ZB3G_EBOK/B009H4ZB3G_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.8.0: Trying to decrypt B009H4ZB3G_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Alan Turing: The Enigma
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/robin.girard/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[13.99] splash screen hidden
[14.00] Started up in 14.00 seconds with 815 books
Added Alan Turing: The Enigma to db in: 0.1
Added 1 books in 1.1 seconds

**Comment by ElleKayEm** [comment]
This book was installed with the currently installed version of Kindle for Mac on the same machine and user as calibre with DeDRM?  Are you certain this is DeDRM 6.8.1?  Unfortunately 6.8.1 didn't get its version number properly updated and shows 6.8.0 in calibre and in debug logs.  But it has an update specifically for retrieving the Kindle key on Mac.

**Comment by robingirard** [comment]
Passing from 6.8.0 to 6.8.1 solved my problem with calibre 4.23. Thanks a lot !
