### ISSUE TITLE
Fail Decrypt epub and pdf - Calibre 5.7.2 DeDRM Plugin v7.0.0b4

### ISSUE THREAD

**Issue by digedag23** [apprenticeharper/DeDRM_tools#1441]
calibre Fehlerdiagnoseprotokoll
calibre 5.7.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 0, 0) && EpubMerge (2, 11, 0) && Find Duplicates (1, 8, 3)
calibre 5.7.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 0, 0) && EpubMerge (2, 11, 0) && Find Duplicates (1, 8, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.45] splash screen shown
[0.45] Initializing db...
[1.42] db initialized
[1.42] Constructing main UI...
[3.12] main UI initialized...
[3.12] Hiding splash screen
Starting QuickView
DeDRM v7.0.0: Trying to decrypt Unbekannt.epub
DeDRM v7.0.0: Verifying zip archive integrity
DeDRM v7.0.0: Error 'can only concatenate str (not "bytes") to str' when checking zip archive
[14.14] splash screen hidden
[14.14] Started up in 14.14 seconds with 22310 books
Added Kriegt das Papa, oder kann das to db in: 1.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.zipfix", line 143, in fix
  File "C:\Users\xxx\AppData\Local\Temp\calibre_y4pl7z_o\qdychrtzplugin_unzip\zipfilerugged.py", line 826, in read
  File "C:\Users\xxx\AppData\Local\Temp\calibre_y4pl7z_o\qdychrtzplugin_unzip\zipfilerugged.py", line 864, in open
zipfilerugged.BadZipfile: File name in directory "b'OEBPS/cont1\xafv\xa6\x10\xbc\xde'" and header "b'OEBPS/content.opf'" differ.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 205, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 146, in fix
  File "calibre_plugins.dedrm.zipfix", line 108, in getfiledata
  File "calibre_plugins.dedrm.zipfix", line 81, in uncompress
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
  File "calibre_plugins.dedrm.__init__", line 208, in ePubDecrypt
Exception: can only concatenate str (not "bytes") to str
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 195, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 218, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 156, in read_bytes
  File "calibre\utils\zipfile.py", line 1006, in read
  File "calibre\utils\zipfile.py", line 1034, in open
  File "calibre\utils\zipfile.py", line 995, in getinfo
KeyError: "There is no item named 'OEBPS/content.opf' in the archive"
DeDRM v7.0.0: Trying to decrypt Langenscheidt Universal Sprachf - Unbekannt.pdf
DeDRM v7.0.0: Unbekannt_01.pdf is a PDF ebook
DeDRM v7.0.0: Trying Encryption key adobekey_1_12345
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with key adobekey_1_12345 after 0.1 seconds
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with key adobekey_1_12345 after 0.1 seconds
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 1 books in 1.7 seconds
Added Langenscheidt Universal Sprachf to db in: 1.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 343, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x00000202AF9FCCA0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x00000202AF9FCCA0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
Added 1 books in 1.9 seconds
is not callable

**Comment by ElleKayEm** [comment]
There have been previous reports of Adobe DRM PDFs not decrypting with DeDRM 7, but you should be able to decrypt EPUBs.  Is Adobe Digital Editions 2.0.1 authorized with your Adobe ID and used to download these books on the same machine and user as calibre with DeDRM?  Have you tried with calibre 4.23 and DeDRM 6.8?

**Comment by digedag23** [comment]
Yes. The Adobe ID is authorized. 
Sometimes EPUBS are decrypt. Sometime Epubs are not decrypt. I can't backtrack why.
I have a try caliebre 4.23 and DeDrm 6.8. There are a fail i Phyton when I open calibre.

**Comment by ElleKayEm** [comment]
Both Adobe DRM PDFs and EPUBs should work with calibre 4.23/DeDRM 6.8.  And anything connected to that same Adobe ID should also work.  Unless they're from different sources and one ebookstore is using hardened DRM.  But if you use ADE 2.0.1, you won't be able to download a book that has hardened  DRM that can't be decrypted.

**Comment by menteb** [comment]
I also run into problems while trying to import a PDF and run it through the module.
I'm using v7.0.0b4.

Any help is welcome!

This is the trace:

```
calibre Debug log
calibre 5.8.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
calibre 5.8.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.32] db initialized
[0.32] Constructing main UI...
[1.02] main UI initialized...
[1.02] Hiding splash screen
Starting QuickView
[5.84] splash screen hidden
[5.84] Started up in 5.84 seconds with 4 books
DeDRM v7.0.0: Trying to decrypt awesome_document.pdf
DeDRM v7.0.0: awesome_document.pdf is a PDF ebook
DeDRM v7.0.0: Trying Encryption key default_key
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
    parser = PDFParser(doc, inf)
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
    self.doc.set_parser(self)
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
    self.xrefs = parser.read_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
    pos = self.find_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
    for line in self.revreadlines():
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
    n = max(s.rfind('\r'), s.rfind('\n'))
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
    parser = PDFParser(doc, inf)
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
    self.doc.set_parser(self)
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
    self.xrefs = parser.read_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
    pos = self.find_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
    for line in self.revreadlines():
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
    n = max(s.rfind('\r'), s.rfind('\n'))
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 343, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
Added awesome_document to db in: 0.0
Added 1 books in 2.2 seconds
```

**Comment by digedag23** [comment]
Some epub  (not all) or pdf  I can't import in Calibre. I tried this with Calibre 4.23 and DeDrm 6.8.x and also with the current Version from Calibre and DeDrm 7.0.x
For the epub, which can't import, but I can open the e-book in the calibre e-book viewer. There I can't see the cover page, but I see the text and I can read it.
When I open the same epub in the calibre e-book editor, than I can't open it. May be, that is the same Problem, that I can't import the e-book into calibre.

**Comment by ElleKayEm** [comment]
@menteb Try calibre 4.23 and DeDRM 6.8.1.

@digedag23 If you can open and read it with the calibre ebook viewer, then it is DRM-free.  Not being able to add something to the calibre library sounds like a calibre issue, not necessarily anything DeDRM related.  Normally calibre will add a book to the library with DRM or not.  Can you add it with DeDRM disabled?

**Comment by digedag23** [comment]
When I add the e-book with DeDrm disabled, the e-book will be added in calibre, but when I open the e-book, the book is decrypt .

The REport:"This book is locked by DRM. To learn more or convert this book in calibre, click here."

When I abled DeDrm in Calibre I can only open the e-book in the calibre e-book viewer and it is not decrypt. I can read this without problems.

In the calibre e-book editor or my ebook read it is not possible. 
May be it is an problem with the cover page or the structure from the ebook. It definitely an ebook with DRM and I think, it is no hard DRM.  I use only Adobe 2.x and I tried this in calibre 4.23/DeDrm 6.8.1 and newer versions.

**Comment by ableeker** [comment]
@digedag23 Decrypting PDF isn't working yet. About your issue with the ePub, apprenticeharper has imported some code that should fix it. It hasn't been released yet, so you'll have to create the DeDRM-plugin.zip yourself. Download the current master by clicking the green button Code, and choose Download ZIP. Unpack the zip, and create a new zip containing all the files in folder DeDRM-plugin. This zip should be named DeDRM-plugin.zip, and should contain only the files in this folder in the root of the zip, not in a folder in the zip, otherwise it won't work. Install this zip in Calibre as usual. This is a version of DeDRM 7.0.0, and should only be loaded in Calibre 5, it doesn't work with Calibre 4.

**Comment by Geremia** [comment]
@digedag23 Your issue appears to be a duplicate of #1401.

**Comment by Geremia** [comment]
@ableeker I run into the same issue using master:
```DeDRM v7.0.0: Trying to decrypt my encrypted pdf book-1.pdf
DeDRM v7.0.0: An introduction to encrypted pdf book-1.pdf is a PDF ebook
DeDRM v7.0.0: Trying Encryption key adobekey_1
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 430, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
    parser = PDFParser(doc, inf)
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
    self.doc.set_parser(self)
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
    self.xrefs = parser.read_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
    pos = self.find_xref()
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
    for line in self.revreadlines():
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
    n = max(s.rfind('\r'), s.rfind('\n'))
TypeError: argument should be integer or bytes-like object, not 'str'
```

**Comment by apprenticeharper** [comment]
I don't currently have a sample Adobe PDF ebook. I would appreciate someone emailing me one along with the corresponding adobekey.der file.
