### ISSUE TITLE
Failed Dedrm of book that has additional material (interactive edition) error "Error -3 while decompressing: invalid stored block lengths"

### ISSUE THREAD

**Issue by helphelpplease** [apprenticeharper/DeDRM_tools#1444]
Hi,
below is snippet from dedrm log, showing fail due to "Error -3 while decompressing: invalid stored block lengths"
is there anything I can do to edit the python script "ineptepub.py", or something else or am I stuck?
Works no problem on all my other titles. This title is unusual in it is an "intereactive ebook". I am guessing that means has video and or audio in it.

Thankyou for any help.
Tested using High Sierra OSX, Alf 6.43. (retested in latest on Catalina/Calibre addon, fails also)

shellresult: Could not decrypt BookXX  The Interactive Edition (97_fixed.epub because of an exception:
Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/ineptepub.py", line 461, in decryptBook
    outf.writestr(zi, decryptor.decrypt(path, data))
  File "/Applications/DeDRM.app/Contents/Resources/ineptepub.py", line 377, in decrypt
    data = self.decompress(data)
  File "/Applications/DeDRM.app/Contents/Resources/ineptepub.py", line 367, in decompress
    bytes = dc.decompress(bytes)
error: Error -3 while decompressing: invalid stored block lengths

**Comment by ElleKayEm** [comment]
Previous issue #704 has a workaround.

**Comment by apprenticeharper** [comment]
This might be because of some files stored uncompressed (because compressing them may increase their length).

Try changing the decompress function at line 354 to 

    def decompress(self, bytes):
        dc = zlib.decompressobj(-15)
        try:
        	decompressed_bytes = dc.decompress(bytes)
			ex = dc.decompress(b'Z') + dc.flush()
			if ex:
				decompressed_bytes = decompressed_bytes + ex
        except:
        	# possibly not compressed by zip - just return bytes
        	return bytes
        return decompressed_bytes

(untested)

**Comment by helphelpplease** [comment]
thankyou  @apprenticeharper,  did not work. error returned in dedrm log + screenshot of the code added to ineptepub.py

  File "/Applications/DeDRM.app/Contents/Resources/ineptepub.py", line 367
    try:
    ^
IndentationError: unexpected indent

**Comment by helphelpplease** [comment]
https://i.imgur.com/epREgIe.png

sorry I do not know how to add an image to this this comment field

**Comment by apprenticeharper** [comment]
White space is significant in python at the start of the line. Fix the indentations. Or wait until I can upload a test version for you.

**Comment by apprenticeharper** [comment]
I've pushed an update to ineptepub.py to the GitHub master branch. Download that and see if it helps.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/ineptepub.py

**Comment by helphelpplease** [comment]
Thankyou thankyou thankyou @Alf. Worked brilliantly.
I updated my version of the script to add your new section as cut paste of the complete script didnt work as I am still on old version in the Alf's standalone tool.
(those white spaces -- it looked identical but obviously not. I used tab button on mac keyboard.  such tricky business for us non-tech people. will read up on this later. Thankyou for tip.)
