### ISSUE TITLE
[QUESTION] TitleDeDRM fails to load in Calibre 5.8.1

### ISSUE THREAD

**Issue by cramerps** [apprenticeharper/DeDRM_tools#1446]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 5.8.1
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.8.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

![12-26-2020 2-58-14 PM](https://user-images.githubusercontent.com/36516558/103160496-d33d4900-478a-11eb-9401-f5811570d2fa.jpg)

```
</details>
DeDRM fails to load included log and image or reported error.  I also tried the latest beta code to no avail.

Many thanks Paul

**Comment by ElleKayEm** [comment]
DeDRM 6.8.1 requires no later then calibre 4.23.  DeDRM 7.0.0b4 should load into calibre 5.x.  Unlike 6.8.1, it is only the DeDRM plugin.  Leave it zipped and load the entire file into calibre 5.
