### ISSUE TITLE
DeDRM v7.0.0: Failed to decrypt with error: No key found in 2 keys tried.

### ISSUE THREAD

**Issue by Tanner-1010** [apprenticeharper/DeDRM_tools#1447]
HI,
I've just downloaded and installed the latest version of Calibre and also installed the latest version of your plugin however I receive the following error when running in debug mode whilst attempting to import a DRM protected file.  Any assistance would be appreciated.

Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Kalinda
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\jason\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Kalinda to db in: 0.1
Added 1 books in 0.6 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds.

**Comment by apprenticeharper** [comment]
If this was downloaded for transfer via USB to an e-ink kindle, you haven't entered that kindle's serial number correctly into the DeDRM preferences.

**Comment by Tanner-1010** [comment]
Hi,
I have double checked the kindle serial and all looks good, I simply added the book to the calibre library and this threw the error, I was then going to convert to epub to test that the removal had worked.  Apologies if I am doing something wrong.

**Comment by ElleKayEm** [comment]
It is an E-ink Kindle and not a Fire?  And are you sure the correct device was chosen when you downloaded the book from the website?

**Comment by Tanner-1010** [comment]
Yes it is an e-ink Kindle and my sister emailed me the file from her kindle, are you saying I need to get her kindle serial number to remove DRM as I added my Kindle serial to the DeDRM plugin preferences

**Comment by ElleKayEm** [comment]
When you download the book from the website, you choose a device.  The serial number in DeDRM needs to match the device that the DRM is keyed to.

**Comment by apprenticeharper** [comment]
Please don't try to remove DRM from books that don't belong to you. Nor share books from which you've removed the DRM with people who aren't authorised to read it.

**Comment by Borg668** [comment]
I am having the same problem. I enter my wife's serial number and her books are converted to epub fine.
when I add my serial number (copied and pasted) my conversion fails.
how do I tell calibre which of the serial numbers to use?

**Comment by ElleKayEm** [comment]
DeDRM will try all saved keys.  Did you download the book for an E-ink Kindle (not a Fire)?  And is that specific Kindle's serial number in DeDRM?
