### ISSUE TITLE
Failure! Utter failure.

### ISSUE THREAD

**Issue by AboShayeb** [apprenticeharper/DeDRM_tools#1448]
Convert book 1 of 1 (Biomedical Applications of Introductory Physics)
DeDRM v7.0.0: Trying to decrypt 00ixwo6u.pdf
DeDRM v7.0.0: 00ixwo6u.pdf is a PDF ebook
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  pdf_serif_family: 'MS Shell Dlg 2'
  output_profile: 'generic_eink'
  read_metadata_from_opf: 'C:\\Users\\ISMAEE~1\\AppData\\Local\\Temp\\calibre_bdc5jni7\\b989jd0p.opf'
  verbose: 2
  pdf_sans_family: 'MS Shell Dlg 2'
  cover: 'C:\\Users\\ISMAEE~1\\AppData\\Local\\Temp\\calibre_bdc5jni7\\f7t4dyv7.jpeg'
Resolved conversion options
calibre version: 5.8.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\ISMAEE~1\\AppData\\Local\\Temp\\calibre_bdc5jni7\\f7t4dyv7.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000025B8D7619A0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000025B8D761CA0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\ISMAEE~1\\AppData\\Local\\Temp\\calibre_bdc5jni7\\b989jd0p.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.0.0: Trying to decrypt 00ixwo6u.pdf
DeDRM v7.0.0: 00ixwo6u.pdf is a PDF ebook
DeDRM v7.0.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Found 1 keys
DeDRM v7.0.0: Trying a new default key
DeDRM v7.0.0: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 481, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2175, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1980, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1788, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1413, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1914, in read_xref
  File "calibre_plugins.dedrm.ineptpdf", line 1865, in find_xref
  File "calibre_plugins.dedrm.ineptpdf", line 851, in revreadlines
TypeError: argument should be integer or bytes-like object, not 'str'
DeDRM v7.0.0: Failed to decrypt with new default key after 0.0 seconds
DeDRM v7.0.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 634, in run
  File "calibre_plugins.dedrm.__init__", line 509, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on C:\Users\ISMAEE~1\AppData\Local\Temp\calibre_bdc5jni7\00ixwo6u.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
Exception ignored in: <function NativeFunction.__del__ at 0x0000025B8D8385E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000025B8D8385E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
We've seen many reports now that DeDRM 7 is not working for Adobe DRM PDFs yet.  Use DeDRM 6.8.1 with calibre 4.23 or wait to try the next DeDRM release.
