### ISSUE TITLE
Syntax error installing on Calibre 5.8.1 64bit

### ISSUE THREAD

**Issue by demonfiddler** [apprenticeharper/DeDRM_tools#1452]
calibre, version 5.8.1
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.8.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
For calibre 5.x, you need pre-release DeDRM 7.0.0.b4.  To install current release DeDRM 6.8.1, use calibre 4.23.

**Comment by demonfiddler** [comment]
Thank you for the advice, @ElleKayEm, much appreciated!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by demonfiddler** [comment]
@ElleKayEm, my apologies for not having read the README - as a GitHub open source ccontributor myself I know how frustrating it is to provide information only to have it ignored :-). Anyhow, I installed the DeDRM 7.0.0b4 and KFX Input plug-ins into Calibre 5.8.1 64bit and attempted to import e-books downloaded by Kindle 1.30.0 (59056). It looks as if that Kindle version uses the KFX format, but unfortunately Calibre/DeDRM was unable to remove the DRM. The only way I could get it to work was to follow the instructions for disabling KFX in the Kindle Reader for PC app (i.e., set the registry key HKEY_CURRENT_USER\SOFTWARE\Amazon\Kindle\User Settings\isKRFDRendererSupported="false" _after_ the Kindle App has started), then to download the e-books anew, in AZW3 format, for which DeDRM 7.0.0b4 was able to remove the DRM. So, success eventually achieved, and thanks for your help!

**Comment by ElleKayEm** [comment]
You can decrypt KFX format from Kindle for PC/Mac 1.26 and earlier with DeDRM 6.8.1 and calibre 4.23.  But generally the AZW3 format is better for conversion and archiving anyway.
