### ISSUE TITLE
Can't remove DRM from kindle books on linux.

### ISSUE THREAD

**Issue by bobo123g** [apprenticeharper/DeDRM_tools#1456]
First of all I'm not sure where logs are stored on linux, can anyone point me in the right direction?

I own a kindle and have been stripping the DRM using my kindle's serial number and everything works great on windows. My library is on my linux boot though. I have done the exact same steps (inputing my serial number) in both calibre applications but the linux calibre will not remove my DRM.

I'm using calibre 5.8.1 and DeDRM 7.0b4 on both.

**Comment by ElleKayEm** [comment]
On Windows, if you go to Preferences > restart in debug mode, add the problem book, then close calibre, the log opens.  I don't know if it works the same on Linux.  Don't know if your issue is just something that simply isn't working yet for Linux with the beta for some reason.  There is a new beta out (7.0.1) you could try.

**Comment by bobo123g** [comment]
calibre Debug log
calibre 5.8.1  embedded-python: False is64bit: True
Linux-5.9.14-1-ck-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.9.14-1-ck', '#1 SMP PREEMPT Mon, 14 Dec 2020 02:02:19 +0000')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
calibre 5.8.1  embedded-python: False is64bit: True
Linux-5.9.14-1-ck-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.9.14-1-ck', '#1 SMP PREEMPT Mon, 14 Dec 2020 02:02:19 +0000')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.25263157894737
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
Failed to read metadata from font file: /usr/share/fonts/TTF/TSCu_Comic.ttf tuple index out of range
Failed to read metadata from font file: /usr/share/fonts/TTF/TSCu_Times.ttf tuple index out of range
[0.00] Starting up...
[0.02] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.59] main UI initialized...
[0.59] Hiding splash screen
Starting QuickView
DeDRM v7.0.0: Trying to decrypt Sapiens (A Brief History).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 15, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.8.1_tmp_ijpjbmsv/4su17jpwplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 627, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 521, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 17, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
[56.45] splash screen hidden
[56.45] Started up in 56.45 seconds with 22 books
Failed to check for calibre update: [Errno 101] Network is unreachable
Added Sapiens (A Brief History) to db in: 0.1
Added 1 books in 0.4 seconds

Going to try 7.0.1 and report back, thanks!

**Comment by ElleKayEm** [comment]
Thanks for reporting the fix!

**Comment by wazabees** [comment]
> On Windows, if you go to Preferences > restart in debug mode

On linux you can run `calibre-debug -g` in a terminal window. The terminal will output the log.

Installing `python-pycryptodome` worked for me as well, thanks for that!

Log before installing the python package:

```
╰─❯ calibre-debug -g
calibre 5.8.1  embedded-python: False is64bit: True
Linux-5.10.3-arch1-1-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.10.3-arch1-1', '#1 SMP PREEMPT Sun, 27 Dec 2020 10:50:46 +0000')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0) && Goodreads (1, 5, 1) && Goodreads Sync (1, 15, 0) && Kindle Collections (1, 7, 29)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.63111668757841 x 109.83783783783784
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.04] splash screen shown
[0.04] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
DEBUG:    0.4 HttpHelper::__init__: proxy=None
[0.59] main UI initialized...
[0.59] Hiding splash screen
Starting QuickView
[0.66] splash screen hidden
[0.66] Started up in 0.66 seconds with 2 books

Debugging DND event
text/uri-list 74 b'file:///home/user/Downloads/book.azw3' 

text/plain 64 b'file:///home/user/Downloads/book.azw3' 


Firefox rurl: None None
URLS: ['file:///home/user/Downloads/book.azw3']
Paths: ['/home/user/Downloads/book.azw3']
Extensions: frozenset({'azw3'})
Firefox rurl: None None
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1194, resource id: 12995100, major code: 40 (TranslateCoords), minor code: 0
DeDRM v7.0.0: Trying to decrypt book.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 15, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.8.1_tmp_q1liyyjc/t5593zhxplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 628, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 522, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 17, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Added Book to db in: 4.0
Added 1 books in 4.3 seconds
```

And after installing the python package.

```
╰─❯ calibre-debug -g                  
calibre 5.8.1  embedded-python: False is64bit: True
Linux-5.10.3-arch1-1-x86_64-with-glibc2.32 Linux ('64bit', 'ELF')
('Linux', '5.10.3-arch1-1', '#1 SMP PREEMPT Sun, 27 Dec 2020 10:50:46 +0000')
Python 3.9.1
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 0) && Count Pages (1, 11, 0) && Goodreads (1, 5, 1) && Goodreads Sync (1, 15, 0) && Kindle Collections (1, 7, 29)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.63111668757841 x 109.83783783783784
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
DEBUG:    0.4 HttpHelper::__init__: proxy=None
[0.58] main UI initialized...
[0.58] Hiding splash screen
Starting QuickView
[0.66] splash screen hidden
[0.66] Started up in 0.66 seconds with 2 books

Debugging DND event
text/uri-list 74 b'file:///home/user/Downloads/book.azw3' 

text/plain 64 b'file:///home/user/Downloads/book.azw3' 


Firefox rurl: None None
URLS: ['file:///home/user/Downloads/book.azw3']
Paths: ['/home/user/Downloads/book.azw3']
Extensions: frozenset({'azw3'})
DeDRM v7.0.0: Trying to decrypt book.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Book
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID removed.
Decrypting. Please wait . . . . . done
Decryption succeeded after 0.1 seconds
DeDRM v7.0.0: Finished after 0.1 seconds
Added Book to db in: 4.3
Added 1 books in 4.6 seconds
Worker Launch took: 0.01 seconds
```

**Comment by Geremia** [comment]
@bobo123g Me, too!

I'm using Linux under Wine, and I had to run:
```
wine "~/.wine/drive_c/Program Files (x86)/Python39-32/Scripts/pip.exe" install pycryptodome
```

**Comment by RealStickman** [comment]
I can confirm that installing pycryptodome worked.  
Note to anyone else having issues: Python should be installed globally in wine and be registered in wine's path.
