### ISSUE TITLE
[QUESTION] Garbled Text

### ISSUE THREAD

**Issue by xist73** [apprenticeharper/DeDRM_tools#1457]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

I deeply apologize but I'm new to this platform and not nerd enough to understand how it really works. I just wanted to report that I've spent several hours trying to get the plugin to work with a book I own, but once I open the book with the Calibre reader the text is all garbled. 
I followed the instructions, I got Kindle 1.17 for Mac, I imported the book in Calibre from the original directory, it imports fine (it seems like), it says it's MOBI but then when I go read it the text is all messed up. 

Any help?

---

## Log
<details><summary>calibre Debug log
</summary>

```log
calibre Debug log
calibre 5.8.1  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.8.1  embedded-python: True is64bit: True
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 82.00000123151645 x 82.00000123151646
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[1.31] main UI initialized...
[1.31] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/fab/Library/Application Support/Kindle/My Kindle Content/B07GS7C9B1_EBOK/B07GS7C9B1_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.0.0: Trying to decrypt B07GS7C9B1_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: A Pianist Prepares: The inner construction of a musical piece
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 7 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 7 PIDs tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/fab/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2011 file: /Users/fab/Library/Application Support/Kindle/storage/.kinf2011
trying username  b'fab'  on file  /Users/fab/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'cdfe902ad9cf'
Decrypted key file using IDString 'cdfe902ad9cf' and UserName 'fab'
trying username  b'fab'  on file  /Users/fab/Library/Application Support/Kindle/storage/.kinf2011
trying IDString: b'cdfe902ad9cf'
Decrypted key file using IDString 'cdfe902ad9cf' and UserName 'fab'
DeDRM v7.0.0: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: A Pianist Prepares: The inner construction of a musical piece
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 535, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 7 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 628, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 578, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[13.34] splash screen hidden
[13.34] Started up in 13.34 seconds with 4 books
Added A Pianist Prepares: The inner construction of a musical piece to db in: 0.0
Added 1 books in 1.8 seconds
```
</details>

**Comment by ElleKayEm** [comment]
DRM is not removed.  Kindle for Mac 1.17 which you used to download the book is on the same machine and user as calibre with DeDRM?

Your best bet is to go back to calibre 4.23 and load DeDRM 6.8.1.  That should definitely work.  The beta version of DeDRM for calibre 5.x is a work in progress and still seems to be hit or miss.
