### ISSUE TITLE
Cannot remove DRM from Amazon kfx format

### ISSUE THREAD

**Issue by tos070** [apprenticeharper/DeDRM_tools#1462]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Log
<details><summary>Removing DRM from book with title Vegan Chocolate</summary>

```log
calibre Debug log
calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Failed to initialize plugin: '/Users/sotiris/Library/Preferences/calibre/plugins/K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.7.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.50000188482092 x 125.50000188482092
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.45] splash screen shown
[0.45] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
[2.53] main UI initialized...
[2.53] Hiding splash screen
Starting QuickView

{'bsd_drives': {'main': '/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/System/Volumes/Data',
               '/dev/disk1s2': '/System/Volumes/Preboot',
               '/dev/disk1s4': '/System/Volumes/VM',
               '/dev/disk1s5s1': '/',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.2 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.5 USBMS: count found in cache: 83, count of files in metadata: 83, need_sync: False
DEBUG:    0.5 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 83
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
DeviceJob: set_books_in_library finished: time= 0.016986846923828125
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
[32.62] splash screen hidden
[32.62] Started up in 32.62 seconds with 154 books
Worker Launch took: 0.04 seconds
Job: 3 Convert book 1 of 1 (Vegan Chocolate Unapologetically Luscious and Decadent Dairy-Free Desserts (English Edition) B06XC7SXSF) finished
Convert book 1 of 1 (Vegan Chocolate Unapologetically Luscious and Decadent Dairy-Free Desserts (English Edition) B06XC7SXSF)
	DeDRM v7.0.0: Trying to decrypt xwi0pkjv.kfx-zip
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	Decrypting KFX-ZIP ebook: xwi0pkjv
	Error getting PIDs from serial number B00E15102222080J: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Error getting PIDs from serial number 90172202516401R1: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Found 0 keys to try after 0.5 seconds
	DeDRM v7.0.0: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v7.0.0: Looking for new default Kindle Key after 0.5 seconds
	Found k4Mac kinf2018 file: /Users/sotiris/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'sotiris'  on file  /Users/sotiris/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0dc3da1296c2'
	Decrypted key file using IDString '0dc3da1296c2' and UserName 'sotiris'
	DeDRM v7.0.0: Found 1 new key
	Decrypting KFX-ZIP ebook: xwi0pkjv
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 1 keys to try after 1.2 seconds
	DeDRM v7.0.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Failed to initialize plugin: '/Users/sotiris/Library/Preferences/calibre/plugins/K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: '/var/folders/13/d83pwvs50vs0g_hvg_g75h6c0000gn/C/calibre_5.7.2_tmp_g8h_glm2/8jbq19hh.opf'
	Resolved conversion options
	calibre version: 5.7.2
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10dc1aa60>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x10dc1ad30>,
	 'page_breaks_before': '/',
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/13/d83pwvs50vs0g_hvg_g75h6c0000gn/C/calibre_5.7.2_tmp_g8h_glm2/8jbq19hh.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 63, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 627, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.0.0: Trying to decrypt xwi0pkjv.kfx-zip
	Decrypting KFX-ZIP ebook: xwi0pkjv
	Error getting PIDs from serial number B00E15102222080J: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Error getting PIDs from serial number 90172202516401R1: string argument without an encoding
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
	    pidlst.extend(map(bytes,getKindlePids(md1, md2, serialnum)))
	TypeError: string argument without an encoding
	Found 0 keys to try after 0.0 seconds
	DeDRM v7.0.0: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v7.0.0: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/sotiris/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'sotiris'  on file  /Users/sotiris/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0dc3da1296c2'
	Decrypted key file using IDString '0dc3da1296c2' and UserName 'sotiris'
	DeDRM v7.0.0: Found 1 new key
	Decrypting KFX-ZIP ebook: xwi0pkjv
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 1 keys to try after 0.6 seconds
	DeDRM v7.0.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 63, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 627, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on /var/folders/13/d83pwvs50vs0g_hvg_g75h6c0000gn/C/calibre_5.7.2_tmp_g8h_glm2/xwi0pkjv.kfx-zip
	Software versions: KFX Input 1.36.0, calibre 5.7.2, macOS-10.16-x86_64-i386-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/13/d83pwvs50vs0g_hvg_g75h6c0000gn/C/calibre_5.7.2_tmp_g8h_glm2/xwi0pkjv.kfx-zip
	Processing container: Vegan Chocolate_ Unapologetically Luscious and Decadent Dairy-Free Desserts (English Edition)_B06XC7SXSF.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Vegan Chocolate_ Unapologetically Luscious and Decadent Dairy-Free Desserts (English Edition)_B06XC7SXSF.kfx has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 123, in convert
	calibre.ebooks.DRMError: This book has DRM!
2021-01-05 10:51:11.762 calibre-debug[21954:268085] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
```
</details>

**Comment by tos070** [comment]
Thanks! I just wanted to say that DeDRM for calibre 5.x under Big Sur worked fine with the previous book I bought from Amazon (see my earlier reported issue). I use indeed "download & transfer via usb" to save the book. That previous book was saved with the extension azw3  when I downloaded it. The book I am having the current issue with is saved without any extension when I use the "download & transfer via usb" from Amazon. In order to add it to Calibre, I used the method I described in my previous comment (I connected the Kindle to my laptop and used Calibre to export it from the Kindle; it was then saved with the kfx extension). I would like to stick to the current Calibre version and method 2 is too complicated for me. I'll wait for a future simpler solution I think. What I don't understand (not for kfx files specifically, but in general) is the following: why is the Kindle for Mac relevant? I mean, if I download a book form Amazon with "download & transfer via usb" and I have customised the DeDRM plugin with the serial number of my E-ink kindle, then Kindle for Mac is not involved at all, is it? I just add the file to Calibre and DeDRM does the job (like it did with the previous book).

**Comment by ElleKayEm** [comment]
Pretty sure the beta DeDRM only works with AZW3 (and perhaps AZW/MOBI) right now.  KFX directly from a Kindle ereader cannot be decrypted at all yet.  And if the file is available in that format (most are now), that's what you'll get (no way to disable KFX downloads on a Kindle).  The Kindle for Mac version is only relevant if you are trying to decrypt books which have been downloaded with the app.

With the book which you downloaded from the website which did not have an extension, try adding the AZW extension and importing it to calibre (without the transfer to your Kindle and back).  Files downloaded from the website aren't KFX.  (At least, they haven't been so far.)  Sounds like the Kindle is replacing that file with the KFX version.  If the original download is actually AZW3 or MOBI, this may work with beta DeDRM.  But if it's some other Kindle format (like AZW4 or TPZ), it would probably only work with DeDRM 6.8.1.

**Comment by tos070** [comment]
It worked! I added the azw extension as you said and problem solved! Thank you so much.

**Comment by ElleKayEm** [comment]
Glad to hear!  Thanks for reporting back.
