### ISSUE TITLE
Failed: Convert Book (Topaz)

### ISSUE THREAD

**Issue by CMic92** [apprenticeharper/DeDRM_tools#1466]
Convert book 1 of 1 (B001ELJU2I EBOK)
DeDRM v7.0.3: Trying to decrypt alh8t4cy.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting Topaz ebook: Callings: Twenty Centuries of Christian Wisdom on Vocation
Found 0 keys to try after 0.1 seconds
DeDRM v7.0.3: Failed to decrypt with error: No key found in 0 keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3733018445' and UserName 'user'
DeDRM v7.0.3: Found 1 new key
Decrypting Topaz ebook: Callings: Twenty Centuries of Christian Wisdom on Vocation
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Trying: b'HNRXSM4C'
Trying: b'gShmRBcs'
Trying: b'6gm5yfOi'
Book Key Found! (df34d0d10ce767e4

[B001ELJU2I_EBOK.azw.zip](https://github.com/apprenticeharper/DeDRM_tools/files/5772891/B001ELJU2I_EBOK.azw.zip)

**Comment by CMic92** [comment]
> DeDRM 7 probably just can't handle Topaz format yet. For now, you will probably need to go back to calibre 4.23 and DeDRM 6.8.1 to decrypt this.

Thanks! I tried to do what you suggested but got this error when trying to install DeDRM 6.8.1...thoughts?

--
calibre, version 4.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'\\\\Mac\\Home\\Downloads\\DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && Package KFX (from KFX Input) (1, 36, 0) && KindleUnpack - The Plugin (0, 83, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 47, 0) && KFX Output (1, 47, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'\\\\Mac\\Home\\Downloads\\DeDRM_tools_6.8.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_6.8.1.zip and load DeDRM_Plugin.zip.
