### ISSUE TITLE
DRM 6.8.0 not working on Mac OS Big Sur, Calibre 4.23

### ISSUE THREAD

**Issue by chi-plus-plus** [apprenticeharper/DeDRM_tools#1467]
When I import a Kindke e-book in Calibre, I can see the cover, but cannot read the text.
I've de-registered and re-installed Kindle, but nothing changes.
I enclose the log.
Thank you,
C:

--
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.41] main UI initialized...
[1.41] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/Name/Documents/Kindle/B0897V52Y7_EBOK/B0897V52Y7_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/yz/ysl_q7gj2f3gwsb63y81sqs40000gn/C/calibre_4.23.0_tmp_dfX2R4/meNX3v.kfx-zip
DeDRM v6.8.0: Trying to decrypt meNX3v.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: meNX3v
Found 3 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8b33323f-6427-42be-925b-113266a5b2de.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/Name/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
[18.36] splash screen hidden
[18.37] Started up in 18.37 seconds with 34 books
Decrypted key file using IDString 'dd9464a91a8f' and UserName 'Name'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: meNX3v
Got DSN key from database default_key_1
Found 1 keys to try after 0.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8b33323f-6427-42be-925b-113266a5b2de.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging /var/folders/yz/ysl_q7gj2f3gwsb63y81sqs40000gn/C/calibre_4.23.0_tmp_dfX2R4/meNX3v.kfx-zip
Processing container: B0897V52Y7_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
KFXDRMError: Book container B0897V52Y7_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/yz/ysl_q7gj2f3gwsb63y81sqs40000gn/C/calibre_4.23.0_tmp_dfX2R4/pZonZe_add_books/0/B0897V52Y7_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
Either use a version of Kindle for Mac no later than 1.26.  Or disable KFX downloads.  See this post:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by chi-plus-plus** [comment]
OK, I've changed the permissions on renderer test and now it's working:

-rw-r--r--  1 root  wheel  41232 Oct 16 20:45 /Applications/Kindle.app/Contents/MacOS/renderer-test

but why? :-)
Where can I find some documentaton about it?
Thank you, again.

Carlo

**Comment by ElleKayEm** [comment]
Kindle for Mac runs renderer-test to check the capabilities of your system.  If it can't run that check, it plays it safe and sends the older format.

**Comment by xxayrx** [comment]
Unable to install to calibre. Detail error log below. Please advise. calibre 5.9  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.1.0', 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 316, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
For calibre 5.x, install pre-release DeDRM 7.0.3.  To install DeDRM 6.8.1, you need calibre 4.23.
