### ISSUE TITLE
"This book is locked by DRM".

### ISSUE THREAD

**Issue by kyede2006** [apprenticeharper/DeDRM_tools#1468]
Using windows 10, I have installed the DRM remover but still, my book will not be removed of DRM meaning that in turn I cannot convert it. I have reinstalled the plugin three times and selected the correct one yet it does not seem to be working. The book is ibn the format .azw so from hat I have read should work but yet it isn't. Could you help me with this please?

**Comment by ElleKayEm** [comment]
Take a look at this post:  https://www.mobileread.com/forums/showthread.php?t=283371

If you still need help, post a log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by HSS-RN** [comment]
Hallo, I am in a same situation like "kyede2006". But I already read all Help-files but I think I don't undersand them enough. And I got the debug-report file and Thank you for help.
Here is the file: 

calibre Fehlerdiagnoseprotokoll
calibre 5.4.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.4.2  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.35652173913041 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[0.95] main UI initialized...
[0.95] Hiding splash screen
Starting QuickView
DeDRM v7.0.0: Trying to decrypt Ruckkehr nach St. Elwine (German Edition) - Britta Orlowski.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Rückkehr nach St. Elwine (German Edition)
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v7.0.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Sac-Stei\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Sac-Stei\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\Sac-Stei\AppData\Local\Amazon\Kindle\storage\.kinf2011
Storage number map:
{(7, 0): [(5, 'C'), (6, 'D')], (7, 1): [(1, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B0231701248409F0&0: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=10)
{'drive_letters': ['E'],
 'pnp_id_map': {'E': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b0231701248409f0&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'E': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.1 USBMS: scan from root False E:\documents
DEBUG:    0.3 USBMS: count found in cache: 286, count of files in metadata: 286, need_sync: False
DEBUG:    0.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 286
DeviceJob: set_books_in_library finished: time= 0.005246639251708984
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
[42.00] splash screen hidden
[42.00] Started up in 42.00 seconds with 8 books
stdout+stderr from file dialog helper: [b'', b'']
Job: 3 Dateien zur Übertragung vom Gerät vorbereiten started
DeviceJob: 3 Dateien zur Übertragung vom Gerät vorbereiten done, calling callback
DeviceJob: 3 Dateien zur Übertragung vom Gerät vorbereiten callback returned
Job: 3 Dateien zur Übertragung vom Gerät vorbereiten finished
Keine Details verfügbar.
Decrypted key file using IDString '307625709' and UserName 'Sac-Stei'
Decrypted key file using IDString '307625709' and UserName 'Sac-Stei'
DeDRM v7.0.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Rückkehr nach St. Elwine (German Edition)
Got DSN key from database default_key_2
Found 4 keys to try after 3.2 seconds
Crypto Type is: 2
DeDRM v7.0.0: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 534, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 476, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 keys tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
  File "calibre_plugins.dedrm.__init__", line 577, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.0: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tooTraceback (most recent call last):
  File "calibre\devices\kindle\driver.py", line 426, in books
  File "calibre\devices\kindle\driver.py", line 435, in kindle_update_booklist
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "calibre\devices\kindle\driver.py", line 426, in books
  File "calibre\devices\kindle\driver.py", line 435, in kindle_update_booklist
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "calibre\devices\kindle\driver.py", line 426, in books
  File "calibre\devices\kindle\driver.py", line 435, in kindle_update_booklist
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Added Rückkehr nach St. Elwine (German Edition) to db in: 0.3
Added 1 books in 3.9 seconds
DeviceJob: set_books_in_library: books to process= 286
DeviceJob: set_books_in_library finished: time= 0.009995222091674805
Worker Launch took: 0.19125103950500488

[tmpey2cgkye.txt](https://github.com/apprenticeharper/DeDRM_tools/files/5789266/tmpey2cgkye.txt)

**Comment by ElleKayEm** [comment]
@HSS-RN 
Looks like a book from the website for "download & transfer via USB".  Did you choose an E-ink Kindle (not a Fire) for the device?  Have you entered the Kindle's serial number into DeDRM's customization?  Also there is a more recent DeDRM pre-release 7.0.3.  I don't know if there are any changes for this, but it can't hurt.

**Comment by HSS-RN** [comment]
@ElleKayEm 
you gave me the best help I could get. 
I updated the DeDRM Plugin and filled in the SN of my Kindle. 
That was it! 
Now I can read my books wherever I want. 👌😊😊
Thank you! 😘
