### ISSUE TITLE
Will not remove DRM on important book I am reading for whistleblower interview. 

### ISSUE THREAD

**Issue by ebookworm** [apprenticeharper/DeDRM_tools#1471]
I have a very important interview with Daniel Sheehan author of the book. "The peoples advocate". I used Calibre to take notes on the book. I have attached the file that has been modified on Calibre. It's an epub. Although I was able to remove the DRM before and use the file just fine, since I reinstalled my OS and therefore Calibre, I cannot get the file to open no matter what I try. I have tried the previous version Calibre 4.23 with the plugin 6.8.1 and I have tried the newest version Calibre 5.8.1 with the new version of the plugin 7.0.3 to no avail. Daniel is an amazing champion of first amendment rights and I have never been more enthusiastic for an interview. Can you please help me modify this epub so it can be opened in Calibre or let me know what to do so i can open it with my present modifications saved on the notes I took on the book. It would be tremendously appreciated and I will personally send you a copy of our interview. 

**Error message I am receiving:** 

Failed to convert book: C:\Users\lemurian vortex\Desktop\Calibre Portable\Calibre Library\Daniel Sheehan\The People's Advocate (4)\The People's Advocate - Daniel Sheehan.epub with error:
DeDRM v7.0.3: Trying to decrypt The People's Advocate - Daniel Sheehan.epub
DeDRM v7.0.3: Verifying zip archive integrity
DeDRM v7.0.3: The People's Advocate - Daniel Sheehan.epub is a secure Adobe Adept ePub
DeDRM v7.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.3: Trying a new default key
Could not decrypt 9fqzo5vu.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 418, in decryptBook
TypeError: object of type 'int' has no len()

DeDRM v7.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\lemurian vortex\Desktop\Calibre Portable\Calibre Library\Daniel Sheehan\The People's Advocate (4)\The People's Advocate - Daniel Sheehan.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 641, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 865, in viewer_main
  File "calibre\srv\render_book.py", line 856, in render_for_viewer
  File "calibre\srv\render_book.py", line 833, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
calibre.ebooks.DRMError: The People's Advocate - Daniel Sheehan.epub
Exception ignored in: <function NativeFunction.__del__ at 0x07288E80>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07288E80>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
```
</details>

**Comment by ElleKayEm** [comment]
Do you have Adobe Digital Editions authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by ebookworm** [comment]
Thank you for your comment and actually. Maybe you can help me solve this. I installed adobe editions and caliber on my machine.  I pulled the acsm file into adobe editions and downloaded it as an epub. I loaded the epub into calibre with the plugin installed and everything worked. I had a major problem with my computer and had to reload the Operating System. I backed up the epub that I was using with caliber redownloaded caliber and tried to open the old epub to no avail. Is there anyway I can get my old epub that worked before to work now with caliber. I have 10 hours of important notes for my interview. FYI I HIGHLY recommend Daniel Sheehans book.

**Comment by ElleKayEm** [comment]
The book in the log still has DRM.  In order to remove Adobe DRM, ADE authorized with your Adobe ID needs to be on the same machine and user as calibre with DeDRM.  If you were previously able to read the old epub in calibre's ebook viewer, then that copy (the one saved in calibre's library, not the original epub from ADE's folder) had the DRM removed.  So this copy is from before it was added to calibre previously?  Not backup from calibre after DRM removal?

**Comment by apprenticeharper** [comment]
You don't mention registering the copy of Adobe Digital Editions with an Adobe ID. If you did not do that, the DRM would be tied to that particular installation of ADE. If that installation got deleted, and if you have lost the copy with DRM removed, then you will have to buy another copy. The key used to encrypt the book has been lost with your lost installation of Adobe Digital Editions.

**Comment by ebookworm** [comment]
Apprenticeharper and ellekayem,
I deleted both adobe digital editions and calibre from my previous installation of windows. I installed a new installation of windows and reinstalled both adobe digital editions and calibre. The file I backed up from the origional installation of calibre and adobe digital additions was an epub I loaded into adobe digital editions and then into Calibre. and removed the DRM with a plugin for Calibre. I then had a backup of the epub which I saved so I could use it again with all my notes attached and all the changes I made to the epub in Calibre. I can tell the changes are there because the file size is larger then the origional epub before I started adding the notes and making the changes.  After I reinstalled my new os I downloaded both adobe digital editions and calibre the epub I backed up simply will not open.

**Comment by ebookworm** [comment]
by the way thank you for all your help in this matter.

**Comment by ebookworm** [comment]
Yes utterly frustrating but unless I have an epiphany or run into someone whom has an answer to the issue I am just going to start from scratch. I def opened it previously in calibre and backed up that particular copy.
