### ISSUE TITLE
Still getting message no DeDRM after installation of DeDRM 7.0.3

### ISSUE THREAD

**Issue by Junec101** [apprenticeharper/DeDRM_tools#1494]
## Still getting error drm protected
<when trying to convert a book from kindle to kobo format EPUB the job starts but then get a message that book is DRM>

## Log
<details><summary>Log Title</summary>

```log
``FFF: INFO: 2021-01-23 12:35:39,303: calibre_plugins.fanficfare_plugin.prefs(218): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2021-01-23 12:35:39,303: calibre_plugins.fanficfare_plugin.prefs(223): Using default settings
FFF: DEBUG: 2021-01-23 12:35:39,312: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:C:\Users\junec\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && FanFicFare (3, 29, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 48, 0) && KFX Output (1, 48, 0)
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && FanFicFare (3, 29, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 48, 0) && KFX Output (1, 48, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.6430769230769 x 133.90057803468207
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[1.69] main UI initialized...
[1.69] Hiding splash screen
Starting QuickView
[142.34] splash screen hidden
[142.34] Started up in 142.34 seconds with 0 books
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:/Users/junec/Documents/My Kindle Content/B08SJ3M1R8_EBOK/B08SJ3M1R8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\junec\AppData\Local\Temp\calibre_5ekno70m\sqsssmcf.kfx-zip
DeDRM v7.0.3: Trying to decrypt sqsssmcf.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: sqsssmcf
Got DSN key from database kindleforpc
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.73010bb8-388b-4474-8f58-0859e63c39c2.voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\junec\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\junec\AppData\Local\Amazon\Kindle\storage\.kinf2018
Added CR!HMS43SZBBH52V26WGBPXAKNX9TBC.azw to db in: 0.1
Added CR!620SWSHF8572X6KAH4KSBPWR90T8.azw to db in: 0.1
Added B08SJ3M1R8 EBOK to db in: 0.1
Added amzn1.drm-voucher.v1.73010bb8-388b-4474-8f58-0859e63c39c2 to db in: 0.1
Decrypted key file using IDString '684769860' and UserName 'junec'
DeDRM v7.0.3: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\junec\AppData\Local\Temp\calibre_5ekno70m\sqsssmcf.kfx-zip
Processing container: B08SJ3M1R8_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\junec\AppData\Local\Temp\calibre_5ekno70m\de9zayem_add_books\2\B08SJ3M1R8_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08SJ3M1R8_EBOK.azw has DRM and cannot be converted
Added Audiophile's Guide: The Stereo to db in: 0.1
Added 5 books in 3.3 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (Audiophile's Guide: The Stereo) finished
Convert book 1 of 1 (Audiophile's Guide: The Stereo)

	DeDRM v7.0.3: Trying to decrypt 5b97r02y.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: 5b97r02y
	Got DSN key from database kindleforpc
	Found 1 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.73010bb8-388b-4474-8f58-0859e63c39c2.voucher
	DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\junec\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\junec\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '684769860' and UserName 'junec'
	DeDRM v7.0.3: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  verbose: 2

	  cover: 'C:\\Users\\junec\\AppData\\Local\\Temp\\calibre_5ekno70m\\uadaybxq.jpeg'

	  read_metadata_from_opf: 'C:\\Users\\junec\\AppData\\Local\\Temp\\calibre_5ekno70m\\rle89ksy.opf'

	  output_profile: 'kindle_fire'

	Resolved conversion options

	calibre version: 5.10.1

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\junec\\AppData\\Local\\Temp\\calibre_5ekno70m\\uadaybxq.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001E38340EB20>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x000001E3833F70A0>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\junec\\AppData\\Local\\Temp\\calibre_5ekno70m\\rle89ksy.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 630, in run

	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.0.3: Trying to decrypt 5b97r02y.kfx-zip
	Decrypting KFX-ZIP ebook: 5b97r02y
	Got DSN key from database kindleforpc
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.73010bb8-388b-4474-8f58-0859e63c39c2.voucher
	DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\junec\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\junec\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '684769860' and UserName 'junec'
	DeDRM v7.0.3: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 630, in run

	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\junec\AppData\Local\Temp\calibre_5ekno70m\5b97r02y.kfx-zip

	Software versions: KFX Input 1.36.0, calibre 5.10.1 [64bit], Windows-10-10.0.19041

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\junec\AppData\Local\Temp\calibre_5ekno70m\5b97r02y.kfx-zip

	Processing container: B08SJ3M1R8_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 105, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08SJ3M1R8_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 123, in convert

	calibre.ebooks.DRMError: This boo
has DRM!
</details>

**Comment by ElleKayEm** [comment]
DeDRM 7.0.3 is not working with KFX format yet.  DeDRM 6.8.1 works with KFX from Kindle for PC version 1.26 and earlier.  Try disabling KFX format downloads.  See method 2 at this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by the-sweet** [comment]
If you apply Method 2 and you still get a DRM applied error on non-KFX downloads, then what? I have a similar setup to this user and am still getting "still DRM protected" errors.

**Comment by ElleKayEm** [comment]
@the-sweet Let's see your log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by the-sweet** [comment]
I tried posting on the blog, but I'm not sure if the post went through. Here's the log (my one difference is I'm on Mac, but I acknowledge that's kind of a big difference): FFF: DEBUG: 2021-01-30 21:25:39,129: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:/Users/meredith/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
QLayout::addChildLayout: layout "" already has a parent
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && BookFusion Plugin (0, 5, 3) && FanFicFare (3, 29, 0) && Goodreads Sync (1, 15, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 48, 0) && KFX Output (1, 48, 0)
calibre 5.10.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && BookFusion Plugin (0, 5, 3) && FanFicFare (3, 29, 0) && Goodreads Sync (1, 15, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 48, 0) && KFX Output (1, 48, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.8 HttpHelper::__init__: proxy=None
[1.75] main UI initialized...
[1.75] Hiding splash screen
[1.75] splash screen hidden
[1.75] Started up in 1.75 seconds with 439 books
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/meredith/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B07D69Z6C2_EBOK/B07D69Z6C2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.0.3: Trying to decrypt B07D69Z6C2_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Chillpreneur
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/meredith/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'meredith'  on file  /Users/meredith/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'61e4bb9fcd39'
trying IDString: b'bba5776d83e5'
trying IDString: b'bba5776d83e4'
trying IDString: b'bd9b4a0a7932'
Decrypted key file using IDString 'bd9b4a0a7932' and UserName 'meredith'
DeDRM v7.0.3: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Chillpreneur
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 1.6 seconds
Crypto Type is: 2
DeDRM v7.0.3: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Chillpreneur to db in: 0.0
Added 1 books in 2.1 seconds
Worker Launch took: 0.03 seconds

**Comment by ElleKayEm** [comment]
I don't think I've seen someone on Big Sur successfully use beta DeDRM on Kindle for Mac books yet.  Try calibre 4.23 and DeDRM 6.8.1.

**Comment by howardintexas** [comment]
Just in case it helps someone else....  I was getting the same error log as the-sweet but I am on MacOs 10.14 (Mojave).  I tried a whole bunch of things but finally it worked to follow the suggestion here to use calibre 4.23 and DeDRM 6.8.1.  Perhaps this is not just a Big Sur issue but related to some other common issue.

**Comment by ElleKayEm** [comment]
I've heard that after getting things working with calibre 4.23/DeDRM 6.8.1 on Mac, people were able to update to the latest calibre and DeDRM.

**Comment by yaroslavvb** [comment]
I also ran into this "No key found in 0 PIDs tried." issue in DeDRM v7.2.1, and was able to fix it by downgrading to calibre 4.23/DeDRM 6.8.1 on Mac 12.1 Mojave

Attached is the log
[tmp55wkhdvi.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8524977/tmp55wkhdvi.txt)

**Comment by ElleKayEm** [comment]
@yaroslavvb I believe the problem with finding the key on Macs has been fixed in [DeDRM 10.0.2](https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2).

**Comment by yaroslavvb** [comment]
Ah, interesting, wasn't aware of the fork. This repo (apprenticeharper/DeDRM_tools) last release is DeDRM 7.2.1, which means I should've used noDRM/DeDRM_tools instead
