### ISSUE TITLE
Issue on install DeDRM - Calibre 4.99.4 on Linux 5.4.0-64-generic (Mint Ulyana)

### ISSUE THREAD

**Issue by Ragnar57** [apprenticeharper/DeDRM_tools#1497]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
calibre, version 4.99.4
ERREUR : Exception non gérée: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.4.0-64-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.4.0-64-generic', '#72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021')
Python 3.8.5
Interface language: fr
Successfully initialized third party plugins: ACE (1, 1, 2)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 179, in load_module
    compiled = compile(code, 'calibre_plugins.%s.%s'%(plugin_name,
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

```log
PUT YOUR LOG
```
Got the same error each time with every version.
Help would be appreciated !
Thanks a lot.

**Comment by ElleKayEm** [comment]
That's a beta Python 3 version of calibre.  You need DeDRM 7.0.3.  I'd recommend updating to the current calibre too.
