### ISSUE TITLE
Can't DRM a Kindle Book (AZW1)

### ISSUE THREAD

**Issue by olidanesma** [apprenticeharper/DeDRM_tools#1498]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
I'm having trouble visualizing a kindle book, with .azw1 code.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.10.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.00000193738563 x 129.00000193738563
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
DeDRM v7.0.3: Trying to decrypt Sobre el viejo humanismo_ Exposición y defensa de una tradición (Estudios nº 77) (Spanish Edition)_B00E3B5S22.azw1
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting Topaz ebook: Sobre el viejo humanismo: Exposición y defensa de una tradición (Estudios) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
DeDRM v7.0.3: Failed to decrypt with error: No key found in 0 keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/danescoto/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'danescoto'  on file  /Users/danescoto/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'55bd3d180f7c'
Decrypted key file using IDString '55bd3d180f7c' and UserName 'danescoto'
DeDRM v7.0.3: Found 1 new key
Decrypting Topaz ebook: Sobre el viejo humanismo: Exposición y defensa de una tradición (Estudios) (Spanish Edition)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.5 seconds
Trying: b'vi7FpClR'
DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[9.79] splash screen hidden
[9.79] Started up in 9.79 seconds with 15 books

{'bsd_drives': {'main': '/dev/disk2'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/System/Volumes/Data',
               '/dev/disk1s2': '/System/Volumes/Preboot',
               '/dev/disk1s4': '/System/Volumes/VM',
               '/dev/disk1s5s1': '/',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 35, count of files in metadata: 35, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 35
DeviceJob: set_books_in_library finished: time= 0.0023343563079833984
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 3 Prepare files for transfer from device started
DeviceJob: 3 Prepare files for transfer from device done, calling callback
DeviceJob: 3 Prepare files for transfer from device callback returned
Job: 3 Prepare files for transfer from device finished
No details available.
Added Sobre el viejo humanismo Exposición y defensa de una tradición (Estudios nº 77) (Spanish Edition) B00E3B5S22 to db in: 0.0
Added 1 books in 1.0 seconds
DeviceJob: set_books_in_library: books to process= 35
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.topazextract", line 361, in processBook
    raise DrmException("No key found in {0:d} keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(len(pidlst)))
calibre_plugins.dedrm.topazextract.DrmException: No key found in 0 keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 416, in get_metadata
  File "calibre/ebooks/metadata/topaz.py", line 378, in get_metadata
  File "calibre/ebooks/metadata/topaz.py", line 114, in __init__
ValueError: '/Volumes/Kindle/documents/Downloads/Items01/Sobre el viejo humanismo_ Exposición y defensa de una tradición (Estudios nº 77) (Spanish Edition)_B00E3B5S22.azw1': Invalid Topaz format - no metadata record

```
</details>

**Comment by ElleKayEm** [comment]
Try with calibre 4.23 and DeDRM 6.8.1.

**Comment by olidanesma** [comment]
Thanks a lot!
