### ISSUE TITLE
azw3 deDRM fails. Serial number not found even though present

### ISSUE THREAD

**Issue by le-dawg** [apprenticeharper/DeDRM_tools#1508]
## Problem Description
I have an `.azw3`  file that I want to deDRM so I can use it on Remarkable Tablet.  The problem is that DRM does not get removed **Log indicates it cannot find the device serial number. But I have added it as eINK Tablet Serial number.** Please assist.

## My Environment
> ## My Environment
> ### Calibre: `5.10.1`
> ### Kindle: `Fire HD`
> ### DeDRM: `7.0.3`

## Log
<details><summary>Log Title</summary>

```
calibre Debug log
calibre 5.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 0, 3)
calibre 5.10 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 115.0 x 115.0
physicalDpi: 283.5348837209302 x 284.26943005181346
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[2.22] splash screen shown
[2.22] Initializing db...
[2.27] db initialized
[2.27] Constructing main UI...
[5.06] main UI initialized...
[5.06] Hiding splash screen
Starting QuickView
DeDRM v7.0.3: Trying to decrypt Who Not How Hardy.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
[10.06] splash screen hidden
[10.08] Started up in 10.08 seconds with 2 books
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Who Not How
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v7.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.0.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\l33t7\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded Who Not How to db in: 0.2
Added 1 books in 2.0 seconds
Worker Launch took: 0.12 seconds
Job: 0 Convert book 1 of 1 (Who Not How) finished
Convert book 1 of 1 (Who Not How)

	DeDRM v7.0.3: Trying to decrypt 8bimi6hf.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Who Not How
	Found 2 keys to try after 0.4 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.4 seconds
	searching for kinfoFiles in C:\Users\l33t7\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  cover: 'C:\\Users\\l33t7\\AppData\\Local\\Temp\\calibre_3lkozxq7\\8c3nzzzc.jpeg'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\l33t7\\AppData\\Local\\Temp\\calibre_3lkozxq7\\7rqlzjwp.opf'

	  output_profile: 'generic_eink'

	Resolved conversion options

	calibre version: 5.10.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\l33t7\\AppData\\Local\\Temp\\calibre_3lkozxq7\\8c3nzzzc.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001F9AA5E3A90>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001F9AA5E3D90>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\l33t7\\AppData\\Local\\Temp\\calibre_3lkozxq7\\7rqlzjwp.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 630, in run

	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.0.3: Trying to decrypt 8bimi6hf.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Who Not How
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\l33t7\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 630, in run

	  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\l33t7\AppData\Local\Temp\calibre_3lkozxq7\8bimi6hf.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: Who Not How



```
</details>

**Comment by ElleKayEm** [comment]
Entering the serial number only works on books that are for an E-ink Kindle, not a Fire.  If you don't have an E-ink Kindle on your Amazon account, then install Kindle for PC and download the book with that.  See this post about avoiding KFX format and getting books in the older format which can be decrypted with DeDRM 7.0.3:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by le-dawg** [comment]
Correct. COmpleted.
