### ISSUE TITLE
[QUESTION] Correct OpenSSL distribution for Windows in Wine

### ISSUE THREAD

**Issue by Threak** [apprenticeharper/DeDRM_tools#1509]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## What's the correct OpenSSL distribution for Windows in Wine?
I installed this one: https://slproweb.com/products/Win32OpenSSL.html
But `find_library('libeay32')` doesn't find the library.
However, when I replace this by `find_library('libcrypto-1_1')` it works: OpenSSL is found and books are decrypted.

Do I have to use a different OpenSSL installation or replace the library name in [adobekey.py](https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/adobekey.py#L118)?

## Log
<details><summary>Calibre DeDRM Plugin log</summary>

```log
adobekey.py v7.0
Copyright © 2009-2020 i♥cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "Z:\home\wisp\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 584, in <module>
    sys.exit(cli_main())
  File "Z:\home\wisp\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 507, in cli_main
    keys = adeptkeys()
  File "Z:\home\wisp\.config\calibre\plugins\DeDRM\libraryfiles\adobekey.py", line 347, in adeptkeys
    raise ADEPTError("PyCrypto or OpenSSL must be installed")
__main__.ADEPTError: PyCrypto or OpenSSL must be installed
```
</details>

**Comment by ableeker** [comment]
I think you're right, libcrypto-1_1 is the name of the library nowadays, it used to be libeay32. I'm not sure though if the old name is still in use on some Windows-computers, so to be safe we could use something like:

`libcrypto = find_library('libcrypto-1_1')`
`if libcrypto is None:`
`  libcrypto = find_library('libeay32')`
`  if libcrypto is None:`
`    raise ADEPTError('libcrypto not found')`

**Comment by Threak** [comment]
Thanks @ableeker 
Opened PR here: https://github.com/apprenticeharper/DeDRM_tools/pull/1560
