### ISSUE TITLE
 Failed to decrypt

### ISSUE THREAD

**Issue by csbpakz** [apprenticeharper/DeDRM_tools#1515]
## CheckList

- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Failed to decrypt
Hi!

Downloaded azw3 from amazon using the 'Download & transfer vis USB'.
When I try to convert it to PDF with Calibre I got DRM error.

Thank you for your help!

## Log
<details><summary>Log Title</summary>

```log
calibre Hibakeresési napló
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
[116.08] splash screen hidden
[116.08] Started up in 116.08 seconds with 4 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x90\x02\x17c\xa4nu\x08u\xe1\x82\x90\xcaa\xf6\xd9\xa6|)\\Y\xd9\xcd\xdc\x86\xc5O\xeb\xaaP\x9f\xb6', 'D:\\Munka\\Training\\Ebook\\AWS Certified SysOps Administrator Study Guide.azw3']
DeDRM v6.8.0: Trying to decrypt AWS Certified SysOps Administrator Study Guide.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: AWS Certified SysOps Administrator Study Guide
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Zoli\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Zoli\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 625, in run
  File "calibre_plugins.dedrm.__init__", line 575, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added AWS Certified SysOps Administrator Study Guide to db in: 0.6
Added 1 books in 1.6 seconds
Worker Launch took: 0.108999967575
Job: 0 Könyvek konvertálása: 1/1 (AWS Certified SysOps Administrator Study Guide) finished
Könyvek konvertálása: 1/1 (AWS Certified SysOps Administrator Study Guide)
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  pdf_serif_family: u'MS Shell Dlg 2'
	  pdf_sans_family: u'MS Shell Dlg 2'
	  read_metadata_from_opf: u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\zcofs1.opf'
	  output_profile: u'kindle'
	  verbose: 2
	  cover: u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\i5gphz.jpeg'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\i5gphz.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002CF94CA9308>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000002CF94CB8548>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'MS Shell Dlg 2',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\zcofs1.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Zoli\AppData\Local\Temp\calibre_d7jpmq\99nn0n.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  AWS Certified SysOps Administrator Study Guide (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	DRMError: AWS Certified SysOps Administrator Study Guide

Könyvek konvertálása: 1/1 (AWS Certified SysOps Administrator Study Guide)
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  pdf_serif_family: u'MS Shell Dlg 2'
  pdf_sans_family: u'MS Shell Dlg 2'
  read_metadata_from_opf: u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\zcofs1.opf'
  output_profile: u'kindle'
  verbose: 2
  cover: u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\i5gphz.jpeg'
Resolved conversion options
calibre version: 4.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\i5gphz.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002CF94CA9308>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000002CF94CB8548>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Zoli\\AppData\\Local\\Temp\\calibre_d7jpmq\\zcofs1.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\Zoli\AppData\Local\Temp\calibre_d7jpmq\99nn0n.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  AWS Certified SysOps Administrator Study Guide (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: AWS Certified SysOps Administrator Study Guide


```
</details>

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device when downloading?  Do you have that Kindle's serial number entered correctly into DeDRM's customization?

**Comment by csbpakz** [comment]
Hi ElleKayEm,

I think I did it right. 
I put my serial number from kindle withepaper device into the DeDRM plugin "EInk Kindle Serial Numbers" which I got clicking the eInk Kindle ebooks button.
_(I typed in the serial withouth the spaces so I get the correct lenght)_

**Comment by ElleKayEm** [comment]
If you choose that E-ink Kindle when downloading the book and its serial number is in DeDRM, then that copy should be decrypted when added to calibre.

**Comment by csbpakz** [comment]
Thank you for your help.

I chose a different approach. I downloaded the book with a windows kindle app and that was working fine.
happy end.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
