### ISSUE TITLE
Failed to decrypt

### ISSUE THREAD

**Issue by Pairofsai** [apprenticeharper/DeDRM_tools#1517]
I get the following log issue:

calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[2.01] main UI initialized...
[2.01] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\machine\OneDrive\Documents\My Kindle Content\B00VQTAXEC_EBOK\B00VQTAXEC_EBOK.azw
[9.78] splash screen hidden
[9.80] Started up in 9.80 seconds with 105 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x03\xf1E8\xd1\xd0\x1c\xef;\x17\xdb\tDb\x1f\xf9\xe5\x17g\xb2\x13\xda\xcb\xff\x08\x88_\xa8\x0c\x1e\xb4^', b'C:\\Users\\machine\\OneDrive\\Documents\\My Kindle Content\\B00VQTAXEC_EBOK\\B00VQTAXEC_EBOK.azw']
Gather KFX-ZIP (from KFX Input): Gathered 10 file(s) as C:\Users\paulo\AppData\Local\Temp\calibre_xc4t6dod\8de1xk8c.kfx-zip
DeDRM v7.0.3: Trying to decrypt 8de1xk8c.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 8de1xk8c
Got DSN key from database default_key
Error getting PIDs from serial number G090G105723504RD: string argument without an encoding
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
TypeError: string argument without an encoding
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c3121cec-dbfe-4c42-a42e-8678ca891436.voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\machine\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\machine\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2152735308' and UserName 'paulo'
DeDRM v7.0.3: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\machine\AppData\Local\Temp\calibre_xc4t6dod\8de1xk8c.kfx-zip
Processing container: B00VQTAXEC_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\machine\AppData\Local\Temp\calibre_xc4t6dod\ph02ve28_add_books\0\B00VQTAXEC_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00VQTAXEC_EBOK.azw has DRM and cannAdded Traditional Bowyer's Bible, Volume 3 to db in: 2.5
Added 1 books in 8.8 seconds

**Comment by ElleKayEm** [comment]
If you want to decrypt KFX format, you need to download it with Kindle for PC 1.26 or earlier.  If that is what you're using, try calibre 4.23 and DeDRM 6.8.1.  If you'd rather stick with calibre 5.x and DeDRM 7.0.3, try disabling KFX downloads.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371
