### ISSUE TITLE
Failure to DeDRM Kindle azw3 [QUESTION] Title

### ISSUE THREAD

**Issue by NotOxford** [apprenticeharper/DeDRM_tools#1518]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Title

Road to Wigan Pier  OUP bought from  from Amzaon.co.uk

Many Thanks,
Roy
## My Environment
Windows 10 Dell XPS 15 2016

### Calibre: `Version`
5.10.1

### Kindle: `Version`
I had version 1.17 but it got updated,  I have installed it again and tried to delete my old kindle device and reregister it, but kindle will not recognise my Amazon email and password
I installed the most recent kindle version as of 6 Feb 2021

### DeDRM: `Version`

6.8.1
## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Failed to initialize plugin: 'C:\\Users\\royma\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'
Successfully initialized third party plugins: 
calibre 5.10.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: 
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 140.9479768786127 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[2.16] splash screen shown
[2.16] Initializing db...
[2.19] db initialized
[2.19] Constructing main UI...
[4.24] main UI initialized...
[4.24] Hiding splash screen
Starting QuickView
[23.66] splash screen hidden
[23.67] Started up in 23.67 seconds with 45 books
Worker Launch took: 0.27 seconds
Job: 0 Convert book 1 of 1 (The Road to Wigan Pier (Oxford World's Classics)) finished
Convert book 1 of 1 (The Road to Wigan Pier (Oxford World's Classics))

	Failed to initialize plugin: 'C:\\Users\\royma\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'

	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\er4ifjoe.opf'

	  verbose: 2

	  cover: 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\zul5n4lr.jpeg'

	Resolved conversion options

	calibre version: 5.10.1

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\zul5n4lr.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'docx_custom_page_size': None,

	 'docx_no_cover': False,

	 'docx_no_toc': False,

	 'docx_page_margin_bottom': 72.0,

	 'docx_page_margin_left': 72.0,

	 'docx_page_margin_right': 72.0,

	 'docx_page_margin_top': 72.0,

	 'docx_page_size': 'letter',

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x087AEB50>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x087AECB8>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\er4ifjoe.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	InputFormatPlugin: MOBI Input running

	on C:\Users\royma\AppData\Local\Temp\calibre_gug6wmns\1sguv2n2.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: The Road to Wigan Pier (Oxford World's Classics)

stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x01\x07\x14\xed\xb0\xeb\xc9l\x10J cG \xf3~\x03\x1bR\xf6\x9b\x9a\xf6.\x99Q\xee\x9cF2\xec\xa8', b"C:\\Users\\royma\\OneDrive\\Documents\\Book_files\\1-N-Z\\O\\Orwell\\2021_work\\wigan\\The Road to Wigan Pier (Oxford World's Classics).azw3"]
Failed to initialize plugin: 'C:\\Users\\royma\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 153
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
Added The Road to Wigan Pier (Oxford World's Classics) to db in: 0.6
Added 1 books in 2.5 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.03 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.01 seconds
Worker Launch took: 0.22 seconds
Job: 8 Convert book 1 of 1 (The Road to Wigan Pier (Oxford World's Classics)) finished
Convert book 1 of 1 (The Road to Wigan Pier (Oxford World's Classics))

	Failed to initialize plugin: 'C:\\Users\\royma\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'

	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\1s8vgr8t.opf'

	  verbose: 2

	  cover: 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\ymyh1b7w.jpeg'

	Resolved conversion options

	calibre version: 5.10.1

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\ymyh1b7w.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_compress': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0894DB50>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'mobi_file_type': 'old',

	 'mobi_ignore_margins': False,

	 'mobi_keep_original_images': False,

	 'mobi_toc_at_start': False,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'no_inline_toc': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x0894DCB8>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'personal_doc': '[PDOC]',

	 'prefer_author_sort': False,

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\royma\\AppData\\Local\\Temp\\calibre_gug6wmns\\1s8vgr8t.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'share_not_sync': False,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	InputFormatPlugin: MOBI Input running

	on C:\Users\royma\AppData\Local\Temp\calibre_gug6wmns\2ar_u6xk.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: The Road to Wigan Pier (Oxford World's Classics)

</details>

**Comment by ElleKayEm** [comment]
If you want to stick with calibre 5.x, then install DeDRM 7.0.3.  For DeDRM 6.8.1, you'll need to go back to calibre 4.23.  For Kindle for PC, try logging into the latest version and then install the older version without uninstalling the new version.  Also see the bottom of [this post for preventing updates](https://www.mobileread.com/forums/showthread.php?t=283371).  Once you've gotten logged into Kindle for PC and calibre is setup with the corresponding version of DeDRM (and they are on the same machine and user), download and import a new copy of the book.

**Comment by NotOxford** [comment]
Hello,

Many thanks for your suggestions.  Unfortunately I am still unable register
the old version of Kindle even after downloading the latest version and
logging in and then trying to install and register KIndle 1.17.

I think I will accept defeat on this occasion.

Best wishes,
Roy

**Comment by ElleKayEm** [comment]
Well, you can decrypt the older formats downloaded with more recent versions of Kindle for PC.  You just need to disable its ability to download the KFX format.  See method 2 at the link I gave in my last reply.
