### ISSUE TITLE
ADE decryption failure on 7.0.3 (TypeError: can only concatenate str (not "bytes") to str)

### ISSUE THREAD

**Issue by dreikin** [apprenticeharper/DeDRM_tools#1519]
Book format: PDF
ADE version: 2.0.1
Calibre version: 5.10.1, Windows 64-bit
DeDRM version: 7.0.3

Potentially important note: This book semi-failed to decrypt on Calibre 4.x with DeDRM 6.x.  Book went through decryption but got "cannot extract the embedded font" in Adobe Acrobat when trying to view anything other than the cover page.  Content could still be viewed/scrolled through except for the fact that most characters were not displayed due to missing font.

What I think is the relevant log subsection:
```
DeDRM v7.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.3: Trying a new default key
DeDRM v7.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 484, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2179, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1792, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1432, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1085, in dict_value
  File "calibre_plugins.dedrm.ineptpdf", line 1011, in resolve1
  File "calibre_plugins.dedrm.ineptpdf", line 1001, in resolve
  File "calibre_plugins.dedrm.ineptpdf", line 1703, in getobj
  File "calibre_plugins.dedrm.ineptpdf", line 1372, in getpos
  File "calibre_plugins.dedrm.ineptpdf", line 445, in nunpack
TypeError: can only concatenate str (not "bytes") to str
DeDRM v7.0.3: Failed to decrypt with new default key after 0.1 seconds
```

Full log, personal info redacted:
```
calibre Debug log
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 32, 0) && Find Duplicates (1, 6, 3) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && KindleUnpack - The Plugin (0, 82, 1) && Obok DeDRM (6, 5, 4)
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (1, 32, 0) && Find Duplicates (1, 6, 3) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && KindleUnpack - The Plugin (0, 82, 1) && Obok DeDRM (6, 5, 4)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.21999999999998 x 109.18208955223879
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.92] db initialized
[0.92] Constructing main UI...
[2.58] main UI initialized...
[2.58] Hiding splash screen
Starting QuickView
DeDRM v7.0.3: Trying to decrypt Title.pdf
DeDRM v7.0.3: Title.pdf is a PDF ebook
DeDRM v7.0.3: Trying Encryption key default_key
DeDRM v7.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 433, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2179, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1792, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1432, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1085, in dict_value
  File "calibre_plugins.dedrm.ineptpdf", line 1011, in resolve1
  File "calibre_plugins.dedrm.ineptpdf", line 1001, in resolve
  File "calibre_plugins.dedrm.ineptpdf", line 1703, in getobj
  File "calibre_plugins.dedrm.ineptpdf", line 1372, in getpos
  File "calibre_plugins.dedrm.ineptpdf", line 445, in nunpack
TypeError: can only concatenate str (not "bytes") to str
DeDRM v7.0.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.0.3: Trying Encryption key default_key2
DeDRM v7.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 433, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2179, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1792, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1432, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1085, in dict_value
  File "calibre_plugins.dedrm.ineptpdf", line 1011, in resolve1
  File "calibre_plugins.dedrm.ineptpdf", line 1001, in resolve
  File "calibre_plugins.dedrm.ineptpdf", line 1703, in getobj
  File "calibre_plugins.dedrm.ineptpdf", line 1372, in getpos
  File "calibre_plugins.dedrm.ineptpdf", line 445, in nunpack
TypeError: can only concatenate str (not "bytes") to str
DeDRM v7.0.3: Failed to decrypt with key default_key2 after 0.1 seconds
DeDRM v7.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.0.3: Trying a new default key
DeDRM v7.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 484, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2179, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1792, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1432, in set_parser
  File "calibre_plugins.dedrm.ineptpdf", line 1085, in dict_value
  File "calibre_plugins.dedrm.ineptpdf", line 1011, in resolve1
  File "calibre_plugins.dedrm.ineptpdf", line 1001, in resolve
  File "calibre_plugins.dedrm.ineptpdf", line 1703, in getobj
  File "calibre_plugins.dedrm.ineptpdf", line 1372, in getpos
  File "calibre_plugins.dedrm.ineptpdf", line 445, in nunpack
TypeError: can only concatenate str (not "bytes") to str
DeDRM v7.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[7.70] splash screen hidden
[7.70] Started up in 7.70 seconds with # books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'HH\xfe\x12\rQ\xed\x93\xbe\xc88\xcd!;4\xa1\xd6\x1b\xaa\xd4?\xe7\xee\x05eL_}8?({', b'C:\\Some Path\\Title']
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 512, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 347, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001C5DF0F5280>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001C5DF0F5280>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 134, in __init__
  File "calibre\gui2\ui.py", line 152, in init_iaction
  File "calibre\customize\__init__.py", line 616, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
ModuleNotFoundError: No module named 'StringIO'
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 389, in initialize
  File "calibre_plugins.find_duplicates.action", line 54, in initialization_complete
  File "calibre_plugins.find_duplicates.duplicates", line 69, in __init__
  File "calibre_plugins.find_duplicates.config", line 111, in get_exemption_lists
NameError: name 'xrange' is not defined
Added Title to db in: 0.2
Added 1 books in 3.9 seconds
```

**Comment by ElleKayEm** [comment]
If it's not working with calibre 4.23 and DeDRM 6.8.1, I got nothing.

**Comment by ableeker** [comment]
It looks like this is code that hasn't been reached decoding PDF's until now. This is the code that throws the error:

`        return struct.unpack('>L', '\x00'+s)[0]`

I can't test this, because when decrypting the PDF's I've got, this line of code isn't used, but I believe the line should read:

`        return struct.unpack('>L', b'\x00'+s)[0]`

Could you test this?

**Comment by mariussteffen** [comment]
Same problem here - the change didn't fix it, log (cut):

`[133.19] Started up in 133.19 seconds with 0 books
Added Verschwörungsmythen. Wie wir mit verdrehten Fakten für dumm verk-1 to db in: 0.0
Added 1 books in 0.6 seconds
DeDRM v7.0.3: Trying to decrypt brand eins.pdf
DeDRM v7.0.3: brand eins.pdf is a PDF ebook
DeDRM v7.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.0.3: Trying a new default key
DeDRM v7.0.3: Saving a new default key
DeDRM v7.0.3: Saved a new default key after 0.9 seconds
DeDRM v7.0.3: Finished after 0.9 seconds
DeDRM v7.0.3: Trying to decrypt Verschwörungsmythen. Wie wir mit verdrehten Fakten für dumm verk.pdf
DeDRM v7.0.3: Verschwörungsmythen. Wie wir mit verdrehten Fakten für dumm verk.pdf is a PDF ebook
DeDRM v7.0.3: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.0.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.0.3: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 512, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1`

with Calibre 4.23 and DeDRM 6.8 everything works alright
