### ISSUE TITLE
Exception when getting default Kindle Key

### ISSUE THREAD

**Issue by jdalbey** [apprenticeharper/DeDRM_tools#1523]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Exception when getting default Kindle Key</summary>

```log
calibre Debug log
calibre 5.10.1  embedded-python: True is64bit: True
Linux-4.15.0-135-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.15.0-135-generic', '#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3)
calibre 5.10.1  embedded-python: True is64bit: True
Linux-4.15.0-135-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.15.0-135-generic', '#139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.51162790697674 x 94.2680412371134
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.07] splash screen shown
[0.07] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.70] main UI initialized...
[0.70] Hiding splash screen
Starting QuickView
DeDRM v7.0.3: Trying to decrypt The Overstory.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Overstory
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.0.3: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 554, in KindleMobiDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[15.60] splash screen hidden
[15.61] Started up in 15.61 seconds with 66 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=109051927', '--filename=/home/jdalbey/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Added The Overstory to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.02 seconds

(xed:7358): Gdk-CRITICAL **: 08:37:24.222: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
```
</details>

**Comment by ElleKayEm** [comment]
If the book was retrieved from the website for "download & transfer via USB" and you selected your Paperwhite for the device, then make sure you have that Paperwhite's serial number entered correctly in DeDRM's customization.

**Comment by jdalbey** [comment]
Thanks for your reply, yes, I understand I need to enter the serial number in the plugin customization.  I have done that, entering the serial number from Device Info on the Paperwhite into "eink Kindle ebooks" section of the configuration dialog.  I have then restarted the PC and relaunched Calibre with the same result.

**Comment by ElleKayEm** [comment]
Are you sure that the Paperwhite was the device you selected when downloading from the website?  Are you sure the serial number for that Paperwhite is entered into DeDRM correctly?  Did you re-add the book to calibre after entering the serial number and restarting calibre?

**Comment by jdalbey** [comment]
> Are you sure that the Paperwhite was the device you selected when downloading from the website?

Aha!  No, a different device was selected than the one to which I'm trying to use.  

Once I try the process with an ebook that was downloaded for the selected device, it works.

Thanks for your patience in answering my question.
