### ISSUE TITLE
[QUESTION] Can't remove DRM from ADE/acsm

### ISSUE THREAD

**Issue by xylem69** [apprenticeharper/DeDRM_tools#1527]
Hi,

the book is in .acsm format, which I can read in ADE. Plugin installed and active in Calibre.
When I import .epub into Calibre it does not strip it from DRM, still says it is locked.

any ideas?

Kobo Reader
OSX BigSur 11.2
ADE: 4.5
## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
Was ADE authorized with your Adobe ID before you opened the acsm file?  Is ADE on the same machine and user as calibre with DeDRM?  If both of those are the case, I'd try calibre 4.23 with DeDRM 6.8.1.

**Comment by xylem69** [comment]
Ok, will try with those versions.

**Comment by xylem69** [comment]
Still nothing using those older versions. Could be ADE version?

**Comment by ElleKayEm** [comment]
Possibly.  It depends on what the ebook vendor allows.
 But to use ADE 2.0.1, you'd need a machine that could run 32-bit programs.  This was adding the epub to calibre, not the acsm?  Is it from Kobo?  You could try Obok with your Kobo ereader or the Kobo Desktop app.

**Comment by xylem69** [comment]
> This was adding the epub to calibre, not the acsm? 
Yes.
>Is it from Kobo? You could try Obok with your Kobo ereader or the Kobo Desktop app.
Yes, Kobo. Any instructions for Obok? I am getting Could not find Kobo library error. I have Kobo desktop app though.

**Comment by ElleKayEm** [comment]
Was this with the version of Obok that comes with DeDRM 6.8.1?  And was it on calibre 4.23?  Obok will also work a Kobo ereader attached via USB.

**Comment by xylem69** [comment]
Yes, Obok within 6.8.1 tools and Calibre 4.23.
Getting error even with Kobo attached:
--
calibre, version 4.23.0
ERROR: Obok DeDRM v6.7.0: <p>No books found in Kobo Library
Are you sure it's installed\configured\synchronized?

**Comment by ElleKayEm** [comment]
Hmm, it's possible the problem with both DeDRM/ADE and Obok/Kobo is Big Sur.  I know there were initially issues for Big Sur and DeDRMing Kindle for Mac books.  If you could post a log adding an Adobe DRM epub and a separate log of just trying to use Obok, then maybe @apprenticeharper or someone can figure it out.  Here's how to get a debug log:   https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by xylem69** [comment]
I will try on Windows environment.

**Comment by xylem69** [comment]
Logfile:
--
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.12] main UI initialized...
[1.12] Hiding splash screen
[9.77] splash screen hidden
[9.77] Started up in 9.77 seconds with 1 books

{u'bsd_drives': {u'main': u'/dev/disk2'},
 u'drives': {u'main': '/Volumes/KOBOeReader'},
 u'mount_map': {'/dev/disk1s1': '/System/Volumes/Data',
                '/dev/disk1s2': '/System/Volumes/Preboot',
                '/dev/disk1s4': '/System/Volumes/VM',
                '/dev/disk1s5': '/System/Volumes/Update/mnt1',
                '/dev/disk1s5s1': '/',
                '/dev/disk1s6': '/System/Volumes/Update',
                '/dev/disk2': '/Volumes/KOBOeReader',
                'devfs': '/dev',
                'map auto_home': '/System/Volumes/Data/home'}}
DEBUG:    0.0 KoboTouch::open_osx - mount_map= {'/dev/disk2': '/Volumes/KOBOeReader', 'map auto_home': '/System/Volumes/Data/home', '/dev/disk1s5': '/System/Volumes/Update/mnt1', '/dev/disk1s4': '/System/Volumes/VM', '/dev/disk1s6': '/System/Volumes/Update', '/dev/disk1s1': '/System/Volumes/Data', '/dev/disk1s2': '/System/Volumes/Preboot', '/dev/disk1s5s1': '/', 'devfs': '/dev'}
DEBUG:    0.0 KoboTouch::open_osx - self._main_prefix= /Volumes/KOBOeReader/
DEBUG:    0.0 KoboTouch::open_osx - self._card_a_prefix= None
DEBUG:    0.0 KoboTouch::open_osx - self._card_b_prefix= None
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 KoboTouch:books - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='None', prefix='/Volumes/KOBOeReader/'
DEBUG:    0.1 Kobo device: Kobo Libra H2O
DEBUG:    0.1 Version of driver: (2, 5, 1) Has kepubs: True
DEBUG:    0.1 Version of firmware: (4, 25, 15875) Has kepubs: True
DEBUG:    0.1 Firmware supports cover image tree: True
DEBUG:    0.1 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.1 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: [u'kepub', u'epub', u'pdf', u'txt', u'cbz', u'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: None, modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 
DEBUG:    0.1 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    0.1 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.1 KoboTouch:books - length bl=0
DEBUG:    0.1 KoboTouch:books - length bl after sync=6
DEBUG:    0.1 KoboTouch:books - reading device database
DEBUG:    0.1 Database Version:  161
DEBUG:    0.1 KoboTouch:books - shelf list: []
DEBUG:    0.1 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId, ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,8,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.1 KoboTouch:books - self.kobo_series_dict= {}
DEBUG:    0.1 KoboTouch:books - about to sync_booklists
DEBUG:    0.1 USBMS: starting sync_booklists
DEBUG:    0.1 USBMS: finished sync_booklists
DEBUG:    0.1 KoboTouch:booDeDRM v6.8.0: Trying to decrypt Hoja.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “Hoja.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 413, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
ks - have done sync_booklists
DEBUG:    0.1 KoboTouch:books - end - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='carda'
DEBUG:    0.1 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.1 KoboTouch:books - oncard='cardb'
DEBUG:    0.1 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 6
DeviceJob: set_books_in_library finished: time= 0.00148892402649
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added Hoja to db in: 0.1
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
This book is not being detected as an Adobe epub at all.  That shouldn't be the case even with ADE 4.5.  This is the EPUB that was downloaded to the Digital Editions folder by ADE when you opened the ACSM file?

> DeDRM v6.8.0: “Hoja.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

**Comment by xylem69** [comment]
Yes, this is the file ADE creates in Documents>Digital Editions after opening .acsm.

**Comment by ElleKayEm** [comment]
That's very odd.  It is missing the info inside the epub that DeDRM needs to unlock it.  As far as DeDRM can tell, this book appears DRM-free.

**Comment by xylem69** [comment]
Tried with other book, same thing.

**Comment by ElleKayEm** [comment]
If you have a Windows machine you can set things up on, you should be good.  I'm on Windows 10, get most of my books from Kobo, and am able to DeDRM the copies downloaded with ADE 2.0.1.

Install [Adobe Digital Editions 2.0.1](https://www.adobe.com/support/digitaleditions/downloads.html).  Authorize it with your  Adobe ID.  Download the ACSM file from Kobo again.  Open the ACSM file.  Add the EPUB to calibre with DeDRM.  Both calibre 4.23/DeDRM 6.8.1 and calibre 5.x/DeDRM 7.0.3 are working with Adobe DRM EPUBs.

If ADE EPUBs downloaded with ADE on Big Sur don't have the rights.xml stored inside them (as appears to be the case with yours), I'm not sure there's going to be a solution there.

**Comment by xylem69** [comment]
ADE 2.0 does not work on my Windows Server 2019 machine. ADE 4.5 works fine, but creates same ePubs as on OSX.
![Screenshot 2021-02-13 at 09 07 06](https://user-images.githubusercontent.com/72762035/107845363-2c187d80-6ddb-11eb-8cd8-d7fc7427cb05.jpg)

I guess I'll have to setup a win10 machine...

**Comment by ElleKayEm** [comment]
Well, that makes me wonder if Kobo is using the hardened Adobe DRM if downloaded with ADE 4.5 first.  If so, then you aren't able to download it with ADE 2 afterward.  But I don't know for sure if that's what's happening here.

**Comment by robinlucidarme1234** [comment]
[1jixya1u_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/5991912/1jixya1u_worker_redirect.log
[Facilities Maintenance & Repair Costs with RSMeans Data, 28th An.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/5991928/Facilities.Maintenance.Repair.Costs.with.RSMeans.Data.28th.An.pdf)
)

In the parse directory, I can see the pictures but we cannot generate a docx or pdf file.
File "calibre_plugins.dedrm.adobekey", line 266, in __del__ any idea what the last message means?

**Comment by ElleKayEm** [comment]
@robinlucidarme1234 
Have you tried this book with calibre 4.23 and DeDRM 6.8.1?

**Comment by robinlucidarme1234** [comment]
[btwih2_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/5999024/btwih2_worker_redirect.log)

I've installed 4.23 and 6.8.1
The logfile shows 
6 Text Styles 9 Combined styles
DOCX output written to C:\Users\Robin\AppData\Local\Temp\calibre_d_f9jq\kiyvp_.docx

but the file isn't generated in this directory.
Is there something else I could try?

![image](https://user-images.githubusercontent.com/79173209/108276814-3ca75b80-712d-11eb-9675-f1ab9b630e9b.png)

**Comment by ElleKayEm** [comment]
@robinlucidarme1234 
I don't see anything to do with DeDRM in that log.  Let's see the import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by robinlucidarme1234** [comment]
![image](https://user-images.githubusercontent.com/79173209/108301665-5bbae300-7157-11eb-96c6-af1b8502c08d.png)
[eouksd_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/6000432/eouksd_worker_redirect.log)

@ElleKayEm you're right I don't see anything from the DRM in the logfile but I configured the plugin. What did I do wrong?

and the logfile says:
Rasterizing SVG images...
Processing index.html
7 Text Styles 8 Combined styles
DOCX output written to C:\Users\Robin\AppData\Local\Temp\calibre_ler2ym\fqdvtd.docx

and the .docx file isn't generated in the folder.

**Comment by j-howell** [comment]
> and the .docx file isn't generated in the folder.

Conversion by calibre puts the result in a temporary file. It is then moved to the folder containing the original format it was converted from. You can find it in your calibre library associated with the original book record.

**Comment by ElleKayEm** [comment]
@robinlucidarme1234 
If you had DeDRM installed before adding that book to calibre, then DRM was probably successfully removed when you first added it.  No need for DeDRM on conversion if the book is already DRM-free.

**Comment by robinlucidarme1234** [comment]
> > and the .docx file isn't generated in the folder.
> 
> Conversion by calibre puts the result in a temporary file. It is then moved to the folder containing the original format it was converted from. You can find it in your calibre library associated with the original book record.

@j-howell 
![image](https://user-images.githubusercontent.com/79173209/108456870-3052f980-7226-11eb-9002-73a979138906.png)
that makes sense. I have worked with different macro's and you want to work in a temp directory and write in the final directory.
In this case I verified the original folder and I couldn't find the converted file. I've uploaded the result in a screenshot.

**Comment by robinlucidarme1234** [comment]
> @robinlucidarme1234
> If you had DeDRM installed before adding that book to calibre, then DRM was probably successfully removed when you first added it. No need for DeDRM on conversion if the book is already DRM-free.

@ElleKayEm in the original directory I only see the original pdf files. I tried to convert to .docx and .pdf but both without results.
Should I install it again or any other tips?
The problem with the current DRM-protected files is you can not search very well in them. If I can convert them to a standard pdf of .docx, this would improve our efficiency a lot.
[Square Foot Costs with RSMeans Data, 42nd Annual Edition.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/6007659/Square.Foot.Costs.with.RSMeans.Data.42nd.Annual.Edition.pdf)

**Comment by ElleKayEm** [comment]
@robinlucidarme1234 
j-howell was talking about the copy in calibre, not the one in the Digital Edition's folder.  The PDF in calibre should be DRM-free.

**Comment by j-howell** [comment]
> j-howell was talking about the copy in calibre, not the one in the Digital Edition's folder. 

Yes. Calibre maintains each library of books in a folder hierarchy that it manages itself. When books are imported into calibre they are copied from the original location into the library. DRM removal happens at that time. Subsequent conversions results in additional files in the library. The calibre GUI allows access to these files. You are not intended to access them via the OS.

**Comment by robinlucidarme1234** [comment]
You guys were right. Thank you so much.
The location is in the calibre folder:
C:\Users\User\Calibre Library\Matt Doheny\Square Foot Costs with RSMeans Data, (17)\

Problem solved. I've added this in the comment for other users of this fantastic tool.

**Comment by ElleKayEm** [comment]
As j-howell said, no need to look into the folder.  Just access the files from within the calibre program.
