### ISSUE TITLE
Exception not considered

### ISSUE THREAD

**Issue by overdrive80** [apprenticeharper/DeDRM_tools#1530]
Versión of Kindle PC: 1.17.0. (44170)
Calibre versión 5.11.0 (x86)
DRM_Tools: 6.8.1
Windows 10 64 bit 20H2 (19042.804)

When I try load plugin on calibre I get this error:

```calibre, version 5.11.0
ERROR: Excepción no considerada: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
````

**Comment by ElleKayEm** [comment]
With calibre 5.x, you need DeDRM 7.0.3.  To use DeDRM 6.8.1, go back to calibre 4.23.

**Comment by overdrive80** [comment]
Thanks for your answer.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by overdrive80** [comment]
I not see the option for closed issue.
