### ISSUE TITLE
[QUESTION] Get Syntax error on installing 7.0.3 into Calibre 5.11

### ISSUE THREAD

**Issue by sheridanmp** [apprenticeharper/DeDRM_tools#1535]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`. Windows 10 Calibre 5.11
- [ ] Code block is used for `the log`. Copied error output from calibre
 7.03

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 5.11.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 163)

calibre 5.11 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 5, 4)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 163
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Looks like you were trying to load DeDRM 6.8.1 or earlier.  Make sure this is DeDRM 7.0.3.

**Comment by sheridanmp** [comment]
Oh for crying out loud. My bad!!!
I put the 7.0.3 file into the calibre folder but calibre opened the dedrm
folder from last time and I didn't notice until your mail.
I am so sorry to have wasted your time for something that I should have
solved myself.
Thank you
And I'll be more careful in the future.

Regards
Sheridan

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by sheridanmp** [comment]
I consider it closed.
The real 7.0.3 loaded just fine.
Thanks.
Is there more I need to do to close it?
Sher

**Comment by ElleKayEm** [comment]
Click the close issue button.

**Comment by sheridanmp** [comment]
My bad. Not actually trying to install 7.0.3. Which worked just fine ince jnstalled.
