### ISSUE TITLE
DRM removal unsuccessful

### ISSUE THREAD

**Issue by oojBuffalo** [apprenticeharper/DeDRM_tools#1536]
# Problem: DRM removal unsuccessful
--------------------------------------------------------------------------------
### Source: Purchased on Amazon
--------------------------------------------------------------------------------

# My Environment
--------------------------------------------------------------------------------
### DeDRM: `Commit` 52bdbe95c91305b423dea700bb5f42f7b0078c79
--------------------------------------------------------------------------------

### General System Information:
macOS Big Sur v11.2.1 (20D74)
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Processor: 2.7 GHz Quad-Core Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
Storage: 256 GB APPLE SSD AP0256M

--------------------------------------------------------------------------------

### Hardware Overview:
Model Name:                 MacBook Pro
Model Identifier:           MacBookPro15,2
Processor Name:             Quad-Core Intel Core i7
Processor Speed:            2.7 GHz
Number of Processors:       1
Total Number of Cores:      4
L2 Cache (per Core):        256 KB
L3 Cache:                   8 MB
Hyper-Threading Technology: Enabled
Memory:                     16 GB
System Firmware Version:    1554.80.3.0.0 (iBridge: 18.16.14346.0.0,0)

--------------------------------------------------------------------------------

## Log
<details><summary>Key Issue</summary>

```log
calibre Debug log
calibre 5.11  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3) && Obok DeDRM (6, 7, 0)
calibre 5.11  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.08] main UI initialized...
[1.08] Hiding splash screen
[1.12] splash screen hidden
[1.12] Started up in 1.12 seconds with 9 books
Starting QuickView
DeDRM v7.0.3: Trying to decrypt B01B1G83SM_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Bioinformatics and Computational Biology in Drug Discovery and Development
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/ooj/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'ooj'  on file  /Users/ooj/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'55bd3d229bbd'
Decrypted key file using IDString '55bd3d229bbd' and UserName 'ooj'
DeDRM v7.0.3: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Bioinformatics and Computational Biology in Drug Discovery and Development
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Bioinformatics and Computational Biology in Drug Discovery and Development to db in: 0.0
Added 1 books in 1.0 seconds
```
</details>

**Comment by ElleKayEm** [comment]
If you want to stick with KFX format, try Kindle for Mac 1.26.  Otherwise, try disabling KFX downloads.  See method 2 here:  https://www.mobileread.com/forums/showthread.php?t=283371

And this Mac specific post here:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
