### ISSUE TITLE
DeDRM7.1.0 won't install

### ISSUE THREAD

**Issue by bgoldnyxnet** [apprenticeharper/DeDRM_tools#1551]
calibre, version 5.11.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 163)

calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 163
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Make sure you are trying to install 7.1.0.  It looks like you tried to install 6.8.1 or earlier.

**Comment by patofufu** [comment]
I am having a similar problem. Caliber 5.12. Trying to install using 7.1.0

calibre, version 5.12.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Kobo Books (1, 8, 0) && Kobo Utilities (2, 12, 3) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Doesn't look like this is actually DeDRM 7.1.0.

**Comment by garfieldnate** [comment]
I came to report the same thing, but I was indeed trying to load the old version :D Callibre remembered the path to the old one, which I installed a long time ago, and it was still sitting in my downloads folder. Just double check the name of the folder you're loading from Callibre. It should work fine :)

**Comment by rayjos** [comment]
Similar issue with DeDRM not installing:

calibre 5.12  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

This looks like I have Calibre 5.12
The unzipped DeDRM tool folder name is DeDRM_tools_7.1.0

This report indicates it was loading KFX plug in.  Before I ran the DeDRM, I had just updated the KFX to 1.37 (latest).   The plug in page lists this 1.37.0 version with the  calibre column listed as 2.0.0.

Please suggest how I may proceed.

**Comment by ElleKayEm** [comment]
@rayjos 
Same answer as above.  Make sure you are loading DeDRM_plugin.zip from the unzipped DeDRM_tools_7.1.0 folder.

**Comment by rayjos** [comment]
Thank you.  After several attempts, I found I was attempting to use the file in the zip file itself.  This time it loaded from the extract folder.

I added a DRM book and no errors were reported.  On attempting to open the book, an error report was emitted stating the file had DRM.  

I removed the book.  I restarted Calibre and added the book again.  I received the same error.  

Viewing the contents of 'Plugins', I see:
Conversion
    KFX Input (1.37.0)
File type
    DeDRM (7.1.0)
    Gather KFX-SIP (from KFX Input)(1.37.0)
    Package KFX (from KFX Input )(1.37.0)  
Metadata reader
    KFX metadata reader (from KFX Input)(1.37.0)

**Comment by ElleKayEm** [comment]
@rayjos 
What type of book?  And how are you downloading?

**Comment by rayjos** [comment]
This is in the My Kindle Content folder.  It has a folder ending in the letters _EBOK and the file has an asw extention.  I downloaded this book to my computer about 6 months ago.  I have read it from there using Kindle for PC and I have used Android TTS to read aloud.

**Comment by rayjos** [comment]
I would like to clarify that use with Android includes the Android Kindle reader.

**Comment by ElleKayEm** [comment]
Download with Kindle for PC 1.26 or earlier.  Or disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by rayjos** [comment]
Thank you all for the input.  

I can now convert all the books I have tried, about 15.  

I am using 1.26 with the latest Calibre and DeDRM and an KFX import tool.  I turned off automatic updates and renamed the storage file to storageOLD.  I toggled the auto update field, saved and restarted Kindle twice.  I have rebooted the machine multiple times to see if updates occurred but it has been stable.  

Finding a copy of 1.26 was challenging.  All references in the string no longer worked.  So one more is from win.horje.com.  

The first book I converted (KFX to EPUB), worked.  So I tried batching 4 books.  Two worked and two failed due to being KFX.  When I ran them individually, they worked.

One quarter of the way there.

**Comment by ElleKayEm** [comment]
If you can disable KFX downloads and get the older formats, conversion might be better.

From what I understand, the way to prevent updates is to replace the updates folder with a text file named updates with no extension.  Or change the properties of the updates folder to read-only.  If you don't have an updates folder, create the text file or a read-only folder with that name.

Finding a legitimate copy of Kindle for PC 1.17 or 1.24 is probably easier.  With 1.17, you don't have to worry about KFX at all. 
 With 1.24, it's easier to turn off KFX downloads.  Always be sure to check the hash!
