### ISSUE TITLE
Won't install - ERROR: Unhandled exception.  DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by LeoLaff** [apprenticeharper/DeDRM_tools#1553]
calibre, version 5.11.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\9\\Documents\\Calibre Library\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\9\\Documents\\Calibre Library\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.1.0.zip.  Load DeDRM_plugin.zip.

**Comment by ProdByJuliot** [comment]
> 
> 
> Unzip DeDRM_tools_7.1.0.zip. Load DeDRM_plugin.zip.

Where's that? I unzipped the master, and the closest thing to that I see is a zip file named alfcrypto_src.zip in
DeDRM_tools-master\DeDRM_tools-master\DeDRM_plugin - there is no zipped DeDRM plugin as far as my eyes see.

**Comment by ElleKayEm** [comment]
@ProdByJuliot 
In the current release:  https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.1.0

**Comment by ProdByJuliot** [comment]
@ElleKayEm Thanks! Looks like I'm just incompetent and new to using GitHub :)

**Comment by kloro2006** [comment]
i'm using 7.1.0 and getting the python exception. i'm running ubuntu 20,04

**Comment by ElleKayEm** [comment]
Latest version is here: https://github.com/noDRM/DeDRM_tools

Same issue as above?  Same solution.
