### ISSUE TITLE
Attempting to convert azw3 file to pdf

### ISSUE THREAD

**Issue by AliceBunn** [apprenticeharper/DeDRM_tools#1555]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Attempting to convert azw3 file to pdf
I did the basics (downloaded, installed, added ebook) but the DRM remained. I am unsure of what the Kindle key is. If I need my Kindle's serial number, where do I find that?

## Log
<details><summary>calibre Debug log</summary>

```log
calibre Debug log
calibre 5.11 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.11 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.58] splash screen shown
[0.58] Initializing db...
[0.58] db initialized
[0.58] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Thus Spoke Zarathustra.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Thus Spoke Zarathustra
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ryanv\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[6.95] splash screen hidden
[6.97] Started up in 6.97 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'5\xee\xc1\xed\x90\x8b\x963:\xc6x\xca\x04\xa7|\x04\x1ea\xb8\xe5g\xd2d\x85\xf0)v$ ;\x8b\xb1', b'D:\\Downloads\\Thus Spoke Zarathustra.azw3']
Added Thus Spoke Zarathustra to db in: 1.0
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 1 books in 1.5 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Thus Spoke Zarathustra) finished
Convert book 1 of 1 (Thus Spoke Zarathustra)

	DeDRM v7.1.0: Trying to decrypt 6g25x4_j.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Thus Spoke Zarathustra
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\ryanv\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  cover: 'C:\\Users\\ryanv\\AppData\\Local\\Temp\\calibre_sgoszrja\\wdlqs_xu.jpeg'

	  pdf_serif_family: 'MS Shell Dlg 2'

	  verbose: 2

	  pdf_sans_family: 'MS Shell Dlg 2'

	  output_profile: 'generic_eink'

	  read_metadata_from_opf: 'C:\\Users\\ryanv\\AppData\\Local\\Temp\\calibre_sgoszrja\\_nzuqnkw.opf'

	Resolved conversion options

	calibre version: 5.11.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\ryanv\\AppData\\Local\\Temp\\calibre_sgoszrja\\wdlqs_xu.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001D4511D7880>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001D4511D7B80>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier',

	 'pdf_mono_font_size': 16,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'MS Shell Dlg 2',

	 'pdf_serif_family': 'MS Shell Dlg 2',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\ryanv\\AppData\\Local\\Temp\\calibre_sgoszrja\\_nzuqnkw.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.1.0: Trying to decrypt 6g25x4_j.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Thus Spoke Zarathustra
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\ryanv\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\ryanv\AppData\Local\Temp\calibre_sgoszrja\6g25x4_j.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: Thus Spoke Z
athustra

```
</details>

**Comment by ElleKayEm** [comment]
Yes, entering the serial number into DeDRM's customization will work if it is an E-ink Kindle, not a Fire.  Easiest way is to copy and paste it from your Content & Devices page on the Amazon website.

**Comment by AliceBunn** [comment]
I have a fire. What do I do about that?

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, then install Kindle for PC on the same machine and user as calibre with DeDRM and import a copy from there.  You will also need to disable KFX downloads or use Kindle for PC 1.26 or earlier and install the KFX Input plugin.  Details here:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by AliceBunn** [comment]
did it. Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
