### ISSUE TITLE
DeDRM 7.1.0 Kindle PC 1.25.1 Calibre not converting

### ISSUE THREAD

**Issue by HerbM** [apprenticeharper/DeDRM_tools#1559]
DeDRM 7.1.0 Kindle PC 1.25.1 Calibre not converting.

I'm trying to convert my purchased books (2 but only one shown here) due to vision problems to a reading format which allows me to see and read the books much better than Kindle reader.

I believe I have repeated all of the steps correctly based on the read me file:

1. Removed books from Calibre
2. Added plugins
3. Restarted Calibre (then repeated all this with restart to Debug mode)
4. Imported books
5. Attempted conversion to both epub and pdf -- both failed.

Please tell me what I am doing wrong and assist if possible...

Thank you so much for your gracious work and great plugins 
(I've used them before quite successfully but it's been some time.)

------ Verbatim LOG FOLLOWS ---

calibre Debug log
calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.21322 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.21322')
Python 3.8.5
Windows: ('10', '10.0.21322', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
calibre 5.11  embedded-python: True is64bit: False
Windows-10-10.0.21322 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.21322')
Python 3.8.5
Windows: ('10', '10.0.21322', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.66492146596858 x 127.59069767441859
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.97] splash screen shown
[0.97] Initializing db...
[0.97] db initialized
[0.97] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.76] main UI initialized...
[1.76] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt B084WT5CKP_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Herb\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Herb\AppData\Local\Amazon\Kindle\storage\.kinf2018
[21.14] splash screen hidden
[21.14] Started up in 21.14 seconds with 3 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd5\x0eN\xf6\x9eL\xc0\x88\x8b.\xa2:\x03\xda\xaevR\xaa\xb06\x8b\x10\xfbGvi\xee\x0b;\\\xd9\x04', b'C:\\Users\\Herb\\Documents\\My Kindle Content\\B084WT5CKP_EBOK\\B084WT5CKP_EBOK.azw']
Decrypted key file using IDString '2902052011' and UserName 'Herb'
DeDRM v7.1.0: Found 1 new key
DeDRM v7.1.0: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Added B084WT5CKP EBOK to db in: 2.2
Added 1 books in 6.4 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (B084WT5CKP EBOK) finished
Convert book 1 of 1 (B084WT5CKP EBOK)

	DeDRM v7.1.0: Trying to decrypt tng76wrf.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\Herb\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Herb\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2902052011' and UserName 'Herb'
	DeDRM v7.1.0: Found 1 new key
	DeDRM v7.1.0: Ultimately failed to decrypt after 4.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  output_profile: 'tablet'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Herb\\AppData\\Local\\Temp\\calibre_zl661s6e\\mmh5wyim.opf'

	Resolved conversion options

	calibre version: 5.11.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07C44838>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x07C44CB8>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Herb\\AppData\\Local\\Temp\\calibre_zl661s6e\\mmh5wyim.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook

	calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 4.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.1.0: Trying to decrypt tng76wrf.azw
	DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Herb\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Herb\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2902052011' and UserName 'Herb'
	DeDRM v7.1.0: Found 1 new key
	DeDRM v7.1.0: Ultimately failed to decrypt after 4.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook

	calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 4.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\Herb\AppData\Local\Temp\calibre_zl661s6e\tng76wrf.azw

	Traceback (most recent call last):

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__

	calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__

	calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX
ooks.

**Comment by ElleKayEm** [comment]
For conversion, I recommend avoiding the KFX format you have here.  See method 1 or 2 here:  https://www.mobileread.com/forums/showthread.php?t=283371
