### ISSUE TITLE
DRM not removed, because not known format

### ISSUE THREAD

**Issue by weechatter** [apprenticeharper/DeDRM_tools#1562]
## CheckList

- [X ] `The Title` and The `Log Title` are setted correctly.
- [ X] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
DeDRM v7.1.0: Trying to decrypt DT0400.9783347007604_A39335358.epub
DeDRM v7.1.0: Verifying zip archive integrity
DeDRM v7.1.0: “DT0400.9783347007604_A39335358.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 642, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 418, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Couldn't decrypt after {2:.1f} seconds. DRM free perhaps?".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
```
</details>

<details><summary>Hexdump from file</summary>
```
0x00000000: 50 4b 03 04 0a 00 00 00 00 00 46 10 c6 50 6f 61 ab 2c 14 00 00 00 14 00 00 00 08 00 00 00 6d 69  PK........F..Poa.,............mi
0x00000020: 6d 65 74 79 70 65 61 70 70 6c 69 63 61 74 69 6f 6e 2f 65 70 75 62 2b 7a 69 70 50 4b 03 04 14 00  metypeapplication/epub+zipPK....
0x00000040: 08 00 08 00 46 10 c6 50 00 00 00 00 00 00 00 00 00 00 00 00 17 00 00 00 4d 45 54 41 2d 49 4e 46  ....F..P................META-INF
0x00000060: 2f 65 6e 63 72 79 70 74 69 6f 6e 2e 78 6d 6c ed dd 5d 8b e3 36 14 06 e0 fb fe 8a 90 5e c7 d6 91  /encryption.xml..]..6.......^...
```
</details>

**Comment by ElleKayEm** [comment]
So is it an Adobe DRM or B&N epub?

**Comment by weechatter** [comment]
The bookstore said, its Adobe DRM

**Comment by ElleKayEm** [comment]
Did you download with Adobe Digital Editions authorized with your Adobe ID?

**Comment by weechatter** [comment]
No i did it with direct link, because i am on linux :-)

**Comment by ElleKayEm** [comment]
That will not work.  DeDRM cannot get the key to unlock the book.  And information expected to be inside the file is not there.
