### ISSUE TITLE
Can't remove DRM / OSX

### ISSUE THREAD

**Issue by jkavirta** [apprenticeharper/DeDRM_tools#1567]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
B078KW348G_EBOK.azw

### Calibre: `Version`
5.12.0
### Kindle: `Version`
1.26.1
### DeDRM: `Version`
7.1.0

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG

calibre Debug log
calibre 5.11  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 0)
calibre 5.11  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
Using calibre Qt style: True
[0.00] Starting up...
[0.05] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[1.08] main UI initialized...
[1.08] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/k88222/Downloads/B078KW348G_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_tfru7_e4/od6tcsle.kfx-zip
DeDRM v7.1.0: Trying to decrypt od6tcsle.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: od6tcsle
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 1 keys to try after 0.3 seconds
DeDRM v7.1.0: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v7.1.0: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2018 file: /Users/k88222/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/k88222/Library/Application Support/Kindle/storage/.kinf2018
[8.33] splash screen hidden
[8.33] Started up in 8.33 seconds with 3 books
trying username  b'k88222'  on file  /Users/k88222/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'092206e8a5b0'
trying IDString: b'2d4c5b5af594'
Decrypted key file using IDString '2d4c5b5af594' and UserName 'k88222'
trying username  b'k88222'  on file  /Users/k88222/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'092206e8a5b0'
trying IDString: b'2d4c5b5af594'
Decrypted key file using IDString '2d4c5b5af594' and UserName 'k88222'
DeDRM v7.1.0: Found 1 new key
Decrypting KFX-ZIP ebook: od6tcsle
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 1 keys to try after 2.1 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging /var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_tfru7_e4/od6tcsle.kfx-zip
Processing container: B078KW348G_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_tfru7_e4/9no0xrdz_add_books/0/B078KW348G_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 63, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B078KW348G_EBOK.azw has DRM and cannot be converted
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
```
</details>

**Comment by ElleKayEm** [comment]
Looks like the main file of the book was moved from its original folder so KFX Input couldn't find all the files needed.

> Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.

You could also try disabling KFX format downloads.  See this post:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by jkavirta** [comment]
A new attempt with method 2. Now original folder is used:
calibre Debug log
calibre 5.11  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 0)
calibre 5.11  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/x/Library/Application Support/Kindle/My Kindle Content/B078KW348G_EBOK/B078KW348G_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B078KW348G_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Strategic Innovation Management
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/x/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'x'  on file  /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'092206e8a5b0'
[10.56] splash screen hidden
[10.56] Started up in 10.56 seconds with 3 books
trying IDString: b'2d4c5b5af594'
Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
trying username  b'x'  on file  /Users/x/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'092206e8a5b0'
trying IDString: b'2d4c5b5af594'
Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Strategic Innovation Management
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 4 keys to try after 1.8 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Strategic Innovation Management to db in: 0.0
Added 1 books in 2.5 seconds
Worker Launch took: 0.02 seconds
Job: 0 Convert book 1 of 1 (Strategic Innovation Management) finished
Convert book 1 of 1 (Strategic Innovation Management)
	DeDRM v7.1.0: Trying to decrypt 99r16874.azw
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Strategic Innovation Management
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	Found k4Mac kinf2018 file: /Users/x/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'x'  on file  /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'092206e8a5b0'
	trying IDString: b'2d4c5b5af594'
	Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
	trying username  b'x'  on file  /Users/x/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'092206e8a5b0'
	trying IDString: b'2d4c5b5af594'
	Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Strategic Innovation Management
	Got SerialNumber from database default_key_2
	Got UsernameHash from database default_key_2
	Found 4 keys to try after 2.0 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  read_metadata_from_opf: '/var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_chk96fsc/h0q9nuv3.opf'
	  output_profile: 'generic_eink'
	  verbose: 2
	  cover: '/var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_chk96fsc/aofhn45x.jpeg'
	Resolved conversion options
	calibre version: 5.11.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_chk96fsc/aofhn45x.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10e789220>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10e7894f0>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Helvetica',
	 'pdf_serif_family': 'Times',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_chk96fsc/h0q9nuv3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.1.0: Trying to decrypt 99r16874.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Strategic Innovation Management
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 4 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	Found k4Mac kinf2018 file: /Users/x/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'x'  on file  /Users/x/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'092206e8a5b0'
	trying IDString: b'2d4c5b5af594'
	Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
	trying username  b'x'  on file  /Users/x/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'092206e8a5b0'
	trying IDString: b'2d4c5b5af594'
	Decrypted key file using IDString '2d4c5b5af594' and UserName 'x'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 4 ebook: Strategic Innovation Management
	Got SerialNumber from database default_key_2
	Got UsernameHash from database default_key_2
	Found 4 keys to try after 1.8 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/c3/3b28bwf53xl6s_tsbbs7zhp0012s9j/C/calibre_5.11.0_tmp_chk96fsc/99r16874.azw
	Traceback (most recent call last):
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 33, in convert
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in extract_content
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Strategic Innovation Management
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 39, in convert
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in extract_content
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Strategic Innovation Management

**Comment by ElleKayEm** [comment]
This copy of the book was downloaded with the current installation of Kindle for Mac on the same machine and user as calibre with DeDRM?

**Comment by jkavirta** [comment]
Yes.

**Comment by ElleKayEm** [comment]
I don't know what the issue is then.  The key is found and decrypted, but it's not working for this book.  Perhaps try calibre 4.23 and DeDRM 6.8.1.

**Comment by jkavirta** [comment]
Downgrading to calibre 4.23 and DeDRM 6.8.1 did the trick. Thank you so much for helping!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by aliusmiles** [comment]
fyi, conversion worked for me on calibre 5.12, DeDRM 7.1.0 and kindle4mac 1.30 after disabling kfx by `chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test` and then 'download but don't open the book'

**Comment by ElleKayEm** [comment]
@aliusmiles 
OP tried that.  The non-KFX book still didn't work in this particular case.
