### ISSUE TITLE
Can't remove DRM from AZW3 file

### ISSUE THREAD

**Issue by nadres** [apprenticeharper/DeDRM_tools#1569]
## Can't remove DRM from AZW3 file

Good day,
I can't remove the DRM of a free-book from Amazon so I can read it in my Kobo device.

I also own a eInk Kindle 4, for which I added its Serial Number from Amazon into the plugin configuration.

There's an exception with Crypto.Cipher. I believe it may be related to my python set up, but I just couldn't figure it out. I think I  have more than one python in my system.

Hope this information i was able to trace is useful, please let me know if you need anything else.

## Python Crypto
<details><summary>Result of pip install</summary>

```
sudo pip3 install pycrypto
Requirement already satisfied: pycrypto in /usr/local/lib/python3.6/site-packages (2.6.1)

sudo pip3 install pycryptodome
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.6/site-packages (3.10.1)
```
</details>

## Log
<details><summary>Calibre Log in Debug Mode </summary>

```log
calibre Debug log
calibre 5.5  embedded-python: True is64bit: True
Linux-5.4.0-66-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-66-generic', '#74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021')
**Python 3.8.5**
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && KePub Input (3, 2, 10) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 4, 1)
calibre 5.5  embedded-python: True is64bit: True
Linux-5.4.0-66-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-66-generic', '#74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && KePub Input (3, 2, 10) && KePub Metadata Reader (3, 2, 9) && KePub Metadata Writer (3, 2, 12) && KePub Output (3, 4, 1)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294117647 x 94.59310344827585
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.45] main UI initialized...
[1.45] Hiding splash screen
Starting QuickView
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 935, resource id: 39846793, major code: 40 (TranslateCoords), minor code: 0
DeDRM v7.1.0: Trying to decrypt Aristotle_ The Complete Works (1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 15, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.5.0_tmp_gjr4c8qm/gw2wr46_plugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/_mode_ecb.py", line 35, in <module>
  File "Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38-x86_64-linux-gnu.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: Not a directory, Trying '_raw_ecb.abi3.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: Not a directory, Trying '_raw_ecb.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: Not a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 525, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.kfxdedrm", line 17, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/_mode_ecb.py", line 35, in <module>
  File "Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38-x86_64-linux-gnu.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-x86_64-linux-gnu.so: cannot open shared object file: Not a directory, Trying '_raw_ecb.abi3.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so: cannot open shared object file: Not a directory, Trying '_raw_ecb.so': /opt/calibre/lib/calibre-extensions/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so: cannot open shared object file: Not a directory
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2313, resource id: 39846804, major code: 40 (TranslateCoords), minor code: 0
[2.91] splash screen hidden
[2.91] Started up in 2.91 seconds with 243 books
Added Aristotle: The Complete Works to db in: 0.1
Added 1 books in 0.7 seconds`
```
</details>

**Comment by ElleKayEm** [comment]
This is beyond me.  But I would have thought your python setup wouldn't matter because calibre has its own embedded python.  Try updating to the latest calibre.  Make sure this copy is from or for your E-Ink Kindle and that its serial number is entered correctly.

**Comment by nadres** [comment]
Thank you for your response!
I did as suggested, updated to Calibre 5.12.0 and it worked perfectly!
