### ISSUE TITLE
Can´t remove DRM for Kindle e-book

### ISSUE THREAD

**Issue by Edwanlima** [apprenticeharper/DeDRM_tools#1570]
calibre Log de Debug
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[0.95] main UI initialized...
[0.95] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\edwan\OneDrive\Documents\My Kindle Content\B0871WYMNZ_EBOK\B0871WYMNZ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\edwan\AppData\Local\Temp\calibre_d74c8e47\5rhze98w.kfx-zip
DeDRM v7.1.0: Trying to decrypt 5rhze98w.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 5rhze98w
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.81deb18f-74dd-46a6-bae0-5a68a86d0f46.voucher
KFX DRM voucher successfully decrypted
DeDRM v7.1.0: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\edwan\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\edwan\AppData\Local\Amazon\Kindle\storage\.kinf2018
[8.19] splash screen hidden
[8.19] Started up in 8.19 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"r\x7fMz\xfa\xee\xe3s?'\xd6ob\x82\x03M|\xf2\\\x9f\x19:\xef\xdb\xbdN\xc1\x82\xcem\x8b\x1d", b'C:\\Users\\edwan\\OneDrive\\Documents\\My Kindle Content\\B0871WYMNZ_EBOK\\B0871WYMNZ_EBOK.azw']
Decrypted key file using IDString '1250582550' and UserName 'edwan'
DeDRM v7.1.0: Found 1 new key
Decrypting KFX-ZIP ebook: 5rhze98w
Got DSN key from database default_key_1
Found 1 keys to try after 4.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.81deb18f-74dd-46a6-bae0-5a68a86d0f46.voucher
KFX DRM voucher successfully decrypted
DeDRM v7.1.0: Ultimately failed to decrypt after 4.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\edwan\AppData\Local\Temp\calibre_d74c8e47\5rhze98w.kfx-zip
Processing container: B0871WYMNZ_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\edwan\AppData\Local\Temp\calibre_d74c8e47\cwim6r6b_add_books\0\B0871WYMNZ_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 88, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 4.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0871WYMNZ_EBOK.azw has DRM and Added MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo to db in: 2.0
Added 1 books in 6.9 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment]
As it says in the log:

> This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by Edwanlima** [comment]
I Bought the book, anda now I have this error message: 
calibre, version 5.12.0
ERRO: Carregamento do livro falhou: Falha ao abrir o livro em C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx. Clique em "Mostrar detalhes" para mais informações.

Failed to convert book: C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx with error:
KFX metadata reader (from KFX Input) activated for C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx
DeDRM v7.1.0: Trying to decrypt METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx
Unknown booktype kfx. Passing back to calibre unchanged
InputFormatPlugin: KFX Input running
on C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx
Software versions: KFX Input 1.36.0, calibre 5.12 [64bit], Windows-10-10.0.19041
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx
Processing container: C:\Users\edwan\Biblioteca do calibre\Michel Deunizio\METODOS AGEIS_ METODOS AGEIS_ SCRUM (50)\METODOS AGEIS_ METODOS AGEIS_ S - Michel Deunizio.kfx
kfxgen version: 20.12.238.0
Features: CanonicalFormat-2, kfxgen.positionMaps-2, max_id-787, yj_custom_word_iterator-1, yj_fixed_layout-1, yj_graphical_highlights-1, yj_pdf_support-1, yj_textbook-1
Metadata: ASIN=B0871WYMNZ, asset_id=CR!WCPDANJE5N3G56G0MM19J1NRVZTG, author="Deunizio, Michel", book_id=ez8vOKiUTnKoKx3E-uotIQ0, book_orientation_lock=none, cde_content_type=EBOK, content_id=B0871WYMNZ, cover_image=691x1080, creator_version=1.37.2.0, file_creator=KC, graphical_highlights=1, is_sample=False, issue_date=2020-04-12, language=pt, multipage_selection=disabled, pages=86, reading_orders=1, selection=enabled, title="MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo", user_visible_labeling=page_exclusive, yj_fixed_layout=1, yj_textbook=1
WARNING: This book contains PDF content, which can be extracted using the KFX Input plugin CLI.
ERROR: This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.
Converting book to EPUB 3
Format is fixed layout print replica
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 117, in convert
Exception: This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 867, in viewer_main
  File "calibre\srv\render_book.py", line 858, in render_for_viewer
  File "calibre\srv\render_book.py", line 835, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre_plugins.kfx_input.__init__", line 128, in convert
calibre.ebooks.conversion.ConversionUserFeedBack: {"msg": "<b>Cannot convert ?</b><br><br>Exception('This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.')", "level": "error", "det_msg": "", "title": "KFX conversion failed"}

**Comment by Edwanlima** [comment]
Here is the log:

calibre Log de Debug
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[0.95] main UI initialized...
[0.95] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\edwan\OneDrive\Documents\My Kindle Content\B0871WYMNZ_EBOK\B0871WYMNZ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\im6ypf3l.kfx-zip
DeDRM v7.1.0: Trying to decrypt im6ypf3l.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: im6ypf3l
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.81deb18f-74dd-46a6-bae0-5a68a86d0f46.voucher
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B0871WYMNZ_EBOK.azw
Decrypting KFX DRMION: CR!VT81JW9MA10ANFBCK3MV2F9462NR.azw.res
Decrypting KFX DRMION: CR!ZSKRP9WNBH69F0S72MEC0V1VWG22.azw.res
Decryption succeeded after 0.1 seconds
DeDRM v7.1.0: Finished after 0.2 seconds
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\j8akw1dm.kfx-zip
Processing container: B0871WYMNZ_EBOK.azw
Processing container: CR!Q0HD78XCV14455EQEN0GS23Q5QM6.azw.md
Processing container: CR!VT81JW9MA10ANFBCK3MV2F9462NR.azw.res
Processing container: CR!ZSKRP9WNBH69F0S72MEC0V1VWG22.azw.res
[10.09] splash screen hidden
[10.09] Started up in 10.09 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xf6f5,3\x19E\xf5\xe3 ?\t0\x88\xcb\xd9\xbb\xbb\xda\xa9\x18P\xc2(\x0fI\x9e\x01\xb7r\xe4y', b'C:\\Users\\edwan\\OneDrive\\Documents\\My Kindle Content\\B0871WYMNZ_EBOK\\B0871WYMNZ_EBOK.azw']
kfxgen version: 20.12.238.0
Features: CanonicalFormat-2, kfxgen.positionMaps-2, max_id-787, yj_custom_word_iterator-1, yj_fixed_layout-1, yj_graphical_highlights-1, yj_pdf_support-1, yj_textbook-1
Metadata: ASIN=B0871WYMNZ, asset_id=CR!WCPDANJE5N3G56G0MM19J1NRVZTG, author="Deunizio, Michel", book_id=ez8vOKiUTnKoKx3E-uotIQ0, book_orientation_lock=none, cde_content_type=EBOK, content_id=B0871WYMNZ, cover_image=691x1080, creator_version=1.37.2.0, file_creator=KC, graphical_highlights=1, is_sample=False, issue_date=2020-04-12, language=pt, multipage_selection=disabled, pages=86, reading_orders=1, selection=enabled, title="MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo", user_visible_labeling=page_exclusive, yj_fixed_layout=1, yj_textbook=1
Package KFX (from KFX Input): Imported as C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\6htbey_j.kfx
KFX metadata reader (from KFX Input) activated for C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\_qmqf07r_add_books\0\B0871WYAdded MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo to db in: 1.7
Added 1 books in 4.5 seconds
Worker Launch took: 0.03 seconds
Job: 0 Converter livro 1 de 1 (MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo) finished
Converter livro 1 de 1 (MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo)

	DeDRM v7.1.0: Trying to decrypt _f51tkj1.kfx
	Unknown booktype kfx. Passing back to calibre unchanged
	Conversion options changed from defaults:

	  cover: 'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_ff9am_tp\\czqio6aq.jpeg'

	  pdf_sans_family: 'MS Shell Dlg 2'

	  pdf_serif_family: 'MS Shell Dlg 2'

	  output_profile: 'generic_eink'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_ff9am_tp\\8oqbfe4v.opf'

	Resolved conversion options

	calibre version: 5.12.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_ff9am_tp\\czqio6aq.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001E8B24F85E0>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001E8B24F8940>,

	 'page_breaks_before': '/',

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier',

	 'pdf_mono_font_size': 16,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'MS Shell Dlg 2',

	 'pdf_serif_family': 'MS Shell Dlg 2',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\edwan\\AppData\\Local\\Temp\\calibre_ff9am_tp\\8oqbfe4v.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	DeDRM v7.1.0: Trying to decrypt _f51tkj1.kfx
	Unknown booktype kfx. Passing back to calibre unchanged
	InputFormatPlugin: KFX Input running

	on C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\_f51tkj1.kfx

	Software versions: KFX Input 1.36.0, calibre 5.12 [64bit], Windows-10-10.0.19041

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\_f51tkj1.kfx

	Processing container: C:\Users\edwan\AppData\Local\Temp\calibre_ff9am_tp\_f51tkj1.kfx

	kfxgen version: 20.12.238.0

	Features: CanonicalFormat-2, kfxgen.positionMaps-2, max_id-787, yj_custom_word_iterator-1, yj_fixed_layout-1, yj_graphical_highlights-1, yj_pdf_support-1, yj_textbook-1

	Metadata: ASIN=B0871WYMNZ, asset_id=CR!WCPDANJE5N3G56G0MM19J1NRVZTG, author="Deunizio, Michel", book_id=ez8vOKiUTnKoKx3E-uotIQ0, book_orientation_lock=none, cde_content_type=EBOK, content_id=B0871WYMNZ, cover_image=691x1080, creator_version=1.37.2.0, file_creator=KC, graphical_highlights=1, is_sample=False, issue_date=2020-04-12, language=pt, multipage_selection=disabled, pages=86, reading_orders=1, selection=enabled, title="MÉTODOS ÁGEIS: MÉTODOS ÁGEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias ágeis utilizadas por grandes empresas para criar o produto certo", user_visible_labeling=page_exclusive, yj_fixed_layout=1, yj_textbook=1

	WARNING: This book contains PDF content, which can be extracted using the KFX Input plugin CLI.

	ERROR: This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.

	Converting book to EPUB 3

	Format is fixed layout print replica

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 117, in convert

	Exception: This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 128, in convert

	calibre.ebooks.conversion.ConversionUserFeedBack: {"msg": "<b>Cannot convert M\u00c9TODOS \u00c1GEIS: M\u00c9TODOS \u00c1GEIS: SCRUM | KANBAN | Um livro com mais de 20 metodologias \u00e1geis utilizadas por grandes empresas para criar o produto certo</b><br><br>Exception('This book has a layout that is incompatible with calibre. For best results use the KFX Input plugin CLI for conversion.')", "level": "error", "det_msg": "", "title": "KFX conversion failed"}

**Comment by ElleKayEm** [comment]
DRM removal is successful.  But there are issues with conversion.  I'd recommend disabling KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

If the older format turns out to be AZW4, I recommend using the Kindle Unpack plugin to extract the PDF.
