### ISSUE TITLE
trouble getting the plugin to work :/ 

### ISSUE THREAD

**Issue by iifar** [apprenticeharper/DeDRM_tools#1573]
calibre, version 5.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\Rafii\\Downloads\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.12  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\Rafii\\Downloads\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.1.0.zip.  Load DeDRM_plugin.zip.
