### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by nuhmey** [apprenticeharper/DeDRM_tools#1576]
I updated Calibre to 5.12 (64bit) and downloaded DeDRM 7.10. I get an invalid syntax error when trying to install it.

SyntaxError:invalid syntax (calibre_plugins.dedrm._init_. line 169)

calibre, version 5.12.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Make sure you're trying with 7.1.0.  Looks like this is 6.8.1 or earlier.

**Comment by nuhmey** [comment]
It was. Stupid windows opened up in the wrong folder and I wasn't paying attention. ><

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
