### ISSUE TITLE
Top level _init_.py not found

### ISSUE THREAD

**Issue by Sthairson** [apprenticeharper/DeDRM_tools#1582]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
When installing the plugin with "load plugin from file" i get the InvalidPlugin error.

## Log
<details><summary>InvalidPlugin exception</summary>

```log
calibre, version 5.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '<Path replaced>\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.12 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 0, 3)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '<Path replaced>\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

```
</details>

**Comment by Sthairson** [comment]
Nevermind should learn to read a manual...

**Comment by ElleKayEm** [comment]
For anyone who has the same issue:  Unzip DeDRM_tools_7.1.0.zip.  Load DeDRM_plugin.zip.
