### ISSUE TITLE
Cannot remove DRM from Kindle Book

### ISSUE THREAD

**Issue by phill451** [apprenticeharper/DeDRM_tools#1585]
I have use both Calibre 5.23 and 4.23 with approprite version of DeDRM tool. I cannot remove DRM in either versions. Book downloaded using Kindle version 1.30 (59056) to my 32 bit widows 10 PC. Below is log from Calibre 4.23 and DRM tool 6.8.1

calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Obok DeDRM (6, 7, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.9763837638 x 96.0945812808
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[2.95] splash screen shown
[2.95] Initializing db...
[3.01] db initialized
[3.01] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.2 obok::action_err.py - loading translations
[7.72] main UI initialized...
[7.72] Hiding splash screen
[11.56] splash screen hidden
[11.56] Started up in 11.56 seconds with 16 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xbb\xa8\xc0\xa8\x11\x84\xf1\x0e#?\xf1\xdc\xb0\xfb\xe3\x1d\xfey,\x03\xb1\xc1U\xd7n\x01\xc4\xc8m\xd2g?', 'C:\\Users\\Phill\\Documents\\My Kindle Content\\B008J58CLW_EBOK\\B008J58CLW_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing C:\Users\Phill\Documents\My Kindle Content\B008J58CLW_EBOK\B008J58CLW_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 13 file(s) as C:\Users\Phill\AppData\Local\Temp\calibre_04vi5p\bap82r.kfx-zip
DeDRM v6.8.0: Trying to decrypt bap82r.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: bap82r
Found 0 keys to try after 0.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cc11445c-d63f-4459-ba77-df0c5552f01d.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 1.3 seconds
searching for kinfoFiles in C:\Users\Phill\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Phill\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '942549858' and UserName '5068696c6c'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: bap82r
Got DSN key from database default_key_1
Found 1 keys to try after 19.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cc11445c-d63f-4459-ba77-df0c5552f01d.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 19.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 19.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.36.0: Packaging C:\Users\Phill\AppData\Local\Temp\calibre_04vi5p\bap82r.kfx-zip
Processing container: B008J58CLW_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
KFXDRMError: Book container B008J58CLW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Phill\AppData\Local\Temp\calibre_04vi5p\lctscp_add_books\0\B008J58CLW_EBOK.kfx-zip
Added Spanish Grammar Drills to db in: 2.7
Added 1 books in 32.2 seconds

**Comment by ElleKayEm** [comment]
Either go back to Kindle PC 1.26 or earlier, or disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
