### ISSUE TITLE
kindle 1.30 on macOS 11.2.2 --> calibre 5.12 + tools 7.1.0 can't find key, calibre 4.23.0 + tools 6.8.1 can

### ISSUE THREAD

**Issue by sahfnwoadi** [apprenticeharper/DeDRM_tools#1587]
## CheckList

- [x] `The Title` and The `Log Title` are set correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

kindle 1.30 on macOS 11.2.2 --> calibre 5.12 + tools 7.1.0 can't find key, calibre 4.23.0 + tools 6.8.1 can

### OS: macOS 11.2.2 (M1 Mac mini)

Using Kindle for Mac 1.30 and a new install of Calibre 5.12 and tools 7.1.0, the DeDRM plugin doesn't initialize itself correctly on first import and never finds the kindle key. I tried on multiple books.

I tried deregistering and reinstalling kindle program as outlined here: https://apprenticealf.wordpress.com. This did not help.

I installed calibre 4.23.0 and tools 6.8.1 on the same machine, alongside 5, and the plugin initializes itself correctly on first import, finds and loads the key it needs, and works as expected.

When I switched back to calibre 5.12, I had to reinstall tools plugin 7.1.0 (seems the two version share the same configuration folder). After reinstalling, the key was already present in the configuration for the plugin, and when I tried to import a kindle book, it worked. I then tried each of three books that had failed, and each imported successfully, so looks like it was not an issue with the books themselves.

Has anyone else run into this issue? If not, is there anything I can do to help troubleshoot?

Thanks!

## Log
<details>
<summary>Single attempt to import kindle book</summary>

```
calibre Debug log
calibre 5.12  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
calibre 5.12  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 36, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 36, 0) && KFX metadata reader (from KFX Input) (1, 36, 0) && KFX Input (1, 36, 0) && Set KFX metadata (from KFX Output) (1, 49, 0) && KFX Output (1, 49, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 92.0000013817014 x 91.00000136668288
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
[0.92] main UI initialized...
[0.92] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.36.0: Importing /Users/<user>/Desktop/B000FCK65W_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B000FCK65W_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Tree Grows in Brooklyn (Harper Perennial Deluxe Editions)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/<user>/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'<user>'  on file  /Users/<user>/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'b13dd2599c8b'
Decrypted key file using IDString 'b13dd2599c8b' and UserName '<user>'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Tree Grows in Brooklyn (Harper Perennial Deluxe Editions)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[11.41] splash screen hidden
[11.41] Started up in 11.41 seconds with 671 books
Added A Tree Grows in Brooklyn (Harper Perennial Deluxe Editions) to db in: 0.0
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 1 books in 1.2 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Looks like you have disabled KFX downloads, right?  Are the books all azw3 once decrypted with the older versions of calibre & DeDRM?

**Comment by sahfnwoadi** [comment]
that is correct, and they are azw3 once they are decrypted. The decryption works on calibre 5 with tools plugin 7.1.0 as well, once the key has been added to the configuration by calibre 4.23.0/tools 6.8.1. It is just getting the key added to the configuration.

This is probably why I didn't have any problem on my other Mac, an intel MacBook pro. It works just fine once the key is in place, and so upgrading from calibre 4 to 5 and tools 6.8.1 to the 7 series there had no issues because the key was already in place. I could try removing all the keys there and see if it has the same problem finding the key. It is an intel Mac running macOS 11.2.2.

**Comment by sahfnwoadi** [comment]
I have the capacity to help troubleshoot in the code, also, if you can point me in the right direction.

**Comment by ElleKayEm** [comment]
Give @apprenticeharper an email at ApprenticeHarper@gmail.com about this issue.  It seems like it may be something specific to the M1 Mac mini.

**Comment by sahfnwoadi** [comment]
OK, I'll send an email.

I can reproduce the problem on my intel Macbook Pro (calibre 5.12, plugin 7.1.0, macOS 11.2.2), though, as well.  There also, I removed all Kindle for Mac and PC Keys in plugin config, closed calibre, re-opened it, and tried to import a book - DRM remained. Then I reloaded the keys that had been there previously and that same file was imported successfully.

So it could just be Big Sur-related, not specific to M1. I looked over kindlekey.py, it seems straightforward enough and well-commented if that is where this is all happening. With a bit of guidance on how to run it (just run the file with system python?), I could do some testing to try to nail down what is going on.

**Comment by ElleKayEm** [comment]
Ok, I'm pretty sure I've seen some say they were fine with Big Sur on 7.1.0, others need 6.8.1.  When Big Sur first came out, there were issues with 6.8.0 and 6.8.1 was put out specifically to fix that.  But something still needs work with DeDRM 7/Python 3 version.

**Comment by Redmattski** [comment]
This issue is also occurring for Calibre 5.12 and tools 7.1.0 on Arch Linux, with no kindle key found on the Kindle for PC application.

**Comment by ElleKayEm** [comment]
It is tricky to get things working on Linux setups.  I'm not sure what is required now for DeDRM to automatically find the key.  One workaround is to temporarily install Windows calibre with DeDRM where you have Kindle for PC.  Save the key and import into Linux calibre.
