### ISSUE TITLE
DeDRM fails to remove the DRM of an ADE-ebook

### ISSUE THREAD

**Issue by jonaskor** [apprenticeharper/DeDRM_tools#1594]
DeDRM fails to remove the DRM of an ADE encrypted ebook. Anyone can tell me why?

Windows 10 / Adobe Digital Editions 4.5.11 / Calibre 5.12.0 / DeDRM 7.1.0

> calibre Fehlerdiagnoseprotokoll
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
calibre 5.12 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 131.09677419354838 x 131.3793103448276
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.55] splash screen shown
[0.55] Initializing db...
[0.55] db initialized
[0.55] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
[1.38] main UI initialized...
[1.38] Hiding splash screen
Starting QuickView
Failed to check for plugin update: Module use of python27.dll conflicts with this version of Python.
DeDRM v7.1.0: Trying to decrypt Souverän investieren.epub
DeDRM v7.1.0: Verifying zip archive integrity
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 642, in run
  File "calibre_plugins.dedrm.__init__", line 219, in ePubDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ignobleepub", line 188, in <module>
  File "calibre_plugins.dedrm.ignobleepub", line 182, in _load_crypto
  File "calibre_plugins.dedrm.ignobleepub", line 118, in _load_crypto_libcrypto
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
[4.22] splash screen hidden
[4.22] Started up in 4.22 seconds with 25 books
Added Souverän investieren to db in: 0.1
Added 1 books in 0.8 secondsTraceback (most recent call last):
  File "calibre\gui2\ui.py", line 134, in __init__
  File "calibre\gui2\ui.py", line 152, in init_iaction
  File "calibre\customize\__init__.py", line 616, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.obok.obok", line 273, in <module>
  File "calibre_plugins.obok_dedrm.obok.obok", line 267, in _load_crypto
  File "calibre_plugins.obok_dedrm.obok.obok", line 205, in _load_crypto_libcrypto
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung

**Comment by jonaskor** [comment]
Problem solved!
The error only came up while I still had calibre 4.8.0 installed (couldn't be uninstalled in the update process to v5.12 because the msi-file was missing. Redownloaded the file (calibre-64bit-4.8.0.msi) and uninstalled 4.8 successfully, now DeDRM is running fine!
