### ISSUE TITLE
Fail on removing Kindle DRM

### ISSUE THREAD

**Issue by ImBadBrainz** [apprenticeharper/DeDRM_tools#1595]
Attempting to remove DRM from a Kindle book purchased yesterday, and downloaded from Amazon to my Dell/Win10 laptop. Running Calibre 5.13. So far, no luck. Suggestions?

calibre Debug log
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Integration status: False
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Goodreads More Tags (1, 2, 1) && KindleUnpack - The Plugin (0, 83, 0) && Library Codes (1, 0, 50) && Obok DeDRM (7, 1, 0) && Overdrive Link (2, 45, 0)
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Goodreads More Tags (1, 2, 1) && KindleUnpack - The Plugin (0, 83, 0) && Library Codes (1, 0, 50) && Obok DeDRM (7, 1, 0) && Overdrive Link (2, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 96.0 x 96.0
physicalDpi: 110.96245733788396 x 110.83636363636363
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.94] main UI initialized...
[1.94] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Stress Less, Accomplish More.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Stress Less, Accomplish More
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\jabbr\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Integration status: False
[5.70] splash screen hidden
[5.70] Started up in 5.70 seconds with 1496 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x9f\x1d.\xed\xf3\x9fh\xd3sl\xd1\xbc\xd9g\xc2\xeb"\x9a\xd5&\x1b\xbe?1(\xd0\xd0wG\xe4\xb5<', b'C:\\Users\\jabbr\\Downloads\\Stress Less, Accomplish More.azw3']
Added Stress Less, Accomplish More to db in: 0.1
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
If you chose an E-ink Kindle (not a Fire) for the device, you need to enter the Kindle's serial number into DeDRM's customization.
