### ISSUE TITLE
"DeDRM v7.1.0: Ultimately failed to decrypt"

### ISSUE THREAD

**Issue by git-rzanelli** [apprenticeharper/DeDRM_tools#1596]
Kindle 4 Mac v1.30.0
Calibre v5.13
DeDRM tools v7.1.0

Import failed with error:
Exception: Failed to decrypt KFX DRM voucher with any key

So deleted book from Kindle 4 Mac and re-downloaded book after turning off support for KFX files:
(chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test) per https://www.mobileread.com/forums/showthread.php?t=283371

Note: After change above, Kindle 4 Mac crashed attempting to read book until execution permissions were restored.

Added book while running Calibre in debug mode (calibre-debug -g) and got this output:

calibre 5.13  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000165954353 x 110.50000165954353
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.05] main UI initialized...
[1.05] Hiding splash screen
Starting QuickView
[1.29] splash screen hidden
[1.29] Started up in 1.29 seconds with 3 books
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing /Volumes/home/Renzo/Files/Amazon e-books/B08B3G1H76_EBOK/B08B3G1H76_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B08B3G1H76_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: How To Do The Work: Recognise Your Patterns, Heal from Your Past, and Create Your Self
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/rzanelli/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'rzanelli'  on file  /Users/rzanelli/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c5a6adcd0ce3'
Decrypted key file using IDString 'c5a6adcd0ce3' and UserName 'rzanelli'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: How To Do The Work: Recognise Your Patterns, Heal from Your Past, and Create Your Self
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added How To Do The Work: Recognise Your Patterns, Heal from Your Past, and Create Your Self to db in: 0.1
Added 1 books in 1.6 seconds

**Comment by git-rzanelli** [comment]
Worked with Calibre 4.23 and DeDRM 6.8.1.
