### ISSUE TITLE
macOS BigSur: code signature in (/usr/local/lib/libcrypto.dylib) not valid...have different Team IDs

### ISSUE THREAD

**Issue by AG7GN** [apprenticeharper/DeDRM_tools#1597]
## code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
DeDRM installed fine, but when I double-click on the plugin to configure it, an __ERROR: Unhandled Exception__ window appears. Text  is in the Log below.

## Log
<details><summary>ERROR: Unhandled Exception</summary>

```calibre, version 5.13.0
ERROR: Unhandled exception: <b>OSError</b>:dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs

calibre 5.13  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 289, in double_clicked
  File "calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "calibre/customize/__init__.py", line 158, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 654, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "ctypes/__init__.py", line 373, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
```
</details>

**Comment by RobertoD91** [comment]
similar issue

```
calibre, version 5.14.0
ERRORE: Eccezione non gestita: <b>OSError</b>:dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

calibre 5.14  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 292, in customize_plugin
  File "calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "calibre/customize/__init__.py", line 158, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 656, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "ctypes/__init__.py", line 373, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

```

**Comment by RobertoD91** [comment]
use codesign (included in command line tools for developer) to check signing
```bash
$ codesign -d --verbose=4 /usr/local/lib/libcrypto.dylib
/usr/local/lib/libcrypto.dylib: code object is not signed at all
```
my version is not signed, so graphical app can't use it

**Comment by RobertoD91** [comment]
My version of libcrypto.dylib was installed by force linking openssl with brew

check if is installed by brew:
```bash
ls -l /usr/local/lib/libcrypto.dylib
```
if something like `-> /usr/local/opt/openssl@1.1/lib/` appear you can unlink with `brew unlink openssl`

Another workaround is to move away `/usr/local/lib/libcrypto.dylib`, run plugin configuration interface and then restore `/usr/local/lib/libcrypto.dylib`.

**Comment by davissorenson** [comment]
Edit: Feel free to ignore, [NoDRM's DeDRM_tools](https://github.com/noDRM/DeDRM_tools) works fine on the latest version of macOS.

On macOS 11 and newer, it seems that shared libs [are not accessible directly on the filesystem](https://stackoverflow.com/questions/73376007/where-are-the-shared-libs-in-macos). Therefore unlinking OpenSSL no longer helps, as that means that there is no `libcrypto.dylib` to use at all. I haven't found a solution to this, but I did try extracting libcrypto from the dyld shared cache. This did not work, as the extracted library was also unsigned. I expect that libcrypto just needs to be loaded in a different way in DeDRM to get it to work with modern versions of macOS, but I don't know how yet.

**Comment by ElleKayEm** [comment]
Since you're in a really old issue...What versions of calibre and DeDRM?

**Comment by davissorenson** [comment]
Switching to [NoDRM's DeDRM_tools](https://github.com/noDRM/DeDRM_tools) fixed my issue.
