### ISSUE TITLE
Fail to remove DRM

### ISSUE THREAD

**Issue by RafaelGuilardi** [apprenticeharper/DeDRM_tools#1598]
calibre Log de Debug
calibre 5.13  embedded-python: True is64bit: True
Linux-5.8.0-44-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-44-generic', '#50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021')
Python 3.8.5
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.13  embedded-python: True is64bit: True
Linux-5.8.0-44-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-44-generic', '#50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021')
Python 3.8.5
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.29] splash screen shown
[0.29] Initializing db...
[0.43] db initialized
[0.43] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[2.34] main UI initialized...
[2.34] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Pflege Heute Kompaktwissen (German Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
[12.21] splash screen hidden
[12.21] Started up in 12.21 seconds with 2 books
['zenity', '--modal', '--file-selection', '--title=Selecione livros', '--separator=\n', '--attach=56623127', '--filename=/home/rafael/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=Livros | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=livros EPUB | *.epub *.kepub', '--file-filter=Livros para Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Livros PDF | *.pdf *.azw4', '--file-filter=Livros HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Livros LIT | *.lit', '--file-filter=Livros TXT | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=HQs | *.cbz *.cbr *.cbc', '--file-filter=Arquivos | *.zip *.rar', '--file-filter=Arquivos de processador de texto | *.odt *.doc *.docx', '--file-filter=Todos os arquivos | *', '--multiple']
Decrypting Kindle Format 8 ebook: Pflege Heute Kompaktwissen (German Edition)
Found 2 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.6 seconds
DeDRM v7.1.0: Exception when getting default Kindle Key after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 555, in KindleMobiDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: 'wine'
DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Pflege Heute Kompaktwissen (German Edition) to db in: 2.2
Added 1 books in 3.9 seconds

**Comment by ElleKayEm** [comment]
If that's for an E-ink Kindle (not a Fire), then enter the Kindle's serial number into DeDRM's customization.

**Comment by RafaelGuilardi** [comment]
It is a Fire. Worked with other book. But not with this one...

**Comment by ElleKayEm** [comment]
Other book must have already been DRM-free.  If you don't have an E-ink Kindle on your account, then the only other option is Kindle for PC/Mac.  That's a bit tricky with Linux.
