### ISSUE TITLE
Failed to remove DRM from Kindle .azw (no problem with .azw3 bought at same time)

### ISSUE THREAD

**Issue by burtonjw** [apprenticeharper/DeDRM_tools#1600]
Logfile attached.  Running calibre 5.13, DeDRM 7.1.0 on MacOS 14.  Grateful for any help or advice, particularly including "this is known not to work, don't waste your time."  Thanks!

--
macOS-10.14.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Tue Nov 10 00:07:31 PST 2020; root:xnu-4903.278.51~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
Using calibre Qt style: True
[0.00] Starting up...
[0.10] Showing splash screen...
[0.86] splash screen shown
[0.86] Initializing db...
[1.22] db initialized
[1.22] Constructing main UI...
Failed to load cached store: ozon_ru
[2.81] main UI initialized...
[2.81] Hiding splash screen
Starting QuickView
objc[43482]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa52a23f0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1333b4f50). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.37.0: Importing /Users/joshua/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B0028Y475A_EBOK/B0028Y475A_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B0028Y475A_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting Topaz ebook: Entering the High Holy Days: A Complete Guide to the History, Prayers and Themes
Found 4 keys to try after 0.1 seconds
Trying: b'9/KN5a7d'
DeDRM v7.1.0: Failed to decrypt with error: ord() expected string of length 1, but int found
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/joshua/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
trying username  b'joshua'  on file  /Users/joshua/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
trying IDString: b'0d85c3d4f701'
Decrypted key file using IDString '0d85c3d4f701' and UserName 'joshua'
DeDRM v7.1.0: Found 1 new key
Decrypting Topaz ebook: Entering the High Holy Days: A Complete Guide to the History, Prayers and Themes
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.4 seconds
Trying: b'fA4pMLCj'
DeDRM v7.1.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.topazextract", line 352, in processBook
    bookKeys+=decryptDkeyRecords(data,pid)
  File "calibre_plugins.dedrm.topazextract", line 192, in decryptDkeyRecords
    key = decryptDkeyRecord(data[1:length+1],PID)
  File "calibre_plugins.dedrm.topazextract", line 174, in decryptDkeyRecord
    record = decryptRecord(data,PID)
  File "calibre_plugins.dedrm.topazextract", line 169, in decryptRecord
    ctx = topazCryptoInit(PID)
  File "calibre_plugins.dedrm.topazextract", line 144, in topazCryptoInit
    return Topaz_Cipher().ctx_init(key)
  File "calibre_plugins.dedrm.alfcrypto", line 211, in ctx_init
    keyByte = ord(keyChar)
TypeError: ord() expected string of length 1, but int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 289, in get_metadata
  File "calibre/ebooks/metadata/mobi.py", line 491, in get_metadata
  File "calibre/ebooks/metadata/topaz.py", line 378, in get_metadata
  File "calibre/ebooks/metadata/topaz.py", line 114, in __init__
ValueError: '/Users/joshua/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B0028Y475A_EBOK/B0028Y475A_EBOK.azw': Invalid Topaz format - no metadata record
[20.22] splash screen hidden
[20.23] Started up in 20.23 seconds with 5951 books
Added B0028Y475A EBOK to db in: 0.0
Added 1 books in 1.1 seconds

**Comment by burtonjw** [comment]
Reverted to calibre 4.23 and DeDRM 6.8.1, and now the file decrypts into an HTMLZ without incident.  This appears to be a DeDRM reversion in the new py3 plugin.  File and Kindle key attached; hope my book will be helpful in further improving this splendid plugin.
[burtonjw.zip](https://github.com/apprenticeharper/DeDRM_tools/files/6135966/burtonjw.zip)

**Comment by ElleKayEm** [comment]
Send @apprenticeharper an email to make sure they see this at apprenticeharper@gmail.com.

**Comment by ableeker** [comment]
There was indeed an issue caused by the conversion to Python 3. I believe I've fixed the issue, because I was able to decrypt the ebook with the key file, and add it to Calibre without DRM. I've submitted pull request #1615 with the fix.
