### ISSUE TITLE
Failed DRM for an KU Indic book 

### ISSUE THREAD

**Issue by nygiants** [apprenticeharper/DeDRM_tools#1601]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Been trying to DeDRM this book gotten via KU. Unable to download the book via USB transfer option so the only method would be to use K4PC. Unable to use older versions of Kindle, to download this book. 

Unable to download the book if 'renderer-test.exe' is renamed to 'renderer-test.xxx'

## Log
<details>calibre, version 5.7.2
ERROR: Loading book failed: Failed to open the book at C:\Users\selva\Calibre Library\Unknown\B08R2PQP5S EBOK (3)\B08R2PQP5S EBOK - Unknown.azw. Click "Show details" for more info.

Failed to convert book: C:\Users\selva\Calibre Library\Unknown\B08R2PQP5S EBOK (3)\B08R2PQP5S EBOK - Unknown.azw with error:
DeDRM v7.1.0: Trying to decrypt B08R2PQP5S EBOK - Unknown.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\selva\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\selva\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\selva\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3499696657' and UserName 'selva'
Decrypted key file using IDString '3499696657' and UserName 'selva'
DeDRM v7.1.0: Found 2 new keys
DeDRM v7.1.0: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\selva\Calibre Library\Unknown\B08R2PQP5S EBOK (3)\B08R2PQP5S EBOK - Unknown.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 285, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 865, in viewer_main
  File "calibre\srv\render_book.py", line 856, in render_for_viewer
  File "calibre\srv\render_book.py", line 833, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
</details>

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by nygiants** [comment]
Thanks Elle.

I don't mind purchasing if DeDRMing Indic books would work for sure.

**Comment by ElleKayEm** [comment]
I am not sure.  If you can download with Kindle for PC 1.26 or earlier, then it may be possible.  Kindle for PC which is used for download and calibre with DeDRM need to be on the same machine and user.  And do not move the main book file out of its original folder structure.  (KFX Input needs to be able to find related files.)  If you can download a sample instead of the KU copy, you could test that.  See if there is a "send a free sample" button beneath the buy buttons on the product page.

**Comment by nygiants** [comment]
Thanks again. I'll give that a shot.
