### ISSUE TITLE
can't make the plugin work

### ISSUE THREAD

**Issue by lcbrandao** [apprenticeharper/DeDRM_tools#1602]
Calibre version: 5.13
DeDRM version: 7.1.0

I import the book I purchased on amazon to my calibre library but when I try to visualize it it goes on error:

calibre, version 5.13.0
ERRO: Carregamento do livro falhou: Falha ao abrir o livro em C:\Users\lucia\Biblioteca do calibre\Desconhecido\CR!3DX3MMER1S683EA01YB3ZVVV81WJ.azw (8)\CR!3DX3MMER1S683EA01YB3ZVVV81WJ - Desconhecido.md. Clique em "Mostrar detalhes" para mais informações.

Failed to convert book: C:\Users\lucia\Biblioteca do calibre\Desconhecido\CR!3DX3MMER1S683EA01YB3ZVVV81WJ.azw (8)\CR!3DX3MMER1S683EA01YB3ZVVV81WJ - Desconhecido.md with error:
InputFormatPlugin: TXT Input running
on C:\Users\lucia\Biblioteca do calibre\Desconhecido\CR!3DX3MMER1S683EA01YB3ZVVV81WJ.azw (8)\CR!3DX3MMER1S683EA01YB3ZVVV81WJ - Desconhecido.md
File extension indicates particular formatting. Forcing formatting type to: markdown
Language not specified
Creator not specified
Building file list...
IgnoreFile("Could not read from file: C:\\Users\\lucia\\AppData\\Local\\calibre-cache\\ev2\\t\\c0-fuicl6he\\¬¶–]-ª½¨Ëèzæ~—Ò\x0bä_A\x1cóä×&}wÁÎìÛ‹s²>fb\x19%ósœ|§·R•nWœŸæ\x1f3pkÔ with error: [Errno 22] Invalid argument: 'C:\\\\Users\\\\lucia\\\\AppData\\\\Local\\\\calibre-cache\\\\ev2\\\\t\\\\c0-fuicl6he\\\\¬¶–]-ª½¨Ëèzæ~—Ò\\x0bä_A\\x1cóä×&}wÁÎìÛ‹s²>fb\\x19%ósœ|§·R•nWœŸæ\\x1f3pkÔ'")
IgnoreFile('Could not read from file: C:\\Users\\lucia\\AppData\\Local\\calibre-cache\\ev2\\t\\c0-fuicl6he\\ñD"‘   Y]Ü’þm\x1bX˜\x16 with error: [Errno 22] Invalid argument: \'C:\\\\Users\\\\lucia\\\\AppData\\\\Local\\\\calibre-cache\\\\ev2\\\\t\\\\c0-fuicl6he\\\\ñD"‘   Y]Ü’þm\\x1bX˜\\x16\'')
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 870, in viewer_main
  File "calibre\srv\render_book.py", line 861, in render_for_viewer
  File "calibre\srv\render_book.py", line 838, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\txt_input.py", line 287, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 84, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 145, in create_oebbook
  File "calibre\ebooks\html\input.py", line 252, in get_filelist
  File "calibre\ebooks\html\input.py", line 225, in traverse
  File "calibre\ebooks\html\input.py", line 111, in __init__
ValueError: embedded null character

-- 
I also cannot convert it to PDF.. I don't understand what went wrong or what I can do to fix it.

**Comment by ElleKayEm** [comment]
Let's see an import log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
