### ISSUE TITLE
[QUESTION] Title

### ISSUE THREAD

**Issue by Anienham** [apprenticeharper/DeDRM_tools#1603]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>tmpqzp1cs41.txt</summary>

```log
calibre Debug log
calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\stefb\\AppData\\Roaming\\calibre\\plugins\\Read MP3 AudioBook metadata.zip'
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Reading List (1, 7, 1) && Wiki Reader (2, 2, 1)
calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Reading List (1, 7, 1) && Wiki Reader (2, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.35820895522387
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.78] splash screen shown
[0.78] Initializing db...
[0.78] db initialized
[0.78] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt The Loneliest Cottage_ A Page-Turning Tale of Mystery, Adventure & Love (Alaskan Hearts Book 1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Loneliest Cottage: A Page-Turning Tale of Mystery, Adventure & Love (Alaskan Hearts Book 1)
Got DSN key from database default_key
Found 6 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 6 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\stefb\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\stefb\AppData\Local\Amazon\Kindle\storage\.kinf2018
[9.92] splash screen hidden
[9.92] Started up in 9.92 seconds with 35 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"M'5\xd7\xf2\x908\x96\xe1\xb5\x90\xbb.y6\x1dQ\xd8\x13i\xe2J\xfcf3\x07sH\x94\x02\xec\xe8", b'C:\\Users\\stefb\\OneDrive - Writing Board\\Documents\\My Kindle Content\\The Loneliest Cottage_ A Page-Turning Tale of Mystery, Adventure & Love (Alaskan Hearts Book 1).azw3']
Decrypted key file using IDString '2820058305' and UserName 'stefb'
DeDRM v7.1.0: Ultimately failed to decrypt after 5.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 6 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 5.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: 'C:\\Users\\stefb\\AppData\\Roaming\\calibre\\plugins\\Read MP3 AudioBook Traceback (most recent call last):
  File "calibre\customize\ui.py", line 703, in initialize_plugins
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.audiobookmetadatareader.__init__", line 8, in <module>
ModuleNotFoundError: No module named 'common'
Added The Loneliest Cottage: A Page-Turning Tale of Mystery, Adventure & Love (Alaskan Hearts Book 1) to db in: 1.1
Added 1 books in 7.1 seconds

```
</details>

**Comment by Anienham** [comment]
I figured it out. Wrong serial number and kindle version.

**Comment by ElleKayEm** [comment]
I was going to say that isn't a Kindle for PC book!  Glad you got it working.
