### ISSUE TITLE
Unable to install - Syntax error

### ISSUE THREAD

**Issue by mattcooperkay** [apprenticeharper/DeDRM_tools#1607]
Using the latest version of both the plugin and Calibre. Just getting a syntax error. Obok plugin installed without issue.

calibre, version 5.13.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Quality Check (1, 11, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Make sure you install version 7.1.0.  Looks like you're trying to install 6.8.x or earlier.  You don't have the 7.1.0 version of Obok either.

**Comment by mattcooperkay** [comment]
> Make sure you install version 7.1.0. Looks like you're trying to install 6.8.x or earlier. You don't have the 7.1.0 version of Obok either.

Y'know, I'd downloaded and installed this morning from DeDRM_tools_7.1.0.zip. I've just rebooted and redownloaded (DeDRM_tools_7.1.0 (1)) and now it works. Makes zero sense, but hey, it works now. Thanks.
