### ISSUE TITLE
Unable to remove DRM from AZW3 

### ISSUE THREAD

**Issue by tschube** [apprenticeharper/DeDRM_tools#1609]
Hi all, 
Not good with the programming side of things. I'm hoping someone can help me out. 

---

## Log
calibre Debug log
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 3.8.5
Windows: ('10', '10.0.16299', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 3.8.5
Windows: ('10', '10.0.16299', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
[1.34] main UI initialized...
[1.34] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt The Giver (Graphic Novel) by Lois Lowry, P. Craig Russell (z-lib.org).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Giver (Graphic Novel)
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\09465448\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[4.64] splash screen hidden
[4.64] Started up in 4.64 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'c\xeb\xc85\x1b\x0c\x95h\xa1\x12\x1c\xedJ\xf3\xcca\x99\xf9\n\x9a\x98\xf7\x18\x06\x8b\x07\x13\x9ft`\xfd\xf5', b'C:\\Users\\09465448\\Desktop\\The Giver (Graphic Novel) by Lois Lowry, P. Craig Russell (z-lib.org).azw3']
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded The Giver (Graphic Novel) to db in: 0.4
Added 1 books in 1.6 seconds
Worker Launch took: 0.01 seconds

</details>

**Comment by ElleKayEm** [comment]
If that's for an E-ink Kindle (not a Fire), you need to enter the Kindle's serial number into DeDRM's customization.
