### ISSUE TITLE
Can't install in Calibre 5.13

### ISSUE THREAD

**Issue by Karrrl** [apprenticeharper/DeDRM_tools#1611]
Hi,

I downloaded the 7.10 version, but i obtained this error:

calibre, version 5.13.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'D:\\Downloads\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'D:\\Downloads\\DeDRM_tools_7.1.0.zip' is invalid. It does not contain a top-level __init__.py file

Thanks for your attention,
C.

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.1.0.zip.  Load DeDRM_plugin.zip into calibre.
