### ISSUE TITLE
Unable to remove DRM from AZW

### ISSUE THREAD

**Issue by teamplay7** [apprenticeharper/DeDRM_tools#1612]
AMAZON

calibre Debug log
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.14671814671814 x 94.07407407407408
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[1.23] main UI initialized...
[1.23] Hiding splash screen
Starting QuickView
Failed to check for plugin update: Module use of python27.dll conflicts with this version of Python.
DeDRM v7.1.0: Trying to decrypt B07FCRKS9K_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 15, in <module>
  File "zipimport.py", line 259, in load_module
  File "C:\Users\Leo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\__init__.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\_mode_ccm.py", line 44, in <module>
ImportError: Module use of python27.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 525, in KindleMobiDecrypt
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.kfxdedrm", line 17, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ion", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\__init__.py", line 33, in <module>
  File "bypy-importer.py", line 203, in exec_module
  File "Crypto\Cipher\_mode_ccm.py", line 44, in <module>
ImportError: Module use of python27.dll conflicts with this version of Python.
[7.34] splash screen hidden
[7.34] Started up in 7.34 seconds with 890 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'T\xff>[\xb4\xe1\x9d\xed\xba\xb3\xfc>\xf9`\xcc\xd2s ;\xf1\xc3\x7f\xa7\xf9,\x07\xb6\xa2\xf03DG', b'D:\\home\\xxxxxx\\My Kindle Content\\ZZZZZZZ_EBOK.azw']
Added yyyyyyyyy to db in: 0.3
Added 1 books in 0.7 seconds

**Comment by teamplay7** [comment]
Kindle 1.17.0
Windows 10
Calibre 5.13

**Comment by ElleKayEm** [comment]
Was this copy of the book downloaded with Kindle for PC 1.17 currently installed on the same machine and user as calibre with DeDRM?

**Comment by teamplay7** [comment]
exactly

**Comment by teamplay7** [comment]
BTW...
![01](https://user-images.githubusercontent.com/66061511/111886738-53f99300-89d0-11eb-8319-a2c37d66ea29.PNG)

**Comment by teamplay7** [comment]
calibre, version 5.13.0
ERROR: Update Check Failed: Unable to reach the plugin index page.

Traceback (most recent call last):
  File "calibre\gui2\dialogs\plugin_updater.py", line 431, in __init__
  File "calibre\gui2\dialogs\plugin_updater.py", line 67, in read_available_plugins
ImportError: Module use of python27.dll conflicts with this version of Python.

**Comment by teamplay7** [comment]
Possibly because of the last DeDRM I have installed today?..

**Comment by ElleKayEm** [comment]
I'm running DeDRM 7.1.0 with calibre 5.13 on Windows 10 without issue.  Looks like there something that needs updating from python 2 to python 3 though.

**Comment by teamplay7** [comment]
something where?
and how to update?

**Comment by ElleKayEm** [comment]
Some other plugin?  Most other plugins can be updated from within calibre.

**Comment by teamplay7** [comment]
Thanks. 
1. Shall I reinstall Calibre?
2. Can you say anything about the log errors above?
3. Is it a known problem with the last version of DeDRM ?

**Comment by ElleKayEm** [comment]
Do you have any other old plugins in there?  Looks like something needs Python 2.  DeDRM 7.1.0 and calibre 5.x are Python 3.  No this is not an issue I've seen.  As I said, I myself am using the same versions with no problem.

**Comment by teamplay7** [comment]
Thanks!!!
I have reinstalled Calibre and DeDRM, it works fine now.

**Comment by ElleKayEm** [comment]
Good!  If you're all set, you can close the issue.

**Comment by teamplay7** [comment]
Thank you!
