### ISSUE TITLE
Can't open AZW

### ISSUE THREAD

**Issue by alizaybak** [apprenticeharper/DeDRM_tools#1614]
Hi, very excited to use this tool. Thanks in advance for any help. I already tried reinstalling Calibre and the plugin. Error note:

calibre Debug log
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[0.67] main UI initialized...
[0.67] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt B00AQQSDB6_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Owner\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Owner\AppData\Local\Amazon\Kindle\storage\.kinf2018
[2.97] splash screen hidden
[2.97] Started up in 2.97 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'}L\x0b\xc4\xe9o\x164\xa1h"\xaa5\xf5M\x05\x9f\x07d/\xf5x\xae\xf9\xea\x199\x1c\x89\xfb\xf7\xc8', b'C:\\Users\\Owner\\Documents\\My Kindle Content\\B00AQQSDB6_EBOK\\B00AQQSDB6_EBOK.azw']
Decrypted key file using IDString '3404184773' and UserName 'Owner'
DeDRM v7.1.0: Found 1 new key
DeDRM v7.1.0: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\xc4\xde\x02\x9d\xAdded B00AQQSDB6 EBOK to db in: 0.1
Added 1 books in 3.1 seconds
Worker Launch took: 0.00 seconds

**Comment by alizaybak** [comment]
I have a .voucher file in the folder of the AZW, but I'm not sure what do with it.

**Comment by ElleKayEm** [comment]
This is a KFX format book.  You'll need to download the book with Kindle for PC 1.26 or earlier and also install the KFX Input plugin.  Alternatively disable KFX downloads and re-download the book in the older format.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by alizaybak** [comment]
tyvm, will try.
