### ISSUE TITLE
[QUESTION] DeDRM not working for adobe digital editions

### ISSUE THREAD

**Issue by hsyim990** [apprenticeharper/DeDRM_tools#1618]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Set KFX metadata (from KFX Output) (1, 50, 0) && KFX Output (1, 50, 0)
calibre 5.13  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Set KFX metadata (from KFX Output) (1, 50, 0) && KFX Output (1, 50, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.99999999999999 x 128.18691588785046
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.27] splash screen shown
[1.27] Initializing db...
[1.28] db initialized
[1.28] Constructing main UI...
[2.06] main UI initialized...
[2.06] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Unlocking Contract Law.pdf
DeDRM v7.1.0: Unlocking Contract Law.pdf is a PDF ebook
DeDRM v7.1.0: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v7.1.0: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with new default key after 0.3 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[10.94] splash screen hidden
[10.94] Started up in 10.94 seconds with 5 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa9\xb1g\xf17\xe1\n*\xc4\xaf\x9e\xde\x87\xe6\xab\xec\xab\x85\xcb]\x03\x9c\x85\x7f\xaa\xf0^,{0\xca`', b'C:\\Users\\sammy\\Documents\\My Digital Editions\\Unlocking Contract Law.pdf']
Added Unlocking Contract Law to db in: 0.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
  File "calibre_plugins.dedrm.__init__", line 513, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 347, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x07B75730>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07B75730>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is notAdded 1 books in 1.1 seconds

```
</details>

**Comment by ElleKayEm** [comment]
Have you tried with calibre 4.23 and DeDRM 6.8.1?  Also, if this is a large file, you may want to try 64-bit calibre.

**Comment by hsyim990** [comment]
> Have you tried with calibre 4.23 and DeDRM 6.8.1? Also, if this is a large file, you may want to try 64-bit calibre.

Yeah when I tried it with calibre 4.23 and DeDRM 6.8.1 it works perfectly!! Thanks for the assist.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
