### ISSUE TITLE
DRM not converting with Big SUr

### ISSUE THREAD

**Issue by AMowat2001** [apprenticeharper/DeDRM_tools#1620]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
alibre Debug log
calibre 5.13  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Obok DeDRM (6, 5, 4)
calibre 5.13  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.2.0', 'Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 126.00000189233016 x 127.00000190734865
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
Loaded cached store plugin for: Smashwords at version: 6
[1.46] main UI initialized...
[1.46] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.37.0: Importing /Users/andrew/Documents/Kindle Books/My Kindle Content/B07Q5TL9SQ_EBOK/B07Q5TL9SQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/sb60cotp.kfx-zip
DeDRM v7.1.0: Trying to decrypt sb60cotp.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python

{'bsd_drives': {'main': '/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/System/Volumes/Data',
               '/dev/disk1s2': '/System/Volumes/Preboot',
               '/dev/disk1s4': '/System/Volumes/VM',
               '/dev/disk1s5': '/System/Volumes/Update/mnt1',
               '/dev/disk1s5s1': '/',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.2 USBMS: count found in cache: 69, count of files in metadata: 69, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 69
DeviceJob: set_books_in_library finished: time= 0.0031158924102783203
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[20.00] splash screen hidden
[20.00] Started up in 20.00 seconds with 2 books
Decrypting KFX-ZIP ebook: sb60cotp
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Found 2 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.86895154-4432-4451-baf3-ce7173ad0778.voucher
DeDRM v7.1.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'andrew'  on file  /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'ed72a0911f8c'
Decrypted key file using IDString 'ed72a0911f8c' and UserName 'andrew'
DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.37.0: Packaging /var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/sb60cotp.kfx-zip
Processing container: B07Q5TL9SQ_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/d0gfj9h__add_books/0/B07Q5TL9SQ_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07Q5TL9SQ_EBOK.azw has DRM and cannot be converted
Added If You Tell: A True Story of Murder, Family Secrets, and the Unbreakable Bond of Sisterhood to db in: 0.1
Added 1 books in 2.1 seconds
Worker Launch took: 0.07 seconds
Job: 3 Convert book 1 of 1 (If You Tell: A True Story of Murder, Family Secrets, and the Unbreakable Bond of Sisterhood) finished
Convert book 1 of 1 (If You Tell: A True Story of Murder, Family Secrets, and the Unbreakable Bond of Sisterhood)
	DeDRM v7.1.0: Trying to decrypt qyqcc_4m.kfx-zip
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	Decrypting KFX-ZIP ebook: qyqcc_4m
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 2 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.86895154-4432-4451-baf3-ce7173ad0778.voucher
	DeDRM v7.1.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'andrew'  on file  /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'ed72a0911f8c'
	Decrypted key file using IDString 'ed72a0911f8c' and UserName 'andrew'
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  verbose: 2
	  cover: '/var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/td2t4csu.jpeg'
	  output_profile: 'kindle'
	  read_metadata_from_opf: '/var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/a156f2og.opf'
	Resolved conversion options
	calibre version: 5.13.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/td2t4csu.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x117f37a00>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x117f37f10>,
	 'page_breaks_before': '/',
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/a156f2og.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.1.0: Trying to decrypt qyqcc_4m.kfx-zip
	Decrypting KFX-ZIP ebook: qyqcc_4m
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 2 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.86895154-4432-4451-baf3-ce7173ad0778.voucher
	DeDRM v7.1.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'andrew'  on file  /Users/andrew/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'ed72a0911f8c'
	Decrypted key file using IDString 'ed72a0911f8c' and UserName 'andrew'
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
	    self.decrypt_voucher(totalpids)
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	    raise Exception("Failed to decrypt KFX DRM voucher with any key")
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on /var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/qyqcc_4m.kfx-zip
	Software versions: KFX Input 1.37.0, calibre 5.13, macOS-10.16-x86_64-i386-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/7g/s20f9s208xl2vd006s7f1y_h0000gn/C/calibre_5.13.0_tmp_y7zzhql7/qyqcc_4m.kfx-zip
	Processing container: B07Q5TL9SQ_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07Q5TL9SQ_EBOK.azw has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	calibre.ebooks.DRMError: This book has DRM!
```
</details>

**Comment by ElleKayEm** [comment]
For KFX format, you need to download with Kindle for Mac 1.26 or earlier.  Alternatively, disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by LwsBtlr** [comment]
The best way, still, is to copy books from a kindle device. Works 100% of the time.

**Comment by ElleKayEm** [comment]
@LwsBtlr
Not directly from the Kindle -- unless it's an old one that doesn't support KFX or the rare case of a book not in KFX.  But method 3 at the link I posted (downloading from the website for an E-ink Kindle) will work.  You'll also need to add the Kindle's serial number to DeDRM's customization.

**Comment by AMowat2001** [comment]
Thanks for your comments, @LwsBtlr I agree it also doesn't work from a Kindle. However your suggestion of older versions of KFM 1.26 and Calibre 4.23.0 works perfectly. Watch out for the auto update of KFM
