### ISSUE TITLE
[QUESTION] Can't open AZW

### ISSUE THREAD

**Issue by Selyen** [apprenticeharper/DeDRM_tools#1622]
Error note:
calibre, version 5.13.0
ERRORE: Caricamento libro fallito: Failed to open the book at C:\Users\chiag\Biblioteca di calibre\Sconosciuto\B079WN5PV2 EBOK (13)\B079WN5PV2 EBOK - Sconosciuto.azw. Click "Show details" for more info.

Failed to convert book: C:\Users\chiag\Biblioteca di calibre\Sconosciuto\B079WN5PV2 EBOK (13)\B079WN5PV2 EBOK - Sconosciuto.azw with error:
DeDRM v7.1.0: Trying to decrypt B079WN5PV2 EBOK - Sconosciuto.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\chiag\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\chiag\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1483474873' and UserName 'chiag'
DeDRM v7.1.0: Found 1 new key
DeDRM v7.1.0: Ultimately failed to decrypt after 5.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\chiag\Biblioteca di calibre\Sconosciuto\B079WN5PV2 EBOK (13)\B079WN5PV2 EBOK - Sconosciuto.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 5.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: Questo è un libro KFX di Amazon. Non può essere elaborato. Vedi https://www.mobileread.com/forums/showthread.php?t=283371 per informazioni su come gestire i libri in formato KFX.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 870, in viewer_main
  File "calibre\srv\render_book.py", line 861, in render_for_viewer
  File "calibre\srv\render_book.py", line 838, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: Questo è un libro KFX di Amazon. Non può essere elaborato. Vedi https://www.mobileread.com/forums/showthread.php?t=283371 per informazioni su come gestire i libri in formato KFX.

**Comment by ElleKayEm** [comment]
KFX books need to be downloaded with Kindle for PC 1.26 or earlier.  Alternatively use one of the methods here to get books in the older format:  https://www.mobileread.com/forums/showthread.php?t=283371
