### ISSUE TITLE
[QUESTION] Unable to convert .azw to epub

### ISSUE THREAD

**Issue by madoni** [apprenticeharper/DeDRM_tools#1628]
## CheckList

- [x] `The Title` and The `Log Title` are set correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
Unable to convert `.azw` to `epub`

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.14  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.14  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 151.0000022677925 x 151.00000226779247
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[0.84] main UI initialized...
[0.84] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt B006Z0QR3I_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Algorithms
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/madoni/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'madoni'  on file  /Users/madoni/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'012642d94617'
Decrypted key file using IDString '012642d94617' and UserName 'madoni'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Algorithms
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticehar
per/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://gi
thub.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository
: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[24.94] splash screen hidden
[24.94] Started up in 24.94 seconds with 1 books
Added Algorithms to db in: 0.0
Added 1 books in 0.9 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Try calibre 4.23 and DeDRM 6.8.1.
