### ISSUE TITLE
DeDRM Fail on older Topaz eBook

### ISSUE THREAD

**Issue by jnl** [apprenticeharper/DeDRM_tools#1630]
### Log Excerpt:
DeDRM v7.1.0: Found 1 new key
Decrypting Topaz ebook: A Small Matter of Programming: Perspectives on End User Computing
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 8.2 seconds
Trying: b'qNn6ZS3O'
DeDRM v7.1.0: Ultimately failed to decrypt after 8.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.topazextract", line 361, in processBook
    raise DrmException("No key found in {0:d} keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(len(pidlst)))
calibre_plugins.dedrm.topazextract.DrmException: No key found in 0 keys tried. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Full log attached.
[debug.log](https://github.com/apprenticeharper/DeDRM_tools/files/6224371/debug.log)

**Comment by ElleKayEm** [comment]
Give it a try with calibre 4.23 and DeDRM 6.8.1.
