### ISSUE TITLE
[QUESTION] Title

### ISSUE THREAD

**Issue by angie1k** [apprenticeharper/DeDRM_tools#1634]
## Log
<details><summary>Log Title</summary>

```log
EpubMerge: DEBUG: 2021-03-31 00:21:21,075: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:C:\Users\Angie\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2021-03-31 00:21:21,095: calibre_plugins.fanficfare_plugin.fff_plugin(222): Plugin FanFicFare macmenuhack file_path:C:\Users\Angie\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Registro de depuración
calibre 5.8.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && Count Pages (1, 11, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 1, 0) && Generate Cover (2, 0, 2) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Prettify Cover (1, 5, 0) && Reading List (1, 7, 2)
calibre 5.8.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && Count Pages (1, 11, 0) && EpubMerge (2, 11, 0) && FanFicFare (4, 1, 0) && Generate Cover (2, 0, 2) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Prettify Cover (1, 5, 0) && Reading List (1, 7, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.67] splash screen shown
[0.67] Initializing db...
[1.28] db initialized
[1.28] Constructing main UI...
Loaded cached store plugin for: Библио.бг at version: 2
[5.14] main UI initialized...
[5.14] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Face-To-Face with Doug Schoon Volume III_ Science and Facts about Nails_nail Products for the Educationally Inclined.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Storage number map:
{(7, 0): [(2, 'F'), (5, 'C'), (6, 'D')], (7, 1): [(1, 'E')], (7, 2): [(1, 'G')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G000PP1292210CC8&0: StorageDeviceNumber(type=7, number=2, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=8)
{'drive_letters': ['G'],
 'pnp_id_map': {'G': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g000pp1292210cc8&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'G': (2, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Obtener información del dispositivo started
DeviceJob: 0 Obtener información del dispositivo done, calling callback
DeviceJob: 0 Obtener información del dispositivo callback returned
Job: 1 Establecer información de la biblioteca started
DeviceJob: 1 Establecer información de la biblioteca done, calling callback
DeviceJob: 1 Establecer información de la biblioteca callback returned
Job: 2 Obtener lista de libros en el dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: G:\ documents
DEBUG:    0.0 USBMS: scan from root False G:\documents
DEBUG:    0.0 USBMS: count found in cache: 6, count of files in metadata: 6, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Obtener lista de libros en el dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 6
DeviceJob: set_books_in_library finished: time= 0.006071329116821289
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
READING LIST: Metadata available: {'main': {'calibre_version': '5.8.1', 'device_store_uuid': '6fa4c45c-c82c-48d5-b38e-8ac6c9d37a00', 'last_library_uuid': None, 'date_last_connected': '2021-03-31T03:21:25.270988+00:00', 'prefix': 'G:/', 'location_code': 'main', 'device_name': 'Amazon Kindle'}}
READING LIST: Sync Now - force_sync= False
DeviceJob: 2 Obtener lista de libros en el dispositivo callback returned
Job: 0 Obtener información del dispositivo finished
No hay detalles disponibles.
Job: 2 Obtener lista de libros en el dispositivo finished
No hay detalles disponibles.
Job: 1 Establecer información de la biblioteca finished
No hay detalles disponibles.
[10.75] splash screen hidden
[10.75] Started up in 10.75 seconds with 5744 books
Decrypting Kindle Format 8 ebook: Face-To-Face with Doug Schoon Volume III: Science and Facts about Nails/nail Products for the Educationally Inclined
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Angie\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.1.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded Face-To-Face with Doug Schoon Volume III: Science and Facts about Nails/nail Products for the Educationally Inclined to db in: 1.6
Added 1 books in 3.0 seconds
Worker Launch took: 0.00 seconds
Worker Launch took: 0.02 seconds

```
</details>

**Comment by ElleKayEm** [comment]
Double-check that you have the serial number entered correctly in DeDRM's customization.  If you download the book from the website, make sure you chose the correct E-ink Kindle (not a Fire).
