### ISSUE TITLE
[QUESTION] Ultimately failed to decrypt 

### ISSUE THREAD

**Issue by zheng1z** [apprenticeharper/DeDRM_tools#1636]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Intro
I used the PC kindle ver1.24.3 to download the .azw file and tried to deDRM it. 
Here seems keys were found but still failed to get working.
Also tried calibre ver 4.2.3 and DeDRM 6.1.1 with no good.
Thanks for the help. 

## Log
<details><summary>calibre Debug log</summary>

```log
calibre Debug log
calibre 5.14  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.14  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt B07WRF35WN_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Southern Horrors and Other Writings: The Anti-Lynching Campaign of Ida B. Wells, 1892-1900 (Bedford Cultural Editions)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\zouzo\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\zouzo\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1050282979' and UserName 'zouzo'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Southern Horrors and Other Writings: The Anti-Lynching Campaign of Ida B. Wells, 1892-1900 (Bedford Cultural Editions)
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: Cannot decode library or rented ebooks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[2.70] splash screen hidden
[2.70] Started up in 2.70 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x80r\x93\xdd\xdf\x9b\x9f\xc1#Ez\x9e\xd4O\xe6\x8d\xf7\xf5M\x04\xb3\x8c\x10\x13\x8e0W\xf0T\xaapS', b'C:\\Users\\zouzo\\Documents\\My Kindle Content\\B07WRF35WN_EBOK\\B07WRF35WN_EBOK.azw']
Added Southern Horrors and Other Writings: The Anti-Lynching Campaign of Ida B. Wells, 1892-1900 (Bedford Cultural Editions) to db in: 0.0
Added 1 books in 0.4 seconds

```
</details>

**Comment by ElleKayEm** [comment]
From the log:

> Failed to decrypt with error: Cannot decode library or rented ebooks.
