### ISSUE TITLE
[QUESTION] name 'htmlentitydefs' is not defined

### ISSUE THREAD

**Issue by asmendorius2** [apprenticeharper/DeDRM_tools#1639]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.
---

## Title
error "name 'htmlentitydefs' is not defined" during conversion of single manga, 
other books works correctly and drm is removed.
i tried it from kindle device, package from website and from PC application.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
calibre 5.13 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.37.0: Importing B:\Kindle\Books_Input\B08TSVCZWY_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.1.0: Trying to decrypt B08TSVCZWY_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.1.0: Failed to decrypt with error: name 'htmlentitydefs' is not defined
DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Asmendorius\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2011
[3.91] splash screen hidden
[3.92] Started up in 3.92 seconds with 0 books
Failed to get storage number for drive: B with error: [WinError 1] Niepoprawna funkcja.
Storage number map:
{(7, 0): [(2, 'C')],
 (7, 1): [(4, 'G')],
 (7, 3): [(2, 'P'), (3, 'A')],
 (7, 4): [(1, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G000PP12918404JP&0: StorageDeviceNumber(type=7, number=4, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=10)
{'drive_letters': ['D'],
 'pnp_id_map': {'D': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g000pp12918404jp&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'D': (4, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.0 USBMS: scan from root False D:\documents
DEBUG:    0.1 USBMS: count found in cache: 50, count of files in metadata: 50, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 50
DeviceJob: set_books_in_library finished: time= 0.015207290649414062
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc6\xa2\xa1<\x13:\xd4li*\xcd\x8d)\xf6\xfeX\xff)\x1f\r[c\xd6$eI\xd7\xd3c\xff_\x0e', b'B:\\Kindle\\Books_Input\\B08TSVCZWY_EBOK.azw']
Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.1.0: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 221, in GetDecryptedBook
  File "calibre_plugins.dedrm.k4mobidedrm", line 198, in unescape
  File "re.py", line 210, in sub
  File "calibre_plugins.dedrm.k4mobidedrm", line 194, in fixup
NameError: name 'htmlentitydefs' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Fox & Little Tanuki, Volume 1 (The Fox & Little Tanuki) to db in: 2.7
Added 1 books in 5.7 seconds
Worker Launch took: 0.03 seconds
Job: 3 Convert book 1 of 1 (The Fox & Little Tanuki, Volume 1 (The Fox & Little Tanuki)) finished
Convert book 1 of 1 (The Fox & Little Tanuki, Volume 1 (The Fox & Little Tanuki))

	DeDRM v7.1.0: Trying to decrypt spxhudko.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Failed to decrypt with error: name 'htmlentitydefs' is not defined
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\Asmendorius\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
	Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  cover: 'C:\\Users\\Asmendorius\\AppData\\Local\\Temp\\calibre_fu04x62q\\idwfqxjr.jpeg'

	  verbose: 2

	  output_profile: 'kindle_pw3'

	  read_metadata_from_opf: 'C:\\Users\\Asmendorius\\AppData\\Local\\Temp\\calibre_fu04x62q\\41ynegjm.opf'

	Resolved conversion options

	calibre version: 5.13.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Asmendorius\\AppData\\Local\\Temp\\calibre_fu04x62q\\idwfqxjr.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_compress': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000202BD22C160>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'mobi_file_type': 'old',

	 'mobi_ignore_margins': False,

	 'mobi_keep_original_images': False,

	 'mobi_toc_at_start': False,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': True,

	 'no_inline_toc': False,

	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x00000202BD22C790>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'personal_doc': '[PDOC]',

	 'prefer_author_sort': False,

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Asmendorius\\AppData\\Local\\Temp\\calibre_fu04x62q\\41ynegjm.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'share_not_sync': False,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 221, in GetDecryptedBook

	  File "calibre_plugins.dedrm.k4mobidedrm", line 198, in unescape

	  File "re.py", line 210, in sub

	  File "calibre_plugins.dedrm.k4mobidedrm", line 194, in fixup

	NameError: name 'htmlentitydefs' is not defined

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.1.0: Trying to decrypt spxhudko.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Failed to decrypt with error: name 'htmlentitydefs' is not defined
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Asmendorius\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: C:\Users\Asmendorius\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
	Decrypted key file using IDString '1915115406' and UserName 'Asmendorius'
	DeDRM v7.1.0: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	DeDRM v7.1.0: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 221, in GetDecryptedBook

	  File "calibre_plugins.dedrm.k4mobidedrm", line 198, in unescape

	  File "re.py", line 210, in sub

	  File "calibre_plugins.dedrm.k4mobidedrm", line 194, in fixup

	NameError: name 'htmlentitydefs' is not defined

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 631, in run

	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\Asmendorius\AppData\Local\Temp\calibre_fu04x62q\spxhudko.azw

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: The Fox & Little Tanuki, Volume 1 (The Fox & L
tle Tanuki)

```
</details>

**Comment by ElleKayEm** [comment]
Try with calibre 4.23 and DeDRM 6.8.1.

**Comment by ableeker** [comment]
This is Python 2 code that has to be adapted for Python 3. I've submitted pull request #1615 that should fix this issue.
