### ISSUE TITLE
Unable to deDRM this book 

### ISSUE THREAD

**Issue by breakDRM** [apprenticeharper/DeDRM_tools#1640]
hi 

I'm unable to de drm this book bought from Apple Store. I'm uisng Calibre 5.14.0 with deDRM plug-in 7.1 the laptop is on Windows 10

Please see below the debug file:   

DeDRM v7.1.0: “yfpo4oxi.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 642, in run

	  File "calibre_plugins.dedrm.__init__", line 418, in ePubDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Couldn't decrypt after 0.3 seconds. DRM free perhaps?

	InputFormatPlugin: EPUB Input running

	on C:\Users\dears\AppData\Local\Temp\calibre_x3ujsom0\yfpo4oxi.epub

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert

	calibre.ebooks.DRMError: yfpo4oxi.epub

**Comment by ElleKayEm** [comment]
These tools don't work on Apple's DRM.
