### ISSUE TITLE
0 PIDs

### ISSUE THREAD

**Issue by HKAR572** [apprenticeharper/DeDRM_tools#1643]
## CheckList

- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Title
This is probably and incredibly stupid issue with an easy fix that I am just not understanding.

I have the Kindle app on my computer, and look in the files that are downloaded - which are given a code designation instead of being identified by book title, The file that is in there that is a AZW file is complete garbage to try importing into Calibre.

So, instead, I go through Amazon to try downloading with the Download & Transfer via USB.  Which seems to provide a file that isn't complete garbage - but attached is the debug log file for what goes on.  I am guessing that the issue is because of needing a device ID, but I have no idea what the device ID would/should be... I have an android phone with MoonReader or my PC with Calibre instead of the Kindle junk app/device.

Either what do I need for a PID, and where do I put it - or am I doing something wrong with accessing the files downloaded with the Kindle App [C:\Users\Documents\My Kindle Content\B00APOW7JI_EBOK\]

## Log
<details><summary>0 PIDs</summary>
calibre Debug log
calibre 5.14  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
calibre 5.14  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 69.86819484240687 x 69.80152671755725
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.88] main UI initialized...
[0.88] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Pagan Christianity__ Exploring the Roots of Our Church Practices.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Pagan Christianity?: Exploring the Roots of Our Church Practices
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\hourl\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\hourl\AppData\Local\Amazon\Kindle\storage\.kinf2018
[2.33] splash screen hidden
[2.33] Started up in 2.33 seconds with 4 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe9 \xb6w\xc9U9;W\x94\xf6y\xdd\x8eu\xe7G\xb3\xa7\xabam\xe7ZK\x99{\xe23a\x8e\xef', b'C:\\Users\\hourl\\Downloads\\Pagan Christianity__ Exploring the Roots of Our Church Practices.azw3']
Decrypted key file using IDString '2565276819' and UserName 'hourl'
DeDRM v7.1.0: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Pagan Christianity?: Exploring the Roots of Our Church Practices
Got DSN key from database default_key_1
Found 4 keys to try after 3.3 seconds
Crypto Type is: 2
DeDRM v7.1.0: Ultimately failed to decrypt after 3.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 3.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added Pagan Christianity?: Exploring the Roots of Our Church Practices to db in: 0.3
Added 1 books in 3.9 seconds

</details>

**Comment by ElleKayEm** [comment]
To get a file which can be decrypted with "Download & Transfer via USB", you need an E-ink Kindle on your account (and add its serial number to DeDRM's customization).  For Kindle for PC, you will need to disable KFX downloads.  Or download the book with Kindle for PC 1.26 or earlier and also install the KFX Input plugin to calibre.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
