### ISSUE TITLE
Unable to DeDRM the following book

### ISSUE THREAD

**Issue by DRMprob** [apprenticeharper/DeDRM_tools#1647]
calibre Journal de débogage
calibre 5.4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[1.00] main UI initialized...
[1.00] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt B01NCO91JM_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.1.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\hp\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\hp\AppData\Local\Amazon\Kindle\storage\.kinf2018
[10.69] splash screen hidden
[10.69] Started up in 10.69 seconds with 24 books
Decrypted key file using IDString '3100804834' and UserName 'hp'
DeDRM v7.1.0: Ultimately failed to decrypt after 3.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 3.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 285, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\xc4\xde\x02\x9c\x8Added B01NCO91JM EBOK to db in: 1.4
Added 1 books in 5.6 seconds

**Comment by ElleKayEm** [comment]
A KFX format book needs to be downloaded with Kindle for PC 1.26 or earlier and you also need the KFX Input plugin.  Alternatively, disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
