### ISSUE TITLE
[QUESTION] Failed to decrypt AZW, MacOS Catalina

### ISSUE THREAD

**Issue by nell** [apprenticeharper/DeDRM_tools#1648]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
Failed to decrypt AZW. 
Using Kindle for Mac (Catalina 10.15.7)
DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
Using latest version of Kindle, disabled KFW with chmod (and installed KFW tools into Calibre for good measure), book downloaded and never opened in the same account where Calibre is installed.
Book purchased on Amazon.jp and downloaded into Kindle for Mac. I don't have any eInk devices.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.14  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
calibre 5.14  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.13] main UI initialized...
[1.13] Hiding splash screen
Starting QuickView
[3.35] splash screen hidden
[3.35] Started up in 3.35 seconds with 12 books
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (おばちゃんたちのいるところ Where The Wild Ladies Are (中公文庫)) finished
Convert book 1 of 1 (おばちゃんたちのいるところ Where The Wild Ladies Are (中公文庫))
	DeDRM v7.1.0: Trying to decrypt lu_43pgt.azw
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: おばちゃんたちのいるところ　Where The Wild Ladies Are (中公文庫)
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/nelly/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'nelly'  on file  /Users/nelly/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0d85c35af4c4'
	Decrypted key file using IDString '0d85c35af4c4' and UserName 'nelly'
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: '/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_5.14.0_tmp__lpsdfpd/7gki490e.opf'
	  cover: '/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_5.14.0_tmp__lpsdfpd/v8n8v8cc.jpeg'
	  output_profile: 'ipad3'
	Resolved conversion options
	calibre version: 5.14.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_5.14.0_tmp__lpsdfpd/v8n8v8cc.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10e619f10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x10e6243a0>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_5.14.0_tmp__lpsdfpd/7gki490e.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.1.0: Trying to decrypt lu_43pgt.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: おばちゃんたちのいるところ　Where The Wild Ladies Are (中公文庫)
	Got SerialNumber from database default_key
	Got UsernameHash from database default_key
	Found 4 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.1.0: Failed to decrypt with error: No key found in 4 PIDs tried.
	DeDRM v7.1.0: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/nelly/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'nelly'  on file  /Users/nelly/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'0d85c35af4c4'
	Decrypted key file using IDString '0d85c35af4c4' and UserName 'nelly'
	DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 631, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_5.14.0_tmp__lpsdfpd/lu_43pgt.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: おばちゃんたちのいるところ　Where The Wild Ladies Are (中公文庫)

```
</details>

**Comment by ElleKayEm** [comment]
Sounds like you've covered all the bases.  The only thing I can think is that something with this book isn't working with Python 3 DeDRM/calibre.  See if it will work with calibre 4.23 and DeDRM 6.8.1.

**Comment by nell** [comment]
Good call, it worked with calibre 4.23 + DeDRM 6.8.1! Thank you!

In case it helps somehow, here is the log from this conversion.


```calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.000001637 x 109.000001637
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.15] main UI initialized...
[1.15] Hiding splash screen
[3.06] splash screen hidden
[3.06] Started up in 3.06 seconds with 12 books
Worker Launch took: 0.092346906662
Job: 0 Convert book 1 of 1 (おばちゃんたちのいるところ　Where The Wild Ladies Are (中公文庫)) finished
Convert book 1 of 1 (おばちゃんたちのいるところ　Where The Wild Ladies Are (中公文庫))
	Conversion options changed from defaults:
	  output_profile: u'ipad3'
	  verbose: 2
	  cover: u'/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/UY1Irl.jpeg'
	  read_metadata_from_opf: u'/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/iKoZ2R.opf'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/UY1Irl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x113b51f10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x113b5f510>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/iKoZ2R.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/NwuRXy.azw3
	Found KF8 MOBI of type u'standalone'
	Extracting text...
	Parsing all content...
	Parsing styles/0002.css ...
	Parsing text/part0020.html ...
	Parsing text/part0015.html ...
	Parsing text/part0000.html ...
	Parsing text/part0003.html ...
	Parsing text/part0016.html ...
	Parsing text/part0011.html ...
	Parsing text/part0039.html ...
	Parsing text/part0028.html ...
	Parsing text/part0013.html ...
	Parsing text/part0019.html ...
	Parsing text/part0012.html ...
	Parsing text/part0023.html ...
	Parsing text/part0025.html ...
	Parsing text/part0024.html ...
	Parsing text/part0035.html ...
	Parsing text/part0001.html ...
	Parsing text/part0040.html ...
	Parsing text/part0033.html ...
	Parsing text/part0031.html ...
	Parsing text/part0036.html ...
	Parsing text/part0034.html ...
	Parsing text/part0029.html ...
	Parsing text/part0007.html ...
	Parsing text/part0005.html ...
	Parsing text/part0006.html ...
	Parsing text/part0022.html ...
	Parsing text/part0010.html ...
	Parsing text/part0008.html ...
	Parsing text/part0018.html ...
	Parsing text/part0032.html ...
	Parsing text/part0026.html ...
	Parsing text/part0038.html ...
	Parsing text/part0002.html ...
	Parsing text/part0017.html ...
	Parsing text/part0014.html ...
	Parsing text/part0021.html ...
	Parsing text/part0009.html ...
	Parsing text/part0030.html ...
	Parsing text/part0027.html ...
	Parsing styles/0004.css ...
	Parsing styles/0001.css ...
	Property: Unknown Property name. [40:5: word-wrap]
	Property: Unknown Property name. [42:5: -webkit-text-align-last]
	Property: Unknown Property name. [43:5: -epub-text-align-last]
	Property: Unknown Property name. [44:5: -webkit-line-break]
	Property: Unknown Property name. [45:5: -epub-line-break]
	Property: Unknown Property name. [46:5: -webkit-word-break]
	Property: Unknown Property name. [47:5: -epub-word-break]
	Property: Unknown Property name. [48:5: -webkit-hyphens]
	Property: Unknown Property name. [49:5: -epub-hyphens]
	Property: Unknown Property name. [50:5: -webkit-text-underline-position]
	Property: Unknown Property name. [79:5: -webkit-writing-mode]
	Property: Unknown Property name. [80:5: -webkit-writing-mode]
	Property: Unknown Property name. [84:5: -webkit-writing-mode]
	Property: Unknown Property name. [85:5: -webkit-writing-mode]
	Property: Unknown Property name. [145:5: -webkit-text-align-last]
	Property: Unknown Property name. [146:5: -epub-text-align-last]
	Property: Unknown Property name. [151:5: -webkit-text-align-last]
	Property: Unknown Property name. [152:5: -epub-text-align-last]
	Property: Unknown Property name. [157:5: -webkit-text-align-last]
	Property: Unknown Property name. [158:5: -epub-text-align-last]
	Property: Unknown Property name. [163:5: -webkit-text-align-last]
	Property: Unknown Property name. [164:5: -epub-text-align-last]
	Property: Unknown Property name. [307:5: -webkit-text-combine]
	Property: Unknown Property name. [308:5: -webkit-text-combine]
	Property: Unknown Property name. [315:5: -webkit-text-combine]
	Property: Unknown Property name. [316:5: -webkit-text-combine]
	Property: Unknown Property name. [319:5: -webkit-text-orientation]
	Property: Unknown Property name. [320:5: -epub-text-orientation]
	Property: Unknown Property name. [323:5: -webkit-text-orientation]
	Property: Unknown Property name. [324:5: -epub-text-orientation]
	Property: Unknown Property name. [325:5: -epub-text-orientation]
	Property: Unknown Property name. [374:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [375:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [378:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [379:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [382:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [383:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [386:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [387:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [390:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [391:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [394:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [395:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [398:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [399:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [402:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [403:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [406:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [407:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [410:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [411:5: -webkit-text-emphasis-style]
	Property: Unknown Property name. [810:5: -webkit-text-emphasis-color]
	Property: Unknown Property name. [811:5: -webkit-text-emphasis-color]
	Property: Unknown Property name. [2663:5: -webkit-line-break]
	Property: Unknown Property name. [2664:5: -epub-line-break]
	Property: Unknown Property name. [2667:5: -webkit-line-break]
	Property: Unknown Property name. [2668:5: -epub-line-break]
	Property: Unknown Property name. [2671:5: -webkit-line-break]
	Property: Unknown Property name. [2672:5: -epub-line-break]
	Property: Unknown Property name. [2675:5: -webkit-line-break]
	Property: Unknown Property name. [2676:5: -epub-line-break]
	Property: Unknown Property name. [2681:5: -webkit-word-break]
	Property: Unknown Property name. [2682:5: -epub-word-break]
	Property: Unknown Property name. [2685:5: -webkit-word-break]
	Property: Unknown Property name. [2686:5: -epub-word-break]
	Property: Unknown Property name. [2689:5: -webkit-word-break]
	Property: Unknown Property name. [2690:5: -epub-word-break]
	Property: Unknown Property name. [2695:5: word-wrap]
	Property: Unknown Property name. [2698:5: word-wrap]
	Parsing styles/0003.css ...
	Parsing text/part0037.html ...
	Parsing text/part0004.html ...
	Reading TOC from NCX...
	Merging user specified metadata...
	Detecting structure...
	Flattening CSS and remapping font sizes...
	Source base font size is 12.00000pt
	Removing fake margins...
	Found 8 items of level: div_4
	Found 10 items of level: p_5
	Found 8 items of level: div_5
	Found 3 items of level: p_4
	Found 19 items of level: p_3
	Found 1200 items of level: p_2
	Found 1 items of level: div_6
	Found 5 items of level: p_7
	Found 41 items of level: div_1
	Found 27 items of level: div_2
	Found 4 items of level: div_3
	Found 9 items of level: p_6
	Ignoring level p_3
	Ignoring level div_3
	Ignoring level div_4
	Ignoring level div_5
	Ignoring level div_6
	Ignoring level p_7
	Ignoring level p_6
	Ignoring level p_5
	Ignoring level p_4
	p_2  left margin stats: Counter({u'0': 1200})
	p_2  right margin stats: Counter({u'0': 1200})
	div_1  left margin stats: Counter({u'0': 22})
	div_1  right margin stats: Counter({u'0': 22})
	div_2  left margin stats: Counter({u'0': 3})
	div_2  right margin stats: Counter({u'0': 3})
	Cleaning up manifest...
	Trimming unused files from manifest...
	Trimming u'images/00029.unknown' from manifest
	Trimming u'images/00030.unknown' from manifest
	Trimming u'images/00028.unknown' from manifest
	Trimming u'images/00025.jpeg' from manifest
	Creating EPUB Output...
	Splitting markup on page breaks and flow limits, if any...
		Looking for large trees in text/part0020.html...
		No large trees found
			Splitting on page-break at id=toc-009
	Adjusted split point to ancestor
		Looking for large trees in text/part0015.html...
		No large trees found
		Looking for large trees in text/part0000.html...
		No large trees found
			Splitting on page-break at id=toc-003
	Adjusted split point to ancestor
		Looking for large trees in text/part0003.html...
		No large trees found
		Looking for large trees in text/part0016.html...
		No large trees found
			Splitting on page-break at id=toc-007
	Adjusted split point to ancestor
		Looking for large trees in text/part0011.html...
		No large trees found
			Splitting on page-break at id=calibre_pb_0
			Splitting on page-break at id=calibre_pb_1
		Looking for large trees in text/part0039.html...
		No large trees found
		Looking for large trees in text/part0028.html...
		No large trees found
			Splitting on page-break at id=toc-008
	Adjusted split point to ancestor
		Looking for large trees in text/part0013.html...
		No large trees found
			Splitting on page-break at id=toc-011
	Adjusted split point to ancestor
		Looking for large trees in text/part0019.html...
		No large trees found
		Looking for large trees in text/part0012.html...
		No large trees found
			Splitting on page-break at id=toc-013
	Adjusted split point to ancestor
		Looking for large trees in text/part0023.html...
		No large trees found
			Splitting on page-break at id=toc-014
	Adjusted split point to ancestor
		Looking for large trees in text/part0025.html...
		No large trees found
		Looking for large trees in text/part0024.html...
		No large trees found
			Splitting on page-break at id=toc-019
	Adjusted split point to ancestor
		Looking for large trees in text/part0035.html...
		No large trees found
			Splitting on page-break at id=calibre_pb_0
			Splitting on page-break at id=calibre_pb_1
		Looking for large trees in text/part0001.html...
		No large trees found
		Looking for large trees in text/part0040.html...
		No large trees found
			Splitting on page-break at id=toc-018
	Adjusted split point to ancestor
		Looking for large trees in text/part0033.html...
		No large trees found
			Splitting on page-break at id=toc-017
	Adjusted split point to ancestor
		Looking for large trees in text/part0031.html...
		No large trees found
		Looking for large trees in text/part0036.html...
		No large trees found
		Looking for large trees in text/part0034.html...
		No large trees found
			Splitting on page-break at id=toc-016
	Adjusted split point to ancestor
		Looking for large trees in text/part0029.html...
		No large trees found
			Splitting on page-break at id=toc-005
	Adjusted split point to ancestor
		Looking for large trees in text/part0007.html...
		No large trees found
			Splitting on page-break at id=toc-004
	Adjusted split point to ancestor
		Looking for large trees in text/part0005.html...
		No large trees found
		Looking for large trees in text/part0006.html...
		No large trees found
		Looking for large trees in text/part0022.html...
		No large trees found
		Looking for large trees in text/part0010.html...
		No large trees found
		Looking for large trees in text/part0008.html...
		No large trees found
		Looking for large trees in text/part0018.html...
		No large trees found
		Looking for large trees in text/part0032.html...
		No large trees found
		Looking for large trees in text/part0026.html...
		No large trees found
			Splitting on page-break at id=calibre_pb_0
			Splitting on page-break at id=calibre_pb_1
		Looking for large trees in text/part0038.html...
		No large trees found
			Splitting on page-break at id=toc-002
	Adjusted split point to ancestor
		Looking for large trees in text/part0002.html...
		No large trees found
			Splitting on page-break at id=toc-010
	Adjusted split point to ancestor
		Looking for large trees in text/part0017.html...
		No large trees found
		Looking for large trees in text/part0014.html...
		No large trees found
			Splitting on page-break at id=toc-012
	Adjusted split point to ancestor
		Looking for large trees in text/part0021.html...
		No large trees found
			Splitting on page-break at id=toc-006
	Adjusted split point to ancestor
		Looking for large trees in text/part0009.html...
		No large trees found
		Looking for large trees in text/part0030.html...
		No large trees found
			Splitting on page-break at id=toc-015
	Adjusted split point to ancestor
		Looking for large trees in text/part0027.html...
		No large trees found
			Splitting on page-break at id=toc-020
	Adjusted split point to ancestor
		Looking for large trees in text/part0037.html...
		No large trees found
		Looking for large trees in text/part0004.html...
		No large trees found
	EPUB output written to /var/folders/ly/fvyztrq95z17vj_xlx0l7bgm0000gn/C/calibre_4.23.0_tmp_KpMiQC/Jvk2LZ.epub

Worker Launch took: 0.141304969788

```
