### ISSUE TITLE
HELP: Calibre cannot convert AZW to PDF due to DRM (see low below)

### ISSUE THREAD

**Issue by caritoarias** [apprenticeharper/DeDRM_tools#1651]
calibre Debug log
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Obok DeDRM (7, 1, 0)
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 37, 0) && DeDRM (7, 1, 0) && Package KFX (from KFX Input) (1, 37, 0) && KFX metadata reader (from KFX Input) (1, 37, 0) && KFX Input (1, 37, 0) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[2.36] main UI initialized...
[2.36] Hiding splash screen
Starting QuickView
[5.31] splash screen hidden
[5.31] Started up in 5.31 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'Z\xe9\x15g\xdd\x9e# \xb5\x82\x07\xb6\x91\xca?\xc3\x04\x9b4J\x17\xd6\xb3\x8f\x810\xfb\xc9\x8f\xf6\xb8\xc3', b'C:\\Users\\DougandCaro\\Documents\\My Kindle Content\\B00JS6HK46_EBOK\\B00JS6HK46_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.37.0: Importing C:\Users\DougandCaro\Documents\My Kindle Content\B00JS6HK46_EBOK\B00JS6HK46_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 8 file(s) as C:\Users\DOUGAN~1\AppData\Local\Temp\calibre_oqxbvf6u\gxn470s8.kfx-zip
DeDRM v7.1.0: Trying to decrypt gxn470s8.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: gxn470s8
Found 0 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ce13639b-e81f-4e58-9acf-122c58e7883e.voucher
DeDRM v7.1.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.1.0: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\DougandCaro\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\DougandCaro\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1550708266' and UserName 'DougandCaro'
DeDRM v7.1.0: Found 1 new key
Decrypting KFX-ZIP ebook: gxn470s8
Got DSN key from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ce13639b-e81f-4e58-9acf-122c58e7883e.voucher
DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.37.0: Packaging C:\Users\DOUGAN~1\AppData\Local\Temp\calibre_oqxbvf6u\gxn470s8.kfx-zip
Processing container: B00JS6HK46_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\DOUGAN~1\AppData\Local\Temp\calibre_oqxbvf6u\mg5dgz3o_add_books\0\B00JS6HK46_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 315, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00JS6HK46_EBOK.azw has DRM and cannAdded Healing is Voltage: The Handbook to db in: 3.0
Added 1 books in 6.3 seconds

**Comment by ElleKayEm** [comment]
With KFX format like this, you need to use Kindle for PC 1.26 or earlier.  Alternatively disable KFX downloads.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
