### ISSUE TITLE
Failed DeDRM azw3 ebooks, please Help

### ISSUE THREAD

**Issue by profecesdersiendo** [apprenticeharper/DeDRM_tools#1652]
calibre Registro de depuración
calibre 5.14  embedded-python: True is64bit: True
Linux-5.4.0-70-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-70-generic', '#78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021')
Python 3.8.5
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.14  embedded-python: True is64bit: True
Linux-5.4.0-70-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-70-generic', '#78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021')
Python 3.8.5
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.07] splash screen shown
[0.07] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
[6.14] splash screen hidden

DeDRM v7.1.0: Trying to decrypt Grandes granjas, grandes gripes (Ensayo) (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Grandes granjas, grandes gripes (Ensayo) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.1.0: Trying to decrypt Llega el monstruo_ COVID-19, gripe aviar y las plagas del capitalismo (Ensayo) (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Llega el monstruo: COVID-19, gripe aviar y las plagas del capitalismo (Ensayo) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.1.0: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.1.0: Looking for new default Kindle Key after 0.1 seconds
000d:err:module:__wine_process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v7.1.0: wine py.exe -3 does not exist
0009:err:module:__wine_process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v7.1.0: wine py.exe -3 does not exist
002d:err:module:__wine_process_init L"C:\\windows\\system32\\python3.exe" not found
002f:err:module:__wine_process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v7.1.0: wine python3.exe does not exist
DeDRM v7.1.0: wine python3.exe does not exist
0031:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
0033:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v7.1.0: wine python.exe does not exist
DeDRM v7.1.0: wine python.exe does not exist
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.1.0: Python3 exec found as wine C:\Python27\python.exe
DeDRM v7.1.0: Running kindlekey.py under Wine
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.1.0: Python3 exec found as wine C:\Python27\python.exe
DeDRM v7.1.0: Running kindlekey.py under Wine
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.1.0: Found and decrypted 0 key files
DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.1.0: Found and decrypted 0 key files
DeDRM v7.1.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 538, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 581, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Grandes granjas, grandes gripes (Ensayo) (Spanish Edition) to db in: 1.1
Added Llega el monstruo: COVID-19, gripe aviar y las plagas del capitalismo (Ensayo) (Spanish Edition) to db in: 1.7
Added 2 books in 4.1 seconds

**Comment by ElleKayEm** [comment]
If the books are tied to an E-ink Kindle (not a Fire), then you need to add the Kindle's serial number to DeDRM's customization.
