### ISSUE TITLE
Can't deDRM an AZW3 eInk book.

### ISSUE THREAD

**Issue by Yuuink** [apprenticeharper/DeDRM_tools#1657]
Hello. I put my kindle serial no. in the plugin and succesfully deDRM'd one azw3 book, downloaded for transfer by usb. When I tried with another book obtained the same way, it failed. Here's my log:

calibre Protokol ladění
calibre 5.14  embedded-python: True is64bit: False
Windows-8.1-6.3.9600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: cs
Successfully initialized third party plugins: DeDRM (7, 2, 0)
calibre 5.14  embedded-python: True is64bit: False
Windows-8.1-6.3.9600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: cs
Successfully initialized third party plugins: DeDRM (7, 2, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
[1.12] main UI initialized...
[1.12] Hiding splash screen
Starting QuickView
DeDRM v7.2.0: Trying to decrypt Elemental Fire.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.kfxdedrm", line 85
    traceback.print_exc()
                        ^
TabError: inconsistent use of tabs and spaces in indentation
[15.48] splash screen hidden
[15.48] Started up in 15.48 seconds with 36 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe7;\xcd\xf4n\xc5\xc8\x03/\xb6\x8dZ\xb0\xc7\xc8\xf1\xdd\\

\x89\x12\xeclE\x9b\x1e\xf1\xb9\xab\xa0!\xe26', b'C:\\Users\\[path to book]
Added Elemental Fire to db in: 0.3
Added 1 books in 1.0 seconds

**Comment by lnxme** [comment]
Looks like DeDRM v7.2.0 had an issue with whitespace that has been fixed in v7.2.1. So download v7.2.1 and install that and try again.

**Comment by Yuuink** [comment]
Thanks, it works now.
