### ISSUE TITLE
Adobe Digital Editions file fails to decrypt (most work fine)

### ISSUE THREAD

**Issue by lyndondrake** [apprenticeharper/DeDRM_tools#1661]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Adobe Digital Editions file fails to decrypt

Most of my ADE files are decrypting properly. This file is a one-day rental which doesn't seem to work. Debug log below.

## Log
<details><summary>Debug log</summary>

```
calibre Debug log
calibre 5.14  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.14  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 92.50000138921064 x 92.50000138921064
Using calibre Qt style: True
[0.00] Starting up...
[0.07] Showing splash screen...
[0.40] splash screen shown
[0.40] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.47] main UI initialized...
[1.47] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Early Narrative Christology the Lord in the Gospel of Luke-1.pdf
DeDRM v7.2.1: Early Narrative Christology the Lord in the Gospel of Luke-1.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[8.28] splash screen hidden
[8.28] Started up in 8.28 seconds with 0 books
Added Early Narrative Christology the Lord in the Gospel of Luke-1 to db in: 0.0
Added 1 books in 0.9 seconds
```

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by lyndondrake** [comment]
Fair enough. I just hate the Adobe reader and prefer reading in my own PDF reader. Through my library I have unlimited renewal on it.

**Comment by lyndondrake** [comment]
FYI Calibre 4.23 and DeDRM 6.8.1 are able to decrypt the file in question.

**Comment by samnlg** [comment]
> FYI Calibre 4.23 and DeDRM 6.8.1 are able to decrypt the file in question.

thank you. you save my days....the mentioned versions work! : ) I have tried latest versions but doesnt remove DRM of my ADE ebook.

**Comment by ElleKayEm** [comment]
@lyndondrake If you're all set, you can close this issue.

**Comment by ElleKayEm** [comment]
Do you have a purchased book with the same issue?  The policy here is not to provide DRM removal help with library, rental, or subscription books.

**Comment by lyndondrake** [comment]
No, I don't at the moment. Happy to close on that basis.
