### ISSUE TITLE
[QUESTION] Title

### ISSUE THREAD

**Issue by ageChapman** [apprenticeharper/DeDRM_tools#1662]
## CheckList

- [x] `The Title` and The `Log Title` are set correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
Calibre 5.14, DeDRM 7.2, AWZ (not KFX) not deDRMed

## Log
<details><summary>Sample import new AWZ book, attempt conversion for Kobo, failure log.</summary>

```log
calibre Debug log
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 0)
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.88] splash screen shown
[0.88] Initializing db...
[0.88] db initialized
[0.88] Constructing main UI...
[1.61] main UI initialized...
[1.61] Hiding splash screen
Starting QuickView
DeDRM v7.2.0: Trying to decrypt B0813VP369_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
[80.72] splash screen hidden
[80.72] Started up in 80.72 seconds with 15 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'tA?\xd3\xe3\x84|\xc8\xd3\xf9\xbb\x91\xdbV\x85W5T\x85\x10\x87$\xf11P8r\xb7\xfc\xcb\x10\xf4', b'\\\\filestore.soton.ac.uk\\users\\TinkerBell\\mydocuments\\My Kindle Content\\B0813VP369_EBOK.azw']
Added Christmas Belle to db in: 0.5
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.kfxdedrm", line 85
    traceback.print_exc()
                        ^
TabError: inconsistent use of tabs and spaces in indentatioAdded 1 books in 1.1 seconds
Worker Launch took: 0.09 seconds
Job: 0 Convert book 1 of 1 (Christmas Belle) finished
Convert book 1 of 1 (Christmas Belle)

	DeDRM v7.2.0: Trying to decrypt phpaypmd.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\TinkerBell\\AppData\\Local\\Temp\\calibre_y7d1zqb7\\7if3v42p.opf'

	  output_profile: 'kobo'

	  cover: 'C:\\Users\\TinkerBell\\AppData\\Local\\Temp\\calibre_y7d1zqb7\\nw96feec.jpeg'

	  verbose: 2

	Resolved conversion options

	calibre version: 5.14.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\TinkerBell\\AppData\\Local\\Temp\\calibre_y7d1zqb7\\nw96feec.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000012E18033760>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x0000012E18033DC0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\TinkerBell\\AppData\\Local\\Temp\\calibre_y7d1zqb7\\7if3v42p.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 632, in run

	  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt

	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

	  File "calibre\customize\zipplugin.py", line 192, in exec_module

	  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>

	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

	  File "calibre\customize\zipplugin.py", line 185, in exec_module

	  File "calibre\customize\zipplugin.py", line 181, in get_code

	  File "calibre_plugins.dedrm.kfxdedrm", line 85

	    traceback.print_exc()

	                        ^

	TabError: inconsistent use of tabs and spaces in indentation

	DeDRM v7.2.0: Trying to decrypt phpaypmd.azw
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 632, in run

	  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt

	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

	  File "calibre\customize\zipplugin.py", line 192, in exec_module

	  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>

	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

	  File "calibre\customize\zipplugin.py", line 185, in exec_module

	  File "calibre\customize\zipplugin.py", line 181, in get_code

	  File "calibre_plugins.dedrm.kfxdedrm", line 85

	    traceback.print_exc()

	                        ^

	TabError: inconsistent use of tabs and spaces in indentation

	InputFormatPlugin: MOBI Input running

	on C:\Users\TinkerBell\AppData\Local\Temp\calibre_y7d1zqb7\phpaypmd.azw

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm

	calibre.ebooks.DRMError: Christmas Belle



```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 7.2.1.
