### ISSUE TITLE
"error decrypting book session key - mismatched length": PDF decryption hangs, 100% CPU

### ISSUE THREAD

**Issue by Geremia** [apprenticeharper/DeDRM_tools#1666]
```
DeDRM v7.2.1: Trying to decrypt my_ACSM-downloaded_PDF.pdf
DeDRM v7.2.1: my_ACSM-downloaded_PDF.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key adobekey_1
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 127
bookkey[0] is 216
DeDRM v7.2.1: Exception when decrypting after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1622, in initialize_ebx
    raise ADEPTError('error decrypting book session key - mismatched length')
calibre_plugins.dedrm.ineptpdf.ADEPTError: error decrypting book session key - mismatched length
DeDRM v7.2.1: Failed to decrypt with key adobekey_1 after 0.6 seconds
DeDRM v7.2.1: Trying Encryption key adobekey_1-new
```
At this point DeDRM hangs, and Calibre is using 100% CPU.
DeDRM is able to decode other PDFs, just not the one above.

**Comment by Geremia** [comment]
I just had to wait. I'm not sure why it took so long. It was only a ~30MB PDF.

**Comment by ElleKayEm** [comment]
If you're on Windows, were you using 64-bit calibre?

**Comment by Geremia** [comment]
@ElleKayEm No, this was on 64bit Linux.
