### ISSUE TITLE
Unable to decrypt the kindle file

### ISSUE THREAD

**Issue by Pranu1k** [apprenticeharper/DeDRM_tools#1667]
calibre, version 5.5.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Pranay\Calibre Library\Unknown\B0823YN7PS EBOK (7)\B0823YN7PS EBOK - Unknown.azw. Click "Show details" for more info.

Failed to convert book: C:\Users\Pranay\Calibre Library\Unknown\B0823YN7PS EBOK (7)\B0823YN7PS EBOK - Unknown.azw with error:
DeDRM v7.2.1: Trying to decrypt B0823YN7PS EBOK - Unknown.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Pranay\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Pranay\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1849480756' and UserName 'Pranay'
DeDRM v7.2.1: Found 1 new key
DeDRM v7.2.1: Ultimately failed to decrypt after 4.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\Pranay\Calibre Library\Unknown\B0823YN7PS EBOK (7)\B0823YN7PS EBOK - Unknown.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 285, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 4.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 195, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 865, in viewer_main
  File "calibre\srv\render_book.py", line 856, in render_for_viewer
  File "calibre\srv\render_book.py", line 833, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
For KFX format, you need Kindle for PC 1.26 or earlier.  Alternately use one of the methods for avoiding KFX format.  See this post for details: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Cgpachore** [comment]
@ElleKayEm Can we remove DRM by Voucher File, I want to remove drm, in kindle content folder  there present folder of ebook that contains voucher file, MD file, also azw file.
The same log generated on my pc as in this issue,  in this log

 DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

Read this log in last I said DRM voucher is required so it is present in my kindle contents folder
So can we remove DRM by using that voucher file

**Comment by ElleKayEm** [comment]
@Cgpachore That's KFX format.  You will need the KFX Input plugin in addition to DeDRM.  And as I said above, Kindle for PC/Mac 1.26 or earlier.  Or see the link above for methods to avoid the KFX format.  If the book is only available in KFX and requires the latest Kindle app, then it can't be decrypted at this time.
