### ISSUE TITLE
Calibre Debug Log - Latest DeDRM not working for Amz - tmp1vzmxdc8.txt

### ISSUE THREAD

**Issue by GeorgeBradford** [apprenticeharper/DeDRM_tools#1669]
## CheckList

- [?] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Log
<details><summary>calibre Debug log</summary>

```log
calibre Debug log
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 38, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 38, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 38, 0) && KFX Input (1, 38, 0) && Set KFX metadata (from KFX Output) (1, 51, 0) && KFX Output (1, 51, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 0)
calibre 5.14 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 38, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 38, 0) && Amazon.com Multiple Countries (1, 0, 0) && KFX metadata reader (from KFX Input) (1, 38, 0) && KFX Input (1, 38, 0) && Set KFX metadata (from KFX Output) (1, 51, 0) && KFX Output (1, 51, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.7458193979933
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[0.83] main UI initialized...
[0.83] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.38.0: Importing C:\Users\drgeo\Documents\My Kindle Content\B08L9JPPSR_EBOK\B08L9JPPSR_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\drgeo\AppData\Local\Temp\calibre_l7q2iz4w\fcl6g95j.kfx-zip
DeDRM v7.2.1: Trying to decrypt fcl6g95j.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: fcl6g95j
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\drgeo\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\drgeo\AppData\Local\Amazon\Kindle\storage\.kinf2018
[58.25] splash screen hidden
[58.25] Started up in 58.25 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd7$g\x06\x80-\xaex;\x9a(\xbfL\xdc\x0ejwC\x99h@\x1a\xcf\x87\x84+\x93\xb5:\x9b@G', b'C:\\Users\\drgeo\\Documents\\My Kindle Content\\B08L9JPPSR_EBOK\\B08L9JPPSR_EBOK.azw']
Decrypted key file using IDString '1391641818' and UserName 'drgeo'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: fcl6g95j
Got DSN key from database default_key_1
Found 1 keys to try after 2.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.38.0: Packaging C:\Users\drgeo\AppData\Local\Temp\calibre_l7q2iz4w\fcl6g95j.kfx-zip
Processing container: B08L9JPPSR_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\drgeo\AppData\Local\Temp\calibre_l7q2iz4w\5jlhih4a_add_books\0\B08L9JPPSR_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08L9JPPSR_EBOK.azw has DRM and cannot be converted
Added Active Learning Online: Five Principles that Make Online Courses Come Alive to db in: 0.1
Added 1 books in 2.5 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Active Learning Online: Five Principles that Make Online Courses Come Alive) finished
Convert book 1 of 1 (Active Learning Online: Five Principles that Make Online Courses Come Alive)

	DeDRM v7.2.1: Trying to decrypt q0o5devr.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: q0o5devr
	Found 0 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\drgeo\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\drgeo\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1391641818' and UserName 'drgeo'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: q0o5devr
	Got DSN key from database default_key_1
	Found 1 keys to try after 2.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  pdf_serif_family: 'MS Shell Dlg 2'

	  output_profile: 'kindle'

	  pdf_sans_family: 'MS Shell Dlg 2'

	  cover: 'C:\\Users\\drgeo\\AppData\\Local\\Temp\\calibre_l7q2iz4w\\hzcdv10s.jpeg'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\drgeo\\AppData\\Local\\Temp\\calibre_l7q2iz4w\\zdhv8hdr.opf'

	Resolved conversion options

	calibre version: 5.14.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\drgeo\\AppData\\Local\\Temp\\calibre_l7q2iz4w\\hzcdv10s.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000023168EA9D00>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x0000023168EB51C0>,

	 'page_breaks_before': '/',

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier',

	 'pdf_mono_font_size': 16,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'MS Shell Dlg 2',

	 'pdf_serif_family': 'MS Shell Dlg 2',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\drgeo\\AppData\\Local\\Temp\\calibre_l7q2iz4w\\zdhv8hdr.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.2.1: Trying to decrypt q0o5devr.kfx-zip
	Decrypting KFX-ZIP ebook: q0o5devr
	Found 0 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\drgeo\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\drgeo\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1391641818' and UserName 'drgeo'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: q0o5devr
	Got DSN key from database default_key_1
	Found 1 keys to try after 2.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.29912343-3058-4ab9-b8a0-cf32f253222c.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\drgeo\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\drgeo\AppData\Local\Temp\calibre_l7q2iz4w\q0o5devr.kfx-zip

	Software versions: KFX Input 1.38.0, calibre 5.14 [64bit], Windows-10-10.0.19041

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\drgeo\AppData\Local\Temp\calibre_l7q2iz4w\q0o5devr.kfx-zip

	Processing container: B08L9JPPSR_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 105, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08L9JPPSR_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 125, in conv
t

	calibre.ebooks.DRMError: This book has DRM!


```
</details>

**Comment by Patitapetit** [comment]
You must use KINDLE FOR PC 1.17. I think You got 1.30

**Comment by GeorgeBradford** [comment]
Thank you Patitapetit! That resolved my issue. You rock!

**Comment by ElleKayEm** [comment]
There are also a few other methods for dealing with or avoiding KFX format.  See this for details:  https://www.mobileread.com/forums/showthread.php?t=283371

@GeorgeBradford 
If you're all set, you can close the issue.

**Comment by GeorgeBradford** [comment]
Thank you ElleKayEm!
