### ISSUE TITLE
failed conversion for kindle eInk 

### ISSUE THREAD

**Issue by homebroo** [apprenticeharper/DeDRM_tools#1670]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title
Just upgraded from Calibre version 4.23 w. older DeDRM which worked well. Upgrades look correct, but fail to convert to MOBI with log below. Thanks!

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.15 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 0)
calibre 5.15 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.58] splash screen shown
[0.58] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[1.73] main UI initialized...
[1.73] Hiding splash screen
Starting QuickView
DeDRM v7.2.0: Trying to decrypt Brimstone.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.kfxdedrm", line 85
    traceback.print_exc()
                        ^
TabError: inconsistent use of tabs and spaces in indentation
[20.14] splash screen hidden
[20.14] Started up in 20.14 seconds with 2397 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'-\x170\xcf\x17\x13\xb1~xO\x17\x12N\x80\xc6\xb9\x96\x96\xe3~\x17\xe1)\xfb\x1c\xd1\xd3\xee\xd1SX\x17', b'C:\\Users\\MainUser\\Desktop\\Brimstone.azw3']
Added Brimstone to db in: 0.3
Added 1 books in 0.8 seconds


```
</details>

**Comment by lnxme** [comment]
You need to upgrade the DeDRM plugin to v7.2.1 as your version has an error with tabs and spaces as reported in the log file.

**Comment by homebroo** [comment]
Thanks! Works like a champ.
