### ISSUE TITLE
DeDRM Not Working - Calibre 3.48, MacOS 10.12 Sierra

### ISSUE THREAD

**Issue by purpleinnej** [apprenticeharper/DeDRM_tools#1672]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Title

Not sure what additional details are needed.  Running Mac OS 10.12 Sierra (because I've upgraded to Mavericks twice and High Sierra once and hated it all 3 times so downgraded back to Sierra, but it may be time to bite the bullet there).  As such, cannot upgrade Calibre beyond 3.48.  Everything imported prior to 9 February DeDRMed as expected.  Everything imported 9 February or later will not open.  I get the error "This book is locked by DRM.  To learn more about DRM and why you cannot read or convert this book in Calibre, click here."

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 3.48  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.48  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.49] main UI initialized...
[1.49] Hiding splash screen
[1.49] splash screen hidden
[1.50] Started up in 1.50 seconds with 789 books
DeDRM v6.6.3: Trying to decrypt Keeper of the Lost Cities #2_ Exile - Shannon Messenger.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Exile (Keeper of the Lost Cities Book 2)
Found 14 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 14 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/Jenni/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.6.3: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 3.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Exile (Keeper of the Lost Cities Book 2) to db in: 0.1
Added 1 books in 4.1 seconds
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x1161d6d90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 827, in open
  File "site-packages/calibre/devices/usbms/device.py", line 396, in open_osx
  File "site-packages/calibre/devices/usbms/device.py", line 386, in osx_bsd_names
  File "site-packages/calibre/devices/usbms/device.py", line 346, in _osx_bsd_names
DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Worker Launch took: 0.0950939655304
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x1161d6d90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 827, in open
  File "site-packages/calibre/devices/usbms/device.py", line 396, in open_osx
  File "site-packages/calibre/devices/usbms/device.py", line 386, in osx_bsd_names
  File "site-packages/calibre/devices/usbms/device.py", line 346, in _osx_bsd_names
DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x1161d6d90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 827, in open
  File "site-packages/calibre/devices/usbms/device.py", line 396, in open_osx
  File "site-packages/calibre/devices/usbms/device.py", line 386, in osx_bsd_names
  File "site-packages/calibre/devices/usbms/device.py", line 346, in _osx_bsd_names
DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x1161d6d90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 827, in open
  File "site-packages/calibre/devices/usbms/device.py", line 396, in open_osx
  File "site-packages/calibre/devices/usbms/device.py", line 386, in osx_bsd_names
  File "site-packages/calibre/devices/usbms/device.py", line 346, in _osx_bsd_names
DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up

```
</details>

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then make sure you have the Kindle's serial number entered correctly in DeDRM's customization.  I'd recommend updating to DeDRM 6.8.1 which is the latest that will work with your version of calibre.

**Comment by purpleinnej** [comment]
SOLUTION: The serial number of the Kindle loaded in the DeDRM customization was an old kindle we no longer have.  Updated to include all of our current Kindle's.  I also updated to Mac OS 10.14, Calibre 5.16.1, and DeDRM 7.2.1.  I believe it was the serial number fix and not the updates that were the correction needed.
