### ISSUE TITLE
Failed to Decrypt.  Mac OSX 10.15.7. Calibre 5.16.1. DeDRM 7.2.1

### ISSUE THREAD

**Issue by Stellaz22** [apprenticeharper/DeDRM_tools#1674]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Ultimately failed to decrypt (used chmod -x to make kcr an azw, then tried to use DeDRM to remove DRM)</summary>

```log
FFF: DEBUG: 2021-04-20 12:41:07,372: calibre_plugins.fanficfare_plugin.fff_plugin(222): Plugin FanFicFare macmenuhack file_path:/Users/NAME/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
QLayout::addChildLayout: layout "" already has a parent
calibre Debug log
calibre 5.16.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && FanFicFare (4, 1, 0) && Import List (1, 5, 4) && Quality Check (1, 11, 2) && Reading List (1, 7, 2) && View Manager (1, 6, 0) && Zotero Metadata Importer (1, 0, 70)
calibre 5.16.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && FanFicFare (4, 1, 0) && Import List (1, 5, 4) && Quality Check (1, 11, 2) && Reading List (1, 7, 2) && View Manager (1, 6, 0) && Zotero Metadata Importer (1, 0, 70)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.46] db initialized
[0.46] Constructing main UI...
[2.75] main UI initialized...
[2.75] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B08BY8QNJW_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: BOOK
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2018 file: /Users/NAME/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'NAME'  on file  /Users/NAME/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'99875e7c72dd'
[4.65] splash screen hidden
[4.65] Started up in 4.65 seconds with 2616 books
Decrypted key file using IDString '99875e7c72dd' and UserName 'NAME'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: BOOK
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```
</details>

**Comment by ElleKayEm** [comment]
This book was downloaded with the current installation of Kindle for Mac on the same machine and user as calibre with DeDRM?

**Comment by Stellaz22** [comment]
Yes it was.

**Comment by ElleKayEm** [comment]
I'm not sure why it's not working then.  Fresh download and re-add to calibre.  Or possibly see if it will work with calibre 4.23 and DeDRM 6.8.1.  Be sure to read this post if you haven't already:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by Stellaz22** [comment]
I tried calibre 4.23 and DeDRM 6.8.1 and it worked! Thank you for the quick and helpful reply.
