### ISSUE TITLE
Will DeDRM convert epubs without the keys

### ISSUE THREAD

**Issue by One-dB-Brown** [apprenticeharper/DeDRM_tools#1676]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Converting epubs (Adobe Digital Editions) Without Keys

## Log
I am running a Windows 10 machine.  I have a lot of old Sony eReader books I purchased for my PRS 600.  Bought one of the original ones.  I have moved through 2 computers since I purchased these books, but I kept the books on an external hard drive.  Didn't have a lot of savvy when I moved them so I didn't know I needed a key file for each book.  I don't know my Sony account name of password, or even credit card info.

Is there any way to deDRM these books and convert them so I can read them on a Kindle?

Just to be sure, I did try to import a book and here is the error log.
Thanks
dB
calibre, version 5.16.1
ERROR: Loading book failed: Failed to open the book at C:\Users\Dave Brown\Calibre Library\James Patterson\1st to Die (11)\1st to Die - James Patterson.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\Dave Brown\Calibre Library\James Patterson\1st to Die (11)\1st to Die - James Patterson.epub with error:
DeDRM v7.1.0: Trying to decrypt 1st to Die - James Patterson.epub
DeDRM v7.1.0: Verifying zip archive integrity
DeDRM v7.1.0: 1st to Die - James Patterson.epub is a secure Adobe Adept ePub
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.1.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 356, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 391, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Could not locate privateLicenseKey
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\Dave Brown\Calibre Library\James Patterson\1st to Die (11)\1st to Die - James Patterson.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 642, in run
  File "calibre_plugins.dedrm.__init__", line 413, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
calibre.ebooks.DRMError: 1st to Die - James Patterson.epub
Exception ignored in: <function NativeFunction.__del__ at 0x0816EAD8>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0816EAD8>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
</details>

**Comment by ElleKayEm** [comment]
You would need Adobe Digital Editions authorized with your Adobe ID installed on the same machine and user as calibre with DeDRM.

**Comment by l-l-l-l-l-l** [comment]
Like ElleKayEm said, you don't need a Sony account, but an Adobe one. If you managed to download them, you should have one.

In case you don't know the password, you could try to reset it (the username is whatever email account you were using back then). Download ADE 2.0 (not 5, although they were working on support for that), then register it with that account. Once you do that, you can either DeDRM them without issue or you can authorize the Kindle (connect the Kindle to the PC with ADE opened, wait till it loads, then right click on the device and click on "authorize device") so it will read them even with DRM.

**Comment by ElleKayEm** [comment]
Kindles cannot be authorized with an Adobe ID or read epubs.  Maybe with an app on a Fire I suppose.

**Comment by One-dB-Brown** [comment]
Thanks very much for taking the time to respond.  I have a few account and I’m not sure which I used.  So it seems I should abandon the idea of converting these 157 books to mobi in Calibre.  I could do everything you said, but at the end of the day, can I get them in to Calibre.  The juice just may not be worth the sqeeze.

 

Thanks again,

 

Dave Brown

**Comment by ElleKayEm** [comment]
If you can still read the books on the Sony, there should be somewhere that you can see the email address for the Adobe ID it's authorized with.  Here's a page for resetting the password if needed:  https://helpx.adobe.com/manage-account/using/change-or-reset-password.html
