### ISSUE TITLE
Unable to convert KFX-ZIP

### ISSUE THREAD

**Issue by guszernial** [apprenticeharper/DeDRM_tools#1679]
Unable to convert KFX-ZIP to PDF
Kubuntu 21.04
calibre, version 5.16.1
DeDRM, version 7.0.0
KFX Inpt 1.39.0
Python 2.7.18
and Python 3.9.4

ERROR: KFX conversion failed: <p><b>Cannot convert Submundo (Spanish Edition)</b><br><br>Exception('Unable to determine KFX container type of ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res (00 05 16 07 00 02 00 00)')</p>

I then tried to update to DeDRM_tools to 7.2.1 from the downloaded zip file and I got:

calibre, version 5.16.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/tmp/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

Also ........
calibre 5.16.1  embedded-python: True is64bit: True
Linux-5.11.0-16-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.11.0-16-generic', '#17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 0, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Set KFX metadata (from KFX Output) (1, 51, 0) && KFX Output (1, 51, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 319, in add_plugin
  File "calibre/customize/ui.py", line 477, in add_plugin
  File "calibre/customize/ui.py", line 65, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/tmp/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.2.1.zip.  Load DeDRM_plugin.zip.

**Comment by guszernial** [comment]
OK I was able to install DeDRM 7.2.1 thanks ElleKayEm. Still unable to convert book, message is:
calibre, version 5.16.1 Cannot convert Submundo (Spanish Edition)</b><br><br>Exception('Unable to determine KFX container type of ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res (00 05 16 07 00 02 00 00)')", "level": "error", "det_msg": "", "title": "KFX conversion failed"}

[tej0nu8v_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/6373725/tej0nu8v_worker_redirect.log)
[tej0nu8v_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/6373706/tej0nu8v_worker_redirect.log)
[tej0nu8v_worker_redirect.log](https://github.com/apprenticeharper/DeDRM_tools/files/6373712/tej0nu8v_worker_redirect.log)

ERROR: KFX conversion failed: <p><b>Cannot convert Submundo (Spanish Edition)</b><br><br>Exception('Unable to determine KFX container type of ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res (00 05 16 07 00 02 00 00)')
</p>Convert book 1 of 1 (Submundo (Spanish Edition))

I added a gzipped version of the offending container:
[CR_PQM.zip](https://github.com/apprenticeharper/DeDRM_tools/files/6373766/CR_PQM.zip)

and here is the debug log:
DeDRM v7.2.1: Trying to decrypt dwlva8vg.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: dwlva8vg
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.65045895-e670-44e7-834a-ddbb71e0b12a.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
0009:err:module:__wine_process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v7.2.1: wine py.exe -3 does not exist
002c:err:module:__wine_process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v7.2.1: wine python3.exe does not exist
002e:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v7.2.1: wine python.exe does not exist
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.2.1: Python3 exec found as wine C:\Python27\python.exe
DeDRM v7.2.1: Running kindlekey.py under Wine
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.2.1: Found and decrypted 0 key files
DeDRM v7.2.1: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  cover: '/tmp/calibre_5.16.1_tmp_sf8c77ba/c4knsyyn.jpeg'
  pdf_mono_family: 'Nimbus Mono PS [urw]'
  read_metadata_from_opf: '/tmp/calibre_5.16.1_tmp_sf8c77ba/nft5sw40.opf'
  output_profile: 'kindle'
  pdf_sans_family: 'Nimbus Sans [urw]'
  verbose: 2
  pdf_serif_family: 'Nimbus Roman [urw]'
Resolved conversion options
calibre version: 5.16.1
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/tmp/calibre_5.16.1_tmp_sf8c77ba/c4knsyyn.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f3ecacfc2e0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7f3ecacfc820>,
 'page_breaks_before': '/',
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Nimbus Mono PS [urw]',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Nimbus Sans [urw]',
 'pdf_serif_family': 'Nimbus Roman [urw]',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/tmp/calibre_5.16.1_tmp_sf8c77ba/nft5sw40.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt dwlva8vg.kfx-zip
Decrypting KFX-ZIP ebook: dwlva8vg
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.65045895-e670-44e7-834a-ddbb71e0b12a.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 879, in decryptvoucher
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 758, in pkcs7unpad
  File "/tmp/calibre_5.16.1_tmp_sf8c77ba/1zzbypyeplugin_unzip/ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
0034:err:module:__wine_process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v7.2.1: wine py.exe -3 does not exist
0036:err:module:__wine_process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v7.2.1: wine python3.exe does not exist
0038:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v7.2.1: wine python.exe does not exist
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.2.1: Python3 exec found as wine C:\Python27\python.exe
DeDRM v7.2.1: Running kindlekey.py under Wine
wine: cannot find 'C:\Python27\python.exe'
DeDRM v7.2.1: Found and decrypted 0 key files
DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: KFX Input running
on /tmp/calibre_5.16.1_tmp_sf8c77ba/dwlva8vg.kfx-zip
Software versions: KFX Input 1.39.0, calibre 5.16.1, Linux-5.11.0-16-generic-x86_64-with-glibc2.2.5
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting /tmp/calibre_5.16.1_tmp_sf8c77ba/dwlva8vg.kfx-zip
Processing container: ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 105, in convert
    book.decode_book(retain_yj_locals=True)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 324, in get_container
    raise Exception("Unable to determine KFX container type of %s (%s)" % (datafile.name, bytes_to_separated_hex(data[:8])))
Exception: Unable to determine KFX container type of ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res (00 05 16 07 00 02 00 00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre_plugins.kfx_input.__init__", line 130, in convert
    raise ConversionUserFeedBack(
calibre.ebooks.conversion.ConversionUserFeedBack: {"msg": "<b>Cannot convert Submundo (Spanish Edition)</b><br><br>Exception('Unable to determine KFX container type of ._CR!PQM78K38357DB1VB1NR6TB9YM0H3.azw.res (00 05 16 07 00 02 00 00)')", "level": "error", "det_msg": "", "title": "KFX conversion failed"}

**Comment by guszernial** [comment]
Given no answer so far, and confirming that I'm Kubuntu 21.04, what version of wine (32 and/or 64-bit), windows and kindle should I be using to register and sync my kindle library?

**Comment by j-howell** [comment]
From your log there appear to be multiple things going wrong. One is a failure to run Python to obtain the key from your Kindle for PC installation.

>wine: cannot find 'C:\Python27\python.exe'

Did you install Python under Wine? See the Linux instructions in the [plugin help page](https://htmlpreview.github.io/?https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/DeDRM_Help.htm).
