### ISSUE TITLE
PDF ADE DRM fails to remove still in 7.2.1

### ISSUE THREAD

**Issue by Matthias84** [apprenticeharper/DeDRM_tools#1692]
## Title
Adobe Digital Editions DRM fails to remove in DeDRM 7.2.1

My setup is working fine on removing ADE DRM on epub ebooks. But I struggle on a PDF decrypted ebook.
It is a Linux Mint 20 with binary installer. I used a windows machine to download the ebooks via ADE and extract the key via the provided skript.
The fallback to a calibre 4.23 and DeDRM 6.8.1 worked fine, so there seem to be still an issue in key management or

_P.S: Thanks very much for the tool! It's the only way how I can read books during corona on my linux notebook to work with the texts!_

## Log
<details><summary>Log by calibre if I add a book and keep console open</summary>

```log
DeDRM v7.2.1: Trying to decrypt abook1.pdf
DeDRM v7.2.1: abook1.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key adobekey_1
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key adobekey_1 after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 466, in PDFDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'wine'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 433, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF

```
</details>

**Comment by EspyBounce** [comment]
Hello,
I had this exact same problem trying to remove the DRM on an Adobe Digital Editions 2.0 PDF. However, per the advice of Paul Durrant on Apprentice Alf's Wordpress, I was able to get it to work by using portable Calibre 4.23 with the 6.8.1 version of the DeDRM tools.

![image](https://user-images.githubusercontent.com/25762653/117630759-24c5fd80-b199-11eb-8eed-fa11f98b0d0c.png)

**Comment by daneelf** [comment]
I also tried this solution (portable Calibre 4.23 with the 6.8.1 version of the DeDRM tools) and it worked fine on Windows 10.
Although this doesn't seem to be working in Ubuntu OS. Nor does Calibre 5x and DeDRM 7.2.1 in Ubuntu.

**Comment by Ozwingle** [comment]
I had this same problem a few days ago. The solution above worked well, as a work around,on a Win 10 PC. 
Thanks for the help.

**Comment by babblecatproduction** [comment]
Same problem using MacOS. Also Kindle eBooks in KFX-ZIP format downloaded with the MacOS client are still protected after importing them in Calibre. My Workaround: using the Windows version of Calibre 4.23 with DeDRM 6.8.1 with **PlayOnMac** and import the Adobe key. Also Kindle for PC 1.17 works fine with **PlayOnMac**.

**Comment by ElleKayEm** [comment]
@daneelf Save the Adobe key from Windows calibre/DeDRM and import it into your Linux calibre/DeDRM setup.

@babblecatproduction Take a look at this info for Kindle for Mac:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
