### ISSUE TITLE
DeDRM wont' work 

### ISSUE THREAD

**Issue by mabras69** [apprenticeharper/DeDRM_tools#1704]
hello everyone
I have just tried to remove drm from two books that i bought from amazon.
It seems that calibre do not recognise them, and asks whith which program I'd like to open them.
There seem to be an issue with the voucher, but I'm not sure (it's my first time with deDRM)
Below you can find the log file:

## Log
calibre Log di debug
calibre 5.17  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Mass Search-Replace (1, 0, 2)
calibre 5.17  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Mass Search-Replace (1, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 84.66666666666667 x 84.66666666666667
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
DEBUG MassSearch/Replace:  Rebuilding menu
[0.72] main UI initialized...
[0.72] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\mabra\My Kindle Content\B074WBWTWN_EBOK\B074WBWTWN_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 18 file(s) as C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\egdgdex9.kfx-zip
DeDRM v7.2.1: Trying to decrypt egdgdex9.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: egdgdex9
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4ad4da0d-d567-4186-b430-40a795567b10.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mabra\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\mabra\AppData\Local\Amazon\Kindle\storage\.kinf2018
[15.47] splash screen hidden
[15.47] Started up in 15.47 seconds with 29 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'"\xa7\xffW\xd1\xc8X\x1b\xf3\xd18\xd1\x8e\xd5\x01\xfb\xeb%\xad\xfb\x925\xae\xf7b\xa2@\x018X\x94\'', b'C:\\Users\\mabra\\My Kindle Content\\B074WBWTWN_EBOK\\B074WBWTWN_EBOK.azw']
Decrypted key file using IDString '3135921088' and UserName 'mabra'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: egdgdex9
Got DSN key from database default_key_1
Found 1 keys to try after 2.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4ad4da0d-d567-4186-b430-40a795567b10.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\egdgdex9.kfx-zip
Processing container: B074WBWTWN_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\155io4_4_add_books\0\B074WBWTWN_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B074WBWTWN_EBOK.azw has DRM and cannot be converted
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\mabra\My Kindle Content\B07D4FH9H7_EBOK\B07D4FH9H7_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\oil4kdgp.kfx-zip
DeDRM v7.2.1: Trying to decrypt oil4kdgp.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: oil4kdgp
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.130218d9-6730-4ac2-932f-97b61a4a2f84.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mabra\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\mabra\AppData\Local\Amazon\Kindle\storage\.kinf2018
Added Play and Creativity in Psychotherapy (Norton Series on Interpersonal Neurobiology): 0 to db in: 0.1
Added 1 books in 2.9 seconds
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x94\x19\x94\xcb\x95\xdb\x1f\xe3\x0b\xfe\xe6\x9c\x04(\x93U\t*\xcd\r\xdf\x88\x93}\x7fB\x83\xed\xa1\xa8k\xaa', b'C:\\Users\\mabra\\My Kindle Content\\B07D4FH9H7_EBOK\\B07D4FH9H7_EBOK.azw']
Decrypted key file using IDString '3135921088' and UserName 'mabra'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: oil4kdgp
Got DSN key from database default_key_1
Found 1 keys to try after 2.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.130218d9-6730-4ac2-932f-97b61a4a2f84.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\oil4kdgp.kfx-zip
Processing container: B07D4FH9H7_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\mabra\AppData\Local\Temp\calibre_ezr49h8_\d7ni326g_add_books\0\B07D4FH9H7_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07D4FH9H7_EBOK.azw has DRM and cannot be converted
DeDRM v7.2.1: Trying to decrypt A tua insaputa (Italian Edition - John Bargh.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: A tua insaputa (Italian Edition - John Bargh
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.130218d9-6730-4ac2-932f-97b61a4a2f84.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\mabra\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\mabra\AppData\Local\Amazon\Kindle\storage\.kinf2018
Added A tua insaputa (Italian Edition) to db in: 0.0
Added 1 books in 2.4 seconds
Decrypted key file using IDString '3135921088' and UserName 'mabra'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: A tua insaputa (Italian Edition - John Bargh
Got DSN key from database default_key_1
Found 1 keys to try after 2.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.130218d9-6730-4ac2-932f-97b61a4a2f84.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\mabra\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging C:\Users\mabra\Biblioteca di calibre\John Bargh\A tua insaputa (Italian Edition) (36)\A tua insaputa (Italian Edition - John Bargh.kfx-zip
Processing container: B07D4FH9H7_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\mabra\Biblioteca di calibre\John Bargh\A tua insaputa (Italian Edition) (36)\A tua insaputa (Italian Edition - John Bargh.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_Added A tua insaputa (Italian Edition) to db in: 0.0
Added 1 books in 15.0 seconds
rror: Book container B07D4FH9H7_EBOK.azw has DRM and cannot be converted

thanks for helping!

**Comment by ElleKayEm** [comment]
Either use no later then Kindle for PC 1.26 or use one of the methods to avoid KFX format.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371
