### ISSUE TITLE
dedrm did not work with Amazon book  

### ISSUE THREAD

**Issue by hrayes** [apprenticeharper/DeDRM_tools#1705]
Calibre 5.17
installed DeDRM and tried to upload amazon book. it uploaded it but as a blank with unknown title or author.
when i tried to open it, it gave me an error 
Your help would be very much appreciated.
here is the error: Loading book failed.:

calibre, version 5.17.0
ERROR: Loading book failed: Failed to open the book at D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2921)\B00AK3YCJC EBOK - Unknown.azw. Click "Show details" for more info.

Failed to convert book: D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2921)\B00AK3YCJC EBOK - Unknown.azw with error:
DeDRM v7.2.1: Trying to decrypt B00AK3YCJC EBOK - Unknown.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\drray\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\drray\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1681152962' and UserName 'drray'
DeDRM v7.2.1: Found 1 new key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2921)\B00AK3YCJC EBOK - Unknown.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
calibre, version 5.17.0
ERROR: Loading book failed: Failed to open the book at D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2920)\B00AK3YCJC EBOK - Unknown.azw. Click "Show details" for more info.

Failed to convert book: D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2920)\B00AK3YCJC EBOK - Unknown.azw with error:
DeDRM v7.2.1: Trying to decrypt B00AK3YCJC EBOK - Unknown.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\drray\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\drray\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1681152962' and UserName 'drray'
DeDRM v7.2.1: Found 1 new key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on D:\CALIBRE LIBRARY\Unknown\B00AK3YCJC EBOK (2920)\B00AK3YCJC EBOK - Unknown.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 498, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
For the KFX format, you need to use no later then Kindle for PC 1.26 and leave the book file in its original folder structure.  See this post for avoiding or dealing with KFX format:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by hrayes** [comment]
Thank you for your help,.
I tried all the solutions suggested.
removed render-test.exe
added kfx plugin to Calibre>> it lists the book as kfx.zip format.
installed kindle 1.24.
nothing worked. Amazon downloads the same files *.Azw and DeDRM cannot resolve it.
could DeDRM getting more intelligent?

**Comment by ElleKayEm** [comment]
After installing Kindle for PC 1.24 and renaming or removing renderer-test, did you download a fresh copy of the book with it?  And is that installation of Kindle for PC on the same computer and user as calibre with DeDRM?

Amazon definitely does keep changing their DRM, but using the older app and getting the older format should work.

**Comment by hrayes** [comment]
thank you for your response.
i did all that you said. it is not working. kindle downloads the same files and you can not remove the key.
I also added a file to prevent kindle to update.  from mobile reader: https://www.mobileread.com/forums/showthread.php?t=283371

disable k4pc download.bat (501 Bytes, 4477 views)

it still does not work :).
I have been using DeDRM for years. No problem whatsoever. This time, it is not working.
We need DeDRM developers to look into it. :)

**Comment by ElleKayEm** [comment]
Still working for me.  Let's see a log from your latest setup.

**Comment by hrayes** [comment]
thank you. I tried again. redid everything calibre accepted it as kfx file. then converted it to epub. it worked.
thank you for your help 👍

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
