### ISSUE TITLE
Calibre 2.76.0 DeDRM 6.5.2 Barnes & Noble

### ISSUE THREAD

**Issue by billolney** [apprenticeharper/DeDRM_tools#171]
I have been having trouble getting Barnes & Noble books to remove DRM. I just downloaded the book 1/3/17. I think this may be related to my inability to retrieve a key. I do have a key from before when the email and credit card number worked.

I have changed my password to not have any special characters.

I tried installing nook study but I was unable to find a link on their site.

Log File:

calibre Debug log
calibre 2.76  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 2) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 8) && Ignoble Epub DeDRM (0, 1, 6) && Quality Check (1, 9, 11) && Clean Metadata (0, 0, 6)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Starting up...
Started up in 22.20 seconds with 591 books
DeDRM v6.5.2: Trying to decrypt 9781101886700.epub
DeDRM v6.5.2: Verifying zip archive integrity
DeDRM v6.5.2: “9781101886700.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.2: Trying Encryption key 1
Could not decrypt 3dt5ex.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 180, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.5.2: Failed to decrypt with key 1 after 0.1 seconds
DeDRM v6.5.2: Trying Encryption key 2
Could not decrypt 3dt5ex.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 180, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.5.2: Failed to decrypt with key 2 after 0.1 seconds
DeDRM v6.5.2: Trying Encryption key 3
Could not decrypt 3dt5ex.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 180, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.5.2: Failed to decrypt with key 3 after 0.1 seconds
DeDRM v6.5.2: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v6.5.2: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 291, in ePubDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.1 seconds.
Added Sleeping Giants to db in: 0.1
Added 1 books in 0.7 seconds
Worker Launch took: 0.109999895096

**Comment by ElleKayEm** [comment]
You're unable to add your current B&N key to the plugin customization?  It's been around 2 years since the credit card based keys stopped working.

Here's a direct link to NookStudy for Windows if you want to give that a try:
https://customer-care.s3.amazonaws.com/nook-study-install/NOOKstudy_Setup.exe

**Comment by billolney** [comment]
Correct it keeps telling me that it is unable to retrieve my key and to check everything. 
Also when I tried to login with nook study it kept telling me that the same thing.

**Comment by ElleKayEm** [comment]
Don't know if this would cause any issue, but you can uninstall the old individual format DeDRM plugins.

K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 8)
Ignoble Epub DeDRM (0, 1, 6)

**Comment by ElleKayEm** [comment]
Are you using Nook for PC to download the books?  Or the Windows 8 Nook app?

Here's Nook for PC if you don't have it:
http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by apprenticeharper** [comment]
This seems to have been solved. If not, please re-open.
