### ISSUE TITLE
Some Kindle files convert while others do not

### ISSUE THREAD

**Issue by captainnurple** [apprenticeharper/DeDRM_tools#1711]
## Some Kindle Titles Convert While Others Do Not

Hello, I have followed all the instructions for disabling KFX support in Mac. Deleting old copies of Kindle books, and then re-downloading them through the Kindle app. After following all these steps, *some* of my Kindle books successfully convert in Calibre, while others throw an error. Hoping someone can help me debug.

Steps I've taken: 
- Blocking use of KFX via `chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test`
- **Deleting** all old copies of books in Kindle for Mac app
- Re-downloading books, then importing into Calibre
- Attempting to convert
- Some books convert while others do not.

## Log
<details><summary>Sample log from one of the books that will not convert:</summary>

```log
calibre Debug log
calibre 5.18  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 5.18  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.00000193738563 x 129.00000193738563
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[0.93] main UI initialized...
[0.93] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /Users/murdm006/Library/Application Support/Kindle/My Kindle Content/B00CVS2J80_EBOK/B00CVS2J80_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B00CVS2J80_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Red Rising (The Red Rising Series, Book 1)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/murdm006/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'murdm006'  on file  /Users/murdm006/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'292035c36c6c'
[5.48] splash screen hidden
[5.48] Started up in 5.48 seconds with 41 books
Decrypted key file using IDString '292035c36c6c' and UserName 'murdm006'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Red Rising (The Red Rising Series, Book 1)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Red Rising (The Red Rising Series, Book 1) to db in: 0.0
Added 1 books in 1.4 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Try using calibre 4.23 and DeDRM 6.8.1.  After successfully decrypting a book with that, you should be able to update to the current versions.  Assume books that converted were already DRM-free.
