### ISSUE TITLE
I can't load the DeDRM plugin

### ISSUE THREAD

**Issue by psychicfashion** [apprenticeharper/DeDRM_tools#1712]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.
  5.10.1

---

## Log
<details><summary>Log Title</summary>

calibre, version 5.10.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Program Files\\Calibre2\\DeDRM_tools_6.8.0\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Program Files\\Calibre2\\DeDRM_tools_6.8.0\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

</details>
I can't load the plugin. I downladed it to the Calibre folder, and attempted to load it from there. What am I doing wrong?

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.2.1.zip and load DeDRM_plugin.zip.
