### ISSUE TITLE
Unable to Remove DRMs

### ISSUE THREAD

**Issue by profjg** [apprenticeharper/DeDRM_tools#1715]
Sometime last year I realized I could no longer remove the DRMs from my Amazon books after upgrading to Calibre 5.x. Here are some things I've tried to resolve the problem:

1. Reverting to Calibre 4.23.0 and DeDRM 6.8.1

2. Upgrading back to Calibre 5.18.0 and DeDRM 7.2.1

4. Reverting back to Calibre 4.23.0 and DeDRM 6.8.1

3. Blocking KFX via chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test 

4. Multiple uninstalls, deregisters, ebook deletions and downloads. 

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Mar  8 22:11:48 PST 2021; root:xnu-4903.278.65~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Mar  8 22:11:48 PST 2021; root:xnu-4903.278.65~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 92.0000013817 x 92.0000013817
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.51] splash screen shown
[0.51] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.83] main UI initialized...
[1.83] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt B07NSC6GJ7_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/jeffreygang/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '3da402b739b8' and UserName 'jeffreygang'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
[12.37] splash screen hidden
[12.37] Started up in 12.37 seconds with 63 books
Added B07NSC6GJ7 EBOK to db in: 0.0
Added 1 books in 1.0 seconds
Worker Launch took: 0.122651100159
Job: 0 Convert book 1 of 1 (B07NSC6GJ7 EBOK) finished
Convert book 1 of 1 (B07NSC6GJ7 EBOK)
	Conversion options changed from defaults:
	  output_profile: u'generic_eink'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/hg/61w4x1ns2xz_my0zzw0jftqh0000gq/C/calibre_4.23.0_tmp_lnC2Uw/IVJAzj.opf'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10a953090>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10a953490>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/hg/61w4x1ns2xz_my0zzw0jftqh0000gq/C/calibre_4.23.0_tmp_lnC2Uw/IVJAzj.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/hg/61w4x1ns2xz_my0zzw0jftqh0000gq/C/calibre_4.23.0_tmp_lnC2Uw/qfUftJ.azw
	Python function terminated unexpectedly: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 37, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 85, in __init__
	calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.


```
</details>

**Comment by ElleKayEm** [comment]
With calibre 4.23, be sure to install DeDRM 6.8.1.  This log shows 6.8.0.  This is also a KFX format book so re-apply the block for KFX format and redownload your book.

**Comment by profjg** [comment]
Ok, thank you. That is odd. I am using DeDRM_tools_6.8.1.zip downloaded directly from apprenticeharper
/DeDRM_tools. I wonder why the log shows 6.8.0?

**Comment by ElleKayEm** [comment]
Since the plugin file itself is always DeDRM_plugin.zip it's easy to go into the older folder and grab a previous version by mistake.  Also restart calibre after loading the plugin before re-adding books.

**Comment by ElleKayEm** [comment]
Ah, I just tried it myself.  The version number wasn't updated.  So that should be good as long as you get the KFX format downloads disabled.

**Comment by ZolaLa9** [comment]
If `chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test` is not working to disable KFX, try it again with sudo:

`sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test`

**Comment by profjg** [comment]
Thank you @ElleKayEm and @ZolaLa9! It worked.

My steps for others who may come across this problem:

1. Reinstalled MacOs Kindle 1.23

2. Took several steps to prevent automatic updates of MacOs Kindle 1.23

3. Reinstalled Calibre 4.23

4. Reinstalled DeDRM_tools_6.8.1

5. Ran sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test

6. Downloaded a Kindle book.

7. Opened in Calibre (Opened this time as AZW3 file)

8. Converted to Epub. Worked perfectly.

**Comment by fryingmonkey** [comment]
>>Reinstalled MacOs Kindle 1.23

@profjg where'd you get the installer for that? I'm stuck with 1.31.

**Comment by ElleKayEm** [comment]
Should work with 1.31 as long as you disable KFX downloads.

**Comment by fryingmonkey** [comment]
> Should work with 1.31 as long as you disable KFX downloads.

I've tried using a .aws file downloaded with 1.31 - no joy.

**Comment by profjg** [comment]
@fryingmonkey 1.23 is difficult to find. I have a .dmg file saved that I use. You may be able to find .torrent copy out there if you are comfortable using one. I didn't have luck with 1.31 but I didn't post a log fie here to determine the issue.

**Comment by ElleKayEm** [comment]
> I've tried using a .aws file downloaded with 1.31 - no joy.

See if this helps:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

Again, version of Kindle for Mac shouldn't be a problem with KFX downloads disabled.

**Comment by fryingmonkey** [comment]
@ElleKayEm thanks very much for your help!

That's the same method I originally found in the description here (that didn't stop me from trying it again to no avail):
[](https://www.youtube.com/watch?v=i7A8GuQS8kg)

Free Kindle DRM Removal 2021 (Calibre DeDRM Plugin for Mac)
Step1. Add DeDRM plugin to Calibre.
Step2. Add kfx-input plugin to Calibre.
Step3. Restart Calibre.
Step4. Open Kindle for Mac (version 1.30), if you have downloaded some books, delete them first.
Step5. copy and paste following command in Terminal , you need to input password to execute command:
 sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test
(if you don’t have password, then run this command: chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test)
Note: Running this command will cause Kindle crashes when you open a kindle book next time. If so, run this command: sudo chmod +x /Applications/Kindle.app/Contents/MacOS/renderer-test
Step6. Right-click to download Kindle books again. They will be .azw in "My Kindle Content" folder.
Step7. Add Kindle books to Calibre library, then the drm will be removed.
Step8. You can continue to convert Kindle AZW to PDF/EPUB with Calibre.

And still no good. I've even done it on a fresh install of 1.31. I'm gonna remove the KFX input plugin just to see what happens.

It's been a while (eh, a few months?) since I used DeDRM, but I've never had a problem with it before...

**Comment by ElleKayEm** [comment]
Let's look at a log and see if we can spot the problem:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by fryingmonkey** [comment]
calibre Debug log
calibre 5.19  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 5.19  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.85] main UI initialized...
[0.85] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /Users/fryingmonkey/Library/Application Support/Kindle/My Kindle Content/B087YW2R3M_EBOK/B087YW2R3M_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B087YW2R3M_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
**Found 0 keys to try after 0.1 seconds**
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'fryingmonkey'  on file  /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a6756e29e'
Decrypted key file using IDString '5d5a6756e29e' and UserName 'fryingmonkey'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[183.79] splash screen hidden
[183.79] Started up in 183.79 seconds with 24 books
Added Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love to db in: 0.0
Added 1 books in 1.2 seconds
Worker Launch took: 0.04 seconds
Job: 0 Convert book 1 of 1 (Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love) finished
Convert book 1 of 1 (Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love)
	DeDRM v7.2.1: Trying to decrypt zohk4dgy.azw
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'fryingmonkey'  on file  /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'5d5a6756e29e'
	Decrypted key file using IDString '5d5a6756e29e' and UserName 'fryingmonkey'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 4 keys to try after 0.5 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: '/var/folders/hb/6b5m9l2x6zd777vy694d_y7w0000gn/C/calibre_5.19.0_tmp_tqo8uov0/lll_8qsn.opf'
	  cover: '/var/folders/hb/6b5m9l2x6zd777vy694d_y7w0000gn/C/calibre_5.19.0_tmp_tqo8uov0/ebw5sie5.jpeg'
	  output_profile: 'ipad3'
	Resolved conversion options
	calibre version: 5.19.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/hb/6b5m9l2x6zd777vy694d_y7w0000gn/C/calibre_5.19.0_tmp_tqo8uov0/ebw5sie5.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1194cb070>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x1194cb4c0>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/hb/6b5m9l2x6zd777vy694d_y7w0000gn/C/calibre_5.19.0_tmp_tqo8uov0/lll_8qsn.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.2.1: Trying to decrypt zohk4dgy.azw
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'fryingmonkey'  on file  /Users/fryingmonkey/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'5d5a6756e29e'
	Decrypted key file using IDString '5d5a6756e29e' and UserName 'fryingmonkey'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 4 keys to try after 0.4 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/hb/6b5m9l2x6zd777vy694d_y7w0000gn/C/calibre_5.19.0_tmp_tqo8uov0/zohk4dgy.azw
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Eliminate Negative Thinking: How to Overcome Negativity, Control Your Thoughts, And Stop Overthinking. Shift Your Focus into Positive Thinking, Self-Acceptance, And Radical Self Love

**Comment by fryingmonkey** [comment]
So it's not finding the key. I have the key, but it's a hidden file and I can't add it manually to calibre.

**Comment by fryingmonkey** [comment]
@ElleKayEm I can't select the key in this dialog.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/29391095/120407871-cbb63900-c302-11eb-96ed-f7cc3a2f999b.png">

**Comment by ElleKayEm** [comment]
Get things working with calibre 4.23 and DeDRM 6.8.1.  Then you should be able to update back to current versions.  Getting the key initially still seems to be a problem for DeDRM 7.2.1 with Macs.

**Comment by fryingmonkey** [comment]
Done and done! Thanks for the help @ElleKayEm !  4.23 + 6.8.1 converted, then 5.19.0 + 7.2.1 did as well.

**Comment by profjg** [comment]
> Get things working with calibre 4.23 and DeDRM 6.8.1. Then you should be able to update back to current versions. Getting the key initially still seems to be a problem for DeDRM 7.2.1 with Macs.

So @ElleKayEm do I understand correctly, that I should be able to upgrade to 5.20.0 without DRM issues now? Assuming I just do the standard upgrade within Calibre and upgrade the plugins from there?

**Comment by ElleKayEm** [comment]
From what I've seen reported, I believe you'll be fine as long as your installation of Kindle for Mac hasn't changed.  The problem for DeDRM 7.2.1 seems to be the initial extraction of the key from Kindle for Mac.  Once DeDRM 6.8.1 has retrieved that, 7.2.1 doesn't seem to have any trouble decrypting the actual books.
