### ISSUE TITLE
Can't remove DRM from Kindle book

### ISSUE THREAD

**Issue by lmarianski** [apprenticeharper/DeDRM_tools#1716]
Log:
```
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/smart_device_app/driver.py", line 1957, in _startup_on_demand
    publish_zeroconf('calibre smart device client',
  File "/usr/lib/calibre/calibre/utils/mdns.py", line 168, in publish
    service = create_service(desc, service_type, port, properties, add_hostname,
  File "/usr/lib/calibre/calibre/utils/mdns.py", line 149, in create_service
    return ServiceInfo(
  File "/usr/lib/python3.9/site-packages/zeroconf/__init__.py", line 1807, in __init__
    if not type_.endswith(service_type_name(name, strict=False)):
TypeError: service_type_name() got an unexpected keyword argument 'strict'
calibre Dziennik debugowania
calibre 5.18  embedded-python: False is64bit: True
Linux-5.12.6-zen1-1-zen-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.12.6-zen1-1-zen', '#1 ZEN SMP PREEMPT Sun, 23 May 2021 00:45:48 +0000')
Python 3.9.5
Interface language: pl
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && EpubSplit (3, 0, 0) && Extract ISBN (1, 5, 0) && Goodreads (1, 5, 1) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Quality Check (1, 11, 2)
calibre 5.18  embedded-python: False is64bit: True
Linux-5.12.6-zen1-1-zen-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.12.6-zen1-1-zen', '#1 ZEN SMP PREEMPT Sun, 23 May 2021 00:45:48 +0000')
Python 3.9.5
Interface language: pl
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && EpubSplit (3, 0, 0) && Extract ISBN (1, 5, 0) && Goodreads (1, 5, 1) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Quality Check (1, 11, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
Key 'S' for shortcut Zapisz na dysku is already used by Scal wpisy książki, ignoring
[0.49] main UI initialized...
[0.49] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 8655
SMART_DEV (   0.03:  0.006) _startup_on_demand registration with bonjour failed
SMART_DEV (   0.04:  0.000) _startup_on_demand listening on port 8655
SMART_DEV (   0.04:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.04:  0.000) _startup_on_demand broadcast socket listening on port 54982

(python3:103598): GVFS-RemoteVolumeMonitor-WARNING **: 21:52:10.952: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
SMART_DEV (   1.04:  1.007) run All IP addresses {'lo': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'enp7s0': [{'addr': '192.168.0.100', 'netmask': '255.255.255.0', 'broadcast': '192.168.0.255'}], 'br-59afbbba209d': [{'addr': '172.24.0.1', 'netmask': '255.255.0.0', 'broadcast': '172.24.255.255'}], 'br-6f276e9729de': [{'addr': '172.20.0.1', 'netmask': '255.255.0.0', 'broadcast': '172.20.255.255'}], 'br-ce230082b4b4': [{'addr': '172.23.0.1', 'netmask': '255.255.0.0', 'broadcast': '172.23.255.255'}], 'br-18f9437d6fde': [{'addr': '172.22.0.1', 'netmask': '255.255.0.0', 'broadcast': '172.22.255.255'}], 'docker0': [{'addr': '172.17.0.1', 'netmask': '255.255.0.0', 'broadcast': '172.17.255.255'}]}
[11.73] splash screen hidden
[11.73] Started up in 11.73 seconds with 175 books
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /home/m00n/Dokumenty/My Kindle Content/B092SQRPTB_EBOK/B092SQRPTB_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /tmp/calibre_5.18.0_tmp_ycw0ekq7/q62p_x_2.kfx-zip
DeDRM v7.2.1: Trying to decrypt q62p_x_2.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: q62p_x_2
Got DSN key from database default_key
Got DSN key from database wine_key
Found 2 keys to try after 0.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.28d7c98e-259c-458a-89c0-f3e278900c40.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.18.0_tmp_ycw0ekq7/eeau5_ilplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.7 seconds
Installed Pythons found by C:\windows\py.exe Launcher for Windows
No Installed Pythons Found!

Requested Python version (3) not installed, use -0 for available pythons
Python 3 not found!
0614:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021E448
Nie uda�o si� uruchomi� aplikacji lub nie ma aplikacji skojarzonej z danym plikiem.
ShellExecuteEx nie powiod�o si�: Nie znaleziono pliku.

DeDRM v7.2.1: wine python3.exe is not python3
Fatal Python error: init_sys_streams: can't initialize sys standard streams
OSError: [WinError 6] Nieprawidłowy uchwyt

Current thread 0x0000062c (most recent call first):
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v7.2.1: wine C:\Python27\python.exe does not exist
DeDRM v7.2.1: Unable to find python3 executable in WINEPREFIX="/home/m00n/Dokumenty/KindleForPC/wineprefix"
DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 176, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging /tmp/calibre_5.18.0_tmp_ycw0ekq7/q62p_x_2.kfx-zip
Processing container: B092SQRPTB_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 176, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B092SQRPTB_EBOK.azw has DRM and cannot be converted
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
```
Book files: [B092SQRPTB_EBOK.zip](https://github.com/apprenticeharper/DeDRM_tools/files/6549329/B092SQRPTB_EBOK.zip)

(Note: I'm on linux and running Kindle for PC via WINE, and i managed to extract the key by setting up python in the wine prefix and the plugin config ui, dunno why this log says it can't detect python)

**Comment by ElleKayEm** [comment]
Easiest workaround is to temporarily install Windows calibre with DeDRM under wine where you have Kindle for PC.  After successfully decrypting a book with that, save the key and import it into the Linux calibre/DeDRM plugin customization.

**Comment by lmarianski** [comment]
@ElleKayEm i do already have the key from the kindle for pc install imported into Calibre
![image](https://user-images.githubusercontent.com/13919176/119731030-b8c0e600-be76-11eb-8124-46afacb419b4.png)

**Comment by lmarianski** [comment]
Interesting, when i launch calibre in debug mode, then the key cannot be found, (but the one i already have added stays there).
Here's the calibre (terminal) output when it *does* work:
```
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/smart_device_app/driver.py", line 1957, in _startup_on_demand
    publish_zeroconf('calibre smart device client',
  File "/usr/lib/calibre/calibre/utils/mdns.py", line 168, in publish
    service = create_service(desc, service_type, port, properties, add_hostname,
  File "/usr/lib/calibre/calibre/utils/mdns.py", line 149, in create_service
    return ServiceInfo(
  File "/usr/lib/python3.9/site-packages/zeroconf/__init__.py", line 1807, in __init__
    if not type_.endswith(service_type_name(name, strict=False)):
TypeError: service_type_name() got an unexpected keyword argument 'strict'
Python 3 not found!
Installed Pythons found by C:\windows\py.exe Launcher for Windows
No Installed Pythons Found!

Requested Python version (3) not installed, use -0 for available pythons
0144:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021E448
Nie udało się uruchomić aplikacji lub nie ma aplikacji skojarzonej z danym pliki
em.
ShellExecuteEx nie powiodło się: Nie znaleziono pliku.

DeDRM v7.2.1: wine python3.exe is not python3
DeDRM v7.2.1: Python3 exec found as wine python.exe
DeDRM v7.2.1: Running kindlekey.py under Wine
kindlekey.py v3.0
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\m00n\Local Settings\Application Data
Found K4PC 1.25+ kinf2018 file: C:\users\m00n\Local Settings\Application Data\Am
azon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1124073472' and UserName 'm00n'
Saved a key to Z:\home\m00n\.config\calibre\plugins\DeDRM\libraryfiles\winekeysd
ir\kindlekey1.k4i
DeDRM v7.2.1: Found and decrypted 1 key file
```

**Comment by ElleKayEm** [comment]
For KFX format, you need no later than Kindle for PC 1.26.  Or use one of the methods to avoid KFX downloads:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by lmarianski** [comment]
ah, thanks!
