### ISSUE TITLE
DRM Not Removing on Ubuntu 20.04 with Kindle Oasis?

### ISSUE THREAD

**Issue by BrodyStone21** [apprenticeharper/DeDRM_tools#1717]
My Kindle Oasis 2019 is updated to the latest version. Calibre is running 15.16.1, I can update to 5.18.0 if needed. I downloaded a book from Libby to my Kindle and now I'm attempting to copy the book and remove the DRM so that I can return it. 

If I right click the book under "Device" on Calibre and try to add it to my library it tells me that I can't because it's a .kfx file, so the next thing I tried was right-clicking it, saving it to the disk, and then manually importing that .kfx file, upon doing so it changes into a .kfx-zip file and if I try to convert it tells me that I am unable to do so because it is DRM protected. This happens even if I check the ignore errors box under the KFX Input plugin. I also tried putting the .kfx inside of the actual container directory and importing it but I am unable to import a directory. Below you can find my log.

```
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /tmp/calibre_5.16.1_tmp_84vo56_j/qepeikja.kfx-zip
DeDRM v7.2.1: Trying to decrypt qepeikja.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: qepeikja
Found 1 keys to try after 0.1 seconds
DeDRM v7.2.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 557, in KindleMobiDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging /tmp/calibre_5.16.1_tmp_84vo56_j/qepeikja.kfx-zip
Processing container: A Promised Land_B08GJZFBYV.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container A Promised Land_B08GJZFBYV.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_5.16.1_tmp_84vo56_j/knc3b_7x_add_books/0/A Promised Land_B08GJZFBYV.kfx-zip
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 433, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
```

EDIT: Closing this issue, you can't use KFX format books and getting the Kindle app to work through wine is incredibly difficult. I opted for just using my home Windows 10 PC.

**Comment by ElleKayEm** [comment]
You can't decrypt KFX format downloaded directly to a Kindle Oasis.

**Comment by BrodyStone21** [comment]
> You can't decrypt KFX format downloaded directly to a Kindle Oasis.

I'm assuming I would need to download the Kindle app via Wine on my system? Any idea how to do this? I tried looking online but saw nothing recent. I'm going to try and see what I can do.

**Comment by ElleKayEm** [comment]
I'll also mention that these tools are intended for purchased books.
