### ISSUE TITLE
ADE PDFs not decrypted

### ISSUE THREAD

**Issue by Vrumfondel** [apprenticeharper/DeDRM_tools#1719]
I just noted that ADE PDFs are not decrypted at all.

I found it working in Release 6.8.1

**Comment by nablak** [comment]
Similar problem here. Since few days I'm not able to decrypt epub or pdf files from internet archive. The files are all ADE and was able to decrypt them previously, my guess is that they changed the key.
I tried with Calibre 4.23 and DeDRM_plug 6.8.0 and 6.8.1, and Calibre 5.19 with DeDRM_plug 7.2.1 but none is working.
You can test this problem with any ADE file from internet archive, here is an example: https://archive.org/details/ugetsukenjimizog0000unse
Thanks

**Comment by ElleKayEm** [comment]
I'm still able to decrypt ADE epubs and pdfs with calibre 5.19 and DeDRM 7.2.1.  I think there are still problems with some pdfs and DeDRM 7.2.1, but calibre 4.23/DeDRM 6.8.1 should work.  If you have a purchased book with the same issue, I'll take a look at a log.

**Comment by Vrumfondel** [comment]
Here a log from an failed decode - maybe it helps ....

`DeDRM v7.2.0: Trying to decrypt XXXX.pdf
DeDRM v7.2.0: XXXX.pdf is a PDF ebook
DeDRM v7.2.0: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.0: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.0: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[8.08] splash screen hidden
[8.09] Started up in 8.09 seconds with 2810 books
Added Gregs Tagebuch 8 to db in: 1.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 639, in run
  File "calibre_plugins.dedrm.__init__", line 514, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 347, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001EB26292AF0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001EB26292AF0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is notAdded 1 books in 1.7 seconds
`

**Comment by ElleKayEm** [comment]
Have you tried with 7.2.1?

**Comment by Vrumfondel** [comment]
Same result with 7.2.1

**Comment by nablak** [comment]
> I'm still able to decrypt ADE epubs and pdfs with calibre 5.19 and DeDRM 7.2.1. I think there are still problems with some pdfs and DeDRM 7.2.1, but calibre 4.23/DeDRM 6.8.1 should work. If you have a purchased book with the same issue, I'll take a look at a log.

I don't know how to get the DeDRM log in Calibre, but using calibre 4.23/DeDRM 6.8.1 the pdf attached is not decrypted, and the same happens with all ADE pdf/epub from internetarchive.
[Ugetsu  Kenji Mizoguchi, director.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/6603923/Ugetsu.Kenji.Mizoguchi.director.pdf)

**Comment by ElleKayEm** [comment]
DeDRM is intended for purchased books.  So if you're having issues with those, I'll help with that.

**Comment by nablak** [comment]
> DeDRM is intended for purchased books. So if you're having issues with those, I'll help with that.

Ok, I did not know that DeDRM is intended only for purchased books. Thanks.

**Comment by 0lm** [comment]
Ive got the same problem. Calibre 5.21 64x with tools version 7.2.1 didnt work.
then i installed calibre 4.23 with tools version 6.8.1 and wir worked.

**Comment by ittegrat** [comment]
Same issue.
Calibre 5.21 / DeDRM 7.2.1 didnt work Calibre 4.23 / DeDRM 6.8.1 worked.
Here the log:
```
calibre Debug log
calibre 5.21 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Amazon.com Multiple Countries (1, 0, 0) && Kobo Books (1, 8, 2)
calibre 5.21 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Amazon.com Multiple Countries (1, 0, 0) && Kobo Books (1, 8, 2)
...
DeDRM v7.2.1: Trying to decrypt xxxx.pdf
DeDRM v7.2.1: xxxx.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 2.0 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 2.0 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 2.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masteRunning file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Extensions: frozenset({'pdf'})
Exception ignored in: <function NativeFunction.__del__ at 0x0116B8E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0116B8E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
```
