### ISSUE TITLE
Unable to DeDRM a title on Kindle 1.26.1/Calibre 5.0/DeDRM 7.2.1 on MacOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by Lireur** [apprenticeharper/DeDRM_tools#1722]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>June 1, 2021 Log</summary>

```log
calibre Debug log
calibre 5.0  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 5.0  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
Loaded cached store plugin for: Библио.бг at version: 2
Loaded cached store plugin for: Project Gutenberg at version: 8
[1.16] main UI initialized...
[1.16] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /Users/sachindrasanam/Library/Application Support/Kindle/My Kindle Content/B08SHCKL4B_EBOK/B08SHCKL4B_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/t_t1x8q3.kfx-zip
DeDRM v7.2.1: Trying to decrypt t_t1x8q3.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: t_t1x8q3
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3c9bcc07-c3e8-49e7-a9eb-2a6c2609227c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/sachindrasanam/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'sachinsanam'  on file  /Users/sachindrasanam/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'3da4022e1004'
[4.75] splash screen hidden
[4.75] Started up in 4.75 seconds with 0 books
Decrypted key file using IDString '3da4022e1004' and UserName 'sachinsanam'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: t_t1x8q3
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 1 keys to try after 0.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3c9bcc07-c3e8-49e7-a9eb-2a6c2609227c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/1vb_7_rcplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/t_t1x8q3.kfx-zip
Processing container: B08SHCKL4B_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_5.0.0_tmp_xlr2c904/278t4xpk_add_books/0/B08SHCKL4B_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08SHCKL4B_EBOK.azw has DRM and cannot be converted
```
</details>

**Comment by ElleKayEm** [comment]
Try with first with calibre 4.23 and DeDRM 6.8.1.  If you get that working, then you should be able to update back to your current versions.

**Comment by Lireur** [comment]
Tried your recommendation, and I'm receiving the same error during conversion that the book is still protected:

Traceback (most recent call last):
  File "site-packages/calibre/gui2/store/loader.py", line 91, in load_cache
  File "site-packages/calibre/gui2/store/loader.py", line 178, in load_object
  File "<string>", line 47
    yield from self._do_search(url, max_results, timeout)
             ^
SyntaxError: invalid syntax
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.4.0', 'Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.42] splash screen shown
[0.43] Initializing db...
[0.44] db initialized
[0.44] Constructing main UI...
Loaded cached store plugin for: Project Gutenberg at version: 8
Failed to load cached store: biblio
[1.60] main UI initialized...
[1.60] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing /Users/sachindrasanam/Library/Application Support/Kindle/My Kindle Content/B08SHCKL4B_EBOK/B08SHCKL4B_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/KlBfob.kfx-zip
DeDRM v6.8.0: Trying to decrypt KlBfob.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: KlBfob
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3c9bcc07-c3e8-49e7-a9eb-2a6c2609227c.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/sachindrasanam/Library/Application Support/Kindle/storage/.kinf2018
[4.07] splash screen hidden
[4.08] Started up in 4.08 seconds with 1 books
Decrypted key file using IDString '3da4022e1004' and UserName 'sachinsanam'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: KlBfob
Got DSN key from database default_key_1
Found 1 keys to try after 0.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3c9bcc07-c3e8-49e7-a9eb-2a6c2609227c.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/KlBfob.kfx-zip
Processing container: B08SHCKL4B_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
KFXDRMError: Book container B08SHCKL4B_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/7P3ERk_add_books/0/B08SHCKL4B_EBOK.kfx-zip
Added The White Coat Investor's Guide for Students: How Medical and Dental Students Can Secure Their Financial Future (The White Coat Investor Series) to db in: 0.1
Added 1 books in 2.0 seconds
Worker Launch took: 0.201761007309
Job: 0 Convert book 1 of 1 (The White Coat Investor's Guide for Students: How Medical and Dental Students Can Secure Their Financial Future (The White Coat Investor Series)) finished
Convert book 1 of 1 (The White Coat Investor's Guide for Students: How Medical and Dental Students Can Secure Their Financial Future (The White Coat Investor Series))
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'generic_eink'
	  cover: u'/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/zlbgQl.jpeg'
	  read_metadata_from_opf: u'/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/n8C33F.opf'
	Resolved conversion options
	calibre version: 4.23.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/zlbgQl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x114fd6090>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x114fd6490>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/n8C33F.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on /var/folders/1f/nl0zmwmn1vx_px046n68yt_m0000gn/C/calibre_4.23.0_tmp_RowidX/hJBats.kfx-zip
	Software versions: KFX

**Comment by ElleKayEm** [comment]
You removed the book from calibre and Kindle?  Then redownloaded and added a fresh copy to calibre?

**Comment by Lireur** [comment]
Yes, that's right

**Comment by ElleKayEm** [comment]
Try disabling KFX downloads.  See method 2 here:  https://www.mobileread.com/forums/showthread.php?t=283371

And Mac specific info here:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by Lireur** [comment]
Method 2 from your link worked well. I thought I had disable renderer-test, but the fact that the kfx-zip kept appearing as the file format should have clued me in that I did not properly disable it.
