### ISSUE TITLE
Can't DeDRM a Kindle book

### ISSUE THREAD

**Issue by J-Majha** [apprenticeharper/DeDRM_tools#1724]
I was recently gifted an ebook for Kindle, but own a Kobo. I'm trying to deDRM the Kindle book to convert it for my other device instead, but Calibre hasn't been removing the DRM from the file at all. Pretty new to this, so apologies if I'm missing something obvious~ Thanks for the help!

calibre Debug log
calibre 5.19  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 5.19  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[0.91] main UI initialized...
[0.91] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\j_000\Documents\My Kindle Content\B004H1TQGC_EBOK\B004H1TQGC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\J_~1\AppData\Local\Temp\calibre_47a8obu4\9_1vbmqf.kfx-zip
DeDRM v7.2.1: Trying to decrypt 9_1vbmqf.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 9_1vbmqf
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\j_000\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\j_000\AppData\Local\Amazon\Kindle\storage\.kinf2018
[7.83] splash screen hidden
[7.83] Started up in 7.83 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc3$5\xd9\x07"\xa1\xd9\xc0}\x7f\xa1\x1a:a\xd7\xe7<\xdbP\x99\x1c\x13\x01\x9d\xc4\xbc\x0e\x93Z\xb41', b'C:\\Users\\j_000\\Documents\\My Kindle Content\\B004H1TQGC_EBOK\\B004H1TQGC_EBOK.azw']
Decrypted key file using IDString '3231736076' and UserName 'J'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 9_1vbmqf
Got DSN key from database default_key_1
Found 1 keys to try after 3.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 3.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging C:\Users\J_~1\AppData\Local\Temp\calibre_47a8obu4\9_1vbmqf.kfx-zip
Processing container: B004H1TQGC_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\J_~1\AppData\Local\Temp\calibre_47a8obu4\yfalnw34_add_books\0\B004H1TQGC_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 3.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B004H1TQGC_EBOK.azw has DRM and cannot be converted
Added Deathless to db in: 1.2
Added 1 books in 5.0 seconds
Worker Launch took: 0.01 seconds
Job: 0 Convert book 1 of 1 (Deathless) finished
Convert book 1 of 1 (Deathless)

	DeDRM v7.2.1: Trying to decrypt h4zxzpfc.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: h4zxzpfc
	Found 0 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\j_000\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\j_000\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3231736076' and UserName 'J'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: h4zxzpfc
	Got DSN key from database default_key_1
	Found 1 keys to try after 4.2 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 4.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\J_~1\\AppData\\Local\\Temp\\calibre_47a8obu4\\xqjkz6zm.opf'

	  output_profile: 'kobo'

	  cover: 'C:\\Users\\J_~1\\AppData\\Local\\Temp\\calibre_47a8obu4\\7jprvsog.jpeg'

	  verbose: 2

	Resolved conversion options

	calibre version: 5.19.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\J_~1\\AppData\\Local\\Temp\\calibre_47a8obu4\\7jprvsog.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07A1B1C0>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x07A1B4F0>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\J_~1\\AppData\\Local\\Temp\\calibre_47a8obu4\\xqjkz6zm.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 4.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.2.1: Trying to decrypt h4zxzpfc.kfx-zip
	Decrypting KFX-ZIP ebook: h4zxzpfc
	Found 0 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\j_000\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\j_000\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3231736076' and UserName 'J'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: h4zxzpfc
	Got DSN key from database default_key_1
	Found 1 keys to try after 4.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.77f5d92d-1233-4580-b85b-7d6ef2ed177d.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\j_000\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 4.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 4.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\J_~1\AppData\Local\Temp\calibre_47a8obu4\h4zxzpfc.kfx-zip

	Software versions: KFX Input 1.39.0, calibre 5.19, Windows-10-10.0.19041

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\J_~1\AppData\Local\Temp\calibre_47a8obu4\h4zxzpfc.kfx-zip

	Processing container: B004H1TQGC_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 105, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B004H1TQGC_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 125, in conv
t

	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Either avoid KFX format or use Kindle for PC 1.26 or earlier.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by J-Majha** [comment]
That worked! Thanks so much!
