### ISSUE TITLE
Unable to install builds 7.2.0 and 7/2/1 into Win64 calibre 5.19 or 5.20

### ISSUE THREAD

**Issue by FredThompsonII** [apprenticeharper/DeDRM_tools#1725]
Here's an example of what I get when i try to load build 7.2.0 or 7.2.1 into Win64 calibre 5.19 or 5.20:

calibre, version 5.20.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Working\\Newest\\Downloads\\DeDRM_tools_7.2.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.20 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && Package KFX (from KFX Input) (1, 39, 0) && Calibre Power Search Plugin (2, 0, 0) && Find Duplicates (1, 8, 5) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && KindleUnpack - The Plugin (0, 83, 0) && Library Codes (1, 0, 50) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Working\\Newest\\Downloads\\DeDRM_tools_7.2.0.zip' is invalid. It does not contain a top-level __init__.py file

So...how to get this to install?

**Comment by Maverynthia** [comment]
YOu have to open the .zip file and there will be the calibre plugin. The ZIP you see here is like the plugins and the readmes
![MWSnap020](https://user-images.githubusercontent.com/2293000/120748020-0e793c00-c4d0-11eb-8abb-5a3fda6e6f6a.png)

**Comment by ElleKayEm** [comment]
As Maverynthia said, unzip DeDRM_tools_7.2.1.zip.  (Don't use 7.2.0)  Load DeDRM_plugin.zip.

**Comment by Skrappysgram** [comment]
Thanks for this!!  I had the same problem with both versions as well.
