### ISSUE TITLE
[QUESTION] KFX DRM note being removed. Problem with Kindle for PC ebook.

### ISSUE THREAD

**Issue by AceMaker81** [apprenticeharper/DeDRM_tools#1729]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

I used the Amazon Prime to get a book under "Prime Reading" facility to get about 11 books. I was able to add 10 books in Calibre but one of those books will not convert. I tried restarting the Calibre and also added the book directly from the Kindle Source Folder, it added to the Calibre Library but it is still DRM enabled. A log created using the debug mode is attached for your reference. Kindly help. 

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.21  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
calibre 5.21  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.7458193979933
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.69] splash screen shown
[0.69] Initializing db...
[0.86] db initialized
[0.86] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.39.0: Importing C:\Users\Sumit\SkyDrive\Documents\My Kindle Content\B0774CTNQG_EBOK\B0774CTNQG_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Sumit\AppData\Local\Temp\calibre_njo9fcex\_nn_2lyr.kfx-zip
DeDRM v7.2.1: Trying to decrypt _nn_2lyr.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: _nn_2lyr
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Sumit\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Sumit\AppData\Local\Amazon\Kindle\storage\.kinf2018
[130.23] splash screen hidden
[130.23] Started up in 130.23 seconds with 1687 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'Y[\xda/\\r\xb6\x99^$\xa8\xf0\x1a4\xcf\xddL\x96\x10\x9b|\x91\x1as-G7\xac\x083\xe7\x9d', b'C:\\Users\\Sumit\\SkyDrive\\Documents\\My Kindle Content\\B0774CTNQG_EBOK\\B0774CTNQG_EBOK.azw']
Decrypted key file using IDString '3744849440' and UserName 'Sumit'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: _nn_2lyr
Got DSN key from database default_key_1
Found 1 keys to try after 5.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 5.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.39.0: Packaging C:\Users\Sumit\AppData\Local\Temp\calibre_njo9fcex\_nn_2lyr.kfx-zip
Processing container: B0774CTNQG_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\Sumit\AppData\Local\Temp\calibre_njo9fcex\fwvwmmn7_add_books\0\B0774CTNQG_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 5.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 85, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0774CTNQG_EBOK.azw has DRM and cannot be converted
Added The Heartfulness Way: Heart-Based Meditations for Spiritual Transformation to db in: 3.9
Added 1 books in 15.3 seconds
Worker Launch took: 0.11 seconds
Job: 0 Convert book 1 of 1 (The Heartfulness Way: Heart-Based Meditations for Spiritual Transformation) finished
Convert book 1 of 1 (The Heartfulness Way: Heart-Based Meditations for Spiritual Transformation)

	DeDRM v7.2.1: Trying to decrypt vl4wsng0.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: vl4wsng0
	Got DSN key from database default_key
	Found 1 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Sumit\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Sumit\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3744849440' and UserName 'Sumit'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: vl4wsng0
	Got DSN key from database default_key_1
	Found 1 keys to try after 5.8 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 5.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  verbose: 2

	  preserve_cover_aspect_ratio: True

	  read_metadata_from_opf: 'C:\\Users\\Sumit\\AppData\\Local\\Temp\\calibre_njo9fcex\\yb0wzdye.opf'

	  output_profile: 'tablet'

	  cover: 'C:\\Users\\Sumit\\AppData\\Local\\Temp\\calibre_njo9fcex\\lhby5nzi.jpeg'

	Resolved conversion options

	calibre version: 5.21.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Sumit\\AppData\\Local\\Temp\\calibre_njo9fcex\\lhby5nzi.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07D701F0>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x07D706B8>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': True,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Sumit\\AppData\\Local\\Temp\\calibre_njo9fcex\\yb0wzdye.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 5.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	DeDRM v7.2.1: Trying to decrypt vl4wsng0.kfx-zip
	Decrypting KFX-ZIP ebook: vl4wsng0
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Sumit\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Sumit\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3744849440' and UserName 'Sumit'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: vl4wsng0
	Got DSN key from database default_key_1
	Found 1 keys to try after 5.7 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdaadf98-04e2-41c8-8310-f0a7e3fe3476.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Sumit\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\Sumit\AppData\Local\Temp\calibre_njo9fcex\vl4wsng0.kfx-zip

	Software versions: KFX Input 1.39.0, calibre 5.21, Windows-10-10.0.19041

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\Sumit\AppData\Local\Temp\calibre_njo9fcex\vl4wsng0.kfx-zip

	Processing container: B0774CTNQG_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 105, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 319, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0774CTNQG_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1105, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 125, 
 convert

	calibre.ebooks.DRMError: This book has DRM!

```
</details>

**Comment by ElleKayEm** [comment]
DeDRM is intended for purchased books.

**Comment by ElleKayEm** [comment]
If you cannot download it in non-KFX format or with Kindle for PC 1.26 or earlier, then DeDRM probably won't work even if you purchase it.
