### ISSUE TITLE
Can't find key (both dedrm 6.8.0 and 7.2.1) 

### ISSUE THREAD

**Issue by appleplants** [apprenticeharper/DeDRM_tools#1730]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

### DeDRM: 6.8.0/7.2.1

I own the book and tried switching to dedrm 6.8.0, but calibre's still unable to find the key. I'm on mac catalina, and I completely understand if this is an issue with the computer, as I know that mac's been a huge pain lately. I really appreciate any help!

## Log 7.2.1
<details><summary>Log Title</summary>

```log

calibre Debug log
calibre 5.21  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && KindleUnpack - The Plugin (0, 83, 0) && Obok DeDRM (7, 2, 1)
calibre 5.21  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && KindleUnpack - The Plugin (0, 83, 0) && Obok DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.53] main UI initialized...
[1.53] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス).azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス)
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.3 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[15.25] splash screen hidden
[15.25] Started up in 15.25 seconds with 3 books
Added 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス) to db in: 0.1
Added 1 books in 0.8 seconds
Worker Launch took: 0.02 seconds


```
</details>

## Log 6.8.0
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Obok DeDRM (6, 7, 0) && KindleUnpack - The Plugin (0, 83, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 39, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 39, 0) && KFX metadata reader (from KFX Input) (1, 39, 0) && KFX Input (1, 39, 0) && Obok DeDRM (6, 7, 0) && KindleUnpack - The Plugin (0, 83, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.10] main UI initialized...
[1.10] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス)
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.3 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[3.16] splash screen hidden
[3.17] Started up in 3.17 seconds with 2 books
Added 女装してめんどくさい事になってるネクラとヤンキーの両片想い 4巻 (ブレイドコミックス) to db in: 0.3
Added 1 books in 2.3 seconds
Worker Launch took: 0.084114074707

```
</details>

**Comment by ElleKayEm** [comment]
If this book is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.

**Comment by appleplants** [comment]
It worked! Thank you so much, you're absolute magic!
