### ISSUE TITLE
Problem with AZW from Kindle[QUESTION] Title

### ISSUE THREAD

**Issue by eddy10957** [apprenticeharper/DeDRM_tools#1731]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

I followed the guide but seems like DeDRM can't decrypt. 

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.21  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.21  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 96.0 x 96.0
physicalDpi: 110.96245733788396 x 110.83636363636363
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.80] main UI initialized...
[0.80] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B07WTM4RTS_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\vivim\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\vivim\AppData\Local\Amazon\Kindle\storage\.kinf2018
[3.05] splash screen hidden
[3.05] Started up in 3.05 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe29\x1a`\x0b\x94\xc7\xff\x05\xb6\x18\xd2\x84.\x95/\xa0\xc8\x94\xe9\xef\xb3\x8f4\x8d\xf4\x88IK`\xd9r', b'C:\\Users\\vivim\\Documents\\My Kindle Content\\B07WTM4RTS_EBOK\\B07WTM4RTS_EBOK.azw']
Decrypted key file using IDString '884811996' and UserName 'vivim'
DeDRM v7.2.1: Found 1 new key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 289, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 503, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in _init_
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\Added B07WTM4RTS EBOK to db in: 0.1
Added 1 books in 6.7 seconds
Worker Launch took: 0.00 seconds
```
</details>

**Comment by ElleKayEm** [comment]
You will need to disable KFX downloads.  Or go back to no later then Kindle for PC 1.26 and install the KFX Input plugin.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by eddy10957** [comment]
Thanks, i didn't  disable kfx cause i saw that the file that was downloaded was .azw, my bad sorry. Anyway worked fine, thank you so much.

**Comment by ElleKayEm** [comment]
It was KFX format in your log.  AZW is a generic Amazon book extension that the Kindle app uses regardless of format.
