### ISSUE TITLE
[QUESTION] TitleHi! I have a problem with a DRM

### ISSUE THREAD

**Issue by huguiyo** [apprenticeharper/DeDRM_tools#1733]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
<!I have a problem with a DRM>

## Log
<details><summary>Log Title</summary>

```log
calibre Registro de depuración
calibre 5.0 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.0 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 84.62536585365852 x 84.81391304347825
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.73] main UI initialized...
[0.73] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Conoce tu cerebro para aprender a aprender_ Guía para jóvenes estudiantes (Spanish Edition) (2).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Conoce tu cerebro para aprender a aprender: Guía para jóvenes estudiantes (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Hugo\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[5.34] splash screen hidden
[5.34] Started up in 5.34 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'GQ\x9cl\x81#\xddl\x97\x89\xfe\x1c+\xde\x8f\xccn\xb0 O\xf5UJZ@\xbf\x1a\x96x\xf1\xe0\xf2', b'C:\\Users\\Hugo\\Downloads\\Conoce tu cerebro para aprender a aprender_ Gui\xcc\x81a para jo\xcc\x81venes estudiantes (Spanish Edition) (2).azw3']
Added Conoce tu cerebro para aprender a aprender: Guía para jóvenes estudiantes (Spanish Edition) to db in: 0.3
Added 1 books in 0.8 seconds

```
</details>

**Comment by ElleKayEm** [comment]
If your book is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.
