### ISSUE TITLE
adobekey.py has some fundamental problems

### ISSUE THREAD

**Issue by benthetechguy** [apprenticeharper/DeDRM_tools#1737]
I tried to run [adobekey.pyw](https://github.com/apprenticeharper/DeDRM_tools/blob/master/Other_Tools/DRM_Key_Scripts/Adobe_Digital_Editions/adobekey.pyw) on my windows PC like the guide told me to and there are some problems.

First of all, it says it's a python2 application, but everyone else is saying it's python3.
Second, there are syntax errors all over the place.

So I gave up with that and tried running the other [adobekey.py](https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/adobekey.py) directly, but then I get this:
```
Traceback (most recent call last):
  File "C:\Users\Ben\Downloads\adobekey.py", line 180, in <module>
    AES = _load_crypto()
  File "C:\Users\Ben\Downloads\adobekey.py", line 174, in _load_crypto
    AES = loader()
  File "C:\Users\Ben\Downloads\adobekey.py", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
```
Any ideas? I've tried all sorts of stuff and nothing is working.

**Comment by ElleKayEm** [comment]
Use calibre and the DeDRM plugin?

**Comment by benthetechguy** [comment]
I'm running Calibre on my Linux PC and I can't run Adobe Digital Editions on it, so I need to extract the key from this Windows PC to use it on the Linux one.

**Comment by ElleKayEm** [comment]
I'd still suggest using calibre and the plugin.  Save the key.  Import it into the Linux setup.

**Comment by ae0579** [comment]
I'm not an expert, but I suggest the next:

These instructions have been tested with Wine 5.0 on Ubuntu 20.04 and Calibre 4.23 (the reason is that with this version I know how to do a manual installation)

    1. Download the software we are going to use
        a) ADE_2.0_Installer.exe can be found in:
           http://download.adobe.com/pub/adobe/digitaleditions/ADE_2.0_Installer.exe 
        b) dotnetfx35.exe can be found in: https://www.microsoft.com/es-ES/download/details.aspx?id=25150
        c) DeDRM_tools_6.7.0.zip can be found in: https://github.com/apprenticeharper/DeDRM_tools/releases 
        d) If there is any problem, we’ll need too:
            1. Python 2.7.X for Windows (x86) from 
                   https://www.python.org/ftp/python/2.7.13/python-2.7.13.msi 
            2.  PyCrypto 2.1 for 32bit Windows and Python 2.7 from 
                   http://www.voidspace.org.uk/python/modules.shtml#pycrypto 
                   (PyCrypto downloads as a zip file. You will need to unzip it.)
           
    2. Install Wine for 32-bit x86 as says in https://wiki.winehq.org/Ubuntu Don’t use wine from Ubuntu repository. Run

	sudo dpkg --add-architecture i386 
	wget -nc https://dl.winehq.org/wine-builds/winehq.key
	sudo apt-key add winehq.key

Add wine repository. For Ubuntu 20.04 is:

	sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/ groovy main' 
	sudo apt update
	sudo apt install --install-recommends winehq-stable

If apt complains about missing dependencies, install them, then repeat the last two steps (update and install). Run

	wine winecfg

		Choose Windows 7, some times wine choose XP

    3. Instal Winetricks from Ubuntu Software and run
       
	winetricks -q corefonts && winetricks -q windowscodecs

    4. Go to winetricks and choose default => Install a Windows DLL or component => Install dotnet35 SP1
    5. Go where you have the software and run

	wine dotnetfx35.exe
	wine ADE_2.0_Installer.exe

    6. Configure Adobe license in AdobeDigitalEdition

    7. Now install DeDRM_Calibre_plugin  
        a) Unzip DeDRM_tools_6.7.0 .zip
        b) Open calibre's Preferences dialog => Click on the "Plugins" button => Next => click on the button, "Load plugin from file" => Navigate to the unzipped DeDRM_tools folder and, in the folder "DeDRM_calibre_plugin", find the file "DeDRM_plugin.zip" => Click to select the file and select "Open" => Click "Yes" in the "Are you sure?" dialog box => Click the "OK" button in the "Success" dialog box.

Now, Calibre should work with DeDRM and Adobe. If there is any problem I suggest install manually version 6.6.3 (so, you'll have to download too it)

    8. Install Python 2.7.x with right button => install with wine. Accept all defaults.
    9. Install PyCrypto 2.1. Accept all defaults. Go where you downloaded Pycrypto and run
       
           wine pycrypto-2.1.0.win32-py2.7.exe
       
    10. Unzip DeDRM_plugin.zip and copy adobekey.pyw from Other_Tools/DRM_Key_Scripts/Adobe_Digital_Editions to somewhere in drive_c, such as ~/.wine/drive_c/DeDRM/
           
           wine 'C:\Python27/python.exe' 'C:\DeDRM/adobekey.pyw'
       
    12. Import the resulting key file to the Calibre plugin through the Adobe Digital Editions ebooks option.
       
And now it should work.

    13. If you install version 6.8.0 you must remove the adobe key for Adobe and now it should work.
   
I hope it's useful for you.

**Comment by benthetechguy** [comment]
Thanks, that worked. Still can't get it to work under native windows though, even in a VM.
