### ISSUE TITLE
Cannot install 7.2.1 on Calibre 5.21

### ISSUE THREAD

**Issue by ADBlues** [apprenticeharper/DeDRM_tools#1739]
Got what it seems to be a Python error while attempting to load the plugin on Calibre.
OS is MacOS 15.4
Calibre is version 5.21
DeDRM is 7.2.1.

Error is below, let me know  if you need more info.
Thanks!

```
calibre, version 5.21.0
ERRORE: Eccezione non gestita: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.21  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0) && Set KFX metadata (from KFX Output) (1, 53, 0) && KFX Output (1, 53, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 477, in add_plugin
  File "calibre/customize/ui.py", line 65, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```

**Comment by lnxme** [comment]
Please see [https://github.com/apprenticeharper/DeDRM_tools/issues/1551](url) for help

**Comment by ElleKayEm** [comment]
Make sure you are trying to install 7.2.1. It looks like you tried to install 6.8.1 or earlier.

**Comment by ADBlues** [comment]
Thanks, those help solved (my bad, did not check the correctness of the plugin folder).
