### ISSUE TITLE
Problems to DeDRM Adobe ebok file

### ISSUE THREAD

**Issue by Conopus** [apprenticeharper/DeDRM_tools#1747]
I installed Caliblri then DeDRM plagin. Drug and drop ebook extracted from ACSM file. But DeDRP didn't work. I got log from calibri debug mod see below. How can I fix the problem?

calibre Журнал ошибок
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.39] splash screen shown
[1.39] Initializing db...
[1.45] db initialized
[1.45] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.2 obok::action_err.py - loading translations
[2.92] main UI initialized...
[2.92] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Le Sexe sous l’Empire.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Le Sexe sous l’Empire.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
Could not decrypt qjevxjsp.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 418, in decryptBook
TypeError: object of type 'int' has no len()

DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Exception ignored in: <function NativeFunction.__del__ at 0x087AD6E8>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x087AD6E8>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[8.77] splash screen hidden
[8.77] Started up in 8.77 seconds with 1 books
Added Le Sexe sous l’Empire to db in: 0.2
Added 1 books in Worker Launch took: 0.00 seconds

**Comment by ElleKayEm** [comment]
Do you have Adobe Digital Editions (that was used to download the book) authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

**Comment by Conopus** [comment]
> Do you have Adobe Digital Editions (that was used to download the book) authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

Seller send me file. I got the file via e-mail. So it wasnt download with ADE and the license do not associated with my Adobe ID. And I opened the file using ADE computer authorisation, then authorization was erased, and file is broken now. I can not open and use the book I bought.

**Comment by ElleKayEm** [comment]
DeDRM relies on getting the key associated with your Adobe ID.  If you cannot read the book in ADE, then DeDRM cannot unlock it either.
