### ISSUE TITLE
Can't DeDRM AZW files in MacOS

### ISSUE THREAD

**Issue by dmedina2015** [apprenticeharper/DeDRM_tools#1748]
My environment:
- MacOS Big Sur 11.4
- Calibre 5.22.1
- DeDRM_tools 7.2.1
- Kindle for Mac 1.30.0 (already disabled KFX using command line)

My problem:
When downloading books in Kindle for Mac the books are in AZW format. But when trying to import them in Calibre, the DeDRM doesn't work. I think it is something related to decryption key, but I dont know how to solve it, because in the wiki its said that MacOS doesn't need any customization in DeDRM_tools. 

Logfile: 
```
calibre Log de Debug
calibre 5.22.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
calibre 5.22.1  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 128.00000192236715
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
[1.55] main UI initialized...
[1.55] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.40.0: Importing /Volumes/Home/daniel/Documents/My Kindle Content/B00OEI3TKM_EBOK/B00OEI3TKM_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B00OEI3TKM_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Scrum - a arte de fazer o dobro de trabalho na metade do tempo
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Volumes/Home/daniel/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Volumes/Home/daniel/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'daniel'  on file  /Volumes/Home/daniel/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c177618249fd'
[4.48] splash screen hidden
[4.49] Started up in 4.49 seconds with 0 books
Decrypted key file using IDString 'c177618249fd' and UserName 'daniel'
trying username  b'daniel'  on file  /Volumes/Home/daniel/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c177618249fd'
Decrypted key file using IDString 'c177618249fd' and UserName 'daniel'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Scrum - a arte de fazer o dobro de trabalho na metade do tempo
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 7 keys to try after 1.4 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

```

**Comment by ElleKayEm** [comment]
DeDRM 7.2.1 has trouble initially retrieving the Kindle for Mac key.  Try calbre 4.23 and DeDRM 6.8.1.  If you able to get that working, you should be able to upgrade back to your current versions of calibre and DeDRM.

**Comment by dmedina2015** [comment]
Thank you so much. Its working now!
