### ISSUE TITLE
Cannot customize plugin

### ISSUE THREAD

**Issue by jonlewis** [apprenticeharper/DeDRM_tools#1749]
I'm on an M1 Macbook Air running MacOS Big Sur (11.3), using v7.2.1 of the plugin with Calibre 5.5.0
When I click the Customize Plugin button, I get the following error and info:
(Thanks for this plugin and for your help!)

calibre, version 5.5.0
ERROR: Unhandled exception: <b>OSError</b>:Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38-darwin.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-darwin.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-darwin.so: stat() failed with errno=20, Trying '_raw_ecb.abi3.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so: stat() failed with errno=20, Trying '_raw_ecb.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so: stat() failed with errno=20

calibre 5.5  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.4.0', 'Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 290, in double_clicked
  File "calibre/gui2/preferences/plugins.py", line 371, in modify_plugin
  File "calibre/customize/__init__.py", line 158, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 656, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 166, in _load_crypto_pycrypto
    from Crypto.Cipher import AES as _AES
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "bypy-importer.py", line 154, in exec_module
  File "Crypto/Cipher/_mode_ecb.py", line 35, in <module>
  File "Crypto/Util/_raw_api.py", line 308, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cpython-38-darwin.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-darwin.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.cpython-38-darwin.so: stat() failed with errno=20, Trying '_raw_ecb.abi3.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.abi3.so: stat() failed with errno=20, Trying '_raw_ecb.so': dlopen(/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so, 6): no suitable image found.  Did find:
	/Applications/calibre.app/Contents/Frameworks/plugins/python-lib.bypy.frozen/Crypto/Util/../Cipher/_raw_ecb.so: stat() failed with errno=20

**Comment by ElleKayEm** [comment]
Update to the current version of calibre.

**Comment by jonlewis** [comment]
That worked, thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
