### ISSUE TITLE
Cannot install DeDRM 7.2.1

### ISSUE THREAD

**Issue by sneumeister** [apprenticeharper/DeDRM_tools#1757]
## Log
<details><summary>Log Installer</summary>

```log
calibre, version 5.22.1
FEHLER: Unbehandelter Ausnahmefehler: InvalidPlugin:The plugin in 'C:\Users\stephan\Downloads\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level init.py file

calibre 5.22.1 [64bit] embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Traceback (most recent call last):
File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
File "calibre\customize\ui.py", line 477, in add_plugin
File "calibre\customize\ui.py", line 65, in load_plugin
File "calibre\customize\zipplugin.py", line 284, in load
File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\Users\stephan\Downloads\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level init.py file
```
</details>

[Downloaded 7.2.1 ZIP file from here](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.2.1)

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_7.2.1.zip.  Load DeDRM_plugin.zip

**Comment by sneumeister** [comment]
Worked. Thanks.
