### ISSUE TITLE
[Obok plugin] cannot convert epub 2 drm

### ISSUE THREAD

**Issue by hasezoey** [apprenticeharper/DeDRM_tools#1764]
i have recently purchased 2 books (total now: 2) (manga(epub 3 DRM) and light novel(epub 2 DRM)), where the manga successfully gets decrypted, but the light novel not (metadata is OK, but content is a mess)

System:
Window 10 (Pro) x64 (inside an qemu-VM, where the host is Linux)

- installed plugins in calibre (both, `DeDRM_plugin` and `Obok_plugin`)
- calibre version is `5.23`
- plugin versions are `7.2.1`

<details>
<summary>calibre 5.23 log</summary>

```
calibre Fehlerdiagnoseprotokoll
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.17134 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 3.8.5
Windows: ('10', '10.0.17134', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.17134 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 3.8.5
Windows: ('10', '10.0.17134', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.97638376383763 x 96.09458128078816
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.36] splash screen shown
[0.36] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1441, in set_metadata
  File "calibre\db\cache.py", line 1364, in set_cover
  File "calibre\db\backend.py", line 1532, in set_cover
  File "calibre\utils\img.py", line 288, in save_cover_data_to
  File "calibre\utils\img.py", line 196, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[2.31] splash screen hidden
[2.33] Started up in 2.33 seconds with 1 books
Running Obok DeDRM v7.2.1
DEBUG:    4.4 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
C:\Users\hasezoey\AppData\Local\Temp\tmpavqxi566
DEBUG:    4.4 got kobodir C:\Users\hasezoey\AppData\Local\Kobo\Kobo Desktop Edition
Found 4 possible keys to try.
DEBUG:    6.7 BookListTableWidget:get_books - book_num: 1
DEBUG:    6.7 BookListTableWidget:get_books - book: Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1
DEBUG:    6.7 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v7.2.1 - Decrypting Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1
Trying key:  b'Sorry, Wont provide the key'
Success!
DEBUG:    7.0 DecryptAddProgressDialog::do_book_action - decrypted book: 'Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1'
Obok DeDRM v7.2.1 - Added Didn't I Say to Make My Abilities Average in the Next Life?! Volume 1
Obok DeDRM v7.2.1 - wrapping up results.
Worker Launch took: 0.01 seconds
```

</details>

also tested:
- calibre version `4.23`
- plugin versions `6.8.1`

Note: in 4.23, the output is still a mess, but a different mess (different characters on view)

<details>
<summary>calibre 4.23 log</summary>

```
calibre Fehlerdiagnoseprotokoll
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.9763837638 x 96.0945812808
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.34] main UI initialized...
[1.34] Hiding splash screen
[14.20] splash screen hidden
[14.20] Started up in 14.20 seconds with 1 books
Running Obok DeDRM v6.7.0
DEBUG:   16.4 didn't find device
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\hasezoey\appdata\local\temp\tmpvfrinb
DEBUG:   16.4 got kobodir C:\Users\hasezoey\AppData\Local\Kobo\Kobo Desktop Edition
Found 4 possible keys to try.
DEBUG:   19.5 BookListTableWidget:get_books - book_num: 1
DEBUG:   19.5 BookListTableWidget:get_books - book: Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1
DEBUG:   19.5 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.7.0 - Decrypting Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1
Trying key:  0eSorry, Wont provide the key
Success!
DEBUG:   19.8 DecryptAddProgressDialog::do_book_action - decrypted book: 'Didn't I Say To Make My Abilities Average In The Next Life?! Light Novel Vol. 1'
Traceback (most recent call last):
  File "site-packages\calibre\db\cache.py", line 1352, in set_metadata
  File "site-packages\calibre\db\cache.py", line 1275, in set_cover
  File "site-packages\calibre\db\backend.py", line 1456, in set_cover
  File "site-packages\calibre\utils\img.py", line 287, in save_cover_data_to
  File "site-packages\calibre\utils\img.py", line 199, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Obok DeDRM v6.7.0 - Added Didn't I Say to Make My Abilities Average in the Next Life?! Volume 1
Obok DeDRM v6.7.0 - wrapping up results.
Worker Launch took: 0.169999837875
```

</details>

Note: in both versions, the output is the correct file size (and from my knowledge contains all required files, but content is not decrypted)

PS: i probably cannot use the ACSM way, because i already had them(both books) activated with ADB 4.5

**Comment by ElleKayEm** [comment]
As far as I'm aware, Kobo doesn't use the hardened Adobe DRM so you could give that method a try.

For Obok, see if the version in this comment works (with calibre 5.x):  https://github.com/apprenticeharper/DeDRM_tools/issues/1718#issuecomment-874246085

**Comment by hasezoey** [comment]
> For Obok, see if the version in this comment works (with calibre 5.x): #1718 (comment)

i have tried to apply #1691, but it did not change the output (i also tried the file from https://github.com/apprenticeharper/DeDRM_tools/issues/1718#issuecomment-874246085)

just to say it again, i have 2 books, where one is EPUB 3 DRM, which successfully got converted, and one that is EPUB 2 DRM, which does not convert correctly
Note: that is the format that kobo says it is on the bottom of the page (`eBook Details` -> `Download options`)

PS: i may also need to mention that Obok says that the EPUB 2 DRM one is `drm-free` (the green symbol, not the red one)

> As far as I'm aware, Kobo doesn't use the hardened Adobe DRM so you could give that method a try.

i tried to install 1.7 (`winetricks adobe_diged`), and it errors with the acsm files with `Error #2038`, but installing 2.x manually, it starts and shows again

when using adobe-digitaleditons 2.x, and calibre 5.x (non-wine) with plugin, it worked, both successfully removed the drm (on both books)
(after some struggle, because at first it didnt wanna work on python27, installed python39, but then pycrypto didnt wanna install, reverted back to python27 and it worked)

but this does not really solve the original issue of obok_plugin not being able to do it for that one book

**Comment by ElleKayEm** [comment]
How about this one: https://github.com/apprenticeharper/DeDRM_tools/issues/1718#issuecomment-869744457

**Comment by hasezoey** [comment]
no #1753 did not work for me (or the attached file from https://github.com/apprenticeharper/DeDRM_tools/issues/1718#issuecomment-869744457)
