### ISSUE TITLE
DeDRM 7.2.1 on Win10 Calibre 5.23 shows calibre reader with black screen

### ISSUE THREAD

**Issue by chrisrm9208** [apprenticeharper/DeDRM_tools#1765]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title

'Lies Sleeping' by Ben Aaronovitch, an AZW3 file from Amazon

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && Find Duplicates (1, 8, 9) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0) && Obok DeDRM (6, 7, 0)
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && Find Duplicates (1, 8, 9) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.04726735598227 x 96.07565011820331
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.73] splash screen shown
[0.73] Initializing db...
[1.03] db initialized
[1.03] Constructing main UI...
[2.31] main UI initialized...
[2.31] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 134, in __init__
  File "calibre\gui2\ui.py", line 152, in init_iaction
  File "calibre\customize\__init__.py", line 626, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
ModuleNotFoundError: No module named 'StringIO'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
DeDRM v7.2.1: Trying to decrypt Lies Sleeping The Seventh Rivers of London novel (A Rivers of London novel Book 7).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Lies Sleeping: The Seventh Rivers of London novel (A Rivers of London novel Book 7)
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID o1x/yFgzYL.
Decrypting. Please wait . . . . . done
Decryption succeeded after 0.1 seconds
DeDRM v7.2.1: Finished after 0.1 seconds
Failed to write backup metadata for id: 10535 once
Failed to write backup metadata for id: 10535 again, giving up
Failed to write backup metadata for id: 10535 once
Failed to write backup metadata for id: 10535 again, giving up
Failed to write backup metadata for id: 10535 once
[13.97] splash screen hidden
[13.97] Started up in 13.97 seconds with 1441 books
Failed to write backup metadata for id: 10535 again, giving up
Failed to write backup metadata for id: 10534 once
Failed to write backup metadata for id: 10534 again, giving up
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xdb\xd6~\x0cr\x81\x0c#\x178+a\xd2\xae\xde\x9b\xbb]D\xe1~\x87\x82\xf1\x86\xb9\x06~\xbb\x19\xfc\xec', b'C:\\Users\\chrismitchell\\Downloads\\Lies Sleeping The Seventh Rivers of London novel (A Rivers of London novel Book 7).azw3']
Failed to write backup metadata for id: 10534 once
Added Lies Sleeping: The Seventh Rivers of London novel (A Rivers of London novel Book 7) to   File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 119, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\The October Man_ A Rivers of London Novella (10535)\\metadata.opf'
Traceback (most recent call last):
  File "calibre\db\backend.py", line 1734, in write_backup
  File "os.py", line 223, in makedirs
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\db\backup.py", line 113, in do_one
  File "calibre\db\cache.py", line 76, in call_func_with_lock
  File "calibre\db\cache.py", line 1298, in write_backup
  File "calibre\db\backend.py", line 1738, in write_backup
  File "polyglot\builtins.py", line 61, in reraise
  File "calibre\db\backend.py", line 1729, in write_backup
PermissionError: [Errno 13] Permission denied: '\\\\Heap\\Chris\\Calibre Library\\Ben Aaronovitch\\False Value (10534)\\metadata.opf'
Added 1 books in 1.7 seconds
Failed to write backup metadata for id: 10534 again, giving up
Failed to write backup metadata for id: 10535 once
Failed to write backup metadata for id: 10535 again, giving up
Failed to write backup metadata for id: 10534 once
```
</details>

**Comment by ElleKayEm** [comment]
DRM seems to be successfully removed.  Looks like some issue with calibre, not DeDRM.

**Comment by chrisrm9208** [comment]
OK,, that's probably true; I can load it to my antique keyboard Kindle and it displays just fine after the DeDRM process, so probably Calibre...
