### ISSUE TITLE
DeDRM fails on book

### ISSUE THREAD

**Issue by BarnT** [apprenticeharper/DeDRM_tools#1767]
Find the log below!
Let me know if you need more info!

```
calibre Debug log
calibre 5.23  embedded-python: True is64bit: True
Linux-5.4.0-77-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-77-generic', '#86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.23  embedded-python: True is64bit: True
Linux-5.4.0-77-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-77-generic', '#86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.25263157894737
physicalDpi: 157.8252427184466 x 157.65517241379308
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.04] splash screen shown
[0.04] Initializing db...
[0.05] db initialized
[0.05] Constructing main UI...
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1127, resource id: 8528388, major code: 40 (TranslateCoords), minor code: 0
DeDRM v7.2.1: Trying to decrypt Popular climbing routes in Slovenia.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “Popular climbing routes in Slovenia.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Couldn't decrypt after {2:.1f} seconds. DRM free perhaps?".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
[10.66] splash screen hidden
[10.66] Started up in 10.66 seconds with 1 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=73400343', '--filename=/home/barnabas/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Added Popular climbing routes in Slovenia to db in: 0.1
Added 1 books in 0.4 seconds
```

**Comment by ElleKayEm** [comment]
Doesn't appear to have DRM these tools work on:
"is neither an Adobe Adept nor a Barnes & Noble encrypted ePub"

**Comment by BarnT** [comment]
I was wondering if it's possible to find out what kind of encryption this book has (I bought it btw, just unable to read it on linux), and maybe add support for that too.

**Comment by ElleKayEm** [comment]
A proprietary DRM from wherever you bought it?  Do you have to read it in their own app?

**Comment by BarnT** [comment]
I have an acsm file. Is that the thing? Or what else should I look for?

**Comment by ElleKayEm** [comment]
That is an Adobe Content Server Message.  Open that with Adobe Digital Editions 2.0.1 authorized with an Adobe ID to download the Adobe DRM epub.
