### ISSUE TITLE
DeDRM fails to decrypt on macOS, for ADE pdf ebook 

### ISSUE THREAD

**Issue by Elie-B** [apprenticeharper/DeDRM_tools#1768]
## CheckList

- [x] `The Title` and The `Log Title` are settled correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## DeDrm fails to decrypt pdf from ADE on macOS

E-books bought from dunod.com

## Log
<details><summary>Log Title</summary>

```log
DeDRM v7.2.1: Trying to decrypt Mathématiques Tout-en-un pour la Licence 1.pdf
DeDRM v7.2.1: Mathématiques Tout-en-un pour la Licence 1.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.4 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 433, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
```
</details>

**Comment by ElleKayEm** [comment]
Give calibre 4.23 and DeDRM 6.8.1 a try.

**Comment by Elie-B** [comment]
worked fine with calibre 4.23 and DeDrm 6.8.1 . 
Thanks @ElleKayEm !!
