### ISSUE TITLE
[QUESTION] Unable to remove DRM, MacOS, KFX disabled

### ISSUE THREAD

**Issue by jstevej** [apprenticeharper/DeDRM_tools#1769]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

### DeDRM: `6.8.1`

I also tried with Calibre 5.23.0 and  DeDRM 7.2.1 with similar results.

I own the book. Purchased and downloaded it via Kindle today.

KFX support is  disabled:

```
MacOS $ pwd
/Applications/Kindle.app/Contents/MacOS
MacOS $ ls -l
total 116648
-rwxr-xr-x@ 1 sjoiner  admin    166640 Oct  8  2020 CrashReporter
-rwxr-xr-x@ 1 sjoiner  admin  59512096 Oct  8  2020 Kindle
-rw-r--r--@ 1 sjoiner  admin     40672 Oct  8  2020 renderer-test
```

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt B00J3526Y6_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/sjoiner/Library/Application Support/Kindle/storage/.kinf2018
Decrypted key file using IDString 'ddeae6afc084' and UserName 'sjoiner'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
[5.62] splash screen hidden
[5.62] Started up in 5.62 seconds with 14 books
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-20.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt B00J3526Y6_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.8.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/sjoiner/Library/Application Support/Kindle/storage/.kinf2018
Decrypted key file using IDString 'ddeae6afc084' and UserName 'sjoiner'
DeDRM v6.8.0: Found 1 new key
DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 323, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 1: invalid start byte
[5.62] splash screen hidden
[5.62] Started up in 5.62 seconds with 14 books
```
</details>

**Comment by ElleKayEm** [comment]
Looks like KFX format is not disabled.

**Comment by jstevej** [comment]
I followed the steps and included the output that confirms that renderer-test has executable permissions removed. Is there something I'm missing?

**Comment by jstevej** [comment]
I got it working. I'm not completely sure what was going on, but I think I was in a stale copy of  the /Applications/Kindle.app/Contents/MacOS directory. Perhaps I went there and did the `chmod` command but then the Kindle app updated itself. Doing an `ls` showed the executable permissions removed, but note the date of the file: Oct 8. When I opened a new terminal to that directory, the date of the file was March 29 and it had executable permissions. I removed them  again and all is working.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
