### ISSUE TITLE
Cannot Customize plugin - ConfigWidget - exception handled

### ISSUE THREAD

**Issue by jkartchner** [apprenticeharper/DeDRM_tools#177]
calibre, version 2.76.0
ERROR: Unhandled exception: <b>AttributeError</b>:'module' object has no attribute 'ConfigWidget'

calibre 2.76  embedded-python: False is64bit: True
Linux-4.8.13-1-ARCH-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.8.13-1-ARCH', '#1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016')
Python 2.7.13
Linux: ('', '', '')
Successfully initialized third party plugins: DeDRM (6, 5, 2)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 293, in customize_plugin
    self.modify_plugin(op='customize')
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 371, in modify_plugin
    if plugin.do_user_config(self.gui):
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 155, in do_user_config
    config_widget = self.config_widget()
  File "calibre_plugins.dedrm.__init__", line 633, in config_widget
AttributeError: 'module' object has no attribute 'ConfigWidget'

**Comment by ElleKayEm** [comment]
After installing DeDRM (or any plugin), always restart calibre.  Also, make sure you don't have any of the old DeDRM plugins lurking around.

**Comment by apprenticeharper** [comment]
No response. Issue closed.

**Comment by tidux** [comment]
This issue is still present on the latest version.
