### ISSUE TITLE
deDRM de-encryption issue

### ISSUE THREAD

**Issue by tabisamra** [apprenticeharper/DeDRM_tools#1773]
Out of 18 files, around 4 or 5 didn't work for some reason. Here's the log for one of them:

`calibre Debug log
calibre 5.23  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.23  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 132.00000198244115 x 132.50000198995036
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt The Philosophical Poetics of Alfarabi, Avicenna and Averroes.pdf
DeDRM v7.2.1: The Philosophical Poetics of Alfarabi, Avicenna and Averroes.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 433, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 347, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[14.04] splash screen hidden
[14.04] Started up in 14.04 seconds with 13 books
Added The Philosophical Poetics of Alfarabi, Avicenna and Averroes to db in: 0.0
Added 1 books in 0.6 seconds
`

**Comment by ElleKayEm** [comment]
DeDRM 7.2.1 has trouble with many Adobe DRM pdfs.  Try calibre 4.23 and DeDRM 6.8.1.
