### ISSUE TITLE
[QUESTION] Windows/Kindle, Unable to remove DRM with Calibre

### ISSUE THREAD

**Issue by bobwukong** [apprenticeharper/DeDRM_tools#1774]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Kindle For PC DRM not being removed

I have purchesed the books from Amazon, and downloaded them through Kindle for PC. Upon adding them to Calibre, The title, author, cover picture etc, are displayed, but a conversion attempt to any format yields a response that the book is locked by DRM. The much suggested combo of "calibre 4.23 and DeDRM 6.8.1" was tried as well but didn't work either.

('Windows', '10', '10.0.19041')
Python 3.8.5
## Log
<details><summary>calibre Debug log</summary>

```log
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\Bob\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[0.69] main UI initialized...
[0.69] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 741, in initialize_plugins
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
[2.72] splash screen hidden
[2.72] Started up in 2.72 seconds with 1 books
Worker Launch took: 0.00 seconds
Job: 0 Convert book 1 of 1 (The Plum in the Golden Vase or, Chin P'ing Mei, Volume One: 56 (Princeton Library of Asian Translations)) finished
Convert book 1 of 1 (The Plum in the Golden Vase or, Chin P'ing Mei, Volume One: 56 (Princeton Library of Asian Translations))

	Failed to initialize plugin: 'C:\\Users\\Bob\\AppData\\Roaming\\calibre\\plugins\\DeDRM.zip'

	Conversion options changed from defaults:

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Bob\\AppData\\Local\\Temp\\calibre_z56ql0l6\\0vmv6hnm.opf'

	  output_profile: 'kindle'

	  cover: 'C:\\Users\\Bob\\AppData\\Local\\Temp\\calibre_z56ql0l6\\2c2pbbgd.jpeg'

```
</details>
[tmp96sl5w60.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6836315/tmp96sl5w60.txt)

**Comment by ElleKayEm** [comment]
Looks like you need to reinstall DeDRM 7.2.1.  Then see this post about either avoiding or dealing with KFX format:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by bobwukong** [comment]
[tmpta18n9tf.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6836466/tmpta18n9tf.txt)
I apologize, the wrong debug log was uploaded. Even with this, from your advice and the mobile read thread I think the best bet, if using the KFX input plugin, is to find 1.26 and try with that. Thank you for your help.

**Comment by ElleKayEm** [comment]
Personally I avoid KFX format altogether by sticking with Kindle for PC 1.17 (for as long as I'm able to).

**Comment by phenomenal11** [comment]
@ElleKayEm As of today there are certain Kindle books that won't even download on version 1.17( ERROR: PCMAC_126_Delivery_Error_Upgrade_PC)

They only get downloaded on the latest version it seems and the DeDRM_Plugin is unable to break the encryption of the file.

**Comment by ElleKayEm** [comment]
Yes, that's true.  Some books are only available in KFX format and require the latest version of Kindle for PC/Mac.  DeDRM can only decrypt KFX format from Kindle for PC/Mac 1.26 or earlier.

**Comment by phenomenal11** [comment]
Oh man that sucks :( 

Is there no hope then for the DeDRMing the latest KFX files?
If none then I suppose I have to move on from Kindle because I am definitely not going to lock myself into the amazon ecosystem.

**Comment by ElleKayEm** [comment]
For the last couple updates of DeDRM, we've been able to DeDRM KFX from the latest version for one day.  Then Amazon changes something and we're back to 1.26 or earlier.
