### ISSUE TITLE
Kindle DeDRM issue with KEy file

### ISSUE THREAD

**Issue by alephtaph** [apprenticeharper/DeDRM_tools#1775]
Latest Kindle App
Latest Calibre App
Latest DeDRM Tool

KFX download via bash disabled
OS: Mac

Output of debug:
calibre Debug log
calibre 5.23  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
calibre 5.23  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 40, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 40, 0) && KFX metadata reader (from KFX Input) (1, 40, 0) && KFX Input (1, 40, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 103.00000154690483 x 103.00000154690481
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.35] splash screen shown
[0.35] Initializing db...
[0.57] db initialized
[0.57] Constructing main UI...
[1.78] main UI initialized...
[1.78] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.40.0: Importing /Users/marco/Library/Application Support/Kindle/My Kindle Content/B00A0WEFV8_EBOK/B00A0WEFV8_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B00A0WEFV8_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Everything Kosher Slow Cooker Cookbook: Includes Chicken Soup with Lukshen Noodles, Apple-Mustard Beef Brisket, Sweet and Spicy Pulled Chicken, Potato ... Sauce and hundreds more! (Everything®)
Got SerialNumber from database default_key
Got UsernameHash from database default_key
Got DSN key from database default_key_2
Found 7 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 7 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/marco/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'marco'  on file  /Users/marco/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'09220617ba06'
Decrypted key file using IDString '09220617ba06' and UserName 'marco'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Everything Kosher Slow Cooker Cookbook: Includes Chicken Soup with Lukshen Noodles, Apple-Mustard Beef Brisket, Sweet and Spicy Pulled Chicken, Potato ... Sauce and hundreds more! (Everything®)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 7 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[6.33] splash screen hidden
[6.34] Started up in 6.34 seconds with 369 books
Added The Everything Kosher Slow Cooker Cookbook: Includes Chicken Soup with Lukshen Noodles, Apple-Mustard Beef Brisket, Sweet and Spicy Pulled Chicken, Potato ... Sauce and hundreds more! (Everything®) to db in: 0.7
Added 1 books in 2.4 seconds

**Comment by ZolaLa9** [comment]
Try going back to Calibre 4.23 and tools 6.8.1. If that works, you should be able to upgrade back to Calibre 5.x and tools 7.2.1.

Some Macs, especially those on Big Sur, have trouble retrieving the key using Calibre 5.x and tools 7.2.1. Going back to Calibre 4.23 and tools 6.8.1 to retrieve the key often fixes the problem. Then you can upgrade back to Calibre 5.x and tools 7.2.1.
