### ISSUE TITLE
Invalid Plugin when trying to install

### ISSUE THREAD

**Issue by pmi123** [apprenticeharper/DeDRM_tools#1778]
I upgrade Calibre to the latest version and downloaded the latest version of DeDRM. I tried installing the plugin and got the error message Invalid Plugin.

Here is the full message:
```
calibre, version 5.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/opt/calibre/DeDRM_tools-master/DeDRM_plugin/alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.23  embedded-python: True is64bit: True
Linux-5.3.0-7648-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.3.0-7648-generic', '#41~1586790036~18.04~600aeb5~dev-Ubuntu SMP Mon Apr 13 17:49:24 ')
Python 3.8.5
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 477, in add_plugin
  File "calibre/customize/ui.py", line 65, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/opt/calibre/DeDRM_tools-master/DeDRM_plugin/alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file
```
What am I missing?

Mark

**Comment by ElleKayEm** [comment]
Looks like you're trying to load the wrong file.  Unzip DeDRM_tools_7.2.1.zip and load DeDRM_plugin.zip.

**Comment by sue45south** [comment]
I'm having the same issue and followed your instruction and still getting error;
 Win 10, calibre 5.26.0  I did the retart in debug mode and this is what it logged. calibre, version 5.26.0 ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)  calibre 5.26 [64bit]  embedded-python: True is64bit: True Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE') ('Windows', '10', '10.0.19041') Python 3.8.5 Windows: ('10', '10.0.19041', '', 'Multiprocessor Free') Interface language: None Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 42, 0) && Package KFX (from KFX Input) (1, 42, 0) && Import List (1, 5, 6) && KFX metadata reader (from KFX Input) (1, 42, 0) && KFX Input (1, 42, 0) && Set KFX metadata (from KFX Output) (1, 55, 0) && KFX Output (1, 55, 0) && Kindle Collections (1, 7, 29) && KindleUnpack - The Plugin (0, 83, 0) && LibraryThing Match (0, 2, 0) && Obok DeDRM (6, 7, 0) && Open With (1, 5, 13) && Overdrive Link (2, 45, 1) && Reading List (1, 7, 6) && Recipe Reader (1, 0, 1) && Save To Format (0, 0, 6) && TTS to MP3 (0, 5, 9) && all recipes Recipe Reader (1, 0, 2) && food network Recipe Reader (1, 0, 2) && Overdrive Link* (2, 45, 1) Traceback (most recent call last):   File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin   File "calibre\customize\ui.py", line 477, in add_plugin   File "calibre\customize\ui.py", line 65, in load_plugin   File "calibre\customize\zipplugin.py", line 293, in load   File "importlib\__init__.py", line 127, in import_module   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import   File "<frozen importlib._bootstrap>", line 991, in _find_and_load   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked   File "calibre\customize\zipplugin.py", line 185, in exec_module   File "calibre\customize\zipplugin.py", line 181, in get_code   File "calibre_plugins.dedrm.__init__", line 168     print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)           ^ SyntaxError: invalid syntax author:sue45south

**Comment by ElleKayEm** [comment]
@sue45south Slightly different issue.  Looks like you're trying to load an old version of DeDRM which isn't compatible with calibre 5 and up.  Make sure you're trying to load the current DeDRM version 7.2.1.
