### ISSUE TITLE
[QUESTION] Can not remove DRM: " DeDRM v6.8.0: Couldn't decrypt after 0.1 seconds. DRM free perhaps?"

### ISSUE THREAD

**Issue by jtMB1** [apprenticeharper/DeDRM_tools#1779]
Hi, I followed instructions in readme file. ADE version is 2.0.1, I tried to extract decoding keys manually and automaticly, but it looks like it doesn't matter, because calibre percieves epub file as DRM free.
The epub file came from ADE on the same machine.

Thanks in advance for any help!

## Log
<details><summary>Log Title</summary>

```log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True

C:\Users\JAN>calibre-debug --gui -g
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.94] main UI initialized...
[1.94] Hiding splash screen
[2.12] splash screen hidden
[2.12] Started up in 2.12 seconds with 1 books
DeDRM v6.8.0: Trying to decrypt Dolina roz.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “Dolina roz.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 637, in run
  File "calibre_plugins.dedrm.__init__", line 413, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Dolina roz to db in: 0.3
Added 1 books in 1.0 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Looks like this book is not configured in the way that DeDRM expects for an Adobe DRM EPUB.  You opened the ACSM file with ADE 2.0.1 authorized with your Adobe ID to download the EPUB?

**Comment by jtMB1** [comment]
Thanks for your quick reply!
Yes, the problem was, I opened acsm file first with ADE 4.5 and after that file was already insidfe the ADE 2.0.1. 
After new authorization of 2.0.1, everything works. 
Thank youu
