### ISSUE TITLE
DeDRM 7.2.1 on Win10 Calibre 5.21 not working on .pdf got with ADE 4.5

### ISSUE THREAD

**Issue by arax-1238** [apprenticeharper/DeDRM_tools#1783]
calibre, version 5.21.0
ERRORE: Caricamento libro fallito: Impossibile aprire il libro in C:\Users\LELE\Documents\calibre - biblioteca\Sconosciuto\Birra. Manuale per aspiranti intend (2961)\Birra. Manuale per aspiranti in - Sconosciuto.pdf. Clicca su "Mostra dettagli" per ulteriori informazioni.

****Failed to convert book: C:\Users\LELE\Documents\calibre - biblioteca\Sconosciuto\Birra. Manuale per aspiranti intend (2961)\Birra. Manuale per aspiranti in - Sconosciuto.pdf with error:****
DeDRM v7.2.1: Trying to decrypt Birra. Manuale per aspiranti in - Sconosciuto.pdf
DeDRM v7.2.1: Birra. Manuale per aspiranti in - Sconosciuto.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
InputFormatPlugin: PDF Input running
on C:\Users\LELE\Documents\calibre - biblioteca\Sconosciuto\Birra. Manuale per aspiranti intend (2961)\Birra. Manuale per aspiranti in - Sconosciuto.pdf
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 346, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
Exception ignored in: <function NativeFunction.__del__ at 0x000002501C12DE50>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000002501C12DE50>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
Try calibre 4.23 and DeDRM 6.8.1.

**Comment by ElleKayEm** [comment]
Can you open the book with ADE 2.0.1 authorized with the same Adobe ID?

**Comment by arax-1238** [comment]
I can open the .pdf with ADE 4.5 and with ADE 2.01.1

**Comment by ElleKayEm** [comment]
Is ADE which was used to download the book authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

**Comment by arax-1238** [comment]
Yes to everything.
DOUBT: I have not customized the DEDRM plugin for caliber importing Adobe Digital Edition Keys, as it asks me for a **.der** file that I can't find ....
Can this be the cause? If yes, where do I find the .drm to import?
Thank you very much for the dedicated time.

**Comment by ElleKayEm** [comment]
This should happen automatically.  You could try de-authorizing and re-authorizing ADE.  See this for how to do that (scroll down for Windows):  https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

I'd also suggest removing ADE 4.5 and just use ADE 2.0.1.  ADE 4.5 can handle DRM which cannot be removed.  And I'd recommend 64-bit calibre 4.23 with DeDRM 6.8.1.  DeDRM 7.2.1 still has trouble with many pdfs which 6.8.1 can handle.

**Comment by arax-1238** [comment]
using ADE 2.0.1 and calibre  4.23 with DeDRM 6.8.1 **IT WORKS** perfectly.  Now I can read my .pdf when and where I want. 
Thank you very much for your help ! :-)
