### ISSUE TITLE
DeDRM 7.2.1 on Calibre 5.23.0 not working on with .AZW3 on .pdf

### ISSUE THREAD

**Issue by pipamediaslargas** [apprenticeharper/DeDRM_tools#1785]
File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\esteban\AppData\Local\Temp\calibre_lgyy613j\n_9n525c.azw3
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1105, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "calibre\ebooks\mobi\reader\mobi6.py", line 163, in check_for_drm
calibre.ebooks.DRMError: Minihuertos (Zenith Green) (Spanish Edition)

**Comment by ElleKayEm** [comment]
Not enough to see what's going on here.  Let's see a log of adding the book to calibre:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
