### ISSUE TITLE
DeDMR 7.2.1 on Calibre 5.23.0  .AZW3 to .pdf (The book is from Amazon)

### ISSUE THREAD

**Issue by pipamediaslargas** [apprenticeharper/DeDRM_tools#1787]
calibre Registro de depuración
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 75.25925925925925 x 108.37333333333332
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[3.23] splash screen shown
[3.23] Initializing db...
[3.25] db initialized
[3.25] Constructing main UI...
[4.94] main UI initialized...
[4.94] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Minihuertos (Zenith Green) (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Minihuertos (Zenith Green) (Spanish Edition)
Found 0 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\esteban\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[7.56] splash screen hidden
[7.56] Started up in 7.56 seconds with 1 books
Added Minihuertos (Zenith Green) (Spanish Edition) to db in: 1.6
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded 1 books in 2.7 seconds
Failed to check for plugin update: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

Thanks for the help!

**Comment by ElleKayEm** [comment]
If this is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.

**Comment by pipamediaslargas** [comment]
What happens if I don´t own a Kindle? There is another way?
Thanks for your time

**Comment by ElleKayEm** [comment]
@pipamediaslargas Yes, download the books with Kindle for PC.  I recommend method 1 or 2 here:  https://www.mobileread.com/forums/showthread.php?t=283371
