### ISSUE TITLE
Unable to view ebook with calibre drm plugin on

### ISSUE THREAD

**Issue by ebokjunkie** [apprenticeharper/DeDRM_tools#1789]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

here is the debug code

calibre Debug log
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.23  embedded-python: True is64bit: False
Windows-10-10.0.18362 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.84] splash screen shown
[1.84] Initializing db...
[1.89] db initialized
[1.89] Constructing main UI...
[5.25] main UI initialized...
[5.25] Hiding splash screen
Starting QuickView
[6.36] splash screen hidden
[6.36] Started up in 6.36 seconds with 1 books
DeDRM v7.2.1: Trying to decrypt Multiple Streams of Income Making Money in 2020 by Robert Allen (z-lib.org).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa0E\n\x93\xf3\xfd\x83r\x8d\xcd1\xbf\xa8}\xd8\xd7\x9cz\xc07"1q\xbeq\x04gn\xb95\xe8\x84', b'C:\\Users\\Indigo\\Downloads\\Multiple Streams of Income Making Money in 2020 by Robert Allen (z-lib.org).azw3']
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Multiple Streams of Income: Making Money in 2020
Found 0 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\Indigo\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Indigo\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3065182836' and UserName 'Indigo'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Multiple Streams of Income: Making Money in 2020
Got DSN key from database default_key_1
Found 4 keys to try after 30.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 30.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 30.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added Multiple Streams of Income: Making Money in 2020 to db in: 0.4
Added 1 books in 31.7 seconds

**Comment by j-howell** [comment]
> DeDRM v7.2.1: Trying to decrypt Multiple Streams of Income Making Money in 2020 by Robert Allen (z-lib.org).azw3

Is that a pirated book from Z-library?
