### ISSUE TITLE
Wine setup: Cannot install pycrypto

### ISSUE THREAD

**Issue by bronger** [apprenticeharper/DeDRM_tools#1790]
I want to DeDRM EPUBs protected with ADE (ADEPT) using wine 6.14 (winehq-staging) and Ubuntu 20.04.

In a 64bit wine setup, I successfully installed ADE 2.0.1 and downloaded an EPUB with it.  This EPUB is fulfilled with my Adobe ID. I also installed ActiveState Python 2.7 64bit.  `ebook-convert` cannot convert the EPUB to something else:

```
Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.
ShellExecuteEx fehlgeschlagen: Datei nicht gefunden.

DeDRM v7.2.1: wine python3.exe is not python3

…

DeDRM v7.2.1: wine C:\Python27\python.exe is not python3
DeDRM v7.2.1: Unable to find python3 executable in WINEPREFIX="/home/bronger/.wine"
DeDRM v7.2.1: Exception when getting default Adobe Key after 1.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 365, in ePubDecrypt
    self.default_key = defaultkeys[0]
IndexError: list index out of range
DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_
tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/a
pprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://
github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

Then, I installed Python 3.5 and got the following error output:

```
adobekey.py v7.0
Copyright © 2009-2020 i?cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "/home/bronger/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 586, in <module>
    sys.exit(cli_main())
  File "/home/bronger/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 509, in cli_main
    keys = adeptkeys()
  File "/home/bronger/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 349, in adeptkeys
    raise ADEPTError("PyCrypto or OpenSSL must be installed")
__main__.ADEPTError: PyCrypto or OpenSSL must be installed

…

DeDRM v7.2.1: Wine subprocess call error: 1
DeDRM v7.2.1: Found and decrypted 0 key files
DeDRM v7.2.1: Exception when getting default Adobe Key after 1.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 365, in ePubDecrypt
    self.default_key = defaultkeys[0]
IndexError: list index out of range
DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

This is a catch-22 situation: pycrypto is EOL for a long time. Its EXE release does not detect ActiveState Python and wouldn’t install.  The ZIP release of pycrypto is 32bit-only, however, ActiveState Python 2.7 is not available anymore for 32bit (AFAICS). And, I found no hints for how to install OpenSSL for wine.

**Comment by bronger** [comment]
Sorry for the noise, I was able to install OpenSSL accoring to https://github.com/apprenticeharper/DeDRM_tools/issues/1509#issue-798765233. (What’s left is possibly an updated https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM but that’s another issue.)
