### ISSUE TITLE
MacCatalina/Kindle 1.30 unable to remove DRM from AZW3 file

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [apprenticeharper/DeDRM_tools#1795]
I forced Kindle 1.30 to download an AZW3 file instead of KFX file. But the decryption/DRM-removal fails.

The key is claimed to be discovered but there is an error decrypting the AZW3 file. Here's the log from Calibre 5.24. I'm not sure what the 4 keys are that it claims to have tried before decrypting the key from the .kinf2018 file. I can't tell from these log messages what the problem might be. (various ID strings have been changed in these log messages)

Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.00000169708973 x 113.50000170459899
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt XYZZYXYZZY_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Ike's Mystery Man
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/someuser/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'someuser'  on file  /Users/someuser/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'7723acbd045a'
Decrypted key file using IDString '7723acbd045a' and UserName 'datihein'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Noisy Book
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

**Comment by JeNeSuisPasDave** [comment]
I was able to run kindlekey.py and it decrypted the .kinf2018 file and produced a kindlekey1.k4i keyfile. I added that to the plugin and tried again. This time it said it had 8 keys to try; none worked, so it found my .kinf2018 file again and pulled keys from that and tried and that failed as well. Very similar to the above log.

**Comment by c00lt** [comment]
I had the same error and tried the same thing.
I was able to fix this issue by reverting to Calibre 4.23 and tools 6.8.1 as proposed [here](https://github.com/apprenticeharper/DeDRM_tools/issues/1775#issuecomment-887834985)

**Comment by hmoffatt** [comment]
I'm downloading for my Kindle Paperwhite.

**Comment by hmoffatt** [comment]
I tried a fresh setup on linux with Calibre 5.29 and DeDRM 7.2.1 and there was no change. I have AZW3 files downloaded from amazon.com for my Paperwhite with the serial number entered in the plugin settings. The exact same config works on Windows, and it worked on Linux with Calibre 4.

Is there any debugging I can turn on to get more info?

**Comment by ElleKayEm** [comment]
Let's see a debug log of adding a book.

**Comment by ElleKayEm** [comment]
Preferences > Restart in debug mode

**Comment by j-howell** [comment]
> So it looks like the root cause of my problem is that the python-crypto library has been removed in the latest Debian release. It is apparently no longer maintained and has been replaced by the Cryptodome library.

Are you using the version of calibre provided by your Linux distribution?

If so you may want to consider installing the [official Linux version of calibre](https://calibre-ebook.com/download_linux) instead.
