### ISSUE TITLE
Calibre 5.24 can't decrypt AZW

### ISSUE THREAD

**Issue by davidpvny** [apprenticeharper/DeDRM_tools#1806]
Calibre 5.24, DeDrm Tools v7.  MacMini M1 2020 Big Sur.  Will greatly appreciate the help.
[tmpzu5y0ewq.txt](https://github.com/apprenticeharper/DeDRM_tools/files/6972971/tmpzu5y0ewq.txt)

**Comment by 2020MacOwner** [comment]
Same here.

**Comment by mizuOda** [comment]
Read: https://www.mobileread.com/forums/showthread.php?s=5ea46a751d2e1add30811d95537a9d5a&t=283371

and https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by 2020MacOwner** [comment]
Still unable to decrypt AZW files.

Environment:
Kindle version: 1.17
Calibre version: attempted both 5.24 and 5.26
Mac version: Big Sur 11.5.2
DRM Tools version: 7.2.1

**Comment by ElleKayEm** [comment]
You cannot be using Kindle for Mac 1.17 with Big Sur as it's a 32-bit program.  All the information you need is in the links that @mizuOda gave above.

**Comment by 2020MacOwner** [comment]
I have 1.17 loaded on another mac running Yosemite, then copy the the files to the mac running the above listed versions.

**Comment by ElleKayEm** [comment]
Then that's the issue.  The Kindle app the books are downloaded to and calibre with DeDRM need to be on the same machine and user.

**Comment by 2020MacOwner** [comment]
They are the same user. This has been working fine for YEARS...it wasn't until Calibre 5.24 that it 'broke'.

**Comment by ElleKayEm** [comment]
Each installation of Kindle for Mac has a unique key for its books.  DeDRM cannot retrieve that key from a different computer.

**Comment by tool3884** [comment]
Good afternoon,  I have Calibre 5.27 and DeDRM 7.2.1 running.  I am no longer able to decrypt my azw3 books I purchase from Amazon. I have double checked the serial numbers in the plugin customization match those of the Kindle Paperwhite I am using when doing the "download and transfer via USB" option.  The log file indicates "No Key Found."  I have tried removing the plugin and reinstalling it. Any ideas?  Thanks!

Here is the log file for reference:

Added The Ledge to db in: 0.2
Added 1 books in Worker Launch took: 0.09 seconds
Job: 0 Convert book 1 of 1 (The Ledge) finished
Convert book 1 of 1 (The Ledge)

	DeDRM v7.2.1: Trying to decrypt m_irkb96.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: The Ledge
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 4 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Jeff_D\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:

	  cover: 'C:\\Users\\Jeff_D\\AppData\\Local\\Temp\\calibre_jsr8pc8y\\xvj2vcqi.jpeg'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Jeff_D\\AppData\\Local\\Temp\\calibre_jsr8pc8y\\48_qs7vb.opf'

	  output_profile: 'kindle_pw3'

	Resolved conversion options

	calibre version: 5.27.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Jeff_D\\AppData\\Local\\Temp\\calibre_jsr8pc8y\\xvj2vcqi.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_compress': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000020A807F7520>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'mobi_file_type': 'old',

	 'mobi_ignore_margins': False,

	 'mobi_keep_original_images': False,

	 'mobi_toc_at_start': False,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': True,

	 'no_inline_toc': False,

	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000020A807F7B20>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'personal_doc': '[PDOC]',

	 'prefer_author_sort': False,

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Jeff_D\\AppData\\Local\\Temp\\calibre_jsr8pc8y\\48_qs7vb.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'share_not_sync': False,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
@tool3884 You have chosen an E-ink Kindle (not a Fire) with "download & transfer via USB"?  Be sure you have that Kindle's serial number in DeDRM's customization.  Try copy and pasting the serial number from the website.

**Comment by tool3884** [comment]
@ElleKayEm Thank you for the super quick response!  Yes, I made sure I am selecting my Kindle Paperwhite when I use the "download & transfer" option.  I also double and triple checked the SNs match (on the device, from the Amazon Devices page, and in the Plugin).  This just recently started happening.  I have been using Calibre and DeDRM for years without issue and this is the first time this has happened.  What I find odd is the log file says "Found 4 Keys to Try."  I only have two SNs in the plugin customization option. Maybe Amazon has changed something on their end as well, I know the website has a new UI.

**Comment by ElleKayEm** [comment]
@tool3884 Still working for me.  Only two things I know to try:  Download a fresh copy of the book to make sure you have chosen the right device and then make sure that is the copy that you add to calibre.  Copy and paste the serial number for that Kindle from your content & devices page into DeDRM to prevent typos.

More than one key is derived from each serial number.  My log shows 10 keys to try when I have 3 serial numbers plus a "default_key" in the Kindle for PC section.

**Comment by tool3884** [comment]
@ElleKayEm The problem seems to be isolated to one computer.  I did a fresh install of Calibre 5.27 and DeDRM 7.2.1 on a different computer and it worked without a problem.  I am going to try to reinstall Calibre on the issue computer and see if it fixes the issue.
