### ISSUE TITLE
[QUESTION] Kindle for PC ebook only available in new DRM format please help

### ISSUE THREAD

**Issue by deucalion** [apprenticeharper/DeDRM_tools#1809]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Kindle for PC ebook only available in new DRM format please help
The ebook in question I bought is only available in the new DRM and KFX format and has an additional limit: `Simultaneous device usage ‏ : ‎ Up to 2 simultaneous devices, per publisher limits`. I wonder if that kind of ebook I just bought qualifies as rented with such a limit and if I can and should persue further decryption attempts.

Trying to use any earlier version of Kindle for PC fails, as the DRM or KFX version appears to require a newer version.

Please advise.

## Log
<details><summary>Calibre and DeDRM log output, stating:

Incorrect padding - wrong key with Calibre and DeDRM;
unable to decrypt with the KFX DRM voucher.</summary>

```log
Convert book 1 of 1 (Options, Futures, and Other Derivatives (2-downloads))
DeDRM v7.2.1: Trying to decrypt 6x6k3cdq.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 6x6k3cdq
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.108d8fbf-67c3-4b6f-9b69-fe89c70b8475.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\defaultuser\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\defaultuser\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '613380195' and UserName 'deucalion'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 6x6k3cdq
Got DSN key from database default_key_1
Found 1 keys to try after 2.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.108d8fbf-67c3-4b6f-9b69-fe89c70b8475.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  flow_size: 0
  output_profile: 'kindle_voyage'
  cover: 'C:\\Users\\deucalion\\AppData\\Local\\Temp\\calibre_e6uxvs8i\\g5473ibd.jpeg'
  verbose: 2
  read_metadata_from_opf: 'C:\\Users\\deucalion\\AppData\\Local\\Temp\\calibre_e6uxvs8i\\eynkqyt6.opf'
Resolved conversion options
calibre version: 5.25.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\deucalion\\AppData\\Local\\Temp\\calibre_e6uxvs8i\\g5473ibd.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 0,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000027622DE67F0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x0000027622DE6B20>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\deucalion\\AppData\\Local\\Temp\\calibre_e6uxvs8i\\eynkqyt6.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt 6x6k3cdq.kfx-zip
Decrypting KFX-ZIP ebook: 6x6k3cdq
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.108d8fbf-67c3-4b6f-9b69-fe89c70b8475.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\defaultuser\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\defaultuser\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '613380195' and UserName 'deucalion'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 6x6k3cdq
Got DSN key from database default_key_1
Found 1 keys to try after 2.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.108d8fbf-67c3-4b6f-9b69-fe89c70b8475.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\defaultuser\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: KFX Input running
on C:\Users\defaultuser\AppData\Local\Temp\calibre_e6uxvs8i\6x6k3cdq.kfx-zip
Software versions: KFX Input 1.41.0, calibre 5.25 [64bit], Windows-10-10.0.19041
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\defaultuser\AppData\Local\Temp\calibre_e6uxvs8i\6x6k3cdq.kfx-zip
Processing container: B08XDGLF44_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 105, in convert
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08XDGLF44_EBOK.azw has DRM and cannot be converted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1105, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre_plugins.kfx_input.__init__", line 125, in convert
calibre.ebooks.DRMError: This book has DRM!

```
</details>

**Comment by mizuOda** [comment]
This appears to be a Pearson textbook. In any case, if it's KFX requiring the latest version of Kindle for PC, I don't think the tools will work.
