### ISSUE TITLE
Kindle for android extract keys failed with exception: UnboundLocalError

### ISSUE THREAD

**Issue by LaraChicharo** [apprenticeharper/DeDRM_tools#1815]
I downloaded the latest release of the tool as of today

calibre, version 5.25.0
ERROR: Unhandled exception: <b>UnboundLocalError</b>:local variable 'read' referenced before assignment

calibre 5.25  embedded-python: True is64bit: True
Linux-4.9.0-6-amd64-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '4.9.0-6-amd64', '#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 41, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 41, 0) && KFX metadata reader (from KFX Input) (1, 41, 0) && KFX Input (1, 41, 0)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 952, in get_android_file
    file_serials = androidkindlekey.get_serials(fpath)
  File "calibre_plugins.dedrm.androidkindlekey", line 282, in get_serials
    read.close()
UnboundLocalError: local variable 'read' referenced before assignment

**Comment by ElleKayEm** [comment]
Extracting the keys from Kindle for Android has not worked for some time now due to a change on Amazon's end.  Books from Kindle for PC/Mac and those downloaded for transfer via USB for an E-ink Kindle can still be decrypted.
