### ISSUE TITLE
[QUESTION] Can't read an .epub?

### ISSUE THREAD

**Issue by kqom** [apprenticeharper/DeDRM_tools#1817]
Hi!
I'm sorry, I... I'm quite unfamiliar with all of this. I've been trying to export an epub from booklive (a Japanese store/reader) and couldn't read it in ADE. I presumed it was something about DMRs, even if I wasn't sure, and tried out with Calibre and the plugin but... Here's what appears when I try to open it:

```
calibre, version 5.25.0
ERREUR : Le chargement du livre a échoué: Impossible d'ouvrir le livre à la position D:\Livres\Inconnu(e)\0 EB000090140800100101502021 (5)\0 EB000090140800100101502021 - Inconnu(e).epub. Cliquez sur "Afficher les détails" pour plus d'informations.

Failed to convert book: D:\Livres\Inconnu(e)\0 EB000090140800100101502021 (5)\0 EB000090140800100101502021 - Inconnu(e).epub with error:
DeDRM v7.2.1: Trying to decrypt 0 EB000090140800100101502021 - Inconnu(e).epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Error 'File is not a zip file' when checking zip archive
InputFormatPlugin: EPUB Input running
on D:\Livres\Inconnu(e)\0 EB000090140800100101502021 (5)\0 EB000090140800100101502021 - Inconnu(e).epub
EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\ebooks\metadata\epub.py", line 161, in get_zip_reader
  File "calibre\utils\zipfile.py", line 775, in __init__
  File "calibre\utils\zipfile.py", line 810, in _GetContents
  File "calibre\utils\zipfile.py", line 825, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 433, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 198, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 238, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 164, in get_zip_reader
  File "calibre\utils\localunzip.py", line 264, in __init__
  File "calibre\utils\localunzip.py", line 240, in _extractall
ValueError: Not a ZIP file
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 210, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 53, in __init__
  File "C:\Users\Celia\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 683, in __init__
  File "C:\Users\Celia\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 709, in _GetContents
  File "C:\Users\Celia\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 721, in _RealGetContents
zipfilerugged.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 214, in ePubDecrypt
Exception: File is not a zip file
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 262, in convert
  File "calibre\utils\zipfile.py", line 775, in __init__
  File "calibre\utils\zipfile.py", line 810, in _GetContents
  File "calibre\utils\zipfile.py", line 825, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 269, in convert
  File "calibre\utils\localunzip.py", line 253, in extractall
  File "calibre\utils\localunzip.py", line 240, in _extractall
ValueError: Not a ZIP file
```

I'm not even sure it's a DMR issue at this point...?

**Comment by ElleKayEm** [comment]
They probably have their own DRM.  For epubs, these tools handle Adobe, Barnes & Noble, and Kobo.
