### ISSUE TITLE
KFX Input CLI Encoding Error

### ISSUE THREAD

**Issue by xxmissingnoxx** [apprenticeharper/DeDRM_tools#1818]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title
KFX Input CLI encoding problem

I received an error via the GUI ("This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion.") and am now attempting to use the CLI, but it seems like there is some sort of unicode issue associated with Python 2. I'm not sure how to address this because I must go through calibre-debug. Any help you can provide would be appreciated. Thank you for your work and time.
## Log
<details><summary>KFX Encoding Error</summary>

```log
Air Desktop % calibre-debug -r "KFX Input" -e Supply\ Chain\ Logistics\ Management\ -\ Donald\ Bowersox.kfx
Python function terminated unexpectedly: Non-ASCII character '\xbb' in file /Users/hobobaggins/Desktop/Supply Chain Logistics Management - Donald Bowersox.kfx on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (Supply Chain Logistics Management - Donald Bowersox.kfx, line 1)
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/debug.py", line 320, in main
  File "site-packages/calibre/debug.py", line 260, in run_script
  File "/Users/hobobaggins/Desktop/Supply Chain Logistics Management - Donald Bowersox.kfx", line 1
SyntaxError: Non-ASCII character '\xbb' in file /Users/hobobaggins/Desktop/Supply Chain Logistics Management - Donald Bowersox.kfx on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
</details>

**Comment by j-howell** [comment]
You need two dashes before the -e. That separates calibre options from plugin options on the command line.:

calibre-debug -r "KFX Input" -- -e Supply\ Chain\ Logistics\ Management\ -\ Donald\ Bowersox.kfx

**Comment by xxmissingnoxx** [comment]
That did the trick. Thank you for the help and developing useful tools.

**Comment by ElleKayEm** [comment]
Looks like this issue can be closed.

**Comment by tk-20** [comment]
I'm a beginner,
I'm having the same issue; where do I go to effect the changes you are talking about?
where do I access this:

calibre-debug -r "KFX Input" -- -e Supply\ Chain\ Logistics\ Management\ -\ Donald\ Bowersox.kfx

**Comment by j-howell** [comment]
> I'm a beginner, I'm having the same issue; where do I go to effect the changes you are talking about? where do I access this:
> 
> calibre-debug -r "KFX Input" -- -e Supply\ Chain\ Logistics\ Management\ -\ Donald\ Bowersox.kfx

That is what the person who opened the issue needed to type in order to activate the command line interface properly.

If you don't know what that means then you do not have the same problem as xxmissingnoxx.

**Comment by Guacamome** [comment]
Hi, I'm encountering the same issue as @xxmissingnoxx 
I'm trying to convert kpf to epub using calibre and this message shows up : "This book has a layout that is incompatible with calibre conversion. For best results use the KFX Input plugin CLI for conversion."
I suspect this is because my ebook is in fixed layout except I don't know what to do to fix the issue, could you please explain as if I were a toddler ? 
Hoping @j-howell can help, or anyone else really
Thanks a lot !

**Comment by j-howell** [comment]
See the "Command Line Interface" in the [KFX Input plugin documentation](https://www.mobileread.com/forums/showthread.php?t=291290).

**Comment by Debsbooks** [comment]
I have the same problem, and I can see what needs to be done (add the "ee") but I don't know how to do that!  Like [Guacamome](https://github.com/Guacamome), I need to be treated like a toddler.

And I followed the provided link but it did not give me how to make the change, just an explanation of KFX files.

Thanks in advance!

Oh, editing:  I also restarted Calibre in debug mode but it looked the same and I didn't know what to do with it.

Stull trying:  I saw this:  "Conversion via CLI does not work for books that have DRM. If the book you are trying to convert has DRM you will need to import it into calibre first so that DRM can be removed and then export it from calibre for use by the plugin CLI."

But Calibre isn't removing the DRM, it's not just the conversion.  So problem is compounded.

**Comment by Boschmen** [comment]
Dear j-howell,

Nice to e-meet you. Thank you for working hard for the plug-in!

By the way, I'm also encountering the same error message saying: 'This book has a layout that is incompatible with calibre conversion. For best results use either the From KFX user interface plugin or the KFX Input plugin CLI for conversion. See the KFX Input plugin documentation for more information.'

It looks that most of recent Japanese books, which are published in KFX format, generate same error message so that I couldn't open KFX format in Calibre.

Since I'm using Windows as my platform, I don't understand at all what you are talking about using debugging mode to solve this issue. May I ask you if there is any workaround for Windows user?

Thanks regards,

**Comment by ElleKayEm** [comment]
Scroll down in this post: https://www.mobileread.com/forums/showthread.php?t=291290

To "From KFX" toolbar action and show the "spoiler".

**Comment by Boschmen** [comment]
@ElleKayEm 

Wow, that's fantastic...

Thanks a lot for your help. I really appreciate it!!!
