### ISSUE TITLE
[QUESTION] Calibre 5.25 & plugin 7.2.1 cannot de-drm PDF file

### ISSUE THREAD

**Issue by Imperatorum** [apprenticeharper/DeDRM_tools#1819]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title

I've been trying to de-drm a pdf file of a book I got but after putting it through calibre it seems that the drm did not get removed. Looked over the log but not really sure what the specific errors in it mean, so if anyone could help me shed light on the matter I'd be very grateful.

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>
[Calibre Error Log.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7046486/Calibre.Error.Log.txt)

**Comment by daneelf** [comment]
I have the same problem with an epub book.  I got the error below when I tried to view the book in my callibre library.

**OS:** Windows 10
**Callibre:** 5.25
**DeDrm:** 7.2.1

**Error log:** 

```
Failed to convert book: C:\Users\danee\Calibre Library\KAZOUO ISIGKOURO\Ta Apomeinaria Mias Meras (2)\Ta Apomeinaria Mias Meras - KAZOUO ISIGKOURO.epub with error:
DeDRM v7.2.1: Trying to decrypt Ta Apomeinaria Mias Meras - KAZOUO ISIGKOURO.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Ta Apomeinaria Mias Meras - KAZOUO ISIGKOURO.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\danee\Calibre Library\KAZOUO ISIGKOURO\Ta Apomeinaria Mias Meras (2)\Ta Apomeinaria Mias Meras - KAZOUO ISIGKOURO.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 824, in viewer_main
  File "calibre\srv\render_book.py", line 815, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
calibre.ebooks.DRMError: Ta Apomeinaria Mias Meras - KAZOUO ISIGKOURO.epub
Exception ignored in: <function NativeFunction.__del__ at 0x0000023E1266D790>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000023E1266D790>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable```

**Comment by Imperatorum** [comment]
> @Imperatorum Check this #1692 .Worked for me on Windows 10.

@daneelf Looked it up and it seems it's working fine now, thank you for helping with the issue.

**Comment by ElleKayEm** [comment]
@Imperatorum DeDRM 7.2.1 still needs work for PDFs.

@daneelf Looks like you don't have ADE activated with your Adobe ID on the same machine and user as calibre with DeDRM.
