### ISSUE TITLE
[QUESTION] can't remove DRM from AZW on Calibre 5.26/DeDRM 7.21

### ISSUE THREAD

**Issue by fredzannarbor** [apprenticeharper/DeDRM_tools#1822]
Kindle paperwhite firmware 5.15

## Log
<details><summary>Log Title</summary>

```log
[6.50] splash screen hidden
[6.50] Started up in 6.50 seconds with 792 books

{'bsd_drives': {'main': '/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1s1': '/',
               '/dev/disk1s2': '/System/Volumes/Data',
               '/dev/disk1s3': '/System/Volumes/Preboot',
               '/dev/disk1s5': '/System/Volumes/VM',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2s1': '/Volumes/Kindle',
               '/dev/disk4s1': '/Volumes/calibre-5.26.0',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    4.8 USBMS: count found in cache: 657, count of files in metadata: 657, need_sync: False
DEBUG:    4.8 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    4.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    4.8 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 657
DeviceJob: set_books_in_library finished: time= 0.00913095474243164
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
Decrypted key file using IDString '5d5a6783fa3a' and UserName 'fred'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```
</details>

The key is the Default key found by DeDRM.

**Comment by ElleKayEm** [comment]
A default key picked up by DeDRM would be for Kindle for PC/Mac.  If you're dealing with an AZW from or for your Paperwhite, you need to enter its serial number into DeDRM's customization.  I don't see a book getting added to calibre in this log so I can't tell what the problem is.
