### ISSUE TITLE
Calibre 5.0.1 & Plugin 7.2.1 cannot remove DRM from  .azw file

### ISSUE THREAD

**Issue by Titandrow** [apprenticeharper/DeDRM_tools#1826]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [x]  Code block is used for `the log`.

---

## Log
<details><summary>Log DRM failure</summary>

```log
PUT YOUR LOG
[kindle-drm.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7072267/kindle-drm.txt)

```
</details>

**Comment by daibew** [comment]
I'm having the same issue using Kindle Version 1.26, DeDRM 7.2.1, Calibre 5.26
 my log is below and from what i can tell the failure is the same:

`calibre Debug log
calibre 5.26  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 42, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 42, 0) && KFX metadata reader (from KFX Input) (1, 42, 0) && KFX Input (1, 42, 0)
calibre 5.26  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 42, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 42, 0) && KFX metadata reader (from KFX Input) (1, 42, 0) && KFX Input (1, 42, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 92.0000013817014 x 91.00000136668288
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[0.79] main UI initialized...
[0.79] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.42.0: Importing /Users/Adam/Library/Application Support/Kindle/My Kindle Content/B088RCSDG1_EBOK/B088RCSDG1_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/bksfiigb.kfx-zip
DeDRM v7.2.1: Trying to decrypt bksfiigb.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: bksfiigb
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5a5da3a0-4acb-4c9d-ac98-fc7f6adae7c8.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/Adam/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/Adam/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'Adam'  on file  /Users/Adam/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'bba5472d9185'
trying IDString: b'a5f513fe2ea7'
[12.41] splash screen hidden
[12.41] Started up in 12.41 seconds with 1 books
trying IDString: b'bba5472d9184'
trying IDString: b'd12a995f1286'
trying IDString: b'292035d5fd80'
trying IDString: b'937798472365'
trying IDString: b'937798472361'
trying IDString: b'937798472365'
trying IDString: b'disk3s1s1'
trying IDString: b'disk3s6'
trying IDString: b'disk3s2'
trying IDString: b'disk3s4'
trying IDString: b'disk1s2'
trying IDString: b'disk1s1'
trying IDString: b'disk1s3'
trying IDString: b'disk3s5'
trying IDString: b'disk4s1'
trying IDString: b'disk6s1'
trying IDString: b'disk7s1'
trying IDString: b'9999999999'
Couldn't decrypt file.
trying username  b'Adam'  on file  /Users/Adam/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'bba5472d9185'
trying IDString: b'a5f513fe2ea7'
trying IDString: b'bba5472d9184'
trying IDString: b'd12a995f1286'
Decrypted key file using IDString 'd12a995f1286' and UserName 'Adam'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: bksfiigb
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 1 keys to try after 8.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5a5da3a0-4acb-4c9d-ac98-fc7f6adae7c8.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/u6kcv8h_plugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 8.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.42.0: Packaging /var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/bksfiigb.kfx-zip
Processing container: B088RCSDG1_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/vh/02vfxp2s38j110t5jb4k50xc0000gn/C/calibre_5.26.0_tmp_fuyoic51/zmmn7cqb_add_books/0/B088RCSDG1_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 8.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B088RCSDG1_EBOK.azw has DRM and cannot be converted
`

**Comment by deirdrew** [comment]
The same issue, can suddenly no longer remove DRM from Amazon AZW books - using Kindle for PC 1.17.1 and 
![image](https://user-images.githubusercontent.com/56893921/132598844-760f84ef-6565-465f-ab4b-180908d5ec92.png)

**Comment by ElleKayEm** [comment]
@Titandrow For KFX format, you need Kindle for PC 1.26 or earlier.  Alternatively, use a method to avoid KFX format.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

@daibew As a Mac user, you might need to try going back to calibre 4.23 and DeDRM 6.8.1.  If that's successful, you should be able to update back to your current versions.

@deirdrew DeDRM Update to DeDRM 7.2.1.

**Comment by deirdrew** [comment]
Thanks, but we seem to be not communicating fully.

 

I have had no issue until today. 

 

I last added an Amazon AZW on my Windows 10 PC on the 5th. I have always used the lasted version of DeDRM (7.2.1) 

 

Again, these are AZW format, not KFX format as I use old Kindle for PC PC v 1.11.0 (circa 2015) or v 1.17

 

Again, Amazon has made a change, alas. ☹

 

D

**Comment by ElleKayEm** [comment]
@deirdrew 
Your screenshot shows 7.2.0.  Just tried myself and had no trouble.  Post a log if you want help.

**Comment by deirdrew** [comment]
Oof –  you are right! I noticed it right after I sent the last email.

 

It had been 7.21 but somehow changed within the few days as I had no issue when removing DRM on the 2nd from about 16 Amazon books.  

This is really weird as the 7.20 download was deleted as soon as 7.21 came out as it didn’t work for me and I alerted him as soon as it came out. 

The new version was done quickly and worked perfectly ever since. 

 

This is a head scratcher, for sure. Seriously, the thing I have done was import to import 2 older libraries into Calibre on the 5th so I could switch libraries from

this system’s library.

 

Thanks for your help. If I figure out how the old plug in was loaded I will let you know

D

**Comment by ElleKayEm** [comment]
The old plugin could have come with the old library.

**Comment by deirdrew** [comment]
Had to as I made the main current library during the period they were
figuring out what was wrong with v 7.20 of the plugin. I added 7.21 to
it but never imported the other 2 libraries at the time and they must
had the non working 7.20 All my other plugins alert me to a version
update so I didn't notice the issue after the 2 libraries were
imported 3 days ago. 

 -------Original Message-------
 From: ElleKayEm ***@***.***>
 To: apprenticeharper/DeDRM_tools ***@***.***>
 Cc: deirdrew ***@***.***>, Mention
***@***.***>
 Subject: Re: [apprenticeharper/DeDRM_tools] Calibre 5.0.1 & Plugin
7.2.1 cannot remove DRM from .azw file (#1826)
 Sent: Sep 08 '21 9:37pm

The old plugin could have come with the old library. 

--
 You are receiving this because you were mentioned.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ElleKayEm** [comment]
@Titandrow Are you able to use one of the methods to get the book in a non-KFX format?  If not, you may be out of luck.
