### ISSUE TITLE
v7.2.1 — Full Release

### ISSUE THREAD

**Issue by Andressa-creator** [apprenticeharper/DeDRM_tools#1834]
### Discussed in https://github.com/apprenticeharper/DeDRM_tools/discussions/1656

<div type='discussions-op-text'>

<sup>Originally posted by **apprenticeharper** April 11, 2021</sup>
I messed up some white space. I still haven't got KFX to work for me, but I don't think I've actually broken anything this time. :)

<hr /><em>This discussion was created from the release <a href='https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.2.1'>v7.2.1 — Full Release</a>.</em></div>

calibre Debug log
calibre 5.26  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Failed to initialize plugin: '/Users/andressamaia/Library/Preferences/calibre/plugins/Kindle and Mobipocket DeDRM.zip'
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.26  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[1.26] main UI initialized...
[1.26] Hiding splash screen
Starting QuickView
[15.45] splash screen hidden
[15.45] Started up in 15.45 seconds with 0 books
DeDRM v7.2.1: Trying to decrypt A morte e o meteoro.azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
DeDRM v7.2.1: Trying to decrypt Después de la ira (Spanish Edition).azw3
DeDRM v7.2.1: Trying to decrypt Distancia de rescate (Spanish Edition).azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A morte e o meteoro
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Después de la ira (Spanish Edition)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Distancia de rescate (Spanish Edition)
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.4 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Después de la ira (Spanish Edition)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.7 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A morte e o meteoro
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.9 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt Maria Altamira.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Maria Altamira
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
DeDRM v7.2.1: Trying to decrypt The Collector of Leftover Souls.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Collector of Leftover Souls
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Distancia de rescate (Spanish Edition)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 2.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt Torto arado.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Torto arado
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
trying username  b'andressamaia'  on file  /Users/andressamaia/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a67549f0f'
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Maria Altamira
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.7 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Collector of Leftover Souls
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.7 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Decrypted key file using IDString '5d5a67549f0f' and UserName 'andressamaia'
DeDRM v7.2.1: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Torto arado
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Got SerialNumber from database default_key_2
Got UsernameHash from database default_key_2
Found 8 keys to try after 1.6 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: '/Users/andressamaia/Library/Preferences/calibre/plugins/Kindle and Mobipocket DeDRM.zip'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: '/Users/andressamaia/Library/Preferences/calibre/plugins/Kindle and Mobipocket DeDRM.zip'
Failed to initialize plugin: '/Users/andressamaia/Library/Preferences/calibre/plugins/Kindle and Mobipocket DeDRM.zip'

**Comment by Andressa-creator** [comment]
It is my very first time trying to use calibre and that is what I got after accessing through debug mode. Any idea why I cannot still remove DRM?

**Comment by th3jamin** [comment]
you will most likely need to configure the plugin with a serial number or key from you Kindle Paperwhite or Kindle Desktop App. For example, if you download via USB from Amazon's website, you will have a choice of "device" the book is being downloaded for. You will then need to go to preferences -> plugins -> search for dedrm and configure it. You will then need to enter your kindle serial number into the eInk Kindle section.

**Comment by gandroz** [comment]
Same here, unable to remove DRM from kfx-zip file. The SN is well entered in the plugin config, I add the book directly from my kindle, I can see it in the library with the cover, but it fails to convert to another format epub or mobi.

**Comment by ElleKayEm** [comment]
@Andressa-creator Looks like a book downloaded from the website.  Those need to be for an E-ink Kindle (not a Fire), and you need to add the Kindle's serial number into DeDRM's customization.

@gandroz KFX format directly from a Kindle cannot be DeDRMed at this time.  See this post for workarounds: https://www.mobileread.com/forums/showthread.php?t=283371
