### ISSUE TITLE
Can't convert epub - calibre 5.27/DeDRM v7.2.1

### ISSUE THREAD

**Issue by peshay** [apprenticeharper/DeDRM_tools#1840]
Debug log here:

```
calibre Fehlerdiagnoseprotokoll
calibre 5.27  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.27  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.5.0', 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 147.50000221522777 x 147.0000022077185
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Team Topologies.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “Team Topologies.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Couldn't decrypt after {2:.1f} seconds. DRM free perhaps?".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.6 seconds. DRM free perhaps?
[15.77] splash screen hidden
[15.77] Started up in 15.77 seconds with 0 books
Added TEAM TOPOLOGIES to db in: 0.0
Added 1 books in 1.0 seconds
```

**Comment by gsgleason** [comment]
Where did you get the epub?  Are you sure it has DRM?
