### ISSUE TITLE
Tool 7.2.1 Update error 

### ISSUE THREAD

**Issue by crash28810** [apprenticeharper/DeDRM_tools#1846]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---I am a 64 bit user and tried updating the most current version of Calibre

## My Environment
5.27 Calibre: `Version`
### Kindle: `Version`
7.2.1 DeDRM: `Version`

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>
calibre, version 5.27.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.27 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 43, 0) && Package KFX (from KFX Input) (1, 43, 0) && ACE (1, 1, 2) && APNX Generator (1, 1, 0) && Adlibris.se (0, 1, 0) && Amazon.com Multiple Countries (1, 0, 0) && Annotations (1, 16, 0) && Audit Log (1, 0, 16) && Author Book Count (2, 2, 2) && Author Book Count Hierarchy (1, 2, 3) && Auto Datestamp and View (0, 0, 9) && BBC GoodFood Recipe Reader (1, 1, 0) && BOL_DE (0, 9, 2) && BOL_NL (4, 5, 5) && BigOven Recipe Reader (1, 0, 1) && Bokon.se (0, 1, 0) && Bokus (0, 1, 0) && BookFusion Plugin (0, 5, 5) && CDON.se (0, 1, 0) && CalibreSpy (1, 0, 84) && Chinese Text Conversion (2, 4, 0) && Clean Metadata (0, 0, 6) && Clipboard Search (1, 3, 1) && Consolidate All Library Metadata (2, 0, 40) && Copy Cover To Device (2, 0, 4) && Count Pages (1, 11, 1) && DOC Input (1, 0, 1) && Diaps Editing Toolbag (0, 3, 7) && Drop Search Results (1, 0, 11) && Embed Comic Metadata (1, 6, 1) && English Noun Frequency (1, 0, 13) && Entities Manager (1, 0, 15) && EpubCheck (0, 2, 3) && EpubMerge (2, 11, 0) && EpubSplit (3, 1, 0) && Ex Libris (1, 0, 19) && Extract ISBN (1, 5, 0) && F_rating (3, 2, 0) && FanFicFare (4, 5, 0) && Favourites Menu (1, 0, 5) && Find Duplicates (1, 8, 10) && Generate Cover (2, 0, 2) && Goodreads Sync (1, 15, 1) && Hymn Reader (1, 0, 1) && Hyphenate This! (0, 1, 3) && Import List (1, 5, 6) && Job Spy (1, 0, 190) && KFX metadata reader (from KFX Input) (1, 43, 0) && KFX Input (1, 43, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 5, 3) && Kindle Collections (1, 7, 29) && KindleUnpack - The Plugin (0, 83, 0) && Kobo Books (1, 8, 2) && Kobo Utilities (2, 14, 1) && KoboTouchExtended (3, 5, 3) && KyBook3 Sync (1, 0, 12) && LanguageTool (0, 1, 1) && Library Codes (1, 0, 50) && Library Splitter (1, 0, 4) && LubimyCzytac (2, 2, 6) && Manage Series (1, 2, 11) && Manage Sony x50 Reader Book List (1, 2, 11) && Media File Importer (1, 0, 24) && Medical Reader (1, 0, 1) && Modify ePub (1, 6, 3) && MultiColumnSearch (1, 0, 87) && OPML Importer (1, 0, 1) && Open With (1, 5, 13) && Overdrive Link (2, 45, 1) && Prettify Cover (1, 5, 0) && Prince PDF (1, 5, 0) && QRCode Tracker Filidel (0, 7, 0) && Quality Check (1, 11, 2) && QuarantineAndScrub (3, 6, 115) && Quick Preferences (1, 5, 0) && Reading List (1, 7, 6) && Recipe Reader (1, 0, 1) && Resize Cover (1, 1, 0) && Save Composite Custom Columns (1, 1, 1) && Save To Format (0, 0, 6) && Save Virtual Libraries To Column (2, 0, 1) && Save Virtual Libraries To Column GUI (2, 3, 0) && ScrambleEbook (0, 4, 5) && Search The Internet (1, 8, 1) && Similar Stories (1, 0, 58) && Skoob Books (1, 5, 1) && Skoob Sync (0, 3, 9) && SmartEject (2, 3, 0) && Sony PRS-T1 notes plugin (1, 1, 0) && TTS to MP3 (0, 5, 9) && Unplugged (1, 0, 0) && User Category (1, 5, 5) && View Manager (1, 6, 0) && Walk Search History (1, 3, 2) && Wiki Reader (2, 2, 1) && Wikidata gui (2, 0, 0) && X-Ray Creator (3, 2, 1) && Zotero Metadata Importer (1, 0, 70) && all recipes Recipe Reader (1, 0, 2) && food network Recipe Reader (1, 0, 2) && Overdrive Link* (2, 45, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by Leseratte10** [comment]
That error means that you aren't running DeDRM 7.2.1 but some older version of the plugin that's not compatible with the most recent Calibre version. 

Try removing the plugin and then reinstall 7.2.1 again and it should work.
