### ISSUE TITLE
AZW failure message

### ISSUE THREAD

**Issue by FlashCrash** [apprenticeharper/DeDRM_tools#185]
Recently-purchased Kindle books could not be deDRM'd, and following error message was produced:

calibre, version 2.77.0
ERROR: Could not open ebook: Failed to read book, C:\Users\Bob\Documents\Calibre Library\Unknown\B01M0VGPLY EBOK (72)\B01M0VGPLY EBOK - Unknown.azw click "Show Details" for more information

Traceback (most recent call last):
  File "site-packages\calibre\utils\ipc\simple_worker.py", line 286, in main
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 81, in __init__
MobiError: Unknown book type: '\x81\xc4\xde\x02|\x8c"\x08'

Thanks.

**Comment by ElleKayEm** [comment]
You've got the new KFX format which can't be DeDRMed yet.  If you can revert to Kindle for PC 1.17, use that and uncheck automatic updates.

If you have an E-ink Kindle, you can still currently get the older format from the website with the "download & transfer via USB" method.  Remember to add the serial number to the plugin customization.

**Comment by FlashCrash** [comment]
Thank you, Thank you, Thank you.

Reverting to v1.17 worked.

Bob
