### ISSUE TITLE
Error trying to load books into Calibre and open them without DRM

### ISSUE THREAD

**Issue by eeganes** [apprenticeharper/DeDRM_tools#1864]
1. Using MacOS Big Sur  11.5.2
2. Using Kindle 1.30.0 (older version on purpose)
3. Using DeDRM_tools_7.2.1 2

- I downloaded a Kindle book from my Library onto my local laptop by opening the Kindle app on my desktop.

- I went into Calibre, followed these instructions from your readme:

  _Open calibre's Preferences dialog.  Click on the "Plugins" button.  Next, click on the button, "Load plugin from file".  
   Navigate to the unzipped DeDRM_tools folder, find the file "DeDRM_plugin.zip".  Click to select the file and select 
   "Open".  Click "Yes" in the "Are you sure?" dialog box. Click the "OK" button in the "Success" dialog box._

- Using Calibre's Add Books from a single Folder, I added the Kindle book I downloaded to my laptop. It had format/title:
- "B074MD56RY_EBOK.azw" (there is also a version that I did not upload that is titled: "CR!PN0Z414MVX6WF4YYQFBQ6Q6VJW3F.azw.md")

Calibre was unable to open the book or to convert it to another e-format like epub or mobi.
This used to work before I updated my MacOS to Big Sur.

Debug log from Calibre:
calibre Debug log
calibre 5.21  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.21  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.00000193738563 x 129.00000193738563
Using calibre Qt style: True
[0.00] Starting up...
[4.74] Showing splash screen...
[5.14] splash screen shown
[5.14] Initializing db...
[5.22] db initialized
[5.22] Constructing main UI...
[6.95] main UI initialized...
[6.95] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B074MD56RY_EBOK.azw
Using Library AlfCrypto Python
[77.60] splash screen hidden
[77.61] Started up in 77.61 seconds with 512 books
Using Library AlfCrypto Python
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/dchander/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2011 file: /Users/dchander/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Found k4Mac kinf2011 file: /Users/dchander/Library/Application Support/Kindle/storage/.kinf2011
trying username  b'dchander'  on file  /Users/dchander/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'9d5c76554316'
Decrypted key file using IDString '9d5c76554316' and UserName 'dchander'
trying username  b'dchander'  on file  /Users/dchander/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
trying IDString: b'9d5c76554316'
trying IDString: b'1d4df378a88a'
trying IDString: b'273e5a65c3a4'
trying IDString: b'273e5a65c3a5'
trying IDString: b'273e5a65c3a0'
trying IDString: b'273e5a65c3a1'
trying IDString: b'273e5a65c3a4'
trying IDString: b'disk1s5s1'
trying IDString: b'disk1s4'
trying IDString: b'disk1s2'
trying IDString: b'disk1s6'
trying IDString: b'disk1s1'
trying IDString: b'disk1s5'
trying IDString: b'disk2s2'
trying IDString: b'9999999999'
Couldn't decrypt file.
trying username  b'dchander'  on file  /Users/dchander/Library/Application Support/Kindle/storage/.kinf2011
trying IDString: b'9d5c76554316'
Decrypted key file using IDString '9d5c76554316' and UserName 'dchander'
DeDRM v7.2.1: Found 2 new keys
DeDRM v7.2.1: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
    raise DrmException("The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.")
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 5.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 433, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 289, in get_metadata
  File "calibre/ebooks/metadata/mobi.py", line 503, in get_metadata
  File "calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "calibre/ebooks/mobi/reader/headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'

**Comment by ElleKayEm** [comment]
That's KFX format.  It can only be decrypted from version 1.26 (and earlier) of the Kindle app.  Or you can disable KFX downloads to get an older format which can be decrypted.  See method 2 at this post:  https://www.mobileread.com/forums/showthread.php?t=283371

And this post for Mac info:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by eeganes** [comment]
It appears my older version of Kindle (1.17) will not run on OS Big Sur. I'll try to follow your instructions after backing up my Kindle content folder.

**Comment by ElleKayEm** [comment]
Yes, I think you need at least Kindle 1.25 as anything older isn't 64-bit.  I'd just delete the Kindle content folder. 
 You'll need to download new copies of the books anyway to deDRM them.
