### ISSUE TITLE
Unable to install plug-in from file

### ISSUE THREAD

**Issue by jkaczor** [apprenticeharper/DeDRM_tools#1865]
## CheckList
- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Log
<details><summary>Unable to install plug-in from file</summary>

```log
calibre 5.28 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 44, 0) && Package KFX (from KFX Input) (1, 44, 0) && KFX metadata reader (from KFX Input) (1, 44, 0) && KFX Input (1, 44, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0) && Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 185, in exec_module
  File "calibre\customize\zipplugin.py", line 181, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
```
</details>

**Comment by ElleKayEm** [comment]
Looks like you're trying to install an old version of the plugin which is incompatible with calibre 5.x.  Be sure you choose the DeDRM_plugin.zip that is inside the unzipped DeDRM 7.2.1 folder.

**Comment by johannesweber42** [comment]
> 
> 
> Looks like you're trying to install an old version of the plugin which is incompatible with calibre 5.x. Be sure you choose the DeDRM_plugin.zip that is inside the unzipped DeDRM 7.2.1 folder.

I'm getting the same issue with DeDRM 7.2.1

**Comment by ElleKayEm** [comment]
The error shown in this log is from trying to load a Python 2 version of DeDRM (6.8.1 or earlier) into a Python 3 version of calibre (5.0 or later).
