### ISSUE TITLE
It just won't work

### ISSUE THREAD

**Issue by jonjon70** [apprenticeharper/DeDRM_tools#1869]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
<For some reason the DeDRM just isn't working. Is this happening for anyone else?>

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.28  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kindle hi-res covers (0, 5, 0) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
calibre 5.28  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kindle hi-res covers (0, 5, 0) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.35] db initialized
[0.35] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.80] main UI initialized...
[1.80] Hiding splash screen
[1.88] splash screen hidden
[1.88] Started up in 1.88 seconds with 75 books
Starting QuickView
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Sharp Objects) finished
Convert book 1 of 1 (Sharp Objects)
	DeDRM v7.2.1: Trying to decrypt 072xed2h.azw3
	Using Library AlfCrypto Python
	Using Library AlfCrypto Python
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Sharp Objects
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/jonreyes/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'jonreyes'  on file  /Users/jonreyes/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'a545e9e7a575'
	trying IDString: b'99875ee333fe'
	Decrypted key file using IDString '99875ee333fe' and UserName 'jonreyes'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Sharp Objects
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 4 keys to try after 1.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  cover: '/var/folders/5g/wh84lr4x245d1hw5lsqzn9jw0000gn/C/calibre_5.28.0_tmp_yivcclyq/i25hsnvn.jpeg'
	  verbose: 2
	  read_metadata_from_opf: '/var/folders/5g/wh84lr4x245d1hw5lsqzn9jw0000gn/C/calibre_5.28.0_tmp_yivcclyq/npiu55zx.opf'
	  change_justification: 'left'
	  output_profile: 'kindle_pw3'
	Resolved conversion options
	calibre version: 5.28.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'left',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/5g/wh84lr4x245d1hw5lsqzn9jw0000gn/C/calibre_5.28.0_tmp_yivcclyq/i25hsnvn.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x115d1b070>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x115d1b6d0>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/5g/wh84lr4x245d1hw5lsqzn9jw0000gn/C/calibre_5.28.0_tmp_yivcclyq/npiu55zx.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	DeDRM v7.2.1: Trying to decrypt 072xed2h.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Sharp Objects
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/jonreyes/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'jonreyes'  on file  /Users/jonreyes/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'a545e9e7a575'
	trying IDString: b'99875ee333fe'
	Decrypted key file using IDString '99875ee333fe' and UserName 'jonreyes'
	DeDRM v7.2.1: Found 1 new key
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Sharp Objects
	Got SerialNumber from database default_key_1
	Got UsernameHash from database default_key_1
	Found 4 keys to try after 1.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 176, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/5g/wh84lr4x245d1hw5lsqzn9jw0000gn/C/calibre_5.28.0_tmp_yivcclyq/072xed2h.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 163, in check_for_drm
	calibre.ebooks.DRMError: Sharp Objects

```
</details
<img width="397" alt="Screen Shot 2021-10-07 at 9 03 56 PM" src="https://user-images.githubusercontent.com/78506249/136482350-411d0bae-9115-4347-8027-741d1635de11.png">
>

**Comment by jonjon70** [comment]
Thank you, I redownloaded the files. I was pressing another device. BUT, that device's serial was also included. Maybe in the wrong slot? Where does Kindle Fire fall in the configuration?

**Comment by ElleKayEm** [comment]
Needs to be an E-ink Kindle, not a Fire.
