### ISSUE TITLE
ADE key not found

### ISSUE THREAD

**Issue by sportmint** [apprenticeharper/DeDRM_tools#1870]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Exception when getting default Adobe Key

## Log
<details><summary>calibre Debug log</summary>

```log
calibre Debug log
calibre 5.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
calibre 5.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Obok DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.10344827586206
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.69] splash screen shown
[0.69] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.38] main UI initialized...
[1.38] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Engadiner Hochjagd-1.epub
DeDRM v7.1.0: Verifying zip archive integrity
DeDRM v7.1.0: Engadiner Hochjagd-1.epub is a secure Adobe Adept ePub
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.1.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 356, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 360, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 340, in CryptUnprotectData
calibre_plugins.dedrm.adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 642, in run
  File "calibre_plugins.dedrm.__init__", line 413, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Exception ignored in: <function NativeFunction.__del__ at 0x000002A505759A60>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000002A505759A60>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
[4.12] splash screen hidden
[4.12] Started up in 4.12 seconds with 955 books
Added Engadiner Hochjagd to db in: 0.1
Added 1 books in 0.4 seconds


```
</details>
When I go to "Customize Plugin" and click "Adobe Digital Editions ebooks" there ist no key. When I click then the "+" button -> "The default encryption key for Adobe Digital Editions could not be found".
In the registry the activation exists under "Computer\HKEY_CURRENT_USER\SOFTWARE\Adobe\Adept\Activation".
The book come from the Kobo Desktop App.

It is the first time that I use it on this computer. Years ago I had no problems on the old machine.

**Comment by ElleKayEm** [comment]
ADE was authorized with your Adobe ID before you opened the acsm file?
