### ISSUE TITLE
SyntaxError:invalid syntax (calibre_plugins.dedrm._init_,line 164) when loading plugin 7.2.1 in Calibre 5.12

### ISSUE THREAD

**Issue by eBug** [apprenticeharper/DeDRM_tools#1878]
calibre, version 5.12.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 164)

calibre 5.12  embedded-python: False is64bit: True
Linux-5.10.0-8-amd64-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.10.0-8-amd64', '#1 SMP Debian 5.10.46-5 (2021-09-23)')
Python 3.9.2
Interface language: None
Successfully initialized third party plugins: Kindle Collections (1, 7, 29) && Obok DeDRM (6, 3, 6)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 316, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 293, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 185, in exec_module
    compiled = self.get_code()
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 181, in get_code
    return compile(self.get_source_as_bytes(fullname), f'calibre_plugins.{self.plugin_name}.{self.fullname_in_plugin}',
  File "calibre_plugins.dedrm.__init__", line 164
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by eBug** [comment]
OK. I tried to install the container zip. My blame.
