### ISSUE TITLE
DeDRM Fails for OBOK plugin after Kobo Desktop update

### ISSUE THREAD

**Issue by jgoodleaf** [apprenticeharper/DeDRM_tools#1885]
I just purchased a book through Kobo and wanted to add it to my library. My Kobo Desktop app force-updated itself. After I downloaded the book, it appears to add to the library correctly, but in the ebook viewer, although the chapter headings are readable, the body content is gibberish. 

I tried again with debug mode, after first removing the book, and Calibre reports successful decryption but it's clearly not fully decrypted when viewed. 

I'm using latest releases of everything. The new version of Kobo Desktop is: 4.29.14582

Any suggestions?

`calibre Debug log
calibre 5.29  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 44, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 44, 0) && KFX metadata reader (from KFX Input) (1, 44, 0) && KFX Input (1, 44, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0) && Obok DeDRM (7, 2, 1)
calibre 5.29  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 44, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 44, 0) && KFX metadata reader (from KFX Input) (1, 44, 0) && KFX Input (1, 44, 0) && Set KFX metadata (from KFX Output) (1, 56, 0) && KFX Output (1, 56, 0) && Obok DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.01] main UI initialized...
[1.01] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre/db/cache.py", line 1458, in set_metadata
  File "calibre/db/cache.py", line 1381, in set_cover
  File "calibre/db/backend.py", line 1532, in set_cover
  File "calibre/utils/img.py", line 288, in save_cover_data_to
  File "calibre/utils/img.py", line 196, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[3.86] splash screen hidden
[3.86] Started up in 3.86 seconds with 892 books
Running Obok DeDRM v7.2.1
DEBUG:    9.4 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
/var/folders/jr/dfwwntcs0053pyln5ysh52fc0000gn/T/tmpusbbty6p
DEBUG:    9.4 got kobodir /Users/<username>/Library/Application Support/Kobo/Kobo Desktop Edition
Error parsing Kobo plist: no legacy user key found.
Found 44 possible keys to try.
DEBUG:   12.8 BookListTableWidget:get_books - book_num: 5
DEBUG:   12.8 BookListTableWidget:get_books - book: The House of Rust
DEBUG:   12.8 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v7.2.1 - Decrypting The House of Rust
Trying key:  b'9e81ed7cc878535727b5ce7eab330b85'
Checking text:b'I\x8a\n\xcb\xe7\x8f_v\xd9\xcd':
Perhaps utf-8 without BOM
Bad character at 1, value 138
Decryption failed, trying next key.
Trying key:  b'19aac3b4c16390f8d05b5cf998f1dc3c'
Checking text:b'\xe1\\\x91\xcf\x91f\x84\xbd\xa6y':
Perhaps utf-8 without BOM
Bad character at 0, value 225
Decryption failed, trying next key.
Trying key:  b'1deef0ce83f05d91414233caa73a81b2'
Checking text:b'f\xeb\x9b\x8cI\xed \xdb\xef\x1f':
Perhaps utf-8 without BOM
Bad character at 1, value 235
Decryption failed, trying next key.
Trying key:  b'250d61cfc96e9bc3fb95a2f6fa861629'
Checking text:b'^\x86\xc9uV\x1cdn\x88\xa0':
Perhaps utf-8 without BOM
Bad character at 1, value 134
Decryption failed, trying next key.
Trying key:  b'063e8daf0d3f5fdf60f2ce8a00c150ae'
Checking text:b'\xf1xY\xc9\xd5A\x1a\x13\x195':
Perhaps utf-8 without BOM
Bad character at 0, value 241
Decryption failed, trying next key.
Trying key:  b'de430bd2d08880b27535dd8113898bb4'
Checking text:b'\xc4I\xb0;+\xa9+\xb5\x9fs':
Perhaps utf-8 without BOM
Bad character at 0, value 196
Decryption failed, trying next key.
Trying key:  b'73ffe1e846c946a8eb274394d1ae62d6'
Checking text:b'\x84\xd6\x8f+\xa8\x12\xbbP\x03p':
Perhaps utf-8 without BOM
Bad character at 0, value 132
Decryption failed, trying next key.
Trying key:  b'3dcd260f8920b6806d56e0b51bde769a'
Checking text:b'\x7f\x1d%I\x07\xedH\xa5\xafK':
Perhaps utf-8 without BOM
Bad character at 1, value 29
Decryption failed, trying next key.
Trying key:  b'48feb23ef2ac1af1a846f956064cf6fd'
Checking text:b'LL]\xac\xf1\xcd\x9cT\xcb\xdd':
Perhaps utf-8 without BOM
Bad character at 3, value 172
Decryption failed, trying next key.
Trying key:  b'768cc0d66cb3769f864ae7255d4d35a2'
Checking text:b'\xd3\xcb\xce\x1en\xc2WJpl':
Perhaps utf-8 without BOM
Bad character at 0, value 211
Decryption failed, trying next key.
Trying key:  b'6327808466fcd9152b6e91d1c48f996f'
Checking text:b'\x0f\t+\xf9\xbeDD\xe5\x070':
Perhaps utf-8 without BOM
Bad character at 0, value 15
Decryption failed, trying next key.
Trying key:  b'5275d67706616ab4ec73bc877eac18cd'
Checking text:b'\xb2\xf6\xc4-@\x8b\xde\xb9\xcca':
Perhaps utf-8 without BOM
Bad character at 0, value 178
Decryption failed, trying next key.
Trying key:  b'1dcce8b70f410dc0e7661eceb2214651'
Checking text:b'\xb8\t\x97\x19\x9a\x1c\xab"\xed}':
Perhaps utf-8 without BOM
Bad character at 0, value 184
Decryption failed, trying next key.
Trying key:  b'3fdb9561059d65d6ba6f6d7e7e532324'
Checking text:b'\x8c\xfd`\x99\x97\xbe\xe8\x95z\x1e':
Perhaps utf-8 without BOM
Bad character at 0, value 140
Decryption failed, trying next key.
Trying key:  b'd75b0257acc38efd90561b23675c9b0b'
Checking text:b'>AW\xe1q\xf32\xbf\xbeD':
Perhaps utf-8 without BOM
Bad character at 3, value 225
Decryption failed, trying next key.
Trying key:  b'a4ba3fb26ed37c59c0b9d4e7d937ad5b'
Checking text:b'\xbe\x02V\xef\x1f)\xd6,\x98.':
Perhaps utf-8 without BOM
Bad character at 0, value 190
Decryption failed, trying next key.
Trying key:  b'd24d639067c3633ccb647b51fd975a3c'
Checking text:b'tj:eJ/m6L ':
Perhaps utf-8 without BOM
Seems to be good text
Success!
DEBUG:   13.3 DecryptAddProgressDialog::do_book_action - decrypted book: 'The House of Rust'
Obok DeDRM v7.2.1 - Added The House of Rust: A Novel
Obok DeDRM v7.2.1 - wrapping up results.
Worker Launch took: 0.02 seconds
`

**Comment by jgoodleaf** [comment]
UPDATE: I downgraded to Kobo Desktop 4.28.x with the same result. I re-downloaded all the content following the downgrade/signout/signin and Calibre reports decryption, but the file is unreadable.

Is the OBOK plugin's text "goodness" test too flexible?

**Comment by jgoodleaf** [comment]
Yes, that resolves the issue for me. (I should have searched more thoroughly; I just assumed it was a recent problem and didn't look back through all the issues... Sorry).

I'll leave this parked here, to serve the Googlers who will follow me :)
