### ISSUE TITLE
Install DeDRM tools 7.2.1 in Calibre 5.12 - It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by zetneteork** [apprenticeharper/DeDRM_tools#1889]
The plugin is invalid. It does not contain a top-level `__init__.py` 

**DeDRM:** 7.2.1
**Calibre:** 5.12

Unable to install this Calibre plugin in the Linux system.

```python
calibre, version 5.12.0
CHYBA: Neošetřená výjimka: <b>InvalidPlugin</b>:The plugin in '/home/lukas/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.12  embedded-python: False is64bit: True
Linux-5.10.0-9-amd64-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.10.0-9-amd64', '#1 SMP Debian 5.10.70-1 (2021-09-30)')
Python 3.9.2
Interface language: cs
Successfully initialized third party plugins: Annotations (1, 16, 0) && Extract ISBN (1, 5, 0) && Find Duplicates (1, 8, 10) && Generate Cover (2, 0, 2) && Goodreads (1, 5, 1) && Goodreads Sync (1, 15, 1) && Kindle hi-res covers (0, 5, 0) && Manage Series (1, 2, 11) && Search The Internet (1, 8, 1) && Wikidata gui (2, 0, 0) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 316, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 284, in load
    plugin_name = self._locate_code(zf, path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 379, in _locate_code
    raise InvalidPlugin(('The plugin in %r is invalid. It does not '
calibre.customize.InvalidPlugin: The plugin in '/home/lukas/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file
```

This issue is reproducible on the Windows platform too.

**DeDRM:** 7.2.1
**Calibre:** 5.12

```python
calibre, version 5.29.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.29 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Find Duplicates (1, 8, 5) && Goodreads Sync (1, 15, 1) && Wiki Reader (2, 2, 1) && X-Ray Creator (3, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 327, in add_plugin
  File "calibre\customize\ui.py", line 477, in add_plugin
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 284, in load
  File "calibre\customize\zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

```

**Comment by pftaylor61** [comment]
There is no file DeDRM_plugin.zip in the archive. I created one, by zipping the DeDRM_plugin directory, but this still will not install. Please advise...

**Comment by ElleKayEm** [comment]
Yes, there is.  Download this:  https://github.com/apprenticeharper/DeDRM_tools/releases/download/v7.2.1/DeDRM_tools_7.2.1.zip

Make sure your browser is not automatically unzipping everything on download.  Then when you unzip the main file, you will see DeDRM_plugin.zip, Obok_plugin.zip, and 3 txt files.
