### ISSUE TITLE
Calibre 2.31 / DeDRM 6.2.1 PyQt4.py error

### ISSUE THREAD

**Issue by dbyron** [apprenticeharper/DeDRM_tools#19]
I find that the DeDRM 6.2.1 tools work fine with Calibre 1.48, but if I upgrade to 2.31 I get an import error on PyQt4.py whenever I try to customize the Ignoble Epub plugin.

The exact exception is:
calibre, version 2.31.0
ERROR: Unhandled exception: <b>ImportError</b>:No module named PyQt4.Qt

calibre 2.31  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Ignoble Epub DeDRM
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 292, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 154, in do_user_config
  File "calibre_plugins.ignobleepub.__init__", line 174, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.ignobleepub.config", line 12, in <module>
ImportError: No module named PyQt4.Qt

I've tried scrubbing my machine of all components and reinstalling everything but I always seem to get the same response.

Have I overlooked something?

**Comment by ElleKayEm** [comment]
Uninstall the Ignoble plug-in.  It is no longer necessary as the DeDRM plug-in includes the B&N DRM removal.  Then you'll be able to update calibre.

**Comment by chyron8472** [comment]
Hey! This seems to have fixed my issue. I wasn't paying attention to that there were other dedrm plugins installed other than the one labelled "DeDRM". Now that I've uninstalled the other DRM related file type plugins, my issue is resolved.

**Comment by dbyron** [comment]
Thanks. I'll give that a try. Didn't realize that ignoble was unnecessary.

**Comment by frojack** [comment]
Even without ignoble installed there are issues.  

Your old keys probably won't work anymore, and even if you had nook for pc, (not the newest version - which is buggered) and can actually read books using it, there is often failures upon import to calibre.

Log Snippit:-----------
DeDRM v6.2.1: Failed to decrypt with key yadda-yadda_XXXX after 0.4 seconds
DeDRM v6.2.1: Trying Encryption key yadda-yadda_XXXX
Could not decrypt rdmewp.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 278, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 209, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 180, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\pycrypto-2.6.1-py2.7-win32.egg\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.2.1: Failed to decrypt with key yadda-yadda_XXXX after 0.4 seconds
DeDRM v6.2.1: Looking for new NOOK Study Keys after 0.4 seconds
No nook Study log files have been found.
DeDRM v6.2.1: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 588, in run
  File "calibre_plugins.dedrm.__init__", line 270, in ePubDecrypt
DeDRMError: DeDRM v6.2.1: Ultimately failed to decrypt after 0.4 seconds.   

----------------
Only after I googled up a copy of Nook Study (its getting harder to find) and got it set up (lied a lot) so it could open my nook library would the plugin work because if found the nook-study log, and extracted some keys.  From then on even the Nook for PC downloads would import properly.

What is this "ValueError: Key cannot be the null string" message, and why is it suddenly showing up now?

**Comment by apprenticeharper** [comment]
The error message is just an indication that the decryption hasn't worked. Decrypting with with wrong key leads to gibberish, which can result in a variety of error messages.

I hope that the support for getting the B&N key via email address and password that's in the new 6.2.2 release will make decrypting B&N ebooks less painful.
