### ISSUE TITLE
 InvalidPlugin: The plugin in u'C:\\Users\\Casa\\Downloads\\DeDRM_tools_6.5.3.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by sdfgsdfgsdfgsdfsafsdfased** [apprenticeharper/DeDRM_tools#190]
calibre, version 2.76.0
ERRO: Exceção sem tratamento: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\123\\Downloads\\DeDRM_tools_6.5.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.76  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 463, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 58, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Casa\\Downloads\\DeDRM_tools_6.5.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by sdfgsdfgsdfgsdfsafsdfased** [comment]
Sorry, I had to extract it.
