### ISSUE TITLE
I cannot remove DRM

### ISSUE THREAD

**Issue by eriksonlima** [apprenticeharper/DeDRM_tools#1906]
attempt log:

calibre Log de Debug
calibre 5.31.1  embedded-python: True is64bit: True
Linux-5.8.0-53-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-53-generic', '#60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021')
Python 3.8.5
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.31.1  embedded-python: True is64bit: True
Linux-5.8.0-53-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-53-generic', '#60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021')
Python 3.8.5
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.76] main UI initialized...
[0.76] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Programando com Perl.pdf
DeDRM v7.2.1: Programando com Perl.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 466, in PDFDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: 'wine'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 318, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[11.82] splash screen hidden
[11.82] Started up in 11.82 seconds with 1 books
['zenity', '--modal', '--file-selection', '--title=Selecione livros', '--separator=\n', '--attach=50331671', '--filename=/home/erikson/Downloads/.fgdfg.gdfhjdhf*&^839', '--file-filter=Livros | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=livros EPUB | *.epub *.kepub', '--file-filter=Livros para Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Livros PDF | *.pdf *.azw4', '--file-filter=Livros HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Livros LIT | *.lit', '--file-filter=Livros TXT | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=HQs | *.cbz *.cbr *.cbc', '--file-filter=Arquivos | *.zip *.rar', '--file-filter=Arquivos de processador de texto | *.odt *.doc *.docx', '--file-filter=Todos os arquivos | *', '--multiple']
Added Programando com Perl to db in: 0.1
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
DeDRM 7.2.1 still has problems with many pdfs.  You could try calibre 4.23 and DeDRM 6.8.1.

**Comment by wonderwomyn** [comment]
Thank you! I had the same problem with a PDF. I reverted to the earlier versions as you said and got it to work. :-)
