### ISSUE TITLE
DRM Issue

### ISSUE THREAD

**Issue by apw21** [apprenticeharper/DeDRM_tools#1910]
This book was bought and I was able to remove the DRM before. I guess with the new updates it is not working anymore.

calibre Debug log
calibre 5.31.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.31.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.32] splash screen shown
[0.32] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.26] main UI initialized...
[1.26] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Die Schule der magischen Tiere, Band 1 Die Schule der magischen .epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Die Schule der magischen Tiere, Band 1 Die Schule der magischen .epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Trying Encryption key default_key
Could not decrypt 7q4b5638.epub. Wrong key
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[6.70] splash screen hidden
[6.70] Started up in 6.70 seconds with 230 books
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
The key that was previous saved is not working for this copy of the book.  And it doesn't seem like DeDRM was able to get a new key.  Did something change with your ADE installation?
