### ISSUE TITLE
DRM removal failure

### ISSUE THREAD

**Issue by kzboray** [apprenticeharper/DeDRM_tools#1911]
I have used DeDRM successfully in the past and used it on a book just two days ago without issue. Today I bought three new books and they all fail on attempts to convert them from KFX format. Any help would be appreciated. 

Log file below:
`Convert book 1 of 1 (Raiders From the Rings)
DeDRM v7.2.1: Trying to decrypt _o0izhcf.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: _o0izhcf
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5b244b46-378d-4d3b-93d8-87c4cf4ae31c.voucher
Traceback (most recent call last):
File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
KFX DRM voucher successfully decrypted
DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\name\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\name\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3304325877' and UserName 'name'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: _o0izhcf
Got DSN key from database default_key_1
Found 1 keys to try after 3.9 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5b244b46-378d-4d3b-93d8-87c4cf4ae31c.voucher
Traceback (most recent call last):
File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
KFX DRM voucher successfully decrypted
DeDRM v7.2.1: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Integration status: False
Conversion options changed from defaults:
verbose: 2
read_metadata_from_opf: 'C:\\Users\\name\\AppData\\Local\\Temp\\calibre_jvwiogcf\\0kv1__pd.opf'
output_profile: 'kindle_fire'
cover: 'C:\\Users\\name\\AppData\\Local\\Temp\\calibre_jvwiogcf\\5ihkjwow.jpeg'
Resolved conversion options
calibre version: 5.31.0
{'allow_conversion_with_errors': False,
'asciiize': False,
'author_sort': None,
'authors': None,
'base_font_size': 0.0,
'book_producer': None,
'change_justification': 'original',
'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
"'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
"'i')) or @class = 'chapter']",
'chapter_mark': 'pagebreak',
'comments': None,
'cover': 'C:\\Users\\name\\AppData\\Local\\Temp\\calibre_jvwiogcf\\5ihkjwow.jpeg',
'debug_pipeline': None,
'dehyphenate': True,
'delete_blank_paragraphs': True,
'disable_font_rescaling': False,
'dont_compress': False,
'duplicate_links_in_toc': False,
'embed_all_fonts': False,
'embed_font_family': None,
'enable_heuristics': False,
'expand_css': False,
'extra_css': None,
'extract_to': None,
'filter_css': '',
'fix_indents': True,
'font_size_mapping': None,
'format_scene_breaks': True,
'html_unwrap_factor': 0.4,
'input_encoding': None,
'input_profile': <calibre.customize.profiles.InputProfile object at 0x079C5D30>,
'insert_blank_line': False,
'insert_blank_line_size': 0.5,
'insert_metadata': False,
'isbn': None,
'italicize_common_cases': True,
'keep_ligatures': False,
'language': None,
'level1_toc': None,
'level2_toc': None,
'level3_toc': None,
'line_height': 0.0,
'linearize_tables': False,
'margin_bottom': 5.0,
'margin_left': 5.0,
'margin_right': 5.0,
'margin_top': 5.0,
'markup_chapter_headings': True,
'max_toc_links': 50,
'minimum_line_height': 120.0,
'mobi_file_type': 'old',
'mobi_ignore_margins': False,
'mobi_keep_original_images': False,
'mobi_toc_at_start': False,
'no_chapters_in_toc': False,
'no_inline_navbars': True,
'no_inline_toc': False,
'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x079C5FE8>,
'page_breaks_before': '/',
'personal_doc': '[PDOC]',
'prefer_author_sort': False,
'prefer_metadata_cover': False,
'pretty_print': False,
'pubdate': None,
'publisher': None,
'rating': None,
'read_metadata_from_opf': 'C:\\Users\\name\\AppData\\Local\\Temp\\calibre_jvwiogcf\\0kv1__pd.opf',
'remove_fake_margins': True,
'remove_first_image': False,
'remove_paragraph_spacing': False,
'remove_paragraph_spacing_indent_size': 1.5,
'renumber_headings': True,
'replace_scene_breaks': '',
'search_replace': '[]',
'series': None,
'series_index': None,
'share_not_sync': False,
'smarten_punctuation': False,
'sr1_replace': None,
'sr1_search': None,
'sr2_replace': None,
'sr2_search': None,
'sr3_replace': None,
'sr3_search': None,
'start_reading_at': None,
'subset_embedded_fonts': False,
'tags': None,
'timestamp': None,
'title': None,
'title_sort': None,
'toc_filter': None,
'toc_threshold': 6,
'toc_title': None,
'transform_css_rules': '[]',
'unsmarten_punctuation': False,
'unwrap_lines': True,
'use_auto_toc': False,
'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
File "calibre_plugins.dedrm.__init__", line 633, in run
File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt _o0izhcf.kfx-zip
Decrypting KFX-ZIP ebook: _o0izhcf
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5b244b46-378d-4d3b-93d8-87c4cf4ae31c.voucher
Traceback (most recent call last):
File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
KFX DRM voucher successfully decrypted
DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\name\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\name\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3304325877' and UserName 'name'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: _o0izhcf
Got DSN key from database default_key_1
Found 1 keys to try after 3.9 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5b244b46-378d-4d3b-93d8-87c4cf4ae31c.voucher
Traceback (most recent call last):
File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
File "C:\Users\name\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
KFX DRM voucher successfully decrypted
DeDRM v7.2.1: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
File "calibre_plugins.dedrm.__init__", line 633, in run
File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 3.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: KFX Input running
on C:\Users\name\AppData\Local\Temp\calibre_jvwiogcf\_o0izhcf.kfx-zip
Software versions: KFX Input 1.44.0, calibre 5.31, Windows-10-10.0.19041
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\name\AppData\Local\Temp\calibre_jvwiogcf\_o0izhcf.kfx-zip
Processing container: B00GTUYOW0_EBOK.azw
Traceback (most recent call last):
File "calibre_plugins.kfx_input.__init__", line 105, in convert
File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00GTUYOW0_EBOK.azw has DRM and cannot be converted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "runpy.py", line 194, in _run_module_as_main
File "runpy.py", line 87, in _run_code
File "site.py", line 82, in <module>
File "site.py", line 77, in main
File "site.py", line 49, in run_entry_point
File "calibre\utils\ipc\worker.py", line 216, in main
File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
File "calibre\ebooks\conversion\plumber.py", line 1105, in run
File "calibre\customize\conversion.py", line 244, in __call__
File "calibre_plugins.kfx_input.__init__", line 125, in convert
calibre.ebooks.DRMError: This book has DRM!
`

**Comment by ElleKayEm** [comment]
As it says in the log:

> DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
