### ISSUE TITLE
[ACSM Conversion Failed] DEDRM Plugin Error with Epub retrieved from ACSM.

### ISSUE THREAD

**Issue by vamsiampolu** [apprenticeharper/DeDRM_tools#1917]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log 
<details>

<summary>/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs</summary>

```log
Job: 0 Convert book 1 of 1 (City of Miracles) finished
Convert book 1 of 1 (City of Miracles)
	DeDRM v7.2.1: Trying to decrypt 9z4z2l_5.epub
	DeDRM v7.2.1: Verifying zip archive integrity
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: 'generic_eink'
	  read_metadata_from_opf: '/var/folders/wp/_480dtys47z07lr44bx8wc540000gn/C/calibre_5.31.1_tmp_qh45j4pk/xy53gtn6.opf'
	Resolved conversion options
	calibre version: 5.31.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10c0bf1c0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10c0bf4c0>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Helvetica',
	 'pdf_serif_family': 'Times',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/wp/_480dtys47z07lr44bx8wc540000gn/C/calibre_5.31.1_tmp_qh45j4pk/xy53gtn6.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 644, in run
	    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 221, in ePubDecrypt
	    import calibre_plugins.dedrm.ignobleepub as ignobleepub
	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
	  File "calibre/customize/zipplugin.py", line 192, in exec_module
	  File "calibre_plugins.dedrm.ignobleepub", line 188, in <module>
	    AES = _load_crypto()
	  File "calibre_plugins.dedrm.ignobleepub", line 182, in _load_crypto
	    AES = loader()
	  File "calibre_plugins.dedrm.ignobleepub", line 118, in _load_crypto_libcrypto
	    libcrypto = CDLL(libcrypto)
	  File "ctypes/__init__.py", line 373, in __init__
	OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
		/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	DeDRM v7.2.1: Trying to decrypt 9z4z2l_5.epub
	DeDRM v7.2.1: Verifying zip archive integrity
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 644, in run
	    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 221, in ePubDecrypt
	    import calibre_plugins.dedrm.ignobleepub as ignobleepub
	  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
	  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
	  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
	  File "calibre/customize/zipplugin.py", line 192, in exec_module
	  File "calibre_plugins.dedrm.ignobleepub", line 188, in <module>
	    AES = _load_crypto()
	  File "calibre_plugins.dedrm.ignobleepub", line 182, in _load_crypto
	    AES = loader()
	  File "calibre_plugins.dedrm.ignobleepub", line 118, in _load_crypto_libcrypto
	    libcrypto = CDLL(libcrypto)
	  File "ctypes/__init__.py", line 373, in __init__
	OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
		/usr/local/lib/libcrypto.dylib: code signature in (/usr/local/lib/libcrypto.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	InputFormatPlugin: EPUB Input running
	on /var/folders/wp/_480dtys47z07lr44bx8wc540000gn/C/calibre_5.31.1_tmp_qh45j4pk/9z4z2l_5.epub
	Traceback (most recent call last):
	  File "runpy.py", line 194, in _run_module_as_main
	  File "runpy.py", line 87, in _run_code
	  File "site.py", line 39, in <module>
	  File "site.py", line 35, in main
	  File "calibre/utils/ipc/worker.py", line 216, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
	  File "calibre/customize/conversion.py", line 244, in __call__
	  File "calibre/ebooks/conversion/plugins/epub_input.py", line 287, in convert
	calibre.ebooks.DRMError: 9z4z2l_5.epub
```
</details>

**Comment by Leseratte10** [comment]
This seems to be a duplicate of #1597. I don't know that much about MacOS, but it looks like a locally-installed libcrypto.dylib conflicts with the one included with the one in this plugin. 

Try this and see if it helps: https://github.com/apprenticeharper/DeDRM_tools/issues/1597#issuecomment-819451707
