### ISSUE TITLE
Can't Remove NOOK DRM Anymore

### ISSUE THREAD

**Issue by dave1050** [apprenticeharper/DeDRM_tools#1923]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title
Can't Remove Nook DRM Anymore

## My Environment
5.26 Calibre: `Version`
5.0.2.38 NOOK Android: `Version`
7.2.1 DeDRM: `Version`

## Log
<details><summary>I can no longer remove DRM from NOOK ebook files downloaded through an android emulator.  I checked and the device key is still the same as when it was working prior though that is what the error seems to be related to.  I was last able to remove the DRM on an October 11th purchase.  I would like to note that I have also tried on version 5.32 of Calibre.</summary>

```log
calibre Debug log
calibre 5.26 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0) && Obok DeDRM (7, 2, 1)
calibre 5.26 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.62] db initialized
[0.62] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.23] main UI initialized...
[1.23] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 2940153637174_drp.v1.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “2940153637174_drp.v1.epub” is a secure Barnes & Noble ePub
DeDRM v7.2.1: Trying Encryption key mykey
Could not decrypt y97cdte8.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 266, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 197, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 168, in __init__
  File "Crypto\Cipher\AES.py", line 232, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v7.2.1: Failed to decrypt with key mykey after 0.4 seconds
DeDRM v7.2.1: Looking for new NOOK Study Keys after 0.4 seconds
No nook Study log files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 176, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 313, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[43.69] splash screen hidden
[43.70] Started up in 43.70 seconds with 164 books
Added Yokai Girls Vol. 2 to db in: 0.2
Added 1 booWorker Launch took: 0.02 seconds

```
</details>

**Comment by ElleKayEm** [comment]
Key and books were retrieved from same app at the same time?

**Comment by dave1050** [comment]
Sorry for the late response, but yes and the ebook (among others) that prompted the issue were purchased today.

**Comment by ElleKayEm** [comment]
I don't know.  Recently someone else had trouble.  They thought their key hadn't changed.  But when they tried extracting it again, it was different and worked with their latest book.

**Comment by dave1050** [comment]
Hm, well I'll see about eventually trying either to reinstall the NOOK app which I assume might(?) generate a new key, trying a different emulator or computer.  Thank you though.

**Comment by dave1050** [comment]
Just reinstalling the NOOK app generated a new key which fixed the issue.  I feel silly for not trying this before, but thank you.

**Comment by ElleKayEm** [comment]
Thanks for reporting back.  Good to know that worked.
