### ISSUE TITLE
[QUESTION]unrecognized DRM od imported epub in Calibre

### ISSUE THREAD

**Issue by algreen702021** [apprenticeharper/DeDRM_tools#1925]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title
cannot decrypt epub

## Log
<details><summary>Log debug of Calibre 5.32 </summary>

```log
```
calibre Log di debug
calibre 5.32  embedded-python: True is64bit: True
Linux-5.11.0-27-lowlatency-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.11.0-27-lowlatency', '#29~20.04.1-Ubuntu SMP PREEMPT Wed Aug 11 17:06:56 UTC 2021')
Python 3.8.5
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.32  embedded-python: True is64bit: True
Linux-5.11.0-27-lowlatency-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.11.0-27-lowlatency', '#29~20.04.1-Ubuntu SMP PREEMPT Wed Aug 11 17:06:56 UTC 2021')
Python 3.8.5
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.16] main UI initialized...
[1.16] Hiding splash screen
Starting QuickView
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 998, resource id: 12450911, major code: 40 (TranslateCoords), minor code: 0
DeDRM v7.2.1: Trying to decrypt file.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: **“file.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub**
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Couldn't decrypt after {2:.1f} seconds. DRM free perhaps?".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: **DeDRM v7.2.1: Couldn't decrypt after 0.2 seconds. DRM free perhaps?**
[14.27] splash screen hidden
[14.27] Started up in 14.27 seconds with 0 books
['zenity', '--modal', '--file-selection', '--title=Seleziona libro', '--separator=\n', '--attach=90177559', '--filename=/media/tess/lacie/.fgdfg.gdfhjdhf*&^839', '--file-filter=Libri | *.lrf *.rar *.zip *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=Libri EPUB | *.epub *.kepub', '--file-filter=Libri Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Libri PDF | *.pdf *.azw4', '--file-filter=Libri HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Libri LIT | *.lit', '--file-filter=Libri TXT | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Fumetti | *.cbz *.cbr *.cbc', '--file-filter=Archivi | *.zip *.rar', '--file-filter=File elaboratore di testi | *.odt *.doc *.docx', '--file-filter=Tutti i file | *', '--multiple']
Added La morte di Ivan Il’ič Tre morti to db in: 0.1
Added 1 books in 1.0 seconds
```
```
</details>

**Comment by ElleKayEm** [comment]
Where is the epub from?

**Comment by algreen702021** [comment]
Hi, 
from italian library; it's **apple fairplay** encoded.

**Comment by ElleKayEm** [comment]
These tools do not work on that DRM and are intended for purchased books.
