### ISSUE TITLE
Importing ADE PDF into Calibre and DeDRM isn't working..

### ISSUE THREAD

**Issue by craigelloyd** [apprenticeharper/DeDRM_tools#1927]
Followed all the instructions, but when importing the PDF, I guess it deDRMing didn't work because Calibre can't open it. Not sure what to do..

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.32  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.32  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
[0.96] main UI initialized...
[0.96] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt A Guide to the Project Management Body of Knowledge (PMBOK® Guid.pdf
DeDRM v7.2.1: A Guide to the Project Management Body of Knowledge (PMBOK® Guid.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key adobekey_1
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key adobekey_1 after 0.1 seconds
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 318, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[17.01] splash screen hidden
[17.02] Started up in 17.02 seconds with 0 books
Added A Guide to the Project Management Body of Knowledge (PMBOK® Guid to db in: 0.0
Added 1 books in 0.7 seconds
```
</details>

**Comment by Leseratte10** [comment]
There's still some bugs with PDF DRM removal in the newest version of this plugin. 

You can either try switching back to Calibre 4.x and version 6.8.1 of this plugin, or you manually add the bugfixes mentioned in #1689 to the plugin.
