### ISSUE TITLE
DeDRM not working - google books for win10 calibre4.23

### ISSUE THREAD

**Issue by aujack2010** [apprenticeharper/DeDRM_tools#1938]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
Adobe Digital Editions v 2.0.1.78765
Calibre 4.23.0
DeDRM_tools_6.8.0

windows10

ebooks download from google books

Error message opening in Calibre e-book viewer:



('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.41] splash screen shown
[0.41] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.44] main UI initialized...
[1.44] Hiding splash screen
[7.80] splash screen hidden
[7.80] Started up in 7.80 seconds with 0 books
DeDRM v6.8.0: Trying to decrypt 猛虎出柙雙劍合璧版--最新 OCA  OCP Java SE 7 Programmer 專業認證(電子書)-1.pdf
DeDRM v6.8.0: 猛虎出柙雙劍合璧版--最新 OCA  OCP Java SE 7 Programmer 專業認證(電子書)-1.pdf is a PDF ebook
DeDRM v6.8.0: Trying Encryption key default_key
DeDRM v6.8.0: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 428, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2183, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1989, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1474, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1606, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.8.0: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 453, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added 猛虎出柙雙劍合璧版--最新 OCA OCP Java SE 7 Programmer 專業認證(電子書)-1 to db in: 0.1
Added 1 books in 1.2 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05B21870>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05B218D0>> ignored

```
</details>

**Comment by ElleKayEm** [comment]
Try 64-bit calibre.

**Comment by aujack2010** [comment]
> Try 64-bit calibre.

Hi ElleKayEm:
I've try 64bits , but still not working. 
And the following is the log output.


calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[1.16] main UI initialized...
[1.16] Hiding splash screen
[3.47] splash screen hidden
[3.47] Started up in 3.47 seconds with 0 books
DeDRM v6.8.0: Trying to decrypt 猛虎出柙雙劍合璧版--最新 OCA  OCP Java SE 7 Programmer 專業認證(電子書)-1.pdf
DeDRM v6.8.0: 猛虎出柙雙劍合璧版--最新 OCA  OCP Java SE 7 Programmer 專業認證(電子書)-1.pdf is a PDF ebook
DeDRM v6.8.0: Trying Encryption key default_key
DeDRM v6.8.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 428, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2183, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1989, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1474, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1606, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.8.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 453, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added 猛虎出柙雙劍合璧版--最新 OCA OCP Java SE 7 Programmer 專業認證(電子書)-1 to db in: 0.1
Added 1 books in 0.8 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000156AD457288>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000156AD235EC8>> ignored

**Comment by ElleKayEm** [comment]
You have ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by aujack2010** [comment]
> You have ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

Yes, ADE authorized and connect to Adobe ID on the same machine.

**Comment by ElleKayEm** [comment]
I don't know.  Hopefully someone else can help.

**Comment by Leseratte10** [comment]
There's been a ton of reports of this error message ("Failed to decrypt user key key") in other issue reports in the past (1395, 1144, 1109, 902 just to name a few). The go-to solution for issues like these is start over completely from the beginning by removing all traces from the Adobe installation, including the activation, and start over with a fresh install.

Is this the first time you're removing DRM on this computer or did this already work in the past?

While looking into how exactly the ADE registration works for my new Calibre plugin ([see here](https://www.mobileread.com/forums/showthread.php?t=341975) if you are interested) I might have figured out what causes this issue, as I finally ran into that on one of my machines, too, and was able to look into that. 

If you have time, would you be able to verify one quick thing before you try deleting ADE?
Assuming you're on Windows, press Windows+R, enter `control userpasswords2`, then press enter, and take note what it says for your account in the "User Name" column. That might be different from what your username is displayed as in other places. 
Once you did that, open up the registry editor (Windows+R again, then enter `regedit`) and navigate to `Computer\HKEY_CURRENT_USER\SOFTWARE\Adobe\Adept\Device`, then check what it says for the entry "username". 

Usually, this should be the same name that was displayed in the `control userpasswords2` window in the earlier step. If it does show something different, that might be the issue. 

Let me know if these two usernames are identical or if they are different - if they are different then I believe I know how to fix this  and I'll try to make a Pull Request with a bugfix.

**Comment by aujack2010** [comment]
> There's been a ton of reports of this error message ("Failed to decrypt user key key") in other issue reports in the past (1395, 1144, 1109, 902 just to name a few). The go-to suggestion for this issue seems to be "start over completely from the beginning, reinstall and re-auth ADE", which seems to work ... sometimes, but I think so far nobody has tracked down what causes this error.
> 
> Is this the first time you're removing DRM on this computer or did this already work in the past?
> 
> While looking into how exactly the ADE registration works for my new Calibre plugin ([see here](https://www.mobileread.com/forums/showthread.php?t=341975) if you are interested) I might have figured out a part of the reason that causes this issue, as I finally ran into that on one of my machines, too, and was able to look into that.
> 
> Right now it's just a theory so I'm not 100% sure if this is correct, but if you have time, would you be able to verify one quick thing before you try deleting ADE? Assuming you're on Windows, press Windows+R, enter `control userpasswords2`, then press enter, and take note what it says for your account in the "User Name" column. That might be different from what your username is displayed as in other places. Once you did that, open up the registry editor (Windows+R again, then enter `regedit`) and navigate to `Computer\HKEY_CURRENT_USER\SOFTWARE\Adobe\Adept\Device`, then check what it says for the entry "username".
> 
> Usually, this should be the same name that was displayed in the `control userpasswords2` window in the earlier step. If it does show something different, that might be the issue.
> 
> Let me know if these two usernames are identical or if they are different - if they are different then I believe I know why this happens and how to fix this and I'll try to make a Pull Request with a bugfix so people won't always have to reinstall ADE in the future...

Hi Leaseratte10 :
Thx for ur help, I followed the step u mentioned  about.
The username was different in 'user password2'  and reg key.
May I have ur help to solve this problem?
Best regards.

**Comment by Leseratte10** [comment]
I've sent you an email to the address on your github profile, with a test version of the plugin that might fix this. Let me know if this worked - if it does, I'll open a pull request.

**Comment by Leseratte10** [comment]
@aujack2010 Did you receive my email and did you have time to test if this fixes your issue yet?

**Comment by aujack2010** [comment]
> @aujack2010 Did you receive my email and did you have time to test if this fixes your issue yet?

Hi Leseratte10  :
Sorry to reply late.
Very thanks for your help.

01. I reinstall the Caliber 5.32.0 x64
02. Then install the DeDRM plugin 7.2.1
03.I followed the instruction with [https://www.mobileread.com/forums/showthread.php?t=341975](url)
04. I export the ""Export account encryption key""" with **DeASCM** plugin.
05.I import the ""Export account encryption key"" file with the **DeDRM7.2.1** plugin in "**Adobe Digital Edition Books**" Button.
06.Restart the Caliber.
07.Drag and drop the file from ADE saving folder.
08....................It worked.

Thanks for your help.
Best Regards.

**Comment by Leseratte10** [comment]
Okay, by following these steps you completely circumvented the actual key retrieval issue as you've used the DeACSM plugin to retrieve the key instead. 
I'm going to put my solution into a pull request anyways in case other people run into a similar issue.
