### ISSUE TITLE
[ISSUE] AZW decryption error

### ISSUE THREAD

**Issue by bark2** [apprenticeharper/DeDRM_tools#1940]
### DeDRM: `7.2.1-2`

Bought a book from amazon, register then loged into 'kindle for pc' and used the book downloaded(from kindle books dir) and dragged into calibre.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.32  embedded-python: False is64bit: True
Linux-5.10.68-1-lts-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.10.68-1-lts', '#1 SMP Wed, 22 Sep 2021 11:00:42 +0000')
Python 3.9.7
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
calibre 5.32  embedded-python: False is64bit: True
Linux-5.10.68-1-lts-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.10.68-1-lts', '#1 SMP Wed, 22 Sep 2021 11:00:42 +0000')
Python 3.9.7
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.04726735598227 x 96.0
physicalDpi: 123.61977186311786 x 123.56756756756756
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.04] splash screen shown
[0.04] Initializing db...
[0.05] db initialized
[0.05] Constructing main UI...
[0.47] main UI initialized...
[0.47] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing /run/media/bar/Windows/Users/bar/Documents/My Kindle Content/B004KA9UXO_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B004KA9UXO_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Dune (The Dune Sequence)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
[11.26] splash screen hidden
[11.26] Started up in 11.26 seconds with 3 books
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v7.2.1: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v7.2.1: wine python3.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v7.2.1: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v7.2.1: wine C:\Python27\python.exe does not exist
DeDRM v7.2.1: Unable to find python3 executable in WINEPREFIX=""
DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Dune (The Dune Sequence) to db in: 0.0
Added 1 books in 1.8 seconds
Worker Launch took: 0.01 seconds

** (xed:22689): WARNING **: 23:57:53.837: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.837: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.841: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.842: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.847: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.847: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.847: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (xed:22689): WARNING **: 23:57:53.847: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

```
</details>

**Comment by ElleKayEm** [comment]
Not sure what is needed to retrieve the key automatically with Linux.  But a workaround would be running the kindlekey script manually and importing the key manually.  Or temporarily installing Windows calibre with DeDRM, decrypting a book, then importing the key into the Linux setup.

**Comment by bark2** [comment]
Thanks, it worked in windows 10. Can you please point me to where should I put the key? Is there are reference on how to use the script?

**Comment by ElleKayEm** [comment]
Preferences > plugins > select the DeDRM plugin (under File Type) > Customize plugin > Kindle for Mac/PC ebooks.  Save the keyfile from Windows calibre and Import existing keyfiles in Linux calibre.
