### ISSUE TITLE
DRM stopped working today.  Amazon now sending AZW instead of AZW3

### ISSUE THREAD

**Issue by marysonthego** [apprenticeharper/DeDRM_tools#1941]
Nothing has changed on my end.  I converted some books yesterday without error.
Thanks in advance for any help!
- Mary
Kindle for PC 1.24.3 (51068)
DeDRM v7.2.1
calibre 5.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22499 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22499')
Python 3.8.
[calibreDebug.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7585325/calibreDebug.txt)

**Comment by marysonthego** [comment]
Full text log:

Microsoft Windows [Version 10.0.22499.1010]
(c) Microsoft Corporation. All rights reserved.

C:\Users\marys>calibre-debug -g
calibre 5.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22499 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22499')
Python 3.8.5
Windows: ('10', '10.0.22499', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && Calibre Power Search Plugin (2, 1, 1) && Find Duplicates (1, 8, 10) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: False
[0.00] Starting up...
[0.02] Showing splash screen...
[1.81] splash screen shown
[1.81] Initializing db...
[2.19] db initialized
[2.19] Constructing main UI...
[4.27] main UI initialized...
[4.27] Hiding splash screen
Starting QuickView
[4.99] splash screen hidden
[4.99] Started up in 4.99 seconds with 4705 books
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08TT5ZK1K_EBOK/B08TT5ZK1K_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08TT5ZK1K_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Right Place, Right Time
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Right Place, Right Time
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Right Place, Right Time to db in: 0.2
Added 1 books in 1.0 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md


Microsoft Windows [Version 10.0.22499.1010]
(c) Microsoft Corporation. All rights reserved.

C:\Users\marys>calibre-debug -g
calibre 5.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22499 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22499')
Python 3.8.5
Windows: ('10', '10.0.22499', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && Calibre Power Search Plugin (2, 1, 1) && Find Duplicates (1, 8, 10) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: False
[0.00] Starting up...
[0.00] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.52] db initialized
[1.52] Constructing main UI...
[3.00] main UI initialized...
[3.02] Hiding splash screen
Starting QuickView
[3.56] splash screen hidden
[3.56] Started up in 3.56 seconds with 4706 books
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08JKNHQR2_EBOK/B08JKNHQR2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08JKNHQR2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Unwell Women
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Unwell Women
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Unwell Women to db in: 0.2
Added 1 books in 102.6 seconds

C:\Users\marys>calibre-debug -g
calibre 5.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22499 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22499')
Python 3.8.5
Windows: ('10', '10.0.22499', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && Calibre Power Search Plugin (2, 1, 1) && Find Duplicates (1, 8, 10) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: False
[0.00] Starting up...
[0.00] Showing splash screen...
[1.08] splash screen shown
[1.08] Initializing db...
[1.36] db initialized
[1.36] Constructing main UI...
[2.75] main UI initialized...
[2.75] Hiding splash screen
Starting QuickView
[3.22] splash screen hidden
[3.22] Started up in 3.22 seconds with 4700 books
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08JKNHQR2_EBOK/B08JKNHQR2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08JKNHQR2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Unwell Women
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Unwell Women
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Unwell Women to db in: 0.2
Added 1 books in 10.1 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08LDXW9Y2_EBOK/B08LDXW9Y2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08LDXW9Y2_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Everyone in This Room Will Someday Be Dead: A Novel
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Everyone in This Room Will Someday Be Dead: A Novel
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Everyone in This Room Will Someday Be Dead: A Novel to db in: 0.2
Added 1 books in 0.9 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08L6YMQGC_EBOK/B08L6YMQGC_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08L6YMQGC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mrs. March: A Novel
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mrs. March: A Novel
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Mrs. March: A Novel to db in: 0.2
Added 1 books in 0.9 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08R2KL3VY_EBOK/B08R2KL3VY_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08R2KL3VY_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Dawn of Everything
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Dawn of Everything
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Dawn of Everything to db in: 1.1
Added 1 books in 1.9 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/marys/Docs/My Kindle Content/B08TT5ZK1K_EBOK/B08TT5ZK1K_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B08TT5ZK1K_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Right Place, Right Time
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\marys\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\marys\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3226106964' and UserName 'marysonthego'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Right Place, Right Time
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Right Place, Right Time to db in: 0.2
Added 1 books in 0.9 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
These were downloaded with the currently installed Kindle for PC on the same machine and user as calibre with DeDRM?

**Comment by marysonthego** [comment]
Yes.

**Comment by ElleKayEm** [comment]
Sorry, I don't know.  I'm not seeing what it might be.  Things are still working for me.

**Comment by marysonthego** [comment]
Understood. After doing more research I downgraded KPC from 1.24 to 1.17. I was allowed to login (yay!) and download books. Amazingly, DRM is now working.  I noticed that DRM decrypted using a different idString and username. Perhaps this was my problem?  I recently switched from logging in to the PC with a Microsoft account to a local account. Possibly wrong appdata/local was used.  Anyway, fixed now and thank you very much for your time. :)

**Comment by ElleKayEm** [comment]
Glad you got things working, and thanks for pointing to a possibility of what might have been going on.

**Comment by S99amuele** [comment]
![msg126685486-94763](https://user-images.githubusercontent.com/81489249/143897421-e28f0bb7-0e97-490f-aa75-ce24e8486985.jpg)

KPC allows login but doesn't allow downloading the books anymore

**Comment by scare376** [comment]
I had this same issue and just figured out the cause in my case. The isKRFDRendererSupported flag is getting set back to true every time I launch the kindle app. Luckily the app only checks the flag when an item is downloaded so it really just causes a minor inconvenience than anything. I think I was on 1.30 before but in troubleshooting I ended up downloading version 1.33. Hopefully this helps anyone else that might have this issue.

**Comment by ElleKayEm** [comment]
If you want to avoid KFX on anything later then Kindle for PC 1.24, start it with the KFX_begone batch file.  Found here:  https://www.mobileread.com/forums/showthread.php?p=4021279#post4021279
