### ISSUE TITLE
error remove drm

### ISSUE THREAD

**Issue by vidiep** [apprenticeharper/DeDRM_tools#1952]
calibre, version 5.32.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Bootstrap Arena INTL-1)

Convert book 1 of 1 (Bootstrap Arena INTL-1)
DeDRM v7.2.1: Trying to decrypt 7ehf1d9z.pdf
DeDRM v7.2.1: 7ehf1d9z.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
    return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)
  File "Crypto/Cipher/PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/gw/1twvncrs2_q2ny39nwb78sv00000gn/C/calibre_5.32.0_tmp_fb2723zn/6v8o1v2x.opf'
  verbose: 2
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 5.32.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10fb5b460>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10fb5b760>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Helvetica',
 'pdf_serif_family': 'Times',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/gw/1twvncrs2_q2ny39nwb78sv00000gn/C/calibre_5.32.0_tmp_fb2723zn/6v8o1v2x.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt 7ehf1d9z.pdf
DeDRM v7.2.1: 7ehf1d9z.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
    return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)
  File "Crypto/Cipher/PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.0 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on /var/folders/gw/1twvncrs2_q2ny39nwb78sv00000gn/C/calibre_5.32.0_tmp_fb2723zn/7ehf1d9z.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1111, in run
  File "calibre/customize/conversion.py", line 244, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by ElleKayEm** [comment]
Try noDRM's updated DeDRM:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

**Comment by vidiep** [comment]
Hi ,
Version not working. you can help me?
calibre, version 5.33.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Bootstrap Arena INTL)

Convert book 1 of 1 (Bootstrap Arena INTL)
DeDRM v10.0.2: Trying to decrypt 8aii13cg.pdf
DeDRM v10.0.2: 8aii13cg.pdf is a PDF ebook for UUID
b1b51381-159d-425e-bab0-0912f2d5638a
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after
0.1 seconds
Found 1 keys
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
ModuleNotFoundError: No module named 'calibre_plugins.deacsm'
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet.
Try getting your distributor to give you a new ACSM file, then open that in
an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give
you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT
encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.3 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 0.3 seconds. Read the
FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  pdf_serif_family: 'MS Shell Dlg 2'
  verbose: 2
  pdf_sans_family: 'MS Shell Dlg 2'
  output_profile: 'generic_eink'
  read_metadata_from_opf:
'C:\\Users\\VIEE7F~1.DIE\\AppData\\Local\\Temp\\calibre__m169d8j\\uriqvkzz.opf'
Resolved conversion options
calibre version: 5.33.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

"'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))',
"
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at
0x07FB7D90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at
0x07FB7F10>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf':
'C:\\Users\\VIEE7F~1.DIE\\AppData\\Local\\Temp\\calibre__m169d8j\\uriqvkzz.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 895, in run
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to
decrypt after 0.3 seconds. Read the FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v10.0.2: Trying to decrypt 8aii13cg.pdf
DeDRM v10.0.2: 8aii13cg.pdf is a PDF ebook for UUID
b1b51381-159d-425e-bab0-0912f2d5638a
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after
0.0 seconds
Found 1 keys
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
ModuleNotFoundError: No module named 'calibre_plugins.deacsm'
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet.
Try getting your distributor to give you a new ACSM file, then open that in
an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give
you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT
encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.1 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 0.1 seconds. Read the
FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 895, in run
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to
decrypt after 0.1 seconds. Read the FAQs at Harper's repository:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on C:\Users\VIEE7F~1.DIE\AppData\Local\Temp\calibre__m169d8j\8aii13cg.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in
gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1111, in run
  File "calibre\customize\conversion.py", line 244, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

Thanks
Vi Diep

**Comment by ElleKayEm** [comment]
From the log:

> This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet.
Try getting your distributor to give you a new ACSM file, then open that in
an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give
you a copy with the old DRM.

**Comment by vidiep** [comment]
thank you ,so much
