### ISSUE TITLE
Obok Conversion Results In Gibberish

### ISSUE THREAD

**Issue by RoverMaelstrom** [apprenticeharper/DeDRM_tools#1953]
Hi! I've just downloaded DeDRM + Obok and I'm honestly not sure what's going wrong with this conversion. The debug log is below and I've attached a screenshot of what the resulting ebook looks like. I'd really appreciate some help in figuring out what I'm doing wrong! Thanks!

EpubMerge: DEBUG: 2021-12-02 10:16:56,301: calibre_plugins.epubmerge.epubmerge_plugin(158): macmenuhack file_path:C:\Users\rover\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2021-12-02 10:16:56,310: calibre_plugins.fanficfare_plugin.fff_plugin(221): Plugin FanFicFare macmenuhack file_path:C:\Users\rover\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 5.32  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 11, 1) && EpubMerge (2, 11, 0) && FanFicFare (4, 8, 0) && Obok DeDRM (7, 2, 1)
calibre 5.32  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 11, 1) && EpubMerge (2, 11, 0) && FanFicFare (4, 8, 0) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 80.34266886326195 x 79.51304347826087
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.92] main UI initialized...
[1.92] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1456, in set_metadata
  File "calibre\db\cache.py", line 1379, in set_cover
  File "calibre\db\backend.py", line 1531, in set_cover
  File "calibre\utils\img.py", line 288, in save_cover_data_to
  File "calibre\utils\img.py", line 196, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[5.17] splash screen hidden
[5.19] Started up in 5.19 seconds with 2426 books
Running Obok DeDRM v7.2.1
DEBUG:    5.0 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
C:\Users\rover\AppData\Local\Temp\tmpalb6tm9x
DEBUG:    5.0 got kobodir C:\Users\rover\AppData\Local\Kobo\Kobo Desktop Edition
Found 4 possible keys to try.
DEBUG:   12.0 BookListTableWidget:get_books - book_num: 3
DEBUG:   12.0 BookListTableWidget:get_books - book: The Ruin of Gabriel Ashleigh
DEBUG:   12.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v7.2.1 - Decrypting The Ruin of Gabriel Ashleigh
Trying key:  b'f71a93d197006bf19053e7506c81922a'
Success!
DEBUG:   12.1 DecryptAddProgressDialog::do_book_action - decrypted book: 'The Ruin of Gabriel Ashleigh'
Obok DeDRM v7.2.1 - Added The Ruin of Gabriel Ashleigh
Obok DeDRM v7.2.1 - wrapping up results.
Worker Launch took: 0.00 seconds
<img width="962" alt="Screenshot of Gibberish Text in Calibre" src="https://user-images.githubusercontent.com/56319398/144481704-08588d3b-b400-45cc-a96f-b9ceab7059a2.png">

**Comment by ElleKayEm** [comment]
Clearly not actually decrypted.  Give noDRM's updated Obok a try:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

**Comment by build6** [comment]
Are you able to install an older version of Calibre and Obok?  I encountered an issue like this where (based on some google search result I can't find again now) I tried an older Calibre (4.23) and Obok (6.7) and it worked, while the latest Calibre (5.32) and Obok (7.2.1) it doesn't.

**Comment by ElleKayEm** [comment]
See reply here:  https://github.com/apprenticeharper/DeDRM_tools/issues/1960#issuecomment-989929498
