### ISSUE TITLE
failed DRM

### ISSUE THREAD

**Issue by yertle** [apprenticeharper/DeDRM_tools#1954]
Hi, I tried to de-drm with this tool and with a fork and both failed. Main tool log pasted below, and other attached. Thank you!

calibre Debug log
calibre 5.33  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
calibre 5.33  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 45, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 45, 0) && KFX metadata reader (from KFX Input) (1, 45, 0) && KFX Input (1, 45, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.96531791907513 x 94.07407407407408
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[1.00] main UI initialized...
[1.00] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.45.0: Importing C:/Users/Brian/Desktop/The Man Who Died Twice_ A Thursday Murder Club Mystery_B08YRM9NBM.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\Brian\AppData\Local\Temp\calibre_xmq2x9vr\w2h7bo1y.kfx-zip
DeDRM v7.2.1: Trying to decrypt w2h7bo1y.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: w2h7bo1y
Found 1 keys to try after 0.1 seconds
DeDRM v7.2.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Brian\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.45.0: Packaging C:\Users\Brian\AppData\Local\Temp\calibre_xmq2x9vr\w2h7bo1y.kfx-zip
Processing container: The Man Who Died Twice_ A Thursday Murder Club Mystery_B08YRM9NBM.kfx
KFX metadata reader (from KFX Input) activated for C:\Users\Brian\AppData\Local\Temp\calibre_xmq2x9vr\n96j3qcs_add_books\0\The Man Who Died Twice_ A Thursday Murder Club Mystery_B08YRM9NBM.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container The Man Who Died Twice_ A Thursday Murder Club Mystery_B08YRM9NBM.kfx has DRM and cannot be converted
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in get_metadata
Exception: Failed to locate a KFX container with metadata
[30.47] splash screen hidden
[30.47] Started up in 30.47 seconds with 529 books
Added The Man Who Died Twice A Thursday Murder Club Mystery B08YRM9NBM to db in: 0.3
Added 1 books in 0.8 seconds

[tmpphip6v2s.txt](https://github.com/apprenticeharper/DeDRM_tools/files/7652940/tmpphip6v2s.txt)

**Comment by ElleKayEm** [comment]
Probably best to avoid KFX format if possible.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by yertle** [comment]
> Probably best to avoid KFX format if possible. See this post for details: https://www.mobileread.com/forums/showthread.php?t=283371

Ahh, ok. I was able to get an azw and that worked great. Thank you!
