### ISSUE TITLE
Can't remove DRM from Kindle book

### ISSUE THREAD

**Issue by MelissaBo13** [apprenticeharper/DeDRM_tools#1958]
Hi, thank you so much for the deDRM plug in! I downloaded some Kindle books from Amazon, and I need to convert them in Calibre to ePUB so I can read them on my Kobo. I just installed Calibre yesterday so I should have the latest version. I did try to customize the plug in by adding a key, but I don't know where to find the key on my Kindle for PC app. Thank you!

calibre Debug log
calibre 5.33.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 14, 1) && KoboTouchExtended (3, 5, 4)
calibre 5.33.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 14, 1) && KoboTouchExtended (3, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294117647 x 95.58188153310104
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.8 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.8 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.8 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.8 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[1.66] main UI initialized...
[1.66] Hiding splash screen
Starting QuickView
Storage number map:
{(7, 0): [(1, 'D')], (7, 1): [(1, 'C')], (7, 2): [(1, 'F')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-STOR_GADGET&REV_0409\N7781A0008062&0: StorageDeviceNumber(type=7, number=2, partition_number=0)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4231 bcd=0x409 devid=usb\vid_2237&pid_4231&rev_0409 devinst=4)
{'drive_letters': ['F'],
 'pnp_id_map': {'F': '\\\\?\\usbstor#disk&ven_linux&prod_file-stor_gadget&rev_0409#n7781a0008062&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'F': (2, 1)}}
DEBUG:    5.6 KoboUtilities:_on_device_connection_changed - self.plugin_device_connection_changed.__class__:  <class 'PyQt5.QtCore.pyqtBoundSignal'>
DEBUG:    5.6 Methods for self.plugin_device_connection_changed:  ['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'connect', 'disconnect', 'emit', 'signal']
DEBUG:    5.6 Have a Kobo device connected connected
DEBUG:    5.6 BEGIN Get Device Path
DEBUG:    5.6 Root path of device: F:\
DEBUG:    5.6 END Get Device Path
DEBUG:    5.6 KoboUtilities:get_device - self.device_path="F:\"
DEBUG:    5.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    5.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 KoboTouch:books - oncard='None'
2021-12-07 21:46:23 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2021-12-07 21:46:23 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000021AFF656940>
DEBUG:    0.0 KoboTouch:books - oncard='None', prefix='F:\'
DEBUG:    0.0 Kobo device: Kobo Sage
DEBUG:    0.0 Version of driver: (3, 5, 4) Has kepubs: True
DEBUG:    0.0 Version of firmware: (4, 30, 18838) Has kepubs: True
DEBUG:    0.0 Firmware supports cover image tree: True
2021-12-07 21:46:23 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2021-12-07 21:46:23 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000021A8475CA90>
DEBUG:    0.0 KoboTouch:books - opts.extra_customization= []
DEBUG:    0.0 KoboTouch:books - driver options= Driver:KoboTouchExtended, Options - format_map: ['kepub', 'epub', 'cbr', 'cbz', 'pdf', 'txt'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: tags, create_collections: True, delete_empty_collections: True, ignore_collections_names: , upload_covers: False, dithered_covers: False, keep_cover_aspect: False, upload_grayscale: False, letterbox_fs_covers: False, letterbox_fs_covers_color: #000000, png_covers: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, update_core_metadata: False, update_purchased_kepubs: False, update_device_metadata: True, update_subtitle: False, subtitle_template: , modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 3.5.4, extra_features: True, upload_encumbered: False, skip_failed: False, hyphenate: False, smarten_punctuation: False, clean_markup: False, full_page_numbers: False, disable_hyphenation: False, file_copy_dir: , hyphenate_chars: 6, hyphenate_chars_before: 3, hyphenate_chars_after: 3, hyphenate_limit_lines: 2
DEBUG:    0.0 KoboTouch:books - prefs['manage_device_metadata']= on_connect
DEBUG:    0.0 KoboTouch:books - set_debugging_title to ''
DEBUG:    0.0 KoboTouch:books - length bl=0
DEBUG:    0.0 KoboTouch:books - length bl after sync=52
DEBUG:    0.0 KoboTouch:books - reading device database
DEBUG:    0.0 Database Version:  166
DEBUG:    0.0 KoboTouch:books - shelf list: ['Sci Fi', 'Romance', 'ReadingList', 'Dystopian', 'Non-Fiction: Life Journeys', 'Chick Lit', 'Heartwarmers', 'Supernatural', 'Chick Lit- Supernatural', 'Non-Fiction: Personal Organization', 'Thriller']
DEBUG:    0.0 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageId, ReadStatus, Description, Publisher , ___ExpirationStatus, FavouritesIndex, Accessibility, Language, IsDownloaded, ISBN, Series, SeriesNumber, ___UserID, ExternalId, Subtitle, SeriesID, SeriesNumberFloat FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,8,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    0.1 KoboTouch:books - automatically managing metadata
DEBUG:    0.1 KoboTouch:books - self.kobo_series_dict= {'A Laurel Heights Novel': '46521c1b-ec49-54d5-98c1-134fdd0ea1e6', 'The Keys to my Diary': '7feae6ee-33bc-5fb5-bfb7-d573b473d156', 'Love Story': '4dbf5717-4177-502a-91e7-838806eea3ab', 'Brent Bolster Space Detective': '74f92b7d-cbbc-545b-badd-df084e2bde12', 'Eridu Series': 'c75370a2-e676-56c5-84dc-f28b4032f699', 'Project Biogenesis': '89c6a9a5-1eee-5402-a8ce-2f0db366ad12', 'The Invasion Chronicles': 'bef28cdf-012c-5168-a874-63597065c3c8', 'The Cull Stories': '979b90ee-4cec-59a1-87fa-27e45a9cbc2d', 'Sins of Our Ancestors': '3f05730c-bfc6-52d0-b782-fa964c8cd6d6', 'Extinction Of All Children': '2e66b35b-716f-5c1d-8225-9047c3a89ab9', 'Singularity Series': '0384348a-453b-5842-ab1c-431b22382845', 'Bliss Brothers': '8d1edf1c-705a-5e9f-9d9b-f141685a944c', 'The Love Game': 'cebb9eea-a565-57ba-9bb9-fa1571ba1cd0', 'Truth in Lies': 'daa6e8fc-cd4f-5bf8-94f9-6aee75d710be', 'Love Online': '35b37ccf-a534-52ed-bb71-236aeed85b2e', 'First Comes Love': '81fb97ef-f366-5a90-b8c5-235196db8605', 'BEYOND': 'd6b5b7a7-2ea1-5df7-a528-cd20cc7c76fb', 'Seasons in a Small Town': 'e3545731-3407-5d74-9f98-4f78f9eaa95f', 'Dreamshifters': 'eed252a8-efd1-5da6-974a-d5d3afd19e39', 'Just Friends': '11c82c60-473e-5505-9206-4f89d957da22', 'Return to Willoughby Close': '4db61c22-dab4-57c3-82c8-009c062a9b56', 'Altered Genes': '606295fe-e849-5d6c-8d4a-15e5d39825a4', 'Instant Reality': 'e728e402-97eb-553e-8afa-fcc6dd849280'}
DEBUG:    0.1 KoboTouch:books - about to sync_booklists
DEBUG:    0.1 USBMS: starting sync_booklists
DEBUG:    0.1 USBMS: finished sync_booklists
DEBUG:    0.1 KoboTouch:books - have done sync_booklists
DEBUG:    0.1 KoboTouch:books - end - oncard='None'
DEBUG:    0.1 KoboTouch:books - oncard='carda'
DEBUG:    0.1 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    0.1 KoboTouch:books - oncard='cardb'
DEBUG:    0.1 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 51
DeviceJob: set_books_in_library finished: time= 0.010000228881835938
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
2021-12-07 21:46:23 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2021-12-07 21:46:23 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000021A86CAEA00>
2021-12-07 21:46:23 [DEBUG] KoboTouchExtended:settings: settings=                                                                  2021-12-07 21:46:23 [DEBUG] <calibre.utils.config_base.OptionValues object at 0x0000021A86CAEFD0>
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DEBUG:    6.0 KoboUtilites:_on_device_metadata_available - Start
DEBUG:    6.0 Have a Kobo device connected connected
DEBUG:    6.0 BEGIN Get Device Path
DEBUG:    6.0 Root path of device: F:\
DEBUG:    6.0 END Get Device Path
DEBUG:    6.0 KoboUtilities:get_device - self.device_path="F:\"
DEBUG:    6.0 KoboUtilities:get_device - drive_info: {'main': {'device_store_uuid': 'e5828256-3881-4fb5-8575-8b081db914b5', 'device_name': 'Kobo Sage', 'location_code': 'main', 'last_library_uuid': None, 'calibre_version': '5.33.2', 'date_last_connected': '2021-12-08T04:46:23.001199+00:00', 'prefix': 'F:/'}}
DEBUG:    6.0 migrate_library_config_if_required - start
DEBUG:    6.0 get_library_config - library_config: {'profiles': {'Default': {'forDevice': None, 'updateOptionsStore': {'doFirmwareUpdateCheck': False, 'firmwareUpdateCheckLastTime': 0, 'doEarlyFirmwareUpdate': False}, 'storeOptionsStore': {'storeOnConnect': False, 'promptToStore': True, 'storeIfMoreRecent': False, 'doNotStoreIfReopened': False}}}, 'SchemaVersion': 0.1}
DEBUG:    6.0 get_plugin_pref - start - store_name='commonOptionsStore', option='individualDeviceOptions'
DEBUG:    6.0 get_prefs - start - store_name='backupOptionsStore'
DEBUG:    6.0 get_prefs - start - store_name='updateOptionsStore'
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - device connected. self.device.fwversion= (4, 30, 18838)
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Connected Device: Kobo Sage
Firmware version: 4.30.18838
Driver: KoboTouchExtended'
DEBUG:    6.0 KoboUtilites:_on_device_metadata_available - self.current_device_profile: None
DEBUG:    6.0 KoboUtilites:_on_device_metadata_available - self.current_backup_config: {'doDailyBackp': False, 'backupEachCOnnection': False, 'backupCopiesToKeepSpin': 5, 'backupDestDirectory': '', 'backupZipDatabase': True}
DEBUG:    6.0 Have a Kobo device connected connected
DEBUG:    6.0 BEGIN Get Device Path
DEBUG:    6.0 Root path of device: F:\
DEBUG:    6.0 END Get Device Path
DEBUG:    6.0 KoboUtilities:get_device - self.device_path="F:\"
DEBUG:    6.0 KoboUtilities:get_device - drive_info: {'main': {'device_store_uuid': 'e5828256-3881-4fb5-8575-8b081db914b5', 'device_name': 'Kobo Sage', 'location_code': 'main', 'last_library_uuid': None, 'calibre_version': '5.33.2', 'date_last_connected': '2021-12-08T04:46:23.001199+00:00', 'prefix': 'F:/'}}
DEBUG:    6.0 migrate_library_config_if_required - start
DEBUG:    6.0 get_library_config - library_config: {'profiles': {'Default': {'forDevice': None, 'updateOptionsStore': {'doFirmwareUpdateCheck': False, 'firmwareUpdateCheckLastTime': 0, 'doEarlyFirmwareUpdate': False}, 'storeOptionsStore': {'storeOnConnect': False, 'promptToStore': True, 'storeIfMoreRecent': False, 'doNotStoreIfReopened': False}}}, 'SchemaVersion': 0.1}
DEBUG:    6.0 get_plugin_pref - start - store_name='commonOptionsStore', option='individualDeviceOptions'
DEBUG:    6.0 get_prefs - start - store_name='backupOptionsStore'
DEBUG:    6.0 get_prefs - start - store_name='updateOptionsStore'
DEBUG:    6.0 rebuild_menus - self.supports_ratings=True, self.supports_tiles=True
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - device connected. self.device.fwversion= (4, 30, 18838)
DEBUG:    6.0 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Connected Device: Kobo Sage
Firmware version: 4.30.18838
Driver: KoboTouchExtended'
DEBUG:    6.0 rebuild_menus - have device.
DeviceJob: 2 Get list of books on device callback returned
Job: 3 Send metadata to device started
DEBUG:    0.2 KOBO:sync_booklists - start
DEBUG:    0.2 KoboTouch:update_device_database_collections - oncard='main'
DEBUG:    0.2 KoboTouch::is_supported_fwversion - self.fwversion[:2] (4, 30)
DEBUG:    0.2 KoboTouch:update_device_database_collections - set_debugging_title to ''
DEBUG:    0.2 KTCollectionsBookList:get_collections - start - collection_attributes= ['tags']
DEBUG:    0.2 KTCollectionsBookList:get_collections - collection_attributes= ['tags']
DEBUG:    0.2 KTCollectionsBookList:get_collections - end
DEBUG:    0.2 KoboTouch:update_device_database_collections - category='Sci Fi' books=3
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Sci Fi'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Heartwarmers' books=1
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Heartwarmers'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Chick Lit- Supernatural' books=7
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Chick Lit- Supernatural'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Non-Fiction: Life Journeys' books=2
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Non-Fiction: Life Journeys'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Supernatural' books=1
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Supernatural'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Chick Lit' books=5
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Chick Lit'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Romance' books=3
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Romance'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Thriller' books=1
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Thriller'
DEBUG:    0.3 KoboTouch:update_device_database_collections - category='Non-Fiction: Personal Organization' books=1
DEBUG:    0.3 KoboTouch:update_device_database_collections - end for category='Non-Fiction: Personal Organization'
DEBUG:    0.3 KoboTouch:update_device_database_collections - managing bookshelves and series.
DEBUG:    0.3 KoboTouch:update_device_database_collections - about to clear empty bookshelves
DEBUG:    0.3 KoboTouch:delete_empty_bookshelves - start
DEBUG:    0.3 KoboTouch:delete_empty_bookshelves - delete_query= DELETE FROM Shelf WHERE Shelf._IsSynced = 'false' AND Shelf.InternalName not in ('Shortlist', 'Wishlist') AND (Type IS NULL OR Type <> 'SystemTag') AND NOT EXISTS (SELECT 1 FROM ShelfContent c WHERE Shelf.Name = C.ShelfName AND c._IsDeleted <> 'true')
DEBUG:    0.3 KoboTouch:delete_empty_bookshelves - update_query= UPDATE Shelf SET _IsDeleted = 'true' WHERE Shelf._IsSynced = 'true' AND Shelf.InternalName not in ('Shortlist', 'Wishlist') AND (Type IS NULL OR Type <> 'SystemTag') AND NOT EXISTS (SELECT 1 FROM ShelfContent C WHERE Shelf.Name = C.ShelfName AND c._IsDeleted <> 'true')
DEBUG:    0.3 KoboTouch:delete_empty_bookshelves - delete_activity_query= DELETE FROM Activity WHERE Type = 'Shelf' AND NOT EXISTS (SELECT 1 FROM Shelf WHERE Shelf.Name = Activity.Id AND Shelf._IsDeleted = 'false')
DEBUG:    0.3 KoboTouch:delete_empty_bookshelves - end
DEBUG:    0.3 KoboTouch:update_device_database_collections - Number of series set=0 Number of books=25
DEBUG:    0.3 KoboTouch:update_device_database_collections - Number of core metadata set=0 Number of books=25
DEBUG:    0.4 KoboTouch:update_device_database_collections - Finished 
DEBUG:    0.4 USBMS: starting sync_booklists
DEBUG:    0.4 USBMS: finished sync_booklists
DEBUG:    0.4 KOBO:sync_booklists - end
DeviceJob: 3 Send metadata to device done, calling callback
DeviceJob: 3 Send metadata to device callback returned
Job: 0 Get device information finished
No details available.
Job: 3 Send metadata to device finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[28.84] splash screen hidden
[28.84] Started up in 28.84 seconds with 27 books
Convert book 1 of 1 (CR!YQ8WR8PZ8X0ZB016X69VNAQSTR0V.azw)

Conversion options changed from defaults:

  read_metadata_from_opf: 'C:\\Users\\jay\\AppData\\Local\\Temp\\calibre_0pcrbx4w\\53kyya92.opf'

  verbose: 2

  output_profile: 'kobo'

Resolved conversion options

calibre version: 5.33.2

{'asciiize': False,

 'author_sort': None,

 'authors': None,

 'base_font_size': 0.0,

 'book_producer': None,

 'change_justification': 'original',

 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

            "'i')) or @class = 'chapter']",

 'chapter_mark': 'pagebreak',

 'comments': None,

 'cover': None,

 'debug_pipeline': None,

 'dehyphenate': True,

 'delete_blank_paragraphs': True,

 'disable_font_rescaling': False,

 'dont_split_on_page_breaks': False,

 'duplicate_links_in_toc': False,

 'embed_all_fonts': False,

 'embed_font_family': None,

 'enable_heuristics': False,

 'epub_flatten': False,

 'epub_inline_toc': False,

 'epub_toc_at_end': False,

 'epub_version': '2',

 'expand_css': False,

 'extra_css': None,

 'extract_to': None,

 'filter_css': '',

 'fix_indents': True,

 'flow_size': 260,

 'font_size_mapping': None,

 'format_scene_breaks': True,

 'formatting_type': 'auto',

 'html_unwrap_factor': 0.4,

 'input_encoding': None,

 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B08B28A820>,

 'insert_blank_line': False,

 'insert_blank_line_size': 0.5,

 'insert_metadata': False,

 'isbn': None,

 'italicize_common_cases': True,

 'keep_ligatures': False,

 'language': None,

 'level1_toc': None,

 'level2_toc': None,

 'level3_toc': None,

 'line_height': 0.0,

 'linearize_tables': False,

 'margin_bottom': 5.0,

 'margin_left': 5.0,

 'margin_right': 5.0,

 'margin_top': 5.0,

 'markdown_extensions': 'footnotes, tables, toc',

 'markup_chapter_headings': True,

 'max_toc_links': 50,

 'minimum_line_height': 120.0,

 'no_chapters_in_toc': False,

 'no_default_epub_cover': False,

 'no_inline_navbars': False,

 'no_svg_cover': False,

 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x000001B08B28AE80>,

 'page_breaks_before': "//*[name()='h1' or name()='h2']",

 'paragraph_type': 'auto',

 'prefer_metadata_cover': False,

 'preserve_cover_aspect_ratio': False,

 'preserve_spaces': False,

 'pretty_print': True,

 'pubdate': None,

 'publisher': None,

 'rating': None,

 'read_metadata_from_opf': 'C:\\Users\\jay\\AppData\\Local\\Temp\\calibre_0pcrbx4w\\53kyya92.opf',

 'remove_fake_margins': True,

 'remove_first_image': False,

 'remove_paragraph_spacing': False,

 'remove_paragraph_spacing_indent_size': 1.5,

 'renumber_headings': True,

 'replace_scene_breaks': '',

 'search_replace': '[]',

 'series': None,

 'series_index': None,

 'smarten_punctuation': False,

 'sr1_replace': None,

 'sr1_search': None,

 'sr2_replace': None,

 'sr2_search': None,

 'sr3_replace': None,

 'sr3_search': None,

 'start_reading_at': None,

 'subset_embedded_fonts': False,

 'tags': None,

 'timestamp': None,

 'title': None,

 'title_sort': None,

 'toc_filter': None,

 'toc_threshold': 6,

 'toc_title': None,

 'transform_css_rules': '[]',

 'transform_html_rules': '[]',

 'txt_in_remove_indents': False,

 'unsmarten_punctuation': False,

 'unwrap_lines': True,

 'use_auto_toc': False,

 'verbose': 2}

InputFormatPlugin: TXT Input running

on C:\Users\jay\AppData\Local\Temp\calibre_0pcrbx4w\bu2jb1dc.md

Reading text from file...

File extension indicates particular formatting. Forcing formatting type to: markdown

Detected input encoding as iso-8859-1 with a confidence of 22.89721667766571%

Running text through markdown conversion...

Language not specified

Creator not specified

Building file list...

Traceback (most recent call last):

  File "runpy.py", line 194, in _run_module_as_main

  File "runpy.py", line 87, in _run_code

  File "site.py", line 82, in <module>

  File "site.py", line 77, in main

  File "site.py", line 49, in run_entry_point

  File "calibre\utils\ipc\worker.py", line 216, in main

  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

  File "calibre\ebooks\conversion\plumber.py", line 1111, in run

  File "calibre\customize\conversion.py", line 244, in __call__

  File "calibre\ebooks\conversion\plugins\txt_input.py", line 313, in convert

  File "calibre\ebooks\conversion\plugins\html_input.py", line 91, in convert

  File "calibre\ebooks\conversion\plugins\html_input.py", line 154, in create_oebbook

  File "calibre\ebooks\html\input.py", line 251, in get_filelist

  File "calibre\ebooks\html\input.py", line 224, in traverse

  File "calibre\ebooks\html\input.py", line 110, in __init__

ValueError: embedded null character

Added CR!YQ8WR8PZ8X0ZB016X69VNAQSTR0V.azw to db in: 1.0
Added 1 books in 2.4 seconds
Worker Launch took: 0.00 seconds
Job: 4 Convert book 1 of 1 (CR!YQ8WR8PZ8X0ZB016X69VNAQSTR0V.azw) finished
Convert book 1 of 1 (CR!YQ8WR8PZ8X0ZB016X69VNAQSTR0V.azw)

	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\jay\\AppData\\Local\\Temp\\calibre_0pcrbx4w\\53kyya92.opf'

	  verbose: 2

	  output_profile: 'kobo'

	Resolved conversion options

	calibre version: 5.33.2

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'formatting_type': 'auto',

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B08B28A820>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markdown_extensions': 'footnotes, tables, toc',

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x000001B08B28AE80>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'paragraph_type': 'auto',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'preserve_spaces': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\jay\\AppData\\Local\\Temp\\calibre_0pcrbx4w\\53kyya92.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'txt_in_remove_indents': False,

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	InputFormatPlugin: TXT Input running

	on C:\Users\jay\AppData\Local\Temp\calibre_0pcrbx4w\bu2jb1dc.md

	Reading text from file...

	File extension indicates particular formatting. Forcing formatting type to: markdown

	Detected input encoding as iso-8859-1 with a confidence of 22.89721667766571%

	Running text through markdown conversion...

	Language not specified

	Creator not specified

	Building file list...

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 216, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1111, in run

	  File "calibre\customize\conversion.py", line 244, in __call__

	  File "calibre\ebooks\conversion\plugins\txt_input.py", line 313, in convert

	  File "calibre\ebooks\conversion\plugins\html_input.py", line 91, in convert

	  File "calibre\ebooks\conversion\plugins\html_input.py", line 154, in create_oebbook

	  File "calibre\ebooks\html\input.py", line 251, in get_filelist

	  File "calibre\ebooks\html\input.py", line 224, in traverse

	  File "calibre\ebooks\html\input.py", line 110, in __init__

	ValueError: embedded null character

**Comment by ElleKayEm** [comment]
DeDRM will automatically retrieve the key for Kindle for PC as long as it is installed on the same machine and user.  But you need to use an older version of Kindle for PC or disable downloads of the newer KFX format.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
