### ISSUE TITLE
Can't DeDRM Kindle books on new Mac installation

### ISSUE THREAD

**Issue by pjft** [apprenticeharper/DeDRM_tools#1959]
## Can't DeDRM Kindle books on new Mac installation
Apologies for bothering. I'm migrating to a new Mac laptop, and whereas in my previous laptop I had Calibre and DeDRM working flawlessly, I am struggling to get this working in the new setup. On my old Mac I have Kindle for Mac 1.33, DeDRM 7.2.1, and Calibre 5.28.

What did I do:

- Installed Calibre
- Installed DeDRM 7.2.1
- Installed Kindle for Mac 1.26.1 (I think it's the first 64-bit version that works?), and it's also the version I had in my previous Mac (though it recently updated to 1.33, and it still works there).
- Did the chmod trick to prevent KFX from being downloaded.

Now, it seems that the book is failing to import immediately. In both it is downloaded as an AZW file, but on the old Mac, it gets imported as "MOBI", whereas on the new Mac it gets imported as AZW and then fails to be converted.

I tried exporting the keys from the old Mac to the new one, but apparently they are unique to the installation. Kindle for Mac and Calibre are installed under the same user. I can confirm that the license file exists in the expected folder, with the expected name.

In the old Mac, the import log is simple:
```
Crypto Type is: 1
File is encoded with PID M2M0bNx412
Decrypting. Please Wait . . . done
```

In the new one it fails. The only other difference is that in the old Mac it is using "Library AlfCrypto DLL/DYLIB/SO" and in the new one it's using "AlfCrypto Python", unsure if that has any impact on it.

Any guidance or pointers would be very much appreciated.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.33.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
calibre 5.33.2  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 32, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 32, 0) && KFX metadata reader (from KFX Input) (1, 32, 0) && KFX Input (1, 32, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[0.94] main UI initialized...
[0.94] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.32.0: Importing /Users/pjt/Library/Application Support/Kindle/My Kindle Content/B0057ZER34_EBOK/B0057ZER34_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B0057ZER34_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Read This Before Our Next Meeting
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/pjt/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'pjt'  on file  /Users/pjt/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'c301c7713d69'
trying IDString: b'c301c7713d68'
[8.24] splash screen hidden
[8.24] Started up in 8.24 seconds with 1803 books
trying IDString: b'99a39584eb81'
Decrypted key file using IDString '99a39584eb81' and UserName 'pjt'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Read This Before Our Next Meeting
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 1.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Read This Before Our Next Meeting to db in: 0.0
Added 1 books in 1.6 seconds
Downloading plugin ZIP attachment:  https://code.calibre-ebook.com/plugins/291290.zip
Installing plugin:  /var/folders/zf/j1wt92hx0njc6v33mx66016xxt47l9/C/calibre_5.33.2_tmp_0jrxyaxo/z5ik7nw8.zip
```
</details>

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.2.  Available here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

**Comment by pjft** [comment]
Oh thank you, it did work with that. I wasn't aware of that project. Is it expectable that those changes will make it here as well at some point?

Regards.

**Comment by ElleKayEm** [comment]
No, Apprentice Harper is no longer maintaining these tools.  See note here:  https://github.com/apprenticeharper/DeDRM_tools#no-longer-maintained
