### ISSUE TITLE
Calibre conversion status is forever 1%

### ISSUE THREAD

**Issue by YoungMaxine** [apprenticeharper/DeDRM_tools#1961]
Hi - I followed the readme instructions, added the latest DeDRM plugin release to Calibre and tried to convert a book i bought on google play (loaded to ADE already) to PDF.  However after 30 minutes it's still showing only 1% progress.  Here's the job details:

Convert book 1 of 1 (命數)
DeDRM v7.2.1: Trying to decrypt a0jxdl6m.pdf
DeDRM v7.2.1: a0jxdl6m.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1460, in initialize
    raise PDFEncryptionError('Document is not encrypted.')
calibre_plugins.dedrm.ineptpdf.PDFEncryptionError: Document is not encrypted.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.0 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1460, in initialize
    raise PDFEncryptionError('Document is not encrypted.')
calibre_plugins.dedrm.ineptpdf.PDFEncryptionError: Document is not encrypted.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/ql/nxd5ws3d78j4h_njjc3bmryc0000gp/C/calibre_5.32.0_tmp_ejyrrztl/dcxlabzh.opf'
  verbose: 2
  cover: '/var/folders/ql/nxd5ws3d78j4h_njjc3bmryc0000gp/C/calibre_5.32.0_tmp_ejyrrztl/v4b0ys0i.jpeg'
  output_profile: 'kindle'
Resolved conversion options
calibre version: 5.32.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/ql/nxd5ws3d78j4h_njjc3bmryc0000gp/C/calibre_5.32.0_tmp_ejyrrztl/v4b0ys0i.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10bd1b280>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x10bd1b790>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Helvetica',
 'pdf_serif_family': 'Times',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/ql/nxd5ws3d78j4h_njjc3bmryc0000gp/C/calibre_5.32.0_tmp_ejyrrztl/dcxlabzh.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: Trying to decrypt a0jxdl6m.pdf
DeDRM v7.2.1: a0jxdl6m.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1460, in initialize
    raise PDFEncryptionError('Document is not encrypted.')
calibre_plugins.dedrm.ineptpdf.PDFEncryptionError: Document is not encrypted.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.0 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1460, in initialize
    raise PDFEncryptionError('Document is not encrypted.')
calibre_plugins.dedrm.ineptpdf.PDFEncryptionError: Document is not encrypted.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.0 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: PDF Input running
on /var/folders/ql/nxd5ws3d78j4h_njjc3bmryc0000gp/C/calibre_5.32.0_tmp_ejyrrztl/a0jxdl6m.pdf
Converting file to html...

Could you advise what the problem is please? Your help is highly appreciated!  Thanks in advance!

Max

**Comment by ElleKayEm** [comment]
If this is Windows calibre, are you using the 64-bit version?  And try noDRM's latest DeDRM:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

(Apprentice Harper is no longer maintaining these tools.)

**Comment by sohang3112** [comment]
I have faced this same Calibre bug with multiple book on linux (conversion stuck at 1% (PDF to EPUB, EPUB to EPUB)) - both in Fedora and Ubuntu linux.

**Comment by ElleKayEm** [comment]
Do they still have DRM or not?

**Comment by sohang3112** [comment]
> Do they still have DRM or not?

No DRM in the books I mentioned.

**Comment by ElleKayEm** [comment]
Suggest asking over at the calibre forum at MobileRead.com.
