### ISSUE TITLE
cannot install plugin in calibre 5.32

### ISSUE THREAD

**Issue by algreen702021** [apprenticeharper/DeDRM_tools#1962]
Hi,
cannot install the DeDRM_tools_7.2.1.zip   **does not contain a top-level __init__.py file**
Any help please?  
thanks Alex

```
calibre, version 5.32.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/tess/Downloads/calibre plugins crack DRM etc/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.32  embedded-python: True is64bit: True
Linux-5.4.0-91-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-91-generic', '#102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: LCPL Input (0, 0, 5)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/tess/Downloads/calibre plugins crack DRM etc/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by j-howell** [comment]
See the FAQ: [I am trying to install the calibre plugin, but calibre says "ERROR: Unhandled exception: InvalidPlugin: The plugin in u’[path]DeDRM_tools_6.5.3.zip’ is invalid. It does not contain a top-level __init__.py file"](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-am-trying-to-install-the-calibre-plugin-but-calibre-says-error-unhandled-exception-invalidplugin-the-plugin-in-upathdedrm_tools_653zip-is-invalid-it-does-not-contain-a-top-level-__init__py-file)

**Comment by j-howell** [comment]
Also newer versions of DeDRM are available at https://github.com/noDRM/DeDRM_tools/releases

**Comment by paulober** [comment]
You have to install the _plugin zip file which you have to extract from the tools zip first! - You can close this issue now
