### ISSUE TITLE
Cannot remove DRM from book

### ISSUE THREAD

**Issue by lince099** [apprenticeharper/DeDRM_tools#1967]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---
Hi there, I downloaded a book from Kindle website to my computer. It won't open in Calibre after installing hte plug in. I also try to download the same book to the Kindle app in my PC and drag the AZW file to calibre. This won't work either. Log below. Can you help me?

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.81139489194499 x 95.9160839160839
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[1.12] main UI initialized...
[1.12] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Python (2nd Edition)_ Learn Python in One Day and Learn It Well. Python for Beginners with Hands-on Project. (Learn Coding Fast with Hands-On Project Book 1) (1).azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Python (2nd Edition): Learn Python in One Day and Learn It Well. Python for Beginners with Hands-on Project. (Learn Coding Fast with Hands-On Project Book 1)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\idelg\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\idelg\AppData\Local\Amazon\Kindle\storage\.kinf2018
[10.26] splash screen hidden
[10.26] Started up in 10.26 seconds with 1 books
Decrypted key file using IDString '2419492668' and UserName 'idelg'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Python (2nd Edition): Learn Python in One Day and Learn It Well. Python for Beginners with Hands-on Project. (Learn Coding Fast with Hands-On Project Book 1)
Got DSN key from database default_key_1
Found 4 keys to try after 2.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 2.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added Python (2nd Edition): Learn Python in One Day and Learn It Well. Python for Beginners with Hands-on Project. (Learn Coding Fast with Hands-On Project Book 1) to db in: 0.1
Added 1 books in 2.8 seconds
Worker Launch took: 0.00 seconds

```
</details>

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device and have that Kindle's serial number entered into DeDRM's customization.

In order to decrypt a book from Kindle for PC, you need an earlier version or you need to prevent KFX format downloads.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by lince099** [comment]
Thank you ElleKayEm!!!! that worked. much appreciated :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
