### ISSUE TITLE
Can't convert awz file, I've followed every steps

### ISSUE THREAD

**Issue by Baswouelle** [apprenticeharper/DeDRM_tools#1977]
I've downloaded ebook from my amazon kindle unlimited account. 
Cheers,

[Edit]
Here are the steps I've followed
Downloaded kindle 1.31
registered my account, unchecked auto update
closed the app
ran sudo chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test in terminal
Opened kindle again, downloaded the book
Imported the B0973NHVSD_EBOK.azw in calibre (DeDRM plugin previously installed)
When I tried to view or convert the book, I get an error saying that the book has a DRM

### FKX input 1.46.0

calibre Debug log
calibre 5.34  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.34  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.25] main UI initialized...
[1.25] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B0973NHVSD_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Feel-Good Experience: Growing Your Physical Therapy Practice with 5-Star Customer Service
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/ariel/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'ariel'  on file  /Users/ariel/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'29203557dc1b'
Decrypted key file using IDString '29203557dc1b' and UserName 'ariel'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Feel-Good Experience: Growing Your Physical Therapy Practice with 5-Star Customer Service
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[9.29] splash screen hidden
[9.29] Started up in 9.29 seconds with 292 books
Added The Feel-Good Experience: Growing Your Physical Therapy Practice with 5-Star Customer Service to db in: 0.0
Added 1 books in 1.0 seconds
Worker Launch took: 0.01 seconds
```
</details>

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by al-iskandar-github** [comment]
> These tools are intended for purchased books.

That doesn't actually make a difference to whether or not the plugin works, as there's no difference in formatting between ordinary kindle ebooks and Kindle Unlimited ones. 

If you're complaining about possible piracy, then if someone is reading a book on Kindle Unlimited then there's no reason they shouldn't be allowed to read it on a different format if they want. There's nothing to indicate any untoward behaviour here.

If you don't actually have anything constructive to add, I'm not sure why you'd bother answering issue posts in the first place. As it is, I'm only sorry for OP that I can't be of any actual help to them.

**Comment by ElleKayEm** [comment]
This plugin does actually check if a KFX format book is licensed as KU.  And removing DRM from Kindle Unlimited books prevents the author from getting paid.  Amazon only pays them based on how much of the book is read.  They can only tell that if you read them in a Kindle app or device with DRM intact.

**Comment by Baswouelle** [comment]
I want to convert it to be able to read it on my kobo. I don't like to read on my computer.
Is that possible ?

**Comment by ElleKayEm** [comment]
Again, this plugin is intended to work with purchased books.

**Comment by al-iskandar-github** [comment]
> This plugin does actually check if a KFX format book is licensed as KU.

Even if it does check, then it doesn't have any impact on the end result. I've always been able to successfully convert kindle unlimited ebooks myself without any issues - hell, I just did so a few minutes ago. I have genuinely no clue where you're getting the idea that DeDRM Tools don't work for Kindle Unlimited books. It's complete and utter nonsense.

>And removing DRM from Kindle Unlimited books prevents the author from getting paid. Amazon only pays them based on how much of the book is read. They can only tell that if you read them in a Kindle app or device with DRM intact.

There are still plenty of valid reasons to want to remove the DRM from a Kindle Unlimited book, for instance so that you can read it on another, non-Amazon device. Regardless, it doesn't change the fact that your moralising is utterly irrelevant to someone asking for technical advice. 

> I want to convert it to be able to read it on my kobo. I don't like to read on my computer.
> Is that possible ?

Yes, there's no reason why you shouldn't be able to convert a Kindle Unlimited book so that you can read it on your Kobo - I've done it myself for that exact reason before. Unfortunately, I'm not familiar with using Calibre and DeDRM on Mac, so I can't give any specific advice in that regards.

Edit: If you could add which exact steps you followed, it would be easier for someone experienced with the Mac version to tell where a problem occurred, and if it's on your end or not.

**Comment by al-iskandar-github** [comment]
> Again, this plugin is intended to work with purchased books.

Again, this plugin works completely fine with Kindle Unlimited books. Also, if you have nothing useful to add, and if you're only going to repeat blatantly incorrect information, then just don't say anything. You're being actively unhelpful at this point.

**Comment by ElleKayEm** [comment]
If you think that anything I've said here isn't true, then you're not paying close enough attention to what I actually wrote.

**Comment by noDRM** [comment]
The plugin (at least this version) does not work with KindleUnlimited books. There's an explicit check. That would lead to a different error message, though, the one in this log probably means you didn't enter the Kindle serial number into the settings.

**Comment by Baswouelle** [comment]
> the one in this log probably means you didn't enter the Kindle serial number into the settings.

It's a Mac app, I don't own a kindle device, so there is no serial number to enter

**Comment by Baswouelle** [comment]
> Edit: If you could add which exact steps you followed, it would be easier for someone experienced with the Mac version to tell where a problem occurred, and if it's on your end or not.

just did it , thanks

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
