### ISSUE TITLE
Cannot remove DRM from purchased book 

### ISSUE THREAD

**Issue by ilteris** [apprenticeharper/DeDRM_tools#1978]
Hello, below is my trace.

I purchased it at amazon.  unfortunately cannot remove DRM :( 

Any help please? Thank you!

```calibre Debug log
calibre 5.34  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && Count Pages (1, 11, 1) && Find Duplicates (1, 8, 10) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
calibre 5.34  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && Count Pages (1, 11, 1) && Find Duplicates (1, 8, 10) && Goodreads Sync (1, 15, 1) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 99.00000148683084 x 99.00000148683085
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.92] db initialized
[0.92] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.8 HttpHelper::__init__: proxy=None
[2.08] main UI initialized...
[2.08] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing /Volumes/Kindle/documents/Downloads/Items01/The Career Toolkit_ Essential Skills for Success That No One Taught You_B08QD93HRT.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/4iu79v7v.kfx-zip
DeDRM v7.2.1: Trying to decrypt 4iu79v7v.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: 4iu79v7v
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/1xo7tix5plugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.46.0: Packaging /var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/4iu79v7v.kfx-zip
Processing container: CR!703WS64FMH7G340W42WN4CDPMHWX.kfx
Processing container: The Career Toolkit_ Essential Skills for Success That No One Taught You_B08QD93HRT.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/8b/b7qvj7_d74d4037tw0p39x9000_0b3/C/calibre_5.34.0_tmp_r9m4g_4p/nqwii3_k_add_books/0/The Career Toolkit_ Essential Skills for Success That No One Taught You_B08QD93HRT.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container The Career Toolkit_ Essential Skills for Success That No One Taught You_B08QD93HRT.kfx has DRM and cannot be converted
[11.78] splash screen hidden
[11.78] Started up in 11.78 seconds with 92 books

{'bsd_drives': {'main': '/dev/disk2'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'//DRIVE@localhost:49419/Google%20Drive': '/Volumes/GoogleDrive',
               '//ilteris@lorimer._afpovertcp._tcp.local/data': '/Volumes/data',
               '//ilteris@lorimer._afpovertcp._tcp.local/usbshare1-2': '/Volumes/usbshare1-2',
               '/dev/disk1s1s1': '/',
               '/dev/disk1s2': '/System/Volumes/Data',
               '/dev/disk1s3': '/System/Volumes/Preboot',
               '/dev/disk1s5': '/System/Volumes/VM',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 14, count of files in metadata: 14, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 14
DeviceJob: set_books_in_library finished: time= 0.005306720733642578
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added The Career Toolkit: Essential Skills for Success That No One Taught You to db in: 1.9
Added 1 books in 2.6 seconds
```

**Comment by ilteris** [comment]
it worked now on a second try so can delete this issue

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by ilteris** [comment]
> If you're all set, you can close the issue.
done
