### ISSUE TITLE
cannot read pdf, epub is fine

### ISSUE THREAD

**Issue by ReiGf** [apprenticeharper/DeDRM_tools#1981]
Thanks for this great work. 
I read the FAQ and tried it with fresh pdf. Maybe I missed something else. The same inputfile works with calibre 4.23 and ineptepub_v01.7, though. 

calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 96.0 x 96.11590909090908
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.50] splash screen shown
[1.50] Initializing db...
[1.50] db initialized
[1.50] Constructing main UI...
[2.86] main UI initialized...
[2.86] Hiding splash screen
Starting QuickView
[107.03] splash screen hidden
[107.03] Started up in 107.03 seconds with 12 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbd3\x03\xefM3:\xbeI~X\xf6xR^U{n.\x94\xee\xcb\x16\xe8\x06\t{\x97\xf8\x06\xb9\xf5', b'C:\\Users\\XXXX\\Documents\\My Digital Editions\\YYYY.pdf']
DeDRM v7.2.1: Trying to decrypt YYYY.pdf
DeDRM v7.2.1: YYYY.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.3 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 318, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler^M
pdfinfo errored out with returAdded YYYY to db in: 1.0
Added 1 books in 3.4 seconds

**Comment by ElleKayEm** [comment]
Try noDRM's DeDRM available here:  https://github.com/noDRM/DeDRM_tools
