### ISSUE TITLE
Problem dedrm kindle book

### ISSUE THREAD

**Issue by alessandrocardelli** [apprenticeharper/DeDRM_tools#1985]
Hello,
I've a problem importing one book (AZW) it says it is still locked.

System: Windows 10
Kindle Desktop App: 1.17.1 (44183)
Calibre: 5.34.0 64bit
DeDRM: 7.2.1

Looks like it cant find the key?

calibre Log di debug
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.34 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.52] splash screen shown
[0.52] Initializing db...
[0.52] db initialized
[0.52] Constructing main UI...
[1.19] main UI initialized...
[1.19] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B08B7X93XW_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Internal Organs (THIEME Atlas of Anatomy)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Andy\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Andy\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[4.44] splash screen hidden
[4.44] Started up in 4.44 seconds with 119 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'-\r\xa0\xeaBD\x02w\xfb\x94]\xf6W\x80\x89\x1f\xc1\x8bU\x0evb\xe1-\x1f\x94\x95\xcc\xc7W\xf6\xc4', b'D:\\Utenti\\Andy\\Google Drive\\B08B7X93XW_EBOK.azw']
Added Internal Organs (THIEME Atlas of Anatomy) to db in: 1.3
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/maAdded 1 books in 1.9 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment]
It found a key, but looks like it wasn't the right one for this book.  Was the book downloaded with the currently installed Kindle for PC app on the same machine and user as calibre with DeDRM?
