### ISSUE TITLE
Problem with proquest book DRM not being removed

### ISSUE THREAD

**Issue by hhpicker** [apprenticeharper/DeDRM_tools#1986]
Hi there,

Attempted to use Calibre to remove DRM on an Adobe Digital Editions encrypted file - have done this many times before with no issue. The book in question is from ProQuest, also have de-DRMed many books from them in the past with no issue. I tried both a pdf and an epub of the book, neither of which worked. Attached is the encrypted pdf file gotten after putting the acsm through ADE, although I only have the loan for a day - can try again also for a longer loan if that would be helpful. Both worked totally fine within ADE. I ran Calibre in debug mode to get the log as instructed in the ReadMe, which is as follows:

calibre Debug log
calibre 5.34  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.34  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.58] splash screen shown
[0.58] Initializing db...
[0.58] db initialized
[0.58] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
[16.52] splash screen hidden
[16.52] Started up in 16.52 seconds with 8 books
Added 422896 to db in: 0.2
Added 1 books in 0.4 seconds
DeDRM v7.2.1: Trying to decrypt A Brief History of Neoliberalism.pdf
DeDRM v7.2.1: A Brief History of Neoliberalism.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.4 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 318, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x07070970>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07070970>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'E#\x80\xe77\xa8\xd5\xfa\xbf\xabCn\xf97\x88\xf0\xfc\xd6}\xb0r\xe0\xe9\\DT\x16\xf0(\x16\xe6#', b'C:\\Users\\Holly\\Documents\\My Digital Editions\\A Brief History of Neoliberalism.pdf']
Added A Brief History of Neoliberalism to db in: 0.2
Added 1 books in 1.0 seconds

Any ideas would be great, thank you!

[A Brief History of Neoliberalism.pdf](https://github.com/apprenticeharper/DeDRM_tools/files/7843286/A.Brief.History.of.Neoliberalism.pdf)

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by j-howell** [comment]
That book has Adobe's hardened DRM. Even if it wasn't a loan these tools would not able able to do anything with it.
