### ISSUE TITLE
[QUESTION]The app is not working 

### ISSUE THREAD

**Issue by Aliakbari089** [apprenticeharper/DeDRM_tools#1987]
Here is the log 

calibre Debug log
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.14393 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 3.8.5
Windows: ('10', '10.0.14393', '', 'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: 'C:\\Users\\Administrator\\AppData\\Roaming\\calibre\\plugins\\KFX Input.zip'
Successfully initialized third party plugins: DeDRM (7, 2, 1) && EpubMerge (2, 5, 0) && KindleUnpack - The Plugin (0, 83, 0)
calibre 5.22.1  embedded-python: True is64bit: False
Windows-10-10.0.14393 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.14393')
Python 3.8.5
Windows: ('10', '10.0.14393', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && EpubMerge (2, 5, 0) && KindleUnpack - The Plugin (0, 83, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.1103448275862
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.62] splash screen shown
[0.62] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
[2.52] main UI initialized...
[2.52] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt ****
DeDRM v7.2.1: Verifying zip archive integrity
[50.08] splash screen hidden
[50.08] Started up in 50.08 seconds with 80 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 408 b'\x01\x00\x00\x00\x0c\x00\x00\x00\xcc\x00\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d:\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xaf&\x00\x01\x00&\x00\xef\xbe\x11\x00\x00\x00\xe3\x0c\xaf}#\xc6\xd3\x01\xba\x1a\x0c\n\xac\xda\xd7\x01\x94\x97\x8b\t\xda\xd9\xd7\x01\x14\x00p\x001\x00\x00\x00\x00\x00.T\xa31\x10\x00MYDIGI~1\x00\x00X\x00\t\x00\x04\x00\xef\xbe|L\xf1V.T\xa31.\x00\x00\x00\xdb\xac\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1fV\xf8\x00M\x00y\x00 \x00D\x00i\x00g\x00i\x00t\x00a\x00l\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00s\x00\x00\x00\x18\x00\x00\x00\xca\x002\x00\xe1\xc5\xbf .T\x8c1 \x00ATLASO~1.EPU\x00\x00\xae\x00\t\x00\x04\x00\xef\xbe.T\x8b1.T\x8b1.\x00\x00\x00\xdc\xdb\x08\x00\x00\x00#\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00A\x19\x17\x00A\x00t\x00l\x00a\x00s\x00 \x00o\x00f\x00 \x00E\x00s\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 b'`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 b'\x01\x00\x00\x00' 

text/uri-list 141 b'file:///C:/Users/Administrator/Documents/My%20Digital%20Editions/Atlas%20of%20Essential%20Orthopaedic%20Procedures,%20Second%20Edition.epub\r\n' 

application/x-qt-windows-mime;value="FileName" 49 b'C:\\Users\\ADMINI~1\\DOCUME~1\\MYDIGI~1\\ATLASO~1.EPU\x00' 

application/x-qt-windows-mime;value="FileContents" 0 b'' 

application/x-qt-windows-mime;value="FileNameW" 232 b'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00A\x00d\x00m\x00i\x00n\x00i\x00s\x00t\x00r\x00a\x00t\x00o\x00r\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00D\x00i\x00g\x00i\x00t\x00a\x00l\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00s\x00\\\x00A\x00t\x00l\x00a\x00s\x00 \x00o\x00f\x00 \x00E\x00s\x00s\x00e\x00n\x00t\x00i\x00a\x00l\x00 \x00O\x00r\x00t\x00h\x00o\x00p\x00a\x00e\x00d\x00i\x00c\x00 \x00P\x00r\x00o\x00c\x00e\x00d\x00u\x00r\x00e\x00s\x00,\x00 \x00S\x00e\x00c\x00o\x00n\x00d\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00.\x00e\x00p\x00u\x00b\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 b'\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xa79\xb1\r\t\xd8\x01\x00\x00\x00\x00\x00\x00\x00\x00\xbf\xbaS\xb2\r\t\xd8\x01\x00\x00\x00\x00\xe1\xc5\xbf A\x00t\x00l\x00a\x00s\x00 \x00o\x00f\x00 \x00E\x00s\x00s\x00e\x00n\x00t\x00i\x00a\x00l\x00 \x00O\x00r\x00t\x00h\x00o\x00p\x00a\x00e\x00d\x00i\x00c\x00 \x00P\x00r\x00o\x00c\x00e\x00d\x00u\x00r\x00e\x00s\x00,\x00 \x00S\x00e\x00c\x00o\x00n\x00d\x00 \x00E\x00d\x00i\x00t\x00i\x00o\x00n\x00.\x00e\x00p\x00u\x00b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

Firefox rurl: None None
URLS: ['file:///C:/Users/Administrator/Documents/My%20Digital%20Editions/Atlas%20of%20Essential%20Orthopaedic%20Procedures,%20Second%20Edition.epub']
Paths: ['C:/Users/Administrator/Documents/My Digital Editions/Atlas of Essential Orthopaedic Procedures, Second Edition.epub']
Extensions: frozenset({'epub'})
DeDRM v7.2.1: “Atlas of Essential Orthopaedic Procedures, Second Edition.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePuTraceback (most recent call last):
  File "calibre\customize\ui.py", line 741, in initialize_plugins
  File "calibre\customize\ui.py", line 65, in load_plugin
  File "calibre\customize\zipplugin.py", line 293, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kfx_input.__init__", line 9, in <module>
ModuleNotFoundError: No module named 'StringIO'
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 134, in __init__
  File "calibre\gui2\ui.py", line 152, in init_iaction
  File "calibre\customize\__init__.py", line 626, in load_actual_plugin
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 192, in exec_module
  File "calibre_plugins.epubmerge.epubmerge_plugin", line 14, in <module>
ModuleNotFoundError: No module named 'StringIO'
Added Atlas of Essential Orthopaedic Procedures, Second Edition to db in: 2.5
Added 1 books in 7.6 seconds

**Comment by ElleKayEm** [comment]
Doesn't look like this has DRM that DeDRM recognizes.

**Comment by Aliakbari089** [comment]
The ebook downloaded through Adobe digital with acsm file !!!
It seems that drm coding is changing

**Comment by ElleKayEm** [comment]
Did you use ADE 2.0.1?  If not, can it be opened in ADE 2.0.1 authorized with the same Adobe ID?

**Comment by Aliakbari089** [comment]
When I tried to download the acsm file through ADE 2.0.1, I received this error: e adept core decrypt license key error
But with ADE 3 and 4 download will complete. and after the file downloaded successfully I can read it on ADE 2.0.1 . But when I want to dedrm the file, it fails to dedrm

**Comment by ElleKayEm** [comment]
The fact that it won't download with ADE 2.0.1 (only 3 and up) would lead me to believe it has the hardened DRM that can't be decrypted.  But as far as I knew, those files can't be read with ADE 2.0.1 either.  At any rate, DeDRM isn't able to find the info in the file that it needs to decrypt it.  That's why the error message in the log says that the book "is neither an Adobe Adept nor a Barnes & Noble encrypted" epub.  I don't know of any workaround for this.

**Comment by Aliakbari089** [comment]
Thanks for replying me, But I appreciate if any one can help me. 
If you want ACSM file to test please let me know :)

**Comment by ElleKayEm** [comment]
Since you have downloaded the epub, that acsm file will only work with your Adobe ID.

The only other suggestion I have is trying the [ACSM Input plugin](https://www.mobileread.com/forums/showthread.php?t=341975) and [noDRM's DeDRM](https://github.com/noDRM/DeDRM_tools/releases).

**Comment by Aliakbari089** [comment]
If you need new acsm file please let me know to provide you

**Comment by ElleKayEm** [comment]
I would think it would still be tied to your account.  What ebookstore is this?

**Comment by blownscarerow** [comment]
> 

hi,would you like to try proquest ebooks?it seems to be the same

**Comment by ElleKayEm** [comment]
Yes, ProQuest seems to have gone to hardened Adobe DRM.  Since that's a library service, not really an issue.

**Comment by blownscarerow** [comment]
> Yes, ProQuest seems to have gone to hardened Adobe DRM. Since that's a library service, not really an issue.
So, is there any decryption method for the  book？

**Comment by blownscarerow** [comment]
> Yes, ProQuest seems to have gone to hardened Adobe DRM. Since that's a library service, not really an issue.

So, is there any decryption method for the book?
In the past, DRM encrypted data could be removed by the plug.

**Comment by ElleKayEm** [comment]
I don't know what exactly is going on with the book in the op here.  Since it can be read with Adobe 2.0.1, it must not be the hardened DRM.  But DeDRM isn't able to find the info in the file it needs to decrypt it.

ProQuest does seem to have switched from the older Adobe DRM which these tools can decrypt to the newer hardened Adobe DRM which has not been figured out yet.

**Comment by blownscarerow** [comment]
> I don't know what exactly is going on with the book in the op here. Since it can be read with Adobe 2.0.1, it must not be the hardened DRM. But DeDRM isn't able to find the info in the file it needs to decrypt it.
> 
> ProQuest does seem to have switched from the older Adobe DRM which these tools can decrypt to the newer hardened Adobe DRM which has not been figured out yet.

Thank you very much for your answer. I'm sorry for mixing the two. If you have time, please update the decryption of the new version of PQ. We will be very grateful
