### ISSUE TITLE
Error converting EPUB to Mobi

### ISSUE THREAD

**Issue by jaimealves** [apprenticeharper/DeDRM_tools#1991]
calibre, version 5.32.0
ERROR: Loading book failed: Failed to open the book at C:\Users\jaime\Calibre Library\Ronaldo Pilati\Ciencia e pseudociencia (6)\Ciencia e pseudociencia - Ronaldo Pilati.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\jaime\Calibre Library\Ronaldo Pilati\Ciencia e pseudociencia (6)\Ciencia e pseudociencia - Ronaldo Pilati.epub with error:
DeDRM v7.2.1: Trying to decrypt Ciencia e pseudociencia - Ronaldo Pilati.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Ciencia e pseudociencia - Ronaldo Pilati.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\jaime\Calibre Library\Ronaldo Pilati\Ciencia e pseudociencia (6)\Ciencia e pseudociencia - Ronaldo Pilati.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 791, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 244, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
calibre.ebooks.DRMError: Ciencia e pseudociencia - Ronaldo Pilati.epub
Exception ignored in: <function NativeFunction.__del__ at 0x07DFFC40>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07DFFC40>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
Looks like Adobe Digital Editions is not activated with an Adobe ID.

**Comment by jaimealves** [comment]
Thanls, i will check it!

**Comment by kaizensidi** [comment]
Hello I seam to have the same problem? How do I remove de Adabe Id?

Boek 1 van 1 (The 7 Habits of Highly Effective People) converteren
Conversion options changed from defaults:
  output_profile: 'cybookg3'
  verbose: 2
  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_imx9bjc0\\x0crtth7.opf'
Resolved conversion options
calibre version: 5.40.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'force_max_line_length': False,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'inline_toc': False,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07BEAF88>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_color': False,
 'keep_image_references': False,
 'keep_ligatures': False,
 'keep_links': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_line_length': 0,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'newline': 'system',
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.CybookG3Output object at 0x07BEF0E8>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_imx9bjc0\\x0crtth7.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'txt_output_encoding': 'utf-8',
 'txt_output_formatting': 'plain',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\Dell\AppData\Local\Temp\calibre_imx9bjc0\4_aw46pr.epub
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
calibre.ebooks.DRMError: 4_aw46pr.epub

**Comment by ElleKayEm** [comment]
This is how to get a log:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
