### ISSUE TITLE
Cannot remove DRM

### ISSUE THREAD

**Issue by regabrio5** [apprenticeharper/DeDRM_tools#1994]
Hi,

Cannot remove DRM from AZW book downloaded from Amazon store.

Calibre 4.23
KFX 1.46.0
DeDRM 6.8.1
Mac OS 12.1

Debug log:

"calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.08] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing /Users/macbook_sk/Desktop/My Kindle Content/B07L5TW59R_EBOK/B07L5TW59R_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as /var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_Tzfzaf/Xbmieh.kfx-zip
DeDRM v6.8.0: Trying to decrypt Xbmieh.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: Xbmieh
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5db6c215-9db7-4a8c-9f93-f1c9b068e85a.voucher
DeDRM v6.8.0: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/macbook_sk/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Decrypted key file using IDString '091997cc631a' and UserName 'macbook_sk'
DeDRM v6.8.0: Found 1 new key
Decrypting KFX-ZIP ebook: Xbmieh
Got DSN key from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5db6c215-9db7-4a8c-9f93-f1c9b068e85a.voucher
DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.46.0: Packaging /var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_Tzfzaf/Xbmieh.kfx-zip
Processing container: B07L5TW59R_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
KFXDRMError: Book container B07L5TW59R_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_Tzfzaf/dgaDI7_add_books/0/B07L5TW59R_EBOK.kfx-zip
[3.54] splash screen hidden
[3.55] Started up in 3.55 seconds with 0 books
qt.qpa.fonts: Populating font family aliases took 565 ms. Replace uses of missing font family "AppleSystemUIFontItalic" with one that exists to avoid this cost."

**Comment by ElleKayEm** [comment]
What version of Kindle for Mac are you using?  Anything later than 1.26 and you won't be able to decrypt KFX format books like this.  I recommend disabling KFX downloads.  See method 2 in this post:  https://www.mobileread.com/forums/showthread.php?t=283371

And Mac specific info here:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by regabrio5** [comment]
Hi EKE,

I've downgraded to 1.26.1 Kindle for Mac and run the terminal command in method 2, same error.
I've also tried the sudo command.

In the "notes" on the last post there is a line: _If Calibre 5.x isn't working, make sure you're using tools v10.0.2 or newer._

How do I check that?

Many thanks

**Comment by regabrio5** [comment]
Here's the latest debug report from calibre:

qt.qpa.fonts: Populating font family aliases took 551 ms. Replace uses of missing font family "AppleSystemUIFontItalic" with one that exists to avoid this cost. 
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.08] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.87] main UI initialized...
[1.87] Hiding splash screen
[10.72] splash screen hidden
[10.72] Started up in 10.72 seconds with 1 books
Worker Launch took: 0.557199001312
Job: 0 Convert book 1 of 1 (The Girl Who Dated Herself) finished
Convert book 1 of 1 (The Girl Who Dated Herself)
	Conversion options changed from defaults:
	  prefer_metadata_cover: True
	  cover: u'/var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/B0r0Me.jpeg'
	  verbose: 2
	  output_profile: u'generic_eink'
	  read_metadata_from_opf: u'/var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/lbCsEF.opf'
	Resolved conversion options
	calibre version: 4.23.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/B0r0Me.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10cab4510>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10cab4910>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': True,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/lbCsEF.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on /var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/kdVZBi.kfx-zip
	Software versions: KFX Input 1.46.0, calibre 4.23, Darwin-21.2.0-x86_64-i386-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/bq/wypmb7tj0tz1tf4z06pcdg6h0000gn/C/calibre_4.23.0_tmp_7xkZS6/kdVZBi.kfx-zip
	Processing container: B07L5TW59R_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
	KFXDRMError: Book container B07L5TW59R_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM!
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by regabrio5** [comment]
Here's a grab of what plug-ins I have installed:
<img width="924" alt="Screen Shot 2022-01-18 at 15 46 49" src="https://user-images.githubusercontent.com/97916081/149970470-b57fc312-628e-4275-812d-24d054303b9e.png">

**Comment by ElleKayEm** [comment]
Your last log doesn't show DeDRM working at all.  Did you have it disabled?

> In the "notes" on the last post there is a line: If Calibre 5.x isn't working, make sure you're using tools v10.0.2 or newer.

How do I check that?

Log shows that you're using calibre 4.23 and 6.8.x.  This should be fine, but you can try calibre 5.x and DeDRM 10.0.2 if you want.
