### ISSUE TITLE
Can't remove DRM

### ISSUE THREAD

**Issue by KJPfeil25** [apprenticeharper/DeDRM_tools#1997]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
Can't remove DRM from Kindle files

## Log
calibre Registro de depuración

```log
calibre Registro de depuración
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
calibre 5.9 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.33] splash screen shown
[1.33] Initializing db...
[1.33] db initialized
[1.33] Constructing main UI...
[2.77] main UI initialized...
[2.77] Hiding splash screen
Starting QuickView
[37.06] splash screen hidden
[37.08] Started up in 37.08 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x9c\x01b\xf7H\x9a\xd9u\x9a\xb7\xc0\xd3 \x07(\xea\xe5\x8e\xa9\xeb\x0f\x85\x8e;\xe1\xbe\x94\x02\x94\x82\xa4\x94', b'C:\\Users\\Portal-Center\\OneDrive\\Documents\\My Kindle Content\\B08TSZFWBT_EBOK\\B08TSZFWBT_EBOK.azw', b'C:\\Users\\Portal-Center\\OneDrive\\Documents\\My Kindle Content\\B08TSZFWBT_EBOK\\CR!FYKBZ08M5X6FX28M57MZWD9CFRG2.azw.md']
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing C:\Users\Portal-Center\OneDrive\Documents\My Kindle Content\B08TSZFWBT_EBOK\B08TSZFWBT_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\97vc749b.kfx-zip
DeDRM v7.2.1: Trying to decrypt 97vc749b.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 97vc749b
Got DSN key from database default_key
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.24cb3e76-5945-4647-a3c2-e51650cd8cbf.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 879, in decryptvoucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 879, in decryptvoucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Portal-Center\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Portal-Center\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '774859244' and UserName 'Portal-Center'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 97vc749b
Got DSN key from database default_key_1
Found 1 keys to try after 7.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.24cb3e76-5945-4647-a3c2-e51650cd8cbf.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 879, in decryptvoucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 879, in decryptvoucher
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\0a4z4tfqplugin_unzip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 7.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.46.0: Packaging C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\97vc749b.kfx-zip
Processing container: B08TSZFWBT_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\PORTAL~1\AppData\Local\Temp\calibre_w2hcnpb2\aw8f_7l2_add_books\0\B08TSZFWBT_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 7.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book conAdded CR!FYKBZ08M5X6FX28M57MZWD9CFRG2.azw to db in: 2.8
Added Ready Player Two (Spanish Edition) to db in: 2.4
Added 2 books in 14.0 seconds

```
</details>

**Comment by ElleKayEm** [comment]
KFX format from Kindle for PC 1.31 can't be decrypted.  Either go back to at least Kindle for PC 1.26 or disable KFX format downloads.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371
