### ISSUE TITLE
Recent Failures - Unable to DeDRM PDF Files from ADE

### ISSUE THREAD

**Issue by edmc774** [apprenticeharper/DeDRM_tools#1998]
Environment:
macOS Monterey 12.1
Calibre 5.34
ADE Version 4.5.11.187606

calibre Debug log
calibre 5.34  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
calibre 5.34  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.2.0', 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1) && Quality Check (1, 11, 4)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 81.00000121649796 x 82.00000123151646
Using calibre Qt style: False
[0.00] Starting up...
[0.03] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.32] db initialized
[0.32] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[5.44] main UI initialized...
[5.44] Hiding splash screen
Starting QuickView
libpng warning: iCCP: known incorrect sRGB profile
DeDRM v7.2.1: Trying to decrypt Lean but Agile-1.pdf
DeDRM v7.2.1: Lean but Agile-1.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
    return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)
  File "Crypto/Cipher/PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
    doc.initialize(userkey)
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
    return self.initialize_ebx(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
    return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)
  File "Crypto/Cipher/PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 318, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[20.03] splash screen hidden
[20.03] Started up in 20.03 seconds with 1150 books
Added Lean but Agile-1 to db in: 0.0
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
I believe this is a book with the hardened Adobe DRM which cannot be decrypted.

**Comment by kokowang8910** [comment]
experiencing the same case.
