### ISSUE TITLE
As others : Cannot remove DRM from Amazon file

### ISSUE THREAD

**Issue by KfGroebe** [apprenticeharper/DeDRM_tools#2008]
Hello List :

1. Downloaded the book B09QL27RNS_EBOK.azw from Amazon 
2. Book installs in Calibre (with filename as title) but does not open.
3. Trying to open it in Calibre's eBook viewer returns error: book could not be loaded.

Seems that DRM was not removed and that book was placed "as is" (with DRM) in Calibre's list.

I would greatly appreciate any help. Thank you so much in advance.
Best Regards 
Karlfried Groebe

My system:
Windows 10 Pro Build: 19042.1466
Calibre 5.35
DeDrm tool 7.2.1
Kindle for PC 1.34.1 (63103)
Book source Amazon.de

Error details from Calibre's eBook viewer:
calibre, version 5.35.0
FEHLER: Buch konnte nicht geladen werden: Buch konnte nicht geöffnet werden: C:\Users\KfG\Documents\My Calibre Library\Unbekannt\B09QL27RNS EBOK (13)\B09QL27RNS EBOK - Unbekannt.azw. "Details anzeigen" anklicken für weitere Informationen.

Failed to convert book: C:\Users\KfG\Documents\My Calibre Library\Unbekannt\B09QL27RNS EBOK (13)\B09QL27RNS EBOK - Unbekannt.azw with error:
DeDRM v7.2.1: Trying to decrypt B09QL27RNS EBOK - Unbekannt.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\KfG\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\KfG\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4264391275' and UserName 'KfG'
DeDRM v7.2.1: Ultimately failed to decrypt after 8.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\KfG\Documents\My Calibre Library\Unbekannt\B09QL27RNS EBOK (13)\B09QL27RNS EBOK - Unbekannt.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 257, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 503, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 8.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 27, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 89, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: Dies ist ein Amazon KFX-Buch. Es kann nicht verarbeitet werden. Weitere Informationen zum Umgang mit KFX-Büchern finden Sie unter https://www.mobileread.com/forums/showthread.php?t=283371.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 791, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 33, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 89, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: Dies ist ein Amazon KFX-Buch. Es kann nicht verarbeitet werden. Weitere Informationen zum Umgang mit KFX-Büchern finden Sie unter https://www.mobileread.com/forums/showthread.php?t=283371.

Error log after closing Calibre:
calibre Fehlerdiagnoseprotokoll
calibre 5.35  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.35  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 69.96843615494979 x 69.9795918367347
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.03] splash screen shown
[1.03] Initializing db...
[1.05] db initialized
[1.06] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.19] main UI initialized...
[2.19] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B09QL27RNS_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\KfG\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\KfG\AppData\Local\Amazon\Kindle\storage\.kinf2018
[8.81] splash screen hidden
[8.81] Started up in 8.81 seconds with 1 books
Decrypted key file using IDString '4264391275' and UserName 'KfG'
DeDRM v7.2.1: Ultimately failed to decrypt after 7.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 7.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 257, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 503, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\xAdded B09QL27RNS EBOK to db in: 0.1
Added 1 books in 8.4 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment]
You'll need to either disable KFX format downloads or go back to at least Kindle for PC 1.26.  See this post for details:  https://www.mobileread.com/forums/showthread.php?t=283371
