### ISSUE TITLE
Amazon ebook dont open by Calibre in Mac

### ISSUE THREAD

**Issue by Julosu71** [apprenticeharper/DeDRM_tools#2011]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre Registro de depuración
calibre 3.42  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0) && Kindle Collections (1, 7, 23) && Find Duplicates (1, 6, 3)
calibre 3.42  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0) && Kindle Collections (1, 7, 23) && Find Duplicates (1, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.71] db initialized
[0.71] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: ManyBooks at version: 2
Loaded cached store plugin for: LitRes at version: 2
Loaded cached store plugin for: Google Books at version: 6
Loaded cached store plugin for: Virtualo at version: 10
Loaded cached store plugin for: Project Gutenberg at version: 6
Loaded cached store plugin for: Legimi at version: 10
Loaded cached store plugin for: XinXii at version: 2
Loaded cached store plugin for: Empik at version: 9
Loaded cached store plugin for: Amazon Kindle at version: 17
Loaded cached store plugin for: Świat Ebooków at version: 2
Loaded cached store plugin for: Woblink at version: 15
[2.75] main UI initialized...
[2.75] Hiding splash screen
[2.80] splash screen hidden
[2.80] Started up in 2.80 seconds with 12403 books
objc[22254]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffadcb6cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12faf4cd8). One of the two will be used. Which one is undefined.
DeDRM v6.8.0: Trying to decrypt Cracking Economics.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cracking Economics
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/macbook/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Decrypted key file using IDString 'e997d02432f0' and UserName 'macbook'
DeDRM v6.8.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Cracking Economics
Got DSN key from database default_key_1
Found 4 keys to try after 1.6 seconds
Crypto Type is: 2
DeDRM v6.8.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
2022-02-07 11:12:34.175 Calibre[22291:16870551] deliverNotificationWithTitle()
* Notification delivered.
Added Cracking Economics to db in: 2.0
Added 1 books in 4.1 seconds
Worker Launch took: 0.171142101288
Worker Launch took: 0.29107093811
Job: 1 Convertido el libro 1 de 1 (Cracking Economics) finished
Convertido el libro 1 de 1 (Cracking Economics)
	Conversion options changed from defaults:
	  cover: u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/bk2Hua.jpeg'
	  verbose: 2
	  output_profile: 'ipad'
	  read_metadata_from_opf: u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/4t_XTO.opf'
	Resolved conversion options
	calibre version: 3.42.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/bk2Hua.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10a94ed10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPadOutput object at 0x10a9592d0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/4t_XTO.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/FasS5T.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly: Cracking Economics
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_p2022-02-07 11:12:53.958 Calibre[22300:16870764] deliverNotificationWithTitle()
* Notification delivered.
oint
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1107, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 46, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 87, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Cracking Economics

Worker Launch took: 0.314080953598
Job: 2 Convertido el libro 1 de 1 (Cracking Economics) finished
Convertido el libro 1 de 1 (Cracking Economics)
	Conversion options changed from defaults:
	  cover: u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/1CEAMk.jpeg'
	  verbose: 2
	  output_profile: 'ipad'
	  read_metadata_from_opf: u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/U_n1DY.opf'
	Resolved conversion options
	calibre version: 3.42.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/1CEAMk.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x116a11d10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPadOutput object at 0x116a182d0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/1v/prdhxz153991bphtm19mjnw40000gn/C/calibre_3.42.0_tmp_Ac7Aj1/U_n1DY.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold':
```
</details>

**Comment by ElleKayEm** [comment]
If this book is from or downloaded for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.
