### ISSUE TITLE
Amazon azw3 DRM removal doesn't work for Kindle Signature Edition downloads

### ISSUE THREAD

**Issue by hanginwithdaddo** [apprenticeharper/DeDRM_tools#2012]
## CheckList

- [ x] `The Title` and The `Log Title` are set correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Amazon azw3 DRM removal doesn't work for Kindle Signature Edition downloads
Trying to remove DRM from an Amazon azw3 file downloaded for a Kindle Signature Edition device does fails to find matching PID, even though the device's serial number is recorded correctly in the plugin. Note that the serial number starts with a "G", not a "B" or "9". DRM removal works fine when downloading the same book for my Kindle Touch, whose serial number starts with a "B". I have included logs from both conversions. 

## Log
<details><summary>Kindle Signature Edition Conversion Log</summary>

```log
calibre Debug log
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Will (1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Will
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\daddo\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[40.58] splash screen hidden
[40.58] Started up in 40.58 seconds with 353 books
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded Will to db in: 0.7
Added 1 books in 2.9 seconds

```
</details>

## Log
<details><summary>Kindle Touch Conversion Log</summary>

```log
calibre Debug log
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
calibre 5.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[0.83] main UI initialized...
[0.83] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Will.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Will
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID wMPuBoyYWJ.
Decrypting. Please wait . . . . . done
Decryption succeeded after 0.1 seconds
DeDRM v7.2.1: Finished after 0.1 seconds
[2.62] splash screen hidden
[2.62] Started up in 2.62 seconds withAdded Will to db in: 0.5
Added 1 books in 2.3 seconds

```
</details>

**Comment by ElleKayEm** [comment]
Hmm, I wonder if it is like the Fires where the key isn't based on the serial number.  Just to double check... you're sure you choose the Signature Edition when downloading the file?  And you're sure its serial number is entered correctly?

**Comment by hanginwithdaddo** [comment]
Yes to both questions.

**Comment by hanginwithdaddo** [comment]
Update... Well, originally I had copied/pasted the serial number from my Amazon account's device list. I just redid this again, retried the conversion, and now it WORKS! I have no idea why. Please ignore this post. I've closed it.

**Comment by ElleKayEm** [comment]
Well, that's good news.  Thanks for reporting back.
