### ISSUE TITLE
Adobe Digital Editions DRM removal failed

### ISSUE THREAD

**Issue by SquareRecord902** [apprenticeharper/DeDRM_tools#2014]
Debug Log below
Calibre updated today (Feb. 14, 2022) to latest
DeDRM updated today to 7.2.1
Surface Pro 5, Windows 10, latest update
Adobe Digital Editions PDF from university library via ProQuest Ebook Central
Opened the book in ADE reader, latest update, then decided I wanted to strip DRM

**calibre Debug log**
calibre 5.36  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
calibre 5.36  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.6430769230769 x 133.90057803468207
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.78] splash screen shown
[1.78] Initializing db...
[1.78] db initialized
[1.78] Constructing main UI...
[2.91] main UI initialized...
[2.91] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Ars Vitae.pdf
DeDRM v7.2.1: Ars Vitae.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
[35.22] splash screen hidden
[35.22] Started up in 35.22 seconds with 24 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd1\xdb\xadu\xaen\xb9\x96FW\xe5\x8b\x0e\xb4\xa5TO\\X\x97t2!U1\\\xcb\x12\n\xd61\xaf', b'C:\\Users\\JR Surface Pro\\OneDrive\\Documents\\My Digital Editions\\Ars Vitae.pdf']
DeDRM v7.2.1: Exception when decrypting after 0.5 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.5 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 315, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x07D57070>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07D57070>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneTAdded Ars Vitae to db in: 0.1
Added 1 books in 1.8 seconds

**Comment by ElleKayEm** [comment]
ProQuest has switched to the hardened Adobe DRM which cannot be removed (yet).

**Comment by SquareRecord902** [comment]
Ah. Thanks.

**Comment by tvphanatic** [comment]
Take a look at [https://github.com/noDRM/DeDRM_tools/pull/48](url) for an update that can decrypt the newer ProQuest files (I tested on two ebooks and it worked).

**Comment by Kiri68** [comment]
> Take a look at [https://github.com/noDRM/DeDRM_tools/pull/48](url) for an update that can decrypt the newer ProQuest files (I tested on two ebooks and it worked).

This link shows no content, can you send me a copy?

**Comment by ElleKayEm** [comment]
Copy and paste the link text.  (Clicking takes you to this repo instead of noDRM's.)

**Comment by Kiri68** [comment]
> Copy and paste the link text. (Clicking takes you to this repo instead of noDRM's.)

thanks！
