### ISSUE TITLE
¿How can I fix this issue? Imported ebooks still have DRM 

### ISSUE THREAD

**Issue by ProfGuille** [apprenticeharper/DeDRM_tools#2018]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.
<x!-- If you don't know the version, please specify 'Unknown'. -->

---

## Title
imported ebooks still have DRM
## My Environment
Windows 10 on Aqemu (Debian 11)
### Calibre: `Version`
Version: Calibre 5.36
### DeDRM: `Version`
 DeDRM (7, 2, 1)
## Log
<details><summary>Log Title</summary>
Calibre Debuggin info/summary

```log
calibre Registro de depuración
calibre 5.36  embedded-python: True is64bit: False
Windows-10-10.0.17763 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 3.8.5
Windows: ('10', '10.0.17763', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.36  embedded-python: True is64bit: False
Windows-10-10.0.17763 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 3.8.5
Windows: ('10', '10.0.17763', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.03692307692307 x 100.03692307692307
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.34] main UI initialized...
[1.34] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt el aire acondicionado en los autos (Spanish Edition).azw
Using Library AlfCrypto DLL/DYLIB/SO
[45.95] splash screen hidden
[45.95] Started up in 45.95 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xa12/Z]e\xbb\x94\xe0\xc5\x80CPC\xaa\xc9[\xcb^e\x91\xfc,\x87'_\xc0\xe8@\x83 \x80", b'C:\\Users\\bauch\\Downloads\\el aire acondicionado en los autos (Spanish Edition).azw']
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: el aire acondicionado en los autos (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\bauch\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masAdded el aire acondicionado en los autos (Spanish Edition) to db in: 0.2
Added 1 books in 1.6 seconds
Worker Launch took: 0.00 seconds

```
</details>

**Comment by ElleKayEm** [comment]
If this is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.

**Comment by ProfGuille** [comment]
> If this is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.
Hello, ¡thanks for your answer!
Well, I have one that is Kindle 2.5.8. But I have also books in my pc.  
¿How can I enter the serial number into DeDRM's customization? ¿Can you guide me? 
Thank you

**Comment by ElleKayEm** [comment]
In calibre go to Preferences > Plugins.  Select the DeDRM plugin under File Type plugins.  Then click Customize plugin > eInk Kindle ebooks > green plus sign.  Best to copy and paste the serial number from your content & devices page at Amazon.  Click ok and apply out of the dialog boxes and restart calibre before trying to add your book again.

**Comment by ProfGuille** [comment]
> In calibre go to Preferences > Plugins. Select the DeDRM plugin under File Type plugins. Then click Customize plugin > eInk Kindle ebooks > green plus sign. Best to copy and paste the serial number from your content & devices page at Amazon. Click ok and apply out of the dialog boxes and restart calibre before trying to add your book again.

I followed your instructions but it doesn't work... just DRM persists... ¿Any option?

**Comment by ElleKayEm** [comment]
Make sure you have chosen that Kindle if you are downloading the book from the website.  Make sure you have the serial number entered correctly.  Delete and add a fresh copy of the book to calibre.

**Comment by ProfGuille** [comment]
> Make sure you have chosen that Kindle if you are downloading the book from the website. Make sure you have the serial number entered correctly. Delete and add a fresh copy of the book to calibre.

I have a copy on my pc and still not work...

**Comment by ElleKayEm** [comment]
Let's see another log.

**Comment by ProfGuille** [comment]
> Let's see another log.

Just frustrated about.

**Comment by ElleKayEm** [comment]
Show me a new log and I'll take look.  Should work.
