### ISSUE TITLE
Ddrm not working in Calibre

### ISSUE THREAD

**Issue by lovetoride-hub** [apprenticeharper/DeDRM_tools#2019]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

### DeDRM: `6.8.0`
Book purchased from Amazon

calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-21.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 107.500001614
Using calibre Qt style: True
[0.00] Starting up...
[0.12] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.12] main UI initialized...
[1.12] Hiding splash screen
DeDRM v6.8.0: Trying to decrypt Wish You Were Here.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Wish You Were Here
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.8.0: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.8.0: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 626, in run
  File "calibre_plugins.dedrm.__init__", line 576, in KindleMobiDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[7.02] splash screen hidden
[7.02] Started up in 7.02 seconds with 1 books
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x103878f90>
Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 201, in do_connect
  File "site-packages/calibre/devices/usbms/device.py", line 827, in open
  File "site-packages/calibre/devices/usbms/device.py", line 396, in open_osx
  File "site-packages/calibre/devices/usbms/device.py", line 386, in osx_bsd_names
  File "site-packages/calibre/devices/usbms/device.py", line 346, in _osx_bsd_names
DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Added Wish You Were Here to db in: 0.0
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.
