### ISSUE TITLE
DRM tool not working for kindle books in macOS Monterey ver 12.2.1

### ISSUE THREAD

**Issue by snorry8090** [apprenticeharper/DeDRM_tools#2024]
calibre Debug log
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && KindleUnpack - The Plugin (0, 82, 1) && Obok DeDRM (6, 5, 4)
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 33, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 33, 0) && KFX metadata reader (from KFX Input) (1, 33, 0) && KFX Input (1, 33, 0) && KindleUnpack - The Plugin (0, 82, 1) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.16] main UI initialized...
[1.16] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.33.0: Importing /Users/evakong/Library/Application Support/Kindle/My Kindle Content/B09SQD8ZBG_EBOK/B09SQD8ZBG_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as /var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/xqmy10vr.kfx-zip
DeDRM v7.2.1: Trying to decrypt xqmy10vr.kfx-zip
Using Library AlfCrypto Python
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: xqmy10vr
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdc380f8-0e0e-4f5f-ab89-861410f1823f.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 759, in pkcs7unpad
    _assert(msg[-paddinglen:] == bchr(paddinglen) * paddinglen, "Incorrect padding - Wrong key")
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/evakong/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'evakong'  on file  /Users/evakong/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'292035521910'
Decrypted key file using IDString '292035521910' and UserName 'evakong'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: xqmy10vr
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.cdc380f8-0e0e-4f5f-ab89-861410f1823f.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 759, in pkcs7unpad
    _assert(msg[-paddinglen:] == bchr(paddinglen) * paddinglen, "Incorrect padding - Wrong key")
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/v0geqqjbplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.33.0: Packaging /var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/xqmy10vr.kfx-zip
Processing container: B09SQD8ZBG_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/27/hlfpk70n59j2qj5fzlbv3z800000gn/C/calibre_5.37.0_tmp_1tmsk6cd/nriig6p6_add_books/0/B09SQD8ZBG_EBOK.kfx-zip
Import symbol table YJ_symbols version 10 max_id 816 exceeds known table size 777
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
    kfx_data = YJ_Book(path_to_ebook, log).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 184, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 291, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09SQD8ZBG_EBOK.azw has DRM and cannot be converted
[6.21] splash screen hidden
[6.21] Started up in 6.21 seconds with 272 books
Added Her Bikers: A Reverse Harem & Age Gap MC Short Story to db in: 0.0
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
See this post: https://www.mobileread.com/forums/showthread.php?t=283371

And this:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

Also suggest switching to DeDRM 10.0.2:  https://github.com/noDRM/DeDRM_tools

**Comment by snorry8090** [comment]
Issue resolved. I updated DRM tools, deleted my Kindle and installed Kindle 1.31.0, ran the sudo chmod script from https://www.mobileread.com/forums/showthread.php?t=283371 and redownloaded the books I wanted to convert to epub.

It worked after all the above.

Thank you, @ElleKayEm ! I followed all the steps in the posts you linked and it worked like a charm :)

**Comment by snorry8090** [comment]
Thank you, @ElleKayEm ! I followed all the steps in the posts you linked and it worked like a charm :)
