### ISSUE TITLE
Calibre does not open a PDF book

### ISSUE THREAD

**Issue by ivanbez** [apprenticeharper/DeDRM_tools#2027]
Hi,

Mac OS 12.2.1

Calibre: 5.37`

DeDRM: 7.2.1

Book in pdf format dowloaded for road, as usual 15 days

Thanks

calibre Log di debug
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Set KFX metadata (from KFX Output) (1, 59, 0) && KFX Output (1, 59, 0)
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Set KFX metadata (from KFX Output) (1, 59, 0) && KFX Output (1, 59, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000162950651 x 107.50000161448803
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.04] main UI initialized...
[1.04] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Manuale di catalogazione.pdf
DeDRM v7.2.1: Manuale di catalogazione.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 315, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[11.09] splash screen hidden
[11.09] Started up in 11.09 seconds with 4119 books

{'bsd_drives': {'main': '/dev/disk3'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk2s1': '/System/Volumes/Data',
               '/dev/disk2s2': '/System/Volumes/Preboot',
               '/dev/disk2s4': '/System/Volumes/VM',
               '/dev/disk2s5s1': '/',
               '/dev/disk2s6': '/System/Volumes/Update',
               '/dev/disk3': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Recupera informazioni sul dispositivo started
DeviceJob: 0 Recupera informazioni sul dispositivo done, calling callback
DeviceJob: 0 Recupera informazioni sul dispositivo callback returned
Job: 1 Imposta informazioni sulla biblioteca started
DeviceJob: 1 Imposta informazioni sulla biblioteca done, calling callback
DeviceJob: 1 Imposta informazioni sulla biblioteca callback returned
Job: 2 Recupera la lista dei libri del dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 98, count of files in metadata: 98, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Recupera la lista dei libri del dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 98
DeviceJob: set_books_in_library finished: time= 0.004215240478515625
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Recupera la lista dei libri del dispositivo callback returned
Job: 0 Recupera informazioni sul dispositivo finished
Nessun dettaglio disponibile.
Job: 2 Recupera la lista dei libri del dispositivo finished
Nessun dettaglio disponibile.
Job: 1 Imposta informazioni sulla biblioteca finished
Nessun dettaglio disponibile.
Added Manuale di catalogazione to db in: 0.0
Added 1 books in 0.5 seconds
[tmpe6ph25ix.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8167933/tmpe6ph25ix.txt)

**Comment by noDRM** [comment]
PDF support in Calibre 5 is broken with this version of the plugin. Either try Calibre 4 and and version ~6.2.0~ _6.8.1_ of this plugin, or try switching to my forked version which has this bug fixed: https://github.com/noDRM/DeDRM_tools/

**Comment by ElleKayEm** [comment]
You'd want the last python 2 versions:  calibre 4.23 and DeDRM 6.8.1.  But better still to try noDRM's DeDRM plugin and just stay with calibre 5.
