### ISSUE TITLE
Cannot de-drm Nook book (PDF) with key

### ISSUE THREAD

**Issue by digitalfreaknyc** [apprenticeharper/DeDRM_tools#2029]
Just bought another Nook book today and it cannot be opened.  It's a PDF instead of an epub.  My key is still the same - hasn't changed. Other epub's that have worked in the past no longer work either.  

Here's the log from the latest calibre:

`calibre Debug log
calibre 5.38 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 11, 2) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (7, 2, 1)
calibre 5.38 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Count Pages (1, 11, 2) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.06] main UI initialized...
[1.06] Started up in 1.06 seconds with 1206 books
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 9781454900955.pdf
DeDRM v7.2.1: 9781454900955.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Trying Encryption key default_key_2
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with key default_key_2 after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 165, in decrypt
ValueError: Ciphertext with incorrect length.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 315, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001AEB566B8B0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001AEB566B8B0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Added 9781454900955 to db in: 0.2
Added 1 books in 0.8 seconds`

**### Here's the log for the older version of calibre that has no problems with PDF's.**

calibre Debug log
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.02] main UI initialized...
[2.02] Hiding splash screen
[5.89] splash screen hidden
[5.91] Started up in 5.91 seconds with 6 books
DeDRM v6.8.0: Trying to decrypt 9781454900955.pdf
DeDRM v6.8.0: 9781454900955.pdf is a PDF ebook
DeDRM v6.8.0: Trying Encryption key default_key
DeDRM v6.8.0: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 428, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2183, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1989, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1474, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1606, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.8.0: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added 9781454900955 to db in: 0.3
Added 1 books in 1.0 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x05079D50>> ignored

**Comment by ElleKayEm** [comment]
This DeDRM plugin isn't able to handle B&N pdfs as is and development has ended at this repo.  There is a script included which I don't think was ever integrated into the plugin or completely updated to Python 3 here:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/ignoblepdf.py

More work has been done by noDRM, but they haven't had B&N pdfs to test with.  So try noDRM's DeDRM and post an issue there:  https://github.com/noDRM/DeDRM_tools

**Comment by digitalfreaknyc** [comment]
> This DeDRM plugin isn't able to handle B&N pdfs as is and development has ended at this repo. There is a script included which I don't think was ever integrated into the plugin or completely updated to Python 3 here: https://github.com/apprenticeharper/DeDRM_tools/blob/master/DeDRM_plugin/ignoblepdf.py
> 
> More work has been done by noDRM, but they haven't had B&N pdfs to test with. So try noDRM's DeDRM and post an issue there: https://github.com/noDRM/DeDRM_tools

Thank you for that info. 

However, that doesn't explain why it's not working on most epubs either.

**Comment by ElleKayEm** [comment]
Something more may have changed.  Again I'd check out noDRM's version and raise the issue over there where active development continues.

**Comment by digitalfreaknyc** [comment]
So there is no active development for Nook epubs  here?

**Comment by ElleKayEm** [comment]
No, the Apprentices have retired.  See the main page here: https://github.com/apprenticeharper/DeDRM_tools

**Comment by digitalfreaknyc** [comment]
I'm so sorry. I didn't realize. Thank you so much
