### ISSUE TITLE
[QUESTION] Ebook continues DRMed

### ISSUE THREAD

**Issue by tbernardes83** [apprenticeharper/DeDRM_tools#2031]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title

I followed the readme and I installed the DeDRM, but the ebook continues DRMed.

## Log
<details><summary>Log Title</summary>

```log
calibre Log de Debug
calibre 5.38  embedded-python: False is64bit: True
Linux-5.16.12-arch1-1-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.16.12-arch1-1', '#1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000')
Python 3.10.2
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
calibre 5.38  embedded-python: False is64bit: True
Linux-5.16.12-arch1-1-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.16.12-arch1-1', '#1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000')
Python 3.10.2
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.26805074971165 x 96.25263157894737
physicalDpi: 157.31612903225806 x 161.36470588235292
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.02] splash screen shown
[0.02] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[0.38] main UI initialized...
[0.38] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Familia Afeto Finanças - Como Colocar Cada Vez Mais Dinheiro e Amor em Seu Lar.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.38.0_tmp_tsavlxop/jy3jn5bzplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
[6.41] splash screen hidden
[6.43] Started up in 6.43 seconds with 7 books

Debugging DND event
text/uri-list 158 b'file:///home/tbernardes/Documents/Ebook/Familia%20Afeto%20Finan%C3%A7as%20-%20Como%20Colocar%20Cada%20Vez%20Mais%20Dinheiro%20e%20Amor%20em%20Seu%20Lar.azw3\r\n' 

text/plain 124 b'file:///home/tbernardes/Documents/Ebook/Familia Afeto Finan\xc3\xa7as - Como Colocar Cada Vez Mais Dinheiro e Amor em Seu Lar.azw3' 

application/x-kde4-urilist 158 b'file:///home/tbernardes/Documents/Ebook/Familia%20Afeto%20Finan%C3%A7as%20-%20Como%20Colocar%20Cada%20Vez%20Mais%20Dinheiro%20e%20Amor%20em%20Seu%20Lar.azw3\r\n' 


Firefox rurl: None None
URLS: ['file:///home/tbernardes/Documents/Ebook/Familia%20Afeto%20Finan%C3%A7as%20-%20Como%20Colocar%20Cada%20Vez%20Mais%20Dinheiro%20e%20Amor%20em%20Seu%20Lar.azw3']
Paths: ['/home/tbernardes/Documents/Ebook/Familia Afeto Finanças - Como Colocar Cada Vez Mais Dinheiro e Amor em Seu Lar.azw3']
Extensions: frozenset({'azw3'})
Added Familia Afeto Finanças - Como Colocar Cada Vez Mais Dinheiro e Amor em Seu Lar to db in: 0.1
Added 1 books in 0.4 seconds
[9876:7:0308/223522.343050:ERROR:command_buffer_proxy_impl.cc(141)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
Worker Launch took: 0.00 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Try the official Linux version of calibre:  https://calibre-ebook.com/download_linux

**Comment by ScanBcn** [comment]
> Try the official Linux version of calibre: https://calibre-ebook.com/download_linux

Works for me, thank you!
