### ISSUE TITLE
7.2.1 not removing drm from IBS ebook

### ISSUE THREAD

**Issue by Loob22** [apprenticeharper/DeDRM_tools#2033]
### Discussed in https://github.com/apprenticeharper/DeDRM_tools/discussions/2032

<div type='discussions-op-text'>

<sup>Originally posted by **Loob22** March  9, 2022</sup>
hi,
Lorenzo
windows 10
bought a ebook from IBS
the 7.2.1 version is not removing the drm
i used adobe to visualise the file before using the dedrm tool, if this can be a problem

log:
calibre Log di debug
calibre 5.38  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.38  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.7674418604651 x 141.4020618556701
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
[1.02] main UI initialized...
[1.02] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Meccatronica_Azionamenti_Elettrici_ed_Ol (1).pdf
DeDRM v7.2.1: Meccatronica_Azionamenti_Elettrici_ed_Ol (1).pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1460, in initialize
calibre_plugins.dedrm.ineptpdf.PDFEncryptionError: Document is not encrypted.
DeDRM v7.2.1: Failed to decrypt with new default key after 0.0 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Exception ignored in: <function NativeFunction.__del__ at 0x07F156A0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07F156A0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[7.72] splash screen hidden
[7.72] Started up in 7.72 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa8\x7fw\x14\xde\xc9\x12\x98\xa3\x9f\x8fR\x9b\xc7\x88\xd0Z\x0f\xaf\xc2\x13\\\xb0\x10 \x87odf\x04\x19Z', b'C:\\Users\\loreb\\Downloads\\Meccatronica_Azionamenti_Elettrici_ed_Ol (1).pdf']
Added () to db in: 0.1
Added 1 books in 0.6 seconds
</div>

**Comment by ElleKayEm** [comment]
Responded here: https://github.com/apprenticeharper/DeDRM_tools/discussions/2032#discussioncomment-2327046
