### ISSUE TITLE
[QUESTION] I can't decrypt a pdf with drm from adobe digital editions

### ISSUE THREAD

**Issue by bogettigian** [apprenticeharper/DeDRM_tools#2037]
## Log
<details><summary>Calibre log</summary>

```log
calibre Debug log
calibre 5.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.36363636363636 x 92.36363636363636
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[0.92] main UI initialized...
[0.92] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Química biológica.pdf
DeDRM v7.2.1: Química biológica.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 315, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001E908C00820>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001E908C00820>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[5.14] splash screen hidden
[5.14] Started up in 5.14 seconds with 9 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xf7\xdfz\xca\xde\x9a=\x17EkS\xc5]\xfe\x11\xed\x03P\xe0\xac\x14#\x9a]:\xd1\xaa\xef\xb7\x92\xd1\xda', b'C:\\Users\\Gian\\Documents\\My Digital Editions\\Qu\xc3\xadmica biol\xc3\xb3gica.pdf']
Added Química biológica to db in: 0.1
Added 1 books in 0.7 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Try noDRM's DeDRM:  https://github.com/noDRM/DeDRM_tools

**Comment by bogettigian** [comment]
Thanks, it worked!
