### ISSUE TITLE
Error with last Calibre

### ISSUE THREAD

**Issue by Anths2016** [apprenticeharper/DeDRM_tools#2039]
calibre, version 5.39.0
ERRORE: Eccezione non gestita: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 165)

calibre 5.39 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && Package KFX (from KFX Input) (1, 47, 0) && Find Duplicates (1, 9, 4) && Generate Cover (2, 1, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Set KFX metadata (from KFX Output) (1, 60, 0) && KFX Output (1, 60, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.__init__", line 165
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
Are you using either DeDRM version 7.2.1 or noDRM's 10.0.2?  Looks like you may be trying to load an earlier version.

**Comment by Anths2016** [comment]
You are right. It was a version that didn't works on Calibre 5.
