### ISSUE TITLE
Can't DeDRM PDF

### ISSUE THREAD

**Issue by thamychan** [apprenticeharper/DeDRM_tools#2041]
I have followed all the tutorials I could find and even looked for other softwares but I can't remove the DRM from PDFs. I did try the older Calibre with the older version of the tool. My ADE is the 2.x too. I can't even create a decrypt key out of it. 

I couldn't find the code to make this post pretty with the log and my versions of the software, I think I've fried my brain trying to solve this. But my ADE is the 2.0.1. I copied two logs below.

Below is a log of one of the times:

calibre Debug log
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
calibre 4.23 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Obok DeDRM (6, 7, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 85.1991614256 x 85.2985074627
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.94] main UI initialized...
[1.94] Hiding splash screen
[28.58] splash screen hidden
[28.58] Started up in 28.58 seconds with 1 books
DeDRM v6.8.0: Trying to decrypt Places.pdf
DeDRM v6.8.0: Places.pdf is a PDF ebook
DeDRM v6.8.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.8.0: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 453, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 379, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 359, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 507, in PDFDecrypt
DeDRMError: DeDRM v6.8.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added Places to db in: 0.1
Added 1 books in 0.6 seconds

------------
**Another time when I tried to use the key and the file from an older computer of mine:**

calibre Log de Debug
calibre 5.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 5.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 85.1991614255765 x 85.29850746268657
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.00] main UI initialized...
[1.00] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Places.pdf
DeDRM v7.2.1: Places.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 461, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 362, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 342, in CryptUnprotectData
calibre_plugins.dedrm.adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 315, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000002571778B040>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000002571778B040>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[5.66] splash screen hidden
[5.66] Started up in 5.66 seconds with 12 books
Added Places to db in: 0.1
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
Try noDRM's DeDRM: https://github.com/noDRM/DeDRM_tools

Make sure that ADE on the same machine and user as calibre with DeDRM is authorized with your Adobe ID and can read the book.

And use the latest 64-bit version of calibre (as you have in that 2nd log).

**Comment by thamychan** [comment]
I loaded noDRM's and still couldn't do it. I was trying with a different key because I can't generate a key for my own computer, but I had already tried without it, I just didn't want to spam with the logs of all the attempts.

Here is the log this time:

calibre Log de Debug
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (10, 0, 2) && Obok DeDRM (7, 2, 1)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: pt_BR
Successfully initialized third party plugins: DeDRM (10, 0, 2) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 85.1991614256 x 85.2985074627
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.48] main UI initialized...
[1.48] Hiding splash screen
[4.78] splash screen hidden
[4.78] Started up in 4.78 seconds with 12 books
DeDRM v10.0.2: Trying to decrypt Places.pdf
DeDRM v10.0.2: Places.pdf is a PDF ebook for UUID 047642e8-1bb5-4a49-a5f0-89cca9f27b04
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 0.9 seconds
DeDRM v10.0.2: Exception when getting default Adobe Key after 0.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 665, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 393, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 371, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
ImportError: No module named deacsm.libadobeAccount
DeDRM v10.0.2: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 895, in run
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
Added Places to db in: 0.1
Added 1 books in 1.6 seconds

I think this is the biggest problem. I'm using it all on the same computer so I think a key is not necessary, but I was looking at my older computer and it does generate a key there (but it's ADE 4 there, while here I installed ADE 2). 
![image](https://user-images.githubusercontent.com/102314066/159979780-e74255fe-199c-411d-a143-192e0bb75e98.png)

**Comment by ElleKayEm** [comment]
Try with latest calibre.  Is ADE 2 on this computer authorized with your Adobe ID?  And are you able to read the pdf with it?

Another thing to look at might be the ACSM Input plugin:  https://www.mobileread.com/forums/showthread.php?t=341975

**Comment by thamychan** [comment]
I had tried it with and without my Adobe account (the book opening normally in ADE all the times). But the ACSM Input worked, it finally found a key to use and now Calibre could remove the DRM. I'm not sure why it can't find a key on its own, but thank you so much! It's great to be able to read on my Kindle again!
