### ISSUE TITLE
Kindle for MAC and without Kindle Devices

### ISSUE THREAD

**Issue by Robotukas** [apprenticeharper/DeDRM_tools#2047]
Hi Team,

It is so sad that I can't use digital books for annotation anymore and study purposes. So I have to have a look at how I can make it work.
I tried your amazing tool but I think I am doing something wrong. I only Have the kindle app on Mac and I don't have any kindle devices.

Could you advise me is a way to do it?

Please see the calibre log below.

Thank you so much for any help.

> calibre Debug log
> calibre 5.40  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: en_GB
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (fr
[tmpfcs89iu7.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8403200/tmpfcs89iu7.txt)
om KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Set KFX metadata (from KFX Output) (1, 60, 0) && KFX Output (1, 60, 0)
> calibre 5.40  embedded-python: True is64bit: True
> macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000')
> Python 3.8.5
> OSX: ('10.16', ('', '', ''), 'x86_64')
> Interface language: en_GB
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && Set KFX metadata (from KFX Output) (1, 60, 0) && KFX Output (1, 60, 0)
> devicePixelRatio: 2.0
> logicalDpi: 72.0 x 72.0
> physicalDpi: 127.50000191485792 x 127.50000191485789
> Using calibre Qt style: True
> [0.00] Starting up...
> [0.01] Showing splash screen...
> [0.20] splash screen shown
> [0.20] Initializing db...
> [0.21] db initialized
> [0.21] Constructing main UI...
> [0.67] main UI initialized...
> [0.67] Hiding splash screen
> Starting QuickView
> Gather KFX-ZIP (from KFX Input) 1.47.0: Importing /Users/Robotukas/Documents/My Kindle/My Kindle Content/B00OYTAXYQ_EBOK/B00OYTAXYQ_EBOK.azw
> Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as /var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/xd2mnr2i.kfx-zip
> DeDRM v7.2.1: Trying to decrypt xd2mnr2i.kfx-zip
> Using Library AlfCrypto Python
> Using Library AlfCrypto Python
> Decrypting KFX-ZIP ebook: xd2mnr2i
> Found 0 keys to try after 0.1 seconds
> Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.fe92033d-76e6-46c4-a4e1-f87495e7aeb7.voucher
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
>     voucher.decryptvoucher()
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 879, in decryptvoucher
>     b = pkcs7unpad(b, 16)
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 758, in pkcs7unpad
>     _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 98, in _assert
>     raise Exception(msg)
> Exception: Incorrect padding - Wrong key
> DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
> DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
> Found k4Mac kinf2018 file: /Users/Robotukas/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
> trying username  b'Robotukas'  on file  /Users/Robotukas/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
> trying IDString: b'af37e95e4473'
> trying IDString: b'af37e95e4472'
> trying IDString: b'af37e95e447d'
> [4.85] splash screen hidden
> [4.85] Started up in 4.85 seconds with 1 books
> trying IDString: b'51712d3bcc4b'
> Decrypted key file using IDString '51712d3bcc4b' and UserName 'Robotukas'
> DeDRM v7.2.1: Found 1 new key
> Decrypting KFX-ZIP ebook: xd2mnr2i
> Got SerialNumber from database default_key_1
> Got UsernameHash from database default_key_1
> Found 1 keys to try after 1.5 seconds
> Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.fe92033d-76e6-46c4-a4e1-f87495e7aeb7.voucher
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
>     book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
>   File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
>     mb.processBook(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
>     self.decrypt_voucher(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
>     raise Exception("Failed to decrypt KFX DRM voucher with any key")
> Exception: Failed to decrypt KFX DRM voucher with any key
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
>     voucher.decryptvoucher()
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 879, in decryptvoucher
>     b = pkcs7unpad(b, 16)
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 758, in pkcs7unpad
>     _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 98, in _assert
>     raise Exception(msg)
> Exception: Incorrect padding - Wrong key
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
>     book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
>   File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
>     mb.processBook(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
>     self.decrypt_voucher(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
>     raise Exception("Failed to decrypt KFX DRM voucher with any key")
> Exception: Failed to decrypt KFX DRM voucher with any key
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
>     voucher.decryptvoucher()
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 879, in decryptvoucher
>     b = pkcs7unpad(b, 16)
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 758, in pkcs7unpad
>     _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
>   File "/var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/jm9csq0oplugin_unzip/ion.py", line 98, in _assert
>     raise Exception(msg)
> Exception: Incorrect padding - Wrong key
> DeDRM v7.2.1: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Package KFX (from KFX Input) 1.47.0: Packaging /var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/xd2mnr2i.kfx-zip
> Processing container: B00OYTAXYQ_EBOK.azw
> KFX metadata reader (from KFX Input) activated for /var/folders/h5/jj3lytw13gdc4frj9nfpqpj00000gn/C/calibre_5.40.0_tmp_1t34moav/a0bb6289_add_books/0/B00OYTAXYQ_EBOK.kfx-zip
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
>     book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
>   File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
>     mb.processBook(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
>     self.decrypt_voucher(totalpids)
>   File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
>     raise Exception("Failed to decrypt KFX DRM voucher with any key")
> Exception: Failed to decrypt KFX DRM voucher with any key
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 633, in run
>     decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
>   File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
>     raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
> calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Running file type plugin Package KFX (from KFX Input) failed with traceback:
> Traceback (most recent call last):
>   File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
>   File "calibre_plugins.kfx_input.package_filetype", line 21, in run
>     return self.run_kfx(path_to_ebook)
>   File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
>     kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
>   File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
>     self.decode_book()
>   File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
>     container = self.get_container(datafile)
>   File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
>     raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
> calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B00OYTAXYQ_EBOK.azw has DRM and cannot be converted
>

**Comment by ElleKayEm** [comment]
Recommend using DeDRM 10.0.2: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

And avoiding KFX format: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ZolaLa9** [comment]
Also, since you are on Mac, be sure to follow further instructions here: 
https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
