### ISSUE TITLE
DeDRM not working for an ebook pdf from McGraw Hill Professional

### ISSUE THREAD

**Issue by ttmysd70c6f5** [apprenticeharper/DeDRM_tools#2048]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## DeDRM not working for an ebook pdf from McGraw Hill Professional

I downloaded a ebook pdf bought from McGraw Hill Professional using Adobe Digital Editions. I tried to remove DRM from the pdf using DeDRM, but it was not converted properly. It would be appreciated if you could help me to solve the problem.

### Windows 10 Home
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor

## Log
<details><summary>Log</summary>

```log
calibre Debug log
calibre 5.40  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
calibre 5.40  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 166.4436860068259 x 169.33333333333334
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.39] splash screen shown
[0.39] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[0.83] main UI initialized...
[0.83] Hiding splash screen
Starting QuickView
DeDRM v7.1.0: Trying to decrypt Principles of Neural Science, Sixth Edition.pdf
DeDRM v7.1.0: Principles of Neural Science, Sixth Edition.pdf is a PDF ebook
DeDRM v7.1.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Found 1 keys
DeDRM v7.1.0: Trying a new default key
[16.83] splash screen hidden
[16.83] Started up in 16.83 seconds with 1 books
error writing pdf: max() arg is an empty sequence
DeDRM v7.1.0: Failed to decrypt with new default key after 42.9 seconds
DeDRM v7.1.0: Ultimately failed to decrypt after 42.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 638, in run
  File "calibre_plugins.dedrm.__init__", line 513, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.1.0: Ultimately failed to decrypt after 42.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x07B9B460>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x07B9B460>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 266, in __del__
TypeError: 'NoneType' object is not caAdded Principles of Neural Science, Sixth Edition to db in: 0.2
Added 1 books in 43.5 seconds

```
</details>

**Comment by ttmysd70c6f5** [comment]
Sorry, the conversion worked when I downgrade the version of DeDRM and Calibre. I will close this issue.

**Comment by ElleKayEm** [comment]
You should also be good if you update to latest calibre and noDRM's DeDRM:  https://github.com/noDRM/DeDRM_tools
