### ISSUE TITLE
not converting ACSM

### ISSUE THREAD

**Issue by kaizensidi** [apprenticeharper/DeDRM_tools#2049]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
EpubMerge: DEBUG: 2022-04-08 07:41:04,124: calibre_plugins.epubmerge.epubmerge_plugin(155): macmenuhack file_path:C:\Users\Dell\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Foutopsporingslog
calibre 5.40  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: DeACSM (0, 0, 15) && EpubMerge (2, 13, 0) && Kobo Books (1, 9, 0) && Kobo Utilities (2, 15, 1) && PocketBook632 (1, 0, 1)
calibre 5.40  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: nl
Successfully initialized third party plugins: DeACSM (0, 0, 15) && EpubMerge (2, 13, 0) && Kobo Books (1, 9, 0) && Kobo Utilities (2, 15, 1) && PocketBook632 (1, 0, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 87.96536796536796 x 84.04411764705881
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
DEBUG:    0.5 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.5 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.5 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.5 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
[1.19] main UI initialized...
[1.19] Hiding splash screen
Starting QuickView
[20.53] splash screen hidden
[20.53] Started up in 20.53 seconds with 9 books
Added The 7 Habits of Highly Effective People to db in: 0.2
Added 1 books in 0.7 seconds
Worker Launch took: 0.03 seconds
Job: 0 Boek 1 van 1 (The 7 Habits of Highly Effective People) converteren finished
Boek 1 van 1 (The 7 Habits of Highly Effective People) converteren

	Conversion options changed from defaults:

	  output_profile: 'cybookg3'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_yg8aa5hv\\a9oiped4.opf'

	Resolved conversion options

	calibre version: 5.40.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07FD7F88>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.CybookG3Output object at 0x07FD50E8>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_yg8aa5hv\\a9oiped4.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	InputFormatPlugin: EPUB Input running

	on C:\Users\Dell\AppData\Local\Temp\calibre_yg8aa5hv\et8qxfi3.epub

	Traceback (most recent call last):

	  File "runpy.py", line 194, in _run_module_as_main

	  File "runpy.py", line 87, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert

	calibre.ebooks.DRMError: et8qxfi3.epub


```
</details>

**Comment by ElleKayEm** [comment]
You don't seem to have DeDRM installed.
