### ISSUE TITLE
After two conversion from AZW3 to PDF, and from AZW3 to EPUB with Kindle Unpack, the text is garbled.

### ISSUE THREAD

**Issue by luigirovatti** [apprenticeharper/DeDRM_tools#2055]
Of the first conversion I have the technical info of the work done by Calibre, of the one done by Kindle Unpack, unfortunately I have no such details. I'll now report the details of the conversion made from AZW3 to PDF:

Converti libro 1 di 1 (Exopolitics: Political Implications Of The Extraterrestrial Presence)
DeDRM v7.1.0: Trying to decrypt m6r4sn0l.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Exopolitics: Political Implications Of The Extraterrestrial Presence
Got DSN key from database default_key
Error getting PIDs from database default_key: can't concat str to bytearray
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
TypeError: can't concat str to bytearray
Got DSN key from database default_key_2
Found 4 keys to try after 0.7 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.7 seconds
DeDRM v7.1.0: Finished after 0.7 seconds
Conversion options changed from defaults:
  pdf_serif_family: 'MS Shell Dlg 2'
  read_metadata_from_opf: 'C:\\Users\\ALMARK~1\\AppData\\Local\\Temp\\calibre_f8to3_an\\h918s1w7.opf'
  pdf_sans_family: 'MS Shell Dlg 2'
  cover: 'C:\\Users\\ALMARK~1\\AppData\\Local\\Temp\\calibre_f8to3_an\\yr1p_2jr.jpeg'
  output_profile: 'kindle'
  verbose: 2
Resolved conversion options
calibre version: 5.40.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\ALMARK~1\\AppData\\Local\\Temp\\calibre_f8to3_an\\yr1p_2jr.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001D8F52E6910>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000001D8F52E6E20>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\ALMARK~1\\AppData\\Local\\Temp\\calibre_f8to3_an\\h918s1w7.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Failed to initialize plugin: 'C:\\Users\\almark164\\AppData\\Roaming\\calibre\\plugins\\Inept Epub DeDRM.zip'
DeDRM v7.1.0: Trying to decrypt er8upp2l.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Exopolitics: Political Implications Of The Extraterrestrial Presence
Got DSN key from database default_key
Error getting PIDs from database default_key: can't concat str to bytearray
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
  File "calibre_plugins.dedrm.kgenpids", line 270, in getK4Pids
TypeError: can't concat str to bytearray
Got DSN key from database default_key_2
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v7.1.0: Finished after 0.1 seconds
InputFormatPlugin: MOBI Input running
on C:\Users\ALMARK~1\AppData\Local\Temp\calibre_f8to3_an\pu25gsgd.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Parsing all content...
Parsing text/part0000.html ...
Forcing text/part0000.html into XHTML namespace
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 637 items of level: div_1
Found 4428 items of level: p_2
Found 245 items of level: p_6
div_1 left margin stats: Counter({'': 312})
div_1 right margin stats: Counter({'': 312})
p_2 left margin stats: Counter({'6pt': 1503, '0': 1397, '27pt': 513, '24pt': 258, '5pt': 201, '9.5pt': 73, '26pt': 56, '15.5pt': 56, '25pt': 42, '19pt': 36, '28.5pt': 32, '9.45pt': 29, '34.5pt': 29, '10.45pt': 24, '4.2pt': 14, '26.8pt': 14, '34pt': 11, '44pt': 11, '38pt': 9, '32.8pt': 9, '23.3pt': 7, '36.3pt': 7, '23.2pt': 6, '109.7pt': 5, '17.3pt': 5, '23pt': 3, '32.7pt': 3, '42.3pt': 3, '47.5pt': 3, '11pt': 2, '23.1pt': 2, '25.35pt': 2, '108.7pt': 2, '22.1pt': 2, '22.2pt': 2, '25.3pt': 2, '17.2pt': 2, '7.8pt': 2, '13.8pt': 2, '50.65pt': 1, '57.8pt': 1, '60.15pt': 1, '39.3pt': 1, '81.7pt': 1, '138.45pt': 1, '65.85pt': 1, '93.3pt': 1, '85.85pt': 1, '68.55pt': 1, '138.8pt': 1, '109.1pt': 1, '103.35pt': 1, '67.85pt': 1, '117.65pt': 1, '82.4pt': 1, '20.95pt': 1, '87.95pt': 1, '10.75pt': 1, '14.1pt': 1, '10.55pt': 1, '19.7pt': 1, '24.3pt': 1, '23.15pt': 1, '24.15pt': 1, '6.1pt': 1, '27.15pt': 1, '5.8pt': 1, '5.65pt': 1, '42pt': 1, '22.7pt': 1, '3.2pt': 1, '4.3pt': 1, '23.85pt': 1, '4.35pt': 1, '33.35pt': 1, '5.1pt': 1, '21.1pt': 1, '21.2pt': 1, '41.85pt': 1, '90.9pt': 1, '76.7pt': 1, '127pt': 1, '51.8pt': 1, '8.7pt': 1, '42.2pt': 1, '45.8pt': 1, '7.7pt': 1, '53.5pt': 1})
p_2 right margin stats: Counter({'0': 2100, '3.15pt': 886, '3.45pt': 210, '3.4pt': 160, '3.25pt': 91, '21.15pt': 85, '3.2pt': 81, '3.3pt': 69, '3.1pt': 51, '2.95pt': 43, '3.05pt': 36, '3.35pt': 35, '3pt': 22, '3.5pt': 21, '21.2pt': 18, '21.45pt': 18, '21pt': 13, '3.65pt': 13, '21.4pt': 11, '3.55pt': 10, '21.1pt': 10, '21.25pt': 9, '21.05pt': 9, '108.7pt': 8, '258.25pt': 5, '176.5pt': 5, '5pt': 4, '20.95pt': 4, '203.8pt': 4, '3.6pt': 4, '4.4pt': 4, '4.45pt': 4, '78.15pt': 4, '21.3pt': 3, '21.55pt': 3, '51.9pt': 3, '6.2pt': 3, '17.1pt': 3, '26.3pt': 2, '72.55pt': 2, '21.35pt': 2, '22.1pt': 2, '21.5pt': 2, '15.75pt': 2, '247.45pt': 2, '80.85pt': 2, '253.25pt': 2, '45.35pt': 2, '74.55pt': 2, '34.2pt': 2, '8.5pt': 2, '91.15pt': 2, '39.7pt': 2, '22.65pt': 2, '239.95pt': 2, '64.1pt': 2, '15.7pt': 2, '3.85pt': 2, '53.95pt': 2, '42.95pt': 2, '14.05pt': 2, '24.25pt': 2, '60pt': 2, '13.4pt': 2, '75.55pt': 2, '86.1pt': 2, '10.65pt': 2, '39.6pt': 2, '18.3pt': 2, '11.9pt': 2, '44.8pt': 1, '47.1pt': 1, '68.7pt': 1, '52.85pt': 1, '138.4pt': 1, '92.3pt': 1, '104.15pt': 1, '235.55pt': 1, '86.7pt': 1, '220.45pt': 1, '84.85pt': 1, '67.5pt': 1, '108.05pt': 1, '102.35pt': 1, '117.65pt': 1, '87.1pt': 1, '197.5pt': 1, '19.95pt': 1, '86.95pt': 1, '9.6pt': 1, '152.15pt': 1, '130.3pt': 1, '103.8pt': 1, '180.3pt': 1, '90.3pt': 1, '129.05pt': 1, '82.3pt': 1, '157.1pt': 1, '80.6pt': 1, '21.6pt': 1, '167.4pt': 1, '142.05pt': 1, '136.6pt': 1, '175.7pt': 1, '180.85pt': 1, '166pt': 1, '124.3pt': 1, '66.45pt': 1, '89.9pt': 1, '73.15pt': 1, '200.05pt': 1, '70pt': 1, '179.45pt': 1, '74.3pt': 1, '206.4pt': 1, '75.6pt': 1, '185.75pt': 1, '188.75pt': 1, '214.45pt': 1, '171.1pt': 1, '92.75pt': 1, '138.8pt': 1, '29.85pt': 1, '19.7pt': 1, '82.85pt': 1, '52.95pt': 1, '30.05pt': 1, '55.9pt': 1, '21.9pt': 1, '57.55pt': 1, '47.4pt': 1, '60.25pt': 1, '115.6pt': 1, '201.1pt': 1, '41.7pt': 1, '25.2pt': 1, '171.85pt': 1, '119.3pt': 1, '179.65pt': 1, '22.2pt': 1, '230.25pt': 1, '59.45pt': 1, '100.65pt': 1, '44pt': 1, '156.85pt': 1, '53.6pt': 1, '22.05pt': 1, '50.15pt': 1, '10.1pt': 1, '15.5pt': 1, '86.55pt': 1, '156.6pt': 1, '79.15pt': 1, '38.7pt': 1, '170.45pt': 1, '58.85pt': 1, '35.95pt': 1, '177.5pt': 1, '2.9pt': 1, '242.75pt': 1, '4.3pt': 1, '4.25pt': 1, '190.9pt': 1, '26.15pt': 1, '13.05pt': 1, '127.65pt': 1, '31.9pt': 1, '161.3pt': 1, '189.35pt': 1, '21.8pt': 1, '21.85pt': 1, '35.25pt': 1, '178.45pt': 1, '91.35pt': 1, '8.1pt': 1, '165.3pt': 1, '35.45pt': 1, '81.9pt': 1, '97.35pt': 1, '31.95pt': 1, '21.7pt': 1, '219.1pt': 1, '80pt': 1, '167.1pt': 1, '15pt': 1, '41.65pt': 1, '193.05pt': 1, '33.95pt': 1, '55.75pt': 1, '227.1pt': 1, '72.45pt': 1, '116.65pt': 1, '160.55pt': 1, '109.05pt': 1, '50.75pt': 1, '150.2pt': 1, '59.4pt': 1, '227.3pt': 1, '251.1pt': 1, '31.45pt': 1, '161pt': 1, '6.7pt': 1, '222.8pt': 1, '221.3pt': 1, '90.7pt': 1, '40.05pt': 1, '48.85pt': 1, '28.55pt': 1, '22.85pt': 1, '75.85pt': 1, '164.4pt': 1, '75.25pt': 1, '30.25pt': 1, '39.25pt': 1, '128.95pt': 1, '64.35pt': 1, '102.1pt': 1, '192.5pt': 1, '196.8pt': 1, '32.35pt': 1, '83.55pt': 1, '78.75pt': 1, '125.9pt': 1, '67.05pt': 1, '26.95pt': 1, '70.8pt': 1, '77.85pt': 1, '93.65pt': 1, '28.35pt': 1, '53.35pt': 1, '241.75pt': 1, '29.6pt': 1, '232.3pt': 1, '211.55pt': 1, '143.55pt': 1, '125pt': 1, '21.75pt': 1, '27pt': 1, '73.35pt': 1, '27.45pt': 1, '11.8pt': 1, '75.8pt': 1, '62.5pt': 1, '31.8pt': 1, '65.05pt': 1, '19.2pt': 1, '12.8pt': 1, '12.9pt': 1, '6.8pt': 1, '71.75pt': 1, '38.05pt': 1, '31.65pt': 1, '26.35pt': 1, '48.45pt': 1, '11.75pt': 1, '25.1pt': 1, '44.15pt': 1, '6.5pt': 1, '35.15pt': 1, '51.35pt': 1, '16.6pt': 1, '15.8pt': 1, '14.7pt': 1, '15.95pt': 1, '34.1pt': 1, '54pt': 1, '23.4pt': 1, '9.9pt': 1, '36pt': 1, '48.35pt': 1, '38.55pt': 1, '14.1pt': 1, '60.85pt': 1, '25.5pt': 1, '69.9pt': 1, '55.4pt': 1, '59.25pt': 1, '68.75pt': 1, '12.25pt': 1, '28.05pt': 1, '38pt': 1, '55.5pt': 1, '18.95pt': 1, '25.4pt': 1, '74.45pt': 1, '64.75pt': 1, '66.7pt': 1, '28.15pt': 1, '9.1pt': 1, '54.2pt': 1, '31.25pt': 1, '3.75pt': 1, '61.45pt': 1, '2.2pt': 1, '69.4pt': 1, '0.45pt': 1, '2.8pt': 1, '33.35pt': 1, '62.25pt': 1, '24.8pt': 1, '11.55pt': 1, '58.2pt': 1, '7.4pt': 1, '19.3pt': 1, '4.9pt': 1, '17.45pt': 1, '24.05pt': 1, '41.95pt': 1, '68.85pt': 1, '44.85pt': 1, '65.35pt': 1, '60.95pt': 1, '79.45pt': 1, '51.4pt': 1, '48.4pt': 1, '5.75pt': 1, '11.2pt': 1, '77.4pt': 1, '7.75pt': 1, '53.9pt': 1, '34.5pt': 1, '17.3pt': 1, '67.1pt': 1, '61.3pt': 1, '45.1pt': 1, '7.05pt': 1, '42.45pt': 1, '19.65pt': 1, '11.3pt': 1, '24.75pt': 1, '79.35pt': 1, '9.3pt': 1, '52.7pt': 1, '46.35pt': 1, '15.55pt': 1, '7.35pt': 1, '33.25pt': 1, '34.15pt': 1, '34.3pt': 1, '12.45pt': 1, '43.15pt': 1, '71.6pt': 1, '68.3pt': 1, '71.1pt': 1, '6.85pt': 1, '7.8pt': 1, '33.55pt': 1, '3.95pt': 1, '42.6pt': 1, '11.1pt': 1, '14.4pt': 1, '36.1pt': 1, '67.75pt': 1, '37.95pt': 1, '13.75pt': 1, '7.65pt': 1, '57.45pt': 1, '23.3pt': 1, '5.25pt': 1, '5.35pt': 1, '18.8pt': 1, '7.2pt': 1, '20.8pt': 1, '66.85pt': 1, '13.55pt': 1, '32.6pt': 1, '66.5pt': 1, '85.05pt': 1, '54.15pt': 1, '9.5pt': 1, '45.45pt': 1, '26.2pt': 1})
p_6 left margin stats: Counter({'0': 96, '6.75pt': 19, '5.3pt': 19, '2.85pt': 18, '27.1pt': 18, '4.1pt': 15, '22.35pt': 9, '5pt': 8, '0.15pt': 7, '3pt': 4, '18.85pt': 4, '19.1pt': 4, '13.75pt': 3, '4.15pt': 3, '13.7pt': 2, '21.95pt': 2, '18.75pt': 2, '19.2pt': 2, '7.7pt': 2, '19.6pt': 1, '27.05pt': 1, '5.35pt': 1, '5.65pt': 1, '5.05pt': 1, '4.4pt': 1, '4.95pt': 1, '5.1pt': 1})
p_6 right margin stats: Counter({'0': 244, '4pt': 1})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'images/00859.jpeg' from manifest
Creating PDF Output...
Converting input as a text based book...
Merged 2 instances of ArialMT reducing size from 64.1 KB to 53.8 KB
Merged 2 instances of Arial-BoldItalicMT reducing size from 28.4 KB to 18.8 KB
Merged 2 instances of Arial-BoldMT reducing size from 32.1 KB to 22.5 KB
Merged 2 instances of Arial-ItalicMT reducing size from 33.4 KB to 23.7 KB
Removed 830 duplicate images
PDF output written to C:\Users\ALMARK~1\AppData\Local\Temp\calibre_f8to3_an\v4s253cm.pdf

Afterwards, I realized the DRM was not removed properly. So, I re-started Calibre in debug mode, and I got the following code:

Failed to initialize plugin: 'C:\\Users\\almark164\\AppData\\Roaming\\calibre\\plugins\\Inept Epub DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 740, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.ineptepub.__init__", line 168
    print 'IneptEpub: Using libcrypto.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('IneptEpub: Using libcrypto.')?
EpubMerge: DEBUG: 2022-04-14 17:32:38,248: calibre_plugins.epubmerge.epubmerge_plugin(155): macmenuhack file_path:C:\Users\almark164\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
FFF: DEBUG: 2022-04-14 17:32:38,300: calibre_plugins.fanficfare_plugin.fff_plugin(218): Plugin FanFicFare macmenuhack file_path:C:\Users\almark164\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Log di debug
calibre 5.40 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && EpubMerge (2, 13, 0) && EpubSplit (3, 3, 0) && FanFicFare (4, 11, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && KindleUnpack - The Plugin (0, 83, 1)
calibre 5.40 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 47, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 47, 0) && EpubMerge (2, 13, 0) && EpubSplit (3, 3, 0) && FanFicFare (4, 11, 0) && KFX metadata reader (from KFX Input) (1, 47, 0) && KFX Input (1, 47, 0) && KindleUnpack - The Plugin (0, 83, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.21564482029598 x 90.10135135135135
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[4.70] splash screen shown
[4.70] Initializing db...
[4.75] db initialized
[4.75] Constructing main UI...
[10.76] main UI initialized...
[10.76] Hiding splash screen
Starting QuickView
[12.98] splash screen hidden
[12.98] Started up in 12.98 seconds with 14 books
Gather KFX-ZIP (from KFX Input) 1.47.0: Importing C:/Users/almark164/Documents/My Kindle Content/B00158SFNU_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt B00158SFNU_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Exopolitics: Political Implications Of The Extraterrestrial Presence
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 7 keys to try after 0.5 seconds
Crypto Type is: 2
File is encoded with PID GOlux87QJC.
Decrypting. Please wait . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . done
Decryption succeeded after 0.7 seconds
DeDRM v7.2.1: Finished after 0.7 seconds
Failed to initialize plugin: 'C:\\Users\\almark164\\AppData\\Roaming\\calibre\\plugins\\Inept EpuAdded Exopolitics: Political Implications Of The Extraterrestrial Presence to db in: 2.4
Added 1 books in 4.5 seconds

**Comment by ElleKayEm** [comment]
First log shows a book with no encryption.  Second log shows successful decryption.
