### ISSUE TITLE
[QUESTION] Need Help with Debug. Cannot read Kindle book in Calibre. Locked by DRM.

### ISSUE THREAD

**Issue by luiscas0801** [apprenticeharper/DeDRM_tools#2059]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title
Configure the DeDRM plugin with the serial # of the Kindle. Install KFX Input. Could not open file from the Calibre reader.  Receive message 'Cannot read book. Locked by DRM.'

I followed this instructions from this webpage: 
https://www.cloudwards.net/remove-drm-from-kindle-books/

I could not remove the DRM from the file. then I found your instructions and tried again, without any luck. 

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.41 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
calibre 5.41 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.95555555555555 x 96.09458128078816
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Estambul (edición definitiva con 250 nuevas fotografías) (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Estambul (edición definitiva con 250 nuevas fotografías) (Spanish Edition)
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\luisc\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[9.66] splash screen hidden
[9.66] Started up in 9.66 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x9a\x11\xd6+\x86\xd7\xf8\xc9\xc0\x93y\xef\x07\xbb\x02\x96\xf4\x06\x87P\xe1\x1c\xeb\x05GK\xcd)\xc9\xb8U\x1e', b'C:\\Users\\luisc\\Downloads\\Estambul (edici\xc3\xb3n definitiva con 250 nuevas fotograf\xc3\xadas) (Spanish Edition).azw3']
Added Estambul (edición definitiva con 250 nuevas fotografías) (Spanish Edition) to db in: 0.2
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
If you're trying with a kfx book directly from the Paperwhite, that isn't going to work.  Go to your content & devices page at Amazon.  Use the download & transfer via usb option and choose your Paperwhite for the device.
