### ISSUE TITLE
Unable to remove DRM from .AZW file on mac

### ISSUE THREAD

**Issue by Arctagon** [apprenticeharper/DeDRM_tools#2060]
Greetings. I hardly want to add to the numerous ongoing issues here, but after trying many different solutions, I am sadly stuck. My Kindle is connected to the Amazon.com store, but I purchase books from Amazon.co.jp from time to time as well, and don't want to have to deregister and reregister my device every time I want to access a book from the other store.

I have downloaded Kindle for Mac, used the terminal command to prevent files from downloading as .kcr, and have essentially got as far as to get the file downloaded as .azw. When I drop this into Calibre, however, it stays as an .azw file, and my Kindle refuses to open it because it is ‘licensed to another user’. I am, however, able to remove the DRM using Epubor Ultimate, but on a trial it only converts 20% of any file.

Kindle for Mac and Calibre are installed on the same user, or I at least assume they are, because I only have one user on this mac.

Any ideas?

Thank you in advance for any assistance.

```
calibre Debug log
calibre 5.41  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.41  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[0.86] main UI initialized...
[0.86] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B01BW9F6BU_EBOK.azw
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 小説　秒速5センチメートル (角川文庫)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/mariusekelund/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'mariusekelund'  on file  /Users/mariusekelund/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'55bd3da2ea26'
Decrypted key file using IDString '55bd3da2ea26' and UserName 'mariusekelund'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 小説　秒速5センチメートル (角川文庫)
Got SerialNumber from database default_key_1
Got UsernameHash from database default_key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[12.55] splash screen hidden
[12.55] Started up in 12.55 seconds with 1 books

{'bsd_drives': {'main': '/dev/disk2'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1s1': '/',
               '/dev/disk1s2': '/System/Volumes/Preboot',
               '/dev/disk1s4': '/System/Volumes/VM',
               '/dev/disk1s5': '/System/Volumes/Data',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 15, count of files in metadata: 15, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 15
DeviceJob: set_books_in_library finished: time= 0.041786909103393555
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Added 小説 秒速5センチメートル (角川文庫) to db in: 0.0
Added 1 books in 0.8 seconds
```

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.2.  Available here:  https://github.com/noDRM/DeDRM_tools

**Comment by Arctagon** [comment]
Worked like a bloody charm. Thank you so much!
