### ISSUE TITLE
DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by e-b** [apprenticeharper/DeDRM_tools#2063]
Hello,
here are the details
thanks e-b

calibre, version 5.42.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/<xyz>/Downloads/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.42  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 326, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 283, in load
  File "calibre/customize/zipplugin.py", line 378, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/<xyz>/Downloads/DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're loading the whole file instead of just the plugin.  Unzip DeDRM_tools_7.2.1.zip and load DeDRM_plugin.zip.

There's a newer version here:  https://github.com/noDRM/DeDRM_tools

**Comment by e-b** [comment]
plugin loaded successfully - thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
