### ISSUE TITLE
Kindle for PC ebook keeps DRM

### ISSUE THREAD

**Issue by StenStone** [apprenticeharper/DeDRM_tools#2068]
## CheckList

- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Title
Kindle for PC ebook keeps DRM

I have tried a couple of things posted here already, including downgrading kindle for pc to 1.17 (I don't own a kindle reader so I cannot directly download from amazon). 
I tried a batchfile that supposedly makes it so the books aren't downloaded with KFX. 
I believe I don't need a key and couldn't see anything about it in the log.

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (7, 2, 0) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (7, 2, 0) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.66] main UI initialized...
[0.66] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.48.0: Importing C:\Users\Sten_Stone\Documents\My Kindle Content\B07NBRM1W1_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.0: Trying to decrypt B07NBRM1W1_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 526, in KindleMobiDecrypt
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.kfxdedrm", line 85
    traceback.print_exc()
                        ^
TabError: inconsistent use of tabs and spaces in indentation
[44.12] splash screen hidden
[44.12] Started up in 44.12 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x1c\xac\xda\x9e4\x13\xce\xd2i\xdb[z{\x85\x9f\xce\xfb\x16\x9a\xa38@\xe4?=\xa2\xf1.tn\xecZ', b'C:\\Users\\Sten_Stone\\Documents\\My Kindle Content\\B07NBRM1W1_EBOK.azw']
Added Wolf Love: Magical Urban Fantasy (Wolf Series Book 1) to db in: 0.6
Added 1 books in 0.9 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Update DeDRM to 7.2.1 or [noDRM's](https://github.com/noDRM/DeDRM_tools)  10.0.2.

**Comment by StenStone** [comment]
Thanks that seemed to work, I tried so many different versions of stuff that I mistook 7.2.0 for 7.2.1. Thanks again for the help :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
