### ISSUE TITLE
[QUESTION] DRM not removed

### ISSUE THREAD

**Issue by KnoAll** [apprenticeharper/DeDRM_tools#2074]
## CheckList

- [X] `The Title` and The `Log Title` are setted correctly.
- [X] Clarified about `my environment`.
- [X] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre Debug log
calibre 5.43 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Author Book Count Hierarchy (1, 2, 3) && Quality Check (1, 11, 4)
calibre 5.43 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Author Book Count Hierarchy (1, 2, 3) && Quality Check (1, 11, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.36363636363636
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.72] splash screen shown
[0.72] Initializing db...
[1.98] db initialized
[1.98] Constructing main UI...
[4.03] main UI initialized...
[4.03] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Encyclopedia of Counseling Maste-asin_B071NDL5K5-type_EBOK-v_0.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Encyclopedia of Counseling
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\kmn2.TOUCHMARK\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Storage number map:
{(7, 0): [(4, 'C')], (7, 1): [(1, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B008A0A011672XS6&0: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=26)
{'drive_letters': ['D'],
 'pnp_id_map': {'D': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b008a0a011672xs6&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'D': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.3 USBMS: scan from root False D:\documents
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DEBUG:    1.1 USBMS: count found in cache: 372, count of files in metadata: 372, need_sync: False
DEBUG:    1.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    1.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 372
Job: 2 Get list of books on device finished
No details available.
DeviceJob: set_books_in_library finished: time= 0.026984691619873047
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
[18.58] splash screen hidden
[18.58] Started up in 18.58 seconds with 11993 books
Job: 2 Get list of books on device finished
No details available.
Job: 3 Prepare files for transfer from device started
DeviceJob: 3 Prepare files for transfer from device done, calling callback
DeviceJob: 3 Prepare files for transfer from device callback returned
Job: 3 Prepare files for transfer from device finished
No details available.
Added Encyclopedia of Counseling to db in: 0.1
Added 1 books in 0.8 seconds
DeviceJob: set_books_in_library: books to process= 372
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 449, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: Cannot decode library or rented ebooks.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/masDeviceJob: set_books_in_library finished: time= 0.06296992301940918
Worker Launch took: 0.00 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Answer is in the log:

> DeDRM v7.2.1: Failed to decrypt with error: Cannot decode library or rented ebooks.
