### ISSUE TITLE
PDF are not opened (DRM not encrypted)

### ISSUE THREAD

**Issue by Pfaff262** [apprenticeharper/DeDRM_tools#2075]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`. Windows 11, Calibre 5.43
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
calibre, version 5.43.0
FEHLER: Buch konnte nicht geladen werden: Buch konnte nicht geöffnet werden: U:\Neustart-01062020\Backup_Weiss\Calibri03062020\Calibre-01.06.2020_SaHan\Unbekannt\Sneakersocken stricken mit Wow-Effe (1680)\Sneakersocken stricken mit Wow- - Unbekannt.pdf. "Details anzeigen" anklicken für weitere Informationen.

Failed to convert book: U:\Neustart-01062020\Backup_Weiss\Calibri03062020\Calibre-01.06.2020_SaHan\Unbekannt\Sneakersocken stricken mit Wow-Effe (1680)\Sneakersocken stricken mit Wow- - Unbekannt.pdf with error:
DeDRM v7.2.1: Trying to decrypt Sneakersocken stricken mit Wow- - Unbekannt.pdf
DeDRM v7.2.1: Sneakersocken stricken mit Wow- - Unbekannt.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1602, in initialize_ebx
TypeError: object of type 'int' has no len()
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Trying Encryption key default_key_2
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key_2 after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
InputFormatPlugin: PDF Input running
on U:\Neustart-01062020\Backup_Weiss\Calibri03062020\Calibre-01.06.2020_SaHan\Unbekannt\Sneakersocken stricken mit Wow-Effe (1680)\Sneakersocken stricken mit Wow- - Unbekannt.pdf
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 323, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 791, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 82, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
Exception ignored in: <function NativeFunction.__del__ at 0x000001F5176701F0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001F5176701F0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
```
</details>

**Comment by Pfaff262** [comment]
It is a pdf from a public bilbleothek. It was all ok until ca. four month. Here a think a new pdf-key was used. It is also by other people. Thanks. 

I dont want the request closed. Sorry

**Comment by ElleKayEm** [comment]
Is it Adobe DRM?

**Comment by Pfaff262** [comment]
I don’t know. But the book  was load first in adobe digital editions and then to calibre. It is by new pdf  books. I believe the Bibleothek and the authors want to make  the books safer. Sorry that my English so bad.

**Comment by ElleKayEm** [comment]
Sounds like it is probably the newer hardened Adobe DRM then.  This version of DeDRM does not remove that.  It is being worked on over at [noDRM's DeDRM](https://github.com/noDRM/DeDRM_tools) , but is not in the latest release yet.

**Comment by Pfaff262** [comment]
Many thanks for the fast answer
