### ISSUE TITLE
Failed to convert azw3 to pdf on 2 books 

### ISSUE THREAD

**Issue by grammstacks** [apprenticeharper/DeDRM_tools#2077]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## AZW3 to PDF conversion fails 
I have 2 books that won't covert to pdf. end of both logs says 'ValueError: Invalid Page Number: (page number)

## Log

<details><summary>Book 1 Log</summary>

```log
calibre, version 5.23.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫))

Convert book 1 of 1 (嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫))
DeDRM v7.2.1: Trying to decrypt dlu5yf9e.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫)
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v7.2.1: Finished after 0.1 seconds
Conversion options changed from defaults:
  pdf_sans_family: 'MS Shell Dlg 2'
  cover: 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\7wnhajwv.jpeg'
  output_profile: 'generic_eink'
  read_metadata_from_opf: 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\v4nu_m1p.opf'
  verbose: 2
  pdf_serif_family: 'MS Shell Dlg 2'
Resolved conversion options
calibre version: 5.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\7wnhajwv.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000196ADA8AD90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000196ADB900D0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\v4nu_m1p.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v7.2.1: Trying to decrypt e9w10llp.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫)
Got DSN key from database default_key
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v7.2.1: Finished after 0.0 seconds
InputFormatPlugin: MOBI Input running
on C:\Users\gramm\AppData\Local\Temp\calibre_3mhs2r47\yk3p6slz.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Parsing all content...
Parsing text/part0019.html ...
Parsing text/part0022.html ...
Parsing text/part0025.html ...
Parsing text/part0027.html ...
Parsing text/part0024.html ...
Parsing styles/0004.css ...
Parsing styles/0001.css ...
Property: Unknown Property name. [44:5: word-wrap]
Property: Unknown Property name. [46:5: -webkit-line-break]
Property: Unknown Property name. [47:5: -epub-line-break]
Property: Unknown Property name. [48:5: -webkit-word-break]
Property: Unknown Property name. [49:5: -epub-word-break]
Property: Unknown Property name. [50:5: -webkit-hyphens]
Property: Unknown Property name. [51:5: -epub-hyphens]
Property: Unknown Property name. [52:5: -webkit-text-underline-position]
Property: Unknown Property name. [53:5: -epub-text-underline-position]
Parsing styles/0002.css ...
Property: Unknown Property name. [85:5: -webkit-writing-mode]
Property: Unknown Property name. [86:5: -webkit-writing-mode]
Property: Unknown Property name. [90:5: -webkit-writing-mode]
Property: Unknown Property name. [91:5: -webkit-writing-mode]
Property: Unknown Property name. [305:5: -webkit-text-combine]
Property: Unknown Property name. [306:5: -webkit-text-combine-upright]
Property: Unknown Property name. [307:5: text-combine-upright]
Property: Unknown Property name. [308:5: -webkit-text-combine]
Property: Unknown Property name. [315:5: -webkit-text-combine]
Property: Unknown Property name. [316:5: -webkit-text-combine-upright]
Property: Unknown Property name. [317:5: text-combine-upright]
Property: Unknown Property name. [318:5: -webkit-text-combine]
Property: Unknown Property name. [321:5: -webkit-text-orientation]
Property: Unknown Property name. [322:5: -epub-text-orientation]
Property: Unknown Property name. [325:5: -webkit-text-orientation]
Property: Unknown Property name. [326:5: -epub-text-orientation]
Property: Unknown Property name. [375:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [376:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [379:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [380:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [383:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [384:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [387:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [388:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [391:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [392:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [395:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [396:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [399:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [400:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [403:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [404:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [407:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [408:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [411:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [412:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [808:5: -webkit-text-emphasis-color]
Property: Unknown Property name. [809:5: -webkit-text-emphasis-color]
Property: Unknown Property name. [2661:5: -webkit-line-break]
Property: Unknown Property name. [2662:5: -epub-line-break]
Property: Unknown Property name. [2665:5: -webkit-line-break]
Property: Unknown Property name. [2666:5: -epub-line-break]
Property: Unknown Property name. [2669:5: -webkit-line-break]
Property: Unknown Property name. [2670:5: -epub-line-break]
Property: Unknown Property name. [2673:5: -webkit-line-break]
Property: Unknown Property name. [2674:5: -epub-line-break]
Property: Unknown Property name. [2679:5: -webkit-word-break]
Property: Unknown Property name. [2680:5: -epub-word-break]
Property: Unknown Property name. [2683:5: -webkit-word-break]
Property: Unknown Property name. [2684:5: -epub-word-break]
Property: Unknown Property name. [2687:5: -webkit-word-break]
Property: Unknown Property name. [2688:5: -epub-word-break]
Property: Unknown Property name. [2693:5: word-wrap]
Property: Unknown Property name. [2696:5: word-wrap]
Parsing styles/0003.css ...
Parsing text/part0003.html ...
Parsing text/part0007.html ...
Parsing text/part0013.html ...
Parsing text/part0016.html ...
Parsing text/part0020.html ...
Parsing text/part0015.html ...
Parsing text/part0021.html ...
Parsing text/part0029.html ...
Parsing text/part0031.html ...
Parsing text/part0002.html ...
Parsing text/part0006.html ...
Parsing text/part0012.html ...
Parsing text/part0030.html ...
Parsing text/part0001.html ...
Parsing text/part0005.html ...
Parsing text/part0009.html ...
Parsing text/part0011.html ...
Parsing text/part0017.html ...
Parsing text/part0023.html ...
Parsing text/part0026.html ...
Parsing text/part0028.html ...
Parsing text/part0018.html ...
Parsing text/part0000.html ...
Parsing text/part0004.html ...
Parsing text/part0008.html ...
Parsing text/part0010.html ...
Parsing text/part0014.html ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 32 items of level: div_1
Found 3165 items of level: p_2
Found 4 items of level: div_2
Found 16 items of level: p_3
Found 1 items of level: div_3
Found 1 items of level: p_4
Ignoring level div_3
Ignoring level p_3
Ignoring level p_4
div_1  left margin stats: Counter({'0': 20})
div_1  right margin stats: Counter({'0': 20})
p_2  left margin stats: Counter({'0': 3165})
p_2  right margin stats: Counter({'0': 3165})
div_2  left margin stats: Counter({'0': 1})
div_2  right margin stats: Counter({'0': 1})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'images/00017.jpeg' from manifest
Trimming 'images/00023.unknown' from manifest
Trimming 'images/00022.unknown' from manifest
Trimming 'images/00021.unknown' from manifest
Trimming 'images/00020.unknown' from manifest
Creating PDF Output...
Converting input as a text based book...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1271, in run
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 188, in convert
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 254, in convert_text
  File "calibre\ebooks\pdf\html_writer.py", line 1081, in convert
  File "calibre\ebooks\pdf\html_writer.py", line 625, in add_toc
  File "calibre\ebooks\pdf\html_writer.py", line 604, in create
ValueError: Invalid page number: 512

```
</details>

<details><summary>Book 2 Log</summary>

```log
calibre, version 5.23.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！２ (ブレイブ文庫) 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫))

Convert book 1 of 1 (嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！２ (ブレイブ文庫) 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫))
DeDRM v7.2.1: Trying to decrypt oo_a9zmr.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！２ (ブレイブ文庫) 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫)
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v7.2.1: Finished after 0.1 seconds
Conversion options changed from defaults:
  pdf_sans_family: 'MS Shell Dlg 2'
  cover: 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\ro5k4ms3.jpeg'
  output_profile: 'generic_eink'
  read_metadata_from_opf: 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\rra4b3ew.opf'
  verbose: 2
  pdf_serif_family: 'MS Shell Dlg 2'
Resolved conversion options
calibre version: 5.23.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\ro5k4ms3.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001A7C6968D90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001A7C6A9D0D0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'MS Shell Dlg 2',
 'pdf_serif_family': 'MS Shell Dlg 2',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\gramm\\AppData\\Local\\Temp\\calibre_3mhs2r47\\rra4b3ew.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v7.2.1: Trying to decrypt 9d9wqyyw.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！２ (ブレイブ文庫) 嫌われ勇者を演じた俺は、なぜかラスボスに好かれて一緒に生活してます！ (ブレイブ文庫)
Got DSN key from database default_key
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v7.2.1: Finished after 0.0 seconds
InputFormatPlugin: MOBI Input running
on C:\Users\gramm\AppData\Local\Temp\calibre_3mhs2r47\3rx2p1tk.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Parsing all content...
Parsing text/part0019.html ...
Parsing text/part0022.html ...
Parsing text/part0025.html ...
Parsing text/part0030.html ...
Parsing text/part0024.html ...
Parsing styles/0004.css ...
Parsing styles/0001.css ...
Property: Unknown Property name. [44:5: word-wrap]
Property: Unknown Property name. [46:5: -webkit-line-break]
Property: Unknown Property name. [47:5: -epub-line-break]
Property: Unknown Property name. [48:5: -webkit-word-break]
Property: Unknown Property name. [49:5: -epub-word-break]
Property: Unknown Property name. [50:5: -webkit-hyphens]
Property: Unknown Property name. [51:5: -epub-hyphens]
Property: Unknown Property name. [52:5: -webkit-text-underline-position]
Property: Unknown Property name. [53:5: -epub-text-underline-position]
Parsing styles/0002.css ...
Property: Unknown Property name. [85:5: -webkit-writing-mode]
Property: Unknown Property name. [86:5: -webkit-writing-mode]
Property: Unknown Property name. [90:5: -webkit-writing-mode]
Property: Unknown Property name. [91:5: -webkit-writing-mode]
Property: Unknown Property name. [305:5: -webkit-text-combine]
Property: Unknown Property name. [306:5: -webkit-text-combine-upright]
Property: Unknown Property name. [307:5: text-combine-upright]
Property: Unknown Property name. [308:5: -webkit-text-combine]
Property: Unknown Property name. [315:5: -webkit-text-combine]
Property: Unknown Property name. [316:5: -webkit-text-combine-upright]
Property: Unknown Property name. [317:5: text-combine-upright]
Property: Unknown Property name. [318:5: -webkit-text-combine]
Property: Unknown Property name. [321:5: -webkit-text-orientation]
Property: Unknown Property name. [322:5: -epub-text-orientation]
Property: Unknown Property name. [325:5: -webkit-text-orientation]
Property: Unknown Property name. [326:5: -epub-text-orientation]
Property: Unknown Property name. [375:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [376:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [379:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [380:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [383:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [384:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [387:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [388:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [391:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [392:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [395:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [396:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [399:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [400:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [403:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [404:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [407:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [408:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [411:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [412:5: -webkit-text-emphasis-style]
Property: Unknown Property name. [808:5: -webkit-text-emphasis-color]
Property: Unknown Property name. [809:5: -webkit-text-emphasis-color]
Property: Unknown Property name. [2661:5: -webkit-line-break]
Property: Unknown Property name. [2662:5: -epub-line-break]
Property: Unknown Property name. [2665:5: -webkit-line-break]
Property: Unknown Property name. [2666:5: -epub-line-break]
Property: Unknown Property name. [2669:5: -webkit-line-break]
Property: Unknown Property name. [2670:5: -epub-line-break]
Property: Unknown Property name. [2673:5: -webkit-line-break]
Property: Unknown Property name. [2674:5: -epub-line-break]
Property: Unknown Property name. [2679:5: -webkit-word-break]
Property: Unknown Property name. [2680:5: -epub-word-break]
Property: Unknown Property name. [2683:5: -webkit-word-break]
Property: Unknown Property name. [2684:5: -epub-word-break]
Property: Unknown Property name. [2687:5: -webkit-word-break]
Property: Unknown Property name. [2688:5: -epub-word-break]
Property: Unknown Property name. [2693:5: word-wrap]
Property: Unknown Property name. [2696:5: word-wrap]
Parsing styles/0003.css ...
Parsing text/part0003.html ...
Parsing text/part0007.html ...
Parsing text/part0011.html ...
Parsing text/part0016.html ...
Parsing text/part0027.html ...
Parsing text/part0029.html ...
Parsing text/part0023.html ...
Parsing text/part0002.html ...
Parsing text/part0006.html ...
Parsing text/part0010.html ...
Parsing text/part0017.html ...
Parsing text/part0018.html ...
Parsing text/part0021.html ...
Parsing text/part0026.html ...
Parsing text/part0028.html ...
Parsing text/part0001.html ...
Parsing text/part0005.html ...
Parsing text/part0009.html ...
Parsing text/part0013.html ...
Parsing text/part0015.html ...
Parsing text/part0020.html ...
Parsing text/part0000.html ...
Parsing text/part0004.html ...
Parsing text/part0008.html ...
Parsing text/part0012.html ...
Parsing text/part0014.html ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 31 items of level: div_1
Found 2841 items of level: p_2
Found 6 items of level: div_2
Found 17 items of level: p_3
Found 1 items of level: div_3
Found 1 items of level: p_4
Ignoring level p_4
Ignoring level div_3
Ignoring level p_3
div_1  left margin stats: Counter({'0': 19})
div_1  right margin stats: Counter({'0': 19})
p_2  left margin stats: Counter({'0': 2841})
p_2  right margin stats: Counter({'0': 2841})
div_2  left margin stats: Counter({'0': 1})
div_2  right margin stats: Counter({'0': 1})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'images/00017.jpeg' from manifest
Trimming 'images/00023.unknown' from manifest
Trimming 'images/00022.unknown' from manifest
Trimming 'images/00021.unknown' from manifest
Trimming 'images/00020.unknown' from manifest
Creating PDF Output...
Converting input as a text based book...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1271, in run
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 188, in convert
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 254, in convert_text
  File "calibre\ebooks\pdf\html_writer.py", line 1081, in convert
  File "calibre\ebooks\pdf\html_writer.py", line 625, in add_toc
  File "calibre\ebooks\pdf\html_writer.py", line 604, in create
ValueError: Invalid page number: 515

```
</details>

**Comment by ElleKayEm** [comment]
This is not a DeDRM issue.  Both logs show books already successfully decrypted or which were DRM-free to begin with.  For ebook problems unrelated to DRM removal, I recommend the calibre forum over at Mobileread.com.
