### ISSUE TITLE
10.0.2 not decrypting azw

### ISSUE THREAD

**Issue by nbi1** [apprenticeharper/DeDRM_tools#2078]
Can 10.0.2 not decrypt azw for kindle 1.37.0 (yes I know, this might be pushing it)? Most of my older ebooks (which I paid for and own) cannot be converted to PDF because they are "DRM locked". At first I thought Amazon might have KFXed these ebooks under the covers, but that is not the case - they are azw. Looks like KindleMobiDecrypt is failing. Thanks.

calibre Debug log
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.95555555555555
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.67] splash screen shown
[0.67] Initializing db...
[0.70] db initialized
[0.70] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing Y:\calibre_win11\Robert K. Wysocki\Effective Project Management_ Tradit (21)\Effective Project Management_ T - Robert K. Wysocki.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.2: Trying to decrypt Effective Project Management_ T - Robert K. Wysocki.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Effective Project Management: Traditional, Agile, Extreme
Got DSN key from database default_key
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\nbi\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\nbi\AppData\Local\Amazon\Kindle\storage\.kinf2018
[171.44] splash screen hidden
[171.44] Started up in 171.44 seconds with 8 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x98\xaf\xd3)~\x1f\xeb\xb8ggy\xee\x1e\xf4\x98j\xce\xdf\xd5\xef\x9e\x97\x98.\x83\xc9\xcf\xc7\x11it\xc0', b'Y:\\calibre_win11\\Robert K. Wysocki\\Effective Project Management_ Tradit (21)\\Effective Project Management_ T - Robert K. Wysocki.azw']
Decrypted key file using IDString '1380002626' and UserName 'nbi'
DeDRM v10.0.2: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Effective Project Management: Traditional, Agile, Extreme
Got DSN key from database default_key_1
Found 4 keys to try after 4.4 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 4.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 4.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_toolsAdded Effective Project Management: Traditional, Agile, Extreme to db in: 2.9
Added 1 books in 8.2 seconds

**Comment by ElleKayEm** [comment]
Was this book originally downloaded with Kindle for PC on the same machine and user as calibre with DeDRM?  It looks like it's being imported from a calibre library here.

It doesn't appear to be KFX, but the last version of Kindle for PC which you can disable KFX format downloads is 1.34.

**Comment by nbi1** [comment]
> Was this book originally downloaded with Kindle for PC on the same machine and user as calibre with DeDRM? It looks like it's being imported from a calibre library here.

It looks that way because after removing the book I copy it into the library directory from a backup directory as I don't want calibre touching my backups. Yes, same machine and user for both kindle and calibre.

**Comment by ElleKayEm** [comment]
Try a freshly downloaded copy straight from the Kindle folder.
