### ISSUE TITLE
DeDRM 7.2.1 is not working in Calibre 5.43.0

### ISSUE THREAD

**Issue by jimkdrm** [apprenticeharper/DeDRM_tools#2080]
The DRM is not removed from a book not previously in Calibre.  This is true for the 3 books I tried.  They were all recently copied from the Kindle.

## Log
calibre Debug log
calibre 5.43  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 5.43  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 125.0 x 125.0
physicalDpi: 106.38743455497382 x 106.32558139534883
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.83] splash screen shown
[0.83] Initializing db...
[1.02] db initialized
[1.02] Constructing main UI...
[3.81] main UI initialized...
[3.81] Hiding splash screen
Starting QuickView
[355.67] splash screen hidden
[355.67] Started up in 355.67 seconds with 478 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'_\xe2\x191T\xc3\xd8p\x10\x07\x06\xb9\xbeG\xae\xa6\xe9\xc7\xf4 \xce\x1b?#\xe3`\xfb2\xe3]\xa4\x98', b'E:\\Calibre Logs\\Aristotle_ The Complete Works_B0776XBS5G.kfx']
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing E:\Calibre Logs\Aristotle_ The Complete Works_B0776XBS5G.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as F:\WinTemp\calibre_8xtegp_8\2izxu5n7.kfx-zip
DeDRM v7.2.1: Trying to decrypt 2izxu5n7.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 2izxu5n7
Found 5 keys to try after 0.5 seconds
DeDRM v7.2.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v7.2.1: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Jim\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Jim\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '315971221' and UserName 'Jim'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 2izxu5n7
Found 1 keys to try after 0.6 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging F:\WinTemp\calibre_8xtegp_8\2izxu5n7.kfx-zip
Processing container: Aristotle_ The Complete Works_B0776XBS5G.kfx
KFX metadata reader (from KFX Input) activated for F:\WinTemp\calibre_i5cl3ztx\4798bdw5_add_books\0\Aristotle_ The Complete Works_B0776XBS5G.kfx-zip
Failed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\Ignoble Epub DeDRM.zip'
Failed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\Inept Epub DeDRM.zip'
Failed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Aristotle_ The Complete Works_B0776XBS5G.kfx has DRM and cannot be converted
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container wFailed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\Ignoble Epub DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 740, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.ignobleepub.__init__", line 152
    print 'IgnobleEpub: Using libcrypto.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('IgnobleEpub: Using libcrypto.')?
Failed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\Inept Epub DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 740, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.ineptepub.__init__", line 168
    print 'IneptEpub: Using libcrypto.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('IneptEpub: Using libcrypto.')?
Failed to initialize plugin: 'C:\\Users\\Jim\\AppData\\Roaming\\calibre\\plugins\\K4PC, K4Mac, Kindle Mobi and Topaz DeDRM.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 740, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.k4mobidedrm.__init__", line 47
    print "%s is not a valid Kindle serial number or PID." % str(customvalue)
          ^
SyntaxError: invalid syntax
Added Aristotle The Complete Works B0776XBS5G to db in: 1.5
Added 1 books in 3.4 seconds

**Comment by ElleKayEm** [comment]
This is the newer KFX format which cannot be decrypted.  See this post for methods of getting Kindle books which can be decrypted:  https://www.mobileread.com/forums/showthread.php?t=283371

Also development on DeDRM has moved here:  https://github.com/noDRM/DeDRM_tools

Recommend switching to the latest version there which is currently 10.0.2.

**Comment by jimkdrm** [comment]
Thank you.  I will try the latest and see if that works.

**Comment by ElleKayEm** [comment]
Make sure you use one of the methods which gets you a file you actually can decrypt.  Unlike the one in this log.
