### ISSUE TITLE
Syntax error in DeDRM_Plugin (version 6.7.0)

### ISSUE THREAD

**Issue by echoLOGNAME** [apprenticeharper/DeDRM_tools#2082]
I downloaded DeDRM_tools_6.7.0.zip, and unzipped.
In Calibre, when I tried to import the DeDRM_Plugin.zip from the DeDRM_tools_6.7.0 folder, I got a syntax error:

`calibre, version 5.44.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 168)

calibre 5.44  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 184, in exec_module
  File "calibre\customize\zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax
'

I'm just mentioning this bug since I couldn't find any other issue with it.  I don't need an immediate fix, I'll just revert back to the previous version of Calibre and DeDRM_Plugin I was using, which was working fine and for years this plugin has been a life saver! :)

**Comment by ElleKayEm** [comment]
That version isn't compatible with calibre 5.x.  Use version 7.2.1 or noDRM's version 10.0.2.

**Comment by echoLOGNAME** [comment]
Thank you so much! I downloaded version 7.2.1 from Apprentice Alf's blog:
[](https://apprenticealf.wordpress.com/2021/04/11/dedrm-tools-7-2-1-released/)
and it installed successfully!😁

**Comment by echoLOGNAME** [comment]
Thank you so much! I downloaded version 7.2.1 from Apprentice Alf's blog:
[https://apprenticealf.wordpress.com/2021/04/11/dedrm-tools-7-2-1-released/](https://apprenticealf.wordpress.com/2021/04/11/dedrm-tools-7-2-1-released/)
and it installed successfully!😁
