### ISSUE TITLE
ebook for deDRM can't be imported

### ISSUE THREAD

**Issue by Vroloc** [apprenticeharper/DeDRM_tools#2090]
which tool was used
: DeDRM Tools
which OS you are using: macOS 12.4
where the ebook file came from (device or application): Purchased on tvz-verlag
any error messages: 

calibre, version 6.0.0
FEHLER: Hinzufügen der Bücher nicht möglich: Einige Bücher konnten nicht hinzugefügt werden. "Details anzeigen" anklicken für weitere Informationen.

Worker process crashed while executing job
Traceback (most recent call last):
  File "calibre/utils/ipc/pool.py", line 108, in recv
  File "calibre/utils/ipc/__init__.py", line 24, in eintr_retry_call
  File "multiprocessing/connection.py", line 221, in recv_bytes
  File "multiprocessing/connection.py", line 419, in _recv_bytes
  File "multiprocessing/connection.py", line 388, in _recv
EOFError

**Comment by ElleKayEm** [comment]
I don't think DeDRM is working with calibre 6 yet.

**Comment by Vroloc** [comment]
I changed to an older version. Now it works. Thanks!
