### ISSUE TITLE
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

### ISSUE THREAD

**Issue by nicolasform** [apprenticeharper/DeDRM_tools#2092]
Hello there! I got this error when I try to use the Obok plugin. I have the Ebook file on my device (Kobo Aura) and I try to convert directly from it. Any idea? Am I doing something wrong?

```
calibre, version 6.0.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.0  embedded-python: True
Windows-10-10.0.19044 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

```

**Comment by ElleKayEm** [comment]
Probably because it isn't working with calibre 6 yet.

**Comment by chrisboeg** [comment]
I was just using it the day before yesterday, then updated calibra yesterday and the error occured. Any idea how long before it will get fixed?

**Comment by ElleKayEm** [comment]
Apparently the master branch is compatible.

**Comment by ElleKayEm** [comment]
See this comment: https://github.com/noDRM/DeDRM_tools/issues/96#issuecomment-1182492150

**Comment by chrisboeg** [comment]
@ElleKayEm As far as I can see, the DeDRM problem with errors when importing epubs is fixed with the master branch you mentioned, but the bug of this topic is not. Others getting the same result?

**Comment by ElleKayEm** [comment]
Might want to ask at noDRM's repo.  Apprentice Harper has retired.

**Comment by nicolasform** [comment]
I downgraded to [v5.44.0](https://download.calibre-ebook.com/5.44.0/) and it works.

**Comment by chrisboeg** [comment]
@nicolasform A new version of DeDRM with both bugs fixed were released yesterday.

**Comment by rayspock** [comment]
There is a fork of the DeDRM tools: https://github.com/noDRM/DeDRM_tools that has this issue fixed.

**Comment by ElleKayEm** [comment]
This repo retired near the end of 2021 and this issue is 2 years old.
