### ISSUE TITLE
Calibre 6.0 add books fails with DeDRM installed

### ISSUE THREAD

**Issue by net-buoy** [apprenticeharper/DeDRM_tools#2094]
### Discussed in https://github.com/apprenticeharper/DeDRM_tools/discussions/2093

<div type='discussions-op-text'>

<sup>Originally posted by **net-buoy** July 12, 2022</sup>
per discussion here: https://www.mobileread.com/forums/showpost.php?p=4238241&postcount=106 (error messages included at cited URL) current DeDRM is causing calibre 6.0 to bork on adding books in OSX, confirmed by Diap here: https://www.mobileread.com/forums/showpost.php?p=4238157&postcount=99

</div>

**Comment by net-buoy** [comment]
Error report from Calibre: 

calibre, version 6.0.0
ERROR: Cannot add books: Failed to add some books, click "Show details" for more information.

Worker process crashed while executing job
Traceback (most recent call last):
  File "calibre/utils/ipc/pool.py", line 108, in recv
  File "calibre/utils/ipc/__init__.py", line 24, in eintr_retry_call
  File "multiprocessing/connection.py", line 221, in recv_bytes
  File "multiprocessing/connection.py", line 419, in _recv_bytes
  File "multiprocessing/connection.py", line 388, in _recv
EOFError

**Comment by ElleKayEm** [comment]
Master branch at noDRM's fork should be compatible with calibre 6.  See https://github.com/noDRM/DeDRM_tools/discussions/54

**Comment by bjcresswell** [comment]
And with me also

calibre, version 6.0.0
ERROR: Cannot add books: Failed to add some books, click "Show details" for more information.

Worker process crashed while executing job
Traceback (most recent call last):
  File "calibre/utils/ipc/pool.py", line 108, in recv
  File "calibre/utils/ipc/__init__.py", line 24, in eintr_retry_call
  File "multiprocessing/connection.py", line 221, in recv_bytes
  File "multiprocessing/connection.py", line 419, in _recv_bytes
  File "multiprocessing/connection.py", line 388, in _recv
EOFError

**Comment by ElleKayEm** [comment]
DeDRM 10.0.3 is released:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by net-buoy** [comment]
> DeDRM 10.0.3 is released: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Is the ApprenticeAlf repository "dead" now? The Apprencntice is dead, long live the apprentice?

**Comment by net-buoy** [comment]
And yes 10.0.3 w Calibre 6.1 resolves the issue
thanks

**Comment by ElleKayEm** [comment]
> > DeDRM 10.0.3 is released: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
> 
> Is the ApprenticeAlf repository "dead" now? The Apprencntice is dead, long live the apprentice?

Basically.  See the note on the main page: https://github.com/apprenticeharper/DeDRM_tools
