### ISSUE TITLE
OBOK failure in Calibre 6.1

### ISSUE THREAD

**Issue by physicsguy43** [apprenticeharper/DeDRM_tools#2096]
I recently installed Calibre 6.1 and added the Obok plugin from DeDRM tools 7.2.  When I attempt to add a book purchased from Kobo and loaded from the Kobo desktop app, I get the following error message:
calibre, version 6.1.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.1  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 63, 0) && KFX Output (1, 63, 0) && Kobo Utilities (2, 16, 4) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

When I load the same book into Calibre 5.44, using the Obok plugin from DeDRM tools 7.2, the book is successfully installed with DRM removed.

**Comment by ElleKayEm** [comment]
Try Obok 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by physicsguy43** [comment]
Thank you.  It worked just as I thought it should.  My only question is, how did I miss the DeDRM revisions from 7.2.1 to 10.0.3?

**Comment by ElleKayEm** [comment]
You only missed a couple.  When noDRM created their fork, they started with 10.0.0 so as not to be confused with any further versions Apprentice Harper put out.  But Apprentice Harper has decided to "retire" now.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
