### ISSUE TITLE
ADEPTError: Failed to decrypt user key key (sic)

### ISSUE THREAD

**Issue by jlevin75** [apprenticeharper/DeDRM_tools#21]
calibre 2.32.1  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Failed to check for calibre update: [Errno 11004] getaddrinfo failed
Failed to check for plugin update: <urlopen error [Errno 11004] getaddrinfo failed>
Started up in 2.62 seconds with 11 books
DeDRM v6.2.2: Trying to decrypt The Girl with the Dragon Tattoo.epub
DeDRM v6.2.2: Verifying zip archive integrity
DeDRM v6.2.2: The Girl with the Dragon Tattoo.epub is a secure Adobe Adept ePub
DeDRM v6.2.2: Looking for new default Adobe Digital Editions Keys after 0.4 seconds
DeDRM v6.2.2: Exception when getting default Adobe Key after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 313, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.2.2: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 590, in run
  File "calibre_plugins.dedrm.__init__", line 367, in ePubDecrypt
DeDRMError: DeDRM v6.2.2: Ultimately failed to decrypt after 0.4 seconds.
Added The Girl with the Dragon Tattoo to db in: 0.5
Added 1 books in 1.9 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x02B81530>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x02B81590>> ignored
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 PRS505: starting fetching books for card None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= PRS505 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ database/media/books
DEBUG:    0.1 USBMS: scan from root True D:\
DEBUG:    0.4 USBMS: count found in cache: 23, count of files in metadata: 23, need_sync: False
DEBUG:    0.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.4 Building XMLCache... {0: 'D:\\database\\cache\\media.xml', 2: 'F:\\Sony Reader\\database\\cache.xml'}
DEBUG:    0.5 Done building XMLCache...
DEBUG:    0.5 Updating JSON cache: 0
DEBUG:    0.5 Start build_id_playlist_map
DEBUG:    0.5 after cleaning playlists
DEBUG:    0.5 Finish build_id_playlist_map. Found 15
DEBUG:    0.5 Finished updating JSON cache: 0
DEBUG:    0.5 PRS505: finished fetching books for card None
DEBUG:    0.5 PRS505: starting fetching books for card carda
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= PRS505 oncard= carda
DEBUG:    0.5 Building XMLCache... {0: 'D:\\database\\cache\\media.xml', 2: 'F:\\Sony Reader\\database\\cache.xml'}
DEBUG:    0.5 Done building XMLCache...
DEBUG:    0.5 PRS505: finished fetching books for card carda
DEBUG:    0.5 PRS505: starting fetching books for card cardb
DEBUG:    0.6 USBMS: Fetching list of books from device. Device= PRS505 oncard= cardb
DEBUG:    0.6 USBMS: dirs are: F:\
DEBUG:    0.6 USBMS: scan from root True F:\
DEBUG:    0.6 USBMS: count found in cache: 3, count of files in metadata: 3, need_sync: False
DEBUG:    0.6 USBMS: Finished fetching list of books from device. oncard= cardb
DEBUG:    0.7 Building XMLCache... {0: 'D:\\database\\cache\\media.xml', 2: 'F:\\Sony Reader\\database\\cache.xml'}
DEBUG:    0.7 Done building XMLCache...
DEBUG:    0.7 Updating JSON cache: 2
DEBUG:    0.7 Start build_id_playlist_map
DEBUG:    0.7 after cleaning playlists
DEBUG:    0.7 Finish build_id_playlist_map. Found 0
DEBUG:    0.7 Finished updating JSON cache: 2
DEBUG:    0.7 PRS505: finished fetching books for card cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 26
DeviceJob: set_books_in_library finished: time= 0.00899982452393
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 2 Set library information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
Job: 1 Get device information finished
No details available.

**Comment by jlevin75** [comment]
I found and fixed my issue.  I installed everything under a user without admin rights (but supplied admin credentials).  I needed to login as an admin to decrypt the ADE key.  Now I'm able to de-drm with my non-admin account.
