### ISSUE TITLE
ADEPTError: error decrypting book session key

### ISSUE THREAD

**Issue by scotartt** [apprenticeharper/DeDRM_tools#210]
Adobe digital editions 1.7.2.1131
DeDRM 6.5.3 (freshly downloaded; had same issue on 6.5.2).
Mac OS 10.12.3

This is the log:

There is 1 ebook to be decrypted.
Processing file: The_Hills_of_Rome_0001.pdf
shellcommand: /usr/local/bin/python '/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py' '/Users/smcphee/Library/Preferences/com.apprenticealf.dedrm/Local Adept Key.der' '/Users/smcphee/Documents/Digital Editions/The_Hills_of_Rome_0001.pdf' '/Users/smcphee/Dropbox/Libraries/PDF_epub/PDF/The_Hills_of_Rome_0001_nodrm.pdf' > '/Users/smcphee/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  Traceback (most recent call last):
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2341, in <module>
    sys.exit(cli_main())
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2211, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2186, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1996, in __init__
    doc.initialize(userkey)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1481, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1613, in initialize_ebx
    raise ADEPTError('error decrypting book session key')
__main__.ADEPTError: error decrypting book session key
There was an error with 1 ebook:
The_Hills_of_Rome_0001.pdf couldn't be decoded:
Traceback (most recent call last):
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2341, in <module>
    sys.exit(cli_main())
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2211, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 2186, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1996, in __init__
    doc.initialize(userkey)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1481, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/private/var/folders/6_/rr7lzhws0t7743tfbt3y8mhh0000gn/T/AppTranslocation/DD6D45AE-145D-42BC-8E6E-B111907F7DAE/d/DeDRM.app/Contents/Resources/ineptpdf.py", line 1613, in initialize_ebx
    raise ADEPTError('error decrypting book session key')
__main__.ADEPTError: error decrypting book session key

**Comment by ElleKayEm** [comment]
The problem is probably ADE 1.7.2.  At least I've seen a number of people having issues with it over at MobileRead.  Give version 2.0.1 a try.  Don't forget to authorize with your Adobe ID.  Available here:

http://www.adobe.com/support/digitaleditions/downloads.html

Be sure to get 2.0.1 and **not** 3.0.
