### ISSUE TITLE
[QUESTION] Cannot install the plugin "InvalidPlugin: Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it."

### ISSUE THREAD

**Issue by kimperssonlindh** [apprenticeharper/DeDRM_tools#2101]
Hi

I cannot install/load the plugin in Calibre version 6.1.0 since it is blacklisted by Calibre. Error message says the plugin is blacklisted and "causes to crashes. Update it to the latest version to use it."

## Log

```log
calibre, version 6.1.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it.

calibre 6.1  embedded-python: True
macOS-12.4-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 483, in add_plugin
  File "calibre/customize/ui.py", line 671, in initialize_plugin
calibre.customize.InvalidPlugin: Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it.
```

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by kimperssonlindh** [comment]
ah.... thx!
