### ISSUE TITLE
DeDRM zip file will not install.

### ISSUE THREAD

**Issue by rafikiphoto** [apprenticeharper/DeDRM_tools#2102]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 6.1.0
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 168)

calibre 6.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeACSM (0, 0, 15) && Kobo Utilities (2, 16, 5) && KoboTouchExtended (3, 6, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 304, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 196, in exec_module
  File "calibre\customize\zipplugin.py", line 192, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by rafikiphoto** [comment]
Thanks. That installed fine.
B.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by rafikiphoto** [comment]
OK.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by rafikiphoto** [comment]
Thank you.
