### ISSUE TITLE
[BUG] Cannot install on Calibre 6.1

### ISSUE THREAD

**Issue by Deuchnord** [apprenticeharper/DeDRM_tools#2103]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Bug description

When I try to install the plugin on Calibre 6.1, I get the following message:

> Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it.

## Log
<details><summary>Log Title</summary>

```log
calibre, version 6.1.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it.

calibre 6.1  embedded-python: True
macOS-12.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.5', ('', '', ''), 'x86_64')
Interface language: fr
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 483, in add_plugin
  File "calibre/customize/ui.py", line 671, in initialize_plugin
calibre.customize.InvalidPlugin: Blacklisting the DeDRM version (7, 2, 1) plugin as it is too old and causes crashes. Update it to the latest version to use it.

```
</details>

**Comment by ElleKayEm** [comment]
You need DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by Deuchnord** [comment]
Oh, sorry, don’t how I fell on 7.2.1!
Thanks!
