### ISSUE TITLE
[QUESTION] Cannot DeDRM ADE eBook?

### ISSUE THREAD

**Issue by kookiechan** [apprenticeharper/DeDRM_tools#2105]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Description

I purchased an eBook from [XanEdu](https://academicpub.sharedbook.com/serve/ac/acapub/student_product_page.html?slug=1604953714_57_46376). I can only use it for the semester. It opens in Adobe Digital Editions. I wanted to DeDRM it and convert it to an EPUB for easier reading. I am unable to.

I was given an .acsm file, which I opened in ADE, accessing my eBook successfully. I downloaded Calibre and added the DeDRM 10.0.3 plugin. I restarted Calibre and tried converting the PDF of my eBook that I found in Users/me/Documents/Digital Editions. 

## Log
<details><summary>Conversion Error Details</summary>

```log
Convert book 1 of 1 (Information Retrieval System Design Principles & Practice, Editi)
Blacklisting the DeDRM plugin as it is too old and causes crashes
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/_k/1mwjchln6kd23dz3ffjwrrqr0000gn/C/calibre_6.2.1_tmp_y9am2354/gd7grjx5.opf'
  verbose: 2
  output_profile: 'ipad3'
Resolved conversion options
calibre version: 6.2.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x110803f10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_images': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x110800070>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/_k/1mwjchln6kd23dz3ffjwrrqr0000gn/C/calibre_6.2.1_tmp_y9am2354/gd7grjx5.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: PDF Input running
on /var/folders/_k/1mwjchln6kd23dz3ffjwrrqr0000gn/C/calibre_6.2.1_tmp_y9am2354/dcnsem5x.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 51, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

```
</details>

**Comment by ElleKayEm** [comment]
Doesn't look like the latest DeDRM 10.0.3 is properly installed since calibre is complaining about it being too old.  Remove any old versions.  Reload 10.0.3 and restart calibre before trying to add your book.

Also did you authorize ADE with your Adobe ID before opening the ACSM file?

**Comment by kookiechan** [comment]
I removed DeDRM 10.0.3 (and that was the only version on it, it seems, as I tried searching 'DeDRM' afterwards and there was no search results), re-loaded DeDRM 10.0.3, and restarted Calibre. I removed and readded my book, but I am met with the same Conversion Error Details. In order to install a plugin, I am supposed to go to Preferences>Change Calibre behavior>Plugins>Load plugin from file, correct? I did that, simply said yes to the warning message, and clicked Apply to apply my changes. 

I did authorize ADE with my Adobe ID before opening the ACSM file.

**Comment by ElleKayEm** [comment]
Let's see a log of adding the book to calibre:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by kookiechan** [comment]
## Log of Adding the Book to Calibre
<details><summary>Log</summary>

```log
Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Debug log
calibre 6.2.1  embedded-python: True
macOS-11.2.3-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101')
Python 3.10.1
OSX: ('11.2.3', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
calibre 6.2.1  embedded-python: True
macOS-11.2.3-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '20.3.0', 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101')
Python 3.10.1
OSX: ('11.2.3', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.01] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
2022-07-29 16:29:20.848 calibre-debug[62359:1557523] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2022-07-29 16:29:20.849 calibre-debug[62359:1557523] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2022-07-29 16:29:20.849 calibre-debug[62359:1557523] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2022-07-29 16:29:20.850 calibre-debug[62359:1557523] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
Blacklisting the DeDRM plugin as it is too old and causes crashes
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[8.77] splash screen hidden
[8.77] Started up in 8.77 seconds with 1 books
Added Information Retrieval System Design Principles & Practice, Editi to db in: 0.0
Added 1 books in 0.4 seconds
```

</details>

**Comment by kookiechan** [comment]
Okay, I redownloaded the entire DeDRM 10.0.3.zip file and redid all of my steps, and I'm not getting an immediate Error message, so I will report back if there is any success!

**Comment by kookiechan** [comment]
How long should the conversion process take? I've had 1% Progress for 8 minutes so far. But no error message yet.

**Comment by kookiechan** [comment]
It worked! Sorry for the trouble. Thank you for taking the time out of your day to help me troubleshoot. :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
