### ISSUE TITLE
[QUESTION] AZW3 imports successfully but won't convert to EPUB

### ISSUE THREAD

**Issue by msalic** [apprenticeharper/DeDRM_tools#2107]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
Convert book 1 of 1 (And Thereby Hangs a Tale, see ISBN 978-1-4299-8417-1)
DeDRM v10.0.3: Trying to decrypt izh8xws8.azw
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: And Thereby Hangs a Tale, see ISBN 978-1-4299-8417-1
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/REDACT/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'REDACT'  on file  /Users/REDACT/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5bf3b1110246'
trying IDString: b'a5819799bcd3'
trying IDString: b'5bf3b1110241'
trying IDString: b'b9f279709173'
Decrypted key file using IDString 'b9f279709173' and UserName 'REDACT'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: And Thereby Hangs a Tale, see ISBN 978-1-4299-8417-1
Got DSN key from database key_0
Found 4 keys to try after 1.1 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/REDACT/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.
```
</details>

**Comment by ElleKayEm** [comment]
Looks like you need to add your Paperwhite's serial number to DeDRM's customization.
