### ISSUE TITLE
Failed To Convert File From ADE [Calibre 6.2.1] [DeDRM 7.2.1 and 10.0.3]

### ISSUE THREAD

**Issue by junemarty** [apprenticeharper/DeDRM_tools#2108]
I got an EPUB file from a friend that I needed to convert into a PDF format. 

I have logged-in on ADE with my ADOBE ID. But I am getting this error: **The vendor account you entered is not associated with the item you are trying to open**.

Error Message: **This book is lock by DRM.**

Calibre: 6.2.1
DeDRM:  10.0.3

I installed DeDRM 7.2.1 version but I got the error below:

calibre, version 6.2.1
ERROR: Loading book failed: Failed to open the book at C:\Users\Gbeltran\Calibre Library\Les Pruitt\Reflection (5)\Reflection - Les Pruitt.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\Gbeltran\Calibre Library\Les Pruitt\Reflection (5)\Reflection - Les Pruitt.epub with error:
DeDRM v7.2.1: Trying to decrypt Reflection - Les Pruitt.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Reflection - Les Pruitt.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
Could not decrypt _4e0mrco.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 425, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 343, in __init__
  File "calibre_plugins.dedrm.ineptepub", line 298, in __init__
  File "Crypto\Cipher\AES.py", line 232, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v7.2.1: Failed to decrypt with new default key after 0.2 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\Gbeltran\Calibre Library\Les Pruitt\Reflection (5)\Reflection - Les Pruitt.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 791, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
calibre.ebooks.DRMError: Reflection - Les Pruitt.epub
Exception ignored in: <function NativeFunction.__del__ at 0x000001B09D7B1750>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001B09D7B1750>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3.  If the book's DRM isn't tied to your Adobe ID and you can't read it in ADE, then that's not going to work.

**Comment by junemarty** [comment]
@ElleKayEm

Should I use the Adobe ID of my friend used to download the file? 

How come an ePUB file associated with Adobe ID if it was purchase on Amazon?

**Comment by junemarty** [comment]
> For calibre 6, use DeDRM 10.0.3. If the book's DRM isn't tied to your Adobe ID and you can't read it in ADE, then that's not going to work.

Should I use the Adobe ID of my friend used to download the file? 

How come an ePUB file associated with Adobe ID if it was purchased on Amazon?

**Comment by ElleKayEm** [comment]
ADE (authorized with an Adobe ID) used to download the book should be on the same machine and user as calibre with DeDRM.

If it was purchased on Amazon, then it wouldn't be an epub.
