### ISSUE TITLE
Could not install plugin on windows calibre, Im a new user

### ISSUE THREAD

**Issue by parrotfella** [apprenticeharper/DeDRM_tools#2111]
Just trying to install a plugin from a file. Fresh install and downloads. New to this and looked for a solution, apologies if i missed it

calibre, version 6.2.1
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 165)

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19042-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19042')
Python 3.10.1
Windows: ('10', '10.0.19042', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 309, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 201, in exec_module
  File "calibre\customize\zipplugin.py", line 197, in get_code
  File "calibre_plugins.dedrm.__init__", line 165
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by ElleKayEm** [comment]
You need DeDRM 10.0.3 for calibre 6.x:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by MagpieCA70** [comment]
Thank you ElleKayEm for the quick reply and new link, I have a similar issue to parrotfella with both both versions of the DeDRM plugin, 7.2.1 and 10.0.3:

calibre-64bit-6.2.1
I'm on a PC running Windows 10 Pro

Error message copied to & from clipboard pasted below:

calibre, version 6.2.1
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 167)

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19042-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19042')
Python 3.10.1
Windows: ('10', '10.0.19042', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 309, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 201, in exec_module
  File "calibre\customize\zipplugin.py", line 197, in get_code
  File "calibre_plugins.dedrm.__init__", line 167
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by ElleKayEm** [comment]
Make sure you are loading the DeDRM_plugin.zip from 10.0.3.  Delete, move, or rename any older versions so you don't mix them up.

**Comment by MagpieCA70** [comment]
YESSSSSS! This worked. Thank you so much again, ElleKayEm!!

**Comment by parrotfella** [comment]
Thank you. I can take it from here. I appreciate that you got the link for
me.

**Comment by ElleKayEm** [comment]
@parrotfella If you're all set, you can close the issue.

**Comment by LDReader** [comment]
Hi, I just installed calibre 6.7.1, then tried to install the 10.0.3 DRM plugins. The DeDRM plugin failed to install, and I got this error message:

calibre, version 6.7.1
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 168)

calibre 6.7.1  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Amazon.com Multiple Countries (1, 0, 0) && Annotations (1, 17, 13) && Count Pages (1, 11, 3) && Embed Comic Metadata (1, 5, 0) && EpubCheck (0, 2, 4) && EpubMerge (2, 15, 0) && EpubSplit (3, 5, 0) && Extract ISBN (1, 5, 1) && Generate Cover (2, 2, 0) && Goodreads (1, 7, 0) && Goodreads Sync (1, 15, 6) && Job Spy (1, 0, 192) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kindle Collections (1, 7, 26) && Kindle hi-res covers (0, 5, 0) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3) && Manage Series (1, 4, 0) && MultiColumnSearch (1, 0, 89) && Obok DeDRM (6, 7, 0) && Overdrive Link (2, 51, 0) && Prettify Cover 0.9.12
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 307, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 199, in exec_module
  File "calibre\customize\zipplugin.py", line 195, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?


How can I get the DeDRM plugin to load successfully? Thank you.


Also, though the Obok plug seemed to load, it's not appearing in on the calibre menu. Does that mean that it didn't load correctly also? 

Thank you!

**Comment by ElleKayEm** [comment]
Looks like you aren't loading 10.0.3, but an older version.

**Comment by LDReader** [comment]
I uninstalled calibre, then reinstalled calibre 6.7.1. Then I made sure I was looking at dedrm 10.0.3, and tried to load DeDRM_plugin.zip then Obok_plugin.zip. Calibre gave me no confirmations that either had been loaded . I verified that neither had loaded by scanning the list of all loaded plugins. I restarted calibre, but still neither set of plugins appeared.

Then I tried loading 10.0.3 set of plugins again. Still nothing loaded. 

What am I doing wrong?

**Comment by ElleKayEm** [comment]
I don't know.  It should ask if you're sure you want to proceed.  Then when you click yes, you should see a success message.

**Comment by LDReader** [comment]
I've received no successmessage each time I've tried loading the plugins.. 

I could de-install calibre v6.7.1  again, then install calibre v4.2.3, which I know works with the deDRM v6.7 plugins. But I would rather have up-to-date software on my PC if possible.

**Comment by ElleKayEm** [comment]
I really don't know what the issue could be.  For me, it works exactly as it always has loading previous versions.  I'm on Windows 10, calibre 6.7.1, and the 10.0.3 plugins.

**Comment by LDReader** [comment]
That's the same setup as what I have: Win10, and calibre 6.7.1. I'm frustrated as I've been trying to get this to work since last week. I have removed the installation and reinstalled many times, and it still isn't working.

**Comment by ElleKayEm** [comment]
Are you still getting an error message?  Does it ask if you want to proceed?  And then nothing?  Or what?

**Comment by LDReader** [comment]
No error message, no success message. Just nothing, after I load first the DeDRM plugin, then the Obok plugin.

**Comment by ElleKayEm** [comment]
Do you see the security risk warning where it asks if you want to proceed?

**Comment by LDReader** [comment]
No, I don't receive that message either. (Sorry, forgot to mention that.)

**Comment by ElleKayEm** [comment]
I wonder if that's hiding somehow -- off to an edge, behind something.

**Comment by LDReader** [comment]
I checked behind any and all other apps I had running. And more importantly, the plugins never appeared in my list of installed plugins.

**Comment by ElleKayEm** [comment]
Yes, I think that's because calibre is waiting for your response to proceed with loading the plugin or not.  As soon as you select a plugin file and click open, that "Are you sure?" dialog box appears.  Nothing will happen unless you answer yes or no.

**Comment by LDReader** [comment]
No dialog box appears. With the Are you sure question. I just tried it again and nothing appeared.

**Comment by ElleKayEm** [comment]
I don't know how you can resolve that.

**Comment by LDReader** [comment]
I retried several times (uninstalling, reinstalling, then reloading plugins) -- failure each time. So I've given up, and reinstalled calibre 4.2.3 and its assoc plugins. Totally frustrated, but nothing has worked so far for me with any other higher versions of calibre and the DRM plugins.

**Comment by ElleKayEm** [comment]
Try installing the 10.0.3 plugins on the older calibre and then update calibre.

**Comment by LDReader** [comment]
So, to confirm:

in calibre v4.2.3, try to load v10.0.3 drm plugins. Then deinstall v4.2.3 and install calibre v6.7.1z.

**Comment by ElleKayEm** [comment]
Since you can install plugins on the older version, load the 10.0.3 plugins in calibre 4.23.  (They are actually suppose to be compatible with older calibre versions too.)  Then just update calibre.  You should see a link at the bottom that a newer version is available.

**Comment by LDReader** [comment]
Trying what you suggested right now. Tried loading v10.0.3 and no Are you sure message. I checked, the message isn't hiding under anything. Also, was I supposed to have removed the older versions of the plugin first, or just load the most recent?

**Comment by LDReader** [comment]
And v10.0.3 didn't load. All that happened was the Apply button remained greyed out after I tried loading both of the plugins. No Are you sure message, no loaded message, and only the Discard button was enabled the whole time. So, nothing loaded.

**Comment by ElleKayEm** [comment]
I'm baffled as to why you are unable to load plugins at all on old or new versions of calibre.  I cannot reproduce the issue of not getting that "Are you sure?" prompt.  Here it is step-by-step to see if we can figure out what's going wrong:

- Download DeDRM_tools_10.0.3.zip from this page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
- Unzip DeDRM_tools_10.0.3.zip
- In calibre, Preferences > Plugins > Load plugin from file
- Navigate to the unzipped DeDRM_tools_10.0.3 folder, select DeDRM_plugin.zip, and click Open
- Click yes in the "Are you sure?" box
- Click OK on the success box
- Click Apply and then close the preferences box
- Close and restart calibre

If you're still stuck on not seeing the "Are you sure?" box, then I'm completely stumped.

**Comment by LDReader** [comment]
Oh my god!!! It worked!! :-)

I followed your instructions exactly (your instructions are what I've been doing already on my own), and it finally worked. I don't know why it didn't work until now, but it worked, and that's all I care about.

You are awesome!! Thank you so, so much!

**Comment by ElleKayEm** [comment]
Whew! I'm so glad it finally worked for whatever reason.

**Comment by LDReader** [comment]
Either way, thank you! Thank you!

**Comment by LDReader** [comment]
Okay, I was too happy too soon. DRM isn't removed. Is that because I I'm using v10.0.3 with cal v4.23? Should I install cal v6.7.1 then load a DRMed book into calibre to verify the 10.0.3 plugins are working?

**Comment by ElleKayEm** [comment]
DeDRM 10.0.3 is supposed to work with older calibre too, but I don't know how well that's been tested.  You may as well update calibre and see.  If that doesn't do it, then post a log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by LDReader** [comment]
Okay, upgraded to calibre v6.7.1, then re-uploaded the same book then two others. All three stripped of DRM successfully. 

This has been a heck of a long road, and thank you so much for all your patience and all your help.

**Comment by ElleKayEm** [comment]
Good to hear!
