### ISSUE TITLE
I can't get off the DRM of an epub achive.

### ISSUE THREAD

**Issue by Elibel97** [apprenticeharper/DeDRM_tools#2113]
ApplicationPaletteChange event ignored Using calibre Qt style: True ApplicationPaletteChange event received calibre Registro de depuración calibre 6.2.1 embedded-python: True Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE') ('Windows', '10', '10.0.19043') Python 3.10.1 Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free') Interface language: es Successfully initialized third party plugins: DeDRM (7, 2, 1) calibre 6.2.1 embedded-python: True Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE') ('Windows', '10', '10.0.19043') Python 3.10.1 Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free') Interface language: es Successfully initialized third party plugins: DeDRM (7, 2, 1) QPA platform: windows devicePixelRatio: 1.0 logicalDpi: 96.0 x 96.0 physicalDpi: 100.86162790697674 x 101.07357512953367 [0.00] Starting up...
 [0.00] Showing splash screen...
 [0.19] splash screen shown [0.19] Initializing db...
 [0.19] db initialized [0.19] Constructing main UI...
 [0.67] main UI initialized...
 [0.67] Hiding splash screen Starting QuickView DeDRM v7.2.1: Trying to decrypt 1824007725.epub DeDRM v7.2.1: Verifying zip archive integrity DeDRM v7.2.1: Error 'File is not a zip file' when checking zip archive Running file type plugin DeDRM failed with traceback:
 Traceback (most recent call last):
 File "calibre_plugins.dedrm.__init__", line 210, in ePubDecrypt File "calibre_plugins.dedrm.zipfix", line 53, in __init__ File "C:\Users\HP\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 683, in __init__ File "C:\Users\HP\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 709, in _GetContents File "C:\Users\HP\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 721, in _RealGetContents zipfilerugged.BadZipfile: File is not a zip file 
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
 File "calibre\customize\ui.py", line 178, in _run_filetype_plugins File "calibre_plugins.dedrm.__init__", line 644, in run File "calibre_plugins.dedrm.__init__", line 214, in ePubDecrypt Exception: File is not a zip file Traceback (most recent call last):
 File "calibre\ebooks\metadata\epub.py", line 160, in get_zip_reader File "calibre\utils\zipfile.py", line 774, in __init__ File "calibre\utils\zipfile.py", line 809, in _GetContents File "calibre\utils\zipfile.py", line 824, in _RealGetContents calibre.utils.zipfile.BadZipfile: File is not a zip file 
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
 File "calibre\customize\ui.py", line 435, in get_file_type_metadata File "calibre\customize\builtins.py", line 176, in get_metadata File "calibre\ebooks\metadata\epub.py", line 216, in get_metadata File "calibre\ebooks\metadata\epub.py", line 163, in get_zip_reader File "calibre\utils\localunzip.py", line 263, in __init__ File "calibre\utils\localunzip.py", line 239, in _extractall ValueError: Not a ZIP file [13.70] splash screen hidden [13.70] Started up in 13.70 seconds with 1 books stdout+stderr from file dialog helper: [b'', b''] piped data from file dialog helper: [b'\x9c\x99D\xd08a\x0e{\x7f\xb9\xea\x9d\x1c\x92\xf7\x98\x0e\x97\xba\xaf\xb4`\xbc\x19\x87\xf8\x14\xd3\x1a^G\x9f', b'C:\\Users\\HP\\Downloads\\1824007725.epub'] Added 1824007725 to db in: 1.Added 1 books in 1.5 seconds
 

### DeDRM: `Version`: DeDRM_tools_7.2.1

I coudn't get off the DRM  and I got this epub from ridibooks.

Thank you for all of your services.

**Comment by ElleKayEm** [comment]
For calibre 6.x, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by noDRM** [comment]
Ridibooks EPUBs aren't supported by this plugin, updating to 10.0.3 is not going to help.
