### ISSUE TITLE
Unable to remove DRM [Bug Report Included]

### ISSUE THREAD

**Issue by HighSteam** [apprenticeharper/DeDRM_tools#2118]
I am unable to remove a DRM of a book i bought thru kindle. I need to read it on Calibre due to me wanting to use my desired formatting for easy read. it is an AZW book. My OS is Fedora Linux. Latest version of Calibre. Latest DeDRM. Bug report below:

```
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B003ODIZL6_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.42.0_tmp_nk1oitif/0550_m9jplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 190, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 190, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib64/calibre/calibre/customize/zipplugin.py", line 190, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
[12.68] splash screen hidden
[12.68] Started up in 12.68 seconds with 32 books
Added The New Oxford American Dictionary to db in: 0.1
Added 1 books in 1.0 seconds

```

**Comment by ElleKayEm** [comment]
For calibre 6.x, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Use the official Linux calibre:  https://calibre-ebook.com/download_linux

Finally, how are you downloading the book?  This post describes all the methods that will get you a book that can be decrypted: https://www.mobileread.com/forums/showthread.php?t=283371

For Linux, it can be a bit tricky unless you have an E-ink Kindle.
