### ISSUE TITLE
[QUESTION] Can you help me remove DRM

### ISSUE THREAD

**Issue by tashpinsent** [apprenticeharper/DeDRM_tools#2121]
Purchased book on Amazon, downloaded as Second-Hand Dog.azw3 wanted to convert as PDF to read on the computer. Loaded into Calibre, added the plugin, restarted and it would not convert due to DRM. First time I heard of it. Bummed. Certainly would appreciate your help!! :)
My system information:
## Log

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
Traceback (most recent call last):
  File "calibre_plugins.koboutilities.common_utils", line 17, in <module>
ImportError: cannot import name 'QRegExpValidator' from 'qt.core' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\qt\core.pyc)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 137, in __init__
  File "calibre\gui2\ui.py", line 155, in init_iaction
  File "calibre\customize\__init__.py", line 624, in load_actual_plugin
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 208, in exec_module
  File "calibre_plugins.koboutilities.action", line 57, in <module>
  File "calibre\customize\zipplugin.py", line 208, in exec_module
  File "calibre_plugins.koboutilities.dialogs", line 19, in <module>
  File "calibre\customize\zipplugin.py", line 208, in exec_module
  File "calibre_plugins.koboutilities.common_utils", line 22, in <module>
ModuleNotFoundError: No module named 'PyQt4'
calibre Debug log
calibre 6.3  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Books (1, 8, 0) && Kobo Utilities (2, 12, 3)
calibre 6.3  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Books (1, 8, 0) && Kobo Utilities (2, 12, 3)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.6430769230769 x 133.90057803468207
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.77] main UI initialized...
[0.77] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Second-Hand Dog.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Second-Hand Dog
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\tashp\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[15.97] splash screen hidden
[15.97] Started up in 15.97 seconds with 27 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xcf\xcb\tC\xd9\xebl\xa9\xc0\xb1\xaa\x92\x0eJ\xf2\x89\xe4W fw\xdcl\xd0\xa8/\xba\xee\x0e\xec\x99\xd4', b'C:\\Users\\tashp\\Downloads\\Second-Hand Dog.azw3']
Added Second-Hand Dog to db in: 0.2
Added 1 books in 0.9 seconds
Worker Launch took: 0.11 seconds
Job: 0 Convert book 1 of 1 (Second-Hand Dog) finished
Convert book 1 of 1 (Second-Hand Dog)

	DeDRM v7.2.1: Trying to decrypt i8p1_tfe.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Second-Hand Dog
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\tashp\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  cover: 'C:\\Users\\tashp\\AppData\\Local\\Temp\\calibre_7lmfo3hq\\f4akg7mz.jpeg'

	  verbose: 2

	  pdf_mono_family: 'Courier New'

	  pdf_serif_family: 'Arial'

	  read_metadata_from_opf: 'C:\\Users\\tashp\\AppData\\Local\\Temp\\calibre_7lmfo3hq\\4vexu3no.opf'

	  output_profile: 'ipad3'

	  pdf_sans_family: 'Arial'

	Resolved conversion options

	calibre version: 6.3.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\tashp\\AppData\\Local\\Temp\\calibre_7lmfo3hq\\f4akg7mz.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000024AB10CD150>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x0000024AB10CC3A0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier New',

	 'pdf_mono_font_size': 16,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'Arial',

	 'pdf_serif_family': 'Arial',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\tashp\\AppData\\Local\\Temp\\calibre_7lmfo3hq\\4vexu3no.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	DeDRM v7.2.1: Trying to decrypt i8p1_tfe.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Second-Hand Dog
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\tashp\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook

	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\tashp\AppData\Local\Temp\calibre_7lmfo3hq\i8p1_tfe.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 82, in <module>

	  File "site.py", line 77, in main

	  File "site.py", line 49, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Secon
Hand Dog

```
</details>

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3.  If the book is tied to an E-ink Kindle (not a Fire), then enter that Kindle's serial number into DeDRM's customization.

**Comment by tashpinsent** [comment]
> For calibre 6, use DeDRM 10.0.3. If the book is tied to an E-ink Kindle (not a Fire), then enter that Kindle's serial number into DeDRM's customization.

IT WORKED!!! THANK YOU!!! Yaaaay!!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by tashpinsent** [comment]
Oops! Now I feel silly!! Will do! Thanks again! <3
