### ISSUE TITLE
[QUESTION] DeDRM not working on Linux

### ISSUE THREAD

**Issue by BillM10** [apprenticeharper/DeDRM_tools#2124]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## DeDRM not working on Linux
Using Linux Mint on a converted Chromebook.  Worked fine using previous versions of Calibre and DeDRM plug-in on Gallium distro.  I switched to Linux Mint as the latest version of Calibre wouldn't run on Gallium.  Ebook files initially obtained using Kindle for PC running on linux using Wine but removal also failed using files downloaded on a Windows PC

## Log
<details><summary>tmpv0ip9zsu.txt</summary>

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.3  embedded-python: True
Linux-5.4.0-124-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.4.0-124-generic', '#140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022')
Python 3.10.1
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && Kindle hi-res covers (0, 5, 0)
calibre 6.3  embedded-python: True
Linux-5.4.0-124-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.4.0-124-generic', '#140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022')
Python 3.10.1
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && Goodreads (1, 5, 3) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 64, 0) && KFX Output (1, 64, 0) && Kindle hi-res covers (0, 5, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 111.79288025889967 x 112.1103448275862
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
[1.25] main UI initialized...
[1.25] Hiding splash screen
Starting QuickView
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 871, resource id: 8448580, major code: 40 (TranslateCoords), minor code: 0
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /home/billm/OneDrive/Books/B00O13IY1Y_EBOK.azw
[14.14] splash screen hidden
[14.14] Started up in 14.14 seconds with 149 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=73400343', '--filename=/home/billm/OneDrive/Books/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf *.kfx-zip *.azw8', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.3: Trying to decrypt B00O13IY1Y_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Last Day of Christmas: The Fall of Jack Parlabane (short story)
Found 0 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.8 seconds
MESA-INTEL: warning: Haswell Vulkan support is incomplete
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python3.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/billm/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/billm/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added The Last Day of Christmas: The Fall of Jack Parlabane (short story) to db in: 0.5
Added 1 books in 5.1 seconds
```
</details>

**Comment by ElleKayEm** [comment]
Looks like Python needs to be installed under Wine in order to retrieve the key from that installation.  Remember the books and key need to be from the same installation of Kindle for PC.

**Comment by auspex** [comment]
Nope. Python 3 is installed and
```
$ WINEPREFIX="/home/derek/.local/share/wineprefixes/k2" wine py.exe -3
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
```
and yet, same errior.

Then I found that if I set the prefix in the plugin config (even though nothing says I need to), I got past that--Python3 is found--but 
```
DeDRM v10.0.9: Running kindlekey.py under Wine
Traceback (most recent call last):
  File "Z:\home\derek\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 49, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'
```
So, now need to figure out how to install the cryptography, too

**Comment by auspex** [comment]
```
pip install pycryptodome
```
(after following the instructions to upgrade pip, itself) seems to have fixed _that_ error, and then
```
DeDRM v10.0.9: Running kindlekey.py under Wine
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\derek\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\users\derek\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1124073472' and UserName 'derek'
Saved a key to Z:\home\derek\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
DeDRM v10.0.9: Found and decrypted 1 key file
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: a1h5dajq
Got DSN key from database key_0
Found 1 keys to try after 1.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.95903e8d-65a2-48b6-bc59-144feadbeb97.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/derek/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/derek/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/home/derek/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key
```
So, I think I have to accept that this is just undecryptable

**Comment by auspex** [comment]
Hallelujah!

I had a thought, after the last post: Where did that `amzn1.drm-voucher.v1.95903e8d-65a2-48b6-bc59-144feadbeb97.voucher` file come from? I deleted everything in `My Kindle Contents`, went back into Kindle for Pc and downloaded the book again, and then tried to import it, and it worked. So, it would seem the important details are to:

- set the Wine Prefix in the DeDrm config
- install python3
- install pycryptodome

**Comment by ElleKayEm** [comment]
Looks like the key found is from an older version of Kindle for PC.  Yet that book is KFX.  Was it downloaded with a different installation of Kindle for PC?  If so, that's why the key didn't work for that book.  Each app installation has a unique key even if they're logged into the same Amazon account.

ETA: Ah, you figured it out.  Book that didn't work must have been downloaded with a previous installation.

**Comment by auspex** [comment]
It probably was--I have been trying with four different versions of Kindle for PC--but the problem is that none of them can actually decode the file until you have installed both `python3` and `pycryptodome` into your wineprefix, and the DeDRM plugin _won't_ get the right prefix unless you specify it in the plugin config.
