### ISSUE TITLE
DeDRM not working - DeDrm 10.0.3 Calibre 6.30 Adobe Electronic Doc 4.5 PDF

### ISSUE THREAD

**Issue by avidd3** [apprenticeharper/DeDRM_tools#2126]
Been trying to remove drm from PDF downloaded from NetGallery with now joy here is the log. Any help is vey appreciated.

Here is the log:

calibre, version 6.3.0
Debug mode: <p>You have started calibre in debug mode. After you quit calibre, the debug log will be available in the file: /var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/T/tmplxmxtjil.txt<p>The log will be displayed automatically.

calibre, version 6.3.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (zepubDecide and Conquer)

Convert book 1 of 1 (zepubDecide and Conquer)
DeDRM v10.0.3: Trying to decrypt cu47r54w.pdf
DeDRM v10.0.3: cu47r54w.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: cu47r54w.pdf is a PDF ebook (EBX) for UUID 14557bc3-7d7c-4420-b7c7-968d0300ccba
DeDRM v10.0.3: Trying encryption key default_key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 724, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with key default_key after 0.2 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.3 seconds
DeDRM v10.0.3: Finished after 0.3 seconds
Conversion options changed from defaults:
  read_metadata_from_opf: '/var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_0e70jf99/95v3rvcy.opf'
  verbose: 2
  output_profile: 'ipad3'
Resolved conversion options
calibre version: 6.3.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x110717d60>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_images': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x110714070>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_0e70jf99/95v3rvcy.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt cu47r54w.pdf
DeDRM v10.0.3: cu47r54w.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: cu47r54w.pdf is a PDF ebook (EBX) for UUID 14557bc3-7d7c-4420-b7c7-968d0300ccba
DeDRM v10.0.3: Trying encryption key default_key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 724, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v10.0.3: Finished after 0.1 seconds
InputFormatPlugin: PDF Input running
on /var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_0e70jf99/cu47r54w.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 51, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by ElleKayEm** [comment]
See if deleting your Adobe key from DeDRM's customization and then re-adding the book to calibre will work (letting DeDRM automatically retrieve your key).  People have been having problems lately when there is already a saved key.  ADE is authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

**Comment by avidd3** [comment]
Thanks for the quick response!

Tried what you suggested...no joy. (see the log below)

What did work was removing the drm from a kindle version (from the
same source)

I am so pleased that I was able to convert the document, but I don't always
have access to another format, So it would be great if we could solve this
issue.

Thanks, again, for your help with this.

Respectfully,

Michael
917.837.0402

calibre, version 6.3.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (xDecide and Conquer)

Convert book 1 of 1 (xDecide and Conquer)
DeDRM v10.0.3: Trying to decrypt pqrxi6s1.pdf
DeDRM v10.0.3: pqrxi6s1.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: pqrxi6s1.pdf is a PDF ebook (EBX) for UUID
14557bc3-7d7c-4420-b7c7-968d0300ccba
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after
0.1 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 2094, in __init__
    doc.initialize(userkey, inept)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.3 seconds
DeDRM v10.0.3: Finished after 0.3 seconds
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'ipad3'
  read_metadata_from_opf:
'/var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_y0wdn41u/l9fdlhvk.opf'
Resolved conversion options
calibre version: 6.3.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

"'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))',
"
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'docx_custom_page_size': None,
 'docx_no_cover': False,
 'docx_no_toc': False,
 'docx_page_margin_bottom': 72.0,
 'docx_page_margin_left': 72.0,
 'docx_page_margin_right': 72.0,
 'docx_page_margin_top': 72.0,
 'docx_page_size': 'letter',
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at
0x111eefd90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at
0x111eec070>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf':
'/var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_y0wdn41u/l9fdlhvk.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt pqrxi6s1.pdf
DeDRM v10.0.3: pqrxi6s1.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: pqrxi6s1.pdf is a PDF ebook (EBX) for UUID
14557bc3-7d7c-4420-b7c7-968d0300ccba
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after
0.0 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 2094, in __init__
    doc.initialize(userkey, inept)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File
"/Users/noscreen/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py",
line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v10.0.3: Finished after 0.1 seconds
InputFormatPlugin: PDF Input running
on
/var/folders/kw/3wsmssqj1yg1f0jv_mq447h80000gn/C/calibre_6.3.0_tmp_y0wdn41u/pqrxi6s1.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 38, in
gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/pdf_input.py", line 51, in convert
  File "calibre/ebooks/pdf/pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by ElleKayEm** [comment]
Another thing to look at would be the ACSM Input plugin: https://www.mobileread.com/forums/showthread.php?t=341975

But otherwise noDRM will have to look at this.  Not sure if they will see it over here on Apprentice Harper's repo.  I suggest posting an issue over at [noDRM's](https://github.com/noDRM/DeDRM_tools)  with a log of adding the book to calibre (not this conversion log).

**Comment by avidd3** [comment]
got it thanks.

Respectfully,

Michael
917.837.0402

**Comment by noDRM** [comment]
Really hard to say just from seeing this log, but this looks like a broken PDF where the DRM wasn't applied correctly. Can ADE successfully open that PDF file?

**Comment by mk14steve** [comment]
> See if deleting your Adobe key from DeDRM's customization and then re-adding the book to calibre will work (letting DeDRM automatically retrieve your key). People have been having problems lately when there is already a saved key. ADE is authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

That worked for me.

**Comment by mk14steve** [comment]
I did the suggested fix from ElleKayEm and the DeDRM did automatically retrieve my key. What would be useful to know is where does it retrieve it from?

**Comment by ElleKayEm** [comment]
From ADE or it can also get it from the DeACSM plugin.
