### ISSUE TITLE
[QUESTION] Error message

### ISSUE THREAD

**Issue by ralphsun73221** [apprenticeharper/DeDRM_tools#2127]
There was a mistake when I opened obok DeDRM.

```
calibre, version 6.3.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.3  embedded-python: True
macOS-12.5.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101')
Python 3.10.1
OSX: ('12.5.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 0) && Obok DeDRM (7, 2, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
    dlg = SelectionDialog(self.gui, self, books)
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
    self.books_table.populate_table(self.books)
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
    self.populate_table_row(row, book)
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
    status_cell = IconWidgetItem(None, icon, val)
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
    ReadOnlyTableWidgetItem.__init__(self, text)
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
    QTableWidgetItem.__init__(self, text, QTableWidgetItem.UserType)
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'
```

**Comment by ElleKayEm** [comment]
For calibre 6, update to the 10.0.3 versions of Obok and DeDRM: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
