### ISSUE TITLE
Unable to remove Amazon DRM

### ISSUE THREAD

**Issue by MichaelBrazier** [apprenticeharper/DeDRM_tools#2128]
I'm running the Kindle PC app, version 1.38, on a Windows 10 OS. Importing a KFX file into Calibre 6.3 with the DeDRM plugin did not remove the encryption. Debug log follows.

Yes, I know Kindle 1.17 will download unencrypted files, but recently Amazon's servers stopped allowing 1.17 to log in, at least from my PC.
---
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.41395348837209
[0.00] Starting up...
[0.02] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.66] main UI initialized...
[0.66] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing C:/Users/micha/Documents/My Kindle Content/B0BCCZ2PF3_EBOK/B0BCCZ2PF3_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\micha\AppData\Local\Temp\calibre_hhn2zlh_\bkqid2ob.kfx-zip
DeDRM v7.2.1: Trying to decrypt bkqid2ob.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: bkqid2ob
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c4e1e2f5-4d22-4d90-9107-b6edf9a314b1.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\micha\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\micha\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\micha\AppData\Local\Amazon\Kindle\storage\.kinf2011
[6.92] splash screen hidden
[6.92] Started up in 6.92 seconds with 453 books
Decrypted key file using IDString '2801373803' and UserName 'micha'
Couldn't decrypt file.
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: bkqid2ob
Got DSN key from database default_key_1
Found 1 keys to try after 1.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c4e1e2f5-4d22-4d90-9107-b6edf9a314b1.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\micha\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging C:\Users\micha\AppData\Local\Temp\calibre_hhn2zlh_\bkqid2ob.kfx-zip
Processing container: B0BCCZ2PF3_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BCCZ2PF3_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\micha\AppData\Local\Temp\calibre_Added Friends and Family (Fall of the Alliance Book 9)

**Comment by MichaelBrazier** [comment]
Upgrading DeDRM to 10.0.3 did not fix the problem.

**Comment by j-howell** [comment]
DRM removal for KFX only works if the book was downloaded using Kindle for PC version 1.26 or earlier.

See [Dealing with Kindle for PC/Mac 1.19 (and later) and KFX in calibre](https://www.mobileread.com/forums/showthread.php?t=283371) for information on what is possible.

**Comment by MichaelBrazier** [comment]
Is there any progress on defeating what Amazon did to lock down Kindle for PC after 1.26?

At least 1.26 does still work. I suppose you can take this as a warning that 1.17 may be generally unusable now, forcing everyone to deal with the KFX format.

**Comment by j-howell** [comment]
Others have reported problems getting version 1.17 to sign in. The post I linked lists workarounds that have worked for some.

There has been no reported progress in defeating the newer KFX DRM. Amazon aggressively protects KFX by having dozens of alternative DRM schemes already in place, ready to be switched on as soon as the current one in use is broken.

**Comment by ElleKayEm** [comment]
Yes, DeDRM has been updated twice to deal with KFX after 1.26.  Both times Amazon broke it by the next day.

When I had an issue logging in to Kindle for PC 1.17, I was able to fix it by deleting the registry key folder HKEY_CURRENT_USER\SOFTWARE\Amazon.

And there are more ways to avoid KFX at the link j-howell gave.

**Comment by j-howell** [comment]
> When I had an issue logging in to Kindle for PC 1.17, I was able to fix it by deleting the registry key folder HKEY_CURRENT_USER\SOFTWARE\Amazon.

That will cause problems if you have other Amazon software installed. It is probably safer to delete HKEY_CURRENT_USER\SOFTWARE\Amazon\Kindle.

**Comment by jantoniosf** [comment]
Hello,
I have the same problem on Linux, but I am using an ebook downloaded from the site with a serial on my kindle paperwhite, see the Calibre log:

calibre 5.12  embedded-python: False is64bit: True
Linux-5.10.0-17-amd64-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.10.0-17-amd64', '#1 SMP Debian 5.10.136-1 (2022-08-13)')
Python 3.9.2
Interface language: pt_BR
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.17] main UI initialized...
[1.17] Hiding splash screen
Starting QuickView
[1.45] splash screen hidden
[1.46] Started up in 1.46 seconds with 107 books
DeDRM v7.2.1: Trying to decrypt A fábrica de cretinos digitais.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.12.0_tmp_spva3kc7/9gkc6ud3plugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Added A fábrica de cretinos digitais to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment]
@jantoniosf Your issue is here:

> calibre 5.12 embedded-python: False

Use the official Linux calibre: https://calibre-ebook.com/download_linux
