### ISSUE TITLE
DRM PDF doesn't work

### ISSUE THREAD

**Issue by Mlnerva** [apprenticeharper/DeDRM_tools#2139]
Procesador	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.20 GHz
RAM instalada	12,0 GB (11,7 GB usable)
Edición	Windows 11 Home
Versión	21H2
Instalado el	‎27/‎06/‎2022
Versión del sistema operativo	22000.856
Experiencia	Paquete de experiencia de características de Windows 1000.22000.856.0

DRM PDF downloaded from eBiblio Canarias, Spain and opened with Adobe Digital Edition

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
Traceback (most recent call last):
  File "calibre\gui2\ui.py", line 137, in __init__
  File "calibre\gui2\ui.py", line 155, in init_iaction
  File "calibre\customize\__init__.py", line 624, in load_actual_plugin
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 204, in exec_module
  File "calibre_plugins.obok_dedrm.action", line 24, in <module>
  File "calibre\customize\zipplugin.py", line 204, in exec_module
  File "calibre_plugins.obok_dedrm.dialogs", line 30, in <module>
  File "calibre\customize\zipplugin.py", line 204, in exec_module
  File "calibre_plugins.obok_dedrm.utilities", line 10, in <module>
ModuleNotFoundError: No module named 'StringIO'
calibre Registro de depuración
calibre 6.4  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (6, 5, 4)
calibre 6.4  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (6, 5, 4)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Suplemento El País - 1192022-1.pdf
DeDRM v7.2.1: Suplemento El País - 1192022-1.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
error writing pdf: max() arg is an empty sequence
DeDRM v7.2.1: Failed to decrypt with new default key after 0.1 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x0000022D869BD7E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000022D869BD7E0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[3.53] splash screen hidden
[3.53] Started up in 3.53 seconds with 0 books
Added Suplemento El País to db in: 0.1
Added 1 books in 0.9 seconds
[tmp1dahc7g0.txt](https://github.com/apprenticeharper/DeDRM_tools/files/9549130/tmp1dahc7g0.txt)
[tmp1dahc7g0.txt](https://github.com/apprenticeharper/DeDRM_tools/files/9549141/tmp1dahc7g0.txt)

**Comment by ElleKayEm** [comment]
For calibre 6.x, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by Mlnerva** [comment]
It's works! thank you so much!

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/09/22,
18:59:16

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by Mlnerva** [comment]
Superfast answered and fixed! Really happy!
