### ISSUE TITLE
type object 'QTableWidgetItem' has no attribute 'UserType'

### ISSUE THREAD

**Issue by joychentw** [apprenticeharper/DeDRM_tools#2146]
Hi, I am trying to import books from KOBO but when clicked on the Obok DeDRM shortcut, the following message popped up:

```
calibre, version 6.5.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.5  embedded-python: True
macOS-12.5.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('12.5.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
    dlg = SelectionDialog(self.gui, self, books)
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
    self.books_table.populate_table(self.books)
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
    self.populate_table_row(row, book)
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
    status_cell = IconWidgetItem(None, icon, val)
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
    ReadOnlyTableWidgetItem.__init__(self, text)
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
    QTableWidgetItem.__init__(self, text, QTableWidgetItem.UserType)
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

```

**Comment by ElleKayEm** [comment]
Update to Obok 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by joychentw** [comment]
Fixed. Thank you!

**Comment by roeters-tech** [comment]
I'm having similar issues. Got the same message as above, updated the plugins but now I get:
"not added because user CHOSE not to insert the new EPUB format or all existing calibre entries HAD an EPUB format already".  

Any suggestions?

**Comment by ElleKayEm** [comment]
Do you have something with the same title?  In Obok 10.0.9 customization you can set Obok to add a new entry.

**Comment by roeters-tech** [comment]
I do not, I'm trying different books, all with the same result. I have version 10.0.3, could that be the problem?

**Comment by ElleKayEm** [comment]
I only ever saw that message that if I was trying to add a book with the same title (even if it was actually a different book).  Try 10.0.9 with add new entry set.
