### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by merritt83** [apprenticeharper/DeDRM_tools#2148]
Just downloaded Calibre and DeDRM today. Downloaded book from Kindle website into download folder. I can see the name and author or the book when it is dragged into Calibre. But after installing plugins I still cannot access the book. Says it is protected by DRM.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.5  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
calibre 6.5  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.84] main UI initialized...
[0.84] Hiding splash screen
Starting QuickView
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
MTP: Loading filesystem metadata...
MTP: Ignored object: Music
MTP: Ignored object: Ringtones
MTP: Ignored object: Alarms
MTP: Ignored object: Notifications
MTP: Ignored object: Pictures
MTP: Ignored object: Movies
MTP: Ignored object: DCIM
MTP: Ignored object: Android/media
MTP: Ignored object: Android/obb
MTP: Ignored object: Android/data/com.amazon.avod
MTP: Ignored object: Android/data/com.amazon.venezia
MTP: Ignored object: Android/data/com.amazon.device.backup
MTP: Ignored object: Android/data/com.amazon.mp3
MTP: Ignored object: Android/data/com.amazon.windowshop
MTP: Ignored object: Android/data/com.amazon.device.software.ota
MTP: Ignored object: Android/data/com.amazon.securitysyncclient
MTP: Ignored object: Android/data/com.amazon.photos
MTP: Ignored object: Android/data/com.amazon.ags.app
MTP: Ignored object: Android/data/com.amazon.zico
MTP: Ignored object: Android/data/com.amazon.firelauncher
MTP: Ignored object: Android/data/amazon
MTP: Ignored object: Android/data/com.amazon.cloud9
MTP: Ignored object: Android/data/com.kingsoft.office.amz
MTP: Ignored object: Android/data/com.here.odnp.service
MTP: Ignored object: Android/data/com.amazon.webapp
MTP: Ignored object: Android/data/com.amazon.kindle.otter.oobe
MTP: Ignored object: Android/data/com.amazon.dee.app
MTP: Ignored object: Android/data/com.audible.application.kindle
MTP: Ignored object: Android/data/com.goodreads.kindle
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DeDRM v7.2.1: Trying to decrypt The Gene Keys.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Gene Keys
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\zelan\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
MTP: Filesystem metadata loaded in 0.763061 seconds (1646 objects)
MTP: Using cached metadata for Internal storage/Android/data/com.amazon.kindle/files/Books/B003ODIZL6/B003ODIZL6_EBOK.prc
MTP: Using cached metadata for Internal storage/Download/The_SHTF_Medicinal_Plant_Map_That_Should_Be_in_Your_Survival_Kit.pdf
MTP: Using cached metadata for Internal storage/Download/Attachments/Handbook-of-medicinal-herbs-2ed-2002-Duke.pdf
MTP: Using cached metadata for Internal storage/Documents/Lord of the Rings, The - J.R.R. Tolkien.mobi
MTP: Using cached metadata for Internal storage/Documents/Angry Tide [Poldark 7], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Four Swans [Poldark 6], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Loving Cup [Poldark 10], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Miller's Dance [Poldark 9], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Twisted Sword [Poldark 11], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Ross Poldark [Poldark 1] - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Bella Poldark [Poldark 12] - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Black Moon [Poldark 5], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Demelza [Poldark 2] - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Jeremy Poldark [Poldark 3] - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Warleggan [Poldark 4] - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Stranger From The Sea [Poldark 8], The - Winston Graham.mobi
MTP: Using cached metadata for Internal storage/Documents/Feast for Crows-4, A - Martin, George RR.mobi
MTP: Using cached metadata for Internal storage/Documents/Storm of Swords-3, A - Martin, George RR.mobi
MTP: Using cached metadata for Internal storage/Documents/Clash of Kings-2, A - Martin, George RR.mobi
MTP: Using cached metadata for Internal storage/Documents/Game of Thrones-1, A - Martin, George RR.mobi
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 20
DeviceJob: set_books_in_library finished: time= 0.0009903907775878906
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
[4.45] splash screen hidden
[4.45] Started up in 4.45 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'9\x07=\xda*\xfds\xd1\xe0*W\xb1}5!2[|\xa4\xe8\x7f\xa9\xadI\xdb\xda\xb4\xc8*Nf;', b'C:\\Users\\zelan\\Downloads\\The Gene Keys.azw3']
Added The Gene Keys to db in: 0.1
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
For calibre 6.x, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device.  You also need to add that Kindle's serial number into DeDRM's customization.  After you've done that, restart calibre.  Delete and re-add your book to calibre.

**Comment by merritt83** [comment]
It doesn’t give me the option to download it as an e-ink because I don’t have a Kindle e-reader. I only have a Kindle Fire. I would need to purchase that device in order to download it in that manner. Also, when I try to upload the book through USB connection, none of the folders have any content in them, even though I have 65 books. I don’t know how to see those books through my PC. Kelly From: ElleKayEmSent: Thursday, September 29, 2022 4:05 AMTo: apprenticeharper/DeDRM_toolsCc: merritt83; AuthorSubject: Re: [apprenticeharper/DeDRM_tools] DeDRM not working (Issue #2148) For calibre 6.x, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device. You also need to add that Kindle's serial number into DeDRM's customization. After you've done that, restart calibre. Delete and re-add your book to calibre.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, you can use an older version of Kindle for PC.  See this post for details: https://www.mobileread.com/forums/showthread.php?t=283371
