### ISSUE TITLE
Failing to remove DRM for Kindle for PC downloaded AZW files

### ISSUE THREAD

**Issue by naidje** [apprenticeharper/DeDRM_tools#2151]
## Details
Hello. I am running Calibre on xUbuntu 22.04.1, and getting my kindle ebooks through Kindle For PC on wine. However, I can't seem to get DeDRM to successfully decrypt my AZW files, no matter what I try. 
kindlekey.py seems to be able to generate my keyfile no problem. But then it fails to decrypt upon importing the ebook.

## log output
```log
naidje@naidje:~$ calibre
Failed to initialize plugin: '/home/naidje/.config/calibre/plugins/BOL_NL.zip'
Using QT6
Ya existen las librerias mutagen y rarfile
Failed to initialize plugin: '/home/naidje/.config/calibre/plugins/BOL_NL.zip'
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /home/naidje/.wine/drive_c/users/naidje/Documents/My Kindle Content/B08Y178MSB_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.3: Trying to decrypt B08Y178MSB_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Visitor (Animorphs Graphix #2)
Got DSN key from database kindlekey2
Found 5 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 5 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.8 seconds
0090:fixme:wineusb:query_id Unhandled ID query type 0x5.
0090:fixme:wineusb:query_id Unhandled ID query type 0x5.
0090:fixme:wineusb:query_id Unhandled ID query type 0x5.
0090:fixme:wineusb:query_id Unhandled ID query type 0x5.
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0110:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0063F350
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running kindlekey.py under Wine
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\naidje\Local Settings\Application Data
Found K4PC 1.25+ kinf2018 file: C:\users\naidje\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3887632206' and UserName 'naidje'
Saved a key to Z:\home\naidje\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
0130:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0063F350
DeDRM v10.0.3: Found and decrypted 1 key file
DeDRM v10.0.3: Ultimately failed to decrypt after 4.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/naidje/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/naidje/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 5 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 4.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
Yeah, it doesn't seem like that key and that book are working together.  They are both definitely from the same installation of Kindle for PC?  You haven't had to reinstall or log in again since downloading this copy of the book?
