### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by mariusmmmm** [apprenticeharper/DeDRM_tools#2156]
DRM is not being removed when I try to convert the book. I tried with all calibre and plugin versions.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.6.1  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.6.1  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 126.26019417475726 x 126.12413793103448
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.81] main UI initialized...
[0.81] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Cincizeci-de-cuvinte-pentru-ploaie.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\Daniela\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
[5.11] splash screen hidden
[5.11] Started up in 5.11 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'3\x92\x9d&\x96\xc1\x8f\x17\xc6\x1f\xd7\xbcN\x9c\xd5(E\xf3\xa1\x15\xf1\xb3t\xdd\x8b\xda.\xa2\x879o\x96',

**Comment by ElleKayEm** [comment]
As the log says:

> LCP DRM removal no longer supported due to a DMCA takedown request.
