### ISSUE TITLE
[QUESTION] DeDRM did not find adobe key

### ISSUE THREAD

**Issue by mepi0011** [apprenticeharper/DeDRM_tools#2159]
## Log
<details><summary>calibre output on Konsole</summary>

```log
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005  
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005  
0098:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005  
00d8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021F350
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running adobekey.py under Wine
adobekey.py v7.4
Copyright © 2009-2020 i♥cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "/home/me/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 625, in <module>
    sys.exit(cli_main())
  File "/home/me/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 542, in cli_main
    keys, names = adeptkeys()
  File "/home/me/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 347, in adeptkeys
    keykey = CryptUnprotectData(device, entropy)
  File "/home/me/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 327, in CryptUnprotectData
    raise ADEPTError("Failed to decrypt user key key (sic)")
__main__.ADEPTError: Failed to decrypt user key key (sic)
0128:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021F350
DeDRM v10.0.3: Wine subprocess call error: 1
DeDRM v10.0.3: Found and decrypted 0 key files
```
</details>

I need help to get DeDRM 10.0.3 running.  
When I click on the green "+" button to add a new adobe key, nothing happens (No info screen pops up).  
I run addobe digital edition 4.5.11on wine (Windows7 / 32bit). For ADE I use a own WINEPREFIX (/home/me/.local/share/wineprefixes/AdobeDigitalEdition/). The complete path to the prefix I filled in at the DeDRM plugin in Calibre.

Any idea what I do wrong?

**Comment by ElleKayEm** [comment]
Try adding a Adobe DRM book to calibre and let DeDRM automatically retrieve the key.

**Comment by mepi0011** [comment]
I get similar error output:

`
DeDRM v10.0.3: Trying to decrypt xxx.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: xxx.epub is a secure Adobe Adept ePub for UUID 98fx3d26-dd07-40c1-bee-1a6c4345a2e
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0090:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00dc:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021F350
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running adobekey.py under Wine
adobekey.py v7.4
Copyright © 2009-2020 i♥cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "/home/kirsten/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 625, in <module>
    sys.exit(cli_main())
  File "/home/kirsten/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 542, in cli_main
    keys, names = adeptkeys()
  File "/home/kirsten/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 347, in adeptkeys
    keykey = CryptUnprotectData(device, entropy)
  File "/home/kirsten/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 327, in CryptUnprotectData
    raise ADEPTError("Failed to decrypt user key key (sic)")
__main__.ADEPTError: Failed to decrypt user key key (sic)
0130:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0021F350
DeDRM v10.0.3: Wine subprocess call error: 1
DeDRM v10.0.3: Found and decrypted 0 key files
DeDRM v10.0.3: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

`

**Comment by ElleKayEm** [comment]
ADE is authorized with your Adobe ID?

**Comment by mepi0011** [comment]
Hi @ElleKayEm,
yes, ADE is authorized with my Adobe ID.
With ADE I can import acsm files and read the downloaded epub.

**Comment by ElleKayEm** [comment]
A workaround might be using the ACSM plugin: https://www.mobileread.com/forums/showthread.php?t=341975

You also might want to post an issue over at [noDRM's repo](https://github.com/noDRM/DeDRM_tools).  Not sure if they'll see it here at Harper's old repo.
