### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by tobiafccn** [apprenticeharper/DeDRM_tools#2161]

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by tobiafccn** [comment]
still don't working 
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Log di debug
calibre 6.7.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.7.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.48370927318295 x 82.13173652694611
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Key '' for shortcut Book list header menu is already used by Gestisci categorie, ignoring
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Bitcoin-Revolution.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\Tobia\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
[8.19] splash screen hidden
[8.19] Started up in 8.19 seconds with 0 books
Added Bitcoin Revolution to db in: 0.3
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
LCP DRM removal no longer supported due to a DMCA takedown request.
