### ISSUE TITLE
File is not KFX format

### ISSUE THREAD

**Issue by hungpham2411** [apprenticeharper/DeDRM_tools#2165]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## 
I tried to follow instruction to remove DRM so I can convert .azw format to .epub format but it wasn't successful. Calibre says "File is not KFX format". Does it mean this file is unable to remove DRM?

## Log
<details><summary>Start Calibre from command line and Add .azw file</summary>

```log
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /path/to/file/The New Oxford American Dictionary.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v7.2.1: Trying to decrypt The New Oxford American Dictionary.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.37.0_tmp_e1t6ng85/fxrqqddyplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```
</details>

**Comment by ElleKayEm** [comment]
It's actually better that it's not KFX.  But if that's the dictionary that came on your Paperwhite, those aren't decryptable.

Also this is an issue:

> ModuleNotFoundError: No module named 'Crypto'

Assume you're not using the official calibre with its embedded Python.

**Comment by hungpham2411** [comment]
> It's actually better that it's not KFX. But if that's the dictionary that came on your Paperwhite, those aren't decryptable.
> 
> Also this is an issue:
> 
> > ModuleNotFoundError: No module named 'Crypto'
> 
> Assume you're not using the official calibre with its embedded Python.

Yes, that's the dictionary from Paperwhite. And my Calibre had been installed from Ubuntu repo.  
Thank you.
