### ISSUE TITLE
DeDRM works on some Kobo not on others

### ISSUE THREAD

**Issue by redbeaver55** [apprenticeharper/DeDRM_tools#2170]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log di debug
calibre 6.8  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: it
Initialized urlfixer
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && Modify ePub (1, 8, 1) && Obok DeDRM (7, 2, 1) && Quality Check (1, 13, 2) && Reading List (1, 14, 0) && Resize Cover (1, 2, 0) && Wiki Reader (2, 2, 1) && Wikidata (2, 0, 0)
calibre 6.8  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && Modify ePub (1, 8, 1) && Obok DeDRM (7, 2, 1) && Quality Check (1, 13, 2) && Reading List (1, 14, 0) && Resize Cover (1, 2, 0) && Wiki Reader (2, 2, 1) && Wikidata (2, 0, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
[0.00] Starting up...
[0.01] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1088, 'width': 1920, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 1057, 'width': 1920, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 1057, 'width': 1920, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1057, 'width': 1920, 'x': 0, 'y': 23}
Restoring widget to maximized
DEBUG:    0.7 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.7 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.7 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.7 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.7 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.7 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[1.06] main UI initialized...
[1.06] Hiding splash screen
Starting QuickView
[10.75] splash screen hidden
[10.75] Started up in 10.75 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b"2022-11-22T12:26:58.294ZE [21600:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\\\.\\Pipe\\GoogleDriveFSPipe_Luigi_shell\r\n2022-11-22T12:26:58.295ZE [21600:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE\r\n2022-11-22T12:26:58.295ZE [17620:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\\\.\\Pipe\\GoogleDriveFSPipe_Luigi_shell\r\n2022-11-22T12:26:58.295ZE [17620:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE\r\n2022-11-22T12:26:58.296ZE [20612:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\\\.\\Pipe\\GoogleDriveFSPipe_Luigi_shell\r\n2022-11-22T12:26:58.296ZE [20612:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE\r\n"]
piped data from file dialog helper: [b'\xe9\x84\xf9\x9d9\xd8\xe3\x0f\xc2\x1a\xda\x98\xba\xa6=_\x9d0\xe3M\xd5\xb0\x0bM\x1d.\x9f\x16x\xbe\xac\xd8', b'C:\\Users\\Luigi\\Downloads\\c760614f-9ccb-408f-a73b-efacb67b395f.epub', b'C:\\Users\\Luigi\\Downloads\\a8fe7e56-67e0-4475-8f2f-3b894c9b1751.epub', b'C:\\Users\\Luigi\\Downloads\\3909c3ba-c953-42e8-865c-07f0740c494c.epub', b'C:\\Users\\Luigi\\Downloads\\85d02b77-f7b8-45e4-99f1-fe785d1b4d38.epub', b'C:\\Users\\Luigi\\Downloads\\7aa78dd0-76b1-41aa-8209-5e698c4b8a94.epub']
DeDRM v7.2.1: Trying to decrypt c760614f-9ccb-408f-a73b-efacb67b395f.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “c760614f-9ccb-408f-a73b-efacb67b395f.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
DeDRM v7.2.1: Trying to decrypt a8fe7e56-67e0-4475-8f2f-3b894c9b1751.epub
DeDRM v7.2.1: Trying to decrypt 3909c3ba-c953-42e8-865c-07f0740c494c.epub
DeDRM v7.2.1: Trying to decrypt 7aa78dd0-76b1-41aa-8209-5e698c4b8a94.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Verifying zip archive integrity
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1693, in set_metadata
  File "calibre\db\cache.py", line 1616, in set_cover
  File "calibre\db\backend.py", line 1626, in set_cover
  File "calibre\utils\img.py", line 297, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
DeDRM v7.2.1: “7aa78dd0-76b1-41aa-8209-5e698c4b8a94.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
DeDRM v7.2.1: Trying to decrypt 85d02b77-f7b8-45e4-99f1-fe785d1b4d38.epub
DeDRM v7.2.1: Verifying zip archive integrity
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1693, in set_metadata
  File "calibre\db\cache.py", line 1616, in set_cover
  File "calibre\db\backend.py", line 1626, in set_cover
  File "calibre\utils\img.py", line 297, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
DeDRM v7.2.1: “a8fe7e56-67e0-4475-8f2f-3b894c9b1751.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.3 seconds. DRM free perhaps?
DeDRM v7.2.1: “85d02b77-f7b8-45e4-99f1-fe785d1b4d38.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
DeDRM v7.2.1: “3909c3ba-c953-42e8-865c-07f0740c494c.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.3 seconds. DRM free perhaps?
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1693, in set_metadata
  File "calibre\db\cache.py", line 1616, in set_cover
  File "calibre\db\backend.py", line 1626, in set_cover
  File "calibre\utils\img.py", line 297, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Added L’ultimo anno dell’impero to db in: 0.1
Added Aristotele e la Montagna d’Oro to db in: 0.2
Added Di follia, di guerra e di altre storie 1915-1918 to db in: 0.1
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1693, in set_metadata
  File "calibre\db\cache.py", line 1616, in set_cover
  File "calibre\db\backend.py", line 1626, in set_cover
  File "calibre\utils\img.py", line 297, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1693, in set_metadata
  File "calibre\db\cache.py", line 1616, in set_cover
  File "calibre\db\backend.py", line 1626, in set_cover
  File "calibre\utils\img.py", line 297, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Initialized urlfixer
Initialized urlfixer
Initialized urlfixer

**Comment by ElleKayEm** [comment]
Doesn't appear to have Adobe DRM.

> DeDRM v7.2.1: “85d02b77-f7b8-45e4-99f1-fe785d1b4d38.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub

If that's from Kobo Desktop or a Kobo ereader, import it with Obok.  Also, for calibre 6.x, update to 10.0.3.

https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
