### ISSUE TITLE
[QUESTION] Can't De-DRM files on Linux Pop_OS 22.04

### ISSUE THREAD

**Issue by it0na72** [apprenticeharper/DeDRM_tools#2171]
## Title
Can't De-DRM files on Linux Pop_OS 22.04 as the title mentions. Posted the log below. I also installed python through wine because I saw it being mentioned in other posts but no luck. It seems like the keys are not being picked up and the plugin can't find the python installation. However i'm not sure how to change that. Any help appreciated. 

## Log
<details><summary>Log Title</summary>

```log
Convert book 1 of 1 (影法師 (講談社文庫))
DeDRM v10.0.3: Trying to decrypt tgyfet7v.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 影法師 (講談社文庫)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
006c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0054:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000003
0024:err:module:process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v10.0.3: wine py.exe -3 does not exist
00d0:err:module:process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v10.0.3: wine python3.exe does not exist
00d8:err:module:process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v10.0.3: wine python.exe does not exist
wine: cannot find L"C:\\Python27\\python.exe"
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/abikyoukan/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/abikyoukan/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  cover: '/tmp/calibre_6.8.0_tmp_pzqt6ige/b9kaxjto.jpeg'
  read_metadata_from_opf: '/tmp/calibre_6.8.0_tmp_pzqt6ige/xj_4bcqy.opf'
  output_profile: 'kobo'
  verbose: 2
Resolved conversion options
calibre version: 6.8.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/tmp/calibre_6.8.0_tmp_pzqt6ige/b9kaxjto.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f8cbce8fc10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x7f8cbce8d690>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/tmp/calibre_6.8.0_tmp_pzqt6ige/xj_4bcqy.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt tgyfet7v.azw
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 影法師 (講談社文庫)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
00fc:err:module:process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v10.0.3: wine py.exe -3 does not exist
0120:err:module:process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v10.0.3: wine python3.exe does not exist
0128:err:module:process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v10.0.3: wine python.exe does not exist
wine: cannot find L"C:\\Python27\\python.exe"
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/abikyoukan/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/abikyoukan/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on /tmp/calibre_6.8.0_tmp_pzqt6ige/tgyfet7v.azw
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: 影法師 (講談社文庫)

```
</details>

**Comment by ElleKayEm** [comment]
I think you need both Python and pycryptodome installed for DeDRM to find and decrypt the key from Kindle for PC.  As a workaround, you can at least temporarily install Windows calibre with DeDRM.  (This will use calibre's embedded Python for the key retrieval script.)  Once you successfully decrypted a book there, you can save the key and import it into your Linux setup.

**Comment by it0na72** [comment]
Thanks for your quick feedback. Would love to get this fixed but I kept trying even after changing some of the file paths + installing pycryptodome and nothing seems to work. 
Seems like the only workaround this will be to get a windows VM and get those keys.

**Comment by ElleKayEm** [comment]
Be sure you're getting books and key from the same installation of Kindle for PC.  Each app installation has a unique key even if logged in to the same account.

**Comment by it0na72** [comment]
> Be sure you're getting books and key from the same installation of Kindle for PC.  Each app installation has a unique key even if logged in to the same account.

Do you happen to know if I delete the app + the books, download another version of the app and re download the books, would the key be the same? if so I'll try it in a bit

**Comment by ElleKayEm** [comment]
The key will change if you completely uninstall, reinstall, and have to log in again.  But as long as books and key are from the same current installation, they will work.

**Comment by junefish** [comment]
Unfortunately don't remember precisely what steps I took to get things working, but DeDRM is working great for me on encrypted ePUBs and PDFs on Pop! OS 22.04.  Happy to provide any logs that might be helpful

**Comment by ElleKayEm** [comment]
This might be helpful: https://github.com/noDRM/DeDRM_tools/issues/182#issuecomment-1356476512
