### ISSUE TITLE
DRM stopped working

### ISSUE THREAD

**Issue by caseem** [apprenticeharper/DeDRM_tools#2172]
I am using Calibre version 4.2. DRM tool removal 6.8.1. 

calibre, version 4.2.0
ERROR: Loading book failed: Failed to open the book at /Users/caseemiller/Calibre Library/Georgia Lyn Hunter/Absolute Surrender (Fallen Guardians Book 1) (1775)/Absolute Surrender (Fallen Guardians Book - Georgia Lyn Hunter.azw3. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/utils/ipc/simple_worker.py", line 290, in main
  File "site-packages/calibre/srv/render_book.py", line 689, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Absolute Surrender (Fallen Guardians Book 1)

**Comment by ElleKayEm** [comment]
If that's tied to an E-ink Kindle (not a Fire), then enter your Kindle's serial number into DeDRM's customization.  Then restart calibre and re-add your book.

**Comment by caseem** [comment]
That worked, thank you.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
