### ISSUE TITLE
Shueisha Kobo book DeDRM failed

### ISSUE THREAD

**Issue by kof11** [apprenticeharper/DeDRM_tools#2179]
Kodansha DeDRM successfully, Shueisha is failed.
example https://books.rakuten.co.jp/rk/da969d7852a33c9db0aa5f67d335dc11/

log detail

Failed to convert book: C:\Users\user1\Documents\calibre 書庫\Wei Zhi\zayo ki6 (70)\zayo ki6 - Wei Zhi.epub with error:
DeDRM v10.0.3: Trying to decrypt zayo ki6 - Wei Zhi.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 3.0 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\user1\AppData\Local\Temp\calibre_3jnbx229\cqsnoko4.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 175, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 237, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 155, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 792, in render
  File "calibre\srv\render_book.py", line 605, in process_exploded_book
  File "calibre\srv\render_book.py", line 264, in create_cover_page
  File "calibre\srv\render_book.py", line 217, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes

**Comment by ElleKayEm** [comment]
Let's see a log of adding the book to calibre instead of this conversion attempt: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by kof11** [comment]
Sorry
-------
calibre 偵錯記錄
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
Not controlling automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 79.16883116883116 x 79.28323699421965
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.38] main UI initialized...
[1.38] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 176, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 155, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
[15.03] splash screen hidden
[15.03] Started up in 15.03 seconds with 56 books
Running Obok DeDRM v10.0.3
DEBUG:   21.1 didn't find device
Obok v10.0.1
Copyright © 2012-2022 Physisticated et al.
C:\Users\user1\AppData\Local\Temp\tmpbc8zc7id
DEBUG:   21.6 got kobodir C:\Users\user1\AppData\Local\Kobo\Kobo Desktop Edition
Found 24 possible keys to try.
DEBUG:   26.7 BookListTableWidget:get_books - book_num: 8
DEBUG:   26.7 BookListTableWidget:get_books - book: 妖怪少女―モンスガ―【期間限定無料】 1
DEBUG:   26.7 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.3 - Decrypting 妖怪少女―モンスガ―【期間限定無料】 1
Trying key:  b'e9cbfae54bb5484cbed3161e49db9873'
Success!
DEBUG:   29.7 DecryptAddProgressDialog::do_book_action - decrypted book: '妖怪少女―モンスガ―【期間限定無料】 1'
Obok DeDRM v10.0.3 - Added  ps0t4hh
Obok DeDRM v10.0.3 - wrapping up results.

**Comment by ElleKayEm** [comment]
This log is showing successful DRM removal.
