### ISSUE TITLE
[QUESTION] Title

### ISSUE THREAD

**Issue by Petya90** [apprenticeharper/DeDRM_tools#2181]
## CheckList
x
- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Hibakeresési napló
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 41, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 41, 0) && KFX metadata reader (from KFX Input) (1, 41, 0) && KFX Input (1, 41, 0)
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 41, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 41, 0) && KFX metadata reader (from KFX Input) (1, 41, 0) && KFX Input (1, 41, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.35820895522387
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 768,
                                'width': 1366,
                                'x': -1366,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY7',
 'serial': '',
 'size_in_logical_pixels': {'height': 768, 'width': 1366},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 528, 'width': 1131, 'x': 454, 'y': 119},
 'full_screened': False,
 'geometry': {'height': 497, 'width': 1131, 'x': 454, 'y': 150},
 'maximized': False,
 'normal_geometry': {'height': 497, 'width': 1131, 'x': 454, 'y': 150},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 3286,
                                 'x': -1366,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
Setting widget geometry to: {'height': 497, 'width': 1131, 'x': 454, 'y': 150}
[0.84] main UI initialized...
[0.84] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Female_Action_ebook.190215-131026.pdf
DeDRM v7.2.1: Female_Action_ebook.190215-131026.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] A rendszer nem találja a megadott fájlt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 461, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'FOPN_foweb' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x0000018CAB3392D0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000018CAB3392D0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
[12.48] splash screen hidden
[12.48] Started up in 12.48 seconds with 0 books
Added Female Action ebook.190215-131026 to db in: 0.1
Added 1 books in 0.6 seconds

```
</details>

**Comment by Petya90** [comment]
Bought 5 five book a couple years ago
always tried to print them, but it was always impossible :/
can you help me?

**Comment by ElleKayEm** [comment]
For calibre 6, you need DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Also, you don't appear to have Adobe Digital Editions authorized with your Adobe ID on this computer.  Are you able to read the books in ADE?

**Comment by Petya90** [comment]
Hellop There
Thanks for the answer
you mean Acrobat reader, for example?
Yes I can read it, but i had to download fileopen Client. (this was the author's rule)
i downloaded DeDRM 10.0.3
These are the results:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Hibakeresési napló
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 41, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 41, 0) && KFX metadata reader (from KFX Input) (1, 41, 0) && KFX Input (1, 41, 0)
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: hu
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 41, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 41, 0) && KFX metadata reader (from KFX Input) (1, 41, 0) && KFX Input (1, 41, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.35820895522387
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 768,
                                'width': 1366,
                                'x': -1366,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY7',
 'serial': '',
 'size_in_logical_pixels': {'height': 768, 'width': 1366},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 528, 'width': 1131, 'x': 454, 'y': 119},
 'full_screened': False,
 'geometry': {'height': 497, 'width': 1131, 'x': 454, 'y': 150},
 'maximized': False,
 'normal_geometry': {'height': 497, 'width': 1131, 'x': 454, 'y': 150},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 3286,
                                 'x': -1366,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 3286, 'x': -1366, 'y': 0}}
Setting widget geometry to: {'height': 497, 'width': 1131, 'x': 454, 'y': 150}
[0.88] main UI initialized...
[0.88] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Female_Action_ebook.190215-131026.pdf
DeDRM v10.0.3: Female_Action_ebook.190215-131026.pdf is a PDF ebook with encryption FOPN_foweb
DeDRM v10.0.3: FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.
DeDRM v10.0.3: Finished after 0.1 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'FOPN_foweb' security handler

pdfinfo errored out with return code: 1
[2.97] splash screen hidden
[2.97] Started up in 2.97 seconds with 0 books
Added Female Action ebook.190215-131026 to db in: 0.1
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
From the log:

> DeDRM v10.0.3: Trying to decrypt Female_Action_ebook.190215-131026.pdf
DeDRM v10.0.3: Female_Action_ebook.190215-131026.pdf is a PDF ebook with encryption FOPN_foweb
DeDRM v10.0.3: FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.
DeDRM v10.0.3: Finished after 0.1 seconds

So this type of DRM isn't supported by DeDRM.  There is a script available here: https://github.com/noDRM/DeDRM_tools/tree/master/Other_Tools/Tetrachroma_FileOpen_ineptpdf

But I'm not familiar with it, it hasn't been updated, and I don't know if it still works.

**Comment by Petya90** [comment]
ok but what should i do with these? :/

**Comment by ElleKayEm** [comment]
That's all I know about removing that DRM.

**Comment by Petya90** [comment]
oh okay, thanks :)
