### ISSUE TITLE
DRM not working - error concerning ASCII characters

### ISSUE THREAD

**Issue by jakhof** [apprenticeharper/DeDRM_tools#2184]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## DRM not working - error concerning ASCII characters
DRM-removal doesn't work for me. Nothing happens: Log says "string argument should contain only ASCII characters"

## Log
<details><summary>Log Title</summary>

Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "encodings/hex_codec.py", line 19, in hex_decode
	ValueError: string argument should contain only ASCII characters
</details>

**Comment by ElleKayEm** [comment]
This is for Adobe DRM?  Delete the saved Adobe key in DeDRM customization.  Then re-add your book letting DeDRM automatically retrieve the key.

**Comment by novy06** [comment]
I have seen the reply to delete the key and try again for this error in several posts and that fix is not working for me.  I have tried that many times with various reboots and installs going on.  I have a couple other error codes going on as well please see below.
I am running on Linux, the wineprefix works, and the DeASCM plugin works.
I have Calibre 6.15.1 and DeDRM 10.0.3.
Error Log:

0024:err:module:process_init L"C:\\windows\\system32\\py.exe" not found
DeDRM v10.0.3: wine py.exe -3 does not exist
00f4:err:module:process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v10.0.3: wine python3.exe does not exist
00fc:err:module:process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v10.0.3: wine python.exe does not exist
wine: cannot find L"C:\\Python27\\python.exe"
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX="/home/ben/.wine"
00a4:err:rpc:I_RpcReceive we got fault packet with status 0x1c010003
DeDRM v10.0.3: Trying to decrypt Spare.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Spare.epub is a secure Adobe Adept ePub for UUID ffd41a66-187b-4daa-83ba-f52a206b6793
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 553, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

**Comment by ElleKayEm** [comment]
On a Linux system it can be difficult to get things working so that DeDRM can automatically retrieve the key.  A workaround is to use Windows calibre/DeDRM to retrieve the key, then import that key into the  Linux setup.

**Comment by artkuo** [comment]
> Delete the saved Adobe key in DeDRM customization. Then re-add your book letting DeDRM automatically retrieve the key.

I recently had success doing just this. The Adobe key looked fine, but I got a `EBX_HANDLER` error. Following the advice here, I deleted the apparently-correct key from DeDRM. I then tried importing the book again, and it worked! Thanks for the strategy, and I suggest others with errors give this a try, since it's so easy to do.
