### ISSUE TITLE
DeDRM 7.2.1 removal doesnt work anymore

### ISSUE THREAD

**Issue by 947116** [apprenticeharper/DeDRM_tools#2185]
A few days ago DeDRM 7.2.1 worked perfectly. With the same epub source, DRM removal doesnt work anymore. Error message: Cannot convert. This book is locked by DRM

## Log
<details><summary>Log Title</summary>

```log
calibre, version 6.10.0
ERROR: Loading book failed: Failed to open the book at C:\Users\robin\Calibre Library\Jan Esswein\Achtsamkeitstraining (2)\Achtsamkeitstraining - Jan Esswein.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\robin\Calibre Library\Jan Esswein\Achtsamkeitstraining (2)\Achtsamkeitstraining - Jan Esswein.epub with error:
DeDRM v7.2.1: Trying to decrypt Achtsamkeitstraining - Jan Esswein.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Achtsamkeitstraining - Jan Esswein.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\robin\Calibre Library\Jan Esswein\Achtsamkeitstraining (2)\Achtsamkeitstraining - Jan Esswein.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 821, in viewer_main
  File "calibre\srv\render_book.py", line 812, in render_for_viewer
  File "calibre\srv\render_book.py", line 789, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
calibre.ebooks.DRMError: Achtsamkeitstraining - Jan Esswein.epub
Exception ignored in: <function NativeFunction.__del__ at 0x000002C3DD7D6EF0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000002C3DD7D6EF0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
```
</details>

**Comment by 947116** [comment]
For calibre 6.1 you need DeDRM_tools_10.0.3 its the same plugin with a new maintainer
https://www.reddit.com/r/Calibre/comments/vy9a68/dedrm_1003_fixes_calibre_v60_issue_with_mac/
