### ISSUE TITLE
Failing to remove DRM from AZW3 file

### ISSUE THREAD

**Issue by Fuzzificationify** [apprenticeharper/DeDRM_tools#2187]
Hi, I'm having an issue where the DRM is not being removed from my AZW3 file. I downloaded the file from Amazon's "Download and Transfer via USB" link. I'm not connecting it to a device, I just want to change the file type. 

Calibre 6.10
DeDRM 10, 0, 3

Any idea? Thanks :)

Here's the log:

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 2.25
logicalDpi: 96.0 x 96.0
physicalDpi: 118.65693430656933 x 118.39453551912568
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 853, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 853, 'width': 1280},
 'virtual_geometry': {'height': 853, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 769, 'width': 1271, 'x': 6, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 740, 'width': 1271, 'x': 6, 'y': 29},
 'maximized': False,
 'normal_geometry': {'height': 740, 'width': 1271, 'x': 6, 'y': 29},
 'screen': {'depth': 32,
            'device_pixel_ratio': 2.25,
            'geometry_in_logical_pixels': {'height': 853,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 853, 'width': 1280},
            'virtual_geometry': {'height': 853, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 853, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 853, 'width': 1280},
 'virtual_geometry': {'height': 853, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 740, 'width': 1271, 'x': 6, 'y': 29}
[0.66] main UI initialized...
[0.66] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Crystal Hunters (Japanese)_ Book 2.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Crystal Hunters (Japanese): Book 2
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\JonoT\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\JonoT\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1625306591' and UserName 'JonoT'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Crystal Hunters (Japanese): Book 2
Got DSN key from database key_0
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\JonoT\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.38] splash screen hidden
[2.38] Started up in 2.38 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbd\xc2\xdd\x07\x97\xc4<\xfd\xa5\xa9R\xd7\xf1\xed\xbcl\x1ak\xc4R7\xd5\xbf\xf3j\xa2qz\xe5\xb4\x89$', b'C:\\Users\\JonoT\\Downloads\\Crystal Hunters (Japanese)_ Book 2.azw3']
Added Crystal Hunters (Japanese): Book 2 to db in: 0.1

```

**Comment by ElleKayEm** [comment]
Looks like you need to enter your Kindle's serial number into DeDRM's customization.

**Comment by Fuzzificationify** [comment]
Hot damn, yep that was it. Maybe I'm just an idiot but it wasn't obvious to me that you had to use your Kindle's serial number if you were trying to convert the file. 
Thanks a lot! :)
