### ISSUE TITLE
Failing to install DeDRM

### ISSUE THREAD

**Issue by peaux** [apprenticeharper/DeDRM_tools#2190]
I used to use DeDRM on a different computer, no issues. Now, I try to install the plugin, and I get this. Maybe I'm completely incompetent, that's very possible.

```
calibre, version 6.10.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'D:\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'D:\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

```

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by peaux** [comment]
I'm completely incompetent, great. Thank you!
