### ISSUE TITLE
Cannot covert purchased books Adobe Digital on other computer

### ISSUE THREAD

**Issue by Bujold1964** [apprenticeharper/DeDRM_tools#2191]
pplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.9  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 6.9  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 131.52103559870548 x 131.3793103448276
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1600, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1600},
 'virtual_geometry': {'height': 900, 'width': 1600, 'x': 0, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 457, 'width': 560, 'x': 629, 'y': 234},
 'full_screened': False,
 'geometry': {'height': 426, 'width': 560, 'x': 629, 'y': 265},
 'maximized': False,
 'normal_geometry': {'height': 426, 'width': 560, 'x': 629, 'y': 265},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1600,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1600},
            'virtual_geometry': {'height': 900, 'width': 1600, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1600, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1600},
 'virtual_geometry': {'height': 900, 'width': 1600, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 426, 'width': 560, 'x': 629, 'y': 265}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 868, 'width': 1600, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 837, 'width': 1600, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 837, 'width': 1600, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1600,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1600},
            'virtual_geometry': {'height': 900, 'width': 1600, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1600, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1600},
 'virtual_geometry': {'height': 900, 'width': 1600, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 837, 'width': 1600, 'x': 0, 'y': 23}
Restoring widget to maximized
[1.31] main UI initialized...
[1.31] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt A fi evreu dupa Holocaust.epub
DeDRM v7.2.1: Verifying zip archive integrity
[21.91] splash screen hidden
[21.91] Started up in 21.91 seconds with 28 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xef\xc5\x9c\xe2\xd0\xc2\x7f\xd9\xff\x8d\x81#\x99d\x80\xebO\xc5\x16\x0b\xeb3\xe5\xb6\xcf\x15w#\xcc{Em', b'E:\\backup cataloage\\My Digital Editions\\A fi evreu dupa Holocaust.epub']
DeDRM v7.2.1: A fi evreu dupa Holocaust.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Trying Encryption key default_key
Could not decrypt 5cimjl_9.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 416, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 317, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 180, in decrypt
  File "Crypto\PublicKey\RSA.py", line 154, in _decrypt
ValueError: Ciphertext too large

DeDRM v7.2.1: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
Found 1 keys
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Exception ignored in: <function NativeFunction.__del__ at 0x000001C2AD8C2170>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001C2AD8C2170>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
For calibre 6, update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

In order for DeDRM to retrieve the key, ADE used to download the book needs to be on the same machine and user as calibre with DeDRM.
