### ISSUE TITLE
DeDRM doesn't work

### ISSUE THREAD

**Issue by aldval59** [apprenticeharper/DeDRM_tools#2195]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log di debug
calibre 6.11  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0)
calibre 6.11  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Set KFX metadata (from KFX Output) (1, 65, 0) && KFX Output (1, 65, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.35820895522387
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1040, 'width': 1920, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1009, 'width': 1920, 'x': 0, 'y': 23}
Restoring widget to maximized
[1.08] main UI initialized...
[1.08] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Il segreto di Isabel.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Il segreto di Isabel.epub is a secure Adobe Adept ePub for UUID 40576db8-f3ec-4405-bd80-a842a6707975
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\Aldo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\Aldo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[22.09] splash screen hidden
[22.09] Started up in 22.09 seconds with 15065 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbc1\xc9(\xe9\xed|\xd7\x95\xd08\xaa\x9c,qN\x9bF\xa4\x12\xccg\xee\x81\x0e\xb3\xfd[pO\xfd\x95', b'C:\\Users\\Aldo\\Documents\\My Digital Editions\\Il segreto di Isabel.epub']
Added Il segreto di Isabel to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
You have Adobe Digital Editions used to download the book on the same machine and user as calibre with DeDRM?

**Comment by aldval59** [comment]
Yes, on the same computer.
The strange thing isole that it worked untilt september or october.

Il Lun 16 Gen 2023, 20:42 ElleKayEm ***@***.***> ha scritto:

**Comment by ElleKayEm** [comment]
In the past some have had luck with deauthorizing and reauthorizing ADE.  On [this page](https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html) scroll down to TROUBLESHOOTING REAUTHORIZATION AND DEAUTHORIZATION ISSUES ON WINDOWS.

Or you might look at the DeACSM plugin which allows you to skip using ADE:  https://www.mobileread.com/forums/showthread.php?t=341975

**Comment by aldval59** [comment]
thank you ElleKay.
I tried to deauthorize and reauthorize my ADE id following the instructions of the suggested page.
The deauthorization was OK but when I tried to delete the Adobe adept registry key I obtained a message that was impossible to delete all specified values, then I have reauthorized my ADE id but nothing has changed.
In the Adobe adept registry key I noticed that in data section there is 'value not setted' 'valore non impostato' in italian language.
Hereafter I tried to paste the image of the registry key but I don't know if you can see the image file.

![adobe registry](https://user-images.githubusercontent.com/122805430/212941627-847cb1f5-b1bc-44b5-867b-d7409522d5bb.jpg)

**Comment by ElleKayEm** [comment]
That is what I see there too on my system and things are working for me.  I do notice that it looks like you have or had different installations of ADE: there are Adobe Digital Editions, Adobe Digital Editions 4.5, and Digital Editions folders.  I have only ever had ADE 2.0.1 on my computer and I only see the Digital Editions folder.  It could be that DeDRM is picking up info from the wrong version.  I wouldn't mess with deleting anything else in the registry.  But if you do have both ADE 4.5 and a previous version installed currently, I'd try de-authorizing and uninstalling the one that you did NOT use to download the book.

Again using the DeACSM plugin and not messing with ADE at all might be a workaround.  I haven't tried that myself at all since ADE has continued to work for me.

**Comment by aldval59** [comment]
I have added DeACSM plugin in Calibre and I have loaded the ebook, when I double-click to open the ebook ADE starts and open the ebook correctly (but I haven't had any problem to open the ebook in ADE before), but I suppose tha the ACSM file that I have in Calibre cannot be loaded in my Pocket Book ereader (and I cannot convert it in any other format).
I'm using 4.5.11 ADE version but I cannot see any other ADE version on my computer.
Thanks a lot again for your support.

**Comment by ElleKayEm** [comment]
No, acsm is not a book.  But the DeACSM plugin should download the epub into calibre.

**Comment by aldval59** [comment]
Not for me, in Calibre I see an ACSM file with the name ACSM, the same I
see in the folder where the ebook has been downloaded.

Il giorno martedì 17 gennaio 2023, ElleKayEm ***@***.***> ha
scritto:

**Comment by ElleKayEm** [comment]
Haven't used it myself, as I said, but that's its entire purpose -- to replace downloading the epub with ADE.

**Comment by MTOakey** [comment]
Windows 11, all App's are the most updated versions, including Kindle for PC.
Just installed AFTER purchasing an Amazon Kindle ebook. Book shows up in KforPC.
Set calibre "default conversion" to PDF.
Selected the .azw file ...
Had Terminal open and ran Calibre in Debug mode...
DID NOT DeDRM.
**************************************************************************************************************************************
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Matth> calibre-debug -g
calibre 6.12  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
ApplicationPaletteChange event ignored
Using calibre Qt style: True
PS C:\Users\Matth> calibre-debug -g
calibre 6.12  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 540, 'width': 1204, 'x': 628, 'y': 197},
 'full_screened': False,
 'geometry': {'height': 509, 'width': 1204, 'x': 628, 'y': 228},
 'maximized': False,
 'normal_geometry': {'height': 509, 'width': 1204, 'x': 628, 'y': 228},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 509, 'width': 1204, 'x': 628, 'y': 228}
[0.69] main UI initialized...
[0.69] Hiding splash screen
Starting QuickView
[1.11] splash screen hidden
[1.11] Started up in 1.11 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xa7|\x96su\x80\x01H84\x82\xca\x8b\x15\xee\xb5\x98\x0cu\x17\x93,\xc6\xaf\x80'\xc6s\xb3S\x93\x99", b'C:\\Users\\Matth\\OneDrive\\Documents\\My Kindle Content\\B07FG1QTP3_EBOK\\B07FG1QTP3_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:\Users\Matth\OneDrive\Documents\My Kindle Content\B07FG1QTP3_EBOK\B07FG1QTP3_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\l2qn2pw9.kfx-zip
DeDRM v7.2.1: Trying to decrypt l2qn2pw9.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: l2qn2pw9
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.93e07b08-9936-4352-97f2-3846688f820e.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Matth\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Matth\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '975722621' and UserName 'Matth'
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.51.0: Packaging C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\l2qn2pw9.kfx-zip
Processing container: B07FG1QTP3_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07FG1QTP3_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\kig8i0so_add_books\0\B07FG1QTP3_EBOK.kfx-zip
Added The Gospel-Driven Church to db in: 0.1
Added 1 books in 2.7 seconds
Restoring geometry for: preferences dialog geometry
{'frame_geometry': {'height': 751, 'width': 930, 'x': 509, 'y': 16},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 509, 'y': 47},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 509, 'y': 47},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 720, 'width': 930, 'x': 509, 'y': 47}
Restoring geometry for: plugin config dialog:File type:DeDRM
{'frame_geometry': {'height': 370, 'width': 230, 'x': 931, 'y': 201},
 'full_screened': False,
 'geometry': {'height': 339, 'width': 230, 'x': 931, 'y': 232},
 'maximized': False,
 'normal_geometry': {'height': 339, 'width': 230, 'x': 931, 'y': 232},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 339, 'width': 230, 'x': 931, 'y': 232}
Saving geometry for: plugin config dialog:File type:DeDRM
{'frame_geometry': {'height': 370, 'width': 230, 'x': 931, 'y': 201},
 'full_screened': False,
 'geometry': {'height': 339, 'width': 230, 'x': 931, 'y': 232},
 'maximized': False,
 'normal_geometry': {'height': 339, 'width': 230, 'x': 931, 'y': 232},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Saving geometry for: preferences dialog geometry
{'frame_geometry': {'height': 751, 'width': 930, 'x': 509, 'y': 16},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 509, 'y': 47},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 509, 'y': 47},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xb2\xf8\xeb~\x1c\x93\xe2\xd6\xcf\x89\xcf\xf6\x0f\x9f'\xd1GBc\x1c!\x98A_pn2&\x0c\xa5Kw", b'C:\\Users\\Matth\\OneDrive\\Documents\\My Kindle Content\\B07FG1QTP3_EBOK\\B07FG1QTP3_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:\Users\Matth\OneDrive\Documents\My Kindle Content\B07FG1QTP3_EBOK\B07FG1QTP3_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\pl0mqsgz.kfx-zip
DeDRM v7.2.1: Trying to decrypt pl0mqsgz.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: pl0mqsgz
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.93e07b08-9936-4352-97f2-3846688f820e.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Matth\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Matth\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '975722621' and UserName 'Matth'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: pl0mqsgz
Got DSN key from database default_key_1
Found 1 keys to try after 2.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.93e07b08-9936-4352-97f2-3846688f820e.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Matth\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.51.0: Packaging C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\pl0mqsgz.kfx-zip
Processing container: B07FG1QTP3_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07FG1QTP3_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Matth\AppData\Local\Temp\calibre_58n_rbig\1epvmvuh_add_books\0\B07FG1QTP3_EBOK.kfx-zip
Added The Gospel-Driven Church to db in: 0.0
Added 1 books in 2.6 seconds
**************************************************************************************************************************************

Any help would be greatly appreciated.

**Comment by ElleKayEm** [comment]
@MTOakey 
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

But you will need an older version of Kindle for PC to get this book in a format that can be decrypted.  See this post: 
 https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by aldval59** [comment]
Hello, probably the problem is that I have not the ADE key configured in Calibre.
Somebody could suggest me where I can find the ADE key ?
Thanks.
![dedrm plugin](https://github.com/apprenticeharper/DeDRM_tools/assets/122805430/ff30006a-b51a-495c-8d3e-56e76bddcb8a)

**Comment by ElleKayEm** [comment]
DeDRM will automatically retrieve the key from ADE installed on the same machine and user as calibre when you add your book.

**Comment by aldval59** [comment]
It should be like you wrote but the error log you can find hereafter shows that it doesn't work.
P.S. Calibre and ADE are on the same machine.

**Starting QuickView
DeDRM v10.0.3: Trying to decrypt Il segreto di Isabel.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Il segreto di Isabel.epub is a secure Adobe Adept ePub for UUID 40576db8-f3ec-4405-bd80-a842a6707975
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\Aldo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\Aldo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md**

**Comment by aldval59** [comment]
So I'm trying to add the ADE key in Calibre configuration, but I don't know how and where retrieve it.

**Comment by ElleKayEm** [comment]
That installation of ADE is the one you used to download the epub?  You can read the epub in ADE?

**Comment by aldval59** [comment]
Yes I can read the ebook in ADE.

**Comment by aldval59** [comment]
I have a problem when I import the ebook in Calibre because the DRM is not removed.

**Comment by ElleKayEm** [comment]
I don't know why it isn't working then.  Adding a book which was downloaded with the current installation of ADE is how the correct key is retrieved.

**Comment by aldval59** [comment]
So you don't know how to add the ADE key by yourself.
Many thanks anyway.

**Comment by ElleKayEm** [comment]
You can add the key by clicking the green plus sign in your screen shot.  But that won't work in your case.  The only other way would be to save a key from another setup (which used the same Adobe ID) and use the import existing keyfiles button.

**Comment by ElleKayEm** [comment]
Maybe try a fresh setup and a fresh download of the book.

**Comment by aldval59** [comment]
Many thanks, I will try following your suggestions.
