### ISSUE TITLE
[QUESTION] 'DeDRM error with Calibre'

### ISSUE THREAD

**Issue by monsieur-saucebrune** [apprenticeharper/DeDRM_tools#2197]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Journal de débogage
calibre 6.11  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: fr_CA
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.11  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: fr_CA
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 43.83640449438202 x 43.8912
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 823, 'width': 1536, 'x': -18, 'y': 110},
 'full_screened': False,
 'geometry': {'height': 793, 'width': 1536, 'x': -18, 'y': 140},
 'maximized': False,
 'normal_geometry': {'height': 793, 'width': 1536, 'x': -18, 'y': 140},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.25,
            'geometry_in_logical_pixels': {'height': 864,
                                           'width': 1536,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 864, 'width': 1536},
            'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 793, 'width': 1536, 'x': -18, 'y': 140}
[0.72] main UI initialized...
[0.72] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Inhabiting Memory in Canadian Literature  Habiter la mémoire dan-1.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Inhabiting Memory in Canadian Literature  Habiter la mémoire dan-1.epub is a secure Adobe Adept ePub for UUID be31d6a9-bd1e-4dca-9d0c-97b0decbae82
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\rebel\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\rebel\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.89] splash screen hidden
[3.89] Started up in 3.89 seconds with 202 books
stdout+stderr from file dialog helper: [b'', b'2023-01-20T13:06:58.046ZE [36156:NonCelloThread] crash.cc:83:HandleCrashpadLog [15772:36156:20230120,080658.045:ERROR crash_report_database_win.cc:614] CreateDirectory C:\\Users\\regin\\AppData\\Local\\Google\\DriveFS\\Crashpad: Le chemin d\xe2\x80\x99acc\xc3\xa8s sp\xc3\xa9cifi\xc3\xa9 est introuvable. (3)\r\n\r\nCould not initialize crash reporting DB\r\nCan not init crashpad with status: CRASHPAD_DB_INIT_ERROR']
piped data from file dialog helper: [b'\x88PQ\x0cl\x01\xb2H\x99\x84l\xa9h\x89\xd1"|\xadh\xd9\x0b\xc8W^/\xe3\xc4\xb4\x15T\xf5\xbc', b'D:\\rebel\\Documents\\My Digital Editions\\Inhabiting Memory in Canadian Literature  Habiter la m\xc3\xa9moire dan-1.epub']
Added Inhabiting Memory in Canadian Literature / Habiter la mémoire dans la littérature canadienne to db in: 0.3
Added 1 books in 0.8 seconds

```
</details>

**Comment by ElleKayEm** [comment]
This book was downloaded with ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by monsieur-saucebrune** [comment]
- DeDRM v10.0.3: Ultimately failed to decrypt
- adobekey.ADEPTError: Failed to decrypt user key key (sic)
In DeDRM pluggin, no key in ADE, even after adding a book
(first time using github...)

**Comment by monsieur-saucebrune** [comment]
> This book was downloaded with ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

Yes, same machine. I don't understand the question about the user in calibre with DeDRM?

**Comment by ElleKayEm** [comment]
ADE installed on the same machine and user as where you have calibre installed was what I meant.

DeDRM only automatically saves a key when it successfully decrypts a book with it.

I don't know why it's failing to decrypt your key.  A workaround might be using the DeACSM plugin instead of ADE:  https://www.mobileread.com/forums/showthread.php?t=341975

It seems like I've been seeing more problems than usual with Adobe DRM lately.  For whatever it's worth, it is still working for me.
