### ISSUE TITLE
[QUESTION] DeDRM not working with B&N?

### ISSUE THREAD

**Issue by jtnobs** [apprenticeharper/DeDRM_tools#2211]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Title
DeDRM not working with B&N Download

## Log
<details><summary>DeDRM not working with B&N Download
</summary>

```log
calibre Debug log
calibre 5.44  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.44  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000165954353 x 110.50000165954353
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.29] splash screen shown
[0.29] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
Loaded cached store plugin for: Kobo at version: 11
[1.30] main UI initialized...
[1.30] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 9781556713644.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “9781556713644.epub” is a secure Barnes & Noble ePub
DeDRM v7.2.1: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to initialize plugin: '/Users/jamesthigpen/Library/Preferences/calibre/plugins/KFX Input.zip'
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 313, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[15.34] splash screen hidden
[15.34] Started up in 15.34 seconds with 76 books
Added African Friends and Money Matters, Second Edition to db in: 0.0
Added 1 books in 0.5 seconds
```
</details>

**Comment by ElleKayEm** [comment]
You need a way to get your B&N key.  The methods built-in to DeDRM 7.2.1 no longer work.  DeDRM 10.0.3 has currently working ways of extracting your key.  The easiest is getting it from the Windows Nook app.  You can also get it from an Android emulator, a rooted Android device, or a rooted Nook.  But that's obviously more involved.  Get DeDRM 10.0.3 here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by jtnobs** [comment]
Just found this!
