### ISSUE TITLE
DRM not being removed from eInk Kindle books

### ISSUE THREAD

**Issue by theposhbloke** [apprenticeharper/DeDRM_tools#2214]
I followed all the installation steps to install the most recent version of the plugin (7.2.1) in Calibre and added my eInk Kindle serial number to it. It still does not work - any help would be appreciated. I get this in the debug when adding a book to Calibre which I have just downloaded:

calibre-debug -g
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-58-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-58-generic', '#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023')
Python 3.10.6
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
[0.55] main UI initialized...
[0.55] Hiding splash screen
Starting QuickView
[0.71] splash screen hidden
[0.71] Started up in 0.71 seconds with 406 books
DeDRM v7.2.1: Trying to decrypt Don't Stop Believin'.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.37.0_tmp_1q4slfid/l612uoqmplugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 633, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 527, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 191, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Added Don't Stop Believin' to db in: 0.2
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
Using the official Linux calibre (with embedded Python) should fix the error you're getting.  This version of DeDRM is fine for calibre 5, but the latest is actually 10.0.3 (which you'll need if using calibre 6):  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by theposhbloke** [comment]
Thank you for your prompt reply. I couldn't find out how to check that the
version of Calibre to install has embedded Python. I originally installed
Calibre via Linux Mint Software Manager. However, I have just installed
Calibre directly from the Calibre site, and, after adding your DeDRM
plugin, everything now appears to be working fine. Thank you very much for
your great support.

**Comment by ElleKayEm** [comment]
Yes, what I meant was that the official Linux calibre has embedded Python unlike the version your log was from.  Glad you got it working.  If you're all set, you can close the issue.

**Comment by theposhbloke** [comment]
Thanks. Issue closed.
