### ISSUE TITLE
[QUESTION] Failed installation

### ISSUE THREAD

**Issue by DriesMoo** [apprenticeharper/DeDRM_tools#2221]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
Tried to install via zip file and got this:

calibre, version 6.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\ZannakLissa\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Amazon.com Multiple Countries (1, 0, 0) && Barnes & Noble (1, 4, 0) && Goodreads (1, 7, 2) && KePub Input (3, 6, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3) && Manage Series (1, 5, 0) && Perrypedia (1, 6, 0) && Search The Internet (1, 10, 0) && ePub Extended Metadata {Writer} (0, 8, 1) && ePub Extended Metadata {Reader} (0, 8, 1) && ePub Extended Metadata (0, 8, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 480, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\ZannakLissa\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
First, for calibre 6.x, use DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Next, don't load the whole file into calibre.  Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip into calibre.
