### ISSUE TITLE
Issue using the zip with calibre

### ISSUE THREAD

**Issue by CeeJ2023** [apprenticeharper/DeDRM_tools#2222]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by CeeJ2023** [comment]
Calibre: Version 6.14.1
Kindle: Version 1.40, since nothing works with 1.17 now. 
DeDRM: Version 10.0.3
Wouldn't let me load plugin. 
calibre, version 6.14.1

ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Program Files\\Calibre2\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.14.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && Set KFX metadata (from KFX Output) (1, 66, 0) && KFX Output (1, 66, 0) && KindleUnpack - The Plugin (0, 83, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Program Files\\Calibre2\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.  See this post for workarounds to get books you can decrypt from Amazon: https://www.mobileread.com/forums/showthread.php?t=283371
