### ISSUE TITLE
DRM working on Calibre

### ISSUE THREAD

**Issue by ghost** [apprenticeharper/DeDRM_tools#2225]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.15.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.15.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.71098265895952
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.80] main UI initialized...
[0.80] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt The Actors handbook.pdf
DeDRM v7.2.1: The Actors handbook.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 366, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 461, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 368, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Could not locate ADE activation
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
[9.26] splash screen hidden
[9.26] Started up in 9.26 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'8\xc5E\xa2\xfa%9dF\xbe\xd83\xea %\x96O\x9aB\xc9n(\x01O\xcc\x86\x0b\xd4\xd42\x1f/', b'C:\\Users\\n_shr\\OneDrive\\Documents\\Bluefire Documents\\The Actors handbook.pdf']
Added The Actors handbook to db in: 0.2
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001DB64621EA0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001DB64621EA0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
First, for calibre 6, use DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Second, is ADE not on this system?

**Comment by ghost** [comment]
Thanks for the prompt reply.
I tried your version but still no success. 
------------------------------------------------
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.15.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.15.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.71098265895952
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.86] main UI initialized...
[0.86] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt The Actors handbook.pdf
DeDRM v10.0.3: The Actors handbook.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: The Actors handbook.pdf is a PDF ebook (EBX) for UUID aafc2a0c-458f-4ce5-9beb-4f33ead53a6b
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "C:\Users\n_shr\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 352, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 753, in PDFIneptDecrypt
  File "C:\Users\n_shr\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 354, in adeptkeys
adobekey.ADEPTError: Could not locate ADE activation
DeDRM v10.0.3: Finished after 0.3 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
[7.05] splash screen hidden
[7.05] Started up in 7.05 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x9b\x92r\x0e8.\x82b\x84\xa1\xd1H\xfa\xc11B\r\x15\xb6\xf815\n\xe9xi\xa6_\xa8\xf6\r\xb8', b'C:\\Users\\n_shr\\OneDrive\\Documents\\Bluefire Documents\\The Actors handbook.pdf']
Added The Actors handbook to db in: 0.1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1

**Comment by j-howell** [comment]
The actual error in that is "Could not locate ADE activation". From the path it looks like you imported that file from another system. You need to be able to read the PDF in Adobe Digital Editions on the PC running calibre for DRM removal to work.

**Comment by ElleKayEm** [comment]
Or look into using the DeACSM plugin.
