### ISSUE TITLE
[QUESTION] Syntax error installing plug-in on Mac line 167

### ISSUE THREAD

**Issue by chocbee** [apprenticeharper/DeDRM_tools#2226]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 5.44.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 167)

calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Goodreads Sync (1, 16, 3) && Reformat plugin (2, 4, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 326, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 292, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 184, in exec_module
  File "calibre/customize/zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.__init__", line 167
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

You could also update to the latest calibre too.
