### ISSUE TITLE
Error loading DeDRM 10.0.3 on Calibre 6.16 - Syntax error, missing parentheses in call to print

### ISSUE THREAD

**Issue by cr21365** [apprenticeharper/DeDRM_tools#2228]
Just upgraded from 4.x to lastest version and was trying to install DeDRM 10.0.3.  
Thanks in advance.

calibre, version 6.16.0
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 167)

calibre 6.16  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 1)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 307, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 199, in exec_module
  File "calibre\customize\zipplugin.py", line 195, in get_code
  File "calibre_plugins.dedrm.__init__", line 167
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by ElleKayEm** [comment]
Looks like you are still trying to install an older version of DeDRM.  Make sure it is really 10.0.3 that you are installing.
