### ISSUE TITLE
Error with obok plugin?

### ISSUE THREAD

**Issue by JeremyNort** [apprenticeharper/DeDRM_tools#2231]
Hello I am using
Windows 10
Calibre: 6.17
Obok plugin from DeDrm_tools_7.2.1

When I try to use the plugin I am getting the following error.
I have tried restarting Calibre and un installing and re-installing.

calibre, version 6.17.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.17  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

**Comment by ElleKayEm** [comment]
Try Obok 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by JeremyNort** [comment]
Thank you that worked

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
