### ISSUE TITLE
Crash when clicking the Obok DeDRM icon: `AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'`

### ISSUE THREAD

**Issue by paweljw** [apprenticeharper/DeDRM_tools#2233]
Steps I took:

* installed obok (not dedrm)
* connected the reader
* clicked the icon
* got the error message

If there are any other details that could be helpful, such as enabled plugins and the like, let me know.

## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 6.17.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.17  embedded-python: True
macOS-13.3.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.4.0', 'Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.3.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
    dlg = SelectionDialog(self.gui, self, books)
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
    self.books_table.populate_table(self.books)
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
    self.populate_table_row(row, book)
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
    status_cell = IconWidgetItem(None, icon, val)
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
    ReadOnlyTableWidgetItem.__init__(self, text)
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
    QTableWidgetItem.__init__(self, text, QTableWidgetItem.UserType)
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'
```
</details>

**Comment by paweljw** [comment]
Oh. Unmaintained. Nevermind then! :D

**Comment by ElleKayEm** [comment]
With calibre 6, use noDRM's 10.0.3 version: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
