### ISSUE TITLE
[QUESTION] DRM removal failing for Barnes & Noble ePub title

### ISSUE THREAD

**Issue by Calibre69** [apprenticeharper/DeDRM_tools#2237]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Title

“Management In a Changing World.epub” is a secure Barnes & Noble ePub I purchased.

## Log
<details><summary>Log for book purchased from Barnes & Noble </summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.17  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (7, 2, 1) && Goodreads Sync (1, 15, 6)
calibre 6.17  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (7, 2, 1) && Goodreads Sync (1, 15, 6)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.4 HttpHelper::__init__: proxy=None
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Management In a Changing World.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “Management In a Changing World.epub” is a secure Barnes & Noble ePub
DeDRM v7.2.1: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 313, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[19.09] splash screen hidden
[19.09] Started up in 19.09 seconds with 74 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'1N\x84o\x9c\xbfi\xc3 p\xf1\xe5`!\x0b*/5\xa4\xe4g\xca\x06\xf7\xc2^\x7f\x97\xc1N\xc6 ', b'G:\\My Drive\\Calibre\\Management In a Changing World.epub']
Added Management In A Changing World: How to Manage for Equity, Sustainability, and Results to db in: 0.3

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Look in DeDRM's customization to retreive your key from the Windows Nook app.
