### ISSUE TITLE
DeDRM not work for my epub

### ISSUE THREAD

**Issue by bay-kolio** [apprenticeharper/DeDRM_tools#2242]
## CheckList
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Дебъг регистър
calibre 6.19.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: bg
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KoboTouchExtended (3, 6, 3) && Obok DeDRM (10, 0, 3)
calibre 6.19.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: bg
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KoboTouchExtended (3, 6, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.97] main UI initialized...
[0.97] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt book.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\PC\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
[4.06] splash screen hidden
[4.06] Started up in 4.06 seconds with 156 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x04.\xef\xda@ZlC\x1a\xad\xe1q\x1e\x83\x92;C\\\xefp/\x10\x07_\xa5<V\xa9q\xe7.\x1a', b'C:\\Users\\PC\\Desktop\\1\\DeDRM_tools_10.0.3\\DeDRM_plugin.zip']
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd6\xc3\x92\x82\x7f\xa5\xb2~\xd7]A\x04 6$\xd3\xa5\xae6\x9d\xc5\x1f\x0e\x90j\x01\x99k\xbd\xf9\xfa!', b'C:\\Users\\PC\\Desktop\\book.epub']
Added Кучешки живот to db in: 0.1
Added 1 books in 1.0 seconds
Traceback (most recent call last):
  File "calibre\devices\kindle\driver.py", line 489, in upload_cover
  File "calibre\devices\kindle\driver.py", line 532, in upload_kindle_thumbnail
  File "calibre\devices\kindle\driver.py", line 513, in thumbpath_from_filepath
  File "calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x03\x04\x14\x00\x16\x08\x08\x00'
---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
That DRM is not supported.  See the links in the log for more info.

**Comment by Batres3** [comment]
Hey! Have you figured anything out?

**Comment by ElleKayEm** [comment]
As it says in the log, "LCP DRM removal no longer supported due to a DMCA takedown request."

**Comment by bay-kolio** [comment]
I am looking for LCD DRM remove and covert.

Nikolay Ivanov

На вт, 6.06.2023 г., 01:31 ч. Batres ***@***.***> написа:

**Comment by ElleKayEm** [comment]
It was part of these tools, but had to be removed in order to allow the rest to remain.

**Comment by bay-kolio** [comment]
I finally got it. It turned out that the passcode that I have from the
seller must be added to the module for installation

____________________________


*  Nikolay Ivanov *   Fr*€€* Lancer
   Mobile: *0898 535 102*
____________________________


На вт, 6.06.2023 г. в 15:38 ч. ElleKayEm ***@***.***> написа:

**Comment by ElleKayEm** [comment]
You can close this issue.
