### ISSUE TITLE
[QUESTION] Calibre 6.22 invalid DeDRM plugin

### ISSUE THREAD

**Issue by MarcelProdan** [apprenticeharper/DeDRM_tools#2247]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title
calibre, version 6.22.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\user1\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\user1\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

## Log
<details><summary>Calibre - Invalid plugin</summary>

```log
calibre, version 6.22.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\user1\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\user1\\Downloads\\DeDRM_tools_7.2.1.zip' is invalid. It does not contain a top-level __init__.py file

```
</details>

**Comment by ElleKayEm** [comment]
First, for calibre 6, you need DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Then unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by acagred** [comment]
calibre, version 6.22.0

Windows 10 pro
Calibre: 6.22
Kindle: Kindle Voyage
DeDRM: 7.2.1


[tmp793blsd0.txt](https://github.com/apprenticeharper/DeDRM_tools/files/11925719/tmp793blsd0.txt)

pplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.01] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.59] main UI initialized...
[0.59] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Viuda de hierro (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Viuda de hierro (Spanish Edition)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Acag\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[16.98] splash screen hidden
[16.98] Started up in 16.98 seconds with 505 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x1a\x1d\xa3\xbc\xe7\x02\x86wL\xaexb\x15\x89e)\xc1 .,!j\xcch&\x15|Z\xf1\x81\xe2\x1d', b'C:\\Users\\Acag\\Downloads\\Viuda de hierro (Spanish Edition).azw3']
Added Viuda de hierro (Spanish Edition) to db in: 0.0
Added 1 books in 0.3 seconds

**Comment by ElleKayEm** [comment]
@acagred 
For calibre 6, use DeDRM 10.0.3:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Enter your Voyage's serial number into DeDRM's customization.

**Comment by RadekHavelka** [comment]
do not try to load the whole archive, open it first, extract the two modules in it and install each of them. Otherwise it throws the error mentioned above.

**Comment by acagred** [comment]
What file are you referring to?
Thanks and best regards

**Comment by ElleKayEm** [comment]
@acagred They are responding to the first post, not yours.
