### ISSUE TITLE
v7.2.1

### ISSUE THREAD

**Issue by lsarios9144** [apprenticeharper/DeDRM_tools#2248]
I have a book that I purchased from GFOA. It will not print correctly (an old and well know issue with Adobe Digital) and the only solution that I can come up with is to remove DRM and convert to PDF so that I can print correctly. However this tool did not work.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.22  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 16, 9)
calibre 6.22  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Kobo Utilities (2, 16, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.5 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.5 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.5 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.5 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[1.00] main UI initialized...
[1.00] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Governmental Accounting, Auditing, and Financial Reporting.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Governmental Accounting, Auditing, and Financial Reporting.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[10.11] splash screen hidden
[10.11] Started up in 10.11 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'eoU:h]\x84o\xbf\x94\x85\xefY\xa7\xbd\x8d\x8d\x16\x96a\xc5\xd4\xfc\xa9\xda&\xea<\xef\xe5u7', b'E:\\Governmental Accounting, Auditing, and Financial Reporting.epub']
Added Governmental Accounting, Auditing, and Financial Reporting to db in: 2.5
Exception ignored in: <function NativeFunction.__del__ at 0x000002127E329990>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000002127E329990>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

### Discussed in https://github.com/apprenticeharper/DeDRM_tools/discussions/1656

<div type='discussions-op-text'>

<sup>Originally posted by **apprenticeharper** April 11, 2021</sup>
I messed up some white space. I still haven't got KFX to work for me, but I don't think I've actually broken anything this time. :)

<hr /><em>This discussion was created from the release <a href='https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v7.2.1'>v7.2.1 — Full Release</a>.</em></div>

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by lsarios9144** [comment]
Still did not work:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kobo Utilities (2, 16, 9) && Prince PDF (1, 6, 0) && ePub Extended Metadata {Writer} (0, 9, 0) && ePub Extended Metadata {Reader} (0, 9, 0) && ePub Extended Metadata (0, 9, 0)
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kobo Utilities (2, 16, 9) && Prince PDF (1, 6, 0) && ePub Extended Metadata {Writer} (0, 9, 0) && ePub Extended Metadata {Reader} (0, 9, 0) && ePub Extended Metadata (0, 9, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[0.98] main UI initialized...
[0.98] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Governmental Accounting, Auditing, and Financial Reporting - Copy.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Governmental Accounting, Auditing, and Financial Reporting - Copy.epub is a secure Adobe Adept ePub for UUID 67072f65-5f4f-43ae-86b5-d0ab9bac5ce9
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "C:\Users\luisa\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 343, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\luisa\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[11.47] splash screen hidden
[11.47] Started up in 11.47 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x18\x8e\xbb\t\x91\xa4-[$H\x9d\xbf\x9f\x13q\xd2\n\xcc\xe7\xfb>\x98m#\xdcxe7M\xe8f\x82', b'E:\\Governmental Accounting, Auditing, and Financial Reporting - Copy.epub']
Added Governmental Accounting, Auditing, and Financial Reporting to db in: 2.0

________________________________

**Comment by lsarios9144** [comment]
> For calibre 6, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

It still did not work:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kobo Utilities (2, 16, 9) && Prince PDF (1, 6, 0) && ePub Extended Metadata {Writer} (0, 9, 0) && ePub Extended Metadata {Reader} (0, 9, 0) && ePub Extended Metadata (0, 9, 0)
calibre 6.22  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kobo Utilities (2, 16, 9) && Prince PDF (1, 6, 0) && ePub Extended Metadata {Writer} (0, 9, 0) && ePub Extended Metadata {Reader} (0, 9, 0) && ePub Extended Metadata (0, 9, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouch'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[0.98] main UI initialized...
[0.98] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Governmental Accounting, Auditing, and Financial Reporting - Copy.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Governmental Accounting, Auditing, and Financial Reporting - Copy.epub is a secure Adobe Adept ePub for UUID 67072f65-5f4f-43ae-86b5-d0ab9bac5ce9
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "C:\Users\luisa\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 343, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\luisa\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[11.47] splash screen hidden
[11.47] Started up in 11.47 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x18\x8e\xbb\t\x91\xa4-[$H\x9d\xbf\x9f\x13q\xd2\n\xcc\xe7\xfb>\x98m#\xdcxe7M\xe8f\x82', b'E:\\Governmental Accounting, Auditing, and Financial Reporting - Copy.epub']
Added Governmental Accounting, Auditing, and Financial Reporting to db in: 2.0

**Comment by ElleKayEm** [comment]
Is this the same PC and user where you have the installation of ADE which you used to download the book?
