### ISSUE TITLE
DRM blocking conversion on KFX file

### ISSUE THREAD

**Issue by waterscaped** [apprenticeharper/DeDRM_tools#2256]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## DRM blocking conversion on KFX file
I am trying to download and convert a Kindle Unlimited book. I was able to get the KFX file off of my Kindle, however when I try to convert it, Calibre tells me that it has DRM installed so I'm unable to do so.

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 3, 0) && Barnes & Noble (1, 5, 2) && Fantastic Fiction (1, 6, 4) && Goodreads (1, 7, 9) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0)
calibre 6.23  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 3, 0) && Barnes & Noble (1, 5, 2) && Fantastic Fiction (1, 6, 4) && Goodreads (1, 7, 9) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.08] main UI initialized...
[1.08] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.3.0: Importing C:/Users/Taylor/Documents/eBooks/The Ellsworth Assortment (unfinished)/Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\Taylor\AppData\Local\Temp\calibre_jborg9in\nm4xzu08.kfx-zip
DeDRM v10.0.9: Trying to decrypt nm4xzu08.kfx-zip
[6.88] splash screen hidden
[6.88] Started up in 6.88 seconds with 66 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 642 b'\x01\x00\x00\x00\x0c\x00\x00\x00`\x01\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d:\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xaf&\x00\x01\x00&\x00\xef\xbe\x11\x00\x00\x00\xb5\xb1\xfa\x16\x802\xd4\x01\xbe\xe9\xb0W\xd3\xd0\xd9\x01X\xba\xf4i\xd3\xd0\xd9\x01\x14\x00T\x001\x00\x00\x00\x00\x00\xfdV\xc2*\x10\x00eBooks\x00\x00>\x00\t\x00\x04\x00\xef\xbe\xebV\xf8|\xfdV\xe12.\x00\x00\x00\xc3\xfe\r\x00\x00\x00$\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Y\x94\x1d\x01e\x00B\x00o\x00o\x00k\x00s\x00\x00\x00\x16\x00\xb0\x001\x00\x00\x00\x00\x00\xfaV3!\x10\x00The Ellsworth Assortment (unfinished)\x00|\x00\t\x00\x04\x00\xef\xbe\xfaV\x04\x1e\xfdV|E.\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19_\xf2\x00T\x00h\x00e\x00 \x00E\x00l\x00l\x00s\x00w\x00o\x00r\x00t\x00h\x00 \x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 b'`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\x8f\x12\x05\t\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 b'\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 b'\x01\x00\x00\x00' 

text/uri-list 218 b'file:///C:/Users/Taylor/Documents/eBooks/The%20Ellsworth%20Assortment%20(unfinished)/Minta%20in%20Spite%20of%20Herself_%20A%20Traditional%20Regency%20Romance%20(The%20Ellsworth%20Assortment%20Book%203)_B0BP49HK4Y.kfx\r\n' 

application/x-qt-windows-mime;value="FileName" 54 b'C:\\Users\\Taylor\\DOCUME~1\\eBooks\\THEELL~1\\MINTAI~1.KFX\x00' 

application/x-qt-windows-mime;value="FileContents" 0 b'' 

application/x-qt-windows-mime;value="FileNameW" 354 b'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00T\x00a\x00y\x00l\x00o\x00r\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00e\x00B\x00o\x00o\x00k\x00s\x00\\\x00T\x00h\x00e\x00 \x00E\x00l\x00l\x00s\x00w\x00o\x00r\x00t\x00h\x00 \x00A\x00s\x00s\x00o\x00r\x00t\x00m\x00e\x00n\x00t\x00 \x00(\x00u\x00n\x00f\x00i\x00n\x00i\x00s\x00h\x00e\x00d\x00)\x00\\\x00M\x00i\x00n\x00t\x00a\x00 \x00i\x00n\x00 \x00S\x00p\x00i\x00t\x00e\x00 \x00o\x00f\x00 \x00H\x00e\x00r\x00s\x00e\x00l\x00f\x00_\x00 \x00A\x00 \x00T\x00r\x00a\x00d\x00i\x00t\x00i\x00o\x00n\x00a\x00l\x00 \x00R\x00e\x00g\x00e\x00n\x00c\x00y\x00 \x00R\x00o\x00m\x00a\x00n\x00c\x00e\x00 \x00(\x00T\x00h\x00e\x00 \x00E\x00l\x00l\x00s\x00w\x00o\x00r\x00t\x00h\x00 \x00A\x00s\x00s\x00o\x00r\x00t\x00m\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 b'\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00F\xa0\xc3+\xd1\xd9\x01\x00\x00\x00\x00\x00\x00\x00\x00\xf49\xde\xc2+\xd1\xd9\x01\x00\x00\x00\x00\xab\xb9\x04\x00M\x00i\x00n\x00t\x00a\x00 \x00i\x00n\x00 \x00S\x00p\x00i\x00t\x00e\x00 \x00o\x00f\x00 \x00H\x00e\x00r\x00s\x00e\x00l\x00f\x00_\x00 \x00A\x00 \x00T\x00r\x00a\x00d\x00i\x00t\x00i\x00o\x00n\x00a\x00l\x00 \x00R\x00e\x00g\x00e\x00n\x00c\x00y\x00 \x00R\x00o\x00m\x00a\x00n\x00c\x00e\x00 \x00(\x00T\x00h\x00e\x00 \x00E\x00l\x00l\x00s\x00w\x00o\x00r\x00t\x00h\x00 \x00A\x00s\x00s\x00o\x00r\x00t\x00m\x00e\x00n\x00t\x00 \x00B\x00o\x00o\x00k\x00 \x003\x00)\x00_\x00B\x000\x00B\x00P\x004\x009\x00H\x00K\x004\x00Y\x00.\x00k\x00f\x00x\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="IsShowingLayered" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragWindow" 4 b'\xe0\x07\x1e\x00' 

application/x-qt-windows-mime;value="IsComputingImage" 4 b'\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DropDescription" 1044 b'\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DisableDragText" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="IsShowingText" 4 b'\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="Preferred DropEffect" 4 b'\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="ComputedDragImage" 4 b'\x8f\x12\x05\t' 


Firefox rurl: None None
URLS: ['file:///C:/Users/Taylor/Documents/eBooks/The%20Ellsworth%20Assortment%20(unfinished)/Minta%20in%20Spite%20of%20Herself_%20A%20Traditional%20Regency%20Romance%20(The%20Ellsworth%20Assortment%20Book%203)_B0BP49HK4Y.kfx']
Paths: ['C:/Users/Taylor/Documents/eBooks/The Ellsworth Assortment (unfinished)/Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx']
Extensions: frozenset({'kfx'})
Decrypting KFX-ZIP ebook: nm4xzu08
Found 0 keys to try after 0.6 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Taylor\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Taylor\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4000831494' and UserName 'Taylor'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: nm4xzu08
Got DSN key from database key_0
Found 1 keys to try after 0.8 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.3.0: Packaging C:\Users\Taylor\AppData\Local\Temp\calibre_jborg9in\nm4xzu08.kfx-zip
Processing container: Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Taylor\AppData\Local\Temp\calibre_jborg9in\z8ml_fsb_add_books\0\Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Minta in Spite of Herself A Traditional Regency Romance (The Ellsworth Assortment Book 3) B0BP49HK4Y to db in: 0.1
Added 1 books in 1.6 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (Minta in Spite of Herself A Traditional Regency Romance (The Ellsworth Assortment Book 3) B0BP49HK4Y) finished
Convert book 1 of 1 (Minta in Spite of Herself A Traditional Regency Romance (The Ellsworth Assortment Book 3) B0BP49HK4Y)

	DeDRM v10.0.9: Trying to decrypt t1jnuslc.kfx-zip
	Decrypting KFX-ZIP ebook: t1jnuslc
	Found 0 keys to try after 0.6 seconds
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
	searching for kinfoFiles in C:\Users\Taylor\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Taylor\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '4000831494' and UserName 'Taylor'
	DeDRM v10.0.9: Found 1 new key
	Decrypting KFX-ZIP ebook: t1jnuslc
	Got DSN key from database key_0
	Found 1 keys to try after 0.8 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher

	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1030, in run

	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  verbose: 2

	  output_profile: 'generic_eink'

	  read_metadata_from_opf: 'C:\\Users\\Taylor\\AppData\\Local\\Temp\\calibre_jborg9in\\l1_xk40w.opf'

	Resolved conversion options

	calibre version: 6.23.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000221F493A920>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000221F493A620>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Taylor\\AppData\\Local\\Temp\\calibre_jborg9in\\l1_xk40w.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v10.0.9: Trying to decrypt t1jnuslc.kfx-zip
	Decrypting KFX-ZIP ebook: t1jnuslc
	Found 0 keys to try after 0.0 seconds
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Taylor\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Taylor\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '4000831494' and UserName 'Taylor'
	DeDRM v10.0.9: Found 1 new key
	Decrypting KFX-ZIP ebook: t1jnuslc
	Got DSN key from database key_0
	Found 1 keys to try after 0.2 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook

	  File "C:\Users\Taylor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher

	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1030, in run

	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\Taylor\AppData\Local\Temp\calibre_jborg9in\t1jnuslc.kfx-zip

	Software versions: KFX Input 2.3.0, calibre 6.23, Windows-10-10.0.19045-SP0

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\Taylor\AppData\Local\Temp\calibre_jborg9in\t1jnuslc.kfx-zip

	Processing container: Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 101, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Minta in Spite of Herself_ A Traditional Regency Romance (The Ellsworth Assortment Book 3)_B0BP49HK4Y.kfx has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 121, in convert

	calibre.ebooks.DRMError: This book has DRM!

```
</details>

**Comment by ElleKayEm** [comment]
Answered here: https://github.com/noDRM/DeDRM_tools/issues/390
