### ISSUE TITLE
Calibre 5.6 and dedrm 7.02

### ISSUE THREAD

**Issue by siango66** [apprenticeharper/DeDRM_tools#2257]
I cannot open kindle books downloaded through kindle 1.17...still few months ago all work now no... I post the txt of error:
calibre Log di debug
calibre 5.6  embedded-python: True is64bit: False
Windows-8.1-6.3.9600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 5.6  embedded-python: True is64bit: False
Windows-8.1-6.3.9600 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.18934911242603 x 96.33185185185185
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
Key 'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.09] main UI initialized...
[1.09] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt B00FF4AU1U_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
[16.77] splash screen hidden
[16.77] Started up in 16.77 seconds with 304 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x98\x95\xb2\xbf\x83\xf1U\xc6\x04\x89 \x7f\xe4B\x8b\x97\xc6\xd2\xbd\x9f\x13\xd8t\x11}\xb2\x89Z`\xcb\xd5\xb7', b'D:\\kin new\\B00FF4AU1U_EBOK.azw']
Decrypting Kindle Format 8 ebook: La Terza Alternativa (Self Help) (Italian Edition)
Got DSN key from database default_key_3
Got DSN key from database default_key_4
Got DSN key from database default_key_5
Got DSN key from database default_key_6
Got DSN key from database default_key_7
Got DSN key from database default_key_8
Found 30 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 30 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Alessio\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 30 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added La Terza Alternativa (Self Help) (Italian Edition) to db in: 1.0
Added 1 books in 2.5 seconds
Worker Launch took: 0.25656747817993164
Job: 0 Converti libro 1 di 1 (La Terza Alternativa (Self Help) (Italian Edition)) finished
Converti libro 1 di 1 (La Terza Alternativa (Self Help) (Italian Edition))	DeDRM v7.2.1: Trying to decrypt 4lbmx1x4.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: La Terza Alternativa (Self Help) (Italian Edition)
	Got DSN key from database default_key_3
	Got DSN key from database default_key_4
	Got DSN key from database default_key_5
	Got DSN key from database default_key_6
	Got DSN key from database default_key_7
	Got DSN key from database default_key_8
	Found 30 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 30 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Alessio\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:	  pdf_serif_family: 'MS Shell Dlg 2'	  read_metadata_from_opf: 'C:\\Users\\Alessio\\AppData\\Local\\Temp\\calibre__dgt_9as\\ofcltlln.opf'	  cover: 'C:\\Users\\Alessio\\AppData\\Local\\Temp\\calibre__dgt_9as\\4z6plqwo.jpeg'	  pdf_sans_family: 'MS Shell Dlg 2'	  verbose: 2	Resolved conversion options	calibre version: 5.6.0	{'asciiize': False,	 'author_sort': None,	 'authors': None,	 'base_font_size': 0.0,	 'book_producer': None,	 'change_justification': 'original',	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "	            "'i')) or @class = 'chapter']",	 'chapter_mark': 'pagebreak',	 'comments': None,	 'cover': 'C:\\Users\\Alessio\\AppData\\Local\\Temp\\calibre__dgt_9as\\4z6plqwo.jpeg',	 'custom_size': None,	 'debug_pipeline': None,	 'dehyphenate': True,	 'delete_blank_paragraphs': True,	 'disable_font_rescaling': False,	 'duplicate_links_in_toc': False,	 'embed_all_fonts': False,	 'embed_font_family': None,	 'enable_heuristics': False,	 'expand_css': False,	 'extra_css': None,	 'filter_css': '',	 'fix_indents': True,	 'font_size_mapping': None,	 'format_scene_breaks': True,	 'html_unwrap_factor': 0.4,	 'input_encoding': None,	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x06C0E880>,	 'insert_blank_line': False,	 'insert_blank_line_size': 0.5,	 'insert_metadata': False,	 'isbn': None,	 'italicize_common_cases': True,	 'keep_ligatures': False,	 'language': None,	 'level1_toc': None,	 'level2_toc': None,	 'level3_toc': None,	 'line_height': 0.0,	 'linearize_tables': False,	 'margin_bottom': 5.0,	 'margin_left': 5.0,	 'margin_right': 5.0,	 'margin_top': 5.0,	 'markup_chapter_headings': True,	 'max_toc_links': 50,	 'minimum_line_height': 120.0,	 'no_chapters_in_toc': False,	 'no_inline_navbars': False,	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x06C0E9E8>,	 'page_breaks_before': "//*[name()='h1' or name()='h2']",	 'paper_size': 'letter',	 'pdf_add_toc': False,	 'pdf_default_font_size': 20,	 'pdf_footer_template': None,	 'pdf_header_template': None,	 'pdf_hyphenate': False,	 'pdf_mark_links': False,	 'pdf_mono_family': 'Courier',	 'pdf_mono_font_size': 16,	 'pdf_odd_even_offset': 0.0,	 'pdf_page_margin_bottom': 72.0,	 'pdf_page_margin_left': 72.0,	 'pdf_page_margin_right': 72.0,	 'pdf_page_margin_top': 72.0,	 'pdf_page_number_map': None,	 'pdf_page_numbers': False,	 'pdf_sans_family': 'MS Shell Dlg 2',	 'pdf_serif_family': 'MS Shell Dlg 2',	 'pdf_standard_font': 'serif',	 'pdf_use_document_margins': False,	 'prefer_metadata_cover': False,	 'preserve_cover_aspect_ratio': False,	 'pretty_print': False,	 'pubdate': None,	 'publisher': None,	 'rating': None,	 'read_metadata_from_opf': 'C:\\Users\\Alessio\\AppData\\Local\\Temp\\calibre__dgt_9as\\ofcltlln.opf',	 'remove_fake_margins': True,	 'remove_first_image': False,	 'remove_paragraph_spacing': False,	 'remove_paragraph_spacing_indent_size': 1.5,	 'renumber_headings': True,	 'replace_scene_breaks': '',	 'search_replace': '[]',	 'series': None,	 'series_index': None,	 'smarten_punctuation': False,	 'sr1_replace': None,	 'sr1_search': None,	 'sr2_replace': None,	 'sr2_search': None,	 'sr3_replace': None,	 'sr3_search': None,	 'start_reading_at': None,	 'subset_embedded_fonts': False,	 'tags': None,	 'timestamp': None,	 'title': None,	 'title_sort': None,	 'toc_filter': None,	 'toc_threshold': 6,	 'toc_title': None,	 'transform_css_rules': '[]',	 'uncompressed_pdf': False,	 'unit': 'inch',	 'unsmarten_punctuation': False,	 'unwrap_lines': True,	 'use_auto_toc': False,	 'use_profile_size': False,	 'verbose': 2}	Running file type plugin DeDRM failed with traceback:	Traceback (most recent call last):	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 30 PIDs tried.		During handling of the above exception, another exception occurred:		Traceback (most recent call last):	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins	  File "calibre_plugins.dedrm.__init__", line 633, in run	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md	DeDRM v7.2.1: Trying to decrypt 4lbmx1x4.azw
	MobiDeDrm v1.0.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: La Terza Alternativa (Self Help) (Italian Edition)
	Got DSN key from database default_key_3
	Got DSN key from database default_key_4
	Got DSN key from database default_key_5
	Got DSN key from database default_key_6
	Got DSN key from database default_key_7
	Got DSN key from database default_key_8
	Found 30 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 30 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Alessio\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:	Traceback (most recent call last):	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 30 PIDs tried.		During handling of the above exception, another exception occurred:		Traceback (most recent call last):	  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins	  File "calibre_plugins.dedrm.__init__", line 633, in run	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md	InputFormatPlugin: MOBI Input running	on C:\Users\Alessio\AppData\Local\Temp\calibre__dgt_9as\4lbmx1x4.azw	Found KF8 MOBI of type 'standalone'	Traceback (most recent call last):	  File "runpy.py", line 194, in _run_module_as_main	  File "runpy.py", line 87, in _run_code	  File "site.py", line 82, in <module>	  File "site.py", line 77, in main	  File "site.py", line 49, in run_entry_point	  File "calibre\utils\ipc\worker.py", line 215, in main	  File "calibre\gui2\convert\gui_conversion.py", line 41, in gui_convert_override	  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run	  File "calibre\customize\conversion.py", line 245, in __call__	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert	  File "calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__	  File "calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm	calibre.ebooks.DRMError: La Terza Alternativa (Self Help) (
alian Edition)

**Comment by ElleKayEm** [comment]
DeDRM cannot find an installation of Kindle for PC to get the key from.

**Comment by siango66** [comment]
You're very kind. Issue solved! Thks a lot

Kindly

Alessio

Il gio 24 ago 2023, 14:42 ElleKayEm ***@***.***> ha scritto:

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
