### ISSUE TITLE
Calibre 6.25 and dedrm 7.2.1

### ISSUE THREAD

**Issue by 93ernesto** [apprenticeharper/DeDRM_tools#2258]
I cannot open this epub downloaded through Google Play Books. Thanks

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.86] main UI initialized...
[0.86] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 9788412511802-2.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: 9788412511802-2.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Trying Encryption key urn:uuid:ca30801a-ea90-4bce-9f20-49bde97a56ae
Could not decrypt _h0d7149.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 425, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 343, in __init__
  File "calibre_plugins.dedrm.ineptepub", line 298, in __init__
  File "Crypto\Cipher\AES.py", line 232, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v7.2.1: Failed to decrypt with key urn:uuid:ca30801a-ea90-4bce-9f20-49bde97a56ae after 0.2 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[3.16] splash screen hidden
[3.17] Started up in 3.17 seconds with 9 books
Added 9788412511802 to db in: 0.3
Exception ignored in: <function NativeFunction.__del__ at 0x0000017E9B320EE0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000017E9B320EE0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3 or pre-release 10.0.9: https://github.com/noDRM/DeDRM_tools/releases

**Comment by 93ernesto** [comment]
With pre-release 10.0.9 still does not work...

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (7, 2, 1)
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.88] main UI initialized...
[0.88] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt 9788412511802.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: 9788412511802.epub is a secure Adobe Adept ePub for UUID 4e317862-0981-4892-8683-367e3cc11bf6
DeDRM v10.0.9: Trying Encryption key ca30801a-ea90-4bce-9f20-49bde97a56ae_AdobeID_
4o_upoao.epub is a secure Adobe Adept ePub.
Could not decrypt 4o_upoao.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\ernes\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\ernes\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 232, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key ca30801a-ea90-4bce-9f20-49bde97a56ae_AdobeID_ after 0.3 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
Found 1 keys
DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.09] splash screen hidden
[3.09] Started up in 3.09 seconds with 9 books
Added 9788412511802 to db in: 0.3

**Comment by ElleKayEm** [comment]
Was this book downloaded with the current installation of ADE on the same machine and user where you have calibre/DeDRM?  Delete any Adobe key already in DeDRM's customization and re-add your book letting DeDRM automatically retrieve the key.

**Comment by 93ernesto** [comment]
Thank you so much. I will have to ask Google to reset my device limit, because it has been reached, but i think the problem will solve.
