### ISSUE TITLE
Failed to Convert Kindle book

### ISSUE THREAD

**Issue by Pivot021** [apprenticeharper/DeDRM_tools#2265]
Hey all,

Books Import into Calibre fine, author and cover page all show up good. Converting to PDF fails though. I used the KFX plug in too.

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.26  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (7, 2, 1)
calibre 6.26  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.52] main UI initialized...
[1.52] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing C:\Users\Jeremy\Documents\My Kindle Content\B006TH9RNO_EBOK\B006TH9RNO_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Jeremy\AppData\Local\Temp\calibre_6_dq434s\0i6as8ro.kfx-zip
DeDRM v7.2.1: Trying to decrypt 0i6as8ro.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 0i6as8ro
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Jeremy\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Jeremy\AppData\Local\Amazon\Kindle\storage\.kinf2018
[24.73] splash screen hidden
[24.73] Started up in 24.73 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x12\xc0g%\x97\xa3}\xb4\n\xbcW?\xc7b\xa6\xbe\xb3\x9f\xe6\xc6E\xf2[\xa7\x06\xc0N\x9b\xb3\xd4vQ', b'C:\\Users\\Jeremy\\Documents\\My Kindle Content\\B006TH9RNO_EBOK']
Decrypted key file using IDString '2126974450' and UserName 'Jeremy'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: 0i6as8ro
Got DSN key from database default_key_1
Found 1 keys to try after 1.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.5.0: Packaging C:\Users\Jeremy\AppData\Local\Temp\calibre_6_dq434s\0i6as8ro.kfx-zip
Processing container: B006TH9RNO_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B006TH9RNO_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Jeremy\AppData\Local\Temp\calibre_6_dq434s\mrf8jpvs_add_books\0\B006TH9RNO_EBOK.kfx-zip
calibre 6.26  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre\gui2\convert\single.py", line 288, in accept
AttributeError: 'MetadataWidget' object has no attribute 'opf_file'

Added CR!HKS2BZJDE94PBDBNP3TCHGQ5GTYQ.azw to db in: 0.0
Added 1 books in 2.1 seconds
Worker Launch took: 0.00 seconds
Job: 0 Convert book 1 of 1 (CR!HKS2BZJDE94PBDBNP3TCHGQ5GTYQ.azw) finished
Convert book 1 of 1 (CR!HKS2BZJDE94PBDBNP3TCHGQ5GTYQ.azw)
	DeDRM v7.2.1: Trying to decrypt 0enbe8xm.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: 0enbe8xm
	Got DSN key from database default_key
	Found 1 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Jeremy\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Jeremy\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2126974450' and UserName 'Jeremy'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: 0enbe8xm
	Got DSN key from database default_key_1
	Found 1 keys to try after 1.5 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_mono_family: 'Courier New'
	  cover: 'C:\\Users\\Jeremy\\AppData\\Local\\Temp\\calibre_6_dq434s\\8dnagbk0.jpeg'
	  verbose: 2
	  read_metadata_from_opf: 'C:\\Users\\Jeremy\\AppData\\Local\\Temp\\calibre_6_dq434s\\zaf3ypic.opf'
	  output_profile: 'kindle'
	  pdf_serif_family: 'Arial'
	  pdf_sans_family: 'Arial'
	Resolved conversion options
	calibre version: 6.26.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\Jeremy\\AppData\\Local\\Temp\\calibre_6_dq434s\\8dnagbk0.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001DCB8310130>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000001DCB8310C70>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_no_cover': False,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Arial',
	 'pdf_serif_family': 'Arial',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\Jeremy\\AppData\\Local\\Temp\\calibre_6_dq434s\\zaf3ypic.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v7.2.1: Trying to decrypt 0enbe8xm.kfx-zip
	Decrypting KFX-ZIP ebook: 0enbe8xm
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Jeremy\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Jeremy\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2126974450' and UserName 'Jeremy'
	DeDRM v7.2.1: Found 1 new key
	Decrypting KFX-ZIP ebook: 0enbe8xm
	Got DSN key from database default_key_1
	Found 1 keys to try after 1.4 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.a4d3b939-6542-4080-b9ca-5243395fadb2.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
	  File "C:\Users\Jeremy\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on C:\Users\Jeremy\AppData\Local\Temp\calibre_6_dq434s\0enbe8xm.kfx-zip
	Software versions: KFX Input 2.5.0, calibre 6.26, Windows-10-10.0.22621-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Jeremy\AppData\Local\Temp\calibre_6_dq434s\0enbe8xm.kfx-zip
	Processing container: B006TH9RNO_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B006TH9RNO_EBOK.azw has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
	  File "calibre\customize\conversion.py", line 242, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 121, in convert
	calibre.ebooks.DRMError: This book has DRM!

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
