### ISSUE TITLE
i got this issue, cannot seem to debug and transfer to kindle

### ISSUE THREAD

**Issue by josephinecassar** [apprenticeharper/DeDRM_tools#2266]
Hi, I need help please. I've created a Calibre account and followed all the steps mentioned by different people and downloaded lots of DeDRMs, the latest being the one from you people. I now ran Calibre in debug mode, imported the book I have bought from my iPad book store but still, got the notice that my book cannot be converted as it is DRM locked. I also got the following note: ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.2.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.11191135734072 x 96.09458128078816
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt Be Careful What You Wish For.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “Be Careful What You Wish For.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
[14.00] splash screen hidden
[14.00] Started up in 14.00 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b' \xd8Sj\x82\x14\x8f\x91\x9d\xe2\x17\n\xa9\x1d\x9e\xa8u&\xf3~\x18\x0f\xd89u\x88\x84\x18\xcf\xaa\xfc\xb3', b'C:\\Users\\cjt\\Downloads\\Automatically Add to iTunes\\Be Careful What You Wish For.epub']
Added Be Careful What You Wish For to db in: 0.1
Added 1 books in 0.8 seconds
I am using Acer PC with windows 10 64-bit and bought the book from iPad book store

**Comment by ElleKayEm** [comment]
Your search continues.  This tool doesn't support DRM removal from Apple Books.  I think there might be a commercial program that does, but I don't know anything about it.

**Comment by josephinecassar** [comment]
Thanks ElleKayEm, maybe someone will reply here and suggest a program I can use as reading books on a shiny, glossy ipad is annoying + drains its battery
