### ISSUE TITLE
Recent Kindle purchase DRM not removing properly - Solved!

### ISSUE THREAD

**Issue by cjbecker17** [apprenticeharper/DeDRM_tools#2269]
calibre Debug log
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-86-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-86-generic', '#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023')
Python 3.10.12
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-86-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-86-generic', '#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023')
Python 3.10.12
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.02] splash screen shown
[0.02] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.34] main UI initialized...
[0.34] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Night Raven (The Moonwind Mysteries), The - Johan Rundberg.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Night Raven (The Moonwind Mysteries)
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
DeDRM v10.0.9: Exception when getting default Kindle Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 949, in KindleMobiDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.61] splash screen hidden
[3.61] Started up in 3.61 seconds with 223 books
Added The Night Raven (The Moonwind Mysteries) to db in: 0.0
Added 1 books in 0.5 seconds
Worker Launch took: 0.01 seconds
Job: 0 Convert book 1 of 1 (The Night Raven (The Moonwind Mysteries)) finished
Convert book 1 of 1 (The Night Raven (The Moonwind Mysteries))
	DeDRM v10.0.9: Trying to decrypt t7g17bns.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: The Night Raven (The Moonwind Mysteries)
	Found 2 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
	DeDRM v10.0.9: Exception when getting default Kindle Key after 0.3 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 949, in KindleMobiDecrypt
	    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
	    pyexec = WinePythonCLI(wineprefix)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
	    self.check_call(["-c", self.py3_test])
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
	    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
	  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
	    retcode = call(*popenargs, **kwargs)
	  File "/usr/lib/python3.10/subprocess.py", line 345, in call
	    with Popen(*popenargs, **kwargs) as p:
	  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'wine'
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw3'
	  read_metadata_from_opf: '/tmp/calibre_5.37.0_tmp_9a96kgz8/h2gs_vgb.opf'
	  verbose: 2
	  cover: '/tmp/calibre_5.37.0_tmp_9a96kgz8/sfwt9tz7.jpeg'
	Resolved conversion options
	calibre version: 5.37.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/tmp/calibre_5.37.0_tmp_9a96kgz8/sfwt9tz7.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f34fa4895d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7f34fa48a200>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/tmp/calibre_5.37.0_tmp_9a96kgz8/h2gs_vgb.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt t7g17bns.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: The Night Raven (The Moonwind Mysteries)
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	DeDRM v10.0.9: Exception when getting default Kindle Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 949, in KindleMobiDecrypt
	    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
	    pyexec = WinePythonCLI(wineprefix)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
	    self.check_call(["-c", self.py3_test])
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
	    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
	  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
	    retcode = call(*popenargs, **kwargs)
	  File "/usr/lib/python3.10/subprocess.py", line 345, in call
	    with Popen(*popenargs, **kwargs) as p:
	  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'wine'
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/cjbecker/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_5.37.0_tmp_9a96kgz8/t7g17bns.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 21, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	    gui_convert(input, output, recommendations, notification=notification,
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
	    self.oeb = self.input_plugin(stream, self.opts,
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 242, in __call__
	    ret = self.convert(stream, options, file_ext,
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	    opf = os.path.abspath(mr())
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	    self.mobi6_reader.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: The Night Raven (The Moonwind Mysteries)
	Error in sys.excepthook:
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
	    with os.fdopen(os.open(pr_filename,
	FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_calibre-parallel.1000.crash'
	
	Original exception was:
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 21, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	    gui_convert(input, output, recommendations, notification=notification,
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
	    self.oeb = self.input_plugin(stream, self.opts,
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 242, in __call__
	    ret = self.convert(stream, options, file_ext,
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	    opf = os.path.abspath(mr())
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	    self.mobi6_reader.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: The Night Raven (The Moonwind Mysteries)

Added /home/cjbecker/Desktop/Rundberg, Johan/Night Raven (The Moonwind Mysteries), The to db in: 0.1
Added 1 books in 0.2 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then make sure you enter that Kindle's serial number correctly into DeDRM's customization.

**Comment by cjbecker17** [comment]
Thank you so much! Worked like a charm. In the past when I updated DRM versions, Calibre automatically pulled my E-ink serial number from the old DRM; it didn't this time. I will not make that mistake again.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
