### ISSUE TITLE
[QUESTION] DeDRM KFX-zip book is not working. How to solve?

### ISSUE THREAD

**Issue by sanwalibrary** [apprenticeharper/DeDRM_tools#2272]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.28.1 Portable embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
calibre 6.28.1 Portable embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.28608414239481 x 112.75838150289016
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.3 obok::action_err.py - loading translations
Using proxies: {'http': '10.77.8.70:8080;', 'https': '10.77.8.70:8080;', 'ftp': '10.77.8.70:8080;'}
[4.55] main UI initialized...
[4.55] Hiding splash screen
Starting QuickView
[18.77] splash screen hidden
[18.77] Started up in 18.77 seconds with 1 books
Failed to check for calibre update: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Using proxies: {'http': '10.77.8.70:8080;', 'https': '10.77.8.70:8080;', 'ftp': '10.77.8.70:8080;'}
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing D:/Calibre/com.amazon.kindle/files/B0CF4XWGR8/CR!484VBZ97556R968Y7WJXCY249FRE.kfx
Gather KFX-ZIP (from KFX Input): Gathered 20 file(s) as C:\Users\sandrine.t\AppData\Local\Temp\calibre_9z48de0x\47m46znm.kfx-zip
DeDRM v10.0.9: Trying to decrypt 47m46znm.kfx-zip
Decrypting KFX-ZIP ebook: 47m46znm
Found 0 keys to try after 1.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.b8b006c8-ab73-4b8d-ad3b-98e1ca4cfffa.ast
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "D:\Calibre\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "D:\Calibre\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: local variable 'ex' referenced before assignment
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 1.4 seconds
searching for kinfoFiles in C:\Users\sandrine.t\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "D:\Calibre\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "D:\Calibre\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "D:\Calibre\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.5.0: Packaging C:\Users\sandrine.t\AppData\Local\Temp\calibre_9z48de0x\47m46znm.kfx-zip
Processing container: CR!14HXWKABH10KXBNBNW065QQMSKSN.kfx
Processing container: CR!1A1V74N5BS5HV4W11DVZVAGCD8QX.kfx
Processing container: CR!484VBZ97556R968Y7WJXCY249FRE.kfx
Processing container: CR!A2HTFAZGWD3E59Q3XERSPKGN9XEX.kfx
Processing container: CR!A68DD082BN53ZASM4JN2PMG4SNTY.kfx
Processing container: CR!B6QYK8FZ2S5P5C8Y49J2ZQ80S5CN.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container CR!B6QYK8FZ2S5P5C8Y49J2ZQ80S5CN.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\sandrine.t\AppData\Local\Temp\calibre_9z48de0x\4ih9dris_add_books\0\CR!484VBZ97556R968Y7WJXCY249FRE.kfx-zip

```
</details>

**Comment by ElleKayEm** [comment]
You won't be able to decrypt a book imported from your Android.  There's no way to get the key from that version.  Try downloading with Kindle for PC.

**Comment by sanwalibrary** [comment]
Ahh I see. Thank you.
I will try with Kindle for PC.
