### ISSUE TITLE
[ISSUE] architecture issue when loading plugin into calibre

### ISSUE THREAD

**Issue by will-iamalpine** [apprenticeharper/DeDRM_tools#2275]
When importing the plugin into calibre, I hit an error (logs below). It appears to be an architecture issue, but I think that might not actually be correct since I indeed do have arm64? The error shows up when I double-click the plugin:

<img width="1443" alt="image" src="https://github.com/apprenticeharper/DeDRM_tools/assets/8934290/94b5df2a-1890-4ba8-9be6-40661af66a0c">

## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Calibre log</summary>
calibre, version 6.29.0
ERROR: Unhandled exception: <b>OSError</b>:dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

calibre 6.29  embedded-python: True
macOS-14.0-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.0.0', 'Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('14.0', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 298, in double_clicked
  File "calibre/gui2/preferences/plugins.py", line 378, in modify_plugin
  File "calibre/customize/__init__.py", line 163, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 656, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
For calibre 6, try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by will-iamalpine** [comment]
Thanks for the prompt response; this worked perfectly, thank you so much!
