### ISSUE TITLE
DRM won't convert

### ISSUE THREAD

**Issue by Flooroom** [apprenticeharper/DeDRM_tools#2276]
Calibre version 6.29.0 created by Kovid Goyal
DeDRM (7.2.1) by Apprentice Alf
Obtain ebook from
Kindle version 2.0.1 (70350) Last updated 11/02/2023 PC app 
Windows 11 Home
Version 22H2
OS build 22621.2506
64-bit operating system, x64-based processor
Windows Feature Experience Pack 1000.22677.1000

calibre, version 6.29.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (CR!2NF5F0018D6GZ3JZ5NNG208QW9FA.azw)

Convert book 1 of 1 (CR!2NF5F0018D6GZ3JZ5NNG208QW9FA.azw)
Conversion options changed from defaults:
  read_metadata_from_opf: 'C:\\Users\\gordg\\AppData\\Local\\Temp\\calibre_sv395zj0\\jytdkg53.opf'
  output_profile: 'generic_eink'
  pdf_mono_family: 'Courier New'
  pdf_serif_family: 'Arial'
  verbose: 2
  pdf_sans_family: 'Arial'
Resolved conversion options
calibre version: 6.29.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'formatting_type': 'auto',
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B5B6BCD7E0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markdown_extensions': 'footnotes, tables, toc',
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001B5B6BCD510>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'paragraph_type': 'auto',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_no_cover': False,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Arial',
 'pdf_serif_family': 'Arial',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'preserve_spaces': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\gordg\\AppData\\Local\\Temp\\calibre_sv395zj0\\jytdkg53.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'txt_in_remove_indents': False,
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: TXT Input running
on C:\Users\gordg\AppData\Local\Temp\calibre_sv395zj0\rv5s1l2k.md
Reading text from file...
File extension indicates particular formatting. Forcing formatting type to: markdown
Detected input encoding as  with a confidence of 0%
No input encoding specified and could not auto detect using utf-8
Running text through markdown conversion...
Language not specified
Creator not specified
Building file list...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\txt_input.py", line 318, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 105, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 169, in create_oebbook
  File "calibre\ebooks\html\input.py", line 287, in get_filelist
  File "calibre\ebooks\html\input.py", line 265, in traverse
  File "calibre\ebooks\html\input.py", line 109, in __init__
ValueError: embedded null character
IgnoreFile("Could not read from file: C:\\Users\\gordg\\AppData\\Local\\Temp\\calibre_sv395zj0\\e4jq1abx_plumber\\Y ٌ L\x06\x1b[ɿ <\x1f\x04y\x15YԐ   \x08bď   U A \x01 t \x14 Q (\x95 _ \x12 !\x17  \x0b œ ĩIq\x1b1     \x14ѥ *yU1j\x12 \x18  !  with error: [Errno 22] Invalid argument: 'C:\\\\Users\\\\gordg\\\\AppData\\\\Local\\\\Temp\\\\calibre_sv395zj0\\\\e4jq1abx_plumber\\\\Y ٌ L\\x06\\x1b[ɿ <\\x1f\\x04y\\x15YԐ   \\x08bď   U A \\x01 t \\x14 Q (\\x95 _ \\x12 !\\x17  \\x0b œ ĩIq\\x1b1     \\x14ѥ *yU1j\\x12 \\x18  ! '")

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Install the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290

If you're still having issues, post an import log: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
