### ISSUE TITLE
Unhandled exception after clicking "Customize plugin"

### ISSUE THREAD

**Issue by peterjdann** [apprenticeharper/DeDRM_tools#2280]
**Calibre version**: 6,29.0
**Mac OS version**: 14.1.1
**Error message detail**:
calibre, version 6.29.0
ERROR: Unhandled exception: <b>OSError</b>:dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in &lt;1FCD44A2-E972-3D3D-95D1-4B7BF8459E95&gt; '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in &lt;1FCD44A2-E972-3D3D-95D1-4B7BF8459E95&gt; '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (code signature in &lt;1FCD44A2-E972-3D3D-95D1-4B7BF8459E95&gt; '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (code signature in &lt;1FCD44A2-E972-3D3D-95D1-4B7BF8459E95&gt; '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

calibre 6.29  embedded-python: True
macOS-14.1.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64')
Python 3.10.1
OSX: ('14.1.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 301, in customize_plugin
  File "calibre/gui2/preferences/plugins.py", line 378, in modify_plugin
  File "calibre/customize/__init__.py", line 163, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 656, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <1FCD44A2-E972-3D3D-95D1-4B7BF8459E95> '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <1FCD44A2-E972-3D3D-95D1-4B7BF8459E95> '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (code signature in <1FCD44A2-E972-3D3D-95D1-4B7BF8459E95> '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' (code signature in <1FCD44A2-E972-3D3D-95D1-4B7BF8459E95> '/usr/local/Cellar/openssl@3/3.1.2/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

**Comment by peterjdann** [comment]
Allowing Caibre to run disregarding the system's security policy did not solve this problem.

**Comment by ElleKayEm** [comment]
For calibre 6, try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by peterjdann** [comment]
Thank you so much! You are a life-saver. Worked flawlessly. Brilliant!

**Comment by peterjdann** [comment]
User (ie, my) error. Was using obsolete version of this plugin.
