### ISSUE TITLE
OBOK DrM problem

### ISSUE THREAD

**Issue by maaktrans** [apprenticeharper/DeDRM_tools#2283]
calibre, version 6.25.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.25  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: KePub Input (3, 6, 6) && KePub Output (3, 6, 6) && Kobo Books (1, 9, 2) && Kobo Metadata (1, 2, 0) && Kobo Utilities (2, 16, 13) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

**Comment by maaktrans** [comment]
Source file is a book purchased and loaded to Kobo aura reader. Obok is able to locate when device plugged in the reader but the above Unhandled exception occurs when DeDRM is attempted. Hav'QfileDe tried this with another purchased book (bought some time ago) and the same result. Note that once Obok is installed, customising the "Kobo Directory" button in plugin options (in Calibre advanced settings) gets an ERROR: unhandled Exception: 'QfileDialog' has no attribute 'ShowDirsonly'

**Comment by ElleKayEm** [comment]
Try Obok 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by maaktrans** [comment]
*Thanks - that worked!*

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
