### ISSUE TITLE
DeDRM not working despite following steps-AZW3

### ISSUE THREAD

**Issue by chrissytrying** [apprenticeharper/DeDRM_tools#2289]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Title

<I am trying to DeDRM a kindle/amazon azw3 download. I downloaded the DeDRM 10.0.3 on top of an older 6 version. Not sure if that does anything but current plugin says v10. I also added my kindle's serial number so am very unsure. Thanks!>

## Log
<details><summary>Log Title</summary>

<Not sure about this>

```ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 2.5
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt [book name].azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: [Book Name}
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\chris\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\chris\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1185040231' and UserName 'chris'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: [Book Name]
Got DSN key from database key_0
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\chris\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[9.19] splash screen hidden
[9.19] Started up in 9.19 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'7RZ\xdcH`1\xf67j\x02\xb8Q\x80x\x92[5(3\xa7\x9e~q\x8c\xc9z\xe8\xf5{Ya', b'C:\\Users\\chris\\Documents\\aSBDS\\[Book name]']
Added [Book Name] to db in: 0.1
Added 1 books in 0.8 seconds

 Failed to decrypt with error: No key found in 2 PIDs tried

```
</details>

**Comment by ElleKayEm** [comment]
You need to choose an E-ink Kindle (not a Fire) for books that are from "download & transfer via usb".  If you don't have an E-ink Kindle, then download with Kindle for PC.  For that you'll probably need DeDRM 10.0.9 and the KFX Input plugin.

**Comment by chrissytrying** [comment]
> You need to choose an E-ink Kindle (not a Fire) for books that are from "download & transfer via usb". If you don't have an E-ink Kindle, then download with Kindle for PC. For that you'll probably need DeDRM 10.0.9 and the KFX Input plugin.

Thank you! I got the KFX. and DeDREM v10.0.9. What do you mean by DL Kindle for PC?

**Comment by ElleKayEm** [comment]
I see you have Kindle for PC installed.  Import a copy of the book downloaded in the app.
