### ISSUE TITLE
DeDRM not working (Adobe Editions)

### ISSUE THREAD

**Issue by ArieVerhagen** [apprenticeharper/DeDRM_tools#2293]
I run Calibre 7.3 on a Macbook Air (Apple M1, Sonoma 14.1.2), and installed the latest (I think) plugin version (7.2.1), but DRM was not removed from both a pdf and an epub file acquired through Adobe Editions.

## Log
<details><summary>Log Title</summary>

```log
Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
2024-01-08 12:22:28.407 calibre-debug[19587:8390618] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Foutopsporingslog
calibre 7.3  embedded-python: True
macOS-14.1.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.1.2', ('', '', ''), 'arm64')
Interface language: nl
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.3  embedded-python: True
macOS-14.1.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.1.2', ('', '', ''), 'arm64')
Interface language: nl
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 93.0000013967199 x 94.00000141173837
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
[0.41] GUI main window shown
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
[0.44] main UI initialized...
[0.44] Hiding splash screen
Blacklisting the DeDRM plugin as it is too old and causes crashes
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 469, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[3.25] splash screen hidden
[3.25] Started up in 3.25 seconds with 33 books
Added The Cambridge Handbook of Linguistic Anthropology to db in: 0.0
Added 1 books in 0.4 seconds

```
</details>

**Comment by ArieVerhagen** [comment]
Somehow I found version 10 on another github page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
This solved the problem!
