### ISSUE TITLE
problem converting using dedrm v10.0.3 

### ISSUE THREAD

**Issue by jipiedra** [apprenticeharper/DeDRM_tools#2295]
Hi, can anyone help me? First time trying..

calibre, version 7.3.0 (win32, embedded-python: True)
Error de conversión: Fallo: Convertido el libro 1 de 1 (TERROR EN CERRO MORENO)

Convertido el libro 1 de 1 (TERROR EN CERRO MORENO)
DeDRM v10.0.3: Trying to decrypt lgf6o4b3.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.1 seconds
Conversion options changed from defaults:
  output_profile: 'kindle_pw3'
  verbose: 2
  read_metadata_from_opf: 'C:\\Users\\jipie\\AppData\\Local\\Temp\\calibre_gtcqjrki\\t_m3ji0e.opf'
  cover: 'C:\\Users\\jipie\\AppData\\Local\\Temp\\calibre_gtcqjrki\\msr7rl3h.jpeg'
Resolved conversion options
calibre version: 7.3.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\jipie\\AppData\\Local\\Temp\\calibre_gtcqjrki\\msr7rl3h.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000226FF8E7550>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x00000226FF8D5FD0>,
 'page_breaks_before': '/',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\jipie\\AppData\\Local\\Temp\\calibre_gtcqjrki\\t_m3ji0e.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt eehrsfvk.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 0.1 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\jipie\AppData\Local\Temp\calibre_gtcqjrki\4dpnr8bn.epub
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 95, in <module>
  File "site.py", line 90, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 238, in __call__
  File "calibre\__init__.py", line 372, in __enter__
PermissionError: [WinError 5] Acceso denegado: 'C:\\Users\\jipie\\AppData\\Local\\Temp\\calibre_gtcqjrki\\k9gbkkie_plumber'

**Comment by ElleKayEm** [comment]
What is the source of your epub?  I'm not really seeing anything useful in this conversion log.  Is it telling you it can't convert due to DRM?  Will it not open in calibre's ebook viewer?

**Comment by jipiedra** [comment]
I bought it from Google play.  I can see it in caliber in the original
format, but when converting it, it generates the problem.

**Comment by ElleKayEm** [comment]
If you can read it in calibre's ebook viewer, then the issue is not DRM.

**Comment by jipiedra** [comment]
So the issue is converting the file to be able to read it in kindle... Do
you have any advise on it?

-jip-

**Comment by ElleKayEm** [comment]
For non-drm ebook issues, I usually look for help in MobileRead's calibre forum.

**Comment by jipiedra** [comment]
Thanks a lot!

-jip-

**Comment by osamacanaan** [comment]
Hello everyone! Can anyone help me?
This is my first time typing.
I installed calibre and the plug-ins and imported a protected Amazon file and this error came up.

calibre, version 6.2.1 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (B0BN224VTY EBOK)

Convert book 1 of 1 (B0BN224VTY EBOK)
DeDRM v10.0.3: Trying to decrypt szguxtpr.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v10.0.3: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Osama Canaan\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Osama Canaan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 228, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  read_metadata_from_opf: 'C:\\Users\\OSAMAC~1\\AppData\\Local\\Temp\\calibre_9ckec2_0\\kmw_zorm.opf'
  verbose: 2
  output_profile: 'generic_eink'
  pdf_sans_family: 'Arial'
  pdf_serif_family: 'Arial'
  pdf_mono_family: 'Courier New'
Resolved conversion options
calibre version: 6.2.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000214DFC88250>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000214DFC8BCD0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Arial',
 'pdf_serif_family': 'Arial',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\OSAMAC~1\\AppData\\Local\\Temp\\calibre_9ckec2_0\\kmw_zorm.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt szguxtpr.azw
DeDRM v10.0.3: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Osama Canaan\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Osama Canaan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 228, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\OSAMAC~1\AppData\Local\Temp\calibre_9ckec2_0\szguxtpr.azw
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 238, in __call__
  File "calibre\__init__.py", line 367, in __enter__
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\OSAMAC~1\\AppData\\Local\\Temp\\calibre_9ckec2_0\\hgtcir6c_plumber'

**Comment by ElleKayEm** [comment]
If you are downloading books with Kindle for PC, calibre needs to be installed on the same computer and user.  You need DeDRM 10.0.9 and the KFX Input plugin.
