### ISSUE TITLE
install returns print ( ) error

### ISSUE THREAD

**Issue by mikibenz** [apprenticeharper/DeDRM_tools#2305]
Hi , I downloaded the zip file, extracted, then used Calibre to install plugin.

When I do this, I get this error:

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(../)?
(calibre_plugins.dedrm._init_. line 165)

Details:

calibre, version 7.7.0
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 165)

calibre 7.7  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 9, 0) && Package KFX (from KFX Input) (2, 9, 0) && Barnes & Noble (1, 5, 3) && KFX metadata reader (from KFX Input) (2, 9, 0) && From KFX (2, 9, 0) && KFX Input (2, 9, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && OverDrive Libby (0, 1, 9)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 308, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 200, in exec_module
  File "calibre\customize\zipplugin.py", line 196, in get_code
  File "calibre_plugins.dedrm.__init__", line 165
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Screenshot:

![image](https://github.com/apprenticeharper/DeDRM_tools/assets/164962017/5b70c70f-826c-4ad1-a2ca-370ef5576c36)

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.9:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by mikibenz** [comment]
> Try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Thank you - this installed now.
