### ISSUE TITLE
[QUESTION] Getting ERROR: not valid for use in process: mapped file has no cdhash

### ISSUE THREAD

**Issue by 101Dude** [apprenticeharper/DeDRM_tools#2314]
Good afternoon. I am running into an error on macOS. I am following directions here:

> Customization
> -------------
> For Kindle ebooks from an E-Ink based Kindle (e.g. Voyage), or books downloaded from the Amazon web site 'for transfer via USB' to an E-Ink base Kindle, you must enter the Kindle's serial number in the customisation dialog.
> 
> When you have finished entering your configuration information, you must click the OK button to save it. If you click the Cancel button, all your changes in all the configuration dialogs will be lost.

This is the output when clicking on that button:

```
calibre, version 7.10.0
ERROR: Unhandled exception: <b>OSError</b>:dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in &lt;E626C437-4BF0-39D1-ABD1-335A76277444&gt; '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in &lt;E626C437-4BF0-39D1-ABD1-335A76277444&gt; '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (code signature in &lt;E626C437-4BF0-39D1-ABD1-335A76277444&gt; '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (code signature in &lt;E626C437-4BF0-39D1-ABD1-335A76277444&gt; '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

calibre 7.10  embedded-python: True
macOS-14.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed Apr 24 21:23:04 PDT 2024; root:xnu-10063.121.3~3/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 298, in customize_plugin
  File "calibre/gui2/preferences/plugins.py", line 375, in modify_plugin
  File "calibre/customize/__init__.py", line 160, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 656, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 205, in exec_module
  File "calibre_plugins.dedrm.config", line 27, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 205, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 205, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in <module>
    AES = _load_crypto()
          ^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.ignoblekeygen", line 184, in _load_crypto
    AES = loader()
          ^^^^^^^^
  File "calibre_plugins.dedrm.ignoblekeygen", line 123, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
                ^^^^^^^^^^^^^^^
  File "ctypes/__init__.py", line 376, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <E626C437-4BF0-39D1-ABD1-335A76277444> '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcrypto.dylib' (no such file), '/usr/local/lib/libcrypto.dylib' (code signature in <E626C437-4BF0-39D1-ABD1-335A76277444> '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (code signature in <E626C437-4BF0-39D1-ABD1-335A76277444> '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (no such file), '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' (code signature in <E626C437-4BF0-39D1-ABD1-335A76277444> '/usr/local/Cellar/openssl@3/3.3.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
```

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
