### ISSUE TITLE
Using Calibre 6.11.0 under Big Sur on mac and DRM plugin 6.8.1 plugin 

### ISSUE THREAD

**Issue by Lillady57** [apprenticeharper/DeDRM_tools#2317]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
calibre, version 6.11.0
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 169)

calibre 6.11  embedded-python: True
macOS-11.7.10-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.7.10', ('', '', ''), 'x86_64')
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 305, in load
  File "polyglot/builtins.py", line 123, in reload
  File "importlib/__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "calibre/customize/zipplugin.py", line 199, in exec_module
  File "calibre/customize/zipplugin.py", line 195, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

```
</details>

**Comment by ElleKayEm** [comment]
That version of DeDRM is too old for the version of calibre you're using.  Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
