### ISSUE TITLE
DeDRM is not work

### ISSUE THREAD

**Issue by floating-7** [apprenticeharper/DeDRM_tools#2320]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Log
<details><summary>ApplicationPaletteChange event ignored</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre 偵錯記錄
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 7.10  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.67] db initialized
[0.67] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.30] GUI main window shown
[1.38] main UI initialized...
[1.38] Hiding splash screen
DeDRM v7.2.1: Trying to decrypt 巨流河十萬冊紀念版.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: 巨流河十萬冊紀念版.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Trying Encryption key default_key
Could not decrypt atfaqyn_.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 425, in decryptBook
  File "calibre_plugins.dedrm.ineptepub", line 343, in __init__
  File "calibre_plugins.dedrm.ineptepub", line 298, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v7.2.1: Failed to decrypt with key default_key after 0.3 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
Found 1 keys
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[39.80] splash screen hidden
[39.80] Started up in 39.80 seconds with 5 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'5\xb7\x8b\xd4\x9a\x82\x8f\xba\xa9\r\x05 \xda9|\x8d~\x1b~\xbe\xff\x18"\x962\x9c\xef\x9c\xaa\xfb\xb5?', b'D:\\Documents\\My Digital Editions\\\xe5\xb7\xa8\xe6\xb5\x81\xe6\xb2\xb3\xe5\x8d\x81\xe8\x90\xac\xe5\x86\x8a\xe7\xb4\x80\xe5\xbf\xb5\xe7\x89\x88.epub']
Exception ignored in: <function NativeFunction.__del__ at 0x0000018D20D8E480>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000018D20D8E480>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Delete the saved Adobe key from DeDRM's customization.  Re-add the book letting DeDRM automatically retrieve the key.  Assuming book was downloaded with ADE on the same computer and user as calibre/DeDRM.
