### ISSUE TITLE
[QUESTION] DRM not being removed

### ISSUE THREAD

**Issue by Shayla93** [apprenticeharper/DeDRM_tools#2327]
Hello, I'm not sure what I'm doing incorrectly, but no matter what I try, the DRM doesn't get removed when I try to convert my Kindle books.

I would appreciate any help on this issue,

Thank you.
---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
FFF: DEBUG: 2024-06-09 17:05:54,987: calibre_plugins.fanficfare_plugin.fff_plugin(218): Plugin FanFicFare macmenuhack file_path:C:\Users\USER\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.12  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && FanFicFare (4, 12, 4) && Obok DeDRM (10, 0, 9)
calibre 7.12  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && FanFicFare (4, 12, 4) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 129.70212765957447 x 91.13621262458472
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.03] GUI main window shown
[1.31] main UI initialized...
[1.31] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt むらさきのスカートの女 (朝日文庫).azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: むらさきのスカートの女 (朝日文庫)
Found 2 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\USER\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\USER\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2792591600' and UserName 'USER'
DeDRM v10.0.9: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: むらさきのスカートの女 (朝日文庫)
Got DSN key from database key_0
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\USER\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[5.58] splash screen hidden
[5.58] Started up in 5.58 seconds with 8 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'2\xe3\x9a\xd1\xca\xa5\x91^\xb1\r\xb9\xec\xb0N\xdbI\rl\xba\xd3/\x17\x18H\xd3s\x95\xaa\xd6|\xb2\xb8', b'C:\\Users\\USER\\Downloads\\\xe3\x82\x80\xe3\x82\x89\xe3\x81\x95\xe3\x81\x8d\xe3\x81\xae\xe3\x82\xb9\xe3\x82\xab\xe3\x83\xbc\xe3\x83\x88\xe3\x81\xae\xe5\xa5\xb3 (\xe6\x9c\x9d\xe6\x97\xa5\xe6\x96\x87\xe5\xba\xab).azw3']
Added むらさきのスカートの女 (朝日文庫) to db in: 0.1
Added 1 books in 1.0 seconds

```
</details>

**Comment by ElleKayEm** [comment]
Is this from or for an E-ink Kindle (not a Fire)?  If so, make sure you have that Kindle's serial number entered correctly into DeDRM's customization.

**Comment by Shayla93** [comment]
> Is this from or for an E-ink Kindle (not a Fire)? If so, make sure you have that Kindle's serial number entered correctly into DeDRM's customization.

The serial number I used is from my Kindle Fire.

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, then download it with Kindle for PC.  Also install the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by Shayla93** [comment]
> If you don't have an E-ink Kindle, then download it with Kindle for PC. Also install the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290

This worked! Thank you so much!
