### ISSUE TITLE
[QUESTION] Plugin not working. DRM not removed. Calibre crashing.

### ISSUE THREAD

**Issue by marta164** [apprenticeharper/DeDRM_tools#2331]
## CheckList

- [x] `The Title` and The `Log Title` are setted correctly.
- [x] Clarified about `my environment`.
- [x] Code block is used for `the log`.

---

## Title

Attempting to use DeDRM plug-in with Calibre to convert .epub file to Kindle format, but DRM is not removed and I am unable to convert. Calibre crashes if I try to edit the plugin in any way.

## Log
<details><summary>Log Title</summary>
Blacklisting the DeDRM plugin as it is too old and causes crashes
ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-07-04 03:29:00.174 calibre-debug[1108:15580] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.13  embedded-python: True
macOS-14.2.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.13  embedded-python: True
macOS-14.2.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 81.50000122400722 x 81.50000122400722
[0.00] Starting up...
[0.01] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.62] GUI main window shown
[0.67] main UI initialized...
[0.67] Hiding splash screen
Blacklisting the DeDRM plugin as it is too old and causes crashes
[10.38] splash screen hidden
[10.38] Started up in 10.38 seconds with 0 books
Added Le Freak to db in: 0.0
Added 1 books in 0.5 seconds
Blacklisting the DeDRM plugin as it is too old and causes crashes
Failed to request permission for showing notification: The operation couldn’t be completed. (UNErrorDomain error 1.)
Worker Launch took: 0.01 seconds
Worker Launch took: 0.03 seconds
Job: 1 Convert book 1 of 1 (Le Freak) finished
Convert book 1 of 1 (Le Freak)
	Blacklisting the DeDRM plugin as it is too old and causes crashes
	Conversion options changed from defaults:
	  read_metadata_from_opf: '/var/folders/my/wx6znrfs06338knlmlv1p_zh0000gn/C/calibre_7.13.0_tmp_rbozb7xz/7w6j5wa0.opf'
	  output_profile: 'kindle'
	  verbose: 2
	Resolved conversion options
	calibre version: 7.13.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x111cc8b10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x111c92290>,
	 'page_breaks_before': '/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/my/wx6znrfs06338knlmlv1p_zh0000gn/C/calibre_7.13.0_tmp_rbozb7xz/7w6j5wa0.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on /var/folders/my/wx6znrfs06338knlmlv1p_zh0000gn/C/calibre_7.13.0_tmp_rbozb7xz/hzvea4yd.epub
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 42, in <module>
	  File "site.py", line 38, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1127, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/epub_input.py", line 293, in convert
	calibre.ebooks.DRMError: hzvea4yd.epub
</details>

**Comment by marta164** [comment]
Seems like I had an old version of DeDRM. Downloaded the latest version and issue is fixed.
