### ISSUE TITLE
Debug info

### ISSUE THREAD

**Issue by arrbee800** [apprenticeharper/DeDRM_tools#2334]
![image](https://github.com/user-attachments/assets/44ec25a2-e12c-49c5-8b24-021c895663c1)
Hi there, have followed the troubleshooting guide as per your steps, see image attached.

Books downloaded via kindle usb mode, windows laptop

**Comment by arrbee800** [comment]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.14  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.14  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.71098265895952
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.55] GUI main window shown
[0.59] main UI initialized...
[0.59] Hiding splash screen
[5.53] splash screen hidden
[5.53] Started up in 5.53 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xff\xee\xab\x7fU\t\x0e\x11iQ\xfdNt\xcd\xce\x9f\x82\x99*#N\xf1\xd1v\x0b+S0[\xfeo\x0f', b'G:\\My Drive\\PhD\\kindle books\\Mastering systems thinking in practice.azw3', b'G:\\My Drive\\PhD\\kindle books\\Strategic planning_ systems thinking in practice.azw3', b'G:\\My Drive\\PhD\\kindle books\\Systems thinking and practice.azw3', b'G:\\My Drive\\PhD\\kindle books\\Systems thinking_ Understanding sustainability.azw3']
DeDRM v7.2.1: Trying to decrypt Mastering systems thinking in practice.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v7.2.1: Trying to decrypt Strategic planning_ systems thinking in practice.azw3
Decrypting Kindle Format 8 ebook: Mastering systems thinking in practice
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
DeDRM v7.2.1: Trying to decrypt Systems thinking and practice.azw3
searching for kinfoFiles in C:\Users\rosin\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Trying to decrypt Systems thinking_ Understanding sustainability.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Systems thinking: Understanding sustainability
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\rosin\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Strategic planning: systems thinking in practice
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Systems thinking and practice
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\rosin\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
searching for kinfoFiles in C:\Users\rosin\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Mastering systems thinking in practice to db in: 0.1
Added Systems thinking: Understanding sustainability to db in: 0.1
Added Systems thinking and practice to db in: 0.1
Added Strategic planning: systems thinking in practice to db in: 0.1
Added 4 books in 1.1 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (Strategic planning: systems thinking in practice) finished
Convert book 1 of 1 (Strategic planning: systems thinking in practice)
	DeDRM v7.2.1: Trying to decrypt jtltzkxi.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Strategic planning: systems thinking in practice
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\rosin\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_mono_family: 'Courier New'
	  verbose: 2
	  read_metadata_from_opf: 'C:\\Users\\rosin\\AppData\\Local\\Temp\\calibre_hxposesk\\gcm5j0r1.opf'
	  cover: 'C:\\Users\\rosin\\AppData\\Local\\Temp\\calibre_hxposesk\\56fb6ynp.jpeg'
	  output_profile: 'kindle'
	  pdf_sans_family: 'Tahoma'
	  pdf_serif_family: 'Tahoma'
	Resolved conversion options
	calibre version: 7.14.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\rosin\\AppData\\Local\\Temp\\calibre_hxposesk\\56fb6ynp.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001E1CD970A90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000001E1CD949410>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_no_cover': False,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Tahoma',
	 'pdf_serif_family': 'Tahoma',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\rosin\\AppData\\Local\\Temp\\calibre_hxposesk\\gcm5j0r1.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v7.2.1: Trying to decrypt jtltzkxi.azw3
	MobiDeDrm v1.0.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Strategic planning: systems thinking in practice
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\rosin\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
	calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on C:\Users\rosin\AppData\Local\Temp\calibre_hxposesk\jtltzkxi.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run
	  File "calibre\customize\conversion.py", line 245, in __call__
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 163, in check_for_drm
	calibre.ebooks.DRMError: Strategic planning: systems thinking in practice

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

If that book is from or for an E-ink Kindle (not a Fire), make sure you have that Kindle's serial number correctly entered in DeDRM's customization.
