### ISSUE TITLE
DeDRM is not work

### ISSUE THREAD

**Issue by johnny5tw** [apprenticeharper/DeDRM_tools#2336]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.
calibre, version 7.16.0
錯誤： 未處理的例外: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 7.16 Portable embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
EXE path: D:\PROG\Calibre Portable\Calibre\calibre.exe
Successfully initialized third party plugins: DeDRM (7, 2, 0) && Chinese Text Conversion (3, 0, 1) && Obok DeDRM (7, 2, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

---

## Log
<details><summary>Log Title</summary>

```log
PUT YOUR LOG
```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
