### ISSUE TITLE
Calibre cannot convert Kindle ebook.

### ISSUE THREAD

**Issue by pillainp2024** [apprenticeharper/DeDRM_tools#2340]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
EpubMerge: DEBUG: 2024-08-15 20:11:34,587: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\xxxx\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && EpubMerge (3, 1, 0) && EpubSplit (3, 9, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
Windows-10-10.0.22635-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22635')
Python 3.11.5
Windows: ('10', '10.0.22635', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && EpubMerge (3, 1, 0) && EpubSplit (3, 9, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.02] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.83] GUI main window shown
[0.88] main UI initialized...
[0.88] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:/Users/xxxx/OneDrive/Documents/My Kindle Content/B09DTMMLSZ_EBOK/B09DTMMLSZ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\xxxx\AppData\Local\Temp\calibre_ps7s1rtl\gnqahim4.kfx-zip
DeDRM v7.2.1: Trying to decrypt gnqahim4.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: gnqahim4
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4d3ed9bf-b810-4eef-be7b-8add3e887eae.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\xxxx\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\xxxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
[3.69] splash screen hidden
[3.69] Started up in 3.69 seconds with 61 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 512 b'\x01\x00\x00\x00\x0c\x00\x00\x00\x8a\x01\x00\x00\x14\x00\x1f\x00f\\\x8d\x013E\x07C\x9bS"M\xe2\xed\x1f\xe6\x94\x001\x00\x00\x00\x00\x00\x08Y\x98r1\x04DOCUME~1\x00\x00|\x00\t\x00\x04\x00\xef\xbe\xffV\xb5$\x0fYFg.\x00\x00\x00\xe2\xde\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x1a`\x00\x90B\x00\x00\x00\x00\x00\xc0\xefB\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\x00\x00@\x00w\x00i\x00n\x00d\x00o\x00w\x00s\x00.\x00s\x00t\x00o\x00r\x00a\x00g\x00e\x00.\x00d\x00l\x00l\x00,\x00-\x002\x001\x007\x007\x000\x00\x00\x00\x18\x00l\x001\x00\x00\x00\x00\x00\x0fY8g1\x04MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xbeDX\x98\x90\x0fY8g.\x00\x00\x00\xa2\x9e\x08\x00\x00\x00\n\x00\x00\x00\x00\x00\x1a\xe0\x00\x90\x00\x00\x00\x00\x00\x00>{\xee\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\x00\x00\x18\x00h\x001\x00\x00\x00\x00\x00\x0fY9g' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 24 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff' 

application/x-qt-windows-mime;value="DragContext" 16 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 b'\x01\x00\x00\x00' 

text/uri-list 101 b'file:///C:/Users/xxxx/OneDrive/Documents/My%20Kindle%20Content/B09DTMMLSZ_EBOK/B09DTMMLSZ_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 64 b'C:\\Users\\xxxx\\OneDrive\\DOCUME~1\\MYKIND~1\\B09DTM~1\\B09DTM~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 b'' 

application/x-qt-windows-mime;value="FileNameW" 176 b'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00p\x00i\x00l\x00l\x00a\x00\\\x00O\x00n\x00e\x00D\x00r\x00i\x00v\x00e\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x009\x00D\x00T\x00M\x00M\x00L\x00S\x00Z\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x009\x00D\x00T\x00M\x00M\x00L\x00S\x00Z\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 b"\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x04\x00\x00\x00'\x07\xb7\x12\xef\xda\x01\x00\x00\x00\x00\x00\x00\x00\x00\xf8\xf7O\xb7\x12\xef\xda\x01\x00\x00\x00\x00\xc2\xd3\x02\x00B\x000\x009\x00D\x00T\x00M\x00M\x00L\x00S\x00Z\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" 

Firefox rurl: None None
URLS: ['file:///C:/Users/xxxx/OneDrive/Documents/My%20Kindle%20Content/B09DTMMLSZ_EBOK/B09DTMMLSZ_EBOK.azw']
Paths: ['C:/Users/xxxx/OneDrive/Documents/My Kindle Content/B09DTMMLSZ_EBOK/B09DTMMLSZ_EBOK.azw']
Extensions: frozenset({'azw'})
Decrypted key file using IDString '880274185' and UserName 'NPP'
DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 2.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\xxxx\AppData\Local\Temp\calibre_ps7s1rtl\gnqahim4.kfx-zip
Processing container: B09DTMMLSZ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09DTMMLSZ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\xxxx\AppData\Local\Temp\calibre_ps7s1rtl\84h6womy_add_books\0\B09DTMMLSZ_EBOK.kfx-zip
Added Spacers: Fleet Action to db in: 0.1
Added 1 books in 2.8 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Spacers: Fleet Action) finished
Convert book 1 of 1 (Spacers: Fleet Action)

	DeDRM v7.2.1: Trying to decrypt qv84hdob.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: qv84hdob
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4d3ed9bf-b810-4eef-be7b-8add3e887eae.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\xxxx\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\xxxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '880274185' and UserName 'NPP'
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  cover: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\calibre_ps7s1rtl\\hnx5wb05.jpeg'

	  read_metadata_from_opf: 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\calibre_ps7s1rtl\\847a6ckd.opf'

	  verbose: 2

	  output_profile: 'generic_eink'

	Resolved conversion options

	calibre version: 7.16.0

	{'add_alt_text_to_img': False,

	 'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\calibre_ps7s1rtl\\hnx5wb05.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002113E41CC90>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000002113E4382D0>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\xxxx\\AppData\\Local\\Temp\\calibre_ps7s1rtl\\847a6ckd.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v7.2.1: Trying to decrypt qv84hdob.kfx-zip
	Decrypting KFX-ZIP ebook: qv84hdob
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4d3ed9bf-b810-4eef-be7b-8add3e887eae.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 911, in parse
	  File "C:\Users\xxxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\xxxx\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\xxxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '880274185' and UserName 'NPP'
	DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt

	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook

	  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 633, in run

	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\xxxx\AppData\Local\Temp\calibre_ps7s1rtl\qv84hdob.kfx-zip

	Software versions: KFX Input 2.15.0, calibre 7.16, Windows-10-10.0.22635-SP0

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\xxxx\AppData\Local\Temp\calibre_ps7s1rtl\qv84hdob.kfx-zip

	Processing container: B09DTMMLSZ_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 102, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09DTMMLSZ_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 198, in _run_module_as_main

	  File "runpy.py", line 88, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 122, in convert

	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.09: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

And be sure you're using Kindle for PC 2.4.0 or older.
