### ISSUE TITLE
Wont convert Kindle book, tried reinstalling but didn't help

### ISSUE THREAD

**Issue by sharpri72** [apprenticeharper/DeDRM_tools#2341]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (7, 2, 1)
calibre 7.16  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 79.3943833943834 x 79.28323699421965
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.58] GUI main window shown
[0.64] main UI initialized...
[0.64] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Relentless_ From Good to Great to Unstoppable.azw3
[4.53] splash screen hidden
[4.53] Started up in 4.53 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x01\xfb\xbb\x94{\xc1\xdc3\x0bv\xed]\x1fH`\x8b\x91\x17I\xe9\x9a\xdb\x1f\xc2\x99\x13w4%\xba\x03\xac', b'C:\\Users\\User\\Downloads\\Relentless_ From Good to Great to Unstoppable.azw3']
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Relentless: From Good to Great to Unstoppable
Found 2 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.8 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\User\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\User\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to enter that Kindle's serial number into DeDRM's customization.

**Comment by sharpri72** [comment]
I did, it has the serial number of the e-ink device. I also just restarted
the set up wizard (in case it makes a difference ) and set it to Amazon -
All kobo's.

**Comment by ElleKayEm** [comment]
Try copy and paste of the serial number from the website into DeDRM's customization.  Then restart calibre before trying to add your book again.
