### ISSUE TITLE
Issue With Program

### ISSUE THREAD

**Issue by hetheron** [apprenticeharper/DeDRM_tools#2347]
Hello, I use a more unknown e-reader and e-book service called kyobo (its korean) and the plugin didn't work. I followed the instructions on the read me and got this as a result. I'm hoping someone can suggest to me next steps because I desperately need this in PDF form ASAP. Thank you! 

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.75
logicalDpi: 96.0 x 96.0
physicalDpi: 138.43841059602647 x 138.2888888888889
[0.00] Starting up...
[0.00] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.17] db initialized
[1.17] Constructing main UI...
[1.41] GUI main window shown
[1.47] main UI initialized...
[1.47] Hiding splash screen
[1.47] splash screen hidden
[1.47] Started up in 1.47 seconds with 1 books
DeDRM v7.2.1: Trying to decrypt 5be029c1-6a76-4778-b683-c5fe32f5d96c.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Error 'File is not a zip file' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 210, in ePubDecrypt
  File "calibre_plugins.dedrm.zipfix", line 53, in __init__
  File "C:\Users\Emily\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 683, in __init__
  File "C:\Users\Emily\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 709, in _GetContents
  File "C:\Users\Emily\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 721, in _RealGetContents
zipfilerugged.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 214, in ePubDecrypt
Exception: File is not a zip file
Traceback (most recent call last):
  File "calibre\ebooks\metadata\epub.py", line 181, in get_zip_reader
  File "calibre\utils\zipfile.py", line 774, in __init__
  File "calibre\utils\zipfile.py", line 809, in _GetContents
  File "calibre\utils\zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 177, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 250, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 184, in get_zip_reader
  File "calibre\utils\localunzip.py", line 266, in __init__
  File "calibre\utils\localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc1\xa8\xb4R[F\x96\xf7O\x8f\xde*\x0b\xc2l \xd3\xc1\\:\xe6c\xd7x.e\x87\x02\xe1\x1c\xb2)', b'C:\\Users\\Emily\\Desktop\\5be029c1-6a76-4778-b683-c5fe32f5d96c.epub']
Added 5be029c1-6a76-4778-b683-c5fe32f5d96c to db in: 0.1
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
DeDRM can remove Adobe DRM from epubs.  I'm guessing this service is using something else.
