### ISSUE TITLE
DRM removal not working on Pearson textbook

### ISSUE THREAD

**Issue by jutochoppa** [apprenticeharper/DeDRM_tools#2348]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

## Losing my mind
I have tried using the older android app, the kindle for PC 2.4 app with no success. 
I have also tried the latest release and autobuild release of DeDRM without success.
I have tried exporting and using the android app files  onthe latest kindle app(.kfx and .ast voucher) without success.

At this point i'm not sure if what i'm doing is wrong or there is some sort of new drm on my book (isbn 9780137594177)
I beg for some guidance here.

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.905604719764 x 96.0
[0.00] Starting up...
[0.02] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[1.95] GUI main window shown
[1.98] main UI initialized...
[1.98] Hiding splash screen
[1.98] splash screen hidden
[1.98] Started up in 1.98 seconds with 0 books
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\joshu\OneDrive\Documents\My Kindle Content\B09VFD6D51_EBOK\B09VFD6D51_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 24 file(s) as C:\Users\joshu\AppData\Local\Temp\calibre_g6k9lqx0\jwevw96o.kfx-zip
DeDRM v10.0.9: Trying to decrypt jwevw96o.kfx-zip
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'K\x13\xa4\x15B\xee\xd6\xa5\xaf\xcbl\xb6D4\x07.\xee\xceC\x9d\x9d\x1b{\xcf\x0bj\x13\xf8:\x8a\xa9\x95', b'C:\\Users\\joshu\\OneDrive\\Documents\\My Kindle Content\\B09VFD6D51_EBOK\\B09VFD6D51_EBOK.azw']
Decrypting KFX-ZIP ebook: jwevw96o
Found 0 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5fdeae7c-1dca-4694-82b9-86f8598866db.voucher
Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\joshu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\joshu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1012175379' and UserName 'joshu'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: jwevw96o
Got DSN key from database key_0
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5fdeae7c-1dca-4694-82b9-86f8598866db.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 974, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\joshu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1039, in run
  File "calibre_plugins.dedrm.__init__", line 990, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\joshu\AppData\Local\Temp\calibre_g6k9lqx0\jwevw96o.kfx-zip
Processing container: B09VFD6D51_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09VFD6D51_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\joshu\AppData\Local\Temp\calibre_g6k9lqx0\pco462xa_add_books\0\B09VFD6D51_EBOK.kfx-zip
```
</details>

**Comment by jutochoppa** [comment]
I would even give access to my account if someone is willing to try.

**Comment by ElleKayEm** [comment]
These have DRM that cannot be removed (at least at this time.)

**Comment by jutochoppa** [comment]
> These have DRM that cannot be removed (at least at this time.)

Oh. ok :(. thank you
