### ISSUE TITLE
DRM not working Biblio 

### ISSUE THREAD

**Issue by GUTZEE** [apprenticeharper/DeDRM_tools#2350]
Taken a book from Biblio (Swedish Library EPUB site) dowloaded from mobile file and sent to computer to then upload on calibre. Changed file to epub.  

Calibre: 6.11 
DEDRM (7.2.1) 
Log: 
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 107.65562913907284 x 108.08510638297872
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 760, 'width': 1280, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 729, 'width': 1280, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 718, 'width': 1209, 'x': 35, 'y': 106},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 729, 'width': 1280, 'x': 0, 'y': 23}
Restoring widget to maximized
[0.61] main UI initialized...
[0.61] Hiding splash screen
Starting QuickView
DeDRM v7.2.1: Trying to decrypt 057082c1-168b-4372-b54e-a0e80a6b1627.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “057082c1-168b-4372-b54e-a0e80a6b1627.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
[3.38] splash screen hidden
[3.38] Started up in 3.38 seconds with 7 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x0f\xda\xb5y\x99C|,\x94\xaf\x84\x18\xc1Q\xd4P \xe5\xb2\x95i\xa8,m\xfc\x1bt\xdc\xfeo\xa6u', b"C:\\Users\\maxim\\Desktop\\PDF Books for Uni\\PDF's Module 1\\057082c1-168b-4372-b54e-a0e80a6b1627.epub"]
Added Om du såg mig nu to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by GUTZEE** [comment]
Attempted with DDRM 10.0.9 also doesn't work 
Log: 
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 6.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 107.65562913907284 x 108.08510638297872
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 760, 'width': 1280, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 729, 'width': 1280, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 729, 'width': 1280, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 729, 'width': 1280, 'x': 0, 'y': 23}
Restoring widget to maximized
[0.72] main UI initialized...
[0.72] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt 057082c1-168b-4372-b54e-a0e80a6b1627.epub
DeDRM v10.0.9: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 318, in ePubDecrypt
  File "C:\Users\maxim\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
[3.55] splash screen hidden
[3.55] Started up in 3.55 seconds with 7 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa3\xaf\x8e\x99<\xc68u\xcat\xb0Vo\xec\x0fs\x0e\x18b\x08\xa0\xdb<\x95\x99\xf1\xeb\xc5X\xfagR', b"C:\\Users\\maxim\\Desktop\\PDF Books for Uni\\PDF's Module 1\\057082c1-168b-4372-b54e-a0e80a6b1627.epub"]
Added Om du såg mig nu to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
Not a DRM that this tools supports.

**Comment by GUTZEE** [comment]
> Not a DRM that this tools supports.
Oh okay, thanks.
