### ISSUE TITLE
Can't remove DRM after plug-in install

### ISSUE THREAD

**Issue by awomack666** [apprenticeharper/DeDRM_tools#2351]
DeDRM 7.2.1
Mac OS Sonoma
device
cannot remove DRM
Blacklisting the DeDRM plugin as it is too old and causes crashes
ApplicationPaletteChange event ignored
Using calibre Qt style: True
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.17  embedded-python: True
macOS-14.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Overdrive Link (2, 57, 0) && PDF Cover (0, 1, 0)
calibre 7.17  embedded-python: True
macOS-14.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Overdrive Link (2, 57, 0) && PDF Cover (0, 1, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.02] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.21] db initialized
[1.21] Constructing main UI...
[2.26] GUI main window shown
[2.34] main UI initialized...
[2.34] Hiding splash screen
[2.43] splash screen hidden
[2.43] Started up in 2.43 seconds with 1 books
Blacklisting the DeDRM plugin as it is too old and causes crashes
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing /Volumes/Kindle/documents/Downloads/Items01/Freud and Beyond_ A History of Modern Psychoanalytic Thought_B01AFE3AJ8.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/09/w08ty28938576frbjj5lj1zr0000gn/C/calibre_7.17.0_tmp_00i6hktn/1vy0quv9.kfx-zip
Package KFX (from KFX Input) 2.15.0: Packaging /var/folders/09/w08ty28938576frbjj5lj1zr0000gn/C/calibre_7.17.0_tmp_00i6hktn/1vy0quv9.kfx-zip
Processing container: CR!Q89R6HC5YN4X39B8KQX0JR8XK6A0.kfx
Processing container: Freud and Beyond_ A History of Modern Psychoanalytic Thought_B01AFE3AJ8.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
    return self.package_kfx(path_to_ebook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
    container = self.get_container(datafile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Freud and Beyond_ A History of Modern Psychoanalytic Thought_B01AFE3AJ8.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/09/w08ty28938576frbjj5lj1zr0000gn/C/calibre_7.17.0_tmp_00i6hktn/burdfh13_add_books/0/Freud and Beyond_ A History of Modern Psychoanalytic Thought_B01AFE3AJ8.kfx-zip
Added Freud and Beyond to db in: 0.0
Added 1 books in 1.2 seconds
Failed to request permission for showing notification: The operation couldn’t be completed. (UNErrorDomain error 1.)

**Comment by ElleKayEm** [comment]
This DeDRM version is too old for this version of calibre.  Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by awomack666** [comment]
Thank you!!! I don't know why I couldn't find the new version. Appreciate your help so much.

**Comment by awomack666** [comment]
Aw I spoke too soon, I'm still missing something...

ApplicationPaletteChange event ignored
Using calibre Qt style: True
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.17  embedded-python: True
macOS-14.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Overdrive Link (2, 57, 0) && PDF Cover (0, 1, 0)
calibre 7.17  embedded-python: True
macOS-14.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Overdrive Link (2, 57, 0) && PDF Cover (0, 1, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.02] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.21] db initialized
[1.21] Constructing main UI...
[2.31] GUI main window shown
[2.38] main UI initialized...
[2.38] Hiding splash screen
[2.48] splash screen hidden
[2.48] Started up in 2.48 seconds with 1 books

**Comment by ElleKayEm** [comment]
New log doesn't show you adding the book.  How are you downloading the book?  Try either Kindle for Mac 1.40 or if you have an E-ink Kindle, you can use the download and transfer option from your content page on the website.

**Comment by awomack666** [comment]
I plugged the kindle into my mac and got the file off the kindle itself like a drive. I can't even find where the app stores books on my computer.

**Comment by ElleKayEm** [comment]
Is it an E-ink Kindle?  If so, download a copy from the website.  Add the Kindle's serial number to DeDRM's customization.

Otherwise, I believe books for Kindle for Mac 1.40 are in Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content.

**Comment by awomack666** [comment]
Ok I got it! I downloaded Kindle 1.40 then changed where the files are stored so it's easier to find, and imported the book from there. It changed the file type from .kfx to .azw by doing it that way, if that makes a difference. THANK YOU! I never would have tried the old Kindle version. I'll add my serial number too just in case.

**Comment by ElleKayEm** [comment]
File should actually be kfx again in calibre once DRM is removed.  Only need your serial number if the book is for an E-ink Kindle (not a Fire).  The serial number does nothing for books from Kindle for Mac.

**Comment by awomack666** [comment]
Ok! I added the serial number to DeDRM I do have an e-ink kindle. THANK YOU
SO MUCH!!!!
