### ISSUE TITLE
[QUESTION] Can't remove DRM

### ISSUE THREAD

**Issue by rsl33** [apprenticeharper/DeDRM_tools#2352]
## CheckList

- [x ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Title
<Can't remove DRM>

## My Environment
Windows 10
### Calibre: `Version`
7.17
### Kindle: `Version`
Fire HD 8
### DeDRM: `Version`
10.0.9
## Log
<details><summary>Log Title</summary>
Using instructions from techradar <https://www.techradar.com/how-to/how-to-convert-a-kindle-book-to-pdf>I downloaded a paid kindle ebook from my amazon library of digital content on amazon,com using chrome and  "download & transfer via usb" to my local hard disk. I installed Calibre and got Alf's plug-inDRM removal tool ver 7.2.1. I tried various times and finally looked at the github blog
Upgraded to deDrm 10.0.9 and opened in the diagnostic mode. ver 7.2.1 had a 72 line log and ver 10.0.9 had a 493 line log

```log
PUT YOUR LOG
```
</details>

**Comment by rsl33** [comment]
Here is my 493 line log
93 line ogApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.00] Showing splash screen...
[1.34] splash screen shown
[1.34] Initializing db...
[1.36] db initialized
[1.36] Constructing main UI...
[1.89] GUI main window shown
[1.99] main UI initialized...
[1.99] Hiding splash screen
[2.00] splash screen hidden
[2.00] Started up in 2.00 seconds with 1 books
DeDRM v10.0.9: Trying to decrypt Oath and Honor.azw3
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xd4'_\xe6\x03\xe40\xb2\x99\xbb\x87\xc0\x04Y\x04\xc8%\xd1\x109Ui\xf5\xd7B\xd1\xb0\xc8\xce\x80\xc1p", b'C:\\Users\\rsl\\Downloads\\Books\\Kindle\\Oath and Honor.azw3']
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Oath and Honor
Found 2 keys to try after 0.8 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.8 seconds
searching for kinfoFiles in C:\Users\rsl\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\rsl\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2592830240' and UserName 'rsl'
DeDRM v10.0.9: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Oath and Honor
Got DSN key from database key_0
Found 4 keys to try after 1.1 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Oath and Honor to db in: 0.2
Added 1 books in 1.7 seconds
Worker Launch took: 0.06 seconds
Job: 0 Convert book 1 of 1 (Oath and Honor) finished
Convert book 1 of 1 (Oath and Honor)

	DeDRM v10.0.9: Trying to decrypt ehft223g.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Oath and Honor
	Found 2 keys to try after 0.8 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.8 seconds
	searching for kinfoFiles in C:\Users\rsl\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\rsl\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2592830240' and UserName 'rsl'
	DeDRM v10.0.9: Found 1 new key
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Oath and Honor
	Got DSN key from database key_0
	Found 4 keys to try after 1.1 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt

	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook

	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook

	mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1030, in run

	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  read_metadata_from_opf: 'C:\\Users\\rsl\\AppData\\Local\\Temp\\calibre_2netjy38\\qf8vecwa.opf'

	  cover: 'C:\\Users\\rsl\\AppData\\Local\\Temp\\calibre_2netjy38\\j04g93o_.jpeg'

	  output_profile: 'generic_eink'

	  pdf_mono_family: 'Courier New'

	  verbose: 2

	Resolved conversion options

	calibre version: 7.17.0

	{'add_alt_text_to_img': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\rsl\\AppData\\Local\\Temp\\calibre_2netjy38\\j04g93o_.jpeg',

	 'custom_size': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001CBE1E9F490>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001CBE1E79C10>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'paper_size': 'letter',

	 'pdf_add_toc': False,

	 'pdf_default_font_size': 20,

	 'pdf_footer_template': None,

	 'pdf_header_template': None,

	 'pdf_hyphenate': False,

	 'pdf_mark_links': False,

	 'pdf_mono_family': 'Courier New',

	 'pdf_mono_font_size': 16,

	 'pdf_no_cover': False,

	 'pdf_odd_even_offset': 0.0,

	 'pdf_page_margin_bottom': 72.0,

	 'pdf_page_margin_left': 72.0,

	 'pdf_page_margin_right': 72.0,

	 'pdf_page_margin_top': 72.0,

	 'pdf_page_number_map': None,

	 'pdf_page_numbers': False,

	 'pdf_sans_family': 'Helvetica',

	 'pdf_serif_family': 'Times',

	 'pdf_standard_font': 'serif',

	 'pdf_use_document_margins': False,

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\rsl\\AppData\\Local\\Temp\\calibre_2netjy38\\qf8vecwa.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'uncompressed_pdf': False,

	 'unit': 'inch',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'use_profile_size': False,

	 'verbose': 2}

	DeDRM v10.0.9: Trying to decrypt ehft223g.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Oath and Honor
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\rsl\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\rsl\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '2592830240' and UserName 'rsl'
	DeDRM v10.0.9: Found 1 new key
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Oath and Honor
	Got DSN key from database key_0
	Found 4 keys to try after 0.4 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt

	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook

	  File "C:\Users\rsl\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook

	mobidedrm.DrmException: No key found in 2 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1030, in run

	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on C:\Users\rsl\AppData\Local\Temp\calibre_2netjy38\ehft223g.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 198, in _run_module_as_main

	  File "runpy.py", line 88, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 163, in check_for_drm

	calibre.ebooks.DRMError: Oath and Honor

**Comment by rsl33** [comment]
Not complete or closed

**Comment by ElleKayEm** [comment]
That method only works for E-ink Kindles, not Fires.  If you don't have an E-ink Kindle, then download it with Kindle for PC 2.4.0 (70904) aka 2.4.70904.  You will also need the KFX Input plugin.

**Comment by rsl33** [comment]
Hi, thanks for the reply.
I don't think my fire is involved downloading from amazon.com digital content;
I have many kindle devices.
With my kindle for pc ver 2.4.1 (70946) aka 2.4.1.70946
I have a folder named My Kindle Content.
How do I identify a book there?
How do I download from amazon.com digital content?
What configuration do I use for the deDRM plugin

Please let me know.

-ron leder
At 10:00 9/9/2024, you wrote:

**Comment by ElleKayEm** [comment]
Since you listed a Fire as your Kindle version, I assumed that was the device choosen when downloading from the website.  If you have an E-ink Kindle, then make sure to choose that when downloading from the website and have its serial number entered correctly into DeDRM's customization.

For books from Kindle for PC, no configuration of DeDRM is needed.  Kindle for PC used to download the book just needs to be installed on the same computer and user as calibre/DeDRM.  You cannot get books for Kindle for PC from the website, only via the app itself. 
 You'll also need the KFX Input plugin for those books.  Books in the My Kindle Content folder are named with their ASIN (found under Product Details and in the url for the book's page.)

**Comment by rsl33** [comment]
Dear LKM,
It worked.

There are a few issues
0. I didn;t realize there were specific formats for different reading devices.
I thought the differences were only the physical locations.
Now it appears a content downloaded to a computer 
for a particular reading device has a special
target format.

1. In the KFPC folder there are two files recognized by calibre
the .azw (content) and the .azw.md (MD Doc; what's this one)
2. The kfx file is twice the size of the azw3 file saved to usb
3. How do suggest I get the overview of Amazon's ebook formats and management?
4. This comment of yours:
"You cannot get books for Kindle for PC from the 
website, only via the app itself."
seems to be at odds with function on the amazon 
website next to each digital content item
  Deliver of Remove from Device; this laoows 
delivery of a book to kindle for PC.
Do you agree?
Thanks again,

-ron leder

At 11:01 9/9/2024, you wrote:

**Comment by ElleKayEm** [comment]
Download and transfer delivers azw3 for most books.  If you choose an E-ink Kindle, they can be decrypted by entering that Kindle's serial number into DeDRM.  This doesn't work if you choose a Fire.

For most books Kindle for PC 2.4.0 delivers kfx format which can be decrypted.  Kindle for PC 2.4.1 delivers kfx format with DRM which currently cannot be removed.  Kindle for PC always uses a generic azw extension for the main book file regardless of the actual format.  Once the DRM is removed you will see a format specific extension in calibre.  If the DRM isn't successfully removed from kfx format, you're left with kfx-zip from the KFX Input plugin gathering up the related files.

When choosing a device for download & transfer from the website, Kindle for PC is greyed out (not available).  The option to deliver to Kindle for PC merely queues the book up so that the next time Kindle for PC is opened the book is downloaded via the app.  I was clarifying that you couldn't download a book directly from the website for Kindle for PC.
