### ISSUE TITLE
[QUESTION] Can't remove DRM

### ISSUE THREAD

**Issue by ben126331** [apprenticeharper/DeDRM_tools#2353]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.18  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.18  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
[0.00] Starting up...
[0.00] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.23] db initialized
[1.23] Constructing main UI...
[1.59] GUI main window shown
[1.64] main UI initialized...
[1.64] Hiding splash screen
[1.64] splash screen hidden
[1.64] Started up in 1.64 seconds with 109 books
DeDRM v7.2.1: Trying to decrypt B0B33ZV6GC_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v7.2.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.2 seconds
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'?\xe7\x9f\xfa\xfdo\xc9\x8bv\xec\xb8F\xab\xc2D\xeb\xf4ud\xf8/ \xe6,\x0eO\xc4\xc5tnN5', b'C:\\Users\\Ben\\Documents\\MYKIND~1\\B0B33ZV6GC_EBOK\\B0B33ZV6GC_EBOK.azw']
searching for kinfoFiles in C:\Users\Ben\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Ben\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '505678752' and UserName 'benja'
DeDRM v7.2.1: Found 1 new key
DeDRM v7.2.1: Ultimately failed to decrypt after 7.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 208, in GetDecryptedBook
calibre_plugins.dedrm.k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 7.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'

```
</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

And install the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by ben126331** [comment]
Works fine ! you rock !
Thanks for this quick answer :-)
