### ISSUE TITLE
Please resolve my issue

### ISSUE THREAD

**Issue by alirazaahsanali** [apprenticeharper/DeDRM_tools#2367]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.19  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.19  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.02] Showing splash screen...
[1.23] splash screen shown
[1.23] Initializing db...
[1.25] db initialized
[1.25] Constructing main UI...
[1.67] GUI main window shown
[1.75] main UI initialized...
[1.75] Hiding splash screen
[1.75] splash screen hidden
[1.75] Started up in 1.75 seconds with 1 books
Convert book 1 of 1 (ABCDS)

Conversion options changed from defaults:

  output_profile: 'generic_eink'

  verbose: 2

  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\r0qkqgxr.opf'

Resolved conversion options

calibre version: 7.19.0

{'add_alt_text_to_img': False,

 'asciiize': False,

 'author_sort': None,

 'authors': None,

 'base_font_size': 0.0,

 'book_producer': None,

 'change_justification': 'original',

 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

            "'i')) or @class = 'chapter']",

 'chapter_mark': 'pagebreak',

 'comments': None,

 'cover': None,

 'debug_pipeline': None,

 'dehyphenate': True,

 'delete_blank_paragraphs': True,

 'disable_font_rescaling': False,

 'duplicate_links_in_toc': False,

 'embed_all_fonts': False,

 'embed_font_family': None,

 'enable_heuristics': False,

 'expand_css': False,

 'extra_css': None,

 'filter_css': '',

 'fix_indents': True,

 'font_size_mapping': None,

 'force_max_line_length': False,

 'format_scene_breaks': True,

 'html_unwrap_factor': 0.4,

 'inline_toc': False,

 'input_encoding': None,

 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000126F92F8610>,

 'insert_blank_line': False,

 'insert_blank_line_size': 0.5,

 'insert_metadata': False,

 'isbn': None,

 'italicize_common_cases': True,

 'keep_color': False,

 'keep_image_references': False,

 'keep_ligatures': False,

 'keep_links': False,

 'language': None,

 'level1_toc': None,

 'level2_toc': None,

 'level3_toc': None,

 'line_height': 0.0,

 'linearize_tables': False,

 'margin_bottom': 5.0,

 'margin_left': 5.0,

 'margin_right': 5.0,

 'margin_top': 5.0,

 'markup_chapter_headings': True,

 'max_line_length': 0,

 'max_toc_links': 50,

 'minimum_line_height': 120.0,

 'newline': 'system',

 'no_chapters_in_toc': False,

 'no_inline_navbars': False,

 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000126F92F6D90>,

 'page_breaks_before': "//*[name()='h1' or name()='h2']",

 'prefer_metadata_cover': False,

 'pretty_print': False,

 'pubdate': None,

 'publisher': None,

 'rating': None,

 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\r0qkqgxr.opf',

 'remove_fake_margins': True,

 'remove_first_image': False,

 'remove_paragraph_spacing': False,

 'remove_paragraph_spacing_indent_size': 1.5,

 'renumber_headings': True,

 'replace_scene_breaks': '',

 'search_replace': '[]',

 'series': None,

 'series_index': None,

 'smarten_punctuation': False,

 'sr1_replace': None,

 'sr1_search': None,

 'sr2_replace': None,

 'sr2_search': None,

 'sr3_replace': None,

 'sr3_search': None,

 'start_reading_at': None,

 'subset_embedded_fonts': False,

 'tags': None,

 'timestamp': None,

 'title': None,

 'title_sort': None,

 'toc_filter': None,

 'toc_threshold': 6,

 'transform_css_rules': '[]',

 'transform_html_rules': '[]',

 'txt_output_encoding': 'utf-8',

 'txt_output_formatting': 'plain',

 'unsmarten_punctuation': False,

 'unwrap_lines': True,

 'use_auto_toc': False,

 'verbose': 2}

InputFormatPlugin: LRF Input running

on C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\z5sfqqn1.lrf

Generating XML

Traceback (most recent call last):

  File "runpy.py", line 198, in _run_module_as_main

  File "runpy.py", line 88, in _run_code

  File "site.py", line 83, in <module>

  File "site.py", line 78, in main

  File "site.py", line 50, in run_entry_point

  File "calibre\utils\ipc\worker.py", line 215, in main

  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

  File "calibre\customize\conversion.py", line 245, in __call__

  File "calibre\ebooks\conversion\plugins\lrf_input.py", line 32, in convert

  File "calibre\ebooks\lrf\lrfparser.py", line 27, in __init__

  File "calibre\ebooks\lrf\meta.py", line 483, in __init__

calibre.ebooks.lrf.meta.LRFException: C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\z5sfqqn1.lrf has an invalid LRF header. Are you sure it is an LRF file?

Convert book 1 of 1 (ABCDS)

Conversion options changed from defaults:

  prefer_metadata_cover: True

  verbose: 2

  output_profile: 'generic_eink'

  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\crm7hwa8.opf'

Resolved conversion options

calibre version: 7.19.0

{'add_alt_text_to_img': False,

 'asciiize': False,

 'author_sort': None,

 'authors': None,

 'base_font_size': 0.0,

 'book_producer': None,

 'change_justification': 'original',

 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

            "'i')) or @class = 'chapter']",

 'chapter_mark': 'pagebreak',

 'comments': None,

 'cover': None,

 'debug_pipeline': None,

 'dehyphenate': True,

 'delete_blank_paragraphs': True,

 'disable_font_rescaling': False,

 'duplicate_links_in_toc': False,

 'embed_all_fonts': False,

 'embed_font_family': None,

 'enable_heuristics': False,

 'expand_css': False,

 'extra_css': None,

 'filter_css': '',

 'fix_indents': True,

 'font_size_mapping': None,

 'force_max_line_length': False,

 'format_scene_breaks': True,

 'html_unwrap_factor': 0.4,

 'inline_toc': False,

 'input_encoding': None,

 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000154ABDB85D0>,

 'insert_blank_line': False,

 'insert_blank_line_size': 0.5,

 'insert_metadata': False,

 'isbn': None,

 'italicize_common_cases': True,

 'keep_color': False,

 'keep_image_references': False,

 'keep_ligatures': False,

 'keep_links': False,

 'language': None,

 'level1_toc': None,

 'level2_toc': None,

 'level3_toc': None,

 'line_height': 0.0,

 'linearize_tables': False,

 'margin_bottom': 5.0,

 'margin_left': 5.0,

 'margin_right': 5.0,

 'margin_top': 5.0,

 'markup_chapter_headings': True,

 'max_line_length': 0,

 'max_toc_links': 50,

 'minimum_line_height': 120.0,

 'newline': 'system',

 'no_chapters_in_toc': False,

 'no_inline_navbars': False,

 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000154ABDB6C90>,

 'page_breaks_before': "//*[name()='h1' or name()='h2']",

 'prefer_metadata_cover': True,

 'pretty_print': False,

 'pubdate': None,

 'publisher': None,

 'rating': None,

 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\crm7hwa8.opf',

 'remove_fake_margins': True,

 'remove_first_image': False,

 'remove_paragraph_spacing': False,

 'remove_paragraph_spacing_indent_size': 1.5,

 'renumber_headings': True,

 'replace_scene_breaks': '',

 'search_replace': '[]',

 'series': None,

 'series_index': None,

 'smarten_punctuation': False,

 'sr1_replace': None,

 'sr1_search': None,

 'sr2_replace': None,

 'sr2_search': None,

 'sr3_replace': None,

 'sr3_search': None,

 'start_reading_at': None,

 'subset_embedded_fonts': False,

 'tags': None,

 'timestamp': None,

 'title': None,

 'title_sort': None,

 'toc_filter': None,

 'toc_threshold': 6,

 'transform_css_rules': '[]',

 'transform_html_rules': '[]',

 'txt_output_encoding': 'utf-8',

 'txt_output_formatting': 'plain',

 'unsmarten_punctuation': False,

 'unwrap_lines': True,

 'use_auto_toc': False,

 'verbose': 2}

InputFormatPlugin: LRF Input running

on C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\jpbljwke.lrf

Generating XML

Traceback (most recent call last):

  File "runpy.py", line 198, in _run_module_as_main

  File "runpy.py", line 88, in _run_code

  File "site.py", line 83, in <module>

  File "site.py", line 78, in main

  File "site.py", line 50, in run_entry_point

  File "calibre\utils\ipc\worker.py", line 215, in main

  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

  File "calibre\customize\conversion.py", line 245, in __call__

  File "calibre\ebooks\conversion\plugins\lrf_input.py", line 32, in convert

  File "calibre\ebooks\lrf\lrfparser.py", line 27, in __init__

  File "calibre\ebooks\lrf\meta.py", line 483, in __init__

calibre.ebooks.lrf.meta.LRFException: C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\jpbljwke.lrf has an invalid LRF header. Are you sure it is an LRF file?

Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 1262, in __init__
IndexError: list index out of range
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (ABCDS) finished
Convert book 1 of 1 (ABCDS)

	Conversion options changed from defaults:

	  output_profile: 'generic_eink'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\r0qkqgxr.opf'

	Resolved conversion options

	calibre version: 7.19.0

	{'add_alt_text_to_img': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'expand_css': False,

	 'extra_css': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'font_size_mapping': None,

	 'force_max_line_length': False,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'inline_toc': False,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000126F92F8610>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_color': False,

	 'keep_image_references': False,

	 'keep_ligatures': False,

	 'keep_links': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_line_length': 0,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'newline': 'system',

	 'no_chapters_in_toc': False,

	 'no_inline_navbars': False,

	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000126F92F6D90>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'pretty_print': False,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\r0qkqgxr.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'txt_output_encoding': 'utf-8',

	 'txt_output_formatting': 'plain',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	InputFormatPlugin: LRF Input running

	on C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\z5sfqqn1.lrf

	Generating XML

	Traceback (most recent call last):

	  File "runpy.py", line 198, in _run_module_as_main

	  File "runpy.py", line 88, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\lrf_input.py", line 32, in convert

	  File "calibre\ebooks\lrf\lrfparser.py", line 27, in __init__

	  File "calibre\ebooks\lrf\meta.py", line 483, in __init__

	calibre.ebooks.lrf.meta.LRFException: C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\z5sfqqn1.lrf has an invalid LRF header. Are you sure it is an LRF file?

Worker Launch took: 0.05 seconds
Job: 1 Convert book 1 of 1 (ABCDS) finished
Convert book 1 of 1 (ABCDS)

Conversion options changed from defaults:

  prefer_metadata_cover: True

  verbose: 2

  output_profile: 'generic_eink'

  read_metadata_from_opf: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\us7ylgqz.opf'

Resolved conversion options

calibre version: 7.19.0

{'add_alt_text_to_img': False,

 'asciiize': False,

 'author_sort': None,

 'authors': None,

 'base_font_size': 0.0,

 'book_producer': None,

 'change_justification': 'original',

 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

            "'i')) or @class = 'chapter']",

 'chapter_mark': 'pagebreak',

 'comments': None,

 'cover': None,

 'debug_pipeline': None,

 'dehyphenate': True,

 'delete_blank_paragraphs': True,

 'disable_font_rescaling': False,

 'duplicate_links_in_toc': False,

 'embed_all_fonts': False,

 'embed_font_family': None,

 'enable_heuristics': False,

 'expand_css': False,

 'extra_css': None,

 'filter_css': '',

 'fix_indents': True,

 'font_size_mapping': None,

 'force_max_line_length': False,

 'format_scene_breaks': True,

 'html_unwrap_factor': 0.4,

 'inline_toc': False,

 'input_encoding': None,

 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B8531F85D0>,

 'insert_blank_line': False,

 'insert_blank_line_size': 0.5,

 'insert_metadata': False,

 'isbn': None,

 'italicize_common_cases': True,

 'keep_color': False,

 'keep_image_references': False,

 'keep_ligatures': False,

 'keep_links': False,

 'language': None,

 'level1_toc': None,

 'level2_toc': None,

 'level3_toc': None,

 'line_height': 0.0,

 'linearize_tables': False,

 'margin_bottom': 5.0,

 'margin_left': 5.0,

 'margin_right': 5.0,

 'margin_top': 5.0,

 'markup_chapter_headings': True,

 'max_line_length': 0,

 'max_toc_links': 50,

 'minimum_line_height': 120.0,

 'newline': 'system',

 'no_chapters_in_toc': False,

 'no_inline_navbars': False,

 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001B8531F6C90>,

 'page_breaks_before': "//*[name()='h1' or name()='h2']",

 'prefer_metadata_cover': True,

 'pretty_print': False,

 'pubdate': None,

 'publisher': None,

 'rating': None,

 'read_metadata_from_opf': 'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_9yfh9iin\\us7ylgqz.opf',

 'remove_fake_margins': True,

 'remove_first_image': False,

 'remove_paragraph_spacing': False,

 'remove_paragraph_spacing_indent_size': 1.5,

 'renumber_headings': True,

 'replace_scene_breaks': '',

 'search_replace': '[]',

 'series': None,

 'series_index': None,

 'smarten_punctuation': False,

 'sr1_replace': None,

 'sr1_search': None,

 'sr2_replace': None,

 'sr2_search': None,

 'sr3_replace': None,

 'sr3_search': None,

 'start_reading_at': None,

 'subset_embedded_fonts': False,

 'tags': None,

 'timestamp': None,

 'title': None,

 'title_sort': None,

 'toc_filter': None,

 'toc_threshold': 6,

 'transform_css_rules': '[]',

 'transform_html_rules': '[]',

 'txt_output_encoding': 'utf-8',

 'txt_output_formatting': 'plain',

 'unsmarten_punctuation': False,

 'unwrap_lines': True,

 'use_auto_toc': False,

 'verbose': 2}

InputFormatPlugin: LRF Input running

on C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\zkkx1h28.lrf

Generating XML

Traceback (most recent call last):

  File "runpy.py", line 198, in _run_module_as_main

  File "runpy.py", line 88, in _run_code

  File "site.py", line 83, in <module>

  File "site.py", line 78, in main

  File "site.py", line 50, in run_entry_point

  File "calibre\utils\ipc\worker.py", line 215, in main

  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

  File "calibre\customize\conversion.py", line 245, in __call__

  File "calibre\ebooks\conversion\plugins\lrf_input.py", line 32, in convert

  File "calibre\ebooks\lrf\lrfparser.py", line 27, in __init__

  File "calibre\ebooks\lrf\meta.py", line 483, in __init__

calibre.ebooks.lrf.meta.LRFException: C:\Users\Dell\AppData\Local\Temp\calibre_9yfh9iin\zkkx1h28.lrf has an invalid LRF header. Are you sure it is an LRF file?

**Comment by ElleKayEm** [comment]
What is your issue?  DeDRM isn't invoked in this log.

**Comment by alirazaahsanali** [comment]
Dear Sir,

I want to convert my LRF file to TXT file. First, i need to remove DRM
protection then want to convert it. Kindly suggest me effective part from
which i convert my file.

*Thank You*
*Best Regards*

*Email: ***@***.*** ***@***.***>*



*Disclaimer: *This message (and any associated files) is intended only for
the use of the individual or entity to which it is addressed and may
contain information that is confidential, or subject to copyright. You are
hereby notified that any unauthorized dissemination, copying or
distribution of this message or files associated with this message, is
prohibited. If you are not the intended recipient/ you have received this
message by error, please notify the sender by replying to the message and
delete it from your system immediately.

**Comment by ElleKayEm** [comment]
I'm not aware of any way to remove DRM from LRF (aka LRX) format.  It was never supported by these tools.
