### ISSUE TITLE
Difficulty installing on Calibre in Docker

### ISSUE THREAD

**Issue by cdn4lf** [apprenticeharper/DeDRM_tools#2368]
## CheckList

- [X ] `The Title` and The `Log Title` are setted correctly.
- [ X] Clarified about `my environment`.
- [ X] Code block is used for `the log`.

---

## Title
When trying to import the package, everything appears to work, however when attempting to configure the package, I receive the error below.

## Log
<details><summary>Log Title</summary>

```log
calibre, version 7.19.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named 'config'

calibre 7.19  embedded-python: True
Linux-6.1.0-25-amd64-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.1.0-25-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26)')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre
Successfully initialized third party plugins: DeDRM (10, 0, 9)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 298, in customize_plugin
  File "calibre/gui2/preferences/plugins.py", line 375, in modify_plugin
  File "calibre/customize/__init__.py", line 160, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 1042, in config_widget
    import config
ModuleNotFoundError: No module named 'config'
```
</details>

**Comment by cdn4lf** [comment]
Apparently it helps when you install the plug-in correctly.  Closing the ticket
