### ISSUE TITLE
Pluggin Not Working to Convert KFX

### ISSUE THREAD

**Issue by ChangLek85** [apprenticeharper/DeDRM_tools#2369]
The PlugIn is not working here is my error when I ran Calibre in bug mode
ApplicationPaletteChange event ignored
Using calibre Qt style: True
EpubMerge: DEBUG: 2024-10-16 21:04:16,446: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\Andrea\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Debug log
calibre 7.19  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (2, 16, 0) && EpubMerge (3, 2, 0) && EpubSplit (3, 9, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && Set KFX metadata (from KFX Output) (2, 11, 0) && KFX Output (2, 11, 0)
calibre 7.19  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (7, 0, 3) && Package KFX (from KFX Input) (2, 16, 0) && EpubMerge (3, 2, 0) && EpubSplit (3, 9, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && Set KFX metadata (from KFX Output) (2, 11, 0) && KFX Output (2, 11, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.23899371069182 x 102.35820895522387
[0.00] Starting up...
[0.00] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.20] db initialized
[1.20] Constructing main UI...
[2.42] GUI main window shown
[2.55] main UI initialized...
[2.55] Hiding splash screen
[2.55] splash screen hidden
[2.55] Started up in 2.55 seconds with 272 books
Gather KFX-ZIP (from KFX Input) 2.16.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B09PY1BK1D_EBOK\B09PY1BK1D_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 7 file(s) as C:\Users\Andrea\AppData\Local\Temp\calibre_eh4znrbg\74cisj11.kfx-zip
DeDRM v7.0.3: Trying to decrypt 74cisj11.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 74cisj11
Got DSN key from database Andrea's Kindle for PC 4
Got DSN key from database default_key
Error getting PIDs from serial number G000PP1301740SM9: string argument without an encoding
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 306, in getPidList
TypeError: string argument without an encoding
Found 2 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.60183618-1552-46d2-8fea-763a1a2c4fb2.voucher
DeDRM v7.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Andrea\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Andrea\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1082636787' and UserName 'Andrea'
DeDRM v7.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: 74cisj11
Got DSN key from database default_key_1
Found 1 keys to try after 2.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.60183618-1552-46d2-8fea-763a1a2c4fb2.voucher
DeDRM v7.0.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 537, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 42, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 82, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 630, in run
  File "calibre_plugins.dedrm.__init__", line 580, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.0.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.16.0: Packaging C:\Users\Andrea\AppData\Local\Temp\calibre_eh4znrbg\74cisj11.kfx-zip
Processing container: B09PY1BK1D_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09PY1BK1D_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Andrea\AppData\Local\Temp\calibre_eh4znrbg\e_qa8bp8_add_books\0\B09PY1BK1D_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
