### ISSUE TITLE
[How to remove DRM from Epub] Unable to open Epub: "Book is Locked by DRM"

### ISSUE THREAD

**Issue by Rb958** [apprenticeharper/DeDRM_tools#2370]
## CheckList
- [x ] `The Title` and The `Log Title` are setted correctly.
- [x ] Clarified about `my environment`.
- [x ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.20  embedded-python: True
Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.9.3-76060903-generic', '#202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J')
Python 3.11.5
Interface language: fr
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.20  embedded-python: True
Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.9.3-76060903-generic', '#202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J')
Python 3.11.5
Interface language: fr
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 141.4020618556701
[0.00] Starting up...
[0.00] Showing splash screen...
[1.09] splash screen shown
[1.09] Initializing db...
[1.12] db initialized
[1.12] Constructing main UI...
[1.49] GUI main window shown
[1.51] main UI initialized...
[1.51] Hiding splash screen
[1.51] splash screen hidden
[1.51] Started up in 1.51 seconds with 1 books
DeDRM v7.2.1: Trying to decrypt Architecture logicielle propre.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “Architecture logicielle propre.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Couldn't decrypt after {2:.1f} seconds. DRM free perhaps?".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
['zenity', '--modal', '--file-selection', '--title=Livres sélectionnés', '--separator=\n', '--attach=98566170', '--filename=/home/zoe-pop/Téléchargements/Telegram Desktop/.fgdfg.gdfhjdhf*&^839', '--file-filter=Livres | *.lrf *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=Livres EPUB | *.epub *.kepub', '--file-filter=Livres Kindle | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=Livres PDF | *.pdf *.azw4', '--file-filter=Livres HTML | *.htm *.html *.xhtm *.xhtml', '--file-filter=Livres LIT | *.lit', '--file-filter=Livres texte | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Bandes Dessinées | *.cbz *.cbr *.cbc *.cb7', '--file-filter=Archives | *.zip *.rar *.7z', '--file-filter=Fichiers du traitement de texte | *.odt *.doc *.docx', '--file-filter=Tous les fichiers | *', '--multiple']
Added Architecture logicielle propre to db in: 0.1
Added 1 books in 0.7 seconds
Path override failed for key base::DIR_APP_DICTIONARIES and path '/opt/calibre/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/opt/calibre/libexec/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/opt/calibre/libexec/qtwebengine_dictionaries'
Worker Launch took: 0.00 seconds
```
</details>

**Comment by ElleKayEm** [comment]
You're using a really old version of DeDRM, but this doesn't appear to be a DRM that is supported anyway.
