### ISSUE TITLE
[QUESTION] 'QTableWidgetItem' has no attribute 'UserType'

### ISSUE THREAD

**Issue by MargretRose** [apprenticeharper/DeDRM_tools#2372]
I may not be doing this correctly, because I don't understand markdown.

I'm using Calibre 7.20.0 on a Windows 11 PC, with DeDRM Tools 7.2.1 installed. When I try to use the Obok plugin I get the following error message:

calibre, version 7.20.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 7.20  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Set KFX metadata (from KFX Output) (2, 11, 0) && KFX Output (2, 11, 0) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

**Comment by ElleKayEm** [comment]
Update to Obok 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by MargretRose** [comment]
Perfect! Thank you **so** much.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
