### ISSUE TITLE
Cant remove DRM from the book of kobo

### ISSUE THREAD

**Issue by Jackmatim** [apprenticeharper/DeDRM_tools#2374]
I followed the steps as instructed and successfully exported the book in Calibre using the Obok DeDRM plugin. It showed that DRM removal was successful, but in reality, it wasn’t removed; the EPUB file opens with garbled text.
There is the log:ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre 调试日志
calibre 7.20  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.11.5
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Obok DeDRM (10, 0, 9)
calibre 7.20  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.11.5
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: zh_CN
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 84.62536585365852 x 84.81391304347825
[0.00] Starting up...
[0.01] Showing splash screen...
[1.67] splash screen shown
[1.67] Initializing db...
[1.67] db initialized
[1.67] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.12] GUI main window shown
[2.22] main UI initialized...
[2.22] Hiding splash screen
[2.22] splash screen hidden
[2.22] Started up in 2.22 seconds with 0 books
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1859, in set_metadata
  File "calibre\db\cache.py", line 1782, in set_cover
  File "calibre\db\backend.py", line 1791, in set_cover
  File "calibre\utils\img.py", line 302, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty

**Comment by ElleKayEm** [comment]
Try closing Kobo Desktop before using Obok.  Make sure the book shows a closed red lock in Obok before attempting to import it.

**Comment by Katrekel** [comment]
I have the same problem and I just can't get Obok to show the red lock for any of my books (of which several have DRM). It always shows green and fails to remove the DRM. I don't know what to do (yes, I know you can use ADE, but I'd rather not do that).

**Comment by ElleKayEm** [comment]
I seem to recall someone reporting that using the very old calibre 4.23 and Obok 6.8.1 worked.
