### ISSUE TITLE
[QUESTION] DeDRM not working : (

### ISSUE THREAD

**Issue by LJGerry** [apprenticeharper/DeDRM_tools#2377]
## CheckList

- [ ] `The Title` and The `Log Title` are setted correctly.
- [ ] Clarified about `my environment`.
- [ ] Code block is used for `the log`.

---

## Log
<details><summary>Log Title</summary>

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.15759312320917 x 93.3061224489796
[0.00] Starting up...
[0.00] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[1.41] GUI main window shown
[1.45] main UI initialized...
[1.45] Hiding splash screen
[1.47] splash screen hidden
[1.47] Started up in 1.47 seconds with 1 books
DeDRM v7.2.1: Trying to decrypt The Running Grave_ Cormoran Strike Book 7.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Running Grave: Cormoran Strike Book 7
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v7.2.1: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\leejg\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\leejg\AppData\Local\Amazon\Kindle\storage\.kinf2018
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x9b\xad\x8a\x82\xe1\xe8\xcco\xfe\x85]E\xb6\xad\x039X\x1e\x9b\x8c\xf2\x80\x0f\xd8\xd6\xb2\x10l\x81~\xac2', b'C:\\temp\\The Running Grave_ Cormoran Strike Book 7.azw3']
Decrypted key file using IDString '1012801664' and UserName 'leejg'
DeDRM v7.2.1: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Running Grave: Cormoran Strike Book 7
Got DSN key from database default_key_1
Found 4 keys to try after 1.3 seconds
Crypto Type is: 2
DeDRM v7.2.1: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 484, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

```
</details>
I bought a 'slave' Kindle device to use [for the serial number] so that I can upload my purchased Kindle books (previously read on a Kindle reader on my iPad) to my ReMarkable. But I get the message that the DRM won't allow the conversion to Epub. The kindle's working fine and I can load books on there.

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

You are downloading new copies of the books and choosing the e-ink Kindle for the device?  Make sure the Kindle's serial number is correctly enter in DeDRM's customization by copy & pasting it from the website.

**Comment by LJGerry** [comment]
Hi. Thank you so much for replying.

I'm downloading books that I've purchased, but I may be re-reading them. So
not necessarily 'new'. They do download to my Kindle via the USB.

Serial number has been copied and pasted and is correct.  I am using the
e-ink  Kindle version, to store the serial number.

I'm not entirely sure what I'm doing wrong. I followed a YouTube video
(which is where I heard about your Plug-in).

Do they have to be 'new and unread' books?

Cheers,

Lee

**Comment by ElleKayEm** [comment]
No, just that they need to be copies where you selected the E-ink Kindle as the device when you downloaded them.  Books for different devices or apps will have different keys even if the devices/apps are logged into the same account.

**Comment by danmoser** [comment]
v10.0.9 worked nicely for me! I was having issues with v7.x ...
