### ISSUE TITLE
[QUESTION] linux wine drm key extract - adobekey.py FileNotFoundError - bug?

### ISSUE THREAD

**Issue by ansorg** [apprenticeharper/DeDRM_tools#2378]
## CheckList

- [ x] `The Title` and The `Log Title` are setted correctly.
- [ x] Clarified about `my environment`.
- [ x] Code block is used for `the log`.

---

### ADE: `4.5`

Wine environment set up with python-3.3 and pycrypto-2.6.win32-py3.3.exe (most recent version found at https://web.archive.org/web/20130119091321/http://www.voidspace.org.uk/downloads/)

As per the log, the call to python3 within wine basically works but then it seems to try to load the `adobekey.py`  from outside the wine prefix 

Is this a bug or is my setup missing something? 

## Log
<details><summary>Console output</summary>

```log
> ~/.wine/drive_c/windows/system32 > calibre                                                                       
011c:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0124:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0124:fixme:msvcrt:__clean_type_info_names_internal (1E27A64C) stub
DeDRM v10.0.9: Python3 exec found as wine py.exe -3
DeDRM v10.0.9: Running adobekey.py under Wine
013c:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0144:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
adobekey.py v7.4
Copyright © 2009-2020 i?cabbages, Apprentice Harper et al.
Traceback (most recent call last):
  File "/home/jens/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 289, in adeptkeys
    regkey = winreg.OpenKey(cuser, DEVICE_KEY_PATH)
FileNotFoundError: [WinError 2] Datei nicht gefunden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jens/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 571, in <module>
    sys.exit(cli_main())
  File "/home/jens/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 488, in cli_main
    keys, names = adeptkeys()
  File "/home/jens/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 292, in adeptkeys
    raise ADEPTError("Adobe Digital Editions not activated")
__main__.ADEPTError: Adobe Digital Editions not activated
0144:fixme:msvcrt:__clean_type_info_names_internal (7A6F882C) stub
0144:fixme:msvcrt:__clean_type_info_names_internal (1D1B51CC) stub
0144:fixme:msvcrt:__clean_type_info_names_internal (1E27A64C) stub
DeDRM v10.0.9: Wine subprocess call error: 1
DeDRM v10.0.9: Found and decrypted 0 key files
```
</details>

**Comment by ansorg** [comment]
hm, seems the error is referring to the `DEVICE_KEY_PATH` rather than the python script file. 

the source https://github.com/apprenticeharper/DeDRM_tools/blob/776f146ca00d11b24575f4fd6e8202df30a2b7ea/DeDRM_plugin/adobekey.py#L183 
mentions a key in HKCU but it is not there for me.  Though ADE has been started multiple times already to import books. 

What am I missing?

**Comment by ElleKayEm** [comment]
Maybe because ADE isn't authorized with an Adobe ID.
