### ISSUE TITLE
Issues removing DRM from certain Kindle Titles (59/136 titles impacted)

### ISSUE THREAD

**Issue by cemerson007** [apprenticeharper/DeDRM_tools#2382]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.26100-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.26100')
Python 3.11.5
Windows: ('10', '10.0.26100', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 18, 0) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (10, 0, 9)
calibre 7.22  embedded-python: True
Windows-10-10.0.26100-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.26100')
Python 3.11.5
Windows: ('10', '10.0.26100', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 18, 0) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 121.11258278145695 x 121.59574468085107
[0.00] Starting up...
[0.03] Showing splash screen...
[1.23] splash screen shown
[1.23] Initializing db...
[1.25] db initialized
[1.25] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.39] GUI main window shown
[2.66] main UI initialized...
[2.66] Hiding splash screen
[2.66] splash screen hidden
[2.66] Started up in 2.66 seconds with 136 books
Worker Launch took: 0.16 seconds
Worker Launch took: 0.09 seconds
Worker Launch took: 0.14 seconds
Worker Launch took: 0.06 seconds
Job: 0 Convert book 59 of 59 (A Courier for Christmas: A Delivery Driver...) finished
Convert book 59 of 59 (A Courier for Christmas: A Delivery Driver...)
	DeDRM v10.0.9: Trying to decrypt fnss4uk6.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: A Courier for Christmas: A Delivery Driver Holiday RomCom
	Found 2 keys to try after 0.6 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
	searching for kinfoFiles in C:\Users\crystal_emerson\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\crystal_emerson\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\crystal_emerson\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 2 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: 'kobo'
	  cover: 'C:\\Users\\CRYSTA~1\\AppData\\Local\\Temp\\calibre_5e9wxd4bv29y79l1.jpeg'
	  read_metadata_from_opf: 'C:\\Users\\CRYSTA~1\\AppData\\Local\\Temp\\calibre_5e9wxd4b\\141ek7b9.opf'
	Resolved conversion options
	calibre version: 7.22.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\CRYSTA~1\\AppData\\Local\\Temp\\calibre_5e9wxd4b\\v29y79l1.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000274A2EE2350>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x00000274A2EF5F10>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\CRYSTA~1\\AppData\\Local\\Temp\\calibre_5e9wxd4b\\141ek7b9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt fnss4uk6.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: A Courier for Christmas: A Delivery Driver Holiday RomCom
	Found 2 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\crystal_emerson\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\crystal_emerson\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\crystal_emerson\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
	mobidedrm.DrmException: No key found in 2 PIDs tried.

**Comment by ElleKayEm** [comment]
From or for an E-ink Kindle (not a Fire), enter that Kindle's serial number into DeDRM's customization.  The ones that worked were already DRM-free.

**Comment by cemerson007** [comment]
The only kindle I have is a fire tablet. That was the serial number provided

**Comment by ElleKayEm** [comment]
Won't work with books for a Fire.  Use Kindle for PC.  See method 2a in this post: https://www.mobileread.com/forums/showthread.php?t=361503
