### ISSUE TITLE
KFX-ZIP to EPUB not working 

### ISSUE THREAD

**Issue by OccassionalBioinformatician** [apprenticeharper/DeDRM_tools#2383]
Kindle (Windows): 2.4.0 (70904)
Calibre: 6.17
DeDRM: 10.0.9
KFXInput: 2.18.0

------
Logs:
```
DeDRM v10.0.9: Trying to decrypt redacted.kfx-zip
	Decrypting KFX-ZIP ebook: redacted
	Got DSN key from database kindle_key_redacted_1
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.redacted.voucher
	Traceback (most recent call last):
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\DELL\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\DELL\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString 'redacted' and UserName 'DELL'
	DeDRM v10.0.9: Found 1 new key
	Decrypting KFX-ZIP ebook: redacted
	Got DSN key from database key_0
	Found 1 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.redacted.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\DELL\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
```
--------
I guess this is one of the un-decryptable ones unless I can get an old eInk. de-DRMing fails and [indeed](https://www.mobileread.com/forums/showpost.php?p=4465820&postcount=330), the imported file stays as KFX-ZIP.

P.S.: I tried downgrading Kindle-for-PC to 2.3 and see if it works. Nope.
P.P.S: The issue should have been opened at noDRM/DeDRM_tools

**Comment by ElleKayEm** [comment]
The book was definitely downloaded with Kindle for PC 2.4.0 or earlier?  Books that are only available in the newer undecryptable KFX DRM are relatively rare.  And they would not be available for an older Kindle either.  The product page will say something about only being available for certain devices and the latest versions of the apps.

**Comment by OccassionalBioinformatician** [comment]
@ElleKayEm https://www.amazon.in/Writer-Rebel-Soldier-Lover-Agyeya-ebook/dp/B0B5LFYJSJ is the book. Yes, I am sure about the Kindle version.

**Comment by j-howell** [comment]
> https://www.amazon.in/Writer-Rebel-Soldier-Lover-Agyeya-ebook/dp/B0B5LFYJSJ is the book.

Many English language books published in India use Amazon’s strongest DRM. There is no known way to handle those books no matter which Kindle device or app you use to download it.

**Comment by ElleKayEm** [comment]
Yeah, that's a book that cannot be decrypted at this time.  As far as I'm aware, even having an E-ink Kindle won't help.  Those books are simply not available in a decryptable format.
