### ISSUE TITLE
[QUESTION] DeDRM + DeASCM not working for my new epub

### ISSUE THREAD

**Issue by gxsw** [apprenticeharper/DeDRM_tools#2384]
---

## Title
DeDRM + DeASCM not working for my new epub

## Log
DeDRM v10.0.3: Found new key 'DeACSM_uuid_1bbc1eed-a97a-452d-a60d-32c5681666d2' in DeACSM plugin
DeDRM v10.0.3: Trying a new default key
oci1l8me.epub is a secure Adobe Adept ePub.
Could not decrypt oci1l8me.epub because of an exception:
Traceback (most recent call last):
  File "/home/hns/.config/calibre/plugins/DeDRM.zip/ineptepub.py", line 305, in decryptBook
    rsakey = RSA.import_key(userkey) # parses the ASN1 structure
             ^^^^^^^^^^^^^^
AttributeError: module 'Crypto.PublicKey.RSA' has no attribute 'import_key'. Did you mean: 'importKey'?

DeDRM v10.0.3: Failed to decrypt with new default key after 1.2 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
    plugin_ret = plugin.run(rpl)
                 ^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

</details>

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by gxsw** [comment]
Thanks!! solved!

**Comment by masteoo** [comment]
@ElleKayEm  goodevening, sorry, can this tool dedrm a protected epub found on AnnasArchive?
https://it.annas-archive.org/md5/5347328de4b5933db27066b1f3cf646c
