### ISSUE TITLE
Where did I go wrong in this process?

### ISSUE THREAD

**Issue by kyle7119** [apprenticeharper/DeDRM_tools#243]
Using files from Kindle for PC 1.17.1

I can convert all other books without a problem.

```
calibre Debug log
calibre 2.38  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Barnes & Noble && Obok DeDRM && KindleUnpack - The Plugin
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Started up in 4.91 seconds with 17 books
DeDRM v6.5.3: Trying to decrypt B00GAF3EUM_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Campbell Biology
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Mark\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Mark\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1190727020' and UserName '4b796c65'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright Â© 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 248
Decrypting Mobipocket 4 ebook: Campbell Biology
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.7 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.7 seconds
Added Campbell Biology to db in: 2.6
Added 1 books in 3.8 seconds
```

**Comment by apprenticeharper** [comment]
Try deleting and downloading a fresh copy.

**Comment by ElleKayEm** [comment]
Looks like there's a mismatch between your current Window user name and the one used to decrypt the K4PC key file -- one is Mark, the other is Kyle (shown in hex in the log).  Workaround is to create a new user account (without any non-ASCII characters) and install Kindle for PC, calibre, and the DeDRM plugin there.

**Comment by apprenticeharper** [comment]
Good catch on the user name! That'll be the problem. Closed.
