### ISSUE TITLE
Calibre plugin problem

### ISSUE THREAD

**Issue by unalignedcoder** [apprenticeharper/DeDRM_tools#260]
When I click on "customize plugin" within Calibre, I get this error message:

```
calibre, version 2.83.0
ERROR: Unhandled exception: <b>AttributeError</b>:'module' object has no attribute 'ConfigWidget'

calibre 2.83  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 0, 8) && Kobo Books (1, 2, 1) && INMONDADORI (0, 2, 1) && Goodreads (1, 1, 12) && Barnes & Noble (1, 2, 14) && EpubSplit (2, 2, 0) && Sony PRS-T1 notes plugin (1, 1, 0) && Kobo Utilities (2, 5, 2) && KoboBooks (1, 0, 0) && Modify ePub (1, 3, 13) && English Noun Frequency (1, 0, 6) && Annotations (1, 4, 11) && KoboTouchExtended (2, 8, 2) && EpubMerge (2, 1, 0) && KePub Metadata Reader (2, 7, 1) && Count Pages (1, 7, 0) && KePub Metadata Writer (2, 7, 1) && Generate Cover (1, 5, 21) && Open With (1, 5, 10) && Find Duplicates (1, 6, 2) && KindleUnpack - The Plugin (0, 81, 4)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 293, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 371, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 155, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 495, in config_widget
AttributeError: 'module' object has no attribute 'ConfigWidget'
```

**Comment by unalignedcoder** [comment]
Forget it - it just needed to be updated. Wonder why Calibre did not warn about it.

**Comment by ElleKayEm** [comment]
Since you load this plugin from a file, instead of through the "get plugins" interface, calibre doesn't know when it's outdated.
