### ISSUE TITLE
Missing encryption key

### ISSUE THREAD

**Issue by Aethercoe** [apprenticeharper/DeDRM_tools#262]
I've been a user of DeDRM for quite some time now and have found it to be an excellent tool. However, recently I haven't been able to remove any DRM's at all. I am on Windows 10 and the books are from ADE 2.0.1. When trying to save the PDF, I get an error message that metadata couldn't be written. Also, when clicking the plus button in customise plugin > ADE keys > default_key, it states that the default encryption key for ADE could not be found. Below is the log from the removal attempt. How do I fix this?

piped data from file dialog helper: ['\xf078\xc0\x14\xf5\x9c\xd0\xdf\x96\xb5\x81?\xeb\xfc\xdaZI_\xd5\x14y3\x19\xbf\x9f:\xe9\xb1\xa5B\x7f', 'C:\\Users\\User\\Documents\\My Digital Editions\\MHiA.pdf']
DeDRM v6.5.3: Trying to decrypt MHiA.pdf
DeDRM v6.5.3: MHiA.pdf is a PDF ebook
DeDRM v6.5.3: Trying Encryption key default_key
DeDRM v6.5.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 413, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2186, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1996, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1481, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1613, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.3: Trying Encryption key default_key_2
DeDRM v6.5.3: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 413, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2186, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1996, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1481, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1614, in initialize_ebx
ValueError: substring not found
DeDRM v6.5.3: Failed to decrypt with key default_key_2 after 0.2 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 438, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 617, in run
  File "calibre_plugins.dedrm.__init__", line 492, in PDFDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 419, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 341, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added MHiA to db in: 0.2
Added 1 books in 1.3 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [">\x90\xbc\xd4\xdb\x1b\x80\x9ak\xc9\xe5K\x02o\x98\xfe\x8d\x96\xa7\x9b\xcbj\xab\\U\xe4\x7f-'\x08 %", 'C:\\Users\\User\\Desktop']
Device using plugboard pdf save_to_disk None
Saved 1 books in 0.6 seconds

**Comment by anshukla** [comment]
You can produce a key using the script in ``adobekey.pyw`` and then set it using preferences.

**Comment by Aethercoe** [comment]
Hi anshukla,
I have followed the windows instructions in the file but can't seem to get it to work. I get a error "Failed to decrypt user key key (sic)". This happens on both the x86 and x64 versions of python (and pycrypto) and no key was generated.

**Comment by ElleKayEm** [comment]
ADE 2.0.1 (authorized with your Adobe ID) is on the same machine and user as calibre?  And the book can be opened in ADE 2.0.1?

**Comment by Aethercoe** [comment]
Yes, ADE 2.0.1.78765. I have tried with both authorisation methods (Adobe ID and computer only). It is on the same machine and user as calibre is run. The book can be opened in ADE 2.0.1

**Comment by ElleKayEm** [comment]
The important thing with the authorization is whether ADE was authorized with your Adobe ID when you originally opened the acsm file.  If not, then the book is tied to this installation of ADE and can't be unlocked.
