### ISSUE TITLE
Kindle + wine + winekeysdir

### ISSUE THREAD

**Issue by ivan-m** [apprenticeharper/DeDRM_tools#320]
This isn't an issue with Python not being found, but of the directory not being found.

Relevant part of log from Calibre:

```
DeDRM v6.5.4: Trying to decrypt B00AHQOPEO_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Hitchhiker's Guide to the Galaxy: Hitchhiker's Guide 1
Found 3 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.5.4: Running kindlekey.py under Wine
DeDRM v6.5.4: Command line: 'WINEPREFIX="/home/ivan/.wine-ade" wine python.exe "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
searching for kinfoFiles in C:\users\ivan\Local Settings\Application Data
Found K4PC 1.9+ kinf2011 file: C:\users\ivan\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '328386898' and UserName '6976616e'
Saved a key to Z:\home\ivan\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
fixme:msvcrt:__clean_type_info_names_internal (0x1d1b6210) stub
fixme:msvcrt:__clean_type_info_names_internal (0x100f0610) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e26e980) stub
DeDRM v6.5.4: Found and decrypted 1 key file
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 168, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added The Hitchhiker's Guide to the Galaxy: Hitchhiker's Guide 1 to db in: 0.2
```

Running the command manually:

```
$ WINEPREFIX="/home/ivan/.wine-ade" wine python.exe "/home/ivan/.config/calibre/plugins/DeDRM/li
braryfiles/kindlekey.py" "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"                        
kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
searching for kinfoFiles in C:\users\ivan\Local Settings\Application Data
Found K4PC 1.9+ kinf2011 file: C:\users\ivan\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '328386898' and UserName '6976616e'
Traceback (most recent call last):
  File "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py", line 1711, in <module>
    sys.exit(cli_main())
  File "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py", line 1652, in cli_main
    if not getkey(outpath, files):
  File "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py", line 1589, in getkey
    with file(outfile, 'w') as keyfileout:
IOError: [Errno 2] No such file or directory: u'C:\\home\\ivan\\.config\\calibre\\plugins\\DeDRM\\libraryfiles\\winekeysdir'                                                                                                               
fixme:msvcrt:__clean_type_info_names_internal (0x1d1b6210) stub
fixme:msvcrt:__clean_type_info_names_internal (0x100f0610) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e26e980) stub
```

It seems that the outputted directory provided to python is formatted wrong for use with wine; if it was converted to `z:` rather than `c:` it may have worked.  That directory does exist; it's just the way it's provided to wine is wrong.

This is using the staging version of wine-2.0; I don't know if it's changed its behaviour somehow in this regard.

**Comment by apprenticeharper** [comment]
Thanks for the report. Has wine started using z: as the default drive instead of c:? The whole wine support needs revisiting, but wine seems to be a constantly moving target.

**Comment by ivan-m** [comment]
Z: corresponds to the root filesystem; C: is the "local" drive.

**Comment by ivan-m** [comment]
Within my wine prefix I tried adding a symbolic link `ln -s /home home` to resolve this; it now seems to find the key file but still fails:

```
DeDRM v6.5.4: Trying to decrypt B00AHQOPEO_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Hitchhiker's Guide to the Galaxy: Hitchhiker's Guide 1
Found 3 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.5.4: Running kindlekey.py under Wine
DeDRM v6.5.4: Command line: 'WINEPREFIX="/home/ivan/.wine-ade" wine python.exe "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/ivan/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
kindlekey.py v2.3
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
searching for kinfoFiles in C:\users\ivan\Local Settings\Application Data
Found K4PC 1.9+ kinf2011 file: C:\users\ivan\Local Settings\Application Data\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '328386898' and UserName '6976616e'
Saved a key to Z:\home\ivan\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey2.k4i
fixme:msvcrt:__clean_type_info_names_internal (0x1d1b6210) stub
fixme:msvcrt:__clean_type_info_names_internal (0x100f0610) stub
fixme:msvcrt:__clean_type_info_names_internal (0x1e26e980) stub
DeDRM v6.5.4: Found and decrypted 2 key files
DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 168, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.2 seconds
Added The Hitchhiker's Guide to the Galaxy: Hitchhiker's Guide 1 to db in: 0.2
Added 1 books in 1.2 seconds
```

I'm not sure if the failure is related and will keep digging into it.

**Comment by ivan-m** [comment]
I uninstalled Kindle, re-installed (I think I had 1.11 previously, this time I installed 1.16) and it seemed to work (even without having the symlink), so it must have been a temporary glitch.

sorry for the noise.
