### ISSUE TITLE
why can't install DeDRM_tools_6.5.4 on windows10 calibre?

### ISSUE THREAD

**Issue by y4f** [apprenticeharper/DeDRM_tools#334]
i want install !!
DeDRM_tools_6.5.4

calibre, version 3.6.0
エラー: ハンドルされない例外: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\yoshiki\\Downloads\\DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: ja
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\yoshiki\\Downloads\\DeDRM_tools_6.5.4.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
In case you closed this by accident or someone else has the same issue...Unzip DeDRM_tools_6.5.4.zip, look in the DeDRM calibre plugin folder, and load DeDRM_plugin.zip into calibre.
