### ISSUE TITLE
DeDRM can't decrypt a random recent .azw file.

### ISSUE THREAD

**Issue by Tenome** [apprenticeharper/DeDRM_tools#343]
Calibre 2.36
DeDRM 6.5.4
Kindle for PC 1.17.0 (44170)
The calibre-loaded book (if you need it): 
http://www.mediafire.com/file/wk3tc7vwx66ffvf/

The next issue that I bought after this worked, so I don't think it's a new DRM policy.

calibre Debug log
calibre 2.36  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM && Find Duplicates && Obok DeDRM && Open With && Goodreads Sync && Clipboard Search && Count Pages && Goodreads && Generate Cover && Favourites Menu && Save To Format
Starting up...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.find_duplicates.action", line 11, in <module>
ImportError: No module named PyQt4.Qt
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.open_with.action", line 13, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.goodreads_sync.action", line 12, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.clipboard_search.action", line 11, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.count_pages.action", line 5, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.count_pages.config", line 11, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.generate_cover.action", line 15, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.generate_cover.config", line 12, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.favourites_menu.action", line 11, in <module>
ImportError: No module named PyQt4.Qt
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 151, in __init__
  File "site-packages\calibre\gui2\ui.py", line 165, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 582, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.savetoformat.savetoformataction", line 3, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.savetoformat.gui.prompt", line 5, in <module>
ImportError: cannot import name NONE
Failed to check for calibre update: [Errno 10051] A socket operation was attempted to an unreachable network
Failed to check for plugin update: <urlopen error [Errno 10051] A socket operation was attempted to an unreachable network>
Started up in 16.88 seconds with 36 books
DeDRM v6.5.4: Trying to decrypt B071YZJSN1_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright ﾂｩ 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: 譛亥・繧ｳ繝溘ャ繧ｯ・繝舌Φ繝√2017蟷ｴ6譛亥捷 [髮題ｪ珪 (繝舌Φ繝√さ繝溘ャ繧ｯ繧ｹ)
Found 6 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Michael\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Michael\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1783167104' and UserName '4d69636861656c'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright ﾂｩ 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: 譛亥・繧ｳ繝溘ャ繧ｯ・繝舌Φ繝√2017蟷ｴ6譛亥捷 [髮題ｪ珪 (繝舌Φ繝√さ繝溘ャ繧ｯ繧ｹ)
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.5.4: Ultimately failed to decrypt after 0.9 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.9 seconds
Added 月刊コミック＠バンチ　2017年6月号 [雑誌] (バンチコミックス) to db in: 3.8
Added 1 books in 6.3 seconds
Worker Launch took: 0.207999944687
Job: 1 Convert book 1 of 1 (月刊コミック＠バンチ　2017年6月号 [雑誌] (バンチコミックス)) finished
Convert book 1 of 1 (月刊コミック＠バンチ　2017年6月号 [雑誌] (バンチコミックス))
	Resolved conversion options
	calibre version: 2.36.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Michael\\AppData\\Local\\Temp\\calibre_btrjoo\\c88c0a.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04856090>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x04856290>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Michael\\AppData\\Local\\Temp\\calibre_btrjoo\\fkdywd.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'template_css': None,
	 'template_html': None,
	 'template_html_index': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Michael\AppData\Local\Temp\calibre_btrjoo\z2hzne.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  月刊コミック＠バンチ　2017年6月号 [雑誌] (バンチコミックス) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 193, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1042, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 143, in check_for_drm
	calibre.ebooks.DRMError: 月刊コミック＠バンチ　2017年6月号 [雑誌] (バンチコミックス)

**Comment by ElleKayEm** [comment]
That's odd.  If they were both downloaded with the same installation of Kindle for PC, they should unlock with the same key (assuming both had DRM).  Try downloading a fresh copy of this one.

**Comment by Tenome** [comment]
It seems to be working again after re-downloading (I tried that last night, and it didn't work). Guess it was an unexplained error with the script or the ebook. Thanks.

**Comment by ElleKayEm** [comment]
Good!  You can close the issue if you're all set.
