### ISSUE TITLE
DeDRMError with an Adobe Adept ePub book

### ISSUE THREAD

**Issue by novoid** [apprenticeharper/DeDRM_tools#347]
Hi!

I successfully extracted the key `adeptkey.der` from my wine Adobe Digital Editions 1.7.2.1131 and imported it to the DeDRM plugin. When I now try to import an Adome Adept ePub, I get following error:

```
user@host ~ % calibre-debug -g
calibre 2.55  embedded-python: False is64bit: True
Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial Linux ('64bit', 'ELF')
('Linux', '4.4.0-92-generic', '#115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017')
Python 2.7.12
Linux: ('Ubuntu', '16.04', 'xenial')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Amazon UK Kindle at version: 15
Loaded cached store plugin for: Baen Ebooks at version: 2
Loaded cached store plugin for: Amazon FR Kindle at version: 15
Loaded cached store plugin for: Woblink at version: 13
Loaded cached store plugin for: Smashwords at version: 5
Loaded cached store plugin for: Amazon Kindle at version: 14
Loaded cached store plugin for: Kobo at version: 7
Loaded cached store plugin for: Amazon DE Kindle at version: 15
Loaded cached store plugin for: Virtualo at version: 9
Loaded cached store plugin for: Amazon ES Kindle at version: 15
Loaded cached store plugin for: Amazon AU Kindle at version: 5
Loaded cached store plugin for: Amazon IN Kindle at version: 5
Loaded cached store plugin for: Legimi at version: 8
Loaded cached store plugin for: Google Books at version: 4
Loaded cached store plugin for: Nexto at version: 4
Loaded cached store plugin for: eBooks.com at version: 3
Loaded cached store plugin for: Ebookpoint at version: 8
Loaded cached store plugin for: Publio at version: 7
Loaded cached store plugin for: Amazon CA Kindle at version: 7
Loaded cached store plugin for: eBook.nl at version: 2
Loaded cached store plugin for: Amazon IT Kindle at version: 15
Started up in 5.39 seconds with 5 books
DeDRM v6.5.1: Trying to decrypt myDRMbook.epub
DeDRM v6.5.1: Verifying zip archive integrity
DeDRM v6.5.1: “myDRMbook.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
    nfp = plugin.run(path_to_file)
  File "calibre_plugins.dedrm.__init__", line 619, in run
  File "calibre_plugins.dedrm.__init__", line 395, in ePubDecrypt
DeDRMError: DeDRM v6.5.1: Couldn't decrypt after 0.3 seconds. DRM free perhaps?
Added myDRMbook - Skeleton Crew to db in: 6.6
Added 1 books in 8.8 seconds
Worker Launch took: 0.418354988098
user@host ~ %
```

Of course, when I try to open the imported ePub within Calibre, I get notified that this ePub can not be opened because of DRM. My ebook reader also can not open it this way.

Is there something I can check?

By the way: is there a (CLI) tool that analyses an ePub and prints out information on the kind of DRM used?

**Comment by ElleKayEm** [comment]
That epub doesn't have a rights.xml inside so it won't unlock with the tools.  Not at all familiar with Linux, but I think you'll need ADE 2.0.1 under Wine to download a copy of the book you can use with the tools.  If it is authorized with the same Adobe ID, it should work with the same key.

**Comment by novoid** [comment]
Okay. I now learned that ePubs are ZIP files. :-)

You're right: the myDRMbook.epub does not contain `META-INF/rights.xml`.

I tried another ePub that has this file in it:

```
calibre 2.55  embedded-python: False is64bit: True
Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial Linux ('64bit', 'ELF')
('Linux', '4.4.0-92-generic', '#115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017')
Python 2.7.12
Linux: ('Ubuntu', '16.04', 'xenial')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Amazon UK Kindle at version: 15
Loaded cached store plugin for: Baen Ebooks at version: 2
Loaded cached store plugin for: Amazon FR Kindle at version: 15
Loaded cached store plugin for: Woblink at version: 13
Loaded cached store plugin for: Smashwords at version: 5
Loaded cached store plugin for: Amazon Kindle at version: 14
Loaded cached store plugin for: Kobo at version: 7
Loaded cached store plugin for: Amazon DE Kindle at version: 15
Loaded cached store plugin for: Virtualo at version: 9
Loaded cached store plugin for: Amazon ES Kindle at version: 15
Loaded cached store plugin for: Amazon AU Kindle at version: 5
Loaded cached store plugin for: Amazon IN Kindle at version: 5
Loaded cached store plugin for: Legimi at version: 8
Loaded cached store plugin for: Google Books at version: 4
Loaded cached store plugin for: Nexto at version: 4
Loaded cached store plugin for: eBooks.com at version: 3
Loaded cached store plugin for: Ebookpoint at version: 8
Loaded cached store plugin for: Publio at version: 7
Loaded cached store plugin for: Amazon CA Kindle at version: 7
Loaded cached store plugin for: eBook.nl at version: 2
Loaded cached store plugin for: Amazon IT Kindle at version: 15
Started up in 5.43 seconds with 6 books
DeDRM v6.5.1: Trying to decrypt myDRMbook2.epub
DeDRM v6.5.1: Verifying zip archive integrity
DeDRM v6.5.1: myDRMbook2.epub is a secure Adobe Adept ePub
DeDRM v6.5.1: Trying Encryption key adeptkey
DeDRM v6.5.1: Decrypted with key adeptkey after 0.4 seconds
DeDRM v6.5.1: Finished after 0.4 seconds
Added the other ePub to db in: 10.0
Added 1 books in 31.9 seconds
```

So the exception from my original posting above is missing.

It is working: I am able to open and read the ePub from within Calibre. Thanks for your help! I'll have to re-download the first ePub from the original source.
