### ISSUE TITLE
No key found

### ISSUE THREAD

**Issue by laredotech** [apprenticeharper/DeDRM_tools#35]
I did one book 2 days ago and now i can't do it. Did the keys changed?

Found 4 keys to try after 2.3 seconds
Crypto Type is: 2
Error decrypting book after 2.3 seconds: No key found in 4 keys tried.
Traceback (most recent call last):
  File "C:\Users\local\Desktop\DRM\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 248, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "C:\Users\local\Desktop\DRM\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 222, in GetDecryptedBook
    mb.processBook(totalpids)
  File "C:\Users\local\Desktop\DRM\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\mobidedrm.py", line 469, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
DeDRM v6.3.4: Failed

DeDRM v6.3.4: Complete:  Successes: 0, Failures: 1

**Comment by apprenticeharper** [comment]
No, the keys haven't changed. You've probably taken this book from a different source - Kindle keys are device specific. If you still have problems, ask at Alf's blog where Laura or Paul or another regular will respond more quickly then me on support issues like this.
