### ISSUE TITLE
unable to decrypt azw4 file

### ISSUE THREAD

**Issue by AcousticNomad** [apprenticeharper/DeDRM_tools#352]
I have been unable to get a particular azw4 book that I just purchased to decrypt.  I have confirmed that I am able to decrypt all other books that I have in my Kindle library (PC), but this one is being stubborn.  The only unusual thing about it is that is larger than any other book that I have (400MB).  I've tried using DeDRM 6.5.4 with Calibre 3.6, and also with the standalone DeDRM script.  I have some experience with Python programming, so let me know how I can assist with debugging, I'm just not sure where to start looking.

```
calibre Debug log
calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 4) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.036923077 x 99.1219512195
Using calibre Qt style: True
Starting up...
Started up in 18.12 seconds with 361 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xcf\x03\xb7q\x9ao \x8f\xff\xeb\xc7C\xe2s\xf4k\xad\xa59\xe9\r\xc8b\xaf\xc8g-\t\x90U)\xa0', 'H:\\Documents\\My Kindle Content\\B00IR9RIGK_EBOK.azw4']
DeDRM v6.5.4: Trying to decrypt B00IR9RIGK_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 4, header length 264
Decrypting Mobipocket 4 ebook: (title removed)
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.4: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Acoustic\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Acoustic\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2755986265' and UserName '45726963'
DeDRM v6.5.4: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds
Added (title removed) to db in: 3.4
Added 1 books in 4.4 seconds
```

**Comment by ElleKayEm** [comment]
I'd try 64-bit calibre.

**Comment by AcousticNomad** [comment]
Awesome, that worked!  It took half an hour to process. :smile:  Thank you very much!
