### ISSUE TITLE
Can't configure DeDRM in Calibre (Windows 10-64b)

### ISSUE THREAD

**Issue by waktion** [apprenticeharper/DeDRM_tools#354]
When I tried configure Calibre's plugin I get this:

----------------------------------
calibre, version 3.7.0
ERROR: Excepción no considerada: <b>ImportError</b>:No module named PyQt4.Qt

calibre 3.7 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.15063-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 0, 8) && Amazon.com Multiple Countries (1, 0, 0) && KindleUnpack - The Plugin (0, 81, 5)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 293, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 371, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 155, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 494, in config_widget
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.dedrm.config", line 12, in <module>
ImportError: No module named PyQt4.Qt
--------------------------------------

Can you tell me where is the problem?
Many thanks

**Comment by ElleKayEm** [comment]
You've got an ancient version of the plugin.  Update to the current release.

**Comment by waktion** [comment]
I have v. 6.5.4
Is it not the last version?

**Comment by waktion** [comment]
Sorry, DeDRM version is 6.0.8    Is this the last one?

**Comment by ElleKayEm** [comment]
6.5.4 is the current one.  Your log shows 6.0.8.  After installing a plugin, always restart calibre before trying to use it.

**Comment by waktion** [comment]
I've reinstalled the plugin antd it works!! Thank you.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
