### ISSUE TITLE
androidkeys error on calibre plugin macos

### ISSUE THREAD

**Issue by hithwen** [apprenticeharper/DeDRM_tools#360]
Installed the calibre plugin, clicked on config plugin and got this exception
```
calibre, version 3.4.0
ERROR: Excepción no considerada: <b>KeyError</b>:'androidkeys'

calibre 3.4  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 5, 4) && Kindle Collections (1, 7, 15)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 293, in customize_plugin
  File "site-packages/calibre/gui2/preferences/plugins.py", line 371, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 155, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 635, in config_widget
  File "calibre_plugins.dedrm.config", line 57, in __init__
  File "calibre_plugins.dedrm.prefs", line 50, in __getitem__
  File "site-packages/calibre/utils/config.py", line 420, in __getitem__
KeyError: 'androidkeys'
```
Seems to have fixed after doing two things:
* Restarting calibre
* Switching computer lang to English

Now I cannot reproduce if I switch lang back to Spanish so I'm going to guess it was the restart that fixed it.

**Comment by ElleKayEm** [comment]
Always restart calibre after installing a new plugin.  If you're all set, you can close this issue.
