### ISSUE TITLE
DRM not removed.

### ISSUE THREAD

**Issue by Reyalan** [apprenticeharper/DeDRM_tools#405]
Since the book I was trying to add was a KFX file format, so I used the "transfer via USB" option from Amazon's website to get a .azw3 file format of it. However, it was unable to decrypt the file for some odd reason. 

Here's the debug log:

```
calibre Debug log
calibre 3.12  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4)
calibre 3.12  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 78.5314009662 x 80.4457478006
Using calibre Qt style: True
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: ebook.de at version: 5
Started up in 10.38 seconds with 8 books
DeDRM v6.5.5: Trying to decrypt Privacy_ What Everyone Needs to Know_.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Privacy: What Everyone Needs to Know?
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Everett\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Everett\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3897689565' and UserName '45766572657474'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Privacy: What Everyone Needs to Know?
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Privacy: What Everyone Needs to Know? to db in: 1.6
Added 1 books in 2.7 seconds
```

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device?  If so, then you need to enter its serial number into the plugin configuration.
