### ISSUE TITLE
Failed to remove DRM on B&N in calibre

### ISSUE THREAD

**Issue by kboldiszar** [apprenticeharper/DeDRM_tools#407]
I am unable to remove DRM with calibre. I am on Windows 10 using Windows 10 Windows app. I have no problems getting the key from B&N. I saw another user with almost identical issue but he said "Ok, so I downloaded the other version of the software (missed that in the instructions derp)" Don't know what he ment?

calibre 3.12  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 92.0536912752
Using calibre Qt style: True
Starting up...
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.97:  0.801) _startup_on_demand listening on port 9090
SMART_DEV (   1.02:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.07:  0.000) _startup_on_demand broadcast socket listening on port 54982
Started up in 4.45 seconds with 2851 books
SMART_DEV (   2.14:  1.020) run All IP addresses {'{1FCAB51B-DAFF-4677-BCD7-B828E10AADBD}': [{'broadcast': u'192.168.0.112', 'netmask': u'255.255.255.255', 'addr': u'192.168.0.112'}], '{7B824C77-9419-11E7-914D-806E6F6E6963}': [{'broadcast': u'127.0.0.1', 'netmask': u'255.255.255.255', 'addr': u'127.0.0.1'}]}
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb0`\xe96-w\x1aN\xf9\xc0\xd0[\x1d(S)\x1d\x10G\x10\xba\xb7\xd1k\xc8\x131\xd7\x83\x81\t\xef', 'C:\\Users\\Kieth\\AppData\\Local\\Packages\\BarnesNoble.Nook_ahnzqzva31enc\\LocalState\\9780525536062.epub']
DeDRM v6.5.5: Trying to decrypt 9780525536062.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “9780525536062.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.5: Trying Encryption key bn_key
Could not decrypt nxhe80.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.5.5: Failed to decrypt with key bn_key after 0.1 seconds
DeDRM v6.5.5: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 298, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Zero Hour to db in: 2.3
Added 1 books in 3.2 seconds
Worker Launch took: 0.123000144958
Job: 1 Convert book 1 of 1 (Zero Hour) finished
Convert book 1 of 1 (Zero Hour)
        Conversion options changed from defaults:
          read_metadata_from_opf: u'C:\\Users\\Kieth\\AppData\\Local\\Temp\\calibre_8cgaw_\\1w2yg0.opf'
          verbose: 2
        Resolved conversion options
        calibre version: 3.12.0
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': None,
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_compress': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x056A8250>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'mobi_file_type': u'old',
         'mobi_ignore_margins': False,
         'mobi_keep_original_images': False,
         'mobi_toc_at_start': False,
         'no_chapters_in_toc': False,
         'no_inline_navbars': False,
         'no_inline_toc': False,
         'output_profile': <calibre.customize.profiles.OutputProfile object at 0x056A8430>,
         'page_breaks_before': u'/',
         'personal_doc': u'[PDOC]',
         'prefer_author_sort': False,
         'prefer_metadata_cover': False,
         'pretty_print': False,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\Kieth\\AppData\\Local\\Temp\\calibre_8cgaw_\\1w2yg0.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'share_not_sync': False,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: EPUB Input running
        on C:\Users\Kieth\AppData\Local\Temp\calibre_8cgaw_\fpsfku.epub
        Python function terminated unexpectedly
          fpsfku.epub (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 101, in main
          File "site.py", line 78, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
          File "site-packages\calibre\customize\conversion.py", line 245, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 268, in convert
        calibre.ebooks.DRMError: fpsfku.epub

**Comment by ElleKayEm** [comment]
Try using Nook for PC.  Here is the setup file:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

The books will be in a B&N folder inside your documents folder.

**Comment by kboldiszar** [comment]
That worked, Thank you!!!

Kieth

Kieth Boldiszar
Littleton, Co

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
