### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by Cosmicist** [apprenticeharper/DeDRM_tools#410]
I downloaded the azw3 from my amazon account and configured my device serial number in the `eInk Kindle ebooks` device configuration correctly. So here's the Calibre debug log:

```
calibre Debug log
calibre 3.13  embedded-python: True is64bit: True
Linux-4.13.0-12-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
('Linux', '4.13.0-12-generic', '#13-Ubuntu SMP Sat Sep 23 03:40:16 UTC 2017')
Python 2.7.12
Linux: ('debian', 'stretch/sid', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.13  embedded-python: True is64bit: True
Linux-4.13.0-12-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
('Linux', '4.13.0-12-generic', '#13-Ubuntu SMP Sat Sep 23 03:40:16 UTC 2017')
Python 2.7.12
Linux: ('debian', 'stretch/sid', '')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Starting up...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
Started up in 11.97 seconds with 2 books
DeDRM v6.5.5: Trying to decrypt The Stranger (Vintage International).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Stranger (Vintage International)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.5.5: Running kindlekey.py under Wine
DeDRM v6.5.5: Command line: 'WINEPREFIX="/home/cosmicist" wine python.exe "/home/cosmicist/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/cosmicist/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
/bin/sh: 1: wine: not found
DeDRM v6.5.5: Found and decrypted 0 key files
DeDRM v6.5.5: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Stranger (Vintage International) to db in: 0.4
Added 1 books in 0.8 seconds
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.
```

Thanks!

**Comment by ElleKayEm** [comment]
Nevertheless, the key in the configuration isn't working for this book.  Make sure that the device chosen when downloading from the website was an E-ink Kindle, not a Fire.  And double-check that the serial number is correct.

**Comment by Cosmicist** [comment]
Thanks! Amazon gives me only one option for download... maybe because I only own a Kindle and nothing else?
I checked the device serial number in amazon and I see it's different from the one that is shown on my device... that... is... weird... I used the one that appears on amazon and now it worked!
Thanks!
