### ISSUE TITLE
Syntax Warning: Invalid Font Weight

### ISSUE THREAD

**Issue by RoseWebb** [apprenticeharper/DeDRM_tools#414]
I am trying to decrypt adobe digital edition. The book is successfully decrypted, however, when I try to open the pdf file, the pdf reader shows an error saying "there was a problem reading this document (110)". Any ideas how to fix this? 
I am using the Calibre plugin.

**Comment by ElleKayEm** [comment]
Have you tried opening it with a different PDF reader?

**Comment by apprenticeharper** [comment]
Have you tried the very latest version of the plugin? There was a fix for the PDF decryption in that update that concerned the treatment of numbers.

**Comment by technomooney** [comment]
i am having a similar issue but the problem is with a amazon kindle book (azw4 format) and it is a pdf wrapped in amazon packaging and i am able to use edge and other pdf readers with the raw pdf (i extracted it by converting from the azw4 file) but even with that i cant convert it to epub even on online converters so i am wondering what may be the issue... 

no matter what i do i get a `UnicodeDecodeError: 'utf8' codec can't decode byte ` at first and when it is converting to html i get a spamming of `Syntax Warning: Invalid Font Weight` 

here is the traceback 
`Python function terminated unexpectedly
  'utf8' codec can't decode byte 0xad in position 1355882: invalid start byte (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\azw4_input.py", line 27, in convert
  File "site-packages\calibre\ebooks\azw4\reader.py", line 57, in extract_content
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_input.py", line 52, in convert
  File "site-packages\calibre\ebooks\pdf\pdftohtml.py", line 98, in pdftohtml
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xad in position 1355882: invalid start byte`
