### ISSUE TITLE
DRM not removed on 1 out of many B&N EPUB files

### ISSUE THREAD

**Issue by TimFH** [apprenticeharper/DeDRM_tools#416]
Tool: both the Calibre plugin and the DeDRM_Macintosh_Application

System: Mac OS 10.9 (Maverick)

Source: Downloaded by Nook Study app (along with all the other files that worked)

Errors: couldn't be decoded

Log: follows

There is 1 ebook to be decrypted.
Processing file: jfk.epub
shellcommand: /usr/local/bin/python '/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/zipfix.py' '/Users/tfhavel/Temp/EpubDRMrem/jfk.epub' '/Users/tfhavel/Desktop/jfk_fixed.epub' > '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  
shellcommand: /usr/local/bin/python '/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/epubtest.py' '/Users/tfhavel/Desktop/jfk_fixed.epub' > '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: B&N
 
shellcommand: /usr/local/bin/python '/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignobleepub.py' '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/tfhavel@gmail.com.b64' '/Users/tfhavel/Desktop/jfk_fixed.epub' '/Users/tfhavel/Desktop/jfk_nodrm.epub' > '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Could not decrypt jfk_fixed.epub because of an exception:
Traceback (most recent call last):
  File "/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignobleepub.py", line 316, in decryptBook
    outf.writestr(zi, decryptor.decrypt(path, data))
  File "/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignobleepub.py", line 234, in decrypt
    data = self.decompress(data)
  File "/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignobleepub.py", line 224, in decompress
    bytes = dc.decompress(bytes)
error: Error -3 while decompressing: invalid distance too far back

 The command exited with a non-zero status.
shellcommand: /usr/local/bin/python '/Applications/3rd Party Utils/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/ignoblekey.py' '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: ignoblekey.py v1.1
Copyright © 2015 Apprentice Alf
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/DesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/DesktopReader/indices/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/BNDesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/BNDesktopReader/indices/BNClientLog.txt
Found 38 keys in the Nook Study log files
Saved a key to /Users/tfhavel/Library/Preferences/com.apprenticealf.dedrm/newKeys/nookkey1.b64
 
There was an error with 1 ebook:
jfk.epub couldn't be decoded:

**Comment by ElleKayEm** [comment]
Hmm, usually these are all or nothing.  Did you try a fresh copy of the book?  Is there anything unusual about that book?  Admittedly I'm not that familiar with the Mac App logs.

**Comment by TimFH** [comment]
I did try a "fresh" copy of the book, and I did decompress it and compared its contents with those of others that worked, and didn't see anything obvious (save that the encrypted text files had the extension ".xhtml" rather than ".html"). Be happy to attach the EPUB file itself if someone who knows more about these things wants to have a look. Or to generate a plugin log file if that's really that different from the app's.

**Comment by ElleKayEm** [comment]
Let's have a look at the plugin log.  Don't worry about attaching the epub.  Apprentice Harper might ask for it if needed.

**Comment by TimFH** [comment]
Thanks. I have since determined that there were at least 3 other BNN Ebooks in my collection that did not get DeDRM'd, but here's the plugin log for the one I found first:

calibre Debug log
calibre 3.14  embedded-python: True is64bit: True
Darwin-13.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '13.4.0', 'Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.9.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.14  embedded-python: True is64bit: True
Darwin-13.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '13.4.0', 'Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.9.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 133.000001997 x 133.000001997
Using calibre Qt style: True
Starting up...
Using proxies: {'http': '127.0.0.1:8228'}
Started up in 5.27 seconds with 65 books
Using proxies: {'http': '127.0.0.1:8228'}
2017-12-21 13:10:00.498 Calibre[6932:507] deliverNotificationWithTitle()
* Notification delivered.
DeDRM v6.5.5: Trying to decrypt jfkandtheunspeakable_9781608330690.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: “jfkandtheunspeakable_9781608330690.epub” is a secure Barnes & Noble ePub
DeDRM v6.5.5: Trying Encryption key tfhavel@gmail.com
Could not decrypt MJFp6j.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 316, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 234, in decrypt
  File "calibre_plugins.dedrm.ignobleepub", line 224, in decompress
error: Error -3 while decompressing: invalid distance too far back

DeDRM v6.5.5: Failed to decrypt with key tfhavel@gmail.com after 0.4 seconds
DeDRM v6.5.5: Looking for new NOOK Study Keys after 0.4 seconds
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/DesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/DesktopReader/indices/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/BNDesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/tfhavel/Library/Application Support/Barnes & Noble/BNDesktopReader/indices/BNClientLog.txt
Found 38 keys in the Nook Study log files
DeDRM v6.5.5: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 298, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added JFK and the Unspeakable: Why He Died and Why It Matters to db in: 0.2
Added 1 books in 5.4 seconds
Worker Launch took: 0.126825809479

**Comment by ElleKayEm** [comment]
I think we'll have to see what @apprenticeharper says about this one.

**Comment by TimFH** [comment]
Hello ElleKayEm,

Anything to report? If not, perhaps you could send @apprenticeharper a 
reminder (now that the holidays are over)?

Happy New Year,

Timothy F. Havel
306 Commonwealth Ave.
Boston, MA 02115, USA

**Comment by ElleKayEm** [comment]
His email is apprenticeharper@gmail.com.

**Comment by apprenticeharper** [comment]
I've had less time than usual to spend here lately. And that's unlikely to change in the near future. However, please attach the ePub in question here, and send me a copy of your B&N key(s) exported from calibre via email to apprenticeharper@gmail.com I'll see what I can do, but it might not be for some weeks.

**Comment by TimFH** [comment]
Just wondering if you'd had a chance to debug the files I sent you via Email a couple of months ago?

**Comment by apprenticeharper** [comment]
Sorry, a change in my work has meant that I now only have a couple of hours a month to spend on this. I have received the files, and I remember taking an initial look, but I haven't got any answers yet.

I've about used up my time this month, but I'll try to take a look next month.

Harper.
