### ISSUE TITLE
Plugin not installing, error message

### ISSUE THREAD

**Issue by quentintarantado** [apprenticeharper/DeDRM_tools#420]
Hi, on Jan 1, 2018, I tried installing the De DRM plugin to Calibre (3.14)
I got this error message:
calibre, version 3.14.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'D:\\joel\\download\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.14 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'D:\\joel\\download\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to install the whole zip file.  Unzip DeDRM_tools_6.5.5.zip.  Look in the DeDRM calibre plugin folder.  Load DeDRM_plugin.zip into calibre.

**Comment by quentintarantado** [comment]
Yes, how stupid of me.
Thank you very much!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
