### ISSUE TITLE
Calibre refuses to install DeDRM plugin 6.5.5.zip

### ISSUE THREAD

**Issue by Dabooda** [apprenticeharper/DeDRM_tools#422]
I just tried to add the DeDRM plugin on Calibre Version 3.6.0, and couldn't.  Error message:

calibre, version 3.6.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\xxxx\\Downloads\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.6  embedded-python: True is64bit: False
Windows-10-10.0.15063-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.15063')
Python 2.7.12+
Windows: ('10', '10.0.15063', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\xxxx\\Downloads\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

What to do?

**Comment by ElleKayEm** [comment]
You're trying to install the whole zip file. Unzip DeDRM_tools_6.5.5.zip. Look in the DeDRM calibre plugin folder. Load DeDRM_plugin.zip into calibre.

**Comment by Dabooda** [comment]
Excellent, that works.  Thanks very much
