### ISSUE TITLE
Calibre DRM Removal Issue

### ISSUE THREAD

**Issue by DrCheshireRaptor** [apprenticeharper/DeDRM_tools#427]
Running Windows 10, got the books from Amazon through purchase and the Kindle Unlimited program (which I didn't have a problem with before, but I know things have changed) I believe this debug is from a Kindle Unlimited book.
calibre Debug log
calibre 3.15  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.15  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
Starting up...
Started up in 5.03 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x06\xdaO\xb9"\x11\x11\xde\xb1\'\t\x89\xaa\xc4\xc6\xc9\xfb\xa4{\x07#o\x9b\x08\x88g\xa5#\xe9 \xda@', 'D:\\Documents\\My Kindle Content\\B00ED1ZHZK_EBOK.azw']
DeDRM v6.5.5: Trying to decrypt B00ED1ZHZK_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Bones Will Tell (Skye Cree, Book 2)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\User\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\User\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3033284609' and UserName '55736572'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Bones Will Tell (Skye Cree, Book 2)
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Bones Will Tell (Skye Cree, Book 2) to db in: 0.3
Added 1 books in 1.5 seconds

**Comment by ElleKayEm** [comment]
Did you know that authors don't get paid when you read Kindle Unlimited books outside a Kindle device/app?

**Comment by DrCheshireRaptor** [comment]
Please don't comment if you have nothing to add to the thread.
