### ISSUE TITLE
Android Keys error on pc with no connected android device ?

### ISSUE THREAD

**Issue by mikeloeven** [apprenticeharper/DeDRM_tools#43]
Just updated to the current version of the plugin however when i click the plugin options i get a unhandled exception 

KeyError: 'androidkeys' 

calibre 1.18  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.5
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 286, in customize_plugin
  File "site-packages\calibre\gui2\preferences\plugins.py", line 361, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 150, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 614, in config_widget
  File "calibre_plugins.dedrm.config", line 57, in __init__
  File "calibre_plugins.dedrm.prefs", line 50, in __getitem__
  File "site-packages\calibre\utils\config.py", line 387, in __getitem__
KeyError: 'androidkeys'

to the best of my knowledge there is no android device currently plugged into my computer or registered with calibre

**Comment by ElleKayEm** [comment]
You're using a really old version of calibre.  It's currently on version 2.40.  I'd try updating that first.
