### ISSUE TITLE
KeyError: 'androidkeys'  this is on a MAC when I press Customize Plugin button in Calibre

### ISSUE THREAD

**Issue by shane-oliver** [apprenticeharper/DeDRM_tools#431]
calibre, version 3.15.0
ERROR: Unhandled exception: <b>KeyError</b>:'androidkeys'

calibre 3.15  embedded-python: True is64bit: True
Darwin-17.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.3.0', 'Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Kindle Collections (1, 7, 17)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 290, in double_clicked
  File "site-packages/calibre/gui2/preferences/plugins.py", line 371, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 155, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 642, in config_widget
  File "calibre_plugins.dedrm.config", line 57, in __init__
  File "calibre_plugins.dedrm.prefs", line 50, in __getitem__
  File "site-packages/calibre/utils/config.py", line 420, in __getitem__
KeyError: 'androidkeys'

**Comment by ElleKayEm** [comment]
Try restarting calibre.  If that doesn't do it, try removing the plugin, restarting calibre, reloading the plugin, then restarting calibre again before trying to customize.

Always a good idea to restart calibre immediately after loading a plugin before trying to do anything with it.

**Comment by shane-oliver** [comment]
You are a champ - Seems to have fixed the issue.  I can now get into the settings section

**Comment by shane-oliver** [comment]
Oh and thanks for the rapid reply
