### ISSUE TITLE
Unable to load Kindle for PC key

### ISSUE THREAD

**Issue by Dngrsone** [apprenticeharper/DeDRM_tools#443]
I am running a fresh install of Mint KDE 18.3.

I have the latest iteration of Calibre for Linux installed (3.17.0) with DeDRM 6.3.3.

I have Kindle for PC via wine.  I have located the key, but when I try to import it I get an unhandled exception error:

> calibre, version 3.17.0
> ERROR: Unhandled exception: <b>ValueError</b>:No JSON object could be decoded
> 
> calibre 3.17  embedded-python: True is64bit: True
> Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid Linux ('64bit', 'ELF')
> ('Linux', '4.13.0-32-generic', '#35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018')
> Python 2.7.12
> Linux: ('debian', 'stretch/sid', '')
> Interface language: None
> Successfully initialized third party plugins: DeDRM (6, 3, 3)
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.config", line 426, in migrate_wrapper
>   File "calibre_plugins.dedrm.config", line 392, in migrate_files
>   File "json/__init__.py", line 339, in loads
>   File "json/decoder.py", line 364, in decode
>   File "json/decoder.py", line 382, in raw_decode
> ValueError: No JSON object could be decoded

Any ideas?

**Comment by apprenticeharper** [comment]
Try with the latest version (6.5.5)
