### ISSUE TITLE
Unable to process AZW4 w/ Calibre-64. Unable to kindle unpack

### ISSUE THREAD

**Issue by Ronzalpha** [apprenticeharper/DeDRM_tools#444]
Hey There! Trying to remove a DRM but it didn't work for some reason. It gave this error message and when i try to unpack the kindle using the plugin, the AZW4 option is greyed out. I have no clue how to proceed. Kindle version 1.15, Win 10 OS

calibre, version 3.17.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Management Information Systems)

Convert book 1 of 1 (Management Information Systems)
Conversion options changed from defaults:
  cover: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_qatts_\\jmwpgu.jpeg'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_qatts_\\l91mbp.opf'
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 3.17.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_qatts_\\jmwpgu.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001E24524C860>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001E24524CBE0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_qatts_\\l91mbp.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Python function terminated unexpectedly
  No embedded PDF found in AZW4 file (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
  File "site-packages\calibre\ebooks\azw4\reader.py", line 24, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
If that's a rented book, DeDRM won't work.  Otherwise, post a log of adding the book:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Ronzalpha** [comment]
Thanks for following up! I bought the book instead of renting it. Here's the log:

[2018-02-11 23:55:04,983]-[DEBUG]-[FILE: main.py]-[FUNC: main]-[LINE: 6]-[MSG: Application start.]
[2018-02-11 23:55:05,769]-[DEBUG]-[FILE: explorer.py]-[FUNC: lib_sort]-[LINE: 786]-[MSG: Sort library books by date.]
[2018-02-11 23:57:16,832]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:57:16,847]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:57:16,847]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:57:16,851]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 4, header length 264]
[2018-02-11 23:57:16,867]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:57:16,867]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:57:16,867]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:57:16,867]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:57:16,868]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:57:16,876]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:57:37,699]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:57:37,715]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00H7HUHSE_EBOK.azw4]
[2018-02-11 23:57:37,715]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:57:37,732]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 4, header length 248]
[2018-02-11 23:57:37,778]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:57:37,779]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:57:37,779]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:57:37,779]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:57:37,781]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00H7HUHSE_EBOK.azw4]
[2018-02-11 23:57:37,783]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:57:41,966]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00H7HUHSE_EBOK.azw4]
[2018-02-11 23:57:41,966]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:57:41,982]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 4, header length 248]
[2018-02-11 23:57:42,025]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:57:42,025]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:57:42,025]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:57:42,025]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:57:42,027]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00H7HUHSE_EBOK.azw4]
[2018-02-11 23:57:42,029]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:57:49,558]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:57:49,573]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B003GEKKXO_EBOK.azw]
[2018-02-11 23:57:49,574]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:57:49,690]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 6, header length 232]
[2018-02-11 23:57:49,690]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 177]-[MSG: Extra Data Flags: 2]
[2018-02-11 23:57:49,693]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:57:49,694]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:57:49,694]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:57:49,694]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:57:49,694]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B003GEKKXO_EBOK.azw]
[2018-02-11 23:57:49,696]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:57:52,965]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:57:52,981]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00IHGVS6E_EBOK.azw]
[2018-02-11 23:57:52,982]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:57:53,025]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 8, header length 264]
[2018-02-11 23:57:53,026]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 177]-[MSG: Extra Data Flags: 3]
[2018-02-11 23:57:53,027]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:57:53,027]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:57:53,027]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:57:53,027]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:57:53,027]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00IHGVS6E_EBOK.azw]
[2018-02-11 23:57:53,029]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:58:01,779]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:58:02,635]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:58:16,696]-[DEBUG]-[FILE: tables.py]-[FUNC: addBooks]-[LINE: 472]-[MSG: Start add books.]
[2018-02-11 23:58:16,712]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:58:16,713]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:58:16,716]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 4, header length 264]
[2018-02-11 23:58:16,726]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:58:16,726]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:58:16,726]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:58:16,726]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:58:16,727]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:58:16,729]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]
[2018-02-11 23:58:35,390]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: remove_drm]-[LINE: 32]-[MSG: Start to remove Kindle drm -- file: C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:58:35,390]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 89]-[MSG: Book is Mobi]
[2018-02-11 23:58:35,394]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: __init__]-[LINE: 174]-[MSG: MOBI header version 4, header length 264]
[2018-02-11 23:58:35,404]-[DEBUG]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 104]-[MSG: Found 3 keys to try]
[2018-02-11 23:58:35,404]-[DEBUG]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 329]-[MSG: Crypto Type is: 2]
[2018-02-11 23:58:35,405]-[ERROR]-[FILE: mobidedrm.py]-[FUNC: processBook]-[LINE: 376]-[MSG: No key found in 3 keys tried.]
[2018-02-11 23:58:35,405]-[ERROR]-[FILE: remove_drm.py]-[FUNC: kindle]-[LINE: 109]-[MSG: Remove drm failed]
[2018-02-11 23:58:35,405]-[DEBUG]-[FILE: tables.py]-[FUNC: run]-[LINE: 1073]-[MSG: Remove drm failed: Kindle DRM - C:\Users\Ronzalpha\Documents\My Kindle Content\B00DC5URI0_EBOK.azw4]
[2018-02-11 23:58:35,407]-[DEBUG]-[FILE: dlgBugReport.py]-[FUNC: __init__]-[LINE: 273]-[MSG: Bug report: remove drm failed.]

**Comment by ElleKayEm** [comment]
That doesn't look like a log from calibre/DeDRM.

**Comment by Ronzalpha** [comment]
oh my, I'm sorry. I posted the wrong log. Here's the correct log

calibre Debug log
calibre 3.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.17 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
Starting up...
Started up in 91.01 seconds with 6 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['n\x12\x0e\xe0:\xcevgK%\x0c\x95\x19\xaf\xbc \x88\xe7?\x1c\xf3\xc6T\x07\xa0\xc1\xa0\xf6\x85\x02*\xc1', 'C:\\Users\\Ronzalpha\\Documents\\My Kindle Content\\B00H7HUHSE_EBOK.azw4']
DeDRM v6.5.5: Trying to decrypt B00H7HUHSE_EBOK.azw4
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Management Information Systems
Got DSN key from database default_key_2
Found 8 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Ronzalpha\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Management Information Systems to db in: 0.2
Added 1 books in 0.7 seconds
Worker Launch took: 0.0599999427795
Job: 1 Convert book 1 of 1 (Management Information Systems) finished
Convert book 1 of 1 (Management Information Systems)
	Conversion options changed from defaults:
	  verbose: 2
	  cover: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\2s2orb.jpeg'
	  output_profile: 'generic_eink'
	  read_metadata_from_opf: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\sxmgey.opf'
	Resolved conversion options
	calibre version: 3.17.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\2s2orb.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000029018EF4D68>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000029018F00128>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\sxmgey.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	Python function terminated unexpectedly
	  No embedded PDF found in AZW4 file (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
	  File "site-packages\calibre\ebooks\azw4\reader.py", line 24, in unwrap
	ValueError: No embedded PDF found in AZW4 file

Convert book 1 of 1 (Management Information Systems)
Conversion options changed from defaults:
  verbose: 2
  cover: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\2s2orb.jpeg'
  output_profile: 'generic_eink'
  read_metadata_from_opf: u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\sxmgey.opf'
Resolved conversion options
calibre version: 3.17.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\2s2orb.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000029018EF4D68>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000029018F00128>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\Ronzalpha\\AppData\\Local\\Temp\\calibre_q6abq6\\sxmgey.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
Python function terminated unexpectedly
  No embedded PDF found in AZW4 file (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1074, in run
  File "site-packages\calibre\ebooks\azw4\reader.py", line 24, in unwrap
ValueError: No embedded PDF found in AZW4 file

**Comment by ElleKayEm** [comment]
If you're downloading the book from the website, you need to chose an E-ink Kindle and put its serial number into the plugin customization.  If you're downloading it to Kindle for PC, then it needs to be on the same machine and user as calibre.

**Comment by Ronzalpha** [comment]
Hmm yeah the problem was resolved. I didn't realize i had to keep kindle for PC installed for azw4 textbooks. Thanks for the help!
