### ISSUE TITLE
DeDRM not working on new Kobo epub

### ISSUE THREAD

**Issue by CoolJoe86** [apprenticeharper/DeDRM_tools#448]
Hi, I like to download my epubs from Kobo (via Adobe Digital Editions) and then import them to Caliber to better manage my library. No problems in the past, but now when I import epubs, the DRM is not removed. I'm running Windows 10 with intel i7. Here is the log file:

calibre Debug log
calibre 3.16  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.16  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 5, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
Starting up...
Started up in 4.28 seconds with 58 books
DeDRM v6.5.5: Trying to decrypt Napoleons Wars.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: Napoleons Wars.epub is a secure Adobe Adept ePub
DeDRM v6.5.5: Trying Encryption key default_key
Could not decrypt qyyib9.epub. Wrong key
DeDRM v6.5.5: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.5: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 400, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Napoleon’s Wars to db in: 2.1
Added 1 books in 2.8 seconds

Thanks for your help.

**Comment by ElleKayEm** [comment]
What changed with your setup?  Looks like the key that was already in the plugin wasn't right for this book.  And then when it looked for the key in the current installation of ADE, that didn't work either.  Was this downloaded with ADE 2.0.1 authorized with your Adobe ID?  And is it on the same machine and user as calibre?

**Comment by CoolJoe86** [comment]
No, I downloaded it on a different machine. Could this be the problem then? Thanks!

**Comment by ElleKayEm** [comment]
Should still work unless they're authorized with different Adobe IDs.

**Comment by CoolJoe86** [comment]
I think that's the problem, since I don't have an Adobe ID, so I imagine some default ID is used which is linked to the computer.

**Comment by ElleKayEm** [comment]
I'm actually surprised that you were able to remove DRM at all then.  You should always authorize any new installation of Adobe Digital Editions with an Adobe ID.  Otherwise, anything downloaded to it will be locked to that installation of ADE.

**Comment by CoolJoe86** [comment]
OK, I will do that in future. Thanks for helping me sort this out.
