### ISSUE TITLE
DeDRM no longer working on Mac?

### ISSUE THREAD

**Issue by Meatius** [apprenticeharper/DeDRM_tools#454]
Hi, I've previously used the Dedrm through Calibre and today it is unable to remove the dam from an ePub.  tired with both Calibre plug in and using the standalone Mac application, the book briefly turns up in the output folder but disappears and is unable to remove the DRM.  Anybody else having Mac issues?

Calibre 3.17
DeDrm 6.2

**Comment by ElleKayEm** [comment]
Post a log:
https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Meatius** [comment]
Processing file: Why_Therapy_Works.epub
shellcommand: /usr/bin/python '/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/zipfix.py' '/Users/meatius/Downloads/Why_Therapy_Works.epub' '/Users/meatius/Desktop/DRM Free Books/Why_Therapy_Works_fixed.epub' > '/Users/meatius/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  
shellcommand: /usr/bin/python '/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/epubtest.py' '/Users/meatius/Desktop/DRM Free Books/Why_Therapy_Works_fixed.epub' > '/Users/meatius/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Adobe
 
shellcommand: /usr/bin/python '/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/adobekey.py' '/Users/meatius/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/meatius/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: adobekey.py v6.0
Copyright © 2009-2013 i♥cabbages and Apprentice Alf
 Traceback (most recent call last):
  File "/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/adobekey.py", line 602, in <module>
    sys.exit(cli_main())
  File "/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/adobekey.py", line 525, in cli_main
    keys = adeptkeys()
  File "/private/var/folders/lx/pwpmy8qn6ql1ylw4lr4zwr400000gn/T/AppTranslocation/7D074F25-4407-4013-93E4-464E0423C9B3/d/DeDRM.app/Contents/Resources/adobekey.py", line 446, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
__main__.ADEPTError: Could not find ADE activation.dat file.
There was an error with 1 ebook:
Why_Therapy_Works.epub couldn't be decoded:

**Comment by ElleKayEm** [comment]
Looks like ADE isn't activated with a Adobe ID?

**Comment by Meatius** [comment]
What is ADE?

Peter Roberts
PRL Executives

**Comment by Flnch** [comment]
ADE is "Adobe Digital Editions".

**Comment by ideologysec** [comment]
Having the same trouble.

macOS Mojave 10.14.3
Adobe Digital Editions: 2.0.1, 3.0, 4.5.

Activated all three with an AdobeID, no _~/Library/Application Support/Adobe Digital Editions_ folder is created.

```find ~/ -name 'activation.dat' ``` returns no results for activation files in my home folder, let alone the above folder, per what the adobekey.pyw script is looking for.

Calibre log:
```calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Reading List (1, 6, 6) && Comicvine (0, 12, 1)
calibre 3.38.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Reading List (1, 6, 6) && Comicvine (0, 12, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 147.500002215 x 147.000002208
Using calibre Qt style: False
[0.00] Starting up...
[0.04] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
[2.12] main UI initialized...
[2.12] Started up in 2.12 seconds with 2118 books
DeDRM v6.6.1: Trying to decrypt Galactic empires, volume II.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: Galactic empires, volume II.epub is a secure Adobe Adept ePub
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 346, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 446, in adeptkeys
ADEPTError: Could not find ADE activation.dat file.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 403, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Failed to check for calibre update: [Errno 64] Host is down
Failed to check for plugin update: [Errno 64] Host is down
Added Galactic empires, volume II to db in: 0.0
Added 1 books in 0.9 seconds
Worker Launch took: 0.147974967957
```

**Comment by ElleKayEm** [comment]
Can you read the book in ADE 2.0.1 activated with your Adobe ID?

**Comment by ideologysec** [comment]
I spun up a Windows 7 x64 VM and tested the same book with the Calibre plugin v6.6.1 and Calibre 3.38.1. Adobe Digital Editions 2.0.1. That worked fine, so I was able to decrypt the book in question.

Removing all traces including plist files and hidden application directories on Mac did not resolve the issue. A clue for me is that every time I open the app, it asks me to activate. It appears to be storing the key in memory on Mojave, and not writing it out to disk (since using a filesystem monitoring tool did not result in any folders actually being created by Adobe Digital Editions in the Library folder). I suspect this is a new macOS/old software version incompatibility but I'm going to dive into the package more thoroughly to make sure I removed all remnants, and try again.

**Comment by ElleKayEm** [comment]
You should be able to save the Adobe key retrieved by your vm windows calibre DeDRM plugin and import it into your Mac calibre DeDRM plugin.  (Assuming it was the same Adobe ID.)

Definitely sounds like you're correct about ADE not saving the key on Mojave beyond its own immediate use.  So DeDRM is unable to grab it.

**Comment by ideologysec** [comment]
It was; where do I find that key?

**Comment by ElleKayEm** [comment]
Go into the Adobe ebooks section of the DeDRM plugin customization and click the save button.

**Comment by Meatius** [comment]
I had the problem pre Mojave release on High Sierra

Peter Roberts
PRL Executives
Sent from my iPhone

On 23 Jan 2019, at 05:10, Eric <notifications@github.com<mailto:notifications@github.com>> wrote:


I spun up a Windows 7 x64 VM and tested the same book with the Calibre plugin v6.6.1 and Calibre 3.38.1. Adobe Digital Editions 2.0.1. That worked fine, so I was able to decrypt the book in question.

Removing all traces including plist files and hidden application directories on Mac did not resolve the issue. A clue for me is that every time I open the app, it asks me to activate. It appears to be storing the key in memory on Mojave, and not writing it out to disk (since using a filesystem monitoring tool did not result in any folders actually being created by Adobe Digital Editions in the Library folder). I suspect this is a new macOS/old software version incompatibility but I'm going to dive into the package more thoroughly to make sure I removed all remnants, and try again.

**Comment by ElleKayEm** [comment]
Not at all familiar with Macs, but could ADE be blocked from writing to the Library folder somehow?

**Comment by Meatius** [comment]
Shouldn’t be blocked from doing that, other software can write to Library file, although it would normally force a pop up asking if it was ok to write to that folder

Peter Roberts
PRL Executives
Sent from my iPhone

On 23 Jan 2019, at 19:43, ElleKayEm <notifications@github.com<mailto:notifications@github.com>> wrote:


Not at all familiar with Macs, but could ADE be blocked from writing to the Library folder somehow?

**Comment by ideologysec** [comment]
Mojave does implement TCC protections; older apps may not ask but shouldn't be denied. Trying with sudo and granting full disk access in security prefpane would be next on my list.

However, stripping DRM in a VM is likely more sustainable longterm as macOS tends to break older software much more rapidly than Windows does, and ADE 2.0.1 is 32bit IIRC so may stop working entirely in the future.
