### ISSUE TITLE
DRM Caliber tool not working on map (with log and info)

### ISSUE THREAD

**Issue by moss1184** [apprenticeharper/DeDRM_tools#455]
Hi,

So I'm a teacher in a highschool in Brazil and just tried out the DRM removal tool.  I followed the instructions, read the read me files and came to this end.  When I copy my Drm kindle file to caliber it won't open or let me convert.  I downloaded the file through amazon (paid for it there too)  and am transferring it from my older model kindle (about 3-4 years old) to caliber.  I ran caliber in debug mode and tried again and you will find the log below.  Anything anyone can do to point me in the right direction would be really helpful,  I need to be able to de-drm this title and other paid for titles to use it more effectively in class.  Thanks so much.  Here is the log:

2018-03-07 09:37:21.498 calibre-debug[53349:40580176] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2018-03-07 09:37:21.866 Calibre[53370:40580705] deliverNotificationWithTitle()
* Notification delivered.
2018-03-07 09:37:38.888 calibre-debug[53349:40580176] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
calibre Debug log
calibre 1.46  isfrozen: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64')
Python 2.7.5
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Starting up...
Started up in 16.10 seconds with 92 books
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 28, count of files in metadata: 28, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 28
Job: 1 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
DeviceJob: set_books_in_library finished: time= 0.034627199173
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
Worker Launch took: 0.117107868195
Job: 3 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.5.5: Trying to decrypt April Raintree_B06XWMCMC4.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: April Raintree
	Found 4 keys to try after 0.1 seconds
	Crypto Type is: 2
	File is encoded with PID NGstZm8KK7.
	Decrypting. Please wait . . . . done
	Decryption succeeded after 0.1 seconds
	DeDRM v6.5.5: Finished after 0.1 seconds

Added April Raintree to db in: 0.221515893936 seconds

**Comment by moss1184** [comment]
I did enter my serial number.  I just tried removing it and entering it again and this time it still did not work but I get a different message saying cannot convert the book it is locked by DRM this time. anyone with ideas?

**Comment by moss1184** [comment]
Here is the second log with the updated serial number using lowercase letters  2018-03-07 10:42:11.137 calibre-debug[53701:40880144] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2018-03-07 10:42:18.809 Calibre[53728:40885289] deliverNotificationWithTitle()
* Notification delivered.
2018-03-07 10:42:20.702 calibre-debug[53701:40880144] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2018-03-07 10:42:29.538 calibre-debug[53701:40880144] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2018-03-07 10:42:29.719 Calibre[53734:40887559] deliverNotificationWithTitle()
* Notification delivered.
calibre Debug log
calibre 1.46  isfrozen: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64')
Python 2.7.5
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Starting up...
Started up in 9.43 seconds with 92 books
Worker Launch took: 0.108484983444
Job: 2 Get device information started
DeviceJob: 2 Get device information done, calling callback
DeviceJob: 2 Get device information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.1 USBMS: count found in cache: 28, count of files in metadata: 28, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 28
DeviceJob: set_books_in_library finished: time= 0.0246150493622
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Job: 2 Get device information finished
No details available.
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.5.5: Trying to decrypt April Raintree_B06XWMCMC4.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: April Raintree
	Found 2 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v6.5.5: Failed to decrypt with error: No key found in 2 keys tried.
	DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
	No k4Mac kindle-info/rainier/kinf2011 files have been found.
	DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages/calibre/customize/ui.py", line 154, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 618, in run
	  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Added April Raintree to db in: 0.226115942001 seconds
Worker Launch took: 0.101922988892
Job: 4 Convert book 1 of 1 (April Raintree) finished
Convert book 1 of 1 (April Raintree)
	Resolved conversion options
	calibre version: 1.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/g7/5mlgjz1n521dg6cvwvxxhyh80000gn/T/calibre_1.46.0_tmp_ZNIn04/Ay8Mnx.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x108d75b10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x108d782d0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/g7/5mlgjz1n521dg6cvwvxxhyh80000gn/T/calibre_1.46.0_tmp_ZNIn04/bIit2z.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: April Raintree
	InputFormatPlugin: MOBI Input running
	on /var/folders/g7/5mlgjz1n521dg6cvwvxxhyh80000gn/T/calibre_1.46.0_tmp_ZNIn04/jidEPh.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 208, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1040, in run
	  File "site-packages/calibre/customize/conversion.py", line 241, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 43, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 77, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 147, in check_for_drm
	calibre.ebooks.DRMError: April Raintree

**Comment by ElleKayEm** [comment]
The first log shows successful DRM removal.
