### ISSUE TITLE
Calibre cannot convert drm locked book

### ISSUE THREAD

**Issue by Alisonjayne** [apprenticeharper/DeDRM_tools#456]
Hi, very new to this!

I tried to convert a book that I downloaded from Amazon but get the error message that the drm is locked to drm, can you help me?

calibre Debug log
calibre 2.63  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 5) && Kindle Collections (1, 7, 17)
Starting up...
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Started up in 17.82 seconds with 465 books
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
DeDRM v6.5.5: Trying to decrypt Lonely Planet Pocket Berlin (Travel Guide).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Lonely Planet Pocket Berlin (Travel Guide)
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Alison\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Alison\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4130140860' and UserName '416c69736f6e'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Lonely Planet Pocket Berlin (Travel Guide)
Got DSN key from database default_key_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Lonely Planet Pocket Berlin (Travel Guide) to db in: 0.3
Added 1 books in 1.9 seconds
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Worker Launch took: 0.311000108719
Job: 1 Convert book 1 of 1 (Lonely Planet Pocket Berlin (Travel Guide)) finished
Convert book 1 of 1 (Lonely Planet Pocket Berlin (Travel Guide))
	Resolved conversion options
	calibre version: 2.63.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Alison\\AppData\\Local\\Temp\\calibre_p6votl\\jaoxe2.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x034C8D50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x034D0130>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Alison\\AppData\\Local\\Temp\\calibre_p6votl\\vzns_w.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Alison\AppData\Local\Temp\calibre_p6votl\tvithr.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Lonely Planet Pocket Berlin (Travel Guide) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 190, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 31, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1060, in run
	  File "site-packages\calibre\customize\conversion.py", line 241, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 43, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 81, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 144, in check_for_drm
	calibre.ebooks.DRMError: Lonely Planet Pocket Berlin (Travel Guide)

Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'F')], (7L, 2L): [(1L, 'E')]}
Drive letters for USBDevice(vendor_id=0x13d3 product_id=0x3304 bcd=0x1 devid=usb\vid_13d3&pid_3304&rev_0001 devinst=2892)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x035D4C50>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 195, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 867, in open
  File "site-packages\calibre\devices\usbms\device.py", line 277, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to select an E-ink Kindle (not a Fire) for the device and enter its serial number into the plugin customization.

**Comment by chengweiv5** [comment]
I did entered my kindle serial number in the plugin, and restarted calibre and re-add the downloaded azw3 file, but it can not be viewed.

![20180604174233](https://user-images.githubusercontent.com/689798/40910429-b10aeda4-681e-11e8-96e7-87adcbe9e5cf.png)

**Comment by ElleKayEm** [comment]
Make sure you chose the right device when downloading.  Double-check your serial number.  Try copy & paste from the website, removing spaces.

**Comment by chengweiv5** [comment]
Thanks @ElleKayEm , I did resolved my problem, that was I installed and old DeDRM tools, I guess I didn't configured it correctly, when I were trying to installed a new version of it, it doesn't applied.

It still use the old version and said failures, after I removed all about DeDRM files/dirs in `~/.config/calibre/plugins`, and reconfigure the new version again, it works as expected, wow, great!
