### ISSUE TITLE
Calibre identified DRM tool as an invalid tool

### ISSUE THREAD

**Issue by JCHobby** [apprenticeharper/DeDRM_tools#459]
error message:
calibre, version 3.19.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Jill Hobby\\DeDRM\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.19 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Jill Hobby\\DeDRM\\DeDRM_tools_6.5.5.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive into calibre.  Unzip it and look inside the DeDRM calibre plugin folder for the DeDRM_plugin.zip.
