### ISSUE TITLE
De-DRM Key Issue for latest Kindle key on MacOS 10.13

### ISSUE THREAD

**Issue by Kal1234** [apprenticeharper/DeDRM_tools#461]
Hi,
The most recent update to the Kindle app on Mac has rendered my existing key useless for decryption and the calibre plugin can't decrypt or use the latest key. I already tried removing all Kindle files on my Mac and redownloading and re-registering my device. I can read books in the Kindle app.

Here's the important bit of the log during a decryption attempt (local username and book name removed since they aren't needed for this):

DeDRM v6.5.5: Trying to decrypt B00O1E3XJQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/USERNAME/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.5.5: Ultimately failed to decrypt after 14.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 14.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by Kal1234** [comment]
I should point out that going into the preferences to try to get the plugin to find and use the key fails. As above, it finds the key but fails to decrypt it from the look of things.

**Comment by Kal1234** [comment]
Never mind. Somehow I missed the fact that it's the new KFX format that is the issue. I downloaded an older Kindle version and it works now.
