### ISSUE TITLE
unable to convert AZW3 in Calibre on Mac, bought the book on amazon com and sent to my mac via downoald

### ISSUE THREAD

**Issue by lukarw** [apprenticeharper/DeDRM_tools#465]
My mac
high sierra 10.13.3 (17D102
13-inch, Mid 2012)
2.5 GHz Intel Core i5
16 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB

calibre Debug log
calibre 3.7  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 5)
calibre 3.7  embedded-python: True is64bit: True
Darwin-17.4.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.4.0', 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.3', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 5)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
Starting up...
Started up in 2.29 seconds with 50 books
DeDRM v6.5.5: Trying to decrypt Tortoises_ Understanding and caring for your tortoise (Practical Pets Series Book 3).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Tortoises: Understanding and caring for your tortoise (Practical Pets Series Book 3)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.5: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.5: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/lukarw/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'cdfe90ec606d' and UserName 'lukarw'
DeDRM v6.5.5: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Tortoises: Understanding and caring for your tortoise (Practical Pets Series Book 3)
Got DSN key from database default_key_1
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.5.5: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 618, in run
  File "calibre_plugins.dedrm.__init__", line 568, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
If that was downloaded from the website, rhen you need to select an E-ink Kindle (not a Fire) for the device and enter its serial number into the plugin customization.
