### ISSUE TITLE
dDRM6.5.5 does not work

### ISSUE THREAD

**Issue by jeant-22** [apprenticeharper/DeDRM_tools#467]
Good evening, 

I have been intently installing the RDM extension in Caliber to remove the DRMs. Alas, I can not do anything.
My post is under Ubuntu 16.04 and Wine is 3.0
Below the file comes out of the command "calibredb add 2018.epub"

Thank you for your help.
-------------------------------
jeant@rama:~/Documents/My⟫ calibredb add 2018.epub
DeDRM v6.5.5: Trying to decrypt 2018.epub
DeDRM v6.5.5: Verifying zip archive integrity
DeDRM v6.5.5: 2018.epub is a secure Adobe Adept ePub
DeDRM v6.5.5: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.5.5: Running adobekey.py under Wine
DeDRM v6.5.5: Command line: 'WINEPREFIX="/home/jeant/Documents/My" wine python.exe "/home/jeant/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/jeant/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
04002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
0017:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0017:err:mscoree:LoadLibraryShim error reading registry key for installroot
0017:err:mscoree:LoadLibraryShim error reading registry key for installroot
0017:err:mscoree:LoadLibraryShim error reading registry key for installroot
0017:err:mscoree:LoadLibraryShim error reading registry key for installroot
0017:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0017:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
001b:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
001b:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
001b:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0010:fixme:dwmapi:DwmIsCompositionEnabled 0x6dbd1518
001d:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x9e65d0, init_notify 0, handle 0x12df9f0): stub
003f:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
003f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
003f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
003d:fixme:dwmapi:DwmIsCompositionEnabled 0x6d5d3018
0041:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0x9588b8, init_notify 0, handle 0x119fc78): stub
wine: configuration in '/home/jeant/Documents/My' has been updated.
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.5.5: Found and decrypted 0 key files
DeDRM v6.5.5: Exception when getting default Adobe Key after 13.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 350, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.5.5: Ultimately failed to decrypt after 13.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 629, in run
  File "calibre_plugins.dedrm.__init__", line 400, in ePubDecrypt
DeDRMError: DeDRM v6.5.5: Ultimately failed to decrypt after 13.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Ajouter les ids de livre : 569

**Comment by ElleKayEm** [comment]
I know there's been an ongoing issue with some Linux systems where Python can't be found.

See this line in the log:

> wine: cannot find L"C:\windows\system32\python.exe"

There's a discussion about it in issue #53 where a few people seem to have gotten things working.
