### ISSUE TITLE
can't remove DRM from epub

### ISSUE THREAD

**Issue by blank274** [apprenticeharper/DeDRM_tools#471]
Running windows 10, book is an ARC shared with me by the publisher for review purposes.  

calibre Debug log
calibre 3.0 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
calibre 3.0 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Using calibre Qt style: True
Starting up...
Started up in 4.09 seconds with 603 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['6\x96\x1a00\x93\xc1\x1c_\xad\x8e\x83>y\x92\xb8\xb4\x8aO\x99\xd1V\x94\xf4\x9d!\x04\xf3\xff\\\xff\\', 'C:\\Users\\Ginny Blankenship\\Documents\\My Digital Editions\\The Crescent Stone - Matt Mikalatos.epub']
DeDRM v6.5.3: Trying to decrypt The Crescent Stone - Matt Mikalatos.epub
DeDRM v6.5.3: Verifying zip archive integrity
DeDRM v6.5.3: The Crescent Stone - Matt Mikalatos.epub is a secure Adobe Adept ePub
DeDRM v6.5.3: Trying Encryption key default_key
Could not decrypt j0f3bq.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.5.3: Trying Encryption key default_key_2
Could not decrypt j0f3bq.epub. Wrong key
DeDRM v6.5.3: Failed to decrypt with key default_key_2 after 0.1 seconds
DeDRM v6.5.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.5.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 337, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 392, in ePubDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Added The Crescent Stone to db in: 1.5
Added 1 books in 2.7 seconds
Worker Launch took: 0.121999979019

**Comment by ElleKayEm** [comment]
First, does the ARC expire?  Or is it yours to keep?

**Comment by blank274** [comment]
Mine to keep.

**Comment by ElleKayEm** [comment]
Try the solution I suggested here:

https://github.com/apprenticeharper/DeDRM_tools/issues/471#issuecomment-378348375
