### ISSUE TITLE
Kindle Book not deDrm

### ISSUE THREAD

**Issue by davidedodste** [apprenticeharper/DeDRM_tools#484]
calibre Log di debug
calibre 3.11.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 6, 0) && EpubMerge (2, 1, 1) && APNX Generator (1, 1, 0) && Goodreads Sync (1, 11, 0) && Goodreads (1, 1, 13) && Count Pages (1, 8, 0)
calibre 3.11.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.14393-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.14393')
Python 2.7.12+
Windows: ('10', '10.0.14393', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 6, 0) && EpubMerge (2, 1, 1) && APNX Generator (1, 1, 0) && Goodreads Sync (1, 11, 0) && Goodreads (1, 1, 13) && Count Pages (1, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 176.695652174 x 175.846153846
Using calibre Qt style: True
Starting up...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 160, in __init__
  File "site-packages\calibre\gui2\ui.py", line 174, in init_iaction
  File "site-packages\calibre\customize\__init__.py", line 614, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.apnx_generator.apnxaction", line 14, in <module>
ImportError: No module named PyQt4.Qt
EpubMerge: DEBUG: 2018-04-16 17:03:20,581: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:C:\Users\pelagotti\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
DEBUG:    0.0 HttpHelper::__init__: proxy=None
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Failed to check for calibre update: [Errno 11002] getaddrinfo failed
Failed to check for plugin update: [Errno 11002] getaddrinfo failed
DeDRM v6.6.0: Trying to decrypt B01CGCT53M_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\pelagotti\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\pelagotti\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1456855342' and UserName '70656c61676f747469'
DeDRM v6.6.0: Found 1 new key
DeDRM v6.6.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B01CGCT53M EBOK to db in: 4.5
Added 1 books in 5.7 seconds
Started up in 23.59 seconds with 681 books

**Comment by ElleKayEm** [comment]
You need the KFX Input plugin.  (Or download the AZW3 version of the book.)

**Comment by davidedodste** [comment]
It works, thank you.

2018-04-16 20:56 GMT+02:00 ElleKayEm <notifications@github.com>:

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
