### ISSUE TITLE
Cannot dedrm kfx book

### ISSUE THREAD

**Issue by jostyee** [apprenticeharper/DeDRM_tools#486]
I've install DeDRM 6.6.0 along with kfx input plugin 1.3.0, and input the kindle sn to dedrm plugin configurations.

```
calibre Debug log
calibre 3.21  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && Set KFX metadata (from KFX Output) (1, 18, 0) && KFX Output (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
calibre 3.21  embedded-python: True is64bit: True
Darwin-17.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && DeDRM (6, 6, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && Set KFX metadata (from KFX Output) (1, 18, 0) && KFX Output (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.50000166 x 110.50000166
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.47] main UI initialized...
[1.47] Hiding splash screen
[1.51] splash screen hidden
[1.51] Started up in 1.51 seconds with 337 books
Gather KFX-ZIP File Type (from KFX Input) 1.3.0: Importing /Users/yee/Desktop/2001_ A Space Odyssey_B01A6E8EQ6.kfx
KFX Input: Ignoring file not in a recognized directory structure
DeDRM v6.6.0: Trying to decrypt 2001_ A Space Odyssey_B01A6E8EQ6.kfx
Unknown booktype kfx. Passing back to calibre unchanged
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 417, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 97, in get_metadata
Exception: Failed to locate a KFX container with metadata
KFX metadata reader activated for /Users/yee/Desktop/2001_ A Space Odyssey_B01A6E8EQ6.kfx
Added 2001 A Space Odyssey B01A6E8EQ6 to db in: 0.0
Added 1 books in 0.5 seconds

{'bsd_drives': {'main': u'/dev/disk3s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/',
               '/dev/disk1s4': '/private/var/vm',
               '/dev/disk3s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
```

**Comment by jostyee** [comment]
@j-howell Thank you, I drag the kfx directly from my Kindle to Calibre and it's fully drdrmed now.
