### ISSUE TITLE
Still can't open Amazon purchased ebook in Calibre - Please Help

### ISSUE THREAD

**Issue by FarmerJoe8** [apprenticeharper/DeDRM_tools#493]
Here by Calibre debug log:

calibre Debug log
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.16299-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[2.64] main UI initialized...
[2.64] Hiding splash screen
[81.56] splash screen hidden
[81.56] Started up in 81.56 seconds with 108 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['4L\xb3R\xe3D>E\r\x15o\x89\x0c\xfc\xca\xd3I{=\xc2$\x87\xc2\x8eU\xdc\xd9]\xa0\x1f\n\x07', 'C:\\Users\\admin\\Documents\\My Kindle Content\\B078KKQW6D_EBOK\\B078KKQW6D_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B078KKQW6D_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.0: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\admin\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\admin\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1912999555' and UserName '61646d696e'
DeDRM v6.6.0: Found 1 new key
DeDRM v6.6.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ¢ÄÞŒ
Added B078KKQW6D EBOK to db in: 2.0
Added 1 books in 3.2 seconds

**Comment by ElleKayEm** [comment]
For KFX files, you also need the KFX Input plugin.  Or to get the book in an older format, use one of the first 3 methods here:
https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by FarmerJoe8** [comment]
Thank-you, I got it working!
