### ISSUE TITLE
DeDRM Plugin For Calibre Does Not Function Anymore

### ISSUE THREAD

**Issue by robotdna** [apprenticeharper/DeDRM_tools#495]
Hi there,

I downloaded an ebook from Amazon to the PC desktop app. I found the location of the file when opening Calibre, but open attempting to open the book it fails. I have installed the plugin for Calibre. I should mention I do not own a Kindle device, so I cannot enter in any serial number. This is my log file: 

```

calibre Debug log
calibre 3.22.1  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.22.1  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 80.3426688633 x 79.5130434783
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[0.91] main UI initialized...
[0.91] Hiding splash screen
[19.44] splash screen hidden
[19.44] Started up in 19.44 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['=\x92KcxZ\xf9\xb0\x19\x8elVlt\x0c\x19"j\xff\x89\x87u\x1f\x9c\xcd\xdc\x17\x8c\xf4\xb0\x96\\', 'C:\\Users\\bioni\\Desktop\\B00ZOZI3P0_EBOK\\B00ZOZI3P0_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B00ZOZI3P0_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Fluid Mechanics
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\bioni\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\bioni\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Fluid Mechanics to db in: 0.2
Added 1 books in 0.7 seconds
Worker Launch took: 0.0450000762939
Worker Launch took: 0.050999879837
Job: 2 Convert book 1 of 1 (Fluid Mechanics) finished
Convert book 1 of 1 (Fluid Mechanics)
	Conversion options changed from defaults:
	  verbose: 2
	  cover: u'C:\\Users\\bioni\\AppData\\Local\\Temp\\calibre_wg5rv5\\nndaow.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\bioni\\AppData\\Local\\Temp\\calibre_wg5rv5\\bfik2d.opf'
	  output_profile: 'generic_eink'
	Resolved conversion options
	calibre version: 3.22.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\bioni\\AppData\\Local\\Temp\\calibre_wg5rv5\\nndaow.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0562B8F0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0562BAF0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\bioni\\AppData\\Local\\Temp\\calibre_wg5rv5\\bfik2d.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\bioni\AppData\Local\Temp\calibre_wg5rv5\w49b4a.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Fluid Mechanics (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Fluid Mechanics
```
Any assistance would be appreciated. Thanks.

**Comment by ElleKayEm** [comment]
As the log says:
DeDRM v6.6.0: Failed to decrypt with error: Cannot decode library or rented ebooks.
