### ISSUE TITLE
Error on adobe DRM decription from Sony e-Reader.

### ISSUE THREAD

**Issue by toni-moreno** [apprenticeharper/DeDRM_tools#5]
I've followed the guide in https://apprenticealf.wordpress.com/ but this tool is not working to me.

```
calibre Registro de depuración
calibre 2.26  isfrozen: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Job: 1 Obtener información del dispositivo started
DeviceJob: 1 Obtener información del dispositivo done, calling callback
DeviceJob: 1 Obtener información del dispositivo callback returned
Job: 2 Establecer información de la biblioteca started
DeviceJob: 2 Establecer información de la biblioteca done, calling callback
DeviceJob: 2 Establecer información de la biblioteca callback returned
Job: 3 Obtener lista de libros en el dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= PRST1 oncard= None
DEBUG:    0.0 USBMS: dirs are: I:\ 
DEBUG:    0.2 USBMS: scan from root False I:\
Job: 1 Obtener información del dispositivo finished
No hay detalles disponibles.
Job: 2 Establecer información de la biblioteca finished
No hay detalles disponibles.
DEBUG:    1.0 USBMS: count found in cache: 31, count of files in metadata: 31, need_sync: False
DEBUG:    1.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    1.0 SQLite DB Path: I:\Sony_Reader\database\books.db
DEBUG:    1.0 Device Offset: 7200000 ms
DeviceJob: 3 Obtener lista de libros en el dispositivo done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 31
DeviceJob: set_books_in_library finished: time= 0.00999999046326
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Obtener lista de libros en el dispositivo callback returned
Job: 3 Obtener lista de libros en el dispositivo finished
No hay detalles disponibles.
Started up in 21.17 seconds with 1 books
Job: 4 Ver libro en el dispositvo started
DeviceJob: 4 Ver libro en el dispositvo done, calling callback
DeviceJob: 4 Ver libro en el dispositvo callback returned
Worker Launch took: 0.388000011444
Job: 4 Ver libro en el dispositvo finished
No hay detalles disponibles.
Job: 6 Preparar archivos para transferir desde el dispositivo started
DeviceJob: 6 Preparar archivos para transferir desde el dispositivo done, calling callback
DeviceJob: 6 Preparar archivos para transferir desde el dispositivo callback returned
DeDRM v6.3.0: Trying to decrypt El Ã¡ngel perdido.epub
DeDRM v6.3.0: Verifying zip archive integrity
Job: 6 Preparar archivos para transferir desde el dispositivo finished
No hay detalles disponibles.
DeDRM v6.3.0: El Ã¡ngel perdido.epub is a secure Adobe Adept ePub
DeDRM v6.3.0: Trying Encryption key adeptkey
Could not decrypt hmybti.epub. Wrong key
DeDRM v6.3.0: Failed to decrypt with key adeptkey after 1.3 seconds
DeDRM v6.3.0: Looking for new default Adobe Digital Editions Keys after 1.3 seconds
DeDRM v6.3.0: Exception when getting default Adobe Key after 1.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 312, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 377, in adeptkeys
ADEPTError: Adobe Digital Editions not activated
DeDRM v6.3.0: Ultimately failed to decrypt after 1.3 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 155, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 590, in run
  File "calibre_plugins.dedrm.__init__", line 366, in ePubDecrypt
DeDRMError: DeDRM v6.3.0: Ultimately failed to decrypt after 1.3 seconds.
Added El ángel perdido to db in: 1.9
Added 1 books in 4.5 seconds
DeviceJob: set_books_in_library: books to process= 31
DeviceJob: set_books_in_library finished: time= 0.0140001773834
Worker Launch took: 0.449000120163
```

**Comment by ElleKayEm** [comment]
Is your copy of Adobe Digital Editions activated with your Adobe ID?

**Comment by toni-moreno** [comment]
do I need to install it , if I'm removing the DRM of this e-book ? I don't have the adobe id from people who bought the ebook.

**Comment by ElleKayEm** [comment]
That's how the plug-in gets the key to unlock the book.  You need to have Adobe Digital Editions installed on the same machine as calibre and registered with the correct Adobe ID for the book you're trying to remove the DRM from.

**Comment by toni-moreno** [comment]
In this case ,  have I  to pay for the book first in order to remove the DRM ? It has no sense to me isn't it ?

**Comment by magu** [comment]
You are only legally allowed to remove DRM from books you own.

**Comment by ElleKayEm** [comment]
Yes, that's what the tools are intended for.  Removing DRM from your own books for your own personal use.  For backing up.  For using on a preferred device.

**Comment by Tarpal** [comment]
I wonder whether one even is allowed to remove DRM from purchased DRM
enabled books. Ownership has slipped towards licensing it seems.

If you are really annoyed by DRM limitations (e.g. you bought both the
printed and the ebook and still can't get around) try "Copistar". Yep, paid
software that can help you out. http://www.copistar.com/
