### ISSUE TITLE
calibre 2.45.0 invalidPlugin

### ISSUE THREAD

**Issue by sea200k** [apprenticeharper/DeDRM_tools#50]
calibre, version 2.45.0
: <b>InvalidPlugin</b>:The plugin in u'C:/Users/lei/Downloads/DeDRM_tools_6.3.4a.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.45  isfrozen: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 388, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 53, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 188, in load
  File "site-packages\calibre\customize\zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'C:/Users/lei/Downloads/DeDRM_tools_6.3.4a.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
That zip file contains more than just the calibre plugin.  Unzip it, and you'll find the one you need to install inside the calibre plugin folder.

**Comment by sea200k** [comment]
Thank you very much. I made it.
