### ISSUE TITLE
DRM still remains after loading into calibre

### ISSUE THREAD

**Issue by QuietusSleeps** [apprenticeharper/DeDRM_tools#507]
I'm using kindle for PC version 1.17 as suggested..  
here's the log:

calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 80.0 x 80.0
physicalDpi: 93.9653179191 x 94.2680412371
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.70] main UI initialized...
[1.70] Hiding splash screen
[4.86] splash screen hidden
[4.88] Started up in 4.88 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['m.\x08\x94\x9dN\x0fYa\x13j\xd5ay\x97;{\xd2\xbd&\xad\x98\xf1d\xe5\x1f:>\xf6\xc8\x85i', 'C:\\Users\\Taen\\Documents\\My Kindle Content\\B07C3HWKNM_EBOK\\B07C3HWKNM_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B07C3HWKNM_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ディアプラス 2018年4月号［期間限定］
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Taen\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Taen\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '654271963' and UserName '5461656e'
DeDRM v6.6.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ディアプラス 2018年4月号［期間限定］
Got DSN key from database default_key_1
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.6.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added ディアプラス 2018年4月号［期間限定］ to db in: 0.7
Added 1 books in 2.5 seconds

I can attach the book file if necessary, its pretty large..

**Comment by ElleKayEm** [comment]
I think it's picking up the key from an earlier installation.  Try following these instructions for completely uninstalling and re-installing Kindle for PC:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by QuietusSleeps** [comment]
Hi there, 
I did as you suggested, and followed the instructions precisely, but I have the same issue.

calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.16299-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.16299')
Python 2.7.12+
Windows: ('10', '10.0.16299', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Not controlling automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 80.0 x 80.0
physicalDpi: 93.9653179191 x 94.2680412371
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.17] main UI initialized...
[1.17] Hiding splash screen
[4.11] splash screen hidden
[4.11] Started up in 4.11 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb3"R\xffC\x91Dwq{\xcc\xba\x93\x82"=\xf6\t\x84\x01"|\x18\x01r\xbbB\x04\xbc\x7fI\x97', 'C:\\Users\\Taen\\Documents\\My Kindle Content\\B07C3HDG64_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B07C3HDG64_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2018年5月号
Got DSN key from database default_key
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Taen\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Taen\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '654271963' and UserName '5461656e'
DeDRM v6.6.0: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: GUSH 2018年5月号
Got DSN key from database default_key_1
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v6.6.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added GUSH 2018年5月号 to db in: 0.9
Added 1 books in 2.5 seconds
Worker Launch took: 0.124000072479

I deregistered, uninstalled, removed all local app data and content, reinstalled 1.17, downloaded a new file, but there is no difference.

**Comment by ElleKayEm** [comment]
Well, I'm stumped.  The books were downloaded with Kindle for PC which is on the same PC and user as calibre/DeDRM, right?

The only other thing I can think to try is using 64-bit calibre.  I don't think that's the problem here, but it can't hurt if these are large files.

**Comment by QuietusSleeps** [comment]
Yeah, it’s all on the one pc. I could try that, sure. It’s so frustrating!

**Comment by apprenticeharper** [comment]
If it's a very big book, it may be running out of memory (and interpreting that as wrong key). Try importing a smaller book and seeing if that works. Or just jump straight to using 64-bit calibre and see if that does the trick.
