### ISSUE TITLE
Cant install DeDRM_tools latest release for kfx support

### ISSUE THREAD

**Issue by CreativeCredent** [apprenticeharper/DeDRM_tools#509]
i get this error when trying to install it calibre, version 3.23.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\brent\\Desktop\\DeDRM.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 3, 0) && Package KFX File Type (from KFX Input) (1, 3, 0) && Goodreads (1, 1, 14) && KFX metadata reader (from KFX Input) (1, 3, 0) && KFX Input (1, 3, 0) && Library Codes (1, 0, 31)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 461, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\brent\\Desktop\\DeDRM.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Just in case someone with the same error comes along:  You need to unzip the archive, look in the DeDRM calibre plugin folder, and load DeDRM_plugin.zip into calibre.

If you're all set, you can close the issue.
