### ISSUE TITLE
Error on fileopen deDRM

### ISSUE THREAD

**Issue by Antarctic74** [apprenticeharper/DeDRM_tools#515]
Hi, can anyone help with this issue? it's a openfile DRM on a PDF file:

calibre Log di debug
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.238993711 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[1.38] main UI initialized...
[1.38] Hiding splash screen
[4.56] splash screen hidden
[4.58] Started up in 4.58 seconds with 1 books
stdout+stderr from file dialog helper: ['', 'Qt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\nQt: Untested Windows version 10.0 detected!\r\n']
piped data from file dialog helper: ["r\xb0\x9b6\x92\xf57K\xab\xdb\x8c\xe5\xc4\xf2F\x8f\xca\xa7\x01\xc0W\t\xc0Y\xaaA[f\x02'\xa8X", 'C:\\Users\\xxxxx\\Downloads\\xxxxxxx.pdf']
DeDRM v6.6.0: Trying to decrypt xxxxxxxxx.pdf
DeDRM v6.6.0: xxxxxxxx.pdf is a PDF ebook
DeDRM v6.6.0: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
Found 1 keys
DeDRM v6.6.0: Trying a new default key
DeDRM v6.6.0: Exception when decrypting after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 474, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1485, in initialize
PDFEncryptionError: Unknown filter: param={'DUID': 'xxxxx.xxx.5afd2940175e77.58821786', 'BUILD': '907', 'SVID': 'xxxxx.xxx', 'V': 2, 'VEID': '9.0', 'Filter': /FOPN#5ffoweb, 'Length': 128, 'INFO': 'HgR50GSLkqXShHKestPel1/ocyoslBDzOQxbbo1igGDzJg3a0iTM9nsUYTCH8SDI+iThsmBnq8p1Avl7/T8csX+A52oYDeVaK8Etr2C61PI3zscTE1SGmSY7ePtDzNnmVrUWPhu8NGVdt0jud66y0YwJpdG0AD6E0wqvw7sZe83+gJz+Sz1glzPY29OhZmLCQaTjDhtYRjh2oA759PQWm0BG8m7LEesHb3BxjIwWTnBVn2DNjNUBy5AIRjfodrsNBx/ly+lzkHwAiolduv7wGXVwNWth1mpWEAKV3P6kZ8NIwkss7iwNcxd8IGqf+Xr0OQVb9qSfg8Bz+4lzHhqHxCFemCvrY4FDzJiOFcqAJ+WqSP4DjeyTIRYUWSxlB3NcLtaXabVHqTCg8+Gsq/GURbAnguCzNDcP1zf9dT6QSyFNsfHFCuBdaAPs6VN1GYQW6ohnbONfKW2ovM2zF44YJqwE8IFsHkrZOmeEVe4E7ps5sF8Fi1F7V7+GCtQgSr0KjZIK8gq7lVXE4sLa6zARDDbqGsMEB7bGFYrwQ4c86D9xGuY6Xm9aQlVY+x42LovQRNUp6WIlMK9mOwwj9B6SGBPxOWt48YbR5FfcffrEEGQcxAMlM6i3zuzqfES6lIBz1IIDU78Dd/LwoxYFihAJK0uS6sfYE/a8UAgBZxhizdEkRVjJGmq3ULqQS6v2OKKzTdtlJj52Zg=='}
DeDRM v6.6.0: Failed to decrypt with new default key after 0.0 seconds
DeDRM v6.6.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 627, in run
  File "calibre_plugins.dedrm.__init__", line 502, in PDFDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'FOPN_foweb' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added xxxxxxxx to db in: 0.0
Added 1 books in 0.7 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x06519550>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x065194F0>> ignored

**Comment by ElleKayEm** [comment]
I think issue #104 might have a solution.
