### ISSUE TITLE
what  I can do ,I used mac system  with python3.6

### ISSUE THREAD

**Issue by ambleryang** [apprenticeharper/DeDRM_tools#521]
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' -s '905A220140370QD3' '/Users/yanggz/Desktop/JavaScript忍者秘籍（第2版）.azw3' '/Users/yanggz/Desktop/' > '/Users/yanggz/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Applications/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/Applications/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/yanggz/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/yanggz/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.5
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/yanggz/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '2920350d95b4' and UserName 'yanggz'
Saved a key to /Users/yanggz/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i

**Comment by ambleryang** [comment]
it is success.  must install python2 with some lib.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
