### ISSUE TITLE
Issues Removing DRM from Kindle Ebook

### ISSUE THREAD

**Issue by ClutchHutch** [apprenticeharper/DeDRM_tools#523]
I cannot get the DRM removed from my kindle ebook.
I have re ran in debug mode and included the log below. Not sure what the issue is. Running on Windows 10. I bought the book from Amazon and opened it with Kindle for PC.

calibre Debug log
calibre 3.24.2  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
calibre 3.24.2  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.356521739 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.75] main UI initialized...
[1.75] Hiding splash screen
[50.05] splash screen hidden
[50.05] Started up in 50.05 seconds with 0 books
stdout+stderr from file dialog helper: ['', 'Qt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\nQt: Untested Windows version 10.0 detected!\r\nlog4cplus:ERROR No appenders could be found for logger (AdSyncNamespace).\r\nlog4cplus:ERROR Please initialize the log4cplus system properly.\r\n']
piped data from file dialog helper: ['\x14\x82L\xba\x8d\xd6\x0c\xda{\x82*\xaaZ\x1e\xf5>^\\w\xfaZ\x99\xbd\x1e\x1c\x99\xc2\x18\x95$\x18l', 'E:\\fluids\\B01AKSZ9Y8_EBOK.azw']
DeDRM v6.6.0: Trying to decrypt B01AKSZ9Y8_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Engineering Fluid Mechanics, 11th Edition
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.0: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.0: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Isaac\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 620, in run
  File "calibre_plugins.dedrm.__init__", line 570, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.0: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Engineering Fluid Mechanics, 11th Edition to db in: 1.9
Added 1 books in 2.9 seconds

**Comment by ElleKayEm** [comment]
Calibre with DeDRM needs to be on the same computer and Windows user as Kindle for PC where the book was downloaded.
