### ISSUE TITLE
wine: cannot find L”C:\\windows\\system32\\python.exe”

### ISSUE THREAD

**Issue by atipico** [apprenticeharper/DeDRM_tools#53]
Wine 1.9.0 Installed following steps from http://wiki.winehq.org/Ubuntu

“ActivePython-2.7.8.10-win64-x64.msi” installed from http://www.activestate.com/activepython/downloads/

This time, ActivePython installer was able to create ~/.wine/drive_c/windows/syswow64/python.exe

I don’t know if this is a problem related to Calibre or the DeDRM script, but, as we can see in the debug below, python.exe is called from the wrong path:
wine: cannot find L”C:\\windows\\system32\\python.exe”
As I said above, the 64bit version installs the "python.exe" file under: "~/.wine/drive_c/windows/syswow64/" folder. 

Don’t know what I can do any further.

Would be a way to define the correct path to python.exe inside the DeDRM script?

- - -

rgr@atipico64: calibre-debug -g
calibre 1.25 isfrozen: False is64bit: True
Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty Linux (’64bit’, ‘ELF’)
(‘Linux’, ‘3.13.0-74-generic’, ‘#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015’)
Python 2.7.6
Linux: (‘Ubuntu’, ‘14.04’, ‘trusty’)
Starting up…
DEBUG: 0.0 obok::utilities.py – loading translations
DEBUG: 0.0 obok::dialogs.py – loading translations
DEBUG: 0.0 obok::config.py – loading translations
DEBUG: 0.0 using xml.etree for xml parsing
DEBUG: 0.0 obok::action_err.py – loading translations
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Started up in 1.37 seconds with 11 books
Worker Launch took: 0.0650780200958
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
DeDRM v6.3.4: Trying to decrypt B00BMWEFR4_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: The Boron Letters
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.3.4: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.3.4: Running kindlekey.py under Wine
DeDRM v6.3.4: Command line: “WINEPREFIX=”/home/rgr” wine python.exe “/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py” “/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir””
wine: cannot find L”C:\\windows\\system32\\python.exe”
DeDRM v6.3.4: Found and decrypted 0 key files
DeDRM v6.3.4: Ultimately failed to decrypt after 1.1 seconds.
Read the FAQs at Alf’s blog: https://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File “/usr/lib/calibre/calibre/customize/ui.py”, line 154, in _run_filetype_plugins
nfp = plugin.run(path_to_file)
File “calibre_plugins.dedrm.__init__”, line 590, in run
File “calibre_plugins.dedrm.__init__”, line 540, in KindleMobiDecrypt
DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 1.1 seconds

Added The Boron Letters to db in: 1.74273991585 seconds

**Comment by atipico** [comment]
Changing the 2 occurrences of "python.exe" in the file "wineutils.py" by the correct path "C:\\Python27\\python.exe" I was able to overcome the error "wine: cannot find L”C:\\windows\\system32\\python.exe”". However I continue to receive this error:

rgr@atipico64: calibre-debug -g
calibre 1.25  isfrozen: False is64bit: True
Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty Linux ('64bit', 'ELF')
('Linux', '3.13.0-74-generic', '#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015')
Python 2.7.6
Linux: ('Ubuntu', '14.04', 'trusty')
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 using xml.etree for xml parsing
DEBUG:    0.0 obok::action_err.py - loading translations
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Started up in 1.37 seconds with 11 books
Worker Launch took: 0.10120010376
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.3.4: Trying to decrypt B00BMWEFR4_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright © 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: The Boron Letters
	Found 0 keys to try after 0.4 seconds
	Crypto Type is: 2
	DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.3.4: Looking for new default Kindle Key after 0.4 seconds
	DeDRM v6.3.4: Exception when getting default Kindle Key after 0.4 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 511, in KindleMobiDecrypt
	  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 175, in load_module
	    import_name), 'exec', dont_inherit=True)
	  File "calibre_plugins.dedrm.wineutils", line 31
	    cmdline = u"WINEPREFIX=\"{2}\" wine "C:\\Python27\\python.exe" \"{0}\" \"{1}\"".format(scriptpath,outdirpath,wineprefix)
	                                         ^
	SyntaxError: invalid syntax
	DeDRM v6.3.4: Ultimately failed to decrypt after 0.4 seconds.
	Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
	    nfp = plugin.run(path_to_file)
	  File "calibre_plugins.dedrm.__init__", line 590, in run
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.4 seconds

Added The Boron Letters to db in: 1.9603509903 seconds

**Comment by apprenticeharper** [comment]
That looks like it would work, except that you have not escaped the quotation marks around the path to python.exe, or the back slashes in the path. Try changing line 31 from

cmdline = u"WINEPREFIX=\"{2}\" wine "C:\Python27\python.exe" \"{0}\" \"{1}\"".format(scriptpath,outdirpath,wineprefix)

to

cmdline = u"WINEPREFIX=\"{2}\" wine \"C:\\Python27\\python.exe\" \"{0}\" \"{1}\"".format(scriptpath,outdirpath,wineprefix)

**Comment by atipico** [comment]
Python.exe appears in line 31 and 33. But I tried the suggestion you made on 31 only and both lines. This is what I got respectively:

rgr@atipico64: calibre-debug -g
calibre 1.25  isfrozen: False is64bit: True
Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty Linux ('64bit', 'ELF')
('Linux', '3.13.0-74-generic', '#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015')
Python 2.7.6
Linux: ('Ubuntu', '14.04', 'trusty')
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 using xml.etree for xml parsing
DEBUG:    0.0 obok::action_err.py - loading translations
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Started up in 1.42 seconds with 11 books
Worker Launch took: 0.0667860507965
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.3.4: Trying to decrypt B00BMWEFR4_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright © 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: The Boron Letters
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.3.4: Looking for new default Kindle Key after 0.0 seconds
	DeDRM v6.3.4: Exception when getting default Kindle Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 511, in KindleMobiDecrypt
	  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 175, in load_module
	    import_name), 'exec', dont_inherit=True)
	  File "calibre_plugins.dedrm.wineutils", line 33
	    cmdline = u"wine "C:\\Python27\\python.exe" \"{0}\" \"{1}\"".format(scriptpath,outdirpath)
	                      ^
	SyntaxError: invalid syntax
	DeDRM v6.3.4: Ultimately failed to decrypt after 0.0 seconds.
	Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
	    nfp = plugin.run(path_to_file)
	  File "calibre_plugins.dedrm.__init__", line 590, in run
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.0 seconds

Added The Boron Letters to db in: 1.99438691139 seconds




AND



rgr@atipico64: calibre-debug -g
calibre 1.25  isfrozen: False is64bit: True
Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty Linux ('64bit', 'ELF')
('Linux', '3.13.0-74-generic', '#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015')
Python 2.7.6
Linux: ('Ubuntu', '14.04', 'trusty')
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 using xml.etree for xml parsing
DEBUG:    0.0 obok::action_err.py - loading translations
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Started up in 1.38 seconds with 11 books
Worker Launch took: 0.0889258384705
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.3.4: Trying to decrypt B00BMWEFR4_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright © 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: The Boron Letters
	Found 0 keys to try after 0.2 seconds
	Crypto Type is: 2
	DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.3.4: Looking for new default Kindle Key after 0.2 seconds
	DeDRM v6.3.4: Running kindlekey.py under Wine
	DeDRM v6.3.4: Command line: “WINEPREFIX="/var/www/teste.com" wine "C:\Python27\python.exe" "/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
	wine: cannot find 'C:\Python27\python.exe'
	DeDRM v6.3.4: Found and decrypted 0 key files
	DeDRM v6.3.4: Ultimately failed to decrypt after 0.7 seconds.
	Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
	    nfp = plugin.run(path_to_file)
	  File "calibre_plugins.dedrm.__init__", line 590, in run
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 0.7 seconds

Added The Boron Letters to db in: 2.197026968 seconds

**Comment by apprenticeharper** [comment]
The second one had the syntax right. The question now is, where is python installed on your wine system? Find where the python executable is on your wine installation, and use that full path instead of C:\Python27\python.exe. (I had thought some people had said it was installed into C:\Python27\python.exe, but apparently not.

**Comment by atipico** [comment]
I'm installing "ActivePython-2.7.8.10-win64-x64.msi" via Wine/Linux. As far as I could notice, the installer writes two Python.exe's: 
rgr@atipico64: sudo find ~/ -name "python.exe"
/home/rgr/.wine/drive_c/Python27/python.exe
/home/rgr/.wine/drive_c/windows/syswow64/python.exe

**Comment by atipico** [comment]
So, I tried:

31 cmdline = u"WINEPREFIX=\"{2}\" wine \"C:\windows/syswow64/python.exe\" \"{0}\" \"{1}\"".format(scriptpath,outdirpath,wineprefix)

and

33 cmdline = u"wine \"C:\\windows/syswow64/python.exe\" \"{0}\" \"{1}\"".format(scriptpath,outdirpath)

However:

rgr@atipico64: calibre-debug -g
calibre 1.25  isfrozen: False is64bit: True
Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty Linux ('64bit', 'ELF')
('Linux', '3.13.0-74-generic', '#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015')
Python 2.7.6
Linux: ('Ubuntu', '14.04', 'trusty')
Starting up...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 using xml.etree for xml parsing
DEBUG:    0.0 obok::action_err.py - loading translations
Unable to open ~/.mtpz-data for reading, MTPZ disabled.Started up in 1.41 seconds with 11 books
Worker Launch took: 0.0849211215973
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.3.4: Trying to decrypt B00BMWEFR4_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.41.
	Copyright © 2008-2012 The Dark Reverser et al.
	MOBI header version 8, header length 264
	Extra Data Flags: 3
	Decrypting Kindle Format 8 ebook: The Boron Letters
	Found 0 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v6.3.4: Failed to decrypt with error: No key found in 0 keys tried.
	DeDRM v6.3.4: Looking for new default Kindle Key after 0.1 seconds
	DeDRM v6.3.4: Running kindlekey.py under Wine
	DeDRM v6.3.4: Command line: “WINEPREFIX="/home/rgr" wine "C:\windows/syswow64/python.exe" "/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/rgr/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
	wine: cannot find L"C:\\windows\\syswow64\\python.exe"
	DeDRM v6.3.4: Found and decrypted 0 key files
	DeDRM v6.3.4: Ultimately failed to decrypt after 1.2 seconds.
	Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
	    nfp = plugin.run(path_to_file)
	  File "calibre_plugins.dedrm.__init__", line 590, in run
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.3.4: Ultimately failed to decrypt after 1.2 seconds

Added The Boron Letters to db in: 2.37090492249 seconds

**Comment by atipico** [comment]
But the files are there!

![screenshot - 07-01-2016 - 10 39 29](https://cloud.githubusercontent.com/assets/349200/12170769/1355818a-b52b-11e5-88e3-1cf3fbd2a69d.png)
![screenshot - 07-01-2016 - 10 40 01](https://cloud.githubusercontent.com/assets/349200/12170770/1358de20-b52b-11e5-981a-ff73629ba0d8.png)

**Comment by apprenticeharper** [comment]
I don't know what's going wrong then. Most mysterious.

**Comment by ckuethe** [comment]
"C:\windows/syswow64/python.exe"

Not sure if it matters, but you have different slashes in there. I'm not even sure that's supposed to work, if this is to be believed... https://forum.winehq.org/viewtopic.php?t=10478

Maybe you can use all forward slashes and WINE can translate them, or you can go through and make sure that you're only using properly escaped backslashes.

**Comment by HeadFullOfWool** [comment]
I'm experiencing the same issue after a Fedora 23 system update upgraded my Wine from 1.8.x to 1.9.x (currently 1.9.4, but also the previous release).
My original install was working fine on this system, then suddenly broke.  I recall seeing the Wine update as part of a bunch of updates and I suspected it was this that may have triggered the current failure.
I first tried a downgrade of wine using DNF.  This took me down to 1.7, but it made no difference.

I then came across this post and have examined my version of wineutils.py, but mine indicates C:\Python27\python.exe, _despite_ the calibre-debug log indicating that it is trying to locate it in C:\Windows\System32\ for some reason.

My "**wineutils.py**":
![image](https://cloud.githubusercontent.com/assets/17648258/13532242/55388e5c-e222-11e5-90e6-7afa0950c05a.png)

My **calibre-debug** output:
`[alec@quietmonster ~]$ calibre-debug -g
calibre 2.52  embedded-python: True is64bit: True
Linux-4.4.3-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three Linux ('64bit', 'ELF')
('Linux', '4.4.3-300.fc23.x86_64', '#1 SMP Fri Feb 26 18:45:40 UTC 2016')
Python 2.7.9
Linux: ('Fedora', '23', 'Twenty Three')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 1.30 seconds with 318 books
DeDRM v6.3.6: Trying to decrypt B00XPCTTT8_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Genesis (Extinction Point Series Book 4)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.3.6: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.3.6: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.3.6: Running kindlekey.py under Wine
DeDRM v6.3.6: Command line: “WINEPREFIX="/home/alec" wine python.exe "/home/alec/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/alec/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
fixme:winediag:start_process Wine Staging 1.9.4 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.3.6: Found and decrypted 0 key files
DeDRM v6.3.6: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 597, in run
  File "calibre_plugins.dedrm.__init__", line 547, in KindleMobiDecrypt
DeDRMError: DeDRM v6.3.6: Ultimately failed to decrypt after 0.1 seconds
Added Genesis (Extinction Point Series Book 4) to db in: 2.4
Added 1 books in 2.8 seconds
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
`

Fortunately I have an older PC (Ubuntu MATE 15.10, Wine 1.6) that still lets me get my book copied decrypted to my Kobo, but it frustrating having my main PC not able to do what it used to.

I'm happy to follow suggested guidance on what to try - for example, where else might the scripts be trying to determine that path if not the wineutils.py file as indicated above?

**Comment by apprenticeharper** [comment]
I am going to set up a new Ubuntu VM to try to work out a solution to this problem. If anyone has any ideas, feel free to comment here.

**Comment by akadaedalus** [comment]
This stymied me too.  However, I believe I figured out the problem.  When the wine prefix text box was empty in the plugin GUI, it gave me this:

```
DeDRM v6.4.0: Command line: “WINEPREFIX="/home/apalmer/.wine/drive_c" wine python.exe "/home/apalmer/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/apalmer/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
...
wine: cannot find L"C:\\windows\\system32\\python.exe"
```

That's not the right WINEPREFIX.  drive_c is a virtual C: in wine, but there are registry files too that cannot be accessed from there.  I put "~/.wine" in the text field and it worked.  In the case of the OP, the wine prefix of "/home/rgr" is incorrect, it should be "/home/rgr/.wine" based on the python executable location.

**Comment by HeadFullOfWool** [comment]
Akadadalus - you are a STAR!!
Your detective work and suggestion has also fixed my install as well.  What a relief!
Thank you.

**Comment by goingalong** [comment]
akadaedalus any chance of a fuller explanation of the solution. I am running DeDRM using say:

`calibredb add mybook.epub`

which gives me the error
```

DeDRM v6.4.0: Running adobekey.py under Wine
DeDRM v6.4.0: Command line: “WINEPREFIX="/home/trevor/My Digital Editions" wine python.exe "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
wine: cannot find L"C:\\windows\\system32\\python.exe"
```

If instead I select the DeDRM Plugin in Calibre and choose "Customise plug-in" then "Adobe Digital Editions Keys" I get a dialogue with a box titled WINEPREFIX. Is this the text field you are referring to, and what should happen after I paste ~/.wine and close the dialogue?

Grateful for any detailed help here as all the responses I have found on other forums assume lots of prior knowledge.

**Comment by akadaedalus** [comment]
Yes, you are most of the way there.  Assuming you have ~/.wine as your wine prefix, you enter that in the dialog box.  Don't close it though, you need to click the green plus + button.  It will use the WINEPREFIX to look for your ADE installation, and if it's successful it will prompt you to name the key and put it in the list of keys in the same dialog.

I don't use the command line very often, but presumably if you complete the configuration it will automatically use the key.  I just tested this on my system, it worked fine.  The key is apparently stored in ~/.config/calibre/plugins/dedrm.json

**Comment by goingalong** [comment]
Thanks for the input. I put "~/trevor/.wine" into the box after setting Calibre into debug mode. After using the green plus key I get an error box saying The default encryption key for Adobe Digital editions could not be found. 

I also changed the ADE field in the .json file to ensure it pointed to the same place - same result.

Tried with ADE running and without.

The Calibre log is :

```
calibre Debug log
calibre 2.33  isfrozen: False is64bit: False
Linux-4.2.0-34-generic-i686-with-Ubuntu-15.10-wily Linux ('32bit', 'ELF')
('Linux', '4.2.0-34-generic', '#39-Ubuntu SMP Thu Mar 10 22:11:49 UTC 2016')
Python 2.7.10
Linux: ('Ubuntu', '15.10', 'wily')
Successfully initialized third party plugins: DeDRM
Starting up...
Loaded cached store plugin for: Amazon CA Kindle at version: 3
Loaded cached store plugin for: Koobe at version: 5
Loaded cached store plugin for: Amazon DE Kindle at version: 11
Loaded cached store plugin for: Amazon Kindle at version: 11
Loaded cached store plugin for: Cdp.pl at version: 8
Loaded cached store plugin for: Amazon FR Kindle at version: 11
Loaded cached store plugin for: Virtualo at version: 6
Loaded cached store plugin for: Amazon ES Kindle at version: 11
Loaded cached store plugin for: Ebookpoint at version: 6
Loaded cached store plugin for: Publio at version: 5
Loaded cached store plugin for: Archive.org at version: 2
Loaded cached store plugin for: Amazon UK Kindle at version: 11
Loaded cached store plugin for: Amazon IT Kindle at version: 11
wine: cannot find L"C:\\windows\\system32\\python.exe"
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 701, in __init__
IndexError: list index out of range
Started up in 29.14 seconds with 2 books
Loaded cached store plugin for: Amazon CA Kindle at version: 3
Loaded cached store plugin for: Koobe at version: 5
Loaded cached store plugin for: Amazon DE Kindle at version: 11
Loaded cached store plugin for: Amazon Kindle at version: 11
Loaded cached store plugin for: Cdp.pl at version: 8
Loaded cached store plugin for: Amazon FR Kindle at version: 11
Loaded cached store plugin for: Virtualo at version: 6
Loaded cached store plugin for: Amazon ES Kindle at version: 11
Loaded cached store plugin for: Ebookpoint at version: 6
Loaded cached store plugin for: Publio at version: 5
Loaded cached store plugin for: Archive.org at version: 2
Loaded cached store plugin for: Amazon UK Kindle at version: 11
Loaded cached store plugin for: Amazon IT Kindle at version: 11
DeDRM v6.4.0: Running adobekey.py under Wine
DeDRM v6.4.0: Command line: “wine python.exe "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
DeDRM v6.4.0: Found and decrypted 0 key files
```
This has the same python not found message but also I note that it makes no mention of ADE even though ""adobewineprefix": "\"~/trevor/.wine\"", " is present in the .json file.

**Comment by akadaedalus** [comment]
The command line looks okay now, so I'm guessing you haven't installed ActivePython and PyCrypto in wine per the instructions included with the plugin.

**Comment by goingalong** [comment]
Sorry, but beginning to feel stupid now. I just installed using  Calibre preferences "Load plug-in from file" and don't remember seeing anything like that. Looking into the zip container I can't see anything there or in the readme. I can see lots of Python scripts though.

So my apologies but I would really appreciate another pointer.

**Comment by akadaedalus** [comment]
Took me a while to find it myself, and I've installed it a few times before.  DeDRM_calibre_plugin/DeDRM_plugin_ReadMe.txt.  Good luck.

**Comment by goingalong** [comment]
For other readers, the install info for wine is in the ReadMe.txt file but is below the section titled "Credits" so when you get to that section don't stop, keep going down.

Having been through all steps and then using the green plus button in Calibre to establish an ADE key I get an error box " the default encryption key for adobe digital editions could not be found". This appears whether or not I set the WINEPREFIX to blank or ~/trevor/.wine. In the Calibre log I get:

```
DeDRM v6.4.0: Command line: “wine python.exe "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
DeDRM v6.4.0: Found and decrypted 0 key files
```

If I use the command line "calibredb add Dune.epub" it seems to be telling me that my ADE is not activated (though it is). Is this something to do with the fact than Calibre is running native under Linux and ADE is running under wine? The command line output is:

```
DeDRM v6.4.0: Trying to decrypt Dune.epub
DeDRM v6.4.0: Verifying zip archive integrity
DeDRM v6.4.0: Dune.epub is a secure Adobe Adept ePub
DeDRM v6.4.0: Looking for new default Adobe Digital Editions Keys after 0.9 seconds
DeDRM v6.4.0: Running adobekey.py under Wine
DeDRM v6.4.0: Command line: “wine python.exe "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"”
adobekey.py v6.0
Copyright © 2009-2013 i?cabbages and Apprentice Alf
Traceback (most recent call last):
  File "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 602, in <module>
    sys.exit(cli_main())
  File "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 525, in cli_main
    keys = adeptkeys()
  File "/home/trevor/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py", line 377, in adeptkeys
    raise ADEPTError("Adobe Digital Editions not activated")
__main__.ADEPTError: Adobe Digital Editions not activated
DeDRM v6.4.0: Found and decrypted 0 key files
DeDRM v6.4.0: Exception when getting default Adobe Key after 3.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 332, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.4.0: Ultimately failed to decrypt after 3.4 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 155, in _run_filetype_plugins
    nfp = plugin.run(path_to_file)
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 380, in ePubDecrypt
DeDRMError: DeDRM v6.4.0: Ultimately failed to decrypt after 3.4 seconds.
Backing up metadata
Added book ids: 14
Notifying calibre of the change

```
Clearly it can find the book inside ADE!

**Comment by apprenticeharper** [comment]
@goingalong: Since python is running correctly under wine for you,this is not the same issue. Please start a separate issue for your problem.

(And yes, it looks like ADE appears to be unregistered. Are you sure you've registered it with your Adobe ID?)

**Comment by willbeaufoy** [comment]
Just to say I had the same problem and akadaedalus's solution worked. The plugin wasn't finding the wine python unless I put in the /home/username/.wine prefix

**Comment by apprenticeharper** [comment]
Thanks, willbeaufoy.

**Comment by A070B24C** [comment]
Experienced same issue today:
```
$ pwd
/home/johndoe
$ wine Downloads/tcmd912x32.exe
wine: cannot find L"unix\\home\\johndoe\\Downloads\\tcmd912x32.exe"
```
Looked over the settings in winecfg and after a close watch at the error message "[..] cannot find L[..]" I realized that the entry for the root directory mapped to drive "L" is missing. I added another "drive" with the letter "L" and - voilà - now everything is working fine.

**Comment by apprenticeharper** [comment]
I'm sorry I just haven't had time to look at this. I'd welcome pull requests.

**Comment by jeant-22** [comment]
Hello,
On the ActiveState site, I found only ActivePython-2.7.17.2717-win64-x64 ... Now, it seems to me that on my computer, Wine 3.0 is in 32 bits.
This version of Python refused to settle in my Wine.
I'm not a beginner, but I'm not at all comfortable with the ed Wine installations and setup. Sorry...

**Comment by skvili** [comment]
Maybe it will help someone. I had the same problem running Fallout4.exe after the update. Also Falloutlauncher.exe was running normally. I running explorer.exe, from it running Fallout4.exe once and all. Further, the error did not occur!

**Comment by Dwarsen** [comment]
I had this issue as well and stumbled across this thread. After a bunch of trial and error, I managed to solve it by symlinking the weird path to my actual wine python installation. After that, the script would run fine and it found my key from my Adobe Digital Editions installation.

So, try this if you're having this issue:
`ln ~/.wine/drive_c/<PythonInstallationDir>/python.exe ~/.wine/drive_c/windows/system32/python.exe`

Where <PythonInstallationDir> is your Python directory, for instance "Python27".
