### ISSUE TITLE
deDRM error: Failed to decrypt KFX DRM voucher with any key

### ISSUE THREAD

**Issue by xixas** [apprenticeharper/DeDRM_tools#531]
Note: I use anaconda for python.

calibre Debug log
calibre 3.23  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0) && EpubMerge (2, 2, 0)
calibre 3.23  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && DeDRM (6, 6, 1) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0) && EpubMerge (2, 2, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
EpubMerge: DEBUG: 2018-06-03 20:03:51,214: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:C:\Users\vikas\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[3.16] main UI initialized...
[3.16] Hiding splash screen
[35.38] splash screen hidden
[35.38] Started up in 35.38 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['{b\x02\xd5\xd9-)\xf9\x17\x03\xd5z\xaf\x01\x1dIq\xe5\x1f\x1c$\xe5\x99\xea\x83^\xdd\xebu\xfa\x8b\xe0', 'C:\\Users\\vikas\\Downloads\\Compressed\\B07BMZ93TL\\CR!3RDXR44VPD6M9E6WCMB51JJ0GMH5.kfx']
Gather KFX-ZIP File Type (from KFX Input) 1.4.0: Importing C:\Users\vikas\Downloads\Compressed\B07BMZ93TL\CR!3RDXR44VPD6M9E6WCMB51JJ0GMH5.kfx
Gather KFX-ZIP File Type (from KFX Input): Gathered 9 files as C:\Users\vikas\AppData\Local\Temp\calibre_3u_lyp\bkkj9c.kfx-zip
DeDRM v6.6.1: Trying to decrypt bkkj9c.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: bkkj9c
Got DSN key from database default_key
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7d291167-da02-4c8f-a55f-f04f9758629f.ast
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\vikas\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\vikas\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3862601819' and UserName '76696b6173'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: bkkj9c
Got DSN key from database default_key_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7d291167-da02-4c8f-a55f-f04f9758629f.ast
DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX File Type (from KFX Input) 1.4.0: Packaging C:\Users\vikas\AppData\Local\Temp\calibre_3u_lyp\bkkj9c.kfx-zip
Processing container: CR!1C5YG8QCFN7633MAFT5YYV84C8M2.kfx
Processing container: CR!3RDXR44VPD6M9E6WCMB51JJ0GMH5.kfx
Processing container: CR!66WDHD482X7QX1DKTF2XBVQK3SY2.kfx
Processing container: CR!9SZSXFJN2X3856GTSEFHJXWYGTKM.kfx
Import symbol table YJ_symbols version 10 max_id 745 exceeds known table size 744
Processing container: CR!DX2G8K7HN15RFAQP8S43SCNYSB8S.kfx
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 52, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container CR!DX2G8K7HN15RFAQP8S43SCNYSB8S.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\vikas\AppData\Local\Temp\calibre_3u_lyp\tysjub_add_books\0\CR!3RDXR44VPD6M9E6WCMB51JJ0GMH5.kfx-zip
Import symbol table YJ_symbols version 10 max_id 745 exceeds known table size 744
Added How a Realist Hero Rebuilt the Kingdom: Volume 6 to db in: 4.0
Added 1 books in 9.9 seconds
Worker Launch took: 0.378000020981
Job: 1 Convert book 1 of 1 (How a Realist Hero Rebuilt the Kingdom: Volume 6) finished
Convert book 1 of 1 (How a Realist Hero Rebuilt the Kingdom: Volume 6)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\vikas\\AppData\\Local\\Temp\\calibre_3u_lyp\\lzdbca.opf'
	  cover: u'C:\\Users\\vikas\\AppData\\Local\\Temp\\calibre_3u_lyp\\d27egk.jpeg'
	  output_profile: 'generic_eink'
	  flow_size: 999999
	Resolved conversion options
	calibre version: 3.23.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\vikas\\AppData\\Local\\Temp\\calibre_3u_lyp\\d27egk.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 999999,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x02FE25D0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x02FE27D0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\vikas\\AppData\\Local\\Temp\\calibre_3u_lyp\\lzdbca.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\vikas\AppData\Local\Temp\calibre_3u_lyp\ru5qvc.kfx-zip
	Software versions: KFX Input 1.4.0, calibre 3.23, Windows-8.1-6.3.9600-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\vikas\AppData\Local\Temp\calibre_3u_lyp\ru5qvc.kfx-zip
	Processing container: CR!1C5YG8QCFN7633MAFT5YYV84C8M2.kfx
	Processing container: CR!3RDXR44VPD6M9E6WCMB51JJ0GMH5.kfx
	Processing container: CR!66WDHD482X7QX1DKTF2XBVQK3SY2.kfx
	Processing container: CR!9SZSXFJN2X3856GTSEFHJXWYGTKM.kfx
	WARNING: Import symbol table YJ_symbols version 10 max_id 745 exceeds known table size 744
	Processing container: CR!DX2G8K7HN15RFAQP8S43SCNYSB8S.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 97, in convert
	  File "calibre_plugins.kfx_input.__init__", line 191, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 71, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
	KFXDRMError: Book container CR!DX2G8K7HN15RFAQP8S43SCNYSB8S.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by xixas** [comment]
I used the same thing for azw format(sample of the book with DRM) and it worked properly without error. Did the decryption successfully. So is the problem from KFX files?

**Comment by xixas** [comment]
I think the problem is because the folder with KFX files and .ast file which i got is from android Kindle. How to solve this?

**Comment by xixas** [comment]
![image](https://user-images.githubusercontent.com/14059393/40897600-9de68b10-67d9-11e8-9f66-63f3989fb8de.png)

**Comment by ElleKayEm** [comment]
There isn't currently a way to get the key for Kindle for Android books.  Can you download it to Kindle for PC?

**Comment by xixas** [comment]
i actually returned the book. because i want epub or some other lighter format for an old smartphone with ebook reader. ll buy again after i get my refund today. Will it work for PC? i will a different book if chances are low.

**Comment by ElleKayEm** [comment]
You should be able to download most books to Kindle for PC.  Books that aren't available for all Kindle apps/devices will say something like "available for these devices & apps" on their page.

Here's a post on getting the older format, instead of the new multi-file KFX format:

https://www.mobileread.com/forums/showthread.php?t=283371
