### ISSUE TITLE
Can't install DeDRM 6.6.1 as plugin to Calibre

### ISSUE THREAD

**Issue by Fabi66** [apprenticeharper/DeDRM_tools#537]
calibre, version 3.25.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Fabi\\Documents\\DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.25 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 471, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 60, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 192, in load
  File "site-packages\calibre\customize\zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Fabi\\Documents\\DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by Fabi66** [comment]
oops.  Thank you so much.  I thought I'd read not to unzip the file.  I didn't realize the instructions referred to another zipped file inside the download zip.  Thanks again!
