### ISSUE TITLE
DRM on loaned book

### ISSUE THREAD

**Issue by rackone** [apprenticeharper/DeDRM_tools#541]
Looking at the readMe, i appears the drm removal tool applied to calibre only works for purchased books?  I downloaded a book w/ the lastest kindle for pc and with both plugins, (drm and kfx) it gives me "This book is locked by DRM", see log below.

drm plugin version :DeDRM_tools_6.6.1
kindle for pc version: 1.23.1
KFX Input plugin added

----------------- log -----------------------
Convert book 1 of 1 (Brian's Winter (Brian's Saga Book 3))
Conversion options changed from defaults:
  cover: u'C:\\Users\\aa\\AppData\\Local\\Temp\\calibre_vdevdr\\nxrjoz.jpeg'
  output_profile: 'kindle'
  verbose: 2
  read_metadata_from_opf: u'C:\\Users\\aa\\AppData\\Local\\Temp\\calibre_vdevdr\\ijacep.opf'
Resolved conversion options
calibre version: 3.24.0
{'allow_conversion_with_errors': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\aa\\AppData\\Local\\Temp\\calibre_vdevdr\\nxrjoz.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x034D1BF0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x034D1F50>,
 'page_breaks_before': u'/',
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\aa\\AppData\\Local\\Temp\\calibre_vdevdr\\ijacep.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: KFX Input running
on C:\Users\aa\AppData\Local\Temp\calibre_vdevdr\sxmzt9.kfx-zip
Software versions: KFX Input 1.4.0, calibre 3.24, Windows-7-6.1.7601-SP1
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\aa\AppData\Local\Temp\calibre_vdevdr\sxmzt9.kfx-zip
Processing container: B000FC1H2I_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 97, in convert
  File "calibre_plugins.kfx_input.__init__", line 191, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 71, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 118, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 205, in get_container
KFXDRMError: Book container B000FC1H2I_EBOK.azw has DRM and cannot be converted
Python function terminated unexpectedly
  This book has DRM! (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1087, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "calibre_plugins.kfx_input.__init__", line 100, in convert
calibre.ebooks.DRMError: This book has DRM!

**Comment by j-howell** [comment]
> Looking at the readMe, i appears the drm removal tool applied to calibre only works for purchased books?

Yes, it will not work for loans or rentals.

DRM removal happens during import. If you want to see what is going wrong you need to post an [import log](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that).

**Comment by rackone** [comment]
having problems with the key...
Do you believe that loaned books will eventually be able to remove the drm in the future?


-----------------------------------
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.acb6878a-3093-fdfeee.ffjhehw,d6.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\aa\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\aa\AppData\Local\Amazon\Kindle\storage\.kinf2011
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: zwlq7z
Got DSN key from database default_key_1
Found 1 keys to try after 1.2 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
