### ISSUE TITLE
Nook Book won't de-DRM

### ISSUE THREAD

**Issue by normx004** [apprenticeharper/DeDRM_tools#544]
Just got a Nook and want to loan one of the books I bought to my son.  I installed Calibre, the DeDRM plugin, configured my B+N userid and pwd to get the key (which looks reasonable, 24 characters of this form:   JYu1********************eW0Q=

Here's the log:

calibre Debug log
calibre 3.25  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.25  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[2.86] main UI initialized...
[2.86] Hiding splash screen
[45.19] splash screen hidden
[45.19] Started up in 45.19 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt 9780679604686.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “9780679604686.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.1: Trying Encryption key Nookkey
Could not decrypt uv2bqk.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.6.1: Failed to decrypt with key Nookkey after 0.4 seconds
DeDRM v6.6.1: Looking for new NOOK Study Keys after 0.4 seconds
No nook Study log files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 301, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Rise and Kill First to db in: 0.5
Added 1 books in 1.7 seconds
Worker Launch took: 0.253000020981

Am I doing something wrong? Please help...

**Comment by ElleKayEm** [comment]
Hmmm, sounds like it should work.  The only thing I can suggest is trying with a copy downloaded with the old Nook for PC program.  Here's the setup file:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by normx004** [comment]
Worked like a charm!  DeDRM'd perfectly.  Thanks!

**Comment by ElleKayEm** [comment]
Good!  If you're all set, you can close this issue.
