### ISSUE TITLE
Windows app stopped working... No module named pylzma

### ISSUE THREAD

**Issue by SpookyUSAF** [apprenticeharper/DeDRM_tools#547]
Using Library AlfCrypto DLL/DYLIB/SO
Traceback (most recent call last):
  File "DeDRM_App.pyw", line 67, in <module>
    from scriptinterface import decryptepub, decryptpdb, decryptpdf, decryptk4mobi
  File "D:\Documents\DeDRM_App\DeDRM_lib\lib\scriptinterface.py", line 14, in <module>
    import k4mobidedrm
  File "D:\Documents\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "D:\Documents\DeDRM_App\DeDRM_lib\lib\kfxdedrm.py", line 20, in <module>
    import ion
  File "D:\Documents\DeDRM_App\DeDRM_lib\lib\ion.py", line 36, in <module>
    import pylzma as lzma
ImportError: No module named pylzma

Using the recommend config at latest Windows 10. ActivePython 2.7.14, PyCrypto 2.6.1. 6.6.0 was working great, removed the app folder from documents, copied new folder from 6.6.1 and now this error.

**Comment by SpookyUSAF** [comment]
Managed to get it working... had to go to command line and use:
pip install pylzma

This should be documented in the windows app readme :)

**Comment by ElleKayEm** [comment]
It looks like both of the stand-alone apps are having problems right now.

#512

**Comment by SpookyUSAF** [comment]
I made 6.6.1 windows app work by commenting the following lines in kfxdedrm.py:

```
try:
    from calibre_plugins.dedrm import ion
except ImportError:
    import ion
```

Note that I am only using ADE epub files so I don't need KFX.

**Comment by minipretzel** [comment]
This fix works for me but I wasn't having this specific lzma missing error.  There is definitely an ongoing issue.

**Comment by intenex** [comment]
Installing pylzma on Mac with sudo pip install pylzma fixed the issue for me flawlessly on the Mac app. Something similar I would expect to work on Windows as well.
