### ISSUE TITLE
Can't make DeDRM 6.61 work. Any idea to resolve

### ISSUE THREAD

**Issue by echidna555** [apprenticeharper/DeDRM_tools#550]
Problem:
- Kindle Amazon ebooks.
- DRM removal works fine on my old desktop with:
Windows 7
Calibre 1.15 (note that sometime inthe past after I updated to a newer version of calibre it did not work anymore, after I unstalled again 1.15, it worked again)
Plugins: Kindle and Mobipocket DeDRM 0.4.19 / Ignoble Epub DeDRM (0.2.6) / Inept Epub DeDRM (0.2.1), all by Diap Dealer, Apprentice Alf and icabbages
- Not sure which of the three do the job
Process: Connect Reader 1, import book from reader to calibre library -> DRM succesfully removed

- Now on my new PC:
Windows 10
Calibre 1.15 AND 3.26.1 (tried with both)
DeDRM 6.6.1
Same process -> DRM still in, book not readable after import
Also tried import from mykindle content. Book imports, but when openning error message "this is an KFX amazon book ..."

Note that the very same book on which this KFX message came works fine on my old PC with the above described setup and process.

Can't find the old plugins on the web, but even if. May it be that Windows 10 vs. 7 is the problem ?
Any suggestions to resolve ?
Thank you.

**Comment by ElleKayEm** [comment]
Use the latest calibre and DeDRM plugin.  Remove the old individual plugins.

If importing from an E-ink Kindle, enter its serial number into the E-ink Kindle section of the plugin customization.  If importing from Kindle for PC, then it needs to be on the same PC and user as calibre with DeDRM.

If you want to avoid KFX files, then follow one of the first 3 methods in this post:

https://www.mobileread.com/forums/showthread.php?t=283371

For KFX files, you will also need the KFX Input plugin:

https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by echidna555** [comment]
Thank you for your quick response but I think your advice is not pointing in the right direction.
The old calibre version and the old plugins are installed on the old PC with Win7 and everything works fine just by plging the reader and add the book to calibre library.
The same process with the same book does not work on the new PC with Win 10 and the latest calibre and plugin versions.
Hence neither of your suggestions would be applicable. The book apparantly is a KFX but it just works fine on the old PC without any special plugin for that.

**Comment by ElleKayEm** [comment]
The copy that worked must have been in the older format.  Depending on how you download it, the same book can be in the old or the new format. 
 DeDRM 6.6.0 was the first version that handled KFX books, and you need the KFX Input plugin (or you need to manually create a kfx-zip file).

**Comment by echidna555** [comment]
Please believe me that what I wrote above is correct. I did it this morning:
I plugged my kindle to the old PC and added the book to calibre with the setup described and it was DRM free then. And there is definetly no KFX plugin on that PC.
Then I plugged the very same kindle and added the very same ebook to calibre on the new PC and the DRM was NOT removed. All details above.

**Comment by echidna555** [comment]
I was not using K4PC !! I am just connecting the kindle device with USB and accessed the device with calibre. 
I even did not have K4PC installed on PC when I tried first !!!

**Comment by j-howell** [comment]
> Also tried import from mykindle content. Book imports, but when openning error message "this is an KFX amazon book ..."

Based on that I assumed that you were importing from Kindle for PC because that program places book files in a folder named "My Kindle Content". Kindle devices that connect via USB do not use such a folder.

At this point I think that the only way to tell what is going on is if you post import logs from adding the same book from the same device to both PCs so that we can see what is different between them.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by echidna555** [comment]
I wrote ALSO tried. This was an attempt after my usual direct method did not work. I then downloaded K4PC and tried that way. I have an old kindle device which I can connect via USB AND, apparantly my books do also appear in the K4PC software after I registrered with my account.

And obviously I have no import logs because I do not use the import dialogue.
I go to device on the calibre menue,  right click on a book and select add to library. Thats all. And there is no error essage. On the old PC the book will open from library, on the new PC it adds w/o problem  to the library, but on trying to open the book in calibre from the library, a window pops up saying that this book is DRM protected.

**Comment by ElleKayEm** [comment]
Try again with my instructions above.  If it still doesn't work, the only way I can help is if you post a log.

**Comment by carolynbm** [comment]
Hello,
I'm trying to remove the DRM from my Kindle books. I'm using a Mac and I have downloaded and installed Calibre and the plugin to remove DRM. I added the plugin to Calibre. I closed calibre and reopened it. I dragged a kindle book into Calibre. I then clicked on convert e-books to convert to PDF format. I get a message telling me it failed. Can anyone help me? 
attached is the message I received and here is the info on the failure 
![screenshot_4632](https://user-images.githubusercontent.com/40350269/41520626-7ea1a168-7283-11e8-8e95-0ddf66bfddb1.jpg)

calibre, version 3.24.1 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Advanced Tarot Secrets: Secrets from the best tarot readers in the world (Aphrodite's Book of Secrets 3))

Convert book 1 of 1 (Advanced Tarot Secrets: Secrets from the best tarot readers in the world (Aphrodite's Book of Secrets 3))
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'kindle'
  cover: u'/var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/rm8jgv.jpeg'
  read_metadata_from_opf: u'/var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/218Dh4.opf'
Resolved conversion options
calibre version: 3.24.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/rm8jgv.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11163c210>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x11163c8d0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/218Dh4.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/fqy22d.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Parsing all content...
Parsing text/part0011.html ...
Parsing text/part0006.html ...
Parsing text/part0001.html ...
Parsing text/part0012.html ...
Parsing text/part0007.html ...
Parsing text/part0002.html ...
Parsing text/part0013.html ...
Parsing text/part0008.html ...
Parsing text/part0016.html ...
Parsing text/part0019.html ...
Parsing text/part0021.html ...
Parsing text/part0003.html ...
Parsing text/part0022.html ...
Parsing text/part0020.html ...
Parsing text/part0014.html ...
Parsing text/part0009.html ...
Parsing text/part0004.html ...
Parsing text/part0017.html ...
Parsing text/part0015.html ...
Parsing text/part0018.html ...
Parsing text/part0010.html ...
Parsing text/part0005.html ...
Parsing styles/0001.css ...
Parsing text/part0000.html ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 1569 items of level: p_1
Found 95 items of level: div_1
Found 498 items of level: p_5
Found 57 items of level: p_2
Negative text indent detected at level  p_1, ignoring this level
div_1  left margin stats: Counter({u'': 5})
div_1  right margin stats: Counter({u'': 5})
p_5  left margin stats: Counter({u'0': 498})
p_5  right margin stats: Counter({u'0': 498})
p_2  left margin stats: Counter({u'0': 57})
p_2  right margin stats: Counter({u'0': 57})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'images/00146.jpeg' from manifest
Trimming u'images/00149.jpeg' from manifest
Creating PDF Output...
Splitting markup on page breaks and flow limits, if any...
		Splitting on page-break at id=calibre_pb_0
		Splitting on page-break at id=page_9
		Splitting on page-break at id=calibre_pb_2
		Splitting on page-break at id=page_23
		Splitting on page-break at id=calibre_pb_4
		Splitting on page-break at id=page_27
		Splitting on page-break at id=calibre_pb_6
		Splitting on page-break at id=page_29
		Splitting on page-break at id=calibre_pb_8
		Splitting on page-break at id=page_32
		Splitting on page-break at id=calibre_pb_10
		Splitting on page-break at id=page_36
		Splitting on page-break at id=calibre_pb_12
		Splitting on page-break at id=page_38
		Splitting on page-break at id=calibre_pb_14
		Splitting on page-break at id=page_42
		Splitting on page-break at id=calibre_pb_16
		Splitting on page-break at id=page_46
	Split into 10 parts
		Splitting on page-break at id=calibre_pb_0
		Splitting on page-break at id=page_61
		Splitting on page-break at id=calibre_pb_2
		Splitting on page-break at id=page_65
		Splitting on page-break at id=calibre_pb_4
		Splitting on page-break at id=page_67
		Splitting on page-break at id=calibre_pb_6
		Splitting on page-break at id=page_71
		Splitting on page-break at id=calibre_pb_8
		Splitting on page-break at id=page_79
	Split into 6 parts
		Splitting on page-break at id=calibre_pb_0
		Splitting on page-break at id=calibre_pb_1
		Splitting on page-break at id=calibre_pb_2
		Splitting on page-break at id=page_82
		Splitting on page-break at id=calibre_pb_4
		Splitting on page-break at id=page_83
	Split into 4 parts
Converting input as a text based book...
Serializing oeb input to disk for processing...
Rendering pages to PDF...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0000.html...
Loading font: family_name=Liberation Serif full_name=Liberation Serif Italic postscript_name=LiberationSerif-Italic subfamily_name=Italic
Loading font: family_name=Liberation Serif full_name=Liberation Serif Bold postscript_name=LiberationSerif-Bold subfamily_name=Bold
Loading font: family_name=Liberation Serif full_name=Liberation Serif postscript_name=LiberationSerif subfamily_name=Regular
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0001.html...
Loading font: family_name=Adobe Caslon Pro full_name=ACaslonPro-Regular postscript_name=ACaslonPro-Regular subfamily_name=Regular
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0002.html...
Loading font: family_name=Liberation Serif full_name=Liberation Serif Bold Italic postscript_name=LiberationSerif-BoldItalic subfamily_name=Bold Italic
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0003.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0004.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0005.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0006.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0007.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0008.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0009.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0010.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0011.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_out/text/part0012_split_000.html...
Processing /var/folders/nx/pjw07f_d5fq508l1v_yqlnrw0000gn/C/calibre_3.24.1_tmp_Q2Qt0Y/_OkILx_pdf_ouPython function terminated unexpectedly: PDF Output failed, see log for details
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1251, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 179, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 257, in convert_text
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 283, in write
  File "site-packages/calibre/ebooks/pdf/render/from_html.py", line 243, in dump
Exception: PDF Output failed, see log for details
t/text/part0012_split_001.html...
Loading font: family_name=Annie BTN full_name=Annie BTN postscript_name=AnnieBTN subfamily_name=Regular
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 39, in errh
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 275, in drawTextItem
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 243, in create_sfnt
  File "site-packages/calibre/utils/fonts/sfnt/container.py", line 69, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 201, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 129, in __init__
  File "site-packages/calibre/utils/fonts/utils.py", line 368, in read_bmp_prefix
error: unpack_from requires a buffer of at least 530 bytes

Loading font: family_name=Annie BTN full_name=Annie BTN postscript_name=AnnieBTN subfamily_name=Regular
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 39, in errh
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 275, in drawTextItem
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 243, in create_sfnt
  File "site-packages/calibre/utils/fonts/sfnt/container.py", line 69, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 201, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 129, in __init__
  File "site-packages/calibre/utils/fonts/utils.py", line 368, in read_bmp_prefix
error: unpack_from requires a buffer of at least 530 bytes

Loading font: family_name=Annie BTN full_name=Annie BTN postscript_name=AnnieBTN subfamily_name=Regular
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 39, in errh
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 275, in drawTextItem
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 243, in create_sfnt
  File "site-packages/calibre/utils/fonts/sfnt/container.py", line 69, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 201, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 129, in __init__
  File "site-packages/calibre/utils/fonts/utils.py", line 368, in read_bmp_prefix
error: unpack_from requires a buffer of at least 530 bytes

Loading font: family_name=Annie BTN full_name=Annie BTN postscript_name=AnnieBTN subfamily_name=Regular
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 39, in errh
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 275, in drawTextItem
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 243, in create_sfnt
  File "site-packages/calibre/utils/fonts/sfnt/container.py", line 69, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 201, in __init__
  File "site-packages/calibre/utils/fonts/sfnt/cmap.py", line 129, in __init__
  File "site-packages/calibre/utils/fonts/utils.py", line 368, in read_bmp_prefix
error: unpack_from requires a buffer of at least 530 bytes

**Comment by gvso** [comment]
It doesn't work for me either when using KFX files (even with KFX Input plugin). However, it works with AZW3 files.

**Comment by ElleKayEm** [comment]
Are the different formats from different sources?  Each Kindle app/device uses its own unique key.  Post a log of one that's not working.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by gvso** [comment]
I got the FKX file from my ebook reader. I got the AZW3 file from "Manage Your Devices and Content" on Amazon. I'll try it again later an post the output.

**Comment by arno2233** [comment]
Not working. I tried with calibre on mac . Downloaded the .azw, imported it in calibre after having installed dedrm 6.6.1.

**Comment by j-howell** [comment]
> Not working. I tried with calibre on mac . Downloaded the .azw, imported it in calibre after having installed dedrm 6.6.1.

Start a new issue to report your problem. Explain what you are doing and include an import log.

**Comment by arno2233** [comment]
the issue was the same. anyway solved by downloading  kindle 1.17
