### ISSUE TITLE
DeDRM_Tools 6.6.1 Will Not Load

### ISSUE THREAD

**Issue by Biker512** [apprenticeharper/DeDRM_tools#554]
I am getting the following errors when trying to install version 6.6.1 on MacOS 10.13.5:

calibre, version 3.26.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/Ray/Downloads/DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.26.1  embedded-python: True is64bit: True
Darwin-17.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.6.0', 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 4, 0) && Package KFX File Type (from KFX Input) (1, 4, 0) && KFX metadata reader (from KFX Input) (1, 4, 0) && KFX Input (1, 4, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 471, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 60, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 192, in load
  File "site-packages/calibre/customize/zipplugin.py", line 290, in _locate_code
InvalidPlugin: The plugin in u'/Users/Ray/Downloads/DeDRM_tools_6.6.1.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by RakiP** [comment]
I encountered the same. It is not evident though. I recommend putting this in the readme.md. Together with the kfx-input plugin and the latest calibre version I succeeded. Thank you!!

**Comment by ElleKayEm** [comment]
It's on the blog, the ReadMe_First.txt, and the FAQ.md.  Couldn't hurt to put it there too I suppose.

**Comment by KatyOnline** [comment]
Hello, I am new here.  I downloaded DeDRM_tools_6.6.1 and found the DeDRM_calibre_plugin file but the file "DeDRM_plugin.zip is not located in the folder DeDRM_calibre_plugin.
I have Windows 10.  I can't copy and paste any error messages because I did not get that far.  I have looked and looked and downloaded it several times but I still can' find it.
Many thanks
KatyOnline

**Comment by ElleKayEm** [comment]
Maybe however you are unzipping the outer file is unzipping the zip files inside it too.  You should only see 2 files in the DeDRM_calibre_plugin folder: DeDRM_plugin.zip and DeDRM_plugin_ReadMe.txt.

**Comment by KatyOnline** [comment]
Hello
Thank you for your quick reply.  I am still having trouble.  Maybe I am
opening the  DeDRM_calibre_plugin folder incorrectly. I navigate to
DeDRM_calibre_plugin folder.  At this stage, it is still unzipped.  The
only way I can open it is to double-click on it.   When it opens, it has a
whole list of files, not just the 2 you mentioned.  I keep trying and doing
all sorts of searches for  DeDRM_plugin.zip  but I have not been able to
see it yet.
What am I doing that is wrong?
Many thanks for your help
Kathleen



Kathleen

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by ElleKayEm** [comment]
It definitely sounds like whatever you're using to unzip DeDRM_tools_6.6.1.zip is also unzipping DeDRM_plugin.zip at the same time.

**Comment by KatyOnline** [comment]
Hello Again
Thank you for your patience and willingness to help.
I deleted 7Zip which is what I was using to unzip the file
DeDRM_tools_6.6.1.zip  and installed WinZip.  I removed all the previous
downloads of DeDRM_tools_6.6.1.zip so that there was no conflict.
Unfortunately, I have the same problem.

When I navigate to DeDRM_calibre_plugin folder and open it, I get a list of
files, not just the 2 files in the DeDRM_calibre_plugin folder:
DeDRM_plugin.zip and DeDRM_plugin_ReadMe.txt.

Can you please offer another suggestion.  Is it a problem with the
unzipping software?  Am I doing something wrong? What software do you
recommend to unzip files? I am in Australia.  Is that causing the problem?

I am becoming a bit disheartened by all these failures.  I have spent many
hours each day for almost a week trying to sort out this problem.  I really
do appreciate the help you have offered so far.

Many thanks


Kathleen

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by ElleKayEm** [comment]
I'm on Windows and I usually just use the built-in utility.  Are you on a Mac?  I think I've heard that Macs default to automatically unzipping files.  So try looking at the main file before using any zip utility.  Or look at your browser settings before downloading.  You're downloading from [here](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.6.1), right?

**Comment by KatyOnline** [comment]
Hello again
I have Windows 10.  What I am going to try now is this...Delete all the
unzip programs again, delete the latest 6.6.1. and try windows unzip
program.  I did try that before but the WinZip took over.  And yes, I do
have the right download source.
Thank you


Kathleen

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by KatyOnline** [comment]
Well, I tried what I said in the previous message and with the same
results.  No matter what I try, once I open DeDR_calibre_plugin, I get a
whole list of files none of which is called DeDR_calibre_plugin.zip.  This
time I used windows 10 and I still get the same result as I did with the
other software.
This problem is really trying my spirit.  Any more ideas?
I am grateful for your persistence.



Kathleen

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by ElleKayEm** [comment]
When you download the file are you using the fist link under Assets?  Right-click that and save it.  Once it's downloaded, go to where you've saved it.  Right-click it and Extract all.  Inside the unzipped main folder, you should have 5 folders and 3 files.  One of these is the DeDRM_calibre_plugin folder.  (Not to be confused with the Obok_calibre_plugin folder.)  If that's not what you're seeing, then I really don't know what's going on.

**Comment by KatyOnline** [comment]
Hello
I uninstalled Calibre and  DeDRM_Tools 6.6.1  then re-installed them.  I
followed your instructions very carefully.
You wrote "
​
inside the unzipped main folder, you should have 5 folders and 3 files. One
of these is the DeDRM_calibre_plugin folder. "  That is exactly what I
found.
When I opened the DeDRM_calibre_plugin folder, I had one folder called
DeDRM_plugin (IT WAS STILL ZIPPED) and one filer called DeDRM_plugin_ ReadMe
I unzipped the DeDRM_plugin  and again I got the long list.

Should the DeDRM_plugin folder be still unzipped at that stage?  I have
attached screenshots to show you what happened.

Thanks again

*Kathleen*

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by ElleKayEm** [comment]
Do not unzip DRM_plug.zip.  That's what you load into calibre, still zipped.

**Comment by KatyOnline** [comment]
Many thanks
I think I have the problem solved.  I never did find DRM _plug.zip.  I gave
up on trying to find it and  I loaded DeDRM_plugin (unzipped) into Calibre
and it worked.  I am still having some trouble getting some Kindle books
into Calibre but I think that is another problem.
Thank you for your persistence.
Cheers

*Kathleen*

*Romans 12:9  Love must be completely sincere. Hate what is evil, hold on
to what is good.*

**Comment by ElleKayEm** [comment]
Ok, the problem must be that you have Windows Explorer set to hide file extensions.  Because the DeDRM_plugin folder with the zipper on the icon IS DeDRM_plugin.zip.  Opening it in Windows Explorer doesn't unzip it.  So that's exactly what you needed to load into calibre.  And if you were able to do so, then it was still zipped.  Because calibre won't let you load a plain folder as a plugin.

If you want to ask about something else, then you can start a new issue.
