### ISSUE TITLE
unable to convert Kindle ebooks using DeDrm 6.6.0 or 6.6.1

### ISSUE THREAD

**Issue by blcjr** [apprenticeharper/DeDRM_tools#556]
I have used DeDrm successfully for several years with no issues.  The last time I used it was March 4 of this year.  I have been accumulating books since but have not processed them until last night.  I could not process any so I downloaded the latest version.  Still could not convert.  I have always used the standalone app and just have not gotten around to installing the Calibre plugin.  I am still using Kindle for Mac version 1.17.0 build 44173.  Here is the log

There is 1 ebook to be decrypted.
Processing file: B00GXN7MU4_EBOK.azw
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/test/Library/Preferences/com.apprenticealf.dedrm/Local Kindle Key.k4i' '/Users/test/Documents/Kindle Books/B00GXN7MU4_EBOK.azw' '/Users/test/Documents/Kindle Books/' > '/Users/test/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Applications/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    from calibre_plugins.dedrm import ion
ImportError: No module named calibre_plugins.dedrm
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/test/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/test/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.5
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/test/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'ed72a0036678' and UserName 'test'
Saved a key to /Users/test/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/test/Library/Preferences/com.apprenticealf.dedrm/KindleKey 6.der' '/Users/test/Documents/Kindle Books/B00GXN7MU4_EBOK.azw' '/Users/test/Documents/Kindle Books/' > '/Users/test/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Applications/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    from calibre_plugins.dedrm import ion
ImportError: No module named calibre_plugins.dedrm
There was an error with 1 ebook:
B00GXN7MU4_EBOK.azw couldn't be decrypted.

**Comment by ElleKayEm** [comment]
There are problems with the stand-alone apps right now.  If you look in other issues, some people have found workarounds.  But since you don't need KFX support with version 1.17 anyway, you could try going back to [DeDRM 6.5.5](https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.5.5).

**Comment by bezosj8** [comment]
If you are facing this problem in your kindle device so, you are trying to contact our tehnician. 

Because our technician are here for your help you can direct talk to him so, visit our website and get contact option for solving [unable to convert kindle eBooks using DeDrm]( http://kindlehelp.org/ ) problem.

**Comment by ElleKayEm** [comment]
@bezosj8's comment is spam or phishing.

**Comment by 51harry** [comment]
Unable to use De Drm 6.5.3

calibre Debug log
calibre 3.26.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 5, 3) && Package KFX File Type (from KFX Input) (1, 5, 0) && Kindle Collections (1, 7, 18) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Modify ePub (1, 3, 13)
calibre 3.26.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP File Type (from KFX Input) (1, 5, 0) && DeDRM (6, 5, 3) && Package KFX File Type (from KFX Input) (1, 5, 0) && Kindle Collections (1, 7, 18) && KFX metadata reader (from KFX Input) (1, 5, 0) && KFX Input (1, 5, 0) && Modify ePub (1, 3, 13)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 70.8837209302 x 71.067357513
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.31] splash screen shown
[0.33] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[5.52] main UI initialized...
[5.52] Hiding splash screen
[22.52] splash screen hidden
[22.52] Started up in 22.52 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x92\xcc\x0c\xdfiVY\xff\x9a\xb2\x9e\x9e!q\x13\\g\x1fW\x83\xc93\xf2v\x168v\xa8\xd3\xd6\xd1\xa1', 'C:\\Users\\Hariz\\Documents\\My Kindle Content\\B00GA22YFQ_EBOK\\B00GA22YFQ_EBOK.azw']
Gather KFX-ZIP File Type (from KFX Input) 1.5.0: Importing C:\Users\Hariz\Documents\My Kindle Content\B00GA22YFQ_EBOK\B00GA22YFQ_EBOK.azw
Gather KFX-ZIP File Type (from KFX Input): Gathered 4 file(s) as C:\Users\Hariz\AppData\Local\Temp\calibre_qehl_a\vlzgei.kfx-zip
DeDRM v6.5.3: Trying to decrypt vlzgei.kfx-zip
Unknown booktype kfx-zip. Passing back to calibre unchanged
Package KFX File Type (from KFX Input) 1.5.0: Packaging C:\Users\Hariz\AppData\Local\Temp\calibre_qehl_a\vlzgei.kfx-zip
Processing container: B00GA22YFQ_EBOK.azw
Running file type plugin Package KFX File Type (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 53, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 121, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 208, in get_container
KFXDRMError: Book container B00GA22YFQ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Hariz\AppData\Local\Temp\calibre_qehl_a\6bvy6v_add_books\0\B00GA22YFQ_EBOK.kfx-zip
Added The Direction of War: Contemporary Strategy in Historical Perspective to db in: 2.2
Added 1 books in 3.8 seconds

**Comment by j-howell** [comment]
> Unable to use De Drm 6.5.3

That book is in KFX format. You need to update to a newer version of DeDRM for that. (6.6.1 is the latest)

**Comment by 51harry** [comment]
Thank you

Have updated to 6.6.1 - bingo it works now

thanx a ton

have a great day

**Comment by xtina** [comment]
Can you point me to a comment with a workaround? I'm having trouble with the latest DeDRM and KFX Input plugin.
