### ISSUE TITLE
Can't decrypt this and many other EPUB

### ISSUE THREAD

**Issue by Bragolatch** [apprenticeharper/DeDRM_tools#565]
C:\WINDOWS\system32>calibre-debug -g
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17704-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17704')
Python 2.7.12+
Windows: ('10', '10.0.17704', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 88.1880650995 x 88.7766990291
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.31] main UI initialized...
[1.31] Hiding splash screen
[1.81] splash screen hidden
[1.81] Started up in 1.81 seconds with 4 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['L2\xa9\xd9\xe3\xa8s\x88\xa3,\xa2\xd2\x1e\xf0 |H\xf7[A\x8a\x98\xe3}\x9f\xf5\x7f\xb8\nD\xbeu', 'D:\\Desktop\\56bc68b3-f2b4-4708-840c-79d32485eebe.epub']
DeDRM v6.6.1: Trying to decrypt 56bc68b3-f2b4-4708-840c-79d32485eebe.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “56bc68b3-f2b4-4708-840c-79d32485eebe.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
Added Le grand livre des plantes médicinales to db in: 1.5
Added 1 books in 2.1 seconds

![image](https://user-images.githubusercontent.com/4919437/42226171-79c0002c-7f08-11e8-80d6-6084741c6245.png)

[56bc68b3-f2b4-4708-840c-79d32485eebe.zip](https://github.com/apprenticeharper/DeDRM_tools/files/2159802/56bc68b3-f2b4-4708-840c-79d32485eebe.zip)

**Comment by ElleKayEm** [comment]
If it's an epub with something other than Adobe DRM or Barnes & Noble's DRM, then these tools can't help.

**Comment by Bragolatch** [comment]
Yeah, I tried many tools, not sure witch now lol but one of them said it was protected by ibooks (Apple Fairplay DRM). Know anything that would do the trick ? I've read about requiem 3.3.6 but it outdated an I can't find a link that is not infected with a trojan. Might be a false positive but my test rig is dead and I don't really want to run it on my main.

**Comment by ElleKayEm** [comment]
I'm not aware of anything free that works anymore on iBooks.  I've heard people say they've had success with paid programs, but I don't know what they were.
