### ISSUE TITLE
Got the new version, still not working

### ISSUE THREAD

**Issue by iwpoe** [apprenticeharper/DeDRM_tools#569]
Log:
calibre Debug log
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.94] main UI initialized...
[1.94] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
[11.28] splash screen hidden
[11.28] Started up in 11.28 seconds with 146 books
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
DeDRM v6.6.1: Trying to decrypt B00UNCO6VY_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\iwpoe\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\iwpoe\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2216438504' and UserName '6977706f65'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 427, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B00UNCO6VY EBOK to db in: 1.6
Added 1 books in 2.8 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
DeDRM v6.6.1: Trying to decrypt B07BTHDPDZ_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Jewish Fables: Darwinism, Materialism, and other Jewish Fables
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID ntZqaeLx1R.
Decrypting. Please wait . . . done
Decryption succeeded after 0.3 seconds
DeDRM v6.6.1: Finished after 0.3 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Added 0 books in 7.4 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
DeDRM v6.6.1: Trying to decrypt B009JW0GUE_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\iwpoe\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\iwpoe\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2216438504' and UserName '6977706f65'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 427, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B009JW0GUE EBOK to db in: 1.5
Added 1 books in 2.4 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
DeDRM v6.6.1: Trying to decrypt B0721KX2BV_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Pope Francis in Context: Have the End Times Arrived in Buenos Aires?
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID eD/MJ4rQQC.
Decrypting. Please wait . . . done
Decryption succeeded after 0.5 seconds
DeDRM v6.6.1: Finished after 0.5 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Added 0 books in 6.4 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
DeDRM v6.6.1: Trying to decrypt B00839H09E_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\iwpoe\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\iwpoe\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2216438504' and UserName '6977706f65'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 427, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B00839H09E EBOK to db in: 1.5
Added 1 books in 2.4 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
DeDRM v6.6.1: Trying to decrypt B007BSCYOE_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: The Jewish Question
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID FihiDNFbQV.
Decrypting. Please wait . . .Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
 done
Decryption succeeded after 0.7 seconds
DeDRM v6.6.1: Finished after 0.7 seconds
Added 0 books in 6.1 seconds
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Connect to device failed, retrying in 5 seconds...
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Storage number map:
{(7L, 0L): [(2L, 'D')], (7L, 1L): [(3L, 'C')]}
Drive letters for USBDevice(vendor_id=0x4e8 product_id=0x6860 bcd=0x400 devid=usb\vid_04e8&pid_6860&rev_0400 devinst=5)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.android.driver.ANDROID object at 0x0000025FA06D21D0>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 198, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 834, in open
  File "site-packages\calibre\devices\usbms\device.py", line 274, in open_windows
DeviceError: Unable to detect any disk drives for the device: Android phone. Try rebooting

Device connect failed again, giving up

**Comment by ElleKayEm** [comment]
I see a few successfully decrypted books.  The others are in KFX format.  You need the KFX Input plugin for those.
