### ISSUE TITLE
KFX Plugin Failure

### ISSUE THREAD

**Issue by Snapitup** [apprenticeharper/DeDRM_tools#573]
Hello Dude  

The first error " The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required." I think I read somewhere that your process will create this. The file you get what assume'Default Kindle Key' from looks to me like it identifies me/my machine and every Kindle book I own. [Found k4Mac kinf2011 file: =Support/Kindle/storage/.kinf2011.] 

I would try on of the workaround that force Amazon not to download KFX - a problem is you need to remove existing files and while you can refresh to book list in Kindle the book file download isn't commenced until a open a book - and it even holds back from full download unless you spin to the last page! Going through entire Kindle library fake reading each book? No thanks.  

Anyway here's the debug log: If you can see any solution much appreciated.   

DRM v6.6.1: Trying to decrypt B07BMQ5YC8_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2011 file: /Users/now2/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '3da402c913e6' and UserName 'now2'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 6.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 6.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 427, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 284, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 494, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 284, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 312, in identity
MobiError: Unknown book type: ??????
Added B07BMQ5YC8 EBOK to db in: 0.1
Added 1 books in 9.8 seconds
INVALID PARENT FOR INTERFACE:  QAccessibleInterface(0x7fa2324aeb18 name="" role=List childc=1 obj=QListView(0x7fa2326128b0)rect=QRect(662,292 1394x21))
Worker Launch took: 0.334094047546

**Comment by ElleKayEm** [comment]
You need the [KFX Input](https://www.mobileread.com/forums/showthread.php?t=291290) plugin.

(On Kindle for PC, you just right-click the cover and choose download to get the full book.  I'm surprised you can't do something similar on Kindle for Mac.  Still a pain if you need to get a lot of books, but better than what you describe.)
