### ISSUE TITLE
This book is locked by DRM

### ISSUE THREAD

**Issue by WeHereNow** [apprenticeharper/DeDRM_tools#580]
I purchased the Book so it's not a loaner. I downloaded a book using KindleforPC 1.17.44170 for pc . installed the Plugin it still gives me "This book is locked by DRM" looks like i'm missing the key. Where can i get the Key?

calibre Debug log
calibre 3.27.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.27.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 36.0177252585 x 36.0283687943
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
[1.75] main UI initialized...
[1.75] Hiding splash screen
Failed to check for calibre update: [Errno 11004] getaddrinfo failed
Failed to check for plugin update: [Errno 11004] getaddrinfo failed
[4.26] splash screen hidden
[4.26] Started up in 4.26 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['s\x12\x93\x9d\xc1\xda\x92\x84\x06\x80((m_\x1c\xb09\xfdNB\xda\x82rG\x98N\xa9\xf2,A2X', 'C:\\Users\\user\\Documents\\My Kindle Content\\B06XXDDB6G_EBOK.azw']
DeDRM v6.6.1: Trying to decrypt B06XXDDB6G_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Six Sigma Green Belt Study Guide: Test Prep Book & Practice Test Questions for the ASQ Six Sigma Green Belt Exam
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Six Sigma Green Belt Study Guide: Test Prep Book & Practice Test Questions for the ASQ Six Sigma Green Belt Exam to db in: 0.3
Added 1 books in 0.8 seconds

**Comment by WeHereNow** [comment]
It was a username issue Problem solved
