### ISSUE TITLE
B&N Nook epub failure

### ISSUE THREAD

**Issue by mike8789** [apprenticeharper/DeDRM_tools#581]
After following all instructions, I was unable to de-DRM my Barnes & Noble epub downloaded using the Nook App for Windows (from the Microsoft Store) and the Calibre plug-in. There's some issue with my key, but I've triple checked  I'm using the right email and password. Any tips for getting a valid key?

Here's the log:

calibre Debug log
calibre 3.27.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.27.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.047267356 x 96.0
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.28] main UI initialized...
[1.28] Hiding splash screen
[2.95] splash screen hidden
[2.95] Started up in 2.95 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1\xe3\xf0\x93!5\xc0\x83\xa1\xedQv\xec\x8b|h#\x8eI\xd1\xda\xee\x14(-\\\x99K\x9d\xafs\x9e', 'C:\\Users\\Mike\\Books\\2940151251433.epub']
DeDRM v6.6.1: Trying to decrypt 2940151251433.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “2940151251433.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.1: Trying Encryption key Nook
Could not decrypt vxerri.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: AES key must be either 16, 24, or 32 bytes long

DeDRM v6.6.1: Failed to decrypt with key Nook after 0.1 seconds
DeDRM v6.6.1: Looking for new NOOK Study Keys after 0.1 seconds
No nook Study log files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 301, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Federalist Papers to db in: 1.3
Added 1 books in 1.9 seconds
Worker Launch took: 0.0590000152588

**Comment by ElleKayEm** [comment]
Try downloading your books with the old Nook for PC program:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

**Comment by mike8789** [comment]
That worked perfectly, thanks @ElleKayEm !!
