### ISSUE TITLE
DRM locked book - have installed plugins

### ISSUE THREAD

**Issue by Tarz-an** [apprenticeharper/DeDRM_tools#589]
Use updated windows 10 with calibre latest version and plug ins.  Purchased book from Amazon today - downloaded to the PC in an azw format - won't open or convert in calibre.  Thanks.

calibre Debug log
calibre 3.28  embedded-python: True is64bit: False
Windows-Vista-6.0.6000-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', 'Vista', '6.0.6000')
Python 2.7.12+
Windows: ('Vista', '6.0.6000', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && FanFicFare (2, 27, 0) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1) && KindleUnpack - The Plugin (0, 81, 5) && Find Duplicates (1, 6, 3) && Goodreads (1, 1, 14) && Set KFX metadata (from KFX Output) (1, 21, 1) && KFX Output (1, 21, 1) && MondoUrania (0, 2, 2) && Kindle Collections (1, 7, 19) && Obok DeDRM (6, 5, 4) && Count Pages (1, 8, 2)
calibre 3.28  embedded-python: True is64bit: False
Windows-Vista-6.0.6000-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', 'Vista', '6.0.6000')
Python 2.7.12+
Windows: ('Vista', '6.0.6000', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && FanFicFare (2, 27, 0) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1) && KindleUnpack - The Plugin (0, 81, 5) && Find Duplicates (1, 6, 3) && Goodreads (1, 1, 14) && Set KFX metadata (from KFX Output) (1, 21, 1) && KFX Output (1, 21, 1) && MondoUrania (0, 2, 2) && Kindle Collections (1, 7, 19) && Obok DeDRM (6, 5, 4) && Count Pages (1, 8, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
FFF: INFO: 2018-07-24 18:54:48,073: calibre_plugins.fanficfare_plugin.prefs(204): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2018-07-24 18:54:48,075: calibre_plugins.fanficfare_plugin.prefs(209): Using default settings
FFF: DEBUG: 2018-07-24 18:54:48,079: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Roy & Tara\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[5.31] main UI initialized...
[5.31] Hiding splash screen
[10.72] splash screen hidden
[10.73] Started up in 10.73 seconds with 1755 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['60D\xa7\xa6x}\xfa\xd1V\x8d\x9da\xe1/O\xbe\xc6N\x83/jx\xd4\xfe\xde\x7f6E\xe5\xd3\x1d', "C:\\Users\\Roy & Tara\\Downloads\\The Paris Seamstress_ Transporting, Twisting, the Most Heartbreaking Novel You'll Read This Year.azw3"]
DeDRM v6.6.1: Trying to decrypt The Paris Seamstress_ Transporting, Twisting, the Most Heartbreaking Novel You'll Read This Year.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Paris Seamstress: Transporting, Twisting, the Most Heartbreaking Novel You'll Read This Year
Found 8 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Roy & Tara\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Roy & Tara\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2186573596' and UserName '526f7920262054617261'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Paris Seamstress: Transporting, Twisting, the Most Heartbreaking Novel You'll Read This Year
Got DSN key from database default_key_1
Found 4 keys to try after 1.8 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Paris Seamstress: Transporting, Twisting, the Most Heartbreaking Novel You'll Read This Year to db in: 9.9
Added 1 books in 14.4 seconds

**Comment by ElleKayEm** [comment]
Books downloaded from the website need to be for an E-ink Kindle (not a Fire).  And its serial number needs to entered into the plugin customization.

**Comment by ElleKayEm** [comment]
Preferences > Plugins.  Then select DeDRM under File Type Plugins.  Then hit the Customize plugin button below.  Then "eInk Kindle ebooks" and the green plus sign.  Easiest way to make sure you get it correct is to copy and paste from the website (removing spaces).  Click OK and Apply out of the various dialogue boxes.  Then restart calibre before trying to add a book.
