### ISSUE TITLE
Failed DRM removal on latest Barnes and Noble epubs

### ISSUE THREAD

**Issue by unipenguin** [apprenticeharper/DeDRM_tools#592]
![bn fail](https://user-images.githubusercontent.com/41847305/43362830-e90f8e08-92c1-11e8-9cf3-f8d49510916c.PNG)
Most of the books that I've bought in last three months will not convert in Calibre now.  As you'll see, I tried with a book that was already installed but did not convert, and then tried to import and convert from the file downloaded from Nook For PC.

I have absolutely no experience in programming, but I can read an FAQ.  I have been gratefully using the DeDRM tools for years, and this is the first fail I've ever had.  

Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\wizki>calibre-debug -g
calibre 3.26.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Find Duplicates (1, 6, 3) && all recipes Recipe Reader (1, 0, 1) && FanFicFare (2, 26, 0) && Kindle Collections (1, 7, 18) && Amazon.com Multiple Countries (1, 0, 0) && KindleUnpack - The Plugin (0, 81, 5) && Barnes & Noble (1, 2, 15) && Overdrive Link (2, 28, 1) && DOC Input (1, 0, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 88.1880650995 x 88.7766990291
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
FFF: INFO: 2018-07-28 23:40:04,809: calibre_plugins.fanficfare_plugin.prefs(204): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2018-07-28 23:40:04,809: calibre_plugins.fanficfare_plugin.prefs(209): Using default settings
FFF: DEBUG: 2018-07-28 23:40:04,812: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\wizki\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[3.09] main UI initialized...
[3.11] Hiding splash screen
[3.34] splash screen hidden
[3.34] Started up in 3.34 seconds with 1141 books
DeDRM v6.6.1: Trying to decrypt Ride the Storm (Cassie Palmer) - Karen Chance.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “Ride the Storm (Cassie Palmer) - Karen Chance.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
Added Ride the Storm to db in: 0.1
Added 1 books in 0.9 seconds
Worker Launch took: 0.146000146866
Job: 1 Convert book 1 of 1 (Ride the Storm) finished
Convert book 1 of 1 (Ride the Storm)
        Conversion options changed from defaults:
          output_profile: 'nook_color'
          read_metadata_from_opf: u'C:\\Users\\wizki\\AppData\\Local\\Temp\\calibre_te38la\\kudalt.opf'
          verbose: 2
        Resolved conversion options
        calibre version: 3.26.1
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': None,
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'epub_version': u'2',
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B2BC096BA8>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.NookColorOutput object at 0x000001B2BC0A5438>,
         'page_breaks_before': u'/',
         'prefer_metadata_cover': False,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\wizki\\AppData\\Local\\Temp\\calibre_te38la\\kudalt.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: EPUB Input running
        on C:\Users\wizki\AppData\Local\Temp\calibre_te38la\v6ihem.epub
        Python function terminated unexpectedly
          v6ihem.epub (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 101, in main
          File "site.py", line 78, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
          File "site-packages\calibre\customize\conversion.py", line 244, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
        calibre.ebooks.DRMError: v6ihem.epub

stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['=\xa1\x1cF\x9e\xf5` \xfar\x84&\x0fm+\x89\xd96\xe1\xf08\x12\xa8\xfb\xa4\t\n#\xbd\x05l\xd5', 'C:\\Users\\wizki\\Desktop\\bn\\9780761171157_epub.v2[1].epub']
DeDRM v6.6.1: Trying to decrypt 9780761171157_epub.v2[1].epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “9780761171157_epub.v2[1].epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
Added 1501 Ways to Reward Employees to db in: 0.1
Added 1 books in 3.5 seconds
Worker Launch took: 0.12299990654
Job: 2 Convert book 1 of 1 (1501 Ways to Reward Employees) finished
Convert book 1 of 1 (1501 Ways to Reward Employees)
        Conversion options changed from defaults:
          output_profile: 'nook_color'
          read_metadata_from_opf: u'C:\\Users\\wizki\\AppData\\Local\\Temp\\calibre_te38la\\uxk28e.opf'
          verbose: 2
        Resolved conversion options
        calibre version: 3.26.1
        {'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': None,
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'epub_version': u'2',
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002993B852080>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.NookColorOutput object at 0x000002993B8528D0>,
         'page_breaks_before': u'/',
         'prefer_metadata_cover': False,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\wizki\\AppData\\Local\\Temp\\calibre_te38la\\uxk28e.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: EPUB Input running
        on C:\Users\wizki\AppData\Local\Temp\calibre_te38la\m_f3p1.epub
        Python function terminated unexpectedly
          m_f3p1.epub (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 101, in main
          File "site.py", line 78, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
          File "site-packages\calibre\customize\conversion.py", line 244, in __call__
          File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
        calibre.ebooks.DRMError: m_f3p1.epub

**Comment by ElleKayEm** [comment]
Those were downloaded with the old Nook for PC program?  Not the Windows Nook app?  Because they're both missing a piece of the DRM.  That's why the log is saying they're "neither an Adobe Adept nor a Barnes & Noble encrypted ePub."  I haven't seen that with Nook for PC -- just the Windows app.  I really hope that hasn't changed.
