### ISSUE TITLE
MacOS Mojave: UnicodeEncodeError on filename

### ISSUE THREAD

**Issue by markus0m** [apprenticeharper/DeDRM_tools#593]
This is odd. Happens on Mac OS Mojave, with a standard filename.
There is no Dash in the Book title either.

Changing the code and instead using _outfilename = orig_fn_root_ works. 

```
Decrypting. Please wait . . . . done
Decryption succeeded after 0.0 seconds
 Traceback (most recent call last):
  File "//DeDRM.app/Contents/Resources/k4mobidedrm.py", line 353, in <module>
    sys.exit(cli_main())
  File "//DeDRM.app/Contents/Resources/k4mobidedrm.py", line 347, in cli_main
    return decryptBook(infile, outdir, kDatabaseFiles, androidFiles, serials, pids)
  File "//DeDRM.app/Contents/Resources/k4mobidedrm.py", line 272, in decryptBook
    outfilename = '{}_{}'.format(orig_fn_root, clean_title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 5: ordinal not in range(128)
There was an error with 1 ebook:
B00ABC1W23_EBOK.azw couldn't be decrypted.
```

**Comment by john-chris** [comment]
The same "UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013'" happened to me on Mac OS High Sierra.

**Comment by jsrichards** [comment]
Is there a fix for this, or does the version of DeDRM need to be downgraded?

**Comment by alexkuc** [comment]
Close this issue with PR #685 was merged?
