### ISSUE TITLE
cant decrypt ADE file

### ISSUE THREAD

**Issue by vidou** [apprenticeharper/DeDRM_tools#596]
calibre Debug log
calibre 2.79  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Starting up...
Started up in 2.21 seconds with 4 books
DeDRM v6.6.1: Trying to decrypt the dogs who found me.epub
DeDRM v6.6.1: Verifying zip archive integrity
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 209, in ePubDecrypt
  File "site-packages/calibre/customize/zipplugin.py", line 183, in load_module
  File "calibre_plugins.dedrm.ignobleepub", line 202, in <module>
  File "calibre_plugins.dedrm.ignobleepub", line 196, in _load_crypto
  File "calibre_plugins.dedrm.ignobleepub", line 132, in _load_crypto_libcrypto
  File "lib/python2.7/ctypes/__init__.py", line 365, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
	/usr/local/lib/libcrypto.dylib: mach-o, but wrong architecture
Added the dogs who found me to db in: 0.2
Added 1 books in 1.3 seconds

**Comment by ElleKayEm** [comment]
Can you read the book in ADE 2.0.1 authorized with your Adobe ID?
