### ISSUE TITLE
DRM not removed Calibre

### ISSUE THREAD

**Issue by jamim04** [apprenticeharper/DeDRM_tools#598]
calibre Debug log
calibre 3.28  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.28  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.453781513 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.97] main UI initialized...
[1.97] Hiding splash screen
[14.19] splash screen hidden
[14.19] Started up in 14.19 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\x8e\xa1'\xe0\x90\x0c\xd1',\xc5\x04\xb0\x05\xdb\x89\xa98\xbe\xd2J\x17\xdf_\xeeq\xfa\xe7\x07\xb6a2\xf4", 'C:\\Users\\David\\Downloads\\Good Omens_ The Nice and Accurate Prophecies of Agnes Nutter, Witch (1).azw3']
DeDRM v6.6.1: Trying to decrypt Good Omens_ The Nice and Accurate Prophecies of Agnes Nutter, Witch (1).azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\David\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\David\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '80355293' and UserName '4461766964'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch to db in: 0.2
Added 1 books in 1.1 seconds
Worker Launch took: 0.0870001316071
Job: 1 Convert book 1 of 1 (Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch) finished
Convert book 1 of 1 (Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch)
	Conversion options changed from defaults:
	  output_profile: 'kindle_fire'
	  cover: u'C:\\Users\\David\\AppData\\Local\\Temp\\calibre_kpxrb9\\npwhdl.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\David\\AppData\\Local\\Temp\\calibre_kpxrb9\\vbhrmm.opf'
	Resolved conversion options
	calibre version: 3.28.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\David\\AppData\\Local\\Temp\\calibre_kpxrb9\\npwhdl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x03715E50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x02A89210>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\David\\AppData\\Local\\Temp\\calibre_kpxrb9\\vbhrmm.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\David\AppData\Local\Temp\calibre_kpxrb9\vq6tmd.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch

**Comment by ElleKayEm** [comment]
If you are downloading from the website, you need an E-ink Kindle (not a Fire) and you need to enter its serial number into DeDRM's customization.
