### ISSUE TITLE
DRM not removed using KFX Input Plugin

### ISSUE THREAD

**Issue by mconnors625** [apprenticeharper/DeDRM_tools#599]
DRM not removed using KFX Input Plugin when strictly following instructions and after successful installation.

Log:

calibre Debug log
calibre 3.28 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
calibre 3.28 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 6, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 6, 1) && KFX metadata reader (from KFX Input) (1, 6, 1) && KFX Input (1, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[3.69] main UI initialized...
[3.69] Hiding splash screen
[9.89] splash screen hidden
[9.89] Started up in 9.89 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xb6\xde\xce`%\x9c\x87\xf3\xdc\xe8\xa8-s\x16\xfazE\xc6$\n\x0b\x11\xf4\xf2^}\xd6\xbb\xf6'\x19R", 'C:\\Users\\Administrator\\Documents\\My Kindle Content\\B00A6CCF0K_EBOK\\B00A6CCF0K_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.6.1: Importing C:\Users\Administrator\Documents\My Kindle Content\B00A6CCF0K_EBOK\B00A6CCF0K_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ADMINI~1\AppData\Local\Temp\calibre_iflhqs\revz0m.kfx-zip
DeDRM v6.6.1: Trying to decrypt revz0m.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: revz0m
Got DSN key from database default_key
Found 2 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bc7edc5c-9e0b-4a3d-9a58-7f676c78c420.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as PublicLibraryLending. These tools are intended for use on purchased books.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Administrator\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Administrator\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2584086977' and UserName '41646d696e6973747261746f72'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: revz0m
Got DSN key from database default_key_1
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.bc7edc5c-9e0b-4a3d-9a58-7f676c78c420.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.6.1: Packaging C:\Users\ADMINI~1\AppData\Local\Temp\calibre_iflhqs\revz0m.kfx-zip
Processing container: B00A6CCF0K_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B00A6CCF0K_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ADMINI~1\AppData\Local\Temp\calibre_iflhqs\aionzw_add_books\0\B00A6CCF0K_EBOK.kfx-zip
Added Doctor Sleep: A Novel (The Shining Book 2) to db in: 1.9
Added 1 books in 4.0 seconds

**Comment by ElleKayEm** [comment]
The log says this is a library book.  These tools are for purchased books.

**Comment by mconnors625** [comment]
Ok. Thank you. I figured that’s what it was. I finally found that buried in all the reading I did on the forums late last night. Should maybe make that statement more prominent somewhere. 

I managed to strip the DRM on a borrowed book previously using Calibre (it was not KFX) without issue and just assumed I would be able to do it on any. Wrong assumption. Thanks. 

Mike Connors

(Sent from my iPhone)

**Comment by mconnors625** [comment]
Maybe right up front in the instructions for installing the kfx plug-in was all I meant. I might not have had to bother you. Thank you so much. 

Mike Connors

(Sent from my iPhone)

**Comment by j-howell** [comment]
I will update the documentation for the KFX Input plugin to point out this limitation. (Though I doubt that many will take note of it.)

**Comment by mconnors625** [comment]
Hi.  It just seemed logical to me that it should be there but I could be
wrong.  I am a novice techie - very novice.  The top hit on my web search
led me to the article "Remove the DRM From Amazon Kindle Books" at
GeoffStratton.com and introduced me to Calibre.  The article was an easy
read and had information on the KFX plugin in bold.  However, it did not
explain the de-DRM tools were not designed for borrowed books vs.
purchased.  If it had said something right there I would have stopped and
lacking that if there had been something prominent on the pages the article
linked to on how to install/use the KFX plugin I would have stopped.
Unfortunately, us novices need some things spelled out in bold up front to
avoid us wasting your time.  That's all I was trying to convey.

Thanks for all you do.  Overall, the information you provide is very, very
helpful.

Mike Connors

c:  813-767-2103

e:  mconnors625@gmail.com
