### ISSUE TITLE
Trouble Converting Comic Book KFX DRM

### ISSUE THREAD

**Issue by jtsgty** [apprenticeharper/DeDRM_tools#610]
I keep getting the persistent DRM even after installing latest DeDRM plugin and KFX input plugin.
I did pull this file directly off of my Android device btw (not downloaded using Kindle for PC).

calibre Debug log
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 7, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 7, 0) && KFX metadata reader (from KFX Input) (1, 7, 0) && KFX Input (1, 7, 0) && Obok DeDRM (6, 5, 4) && Set KFX metadata (from KFX Output) (1, 22, 0) && KFX Output (1, 22, 0)
calibre 3.30 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 7, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 7, 0) && KFX metadata reader (from KFX Input) (1, 7, 0) && KFX Input (1, 7, 0) && Obok DeDRM (6, 5, 4) && Set KFX metadata (from KFX Output) (1, 22, 0) && KFX Output (1, 22, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.70] main UI initialized...
[1.70] Hiding splash screen
[213.12] splash screen hidden
[213.12] Started up in 213.12 seconds with 12 books
Worker Launch took: 0.138999938965
Job: 1 Convert book 1 of 1 (Sankarea Vol. 1) finished
Convert book 1 of 1 (Sankarea Vol. 1)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\gddre\\AppData\\Local\\Temp\\calibre_6hhusx\\t3e7lb.opf'
	  output_profile: 'kindle_fire'
	  cover: u'C:\\Users\\gddre\\AppData\\Local\\Temp\\calibre_6hhusx\\lgapiy.jpeg'
	Resolved conversion options
	calibre version: 3.30.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\gddre\\AppData\\Local\\Temp\\calibre_6hhusx\\lgapiy.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000208FD642160>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x00000208FD6427B8>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\gddre\\AppData\\Local\\Temp\\calibre_6hhusx\\t3e7lb.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\gddre\AppData\Local\Temp\calibre_6hhusx\004urs.kfx-zip
	Software versions: KFX Input 1.7.0, calibre 3.30 [64bit], Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\gddre\AppData\Local\Temp\calibre_6hhusx\004urs.kfx-zip
	Processing container: CR!09E05CBE2H48Z1V6NK8216ZS441Q.kfx
	Processing container: CR!0FCB2ZZ5T17FHAKP76E72S6J41FC.kfx
	Processing container: CR!0PYV445AR95WZ8WEG5XB48PE6MJ9.kfx
	Processing container: CR!18KM9N4HXN7P5E873N7KDTSJJ368.kfx
	Processing container: CR!1J9V4S6N1X7PX8G1NGZYF5CJHQGH.kfx
	Processing container: CR!1ZDS2F15AS2K5AT11KEF0GVJ2FH0.kfx
	Processing container: CR!2MQHHRNZS545DE04ERACASRYN7WW.kfx
	Processing container: CR!2V3PG80SKS5N7B68N1MSYQ6C84N4.kfx
	Processing container: CR!3S49X8TXXD6SKD5CXAEJ54VSRXER.kfx
	Processing container: CR!4X1XHHDXNH4GFASWW010PWHC5WKF.kfx
	Processing container: CR!59B1QE3F5S6QNAM658W5D1WEAN1W.kfx
	Processing container: CR!5FFNKJ4WZ97YQ6JTZTN34T94BZ9D.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 95, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
	KFXDRMError: Book container CR!5FFNKJ4WZ97YQ6JTZTN34T94BZ9D.kfx has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by jtsgty** [comment]
Well that's terrible news.  Thanks for answering even though it was found in the FAQs, apparently.

**Comment by jtsgty** [comment]
Because there are some accounts right now that cannot download books to PC with Amazon right now.  Apparently, it's being written into an update or something.  Anyway, my account is one such account (over 100 comic books I cannot download).

It's this kind of reason I WANT to back up my account... because they don't demonstrate themselves able to deliver what I paid for.

**Comment by ElleKayEm** [comment]
Ah, didn't realize that ... the book shows that it's suppose to be available to Kindle for PC.  Hopefully they'll get it fixed.

**Comment by jtsgty** [comment]
I don't suppose there is another alternative that you can think of, is there?

**Comment by ElleKayEm** [comment]
The only other option for these tools would be if you have an E-ink Kindle (not a Fire).  But the images delivered to that might be lower res.

But since it can also be read on Comixology, you could use another tool: [comic-backup](https://github.com/Cortys/comic-backup).

**Comment by bobaf81** [comment]
Hi I’ve successfully de drm’d a kindle comic using the tool through calibre. However all files downloaded to the kindle for Mac app are very small and in SD format not HD. Anyone know a way round this?
