### ISSUE TITLE
Plug-in won't work

### ISSUE THREAD

**Issue by Maradadi** [apprenticeharper/DeDRM_tools#622]
Hi, I've gone through the process twice and used Calibre in de-bug mode. I bought the mobi version from Amazon.com today of "Make a Killing on Kindle 2018 Edition". It's an expensive ebook $9+ and Iwant to print off some of the chapters. I have a PC using Windows 10. Here is the log:

calibre Debug log
calibre 3.30  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 2)
calibre 3.30  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 5, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164557 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[2.97] main UI initialized...
[2.97] Hiding splash screen
[14.08] splash screen hidden
[14.08] Started up in 14.08 seconds with 792 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['1\xe0\xe18\xc4\xdei\x80\xc7\xb8\xa2V\x1d\xdc&\x05\xd1\xa50E;\x04\xc4\x8b\xa9f\xc2\x82"\x80\x99\xab', 'C:\\Users\\Dell\\Downloads\\Make A Killing On Kindle 2018 Edition_ Book #1 In The Killing It On Kindle Series.azw3']
DeDRM v6.5.2: Trying to decrypt Make A Killing On Kindle 2018 Edition_ Book #1 In The Killing It On Kindle Series.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Dell\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Dell\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3765492864' and UserName '44656c6c'
DeDRM v6.5.2: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 609, in run
  File "calibre_plugins.dedrm.__init__", line 559, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.2: Ultimately failed to decrypt after 0.3 seconds
Added Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series to db in: 2.7
Added 1 books in 4.1 seconds
Worker Launch took: 0.228000164032
Job: 1 Convert book 1 of 1 (Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series) finished
Convert book 1 of 1 (Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_es9dwy\\yplnez.opf'
	  cover: u'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_es9dwy\\0yqxju.jpeg'
	  output_profile: 'kindle_dx'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.30.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_es9dwy\\0yqxju.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'docx_custom_page_size': None,
	 'docx_no_cover': False,
	 'docx_no_toc': False,
	 'docx_page_margin_bottom': 72.0,
	 'docx_page_margin_left': 72.0,
	 'docx_page_margin_right': 72.0,
	 'docx_page_margin_top': 72.0,
	 'docx_page_size': u'letter',
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x053B3110>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x053B3490>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Dell\\AppData\\Local\\Temp\\calibre_es9dwy\\yplnez.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Dell\AppData\Local\Temp\calibre_es9dwy\isjkfe.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Make A Killing On Kindle 2018 Edition: Book #1 In The Killing It On Kindle Series

**Comment by ElleKayEm** [comment]
Looks like a book downloaded from the website.  For those, you need to choose an E-ink Kindle (not a Fire) and have its serial number in the plugin customization.  Or use a copy from Kindle for PC.  You're also using an old edition of DeDRM.  If you want to decrypt KFX files, you'll need the KFX Input plugin too.

**Comment by ElleKayEm** [comment]
First, upgrade to the current version of DeDRM.  Is the device you're choosing when you download the book an E-ink Kindle -- like a Paperwhite, Voyage, or Oasis -- not a Kindle Fire?  If so, you need to enter its serial number into the plugin customization.

If you don't have an E-ink Kindle, then you will need to download the book with Kindle for PC.  With recent versions, the books may be in a new format called KFX.  You can find out how to deal with that here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by Maradadi** [comment]
Thank you for taking the time to explain. I'll try that out tomorrow. Kind
regards.
