### ISSUE TITLE
Kindle azw3 import error

### ISSUE THREAD

**Issue by rsloss** [apprenticeharper/DeDRM_tools#625]
azw3 import fails
debug log follows:
calibre Debug log
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.9056047198 x 95.7486910995
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.20] main UI initialized...
[1.20] Hiding splash screen
[31.36] splash screen hidden
[31.36] Started up in 31.36 seconds with 284 books
DeDRM v6.6.1: Trying to decrypt The Storyteller's Secret_ A Novel.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Storyteller's Secret: A Novel
Got DSN key from database default_key
Found 6 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID NOQn94+YEA.
Decrypting. Please wait . . . . done
Decryption succeeded after 0.9 seconds
DeDRM v6.6.1: Finished after 0.9 seconds
Added 0 books in 2.4 seconds
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "site-packages\calibre\db\backup.py", line 54, in run
  File "site-packages\calibre\db\backup.py", line 116, in do_one
  File "site-packages\calibre\db\cache.py", line 63, in call_func_with_lock
  File "site-packages\calibre\db\cache.py", line 1154, in clear_dirtied
  File "site-packages\calibre\db\backend.py", line 844, in execute
  File "c:\t\t\apsw-j1n8vs\apsw-3.23.1-r1\src\cursor.c", line 236, in resetcursor
CantOpenError: CantOpenError: unable to open database file

**Comment by ElleKayEm** [comment]
Well, the DRM removal is successful, but calibre didn't save it.  Does it save them if you have DeDRM disabled?

**Comment by rsloss** [comment]
Ahh. Didn't notice that. Good eye.
Yep, this is a calibre issue. Disabled DeDRM and got same issue with an unecrypted PDF.
Please close this issue.
