### ISSUE TITLE
DRM and KFX Problem

### ISSUE THREAD

**Issue by PendragnJenna** [apprenticeharper/DeDRM_tools#628]
I'm in the process of switching to a new computer. I had DeDRM and KFX Input working fine on my old computer, but I'm getting the cannot convert message on the new computer. Can someone please let me know what's going awry or what I'm doing wrong? Thanks!

Here's the debug log:

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
EpubMerge: DEBUG: 2018-09-13 13:25:00,845: calibre_plugins.epubmerge.epubmerge_plugin(152): macmenuhack file_path:/Users/jennk/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
FFF: DEBUG: 2018-09-13 13:25:00,861: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:/Users/jennk/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 3.31  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && Set KFX metadata (from KFX Output) (1, 22, 0) && KFX Output (1, 22, 0) && Search The Internet (1, 7, 6) && Manage Series (1, 2, 8) && Goodreads (1, 1, 14) && Count Pages (1, 8, 2) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && Author Book Count (2, 1, 5) && User Category (1, 5, 3) && Consolidate All Library Metadata (2, 0, 32) && Author Book Count Hierarchy (1, 1, 8) && MultiColumnSearch (1, 0, 74) && EpubMerge (2, 3, 0) && Reading List (1, 6, 6) && FanFicFare (3, 0, 0) && Kindle covers (G) (0, 3, 0) && Find Duplicates (1, 6, 3) && EpubSplit (2, 5, 0) && Obok DeDRM (6, 5, 4)
calibre 3.31  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && Set KFX metadata (from KFX Output) (1, 22, 0) && KFX Output (1, 22, 0) && Search The Internet (1, 7, 6) && Manage Series (1, 2, 8) && Goodreads (1, 1, 14) && Count Pages (1, 8, 2) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0) && Author Book Count (2, 1, 5) && User Category (1, 5, 3) && Consolidate All Library Metadata (2, 0, 32) && Author Book Count Hierarchy (1, 1, 8) && MultiColumnSearch (1, 0, 74) && EpubMerge (2, 3, 0) && Reading List (1, 6, 6) && FanFicFare (3, 0, 0) && Kindle covers (G) (0, 3, 0) && Find Duplicates (1, 6, 3) && EpubSplit (2, 5, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
MCS has finished initialization...
[2.55] main UI initialized...
[2.55] Started up in 2.55 seconds with 4345 books
Gather KFX-ZIP (from KFX Input) 1.8.0: Importing /Users/jennk/Documents/Calibre Auto-Add/B07H4SC7V8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/2qoC67.kfx-zip
DeDRM v6.6.1: Trying to decrypt 2qoC67.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 2qoC67
Found 0 keys to try after 0.0 seconds
DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2011 file: /Users/jennk/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '55bd3db89cf1' and UserName 'jennk'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: 2qoC67
Got DSN key from database default_key_1
Found 1 keys to try after 0.4 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B07H4SC7V8_EBOK.azw has DRM and cannot be converted
2018-09-13 13:25:30.118 Calibre[3756:411079] deliverNotificationWithTitle()
* Notification delivered.
2018-09-13 13:25:46.426 calibre-debug[3725:410173] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_attributesForCharacterIndex:reply:) block performed very slowly (1.87 secs).
Package KFX (from KFX Input) 1.8.0: Packaging /var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/2qoC67.kfx-zip
Processing container: B07H4SC7V8_EBOK.azw
Worker Launch took: 0.0875980854034
Job: 1 Convert book 1 of 1 (B07H4SC7V8 EBOK) finished
Convert book 1 of 1 (B07H4SC7V8 EBOK)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/rfIP_J.opf'
	  output_profile: 'generic_eink'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.31.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x118523390>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x118523790>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/rfIP_J.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 198, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 95, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
	KFXDRMError: Book container B07H4SC7V8_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM!
	InputFormatPlugin: KFX Input running
	on /var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/0Uy_mX.kfx-zip
	Software versions: KFX Input 1.8.0, calibre 3.31, Darwin-17.7.0-x86_64-i386-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/r0/xvg97jzj5m109ncpr5kfj1m40000gn/C/calibre_3.31.0_tmp_qOPOLc/0Uy_mX.kfx-zip
	Processing container: B07H4SC7V8_EBOK.azw
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by j-howell** [comment]
See the error:

>> Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.

It looks like you are using a configured folder to automatically add books to calibre that are added to it. That won't work with books in KFX format.

You need to add the main book file (.azw) from its original location in a subfolder of My Kindle Content. You can do that using drag and drop or "Add books from a single directory".

If instead you insist on using auto-add you can zip the contents of the book's subfolder under My Kindle Content, change the extension from .zip to .kfx-zip, and then place that in the auto-add folder.

**Comment by PendragnJenna** [comment]
Thank you! I'll change how I add my books.
