### ISSUE TITLE
Not removing DRM from Google Play book?

### ISSUE THREAD

**Issue by stevendesu** [apprenticeharper/DeDRM_tools#638]
I downloaded a book from Google Play. Despite the Google Play link claiming it was an EPUB, it downloaded an ACSM file.

I opened this file in Adobe Digital Editions, then found the EPUB had been created on my hard drive.

I installed DeDRM 6.6.1 to Calibre Portable 3.31.0

I then dragged the EPUB into my Calibre library, which I'm to understand is all I need to do in order to strip DRM, but when I attempted to read the book it said that the book was locked by DRM.

![calibre-drm-fail](https://user-images.githubusercontent.com/1384974/45920426-e0638300-be71-11e8-80b9-fd6579e515f9.jpg)

![calibre-drm-fail2](https://user-images.githubusercontent.com/1384974/45920432-f709da00-be71-11e8-9dbc-41c3d012112d.jpg)

What am I doing wrong?

**Comment by ElleKayEm** [comment]
Was ADE authorized with an Adobe ID?  Is it on the same machine and user as calibre with DeDRM?

**Comment by stevendesu** [comment]
@ElleKayEm ADE ***was*** authorized with my Adobe ID (in fact, doing so caused it to download 50-something books that my wife purchased on the account), and everything was done on the same computer which only has one user.

**Comment by ElleKayEm** [comment]
I'd try a complete uninstall and reinstall of ADE. See issue #348 for the details of what worked for someone else.

While I haven't heard of Google Play using the newer Adobe DRM, it's recommended to use ADE 2.0.1 so you don't get stuck with DRM that can't be removed (yet).

**Comment by stevendesu** [comment]
>uninstall and reinstall of ADE

Will give this a try when I'm back home, but it'll be a while. Unfortunately I was leaving on a two-week trip and trying to get the DRM off my ebooks before I had to fly out this morning so I could read them on my Kindle. Ended up just bringing a Nintendo DS for entertainment, instead.

I'll follow up in two weeks with the results.

**Comment by kswirydo** [comment]
Same here! I am using mac and my book was purchased from Google Play Books (NEVER AGAIN!!!). Authorized ADE with my user id. Downoaded book in acsm and converted to epub. Epub opens (also in calibra) but the same exact window with "Cannot convert, DRM protected" shows :( Everything on the same exact computer.

**Comment by ElleKayEm** [comment]
@kswirydo 
No luck trying what I suggest above?  The issue I linked to was on Windows and involved deleting a registry key -- not sure what the equivalent would be on a Mac.

**Comment by stevendesu** [comment]
I forgot about this issue until these two comments just showed up in my email :smile: I'll set a reminder / alarm to go test re-installing ADE after work today. Will report back tonight with the results.

**Comment by stevendesu** [comment]
So last night I got done with work extremely late, but I did find time to uninstall ADE and reinstall it. I just ran into more issues and went to bed angry instead of posting here.

Upon uninstalling and reinstalling ADE I tried to re-import my ACSM file and got the following error:

![google-device-limit-reached](https://user-images.githubusercontent.com/1384974/49657958-e3045c00-fa0e-11e8-982e-8efed47ed087.jpg)

I may eventually give up and try to find these same e books somewhere else (not Google) that respects a consumer's right to products they pay for

**Comment by ElleKayEm** [comment]
You can contact Google and have them reset your number of devices.  Details here:

https://productforums.google.com/d/msg/play/IahWn_4mh8A/NlE8YLR8AgAJ

**Comment by JulieUK** [comment]
I've just updated Calibre and my DeDRM tools because an epub that I downloaded from Google Play Books failed to have its DRM removed when I added it to Calibre.  It does open fine in Adobe Digital Editions, and Calibre regularly handles ADE books that I borrow from the library and then transfer to a Kindle to read.

Here is the Debug output file contents:

> calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46&#126;18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
calibre 4.23  embedded-python: True is64bit: True
Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '5.4.0-42-generic', '#46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 8, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.5388994307 x 92.6756756757
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[1.22] main UI initialized...
[1.22] Hiding splash screen
[12.44] splash screen hidden
[12.44] Started up in 12.44 seconds with 252 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=90177559', '--filename=/home/julie/Documents/My Digital Editions/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | <snip>]
DeDRM v6.8.0: Trying to decrypt A_History_of_Modern_Britain.epub
DeDRM v6.8.0: Verifying zip archive integrity
DeDRM v6.8.0: “A_History_of_Modern_Britain.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 636, in run
  File "calibre_plugins.dedrm.__init__", line 412, in ePubDecrypt
DeDRMError: DeDRM v6.8.0: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
Added A History of Modern Britain to db in: 0.3
Added 1 books in 1.0 seconds

Thoughts?

**Comment by ElleKayEm** [comment]
@JulieUK 
DeDRM isn't registering that book as having Adobe DRM (at least not setup the way it expects).  Did you download the ACSM and open it with Adobe Digital Editions authorized with your Adobe ID?

**Comment by JulieUK** [comment]
Well, yes and no.  Google Play Books produced an unusual ACSM (compared with, say, the ones I get from my library) and ADE didn't seem to know what to do with it, TBH.  It kept showing a download error quoting a long URL. I pasted that URL into a browser address bar, and it happily handed me an ePub file which I saved.  I could then open it in ADE and read it, but when I added it to Calibre and tried to view it, I got the standard DRM error message.

**Comment by ElleKayEm** [comment]
I don't know how to get that decrypted.  When downloaded like that, the rights.xml (part of the DRM) will be missing from inside the epub.  I don't know where that info is stored instead, and DeDRM won't be able to decrypt it without that.

**Comment by JulieUK** [comment]
Hmm, tricky.  I did wonder if ADE might change the file when it opened it.  I wanted to try this same procedure with another ACSM file but discovered that regular ACSM files do not just contain the URL for the ePub inside a neat little tag (which ADE is choking on for reasons unknown).

I've bounced this one on to the Google community - just the bit about getting ADE to open the file, not the bit about DeDRM not working. ;-) No one else seemed to have reported it under these specific circumstances so I'd be interested to see what they come up with.

**Comment by ElleKayEm** [comment]
I'll be curious to hear what they say too.
