### ISSUE TITLE
Can't DeDRM A Book

### ISSUE THREAD

**Issue by rudenik** [apprenticeharper/DeDRM_tools#640]
Hi there, 

I'm trying to use the plugin and am getting an error when I try and convert it. Here's the  log file from the debug log. 

calibre Debug log
calibre 3.31  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
calibre 3.31  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 8, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 8, 0) && KFX Input (1, 8, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
[1.88] main UI initialized...
[1.88] Hiding splash screen
[1.89] splash screen hidden
[1.89] Started up in 1.89 seconds with 2 books
Gather KFX-ZIP (from KFX Input) 1.8.0: Importing /Users/student/Library/Application Support/Kindle/My Kindle Content/B00J6YBOFQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B00J6YBOFQ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Zero to One: Notes on Startups, or How to Build the Future
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/student/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.6.1: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
2018-09-24 15:28:02.467 Calibre[28860:170929] deliverNotificationWithTitle()
* Notification delivered.
Added Zero to One: Notes on Startups, or How to Build the Future to db in: 0.1
Added 1 books in 3.3 seconds
Worker Launch took: 0.133553981781
Job: 1 Convert book 1 of 1 (Zero to One: Notes on Startups, or How to Build the Future) finished
Convert book 1 of 1 (Zero to One: Notes on Startups, or How to Build the Future)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/9w/pjsvb0zx2n51s76j0m07xxd40000gn/C/calibre_3.31.0_tmp_Qx74T7/dRk6fX.opf'
	  output_profile: 'tablet'
	  verbose: 2
	  cover: u'/var/folders/9w/pjsvb0zx2n51s76j0m07xxd40000gn/C/calibre_3.31.0_tmp_Qx74T7/fn5zeB.jpeg'
	Resolved conversion options
	calibre version: 3.31.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/9w/pjsvb0zx2n51s76j0m07xxd40000gn/C/calibre_3.31.0_tmp_Qx74T7/fn5zeB.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11c9e3810>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x11c9f4450>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/9w/pjsvb0zx2n51s76j0m07xxd40000gn/C/calibre_3.31.0_tmp_Qx74T7/dRk6fX.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose

**Comment by ElleKayEm** [comment]
That was downloaded with installation of Kindle for Mac currently on the same machine and user as calibre with DeDRM?

**Comment by rudenik** [comment]
No different computer, but I copied over the application support kindle folder.
