### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by strikethehour** [apprenticeharper/DeDRM_tools#643]
This plug-in used to work perfectly for me but I haven't had it work in years. I just downloaded the latest version and tried again, and still nothing. I'm thinking it may be because I use a very old version of kindle—maybe I should download an older version of DeDRM? Here is the log:

calibre Debug log
calibre 3.32  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && EpubSplit (2, 2, 1)
calibre 3.32  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && EpubSplit (2, 2, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
[1.65] splash screen hidden
[1.65] Started up in 1.65 seconds with 60 books
DeDRM v6.6.1: Trying to decrypt We Are Okay_B01K1ATZ36.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: We Are Okay
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/magdalena/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'b578148f7e30' and UserName 'magdalena'
DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added We Are Okay to db in: 0.0
Added 1 books in 1.1 seconds
2018-09-28 00:08:16.274 Calibre[5970:142138] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.105515003204

{'bsd_drives': {'main': u'/dev/disk2s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1': '/',
               '/dev/disk2s1': '/Volumes/Kindle',
               '/dev/disk3s1': '/Volumes/calibre-3.32.0',
               'devfs': '/dev',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 2 Get device information started
DeviceJob: 2 Get device information done, calling callback
DeviceJob: 2 Get device information callback returned
Job: 3 Set library information started
DeviceJob: 3 Set library information done, calling callback
DeviceJob: 3 Set library information callback returned
Job: 4 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 12, count of files in metadata: 12, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 4 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 12
DeviceJob: set_books_in_library finished: time= 0.0113170146942
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 4 Get list of books on device callback returned
Job: 4 Get list of books on device finished
No details available.
Job: 2 Get device information finished
No details available.
Job: 3 Set library information finished
No details available.

**Comment by ElleKayEm** [comment]
Are you talking about a Kindle device?  As long as it's an E-ink Kindle and not a Fire, you just need to put its serial number into the plugin customization.
