### ISSUE TITLE
Can add .kfx-zip; cannot view or convert to .epub

### ISSUE THREAD

**Issue by readyready15728** [apprenticeharper/DeDRM_tools#644]
So I have followed the steps on installing the latest DeDRM and the KFX add-on that still seems to be necessary even though KFX support appears in the DeDRM base code. I also have a .kfx-zip assembled  from four .kfx files I was able to pull from my Android phone. What's weird is that I get a thumbnail view of the cover as well as metadata, indicating that the process succeeded on some level. However, the log output is pretty dismal:

```
DeDRM v6.6.1: Trying to decrypt dsfs.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: dsfs
Found 0 keys to try after 0.3 seconds
DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
DeDRM v6.6.1: Running kindlekey.py under Wine
DeDRM v6.6.1: Command line: 'WINEPREFIX="/home/muhammad/Downloads" wine python.exe "/home/muhammad/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/muhammad/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
err:wineboot:main Cannot set the dir to L"C:\\windows" (2)
err:process:init_windows_dirs directory L"C:\\windows" could not be created, error 2
err:process:init_windows_dirs directory L"C:\\windows\\system32" could not be created, error 3
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.6.1: Found and decrypted 0 key files
DeDRM v6.6.1: Ultimately failed to decrypt after 26.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
    nfp = plugin.run(path_to_file)
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 26.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.8.0: Packaging /home/muhammad/Downloads/dsfs.kfx-zip
Processing container: CR!95JGVVGJ1X45QA45GXXG17ZREG3A.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 154, in _run_filetype_plugins
    nfp = plugin.run(path_to_file)
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container CR!95JGVVGJ1X45QA45GXXG17ZREG3A.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /home/muhammad/Downloads/dsfs.kfx-zip
```

If I try to open the book, it just opens Archive Manager and I see a bunch of .kfx files, not a book. I also can't convert to .epub. Here's more log output though I'm not sure what it means:

```
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/notify.py", line 74, in __call__
    timeout)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.419 was not provided by any .service files
```

I've heard I might need to add a key of some sort but I'm not sure how to do that for the original platform in question (Android).

**Comment by j-howell** [comment]
There are several problems.

>> DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

There will be a voucher file in the book's folder along with the kfx files. That is needed for decryption and must be included in the kfx-zip.

>> I've heard I might need to add a key of some sort but I'm not sure how to do that for the original platform in question (Android).

The DeDRM tools no longer work for the Kindle for Android app. See the FAQ: [Why don't the tools work with Kindle for Android ebooks?](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#why-dont-the-tools-work-with-kindle-for-android-ebooks)

If you do not own an e-ink Kindle device then you will need to use Kindle for PC or Kindle for Mac to download the book, instead of the Android app.

Once you have removed DRM you will still be left with a kfx-zip file. You need to use the KFX Input plugin in calibre to convert that into something useful.
