### ISSUE TITLE
'module' object has no attribute 'LZMADecompressor'

### ISSUE THREAD

**Issue by raffam** [apprenticeharper/DeDRM_tools#646]
> DeDRM v6.6.1: Processing: B00AKE1QK4_EBOK.kfx-zip...
> Decrypting KFX-ZIP ebook: B00AKE1QK4_EBOK
> Got DSN key from database C:\Users\raffa\AppData\Local\DeDRMPrefs\kindlekey.k4i
> Found 1 keys to try after 0.0 seconds
> Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.aa5bdb41-4945-4b81-a93b-0999c297e652.voucher
> KFX DRM voucher successfully decrypted
> Decrypting KFX DRMION: B00AKE1QK4_EBOK.azw
> Error decrypting book after 0.0 seconds: 'module' object has no attribute 'LZMADecompressor'
> Traceback (most recent call last):
>   File "D:\data\programmi\DeDRM_tools\src\k4mobidedrm.py", line 259, in decryptBook
>     book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
>   File "D:\data\programmi\DeDRM_tools\src\k4mobidedrm.py", line 233, in GetDecryptedBook
>     mb.processBook(totalpids)
>   File "D:\data\programmi\DeDRM_tools\src\kfxdedrm.py", line 48, in processBook
>     ion.DrmIon(StringIO(data[8:-8]), lambda name: self.voucher).parse(outfile)
>   File "D:\data\programmi\DeDRM_tools\src\ion.py", line 954, in parse
>     self.processpage(ct, civ, outpages, decompress)
>   File "D:\data\programmi\DeDRM_tools\src\ion.py", line 981, in processpage
>     decomp = lzma.LZMADecompressor(format=lzma.FORMAT_ALONE)
> AttributeError: 'module' object has no attribute 'LZMADecompressor'
> DeDRM v6.6.1: Failed
> 
> DeDRM v6.6.1: Complete:  Successes: 0, Failures: 1

**Comment by raffam** [comment]
So I solved it by downloading the Backports.lzma wheel from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#backports.lzma) and installing the wheel using pip
