### ISSUE TITLE
Failed to decrypt KFX DRM voucher with any key

### ISSUE THREAD

**Issue by someone235** [apprenticeharper/DeDRM_tools#653]
Hi, I get the above error when adding a book.
The full log is attached.
Thanks in advance.

```
calibre Debug log
calibre 3.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
calibre 3.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.453781513 x 102.358208955
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[1.95] main UI initialized...
[1.95] Hiding splash screen
[4.62] splash screen hidden
[4.62] Started up in 4.62 seconds with 1 books
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90D4220434370G7C&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=2)
{u'drive_letters': ['D'],
 u'pnp_id_map': {'D': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90d4220434370g7c&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'D': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.1 USBMS: scan from root False D:\documents
DEBUG:    0.2 USBMS: count found in cache: 109, count of files in metadata: 109, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 109
DeviceJob: set_books_in_library finished: time= 0.00800013542175
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 2 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfeOZ_9\x02%\x86\x84\x06\x99xV\xcf&\xef\xe2Z"&\xb1\xf2\x99n\xf2J\xaa+\xa6\xdb\x8b\x16', "D:\\documents\\The Hitchhiker's Guide to the Galaxy_B003GK2180.kfx"]
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing D:\documents\The Hitchhiker's Guide to the Galaxy_B003GK2180.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\kobit\AppData\Local\Temp\calibre_lzkqg9\egozdm.kfx-zip
DeDRM v6.6.1: Trying to decrypt egozdm.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: egozdm
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kobit\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.9.0: Packaging C:\Users\kobit\AppData\Local\Temp\calibre_lzkqg9\egozdm.kfx-zip
Processing container: CR!YC3365XHDX15F55AJGEZEDCTMPGH.kfx
Processing container: The Hitchhiker's Guide to the Galaxy_B003GK2180.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container The Hitchhiker's Guide to the Galaxy_B003GK2180.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\kobit\AppData\Local\Temp\calibre_lzkqg9\n09yks_add_books\0\The Hitchhiker's Guide to the Galaxy_B003GK2180.kfx-zip
Added The Hitchhiker's Guide to the Galaxy to db in: 2.2
Added 1 books in 3.1 seconds
```

**Comment by ElleKayEm** [comment]
Is it from an E-ink Kindle?  If so, you need to enter its serial number into the plugin customization.

**Comment by ElleKayEm** [comment]
Yup, only works from an E-ink Kindle (not a Fire) if you have its serial number correctly entered into the plugin customization.  Otherwise, use a copy from Kindle for PC/Mac.
