### ISSUE TITLE
DeDRM plug in - not working

### ISSUE THREAD

**Issue by ylonka** [apprenticeharper/DeDRM_tools#655]
I have calibre ver. 3.32 and today installed DeDRM 6.6.1. Been using Kindle for PC when buying books from Amazon. Until a month ago I've never had a problem with conversion, however, today it doesn't seem to work. I haven't found an older version of the app (1.17 was recommended; I've got 1.24).
The log is below. Thanks for your help.

calibre Debug log
calibre 3.32  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 5, 3) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
calibre 3.32  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 5, 3) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.2156448203 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
[1.45] main UI initialized...
[1.45] Hiding splash screen
[16.67] splash screen hidden
[16.67] Started up in 16.67 seconds with 34 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe4\x9e\xbb\x1f\xca\xf1\xe4\x10\xa8%[)\xdc\x18\x15R\x92\xe9\x7fg\xfaU\xc0gEP<\xe4\xaa\xady\x99', 'C:\\Users\\ylonk\\Documents\\My Kindle Content\\B078VW7QSD_EBOK\\B078VW7QSD_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing C:\Users\ylonk\Documents\My Kindle Content\B078VW7QSD_EBOK\B078VW7QSD_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\zg0dxc.kfx-zip
DeDRM v6.5.3: Trying to decrypt zg0dxc.kfx-zip
Unknown booktype kfx-zip. Passing back to calibre unchanged
Package KFX (from KFX Input) 1.9.0: Packaging C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\zg0dxc.kfx-zip
Processing container: B078VW7QSD_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B078VW7QSD_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\nnksat_add_books\0\B078VW7QSD_EBOK.kfx-zip
Added The Lies We Told to db in: 0.2
Added 1 books in 0.7 seconds
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x91(x\xc1\xed\x03\x87\x82\xd4\r\x12\xd2q\x1a\xbb\x0fk\xac\x9d\xfa\x99\xa9\xb0\x04\x1c~#\x01L\xd7a\xea', 'C:\\Users\\ylonk\\Documents\\My Kindle Content\\B074CH1CDH_EBOK\\B074CH1CDH_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing C:\Users\ylonk\Documents\My Kindle Content\B074CH1CDH_EBOK\B074CH1CDH_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\jnvgfl.kfx-zip
DeDRM v6.5.3: Trying to decrypt jnvgfl.kfx-zip
Unknown booktype kfx-zip. Passing back to calibre unchanged
Package KFX (from KFX Input) 1.9.0: Packaging C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\jnvgfl.kfx-zip
Processing container: B074CH1CDH_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B074CH1CDH_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ylonk\AppData\Local\Temp\calibre_mhefjp\hl8cc1_add_books\0\B074CH1CDH_EBOK.kfx-zip
Added The Friend: An emotional psychological thriller with a twist to db in: 0.2
Added 1 books in 0.8 seconds

**Comment by j-howell** [comment]
The log shows that you have DeDRM version 6.5.3 installed. You need the latest version (6.6.1) to handle KFX files.

**Comment by ylonka** [comment]
Thanks. I've just downloaded and installed 6.6.1; no clue why it didn't get installed yesterday. Anyway, the conversion still didn't work. Found and download Kindle app 1.17 and managed to convert the books, but they were in AZW3 format.
