### ISSUE TITLE
Linux - error with deDRM

### ISSUE THREAD

**Issue by larkaa** [apprenticeharper/DeDRM_tools#660]
I'm having some issues converting azw books with the plugins and I'm not sure what the issue is. Attached is a log of when I tried to import one file. It says decryption successful, but the file remains in azw after importing. 

calibre Debug log
calibre 2.55  embedded-python: False is64bit: True
Linux-4.4.0-137-generic-x86_64-with-Ubuntu-16.04-xenial Linux ('64bit', 'ELF')
('Linux', '4.4.0-137-generic', '#163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018')
Python 2.7.12
Linux: ('Ubuntu', '16.04', 'xenial')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) && DeDRM && Package KFX (from KFX Input) && KFX metadata reader (from KFX Input) && KFX Input && Find Duplicates
Starting up...
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Switch/create library..." under id 39
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Calibre Library" under id 67
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Calibre Library" under id 68
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Calibre Library" under id 69
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Calibre Library" under id 46
[31mvoid DBusMenuExporterPrivate::addAction(QAction*, int)[0m: Already tracking action "Help" under id 66
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/kindle/driver.py", line 115, in metadata_from_path
    mi = read_metadata_kfx(f)
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 270, in read_metadata_kfx
    m = extract_metadata(c.decode())
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 251, in extract_metadata
    for value1 in entity_value[PROP_METADATA3]:
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 235, in update_booklist
    if bl.add_book(self.book_from_path(prefix, lpath),
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 536, in book_from_path
    book = cls.book_class(prefix, lpath, other=mi, size=size)
  File "/usr/lib/calibre/calibre/devices/usbms/books.py", line 39, in __init__
    if other:
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 786, in __nonzero__
    return bool(self.title or self.author or self.comments or self.tags)
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 149, in __getattribute__
    'Metadata object has no attribute named: '+ repr(field))
AttributeError: Metadata object has no attribute named: 'author'
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/kindle/driver.py", line 115, in metadata_from_path
    mi = read_metadata_kfx(f)
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 270, in read_metadata_kfx
    m = extract_metadata(c.decode())
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 251, in extract_metadata
    for value1 in entity_value[PROP_METADATA3]:
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 235, in update_booklist
    if bl.add_book(self.book_from_path(prefix, lpath),
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 536, in book_from_path
    book = cls.book_class(prefix, lpath, other=mi, size=size)
  File "/usr/lib/calibre/calibre/devices/usbms/books.py", line 39, in __init__
    if other:
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 786, in __nonzero__
    return bool(self.title or self.author or self.comments or self.tags)
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 149, in __getattribute__
    'Metadata object has no attribute named: '+ repr(field))
AttributeError: Metadata object has no attribute named: 'author'
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/kindle/driver.py", line 115, in metadata_from_path
    mi = read_metadata_kfx(f)
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 270, in read_metadata_kfx
    m = extract_metadata(c.decode())
  File "/usr/lib/calibre/calibre/ebooks/metadata/kfx.py", line 251, in extract_metadata
    for value1 in entity_value[PROP_METADATA3]:
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 235, in update_booklist
    if bl.add_book(self.book_from_path(prefix, lpath),
  File "/usr/lib/calibre/calibre/devices/usbms/driver.py", line 536, in book_from_path
    book = cls.book_class(prefix, lpath, other=mi, size=size)
  File "/usr/lib/calibre/calibre/devices/usbms/books.py", line 39, in __init__
    if other:
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 786, in __nonzero__
    return bool(self.title or self.author or self.comments or self.tags)
  File "/usr/lib/calibre/calibre/ebooks/metadata/book/base.py", line 149, in __getattribute__
    'Metadata object has no attribute named: '+ repr(field))
AttributeError: Metadata object has no attribute named: 'author'
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing /home/larkaa/Downloads/Verdi With a Vengeance_ An Energetic Guide to the Life and Complete Works of the King of Opera (Vintage Original).azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt Verdi With a Vengeance_ An Energetic Guide to the Life and Complete Works of the King of Opera (Vintage Original).azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Verdi With a Vengeance: An Energetic Guide to the Life and Complete Works of the King of Opera (Vintage Original)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID 5/UZh0aTVR.
Decrypting. Please wait . . . . . done
Decryption succeeded after 0.0 seconds
DeDRM v6.6.1: Finished after 0.0 seconds

**Comment by larkaa** [comment]
Updating Calibre solved it! Thanks!
