### ISSUE TITLE
Unable to de-DRM Kindle publications through Calibre plugin (Windows)

### ISSUE THREAD

**Issue by DefiantCatgirl** [apprenticeharper/DeDRM_tools#663]
Windows 10, Kindle for PC, Calibre 3.32, DeDRM 6.61 (though same happened with older versions)

De-DRM-ing this file through the standalone script for Windows works fine, that's my usual workaround.

Tried both the auto-generated key file and the key file that the standalone script generates, to no avail.

```
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing C:/Users/Artemiy/Documents/My Kindle Content/B07JPH5XWL_EBOK/B07JPH5XWL_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B07JPH5XWL_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright ﾂｩ 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 髮ｻ謦・・繧ｪ繧ｦ 2018蟷ｴ12譛亥捷 [髮題ｪ珪
Got DSN key from database default_key
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\Artemiy\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Artemiy\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3437607810' and UserName '417274656d6979'
DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 電撃マオウ 2018年12月号 [雑誌] to db in: 2.9
Added 1 books in 4.9 seconds
```

**Comment by ElleKayEm** [comment]
The Kindle for PC installation where you downloaded the book, calibre with DeDRM, and the stand-alone DeDRM app are all on the same machine and user?  Because each installation of the app (and each device) has its own unique key.

I think the DeDRM plugin might be picking up a key from a previous installation.  Try these instructions for completely uninstalling and reinstalling Kindle for PC:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by DefiantCatgirl** [comment]
They all run on the same machine and user. I even manually imported the same key that works just fine with the standalone script from the same version. Or are the k4i keys incompatible between the script and the Calibre plugin?

I'll try a clean reinstall and see if that works...

**Comment by DefiantCatgirl** [comment]
Uninstalled, deleted directories, deregistered, reinstalled plugin, redownloaded book, same.

```
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing C:/Users/Artemiy/Documents/My Kindle Content/B07GSNKHM1_EBOK/B07GSNKHM1_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B07GSNKHM1_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright ﾂｩ 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 髮ｻ謦・・繧ｪ繧ｦ 2018蟷ｴ10譛亥捷 [髮題ｪ珪
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Artemiy\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Artemiy\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3437607810' and UserName '417274656d6979'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright ﾂｩ 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 髮ｻ謦・・繧ｪ繧ｦ 2018蟷ｴ10譛亥捷 [髮題ｪ珪
Got DSN key from database default_key_1
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added 電撃マオウ 2018年10月号 [雑誌] to db in: 1.9
Added 1 books in 4.2 seconds
Worker Launch took: 0.138000011444
```

**Comment by ElleKayEm** [comment]
Huh, still seems to be finding an old key.
