### ISSUE TITLE
Unable to de-DRM new Kindle magazines (Windows)

### ISSUE THREAD

**Issue by DefiantCatgirl** [apprenticeharper/DeDRM_tools#664]
Windows 10, Kindle for PC, DeDRM 6.61 (though same happens with older versions)

The older issues of the same magazine are getting decrypted just fine through the standalone script, however a fresh one that was just recently published is no longer getting decrypted.

Cannot provide a useful log because I can't get the Calibre plugin to work in the first place - as per https://github.com/apprenticeharper/DeDRM_tools/issues/663 (using the same magazine as an example, it's the same log there regardless of whether it works with the standalone script or not)

The standalone script only writes in the console the following whether the decryption was successful or not:
```
Using Library AlfCrypto DLL/DYLIB/SO
No nook Study log files have been found.
Using Library AlfCrypto DLL/DYLIB/SO
```

**Comment by ElleKayEm** [comment]
A log file wasn't created in your user folder?  I know a lot of people are having trouble with the last couple releases of the stand-alone apps.

**Comment by DefiantCatgirl** [comment]
Oh, there it was, apologies for not reading the docs attentively enough. Unfortunately the log doesn't seem to be too helpful either.

```
DeDRM v6.6.1: Processing: B07JPH5XWL_EBOK.azw...
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 電撃マオウ 2018年12月号 [雑誌]
Got DSN key from database C:\Users\Artemiy\AppData\Local\DeDRMPrefs\kindlekey.k4i
Got DSN key from database C:\Users\Artemiy\AppData\Local\DeDRMPrefs\kindlekey1.k4i
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
Error decrypting book after 0.7 seconds: No key found in 4 keys tried.
Traceback (most recent call last):
  File "D:\Downloads\Software\Ripping\DeDRM_tools_6.6.1\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 259, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "D:\Downloads\Software\Ripping\DeDRM_tools_6.6.1\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\k4mobidedrm.py", line 233, in GetDecryptedBook
    mb.processBook(totalpids)
  File "D:\Downloads\Software\Ripping\DeDRM_tools_6.6.1\DeDRM_Windows_Application\DeDRM_App\DeDRM_lib\lib\mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
DeDRM v6.6.1: Failed

DeDRM v6.6.1: Complete:  Successes: 0, Failures: 1
```

**Comment by ElleKayEm** [comment]
Do fresh copies of the old issues work?

**Comment by DefiantCatgirl** [comment]
Yes, I re-downloaded an old issue and it was decrypted successfully, although only from the second attempt for some reason.

**Comment by ElleKayEm** [comment]
Was this only with the stand-alone again?  And was the old issue downloaded with the same K4PC installation as the new issue?

**Comment by DefiantCatgirl** [comment]
Only with the stand-alone (these really are different issues, I think), and both the working and non-working issues were downloaded with the same fresh K4PC installation, yes.

**Comment by DefiantCatgirl** [comment]
> Hmm, books downloaded with the same app should unlock with the same key.

Hence why I suspect there might have been some changes to the encryption or something, although when I downgraded K4PC to 1.17 it still opened the magazine fine, and I still wasn't able to have it decrypted... It's a mystery to me as well, so far.

Don't think this is directly related to #663, I created that one since I thought solving it might provide a more useful log, but you helped me find the standalone logs already.

**Comment by DefiantCatgirl** [comment]
Just as an addition, the newer issues of the same magazine are being decrypted successfully, the problem was only with that particular issue so far. I blame the filesize, the other ones were below 350-420 MB, and the problematic one was 480 MB.

Got most of the pages out of the .res file anyway, so not a huge deal in the end.

**Comment by ElleKayEm** [comment]
Might be able to do it with 64-bit calibre and the plugin if you haven't tried that.

**Comment by DefiantCatgirl** [comment]
That was a brilliant idea, thanks! Baffled that I didn't think of trying this since this was a memory issue. 

While I can't get Calibre to work with DeDrm for reasons beyond my comprehension - I have tried everything - running the standalone in a 64-bit Python environment does seem to do the trick. I don't have that particular magazine, but I had the same problem with a new one (450 MB) and it decrypted perfectly fine when I switched to Python 2.7 64-bit.
