### ISSUE TITLE
Unable to convert kfx-zip to azw3

### ISSUE THREAD

**Issue by morimodi** [apprenticeharper/DeDRM_tools#665]
Hi, I have installed DeDRM 6.6.1 and KFX input to Cailbre, when I started to convert kfx-zip to azw3 or other formats, it showed a pop-up window about failing to convert. My devices are Kindle oasis 7 and Mac OS 10.4. Please tell me if I do something wrong, thanks!

Here is the log:
`calibre Debug log
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
calibre 3.33.1  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
[1.16] splash screen hidden
[1.18] Started up in 1.18 seconds with 1 books
objc[9313]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8efda1d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11e80bdc8). One of the two will be used. Which one is undefined.
2018-10-27 18:09:10.505 Calibre[9324:3170527] deliverNotificationWithTitle()
* Notification delivered.
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container 马克思与《资本论》_B07CZMNS6T.kfx has DRM and cannot be converted
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing /Volumes/Kindle/documents/Downloads/Items01/马克思与《资本论》_B07CZMNS6T.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/GrcRAA.kfx-zip
Package KFX (from KFX Input) 1.9.0: Packaging /var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/GrcRAA.kfx-zip
Processing container: CR!JPZW07TYRH0D75SN1JXYADPRY70Z.kfx
Processing container: metadata.kfx
Processing container: 马克思与《资本论》_B07CZMNS6T.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/YMw3LX_add_books/0/马克思与《资本论》_B07CZMNS6T.kfx-zip

{'bsd_drives': {'main': u'/dev/disk8'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/Applications/SketchUp 2018/SketchUp.app': '/private/var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/T/AppTranslocation/1D010045-E313-4707-AD19-B410EA65B3EF',
               '/dev/disk1s1': '/',
               '/dev/disk1s4': '/private/var/vm',
               '/dev/disk2s1': '/Volumes/calibre-3.33.1',
               '/dev/disk3s2': '/Volumes/Autodesk AutoCAD 2017 for Mac [kg]',
               '/dev/disk4s1': '/Volumes/Autodesk AutoCAD 2017 for Mac Installation',
               '/dev/disk5s2': '/Volumes/\xe7\x99\xbe\xe5\xba\xa6\xe7\xbd\x91\xe7\x9b\x98',
               '/dev/disk6s2': '/Volumes/SketchUp 2018 by Appked',
               '/dev/disk7s1': '/Volumes/gutenprint-5.2.14',
               '/dev/disk8': '/Volumes/Kindle',
               'devfs': '/dev',
               'drivefs': '/Volumes/GoogleDrive',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 11, count of files in metadata: 11, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 11
DeviceJob: set_books_in_library finished: time= 0.00992012023926
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Added 马克思与《资本论》 to db in: 0.0
Added 1 books in 0.6 seconds
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
2018-10-27 18:10:43.285 Calibre[9328:3172214] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.124251127243
Job: 4 Convert book 1 of 1 (马克思与《资本论》) finished
Convert book 1 of 1 (马克思与《资本论》)
	Conversion options changed from defaults:
	  verbose: 2
	  cover: u'/var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/Bs0hhC.jpeg'
	  output_profile: 'kindle'
	  read_metadata_from_opf: u'/var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/is9RAA.opf'
	Resolved conversion options
	calibre version: 3.33.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/Bs0hhC.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x119cc7a90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x119cd8190>,
	 'page_breaks_before': u'/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/is9RAA.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init__", line 200, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 95, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
	KFXDRMError: Book container 马克思与《资本论》_B07CZMNS6T.kfx has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM!
	InputFormatPlugin: KFX Input running
	on /var/folders/jj/jvw60yzx7zb3_3xqpn6_fgsh0000gn/C/calibre_3.33.1_tmp_sUqO4L/Q5wvhj.kfx-zip`

**Comment by j-howell** [comment]
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && Package KFX (from KFX Input) (1, 9, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0)

Your log shows that the DeDRM plugin is not installed. You need to install the latest version of that plugin and configure it with the serial number of your kindle device.

**Comment by morimodi** [comment]
Thank you! Now it works successfully,

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
