### ISSUE TITLE
DeDRM Not Working - Kindle Windows

### ISSUE THREAD

**Issue by RocklinJP** [apprenticeharper/DeDRM_tools#666]
I am using Windows PC, downloading to USB files, added DeDRM 6.6.1 and Obok DeDrm plugins to Calibre. Removed all attempts and tried again several times with no success on any book. 

calibre Debug log
calibre 3.33.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
calibre 3.33.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 83.2218430034 x 83.1272727273
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.52] main UI initialized...
[1.52] Hiding splash screen
[8.91] splash screen hidden
[8.91] Started up in 8.91 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt The Forbidden Door_ A Jane Hawk Novel.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: The Forbidden Door: A Jane Hawk Novel
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\jene_\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\jene_\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '206908848' and UserName '6a656e655f'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: The Forbidden Door: A Jane Hawk Novel
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Forbidden Door: A Jane Hawk Novel to db in: 0.2
Added 1 books in 0.8 seconds

**Comment by ElleKayEm** [comment]
When downloading from Amazon, you need to choose an E-ink Kindle (not a Fire) and add its serial number to the plugin customization.

(Obok is for books from the Kobo Desktop app.)
