### ISSUE TITLE
Callibre - DRM removal issues (No decrpty key found)

### ISSUE THREAD

**Issue by james-wt** [apprenticeharper/DeDRM_tools#668]
Hi there

I am unable to remove DRM from the EPUB books. I want to convert the EPUB book to a mobi format so that it could be read in a kindle.
Please could you help - Many thanks

calibre Debug log
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
calibre 3.31 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.72] main UI initialized...
[2.72] Hiding splash screen
[145.05] splash screen hidden
[145.05] Started up in 145.05 seconds with 41 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xc0\xd0\x0bt\xb6$v\xc2\xc7=4\xf5.\x1c\xa6\xe6=\xa7P\xcf\xda\xc7\x04\xf4d\x89h\x89RV\x81j', 'C:\\Users\\user\\Documents\\My Digital Editions\\Daddy.epub']
DeDRM v6.6.1: Trying to decrypt Daddy.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: Daddy.epub is a secure Adobe Adept ePub
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 346, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 403, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Daddy to db in: 0.3
Added 1 books in 1.9 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x00000000055588D0>> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x0000000005558A20>> ignored
Worker Launch took: 0.414999961853
Job: 1 Convert book 1 of 1 (Daddy) finished
Convert book 1 of 1 (Daddy)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_dhsflg\\fak3xj.opf'
	  output_profile: 'kindle_pw3'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.31.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000000000230E278>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000000000230E978>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_dhsflg\\fak3xj.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\user\AppData\Local\Temp\calibre_dhsflg\q6p4n_.epub
	Python function terminated unexpectedly
	  q6p4n_.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 288, in convert
	calibre.ebooks.DRMError: q6p4n_.epub

**Comment by ElleKayEm** [comment]
Are you using Adobe Digital Editions 2.0.1 authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?
