### ISSUE TITLE
Removing DRM KFX-book doesn't work (Calibre on Windows 10) 

### ISSUE THREAD

**Issue by Daantjerrr** [apprenticeharper/DeDRM_tools#674]
Hey, I'm trying to remove the DRM from an ebook I just bought, but it isn't working. I'm using Calibre  3.33.1 with the KFX input plug-in and DeDRM Tool 6.6.1 plug-in. I didn't get any pop-ups, it just didn't work. Here is my log: 

calibre Debug log
calibre 3.33.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 9, 0) && Goodreads (1, 2, 0) && Annotations (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0) && Count Pages (1, 8, 2) && Quality Check (1, 9, 11) && Goodreads Sync (1, 12, 1)
calibre 3.33.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 9, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 9, 0) && Goodreads (1, 2, 0) && Annotations (1, 8, 0) && KFX metadata reader (from KFX Input) (1, 9, 0) && KFX Input (1, 9, 0) && Count Pages (1, 8, 2) && Quality Check (1, 9, 11) && Goodreads Sync (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
DEBUG:    0.0 Annotations plugin: Error loading libiMobileDevice. This hasn't worked for a while, and is blacklisted in calibre v3.
DEBUG:    0.0 Annotations plugin: Error is:  No module named idevice.libimobiledevice
DEBUG:    0.0 Annotations::reader_app_support.py - loading translations
DEBUG:    0.0 Annotations::common_utils.py - loading translations
DEBUG:    0.0 Annotations::appearance.py - loading translations
DEBUG:    0.0 Annotations::config.py - loading translations
DEBUG:    0.0 Annotations::annotated_books.py - loading translations
DEBUG:    0.4 Annotations::action.py - loading translations
DEBUG:    0.0 HttpHelper::__init__: proxy=None
[1.80] main UI initialized...
[1.80] Hiding splash screen
Storage number map:
{(7L, 0L): [(4L, 'C'), (5L, 'D')], (7L, 1L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_LINUX&PROD_FILE-STOR_GADGET&REV_0401\N249850091620&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x2237 product_id=0x4228 bcd=0x401 devid=usb\vid_2237&pid_4228&rev_0401 devinst=5)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_linux&prod_file-stor_gadget&rev_0401#n249850091620&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (1L, 1L)}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    6.3 KoboTouch:books - oncard='None'
DEBUG:    6.3 KoboTouch:books - oncard='None', prefix='F:\'
DEBUG:    6.3 Kobo device: Kobo Clara HD
DEBUG:    6.3 Version of driver: (2, 3, 3) Has kepubs: True
DEBUG:    6.3 Version of firmware: (4, 8, 10959) Has kepubs: True
DEBUG:    6.3 Firmware supports cover image tree: True
DEBUG:    6.3 KoboTouch:books - opts.extra_customization= []
DEBUG:    6.3 KoboTouch:books - driver options= Driver:KoboTouch, Options - format_map: ['kepub', 'epub', 'pdf', 'txt', 'cbz', 'cbr'], use_subdirs: True, read_metadata: True, use_author_sort: False, save_template: {author_sort}/{title} - {authors}, extra_customization: [], manage_collections: True, collections_columns: , create_collections: False, delete_empty_collections: False, ignore_collections_names: , upload_covers: False, keep_cover_aspect: False, upload_grayscale: False, show_archived_books: False, show_previews: False, show_recommendations: False, update_series: True, update_device_metadata: True, modify_css: False, override_kobo_replace_existing: True, support_newer_firmware: False, debugging_title: , driver_version: 
DEBUG:    6.3 KoboTouch:books - prefs['manage_device_metadata']= manual
DEBUG:    6.3 KoboTouch:books - set_debugging_title to ''
DEBUG:    6.3 KoboTouch:books - length bl=0
DEBUG:    6.3 KoboTouch:books - length bl after sync=2
DEBUG:    6.3 KoboTouch:books - reading device database
DEBUG:    6.3 Database Version:  146
DEBUG:    6.3 KoboTouch:books - shelf list: []
DEBUG:    6.3 KoboTouch:books - query= SELECT Title, Attribution, DateCreated, ContentID, MimeType, ContentType, ImageID, ReadStatus, ___ExpirationStatus, FavouritesIndex, Accessibility, IsDownloaded, Series, SeriesNumber, ___UserID, ExternalId FROM content  WHERE BookID IS NULL  AND ((Accessibility = -1 AND IsDownloaded in ('true', 1 ))       OR (Accessibility IN (1,2,9) and IsDownloaded in ('true', 1))         )  AND (externalId IS NULL OR externalId = '') AND contentId NOT LIKE 'file:///mnt/sd/%'
DEBUG:    6.3 KoboTouch:books - about to sync_booklists
DEBUG:    6.3 USBMS: starting sync_booklists
DEBUG:    6.4 USBMS: finished sync_booklists
DEBUG:    6.4 KoboTouch:books - have done sync_booklists
DEBUG:    6.4 KoboTouch:books - end - oncard='None'
DEBUG:    6.4 KoboTouch:books - oncard='carda'
DEBUG:    6.4 KoboTouch:books - Asked to process 'carda', but do not have one!
DEBUG:    6.4 KoboTouch:books - oncard='cardb'
DEBUG:    6.4 KoboTouch:books - Asked to process 'cardb', but do not have one!
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 2
DeviceJob: set_books_in_library finished: time= 0.00600004196167
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
Job: 2 Set library information finished
No details available.
[12.33] splash screen hidden
[12.33] Started up in 12.33 seconds with 79 books
Gather KFX-ZIP (from KFX Input) 1.9.0: Importing C:/Users/Daniëlle/Documents/My Kindle Content/B00UXKIZZO_EBOK/B00UXKIZZO_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\DANILL~1\AppData\Local\Temp\calibre_b9lwhp\onp_ln.kfx-zip
DeDRM v6.6.1: Trying to decrypt onp_ln.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: onp_ln
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.69504d43-adb6-4bc4-a0cc-1ad7cd1d707f.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Danille\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Danille\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '4269596096' and UserName '44616e69efbfbd6c6c65'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: onp_ln
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.69504d43-adb6-4bc4-a0cc-1ad7cd1d707f.voucher
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.9.0: Packaging C:\Users\DANILL~1\AppData\Local\Temp\calibre_b9lwhp\onp_ln.kfx-zip
Processing container: B00UXKIZZO_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 76, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 149, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 260, in get_container
KFXDRMError: Book container B00UXKIZZO_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\DANILL~1\AppData\Local\Temp\calibre_b9lwhp\uuvtpu_add_books\0\B00UXKIZZO_EBOK.kfx-zip
Added The Traitor (Masquerade) to db in: 2.2
Added 1 books in 3.0 seconds

**Comment by ElleKayEm** [comment]
I remember people used to have trouble when their Windows user name had non-ASCII characters, but I thought that bug had been squashed.  Did you download the book with Kindle for PC on the same machine and user as calibre with DeDRM?

**Comment by Daantjerrr** [comment]
Thanks for your quick response! Yes, I did download the book with Kindle for PC, also with same machine and user. Might try again on another PC to see if the non-ASCII character might be the problem.

**Comment by ElleKayEm** [comment]
Yeah, a fresh install might do the trick anyway.

**Comment by Daantjerrr** [comment]
Sorry for the late response! I've gotten it to work on the other laptop. Thanks for your help!
