### ISSUE TITLE
Mac app 6.6.1 UnicodeEncodeError

### ISSUE THREAD

**Issue by edoardocomar** [apprenticeharper/DeDRM_tools#676]
After I fixed the executable bit of Contents/MacOS and added the pip pycrypto modules as in #662 
I get the following error - both with Apple's python 2.7 `/usr/bin/python` and with `brew`'s python2 `in /usr/local/bin/python`:

```
Found 7 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID wtabCNAUGA.
Decrypting. Please wait . . . done
Decryption succeeded after 0.0 seconds
 Traceback (most recent call last):
  File "/private/var/folders/m7/4ndlz5t10vz6791qnqhgn10m0000gn/T/AppTranslocation/BBA4A8FB-CDF1-46FF-8214-F52ECC2585FC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 353, in <module>
    sys.exit(cli_main())
  File "/private/var/folders/m7/4ndlz5t10vz6791qnqhgn10m0000gn/T/AppTranslocation/BBA4A8FB-CDF1-46FF-8214-F52ECC2585FC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 347, in cli_main
    return decryptBook(infile, outdir, kDatabaseFiles, androidFiles, serials, pids)
  File "/private/var/folders/m7/4ndlz5t10vz6791qnqhgn10m0000gn/T/AppTranslocation/BBA4A8FB-CDF1-46FF-8214-F52ECC2585FC/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 272, in decryptBook
    outfilename = '{}_{}'.format(orig_fn_root, clean_title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 18: ordinal not in range(128)
```

**Comment by NastyDT** [comment]
I gotta the same issue. I found \u2013 is a dash "-". And when I delete the dash from the file name my book, it worked just fine.

**Comment by alexkuc** [comment]
Close this issue with PR #685 was merged?
