### ISSUE TITLE
DeDRM v6.6.1: Ultimately failed to decrypt

### ISSUE THREAD

**Issue by bilgipinar** [apprenticeharper/DeDRM_tools#677]
I'm trying to add a PDF e-book to calibre...
- macOS 10.13.6
- DeDRM 6.6.1
- e-TextBook purchased @ www.kortext.com: Plant Physiology & Development.pdf

calibre Debug log
calibre 3.34  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.34  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.000001637 x 109.000001637
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.76] main UI initialized...
[1.76] Hiding splash screen
[1.78] splash screen hidden
[1.78] Started up in 1.78 seconds with 122 books
DeDRM v6.6.1: Trying to decrypt Plant Physiology & Development.pdf
DeDRM v6.6.1: Plant Physiology & Development.pdf is a PDF ebook
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.1: Trying a new default key
DeDRM v6.6.1: Exception when decrypting after 0.4 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 475, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1484, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1614, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 216, in decrypt
ADEPTError: RSA decryption failed
DeDRM v6.6.1: Failed to decrypt with new default key after 0.4 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 628, in run
  File "calibre_plugins.dedrm.__init__", line 503, in PDFDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Debugging DND event
text/uri-list 117 'file:///Users/imac/Library/Application%20Support/com.kortext.KortextReader/Plant%20Physiology%20&%20Development.pdf\r\n' 

Firefox rurl: None None
URLS: ['file:///Users/imac/Library/Application%20Support/com.kortext.KortextReader/Plant%20Physiology%20&%20Development.pdf']
Paths: [u'/Users/imac/Library/Application Support/com.kortext.KortextReader/Plant Physiology & Development.pdf']
Extensions: frozenset([u'pdf'])
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 342, in get_metadata
  File "site-packages/calibre/ebooks/metadata/pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by ElleKayEm** [comment]
Are you able to use a specific Adobe ID with Kortext downloads?

**Comment by bilgipinar** [comment]
Thanks for your help!

no need for Adobe ID. Kortext sent me an access link to the PDF file:
Your Access Code: Direct-attach provisioning

**Comment by bilgipinar** [comment]
update!

I managed to authorize my Adobe ID and added the book to my ADE library.

**Comment by ElleKayEm** [comment]
So are you able to remove the DRM now?

**Comment by bilgipinar** [comment]
still the same error in the log:

DeDRM v6.6.1: Trying to decrypt Plant Physiology & Development.pdf
DeDRM v6.6.1: Plant Physiology & Development.pdf is a PDF ebook
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v6.6.1: Trying a new default key
ADEPTError: RSA decryption failed
DeDRM v6.6.1: Failed to decrypt with new default key after 0.4 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds

**Comment by ElleKayEm** [comment]
If you're using a recent version of ADE, see if you can open the book with ADE 2.0.1 authorized with your Adobe ID.

**Comment by bilgipinar** [comment]
I uninstalled ADE 4.5 and installed ADE 2.0, as you recommended. I couldn't add the book to my library because "this item is authorized to another account"!? Then, uninstalled ADE 2.0, and installed ADE 4.5 again. I was able to add the same book to my library using the same adobe authorization!?

**Comment by ElleKayEm** [comment]
Sounds like it may be using DRM that cannot be removed yet.  See this section of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm

**Comment by bilgipinar** [comment]
Thank you for all your help, really appreciate it! 😊 Seems like there's not much I can do, but I'm not giving up yet 😉 Have a good night/day ☀️
