### ISSUE TITLE
Problem with DeDRM and Calibre

### ISSUE THREAD

**Issue by vicentselfa** [apprenticeharper/DeDRM_tools#681]
calibre Registro de depuración
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.1467181467 x 94.0740740741
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.51] main UI initialized...
[1.51] Hiding splash screen
[8.34] splash screen hidden
[8.34] Started up in 8.34 seconds with 102 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x91\xb2{=\x87\xa1h\xe3\xd1d\xa1\xad\x17\xbb\x11)(D6\x91\x1d\x0e7]\xc6\xfa~\xa4\xfd`X\xaf', 'F:\\Llibres\\Llibres EPUB Francesc\\Hist\xc3\xb3rica\\Posteguillo, Santiago (1967 Espa\xc3\xb1a)\\Yo, Julia.azw3']
DeDRM v6.6.1: Trying to decrypt Yo, Julia.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Yo, Julia (Volumen independiente) (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Vicent\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Vicent\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2989008570' and UserName '566963656e74'
DeDRM v6.6.1: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Yo, Julia (Volumen independiente) (Spanish Edition)
Got DSN key from database default_key_1
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Yo, Julia (Volumen independiente) (Spanish Edition) to db in: 0.1
Added 1 books in 5.4 seconds
Worker Launch took: 0.18799996376
Job: 1 Convertido el libro 1 de 1 (Yo, Julia (Volumen independiente) (Spanish Edition)) finished
Convertido el libro 1 de 1 (Yo, Julia (Volumen independiente) (Spanish Edition))
	C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Vicent\\AppData\\Local\\Temp\\calibre_o1ktnq\\glvdf7.opf'
	  cover: u'C:\\Users\\Vicent\\AppData\\Local\\Temp\\calibre_o1ktnq\\msfszw.jpeg'
	  output_profile: 'kindle_pw'
	Resolved conversion options
	calibre version: 3.34.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Vicent\\AppData\\Local\\Temp\\calibre_o1ktnq\\msfszw.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04209550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x04209930>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Vicent\\AppData\\Local\\Temp\\calibre_o1ktnq\\glvdf7.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Vicent\AppData\Local\Temp\calibre_o1ktnq\cfmisn.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Yo, Julia (Volumen independiente) (Spanish Edition) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Yo, Julia (Volumen independiente) (Spanish Edition)

**Comment by ElleKayEm** [comment]
If that was downloaded from the website and the device chosen was an E-ink Kindle (not a Fire), then you need to add its serial number to the plugin customization.

**Comment by vicentselfa** [comment]
Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
