### ISSUE TITLE
Calibre not importing correctly

### ISSUE THREAD

**Issue by frostbitesouth** [apprenticeharper/DeDRM_tools#683]
Calibre has began to no longer import books correctly.  They can't be converted nor opened.  They show to be a KFX-ZIP file.  Below is the information from running the debug...

calibre Debug log
calibre 3.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 10, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 10, 0) && KFX metadata reader (from KFX Input) (1, 10, 0) && KFX Input (1, 10, 0)
calibre 3.32 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 10, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 10, 0) && KFX metadata reader (from KFX Input) (1, 10, 0) && KFX Input (1, 10, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.86] main UI initialized...
[1.86] Hiding splash screen
[38.41] splash screen hidden
[38.41] Started up in 38.41 seconds with 181 books
Gather KFX-ZIP (from KFX Input) 1.10.0: Importing C:/Users/jwbui/Documents/My Kindle Content/B01M65CRXF_EBOK/B01M65CRXF_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 8 file(s) as C:\Users\jwbui\AppData\Local\Temp\calibre_gwq_on\l7bphc.kfx-zip
DeDRM v6.6.1: Trying to decrypt l7bphc.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: l7bphc
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c3c64393-83fb-4da9-8cc2-cd98bdeeca81.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\jwbui\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.10.0: Packaging C:\Users\jwbui\AppData\Local\Temp\calibre_gwq_on\l7bphc.kfx-zip
Processing container: B01M65CRXF_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B01M65CRXF_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\jwbui\AppData\Local\Temp\calibre_gwq_on\i3aqb4_add_books\0\B01M65CRXF_EBOK.kfx-zip
Added The Bushcraft Field Guide to Trapping, Gathering, and Cooking in the Wild to db in: 1.1
Added 1 books in 2.1 seconds

**Comment by j-howell** [comment]
From the log that book was apparently downloaded using Kindle for PC, but DeDRM is failing to locate a needed file.

Is the Kindle for PC installed on the same PC and user as your calibre installation?
Which version of Kindle for PC do you have?

The answers will help to diagnose the problem.

**Comment by frostbitesouth** [comment]
Yes the Kindle for PC is on the same PC as the calibre installation and same user.

I have version 1.25.0 version of Kindle for PC

**Comment by frostbitesouth** [comment]
You got me to thinking when you asked about my version of Kindle.  I noticed that it updated today.  So I uninstalled that version and went back and put the previous version on. Problem solved.  It appears the new version is the problem.

**Comment by j-howell** [comment]
>> I have version 1.25.0 version of Kindle for PC

I was afraid of that. It looks like Amazon is starting to roll out that new K4PC version and it uses new DRM that the current version of the DeDRM plugin cannot handle.

Uninstalling K4PC and reinstalling an older version is the only option for now. For others who may come across this issue, the last version that works with DeDRM is available here:

https://s3.amazonaws.com/kindleforpc/51068/KindleForPC-installer-1.24.51068.exe
