### ISSUE TITLE
DeDRM not working with Calibre on Mac

### ISSUE THREAD

**Issue by brgt** [apprenticeharper/DeDRM_tools#684]
I am trying to convert an ebook from my Kindle Paperwhite but it does not remove the DRM, follow the log

Calibre 3.34
macOS Mohave

Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 101, in convert
  File "calibre_plugins.kfx_input.__init__", line 203, in convert_from_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 96, in convert_to_epub
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container Cultura Política Comparada (Portuguese Edition)_B015J8VEJ8.kfx has DRM and cannot be converted
Python function terminated unexpectedly: This book has DRM!
InputFormatPlugin: KFX Input running
on /var/folders/bl/76q_639911x8dc54j1rmbkdh0000gn/C/calibre_3.34.0_tmp_Czh8aL/9dNsHh.kfx-zip
Software versions: KFX Input 1.10.0, calibre 3.34, Darwin-18.2.0-x86_64-i386-64bit
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting /var/folders/bl/76q_639911x8dc54j1rmbkdh0000gn/C/calibre_3.34.0_tmp_Czh8aL/9dNsHh.kfx-zip
Processing container: CR!0QN7PFTVS165V9XP1HMTYR0AN55X.kfx
Processing container: Cultura Política Comparada (Portuguese Edition)_B015J8VEJ8.kfx
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
  File "calibre_plugins.kfx_input.__init__", line 104, in convert
calibre.ebooks.DRMError: This book has DRM!

**Comment by j-howell** [comment]
DRM removal happens when a book is imported into calibre. Post an import log. See the FAQ for instructions:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by brgt** [comment]
Hi j-howell, thank you1

Follow the complete log:

calibre Debug log
calibre 3.34  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 10, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 10, 0) && Set KFX metadata (from KFX Output) (1, 24, 0) && KFX Output (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 10, 0) && KFX Input (1, 10, 0)
calibre 3.34  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 10, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 10, 0) && Set KFX metadata (from KFX Output) (1, 24, 0) && KFX Output (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 10, 0) && KFX Input (1, 10, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 149.000002238 x 149.000002238
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[1.93] main UI initialized...
[1.93] Hiding splash screen
[1.99] splash screen hidden
[2.00] Started up in 2.00 seconds with 1 books
objc[14199]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8db121d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1157bfdc8). One of the two will be used. Which one is undefined.
2018-11-14 10:37:52.675 Calibre[14215:3693030] deliverNotificationWithTitle()
* Notification delivered.
Gather KFX-ZIP (from KFX Input) 1.10.0: Importing /Volumes/Kindle/documents/Bookname_B015J8VEJ8.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/bl/76q_639911x8dc54j1rmbkdh0000gn/C/calibre_3.34.0_tmp_eXxT4p/InXgvA.kfx-zip
DeDRM v6.6.1: Trying to decrypt InXgvA.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO

{'bsd_drives': {'main': u'/dev/disk3s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/',
               '/dev/disk1s4': '/private/var/vm',
               '/dev/disk2s1': '/Volumes/Java 8 Update 191',
               '/dev/disk3s1': '/Volumes/Kindle',
               '/dev/disk4s1': '/Volumes/calibre-3.34.0',
               'devfs': '/dev',
               'drivefs': '/Volumes/GoogleDrive',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.1 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.3 USBMS: count found in cache: 66, count of files in metadata: 66, need_sync: False
DEBUG:    0.3 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.3 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 66
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
DeviceJob: set_books_in_library finished: time= 0.499408006668
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Decrypting KFX-ZIP ebook: InXgvA
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/welysson/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'dd9464696051' and UserName 'welysson'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: InXgvA
Got DSN key from database default_key_1
Found 1 keys to try after 0.6 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Bookname_B015J8VEJ8.kfx has DRM and cannot be converted
Package KFX (from KFX Input) 1.10.0: Packaging /var/folders/bl/76q_639911x8dc54j1rmbkdh0000gn/C/calibre_3.34.0_tmp_eXxT4p/InXgvA.kfx-zip
Processing container: CR!0QN7PFTVS165V9XP1HMTYR0AN55X.kfx
Processing container: Bookname_B015J8VEJ8.kfx
KFX metadata reader (from KFX Input) activated for /var/folders/bl/76q_639911x8dc54j1rmbkdh0000gn/C/calibre_3.34.0_tmp_eXxT4p/k5OaTn_add_books/0/Bookname_B015J8VEJ8.kfx-zip
Added Bookname db in: 0.0
Added 1 books in 1.8 seconds

**Comment by ElleKayEm** [comment]
Looks like you need to enter the serial number for your Paperwhite into the plugin customization.

**Comment by j-howell** [comment]
Thanks @ElleKayEm. I failed to see that despite Kindle for Mac being installed that book was being obtained from a Kindle device instead.

**Comment by brgt** [comment]
> Looks like you need to enter the serial number for your Paperwhite into the plugin customization.

That's right! I added the serial number and now it worked. Thank you very much :)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by arno2233** [comment]
Not working with calibre on mac. There is no serial for kindle on mac.
