### ISSUE TITLE
DeDRM (6.3.6) & kindle for android - not accepting backup.ab

### ISSUE THREAD

**Issue by spyderboyant** [apprenticeharper/DeDRM_tools#69]
With DeDRM and Calibre I am unable to select/use the backup.ab file I have created using the "adb backup com.amazon.kindle" command. The backup.ab file is only 41 bytes in length. I have not rooted my Sony Z5.... Do I need to root my phone to backup the drm key for the kindle app?

If I try and use this backup file I get an error asking me to "Please choose a kindle for android backup file".

If I try to use the backup.ab file with "import existing key files" I get the following error:

 calibre 2.50.1 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 289, in double_clicked
  File "site-packages\calibre\gui2\preferences\plugins.py", line 370, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 175, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 624, in save_settings
  File "calibre_plugins.dedrm.config", line 176, in save_settings
  File "calibre_plugins.dedrm.prefs", line 57, in set
  File "site-packages\calibre\utils\config.py", line 408, in __setitem__
  File "site-packages\calibre\utils\config.py", line 353, in commit
  File "site-packages\calibre\utils\config.py", line 392, in to_raw
  File "json\__init__.py", line 250, in dumps
  File "json\encoder.py", line 209, in encode
  File "json\encoder.py", line 434, in _iterencode
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 313, in _iterencode_list
UnicodeDecodeError: 'utf8' codec can't decode byte 0xda in position 1: invalid continuation byte

**Comment by ElleKayEm** [comment]
The latest version of Kindle for Android doesn't allow the creation of a proper backup file.  It also supports the new kfx format (when available) which the tools can't decrypt.  Reverting back to version 4.17 has worked in some cases.  See this comment over at the blog:

https://apprenticealf.wordpress.com/2012/09/10/drm-removal-tools-for-ebooks/comment-page-6/#comment-53382
