### ISSUE TITLE
Book locked with DRM

### ISSUE THREAD

**Issue by felipenam** [apprenticeharper/DeDRM_tools#692]
Can you help me please? .. Book downloaded to my pc from Kindle Paperwhite

> Starting up...
Started up in 5.34 seconds with 2 books
Gather KFX-ZIP (from KFX Input) 1.10.0: Importing C:/Users/Admin/Documents/libros calibre/Sales Differentiation_ 19 Powerful Strategies to Win More Deals at the Prices You Want_B07CCGW34Y.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\Admin\AppData\Local\Temp\calibre_vaqok7\bdfaye.kfx-zip
DeDRM v6.6.1: Trying to decrypt bdfaye.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: bdfaye
Found 1 keys to try after 0.1 seconds
DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Admin\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.10.0: Packaging C:\Users\Admin\AppData\Local\Temp\calibre_vaqok7\bdfaye.kfx-zip
Processing container: Sales Differentiation_ 19 Powerful Strategies to Win More Deals at the Prices You Want_B07CCGW34Y.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container Sales Differentiation_ 19 Powerful Strategies to Win More Deals at the Prices You Want_B07CCGW34Y.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Admin\AppData\Local\Temp\calibre_vaqok7\buh0ij_add_books\0\Sales Differentiation_ 19 Powerful Strategies to Win More Deals at the Prices You Want_B07CCGW34Y.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 122, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Sales Differentiation 19 Powerful Strategies to Win More Deals at the Prices You Want B07CCGW34Y to db in: 0.1
Added 1 books in 0.9 seconds

>

**Comment by j-howell** [comment]
>> Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.

The KFX Input plugin needs access to more than just the main file when importing books in KFX format. See the "Importing KFX books into calibre for conversion" in the [KFX Input plugin documentation](https://www.mobileread.com/forums/showthread.php?t=291290) for more information.

**Comment by felipenam** [comment]
Thanks! I was dragging the KFX file directly to my library. But now I connected the kindle, search for the book and clicked "Add to library" then convert and voila! Thanks so much

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
