### ISSUE TITLE
DeDRM 6.61 not finding/removing DRM from Nook

### ISSUE THREAD

**Issue by jag986** [apprenticeharper/DeDRM_tools#693]
I've put in my credentials, but it doesn't seem like the tool knows what the DRM is. Files are downloaded from the Win10 app, nothing else seems to be able to get the Nook books.

Debug:

calibre Debug log
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.34  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.83] main UI initialized...
[1.83] Hiding splash screen
[5.19] splash screen hidden
[5.19] Started up in 5.19 seconds with 498 books
DeDRM v6.6.1: Trying to decrypt 2940153638744.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “2940153638744.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.4 seconds. DRM free perhaps?
Added The Testament of Sister New Devil STORM! Vol. 1 to db in: 1.9
Added 1 books in 2.9 seconds
Worker Launch took: 0.153000116348
Worker Launch took: 0.146000146866
Job: 2 Convert book 1 of 1 (The Testament of Sister New Devil STORM! Vol. 1) finished
Convert book 1 of 1 (The Testament of Sister New Devil STORM! Vol. 1)
	Conversion options changed from defaults:
	  output_profile: 'kindle_voyage'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Jag\\AppData\\Local\\Temp\\calibre_nvj9fd\\ksrdbl.opf'
	Resolved conversion options
	calibre version: 3.34.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0266A870>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x0266AC90>,
	 'page_breaks_before': u'/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Jag\\AppData\\Local\\Temp\\calibre_nvj9fd\\ksrdbl.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\Jag\AppData\Local\Temp\calibre_nvj9fd\v_gomd.epub
	Python function terminated unexpectedly
	  v_gomd.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 288, in convert
	calibre.ebooks.DRMError: v_gomd.epub

Any help is appreciated!

**Comment by jag986** [comment]
OK, thanks. I'll try it when I get home and see how it goes.

**Comment by jag986** [comment]
Unfortunately I'm running into the same issue as the 651...which is a shame because right now this is the only source for these comics digitally...

**Comment by jag986** [comment]
Thanks for the help though! I'll keep an eye here to see if anything changes.

**Comment by ElleKayEm** [comment]
Ugh... sounds like they might have closed the door on this method then.  Thanks for reporting back anyway.  Maybe someone can figure out something else.

**Comment by HamsterExAstris** [comment]
For what it's worth, I just purchased a comic, downloaded with the Windows 10 app, and used that method; it worked fine for me.

(OP, if you're still having issues, Kobo has that series available now. They don't have *everything* from that publisher that Nook has - my test title was also from Seven Seas - but rebuying might be better than nothing if you still can't get it to work.)

**Comment by jag986** [comment]
Interesting.

I'll break it down and play with it more, and see if I can get it to work
and report back to you. I did find out that Google Play sells the series
and bought it there, so I do have a back up if I need it. I might look into
Kobo though, so if I do do backups, I won't be using an account I worry too
much about.

thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jag986** [comment]
Just to update this thread, I still haven't had a chance to try this again,
but I will report back if I can get it to work after all so that others
don't make my mistakes :)

I've got a few more books I want to try now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jag986** [comment]
I've had an opportunity to try this again. I'm going to put the pastebin
for my rights.xml file here first.

https://pastebin.com/GZHWPNGj

When I use this file, I don't get any errors in Calibre, but the resulting
image files are blank and unusuable as if they were still encrypted. I'm
not sure what to do.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jag986** [comment]
Here's a pastebin of the log

https://pastebin.com/eQQJ7skn

**Comment by ElleKayEm** [comment]
It doesn't look like you have the rights.xml back in the epub correctly.  You shouldn't still be getting that line in the log about it not being "an Adobe Adept nor a Barnes & Noble encrypted ePub."

**Comment by jag986** [comment]
Hmm OK I'll double check that when I get back home.

**Comment by jag986** [comment]
I got it to work! Turns out I was doing a very stupid thing.

I would unzip the archive to a folder, but then when I zipped it back up, I
would include that folder. So the rights.xml would be in the appropriate
folder per your instructions, but I was adding another level to the path
and that's why it couldn't find it.

One note, it would not automatically import my key from Nook for PC,
fortunately I had a backup of my key from before.

Thanks for your help. I don't like buying things from Nook but some Seven
Seas series are only there or on Bookwalker and no one has cracked
bookwalker yet.

**Comment by ElleKayEm** [comment]
Glad you got it working.

Good thing you still had a key from before because the ways that DeDRM retrieved the Nook key are broken ever since the old Nook apps stopped working.
