### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by felagund** [apprenticeharper/DeDRM_tools#7]
Upon installing the plugin on Calibre 2.27 and tryin to configure it, it gives me this error:

calibre 2.27  isfrozen: True is64bit: True
Linux-3.19.0-16-generic-x86_64-with-debian-jessie-sid Linux ('64bit', 'ELF')
('Linux', '3.19.0-16-generic', '#16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015')
Python 2.7.9
Linux: ('debian', 'jessie/sid', '')
Successfully initialized third party plugins: DeDRM
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 292, in customize_plugin
  File "site-packages/calibre/gui2/preferences/plugins.py", line 370, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 154, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 601, in config_widget
AttributeError: 'module' object has no attribute 'ConfigWidget'

**Comment by ElleKayEm** [comment]
Make sure you have the latest version 6.2.1 of the plugin installed.  Then close calibre, restart, and try again.

**Comment by felagund** [comment]
ah yes, restarting calibre did the trick (I am not sure if that is calibre's bug or in your plugin, it sounds very unintuitive to have to restart the app for preferences of a plugin to start to work)
