### ISSUE TITLE
error while decrypting an azw book on mac (from kindle for mac)

### ISSUE THREAD

**Issue by mgrde** [apprenticeharper/DeDRM_tools#700]
when decrypting an azw-book with drdrm.app I get following error message in dedrm.log:

-----start log excerpt-----
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/Applications/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/Applications/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
-----end log-----

???

**Comment by mgrde** [comment]
good one, sorry for not reading the FAQ completely.

Just a suggestion for that topic:

expand the terminal command "python -m pip pycrypto" to
python -m pip **install** pycrypto
