### ISSUE TITLE
failed to remove DRM

### ISSUE THREAD

**Issue by gerodonovan1** [apprenticeharper/DeDRM_tools#701]
Hi,
Got following while trying to decrypt .AZW file.
I loaded DeDRM plugin and I can see it as being enabled.

stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xff\x9c\x82B\x0c\xc4OH\xc7\xeeJ\xe0*o\xee\xc6\xa8]Qp\xf4\xe4\x83\x7f \x1f\xa9h\x12\x8b\xb4S', 'C:\\Users\\ger\\Documents\\My Kindle Content\\B07KRDLV6P_EBOK\\B07KRDLV6P_EBOK.azw']
DeDRM v6.5.4: Trying to decrypt B07KRDLV6P_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.5.4: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.4: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ger\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\ger\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3300211124' and UserName '676572'
DeDRM v6.5.4: Found 1 new key
DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 611, in run
  File "calibre_plugins.dedrm.__init__", line 561, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.4: Ultimately failed to decrypt after 0.4 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 417, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 494, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: 
Added B07KRDLV6P EBOK to db in: 1.1
Added 1 books in 2.2 seconds

**Comment by gerodonovan1** [comment]
I'll do that thanks.
