### ISSUE TITLE
Why dedrm cannot decrypt in sometime ?

### ISSUE THREAD

**Issue by Nellypride** [apprenticeharper/DeDRM_tools#705]
It is in same computer and same Kindle version :

PC OS : Windows 7 Pro 32bit
Kindle version : 1.17
Calibre version : 3.35
DeDem version : 6.61

For example , I can decrypt one .azw file and save to jpg .
But after next day I import same .azw file to Calibre , decrypt fail .

Following is the log when fail :

================================

calibre Debug log
calibre 3.35 embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.35 embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[2.20] main UI initialized...
[2.20] Hiding splash screen
[33.93] splash screen hidden
[33.93] Started up in 33.93 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt B079YP11QG_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: [Book Name]
Got DSN key from database default_key
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
File is encoded with PID cxFZvv++9G.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.2 seconds
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
File "calibre_plugins.dedrm.__init__", line 621, in run
File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
File "calibre_plugins.dedrm.mobidedrm", line 407, in getFile
IOError: [Errno 22] Invalid argument
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:60 1: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added [Book Name] to db in: 3.5
Added 1 books in 5.2 seconds
Added B079YP11QG EBOK to db in: 3.7
Added 1 books in 4.1 seconds
isEncrypted = True

========================================

In KindleUnpack the lock red color and cannot export .

But after I reboot computer . It work fine .

Do anyone know why ?

*** My computer have two user account do it is the factor ?

**Comment by ElleKayEm** [comment]
Ok, this log shows successful DRM removal.

> Decryption succeeded after 1.2 seconds

But then 

> Added B079YP11QG EBOK to db in: 3.7
> Added 1 books in 4.1 seconds
> isEncrypted = True

So I don't know what's up with that.  Having two user accounts shouldn't be a problem as long as both calibre with DeDRM and Kindle for PC where the book was downloaded are on the same user account.

**Comment by Nellypride** [comment]
Do the following affected : 

1. Bookname is Japanese and ,azw file size over 200MB .

2. Actually my another user accounting also using Kindle reg. another Kindle account .

**Comment by Nellypride** [comment]
Log in success  : 

calibre Debug log
calibre 3.35  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.35  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1) && KindleUnpack - The Plugin (0, 81, 5)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[2.28] main UI initialized...
[2.28] Hiding splash screen
DeDRM v6.6.1: Trying to decrypt B07DNYWT7B_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: デジタル版ヤングガンガン 2018 No.14【デジタル限定グラビア増量版】 [雑誌]
Got DSN key from database default_key
Found 4 keys to try after 1.2 seconds
Crypto Type is: 2
File is encoded with PID MjBNWf7hEC.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.8 seconds
DeDRM v6.6.1: Finished after 2.7 seconds
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added デジタル版ヤングガンガン 2018 No.14【デジタル限定グラビア増量版】 [雑誌] to db in: 4.0
Added 1 books in 7.2 seconds

**Comment by ElleKayEm** [comment]
Ok, this is successful.  What's the question?

**Comment by Nellypride** [comment]
Success and fail randomly happen on my case . 
it is ridiculous on computer science.

**Comment by ElleKayEm** [comment]
Yeah, it should be consistant.  It is for me.  Keep in mind that each Kindle app installation and device has its own unique key.  Even for the same Amazon account.  Even a reinstallation or update of the Kindle app on the same machine can have a different key.  So always use fresh copies of your books.

Do you have any books you can't unlock at all?

**Comment by Nellypride** [comment]
> 
> 
> Yeah, it should be consistant. It is for me. Keep in mind that each Kindle app installation and device has its own unique key. Even for the same Amazon account. Even a reinstallation or update of the Kindle app on the same machine can have a different key. So always use fresh copies of your books.
> 
> Do you have any books you can't unlock at all?

I will test on next purchase and download next few day .
