### ISSUE TITLE
Failed to deDRM with v6.6.1 and KFX input plugin in Calibre

### ISSUE THREAD

**Issue by kw02** [apprenticeharper/DeDRM_tools#707]
Here is the log. Thanks in advance for your assistance.

calibre Debug log
calibre 3.35  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 11, 0) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
calibre 3.35  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 11, 0) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 73.4457831325 x 73.7419354839
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[2.47] main UI initialized...
[2.47] Hiding splash screen
[6.36] splash screen hidden
[6.36] Started up in 6.36 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x08\xecg{.c\n\xa3\x9bXA5\xeb\xf5U\x86m\x19_T|\x8e*\xdc4_\xc0\xc7\x90N\tQ', 'C:\\Users\\Kitty\\Documents\\My Kindle Content\\B07CLDXD9Y_EBOK\\B07CLDXD9Y_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.11.0: Importing C:\Users\Kitty\Documents\My Kindle Content\B07CLDXD9Y_EBOK\B07CLDXD9Y_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Kitty\AppData\Local\Temp\calibre_frcxrl\vcvz37.kfx-zip
DeDRM v6.6.1: Trying to decrypt vcvz37.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: vcvz37
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.1b99d2c9-3307-4bd9-9812-e0283e228d05.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Kitty\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.11.0: Packaging C:\Users\Kitty\AppData\Local\Temp\calibre_frcxrl\vcvz37.kfx-zip
Processing container: B07CLDXD9Y_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B07CLDXD9Y_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Kitty\AppData\Local\Temp\calibre_frcxrl\jqgopu_add_books\0\B07CLDXD9Y_EBOK.kfx-zip
Added Music Therapy Assessment to db in: 0.2
Added 1 books in 1.8 seconds

**Comment by ElleKayEm** [comment]
Are you using Kindle for PC 1.24 or earlier?

**Comment by kw02** [comment]
My Kindle for PC is 1.25.1

**Comment by ElleKayEm** [comment]
That's the issue.  See this post:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by j-howell** [comment]
> No K4PC kindle.info/kinf/kinf2011 files have been found.

On thing I noticed in the new Kindle for PC version is that the .kinf2011 file has been replaced by a new .kinf2018 file. So there is more going on than just the update to KFX DRM.

**Comment by kw02** [comment]
> That's the issue. See this post:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371

Thanks a lot for the info. I managed to download the older Kindle version 1.17 and successfully convert the kfx file to pdf. Thank you again for your prompt reply.
