### ISSUE TITLE
DeDRM an dCalibre

### ISSUE THREAD

**Issue by Paengelanton** [apprenticeharper/DeDRM_tools#708]
Hello,
ADE 2.0, Calibre 3.35 (64 bit) and DeDRM 6.6.1. DeDRM successful installed.
I load an ascm-file and load with this via ADE the epub. In ADE I can read the book. Everything ok. The import to calibre doesn't work. I see the title in the user interface but not the cover. When I try to open it I get the message, that the book ist DRM protected. Also the converting doesn't help.

Here the report from the debug mode:

Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.12+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.50] main UI initialized...
[1.50] Hiding splash screen
[2.00] splash screen hidden
[2.00] Started up in 2.00 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xde\xea\xd9G\xec!z\xd2\x89\x81M\xf0\x1a\xf2t\x87\x90\x8c\xca\x99\x80\x11\x97\xeb\x16FF\xd7`\xee\xed\xc5', 'C:\\Users\\mail\\Documents\\My Digital Editions\\Dunkler Sommer-1.epub']
DeDRM v6.6.1: Trying to decrypt Dunkler Sommer-1.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: Dunkler Sommer-1.epub is a secure Adobe Adept ePub
DeDRM v6.6.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 346, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
**ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs** at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 403, in ePubDecrypt
DeDRMError:DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Dunkler Sommer to db in: 0.1
Added 1 books in 1.0 seconds

Has anyone an idea? On my old PC everything worked fine. 

Thank you

Frank

**Comment by ElleKayEm** [comment]
ADE is authorized with your Adobe ID?  Seems to be having trouble retrieving your key.

Is your old PC setup still accessible?  If so and if it was the same Adobe ID, you could save the key from the old DeDRM and import it into this one.

**Comment by Paengelanton** [comment]
Some attempts later..... I found a description in one of your answers that helped:
I deinstalled ADE, deleted the registration in windows with regedit and installed ADE again. 
"HKEY_CURRENT_USER\Software\Adobe\Adept"
login and it works. Maybe the problem was that I first installed ADE 4.5 (it worked on my old PC). And the deinstallation deleted not everything.
After 3 evenings the problem is solved.

Thank you

**Comment by ElleKayEm** [comment]
Yes, that was probably it.  Reinstalling would have been my next suggestion.  Glad you found the answer.
