### ISSUE TITLE
DeDRM 6.6.1 not working

### ISSUE THREAD

**Issue by cultivationzone** [apprenticeharper/DeDRM_tools#714]
The log:
calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7600-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7600')
Python 2.7.12+
Windows: ('7', '6.1.7600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && eReader PDB 2 PML (0, 0, 8) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7600-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '7', '6.1.7600')
Python 2.7.12+
Windows: ('7', '6.1.7600', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && eReader PDB 2 PML (0, 0, 8) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 114.3 x 87.8416666667
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.10] db initialized
[0.10] Constructing main UI...
[1.55] main UI initialized...
[1.55] Hiding splash screen
[51.68] splash screen hidden
[51.68] Started up in 51.68 seconds with 164 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['L\xfcc\x87)P\xe73\xac_\x99\xe2\x19\xe2\xcd\x03\x93g\xab"X\xd8B%P P\xb4N\x9f\x96F', 'C:\\Users\\VirtualBox\\Documents\\My Kindle Content\\B072N6MQ5V_EBOK\\B072N6MQ5V_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.0: Importing C:\Users\VirtualBox\Documents\My Kindle Content\B072N6MQ5V_EBOK\B072N6MQ5V_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B072N6MQ5V_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: High Performance Habits
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\VirtualBox\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added High Performance Habits to db in: 0.1
Added 1 books in 1.2 seconds
Worker Launch took: 0.165999889374

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.24 or earlier.

**Comment by rajkishoreworks** [comment]
not working. I tried even version 1.21

**Comment by rajkishoreworks** [comment]
After I upgraded Calibre to latest 3.36.0 version, I was able to import file but could not convert to epub.  I used Kindle for PC 1.21. Here is the Calibre logs-

calibre, version 3.36.0
ERROR: Conversion failed: <p><b>Failed to convert: B008593O8S EBOK<p>This is an Amazon KFX book. It cannot be processed. See <a href="https://www.mobileread.com/forums/showthread.php?t=283371">here</a> for information on how to handle KFX books.

Convert book 1 of 1 (B008593O8S EBOK)
Conversion options changed from defaults:
  verbose: 2
  input_profile: 'kindle'
  read_metadata_from_opf: u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre__fqgxb\\vxfa29.opf'
Resolved conversion options
calibre version: 3.36.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.KindleInput object at 0x030AF210>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x030AF330>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre__fqgxb\\vxfa29.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\HP\AppData\Local\Temp\calibre__fqgxb\af1zzt.azw
Python function terminated unexpectedly
  This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books. (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 35, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 84, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by j-howell** [comment]
You need to post an import log, not a conversion log.

**Comment by rajkishoreworks** [comment]
Sorry guys, I'm new to Calibre. So didn't know exactly what specific logs are required. Please give me direction if I'm wrong again but I guess, below is what you expected-

calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.55] main UI initialized...
[1.55] Hiding splash screen
[3.89] splash screen hidden
[3.89] Started up in 3.89 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xc9}\xael\xff\x9cF5\x9c\n\xe8\x1dbh\xab'$\xe1`gZD(\xaf\xa3 \xf4P\x9a\xa5[\xfd", 'C:\\Users\\HP\\Documents\\My Kindle Content\\B008593O8S_EBOK\\B008593O8S_EBOK.azw']
DeDRM v6.6.1: Trying to decrypt B008593O8S_EBOK.azw
Using Library AlfCrypto Python
DeDRM v6.6.1: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\HP\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\HP\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '179853146' and UserName '4850'
DeDRM v6.6.1: Found 1 new key
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 284, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 495, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 284, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 312, in identity
MobiError: Unknown book type: 
Added B008593O8S EBOK to db in: 1.5
Added 1 books in 2.2 seconds
Worker Launch took: 0.128000020981

**Comment by ElleKayEm** [comment]
For this format, you also need to install the KFX Input plugin.  Alternatively you can get the book in another format.  See this post for more info:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by rajkishoreworks** [comment]
I appreciate your quick response. I have gone through with post above and nothing seems to work in my case. 

**Option 1 & 2** - don't allow to download file in kindle anymore. It states below popup message -

> "Your Kindle requires a software update to view this content. Please visit http://www.amazon.com/kindlesoftwareupdates for instructions on how to install the free update for your device."

**Option 3** - Not applicable as I don't carry e-ink Kindle device to give it a try.
**Option 4** - Using KFX Input plugin. Not worked, here is the logs-

calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
[6.11] splash screen hidden
[6.11] Started up in 6.11 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [']``\xd4\x8f\x0b\xc0\xea\xd9~\x95\x08\xbd\x19\x90\xefkh;V\x1f\xdc@NR\xf6\x81\xec\xa9\xe4\x94}', 'C:\\Users\\HP\\Documents\\My Kindle Content\\B008593O8S_EBOK\\B008593O8S_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.0: Importing C:\Users\HP\Documents\My Kindle Content\B008593O8S_EBOK\B008593O8S_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\HP\AppData\Local\Temp\calibre_znjsju\_9ukf9.kfx-zip
DeDRM v6.6.1: Trying to decrypt _9ukf9.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: _9ukf9
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.f509fd9e-0b2b-4726-976a-7bc4cad63fff.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\HP\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\HP\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '179853146' and UserName '4850'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: _9ukf9
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.f509fd9e-0b2b-4726-976a-7bc4cad63fff.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.0: Packaging C:\Users\HP\AppData\Local\Temp\calibre_znjsju\_9ukf9.kfx-zip
Processing container: B008593O8S_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B008593O8S_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\HP\AppData\Local\Temp\calibre_znjsju\5a2mho_add_books\0\B008593O8S_EBOK.kfx-zip
Added Immortals of Meluha (The Shiva Trilogy) to db in: 2.1
Added 1 books in 3.1 seconds
Worker Launch took: 0.220999956131
Job: 1 Convert book 1 of 1 (Immortals of Meluha (The Shiva Trilogy)) finished
Convert book 1 of 1 (Immortals of Meluha (The Shiva Trilogy))
        Conversion options changed from defaults:
          input_profile: 'kindle'
          read_metadata_from_opf: u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre_znjsju\\uz7ydg.opf'
          cover: u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre_znjsju\\d8vllf.jpeg'
          verbose: 2
        Resolved conversion options
        calibre version: 3.36.0
        {'allow_conversion_with_errors': False,
         'asciiize': False,
         'author_sort': None,
         'authors': None,
         'base_font_size': 0.0,
         'book_producer': None,
         'change_justification': u'original',
         'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
         'chapter_mark': u'pagebreak',
         'comments': None,
         'cover': u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre_znjsju\\d8vllf.jpeg',
         'debug_pipeline': None,
         'dehyphenate': True,
         'delete_blank_paragraphs': True,
         'disable_font_rescaling': False,
         'dont_split_on_page_breaks': False,
         'duplicate_links_in_toc': False,
         'embed_all_fonts': False,
         'embed_font_family': None,
         'enable_heuristics': False,
         'epub_flatten': False,
         'epub_inline_toc': False,
         'epub_toc_at_end': False,
         'epub_version': u'2',
         'expand_css': False,
         'extra_css': None,
         'extract_to': None,
         'filter_css': u'',
         'fix_indents': True,
         'flow_size': 260,
         'font_size_mapping': None,
         'format_scene_breaks': True,
         'html_unwrap_factor': 0.4,
         'input_encoding': None,
         'input_profile': <calibre.customize.profiles.KindleInput object at 0x05A1B7F0>,
         'insert_blank_line': False,
         'insert_blank_line_size': 0.5,
         'insert_metadata': False,
         'isbn': None,
         'italicize_common_cases': True,
         'keep_ligatures': False,
         'language': None,
         'level1_toc': None,
         'level2_toc': None,
         'level3_toc': None,
         'line_height': 0.0,
         'linearize_tables': False,
         'margin_bottom': 5.0,
         'margin_left': 5.0,
         'margin_right': 5.0,
         'margin_top': 5.0,
         'markup_chapter_headings': True,
         'max_toc_links': 50,
         'minimum_line_height': 120.0,
         'no_chapters_in_toc': False,
         'no_default_epub_cover': False,
         'no_inline_navbars': False,
         'no_svg_cover': False,
         'output_profile': <calibre.customize.profiles.OutputProfile object at 0x05A1B910>,
         'page_breaks_before': u'/',
         'prefer_metadata_cover': False,
         'preserve_cover_aspect_ratio': False,
         'pretty_print': True,
         'pubdate': None,
         'publisher': None,
         'rating': None,
         'read_metadata_from_opf': u'C:\\Users\\HP\\AppData\\Local\\Temp\\calibre_znjsju\\uz7ydg.opf',
         'remove_fake_margins': True,
         'remove_first_image': False,
         'remove_paragraph_spacing': False,
         'remove_paragraph_spacing_indent_size': 1.5,
         'renumber_headings': True,
         'replace_scene_breaks': u'',
         'search_replace': '[]',
         'series': None,
         'series_index': None,
         'smarten_punctuation': False,
         'sr1_replace': None,
         'sr1_search': None,
         'sr2_replace': None,
         'sr2_search': None,
         'sr3_replace': None,
         'sr3_search': None,
         'start_reading_at': None,
         'subset_embedded_fonts': False,
         'tags': None,
         'timestamp': None,
         'title': None,
         'title_sort': None,
         'toc_filter': None,
         'toc_threshold': 6,
         'toc_title': None,
         'transform_css_rules': '[]',
         'unsmarten_punctuation': False,
         'unwrap_lines': True,
         'use_auto_toc': False,
         'verbose': 2}
        InputFormatPlugin: KFX Input running
        on C:\Users\HP\AppData\Local\Temp\calibre_znjsju\lvaoep.kfx-zip
        Software versions: KFX Input 1.12.0, calibre 3.36, Windows-10-10.0.17134-SP0
        KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
        Converting C:\Users\HP\AppData\Local\Temp\calibre_znjsju\lvaoep.kfx-zip
        Processing container: B008593O8S_EBOK.azw
        Traceback (most recent call last):
          File "calibre_plugins.kfx_input.__init__", line 102, in convert
          File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 96, in convert_to_epub
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
          File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
        KFXDRMError: Book container B008593O8S_EBOK.azw has DRM and cannot be converted
        Python function terminated unexpectedly
          This book has DRM! (Error Code: 1)
        Traceback (most recent call last):
          File "site.py", line 101, in main
          File "site.py", line 78, in run_entry_point
          File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
          File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
          File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
          File "site-packages\calibre\customize\conversion.py", line 244, in __call__
          File "calibre_plugins.kfx_input.__init__", line 105, in convert
        calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Oddly, it says "KFX DRM voucher successfully decrypted"  then right after that "Ultimately failed to decrypt".  The only thing I can think to suggest is trying 64-bit calibre.

What version of Kindle for PC gave you that message about needing to update?

**Comment by rajkishoreworks** [comment]
I'm already using 64-bit calibre.

_Kindle for PC_ **1.17**, **1.20** are giving message about needing to update.
And I also get the same message, when I try second method from https://www.mobileread.com/forums/showthread.php?t=283371 , which is below command-

`ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx`

**Comment by rajkishoreworks** [comment]
Yayy! It works with 64-bit. I was having the same 64-bit version earlier but may be during Calibre upgrade, I by mistakenly installed 32-bit version. It was such a pain but you made my day. Thanks Man! appreciate it.

**Comment by ElleKayEm** [comment]
Glad that worked.  Thanks for letting us know.
