### ISSUE TITLE
KFX-Zip books not imported

### ISSUE THREAD

**Issue by FelixVA** [apprenticeharper/DeDRM_tools#715]
Hi,

Another failed to import property report. Calibre does import but I get a KFX-ZIP file, which Calibre then won't convert.

Here is my log file:

calibre Debug log
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
calibre 3.36  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 0) && KFX metadata reader (from KFX Input) (1, 12, 0) && KFX Input (1, 12, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.0567375887 x 71.8867924528
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.95] main UI initialized...
[1.95] Hiding splash screen
[34.77] splash screen hidden
[34.77] Started up in 34.77 seconds with 22 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: [',#\xbb\xdcw\xd1\x13\xfdO\x0f|v2\x14\xd0u*\x8ev\x97\xd94u\x82\x8c|\x02\xea\x1d\xa8\x98;', 'C:\\Users\\cnhmxfvargas\\Documents\\My Kindle Content\\B00LA9GA5O_EBOK\\B00LA9GA5O_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.0: Importing C:\Users\cnhmxfvargas\Documents\My Kindle Content\B00LA9GA5O_EBOK\B00LA9GA5O_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\CNHMXF~1\AppData\Local\Temp\calibre_w1l7br\wv1ob3.kfx-zip
DeDRM v6.6.1: Trying to decrypt wv1ob3.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: wv1ob3
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.415db7d9-5629-4a0a-8caf-986cf6c124b3.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\cnhmxfvargas\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.0: Packaging C:\Users\CNHMXF~1\AppData\Local\Temp\calibre_w1l7br\wv1ob3.kfx-zip
Processing container: B00LA9GA5O_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B00LA9GA5O_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\CNHMXF~1\AppData\Local\Temp\calibre_w1l7br\eitbwz_add_books\0\B00LA9GA5O_EBOK.kfx-zip
Added The Beginner's Guide to Intercessory Prayer to db in: 0.3
Added 1 books in 2.0 seconds

**Comment by ElleKayEm** [comment]
Use Kindle for PC 1.24 or earlier.

**Comment by FelixVA** [comment]
Thanks! I went down to 1.17. It worked!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
