### ISSUE TITLE
DeDRM textbook for printing

### ISSUE THREAD

**Issue by JayCeeDeDRM** [apprenticeharper/DeDRM_tools#717]
The following info came from the command prompt to debug. How do I get Calibre to DeDRM my textbook.

Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\johnn>calibre-debug -g
calibre 3.36  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[1.83] main UI initialized...
[1.83] Hiding splash screen
[2.48] splash screen hidden
[2.48] Started up in 2.48 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['<5\n\x86\xa5j\x1b\xf6B-p\t \xf9\x88\xc2\x1f\xe1w\xd3\xde\xd0Y\x96\xc51\xad:\x17\x17\nZ', 'C:\\Users\\johnn\\OneDrive\\Documents\\My Kindle Content\\B01MTFHLLE_EBOK\\B01MTFHLLE_EBOK.azw']
DeDRM v6.6.1: Trying to decrypt B01MTFHLLE_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Environmental Science
Found 0 keys to try after 1.5 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 1.5 seconds
searching for kinfoFiles in C:\Users\johnn\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 1.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Environmental Science to db in: 3.2
Added 1 books in 5.8 seconds
Worker Launch took: 0.156999826431

**Comment by ElleKayEm** [comment]
Use Kindle for PC version 1.24 or earlier.

**Comment by j-howell** [comment]
Be aware that if you rented that textbook instead of buying it then these tools will not remove DRM from it.

**Comment by JayCeeDeDRM** [comment]
Textbook was purchased not rented
