### ISSUE TITLE
Nook DRM

### ISSUE THREAD

**Issue by Chaormz** [apprenticeharper/DeDRM_tools#722]
I looked at a few current issues but they seem to be related to comic books. I have about 70 books i'm trying to pull into calibre, none are removing their DRM. I'm using a MAC. I'm downloading the books straight from my nook to calibre directly. Any insight will be helpful. Thanks. 

calibre Debug log
calibre 3.36  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.36  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.000001712 x 114.000001712
Using calibre Qt style: True
[0.00] Starting up...
[0.05] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.43] db initialized
[0.43] Constructing main UI...
[2.53] main UI initialized...
[2.53] Hiding splash screen
[2.53] splash screen hidden
[2.54] Started up in 2.54 seconds with 0 books
DeDRM v6.6.1: Trying to decrypt 9780062190185.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “9780062190185.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.1: Trying Encryption key NookX
Could not decrypt uWzSxr.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 160, in __init__
IGNOBLEError: AES improper key used

DeDRM v6.6.1: Failed to decrypt with key NookX after 0.5 seconds
DeDRM v6.6.1: Looking for new NOOK Study Keys after 0.5 seconds
Found nookStudy log file: /Users/barb/Library/Application Support/Barnes & Noble/DesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/barb/Library/Application Support/Barnes & Noble/DesktopReader/indices/BNClientLog.txt
Found nookStudy log file: /Users/barb/Library/Application Support/Barnes & Noble/BNDesktopReader/logs/BNClientLog.txt
Found nookStudy log file: /Users/barb/Library/Application Support/Barnes & Noble/BNDesktopReader/indices/BNClientLog.txt
DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 301, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Rise of Nine to db in: 0.1
Added 1 books in 1.5 seconds
2019-01-01 17:29:56.320 Calibre[8784:448250] deliverNotificationWithTitle()
* Notification delivered.
2019-01-01 17:30:13.150 Calibre[8788:448439] deliverNotificationWithTitle()
* Notification delivered.

{'bsd_drives': {'main': u'/dev/disk5'},
 'drives': {'main': '/Volumes/nook'},
 'mount_map': {'/dev/disk0s2': '/',
               '/dev/disk1s2': '/Volumes/EPubsoft DRM Removal',
               '/dev/disk2s1': '/Volumes/calibre-3.36.0',
               '/dev/disk3s1': '/Volumes/ADE 4.5',
               '/dev/disk4s2': '/Volumes/NOOK DRM Removal',
               '/dev/disk5': '/Volumes/nook',
               '/dev/disk6': '/Volumes/NOOKStudy',
               'devfs': '/dev',
               'localhost:/tTbzhF8s5pmJCNBsPpt3G8': '/Volumes/MobileBackups',
               'map -hosts': '/net',
               'map auto_home': '/home'}}
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= NOOK oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/nook/ my documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/nook/my documents
DEBUG:    0.0 USBMS: count found in cache: 7, count of files in metadata: 7, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= NOOK oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= NOOK oncard= cardb
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 7
Job: 1 Get device information finished
No details available.
Job: 2 Set library information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
DeviceJob: set_books_in_library finished: time= 0.0329508781433
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 3 Get list of books on device finished
No details available.
Worker Launch took: 0.468411922455
Job: 4 Convert book 1 of 1 (The Rise of Nine) finished
Convert book 1 of 1 (The Rise of Nine)
	Conversion options changed from defaults:
	  prefer_author_sort: True
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/5s/7j0ftr_n40s2226sj2rrndqr0000gn/C/calibre_3.36.0_tmp_DBVA_P/b3lJkC.opf'
	  output_profile: 'generic_eink'
	Resolved conversion options
	calibre version: 3.36.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10a9d9b10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter

**Comment by ElleKayEm** [comment]
It seems like the books on your device are using a different key.  Are they fresh downloads?  Is the key in the plugin from your current B&N account login and password?

Since I see you have Nookstudy installed, you might try books downloaded with that.

**Comment by ElleKayEm** [comment]
Yeah, those books undoubtedly are tied to an old out-of-date key.

Here's a link for Nook for Mac:

http://images.barnesandnoble.com/PResources/download/ereader2/bn/mac/NOOKforMac.dmg.zip

And here is Nookstudy for Mac:

http://images.barnesandnoble.com/PResources/download/ereader2/sc/BN/mac/NOOKstudy.dmg.zip

I don't know if either will work.  B&N stopped updating and officially supporting the desktop programs for both Mac and PC years ago.  The PC versions worked for me the last time I tried them a couple weeks ago.  However, they've always been buggy and troublesome.  I've had success just letting them sit with nothing else running.  Or closing and restarting if it's been unresponsive for a really long time.  Don't know if the same is true for the Mac versions.

If you have any way to try on a Windows machine, here are the PC versions:

http://images.barnesandnoble.com/PResources/download/eReader2/bndr2_setup_latest.exe

http://images.barnesandnoble.com/PResources/download/ereader2/sc/BN/pc/NOOKstudy_Setup.exe

**Comment by mjr2204** [comment]
Nook Study won't allow me to log in, and I'm getting a "technical difficulties" error (2157) when I try to download my books from Nook for PC.

The plug-in doesn't seem to work with books downloaded from the Windows Store version of the Nook app.

Does anyone have a work-around yet?

**Comment by ElleKayEm** [comment]
The trick with Nookstudy is to close it before your login attempt errors out.  When you reopen, you'll be logged in.

If you tried the Windows app again after trying Nookstudy, DeDRM may have found another key in the Nookstudy log which also worked on the Nook app books.  So you might not have to worry about having Nook for PC open.

(Incidentally, Nook for PC will still download DRM-free books.)

**Comment by mjr2204** [comment]
Nook for PC isn’t downloading books at all for me. Getting the 2157 technical difficulties error. Windows store app downloads them fine.

I’m going to try that with Nook Study, though. Thanks!

**Comment by jamosb** [comment]
nook study wont connect anymore either any other solutions. I heard a rumor that it can work through the Microsoft app but haven't gotten that to work either.

**Comment by Crewmom** [comment]
Same problem here.  Now that Nook for PC and Nook Study won't connect.  I have the book from the Windows Nook app, how do I get it deDRMed?

**Comment by ElleKayEm** [comment]
If you have a key which worked with books from the older apps, it may work with Windows Nook app books too.  The only other way I know to find it is on a rooted android device with the Nook app or an older rooted Nook device.

**Comment by mjr2204** [comment]
Open the old app and the new app. 

Download in the new app. Find your books. 

Leave both apps open and then deDRM. 

It’s been working for me.

**Comment by ElleKayEm** [comment]
Working for me too, but no need to open the old app.

**Comment by Sogl** [comment]
Any ideas how to deDRM Nook book in the end of 2019? Nook for PC and Nook study doesn't work.

**Comment by ElleKayEm** [comment]
See Issue #814.
