### ISSUE TITLE
DeDRM doesn't work

### ISSUE THREAD

**Issue by woewi** [apprenticeharper/DeDRM_tools#723]
After installing Calibre I then added DeDRM for Windows. However nothing seems to work. I tried various ebooks - no luck.
The PC is an Acer Aspire 5 A517-51G-80LF. The ebook file is from my personal Kindle.
Here is the protocol:
calibre Fehlerdiagnoseprotokoll
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.03] main UI initialized...
[1.03] Hiding splash screen
Storage number map:
{(7L, 0L): [(1L, 'D')], (7L, 1L): [(3L, 'C')], (7L, 2L): [(1L, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B00E15011447233F&0: StorageDeviceNumber(type=7L, number=2L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=6)
{u'drive_letters': ['F'],
 u'pnp_id_map': {'F': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b00e15011447233f&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'F': (2L, 1L)}}
Job: 1 Geräteinformationen abrufen started
DeviceJob: 1 Geräteinformationen abrufen done, calling callback
DeviceJob: 1 Geräteinformationen abrufen callback returned
Job: 2 Bibliotheksinformationen festlegen started
DeviceJob: 2 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 2 Bibliotheksinformationen festlegen callback returned
Job: 3 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.0 USBMS: scan from root False F:\documents
DEBUG:    0.0 USBMS: count found in cache: 22, count of files in metadata: 22, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 3 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 22
DeviceJob: set_books_in_library finished: time= 0.00200009346008
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Gerätebücherliste abrufen callback returned
Job: 2 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
Job: 3 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 1 Geräteinformationen abrufen finished
Keine Details verfügbar.
[25.39] splash screen hidden
[25.39] Started up in 25.39 seconds with 18 books
Job: 4 Dateien zur Übertragung vom Gerät vorbereiten started
DeviceJob: 4 Dateien zur Übertragung vom Gerät vorbereiten done, calling callback
DeviceJob: 4 Dateien zur Übertragung vom Gerät vorbereiten callback returned
DeDRM v6.6.1: Trying to decrypt The Pillars of the Earth TV Tie-asin_B003GK21JO-type_EBOK-v_0.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Pillars of the Earth: TV Tie-in
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Standard\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Pillars of the Earth: TV Tie-in to db in: 3.7
Job: 4 Dateien zur Übertragung vom Gerät vorbereiten finished
Keine Details verfügbar.
Added 1 books in 4.1 seconds
DeviceJob: set_books_in_library: books to process= 22
DeviceJob: set_books_in_library finished: time= 0.00899982452393
Job: 5 Buch auf Gerät anzeigen started
DeviceJob: 5 Buch auf Gerät anzeigen done, calling callback
DeviceJob: 5 Buch auf Gerät anzeigen callback returned
Worker Launch took: 0.129999876022
Job: 5 Buch auf Gerät anzeigen finished
Keine Details verfügbar.

**Comment by ElleKayEm** [comment]
For a book directly from a Kindle, it needs to be an E-ink Kindle (not a Fire), and you need to enter its serial number into the plugin customization.

**Comment by woewi** [comment]
I don't know for sure, what kind of Kindle it is. I believe an ordinary one, before the Fire was out, about 6 years old. Would that mean, I can't convert the books at all?

**Comment by ElleKayEm** [comment]
If it is an ordinary black and white screen Kindle, then you can remove the DRM and convert.  Just put its serial number into the E-ink Kindle section of the plugin customization.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
