### ISSUE TITLE
Can't remove DRM 

### ISSUE THREAD

**Issue by gabyblech** [apprenticeharper/DeDRM_tools#731]
Installed the Calibre plugin, removed the offending books then reimported. Still unable to convert to iPad format.

here is the log

calibre Debug log
calibre 3.37  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.37  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 96.0000014418 x 95.0000014268
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.20] main UI initialized...
[1.20] Hiding splash screen
[1.24] splash screen hidden
[1.24] Started up in 1.24 seconds with 46 books
DeDRM v6.6.1: Trying to decrypt Our Australian Girl Alice of Pep-asin_B008CNZYXA-type_EBOK-v_0.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Our Australian Girl: Alice of Peppermint Grove (Book 3): Alice of Peppermint Grove (Book 3)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

Debugging DND event
text/uri-list 120 'file:///Users/gabrielblecher/Gdrive/Dana/Our%20Australian%20Girl%20Alice%20of%20Pep-asin_B008CNZYXA-type_EBOK-v_0.azw3\r\n' 

Firefox rurl: None None
URLS: ['file:///Users/gabrielblecher/Gdrive/Dana/Our%20Australian%20Girl%20Alice%20of%20Pep-asin_B008CNZYXA-type_EBOK-v_0.azw3']
Paths: [u'/Users/gabrielblecher/Gdrive/Dana/Our Australian Girl Alice of Pep-asin_B008CNZYXA-type_EBOK-v_0.azw3']
Extensions: frozenset([u'azw3'])
Added Our Australian Girl: Alice of Peppermint Grove (Book 3): Alice of Peppermint Grove (Book 3) to db in: 0.0
Added 1 books in 0.6 seconds

**Comment by ElleKayEm** [comment]
Was this book downloaded from the website or directly from a Kindle device?  For those, the device needs to be an E-ink Kindle (not a Fire), and you need to enter its serial number into the plugin customization.

**Comment by gabyblech** [comment]
I believe the books were downloaded directly from an old keyboard kindle

But now I wish to put the books on an iPad running the kindle app

**Comment by ElleKayEm** [comment]
Then put the Kindle Keyboard's serial number in the plugin customization.

But to read them in the Kindle app on an iPad, just download new copies there.
