### ISSUE TITLE
cannot remove drm (google book)

### ISSUE THREAD

**Issue by btteamss** [apprenticeharper/DeDRM_tools#733]
I have dowlonad the pdf from ADE 2.0 (i am using google book and imported the acsm file to ADE 2.0) and import to calibre. However, the drm cannot be remove as the calibre viewer cannot read the book and cannot convert the book

here are the log
calibre Debug log
calibre 2.83  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.664921466 x 127.590697674
Starting up...
Started up in 12.77 seconds with 44 books
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added 0 books in 20.1 seconds
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 416, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 342, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Added Germany Since 1945 to db in: 0.2
Added 1 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
Try again with the latest version of 64-bit calibre (currently 3.37).  And I don't even see the DeDRM plugin get initialized here.  Are you sure you have it installed?  Do you have it disabled?
