### ISSUE TITLE
deDRM not working

### ISSUE THREAD

**Issue by laiceyshae** [apprenticeharper/DeDRM_tools#734]
Using Mac 10.13.1
Kindle 1.25.2
latest calibre and drm packages. It worked previously until I updated Calibre and now it's not working at all. 

I don't know anything about computers. Please help :(

calibre Debug log
calibre 3.30  embedded-python: True is64bit: True
Darwin-17.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.30  embedded-python: True is64bit: True
Darwin-17.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.13.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.88] main UI initialized...
[1.88] Hiding splash screen
[1.92] splash screen hidden
[1.93] Started up in 1.93 seconds with 9 books
objc[4916]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffae9aca70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11a702cd8). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing /Users/baileyfrancom/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B00HYMCIZC_EBOK/B00HYMCIZC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/b4/q9xk45xx11vg5ph4w7wxdrvw0000gn/C/calibre_3.30.0_tmp_n1owQr/aXq8nU.kfx-zip
DeDRM v6.6.1: Trying to decrypt aXq8nU.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: aXq8nU
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.59594eb3-ab2e-4bd7-b10c-4db2d2a834c7.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B00HYMCIZC_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.12.1: Packaging /var/folders/b4/q9xk45xx11vg5ph4w7wxdrvw0000gn/C/calibre_3.30.0_tmp_n1owQr/aXq8nU.kfx-zip
Processing container: B00HYMCIZC_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/b4/q9xk45xx11vg5ph4w7wxdrvw0000gn/C/calibre_3.30.0_tmp_n1owQr/Y76h7O_add_books/0/B00HYMCIZC_EBOK.kfx-zip
Added Chinese Rules to db in: 0.0
Added 1 books in 1.2 seconds
2019-01-13 12:25:05.766 Calibre[4934:1025423] deliverNotificationWithTitle()
* Notification delivered.

**Comment by ElleKayEm** [comment]
You'll need to go back to a previous version of Kindle for Mac.  Be sure to uncheck the option for auto-updates even before uninstalling 1.25.  Then make sure it's still unchecked when you get the older version installed.  For a link to the last working version, see the bottom of the first post here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by JayBrown** [comment]
I can import azw (KFX-zip) freshly downloaded with Kindle for macOS v1.25.2 into Calibre with DeDRM and Howell's plugin enabled, all the metadata is there, but I can't read them in the Calibre viewer, and I can't convert them either.

However, there's no going back to earlier versions of Kindle for Mac, because those are 32-bit. Sure, that old junk still runs on macOS, including Mojave, but not for long, so we'll eventually need a method to remove DRM from KFX-zip.

**Comment by laiceyshae** [comment]
@apprenticealf @apprenticeharper - is this a known issue?

**Comment by j-howell** [comment]
The FAQ was recently updated to indicate that version 1.25 of Kindle for Mac is not supported. [A Recent Change to Kindle for PC/Kindle for Mac](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac) (Kindle for PC is not mentioned but the same applies to that software.)
