### ISSUE TITLE
DeDRM Won't Convert

### ISSUE THREAD

**Issue by Dabble95** [apprenticeharper/DeDRM_tools#735]
I'm trying to convery a book that I've purchased. I use Kindle for PC. Here is an error log. 

calibre Debug log
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[1.83] main UI initialized...
[1.83] Hiding splash screen
[10.08] splash screen hidden
[10.08] Started up in 10.08 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt B0792X6DX3_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright ﾂｩ 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 繧・ｏ繧峨°3DCG謨吝ｮ､
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Elijah\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added やわらか3DCG教室 to db in: 5.2
Added 1 books in 6.8 seconds
Worker Launch took: 0.204999923706

**Comment by Dabble95** [comment]
Don't worry about it. I was able to solve my issue.

**Comment by Dabble95** [comment]
Was using Kindle 1.25. Had to re-install to Kindle 1.24 and check the option to not auto-update to 1.25.
