### ISSUE TITLE
De_DRM tool for Windows not working

### ISSUE THREAD

**Issue by Kaetrin** [apprenticeharper/DeDRM_tools#740]
I've been using the Windows App for De-DRM since 2017 without any issues. This month the app stopped working. Now it doesn't do anything when I drag and drop. The Calibre de-DRM still works but I prefer the drag and drop and I'd like to get it working again.  I haven't changed anything on my PC. 

I've uninstalled Python and downloaded the latest version and installed it. I have downloaded the latest version of Pycrypto and uninstalled previous versions. I've downloaded the latest tools (6.6.1). So far nothing has worked. 

I have no programming experience. I'm not sure what information I need to tell folks to get some help.  I've been referred here via Apprentice Alf's blog. I'm hoping someone can point me in the right direction?

**Comment by ElleKayEm** [comment]
What type of books were you trying to DeDRM?  And what version of DeDRM were you using when it stopped working?

**Comment by Kaetrin** [comment]
I had been using tools 6.5.3. Both Kindle books (Kindle for PC) and Adobe DE books. No problem from 2017 until it stopped working in January this year for no apparent reason.  The Calibre plugin still works, I just prefer the drag and drop because reasons.

*I should also add that when I read the ReadMe file in the latest version of the tools, it said I needed Python 2.7 and Pycrypto 2.6 so I have uninstalled the other versions and installed these versions from the links in the ReadMe file (which was essentially what I had originally) but it's still not working. I've followed all the instructions but nothing.

**Comment by Kaetrin** [comment]
Update: A helpful person at Apprentice Alf's blog suggested I install version 6.5.5 of the tools and try that. It has helped in that the app is now working. I can't strip epub books at present but it's working on kindle books. I'm trying to sort out why the Adobe DE isn't working but I think the app itself is doing what it's supposed to and it's actually telling me it's doing something now.

**Comment by Kaetrin** [comment]
Yes

**Comment by Kaetrin** [comment]
I just downloaded a further copy of a DRM book from my Kobo account and the same error message appears: 
Using Library AlfCrypto DLL/DYLIB/SO
No nook Study log files have been found.
Using Library AlfCrypto DLL/DYLIB/SO

**Comment by ElleKayEm** [comment]
Hmm, not sure why it's not telling us about an error trying to unlock the Adobe book.

I know you want to get the stand-alone working, but I'm curious if you're able to get these same epubs unlocked with the plugin.

**Comment by Kaetrin** [comment]
Yes I can. Absolutely no issue! The Calibre plugins never stopped working (from 6.5.3). I haven't reinstalled them from tools 6.5.5 because the old ones still worked.

**Comment by ElleKayEm** [comment]
I'm not familiar wirh the stand-alone myself...is there an option in the preference settings to import an Adobe Key?  If there is, you could try saving your key from the plugin and importing it into the stand-alone.

**Comment by Kaetrin** [comment]
I tried that but it didn't work. I'm not sure why I'm getting an error message about Nook study when I'm not trying to strip DRM off a Nook book. It's a conundrum.

**Comment by Kaetrin** [comment]
I've tried a few things, none of them have worked but the last time I did get a longer error message:
Using Library AlfCrypto DLL/DYLIB/SO
No nook Study log files have been found.
Using Library AlfCrypto DLL/DYLIB/SO
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "D:\Users\User\Documents\DeDRM_App\DeDRM_lib\DeDRM_App.pyw", line 434, in doit
    self.master.cd.doit(self.prefs_array,filenames)
  File "D:\Users\User\Documents\DeDRM_App\DeDRM_lib\DeDRM_App.pyw", line 490, in doit
    self.processBooks()
  File "D:\Users\User\Documents\DeDRM_App\DeDRM_lib\DeDRM_App.pyw", line 515, in processBooks
    self.logfile.write("DeDRM v{0}: {1}\n".format(__version__,msg))
ValueError: I/O operation on closed file


I'm not sure if that sheds any light?
