### ISSUE TITLE
kindle pc drm not working

### ISSUE THREAD

**Issue by jje6421** [apprenticeharper/DeDRM_tools#741]
calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 95.25 x 95.25
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.25] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[3.05] main UI initialized...
[3.05] Hiding splash screen
[8.66] splash screen hidden
[8.66] Started up in 8.66 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xae\xd9\xfd\xad\xb6,\x13.(Be\x965\xe3\xe1\xaa\xe9\xae\x99\\)\x9f\xa6\xf0!\x91\xe1\x8e\x85\xab\x0c\xd7', 'C:\\Users\\JakFalTrades\\Documents\\My Kindle Content\\B01CECMA90_EBOK\\B01CECMA90_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:\Users\JakFalTrades\Documents\My Kindle Content\B01CECMA90_EBOK\B01CECMA90_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\JAKFAL~1\AppData\Local\Temp\calibre_3hjnrj\liaqjf.kfx-zip
DeDRM v6.6.1: Trying to decrypt liaqjf.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: liaqjf
Found 0 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5d65a7d4-273b-4f31-a5de-abe76dbf7850.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\JakFalTrades\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.12.1: Packaging C:\Users\JAKFAL~1\AppData\Local\Temp\calibre_3hjnrj\liaqjf.kfx-zip
Processing container: B01CECMA90_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B01CECMA90_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\JAKFAL~1\AppData\Local\Temp\calibre_3hjnrj\zgzah4_add_books\0\B01CECMA90_EBOK.kfx-zip
Added Hero to the Rescue (The Hunter Legacy Book 8) to db in: 0.6
Added 1 books in 3.8 seconds
Worker Launch took: 0.469000101089
Job: 1 Convert book 1 of 1 (Hero to the Rescue (The Hunter Legacy Book 8)) finished
Convert book 1 of 1 (Hero to the Rescue (The Hunter Legacy Book 8))
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\JAKFAL~1\\AppData\\Local\\Temp\\calibre_3hjnrj\\sutt_k.jpeg'
	  output_profile: 'tablet'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\JAKFAL~1\\AppData\\Local\\Temp\\calibre_3hjnrj\\olsxni.opf'
	Resolved conversion options
	calibre version: 3.38.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\JAKFAL~1\\AppData\\Local\\Temp\\calibre_3hjnrj\\sutt_k.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05642F30>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x0564B550>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\JAKFAL~1\\AppData\\Local\\Temp\\calibre_3hjnrj\\olsxni.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\JAKFAL~1\AppData\Local\Temp\calibre_3hjnrj\cjb36b.kfx-zip
	Software versions: KFX Input 1.12.1, calibre 3.38.1, Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\JAKFAL~1\AppData\Local\Temp\calibre_3hjnrj\cjb36b.kfx-zip
	Processing container: B01CECMA90_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 96, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
	KFXDRMError: Book container B01CECMA90_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Are you using version 1.25 of Kindle for PC?  If so, uncheck auto-update and go back to at least version 1.24.

**Comment by j-howell** [comment]
From the log:

> DeDRM v6.6.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

**Comment by philgoetz** [comment]
> Are you using version 1.25 of Kindle for PC? If so, uncheck auto-update and go back to at least version 1.24.

Go back how?

**Comment by j-howell** [comment]
> Go back how?

See [this thread on MobileRead](https://www.mobileread.com/forums/showthread.php?t=283371).

> How did you produce a calibre debug log?

Instructions are in the [FAQ](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md).

**Comment by ElleKayEm** [comment]
Here's a direct link to the section of the facts with instructions for producing a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
