### ISSUE TITLE
Kindle macOS Calibre DeDRM suddenly stopped working Jan 2019.

### ISSUE THREAD

**Issue by minimondo** [apprenticeharper/DeDRM_tools#742]
3 days ago I was able to download any purchased Kindle books and de-drm them. Today I installed the new Calibre 3.38.1 and the de-drm ceased working. I reverted to 3.38.0, reinstalled all Calibre plugins but still no DRM removal. I am using the most recent version (6.6.1).

The Kindle reader I use hasn't been updated for 18 months. I have read the FAQ but remain baffled. The log contains the error message trio:

DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.

Any help would be most appreciated. Log file follows...
=========================================================

QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
QCoreTextFontDatabase: Failed to resolve family name for PostScript name  "AppleMyungjo"
EpubMerge: DEBUG: 2019-01-21 22:09:02,762: calibre_plugins.epubmerge.epubmerge_plugin(154): macmenuhack file_path:/Users/XXXXXXXX/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 3.38  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && EpubSplit (2, 6, 0) && Amazon.com Multiple Countries (1, 0, 0) && Goodreads (1, 4, 0) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0) && Kindle hi-res covers (0, 4, 0) && Kindle Collections (1, 7, 23) && Barnes & Noble (1, 2, 15) && EpubMerge (2, 5, 0) && Kobo Books (1, 5, 0) && KindleUnpack - The Plugin (0, 81, 5)
calibre 3.38  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1) && EpubSplit (2, 6, 0) && Amazon.com Multiple Countries (1, 0, 0) && Goodreads (1, 4, 0) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0) && Kindle hi-res covers (0, 4, 0) && Kindle Collections (1, 7, 23) && Barnes & Noble (1, 2, 15) && EpubMerge (2, 5, 0) && Kobo Books (1, 5, 0) && KindleUnpack - The Plugin (0, 81, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.01] main UI initialized...
[1.01] Hiding splash screen
[1.01] splash screen hidden
[1.02] Started up in 1.02 seconds with 0 books
2019-01-21 22:09:27.117 calibre-debug[55408:4033116] [QL] file:///Users/XXXXXXX/Library/QuickLook/epub.qlgenerator/ has no identifier: ignoring
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing /Users/XXXXXXX/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B01AQGKKJ8_EBOK/B01AQGKKJ8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/hzYKxg.kfx-zip
DeDRM v6.6.1: Trying to decrypt hzYKxg.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: hzYKxg
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4e0028ae-7a10-4acd-b3e9-41458fdfa471.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 77, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
KFXDRMError: Book container B01AQGKKJ8_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.12.1: Packaging /var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/hzYKxg.kfx-zip
Processing container: B01AQGKKJ8_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/6clXQD_add_books/0/B01AQGKKJ8_EBOK.kfx-zip
Added The Big Breach : From Top Secret To Maximum Security to db in: 0.0
Added 1 books in 1.0 seconds
2019-01-21 22:10:28.790 Calibre[55453:4038054] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.15469789505
Job: 1 Convert book 1 of 1 (The Big Breach : From Top Secret To Maximum Security) finished
Convert book 1 of 1 (The Big Breach : From Top Secret To Maximum Security)
	Conversion options changed from defaults:
	  output_profile: 'tablet'
	  verbose: 2
	  cover: u'/var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/Wge5ij.jpeg'
	  read_metadata_from_opf: u'/var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/6RlgsO.opf'
	Resolved conversion options
	calibre version: 3.38.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/Wge5ij.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x114db2d10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x114dbd950>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/6RlgsO.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 96, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 261, in get_container
	KFXDRMError: Book container B01AQGKKJ8_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM!
	InputFormatPlugin: KFX Input running
	on /var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/oVN76E.kfx-zip
	Software versions: KFX Input 1.12.1, calibre 3.38, Darwin-18.2.0-x86_64-i386-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/vv/mvytq58n5tb5wt25j_1w97dc0000gn/C/calibre_3.38.0_tmp_bAMT6W/oVN76E.kfx-zip
	Processing container: B01AQGKKJ8_EBOK.azw
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 199, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1106, in run
	  File "site-packages/calibre/customize/conversion.py", line 244, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by minimondo** [comment]
OK, cause of problem found.

Within the last 3 days, Amazon silently updated my Kindle app to version "1.25.2" dated 9 January 2019 (yes, I had the auto-update enabled). The new version is for the first time 64-bit, but apparently introduces some DRM mod. Annoyingly, on the version screen it left an 18 month old date for "last updated".

The closest "old" app I could find was "1.23.1". I completely removed all trace of the new Kindle and installed the old. Everything works perfectly again (except that I'm stuck with a 32-bit app again).

So I conclude that the version immediately before 1.25.2 was OK. If anyone knows where I can find it I would be grateful to hear.

Regards, M.

**Comment by j-howell** [comment]
You have the most recent release before 1.25. (There was no 1.24 release for MacOS.)

The 1.25 release is the first with 64-bit support, but it also introduces new DRM that these tools cannot handle.

**Comment by minimondo** [comment]
Thank you J. My apologies for not checking further beforehand. Cheers, M.

**Comment by j-howell** [comment]
> Do you have plans to support the new kinf2018 key file?

There are no plans. If someone comes up with a solution and shares it then I am sure that Apprentice Harper will add it to the tools.
