### ISSUE TITLE
DeDRM Plugin Not Working for KFX Files

### ISSUE THREAD

**Issue by emunk94** [apprenticeharper/DeDRM_tools#746]
I updated to the latest plugin and installed the KFX Plugin. 

calibre Debug log
calibre 2.67  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
devicePixelRatio: 1.0
logicalDpi: 192.0 x 192.0
physicalDpi: 267.286153846 x 267.801156069
Starting up...
Loaded cached store plugin for: Beam EBooks DE at version: 3
Loaded cached store plugin for: Legimi at version: 9
Loaded cached store plugin for: Amazon FR Kindle at version: 15
Loaded cached store plugin for: eBooks.com at version: 3
Loaded cached store plugin for: Amazon ES Kindle at version: 15
Loaded cached store plugin for: Woblink at version: 14
Loaded cached store plugin for: Empik at version: 8
Loaded cached store plugin for: Mills and Boon UK at version: 3
Loaded cached store plugin for: Publio at version: 9
Loaded cached store plugin for: Amazon CA Kindle at version: 7
Loaded cached store plugin for: Amazon DE Kindle at version: 15
Loaded cached store plugin for: Smashwords at version: 5
Loaded cached store plugin for: Google Books at version: 4
Loaded cached store plugin for: Baen Ebooks at version: 2
Loaded cached store plugin for: Amazon AU Kindle at version: 5
Loaded cached store plugin for: Ebookpoint at version: 8
Loaded cached store plugin for: Kobo at version: 7
Loaded cached store plugin for: Amazon UK Kindle at version: 15
Loaded cached store plugin for: ebook.de at version: 5
Loaded cached store plugin for: Amazon IT Kindle at version: 15
Loaded cached store plugin for: Amazon IN Kindle at version: 5
Loaded cached store plugin for: Amazon Kindle at version: 14
Loaded cached store plugin for: eBook.nl at version: 2
Loaded cached store plugin for: Virtualo at version: 9
Started up in 6.91 seconds with 13 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe7\xb8g\xd7\x95\xf2~\xfbzT\x97\x81!\xdb\xa6_\xb6$r\xcc\x81MU\xe9X\xc2.8\x88\xa4 \xc6', 'C:\\Users\\elyas\\OneDrive\\Documents\\My Kindle Content\\B06X9LVCYB_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:\Users\elyas\OneDrive\Documents\My Kindle Content\B06X9LVCYB_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B06X9LVCYB_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Social Policy for Effective Practice: A Strengths Approach
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
File is encoded with PID vBc/nDOeZ3.
Decrypting. Please wait . . . . . . . . . . done
Decryption succeeded after 0.3 seconds
DeDRM v6.6.1: Finished after 0.3 seconds
Added Social Policy for Effective Practice: A Strengths Approach to db in: 0.4
Added 1 books in 2.2 seconds

**Comment by emunk94** [comment]
> This file is not KFX and is successfully decrypted.

As someone who is a noob when it comes to these things. What exactly does this mean? Is it possible to convert this file?
Thanks

**Comment by ElleKayEm** [comment]
Yes, the DRM has been removed.  Try using 64-bit calibre and the Kindle Unpack plugin if you're having trouble converting it.

**Comment by emunk94** [comment]
Hi Still having issues. I can convert those that were originally in AZW4 but not those in AZW. Here is the log from one of the books that are having issuess 

Convert book 1 of 1 (Essential Psychopathology & Its Treatment (Fourth Edition))
Conversion options changed from defaults:
  read_metadata_from_opf: u'C:\\Users\\elyas\\AppData\\Local\\Temp\\calibre_eubnqm\\ujuq5e.opf'
  cover: u'C:\\Users\\elyas\\AppData\\Local\\Temp\\calibre_eubnqm\\cq835j.jpeg'
  output_profile: 'kindle_dx'
  verbose: 2
Resolved conversion options
calibre version: 3.38.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\elyas\\AppData\\Local\\Temp\\calibre_eubnqm\\cq835j.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B5CC128470>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleDXOutput object at 0x000001B5CC128A90>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\elyas\\AppData\\Local\\Temp\\calibre_eubnqm\\ujuq5e.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\elyas\AppData\Local\Temp\calibre_eubnqm\7u_ha0.azw
Found KF8 MOBI of type 'standalone'
Python function terminated unexpectedly
  Essential Psychopathology & Its Treatment (Fourth Edition) (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 101, in main
  File "site.py", line 78, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
calibre.ebooks.DRMError: Essential Psychopathology & Its Treatment (Fourth Edition)

**Comment by ElleKayEm** [comment]
DRM removal happens when you first import the book, not during conversion.  We'll need to see a log like the first one to see why DRM hasn't been removed.
