### ISSUE TITLE
DRM removal not working windows 10 surface pro kindle e book

### ISSUE THREAD

**Issue by joshneedshelp** [apprenticeharper/DeDRM_tools#749]
calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 12, 1) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 12, 1) && KFX metadata reader (from KFX Input) (1, 12, 1) && KFX Input (1, 12, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.0 x 108.213017751
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[2.11] main UI initialized...
[2.11] Hiding splash screen
[8.48] splash screen hidden
[8.48] Started up in 8.48 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['l\x086\xcdn\xdc\x1a\x84\x92x\xab\x9cp\x01og\xa3\x98\xfe\x88\xe6\xa5\x0eh\xd9M\xa5\xd2\x84\xf4e!', 'C:\\Users\\mahog\\OneDrive\\Documents\\My Kindle Content\\B071CNHYWD_EBOK\\B071CNHYWD_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.12.1: Importing C:\Users\mahog\OneDrive\Documents\My Kindle Content\B071CNHYWD_EBOK\B071CNHYWD_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B071CNHYWD_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Texas Insurance License Exam Study Course: General Lines â€“ Life, Accident, Health and HMO
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\mahog\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Texas Insurance License Exam Study Course: General Lines – Life, Accident, Health and HMO to db in: 0.5
Added 1 books in 2.6 seconds
Worker Launch took: 0.27999997139
Job: 1 Convert book 1 of 1 (Texas Insurance License Exam Study Course: General Lines – Life, Accident, Health and HMO) finished
Convert book 1 of 1 (Texas Insurance License Exam Study Course: General Lines – Life, Accident, Health and HMO)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\mahog\\AppData\\Local\\Temp\\calibre_k3o0jv\\othqje.opf'
	  output_profile: 'tablet'
	  cover: u'C:\\Users\\mahog\\AppData\\Local\\Temp\\calibre_k3o0jv\\std93c.jpeg'
	Resolved conversion options
	calibre version: 3.38.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\mahog\\AppData\\Local\\Temp\\calibre_k3o0jv\\std93c.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05C62F70>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x05C6A590>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\mahog\\AppData\\Local\\Temp\\calibre_k3o0jv\\othqje.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\mahog\AppData\Local\Temp\calibre_k3o0jv\fzbabm.azw
	Python function terminated unexpectedly
	  Texas Insurance License Exam Study Course: General Lines – Life, Accident, Health and HMO (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 37, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Texas Insurance License Exam Study Course: General Lines – Life, Accident, Health and HMO

**Comment by joshneedshelp** [comment]
thank you all for the assistance. i have no idea what isn't working. i could use any advice.

**Comment by joshneedshelp** [comment]
the book is not stripping the DRM no matter what i try. what am i doing wrong>?
