### ISSUE TITLE
DeDRM not working for AZW format

### ISSUE THREAD

**Issue by brajbhushan-tripathi** [apprenticeharper/DeDRM_tools#752]
I am running following:
1. Calibre version 3.38.1
2. DeDRM version 6.6.1
3. Kindle for PC 1..25.1 (disabled the KFX using ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx)

Downloaded the book which is in AZW format and dragged it to Calibre. When I try to open the book getting error "This book is locked by DRM". Here are the logs, please help:

Traceback (most recent call last):
  File "site-packages\calibre\utils\config.py", line 319, in refresh
  File "site-packages\calibre\utils\config.py", line 412, in raw_to_object
  File "json\__init__.py", line 352, in loads
  File "json\decoder.py", line 364, in decode
  File "json\decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded
DeDRM v6.6.1: Trying to decrypt B072MJ8SWY_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Dog Man and Cat Kid: From the Creator of Captain Underpants (Dog Man #4)
Found 0 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\brajb\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Dog Man and Cat Kid: From the Creator of Captain Underpants (Dog Man #4) to db in: 0.5
Added 1 books in 1.8 seconds

[tmp1p0wo5.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2801870/tmp1p0wo5.txt)

**Comment by j-howell** [comment]
> Kindle for PC 1..25.1 (disabled the KFX using ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx)

These tools will not work with Kindle for PC/Mac version 1.25 or greater.

**Comment by brajbhushan-tripathi** [comment]
> > Kindle for PC 1..25.1 (disabled the KFX using ren %localappdata%\Amazon\Kindle\application\renderer-test.exe renderer-test.xxx)
> 
> These tools will not work with Kindle for PC/Mac version 1.25 or greater.
> 
> See [this thread on MobileRead](https://www.mobileread.com/forums/showthread.php?t=283371) for solutions.

Can you please let me know how can I go to version 1.24?

**Comment by j-howell** [comment]
> Can you please let me know how can I go to version 1.24?

See the bottom of the first post in the thread I linked previously.
