### ISSUE TITLE
Fail to decrypt file

### ISSUE THREAD

**Issue by ringsaturn** [apprenticeharper/DeDRM_tools#757]
Hi,

I'm using Kindle 1.17.1 and DeDRM 6.6.1 but fail to decrypt file. Here is the log.

Before I running this Kindle 1.17.1, I have tried latest version of Kindle and I remove it with CleanMyMac.

```
There is 1 ebook to be decrypted.
Processing file: B00T9ZHR6C_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/ringsaturn/Downloads/DeDRM_tools_6/DeDRM_Macintosh_Application/B00T9ZHR6C_EBOK.azw' '/Users/ringsaturn/Desktop/' > '/Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.5.
Copyright © 2008-2017 Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Past Futures: The Impossible Necessity of History (Joanne Goodman Lectures)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 259, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 233, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.5
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/ringsaturn/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '45096e743513' and UserName 'ringsaturn'
Saved a key to /Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/KindleKey.der' '/Users/ringsaturn/Downloads/DeDRM_tools_6/DeDRM_Macintosh_Application/B00T9ZHR6C_EBOK.azw' '/Users/ringsaturn/Desktop/' > '/Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.5.
Copyright © 2008-2017 Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Past Futures: The Impossible Necessity of History (Joanne Goodman Lectures)
Got DSN key from database /Users/ringsaturn/Library/Preferences/com.apprenticealf.dedrm/KindleKey.der
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
File is encoded with PID 3nAgXeQpUB.
Decrypting. Please wait . . . . . done
Decryption succeeded after 0.0 seconds
 Traceback (most recent call last):
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 353, in <module>
    sys.exit(cli_main())
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 347, in cli_main
    return decryptBook(infile, outdir, kDatabaseFiles, androidFiles, serials, pids)
  File "/private/var/folders/10/m4vyjzrs5n36yjwb9_lm359r0000gn/T/AppTranslocation/4F316295-2D6A-4953-814F-C03D912B7BA2/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 272, in decryptBook
    outfilename = '{}_{}'.format(orig_fn_root, clean_title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 13: ordinal not in range(128)
There was an error with 1 ebook:
B00T9ZHR6C_EBOK.azw couldn't be decrypted.
```

**Comment by ElleKayEm** [comment]
Looks like this is a bug that has been mentioned in other issues here.  The problem seems to be with certain characters in the book's title.  Search issues for this error seen in your log:

>UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013'

Appears that a fix has been found, but it isn't in the released version yet.  See here:

https://github.com/apprenticeharper/DeDRM_tools/pull/685/commits/454286b08b62edd393babd65eea424d99308d474
