### ISSUE TITLE
DRM removal problem Kindle Touch / win 10 Home 32 bit

### ISSUE THREAD

**Issue by EnkaraMandula** [apprenticeharper/DeDRM_tools#758]
Greetings, 

I have a Kindle Touch. I have purchased an e-book from Amazon, succesfully downloaded it to both my Kindle and my computer (Asus T100TA netbook, 32 bit win10 home) via Calibre. I wanted to convert it to another format via Calibre. I have installed the DRM removal plugin and followed the instructions, plugin customization included with my device's serial number, but despite my efforts the conversion has failed several times. I tried to import the book from my Kindle for PC program (installed from Amazon), and also with just drag and drop via Total Commander from my laptop. Since I've returned the book to Amazon, I only have the downloaded version (AZW), that is what I've tried to convert the latest, and here is the log from the troubleshooting, if you may take a look at it and advice me, what did I do wrong. Thank you in advance! :) <3

Mandula

calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 150.853913043 x 150.055384615
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[3.86] main UI initialized...
[3.86] Hiding splash screen
[11.64] splash screen hidden
[11.64] Started up in 11.64 seconds with 1 books
DeDRM v6.6.1: Trying to decrypt Complete Hungarian_ Teach Yourself_ Audio eBook (Teach Yourself Audio eBooks) - Zsuzsanna Pontifex.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks)
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Mandula\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks) to db in: 0.5
Added 1 books in 3.3 seconds
Worker Launch took: 0.529000043869
Job: 1 Convert book 1 of 1 (Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks)) finished
Convert book 1 of 1 (Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks))
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_wnxtbi\\nzz6v2.opf'
	  output_profile: 'kindle'
	  cover: u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_wnxtbi\\2sjpod.jpeg'
	  remove_paragraph_spacing: True
	Resolved conversion options
	calibre version: 3.38.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_wnxtbi\\2sjpod.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x02754030>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x02754390>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_wnxtbi\\nzz6v2.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': True,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Mandula\AppData\Local\Temp\calibre_wnxtbi\z9rwfd.azw
	Python function terminated unexpectedly
	  Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 37, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Complete Hungarian: Teach Yourself: Audio eBook (Teach Yourself Audio eBooks)

**Comment by ElleKayEm** [comment]
Not willing to help with a book you've already gotten your money back for.

**Comment by EnkaraMandula** [comment]
The reason I have returned it was that all my devices turned out to be incompatible with the audio attachments of the book. For I have the original in paperback, I hoped that at least I can have the text parts in more portable format than AZW, in case if I wanted to read it not only my own devices.  Scanning it would be a b*tch, even if I had a scanner, but I don't. :( Please...?
