### ISSUE TITLE
k4i key not found from Kindle for PC - AZW format 8 decrypt failing

### ISSUE THREAD

**Issue by mcarans** [apprenticeharper/DeDRM_tools#76]
Thanks for a your work!

I have the latest Kindle for PC and latest plugin and decrypt fails with AZW (but works with Nook books). It seems unable to find my "default encryption key" when I tried clicking the green plus icon under customize plugin -> Kindle for Mac and PC Keys. The log for AZW is:

calibre Debug log
calibre 2.52 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 6.90 seconds with 14 books
DeDRM v6.3.6: Trying to decrypt XXXXXXXXX_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: XXXXXXXXX

Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.3.6: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.3.6: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\XXXXXX\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\XXXXXX\AppData\Local\Amazon\Kindle\storage\.kinf2011
DeDRM v6.3.6: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Alf's blog: http://apprenticealf.wordpress.com/
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 597, in run
  File "calibre_plugins.dedrm.__init__", line 547, in KindleMobiDecrypt
DeDRMError: DeDRM v6.3.6: Ultimately failed to decrypt after 0.2 seconds
Added XXXXXXX to db in: 0.3
Added 1 books in 1.1 seconds
Worker Launch took: 0.265999794006

**Comment by mcarans** [comment]
I uninstalled Kindle for PC, deleted my C:\Users\XXXXXX\AppData\Local\Amazon\Kindle\ and C:\Users\XXXXX\Documents\My Kindle Content folders, deregistered, reinstalled Kindle for PC and reregistered and the problem went away!
