### ISSUE TITLE
Default encryption key for Kindle not being generated on Mac

### ISSUE THREAD

**Issue by spinosman** [apprenticeharper/DeDRM_tools#762]
Downloaded book using Kindle for Mac (version 1.25.2) directly onto Mac running macOS Mojave (version 10.14.2). Then tried to de-DRM using DeDRM plugin (version 6.6.1) but the DRM does not get removed. I have already tried completely removing and re-installing all apps and plugins, but still no luck. Please help. Here is the debug output:

calibre Debug log
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.05] main UI initialized...
[1.05] Hiding splash screen
[1.11] splash screen hidden
[1.12] Started up in 1.12 seconds with 5 books
objc[3737]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa1736210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x111a65dc8). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing /Users/Osman/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B01JTV79X6_EBOK/B01JTV79X6_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/43/46gfc2j90kndrd54rk7rnbv80000gn/C/calibre_3.39.1_tmp_v3kkhk/9Ly4P5.kfx-zip
DeDRM v6.6.1: Trying to decrypt 9Ly4P5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 9Ly4P5
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.7d1751e9-dc79-4a00-a966-99573c656df2.voucher
DeDRM v6.6.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B01JTV79X6_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.13.0: Packaging /var/folders/43/46gfc2j90kndrd54rk7rnbv80000gn/C/calibre_3.39.1_tmp_v3kkhk/9Ly4P5.kfx-zip
Processing container: B01JTV79X6_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/43/46gfc2j90kndrd54rk7rnbv80000gn/C/calibre_3.39.1_tmp_v3kkhk/uyhDDz_add_books/0/B01JTV79X6_EBOK.kfx-zip
Added Age of Anger: A History of the Present to db in: 0.1
Added 1 books in 0.9 seconds

**Comment by j-howell** [comment]
See issue #752

**Comment by spinosman** [comment]
That worked. Thank you very much. Thanks also for the quick reply. Library saved. Regards, Osman
