### ISSUE TITLE
Plugin not working anymore (DeDRM Calibre Kindle Mac OS)

### ISSUE THREAD

**Issue by jorgefiffe** [apprenticeharper/DeDRM_tools#763]
Thanks to anyone here who can help!

I haven't used Calibre in a couple of months and when I tried to import some recently purchased Prime Reading ebooks I get "Cannot convert" and "This book is locked by DRM." messages.

I'm using Calibre 3.39.1 / DeDRM 6.6.1 plugin / Kindle for Mac 1.17.1 also have KFX input and KFX output plugins installed.

Here's the info from debug log:

calibre Debug log
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && Overdrive Link (2, 32, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0)
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && Overdrive Link (2, 32, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 26, 0) && KFX Output (1, 26, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.48] db initialized
[0.48] Constructing main UI...
[2.56] main UI initialized...
[2.56] Hiding splash screen
[2.60] splash screen hidden
[2.61] Started up in 2.61 seconds with 999 books
objc[2061]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffac7e0210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11935ddc8). One of the two will be used. Which one is undefined.
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing /Volumes/Casper/Kindle/My Kindle Content/B00AXS6BEI_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B00AXS6BEI_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Ludwig Conspiracy
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/fiffe/Library/Application Support/Kindle/storage/.kinf2011
Couldn't decrypt file.
DeDRM v6.6.1: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

**Comment by Michael55plus** [comment]
I have the same problem using same versions as jorgefiffe: using Calibre 3.39 / DeDRM 6.6.1 plugin / Kindle for PC 1.15.0 (Kindle reader), also have KFX input  plugin installed. All is installed on Ubuntu 16.04 LTS kernel version 4.15.0-45-generic. The book I cannot deDRM is bought not borrowed. I checked an older book I could deDRM formerly and it is possible to deDRM it also now. Only the new book cannot be deDRMd. calibre imports, but the ebook viewer complains, that the book has DRM.

**Comment by ElleKayEm** [comment]
Please start your own issue and post a log.

**Comment by sbibauw** [comment]
I had the same problem using the last version of Kindle for Mac (`1.25`): (log: `Found 0 keys to try after 0... seconds`).
I downgraded Kindle for Mac to a previous version (e.g. `1.17` via [this link](https://www.ebook-converter.com/222-drmexception-invalid-file-format.htm)) and it worked perfectly!

**Comment by ElleKayEm** [comment]
Be sure to verify that you have found an unmessed with setup file for version 1.17 by using the hash values shown under Method 1 here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by sbibauw** [comment]
@ElleKayEm Thank you for noting that! It is not exactly the same 1.17 version (`1.17.441732` vs. `1.17.44182`), so not sure about this precise link, so I removed the link.
