### ISSUE TITLE
Faced an issue while DeDRM an file

### ISSUE THREAD

**Issue by ahmadomar** [apprenticeharper/DeDRM_tools#768]
calibre Debug log
calibre 3.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.12+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Obok DeDRM (6, 5, 4)
calibre 3.36 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.12+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.048235294 x 102.669473684
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Loaded cached store plugin for: Google Books at version: 5
[1.77] main UI initialized...
[1.77] Hiding splash screen
[11.86] splash screen hidden
[11.86] Started up in 11.86 seconds with 15 books
Worker Launch took: 0.165999889374
Job: 1 Convert book 1 of 1 (Machine Learning for Absolute Beginners: A Plain English Introduction (First Edition)) finished
Convert book 1 of 1 (Machine Learning for Absolute Beginners: A Plain English Introduction (First Edition))
	Conversion options changed from defaults:
	  allow_conversion_with_errors: True
	  verbose: 2
	  output_profile: 'kindle_pw3'
	  cover: u'C:\\Users\\admin\\AppData\\Local\\Temp\\calibre_ihkrdm\\2bljyv.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\admin\\AppData\\Local\\Temp\\calibre_ihkrdm\\wkragh.opf'
	Resolved conversion options
	calibre version: 3.36.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\admin\\AppData\\Local\\Temp\\calibre_ihkrdm\\2bljyv.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001EC78577F98>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000001EC786F86D8>,
	 'page_breaks_before': u'/',
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\admin\\AppData\\Local\\Temp\\calibre_ihkrdm\\wkragh.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\admin\AppData\Local\Temp\calibre_ihkrdm\gh3uxh.kfx-zip
	Software versions: KFX Input 1.13.0, calibre 3.36 [64bit], Windows-10-10.0.17763-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\admin\AppData\Local\Temp\calibre_ihkrdm\gh3uxh.kfx-zip
	Processing container: B06VXKBLNG_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 98, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
	KFXDRMError: Book container B06VXKBLNG_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
