### ISSUE TITLE
Cannot DeDRM google play book

### ISSUE THREAD

**Issue by sasha-** [apprenticeharper/DeDRM_tools#772]
I purchased Google Play Book, not available in Kindle store  and I want to read it on Kindle Paperwhite.

Steps:
- Bought book on Googe books and dowloaded .acsm file
- Installed ADE on wine,  dropped on it .acsm file and it downloaded .epub file
- .epub is readable in ADE

- Installed Calibre on Ubuntu
- Installed DeDRM 
- Configured DeDRM (run .py script with python.exe  within wine to get key from ADE and added that key in DeDRM ADE configuration - it shows as adobekey_1)
- While trying to import .epub in Calibre, this is the output:
-------------------
DeDRM v6.6.1: Trying to decrypt Brdo.epub
DeDRM v6.6.1: Verifying zip archive integrity
DeDRM v6.6.1: “Brdo.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 171, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 632, in run
  File "calibre_plugins.dedrm.__init__", line 408, in ePubDecrypt
DeDRMError: DeDRM v6.6.1: Couldn't decrypt after 0.4 seconds. DRM free perhaps?
-------------------
- Clicking on the book in Calibre pops dialogue titled "This book has DRM".

- Inpecting .epub file showed that META-INF/rights.xml is missing
From there is was just a matter of recreating rights.xml following this:
https://github.com/apprenticeharper/DeDRM_tools/issues/342#issuecomment-329862920

rights.xml ended up looking like this: 

<?xml version="1.0"?>
<rights xmlns="http://ns.adobe.com/adept">
<licenseToken>
..... bunch of content here as copied from the Temp file 
 </licenseToken>    
  <licenseServiceInfo>
    <licenseURL>https://nasigningservice.adobe.com/licensesign</licenseURL>
    <certificate>base64-encoded-certificate</certificate>
  </licenseServiceInfo>
</rights>

The book is short 110 pages novel, so I guess this  was worth it. For anything shorter it would make more sense to just  write the book myself rather than wasting all this time.

**Comment by ElleKayEm** [comment]
Thanks for the info.  What version of ADE?

**Comment by sasha-** [comment]
It is ADE 1.2.7

I installed version 4.5 too, but it refused to run and I did bother too much trying to get it to work.

Btw, somewhat related,  while playing with this process and seeing Temp files ADE creates while obtaining a book, got me  thinking that, with a bit of  sniffing/stracing  I  could recreate entire process ADE goes through do download the book from Google and fetch rights.xml and stick it in there.  ADE install would still probably be initially required and the first book would still have to be downloaded via ADE, but future books could be fetched right from withing Calibre.  This is project for another day tough.

**Comment by ElleKayEm** [comment]
1.7.2?  Books I've gotten from Google using 2.0.1 don't have rights.xml missing.  But I don't know if you can get 2.0.1 running under Wine either.  Version 4.5 can handle a different type of Adobe DRM which cannot be removed (yet).  Although I haven't seen anyone report that Google is using that DRM -- better to stick with 2.0.1 which won't download a book with the newer DRM.

**Comment by ideologysec** [comment]
> It is ADE 1.2.7
> 
> I installed version 4.5 too, but it refused to run and I did bother too much trying to get it to work.
> 
> Btw, somewhat related, while playing with this process and seeing Temp files ADE creates while obtaining a book, got me thinking that, with a bit of sniffing/stracing I could recreate entire process ADE goes through do download the book from Google and fetch rights.xml and stick it in there. ADE install would still probably be initially required and the first book would still have to be downloaded via ADE, but future books could be fetched right from within Calibre. This is project for another day tough.

I'd be curious to know what you found; I've got some free time, some python experience, enough Wireshark know-how to get into trouble, and a love of non-DRM epubs.

Separately, have you tried with ADE 2.0.1 in wine? I'm working on building a winepak/flatpak for ADE which should make some of this easier, but in the meantime, does that newer version work ok? (I can send you the installer for Windows if you need a copy).

**Comment by LaHaine** [comment]
I have had the same error message from an EPUB decrypted using ADE 2.0.1 on WINE. It also didn't contain a rights.xml file. But then I have noticed I had the file twice, once under the Temp directory and one proper file under 'My Documents' that did have the rights.xml.
