### ISSUE TITLE
Another DRM removal problem Kindle Touch / win 10 Home 32 bit

### ISSUE THREAD

**Issue by EnkaraMandula** [apprenticeharper/DeDRM_tools#775]
Greetings, 

I have a Kindle Touch. I have purchased an e-book from Amazon, downloaded it to my computer (Asus T100TA netbook, 32 bit win10 home). I wanted to convert it to another format (first to mobi, then to rtf) via Calibre. I have installed the DRM removal plugin and followed the instructions, plugin customization included with my device's serial number, but despite my efforts the conversion has failed. I imported the book with drag and drop via Total Commander from my netbook. Here is the log from the troubleshooting (the rtf version), if you may take a look at it and advice me, what did I do wrong. Thank you in advance! :) <3

Mandula

calibre Debug log
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 150.853913043 x 150.055384615
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.36] db initialized
[0.36] Constructing main UI...
[3.77] main UI initialized...
[3.77] Hiding splash screen
[7.70] splash screen hidden
[7.70] Started up in 7.70 seconds with 2 books
DeDRM v6.6.1: Trying to decrypt B079MCLYG9_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings)
Found 2 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\Mandula\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings) to db in: 0.6
Added 1 books in 3.5 seconds
Worker Launch took: 0.529000043869
Job: 1 Convert book 1 of 1 (Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings)) finished
Convert book 1 of 1 (Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings))
	C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_rfauus\\t3qi4a.opf'
	  output_profile: 'kindle'
	  remove_paragraph_spacing: True
	  verbose: 2
	Resolved conversion options
	calibre version: 3.38.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04E37FF0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x022B3370>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Mandula\\AppData\\Local\\Temp\\calibre_rfauus\\t3qi4a.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': True,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Mandula\AppData\Local\Temp\calibre_rfauus\qlc7ke.azw
	Python function terminated unexpectedly
	  Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1106, in run
	  File "site-packages\calibre\customize\conversion.py", line 244, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 37, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 161, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Hungarian Proverbs... Vol.1: Everyday Hungarian sayings you might not understand. (Book of Essential Native Hungarian Traditional Culture Idioms / Proverbs / Sayings)

**Comment by ElleKayEm** [comment]
The key isn't working for that book.  Make sure you have the serial number entered correctly.  They can be really hard to read from the device itself.  Try copy and paste from the website, removing any spaces.

If you downloaded the book from the website, make sure you selected the correct device.  Or with a Kindle Touch, you could import the book directly from the device.

**Comment by j-howell** [comment]
> DeDRM v6.6.1: Trying to decrypt B079MCLYG9_EBOK.azw

That file did not come from an e-ink Kindle device.

**Comment by ElleKayEm** [comment]
Oh, good catch!

Kindle for PC needs to be on the same machine and user as calibre with DeDRM.  And it needs to be version 1.24 or earlier.

**Comment by EnkaraMandula** [comment]
I have double-checked the serial, removed and copy-pasted again from my Amazon account, without the spaces.
My Kindle for PC is version 1.25.1. :(
When I took a look at the list of my books on Amazon, selected this one to "deliver to default device", it said "You have selected content that is not compatible with your default device ". Also on my Kindle Touch when I have selected the book, it again said "Unavailable for download" and "This item is not compatible with your device". 
I have updated Calibre to version 3.39.1, it did not help.
Does this mean that I will not be able to convert this book in any way to make it compatible with my Kindle? Even if I find a way to replace Kindle for PC to that earlier version?

**Comment by ElleKayEm** [comment]
Sounds like this book is only available in the KFX format.  I believe you should be able to DeDRM and convert using version 1.24 of Kindle for PC and also adding the KFX Input plugin to calibre.  See Method 4 in this post at MobileRead:

https://www.mobileread.com/forums/showthread.php?t=283371

There's also a link for K4PC 1.24 there.
