### ISSUE TITLE
Cant remove DRM, eBooks from Dawsonera

### ISSUE THREAD

**Issue by infolib** [apprenticeharper/DeDRM_tools#778]
I have access to Dawsonera ebooks, and before this issue happen i was successfully remove DRM from ebooks  in PDF which downloaded using Adobe Digital Ed. But recently, i found that now using the latest apprentice tools (DeDRM for Mac) i cant remove ebooks DRM from dawsonera. My ADE version is 4.5.6 177148. Please help and share how to solve this problem. Thank you.
DeDRM.log

There is 1 ebook to be decrypted.
Processing file: deWits Fundamental Concepts and Skills for Nursing - E-Book.pdf
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/ineptpdf.py' '/Users/rudihadiarto/Library/Preferences/com.apprenticealf.dedrm/adobekey_1 3.der' '/Users/rudihadiarto/Documents/Digital Editions/deWits Fundamental Concepts and Skills for Nursing - E-Book.pdf' '/Users/rudihadiarto/Downloads/deWits Fundamental Concepts and Skills for Nursing - E-Book_nodrm.pdf' > '/Users/rudihadiarto/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2349, in <module>
    sys.exit(cli_main())
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2218, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2193, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1999, in __init__
    doc.initialize(userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1484, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1614, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 216, in decrypt
    raise ADEPTError('RSA decryption failed')
__main__.ADEPTError: RSA decryption failed
shellcommand: /usr/bin/python '/Applications/DeDRM.app/Contents/Resources/ineptpdf.py' '/Users/rudihadiarto/Library/Preferences/com.apprenticealf.dedrm/adobekey_1 4.der' '/Users/rudihadiarto/Documents/Digital Editions/deWits Fundamental Concepts and Skills for Nursing - E-Book.pdf' '/Users/rudihadiarto/Downloads/deWits Fundamental Concepts and Skills for Nursing - E-Book_nodrm.pdf' > '/Users/rudihadiarto/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult:  Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2349, in <module>
    sys.exit(cli_main())
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2218, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2193, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1999, in __init__
    doc.initialize(userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1484, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1614, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 216, in decrypt
    raise ADEPTError('RSA decryption failed')
__main__.ADEPTError: RSA decryption failed
There was an error with 1 ebook:
deWits Fundamental Concepts and Skills for Nursing - E-Book.pdf couldn't be decoded:
Traceback (most recent call last):
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2349, in <module>
    sys.exit(cli_main())
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2218, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 2193, in decryptBook
    serializer = PDFSerializer(inf, userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1999, in __init__
    doc.initialize(userkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1484, in initialize
    return self.initialize_ebx(password, docid, param)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 1614, in initialize_ebx
    bookkey = rsa.decrypt(bookkey)
  File "/Applications/DeDRM.app/Contents/Resources/ineptpdf.py", line 216, in decrypt
    raise ADEPTError('RSA decryption failed')
__main__.ADEPTError: RSA decryption failed

**Comment by ElleKayEm** [comment]
These tools are intended for books you own.

**Comment by infolib** [comment]
These books has been purchased by the library. before this problem arise, the deDRM tools for ebooks from Dawsonera works fine.

**Comment by eBJanith** [comment]
@infolib  were you able to remove deDRM from Dawsonera?

**Comment by Wannabe99** [comment]
> These tools are intended for books you own.

So not for books on loan?
