### ISSUE TITLE
Trying to import from Kindle for PC on Windows 10 Using Calibre-64

### ISSUE THREAD

**Issue by kfezer** [apprenticeharper/DeDRM_tools#780]
Logs:

`calibre Debug log
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0)
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0) && Set KFX metadata (from KFX Output) (1, 27, 0) && KFX Output (1, 27, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 123.385199241 x 123.567567568
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[2.06] main UI initialized...
[2.06] Hiding splash screen
[8.97] splash screen hidden
[8.97] Started up in 8.97 seconds with 4112 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x99\x0e(\x89|;\x89\xc4\xff\xcf<\xde\xa2\x04\x99\xd6t7\xd6\x86\x07\x0eAP\xc6\xc8\xea\t\x11\x19\xec\x07', 'C:\\Users\\Mazer\\Documents\\My Kindle Content\\B00IYUYF4A_EBOK\\B00IYUYF4A_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing C:\Users\Mazer\Documents\My Kindle Content\B00IYUYF4A_EBOK\B00IYUYF4A_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.1: Trying to decrypt B00IYUYF4A_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: What If?: Serious Scientific Answers to Absurd Hypothetical Questions
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Mazer\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added What If?: Serious Scientific Answers to Absurd Hypothetical Questions to db in: 2.1
Added 1 books in 3.9 seconds
Worker Launch took: 0.186000108719
Worker Launch took: 0.218999862671
`

It looks like it's looking for a key, but that shouldn't be necessary with Kindle for PC, right?

**Comment by ElleKayEm** [comment]
It should find the key automatically if Kindle for PC is on the same machine and user as calibre with DeDRM.  If it is, then you need to make sure you're using version 1.24 or earlier of Kindle for PC.
