### ISSUE TITLE
New DeDRM won't convert .azw 

### ISSUE THREAD

**Issue by sunspear571** [apprenticeharper/DeDRM_tools#786]
calibre Debug log
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
calibre 3.39.1  embedded-python: True is64bit: True
Darwin-18.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.2.0', 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 13, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 13, 0) && KFX metadata reader (from KFX Input) (1, 13, 0) && KFX Input (1, 13, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 111.000001667 x 110.000001652
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.47] main UI initialized...
[1.47] Hiding splash screen
[1.50] splash screen hidden
[1.50] Started up in 1.50 seconds with 1354 books
Gather KFX-ZIP (from KFX Input) 1.13.0: Importing /Users/josephsomerville/Documents/My Kindle Content/B07GJL19B4_EBOK/B07GJL19B4_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/7NqOGM.kfx-zip
DeDRM v6.6.2: Trying to decrypt 7NqOGM.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 7NqOGM
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.32828471-1f17-4a0d-bfc7-b6123e5c237e.voucher
DeDRM v6.6.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.2: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container B07GJL19B4_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.13.0: Packaging /var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/7NqOGM.kfx-zip
Processing container: B07GJL19B4_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/zuXdUx_add_books/0/B07GJL19B4_EBOK.kfx-zip
Added The Rescue (Ryan Decker Book 1) to db in: 0.2
Added 1 books in 1.1 seconds
2019-03-01 13:59:48.864 Calibre[3323:801273] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.153349876404
Job: 1 Convert book 1 of 1 (The Rescue (Ryan Decker Book 1)) finished
Convert book 1 of 1 (The Rescue (Ryan Decker Book 1))
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/Q2XnUs.opf'
	  verbose: 2
	  output_profile: 'ipad3'
	  cover: u'/var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/SqMZGl.jpeg'
	Resolved conversion options
	calibre version: 3.39.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/SqMZGl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x114839110>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x1148396d0>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/s7/pgqyjf355ln9yqxtcdcc35v00000gn/C/calibre_3.39.1_tmp_TiMHyK/Q2XnUs.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 98, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
	KFXDRMError: Book container B07GJL19B4_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly: This book has DRM!
	InputFormatPlugin: KFX In

**Comment by ElleKayEm** [comment]
You need to use Kindle for Mac 1.23 or earlier.

**Comment by ahanqin** [comment]
> You need to use Kindle for Mac 1.23 or earlier.

This operation no longer works.
I compared the azw files downloaded from the same book at different times. Even with the previous 1.21 version, the newly downloaded azw file looks smaller than before, and the plugin no longer works. After importing Calibre, the azw format is maintained instead of being Automatically converted to the mobi format.

**Comment by ElleKayEm** [comment]
Start a new issue and post a log.

**Comment by electricmessiah** [comment]
> > You need to use Kindle for Mac 1.23 or earlier.
> 
> This operation no longer works.
> I compared the azw files downloaded from the same book at different times. Even with the previous 1.21 version, the newly downloaded azw file looks smaller than before, and the plugin no longer works. After importing Calibre, the azw format is maintained instead of being Automatically converted to the mobi format.

Yeah, it's broken. Wait for a fix or use a different tool that's updated like I did.

**Comment by ElleKayEm** [comment]
Still working for me.
