### ISSUE TITLE
.azw file import into Calibre can't deal with DRM

### ISSUE THREAD

**Issue by Nagaraj-Pudukotai** [apprenticeharper/DeDRM_tools#788]
Here is the log from Calibre 3.40.1 after I restarted in debug mode. It is unable to read the Kindle book (.azw).  Any help to strip the DRM, in this case, will be highly appreciated.  

calibre Debug log
calibre 3.40.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
calibre 3.40.1 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[2.43] main UI initialized...
[2.43] Hiding splash screen
Failed to check for calibre update: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[28.21] splash screen hidden
[28.21] Started up in 28.21 seconds with 348 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x08:\x0e5,\xd7\x15XTr\xb0\xddq\xf6\xd4\xdcZ\xa0\xb7\xc3\xc3JGY$}\xd0a"\xd7\x98\x0e', 'C:\\Users\\A462707\\Documents\\My Kindle Content\\B076HT1JRZ_EBOK\\B076HT1JRZ_EBOK.azw']
DeDRM v6.6.2: Trying to decrypt B076HT1JRZ_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: CAMBRIDGE IGCSE PHYSICS: O LEVEL (Complete StudyBook and Revision Guide)
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\A462707\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added CAMBRIDGE IGCSE PHYSICS: O LEVEL (Complete StudyBook and Revision Guide) to db in: 0.4
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC 1.24 or earlier.  See this post for more info:

https://www.mobileread.com/forums/showthread.php?t=283371
