### ISSUE TITLE
Error That was a file that this script cannot process.

### ISSUE THREAD

**Issue by amrods** [apprenticeharper/DeDRM_tools#792]
I downloaded the Kindle for Mac version for which books can be decrypted, obtained the keys with the script provided and tried to decrypt a .azw file. A dialog box says "That was a file that this script cannot process." and the log file says
Error Message: Finder got an error: Can’t get document file "kindlekey1.k4i" of folder "TemporaryItems" of folder "T" of folder "mxsg7mlj3x170k8564gkqhv00000gn" of folder "28" of folder "folders" of folder "var" of item "private" of startup disk.
Error Number: -1728

When I go to configure Kindle for Mac in the DeDRM window I see that there is a file "kindlekey1 6.k4i", but it seems that DeDRM is looking for "kindlekey1.k4i".

How do I solve this problem?

**Comment by ElleKayEm** [comment]
Are you referring to the stand-alone Mac DeDRM app?  Are you using Kindle for Mac version 1.17?  Or do you have one of the later versions set not to download KFX files?

**Comment by amrods** [comment]
Yes, I'm using the stand-alone DeDRM app for mac. Kindle for Mac version 1.23.1, and I had already set not to download KFX. I basically followed method 2 of [this link](https://www.mobileread.com/forums/showthread.php?t=283371).

**Comment by ElleKayEm** [comment]
Ok, let's see the whole log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-macintosh-dedrm-application-and-now-i-need-to-post-a-log-how-do-i-do-that

Incidentally, someone has now figured out a way to use Kindle for Mac 1.25 as well:

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by amrods** [comment]
I am sorry. I got it working with the Calibre plug in. I then deleted the encrypted .azw file and the log of the failed attempts. I can't reproduce the error with the same book, but let me see what I can do now. It was a very short log. FWIW, I think the error arises because the stand alone app cannot find the kindle key.

**Comment by amrods** [comment]
This is the log with another book. But I think this is a different error.
```
There is 1 ebook to be decrypted.
Processing file: book_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/kindlekey1 7.k4i' -k '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/kindlekey1 8.k4i' '/Users/amrods/Desktop/book_EBOK.azw' '/Users/amrods/Desktop/' > '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.5
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/amrods/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'xxx' and UserName 'amrods'
Saved a key to /Users/amrods/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/KindleKey 9.der' '/Users/amrods/Desktop/book_EBOK.azw' '/Users/amrods/Desktop/' > '/Users/amrods/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 93, in <module>
    import kfxdedrm
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/28/mxsg7mlj3x170k8564gkqhv00000gn/T/AppTranslocation/46F43B40-AF06-421A-B7DA-6EE3E2CA5906/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
book_EBOK.azw couldn't be decrypted.
```

**Comment by ElleKayEm** [comment]
That error is mentioned in the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-application-opens-but-always-gives-an-error-in-the-log-importerror-no-module-named-cryptocipher

Also see issue #662.

**Comment by amrods** [comment]
Yeah, it's a different error.

**Comment by ElleKayEm** [comment]
I don't know why it couldn't find the key before, but that's not the problem any longer.

**Comment by pettitr** [comment]
The FAQ and fix about the "No module named Crypto.Cipher" doesn't work.
