### ISSUE TITLE
Mi Historia

### ISSUE THREAD

**Issue by Gabrieltambien** [apprenticeharper/DeDRM_tools#797]
Hello !!
My Laptop are a Samsung, I7 with 8 gb of memory.
Y buy de book in Amazon and download to my laptop and send by usb to my Kindle.

calibre Registro de depuración
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 11, 0) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
calibre 3.40.1  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 11, 0) && DeDRM (6, 6, 2) && Package KFX (from KFX Input) (1, 11, 0) && KFX metadata reader (from KFX Input) (1, 11, 0) && KFX Input (1, 11, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[3.06] db initialized
[3.06] Constructing main UI...
[8.53] main UI initialized...
[8.53] Hiding splash screen
[25.56] splash screen hidden
[25.56] Started up in 25.56 seconds with 55332 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x02\\\x99\x96\xd7\x92\xa9\xfc(\xccl\\#x\xb1\x7f\xd7:\xda\xf4OF\xad0\x1cX\xc9\x14Fa\xb3o', 'C:\\Users\\Gabriel Laptop\\Desktop\\Pepe Laptop\\Mi historia (Spanish Edition).azw3']
DeDRM v6.6.2: Trying to decrypt Mi historia (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mi historia (Spanish Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.2: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Gabriel Laptop\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 622, in run
  File "calibre_plugins.dedrm.__init__", line 572, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Mi historia (Spanish Edition) to db in: 0.2
Added 1 books in 1.1 seconds
Worker Launch took: 0.31200003624

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) for the device.  And you need to enter its serial number into the plugin customization.
