### ISSUE TITLE
Failed to import key from Kindle for PC 1.25.1 using DeDRM 6.6.3

### ISSUE THREAD

**Issue by j-howell** [apprenticeharper/DeDRM_tools#798]
I tried to import the key from a Kindle for PC 1.25.1 installation using the new plugin version 6.6.3. The process completed without producing an error, but when I looked at the .k4i file produced all of the values in it were "6661696c6564", which is the hex equivalent to the string "failed".

So it appears that the format of the .kinf2018 files is similar, but not identical to the old .kinf2011 files.

**Comment by timlt** [comment]
Same issue, exactly.

**Comment by ZolaLa9** [comment]
Key not importing from Kindle for Mac 1.25.2 either, but with the following error: "No k4Mac kindle-info/rainier/kinf2011 files have been found".

**Comment by ZolaLa9** [comment]
Key not importing from Kindle for Mac 1.25.2 either, but with the following error: 
"No k4Mac kindle-info/rainier/kinf2011 files have been found"

I added the filepath to kindlekey.py as follows: /Library/Application Support/Kindle/storage/.kinf2018

DeDRM 6.6.3 found kinf2018, but was not able to retrieve a key. No .k4i or .der file was produced.

The log reads:
Found k4Mac kinf2018 file: /Users/Zola/Library/Application Support/Kindle/storage/.kinf2018
Couldn't decrypt file.
Could not retrieve Kindle for Mac/PC key.

I have limited computer skills, but if there's anything anyone would like me to try on a Mac, please let me know. 

(If you think this is a sufficiently separate issue that I should delete this post and open a new issue specifically for K4Mac, let me know.)

**Comment by j-howell** [comment]
> If you think this is a sufficiently separate issue that I should delete this post and open a new issue specifically for K4Mac, let me know.

I think that the issue is basically the same. DeDRM cannot decrypt .kinf2018 files.

**Comment by stefano-sb** [comment]
Hi, same issue with Kindle for PC 1.25.1 and DeDRM 6.6.3! Do you know if there is a similar problem importing KFX/AZW3 ebook from Kindle PW3 with firmware version 5.10.2 or later? Now I have a Kindle with fw 5.10.1.1. Thanks

**Comment by j-howell** [comment]
> Do you know if there is a similar problem importing KFX/AZW3 ebook from Kindle PW3 with firmware version 5.10.2 or later?

This particular issue with obtaining the decryption key only affects Kindle for PC and Kindle for Mac version 1.25 or later.

There was also a recent change to the DRM used for books in KFX format. That is a separate issue that affects Kindle firmware 5.10.2 and later as well as the PC and Mac apps.

**Comment by stefano-sb** [comment]
Thanks. So DeDRM 6.6.3 doesn’t work jet with KFX from a Kindle device (eg PW3) with firmware version 5.10.2 and later. Is it correct?

**Comment by j-howell** [comment]
> Thanks. So DeDRM 6.6.3 doesn’t work jet with KFX from a Kindle device (eg PW3) with firmware version 5.10.2 and later. Is it correct?

That is correct.

**Comment by PhilipPeake** [comment]
If this helps - debug from attempting to convert a book from the (Mac) Kindle app.

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.5.0', 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 14, 0) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
calibre 3.40.1  embedded-python: True is64bit: True
Darwin-18.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.5.0', 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 14, 0) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.000001937 x 129.000001937
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.86] main UI initialized...
[0.86] Hiding splash screen
[0.91] splash screen hidden
[0.93] Started up in 0.93 seconds with 29 books
2019-04-02 13:19:32.412 Calibre[6109:363167] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.111970186234
Job: 1 Convert book 1 of 1 (The Grand Alliance (Blood on the Stars Book 11)) finished
Convert book 1 of 1 (The Grand Alliance (Blood on the Stars Book 11))
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/wg/c2yd0wlx279426h0bbnq58840000gn/C/calibre_3.40.1_tmp_ow0kaw/lg8kAh.opf'
	  cover: u'/var/folders/wg/c2yd0wlx279426h0bbnq58840000gn/C/calibre_3.40.1_tmp_ow0kaw/zMProC.jpeg'
	Resolved conversion options
	calibre version: 3.40.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/wg/c2yd0wlx279426h0bbnq58840000gn/C/calibre_3.40.1_tmp_ow0kaw/zMProC.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10eee82d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x10eee8a90>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/wg/c2yd0wlx279426h0bbnq58840000gn/C/calibre_3.40.1_tmp_ow0kaw/lg8kAh.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.__init__", line 204, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 98, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
	KFXDRMError: Book container B07N2PCCB7_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpec

**Comment by ElleKayEm** [comment]
DRM removal happens on import, not conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by j-howell** [comment]
kinf2018, used by the latest Kindle for PC and Mac, cannot be decoded properly by this software. A conversion log isn’t going to be of any use in fixing this.

**Comment by apprenticeharper** [comment]
The key file values are now encrypted with a new value. Some reverse engineering is needed on Mac and PC.

**Comment by ZolaLa9** [comment]
I don't know enough about encryption to know if this will help with the reverse engineering, but fwiw, when using this [Mac workaround for getting KF8/azw3 from Kindle for Mac 1.25.2](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508), the old kinf2011 key still works.

**Comment by MartijnBerlage** [comment]
> I don't know enough about encryption to know if this is helpful for the reverse engineering, but the old kinf2011 works on KF8 downloaded from Kindle for Mac 1.25.2 when using [this workaround](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508).

Thanks for the pointer. That workaround did the trick for me.
