### ISSUE TITLE
plugin not working/suggestion for documentation

### ISSUE THREAD

**Issue by NoraCarrington** [apprenticeharper/DeDRM_tools#802]
I've attached my log and I know why it's not working; I obtained the files I wanted to import into Calibre by plugging my kindle paperwhite into the computer with a USB cable and simply copying the "documents" folder. I didn't preserve the file structure, etc. Just a general word up top in some of your documentation/instructions that this method *WILL NOT* work would be helpful, as it's so self-evidently the fastest and easiest way to move material purchased and sent to the kindle onto another machine. 

log:

calibre Debug log
calibre 3.40.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 14, 0) && Find Duplicates (1, 6, 3) && FanFicFare (3, 4, 0) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
calibre 3.40.1  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 14, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 14, 0) && Find Duplicates (1, 6, 3) && FanFicFare (3, 4, 0) && KFX metadata reader (from KFX Input) (1, 14, 0) && KFX Input (1, 14, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.0567375887 x 71.8867924528
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[3.51] db initialized
[3.51] Constructing main UI...
FFF: INFO: 2019-04-08 13:42:30,177: calibre_plugins.fanficfare_plugin.prefs(206): Attempting to read settings from predecessor--FFDL
FFF: DEBUG: 2019-04-08 13:42:30,184: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Susan Bernick\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[11.34] main UI initialized...
[11.34] Hiding splash screen
[16.33] splash screen hidden
[16.33] Started up in 16.33 seconds with 20660 books
Gather KFX-ZIP (from KFX Input) 1.14.0: Importing C:/Users/Susan Bernick/Downloads/Torrents/KFX Files/Poisonfeather - Matthew Fitzsimmons.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\SUSANB~1\AppData\Local\Temp\calibre_lkgm7b\amegvc.kfx-zip
DeDRM v6.6.1: Trying to decrypt amegvc.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: amegvc
Found 1 keys to try after 0.1 seconds
DeDRM v6.6.1: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.1: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Susan Bernick\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Susan Bernick\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '249491795' and UserName '537573616e204265726e69636b'
DeDRM v6.6.1: Found 1 new key
Decrypting KFX-ZIP ebook: amegvc
Got DSN key from database default_key_1
Found 1 keys to try after 0.3 seconds
DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.14.0: Packaging C:\Users\SUSANB~1\AppData\Local\Temp\calibre_lkgm7b\amegvc.kfx-zip
Processing container: Poisonfeather - Matthew Fitzsimmons.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container Poisonfeather - Matthew Fitzsimmons.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\SUSANB~1\AppData\Local\Temp\calibre_lkgm7b\ni5axk_add_books\0\Poisonfeather - Matthew Fitzsimmons.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 124, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Poisonfeather to db in: 0.3
Added 1 books in 2.6 seconds

**Comment by ElleKayEm** [comment]
If your Paperwhite is running firmware 5.10.2 or newer, you will not be able to DeDRM the KFX format books downloaded to it.

For info on obtaining Kindle files that can be DeDRMed, see this thread:

https://www.mobileread.com/forums/showthread.php?t=283371

To make a suggestion about the KFX Input plugin's documentation, try here:

https://www.mobileread.com/forums/showthread.php?t=291290
