### ISSUE TITLE
DeDRM plugin for calibre not working on Windows

### ISSUE THREAD

**Issue by hjings** [apprenticeharper/DeDRM_tools#804]
I use DeDRM plugin for calibre to decrypt ebooks that I downloaded from Kindle for PC v1.25.1 (52068). The DeDRM is v6.6.3 and calibre is v3.39.1. After adding the plugin to calibre and restarting calibre, I dragged three books to the calibre library, but DeDRM didn't work and DRM wasn't removed. The logs are shown below:

```
calibre 调试日志
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.39.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 80.078817734 x 78.6017191977
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
Loaded cached store plugin for: Amazon Kindle at version: 16
[1.23] main UI initialized...
[1.23] Hiding splash screen
[7.28] splash screen hidden
[7.28] Started up in 7.28 seconds with 6 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 384 '\x01\x00\x00\x00\x0c\x00\x00\x00\n\x01\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d\x14\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xafl\x001\x00\x00\x00\x00\x00\x8aN\xe8[\x10\x00MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xbeeN\x18`\x8aN\xe8[.\x00\x00\x00\x17\xd6\x01\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcfi\xbd\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\x00\x00\x18\x00h\x001\x00\x00\x00\x00\x00\x8aN\xe9[\x10\x00B007K5~1\x00\x00P\x00\t\x00\x04\x00\xef\xbe\x89N\x9ax\x8aN\xe9[.\x00\x00\x00\xad\xed\x08\x00\x00\x00#\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00(\xa4\xa0\x00B\x000\x000\x007\x00K\x005\x00I\x000\x005\x000\x00_\x00E\x00B\x00O\x00K\x00\x00\x00\x18\x00\x00\x00t\x002\x00\x7f\xb6"\x00\x89N\x9cx \x00B007K5~1.AZW\x00\x00X\x00\t\x00\x04\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 82968 '\x90\x00\x00\x00\x90\x00\x00\x00H\x00\x00\x00\x85\x00\x00\x00\xeb\x16\x05 \xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 92 'file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B007K5I050_EBOK/B007K5I050_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 55 'C:\\Users\\hjing\\DOCUME~1\\MYKIND~1\\B007K5~1\\B007K5~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 158 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00h\x00j\x00i\x00n\x00g\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x000\x007\x00K\x005\x00I\x000\x005\x000\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x000\x007\x00K\x005\x00I\x000\x005\x000\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x82G\x95\xe5\xee\xd4\x01\x00\x00\x00\x00\x00\x00\x00\x00bv\x8a\x97\xe5\xee\xd4\x01\x00\x00\x00\x00\x7f\xb6"\x00B\x000\x000\x007\x00K\x005\x00I\x000\x005\x000\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 


Firefox rurl: None None
URLS: ['file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B007K5I050_EBOK/B007K5I050_EBOK.azw']
Paths: [u'C:/Users/hjing/Documents/My Kindle Content/B007K5I050_EBOK/B007K5I050_EBOK.azw']
Extensions: frozenset([u'azw'])
DeDRM v6.6.3: Trying to decrypt B007K5I050_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 楂樺矝鏄撴柇:鍗犳柇鐮磋В
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\hjing\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\hjing\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '994142' and UserName '686a696e67'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 楂樺矝鏄撴柇:鍗犳柇鐮磋В
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added book1 to db in: 0.1
Added 1 books in 0.7 seconds

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 384 '\x01\x00\x00\x00\x0c\x00\x00\x00\n\x01\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d\x14\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xafl\x001\x00\x00\x00\x00\x00\x8aN\xe8[\x10\x00MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xbeeN\x18`\x8aN\xe8[.\x00\x00\x00\x17\xd6\x01\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcfi\xbd\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\x00\x00\x18\x00h\x001\x00\x00\x00\x00\x00\x8aN\xe9[\x10\x00B012ZC~1\x00\x00P\x00\t\x00\x04\x00\xef\xbe\x89N\xa4x\x8aN\xe9[.\x00\x00\x00\x0e\xef\x08\x00\x00\x00!\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00q\xab*\x00B\x000\x001\x002\x00Z\x00C\x00H\x00U\x007\x006\x00_\x00E\x00B\x00O\x00K\x00\x00\x00\x18\x00\x00\x00t\x002\x00\xbcDN\x00\x89N\xa7x \x00B012ZC~1.AZW\x00\x00X\x00\t\x00\x04\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 82968 '\x90\x00\x00\x00\x90\x00\x00\x00H\x00\x00\x00\x85\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 92 'file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B012ZCHU76_EBOK/B012ZCHU76_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 55 'C:\\Users\\hjing\\DOCUME~1\\MYKIND~1\\B012ZC~1\\B012ZC~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 158 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00h\x00j\x00i\x00n\x00g\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x001\x002\x00Z\x00C\x00H\x00U\x007\x006\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x001\x002\x00Z\x00C\x00H\x00U\x007\x006\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xea\xd0\x9e\xe5\xee\xd4\x01\x00\x00\x00\x00\x00\x00\x00\x00\xa8\xfb\x03\xa2\xe5\xee\xd4\x01\x00\x00\x00\x00\xbcDN\x00B\x000\x001\x002\x00Z\x00C\x00H\x00U\x007\x006\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 


Firefox rurl: None None
URLS: ['file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B012ZCHU76_EBOK/B012ZCHU76_EBOK.azw']
Paths: [u'C:/Users/hjing/Documents/My Kindle Content/B012ZCHU76_EBOK/B012ZCHU76_EBOK.azw']
Extensions: frozenset([u'azw'])
DeDRM v6.6.3: Trying to decrypt B012ZCHU76_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐧借瘽楂樺矝鏄撴柇锛堜笂锛?
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\hjing\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\hjing\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '994142' and UserName '686a696e67'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐧借瘽楂樺矝鏄撴柇锛堜笂锛?
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added book2 to db in: 0.1
Added 1 books in 0.7 seconds

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 384 '\x01\x00\x00\x00\x0c\x00\x00\x00\n\x01\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d\x14\x00.\x80\x92+\x16\xd3e\x93zF\x95k\x92p:\xca\x08\xafl\x001\x00\x00\x00\x00\x00\x8aN\xe8[\x10\x00MYKIND~1\x00\x00T\x00\t\x00\x04\x00\xef\xbeeN\x18`\x8aN\xe8[.\x00\x00\x00\x17\xd6\x01\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcfi\xbd\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\x00\x00\x18\x00h\x001\x00\x00\x00\x00\x00\x8aN\xe9[\x10\x00B016HW~1\x00\x00P\x00\t\x00\x04\x00\xef\xbe\x89N\x9dx\x8aN\xe9[.\x00\x00\x00\xa0\xed\x08\x00\x00\x00"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\x08e\x00B\x000\x001\x006\x00H\x00W\x00C\x006\x000\x00G\x00_\x00E\x00B\x00O\x00K\x00\x00\x00\x18\x00\x00\x00t\x002\x00\xb3^8\x00\x89N\xa2x \x00B016HW~1.AZW\x00\x00X\x00\t\x00\x04\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 82968 '\x90\x00\x00\x00\x90\x00\x00\x00H\x00\x00\x00\x85\x00\x00\x00\x0c\x12\x05\xcc\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 92 'file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B016HWC60G_EBOK/B016HWC60G_EBOK.azw\r\n' 

application/x-qt-windows-mime;value="FileName" 55 'C:\\Users\\hjing\\DOCUME~1\\MYKIND~1\\B016HW~1\\B016HW~1.AZW\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 158 'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00h\x00j\x00i\x00n\x00g\x00\\\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00s\x00\\\x00M\x00y\x00 \x00K\x00i\x00n\x00d\x00l\x00e\x00 \x00C\x00o\x00n\x00t\x00e\x00n\x00t\x00\\\x00B\x000\x001\x006\x00H\x00W\x00C\x006\x000\x00G\x00_\x00E\x00B\x00O\x00K\x00\\\x00B\x000\x001\x006\x00H\x00W\x00C\x006\x000\x00G\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\t\xdb\x98\xe5\xee\xd4\x01\x00\x00\x00\x00\x00\x00\x00\x00k<^\x9b\xe5\xee\xd4\x01\x00\x00\x00\x00\xb3^8\x00B\x000\x001\x006\x00H\x00W\x00C\x006\x000\x00G\x00_\x00E\x00B\x00O\x00K\x00.\x00a\x00z\x00w\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 


Firefox rurl: None None
URLS: ['file:///C:/Users/hjing/Documents/My%20Kindle%20Content/B016HWC60G_EBOK/B016HWC60G_EBOK.azw']
Paths: [u'C:/Users/hjing/Documents/My Kindle Content/B016HWC60G_EBOK/B016HWC60G_EBOK.azw']
Extensions: frozenset([u'azw'])
DeDRM v6.6.3: Trying to decrypt B016HWC60G_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐧借瘽楂樺矝鏄撴柇锛堜笅锛?
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\hjing\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\hjing\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '994142' and UserName '686a696e67'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐧借瘽楂樺矝鏄撴柇锛堜笅锛?
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added book3 to db in: 0.1
Added 1 books in 0.7 seconds
```

**Comment by ElleKayEm** [comment]
Unfortunately the tools are still not working with Kindle for PC 1.25.  You will need to go back to version 1.24 or earlier.  See this post for more info:

https://www.mobileread.com/forums/showthread.php?t=283371
