### ISSUE TITLE
Metadata error when saving an imported DRM ADE PDF ebook

### ISSUE THREAD

**Issue by wulle77** [apprenticeharper/DeDRM_tools#811]
Hi there, I have the following error when saving an imported DRM pdf (ADE type). Can somebody help me to understand what the problem is. Thank you!

calibre, version 3.41.3
WARNING: Error while saving: Failed to update metadata in some books, click "Show details" for more information

Failed to update the metadata in the PDF format of: 'bookname' by Unknown, with error:
    Traceback (most recent call last):
      File "site-packages\calibre\customize\ui.py", line 448, in set_file_type_metadata
      File "site-packages\calibre\customize\builtins.py", line 544, in set_metadata
      File "site-packages\calibre\ebooks\metadata\pdf.py", line 177, in set_metadata
      File "site-packages\calibre\utils\podofo\__init__.py", line 45, in set_metadata
    Exception: Failed to set PDF metadata in ('bookname'): Traceback (most recent call last):
      File "site-packages\calibre\utils\ipc\simple_worker.py", line 291, in main
      File "site-packages\calibre\utils\podofo\__init__.py", line 62, in set_metadata_
    Error: ePdfError_UnsupportedFilter

**Comment by ElleKayEm** [comment]
Is the DRM removed?
