### ISSUE TITLE
Unable to Remove DRM from a Kindle book downloaded for windows 10

### ISSUE THREAD

**Issue by hyrule13** [apprenticeharper/DeDRM_tools#812]
calibre Debug log
calibre 3.41.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.41.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.917922948 x 108.857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
[8.89] splash screen hidden
[8.89] Started up in 8.89 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt B07NPR265B_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: NEKOPARA - Chapter 03: We know what we want
Got DSN key from database default_key
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Hyrule13\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Hyrule13\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2692839820' and UserName '487972756c653133'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added NEKOPARA - Chapter 03: We know what we want to db in: 1.7
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
Go back to Kindle for PC version 1.24 or earlier.  See this post for more details:

https://www.mobileread.com/forums/showthread.php?t=283371
