### ISSUE TITLE
Unable to remove DRM from PDF (obtained through Adobe Digital Editions 4.5)

### ISSUE THREAD

**Issue by Kaine90** [apprenticeharper/DeDRM_tools#815]
**I'm able to remove DRM from most books using this method, but now and then it can't. What seems to be the problem in this case?**

calibre Debug log
calibre 3.41.3  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.41.3  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 58.7920433996 x 58.8038585209
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[0.91] main UI initialized...
[0.92] Hiding splash screen
[5.89] splash screen hidden
[5.89] Started up in 5.89 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt [9781400845538] Democratic Reas - Unknown.pdf
DeDRM v6.6.3: [9781400845538] Democratic Reas - Unknown.pdf is a PDF ebook
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 452, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 506, in PDFDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 429, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 116, in get_metadata
ValueError: Could not read info dict from PDF
Added [9781400845538] Democratic Reas to db in: 0.1
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
Well, it says it can't decrypt the user key.  Have you been able to remove Adobe DRM from other books from the same ebookstore?

First thing I'd suggest is trying again with 64-bit calibre.

**Comment by Kaine90** [comment]
Thanks for the quickly reply. I hadn't even noticed that I wasn't running 64-bit. So I uninstalled Calibre, and installed the latest 64-bit version, and added the plugin. Still same result. 

I mainly use it for books I download from databases through my university access. I think it's the first time I've downloaded a book from that specific site, although I've had the same problem happen before.

**Comment by ElleKayEm** [comment]
ADE is on the same machine and user as calibre with DRM and authorized with your Adobe ID?

Also, see if you can open your book with ADE 2.0.1 authorized with the same Adobe ID.

**Comment by Kaine90** [comment]
No problem opening it in ADE 4.5. With ADE 2.0.1 I at first got an error saying "Error! Check Activation." when dragging the .acsm file into the program. But after opening the file with ADE 4.5 first, it shows up in ADE 2.0.1 as well. However, when then trying to open it there, it says that it needs to be authorized with vendor ID. I guess that's because it's downloaded through university access? So I would assume it's not possible to get it opened through ADE 2.0.1?

**Comment by Kaine90** [comment]
And yes, all on the same machine.

**Comment by ElleKayEm** [comment]
Hmm, do you have ADE 2.0.1 authorized with your Adobe ID?  Not a good sign if you can't open it with 2.0.1.  You may have DRM that can't be removed.
