### ISSUE TITLE
DeDRM_tools_6.6.3 not work on windows

### ISSUE THREAD

**Issue by fangj** [apprenticeharper/DeDRM_tools#816]
DeDRM_tools_6.6.3
calibre 1.24.0
windows 10
kindle for pc 1.25.1

log:

calibre Debug log
calibre 1.24 [64bit]  isfrozen: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.5
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Starting up...
Started up in 11.89 seconds with 63 books
Worker Launch took: 0.243999958038
Job: 1 Read metadata (0 of 1) finished
Read metadata (0 of 1)
	DeDRM v6.6.3: Trying to decrypt B078JCN1SQ_EBOK.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v0.42.
	Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: 鑲℃寚鏈熻揣鎶曡祫鍏ラ棬
	Found 2 keys to try after 0.2 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
	DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
	searching for kinfoFiles in C:\Users\qffj\AppData\Local
	Found K4PC 2.25+ kinf2018 file: C:\Users\qffj\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3270353568' and UserName '7166666a'
	DeDRM v6.6.3: Found 1 new key
	MobiDeDrm v0.42.
	Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: 鑲℃寚鏈熻揣鎶曡祫鍏ラ棬
	Got DSN key from database default_key_1
	Found 3 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 154, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 624, in run
	  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
	DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md

C:\Program Files\Calibre2\pylib.zip\dateutil\parser.py:336: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 股指期货投资入门 to db in: 1.35899996758 seconds

**Comment by ElleKayEm** [comment]
DeDRM is not working with books from Kindle for PC version 1.25 yet.  So go back to 1.24 or earlier.  You should probably update calibre though -- it's currently on version 3.42!
