### ISSUE TITLE
6.4.0 Calibra/DeDR_tools_6.4.0 zip is invalid?

### ISSUE THREAD

**Issue by vherring** [apprenticeharper/DeDRM_tools#82]
calibre, version 2.53.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'D:/Downloads/Calibra/DeDRM_tools_6.4.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.53 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: Extract ISBN && Author Book Count && Save To Format && User Category && View Manager && Goodreads && EpubMerge && Count Pages
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 316, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 397, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 54, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 188, in load
  File "site-packages\calibre\customize\zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'D:/Downloads/Calibra/DeDRM_tools_6.4.0.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip the main file.  Look inside the DeDRM calibre plugin for the zip to load into calibre.
