### ISSUE TITLE
Cannot remove DRM

### ISSUE THREAD

**Issue by ranesykes** [apprenticeharper/DeDRM_tools#820]
Used the DeDRM Plugin and KFX Input Plugin in Calibre, won't allow me to convert books purchased from Amazon. Trying to import books from Kindle for Windows 1.26.0. Using PC on Windows 10 Pro. Log below:

calibre Debug log
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0)
calibre 3.42  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 125.257761733 x 125.046153846
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.28] main UI initialized...
[1.28] Hiding splash screen
[12.52] splash screen hidden
[12.52] Started up in 12.52 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8e\xa7\xfc\x03C\xe5\xc4\x82\xdf\xea\xbd\xc3#\xc4 \xda\x9ei\xaf\xdeH\xa4\x8c]\x0b\\\x04r\x8c\x8e\x17z', 'C:\\Users\\MSI\\Documents\\My Kindle Content\\B00ECY6BSA_EBOK\\B00ECY6BSA_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.16.0: Importing C:\Users\MSI\Documents\My Kindle Content\B00ECY6BSA_EBOK\B00ECY6BSA_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B00ECY6BSA_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\MSI\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\MSI\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1889774984' and UserName '4d5349'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3
Got DSN key from database default_key_1
Found 3 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3 to db in: 0.4
Added 1 books in 1.9 seconds
Worker Launch took: 0.129999876022
Job: 0 Convert book 1 of 1 (Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3) finished
Convert book 1 of 1 (Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3)
	Conversion options changed from defaults:
	  output_profile: 'generic_eink'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\MSI\\AppData\\Local\\Temp\\calibre_vgw84s\\5yc49y.opf'
	  cover: u'C:\\Users\\MSI\\AppData\\Local\\Temp\\calibre_vgw84s\\tykc37.jpeg'
	Resolved conversion options
	calibre version: 3.42.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\MSI\\AppData\\Local\\Temp\\calibre_vgw84s\\tykc37.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x064F8870>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x064F8A70>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\MSI\\AppData\\Local\\Temp\\calibre_vgw84s\\5yc49y.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\MSI\AppData\Local\Temp\calibre_vgw84s\qphsnn.azw
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3 (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 200, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1107, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 46, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Little Red Riding Hood: Caperucita Roja - Bilingual English and Spanish Children's Fairy Tale Keepsake Stories, Pre K - 3

**Comment by ElleKayEm** [comment]
DeDRM isn't working with Kindle for PC 1.25 and later yet.  Go back to 1.24 or earlier.

**Comment by ayyatusabe** [comment]
I am having the same issue... the book i'm trying to use requires me to use 1.26  it will not allow me to use anything earlier through kindle

**Comment by ElleKayEm** [comment]
@ayyatusabe 
Then you will not be able to remove the DRM at this time.
