### ISSUE TITLE
Unable to covert amazon book

### ISSUE THREAD

**Issue by ohoka** [apprenticeharper/DeDRM_tools#823]

**Comment by ohoka** [comment]
calibre Debug log
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.37 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.12+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 78.9126213592 x 79.2832369942
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[1.44] main UI initialized...
[1.44] Hiding splash screen
[67.95] splash screen hidden
[67.95] Started up in 67.95 seconds with 43 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['E\xadW\xd4l\x83m\xe5\xb6\xbf\x89-\xf5\xc6\xe8\x9b\xc3\xf3]\xb8\xcd\x1f\xee\xfd\x0cI\x87\xe3z\xb3\xe7d', 'C:\\Users\\tommo\\Desktop\\The Work Cure.azw3']
DeDRM v6.6.3: Trying to decrypt The Work Cure.azw3
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Work Cure
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\tommo\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\tommo\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3158721018' and UserName '746f6d6d6f'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Work Cure
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Work Cure to db in: 0.2
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.
