### ISSUE TITLE
DeDRM does not work on AZW3 file using Calibre on Windows 10

### ISSUE THREAD

**Issue by FelianDamakos** [apprenticeharper/DeDRM_tools#824]
I followed all the steps, installed the most recent version of the plug in on Calibre and added my Amazon Fire serial number to it.
It still does not work and get this in the debug. Thanks for supporting:

calibre Debug log
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Kindle and Mobipocket DeDRM (0, 4, 13)
calibre 3.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Kindle and Mobipocket DeDRM (0, 4, 13)
Turning on automatic hidpi scaling
devicePixelRatio: 3.0
logicalDpi: 80.0 x 80.0
physicalDpi: 94.511627907 x 94.2680412371
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
[4.03] splash screen hidden
[4.05] Started up in 4.05 seconds with 1 books
DeDRM v6.6.3: Trying to decrypt Return to Ravnica.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Return to Ravnica
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Flavio\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Kindle and Mobipocket DeDRM v0.4.13: Trying to decrypt Return to Ravnica.azw3.
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin Kindle and Mobipocket DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 116, in run
  File "calibre_plugins.k4mobidedrm.__init__", line 249, in config
  File "site-packages\calibre\customize\zipplugin.py", line 186, in load_module
  File "calibre_plugins.k4mobidedrm.config", line 4, in <module>
ImportError: No module named PyQt4.Qt
Added Return to Ravnica to db in: 1.5
Added 1 books in 3.8 seconds

**Comment by ElleKayEm** [comment]
DeDRM doesn't work with files from/for Kindle Fires.  Only the E-ink Kindles.  If you don't have an E-ink Kindle, you'll need to download it with Kindle for PC version 1.24 or earlier.  See this post for info about dealing with or avoiding the KFX format:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by royluo1984** [comment]
> DeDRM doesn't work with files from/for Kindle Fires. Only the E-ink Kindles. If you don't have an E-ink Kindle, you'll need to download it with Kindle for PC version 1.24 or earlier. See this post for info about dealing with or avoiding the KFX format:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371

Hi ElleKayEm,
I tried, but it seems amazon doesn't allow me to download kindle ebook file if I am not using kindle 1.26 or above

I thought there were some saved setting to prevent me to do that so I uninstalled kindle manually but still

**Comment by ElleKayEm** [comment]
That's weird.  I'm still using K4PC version 1.17.  Did you see the info at the link I gave about preventing unwanted updates?
