### ISSUE TITLE
doesnt' work with Calibre 3.42.0 

### ISSUE THREAD

**Issue by liseuse78** [apprenticeharper/DeDRM_tools#825]
Hello
I update Calibre on 3.42.0 version but it doesn't work... I have this message 👍 

calibre, version 3.42.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:The plugin in u'/Users/dianedc/Downloads/DeDRM_tools_6.6.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.42  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: fr
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 318, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 473, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 62, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 195, in load
  File "site-packages/calibre/customize/zipplugin.py", line 293, in _locate_code
InvalidPlugin: The plugin in u'/Users/dianedc/Downloads/DeDRM_tools_6.6.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the wrong file.  Unzip DeDRM_tools_6.6.3.zip and look in the DeDRM_calibre_plugin folder for DeDRM_plugin.zip.

**Comment by liseuse78** [comment]
> You're trying to load the wrong file. Unzip DeDRM_tools_6.6.3.zip and look in the DeDRM_calibre_plugin folder for DeDRM_plugin.zip.

oh thanks you ! it's good now !

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
