### ISSUE TITLE
DDRM caliber plugin 6.6.3 not importing azw 

### ISSUE THREAD

**Issue by grillod** [apprenticeharper/DeDRM_tools#834]
I have verision 1.24.3 of the kindle pc app and I'm trying to import an azw with the caliber plugin.

It imports but is not decrypted.

calibre Debug log
calibre 3.42  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
calibre 3.42  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9292035398 x 72.0487534626
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.08] db initialized
[0.08] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.76] main UI initialized...
[1.76] Hiding splash screen
[12.17] splash screen hidden
[12.17] Started up in 12.17 seconds with 444 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x9eL\xd3\x14\xdb\xc5!\xd8G\xc2\x87\xd0\x06$\xb5\xa9\xd3\xb2\x85%Q\n\x88\xe7\xdcU\x19\xf9\x01J\xac\x9a', 'C:\\Users\\Dan\\Documents\\My Kindle Content\\B07MNJX8B5_EBOK\\B07MNJX8B5_EBOK.azw']
DeDRM v6.6.3: Trying to decrypt B07MNJX8B5_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.3: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Dan\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Dan\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\Dan\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1348014362' and UserName '44616e'
Decrypted key file using IDString '1348014362' and UserName '44616e'
DeDRM v6.6.3: Found 2 new keys
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 429, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 285, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 495, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 285, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 313, in identity
MobiError: Unknown book type: ¢ÄÞŒ
Added B07MNJX8B5 EBOK to db in: 1.1
Added 1 books in 1.8 seconds

**Comment by grillod** [comment]
Disregard. I had to install the kfx input plugin as well. It's working for me now. 

https://www.mobileread.com/forums/showthread.php?t=291290
