### ISSUE TITLE
Unable to decrypt recently purchased kindle books

### ISSUE THREAD

**Issue by davidkels** [apprenticeharper/DeDRM_tools#838]
Using Calibre with the latest kfx plugin I was able to decrypt most but not all of my kindle books copied from my e-ink kindle device. The newest books (about 4) failed to decrypt. The final input is stored as a kfx-zip file which I gather means the DRM removal failed. The log output is as follows
```
calibre Debug log
calibre 3.41.3 Portable embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0)
calibre 3.41.3 Portable embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 16, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 16, 0) && KFX metadata reader (from KFX Input) (1, 16, 0) && KFX Input (1, 16, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.643076923 x 133.900578035
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.56] main UI initialized...
[1.56] Hiding splash screen
[15.47] splash screen hidden
[15.47] Started up in 15.47 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xba\xc00\x14\x9c\xaa\xad\xda\xcbJ\x02Y\xebBf\xe1\x806 \xc2|\xf3\x8a\xafz\xc6\xd8\x9c\x82\xf3\x80\xbd', 'U:\\udataKindle\\Effective C++ Digital Collection_ 140 Ways to Improve Your Programming_B008E30L9A.kfx']
Gather KFX-ZIP (from KFX Input) 1.16.0: Importing U:\udataKindle\Effective C++ Digital Collection_ 140 Ways to Improve Your Programming_B008E30L9A.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\dave\AppData\Local\Temp\calibre_xuhlwr\dpoqk3.kfx-zip
DeDRM v6.6.3: Trying to decrypt dpoqk3.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: dpoqk3
Found 1 keys to try after 0.1 seconds
DeDRM v6.6.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\dave\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.16.0: Packaging C:\Users\dave\AppData\Local\Temp\calibre_xuhlwr\dpoqk3.kfx-zip
Processing container: Effective C++ Digital Collection_ 140 Ways to Improve Your Programming_B008E30L9A.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 173, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 22, in run
  File "calibre_plugins.kfx_input.package_filetype", line 35, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 152, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 263, in get_container
KFXDRMError: Book container Effective C++ Digital Collection_ 140 Ways to Improve Your Programming_B008E30L9A.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\dave\AppData\Local\Temp\calibre_xuhlwr\to1lqs_add_books\0\Effective C++ Digital Collection_ 140 Ways to Improve Your Programming_B008E30L9A.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 429, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 124, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added Effective C++ Digital Collection 140 Ways to Improve Your Programming B008E30L9A to db in: 0.2
Added 1 books in 2.6 seconds
```
I'm guessing I might have more success perhaps using kindle for PC but don't know where to locate an appropriate older version.

**Comment by ElleKayEm** [comment]
If your Kindle has firmware 5.10.2 or later, you won't be able to remove DRM from the KFX format books on it.

See this post for other options and a link for Kindle for PC version 1.24:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by davidkels** [comment]
@ElleKayEm Ok, that makes sense I would have downloaded those books after the firmware update so I only those books are affected. Many thanks for the info I will look at the other options.
