### ISSUE TITLE
Unable to remove DRM

### ISSUE THREAD

**Issue by swalkerc** [apprenticeharper/DeDRM_tools#839]
I'm having trouble removing DRM from a Kindle ebook I purchased. I'm on a Mac OS 10.14.5 using Calibre 3.44.0 and the de-DRM plugin 6.6.3 and Kindle software version 1.23.1
Here's the log I copied from the debug mode
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 3.44  embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 0) && KFX metadata reader (from KFX Input) (1, 17, 0) && KFX Input (1, 17, 0) && Obok DeDRM (6, 5, 4) && Kindle Collections (1, 7, 23) && Goodreads (1, 4, 0) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && Overdrive Link (2, 33, 0)
calibre 3.44  embedded-python: True is64bit: True
Darwin-18.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.6.0', 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 0) && KFX metadata reader (from KFX Input) (1, 17, 0) && KFX Input (1, 17, 0) && Obok DeDRM (6, 5, 4) && Kindle Collections (1, 7, 23) && Goodreads (1, 4, 0) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && Overdrive Link (2, 33, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.29] splash screen shown
[0.29] Initializing db...
Failed to read metadata from font file: /Users/Sarah/Library/Fonts/CALVINN.TTF tuple index out of range
[0.34] db initialized
[0.34] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
/Users/Sarah/Documents/Kindle Books to Calibre is not a valid directory to watch for new ebooks, ignoring
[1.93] main UI initialized...
[1.93] Hiding splash screen
[2.02] splash screen hidden
[2.03] Started up in 2.03 seconds with 248 books
objc[5736]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9e4413d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11cb6bf50). One of the two will be used. Which one is undefined.
DeDRM v6.6.3: Trying to decrypt Encountering God.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Encountering God
Got DSN key from database default_key_2
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/Sarah/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '0919978a0e94' and UserName 'Sarah'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Encountering God
Got DSN key from database default_key_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Encountering God to db in: 0.0
Added 1 books in 1.1 seconds
libpng warning: iCCP: known incorrect sRGB profile
2019-06-04 09:09:45.293 Calibre[5821:6518189] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.203444004059
Job: 0 Convert book 1 of 1 (Encountering God) finished
Convert book 1 of 1 (Encountering God)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'kindle_pw'
	  cover: u'/var/folders/ct/fv07nf_96pn8qkrg1wb9zym80000gn/C/calibre_3.44.0_tmp_Btgeiq/C49ZJS.jpeg'
	  read_metadata_from_opf: u'/var/folders/ct/fv07nf_96pn8qkrg1wb9zym80000gn/C/calibre_3.44.0_tmp_Btgeiq/0k6cau.opf'
	Resolved conversion options
	calibre version: 3.44.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/ct/fv07nf_96pn8qkrg1wb9zym80000gn/C/calibre_3.44.0_tmp_Btgeiq/C49ZJS.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x108e62290>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x108e62a50>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/ct/fv07nf_96pn8qkrg1wb9zym80000gn/C/calibre_3.44.0_tmp_Btgeiq/0k6cau.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/ct/fv07nf_96pn8qkrg1wb9zym80000gn/C/calibre_3.44.0_tmp_Btgeiq/xk1aAi.azw3
	Found KF8

**Comment by swalkerc** [comment]
Deleted everything and got it to work.
