### ISSUE TITLE
Calibre issue with AZW3

### ISSUE THREAD

**Issue by crash28810** [apprenticeharper/DeDRM_tools#846]
I'm running Windows 10, Calibre 3.44 and I downloaded a Kindle file in an AZW3 format to my  Kindle E-reader (2nd generation). I, subsequently, imported the file into Calibre and tried viewing the file and received a DRM warning. I have no uninstalled Plugins and have 6.6.3 Tools installed and I have the Kindle E-reader serial number added to the DeDRM plugin . I have 5 books that I can read with my Kindle E-reader but I can't read in Calibre. Here is the log:
calibre Debug log
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.33] main UI initialized...
[1.33] Hiding splash screen
[5.33] splash screen hidden
[5.33] Started up in 5.33 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xd7\x92\xfbv\xab\xd9\xe7\xa85\xaa*\x8d\x13)\x1d\x060\x0c\x93Nz\x84X\x90\xd4\x16\xc4\xab\xde\xc3\x87\xd7', 'C:\\Users\\LeonardK\\Desktop\\Newest Books\\Bittersweet (True North Book 1) - Sarina Bowen.azw3']
DeDRM v6.6.3: Trying to decrypt Bittersweet (True North Book 1) - Sarina Bowen.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Bittersweet (True North Book 1)
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\LeonardK\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Bittersweet (True North Book 1) to db in: 1.8
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
Double-check the serial number -- try copy & paste from the website.  You might also want to try using 64-bit calibre.

**Comment by crash28810** [comment]
I followed your instructions and it worked; but, I don't understand why it works. I will admit that I neglected to use capitalization on the serial number and if that's the reason than perhaps a warning should be issued at the time of data entry. As for the difference between 32 and 64 bit versions, who knows?
