### ISSUE TITLE
Still can't open a MOBI

### ISSUE THREAD

**Issue by Gummomarx** [apprenticeharper/DeDRM_tools#853]
**I'm trying to read the MOBI on my Windows 7 PC but the DRM is still intact in spite of the manoeuvre with Calibre 3.44 and DeDRM_tools_6.6.3.

Help!**

calibre Debug log
calibre 3.44 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.44 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 71.9595278246 x 72.0810810811
Using calibre Qt style: True
[0.00] Starting up...
Failed to read metadata from font file: c:\windows\fonts\calvinn.ttf tuple index out of range
Failed to read metadata from font file: [0.02] Showing splash screen...c:\windows\fonts\calvino.ttf
 tuple index out of range
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[2.18] main UI initialized...
[2.18] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=2660)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x0000000003FD6A58>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 200, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Amazon Kindle. Try rebooting

Connect to device failed, retrying in 5 seconds...
[14.40] splash screen hidden
[14.40] Started up in 14.40 seconds with 16 books
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=2660)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x0000000003FD6A58>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 200, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Amazon Kindle. Try rebooting

Device connect failed again, giving up
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe5\xb5\x96M\xd1\x18\x948 \x19<\xf97\x1e\x87\xaa]\x14\xc5\xa4\x8f\x14Tl\x8b\xcf\xe4gp\xc9(\xb9', 'C:\\My Documents\\Downloads\\Richard Douthwaite - The Growth Illusion.mobi']
DeDRM v6.6.3: Trying to decrypt Richard Douthwaite - The Growth Illusion.mobi
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: The Growth Illusion: How economic growth has enriched the few, impoverished the many and endangered the planet.
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Winterfell\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Growth Illusion: How economic growth has enriched the few, impoverished the many and endangered the planet. to db in: 0.1
Added 1 books in 0.8 seconds
Worker Launch took: 0.171000003815
Storage number map:
{(7L, 0L): [(2L, 'C')], (7L, 1L): [(1L, 'D')]}
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=2660)
{u'drive_letters': [],
 u'pnp_id_map': {},
 u'readonly_drives': set([]),
 u'sort_map': {}}
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x0000000003FD6A58>
Traceback (most recent call last):
  File "site-packages\calibre\gui2\device.py", line 200, in do_connect
  File "site-packages\calibre\devices\usbms\device.py", line 821, in open
  File "site-packages\calibre\devices\usbms\device.py", line 275, in open_windows
DeviceError: Unable to detect any disk drives for the device: Amazon Kindle. Try rebooting

Connect to device failed, retrying in 5 seconds...

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the plugin customization.
