### ISSUE TITLE
Installation problem 'DeDRM_plugin.zip' missing

### ISSUE THREAD

**Issue by sizeur** [apprenticeharper/DeDRM_tools#856]
Hello, 
The [installation doc](https://github.com/apprenticeharper/DeDRM_tools/blob/master/CALIBRE_CLI_INSTRUCTIONS.md#install-plugins) says: 
"cd *the unzipped DeDRM_tools folder*
calibre-customize --add DeDRM_calibre_plugin/DeDRM_plugin.zip"

What I did is:
toto@toto-Latitude-5591:/Downloads# git clone https://github.com/apprenticeharper/DeDRM_tools.git
[...]
toto@toto-Latitude-5591:/Downloads ls
DeDRM_tools
toto@toto-Latitude-5591:/Downloads$ cd DeDRM_tools/
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ ls
CALIBRE_CLI_INSTRUCTIONS.md  contrib  dedrm_src  FAQs.md  make_release.py  obok_src  README.md
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ cd contrib/DeDRM_calibre_plugin/
toto@toto-Latitude-5591:/Downloads/DeDRM_tools/contrib/DeDRM_calibre_plugin$ ls
DeDRM_plugin_ReadMe.txt

**There is no file called "DeDRM_plugin.zip" here or anywhere else:** 

toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ find -name '*zip' 
./dedrm_src/alfcrypto_src.zip
./contrib/Other_Tools/Rocket_ebooks/rebhack.zip
./contrib/DeDRM_Macintosh_Application/DeDRM.app/Contents/Resources/DeDRM Progress Source.zip
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ sudo updatedb
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ locate 'DeDRM_plugin.zip'
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$

toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ calibre-customize --add ./dedrm_src/alfcrypto_src.zip 
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/customize/ui.py", line 798, in main
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'./dedrm_src/alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file
toto@toto-Latitude-5591:/Downloads/DeDRM_tools$ cd dedrm_src/
toto@totoLatitude-5591:/Downloads/DeDRM_tools/dedrm_src$ calibre-customize --add alfcrypto_src.zip
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/customize/ui.py", line 798, in main
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 194, in load
  File "site-packages/calibre/customize/zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_6.6.3.zip from here:

https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.6.3

Unzip that, look in the DeDRM_calibre_plugin folder for DeDRM_plugin.zip.

**Comment by sizeur** [comment]
Thank's dude it works like a charm keep going :muscle:
