### ISSUE TITLE
Can't find a usable init.tcl

### ISSUE THREAD

**Issue by voltagex** [apprenticeharper/DeDRM_tools#86]
On a new Python 2.7.11 install on Windows (32 bit), the drop target wasn't working at all

```
python DeDRM_App.pyw
Using Library AlfCrypto DLL/DYLIB/SO
Traceback (most recent call last):
  File "DeDRM_App.pyw", line 688, in <module>
    sys.exit(main())
  File "DeDRM_App.pyw", line 682, in main
    app = MainApp(apphome, dnd, filenames)
  File "DeDRM_App.pyw", line 78, in __init__
    Tk.__init__(self)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1814, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Program Files (x86)\CSR\BlueSuite 2.5.0} C:/Python27/lib/tcl8.5 C:/lib/tcl8.5 C:/lib/tcl8.5 C:/library C:/library C:/tcl8.5.15/library C:/tcl8.5.15/library



This probably means that Tcl wasn't installed properly.
```

**Comment by voltagex** [comment]
Fixed by setting the TCL_LIBRARY environment variable to C:\Python27\tcl\tcl8.5\

**Comment by jefmud** [comment]
I ran into this when building a tkinter gui in a virtual environment (Python 2.7).  I had to use the setting (that voltagex mentioned above) to get my program to work properly.
