### ISSUE TITLE
Trouble removing DRM from kindle ebook

### ISSUE THREAD

**Issue by ghov111** [apprenticeharper/DeDRM_tools#860]
I was unable to removed DRM on a kindle ebook I downloaded off of the Amazon website. I'm using a Mac, version 10.12.6. I'm trying to convert the book to PDF.  Here is the code from debug mode:

calibre Debug log
calibre 3.44  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.44  embedded-python: True is64bit: True
Darwin-16.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '16.7.0', 'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[1.53] main UI initialized...
[1.53] Hiding splash screen
[1.53] splash screen hidden
[1.53] Started up in 1.53 seconds with 1 books
DeDRM v6.6.3: Trying to decrypt Coming Up Short.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Coming Up Short
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Coming Up Short to db in: 0.1
Added 1 books in 1.0 seconds

Here's a link to the book: https://www.amazon.com/gp/product/B00DI8RM2A?pf_rd_p=2d1ab404-3b11-4c97-b3db-48081e145e35&pf_rd_r=KS0EA46SMRAWBCNN998B

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to chose an E-ink Kindle (not a Fire) for the device and enter its serial number into the DeDRM plugin customization.

**Comment by ghov111** [comment]
What if I don’t have an actual device?

**Comment by j-howell** [comment]
>> What if I don’t have an actual device?

The "Download & transfer via USB" function on Amazon's website is made only available if you own a Kindle or Fire device and you have to select which device you intend to book to be used on.

IF you obtained the book using some other method you will have to indicate how you did that in order to get correct instructions.

**Comment by ghov111** [comment]
Oh, that makes sense. I had a kindle back in the day, so the “download & transfer to usb” is showing up for that one.

Re: "When downloading from the website, you need to chose an E-ink Kindle (not a Fire) for the device and enter its serial number into the DeDRM plugin customization.”  

The only option amazon gives me is to transfer it to this Kindle Fire. Is there another way I can download the file? Or how can I get the option to choose E-ink Kindle? 

Thanks!!

**Comment by j-howell** [comment]
> Is there another way I can download the file? Or how can I get the option to choose E-ink Kindle?

You will only have the option to download for an e-ink Kindle if you have one registered to your Amazon account.

The other way to obtain Kindle files is by using Kindle for PC or Kindle for Mac. See the FAQ for more details.

**Comment by nashthecoder** [comment]
I have bought 3 book on google books and I would like to have them on my kindle. I have tried usinf the DeDRM plugin on Calibre as well as the DeDRM app directly but I have been unable to convert them to MOBI. 
This is the error I get when I use Calibre in debug mode. 

calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.0.0', 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 126.000001892 x 127.000001907
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.26] db initialized
[0.26] Constructing main UI...
[1.43] main UI initialized...
[1.43] Hiding splash screen
[1.45] splash screen hidden
[1.46] Started up in 1.46 seconds with 4 books
Worker Launch took: 0.13011598587
Worker Launch took: 0.127622842789
Worker Launch took: 0.153414964676
Job: 0 Convert book 3 of 3 (A Mind For Numbers) finished
Convert book 3 of 3 (A Mind For Numbers)
	Conversion options changed from defaults:
	  output_profile: u'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/l6SzNZ.opf'
	Resolved conversion options
	calibre version: 3.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10eed6550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x10eed6d50>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/l6SzNZ.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on /var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/dsCAtF.epub
	Python function terminated unexpectedly: dsCAtF.epub
	Traceback (most recent call last):
	  File "/private/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/T/AppTranslocation/1945086C-4F5C-44FF-BF19-0249EA8C75B0/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/private/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/T/AppTranslocation/1945086C-4F5C-44FF-BF19-0249EA8C75B0/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: dsCAtF.epub

Job: 1 Convert book 2 of 3 (Mindshift) finished
Convert book 2 of 3 (Mindshift)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'kindle_pw3'
	  read_metadata_from_opf: u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/IpQBpQ.opf'
	Resolved conversion options
	calibre version: 3.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f2ae590>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x10f2aed90>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/IpQBpQ.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on /var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/ihMpok.epub
	Python function terminated unexpectedly: ihMpok.epub
	Traceback (most recent call last):
	  File "/private/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/T/AppTranslocation/1945086C-4F5C-44FF-BF19-0249EA8C75B0/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/private/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/T/AppTranslocation/1945086C-4F5C-44FF-BF19-0249EA8C75B0/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: ihMpok.epub

Job: 2 Convert book 1 of 3 (Moonwalking with Einstein: The Art and Science of...) finished
Convert book 1 of 3 (Moonwalking with Einstein: The Art and Science of...)
	Conversion options changed from defaults:
	  output_profile: u'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/_t5kCl.opf'
	Resolved conversion options
	calibre version: 3.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x115b52550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x115b52d50>,
	 'page_breaks_before': u'/',
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/jv/82t30xxx4y9cf989jbny9qmm0000gn/C/calibre_3.46.0_tmp_ZKPWds/_t5kCl.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules'

**Comment by ElleKayEm** [comment]
Since this is completely unrelated to this issue, open a new issue and post an import log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
