### ISSUE TITLE
Unable to decrypt kindle for pc azw file

### ISSUE THREAD

**Issue by lcsa** [apprenticeharper/DeDRM_tools#861]
dedrm v6.6.3，have returned to kindle 1.17 but no use.

calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.44  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 81.28 x 80.6823529412
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.25] main UI initialized...
[1.25] Hiding splash screen
[11.89] splash screen hidden
[11.89] Started up in 11.89 seconds with 60 books
DeDRM v6.6.3: Trying to decrypt B077M6FQ2L_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐪熴兓濂崇杌㈢敓 DEEP STRANGE JOURNEY銆€鍏紡銉戙兗銉曘偋銈儓銈偆銉?(銈儓銉┿偣銉曘偂銉熼€?
Got DSN key from database default_key
Found 3 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.9 seconds
searching for kinfoFiles in C:\Users\Lyner\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Lyner\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1723951909' and UserName '4c796e6572'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐪熴兓濂崇杌㈢敓 DEEP STRANGE JOURNEY銆€鍏紡銉戙兗銉曘偋銈儓銈偆銉?(銈儓銉┿偣銉曘偂銉熼€?
Got DSN key from database default_key_1
Found 4 keys to try after 1.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added 鐪熴兓濂崇杌㈢敓 DEEP STRANGE JOURNEY銆€鍏紡銉戙兗銉曘偋銈儓銈偆銉?(銈儓銉┿偣銉曘偂銉熼€? to db in: 0.7
Added 1 books in 2.6 seconds
Worker Launch took: 0.198000192642
Using Library AlfCrypto Python
searching for kinfoFiles in C:\Users\Lyner\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Lyner\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1723951909' and UserName '4c796e6572'
searching for kinfoFiles in C:\Users\Lyner\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Lyner\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1723951909' and UserName '4c796e6572'
searching for kinfoFiles in C:\Users\Lyner\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Lyner\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1723951909' and UserName '4c796e6572'
DeDRM v6.6.3: Trying to decrypt B077M6FQ2L_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright 漏 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 鐪熴兓濂崇杌㈢敓 DEEP STRANGE JOURNEY銆€鍏紡銉戙兗銉曘偋銈儓銈偆銉?(銈儓銉┿偣銉曘偂銉熼€?
Got DSN key from database default_key
Found 4 keys to try after 1.1 seconds
Crypto Type is: 2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 536, in KindleMobiDecrypt
IndexError: tuple index out of range
Added 鐪熴兓濂崇杌㈢敓 DEEP STRANGE JOURNEY銆€鍏紡銉戙兗銉曘偋銈儓銈偆銉?(銈儓銉┿偣銉曘偂銉熼€? to db in: 0.7
Added 1 books in 2.8 seconds
Worker Launch took: 0.192999839783

**Comment by ElleKayEm** [comment]
Try 64-bit calibre.
