### ISSUE TITLE
Troubleshooting - not removing DRM on 2-3 books (Win10/Amazon Kindle PC)

### ISSUE THREAD

**Issue by Darpaou1** [apprenticeharper/DeDRM_tools#869]
When you tell me what I am doing wrong....  Can you tell me how you know?  Or what I should have looked for.  This debugging log is just a bunch or random words to me.  Almost ALL my books had DRM removed.  However this was one problem:

C:\Users\XXXX>calibre-debug -g
calibre 3.46  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[3.30] splash screen shown
[3.30] Initializing db...
[4.20] db initialized
[4.20] Constructing main UI...
[18.31] main UI initialized...
[18.31] Hiding splash screen
[19.84] splash screen hidden
[19.84] Started up in 19.84 seconds with 67 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x0c\xa2\x15\x98k\xcf\xa2Bo\xcc\xd7\xdf\xc9.\x1eV\xec3\x1e\xd7\x88Q\x13G<\xcdA\xfdE\xec\xa5\xba', "C:\\Users\\InelU\\Desktop\\Empath's Book Of Energy Healing In 5-Minute_ Remove Negative Energies & People NOW.azw3"]
DeDRM v6.6.3: Trying to decrypt Empath's Book Of Energy Healing In 5-Minute_ Remove Negative Energies & People NOW.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Empath's Book Of Energy Healing In 5-Minute: Remove Negative Energies & People NOW
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\InelU\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\InelU\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4168485429' and UserName '496e656c55'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Empath's Book Of Energy Healing In 5-Minute: Remove Negative Energies & People NOW
Got DSN key from database default_key_1
Found 3 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Empath's Book Of Energy Healing In 5-Minute: Remove Negative Energies & People NOW to db in: 0.8
Added 1 books in 2.5 seconds

**Comment by ElleKayEm** [comment]
When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into DeDRM's customization.

**Comment by Darpaou1** [comment]
> When downloading from the website, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into DeDRM's customization.

I saw this solution.  I am downloading from my computer.  I download my ebook from: "Manage Your Content and Devices"  select content, click the "... then download.



I will just do what you said.  Unless the above description changes anything TY.
