### ISSUE TITLE
Unable to decrypt Kindle Files Using Calibre Plugin or GUI Version

### ISSUE THREAD

**Issue by alexhunter90** [apprenticeharper/DeDRM_tools#874]
Downloading books from Kindle for Mac 1.17.1 (on another machine running High Sierra)

Have tried 2 books now and both have failed. I've tried using Calibre plugin and GUI standalone.

Any help would be much appreciated.

Here's my log:

[DeDRM.log](https://github.com/apprenticeharper/DeDRM_tools/files/3489342/DeDRM.log)

**Comment by alexhunter90** [comment]
`There is 1 ebook to be decrypted.
Processing file: B002XHNN7A_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/alex/Desktop/Archive2/B002XHNN7A_EBOK.azw' '/Users/alex/Desktop/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.6
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/alex/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'ddeae6b6f4ba' and UserName 'alex'
Saved a key to /Users/alex/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/KindleKey.der' '/Users/alex/Desktop/Archive2/B002XHNN7A_EBOK.azw' '/Users/alex/Desktop/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/92D2596A-5FA2-4C44-8528-DDAEA4BBD69B/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
B002XHNN7A_EBOK.azw couldn't be decrypted.

`

**Comment by alexhunter90** [comment]
Ok now I noticed the FAQ section titled "The application opens, but always gives an error in the log 'ImportError: No module named Crypto.Cipher'"

I successfully installed everything, I did still get the "something about pylzma in error log" and installed that too.

But now it is still failing with a different reason:

`There is 1 ebook to be decrypted.
Processing file: B002XHNN7A_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/alex/Desktop/Archive2/B002XHNN7A_EBOK.azw' '/Users/alex/Desktop/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.7.
Copyright © 2008-2017 Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Siddhartha (Penguin Modern Classics)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 0 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 265, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 239, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 0 keys tried.
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.6
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/alex/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString 'ddeae6b6f4ba' and UserName 'alex'
Saved a key to /Users/alex/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/KindleKey 3.der' '/Users/alex/Desktop/Archive2/B002XHNN7A_EBOK.azw' '/Users/alex/Desktop/' > '/Users/alex/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
K4MobiDeDrm v5.7.
Copyright © 2008-2017 Apprentice Harper et al.
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Siddhartha (Penguin Modern Classics)
Got DSN key from database /Users/alex/Library/Preferences/com.apprenticealf.dedrm/KindleKey 3.der
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
Error decrypting book after 0.0 seconds: No key found in 4 keys tried.
 Traceback (most recent call last):
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 265, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 239, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/private/var/folders/yb/w1c95y6x0tn7_ttqcwnnyvdm0000gn/T/AppTranslocation/6754B0BC-3CC5-499A-B4A6-7C4314AACEAE/d/DeDRM.app/Contents/Resources/mobidedrm.py", line 471, in processBook
    raise DrmException(u"No key found in {0:d} keys tried.".format(len(goodpids)))
DrmException: No key found in 4 keys tried.
There was an error with 1 ebook:
B002XHNN7A_EBOK.azw couldn't be decrypted.

`

**Comment by ElleKayEm** [comment]
Were the books downloaded with the installation of Kindle for Mac which is on the same machine and user as DeDRM?

**Comment by alexhunter90** [comment]
Thanks that fixed it!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
