### ISSUE TITLE
unable to deDRM AWZ?

### ISSUE THREAD

**Issue by IAmInept** [apprenticeharper/DeDRM_tools#875]
calibre Debug log
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.373333333 x 107.576470588
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[1.05] main UI initialized...
[1.05] Hiding splash screen
[3.67] splash screen hidden
[3.67] Started up in 3.67 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['B\xf3\xbf\x08\x13\x94o\x89,.Y;c\x04kX\xb9.\xc3\xe4U[\x99\xf19\x92\xef\x97\xa3\x84O\x88', 'C:\\Users\\cyani\\Documents\\My Kindle Content\\B07PFHZS85_EBOK\\B07PFHZS85_EBOK.azw']
DeDRM v6.6.3: Trying to decrypt B07PFHZS85_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ブルーロック（３） (週刊少年マガジンコミックス)
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\cyani\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\cyani\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '574090978' and UserName '6379616e69'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: ブルーロック（３） (週刊少年マガジンコミックス)
Got DSN key from database default_key_1
Found 3 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added ブルーロック（３） (週刊少年マガジンコミックス) to db in: 0.2
Added 1 books in 1.7 seconds

**Comment by ElleKayEm** [comment]
DeDRM doesn't work with the latest versions of Kindle for PC.  You'll need to go back to version 1.24 or earlier.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371
