### ISSUE TITLE
Trouble removing DRM from AZW Kindle for Mac

### ISSUE THREAD

**Issue by kv86** [apprenticeharper/DeDRM_tools#881]
calibre Debug log
calibre 3.15  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
calibre 3.15  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.12
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 17, 1) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 17, 1) && Set KFX metadata (from KFX Output) (1, 30, 0) && KFX Output (1, 30, 0) && KFX metadata reader (from KFX Input) (1, 17, 1) && KFX Input (1, 17, 1)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 103.000001547 x 103.000001547
Using calibre Qt style: True
Starting up...
Started up in 1.52 seconds with 1 books
Gather KFX-ZIP (from KFX Input) 1.17.1: Importing /Users/krystal/Documents/My Kindle Content/B00SZE8ZW8_EBOK/B00SZE8ZW8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 7 file(s) as /var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/YOWMVC.kfx-zip
DeDRM v6.6.3: Trying to decrypt YOWMVC.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: YOWMVC
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c68a677f-e847-4850-b76a-eb040af2a112.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B00SZE8ZW8_EBOK.azw has DRM and cannot be converted
Package KFX (from KFX Input) 1.17.1: Packaging /var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/YOWMVC.kfx-zip
Processing container: B00SZE8ZW8_EBOK.azw
KFX metadata reader (from KFX Input) activated for /var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/9J7B98_add_books/0/B00SZE8ZW8_EBOK.kfx-zip
2019-08-19 17:49:21.680 Calibre[40487:5759665] deliverNotificationWithTitle()
* Notification delivered.
Added Language Development to db in: 0.1
Added 1 books in 1.6 seconds
Worker Launch took: 0.0990941524506
Job: 1 Convert book 1 of 1 (Language Development) finished
Convert book 1 of 1 (Language Development)
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/pGuDa7.opf'
	  cover: u'/var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/ldJRn4.jpeg'
	Resolved conversion options
	calibre version: 3.15.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/ldJRn4.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x112a70490>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x112a70c50>,
	 'page_breaks_before': u'/',
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Liberation Mono',
	 'pdf_mono_font_size': 16,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Liberation Sans',
	 'pdf_serif_family': u'Liberation Serif',
	 'pdf_standard_font': u'serif',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/ps/68gd2gvn213gyrftp93sxz880000gn/C/calibre_3.15.0_tmp_dbpe1h/pGuDa7.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 98, in convert
	  File "calibre_plugins.kfx_input.__init_

**Comment by kv86** [comment]
I just need to download kindle for mac 1.7
