### ISSUE TITLE
Failed: convert book  1 of 1 

### ISSUE THREAD

**Issue by narddawg69** [apprenticeharper/DeDRM_tools#882]
Hello, 
I'm not sure what I'm doing wrong

any help is appreciated!! 

calibre, version 3.46.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 

Convert book 1 of 1 (Adventures in the Human Spirit)
Conversion options changed from defaults:
  read_metadata_from_opf: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_ENr8z7/0jh4Qp.opf'
  output_profile: u'generic_eink'
  verbose: 2
  cover: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_ENr8z7/nrXY5d.jpeg'
Resolved conversion options
calibre version: 3.46.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_ENr8z7/nrXY5d.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1123a2e90>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x1123972d0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_ENr8z7/0jh4Qp.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: AZW4 Input running
on /var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_ENr8z7/H7lq86.azw4
Extracting PDF from AZW4 Container...
Converting file to html...
Python function terminated unexpectedly: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/azw4_input.py", line 27, in convert
  File "site-packages/calibre/ebooks/azw4/reader.py", line 59, in extract_content
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
  File "site-packages/calibre/ebooks/pdf/pdftohtml.py", line 89, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by narddawg69** [comment]
Thanks for the fast response!!
I got this message. what should I do next ? 

calibre, version 3.46.0
Debug mode: <p>You have started calibre in debug mode. After you quit calibre, the debug log will be available in the file: /var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/T/tmpCEeMjs.txt<p>The log will be displayed automatically.

**Comment by narddawg69** [comment]
I also got this 

calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KindleUnpack - The Plugin (0, 81, 2) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KindleUnpack - The Plugin (0, 81, 2) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 126.000001892 x 127.000001907
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.89] main UI initialized...
[1.89] Hiding splash screen
[1.89] splash screen hidden
[1.89] Started up in 1.89 seconds with 0 books

**Comment by ElleKayEm** [comment]
You need to add a book once you've opened in debug mode.

**Comment by narddawg69** [comment]
calibre Debug log
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KindleUnpack - The Plugin (0, 81, 2) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
calibre 3.46  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KindleUnpack - The Plugin (0, 81, 2) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 126.000001892 x 127.000001907
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.29] db initialized
[0.29] Constructing main UI...
[1.39] main UI initialized...
[1.39] Hiding splash screen
[1.43] splash screen hidden
[1.45] Started up in 1.45 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt B00AM291U6_EBOK.azw4
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Adventures in the Human Spirit
Got DSN key from database default_key
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.3: Looking for new default Kindle Key after 1.0 seconds
Found k4Mac kinf2011 file: /Users/Aljarrah/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '141308408574' and UserName 'Aljarrah'
DeDRM v6.6.3: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Adventures in the Human Spirit to db in: 0.6
Added 1 books in 3.3 seconds
Worker Launch took: 0.140898942947
Job: 0 Convert book 1 of 1 (Adventures in the Human Spirit) finished
Convert book 1 of 1 (Adventures in the Human Spirit)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/SjzhzA.opf'
	  verbose: 2
	  output_profile: u'generic_eink'
	  cover: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/ZKP1do.jpeg'
	Resolved conversion options
	calibre version: 3.46.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/ZKP1do.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10eb54f10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10eb5b350>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/SjzhzA.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: AZW4 Input running
	on /var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/7u6s6m.azw4
	Extracting PDF from AZW4 Container...
	Converting file to html...
	Python function terminated unexpectedly: pdftohtml failed with return code: 1
	Syntax Warning: May not be a PDF file (continuing anyway)
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't read xref table
	Traceback (most recent call last):
	Convert book 1 of 1 (Adventures in the Human Spirit)
Conversion options changed from defaults:
  read_metadata_from_opf: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/SjzhzA.opf'
  verbose: 2
  output_profile: u'generic_eink'
  cover: u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/ZKP1do.jpeg'
Resolved conversion options
calibre version: 3.46.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/ZKP1do.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': u'2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10eb54f10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10eb5b350>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/SjzhzA.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: AZW4 Input running
on /var/folders/vx/bl8p5gtj6hz1gg4n9x9dwhym0000gn/C/calibre_3.46.0_tmp_SQnioJ/7u6s6m.azw4
Extracting PDF from AZW4 Container...
Converting file to html...
Python function terminated unexpectedly: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/azw4_input.py", line 27, in convert
  File "site-packages/calibre/ebooks/azw4/reader.py", line 59, in extract_content
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
  File "site-packages/calibre/ebooks/pdf/pdftohtml.py", line 89, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table

  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 200, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 27, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/azw4_input.py", line 27, in convert
	  File "site-packages/calibre/ebooks/azw4/reader.py", line 59, in extract_content
	  File "site-packages/calibre/ebooks/conversion/plugins/pdf_input.py", line 54, in convert
	  File "site-packages/calibre/ebooks/pdf/pdftohtml.py", line 89, in pdftohtml
	calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
	Syntax Warning: May not be a PDF file (continuing anyway)
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't find trailer dictionary
	Syntax Error: Couldn't read xref table

**Comment by narddawg69** [comment]
it says can't decode library or rented books. Do I have to purchase books to be able to dedrm?

**Comment by j-howell** [comment]
From the FAQ:

>The tools are not designed to remove DRM from rented or library ebooks.

**Comment by maxbEternauta** [comment]
i´m running Calibre 5. 6.0 and i want to remove a DRM from a book. This is the error i`ve

calibre, version 5.6.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (dignidad (Ensayo) (Spanish Edition))

Convert book 1 of 1 (dignidad (Ensayo) (Spanish Edition))
DeDRM v7.0.0: Trying to decrypt qqjqxx10.azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: dignidad (Ensayo) (Spanish Edition)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 10 keys to try after 0.1 seconds
Crypto Type is: 2
File is encoded with PID b'7PUMOtXj73'.
Decrypting. Please wait . . . . done
Decryption succeeded after 1.1 seconds
DeDRM v7.0.0: Finished after 1.1 seconds
Conversion options changed from defaults:
  output_profile: 'kindle_pw3'
  read_metadata_from_opf: '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_sfegpf8a/65v24xxd.opf'
  cover: '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_sfegpf8a/c5f0bkcl.jpeg'
  verbose: 2
Resolved conversion options
calibre version: 5.6.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_sfegpf8a/c5f0bkcl.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11289dd60>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x1128ac400>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_sfegpf8a/65v24xxd.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v7.0.0: Trying to decrypt dq1ky201.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: dignidad (Ensayo) (Spanish Edition)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 10 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v7.0.0: Finished after 0.0 seconds
InputFormatPlugin: MOBI Input running
on /var/folders/x8/rc92y2k918b3bd8w9651vdn40000gn/C/calibre_5.6.0_tmp_sfegpf8a/yzh0rzhe.azw3
Found KF8 MOBI of type 'standalone'
Extracting text...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 114, in __call__
  File "calibre/ebooks/mobi/reader/mobi8.py", line 467, in expand_text
  File "calibre/ebooks/mobi/reader/markup.py", line 339, in expand_mobi8_markup
  File "calibre/ebooks/mobi/reader/markup.py", line 217, in update_flow_links
TypeError: sequence item 3: expected str instance, bytes found

Can you help me??

**Comment by ElleKayEm** [comment]
The log shows a successfully decrypted book and a book without DRM to begin with.

**Comment by maxbEternauta** [comment]
but i can´t see the ebook converted?

**Comment by ElleKayEm** [comment]
They aren't there in your calibre library?

**Comment by maxbEternauta** [comment]
> They aren't there in your calibre library?

No... 🥺

**Comment by ElleKayEm** [comment]
Well, DeDRM has removed the DRM on the one book and the other didn't have DRM.  Otherwise, I don't know what the issue is.  I'd try removing and re-adding the book.  If that doesn't work, then I suggest trying DeDRM 6.8.1 with calibre 4.23.

**Comment by j-howell** [comment]
> Conversion error: Failed: Convert book 1 of 1 (dignidad (Ensayo) (Spanish Edition))
> ...
> TypeError: sequence item 3: expected str instance, bytes found
> 
> Can you help me??

That is not a problem with DRM removal, it is an error during conversion to another format. You will have to ask for help with that issue in the [calibre conversion forum](https://www.mobileread.com/forums/forumdisplay.php?f=235).
