### ISSUE TITLE
Just installed on Windows, not working

### ISSUE THREAD

**Issue by ElektroQuark** [apprenticeharper/DeDRM_tools#885]
Hi,

Here is the log, as requested.
THANK YOU VERY MUCH.
________________________________________________________________________________________________
calibre Registro de depuración
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Kobo Utilities (2, 6, 0) && KoboTouchExtended (3, 0, 2)
calibre 3.46 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Kobo Utilities (2, 6, 0) && KoboTouchExtended (3, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 83.793814433 x 83.7362637363
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    1.4 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    1.4 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    1.4 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    1.4 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver:KoboTouchExtended'
[1.69] main UI initialized...
[1.69] Started up in 1.69 seconds with 855 books
C:\Program Files\Calibre2\app\pylib.zip\dateutil\parser.py:601: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
DeDRM v6.6.3: Trying to decrypt XXXXXX_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: XXXXXXXXXXXX
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\XXXXX\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\XXXXX\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString 'XXXXXXXXX' and UserName 'XXXXXXXXXX'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: XXXXXXXXXXXXXX
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Worker Launch took: 0.197999954224

**Comment by ElleKayEm** [comment]
Was the book downloaded with Kindle for PC that's currently installed on the same machine and user as calibre with DeDRM?

**Comment by tenxt** [comment]
I had the same issue and the Kindle for PC was currently installed on the same machine and user as calibre with DeDRM

**Comment by tenxt** [comment]
Ok I just solved my own issue. The reason it has taken me so long is due to all the scatter instructions and you kind of have to piece all the information together. 

Here are instructions in the most paraphrased form. At least how it would of helped me anyways..

Steps for DeDRM and KFX plugins with Windows 10 PC, Kindle book:
1. Download Kindle version 1.24.3 or less.
- Link here: [https://medium.com/@angeldan1989/the-latest-solution-to-remove-drm-from-kindle-kfx-books-2018-e27d6f71df4f](url)
2. Register/Login to your Amazon account.
3. Buy the Kindle book you want on Amazon. Do not buy the rented version because it won't work.
4. Wait for book to download on Kindle Window PC Program
5. Download calibre
-Link here: [https://calibre-ebook.com/download_windows](url)
6. Download DeDRM from apprenticeharper
- Link here: v6.6.3 [https://github.com/apprenticeharper/DeDRM_tools/releases](url)
7. Unzip file
8. Go in to calibre to add plugins under "Preferences". Click the unzipped DeDRM folder. Choose folder "DeDRM_calibre_plugin" and then click the zip file name "DeDRM_plugin" to add the plugin.
9. Click ok on all and then "apply"
10. Exit calibre and open again.
11. Download the KFX plugin
- Link here: [https://www.mobileread.com/forums/showthread.php?t=291290](url)
12. Go in to calibre to add plugins under "Preferences". Click the zip file "KFX Input" to add the plugin.
13. Click ok on all and then "apply"
14. Exit calibre and open again.
15. Now click add books. Click folder "My Kindle Content." Then click the book you want to add.
16. After the book is added, check the side of calibre to see if there was any change to "Format: azw." If the format changed anything like "Format: azw4" etc. then you have been successful.
17. Now you can convert the book in to any other format you wish.
18. Happy reading.

**Comment by Ultrabenosaurus** [comment]
@tenxt you are excellent. I realised yesterday that I hadn't backed up my new Kindle books in a while, went through the usual steps, but got stuck with `KFX-ZIP` files that were completely useless. Most of my searches came up saying "Calibre doesn't remove DRM from Kindle Unlimited books because they're rentals" except these aren't KU books, they're books purchased while I had a KU subscription. I thought all was lost until I found this post, downgraded Kindle for PC to v1.24.3! Now they import as KFX which Calibre still won't open, but can convert to other formats. Thank you very much.

**Comment by tenxt** [comment]
@Ultrabenosaurus Thx so much! I’m glad it helped! I remember spending a whole day looking up everything there was to know about how to do this. I just didn’t want someone else to have to go through what I went through! Happy reading!
