### ISSUE TITLE
Unable to decrypt pdf

### ISSUE THREAD

**Issue by aunez48** [apprenticeharper/DeDRM_tools#890]
I´ve just bought a book and i open it with adobe digital edition 4.5 (could not open with lower version) I have DeDRM several books before from amazon and google but I cannot DeDRM this.
Here I copy calibre log.

Thank you in advance!

calibre Registro de depuración
calibre 3.47  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
calibre 3.47  embedded-python: True is64bit: False
Windows-10-10.0.17763-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 96.0 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.11] splash screen shown
[0.11] Initializing db...
[0.11] db initialized
[0.11] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
[17.92] splash screen hidden
[17.92] Started up in 17.92 seconds with 41 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['e\xf7t\xc9\x0e\xc5 \x97%\xe12\xd3\xc1\xed\xb5X\x8c\x9a\xef\xa1 \xa2\xf0\t\xb5%\x93\xb8\xe8yS<', 'D:\\Alvaro\\My Digital Editions\\MATEM\xc3\x81TICAS PARA LA COMPUTACI\xc3\x93N 3\xc2\xaa Edici\xc3\xb3n.pdf']
DeDRM v6.6.3: Trying to decrypt MATEMÃTICAS PARA LA COMPUTACIÃ“N 3Âª EdiciÃ³n.pdf
DeDRM v6.6.3: MATEMÃTICAS PARA LA COMPUTACIÃ“N 3Âª EdiciÃ³n.pdf is a PDF ebook
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v6.6.3: Trying a new default key
DeDRM v6.6.3: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 478, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1484, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1616, in initialize_ebx
ADEPTError: error decrypting book session key
DeDRM v6.6.3: Failed to decrypt with new default key after 0.2 seconds
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 506, in PDFDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 343, in get_metadata
  File "site-packages\calibre\ebooks\metadata\pdf.py", line 128, in get_metadata
ValueError: Could not read info dict from PDF
Added MATEMÁTICAS PARA LA COMPUTACIÓN 3ª Edición to db in: 1.1
Added 1 books in 2.4 seconds

**Comment by ElleKayEm** [comment]
If you couldn't open it with ADE 2.0.1, then you may have run into a newer Adobe DRM which cannot be removed.

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-registered-adobe-digital-editions-30-or-later-with-an-adobe-id-before-downloading-but-my-epub-or-pdf-still-has-drm

**Comment by aunez48** [comment]
Thank you for your answer, so i cannot do it :( 
May be in the future will be posibble....
Thanks again
