### ISSUE TITLE
cannot get the plugin installer file to open.

### ISSUE THREAD

**Issue by CandaceMS** [apprenticeharper/DeDRM_tools#891]
calibre, version 3.47.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\Candace\\Desktop\\DeDRM_tools-6.6.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 3.47.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 318, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\Candace\\Desktop\\DeDRM_tools-6.6.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
You're trying to load the whole archive.  Unzip that file.  Look in the DeDRM calibre plugin folder.  Load DeDRM_plugin.zip.
