### ISSUE TITLE
Still can't DeDRM in Calibre for Amazon ebook

### ISSUE THREAD

**Issue by sgweinst** [apprenticeharper/DeDRM_tools#892]
I still can't DeDRM in Calibre for Amazon ebook. I added the plug-in, and tried converting. 
Please help me. I have a few other books I have purchased from mazon that I am unable to remove DRM.
Thanks
Here's my log:
calibre Debug log
calibre 3.47  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
calibre 3.47  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.41] main UI initialized...
[1.41] Hiding splash screen
[8.33] splash screen hidden
[8.33] Started up in 8.33 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xf3\\\xe5\xf6:\xb5+\xb4\xf5\x18\x9e\t\xc5j\x0e^T{,d\xe8,V\xe8\xca$\xd1\xa2N\x90\xec\x1a', 'C:\\Users\\Susan\\Documents\\New books\\Kindle Books\\Surprise Goddess 00 - Rise Like a Goddess.azw3']
DeDRM v6.6.3: Trying to decrypt Surprise Goddess 00 - Rise Like a Goddess.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0)
Got DSN key from database kindlekey1
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 9 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 9 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Susan\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Susan\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '611564336' and UserName '537573616e'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0)
Got DSN key from database default_key_1
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0) to db in: 0.2
Added 1 books in 2.2 seconds
Worker Launch took: 0.203999996185
Job: 0 Convert book 1 of 1 (Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0)) finished
Convert book 1 of 1 (Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0))
	Conversion options changed from defaults:
	  cover: u'C:\\Users\\Susan\\AppData\\Local\\Temp\\calibre_lhjitq\\rkczbe.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\Susan\\AppData\\Local\\Temp\\calibre_lhjitq\\trjzwc.opf'
	  verbose: 2
	  output_profile: u'ipad3'
	Resolved conversion options
	calibre version: 3.47.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Susan\\AppData\\Local\\Temp\\calibre_lhjitq\\rkczbe.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x050B6A50>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x050B6D30>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Susan\\AppData\\Local\\Temp\\calibre_lhjitq\\trjzwc.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Susan\AppData\Local\Temp\calibre_lhjitq\7dwwcs.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0) (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 200, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Rise Like a Goddess: A Surprise Goddess Cozy Mystery Prequel (Surprise Goddess Mystery Book 0)

**Comment by ElleKayEm** [comment]
If that was downloaded from the website for transfer via USB, then it need to be for an E-ink Kindle (not a Fire) and you need to enter the Kindle's serial number into DeDRM's customization.

**Comment by sgweinst** [comment]
I only have a Fire that my daughter uses. I usually download stuff and read it on my iPad. Sometimes I use the Kindle app on my iPad to read stuff. Most of the books don;t have DRM on them and I can convert them in Calibre without a problem. There are just a few that I have not been able to convert.

**Comment by ElleKayEm** [comment]
If you don't have an E-ink Kindle, then you can download the books with Kindle for PC version 1.24 or earlier.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by bootchan** [comment]
I have an e-ink kindle and I did all the steps. I am also getting the error message that the DRM is not removable.

**Comment by ElleKayEm** [comment]
@bootchan
Start your own issue and post a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
