### ISSUE TITLE
Failed Conversion of Kindle Books From Another Amazon Account Holder

### ISSUE THREAD

**Issue by jinx2019** [apprenticeharper/DeDRM_tools#901]
Hi all! Fair warning that I am very much a novice when it comes to coding, program troubleshooting, and similar. I recently installed Apprentice Harper's (Alf's) DeDRM tool for Calibre, and set out to strip the DRM from books I had legally purchased through Amazon Kindle. I started by downloading the books from Amazon to my desktop in an AZW3 format, then loading them into Calibre. No troubles there, but when I attempted to do the same for my mother (using my computer but a thumb drive full of Kindle books she had downloaded from her own Amazon account) I had no luck with most of them. The only one I could successfully load onto Calibre was a book I suspect is in the public domain. I verified that the books are all purchased - no loaners or KindleUnlimited books. Below I have entered the info I got from Calibre's error log after testing one of the books in Calibre's debug mode - the book was added but still had DRM and could not be opened. Any advice would be much appreciated.

calibre Debug log
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0) && Obok DeDRM (6, 5, 4)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.38] main UI initialized...
[2.38] Hiding splash screen
[52.14] splash screen hidden
[52.14] Started up in 52.14 seconds with 2295 books
stdout+stderr from file dialog helper: ['', '']
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x15\x9fd?\x06\x91\xd3h\x85\xf4]\xbd\x1eE\xe7r|\x92/\xde\x85>&J\x9e9\xa1\x1d\xb3\x10=\x86', 'F:\\Murder by the Book (A Nero Wolfe Mystery 19) (1).azw3']
DeDRM v6.6.3: Trying to decrypt Murder by the Book (A Nero Wolfe Mystery 19) (1).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Murder by the Book (A Nero Wolfe Mystery 19)
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Ellen 2017 New PC\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Ellen 2017 New PC\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1120226647' and UserName '456c6c656e2032303137204e6577205043'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Murder by the Book (A Nero Wolfe Mystery 19)
Got DSN key from database default_key_1
Found 3 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Murder by the Book (A Nero Wolfe Mystery 19) to db in: 1.7
Added 1 books in 3.8 seconds
Worker Launch took: 0.31500005722

**Comment by ElleKayEm** [comment]
For books download from the website, you need to choose an E-ink Kindle for the device (not a Fire) and you need to enter the Kindle's serial number into the DeDRM plugin customization.
