### ISSUE TITLE
ADE default ecryption key not found

### ISSUE THREAD

**Issue by Chesshur** [apprenticeharper/DeDRM_tools#902]
I can no longer remove the drm from any epub files downloaded from either ADE 2.0 or 3.0. I even tried adding a new ADE key and got the following message - "default ecrpyption key not found'. Here is the log from a book that I downloaded with ADE 2.0 authorized under my Adobe ID
calibre Debug log
calibre 3.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && FanFicFare (3, 11, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
calibre 3.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.15+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && FanFicFare (3, 11, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 112.286084142 x 112.110344828
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
FFF: INFO: 2019-09-17 04:48:20,759: calibre_plugins.fanficfare_plugin.prefs(206): Attempting to read settings from predecessor--FFDL
FFF: INFO: 2019-09-17 04:48:20,759: calibre_plugins.fanficfare_plugin.prefs(211): Using default settings
FFF: DEBUG: 2019-09-17 04:48:20,813: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:C:\Users\Shirley Gilbert\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.70] main UI initialized...
[2.70] Hiding splash screen
[15.69] splash screen hidden
[15.69] Started up in 15.69 seconds with 1 books
DeDRM v6.6.3: Trying to decrypt The Victorian Bookshelf.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: The Victorian Bookshelf.epub is a secure Adobe Adept ePub
DeDRM v6.6.3: Trying Encryption key default_key
Could not decrypt efnmuk.epub. Wrong key
DeDRM v6.6.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 349, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 378, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 358, in CryptUnprotectData
ADEPTError: Failed to decrypt user key key (sic)
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 406, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added The Victorian Bookshelf to db in: 1.6
Added 1 books in 2.6 seconds
Exception TypeError: "'NoneType' object is not callable" in <bound method NativeFunction.__del__ of <calibre_plugins.dedrm.adobekey.NativeFunction object at 0x000001C605F50F28>> ignored
Worker Launch took: 0.22000002861
Job: 0 Convert book 1 of 1 (The Victorian Bookshelf) finished
Convert book 1 of 1 (The Victorian Bookshelf)
	Conversion options changed from defaults:
	  output_profile: u'tablet'
	  read_metadata_from_opf: u'C:\\Users\\SHIRLE~1\\AppData\\Local\\Temp\\calibre_ld4hiz\\3tt7fv.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 3.44.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000241B9585048>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x00000241B9585AC8>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\SHIRLE~1\\AppData\\Local\\Temp\\calibre_ld4hiz\\3tt7fv.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\SHIRLE~1\AppData\Local\Temp\calibre_ld4hiz\sz_rtf.epub
	Python function terminated unexpectedly
	  sz_rtf.epub (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 200, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 42, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 27, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: sz_rtf.epub

**Comment by ElleKayEm** [comment]
Try the solution I suggested here:

https://github.com/apprenticeharper/DeDRM_tools/issues/471#issuecomment-378348375
