### ISSUE TITLE
Please Help! I'm An Amateur

### ISSUE THREAD

**Issue by jillgibson** [apprenticeharper/DeDRM_tools#903]
Any help appreciated. The latest version of DeDRM that I can use successfully is 6.5.4. Every other release gives me error messages when I try to decrypt my kindle books. I don't know anything about scripting or codes. I just know that I need help to be able to use the later versions of DeDRM because the earlier versions are 32 bit and I will be upgrading my OS to Catalina and it will require all apps to be 64 bit. I'm attaching the DeDRM log. Thanks in advance for any suggestions and detailed help. Again, I'm an amateur!

macOS Mojave
Version 10.14.6
Safari 13.0

[DeDRM.log](https://github.com/apprenticeharper/DeDRM_tools/files/3655165/DeDRM.log)

**Comment by ElleKayEm** [comment]
Have you looked at this section of the FAQs?

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-macintosh-application

**Comment by jillgibson** [comment]
Yes, I have. None of the suggestions address my issues. I can use any of the 6.5 version tools, no problem, but any of the 6.6 versions I cannot use. I do not use the Calibre plugin. I have the tools icon in my dock, drag the book onto it, and wait for the tools to do their magic. Beyond that, I don't have a clue what to do next to figure out what is causing the hangup with the later versions that are 64 bit. And these are the ones I will be needing once I upgrade my OS to Catalina. 

Thank you for any ideas to help me!

**Comment by jillgibson** [comment]
I decided to try installing the plugin into Calibre and it worked with the 6.6.3 Tools! A few years back I had tried the plugin and had problems with it and haven't attempted it again since, but decided to give it a go again tonight. I was very happy to discover that when I imported a new book into Calibre it automatically dearmed it. I'm super happy about this! If anyone else runs into this issue with the later version of the DeDRM tools, I recommend installing the plugin into Calibre. Worked great for me!

**Comment by ElleKayEm** [comment]
With the stand alone app, you were still getting this error:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-application-opens-but-always-gives-an-error-in-the-log-importerror-no-module-named-cryptocipher

But glad the plugin works for you.

**Comment by jillgibson** [comment]
Thank you for pointing me toward this. I followed the instructions and receive this error:
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-mUcciV/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-YiwuDe/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-mUcciV/pycrypto/

I could never get to the command to "continue." I will paste below the entire terminal window message. I would be really grateful if you could help me figure out what I can do next to use the stand alone app again. Thank you!

Last login: Fri Apr  5 09:12:53 on ttys000
Jills-New-iMac:~ jillgibson$ 
  [Restored Sep 26, 2019 at 8:59:39 AM]
Last login: Thu Sep 26 08:54:35 on console
Jills-New-iMac:~ jillgibson$ sudo python -m pip install pycrypto
Password:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/jillgibson/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/jillgibson/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pycrypto
sh  Downloading https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 450kB 5.7MB/s 
orInstalling collected packages: pycrypto
  Running setup.py install for pycrypto ... t-error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-0gWIMC/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-5aQbxa/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.3-x86_64-2.7
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto
    copying lib/Crypto/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Hash
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Cipher
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/py21compat.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/number.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Util
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/random.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/Fortuna
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Random/OSRNG
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Cipher
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Hash
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Protocol
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/PublicKey
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Util
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/SelfTest/Signature
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Protocol
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/PublicKey
    creating build/lib.macosx-10.3-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.3-x86_64-2.7/Crypto/Signature
    running build_ext
    running build_configure
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/tmp/pip-install-0gWIMC/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-0gWIMC/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-0gWIMC/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-0gWIMC/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-0gWIMC/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-5aQbxa/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-0gWIMC/pycrypto/

**Comment by jillgibson** [comment]
I also noticed in the terminal window something about my python version going to be discontinued in 2020 so I just installed the latest 64 bit python, version 3.7.4. Restarted my computer, ran the terminal window with the commands you suggested, and still get the same error at the end. Failed with error code. It looks like it has something to do with user permissions? I don't know enough to go beyond this point. Thanks again for helping me!

**Comment by ElleKayEm** [comment]
I don't know how to resolve that either.  But FYI, there will be other issues trying to remove DRM on Catalina.  The programs for downloading ebooks which work with DeDRM are also 32-bit:  Kindle for Mac 1.23 (or earlier) and Adobe Digital Editions 2.0.1.

**Comment by jillgibson** [comment]
Thank you for looking it that and helping all you could. Kind of discouraging about future issues with Catalina. I usually download my kindle books directly to my computer from my amazon account and then remove the DRM from there. Do you know if I will still be able to at least do that?

**Comment by ElleKayEm** [comment]
As far as I know, that should still work.

**Comment by ZolaLa9** [comment]
The DeDRM standalone app appears to still have some 32-bit code that will prevent it from running on Catalina. More here: Issue #898 - "MacOS warns DeDRM is 32-bit, will not work with Catalina this fall."

Hopefully the Calibre plugin will continue to work in Catalina and Amazon will continue to offer the direct-download option. 

As EllKayEm notes, Kindle for Mac 1.23.1 and Adobe Digital Editions 2.0.1 will not work with Catalina. There is a [possible workaround for 64-bit Kindle for Mac (1.25+)](https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508), but I haven't seen any reports of it being tested on Catalina yet. ADE 4.x is 64-bit and should work as long as the vendor hasn't turned on the hardened DRM. 

All in all, it's looking kinda dicey for macOS going forward.

**Comment by jillgibson** [comment]
Thanks for the heads up. Hopefully all these apps will catch up to Catalina soon, especially DeDRM!
