### ISSUE TITLE
Calibre DeDrm Issue

### ISSUE THREAD

**Issue by sailormoon82** [apprenticeharper/DeDRM_tools#904]
I was able to dedrm a few days ago, and now it's not working.  I tried reinstalling and that didn't work.  I feel like I'm missing something obvious here...please help...

calibre Debug log
calibre 3.48  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.15+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
calibre 3.48  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.15+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 18, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 18, 0) && KFX metadata reader (from KFX Input) (1, 18, 0) && KFX Input (1, 18, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164557 x 90.1013513514
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[2.75] main UI initialized...
[2.75] Hiding splash screen
[6.42] splash screen hidden
[6.42] Started up in 6.42 seconds with 3 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe0\xaa0\x82\xf0|\xa0\xdf\x11d\rzv\xab\x92E\x06DH\x85\xd3\x9c\x8e\xb2\xbf\x90O\xbfe\x183\xfd', 'C:\\Users\\SNL\\Documents\\My Kindle Content\\B07H724GFW_EBOK']
Gather KFX-ZIP (from KFX Input) 1.18.0: Importing C:\Users\SNL\Documents\My Kindle Content\B07H724GFW_EBOK\B07H724GFW_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 11 file(s) as C:\Users\SNL\AppData\Local\Temp\calibre_gdezy2\rkubjk.kfx-zip
DeDRM v6.6.3: Trying to decrypt rkubjk.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: rkubjk
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c55fc099-af1b-4134-bfc6-68e8eeda70a8.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\SNL\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\SNL\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\SNL\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2828853319' and UserName '75736572'
Decrypted key file using IDString '2828853319' and UserName '75736572'
DeDRM v6.6.3: Found 2 new keys
Decrypting KFX-ZIP ebook: rkubjk
Got DSN key from database default_key_1
Got DSN key from database default_key_2
Found 2 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c55fc099-af1b-4134-bfc6-68e8eeda70a8.voucher
KFX DRM voucher successfully decrypted
DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.18.0: Packaging C:\Users\SNL\AppData\Local\Temp\calibre_gdezy2\rkubjk.kfx-zip
Processing container: B07H724GFW_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07H724GFW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\SNL\AppData\Local\Temp\calibre_gdezy2\wzbqks_add_books\0\B07H724GFW_EBOK.kfx-zip
Added CR!GTKNHNJBBH4Z5D6KM6DNVAQ03HJW.azw to db in: 2.1
Added 1 books in 5.3 seconds

**Comment by sailormoon82** [comment]
It was a KFX issue, resolved with help from #773.
