### ISSUE TITLE
Failed to DeDRM

### ISSUE THREAD

**Issue by caste2015** [apprenticeharper/DeDRM_tools#915]
Below the log:

calibre Debug log
calibre 4.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0)
calibre 4.1 Portable embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 20, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 20, 0) && KFX metadata reader (from KFX Input) (1, 20, 0) && KFX Input (1, 20, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 125.257761733 x 125.046153846
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
[2.17] main UI initialized...
[2.17] Hiding splash screen
[19.89] splash screen hidden
[19.89] Started up in 19.89 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["\xfbU\x8f\xe7\x05\x1c'E\xb0aI\x9f;\xa2M\xe7u\xe9\xc2M*\xd6]B\xec\xac\x10\xe31\xe8\x0c\x80", 'C:\\Users\\XXXX\\Desktop\\B00L2EBDX6_EBOK\\B00L2EBDX6_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.20.0: Importing C:\Users\XXXX\Desktop\B00L2EBDX6_EBOK\B00L2EBDX6_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 14 file(s) as C:\Users\XXXX\AppData\Local\Temp\calibre_bipjse\hyroeq.kfx-zip
DeDRM v6.6.3: Trying to decrypt hyroeq.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: hyroeq
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.59d50e8a-cedf-4fe1-8a67-7d5454bba7b3.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\XXXX\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\XXXX\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1960096248' and UserName '416c6578'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: hyroeq
Got DSN key from database default_key_1
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.59d50e8a-cedf-4fe1-8a67-7d5454bba7b3.voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.20.0: Packaging C:\Users\XXXX\AppData\Local\Temp\calibre_bipjse\hyroeq.kfx-zip
Processing container: B00L2EBDX6_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B00L2EBDX6_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\XXXX\AppData\Local\Temp\calibre_bipjse\nrzyya_add_books\0\B00L2EBDX6_EBOK.kfx-zip
Added Handbook of Toxicology to db in: 0.3
Added 1 books in 2.9 seconds

**Comment by ElleKayEm** [comment]
Go back to Kindle for PC 1.24 or earlier.
