### ISSUE TITLE
DeDRM fail

### ISSUE THREAD

**Issue by Gabomb** [apprenticeharper/DeDRM_tools#916]
calibre Registro de depuración
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
calibre 4.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: DeDRM (6, 6, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.618127786 x 96.5915492958
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
[1.81] main UI initialized...
[1.81] Hiding splash screen
[8.17] splash screen hidden
[8.17] Started up in 8.17 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['^\xc9\x15\xdf\xb8\xac0K\xf4\x0cw\xb3\xfc\xeb&\x84b\x19X\x02\x03Ic\xc2\xf0\xec~E\xd1\xba\x11\x06', 'Z:\\OneDrive\\Libros\\ebookmundo\\El vendedor de silencio (Spanish Edition).azw3']
DeDRM v6.6.1: Trying to decrypt El vendedor de silencio (Spanish Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: El vendedor de silencio (Spanish Edition)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.1: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\SPARTAN PC\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 621, in run
  File "calibre_plugins.dedrm.__init__", line 571, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files (x86)\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added El vendedor de silencio (Spanish Edition) to db in: 0.2
Added 1 books in 0.9 seconds

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the DeDRM plugin customization.

A couple other things: you're not using the latest version of DeDRM which is 6.6.3.  You also might want to use 64-bit calibre.
