### ISSUE TITLE
Unable to remove DRM

### ISSUE THREAD

**Issue by SirSoulBrother** [apprenticeharper/DeDRM_tools#918]
Oct 22, 2019 - Installed your plug-in and unable to remove DRM. Installed newest Calibre after second attempt. Still no luck. Debug log below.

calibre Debug log
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.5518394649 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.34] splash screen shown
[0.34] Initializing db...
[0.34] db initialized
[0.34] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
[10.16] splash screen hidden
[10.16] Started up in 10.16 seconds with 101 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xe4\xd6O?\xbc\xee\xf7*\xc6\xa1\xa8N\xe4tg\x06W\xb4\xc0\\\x8e\xf1\xa5\xe82\xd4 :\xf9\x02\x87p', 'E:\\_Downloads\\_Completed\\jewishjapanesese00doug_encrypted.epub']
DeDRM v6.6.3: Trying to decrypt jewishjapanesese00doug_encrypted.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: “jewishjapanesese00doug_encrypted.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 411, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
Added The Jewish-Japanese sex and cookbook and how to raise wolves to db in: 1.4
Added 1 books in 9.2 seconds

**Comment by ElleKayEm** [comment]
The log says that your book "is neither an Adobe Adept nor a Barnes & Noble encrypted ePub."  Is that true?  Those are the only epub DRMs that DeDRM handles.  There's also the Obok plugin for Kobo epubs.  But if this has some other DRM, these tools won't work.

**Comment by SirSoulBrother** [comment]
The file is an epub from archive.org. I think it's DAISY encrypted.
