### ISSUE TITLE
calibre plugin prevents metadata from being imported

### ISSUE THREAD

**Issue by azurely** [apprenticeharper/DeDRM_tools#92]
This happens consistently with every ebook format I've thrown at it. Strangely, the error only occurs if Calibre is detached from the console.

```
calibre, version 2.54.0, linux, DeDRM (6.4.0)
WARNING: Errors while adding: There were problems adding some files, click "Show details" for more information
----------------------------------------------------------------------
Failed to read metadata from the file(s):
	book.mobi
With error:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/utils/ipc/pool.py", line 363, in worker_main
    result = func(*job.args, **job.kwargs)
  File "/usr/lib/calibre/calibre/ebooks/metadata/worker.py", line 64, in read_metadata
    paths = run_import_plugins(paths, group_id, tdir)
  File "/usr/lib/calibre/calibre/ebooks/metadata/worker.py", line 44, in run_import_plugins
    traceback.print_exc()
  File "/usr/lib/python2.7/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
  File "/usr/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
  File "calibre_plugins.dedrm.__init__", line 91, in write
IOError: [Errno 5] Input/output error
```

**Comment by apprenticeharper** [comment]
My guess would be some kind of file permission error. But which file and where I'm at a loss. This is not a common error (i.e. I don't remember seeing it before), so it's probably something unusual in your system.

**Comment by azurely** [comment]
Enabling it as it needed works for me!

**Comment by apprenticeharper** [comment]
Closing, as this seems to not be a general problem.
