### ISSUE TITLE
I can't remove DMR from kinkle

### ISSUE THREAD

**Issue by cpuentef** [apprenticeharper/DeDRM_tools#924]
I can't remove DMR in a ebook buyed in amazon kindle, using calibre with the plugin DeDMR
The computer is a DELL with a i7

The log created during debugging is the next:

calibre Registro de depuración
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 21, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 21, 0) && KFX metadata reader (from KFX Input) (1, 21, 0) && KFX Input (1, 21, 0)
calibre 4.2 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17134-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 21, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 21, 0) && KFX metadata reader (from KFX Input) (1, 21, 0) && KFX Input (1, 21, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.8113948919 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.64] db initialized
[0.64] Constructing main UI...
[1.56] main UI initialized...
[1.56] Hiding splash screen
[62.92] splash screen hidden
[62.92] Started up in 62.92 seconds with 17 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['^\xef\x07\x95\rJ\xcb\xeb\x9a\xbbs\xfeU\xf2\xeb\xb2\xd1\xe0vl\xff\xca\xb9{\x8f\xeb\xd5\x874\x04\x84z', 'C:\\Users\\Carlos\\Documents\\My Kindle Content\\B07GY2M7JH_EBOK\\B07GY2M7JH_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.21.0: Importing C:\Users\Carlos\Documents\My Kindle Content\B07GY2M7JH_EBOK\B07GY2M7JH_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\ohn5so.kfx-zip
DeDRM v6.6.3: Trying to decrypt ohn5so.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: ohn5so
Got DSN key from database kindlekey1
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.0253f025-eaa5-4124-94ab-d810d9ebcd72.voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Carlos\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Carlos\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '277065053' and UserName '4361726c6f73'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.21.0: Packaging C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\ohn5so.kfx-zip
Processing container: B07GY2M7JH_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container B07GY2M7JH_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\1selxo_add_books\0\B07GY2M7JH_EBOK.kfx-zip
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added The Frequencies of Rifing - From the first frequencies discovered by Royal Rife to today.: Guide to selection and use of Spooky2 frequencies to db in: 1.1
Added 1 books in 2.0 seconds
Worker Launch took: 0.18799996376
Job: 0 Convertido el libro 1 de 1 (The Frequencies of Rifing - From the first frequencies discovered by Royal Rife to today.: Guide to selection and use of Spooky2 frequencies) finished
Convertido el libro 1 de 1 (The Frequencies of Rifing - From the first frequencies discovered by Royal Rife to today.: Guide to selection and use of Spooky2 frequencies)
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  allow_conversion_with_errors: True
	  read_metadata_from_opf: u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\n_rh0u.opf'
	  verbose: 2
	  cover: u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\d7isk8.jpeg'
	  output_profile: u'kindle_fire'
	Resolved conversion options
	calibre version: 4.2.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\d7isk8.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000239B1A183C8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x00000239B1A219C8>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\n_rh0u.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\sreue6.kfx-zip
	Software versions: KFX Input 1.21.0, calibre 4.2 [64bit], Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\sreue6.kfx-zip
	Processing container: B07GY2M7JH_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	  File "calibre_plugins.kfx_input.__init__", line 195, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container B07GY2M7JH_EBOK.azw has DRM and cannot be converted
	P y t h o n   f u n c t i o n   t e r m i n a t e d   u n e x p e c t e d l y 
	 
	     T h i s   b o o k   h a s   D R M !   ( E r r o r   C o d e :   1 ) 
	 
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 103, in convert
	calibre.ebooks.DRMError: This book has DRM!

Worker Launch took: 0.18700003624
Job: 1 Convertido el libro 1 de 1 (The Frequencies of Rifing - From the first frequencies discovered by Royal Rife to today.: Guide to selection and use of Spooky2 frequencies) finished
Convertido el libro 1 de 1 (The Frequencies of Rifing - From the first frequencies discovered by Royal Rife to today.: Guide to selection and use of Spooky2 frequencies)
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  allow_conversion_with_errors: True
	  read_metadata_from_opf: u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\ssnpnk.opf'
	  verbose: 2
	  output_profile: u'kindle_fire'
	  cover: u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\uivuq5.jpeg'
	Resolved conversion options
	calibre version: 4.2.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\uivuq5.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000228DEE4F348>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleFireOutput object at 0x00000228DEE58948>,
	 'page_breaks_before': u'/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Carlos\\AppData\\Local\\Temp\\calibre_my1fai\\ssnpnk.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: KFX Input running
	on C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\rgyguq.kfx-zip
	Software versions: KFX Input 1.21.0, calibre 4.2 [64bit], Windows-10-10.0.17134-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\Carlos\AppData\Local\Temp\calibre_my1fai\rgyguq.kfx-zip
	Processing container: B07GY2M7JH_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 100, in convert
	  File "calibre_plugins.kfx_input.__init__", line 195, in convert_from_kfx
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 106, in convert_to_epub
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
	KFXDRMError: Book container B07GY2M7JH_EBOK.azw has DRM and cannot be converted
	P y t h o n   f u n c t i o n   t e r m i n a t e d   u n e x p e c t e d l y 
	 
	     T h i s   b o o k   h a s   D R M !   ( E r r o r   C o d e :   1 ) 
	 
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 103, in convert
	calibre.ebooks.DRMError: This book has DRM!

Thank you

**Comment by ElleKayEm** [comment]
Try using Kindle for PC 1.24 or earlier.  Link for that version and more info here:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by cpuentef** [comment]
Following your advice I have managed to remove the DMR

Thank you very much

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
