### ISSUE TITLE
Obok error: IOError. No such file or directory

### ISSUE THREAD

**Issue by hub2git** [apprenticeharper/DeDRM_tools#929]
I've successfully used the Obok plugin with other DeDRMed books in the past. but not today.

```
calibre, version 4.2.0
ERROR: Unhandled exception: <b>IOError</b>:[Errno 2] No such file or directory: u'/media/hub2git/KOBOeReader/.kobo/kepub/a5d18df8-f77c-4c78-9fad-02191dcaa4d1'

calibre 4.2  embedded-python: True is64bit: True
Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '4.15.0-66-generic', '#75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 22, 0) && DeDRM (6, 6, 1) && Package KFX (from KFX Input) (1, 22, 0) && Annotations (1, 10, 0) && Find Duplicates (1, 6, 3) && Obok DeDRM (6, 5, 4) && Quality Check (1, 9, 11) && KFX metadata reader (from KFX Input) (1, 22, 0) && KFX Input (1, 22, 0) && KoboTouchExtended (3, 1, 5) && Kobo Utilities (2, 9, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.dialogs", line 272, in do_book_action
  File "calibre_plugins.obok_dedrm.action", line 219, in get_decrypted_kobo_books
  File "calibre_plugins.obok_dedrm.action", line 373, in decryptBook
  File "zipfile.py", line 779, in __init__
IOError: [Errno 2] No such file or directory: u'/media/hub2git/KOBOeReader/.kobo/kepub/a5d18df8-f77c-4c78-9fad-02191dcaa4d1'

```

**Comment by jfines** [comment]
Yep. Me too!

There aren't any detailed instructions that I've found and I'm just trying to make the best use of an ebook I bought - not become a computer engineer! Spent several hours over the last 2 days just trying to figure out what to do (I have a life outside of this). It's been nothing but problems (this is strike 2) since trying to use the plugin. I don't even know if this is the right plugin or not (there seemed to be 2 in the downloaded zip file) - and again - no instructions on installation or use except by others in other places online. DeDRM <-- Welcome to HELL!

**Comment by ElleKayEm** [comment]
What types of books are you trying to decrypt and what versions of programs are you using?

**Comment by jfines** [comment]
@ElleKayEm 

I hope this is appropriate bc I took a long time writing [this](https://www.reddit.com/r/Calibre/comments/1c5q2wn/im_struggling_to_just_get_a_kindle_ebook_saved/) already. It describes everthing real succinctly there at that link. ty

**Comment by ElleKayEm** [comment]
Yeah, Linux and no E-ink Kindle is probably a no go at this point.  At least it is beyond me.  I don't know if you can get either the latest Kindle for PC running under wine or get the key out of it.  No idea what options you have for an Android emulator to get key and books out of an older version of Kindle for Android.

Definitely sounds like not worth the trouble in your situation.  Is the ebook only available on Amazon?

**Comment by jfines** [comment]
Im sorry i ended up just returning the book. I hope im never so stupid to buy another one (but thats just my feeling on it). Really appreciate your response tho.--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 4/16/24, 4:49 PM ElleKayEm ***@***.***> wrote:

   
  Yeah, Linux and no E-ink Kindle is probably a no go at this point. At least it is beyond me. I don't know if you can get either the latest Kindle for PC running under wine or get the key out of it. No idea what options you have for an Android emulator to get key and books out of an older version of Kindle for Android. 
  Definitely sounds like not worth the trouble in your situation. Is the ebook only available on Amazon?

**Comment by ElleKayEm** [comment]
@jfines 

> Im sorry i ended up just returning the book.

Seems like the best choice for you.  At least Amazon is good for that.
