### ISSUE TITLE
Unable To remove DRM

### ISSUE THREAD

**Issue by Ejones786** [apprenticeharper/DeDRM_tools#932]
Hi,
I'm just buy some ebook, and want to convert from EPUB to AWZ3, But it's not working.
There is a Calibre log.

calibre Debug log
calibre 4.3  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.3  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.16] splash screen shown
[1.16] Initializing db...
[1.16] db initialized
[1.16] Constructing main UI...
[2.75] main UI initialized...
[2.75] Hiding splash screen
[12.81] splash screen hidden
[12.81] Started up in 12.81 seconds with 1 books
Worker Launch took: 0.150000095367
Job: 0 Convert book 1 of 1 (เพชรพระอุมา ภาค ๒ ตอนที่ ๖ มงกุฎไพร เล่ม ๔๘) finished
Convert book 1 of 1 (เพชรพระอุมา ภาค ๒ ตอนที่ ๖ มงกุฎไพร เล่ม ๔๘)
	Conversion options changed from defaults:
	  output_profile: u'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\AEC-DE~1\\AppData\\Local\\Temp\\calibre_u6p4wm\\sxw_6j.opf'
	Resolved conversion options
	calibre version: 4.3.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x05351BD0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x05351FD0>,
	 'page_breaks_before': u'/',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\AEC-DE~1\\AppData\\Local\\Temp\\calibre_u6p4wm\\sxw_6j.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on C:\Users\AEC-DE~1\AppData\Local\Temp\calibre_u6p4wm\n62iky.epub
	Python function terminated unexpectedly
	  n62iky.epub (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: n62iky.epub

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre, not during conversion.  Remove the book.  Reopen calibre in debug mode and add the book again.  Post the new log.

You might want to use 64-bit calibre as well.

**Comment by Ejones786** [comment]
There are new log in debug mode.

calibre Debug log
calibre 4.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.3 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
[1.80] main UI initialized...
[1.80] Hiding splash screen
[8.49] splash screen hidden
[8.49] Started up in 8.49 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["9\xfb\xfc\x0b\xa4\x92'\x0f\x15N\x07\xc1\x8c\xd5|%9\xcf#\x90\xce\xbcf\xfe\x9b\xc7\x97Z\xcb\xb2Q\xb8", 'D:\\Nop\\E-Books\\\xe0\xb9\x80\xe0\xb8\x9e\xe0\xb8\x8a\xe0\xb8\xa3\xe0\xb8\x9e\xe0\xb8\xa3\xe0\xb8\xb0\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\xa1\xe0\xb8\xb2 \xe0\xb8\xa0\xe0\xb8\xb2\xe0\xb8\x84 \xe0\xb9\x92 \xe0\xb8\x95\xe0\xb8\xad\xe0\xb8\x99\xe0\xb8\x97\xe0\xb8\xb5\xe0\xb9\x88 \xe0\xb9\x96 \xe0\xb8\xa1\xe0\xb8\x87\xe0\xb8\x81\xe0\xb8\xb8\xe0\xb8\x8e\xe0\xb9\x84\xe0\xb8\x9e\xe0\xb8\xa3 \xe0\xb9\x80\xe0\xb8\xa5\xe0\xb9\x88\xe0\xb8\xa1 \xe0\xb9\x94\xe0\xb9\x98.epub']
DeDRM v6.6.3: Trying to decrypt เน€เธเธเธฃเธเธฃเธฐเธญเธธเธกเธฒ เธ เธฒเธ เน’ เธ•เธญเธเธ—เธตเน เน– เธกเธเธเธธเธเนเธเธฃ เน€เธฅเนเธก เน”เน.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: โ€เน€เธเธเธฃเธเธฃเธฐเธญเธธเธกเธฒ เธ เธฒเธ เน’ เธ•เธญเธเธ—เธตเน เน– เธกเธเธเธธเธเนเธเธฃ เน€เธฅเนเธก เน”เน.epubโ€ is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 411, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Couldn't decrypt after 0.1 seconds. DRM free perhaps?
Added เพชรพระอุมา ภาค ๒ ตอนที่ ๖ มงกุฎไพร เล่ม ๔๘ to db in: 1.6
Added 1 books in 2.2 seconds

**Comment by ElleKayEm** [comment]
Looks like this is not a type of DRM that these tools can remove.  For epubs, Adobe DRM can be removed.  (And with some extra effort Barnes & Noble DRM.)

**Comment by Ejones786** [comment]
This ebook  is a Adobe DRM correctly. seller is recommend to use a ADE 4.5 requirement.

**Comment by ElleKayEm** [comment]
In that case, it may be the hardened Adobe DRM that cannot be removed yet.  You could try opening it with Adobe Digital Editions 2.0.1 authorized with your Adobe ID.

**Comment by Ejones786** [comment]
Ok, I'll try that. Thank you in your advance.
