### ISSUE TITLE
Unable to convert file

### ISSUE THREAD

**Issue by C10H20O** [apprenticeharper/DeDRM_tools#934]
Hello, I bought an e-book on Amazon and wanted to convert it to pdf.
I successfully installed the plugin to remove DRM, and succeeded in importing the e-book on Calibre once the plugin had been installed. However, I cannot convert the book into pdf as Calibre gives me a "failed" message.

I tried to launch Calibre in debug mode, import my e-book and close it again, and here is  the log I get :
calibre Debug log
calibre 4.3  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.3  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.33] splash screen shown
[0.33] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[1.62] main UI initialized...
[1.62] Hiding splash screen
[9.92] splash screen hidden
[9.92] Started up in 9.92 seconds with 9 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 324 '\x01\x00\x00\x00\x0c\x00\x00\x00^\x00\x00\x00P\x001\x00\x00\x00\x00\x00\xd0N<9\x10\x00Books\x00<\x00\t\x00\x04\x00\xef\xbe\xa6N\xf8\x89\xd0N<9.\x00\x00\x00\xd7*\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x96\xe7:\x00B\x00o\x00o\x00k\x00s\x00\x00\x00\x14\x00\x00\x00\xe4\x002\x00|\xc3\t\x00nO\x84\x94 \x00Sword of Destiny_ Witcher 2_ Tales of the Witcher.azw3\x00\x00\x9e\x00\t\x00\x04\x00\xef\xbenO\x84\x94nO\x84\x94.\x00\x00\x00\xc3\xcd\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x93\xf5#\x00S\x00w\x00o\x00r\x00d\x00 \x00o\x00f\x00 \x00D\x00e\x00s\x00t\x00i\x00n\x00y\x00_\x00 \x00W\x00i\x00t\x00c\x00h\x00e\x00r\x00 \x002\x00_\x00 \x00T\x00a\x00l\x00e\x00s\x00 \x00o\x00f\x00 \x00t\x00h\x00e\x00 \x00W\x00i\x00t\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 36888 '`\x00\x00\x00`\x00\x00\x000\x00\x00\x00Y\x00\x00\x00\xce\x14\x05\x89\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragContext" 16 '\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 '\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 '\x01\x00\x00\x00' 

text/uri-list 96 'file:///E:/Bureau/Books/Sword%20of%20Destiny_%20Witcher%202_%20Tales%20of%20the%20Witcher.azw3\r\n' 

application/x-qt-windows-mime;value="FileName" 71 'E:\\Bureau\\Books\\Sword of Destiny_ Witcher 2_ Tales of the Witcher.azw3\x00' 

application/x-qt-windows-mime;value="FileContents" 0 '' 

application/x-qt-windows-mime;value="FileNameW" 142 'E\x00:\x00\\\x00B\x00u\x00r\x00e\x00a\x00u\x00\\\x00B\x00o\x00o\x00k\x00s\x00\\\x00S\x00w\x00o\x00r\x00d\x00 \x00o\x00f\x00 \x00D\x00e\x00s\x00t\x00i\x00n\x00y\x00_\x00 \x00W\x00i\x00t\x00c\x00h\x00e\x00r\x00 \x002\x00_\x00 \x00T\x00a\x00l\x00e\x00s\x00 \x00o\x00f\x00 \x00t\x00h\x00e\x00 \x00W\x00i\x00t\x00c\x00h\x00e\x00r\x00.\x00a\x00z\x00w\x003\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 '\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xdc:a\x1a\x9b\xd5\x01\x00\x00\x00\x00\x00\x00\x00\x00m\xe6\x16a\x1a\x9b\xd5\x01\x00\x00\x00\x00|\xc3\t\x00S\x00w\x00o\x00r\x00d\x00 \x00o\x00f\x00 \x00D\x00e\x00s\x00t\x00i\x00n\x00y\x00_\x00 \x00W\x00i\x00t\x00c\x00h\x00e\x00r\x00 \x002\x00_\x00 \x00T\x00a\x00l\x00e\x00s\x00 \x00o\x00f\x00 \x00t\x00h\x00e\x00 \x00W\x00i\x00t\x00c\x00h\x00e\x00r\x00.\x00a\x00z\x00w\x003\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

Firefox rurl: None None
URLS: [u'file:///E:/Bureau/Books/Sword%20of%20Destiny_%20Witcher%202_%20Tales%20of%20the%20Witcher.azw3']
Paths: [u'E:/Bureau/Books/Sword of Destiny_ Witcher 2_ Tales of the Witcher.azw3']
Extensions: frozenset([u'azw3'])
DeDRM v6.6.3: Trying to decrypt Sword of Destiny_ Witcher 2_ Tales of the Witcher.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Sword of Destiny: Witcher 2: Tales of the Witcher
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\C10\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
E:\Programmes\Calibre\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added Sword of Destiny: Witcher 2: Tales of the Witcher to db in: 1.3
Added 1 books in 2.0 seconds

Here are the details i get when i try to convert it into pdf :   

Convert book 1 of 1 (Sword of Destiny: Witcher 2: Tales of the Witcher)
E:\Programmes\Calibre\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Conversion options changed from defaults:
  pdf_serif_family: u'MS Shell Dlg 2'
  cover: u'C:\\Users\\C10\\AppData\\Local\\Temp\\calibre_3yw7jj\\leuw0a.jpeg'
  read_metadata_from_opf: u'C:\\Users\\C10\\AppData\\Local\\Temp\\calibre_3yw7jj\\l08htp.opf'
  output_profile: u'kindle'
  pdf_sans_family: u'MS Shell Dlg 2'
  verbose: 2
Resolved conversion options
calibre version: 4.3.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\C10\\AppData\\Local\\Temp\\calibre_3yw7jj\\leuw0a.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0526E970>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x0526ECD0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\C10\\AppData\\Local\\Temp\\calibre_3yw7jj\\l08htp.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\C10\AppData\Local\Temp\calibre_3yw7jj\kv5ajs.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  Sword of Destiny: Witcher 2: Tales of the Witcher (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: Sword of Destiny: Witcher 2: Tales of the Witcher

I thank you in advance for your help.

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter its serial number into the DeDRM plugin customization.

**Comment by C10H20O** [comment]
Thank you very much !! <3<3

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
