### ISSUE TITLE
Unable to remove DRM using 6.6.3 Mac Application

### ISSUE THREAD

**Issue by alanbsmithee** [apprenticeharper/DeDRM_tools#935]
There is 1 ebook to be decrypted.
Processing file: B00FVZDZ6K_EBOK.azw
shellcommand: /usr/bin/python '/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' '/Users/unknown/Documents/BOOKS/Books_DRM/B00FVZDZ6K_EBOK.azw' '/Users/unknown/Desktop/' > '/Users/unknown/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
shellcommand: /usr/bin/python '/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/kindlekey.py' '/Users/unknown/Library/Preferences/com.apprenticealf.dedrm/newKeys/' > '/Users/unknown/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: kindlekey.py v2.6
Copyright © 2010-2016 by some_updates, Apprentice Alf and Apprentice Harper
Found k4Mac kinf2011 file: /Users/unknown/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '8d6a4c2ebbca' and UserName 'unknown'
Saved a key to /Users/unknown/Library/Preferences/com.apprenticealf.dedrm/newKeys/kindlekey1.k4i
 
shellcommand: /usr/bin/python '/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/k4mobidedrm.py' -k '/Users/unknown/Library/Preferences/com.apprenticealf.dedrm/KindleKey 4.der' '/Users/unknown/Documents/BOOKS/Books_DRM/B00FVZDZ6K_EBOK.azw' '/Users/unknown/Desktop/' > '/Users/unknown/Library/Preferences/com.apprenticealf.dedrm/DeDRM_temp.log'
shellresult: Using Library AlfCrypto DLL/DYLIB/SO
 Traceback (most recent call last):
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/k4mobidedrm.py", line 94, in <module>
    import kfxdedrm
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/kfxdedrm.py", line 20, in <module>
    import ion
  File "/private/var/folders/hm/tbt5vf5168j71zpsf17dmwb40000gn/T/AppTranslocation/F9638090-F5B0-43AF-B59F-CA8ED3A88C12/d/DeDRM.app/Contents/Resources/ion.py", line 20, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
There was an error with 1 ebook:
B00FVZDZ6K_EBOK.azw couldn't be decrypted.

**Comment by ElleKayEm** [comment]
See this section of the FAQs:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#the-application-opens-but-always-gives-an-error-in-the-log-importerror-no-module-named-cryptocipher
