### ISSUE TITLE
Cannot convert to EPUB

### ISSUE THREAD

**Issue by mpaezt** [apprenticeharper/DeDRM_tools#936]
Hi, after I opened the azw book in calibre, it looks fine but if I want to convert it to EPUB (or any other format), calibre shows a message error "This book has DRM, cannot convert <book>". I bought this book in amazon and was send to my Kindle app on mac with Catalina.

Here is the log:

calibre Debug log
calibre 4.2  embedded-python: True is64bit: True
Darwin-19.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.0.0', 'Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.1', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 21, 0) && DeDRM (6, 6, 3) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 1) && Package KFX (from KFX Input) (1, 21, 0) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 21, 0) && KFX Input (1, 21, 0) && Inept PDF DeDRM (0, 1, 4) && eReader PDB 2 PML (0, 0, 5) && Ignoble Epub DeDRM (0, 1, 6)
calibre 4.2  embedded-python: True is64bit: True
Darwin-19.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.0.0', 'Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.1', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 21, 0) && DeDRM (6, 6, 3) && K4PC, K4Mac, Kindle Mobi and Topaz DeDRM (0, 3, 1) && Package KFX (from KFX Input) (1, 21, 0) && Inept Epub DeDRM (0, 1, 7) && KFX metadata reader (from KFX Input) (1, 21, 0) && KFX Input (1, 21, 0) && Inept PDF DeDRM (0, 1, 4) && eReader PDB 2 PML (0, 0, 5) && Ignoble Epub DeDRM (0, 1, 6)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[1.42] main UI initialized...
[1.42] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 1.21.0: Importing /Users/mpaez/Documents/Box Sync/Desktop/Books/B07XF1WB1Q_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
[18.81] splash screen hidden
[18.81] Started up in 18.81 seconds with 201 books
DeDRM v6.6.3: Trying to decrypt B07XF1WB1Q_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Vizcarra, una breve historia de lealtad y traición (Spanish Edition)
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin K4PC, K4Mac, Kindle Mobi and Topaz DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.k4mobidedrm.__init__", line 89, in run
ImportError: No module named PyQt4.Qt
 is not a valid Kindle serial number or PID.
K4MobiDeDRM: Calibre configuration directory = /Users/mpaez/Library/Preferences/calibre
MOBI header version = 8, length = 264
Extra Data Flags = 3
No kindle-info files have been found.
Crypto Type is:  2
Added Vizcarra, una breve historia de lealtad y traición (Spanish Edition) to db in: 0.0
Added 1 books in 2.9 seconds

Thank you in advance!

**Comment by ElleKayEm** [comment]
You may have trouble getting this to work if you're already on Catalina.  I'm not familiar with this myself, but I believe info about getting Kindle books you can DeDRM from Kindle for Mac is here:

https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by mpaezt** [comment]
Yes, I followed the steps and the book opened in calibre to read but if I want to convert it to EPUB, the error message is shown.

**Comment by ZolaLa9** [comment]
You can read the book in Calibre? If so, then the book doesn't have DRM, which is odd because the DeDRM log you posted suggests it does.

**Comment by ElleKayEm** [comment]
As Zola said, if you can actually read the book in the calibre ebook viewer, then it's DRM-free.  But just seeing it in your calibre library doesn't mean it is.

You can also remove all the old individual file-type DeDRM plugins.  They are all replaced by DeDRM 6.6.3.

**Comment by mpaezt** [comment]
I removed the old individual file-type DeDRM plugins, I got the same error. Any other ideas? Thank you!

**Comment by ElleKayEm** [comment]
Did you have DeDRM working with Kindle for Mac before updating to Catalina?  Or do you have access to a Mac not on Catalina?  Or a Windows machine?

**Comment by mpaezt** [comment]
Well, I updated to Catalina without knowing that it would give problems. So, I installed old versions of kindle app and calibre for windows on the VM installed on my mac and all worked like a charm. I guess that for mac I will have to wait for a new DeDRM version. Thank you all for the help!

**Comment by ElleKayEm** [comment]
Glad you figured out a workaround for now.
