### ISSUE TITLE
Cannot remove DRM on Mac

### ISSUE THREAD

**Issue by spacequeer** [apprenticeharper/DeDRM_tools#938]
I cannot remove the DRM on any of my Adobe books when they've worked fine before.

FFF: DEBUG: 2019-11-20 21:54:47,950: calibre_plugins.fanficfare_plugin.fff_plugin(207): Plugin FanFicFare macmenuhack file_path:/Users/nitatyndall/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 4.3  embedded-python: True is64bit: True
Darwin-19.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.0.0', 'Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Barnes & Noble (1, 2, 15) && FanFicFare (3, 10, 5)
calibre 4.3  embedded-python: True is64bit: True
Darwin-19.0.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.0.0', 'Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Barnes & Noble (1, 2, 15) && FanFicFare (3, 10, 5)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 108.50000163
Using calibre Qt style: False
[0.00] Starting up...
[0.02] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
Using proxies: {'http': '127.0.0.1:7769', 'https': '127.0.0.1:7769'}
Using proxies: {'http': '127.0.0.1:7769', 'https': '127.0.0.1:7769'}
[1.49] main UI initialized...
[1.49] Started up in 1.49 seconds with 212 books
Worker Launch took: 0.0665619373322
Job: 0 Convert book 1 of 1 (I Killed Zoe Spanos) finished
Convert book 1 of 1 (I Killed Zoe Spanos)
	Conversion options changed from defaults:
	  output_profile: u'nook'
	  read_metadata_from_opf: u'/var/folders/vt/pl_83zk14vvbrvr8h83ypxpw0000gn/C/calibre_4.3.0_tmp_SFBGT8/JnBtiR.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.3.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10acf02d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.NookOutput object at 0x10acf0c10>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/vt/pl_83zk14vvbrvr8h83ypxpw0000gn/C/calibre_4.3.0_tmp_SFBGT8/JnBtiR.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: EPUB Input running
	on /var/folders/vt/pl_83zk14vvbrvr8h83ypxpw0000gn/C/calibre_4.3.0_tmp_SFBGT8/lMJxpl.epub
	Python function terminated unexpectedly: lMJxpl.epub
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 163, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 208, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
	calibre.ebooks.DRMError: lMJxpl.epub

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add the book to calibre, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that
