### ISSUE TITLE
Nook book DRM problem (windows 10)

### ISSUE THREAD

**Issue by Sogl** [apprenticeharper/DeDRM_tools#939]
Log:
```
calibre Журнал ошибок
calibre 4.4  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
calibre 4.4  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 144.78 x 143.792222222
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.47] splash screen shown
[0.47] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.14] main UI initialized...
[2.14] Hiding splash screen
[9.34] splash screen hidden
[9.34] Started up in 9.34 seconds with 0 books
DeDRM v6.6.3: Trying to decrypt 9782923364759.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: вЂњ9782923364759.epubвЂќ is a secure Barnes & Noble ePub
DeDRM v6.6.3: Trying Encryption key nook key(mymail@mail.com)
Could not decrypt qsxjza.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 182, in __init__
  File "site-packages\Crypto\Cipher\AES.py", line 95, in new
  File "site-packages\Crypto\Cipher\AES.py", line 59, in __init__
  File "site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
ValueError: Key cannot be the null string

DeDRM v6.6.3: Failed to decrypt with key nook key(artyomXX@inbox.ru) after 0.2 seconds
DeDRM v6.6.3: Looking for new NOOK Study Keys after 0.2 seconds
Found nookStudy log file: C:\Users\artyom\AppData\Roaming\Barnes & Noble\NOOKstudy\logs\BNClientLog.txt
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 304, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added mybook to db in: 0.2
Added 1 books in 1.7 seconds

```

**Comment by ElleKayEm** [comment]
How did you get your key?

**Comment by Sogl** [comment]
Epubor support generate it for me using my NOOK credentials.

**Comment by ElleKayEm** [comment]
Does it work with Epubor's software?

**Comment by Sogl** [comment]
Nope. I'm trying to figure out with Epubor support. 

Do you think the problem is in the key?

**Comment by ElleKayEm** [comment]
Well, it's not the right one for that book.

If they used something like the method described in issue #814 to retrieve your key, then it might only work on books downloaded via Nook for Android.  In many cases, a Nook account will only have one key, but some people have reported that different apps or devices used a different key even on the same account.

**Comment by Sogl** [comment]
Solved. My key was wrong, I got it using Android Emulator  😉

**Comment by ElleKayEm** [comment]
Glad you got it sorted.  The Apprentices always decline donations for this project.
