### ISSUE TITLE
DeDRM error from AZW to epub 

### ISSUE THREAD

**Issue by issei42700** [apprenticeharper/DeDRM_tools#942]
Conversion du livre 1 sur 1 (Psycho Bank T01 (French Edition))
Conversion options changed from defaults:
  read_metadata_from_opf: u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_jyde_k\\03fsjx.opf'
  cover: u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_jyde_k\\twyzfa.jpeg'
  output_profile: u'generic_eink'
  verbose: 2
Resolved conversion options
calibre version: 4.5.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_jyde_k\\twyzfa.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001FCF7DC16C8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001FCF7F3B308>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_jyde_k\\03fsjx.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\bleac\AppData\Local\Temp\calibre_jyde_k\g20yxj.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly
  Psycho Bank T01 (French Edition) (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
calibre.ebooks.DRMError: Psycho Bank T01 (French Edition)

calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 24, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 24, 0) && KFX Input (1, 24, 0)
USB devices on system:
(USBDevice(vendor_id=0x8087 product_id=0x7dc bcd=0x1 devid=usb\vid_8087&pid_07dc&rev_0001 devinst=1),
 USBDevice(vendor_id=0x8087 product_id=0x8000 bcd=0x5 devid=usb\vid_8087&pid_8000&rev_0005 devinst=2),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub30&vid8086&pid8c31&rev0005 devinst=3),
 USBDevice(vendor_id=0x258a product_id=0x1007 bcd=0x100 devid=usb\vid_258a&pid_1007&rev_0100&mi_00 devinst=4),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub20&vid8086&pid8c26&rev0005 devinst=5),
 USBDevice(vendor_id=0x8087 product_id=0x8008 bcd=0x5 devid=usb\vid_8087&pid_8008&rev_0005 devinst=6),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub20&vid8086&pid8c2d&rev0005 devinst=7),
 USBDevice(vendor_id=0x258a product_id=0x1007 bcd=0x100 devid=usb\vid_258a&pid_1007&rev_0100&mi_01 devinst=8),
 USBDevice(vendor_id=0x258a product_id=0x1007 bcd=0x100 devid=usb\vid_258a&pid_1007&rev_0100 devinst=9),
 USBDevice(vendor_id=0x1770 product_id=0xff00 bcd=0x110 devid=usb\vid_1770&pid_ff00&rev_0110 devinst=10))

No disabled plugins
Looking for devices of type: MTP_DEVICE
The Windows WPD service says there are no portable devices connected

aider moi s'il vous plait j'ai gros probleme

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Here's how to get the log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by issei42700** [comment]
Je lai fait plusieurs fois j'ai ajouter le livre pour la première fois

**Comment by ElleKayEm** [comment]
So what is your question here?  This log doesn't show any attempt at DRM removal.

**Comment by issei42700** [comment]
the problem is before it works well but i had a problem i get everything everything removes i install drm but i think its must python i do not know which version the ddrm i took last ( ddrm error )

**Comment by ElleKayEm** [comment]
Remove the DRMed book from calibre. Click the Preferences drop-down menu and choose 'Restart in debug mode'. Once calibre has re-started, import the problem ebook. Now close calibre. A log will appear that you can copy and paste here.

**Comment by issei42700** [comment]
voila
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 24, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 24, 0) && KFX Input (1, 24, 0)
calibre 4.5 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 24, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 24, 0) && KFX metadata reader (from KFX Input) (1, 24, 0) && KFX Input (1, 24, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 128.0 x 128.186915888
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.69] splash screen shown
[1.69] Initializing db...
[1.70] db initialized
[1.70] Constructing main UI...
[4.08] main UI initialized...
[4.08] Hiding splash screen
[25.80] splash screen hidden
[25.80] Started up in 25.80 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x13Fc\xafDd\xd5\xc9jq\x9f\x833\xb1jE#~\x04L4\x1c\xf8Xtup\xbdI|\xc8;', 'C:\\Users\\bleac\\OneDrive\\Bureau\\B07NWY233M_EBOK\\B07NWY233M_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.24.0: Importing C:\Users\bleac\OneDrive\Bureau\B07NWY233M_EBOK\B07NWY233M_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B07NWY233M_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Psycho Bank T01 (French Edition)
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\bleac\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\bleac\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1479851786' and UserName '626c656163'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright Â© 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Psycho Bank T01 (French Edition)
Got DSN key from database default_key_1
Found 3 keys to try after 0.9 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Psycho Bank T01 (French Edition) to db in: 0.8
Added 1 books in 3.7 seconds
Worker Launch took: 0.694999933243
Job: 0 Conversion du livre 1 sur 1 (Psycho Bank T01 (French Edition)) finished
Conversion du livre 1 sur 1 (Psycho Bank T01 (French Edition))
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_ow4xvx\\snozls.opf'
	  cover: u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_ow4xvx\\fb23s4.jpeg'
	  output_profile: u'generic_eink'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.5.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_ow4xvx\\fb23s4.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000225964B5848>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x00000225964BD488>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\bleac\\AppData\\Local\\Temp\\calibre_ow4xvx\\snozls.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'template_css': None,
	 'template_html': None,
	 'template_html_index': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\bleac\AppData\Local\Temp\calibre_ow4xvx\i_hqge.azw
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  Psycho Bank T01 (French Edition) (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Psycho Bank T01 (French Edition)

**Comment by ElleKayEm** [comment]
You need to use Kindle for PC 1.24 or earlier.  Link and more information in this post:

https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by issei42700** [comment]
but it is file marchais a week ago more I kindle my account has been deleted and I just take a book on the other account amazon its mean the other books squeeze me ah nothing?

**Comment by ElleKayEm** [comment]
Sorry, I don't understand.

**Comment by issei42700** [comment]
sorry I meant it's azw files from my external hard drive it works 1 week I do not account anymore amazon I lost but books its mean?

**Comment by ElleKayEm** [comment]
You no longer have the Amazon account that these books were purchased from?  You cannot download new copies?  If so, then you will not be able to remove the DRM.

**Comment by issei42700** [comment]
yes the problem is that it's even file walk and I managed to break drm and no I do not know who had

**Comment by ElleKayEm** [comment]
For DeDRM to work, you need to download the book with Kindle for PC version 1.24 or earlier.  Kindle for PC needs to be installed on the same PC and under the same Windows user as calibre with the DeDRM plugin.

**Comment by issei42700** [comment]
it was all file I had it on previous version and it still works
and must have python problem I tell you I arrived ah read without kindle since my account was deleted
