### ISSUE TITLE
Unable to remove DRM from .azw file (Mac)

### ISSUE THREAD

**Issue by danielacoder** [apprenticeharper/DeDRM_tools#949]
I have installed and uninstalled kindle, uninstalled and reinstalled calibre, and found the key for the DeDRM tool. However, when I try to open or convert the book after reuploading it to Calibre, I still get the message that the book is DRM-protected.
I have used the debug version of calibre to get this message:

calibre Debug log
calibre 4.5  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.5  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.500001705 x 113.500001705
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
[1.40] main UI initialized...
[1.40] Hiding splash screen
DeDRM v6.6.3: Trying to decrypt BOOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: BOOK
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2011 file: /Users/USER/Library/Application Support/Kindle/storage/.kinf2011
Decrypted key file using IDString '053c3ebdafbc' and UserName 'danielchan'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[7.18] splash screen hidden
[7.18] Started up in 7.18 seconds with 1 books
Added BOOK to db in: 0.0
Added 1 books in 1.0 seconds

What should I do? Thanks.

**Comment by ElleKayEm** [comment]
Not really seeing anything in particular here.  Can only figure the uninstalling and reinstalling of Kindle for Mac has left some piece of a previous installation.  What version of K4Mac are you using?  And what do you mean by "found the key for the DeDRM tool"?

**Comment by danielacoder** [comment]
I am using version 1.23.1 of Kindle for Mac. On a newer version of K4Mac, the plugin couldn't find the default key for "Kindle for Mac/PC ebooks" when I clicked through the menus (preferences, plugins, file-type plugins, deDRM) until I deregistered and uninstalled and then redownloaded and reregistered Kindle for Mac.

One more question, though... is it possible for a .azw file to be a .kfx file in disguise? When I ripped the book files from the Application Support library and I tried to open it in calibre, I got this error message. The last statement is confusing but seems to imply that the book is actually a .kfx file.

calibre, version 4.5.0
ERROR: Loading book failed: Failed to open the book at /Users/USER/Calibre Library/Unknown/B01G61W9EQ EBOK (13)/B01G61W9EQ EBOK - Unknown.azw. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages/calibre/gui2/viewer/ui.py", line 360, in _load_ebook_worker
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 231, in prepare_book
  File "site-packages/calibre/gui2/viewer/convert_book.py", line 188, in do_convert
ConversionFailure: Failed to convert book: /Users/danielchan/Calibre Library/Unknown/B01G61W9EQ EBOK (13)/B01G61W9EQ EBOK - Unknown.azw with error:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 285, in get_metadata
  File "site-packages/calibre/ebooks/metadata/mobi.py", line 498, in get_metadata
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 293, in __init__
  File "site-packages/calibre/ebooks/mobi/reader/headers.py", line 321, in identity
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
InputFormatPlugin: MOBI Input running
on /Users/USER/Calibre Library/Unknown/B01G61W9EQ EBOK (13)/B01G61W9EQ EBOK - Unknown.azw
Python function terminated unexpectedly: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 163, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 189, in main
  File "<string>", line 1, in <module>
  File "site-packages/calibre/srv/render_book.py", line 830, in viewer_main
  File "site-packages/calibre/srv/render_book.py", line 823, in render_for_viewer
  File "site-packages/calibre/srv/render_book.py", line 798, in render
  File "site-packages/calibre/ebooks/oeb/iterator/book.py", line 64, in extract_book
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 37, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 85, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

**Comment by ElleKayEm** [comment]
Did you redownload your books after reinstalling Kindle for Mac?  Kindle for Mac (and PC) give all book files the generic AZW extension, no matter what the underlying format is.  You can turn off the ability for Kindle for Mac to download KFX files.  Or you can install the KFX Input plugin to deal with them.  See the MobileRead link in the log for details.
