### ISSUE TITLE
CloudLibrary epub fails with DRMError: KWAx7C.epub

### ISSUE THREAD

**Issue by EthanDF** [apprenticeharper/DeDRM_tools#954]
I'm trying to remove the DRM from ebooks downloaded from CloudLibrary (fka 3M books) so that I can convert them from epub to MOBI to read on my Kindle.

I had to install the CloudLibrary app on my Pixel 2 (android).
Download the book
Find the epub in storage and upload to Google Drive
Download the epub onto my Mac
Import into Calibre.

However, when I try to convert, it fails. The log is attached. I tried adding some key information but that didn't help.

calibre Debug log

> calibre 4.6  embedded-python: True is64bit: True
> Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
> Python 2.7.16
> OSX: ('10.14.6', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0)
> calibre 4.6  embedded-python: True is64bit: True
> Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
> ('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
> Python 2.7.16
> OSX: ('10.14.6', ('', '', ''), 'x86_64')
> Interface language: None
> Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0)
> devicePixelRatio: 2.0
> logicalDpi: 72.0 x 72.0
> physicalDpi: 110.50000166 x 110.50000166
> Using calibre Qt style: True
> [0.00] Starting up...
> [0.03] Showing splash screen...
> [0.27] splash screen shown
> [0.27] Initializing db...
> [0.28] db initialized
> [0.28] Constructing main UI...
> [1.45] main UI initialized...
> [1.45] Hiding splash screen
> objc[45811]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffb25103d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x118d6af50). One of the two will be used. Which one is undefined.
> DeDRM v6.6.3: Trying to decrypt Mort.epub
> DeDRM v6.6.3: Verifying zip archive integrity
> DeDRM v6.6.3: Mort.epub is a secure Adobe Adept ePub
> DeDRM v6.6.3: Trying Encryption key default_key
> Could not decrypt XBDyqV.epub. Wrong key
> DeDRM v6.6.3: Failed to decrypt with key default_key after 0.1 seconds
> DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
> DeDRM v6.6.3: Exception when getting default Adobe Key after 0.3 seconds
> Traceback (most recent call last):
>   File "calibre_plugins.dedrm.__init__", line 349, in ePubDecrypt
>   File "calibre_plugins.dedrm.adobekey", line 451, in adeptkeys
> AttributeError: 'NoneType' object has no attribute 'decode'
> DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> Running file type plugin DeDRM failed with traceback:
> Traceback (most recent call last):
>   File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
>   File "calibre_plugins.dedrm.__init__", line 635, in run
>   File "calibre_plugins.dedrm.__init__", line 406, in ePubDecrypt
> DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
> [8.92] splash screen hidden
> [8.92] Started up in 8.92 seconds with 14 books
> Added Mort to db in: 0.0
> Added 1 books in 0.9 seconds
> Worker Launch took: 0.121606826782
> Job: 0 Convert book 1 of 1 (Mort) finished
> Convert book 1 of 1 (Mort)
> 	Conversion options changed from defaults:
> 	  read_metadata_from_opf: u'/var/folders/ly/ydsc25ns4dvf06gw8rc8jn_d3b8nf1/C/calibre_4.6.0_tmp_gePUPW/LL1OjT.opf'
> 	  output_profile: u'kindle_pw3'
> 	  verbose: 2
> 	Resolved conversion options
> 	calibre version: 4.6.0
> 	{'asciiize': False,
> 	 'author_sort': None,
> 	 'authors': None,
> 	 'base_font_size': 0.0,
> 	 'book_producer': None,
> 	 'change_justification': u'original',
> 	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
> 	 'chapter_mark': u'pagebreak',
> 	 'comments': None,
> 	 'cover': None,
> 	 'debug_pipeline': None,
> 	 'dehyphenate': True,
> 	 'delete_blank_paragraphs': True,
> 	 'disable_font_rescaling': False,
> 	 'dont_compress': False,
> 	 'duplicate_links_in_toc': False,
> 	 'embed_all_fonts': False,
> 	 'embed_font_family': None,
> 	 'enable_heuristics': False,
> 	 'expand_css': False,
> 	 'extra_css': None,
> 	 'extract_to': None,
> 	 'filter_css': u'',
> 	 'fix_indents': True,
> 	 'font_size_mapping': None,
> 	 'format_scene_breaks': True,
> 	 'html_unwrap_factor': 0.4,
> 	 'input_encoding': None,
> 	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1121804d0>,
> 	 'insert_blank_line': False,
> 	 'insert_blank_line_size': 0.5,
> 	 'insert_metadata': False,
> 	 'isbn': None,
> 	 'italicize_common_cases': True,
> 	 'keep_ligatures': False,
> 	 'language': None,
> 	 'level1_toc': None,
> 	 'level2_toc': None,
> 	 'level3_toc': None,
> 	 'line_height': 0.0,
> 	 'linearize_tables': False,
> 	 'margin_bottom': 5.0,
> 	 'margin_left': 5.0,
> 	 'margin_right': 5.0,
> 	 'margin_top': 5.0,
> 	 'markup_chapter_headings': True,
> 	 'max_toc_links': 50,
> 	 'minimum_line_height': 120.0,
> 	 'mobi_file_type': u'old',
> 	 'mobi_ignore_margins': False,
> 	 'mobi_keep_original_images': False,
> 	 'mobi_toc_at_start': False,
> 	 'no_chapters_in_toc': False,
> 	 'no_inline_navbars': True,
> 	 'no_inline_toc': False,
> 	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x112180cd0>,
> 	 'page_breaks_before': u'/',
> 	 'personal_doc': u'[PDOC]',
> 	 'prefer_author_sort': False,
> 	 'prefer_metadata_cover': False,
> 	 'pretty_print': False,
> 	 'pubdate': None,
> 	 'publisher': None,
> 	 'rating': None,
> 	 'read_metadata_from_opf': u'/var/folders/ly/ydsc25ns4dvf06gw8rc8jn_d3b8nf1/C/calibre_4.6.0_tmp_gePUPW/LL1OjT.opf',
> 	 'remove_fake_margins': True,
> 	 'remove_first_image': False,
> 	 'remove_paragraph_spacing': False,
> 	 'remove_paragraph_spacing_indent_size': 1.5,
> 	 'renumber_headings': True,
> 	 'replace_scene_breaks': u'',
> 	 'search_replace': '[]',
> 	 'series': None,
> 	 'series_index': None,
> 	 'share_not_sync': False,
> 	 'smarten_punctuation': False,
> 	 'sr1_replace': None,
> 	 'sr1_search': None,
> 	 'sr2_replace': None,
> 	 'sr2_search': None,
> 	 'sr3_replace': None,
> 	 'sr3_search': None,
> 	 'start_reading_at': None,
> 	 'subset_embedded_fonts': False,
> 	 'tags': None,
> 	 'timestamp': None,
> 	 'title': None,
> 	 'title_sort': None,
> 	 'toc_filter': None,
> 	 'toc_threshold': 6,
> 	 'toc_title': None,
> 	 'transform_css_rules': '[]',
> 	 'unsmarten_punctuation': False,
> 	 'unwrap_lines': True,
> 	 'use_auto_toc': False,
> 	 'verbose': 2}
> 	InputFormatPlugin: EPUB Input running
> 	on /var/folders/ly/ydsc25ns4dvf06gw8rc8jn_d3b8nf1/C/calibre_4.6.0_tmp_gePUPW/KWAx7C.epub
> 	Python function terminated unexpectedly: KWAx7C.epub
> 	Traceback (most recent call last):
> 	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 163, in main
> 	    return run_entry_point()
> 	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
> 	    return getattr(pmod, func)()
> 	  File "site-packages/calibre/utils/ipc/worker.py", line 208, in main
> 	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
> 	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
> 	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
> 	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
> 	  File "site-packages/calibre/ebooks/conversion/plugins/epub_input.py", line 290, in convert
> 	calibre.ebooks.DRMError: KWAx7C.epub

**Comment by ElleKayEm** [comment]
These tools are intended for books you've purchased.
