### ISSUE TITLE
OBOK plugin formatting issue

### ISSUE THREAD

**Issue by idlelane** [apprenticeharper/DeDRM_tools#958]
Hi, I'm attempting to strip Kobo DRM, but the formatting ends up all wonky. The book is a guitar tab book with a mixture of graphics and text. Stripping DRM seems to work fine:

```calibre Debug log
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3) && Obok DeDRM (6, 5, 4)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 155.312101911 x 145.142857143
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.44] splash screen shown
[1.44] Initializing db...
[1.78] db initialized
[1.78] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[4.02] main UI initialized...
[4.02] Hiding splash screen
[10.53] splash screen hidden
[10.53] Started up in 10.53 seconds with 2817 books
Running Obok DeDRM v6.5.4
DEBUG:   29.7 didn't find device
Obok v3.2.4
Copyright © 2012-2016 Physisticated et al.
c:\users\appdata\local\temp\tmpc86a39
DEBUG:   29.7 got kobodir C:\Users\AppData\Local\Kobo\Kobo Desktop Edition
Found 36 possible keys to try.
DEBUG:   34.0 BookListTableWidget:get_books - book_num: 0
DEBUG:   34.0 BookListTableWidget:get_books - book: Justin Guitar: Christmas Songbook
DEBUG:   34.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v6.5.4 - Decrypting Justin Guitar: Christmas Songbook
Trying key:  9c991a0d7602078e10a1896d190cd48b
Checking text:<?xml vers:
Perhaps utf-8 without BOM
Seems to be good text
Success!
DEBUG:   35.5 DecryptAddProgressDialog::do_book_action - decrypted book: 'Justin Guitar: Christmas Songbook'
Obok DeDRM v6.5.4 - Added Justin Guitar: Christmas Songbook
Obok DeDRM v6.5.4 - wrapping up results.
```

However, conversion to PDF then fails: 
```Convert book 1 of 1 (Justin Guitar: Christmas Songbook)
Conversion options changed from defaults:
  pdf_mono_family: u'Liberation Mono'
  cover: u'C:\\Users\\AppData\\Local\\Temp\\calibre_yz_llx\\l0dkqj.jpeg'
  read_metadata_from_opf: u'C:\\Users\\AppData\\Local\\Temp\\calibre_yz_llx\\jvtbm6.opf'
  output_profile: u'kindle_pw3'
  pdf_sans_family: u'Liberation Sans'
  pdf_serif_family: u'Liberation Serif'
  verbose: 2
Resolved conversion options
calibre version: 4.6.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\AppData\\Local\\Temp\\calibre_yz_llx\\l0dkqj.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001D51AC0C4C8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000001D51AC15D08>,
 'page_breaks_before': u'/',
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Liberation Mono',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Liberation Sans',
 'pdf_serif_family': u'Liberation Serif',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\AppData\\Local\\Temp\\calibre_yz_llx\\jvtbm6.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: EPUB Input running
on C:\Users\AppData\Local\Temp\calibre_yz_llx\kovbvd.epub
Found HTML cover OEBPS/cover.xhtml
Parsing all content...
Parsing OEBPS/page092.xhtml ...
Parsing OEBPS/page018.xhtml ...
Parsing OEBPS/page094.xhtml ...
Parsing OEBPS/page058.xhtml ...
Parsing OEBPS/page089.xhtml ...
Parsing OEBPS/page096.xhtml ...
Parsing OEBPS/page011.xhtml ...
Parsing OEBPS/empty.xhtml ...
Parsing OEBPS/page002.xhtml ...
Parsing OEBPS/page047.xhtml ...
Parsing OEBPS/page020.xhtml ...
Parsing OEBPS/page004.xhtml ...
Parsing OEBPS/page008.xhtml ...
Parsing OEBPS/page006.xhtml ...
Parsing OEBPS/page016.xhtml ...
Parsing OEBPS/page003.xhtml ...
Parsing OEBPS/page024.xhtml ...
Parsing OEBPS/page098.xhtml ...
Parsing OEBPS/nav.xhtml ...
Parsing OEBPS/page005.xhtml ...
Parsing OEBPS/page036.xhtml ...
Parsing OEBPS/page028.xhtml ...
Parsing OEBPS/page082.xhtml ...
Parsing OEBPS/page012.xhtml ...
Parsing OEBPS/page061.xhtml ...
Parsing OEBPS/page030.xhtml ...
Parsing OEBPS/page013.xhtml ...
Parsing OEBPS/page063.xhtml ...
Parsing OEBPS/page032.xhtml ...
Parsing OEBPS/page065.xhtml ...
Parsing OEBPS/page034.xhtml ...
Parsing OEBPS/page067.xhtml ...
Parsing OEBPS/page069.xhtml ...
Parsing OEBPS/page038.xhtml ...
Parsing OEBPS/page026.xhtml ...
Parsing OEBPS/page071.xhtml ...
Parsing OEBPS/page040.xhtml ...
Parsing OEBPS/page073.xhtml ...
Parsing OEBPS/page007.xhtml ...
Parsing OEBPS/page075.xhtml ...
Parsing OEBPS/page044.xhtml ...
Parsing OEBPS/page077.xhtml ...
Parsing OEBPS/page060.xhtml ...
Parsing OEBPS/page046.xhtml ...
Parsing OEBPS/page042.xhtml ...
Parsing OEBPS/page079.xhtml ...
Parsing OEBPS/page048.xhtml ...
Parsing OEBPS/page055.xhtml ...
Parsing OEBPS/page056.xhtml ...
Parsing OEBPS/page081.xhtml ...
Parsing OEBPS/page050.xhtml ...
Parsing OEBPS/page083.xhtml ...
Parsing OEBPS/page053.xhtml ...
Parsing OEBPS/page085.xhtml ...
Parsing OEBPS/page054.xhtml ...
Parsing OEBPS/page087.xhtml ...
Parsing OEBPS/page017.xhtml ...
Parsing OEBPS/page091.xhtml ...
Parsing OEBPS/page093.xhtml ...
Parsing OEBPS/page095.xhtml ...
Parsing OEBPS/page033.xhtml ...
Parsing OEBPS/page097.xhtml ...
Parsing OEBPS/fixed.css ...
Parsing OEBPS/page021.xhtml ...
Parsing OEBPS/page015.xhtml ...
Parsing OEBPS/page019.xhtml ...
Parsing OEBPS/page023.xhtml ...
Parsing OEBPS/page025.xhtml ...
Parsing OEBPS/page027.xhtml ...
Parsing OEBPS/page029.xhtml ...
Parsing OEBPS/page062.xhtml ...
Parsing OEBPS/page031.xhtml ...
Parsing OEBPS/page064.xhtml ...
Parsing OEBPS/page066.xhtml ...
Parsing OEBPS/page009.xhtml ...
Parsing OEBPS/page035.xhtml ...
Parsing OEBPS/page068.xhtml ...
Parsing OEBPS/page037.xhtml ...
Parsing OEBPS/page001.xhtml ...
Parsing OEBPS/page070.xhtml ...
Parsing OEBPS/page039.xhtml ...
Parsing OEBPS/page072.xhtml ...
Parsing OEBPS/page059.xhtml ...
Parsing OEBPS/page041.xhtml ...
Parsing OEBPS/page014.xhtml ...
Parsing OEBPS/page074.xhtml ...
Parsing OEBPS/page043.xhtml ...
Parsing OEBPS/page076.xhtml ...
Parsing OEBPS/page045.xhtml ...
Parsing OEBPS/page078.xhtml ...
Parsing OEBPS/page010.xhtml ...
Parsing OEBPS/page080.xhtml ...
Parsing OEBPS/page049.xhtml ...
Parsing OEBPS/page051.xhtml ...
Parsing OEBPS/cover.xhtml ...
Parsing OEBPS/page084.xhtml ...
Parsing OEBPS/page022.xhtml ...
Parsing OEBPS/page086.xhtml ...
Parsing OEBPS/page052.xhtml ...
Parsing OEBPS/page088.xhtml ...
Parsing OEBPS/page057.xhtml ...
Parsing OEBPS/page090.xhtml ...
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 17.40000pt
Removing fake margins...
Found 98 items of level: div_1
Found 447 items of level: div_3
Found 305 items of level: div_2
div_1  left margin stats: Counter({u'0': 53})
div_1  right margin stats: Counter({u'': 53})
Negative text indent detected at level  div_3, ignoring this level
div_2  left margin stats: Counter({u'': 29})
div_2  right margin stats: Counter({u'': 29})
Cleaning up manifest...
Trimming unused files from manifest...
Trimming u'OEBPS/toc.ncx' from manifest
Trimming u'OEBPS/empty.xhtml' from manifest
Trimming u'OEBPS/nav.xhtml' from manifest
Trimming u'OEBPS/docimages/img_p98.jpg' from manifest
Trimming u'OEBPS/cover.xhtml' from manifest
Creating PDF Output...
Converting input as a text based book...
The cover image has an id != "cover". Renaming to work around bug in Nook Color
Python function terminated unexpectedly
  Size mismatch for glyph id: 0 prev_sz: 84 sz: 68 (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1275, in run
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_output.py", line 188, in convert
  File "site-packages\calibre\ebooks\conversion\plugins\pdf_output.py", line 255, in convert_text
  File "site-packages\calibre\ebooks\pdf\html_writer.py", line 1214, in convert
  File "site-packages\calibre\ebooks\pdf\html_writer.py", line 955, in merge_fonts
  File "site-packages\calibre\ebooks\pdf\html_writer.py", line 911, in merge_font
  File "site-packages\calibre\utils\fonts\sfnt\merge.py", line 31, in merge_truetype_fonts_for_pdf
GlyphSizeMismatch: Size mismatch for glyph id: 0 prev_sz: 84 sz: 68
```
-----
And conversion to AZW3 yields the following
![Annotation 2019-12-18 165711] (https://user-images.githubusercontent.com/59023777/71101746-873ee800-21b7-11ea-8773-d5eefc4abbfc.png)

I've DRM-ed a similar (guitar tab) book purchased from Amazon and that worked fine.

**Comment by ElleKayEm** [comment]
DRM is successfully removed.  For conversion issues, try asking in the calibre forums at MobileRead.  Also, if you've only tried looking at it with the calibre ebook viewer, give it a try with something else.

**Comment by idlelane** [comment]
OK, will do. Thanks.
