### ISSUE TITLE
Fail to convert kindle azw3 to ePUB , DRM  still works on

### ISSUE THREAD

**Issue by joanne-du** [apprenticeharper/DeDRM_tools#960]
calibre 调试日志
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: zh_CN
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 157.825242718 x 157.655172414
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.39] splash screen shown
[1.39] Initializing db...
[1.39] db initialized
[1.39] Constructing main UI...
[2.81] main UI initialized...
[2.81] Hiding splash screen
[35.47] splash screen hidden
[35.47] Started up in 35.47 seconds with 2 books
Worker Launch took: 0.391000032425
Job: 0 转换书籍 第 1 本，共 1 本 (机器学习实战 (图灵程序设计丛书 72)) finished
转换书籍 第 1 本，共 1 本 (机器学习实战 (图灵程序设计丛书 72))
	C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
	Conversion options changed from defaults:
	  output_profile: u'ipad3'
	  read_metadata_from_opf: u'C:\\Users\\joann\\AppData\\Local\\Temp\\calibre_rew5mx\\iprs0h.opf'
	  verbose: 2
	  cover: u'C:\\Users\\joann\\AppData\\Local\\Temp\\calibre_rew5mx\\ztzbps.jpeg'
	Resolved conversion options
	calibre version: 4.6.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\joann\\AppData\\Local\\Temp\\calibre_rew5mx\\ztzbps.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000018D0A967E88>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x0000018D0A96FF88>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\joann\\AppData\\Local\\Temp\\calibre_rew5mx\\iprs0h.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\joann\AppData\Local\Temp\calibre_rew5mx\bopai3.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  机器学习实战 (图灵程序设计丛书 72) (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 208, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: 机器学习实战 (图灵程序设计丛书 72)

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Here's how to get the log that will show what is happening with DRM removal:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by caafurcias42** [comment]
I have the same issue, this is the debug code

calibre Debug log
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0) && KindleUnpack - The Plugin (0, 82, 1)
calibre 4.6 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.16+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 25, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 25, 0) && KFX metadata reader (from KFX Input) (1, 25, 0) && KFX Input (1, 25, 0) && KindleUnpack - The Plugin (0, 82, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 83.2218430034 x 83.1272727273
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.59] db initialized
[0.59] Constructing main UI...
[1.77] main UI initialized...
[1.77] Hiding splash screen
[8.20] splash screen hidden
[8.20] Started up in 8.20 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x8b\x12)\xfd\xa4\xb8@#}\xf5\x8c\x07\x83\x96V \x85\x93\x9d(\x10D\xf0.$(\xf2j\xd0\xedK\x97', 'C:\\Users\\Ricardo\\Desktop\\USMLE Step 2 CS Complex Cases_ Challenging Cases for Advanced Study (USMLE Prep).azw3']
DeDRM v6.6.3: Trying to decrypt USMLE Step 2 CS Complex Cases_ Challenging Cases for Advanced Study (USMLE Prep).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: USMLE Step 2 CS Complex Cases: Challenging Cases for Advanced Study (USMLE Prep)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Ricardo\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\Ricardo\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '440632859' and UserName '5269636172646f'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: USMLE Step 2 CS Complex Cases: Challenging Cases for Advanced Study (USMLE Prep)
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added USMLE Step 2 CS Complex Cases: Challenging Cases for Advanced Study (USMLE Prep) to db in: 0.2
Added 1 books in 1.3 seconds

**Comment by ElleKayEm** [comment]
If that book was downloaded from the website, you need to choose an E-ink Kindle for the device (not a Fire) and enter the Kindle's serial number into the DeDRM plugin's customization.

**Comment by joanne-du** [comment]
thanks a lot! According to your direction, the problem has been resolved. The tool is very important for me, thank you!发自我的华为手机-------- 原始邮件 --------主题：Re: [apprenticeharper/DeDRM_tools] Fail to convert kindle azw3 to ePUB , DRM  still works on (#960)发件人：ElleKayEm 收件人：apprenticeharper/DeDRM_tools 抄送：joanne-du <13723712897@139.com>,Author If that book was downloaded from the website, you need to choose an E-ink Kindle for the device (not a Fire) and enter the Kindle's serial number into the DeDRM plugin's customization.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apprenticeharper/DeDRM_tools/issues/960?email_source=notifications\u0026email_token=ALRDTCWGCIL63DYI43C3DOTQ2DCANA5CNFSM4J5H26B2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHRG3HI#issuecomment-568487325",
"url": "https://github.com/apprenticeharper/DeDRM_tools/issues/960?email_source=notifications\u0026email_token=ALRDTCWGCIL63DYI43C3DOTQ2DCANA5CNFSM4J5H26B2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHRG3HI#issuecomment-568487325",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by bclark1000** [comment]
Which file on the paperwhite do I transfer to calibre?

**Comment by ElleKayEm** [comment]
@bclark1000 
Download the file from the website.  Go to the manage your content and devices page.  Choose "download & transfer via USB" and select your Paperwhite for the device.  Put your Paperwhite's serial number into DeDRM's customization.

**Comment by bclark1000** [comment]
Thank you very much!
