### ISSUE TITLE
AES improper key error 

### ISSUE THREAD

**Issue by smeroney** [apprenticeharper/DeDRM_tools#970]
I am trying to get several epub books off my nook and remove the DeDRM to reformat them for use on my kindle. I paid for each of the books. Please help!

I am using a Mac running 10.14.6 (Mojave). 
I installed Nook for Android on a virtual device following the advice from this article: https://www.aricrenzo.gq/2019-12-13-Liberate-Your-Nook-Ebooks/. 
I was able to download the books to my computer and access the relevant database to extract the hash from it, which I saved as a text file in .b64 format. I uploaded the key file into the DeDRM 6.6.3 plugin in Calibre, then imported the books. It failed to decrypt/remove the DeDRM from the books. 
I tried again by removing the books, double checking that the key was saved, restarting Calibre, and re-importing the books. They were not decrypted/DeDRM'd. 
According to the log, I am using an improper AES key.  
What am I missing? 

I have attached the Terminal output screen containing my hash in case that's helpful.
[Terminal Output cchashdata.txt](https://github.com/apprenticeharper/DeDRM_tools/files/4019906/Terminal.Output.cchashdata.txt)

Here is the log from an attempt to import one book in debug mode:
 calibre Debug log
calibre 4.7  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.7  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[1.22] main UI initialized...
[1.22] Hiding splash screen
objc[95091]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9c3c43d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11f87bf50). One of the two will be used. Which one is undefined.
qt.qpa.window: Window position QRect(-28,453 732x120) outside any known screen, using primary screen
DeDRM v6.6.3: Trying to decrypt 9780062316103_epub.v17.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: “9780062316103_epub.v17.epub” is a secure Barnes & Noble ePub
DeDRM v6.6.3: Trying Encryption key BNkey
Could not decrypt SjFamg.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ignobleepub", line 280, in decryptBook
  File "calibre_plugins.dedrm.ignobleepub", line 211, in __init__
  File "calibre_plugins.dedrm.ignobleepub", line 160, in __init__
IGNOBLEError: AES improper key used

DeDRM v6.6.3: Failed to decrypt with key BNkey after 0.2 seconds
DeDRM v6.6.3: Looking for new NOOK Study Keys after 0.2 seconds
No nook Study log files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 304, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[13.14] splash screen hidden
[13.14] Started up in 13.14 seconds with 1 books
Added Sapiens to db in: 0.1
Added 1 books in 1.2 seconds

**Comment by ElleKayEm** [comment]
Are the books older copies?  Try downloading new ones.

**Comment by smeroney** [comment]
@ElleKayEm I downloaded them on the virtual android device from the nook app I installed on that virtual device at the same time that I downloaded the B&N key from the virtual device. So they’re only a week or so old.

**Comment by ElleKayEm** [comment]
Yeah, the key retrieved at the same time from the same app should work.  So all I can suggest is making sure it's entered correctly.

**Comment by smeroney** [comment]
@ElleKayEm Thanks for your help. I’ll try re-downloading the books just in case. 

One more question... the key I extracted has a “/“ symbol in it. Is that normal? Also, the “=“ at the end was the 28th character. I included the “=“ when saving it, should I have removed it or does the “=“ usually belong in the extracted key?

**Comment by ElleKayEm** [comment]
I don't know about the forward slash.  I don't recall seeing anything but letters, numbers, and the equal sign.  But in my experience, there's always been an equal sign for the 28th character.  Make sure that the .b64 text file contains absolutely nothing else but those 28 characters.  Absolutely plain text.

**Comment by jcd1013** [comment]
@smeroney, I ran into a similar issue today and I think it has to do with how Macs encode the b64 file. First, it wouldn't let me save it as anything other than an txt file and then when I attempted to convert it to a b64 file through Terminal, it added characters. The solution I found was to email myself a copy of the cchash txt file, open it on a windows machine and save it as a .b64 file in Notepad and email it back. Success!
