### ISSUE TITLE
My deDRM is not converting Kindle files

### ISSUE THREAD

**Issue by Luciauv** [apprenticeharper/DeDRM_tools#976]
calibre, version 4.8.0 (darwin, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (Histología. Atlas en color y texto, 7e (Spanish Edition))

Convert book 1 of 1 (Histología. Atlas en color y texto, 7e (Spanish Edition))
Conversion options changed from defaults:
  read_metadata_from_opf: u'/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/C/calibre_4.8.0_tmp_TQJy1N/6FD0YB.opf'
  verbose: 2
  output_profile: u'kindle'
  cover: u'/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/C/calibre_4.8.0_tmp_TQJy1N/P6SJvc.jpeg'
Resolved conversion options
calibre version: 4.8.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/C/calibre_4.8.0_tmp_TQJy1N/P6SJvc.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10b0dd290>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x10b0dd950>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/C/calibre_4.8.0_tmp_TQJy1N/6FD0YB.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/C/calibre_4.8.0_tmp_TQJy1N/f9ud0G.azw3
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly: Histología. Atlas en color y texto, 7e (Spanish Edition)
Traceback (most recent call last):
  File "/private/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/T/AppTranslocation/21940E25-7060-45A5-9770-A371C2DB3A6A/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/private/var/folders/yz/w5j8s5sj4b7_011tb_147j1w0000gn/T/AppTranslocation/21940E25-7060-45A5-9770-A371C2DB3A6A/d/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: Histología. Atlas en color y texto, 7e (Spanish Edition)

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Here's how to get a log:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Luciauv** [comment]
Thanks! I need to convert it to PDF, I have it on my calibre library.

**Comment by ElleKayEm** [comment]
Post a log using the instructions at the link.

**Comment by JeffVandrewJr** [comment]
@ElleKayEm I have the exact same issue. Here is the log: https://pastebin.com/wjugQna9

**Comment by ElleKayEm** [comment]
There's a problem right now with DeDRM, KFX format, and calibre 4.6 and later.  To workaround, either disable KFX downloads in Kindle for PC or go back to calibre 4.5.

**Comment by JeffVandrewJr** [comment]
Worked perfectly. 

Here's how to disable KFX for those that need it: 
https://www.mobileread.com/forums/showthread.php?t=283371
