### ISSUE TITLE
Unable to remove DRM from Kindle books

### ISSUE THREAD

**Issue by freelikethebirds** [apprenticeharper/DeDRM_tools#980]
I have only had this issue with these two books.  I have tried removing the plugin and books and redownloading everything without luck.  I don't know what more I can do so I really appreciate any help offered.  

calibre, version 4.1.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Andrea\Calibre Library\Howard Rosenthal\Encyclopedia of Counseling (945)\Encyclopedia of Counseling - Howard Rosenthal.azw. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages\calibre\utils\ipc\simple_worker.py", line 290, in main
  File "site-packages\calibre\srv\render_book.py", line 668, in render
  File "site-packages\calibre\srv\render_book.py", line 206, in __init__
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: Encyclopedia of Counseling

calibre, version 4.1.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Andrea\Calibre Library\Garry L. Landreth\Play Therapy (944)\Play Therapy - Garry L. Landreth.azw. Click "Show details" for more info.

Traceback (most recent call last):
  File "site-packages\calibre\utils\ipc\simple_worker.py", line 290, in main
  File "site-packages\calibre\srv\render_book.py", line 668, in render
  File "site-packages\calibre\srv\render_book.py", line 206, in __init__
  File "site-packages\calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: Play Therapy

**Comment by ElleKayEm** [comment]
Here's how to get the log which will help us figure out what the problem is:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by freelikethebirds** [comment]
calibre Debug log
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 37, 0) && KFX Output (1, 37, 0)
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 37, 0) && KFX Output (1, 37, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[2.44] main UI initialized...
[2.44] Hiding splash screen
[44.59] splash screen hidden
[44.59] Started up in 44.59 seconds with 803 books
Worker Launch took: 1.19099998474
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xdd\x88a\x89\x12#\x8f\xca\xe1K\xb1\x1e\x953%A\xac\xbdq\x04\xdc^\x15\xd2\xcbd\xe1\n\xaf\xf7\xddq', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B00JWF19W2_EBOK.azw', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B06XFZ2322_EBOK.azw', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B007ZZ1F20_EBOK.azw', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B071NDL5K5_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B06XFZ2322_EBOK.azw
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B007ZZ1F20_EBOK.azw
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B00JWF19W2_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
Gather KFX-ZIP (from KFX Input): File is not KFX format
Gather KFX-ZIP (from KFX Input): File is not KFX format
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B071NDL5K5_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
Added Grim Holiday (Aisling Grimlock Book 6) to db in: 3.3
Added Play Therapy to db in: 5.3
Added Encyclopedia of Counseling to db in: 3.7
Added 3 books in 18.0 seconds
Worker Launch took: 0.444000005722
Worker Launch took: 0.443000078201
Worker Launch took: 0.490000009537

**Comment by ElleKayEm** [comment]
You don't have the DeDRM plugin loaded.

**Comment by freelikethebirds** [comment]
I've tried loading it several times.  What do I need to do to add it?

**Comment by freelikethebirds** [comment]
I tried redownloading the plugin and adding it.  I got the same error

calibre Debug log
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 37, 0) && KFX Output (1, 37, 0)
calibre 4.8  embedded-python: True is64bit: False
Windows-10-10.0.17134-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.17134')
Python 2.7.16+
Windows: ('10', '10.0.17134', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 37, 0) && KFX Output (1, 37, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.861627907 x 100.55257732
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.64] splash screen shown
[0.64] Initializing db...
[0.74] db initialized
[0.74] Constructing main UI...
[3.55] main UI initialized...
[3.55] Hiding splash screen
[5.67] splash screen hidden
[5.67] Started up in 5.67 seconds with 803 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ["!\x06st8W!\xc4'M'\xf2\xf7\xd6\xd1\xf5\xa7\x8e\x89@J%\xcf\x17\x90\x95\xbc3\xc1\xea\x8bP", 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B06XFZ2322_EBOK.azw', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B007ZZ1F20_EBOK.azw', 'C:\\Users\\Andrea\\Documents\\My Kindle Content\\B071NDL5K5_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B06XFZ2322_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B007ZZ1F20_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
Gather KFX-ZIP (from KFX Input) 1.27.0: Importing C:\Users\Andrea\Documents\My Kindle Content\B071NDL5K5_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B06XFZ2322_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Grim Holiday (Aisling Grimlock Book 6)
Got DSN key from database default_key
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
File is encoded with PID tyX6o4H3KY.
Decrypting. Please wait . . . . . . done
Decryption succeeded after 0.4 seconds
DeDRM v6.6.3: Finished after 0.4 seconds
DeDRM v6.6.3: Trying to decrypt B007ZZ1F20_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.6.3: Trying to decrypt B071NDL5K5_EBOK.azw
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting Kindle Format 8 ebook: Play Therapy
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Andrea\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Andrea\AppData\Local\Amazon\Kindle\storage\.kinf2011
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Encyclopedia of Counseling
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: Cannot decode library or rented ebooks.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Andrea\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Andrea\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1388030022' and UserName '416e64726561'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Decrypted key file using IDString '1388030022' and UserName '416e64726561'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Grim Holiday (Aisling Grimlock Book 6) to db in: 1.7
Added Play Therapy to db in: 1.7
Added Encyclopedia of Counseling to db in: 2.1
Added 3 books in 7.2 seconds
Worker Launch took: 0.205999851227
Worker Launch took: 0.262000083923

**Comment by ElleKayEm** [comment]
From the log:

> Failed to decrypt with error: Cannot decode library or rented ebooks.

**Comment by gannon345** [comment]
I'm having the same issue with owned books. Maybe this log will help:

calibre Debug log
calibre 4.8  embedded-python: True is64bit: True
Linux-5.3.0-26-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '5.3.0-26-generic', '#28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0)
calibre 4.8  embedded-python: True is64bit: True
Linux-5.3.0-26-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '5.3.0-26-generic', '#28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019')
Python 2.7.16
Linux: ('debian', 'buster/sid', '')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.13] db initialized
[0.13] Constructing main UI...
Looking for desktop notifier support from: org.freedesktop.Notifications
org.freedesktop.Notifications found in 0.0 seconds
[0.74] main UI initialized...
[0.74] Hiding splash screen
[13.25] splash screen hidden
[13.25] Started up in 13.25 seconds with 718 books
DeDRM v6.6.3: Trying to decrypt A Little Hatred_ 1 (The Age of Madness).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Little Hatred: 1 (The Age of Madness)
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
DeDRM v6.6.3: Running kindlekey.py under Wine
DeDRM v6.6.3: Command line: 'WINEPREFIX="/home/tk" wine python.exe "/home/tk/.config/calibre/plugins/DeDRM/libraryfiles/kindlekey.py" "/home/tk/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: cannot find L"C:\\windows\\system32\\python.exe"
DeDRM v6.6.3: Found and decrypted 0 key files
DeDRM v6.6.3: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added A Little Hatred: 1 (The Age of Madness) to db in: 0.1
Added 1 books in 1.5 seconds
Worker Launch took: 0.0382959842682

**Comment by ElleKayEm** [comment]
@gannon345 
Looks like a book from the website for "download and transfer via USB".  For those, you need to choose an E-ink Kindle (not a Fire) for the device and enter its serial number into the DeDRM plugin customization.

**Comment by gannon345** [comment]
Yeah, @ElleKayEm I'm a dummy. I updated to 4.8 this morning and it looks somehow it wiped out my Kindle serial from the DeDRM plugin. Added it back and now it's working. Sorry for the confusion.

**Comment by ElleKayEm** [comment]
If you have an E-ink Kindle (not a Fire), download the book from the website for "download and transfer via USB" selecting that Kindle for the device.
