### ISSUE TITLE
Digital editions on Macintosh

### ISSUE THREAD

**Issue by rll307** [apprenticeharper/DeDRM_tools#987]
Hi... I tried to remove a DRM in my Calibre 4.9.1 using the latest tools.. The book is under adobre digital editions. Older versions of digital edition do not seem to work in Catalina anymore. That is the log:

```
calibre Debug log
calibre 4.9.1  embedded-python: True is64bit: True
Darwin-19.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.2.0', 'Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 38, 0) && KFX Output (1, 38, 0) && Obok DeDRM (6, 5, 4)
calibre 4.9.1  embedded-python: True is64bit: True
Darwin-19.2.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.2.0', 'Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.2', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 27, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 27, 0) && KFX metadata reader (from KFX Input) (1, 27, 0) && KFX Input (1, 27, 0) && Set KFX metadata (from KFX Output) (1, 38, 0) && KFX Output (1, 38, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 94.0000014117 x 94.0000014117
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.59] main UI initialized...
[1.59] Hiding splash screen
DeDRM v6.6.3: Trying to decrypt [9780203880920] Quantitative Corpus Linguistics with R.pdf
DeDRM v6.6.3: [9780203880920] Quantitative Corpus Linguistics with R.pdf is a PDF ebook
DeDRM v6.6.3: Trying Encryption key default_key
DeDRM v6.6.3: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 427, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2193, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1999, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1484, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1614, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 216, in decrypt
ADEPTError: RSA decryption failed
DeDRM v6.6.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 631, in run
  File "calibre_plugins.dedrm.__init__", line 506, in PDFDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 428, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 343, in get_metadata
  File "site-packages/calibre/ebooks/metadata/pdf.py", line 129, in get_metadata
ValueError: Could not read info dict from PDF
[7.73] splash screen hidden
[7.73] Started up in 7.73 seconds with 2 books
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

```

Could someone help me please?

**Comment by ElleKayEm** [comment]
You have ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

**Comment by rll307** [comment]
Hi..

Yes I do I have chosen to be authorised by the book provider (my University Library). I can open the book normally in digital editions.

**Comment by ElleKayEm** [comment]
These tools are intended for purchased books.

**Comment by rll307** [comment]
OK, sorry
