### ISSUE TITLE
DeDRM

### ISSUE THREAD

**Issue by EeMmSs** [apprenticeharper/DeDRM_tools#990]
hey. i tried DeDRMing an ebook from my kindle to store it in my library in calibre. i didnt get from my kindle app (1.24), but directly from my kindle device, using an usb. i did this for one other book, which i believe wasn't DRMed, because i managed to convert it from epub to mobi. the DRMed book (slaying Brexit Unicorns) i have as a KFX-ZIP in calibre, but i installed jhowell's KFX input plugin succesfully to my calibre. i tried removing the book and going to prefrences/adding books/ auto-merge/overwrite and then adding the book back, like it said on the faq page. i then added the book back and tried to see if it deDRMDed by trying to convert it. i got an error pop up, saying the book cant be converted cuz of DRM

which tool: DeDRM 6.6.3
OS: Windows 10
where the ebook file came from: device
a log of the attempt: 
calibre Debug log
calibre 4.9.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
calibre 4.9.1  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[1.25] main UI initialized...
[1.25] Hiding splash screen
Storage number map:
{(7L, 0L): [(2L, 'C'), (4L, 'D')], (7L, 1L): [(1L, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G0011L0593640HJQ&0: StorageDeviceNumber(type=7L, number=1L, partition_number=0L)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x401 devid=usb\vid_1949&pid_0004&rev_0401 devinst=3)
{u'drive_letters': ['E'],
 u'pnp_id_map': {'E': u'\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g0011l0593640hjq&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 u'readonly_drives': set([]),
 u'sort_map': {'E': (1L, 1L)}}
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 9, count of files in metadata: 9, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 9
DeviceJob: set_books_in_library finished: time= 0.00500011444092
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[9.36] splash screen hidden
[9.36] Started up in 9.36 seconds with 9 books
DeDRM v6.6.3: Trying to decrypt Slaying Brexit Unicorns_ The truth about our decision to leave the EU - Edwin Hayward.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: Slaying Brexit Unicorns_ The truth about our decision to leave the EU - Edwin Hayward
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Fata\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Fata\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2622051389' and UserName '4d264d'
DeDRM v6.6.3: Found 1 new key
Decrypting KFX-ZIP ebook: Slaying Brexit Unicorns_ The truth about our decision to leave the EU - Edwin Hayward
Got DSN key from database default_key_1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.28.0: Packaging C:/Users/Fata/Desktop/Hayward, Edwin/Slaying Brexit Unicorns_ The truth about our decision to leave the EU/Slaying Brexit Unicorns_ The truth about our decision to leave the EU - Edwin Hayward.kfx-zip
Processing container: Slaying Brexit Unicorns_ The truth about our decision to leave the EU_B07Z1FTRQW.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 33, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 87, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 160, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 267, in get_container
KFXDRMError: Book container Slaying Brexit Unicorns_ The truth about our decision to leave the EU_B07Z1FTRQW.kfx has DRM and cannot be converted
Added Slaying Brexit Unicorns: The truth about our decision to leave the EU to db in: 0.1
Added 1 books in 0.8 seconds

thanks...

**Comment by EeMmSs** [comment]
forgot to mention, but i did enter my serial number in the costumize option

**Comment by ElleKayEm** [comment]
You will not be able remove DRM from KFX format books directly off your Kindle.  You can either get the older format from the website for "download & transfer via USB" or use Kindle for PC version 1.24 or earlier.  See this post for details:

https://www.mobileread.com/forums/showthread.php?t=283371
