### ISSUE TITLE
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried

### ISSUE THREAD

**Issue by dolphy22** [apprenticeharper/DeDRM_tools#994]
calibre Debug log
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.493734336 x 109.182089552
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.42] splash screen shown
[0.42] Initializing db...
[0.42] db initialized
[0.42] Constructing main UI...
[1.64] main UI initialized...
[1.64] Hiding splash screen
[5.72] splash screen hidden
[5.72] Started up in 5.72 seconds with 12 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xcd\xde\xfc;\xb6\xe1T-\x90\x07g\xa3\xa8)\xee \xc1\x92\xf8[\x17\xbb\xc2\x15Q\xbd\xc8\x9c\x1d\xd6\xca\x87', 'H:\\Jason\\Downloads\\Creating Games Unreal Engine 4_ Book 2.azw']
DeDRM v6.6.3: Trying to decrypt Creating Games Unreal Engine 4_ Book 2.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Creating Games Unreal Engine 4: Book 2
Got DSN key from database default_key
Found 4 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 4 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\...\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\...\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3611083472' and UserName '646f6e6e69'
DeDRM v6.6.3: Found 1 new key
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Creating Games Unreal Engine 4: Book 2
Got DSN key from database default_key_1
Found 3 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added Creating Games Unreal Engine 4: Book 2 to db in: 0.1
Added 1 books in 0.6 seconds
Worker Launch took: 0.0920000076294
Job: 0 Convert book 1 of 1 (Creating Games Unreal Engine 4: Book 2) finished
Convert book 1 of 1 (Creating Games Unreal Engine 4: Book 2)
	Conversion options changed from defaults:
	  pdf_sans_family: u'MS Shell Dlg 2'
	  read_metadata_from_opf: u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\rox9fn.opf'
	  output_profile: u'generic_eink'
	  pdf_serif_family: u'MS Shell Dlg 2'
	  verbose: 2
	  cover: u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\glx61u.jpeg'
	Resolved conversion options
	calibre version: 4.10.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\glx61u.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002953C065248>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000002953C065E48>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'MS Shell Dlg 2',
	 'pdf_serif_family': u'MS Shell Dlg 2',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\rox9fn.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\...\AppData\Local\Temp\calibre_vdnvpi\pr31ag.azw
	Python function terminated unexpectedly
	  Creating Games Unreal Engine 4: Book 2 (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 39, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 162, in extract_content
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	DRMError: Creating Games Unreal Engine 4: Book 2

Convert book 1 of 1 (Creating Games Unreal Engine 4: Book 2)
Conversion options changed from defaults:
  pdf_sans_family: u'MS Shell Dlg 2'
  read_metadata_from_opf: u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\rox9fn.opf'
  output_profile: u'generic_eink'
  pdf_serif_family: u'MS Shell Dlg 2'
  verbose: 2
  cover: u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\glx61u.jpeg'
Resolved conversion options
calibre version: 4.10.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\glx61u.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002953C065248>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000002953C065E48>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'MS Shell Dlg 2',
 'pdf_serif_family': u'MS Shell Dlg 2',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'C:\\Users\\...\\AppData\\Local\\Temp\\calibre_vdnvpi\\rox9fn.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on C:\Users\...\AppData\Local\Temp\calibre_vdnvpi\pr31ag.azw
Python function terminated unexpectedly
  Creating Games Unreal Engine 4: Book 2 (Error Code: 1)
 Traceback (most recent call last):
  File "site.py", line 114, in main
  File "site.py", line 88, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 39, in convert
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 162, in extract_content
  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
DRMError: Creating Games Unreal Engine 4: Book 2

**Comment by ElleKayEm** [comment]
How did you download the book?  Was it from the website for "download & transfer via USB"?  In that case, you need to choose an E-ink Kindle (not a Fire) and enter its serial number into the DeDRM customization plugin.

**Comment by dolphy22** [comment]
Thanks for the prompt response.  Yes I chose my Fire in download & transfer. I don't have my old Kindle registered anymore. The only other choice is to have it downloaded directly to Kindle for PC and I did that but then there's a KFX error showing up when trying to convert. I have the 1.27 ver. of Kindle for PC so I'll download the earlier version. Thanks again.

**Comment by ElleKayEm** [comment]
There's more info on what works and a link to Kindle for PC 1.24 at this post:

https://www.mobileread.com/forums/showthread.php?t=283371

Be sure to look at the info on keeping K4PC from updating.
