### ISSUE TITLE
DRM Not working

### ISSUE THREAD

**Issue by edwardoblenis** [apprenticeharper/DeDRM_tools#995]
Mac 10.15.3
Kindle 4 Mac 1.27.0 (modified)
Calibre 4.10.1
Book obtained from Amazon.com

calibre Debug log
calibre 4.10.1  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0) && Obok DeDRM (6, 5, 4)
calibre 4.10.1  embedded-python: True is64bit: True
Darwin-19.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.3.0', 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.3', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 28, 0) && DeDRM (6, 6, 3) && Package KFX (from KFX Input) (1, 28, 0) && KFX metadata reader (from KFX Input) (1, 28, 0) && KFX Input (1, 28, 0) && Obok DeDRM (6, 5, 4)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.000001922 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.04] Showing splash screen...
[0.30] splash screen shown
[0.30] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.64] main UI initialized...
[1.64] Hiding splash screen
[1.65] splash screen hidden
[1.65] Started up in 1.65 seconds with 31 books
Gather KFX-ZIP (from KFX Input) 1.28.0: Importing /Users/edwardoblenis/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B003QMLHHO_EBOK/B003QMLHHO_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v6.6.3: Trying to decrypt B003QMLHHO_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: How to Improvise a Full-Length Play: The Art of Spontaneous Theater
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Added How to Improvise a Full-Length Play: The Art of Spontaneous Theater to db in: 0.0
Added 1 books in 1.3 seconds
Worker Launch took: 0.488513946533
Job: 0 Convert book 1 of 1 (How to Improvise a Full-Length Play: The Art of Spontaneous Theater) finished
Convert book 1 of 1 (How to Improvise a Full-Length Play: The Art of Spontaneous Theater)
	Conversion options changed from defaults:
	  read_metadata_from_opf: u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/x21ZIe.opf'
	  output_profile: u'ipad3'
	  verbose: 2
	  cover: u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/qOakMO.jpeg'
	Resolved conversion options
	calibre version: 4.10.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/qOakMO.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f5a7ad0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x10f5b30d0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'paper_size': u'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': u'Courier',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': u'Helvetica',
	 'pdf_serif_family': u'Times',
	 'pdf_standard_font': u'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/x21ZIe.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': u'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 Convert book 1 of 1 (How to Improvise a Full-Length Play: The Art of Spontaneous Theater)
Conversion options changed from defaults:
  read_metadata_from_opf: u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/x21ZIe.opf'
  output_profile: u'ipad3'
  verbose: 2
  cover: u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/qOakMO.jpeg'
Resolved conversion options
calibre version: 4.10.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/qOakMO.jpeg',
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': u'',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f5a7ad0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x10f5b30d0>,
 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
 'paper_size': u'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': u'Courier',
 'pdf_mono_font_size': 16,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': u'Helvetica',
 'pdf_serif_family': u'Times',
 'pdf_standard_font': u'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': u'/var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/x21ZIe.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'uncompressed_pdf': False,
 'unit': u'inch',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
InputFormatPlugin: MOBI Input running
on /var/folders/mb/_sv4m89526s1281gxldqddpm0000gn/C/calibre_4.10.1_tmp_w5oPdb/0PGX1d.azw
Found KF8 MOBI of type u'standalone'
Python function terminated unexpectedly: How to Improvise a Full-Length Play: The Art of Spontaneous Theater
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
DRMError: How to Improvise a Full-Length Play: The Art of Spontaneous Theater

**Comment by ElleKayEm** [comment]
Did you have a working DeDRM setup on this machine previously?

**Comment by ZolaLa9** [comment]
See this post: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

If you had a working DeDRM setup before you upgraded to Catalina, you may be able to get it working by copying over backups of the following files/folders:

-  User > Library > Application Support > **Kindle folder**
- User > Library > Preferences > com.apprenticealf.dedrm > **KindleKey.der**
- User > Library > Preferences > calibre > plugins > **dedrm.json**

**Comment by edwardoblenis** [comment]
Thank you for helping. 

No, there was no DeDRM setup on this machine previously. This is the first time that I have reopened Calibre in a number of years.

**Comment by ElleKayEm** [comment]
ZolaLa9 is much more familiar with the Mac side of things than I am.  But I don't believe there's a way at present to start from scratch on Catalina.

**Comment by ZolaLa9** [comment]
Unfortunately, ElleKayEm is correct. The only way to get Kindle for Mac and DeDRM to work together on Catalina is to have a previous working setup. 

Ideally it should be on the same Mac, but if you have a backup from another Mac, you could give it a try.

**Comment by edwardoblenis** [comment]
Thank you for clarifying. Wow! That's kind of horrible news. So if I want a PDF version of a book and use Catalina the book can't be a Kindle version? Correct? Is there a workaround? Like, would it make more sense to download from a different seller?

**Comment by ElleKayEm** [comment]
There are potential pitfalls with other ebookstores as well.  Barnes & Noble Nook is much more trouble than it's worth for anyone now.  The other major DRM these tools work on is Adobe DRM, and the most reliable program for getting books whose DRM can be removed is a 32-bit program (Adobe Digital Editions 2.0.1).

If you have an E-ink Kindle (that is, not a Fire), you can download a copy of the book from the website which can be DeDRMed.  There are a few books which are not available that way however.

**Comment by ZolaLa9** [comment]
If you have an e-ink Kindle, you can use Method 3 here: https://www.mobileread.com/forums/showthread.php?s=ee1c821250e0fe203d396e7a0fa548b0&t=283371
Some people have purchased cheap used Kindles just for this purpose. 

You could also try a vendor that uses Adobe Digital Editions (ADE), but you will need to use ADE 4.x as earlier versions won't run on Catalina, and ADE 4.x is capable of hardened DRM that cannot be decrypted at this time. I'm not 100% sure, but I think ADE epubs from Kobo and Google Play still work.

Kobo also has a proprietary format (kepub) that use the Obok plugin. I'm not sure if that works with Catalina. 

You can also wait and hope someone will figure out the new Kindle decryption so that K4Mac will work with Catalina without a pre-existing setup. 

Finally, you can set up a virtual machine on your Catalina Mac and install a Mojave VM or Windows VM then install Kindle for Mac/PC on the VM.

**Comment by edwardoblenis** [comment]
Much thanks to the both of you for outlining these options in such great detail. I’ll probably look into buying a cheap E ink Kindle (used to have one and probably tossed it) or wait for the next ingenious decryption creation. THANK YOU!

**Comment by ZolaLa9** [comment]
Any chance your old Kindle is still registered? If so, you don't need the actual device. As long as it's still registered, you can use Method 3. (You can get the serial number from your Amazon account under My Content & Devices.)

**Comment by edwardoblenis** [comment]
I just checked and I must have un-registered it. Thanks for the suggestion though.
