### ISSUE TITLE
DRM is not working

### ISSUE THREAD

**Issue by college8816** [apprenticeharper/DeDRM_tools#996]
Kindle for PC version : 1.28.0

calibre Debug log
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
calibre 4.10.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259 x 93.6245733788
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.45] splash screen shown
[0.45] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[1.84] main UI initialized...
[1.84] Hiding splash screen
[6.22] splash screen hidden
[6.22] Started up in 6.22 seconds with 1 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xb8\xe4\xd9\x14\xad\x055l\x91d\xa3\x89^\xbcA\xb9\xc4\xf0\x85\xee\x19\xe9\x18\xb4\x81alru+aa', 'C:\\Users\\colle\\OneDrive\\Documents\\My Kindle Content\\B083J1HNM3_EBOK\\B083J1HNM3_EBOK.azw']
DeDRM v6.6.3: Trying to decrypt B083J1HNM3_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.42.
Copyright © 2008-2017 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: FLASHスペシャル グラビアBEST 2020年1月25日増刊号 [雑誌]
Got DSN key from database default_key
Found 3 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.6.3: Failed to decrypt with error: No key found in 3 keys tried.
DeDRM v6.6.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\colle\AppData\Local
Found K4PC 2.25+ kinf2018 file: C:\Users\colle\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1653255027' and UserName '636f6c6c65'
DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 624, in run
  File "calibre_plugins.dedrm.__init__", line 574, in KindleMobiDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
C:\Program Files\Calibre2\\app\pylib.zip\dateutil\parser\_parser.py:1177: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Added FLASHスペシャル グラビアBEST 2020年1月25日増刊号 [雑誌] to db in: 0.2
Added 1 books in 1.0 seconds

how can I fix this, thanks

**Comment by ElleKayEm** [comment]
You need to go back to Kindle for PC 1.24 or earlier.  Then either disable KFX format downloads from K4PC.  Or add the KFX Input plugin and go back to calibre 4.5.  Details here:

https://www.mobileread.com/forums/showthread.php?t=283371
