### ISSUE TITLE
python.exe not found

### ISSUE THREAD

**Issue by yananet** [apprenticeharper/DeDRM_tools#999]
Hello

I am using linux, ADE is installed by wine because there is no linux version,
and I am running linux native calibre.
ADE 2.0.1 imported epub is not working for me, following is debug message.
it looks that python.exe is missing, is it necessary to run python over wine?

```
[7.14] Started up in 7.14 seconds with 2 books
0009:err:module:__wine_process_init L"C:\\windows\\system32\\python.exe" not found
DeDRM v6.6.3: Found and decrypted 0 key files
DeDRM v6.6.3: Exception when getting default Adobe Key after 2.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 356, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.6.3: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 406, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
Yes, I believe you need both Python and PyCrypto under Wine.  See the readme in the plugin folder.

**Comment by yananet** [comment]
Dear @ElleKayEm 

Thank you so much for quick reply,
I installed python27 and PyCrypto with wine,
but still not working as following log, may I have any advice?

```
DeDRM v6.6.3: Trying to decrypt _mybookname_.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: _mybookname_.epub is a secure Adobe Adept ePub
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.7 seconds
DeDRM v6.6.3: Running adobekey.py under Wine
DeDRM v6.6.3: Command line: 'WINEPREFIX="/home/yananet" wine python.exe "/home/yananet/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/yananet/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
wine: WINEARCH set to win32 but '/home/yananet' is a 64-bit installation.
DeDRM v6.6.3: Found and decrypted 0 key files
DeDRM v6.6.3: Exception when getting default Adobe Key after 0.8 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 356, in ePubDecrypt
IndexError: list index out of range
DeDRM v6.6.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 172, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 635, in run
  File "calibre_plugins.dedrm.__init__", line 406, in ePubDecrypt
DeDRMError: DeDRM v6.6.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
Maybe this from the log is the issue now?

> WINEARCH set to win32 but '/home/yananet' is a 64-bit installation

I know some people have ended up running the key script manually (adobekey.py) and then imported the retrieved key file into the plugin themselves.

**Comment by yananet** [comment]
@ElleKayEm 

Thanks again for your advice, fortunately, it is working now.
```
DeDRM v6.6.3: Trying to decrypt _mybookname_.epub
DeDRM v6.6.3: Verifying zip archive integrity
DeDRM v6.6.3: _mybookname_.epub is a secure Adobe Adept ePub
DeDRM v6.6.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v6.6.3: Running adobekey.py under Wine
DeDRM v6.6.3: Command line: 'WINEPREFIX="/home/yananet/.local/share/wineprefixes/32bitprofile" wine python.exe "/home/yananet/.config/calibre/plugins/DeDRM/libraryfiles/adobekey.py" "/home/yananet/.config/calibre/plugins/DeDRM/libraryfiles/winekeysdir"'
adobekey.py v6.0
Copyright ? 2009-2013 i?cabbages and Apprentice Alf
Found 1 keys
Saved a key to Z:\home\yananet\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\adobekey_1.der
00ac:fixme:msvcrt:__clean_type_info_names_internal (0x100087f4) stub
00ac:fixme:msvcrt:__clean_type_info_names_internal (0x1d1b7210) stub
00ac:fixme:msvcrt:__clean_type_info_names_internal (0x1e2719d0) stub
DeDRM v6.6.3: Found and decrypted 1 key file
DeDRM v6.6.3: Trying a new default key
DeDRM v6.6.3: Saving a new default key
DeDRM v6.6.3: Saved a new default key after 2.3 seconds
DeDRM v6.6.3: Decrypted with new default key after 2.3 seconds
DeDRM v6.6.3: Finished after 2.3 seconds
```

thanks again for the good tool, and let me share my experience to be helpful for linux user.

- `winetricks python27` just worked for me.
- I made a separated profile for 32bit wine as described in https://forum.winehq.org/viewtopic.php?t=27296
- I created the prefix with `winetricks`, and added `export WINEPREFIX` in `~/.bashrc`.
- However, this broke every existing installations in wine, including ADE, so prepare 32bit prefix correctly at the beginning.
- ADE and DeDrm should be running with the same 32bit wine profile.
- prefix path(`WINEPREFIX`) should be configured in calibre plugin configuration.

That's it, good luck.

**Comment by ElleKayEm** [comment]
Thanks for letting us know what worked!
